### ISSUE TITLE
NullPointerException in OkHttp Dispatcher

### ISSUE THREAD

**Issue by gadagip** [Azure/azure-sdk-for-java#1000]
I keep getting this NullPointerException whenever I use the OkHttpClient. 

```
Exception in thread "OkHttp Dispatcher" java.lang.NullPointerException
    at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:187)
    at com.microsoft.rest.credentials.TokenCredentialsInterceptor.sendRequestWithAuthorization(TokenCredentialsInterceptor.java:49)
    at com.microsoft.rest.credentials.TokenCredentialsInterceptor.intercept(TokenCredentialsInterceptor.java:37)
    at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:187)
    at com.microsoft.rest.credentials.TokenCredentialsInterceptor.sendRequestWithAuthorization(TokenCredentialsInterceptor.java:49)
    at com.microsoft.rest.credentials.TokenCredentialsInterceptor.intercept(TokenCredentialsInterceptor.java:37)
    at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:187)
    at com.microsoft.azure.CustomHeaderInterceptor.intercept(CustomHeaderInterceptor.java:133)
    at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:187)
    at com.microsoft.rest.credentials.TokenCredentialsInterceptor.sendRequestWithAuthorization(TokenCredentialsInterceptor.java:49)
    at com.microsoft.rest.credentials.TokenCredentialsInterceptor.intercept(TokenCredentialsInterceptor.java:37)
    at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:187)
    at com.microsoft.azure.CustomHeaderInterceptor.intercept(CustomHeaderInterceptor.java:133)
    at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:187)
    at com.microsoft.azure.CustomHeaderInterceptor.intercept(CustomHeaderInterceptor.java:133)
    at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:187)
    at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:187)
    at com.microsoft.rest.UserAgentInterceptor.intercept(UserAgentInterceptor.java:58)
    at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:187)
    at com.microsoft.azure.CustomHeaderInterceptor.intercept(CustomHeaderInterceptor.java:133)
    at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:187)
    at com.microsoft.rest.credentials.TokenCredentialsInterceptor.sendRequestWithAuthorization(TokenCredentialsInterceptor.java:49)
    at com.microsoft.rest.credentials.TokenCredentialsInterceptor.intercept(TokenCredentialsInterceptor.java:37)
    at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:187)
    at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:160)
    at okhttp3.RealCall.access$100(RealCall.java:30)
    at okhttp3.RealCall$AsyncCall.execute(RealCall.java:127)
    at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

I don't get it regularly, but I do encounter this issue at least once in 3 runs.

**Comment by gadagip** [comment]
We're seeing this error more frequently now. Is there a recommended approach on using the OkHttpClient and the RetrofitBuilder? Any solutions for the above issue?

**Comment by jianghaolu** [comment]
This looks like a bug in our credentials interceptor.

**Comment by gadagip** [comment]
@jianghaolu Do you have an estimate on when this will be fixed?

**Comment by jianghaolu** [comment]
@gadagip Can you share the code of how you create the client? Including the configurations of headers and authentication. Please remove the auth info, of course.

**Comment by gadagip** [comment]
I'm creating the clients in the most simplest way possible:

`OkHttpClient httpClient = new OkHttpClient();`
`OkHttpClient.Builder clientBuilder = ctx.httpClient.newBuilder();`

And for the RetrofitBuilder:

`Retrofit.Builder builder = new Retrofit.Builder();`
`builder.callbackExecutor(this.executorService); // Creating a java executor service`

And the ComputeClient in this way:
`ComputeManagementClient computeClient = new ComputeManagementClientImpl(BASE_URI, credentials, clientBuilder,
                    builder);`

**Comment by rbtcollins** [comment]
Looks like newRequest might be nil at https://github.com/Azure/azure-sdk-for-java/blob/0f8a40791f58e8418431808eecdd085a4a127b99/runtimes/client-runtime/src/main/java/com/microsoft/rest/credentials/TokenCredentialsInterceptor.java#L49 which would suggest .build() is failing silently?

**Comment by gadagip** [comment]
@jianghaolu Any comments/updates/workarounds based on the way I'm creating clients?

**Comment by jianghaolu** [comment]
Death marching on a release right now, will try to reproduce when that's settled.

**Comment by jianghaolu** [comment]
@rbtcollins It shouldn't because looking at the [source code](https://github.com/square/okhttp/blob/parent-3.1.2/okhttp/src/main/java/okhttp3/Request.java) of `.build()` you see
```java
    public Request build() {
      if (url == null) throw new IllegalStateException("url == null");
      return new Request(this);
    }
```
which will not give us a null object.

So I looked at the top of the stack trace, [RealCall:185-187](https://github.com/square/okhttp/blob/parent-3.1.2/okhttp/src/main/java/okhttp3/RealCall.java#L187) is 
```java
185     Interceptor.Chain chain = new ApplicationInterceptorChain(index + 1, request, forWebSocket);
186     Interceptor interceptor = client.interceptors().get(index);
187     Response interceptedResponse = interceptor.intercept(chain);
```

Looks like an interceptor is null. The index should not be out of bound because otherwise line 186 will throw. Looking at your code 

Did you add any interceptors to http client? I see you have 2 http clients, `httpClient` and `ctx.httpClient`. Do you happen to use them interchangeably and asynchronously?

**Comment by gadagip** [comment]
@jianghaolu I remember debugging through and setting breakpoints in the RealCall class and that is exactly where I saw the interceptor was null. 

I did try adding multiple interceptors, including CustomHeaderInterceptor, while creating the clients. I still got the errors, but for different interceptors this time. I would assume that we shouldn't be on the hook to add the interceptors since we have no idea what interceptors are actually used.

And both httpClient are the same. I just modified the code in my comment to make it easier to understand. I've updated my comment.

**Comment by jianghaolu** [comment]
@gadagip 
By default, we add UserAgentInterceptor, RetryHander, a CustomerHeaderInterceptor including a request ID. You can add interceptors by all means. But it seems weird why your stack trace is so complicated, with even multiple hits of the credentials interceptor.

One thing that might be helpful to try is to inspect the value of `httpClient.interceptors()` right before you make the actual REST call. You might also want to try removing some of the interceptors. 

As a quick test on my side, I created 2 http clients and 2 compute clients, running asynchronously for 50 
calls. But I couldn't reproduce it. 

If you are just using virtual machines, I also recommend you taking a look at [a sample written with 1.0.0-beta2 version of the SDK](https://github.com/Azure-Samples/compute-java-manage-vm/blob/master/src/main/java/com/microsoft/azure/management/compute/samples/ManageVirtualMachine.java). We've simplified the process of creating a client and configuring on it.

**Comment by jianghaolu** [comment]
390 days later - please reopen if it's still an issue.
