### ISSUE TITLE
EventHubClientBuilder parses wrongly HTTP_PROXY URL

### ISSUE THREAD

**Issue by stan-antyufeev-8451** [Azure/azure-sdk-for-java#10096]
**Describe the bug**
If HTTP_PROXY sets to an URL format of  "http://host:port" then the EventHubClientBuilder class  will fail of creation  of an instance of EventHubProducerClient type

***Exception or Stack Trace***
[ERROR] 2020-04-10 16:53:32.353 [main] MessagingNotificationService -  
java.lang.NumberFormatException: For input string: "//proxy-host"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:?]
	at java.lang.Integer.parseInt(Integer.java:638) ~[?:?]
	at java.lang.Integer.parseInt(Integer.java:770) ~[?:?]
	at com.azure.messaging.eventhubs.EventHubClientBuilder.getDefaultProxyConfiguration(EventHubClientBuilder.java:633) ~[azure-messaging-eventhubs-5.0.3.jar:?]
	at com.azure.messaging.eventhubs.EventHubClientBuilder.getConnectionOptions(EventHubClientBuilder.java:596) ~[azure-messaging-eventhubs-5.0.3.jar:?]
	at com.azure.messaging.eventhubs.EventHubClientBuilder.buildConnectionProcessor(EventHubClientBuilder.java:543) ~[azure-messaging-eventhubs-5.0.3.jar:?]
	at com.azure.messaging.eventhubs.EventHubClientBuilder.buildAsyncClient(EventHubClientBuilder.java:480) ~[azure-messaging-eventhubs-5.0.3.jar:?]
	at com.azure.messaging.eventhubs.EventHubClientBuilder.buildClient(EventHubClientBuilder.java:514) ~[azure-messaging-eventhubs-5.0.3.jar:?]
	at com.azure.messaging.eventhubs.EventHubClientBuilder.buildProducerClient(EventHubClientBuilder.java:429) ~[azure-messaging-eventhubs-5.0.3.jar:?]

**To Reproduce**
Set environment variable HTTP_PROXY to any proxy URL in format of "http://hostname:port" and create EventHubProducerClient instance.

***Code Snippet***
None, use code snippets example from documentation

**Expected behavior**
Azure Event Hub client library should correctly parse HTTP_PROXY and HTTPS_PROXY URLs.

**Setup (please complete the following information):**
 - OS: MAC OS
 - IDE : Intellij
 - Version of the Library: 5.0.3

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X ] Bug Description Added
- [ X] Repro Steps Added
- [ X] Setup information Added

**Comment by stan-antyufeev-8451** [comment]
It could be not enough to parse http://host:port.
More common format is http_proxy=http://username:password@host:port
For instance, take a look at here https://ubuntuforums.org/showthread.php?t=1575

**Comment by srnagar** [comment]
@stan-antyufeev-8451 PR #10145 supports `http://host:port`, `http://username:password@host:port` and  `host:port` formats. This should cover all formats.

See test cases in the PR - https://github.com/Azure/azure-sdk-for-java/pull/10145/files#diff-997a4c57d09541c8856db5cce05b3637R114
