### ISSUE TITLE
EventHubClient creation failed java.io.IOException: Too many open files

### ISSUE THREAD

**Issue by uttamu2812** [Azure/azure-sdk-for-java#10107]
While running a sevent hub consumer I am getting below error in my console.

941893 [[drsrefdata-uw-eh-r|phoenix|PhoenixApplication-d3ae3a4b-502b-4742-9a7a-7d8aaaa1deb1]-1-13] ERROR com.microsoft.azure.eventprocessorhost.PartitionPump - host PhoenixApplication-d3ae3a4b-502b-4742-9a7a-7d8aaaa1deb1: 0: EventHubClient creation failed
java.io.IOException: Too many open files
	at sun.nio.ch.IOUtil.makePipe(Native Method)
	at sun.nio.ch.PipeImpl.<init>(PipeImpl.java:42)
	at sun.nio.ch.SelectorProviderImpl.openPipe(SelectorProviderImpl.java:50)
	at java.nio.channels.Pipe.open(Pipe.java:155)
	at org.apache.qpid.proton.reactor.impl.IOImpl.pipe(IOImpl.java:34)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.<init>(ReactorImpl.java:101)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.<init>(ReactorImpl.java:112)
	at org.apache.qpid.proton.reactor.Reactor$Factory.create(Reactor.java:57)
	at org.apache.qpid.proton.Proton.reactor(Proton.java:118)
	at com.microsoft.azure.eventhubs.impl.ProtonUtil.reactor(ProtonUtil.java:24)
	at com.microsoft.azure.eventhubs.impl.MessagingFactory$ReactorFactory.create(MessagingFactory.java:414)
	at com.microsoft.azure.eventhubs.impl.MessagingFactory.startReactor(MessagingFactory.java:158)
	at com.microsoft.azure.eventhubs.impl.MessagingFactory.createConnection(MessagingFactory.java:154)
	at com.microsoft.azure.eventhubs.impl.MessagingFactory.createFromConnectionString(MessagingFactory.java:102)
	at com.microsoft.azure.eventhubs.impl.MessagingFactory.createFromConnectionString(MessagingFactory.java:88)
	at com.microsoft.azure.eventhubs.impl.EventHubClientImpl.create(EventHubClientImpl.java:53)
	at com.microsoft.azure.eventhubs.EventHubClient.create(EventHubClient.java:85)
	at com.microsoft.azure.eventprocessorhost.PartitionPump.openClients(PartitionPump.java:178)
	at com.microsoft.azure.eventprocessorhost.PartitionPump.lambda$openClientsRetryWrapper$9(PartitionPump.java:130)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
941939 [[drsrefdata-uw-eh-r|phoenix|PhoenixApplication-d3ae3a4b-502b-4742-9a7a-7d8aaaa1deb1]-1-5] INFO com.microsoft.azure.eventprocessorhost.PartitionPump - host PhoenixApplication-d3ae3a4b-502b-4742-9a7a-7d8aaaa1deb1: 0: Opening EH client
941958 [[drsrefdata-uw-eh-r|phoenix|PhoenixApplication-d3ae3a4b-502b-4742-9a7a-7d8aaaa1deb1]-1-3] ERROR com.microsoft.azure.eventprocessorhost.PartitionPump - host PhoenixApplication-d3ae3a4b-502b-4742-9a7a-7d8aaaa1deb1: 1: PartitionReceiver creation failed
java.util.concurrent.CompletionException: com.microsoft.azure.eventhubs.EventHubException: The supplied offset '8589943808' is invalid. The last offset in the system is '17752' TrackingId:7d8022ad-5998-4aa7-9b96-67957d550b92_B18, SystemTracker:drs-uw-ehns-r:eventhub:drsrefdata-uw-eh-r~16383, Timestamp:2020-03-30T20:59:44 Reference:20564b39-baba-4b77-9977-509fbdf6f106, TrackingId:bd901fc6-2eec-486a-a234-6ca6022709c4_B18, SystemTracker:drs-uw-ehns-r:eventhub:drsrefdata-uw-eh-r~16383|phoenix, Timestamp:2020-03-30T20:59:44 TrackingId:593d58d5fa114055902c735bdde3a5f7_G14, SystemTracker:gateway5, Timestamp:2020-03-30T20:59:44, errorContext[NS: drs-uw-ehns-r.servicebus.windows.net, PATH: drsrefdata-uw-eh-r/ConsumerGroups/phoenix/Partitions/1, REFERENCE_ID: 5144f8_5f7_G14_1585601984249]
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:647)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at com.microsoft.azure.eventhubs.impl.ExceptionUtil.completeExceptionally(ExceptionUtil.java:98)
	at com.microsoft.azure.eventhubs.impl.MessageReceiver.cancelOpen(MessageReceiver.java:357)
	at com.microsoft.azure.eventhubs.impl.MessageReceiver.onOpenComplete(MessageReceiver.java:347)
	at com.microsoft.azure.eventhubs.impl.MessageReceiver.onError(MessageReceiver.java:414)
	at com.microsoft.azure.eventhubs.impl.MessageReceiver.onClose(MessageReceiver.java:736)
	at com.microsoft.azure.eventhubs.impl.BaseLinkHandler.processOnClose(BaseLinkHandler.java:74)
	at com.microsoft.azure.eventhubs.impl.BaseLinkHandler.handleRemoteLinkClosed(BaseLinkHandler.java:113)
	at com.microsoft.azure.eventhubs.impl.BaseLinkHandler.onLinkRemoteClose(BaseLinkHandler.java:48)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:176)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291)
	at com.microsoft.azure.eventhubs.impl.MessagingFactory$RunReactor.run(MessagingFactory.java:507)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.microsoft.azure.eventhubs.EventHubException: The supplied offset '8589943808' is invalid. The last offset in the system is '17752' TrackingId:7d8022ad-5998-4aa7-9b96-67957d550b92_B18, SystemTracker:drs-uw-ehns-r:eventhub:drsrefdata-uw-eh-r~16383, Timestamp:2020-03-30T20:59:44 Reference:20564b39-baba-4b77-9977-509fbdf6f106, TrackingId:bd901fc6-2eec-486a-a234-6ca6022709c4_B18, SystemTracker:drs-uw-ehns-r:eventhub:drsrefdata-uw-eh-r~16383|phoenix, Timestamp:2020-03-30T20:59:44 TrackingId:593d58d5fa114055902c735bdde3a5f7_G14, SystemTracker:gateway5, Timestamp:2020-03-30T20:59:44, errorContext[NS: drs-uw-ehns-r.servicebus.windows.net, PATH: drsrefdata-uw-eh-r/ConsumerGroups/phoenix/Partitions/1, REFERENCE_ID: 5144f8_5f7_G14_1585601984249]
	at com.microsoft.azure.eventhubs.impl.ExceptionUtil.toException(ExceptionUtil.java:43)
	at com.microsoft.azure.eventhubs.impl.MessageReceiver.onClose(MessageReceiver.java:735)
	... 15 more
Caused by: com.microsoft.azure.eventhubs.impl.AmqpException: The supplied offset '8589943808' is invalid. The last offset in the system is '17752' TrackingId:7d8022ad-5998-4aa7-9b96-67957d550b92_B18, SystemTracker:drs-uw-ehns-r:eventhub:drsrefdata-uw-eh-r~16383, Timestamp:2020-03-30T20:59:44 Reference:20564b39-baba-4b77-9977-509fbdf6f106, TrackingId:bd901fc6-2eec-486a-a234-6ca6022709c4_B18, SystemTracker:drs-uw-ehns-r:eventhub:drsrefdata-uw-eh-r~16383|phoenix, Timestamp:2020-03-30T20:59:44 TrackingId:593d58d5fa114055902c735bdde3a5f7_G14, SystemTracker:gateway5, Timestamp:2020-03-30T20:59:44
	... 17 more
942003 [[drsrefdata-uw-eh-r|phoenix|PhoenixApplication-d3ae3a4b-502b-4742-9a7a-7d8aaaa1deb1]-1-7] ERROR com.microsoft.azure.eventprocessorhost.PartitionPump - host PhoenixApplication-d3ae3a4b-502b-4742-9a7a-7d8aaaa1deb1: 3: EventHubClient creation failed
java.io.IOException: Too many open files
	at sun.nio.ch.IOUtil.makePipe(Native Method)
	at sun.nio.ch.PipeImpl.<init>(PipeImpl.java:42)
	at sun.nio.ch.SelectorProviderImpl.openPipe(SelectorProviderImpl.java:50)
	at java.nio.channels.Pipe.open(Pipe.java:155)
	at org.apache.qpid.proton.reactor.impl.IOImpl.pipe(IOImpl.java:34)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.<init>(ReactorImpl.java:101)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.<init>(ReactorImpl.java:112)
	at org.apache.qpid.proton.reactor.Reactor$Factory.create(Reactor.java:57)
	at org.apache.qpid.proton.Proton.reactor(Proton.java:118)
	at com.microsoft.azure.eventhubs.impl.ProtonUtil.reactor(ProtonUtil.java:24)
	at com.microsoft.azure.eventhubs.impl.MessagingFactory$ReactorFactory.create(MessagingFactory.java:414)
	at com.microsoft.azure.eventhubs.impl.MessagingFactory.startReactor(MessagingFactory.java:158)
	at com.microsoft.azure.eventhubs.impl.MessagingFactory.createConnection(MessagingFactory.java:154)
	at com.microsoft.azure.eventhubs.impl.MessagingFactory.createFromConnectionString(MessagingFactory.java:102)
	at com.microsoft.azure.eventhubs.impl.MessagingFactory.createFromConnectionString(MessagingFactory.java:88)
	at com.microsoft.azure.eventhubs.impl.EventHubClientImpl.create(EventHubClientImpl.java:53)
	at com.microsoft.azure.eventhubs.EventHubClient.create(EventHubClient.java:85)
	at com.microsoft.azure.eventprocessorhost.PartitionPump.openClients(PartitionPump.java:178)
	at com.microsoft.azure.eventprocessorhost.PartitionPump.lambda$openClientsRetryWrapper$9(PartitionPump.java:130)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
942039 [[drsrefdata-uw-eh-r|phoenix|PhoenixApplication-d3ae3a4b-502b-4742-9a7a-7d8aaaa1deb1]-1-3] INFO com.microsoft.azure.eventprocessorhost.PartitionPump - host PhoenixApplication-d3ae3a4b-502b-4742-9a7a-7d8aaaa1deb1: 2: Opening EH client
942048 [[drsrefdata-uw-eh-r|phoenix|PhoenixApplication-d3ae3a4b-502b-4742-9a7a-7d8aaaa1deb1]-1-15] WARN com.microsoft.azure.eventprocessorhost.PartitionPump - host PhoenixApplication-d3ae3a4b-502b-4742-9a7a-7d8aaaa1deb1: 2: Failure creating client or receiver, retrying
java.util.concurrent.CompletionException: com.microsoft.azure.eventhubs.EventHubException: The supplied offset '8589942784' is invalid. The last offset in the system is '4294968320' TrackingId:3650f196-8abd-4028-b947-a6d22d31d1b2_B29, SystemTracker:drs-uw-ehns-r:eventhub:drsrefdata-uw-eh-r~24575, Timestamp:2020-03-30T20:59:44 Reference:c477eb08-a6b3-4586-9905-df59512b9863, TrackingId:04969834-af9a-4620-9579-f1699e526ffa_B29, SystemTracker:drs-uw-ehns-r:eventhub:drsrefdata-uw-eh-r~24575|phoenix, Timestamp:2020-03-30T20:59:44 TrackingId:6252ae08e6284fca907f96daa2f3d6fd_G36, SystemTracker:gateway5, Timestamp:2020-03-30T20:59:44, errorContext[NS: drs-uw-ehns-r.servicebus.windows.net, PATH: drsrefdata-uw-eh-r/ConsumerGroups/phoenix/Partitions/2, REFERENCE_ID: 292563_6fd_G36_1585601984056]
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:647)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at com.microsoft.azure.eventhubs.impl.ExceptionUtil.completeExceptionally(ExceptionUtil.java:98)
	at com.microsoft.azure.eventhubs.impl.MessageReceiver.cancelOpen(MessageReceiver.java:357)
	at com.microsoft.azure.eventhubs.impl.MessageReceiver.onOpenComplete(MessageReceiver.java:347)
	at com.microsoft.azure.eventhubs.impl.MessageReceiver.onError(MessageReceiver.java:414)
	at com.microsoft.azure.eventhubs.impl.MessageReceiver.onClose(MessageReceiver.java:736)
	at com.microsoft.azure.eventhubs.impl.BaseLinkHandler.processOnClose(BaseLinkHandler.java:74)
	at com.microsoft.azure.eventhubs.impl.BaseLinkHandler.handleRemoteLinkClosed(BaseLinkHandler.java:113)
	at com.microsoft.azure.eventhubs.impl.BaseLinkHandler.onLinkRemoteClose(BaseLinkHandler.java:48)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:176)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291)
	at com.microsoft.azure.eventhubs.impl.MessagingFactory$RunReactor.run(MessagingFactory.java:507)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.microsoft.azure.eventhubs.EventHubException: The supplied offset '8589942784' is invalid. The last offset in the system is '4294968320' TrackingId:3650f196-8abd-4028-b947-a6d22d31d1b2_B29, SystemTracker:drs-uw-ehns-r:eventhub:drsrefdata-uw-eh-r~24575, Timestamp:2020-03-30T20:59:44 Reference:c477eb08-a6b3-4586-9905-df59512b9863, TrackingId:04969834-af9a-4620-9579-f1699e526ffa_B29, SystemTracker:drs-uw-ehns-r:eventhub:drsrefdata-uw-eh-r~24575|phoenix, Timestamp:2020-03-30T20:59:44 TrackingId:6252ae08e6284fca907f96daa2f3d6fd_G36, SystemTracker:gateway5, Timestamp:2020-03-30T20:59:44, errorContext[NS: drs-uw-ehns-r.servicebus.windows.net, PATH: drsrefdata-uw-eh-r/ConsumerGroups/phoenix/Partitions/2, REFERENCE_ID: 292563_6fd_G36_1585601984056]
	at com.microsoft.azure.eventhubs.impl.ExceptionUtil.toException(ExceptionUtil.java:43)
	at com.microsoft.azure.eventhubs.impl.MessageReceiver.onClose(MessageReceiver.java:735)
	... 15 more
Caused by: com.microsoft.azure.eventhubs.impl.AmqpException: The supplied offset '8589942784' is invalid. The last offset in the system is '4294968320' TrackingId:3650f196-8abd-4028-b947-a6d22d31d1b2_B29, SystemTracker:drs-uw-ehns-r:eventhub:drsrefdata-uw-eh-r~24575, Timestamp:2020-03-30T20:59:44 Reference:c477eb08-a6b3-4586-9905-df59512b9863, TrackingId:04969834-af9a-4620-9579-f1699e526ffa_B29, SystemTracker:drs-uw-ehns-r:eventhub:drsrefdata-uw-eh-r~24575|phoenix, Timestamp:2020-03-30T20:59:44 TrackingId:6252ae08e6284fca907f96daa2f3d6fd_G36, SystemTracker:gateway5, Timestamp:2020-03-30T20:59:44
	... 17 more
942049 [[drsrefdata-uw-eh-r|phoenix|PhoenixApplication-d3ae3a4b-502b-4742-9a7a-7d8aaaa1deb1]-1-15] INFO com.microsoft.azure.eventhubs.impl.SessionHandler - onSessionRemoteClose entityName[drsrefdata-uw-eh-r/ConsumerGroups/phoenix/Partitions/2], condition[Error{condition=com.microsoft:argument-error, description='The supplied offset '8589942784' is invalid. The last offset in the system is '4294968320' TrackingId:3650f196-8abd-4028-b947-a6d22d31d1b2_B29, SystemTracker:drs-uw-ehns-r:eventhub:drsrefdata-uw-eh-r~24575, Timestamp:2020-03-30T20:59:44 Reference:c477eb08-a6b3-4586-9905-df59512b9863, TrackingId:04969834-af9a-4620-9579-f1699e526ffa_B29, SystemTracker:drs-uw-ehns-r:eventhub:drsrefdata-uw-eh-r~24575|phoenix, Timestamp:2020-03-30T20:59:44 TrackingId:6252ae08e6284fca907f96daa2f3d6fd_G36, SystemTracker:gateway5, Timestamp:2020-03-30T20:59:44', info=null}]
942060 [[drsrefdata-uw-eh-r|phoenix|PhoenixApplication-d3ae3a4b-502b-4742-9a7a-7d8aaaa1deb1]-1-3] INFO com.microsoft.azure.eventprocessorhost.PartitionPump - host PhoenixApplication-d3ae3a4b-502b-4742-9a7a-7d8aaaa1deb1: 1: Opening EH client
942197 [[drsrefdata-uw-eh-r|phoenix|PhoenixApplication-d3ae3a4b-502b-4742-9a7a-7d8aaaa1deb1]-1-6] INFO com.microsoft.azure.eventhubs.impl.BaseLinkHandler - onLinkRemoteClose linkName[cbs:sender], errorCondition[amqp:connection:forced], errorDescription[The connection was inactive for more than the allowed 300000 milliseconds and is closed by container 'LinkTracker'. TrackingId:fea9836c9f2f43948b2afee779d1bf84_G26, SystemTracker:gateway5, Timestamp:2020-03-30T20:59:45]
942197 [[drsrefdata-uw-eh-r|phoenix|PhoenixApplication-d3ae3a4b-502b-4742-9a7a-7d8aaaa1deb1]-1-6] INFO com.microsoft.azure.eventhubs.impl.BaseLinkHandler - processOnClose linkName[cbs:sender], errorCondition[amqp:connection:forced], errorDescription[The connection was inactive for more than the allowed 300000 milliseconds and is closed by container 'LinkTracker'. TrackingId:fea9836c9f2f43948b2afee779d1bf84_G26, SystemTracker:gateway5, Timestamp:2020-03-30T20:59:45]
942197 [[drsrefdata-uw-eh-r|phoenix|PhoenixApplication-d3ae3a4b-502b-4742-9a7a-7d8aaaa1deb1]-1-6] INFO com.microsoft.azure.eventhubs.impl.BaseLinkHandler - closeSession for linkName[cbs:sender], errorCondition[amqp:connection:forced], errorDescription[The connection was inactive for more than the allowed 300000 milliseconds and is closed by container 'LinkTracker'. TrackingId:fea9836c9f2f43948b2afee779d1bf84_G26, SystemTracker:gateway5, Timestamp:2020-03-30T20:59:45]
942197 [[drsrefdata-uw-eh-r|phoenix|PhoenixApplication-d3ae3a4b-502b-4742-9a7a-7d8aaaa1deb1]-1-6] INFO com.microsoft.azure.eventhubs.impl.BaseLinkHandler - onLinkRemoteClose linkName[cbs:receiver], errorCondition[amqp:connection:forced], errorDescription[The connection was inactive for more than the allowed 300000 milliseconds and is closed by container 'LinkTracker'. TrackingId:fea9836c9f2f43948b2afee779d1bf84_G26, SystemTracker:gateway5, Timestamp:2020-03-30T20:59:45]
942197 [[drsrefdata-uw-eh-r|phoenix|PhoenixApplication-d3ae3a4b-502b-4742-9a7a-7d8aaaa1deb1]-1-6] INFO com.microsoft.azure.eventhubs.impl.BaseLinkHandler - processOnClose linkName[cbs:receiver], errorCondition[amqp:connection:forced], errorDescription[The connection was inactive for more than the allowed 300000 milliseconds and is closed by container 'LinkTracker'. TrackingId:fea9836c9f2f43948b2afee779d1bf84_G26, SystemTracker:gateway5, Timestamp:2020-03-30T20:59:45]
942197 [[drsrefdata-uw-eh-r|phoenix|PhoenixApplication-d3ae3a4b-502b-4742-9a7a-7d8aaaa1deb1]-1-6] INFO com.microsoft.azure.eventhubs.impl.SessionHandler - onSessionRemoteClose entityName[cbs-session], condition[Error{condition=null, description='null', info=null}]
942197 [[drsrefdata-uw-eh-r|phoenix|PhoenixApplication-d3ae3a4b-502b-4742-9a7a-7d8aaaa1deb1]-1-6] INFO com.microsoft.azure.eventhubs.impl.ConnectionHandler - onConnectionRemoteClose: hostname[drs-uw-ehns-r.servicebus.windows.net:5671], errorCondition[amqp:connection:forced], errorDescription[The connection was inactive for more than the allowed 300000 milliseconds and is closed by container 'LinkTracker'. TrackingId:fea9836c9f2f43948b2afee779d1bf84_G26, SystemTracker:gateway5, Timestamp:2020-03-30T20:59:45]
942197 [[drsrefdata-uw-eh-r|phoenix|PhoenixApplication-d3ae3a4b-502b-4742-9a7a-7d8aaaa1deb1]-1-6] WARN com.microsoft.azure.eventhubs.impl.MessagingFactory - onConnectionError: messagingFactory[MessagingFactory23e318], hostname[drs-uw-ehns-r.servicebus.windows.net], error[The connection was inactive for more than the allowed 300000 milliseconds and is closed by container 'LinkTracker'. TrackingId:fea9836c9f2f43948b2afee779d1bf84_G26, SystemTracker:gateway5, Timestamp:2020-03-30T20:59:45]
942197 [[drsrefdata-uw-eh-r|phoenix|PhoenixApplication-d3ae3a4b-502b-4742-9a7a-7d8aaaa1deb1]-1-6] WARN com.microsoft.azure.eventhubs.impl.MessagingFactory - onConnectionError: messagingFactory[MessagingFactory23e318], hostname[drs-uw-ehns-r.servicebus.windows.net], closing current connection
942197 [[drsrefdata-uw-eh-r|phoenix|PhoenixApplication-d3ae3a4b-502b-4742-9a7a-7d8aaaa1deb1]-1-6] INFO com.microsoft.azure.eventhubs.impl.BaseLinkHandler - onLinkLocalClose linkName[cbs:sender], errorCondition[amqp:connection:forced], errorDescription[The connection was inactive for more than the allowed 300000 milliseconds and is closed by container 'LinkTracker'. TrackingId:fea9836c9f2f43948b2afee779d1bf84_G26, SystemTracker:gateway5, Timestamp:2020-03-30T20:59:45] 
.......... 

**Setup (please complete the following information if applicable):**
 - OS: [linux]
 - IDE : [e.g. IntelliJ]
 - Version of the Library used
   -- java 1.7
--- azure-eventhubs 2.2.0
-- azure-eventhubs-eph 2.4.0
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Query Added
- [ ] Setup information Added

**Comment by joshfree** [comment]
Thanks for reporting this issue in the previous release of EventHubs/EPH @uttamu2812.  @conniey could you please follow up?

**Comment by ughorai** [comment]
Is this issue there in old version?and fixed in new version 3.0.0?

**Comment by conniey** [comment]
@JamesBirdsall Have you seen this issue before? I haven't seen this IO exception.

**Comment by JamesBirdsall** [comment]
The exception is happening when it's trying to open the pipe that the client uses to poke Proton when it needs to process sends. I suspect that "too many open files" is Java trying to translate a Windows error that is actually "too many handles" or maybe it has hit the limit on the number of pipes.

**Comment by conniey** [comment]
@uttamu2812 Have you tried to increase the limits in your shell? (via `ulimit`).

**Comment by srnagar** [comment]
@uttamu2812 have you had a chance to try what @conniey has suggested?
