### ISSUE TITLE
[QUERY]Error occurs when downloading  files with Japanese filename from Azure Files with Azure SDK for Java on Eclipse

### ISSUE THREAD

**Issue by azumi123** [Azure/azure-sdk-for-java#10216]
Title: Error occurs when downloading  files with Japanese filename from Azure Files with Azure SDK for Java on Eclipse

---Wanted answer---
Does SDK support downloading files with Japanese filename? 
Is there any workaround ?
Is any plans to fix this(support download a file with Japanese file name )?

---replication procedure---
1. Upload Japanese language file to Azure Files.
file name: 日本語.txt

2. Configure Eclipse. Install Java and Azure SDK.
azure-storage-file-share 12.2.0
azure-storage-common 12.4.0
azure-core 1.2.0
azure-core-http-netty 1.3.0

3.Execute code(Error occur by fileClient.openInputStream();)

/**
*
*/
package TestAzureFiles;
import com.azure.core.http.HttpClient;
import com.azure.storage.file.share.ShareClient;
import com.azure.storage.file.share.ShareFileClient;
import com.azure.storage.file.share.ShareServiceClient;
import com.azure.storage.file.share.ShareServiceClientBuilder;
/**
* @author ...
*
*/
public class TestModule001 {

    public static final String CONNECTION_STRING =
            "DefaultEndpointsProtocol=https;AccountName=<ACCOUNT_NAME>;AccountKey=<ACCOUNT_KEY>;EndpointSuffix=core.windows.net";
   /**
     * @param args
     */
    public static void main(String[] args)  {
        HttpClient httpClient1 = HttpClient.createDefault();
        ShareServiceClient serviceClient = new ShareServiceClientBuilder().connectionString(CONNECTION_STRING)
        .httpClient(httpClient1).buildClient();
        String id = "120031026002037";
        // Get File Sharing Client
        ShareClient shareClient = serviceClient.getShareClient(id);
        // What I tried
        String filepath = "日本語.txt";
        ShareFileClient fileClient = shareClient.getFileClient((String) filepath);
        fileClient.getFilePath();
        fileClient.openInputStream();
    }
}

---logs of error(java.lang.Exception)---
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 26085 out of bounds for length 256
    at com.azure.core.http.rest.PercentEscaper.escape(PercentEscaper.java:93)
    at com.azure.core.http.rest.SwaggerMethodParser.applySubstitutions(SwaggerMethodParser.java:566)
    at com.azure.core.http.rest.SwaggerMethodParser.setPath(SwaggerMethodParser.java:274)
    at com.azure.core.http.rest.RestProxy.createHttpRequest(RestProxy.java:218)
    at com.azure.core.http.rest.RestProxy.invoke(RestProxy.java:131)
    at com.azure.storage.file.share.implementation.$Proxy7.getProperties(Unknown Source)
    at com.azure.storage.file.share.implementation.FilesImpl.getPropertiesWithRestResponseAsync(FilesImpl.java:317)
    at com.azure.storage.file.share.ShareFileAsyncClient.getPropertiesWithResponse(ShareFileAsyncClient.java:880)
    at com.azure.storage.file.share.ShareFileAsyncClient.lambda$getPropertiesWithResponse$22(ShareFileAsyncClient.java:870)
    at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:118)
    at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:121)
    at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2274)
    at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:162)
    at reactor.core.publisher.MonoFlatMap$FlatMapMain.onSubscribe(MonoFlatMap.java:103)
    at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:90)
    at reactor.core.publisher.MonoCurrentContext.subscribe(MonoCurrentContext.java:35)
    at reactor.core.publisher.Mono.subscribe(Mono.java:4210)
    at reactor.core.publisher.Mono.block(Mono.java:1665)
    at com.azure.storage.file.share.StorageFileInputStream.<init>(StorageFileInputStream.java:49)
    at com.azure.storage.file.share.ShareFileClient.openInputStream(ShareFileClient.java:111)
    at com.azure.storage.file.share.ShareFileClient.openInputStream(ShareFileClient.java:99)
    at TestAzureFiles.TestModule001.main(TestModule001.java:42)
    Suppressed: java.lang.Exception: #block terminated with an error
        at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
        at reactor.core.publisher.Mono.block(Mono.java:1666)
        ... 4 more

---cause of error---
Error occurs when SDK for Java creates download path. Perhaps an error in percent encoding.
The conversion character is defined as 256 characters.
In other cases such as Japanese, will occur "ArrayIndexOutOfBoundsException".

Problem in the Azure-SDK-for-Java processing of " original.charAt(i)".
Please confirm in the source code line 81.

URL: https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/core/azure-core/src/main/java/com/azure/core/http/rest/PercentEscaper.java#L81
(line 81: char c = original.charAt(i);)

**Comment by rickle-msft** [comment]
@alzimmermsft Can you take a look at this as the source of the exception seems to be in core? 

Note: I've edited your issue to redact the account name and key that you shared. These should be kept as secrets to prevent anyone from illegitimately gaining access to your account. As you have shared the key publicly, I recommend rotating it to ensure security.

**Comment by alzimmermsft** [comment]
Thank you for submitting this issue @azumi123, do you mind also telling the charset being used in the JVM instance?

**Comment by azumi123** [comment]
Hi, Allen
I confirmed utf8 and utf16, But It was the same event.

**Comment by alzimmermsft** [comment]
This issue should be resolved with the changes made in #10273
