### ISSUE TITLE
[ERROR:Pooled connection observed an error;]

### ISSUE THREAD

**Issue by xiaowufan** [Azure/azure-sdk-for-java#10347]
**Query/Question**
I find that every time I download a file with BlockBlobClient, an error log will appear in the background later. This error **does not affect** my application,it work well, but I think it will have some impact on operation team.
I used the sample code [BasicExample.java](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/storage/azure-storage-blob/src/samples/java/com/azure/storage/blob/BasicExample.java)

**My Question is Is this a problem, and how to avoid it.**.

**Log:**
`2020-04-19 11:03:51,280 ERROR [reactor-http-nio-4] (Loggers.java:300) (reactor.util.Loggers$Slf4JLogger:error) - [id: *********, L:/*********** - R:***********.blob.core.windows.net/***********:443] Pooled connection observed an error; [   ]
java.io.IOException: 既存の接続はリモート ホストに強制的に切断されました。
	at java.base/sun.nio.ch.SocketDispatcher.read0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:358)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:648)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:583)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at java.base/java.lang.Thread.run(Thread.java:834)`

***Why is this not a Bug or a feature Request?***
A clear explanation of why is this not a bug or a feature request?

**Setup (please complete the following information if applicable):**
 - OS: [e.g. Windows10]
 - IDE : [e.g. STS]
 - JDK: zulu 11
 - azure-storage-blob V12
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [Yes] Query Added
- [Yes] Setup information Added

**Comment by anuchandy** [comment]
Decoding the error message: 

Pooled connection observed an error; [ ] java.io.IOException: Existing connection forced to the remote host

One possibility is service sending a RST packet, there is no clean way for us to know if a connection is in this state (where the service has sent an RST packet) without actually trying to read or write data into the connection/channel. An attempt to write|read on such connection result in "An existing connection was forcibly closed by the remote host". There could be various reason service decide to close (i.e. sending RST), such as service timeout set on connections.

I believe such exceptions are retried by creating a new connection or picking a healthy connection to the same host from the pool. Due to the retry underneath, this retryable may not surface to the application, which explain why your application expected behavior is not impacted.

\\\cc @rickle-msft

**Comment by xiaowufan** [comment]
@anuchandy 

Thanks for your comments.
I tried to set the max-retires to 0, But the same error happened.

**Comment by xiaowufan** [comment]
Maybe  this problem due to the version of netty.
azure-blob-storage sdk(v12) has no problem. 
my springboot version is 2.1.1. and the nested netty's version is too old. when I change to 2.2.x, it never occurs any more.
@anuchandy thank you again. 
I will close this issue..
