### ISSUE TITLE
[BUG]Azure.Security.KeyVault.Secret is wrong

### ISSUE THREAD

**Issue by liuhegui** [Azure/azure-sdk-for-java#10457]
When I tried Azure.Security.KeyVault.Secret sample code (How to get, set,update and delete Secrets Synchronously),  always gives me the error message like this:
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.NoClassDefFoundError: com/azure/core/implementation/RestProxy
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.NoClassDefFoundError: com/azure/core/implementation/RestProxy
	at com.azure.security.keyvault.secrets.SecretAsyncClient.<init>(SecretAsyncClient.java:78)
	at com.azure.security.keyvault.secrets.SecretClientBuilder.buildAsyncClient(SecretClientBuilder.java:154)
	at com.azure.security.keyvault.secrets.SecretClientBuilder.buildClient(SecretClientBuilder.java:97)
	at Helloworold.main(AzureKeyVaultHandler.java:38)
Caused by: java.lang.ClassNotFoundException: com.azure.core.implementation.RestProxy
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 4 more

**Comment by joshfree** [comment]
Thanks for reporting this issue with the KeyVault sample @liuhegui.  @vcolin7 can you please take a look?

**Comment by vcolin7** [comment]
Hi @liuhegui, I ran the samples found [here](https://docs.microsoft.com/en-us/java/api/overview/azure/security-keyvault-secrets-readme?view=azure-java-stable#create-a-secret) in a standalone project and could not reproduce this issue. Could you kindly share your project's POM and the result of running `mvn clean package && mvn dependency:tree`? I suspect there could be a dependency conflict somewhere in your project.

**Comment by liuhegui** [comment]
HI @vcolin7 , it is too long time, I can't reproduce issue too. So I will close the ticket.

**Comment by vcolin7** [comment]
Thank you for reporting this and sorry for taking a while to get back to you. Have a great week!
