### ISSUE TITLE
[QUERY] Deadletter Queue for Service Bus Queue with Session

### ISSUE THREAD

**Issue by rushabh196** [Azure/azure-sdk-for-java#10662]
**Query/Question**
Provided that there exists a session based Service Bus Queue, is it possible to implement a listener for the Deadletter Queue using session?

Attempting to write a listener for the Deadletter Queue by implementing the ISessionHandler interface, I run into this exception:

INFO  com.microsoft.azure.servicebus.primitives.CoreMessageReceiver - Completeing all pending receive and updateState operation on the receiver to 'testQueueWithSession/$deadletterqueue'
INFO  com.microsoft.azure.servicebus.MessageAndSessionPump - Accepting a session from entity 'testQueueWithSession/$deadletterqueue' failed.
java.lang.UnsupportedOperationException: Cannot create a MessageSession for a sub-queue. Reference:f9e680d5-97ec-418e-930a-4aee0fc985d9, TrackingId:3a0ba34a-68aa-4482-8306-ac16bbc0ae29_B16, SystemTracker:soochi-service:Queue:testQueueWithSession|$deadletterqueue, Timestamp:2020-04-28T04:56:44 TrackingId:23d4619a092945ff90aecea495c48280_G6, SystemTracker:gateway5, Timestamp:2020-04-28T04:56:44
                at com.microsoft.azure.servicebus.primitives.ExceptionUtil.toException(ExceptionUtil.java:47) ~[azure-servicebus-3.1.4.jar:?]
                at com.microsoft.azure.servicebus.primitives.CoreMessageReceiver.onClose(CoreMessageReceiver.java:815) ~[azure-servicebus-3.1.4.jar:?]
                at com.microsoft.azure.servicebus.amqp.BaseLinkHandler.processOnClose(BaseLinkHandler.java:66) ~[azure-servicebus-3.1.4.jar:?]
                at com.microsoft.azure.servicebus.amqp.BaseLinkHandler.onLinkRemoteClose(BaseLinkHandler.java:42) ~[azure-servicebus-3.1.4.jar:?]
                at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:176) ~[proton-j-0.33.2.jar:?]
                at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108) ~[proton-j-0.33.2.jar:?]
                at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324) ~[proton-j-0.33.2.jar:?]
                at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291) ~[proton-j-0.33.2.jar:?]
                at com.microsoft.azure.servicebus.primitives.MessagingFactory$RunReactor.run(MessagingFactory.java:500) ~[azure-servicebus-3.1.4.jar:?]
                at java.lang.Thread.run(Thread.java:834) [?:?]

The error message kind of explains that it failed to create the MessageSession for the sub-queue (Deadletter Queue in this case).

Also, things seem to work when the listener for Deadletter Queue implements the IMessageHandler interface (without sessions).

Is there a way the use Deadletter Queue with sessions?

**Setup (please complete the following information if applicable):**
 - OS: iOS
 - IDE : Eclipse
 - Version of the Library used
	com.microsoft.azure
	azure-servicebus
	3.1.4
 

 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Query Added
- [X] Setup information Added

**Comment by nemakam** [comment]
@rushabh196, We do not support this feature right now. We do not have any near term plans to support this either.
Can we know what is the use-case you are looking at?

I'll close this for now. If we decide to make changes to the plan, we will reopen this.

**Comment by fabianmeyer** [comment]
@nemakam, not the original poster but I've stumpled upon a similar requirement when using Azure Service Bus' session-based request-reply-pattern. I have a command queue that is consumed by an Azure function (the command processor). In some cases, the commanding client has to block and wait for the result of a command. In order to implement some kind of timeout for the command, my idea was to define a TTL when sending the command, spawn a session receiver for the reply queue and a session receiver for the dead letter queue of the command queue and "race" the two receive tasks. This way, I can be sure that after the TTL either the command processor took the command from the queue and started processing (so that I will evantually get a result) or the command was dead lettered and will never be processed (it timed out).

**Comment by Archomeda** [comment]
@nemakam Also not the original poster, and it's 2 years later now, but I've found that it's currently impossible to iterate over the active session states (because the .NET library doesn't support it), and if the messages are deadlettered and those sessions are not cleaned up because of that, it's also impossible to clear the session state in the deadletter queue.

Is there any way to clean stale sessions in a non-workaround way without resorting to sending new, specific-cleaning queue messages based on scheduledTime or from the DLQ?
