### ISSUE TITLE
[BUG] TimeoutException: Cannot make a working EventHubConsumerClient

### ISSUE THREAD

**Issue by ShahmirAhmed** [Azure/azure-sdk-for-java#10915]
**Describe the bug**
1) I have successfully built an `EventHubProducerClient` using the connection string from my Event Hubs instance. I was able to see in the Azure portal that my logs came in (seeing the correct number of Incoming Messages). 

2) Now I am trying to consume back the log that I sent. I have followed the documentation to build out an `EventHubConsumerClient` and I am trying to first check my partition ids to check that the consumer is built out properly. When I try to print my partition ids, I get a timeout exception.

Note: I've also failed to receive events and it errors out. Which leads me to believe all operations with the consumer are timing out.

***Exception or Stack Trace***
```
Exception in thread "main" reactor.core.Exceptions$ReactiveException: java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 60000ms in 'source(MonoWhen)' (and no fallback has been configured)
	at reactor.core.Exceptions.propagate(Exceptions.java:336)
	at reactor.core.publisher.BlockingIterable$SubscriberIterator.hasNext(BlockingIterable.java:162)
	at com.eis.kraken.EventHubProducerMain.main(EventHubProducerMain.java:84)
Caused by: java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 60000ms in 'source(MonoWhen)' (and no fallback has been configured)
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.handleTimeout(FluxTimeout.java:288)
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.doTimeout(FluxTimeout.java:273)
	at reactor.core.publisher.FluxTimeout$TimeoutTimeoutSubscriber.onNext(FluxTimeout.java:390)
	at reactor.core.publisher.StrictSubscriber.onNext(StrictSubscriber.java:89)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:73)
	at reactor.core.publisher.MonoDelay$MonoDelayRunnable.run(MonoDelay.java:117)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**To Reproduce**
1. Create an Event Hub name space.
2. Create an Event Hubs instance.
3. Create policy on the instance with Manage permissions and get the connection string
4. Build an EventHubConsumerClient with the connection string and default consumer group.
5. Get all the partition ids from the EventHubConsumerClient.
6. Run a foreach to print out your partition ids

***Code Snippet***
```
      Logger logger = LoggerFactory.getLogger(EventHubProducerMain.class);
      String connectionString = System.getenv("CONNECTION_STRING");

      EventHubConsumerClient consumer = new EventHubClientBuilder()
              .connectionString(connectionString)
              .transportType(AmqpTransportType.AMQP_WEB_SOCKETS)
              .consumerGroup(EventHubClientBuilder.DEFAULT_CONSUMER_GROUP_NAME)
              .buildConsumerClient();

      IterableStream<String> partitionIds = consumer.getPartitionIds();
      for (String partitionId : partitionIds) {
        logger.info(partitionId);
      }
```

**Expected behavior**
Expected to print out the 2 partition ids that are created in my instance

**Setup (please complete the following information):**
 - OS: macOSX
 - IDE : IntelliJ 2020 Professional
 - Version of the Library used : 5.0.2

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by srnagar** [comment]
@ShahmirAhmed Thank you for reporting this issue. Is your host behind a proxy? If so, you might have to configure proxy when building your client.

**Comment by ShahmirAhmed** [comment]
So I'm working on a corporate network and after talking to our cloud team, we realized that our network policy blocks port 9093, which is used by this sdk to receive logs from Event Hubs. Is there any way to override that?

**Comment by srnagar** [comment]
@ShahmirAhmed The ports cannot be overridden from the SDK. You may, however, set up a proxy server that whitelists [Azure Event Hubs ports](https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-faq#what-ports-do-i-need-to-open-on-the-firewall) and connect via proxy.

**Comment by ShahmirAhmed** [comment]
Hi @srnagar yes setting up the required transportType on my end has helped me. Thank you so much for your help. My issue has been resolved

**Comment by srnagar** [comment]
@ShahmirAhmed Great to know! Thanks for the update.
