### ISSUE TITLE
[QUERY] AmqpEventHubConsumer.IdleTimerExpired in Java EventHubConsumer SDK

### ISSUE THREAD

**Issue by shubhambhattar** [Azure/azure-sdk-for-java#11233]
**Query/Question**
I am getting ERRORS of the type 
```
The link 'G17:0000000:15_b00c67_1589608397028' is force detached. Code: ServerError. Details: AmqpEventHubConsumer.IdleTimerExpired: Idle timeout: 00:30:00.
```

- This ERROR is not thrown back to the application. Does this mean I am not supposed to handle it?
Along with this, a few other ERRORS are also popping up. 

```
05:32:17 [single-1] ERROR c.a.c.a.i.ReactorReceiver - connectionId[MF_2e3c67_1589612249281] linkName[15_b00c67_1589608397028] entityPath[click/ConsumerGroups/eventhub-sdk-test/Partitions/15] Error occurred in link.
The link 'G17:6442759:15_b00c67_1589608397028' is force detached. Code: ServerError. Details: AmqpEventHubConsumer.IdleTimerExpired: Idle timeout: 00:30:00. TrackingId:af954c3400018d94002b871e5ec0c559_G17_B5, SystemTracker:some-namespace:eventhub:click~16383|eventhub-sdk-test, Timestamp:2020-05-17T05:32:17, errorContext[NAMESPACE: some-namespace.servicebus.windows.net, PATH: click/ConsumerGroups/eventhub-sdk-test/Partitions/15, REFERENCE_ID: 15_b00c67_1589608397028, LINK_CREDIT: 0]
05:48:39 [single-1] WARN  c.a.c.a.i.h.ConnectionHandler - onTransportError hostname[some-namespace.servicebus.windows.net:5671], connectionId[MF_2d05f1_1589608387087], error[Connection timed out]
05:48:39 [single-1] ERROR c.a.c.a.i.ReactorConnection - connectionId[MF_2d05f1_1589608387087] Error occurred in connection handler.
Connection timed out, errorContext[NAMESPACE: some-namespace.servicebus.windows.net]
05:49:39 [single-1] WARN  c.a.c.a.i.h.ConnectionHandler - onTransportError hostname[some-namespace.servicebus.windows.net:5671], connectionId[MF_3e0104_1589608297028], error[Connection timed out]
05:49:39 [single-1] ERROR c.a.c.a.i.ReactorConnection - connectionId[MF_3e0104_1589608297028] Error occurred in connection handler.
Connection timed out, errorContext[NAMESPACE: some-namespace.servicebus.windows.net]
05:49:41 [parallel-1] ERROR c.a.m.e.PartitionBasedLoadBalancer - There are no partitions in Event Hub click
05:49:41 [parallel-1] ERROR a.e.h.Error - There are no partitions in Event Hub click
05:49:51 [parallel-1] ERROR c.a.m.e.PartitionBasedLoadBalancer - There are no partitions in Event Hub click
05:49:51 [parallel-1] ERROR a.e.h.Error - There are no partitions in Event Hub click
05:50:01 [parallel-1] ERROR c.a.m.e.PartitionBasedLoadBalancer - There are no partitions in Event Hub click
05:50:01 [parallel-1] ERROR a.e.h.Error - There are no partitions in Event Hub click
05:50:11 [parallel-1] ERROR c.a.m.e.PartitionBasedLoadBalancer - There are no partitions in Event Hub click
05:50:11 [parallel-1] ERROR a.e.h.Error - There are no partitions in Event Hub click
05:50:21 [parallel-1] ERROR c.a.m.e.PartitionBasedLoadBalancer - There are no partitions in Event Hub click
05:50:21 [parallel-1] ERROR a.e.h.Error - There are no partitions in Event Hub click
05:50:31 [parallel-1] ERROR c.a.m.e.PartitionBasedLoadBalancer - There are no partitions in Event Hub click
05:50:31 [parallel-1] ERROR a.e.h.Error - There are no partitions in Event Hub click
05:50:39 [single-1] WARN  c.a.c.a.i.h.ConnectionHandler - onTransportError hostname[some-namespace.servicebus.windows.net:5671], connectionId[MF_5b49bb_1589694519655], error[org.apache.qpid.proton.engine.TransportException: connection aborted]
05:50:39 [single-1] ERROR c.a.c.a.i.ReactorConnection - connectionId[MF_5b49bb_1589694519655] Error occurred in connection handler.
errorCondition[amqp:connection:framing-error]. description[org.apache.qpid.proton.engine.TransportException: connection aborted], errorContext[NAMESPACE: some-namespace.servicebus.windows.net]
05:50:41 [parallel-1] ERROR c.a.m.e.PartitionBasedLoadBalancer - There are no partitions in Event Hub click
05:50:41 [parallel-1] ERROR a.e.h.Error - There are no partitions in Event Hub click
05:50:51 [parallel-1] ERROR c.a.m.e.PartitionBasedLoadBalancer - There are no partitions in Event Hub click
05:50:51 [parallel-1] ERROR a.e.h.Error - There are no partitions in Event Hub click
05:51:01 [parallel-1] ERROR c.a.m.e.PartitionBasedLoadBalancer - There are no partitions in Event Hub click
05:51:01 [parallel-1] ERROR a.e.h.Error - There are no partitions in Event Hub click
05:51:11 [parallel-1] ERROR c.a.m.e.PartitionBasedLoadBalancer - There are no partitions in Event Hub click
05:51:11 [parallel-1] ERROR a.e.h.Error - There are no partitions in Event Hub click
05:51:21 [parallel-1] ERROR c.a.m.e.PartitionBasedLoadBalancer - There are no partitions in Event Hub click
05:51:21 [parallel-1] ERROR a.e.h.Error - There are no partitions in Event Hub click
05:51:31 [parallel-1] ERROR c.a.m.e.PartitionBasedLoadBalancer - There are no partitions in Event Hub click
05:51:31 [parallel-1] ERROR a.e.h.Error - There are no partitions in Event Hub click
05:51:39 [single-1] WARN  c.a.c.a.i.h.ConnectionHandler - onTransportError hostname[some-namespace.servicebus.windows.net:5671], connectionId[MF_84186c_1589694579804], error[org.apache.qpid.proton.engine.TransportException: connection aborted]
05:51:39 [single-1] ERROR c.a.c.a.i.ReactorConnection - connectionId[MF_84186c_1589694579804] Error occurred in connection handler.
errorCondition[amqp:connection:framing-error]. description[org.apache.qpid.proton.engine.TransportException: connection aborted], errorContext[NAMESPACE: some-namespace.servicebus.windows.net]
05:51:41 [parallel-1] ERROR c.a.m.e.PartitionBasedLoadBalancer - There are no partitions in Event Hub click
05:51:41 [parallel-1] ERROR a.e.h.Error - There are no partitions in Event Hub click
05:51:51 [parallel-1] ERROR c.a.m.e.PartitionBasedLoadBalancer - There are no partitions in Event Hub click
05:51:51 [parallel-1] ERROR a.e.h.Error - There are no partitions in Event Hub click
05:52:01 [parallel-1] ERROR c.a.m.e.PartitionBasedLoadBalancer - There are no partitions in Event Hub click
05:52:01 [parallel-1] ERROR a.e.h.Error - There are no partitions in Event Hub click
05:52:11 [parallel-1] ERROR c.a.m.e.PartitionBasedLoadBalancer - There are no partitions in Event Hub click
05:52:11 [parallel-1] ERROR a.e.h.Error - There are no partitions in Event Hub click
05:52:21 [parallel-1] ERROR c.a.m.e.PartitionBasedLoadBalancer - There are no partitions in Event Hub click
05:52:21 [parallel-1] ERROR a.e.h.Error - There are no partitions in Event Hub click
05:52:31 [parallel-1] ERROR c.a.m.e.PartitionBasedLoadBalancer - There are no partitions in Event Hub click
05:52:31 [parallel-1] ERROR a.e.h.Error - There are no partitions in Event Hub click
05:53:50 [parallel-1] WARN  c.a.c.a.i.RetryUtil - Retry attempts are exhausted. Current: 3. Max: 4.
05:53:50 [elastic-20] ERROR r.c.p.Operators - Operator called default onErrorDropped
java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 60000ms in 'takeUntil' (and no fallback has been configured)
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.handleTimeout(FluxTimeout.java:289)
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.doTimeout(FluxTimeout.java:274)
	at reactor.core.publisher.FluxTimeout$TimeoutTimeoutSubscriber.onNext(FluxTimeout.java:396)
	at reactor.core.publisher.StrictSubscriber.onNext(StrictSubscriber.java:89)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:73)
	at reactor.core.publisher.MonoDelay$MonoDelayRunnable.run(MonoDelay.java:117)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
05:53:50 [elastic-20] ERROR r.c.s.Schedulers - Scheduler worker in group main failed with an uncaught exception
java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 60000ms in 'takeUntil' (and no fallback has been configured)
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.handleTimeout(FluxTimeout.java:289)
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.doTimeout(FluxTimeout.java:274)
	at reactor.core.publisher.FluxTimeout$TimeoutTimeoutSubscriber.onNext(FluxTimeout.java:396)
	at reactor.core.publisher.StrictSubscriber.onNext(StrictSubscriber.java:89)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:73)
	at reactor.core.publisher.MonoDelay$MonoDelayRunnable.run(MonoDelay.java:117)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

```

I am unable to reproduce it on my own and the issue seems to be happening intermittently with no pattern (or atleast I haven't been able to recognize it).

What am I supposed to do for these ERRORs? 

***Why is this not a Bug or a feature Request?***
Couldn't reproduce it on my own.

**Setup (please complete the following information if applicable):**
 - Version of the Library used: `5.1.0`
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by srnagar** [comment]
@shubhambhattar any errors that are retry-able will not be surfaced to the calling application unless all retry attempts have failed. For errors that are not retry-able, the calling application will be notified. 

In this case, it looks like the receiver has been idle with no events to consume for more than 30 minutes. So, the service closes the connection and the processor client retries to reconnect based on the configured retry policy. The application will be notified through the error handler if all retry attempts fail.

**Comment by shubhambhattar** [comment]
@srnagar The errors that I posted above actually persisted for hours. Also, new messages were available for consumption because the EventHub from which I consumer is always receiving new data. This is why I brought this up. 

Retry wasn't happening for hours and the application was only throwing these logs for hours.

**Comment by shubhambhattar** [comment]
@srnagar Any help here would be appreciated. I am getting these randomly and not able to reproduce it exactly. And just to be sure, it doesn't resolve by itself even if left for hours.

**Comment by shubhambhattar** [comment]
@srnagar Got this issue again:

```
08:05:43 [single-1] ERROR c.a.c.a.i.ReactorReceiver - connectionId[MF_e21315_1590471144782] linkName[16_af18a7_1590471144782] entityPath[eventhub/ConsumerGroups/eventhub-sdk-test/Partitions/16] Error occurred in link.
The link 'G25:17658338:16_af18a7_1590471144782' is force detached. Code: ServerError. Details: AmqpEventHubConsumer.IdleTimerExpired: Idle timeout: 00:30:00. TrackingId:99593e2b00018d950056060a5eccc6cf_G25_B14, SystemTracker:some-namespace:eventhub:eventhub~17407|eventhub-sdk-test, Timestamp:2020-05-26T08:05:43, errorContext[NAMESPACE: some-namespace.servicebus.windows.net, PATH: eventhub/ConsumerGroups/eventhub-sdk-test/Partitions/16, REFERENCE_ID: 16_af18a7_1590471144782, LINK_CREDIT: 0]
```

And here's the Grafana screenshot for 3 hrs which shows that the application isn't able to recover from this:

[https://imgur.com/a/8gGUadW](https://imgur.com/a/8gGUadW)

There are 2 consumers running and one of the consumer is only consuming from Partition 16. After the initial spike, the consumption stopped and never started again. This ERROR was also not propagated to the calling application and as we can see, recovery is also not happening.

Consumer- RPS is a graph which represents number of messages consumer from a partition per second.
Lag is a gauge, hence whatever last value was fetched is being reported throughout.

- Till now, I don't have a code to reproduce the issue but the issue is definitely there. 
- It also says that it's a `ServerError` and the link was `force detached`.

**Comment by srnagar** [comment]
@shubhambhattar The error seems to happen when the network connection is lost temporarily and the receiver fails to recover even after the connection is restored. I have a PR open to fix this issue.
https://github.com/Azure/azure-sdk-for-java/pull/11432

**Comment by shubhambhattar** [comment]
Hi @srnagar, any idea when this PR will me merged (and subsequently new version of the SDK will be released)? I am seeing another new type of Error but I feel it is a consequence of this issue:
```
04:00:32 [pool-2-thread-1] ERROR a.e.h.Error - errorCondition[amqp:connection:framing-error]. description[org.apache.qpid.proton.engine.TransportException: connection aborted], errorContext[NAMESPACE: some-namespace.servicebus.windows.net]
04:00:42 [pool-2-thread-1] WARN  c.a.m.e.PartitionBasedLoadBalancer - Load balancing for event processor failed - errorCondition[amqp:connection:framing-error]. description[org.apache.qpid.proton.engine.TransportException: connection aborted], errorContext[NAMESPACE: some-namespace.servicebus.windows.net]
errorCondition[amqp:connection:framing-error]. description[org.apache.qpid.proton.engine.TransportException: connection aborted], errorContext[NAMESPACE: some-namespace.servicebus.windows.net]
```

**Comment by srnagar** [comment]
@shubhambhattar The new version is expected to be released next week. I will update this issue when it's released.

**Comment by srnagar** [comment]
@shubhambhattar The new version is released to Maven central. 
https://mvnrepository.com/artifact/com.azure/azure-messaging-eventhubs/5.1.1
https://mvnrepository.com/artifact/com.azure/azure-messaging-eventhubs-checkpointstore-blob/1.1.1

**Comment by shubhambhattar** [comment]
@srnagar I think the issue is still present. I am consuming from an EventHub (with 32 partitions) using latest `5.1.1` version of SDK and consumption from some partitions are still stopping after a certain time: [https://imgur.com/a/Fio3vs9](https://imgur.com/a/Fio3vs9)

**Comment by shubhambhattar** [comment]
@srnagar The issue is still present. I am consuming from an EventHub (with 32 partitions) using latest `5.1.2` version of SDK and consumption from some partitions are still stopping after a certain time: 

For all partitions: [https://imgur.com/a/ZU51zU1](https://imgur.com/a/ZU51zU1)

For partition 6 from which nothing is being consumed: [https://imgur.com/a/k4wjOjj](https://imgur.com/a/k4wjOjj)

Errors in log:

```
2020-08-14 20:12:12,474 [parallel-1] WARN  c.a.c.a.i.RetryUtil - Retry attempts are exhausted. Current: 4. Max: 3.
2020-08-14 20:12:12,475 [boundedElastic-19] WARN  c.a.m.e.PartitionPumpManager - Error receiving events from partition 6
Did not observe any item or terminal signal within 60000ms in 'takeUntil' (and no fallback has been configured)
2020-08-14 20:12:12,475 [boundedElastic-19] ERROR c.e.e.i.ProcessError - Error while consuming from EventHub partition 6
java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 60000ms in 'takeUntil' (and no fallback has been configured)
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.handleTimeout(FluxTimeout.java:288)
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.doTimeout(FluxTimeout.java:273)
	at reactor.core.publisher.FluxTimeout$TimeoutTimeoutSubscriber.onNext(FluxTimeout.java:395)
	at reactor.core.publisher.StrictSubscriber.onNext(StrictSubscriber.java:89)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:73)
	at reactor.core.publisher.MonoDelay$MonoDelayRunnable.run(MonoDelay.java:117)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2020-08-14 20:45:11,771 [single-1] WARN  c.a.c.a.i.h.ConnectionHandler - onTransportError hostname[some-namespace.servicebus.windows.net:5671], connectionId[MF_cdeb28_1597415285877], error[Connection timed out]
2020-08-14 20:45:11,772 [single-1] ERROR c.a.c.a.i.ReactorConnection - connectionId[MF_cdeb28_1597415285877] Error occurred in connection handler.
Connection timed out, errorContext[NAMESPACE: some-namespace.servicebus.windows.net]
2020-08-14 20:46:11,773 [single-1] WARN  c.a.m.e.i.EventHubConnectionProcessor - Retry #1. Transient error occurred. Retrying after 4511 ms.
Connection timed out, errorContext[NAMESPACE: some-namespace.servicebus.windows.net]
2020-08-14 20:46:11,807 [single-1] WARN  c.a.c.a.i.h.ConnectionHandler - onTransportError hostname[some-namespace.servicebus.windows.net:5671], connectionId[MF_a397ff_1597430316894], error[Connection timed out]
2020-08-14 20:46:11,807 [single-1] ERROR c.a.c.a.i.ReactorConnection - connectionId[MF_a397ff_1597430316894] Error occurred in connection handler.
Connection timed out, errorContext[NAMESPACE: some-namespace.servicebus.windows.net]
2020-08-14 20:46:17,301 [parallel-1] WARN  c.a.m.e.PartitionBasedLoadBalancer - Load balancing for event processor failed - Did not observe any item or terminal signal within 60000ms in 'flatMapMany' (and no fallback has been configured)
Did not observe any item or terminal signal within 60000ms in 'flatMapMany' (and no fallback has been configured)
2020-08-14 20:46:17,301 [parallel-1] ERROR c.e.e.i.ProcessError - Error while consuming from EventHub partition NONE
java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 60000ms in 'flatMapMany' (and no fallback has been configured)
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.handleTimeout(FluxTimeout.java:288)
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.doTimeout(FluxTimeout.java:273)
	at reactor.core.publisher.FluxTimeout$TimeoutTimeoutSubscriber.onNext(FluxTimeout.java:395)
	at reactor.core.publisher.StrictSubscriber.onNext(StrictSubscriber.java:89)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:73)
	at reactor.core.publisher.MonoDelay$MonoDelayRunnable.run(MonoDelay.java:117)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2020-08-14 20:47:11,808 [single-1] WARN  c.a.m.e.i.EventHubConnectionProcessor - Retry #1. Transient error occurred. Retrying after 4511 ms.
Connection timed out, errorContext[NAMESPACE: some-namespace.servicebus.windows.net]
2020-08-14 20:47:11,870 [single-1] WARN  c.a.c.a.i.h.ConnectionHandler - onTransportError hostname[some-namespace.servicebus.windows.net:5671], connectionId[MF_4cbaca_1597437911772], error[org.apache.qpid.proton.engine.TransportException: connection aborted]
2020-08-14 20:47:11,870 [single-1] ERROR c.a.c.a.i.ReactorConnection - connectionId[MF_4cbaca_1597437911772] Error occurred in connection handler.
org.apache.qpid.proton.engine.TransportException: connection aborted, errorContext[NAMESPACE: some-namespace.servicebus.windows.net]
2020-08-14 20:47:17,302 [parallel-1] WARN  c.a.m.e.PartitionBasedLoadBalancer - Load balancing for event processor failed - Did not observe any item or terminal signal within 60000ms in 'flatMapMany' (and no fallback has been configured)
Did not observe any item or terminal signal within 60000ms in 'flatMapMany' (and no fallback has been configured)
2020-08-14 20:47:17,302 [parallel-1] ERROR c.e.e.i.ProcessError - Error while consuming from EventHub partition NONE
java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 60000ms in 'flatMapMany' (and no fallback has been configured)
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.handleTimeout(FluxTimeout.java:288)
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.doTimeout(FluxTimeout.java:273)
	at reactor.core.publisher.FluxTimeout$TimeoutTimeoutSubscriber.onNext(FluxTimeout.java:395)
	at reactor.core.publisher.StrictSubscriber.onNext(StrictSubscriber.java:89)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:73)
	at reactor.core.publisher.MonoDelay$MonoDelayRunnable.run(MonoDelay.java:117)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2020-08-14 20:48:11,871 [single-1] WARN  c.a.m.e.i.EventHubConnectionProcessor - Retry #2. Transient error occurred. Retrying after 14575 ms.
org.apache.qpid.proton.engine.TransportException: connection aborted, errorContext[NAMESPACE: some-namespace.servicebus.windows.net]
2020-08-14 20:48:11,911 [single-1] WARN  c.a.c.a.i.h.ConnectionHandler - onTransportError hostname[some-namespace.servicebus.windows.net:5671], connectionId[MF_8b5d55_1597437971807], error[org.apache.qpid.proton.engine.TransportException: connection aborted]
2020-08-14 20:48:11,911 [single-1] ERROR c.a.c.a.i.ReactorConnection - connectionId[MF_8b5d55_1597437971807] Error occurred in connection handler.
org.apache.qpid.proton.engine.TransportException: connection aborted, errorContext[NAMESPACE: some-namespace.servicebus.windows.net]
2020-08-14 20:48:27,303 [parallel-1] WARN  c.a.m.e.PartitionBasedLoadBalancer - Load balancing for event processor failed - Did not observe any item or terminal signal within 60000ms in 'flatMapMany' (and no fallback has been configured)
Did not observe any item or terminal signal within 60000ms in 'flatMapMany' (and no fallback has been configured)
2020-08-14 20:48:27,304 [parallel-1] ERROR c.e.e.i.ProcessError - Error while consuming from EventHub partition NONE
java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 60000ms in 'flatMapMany' (and no fallback has been configured)
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.handleTimeout(FluxTimeout.java:288)
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.doTimeout(FluxTimeout.java:273)
	at reactor.core.publisher.FluxTimeout$TimeoutTimeoutSubscriber.onNext(FluxTimeout.java:395)
	at reactor.core.publisher.StrictSubscriber.onNext(StrictSubscriber.java:89)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:73)
	at reactor.core.publisher.MonoDelay$MonoDelayRunnable.run(MonoDelay.java:117)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```
