### ISSUE TITLE
[BUG] BlobContainerAsyncClient.listBlobsByHierarchy sporadically very slow

### ISSUE THREAD

**Issue by tysonnorris** [Azure/azure-sdk-for-java#11375]
**Describe the bug**

Part of our application workflow is to delete blobs that may or may not have been created as part of other workflows. To determine if blobs exist that need deleting, we call BlobContainerAsyncClient.listBlobsByHierarchy(). This is typically fast (~100ms-300ms), but always at some point it runs very slow (~30s-90s) causing timeouts in other parts of our application. 

Diagnostic logs indicate only <1s response times from azure server perspective, which does NOT match with what we see at the client. We have tested in same azure region as blob store on different networks etc, and always get the same sporadic client behavior of netty exception + slow response time.

***Exception or Stack Trace***
Add the exception log and stack trace if available

With debug logs enabled via logback, we see exceptions from netty `java.io.IOException: Operation timed out` like below - note that it looks like there is some netty behavior that does `Created a new pooled channel` immediately before this happens each time. I'm not sure why existing channel is not reused?

{code}
2020-05-21 08:32:30,349 DEBUG [reactor-http-nio-1] reactor.netty.http.client.HttpClientOperations: [id: 0x74d8953c, L:/10.177.41.243:61935 - R:adobeioruntimeprod.blob.core.windows.net/52.239.155.196:443] Received last HTTP packet
  Thu May 21 08:32:30 PDT 2020 completed in : 98 
2020-05-21 08:32:30,350 DEBUG [reactor-http-nio-1] reactor.netty.resources.PooledConnectionProvider: [id: 0x74d8953c, L:/10.177.41.243:61935 - R:adobeioruntimeprod.blob.core.windows.net/52.239.155.196:443] onStateChange(GET{uri=/runtime-blob-attachments?prefix=directoryName&delimiter=/&restype=container&comp=list, connection=PooledConnection{channel=[id: 0x74d8953c, L:/10.177.41.243:61935 - R:adobeioruntimeprod.blob.core.windows.net/52.239.155.196:443]}}, [response_completed])
2020-05-21 08:32:30,350 DEBUG [reactor-http-nio-1] reactor.netty.resources.PooledConnectionProvider: [id: 0x74d8953c, L:/10.177.41.243:61935 - R:adobeioruntimeprod.blob.core.windows.net/52.239.155.196:443] onStateChange(GET{uri=/runtime-blob-attachments?prefix=directoryName&delimiter=/&restype=container&comp=list, connection=PooledConnection{channel=[id: 0x74d8953c, L:/10.177.41.243:61935 - R:adobeioruntimeprod.blob.core.windows.net/52.239.155.196:443]}}, [disconnecting])
2020-05-21 08:32:30,350 DEBUG [reactor-http-nio-1] reactor.netty.resources.PooledConnectionProvider: [id: 0x74d8953c, L:/10.177.41.243:61935 - R:adobeioruntimeprod.blob.core.windows.net/52.239.155.196:443] Releasing channel
2020-05-21 08:32:30,350 DEBUG [reactor-http-nio-1] reactor.netty.resources.PooledConnectionProvider: [id: 0x74d8953c, L:/10.177.41.243:61935 - R:adobeioruntimeprod.blob.core.windows.net/52.239.155.196:443] Channel cleaned, now 0 active connections and 1 inactive connections
Thu May 21 08:32:40 PDT 2020 starting2020-05-21 08:32:40,258 DEBUG [reactor-http-nio-1] reactor.netty.resources.PooledConnectionProvider: [id: 0x74d8953c, L:/10.177.41.243:61935 - R:adobeioruntimeprod.blob.core.windows.net/52.239.155.196:443] Channel acquired, now 1 active connections and 0 inactive connections
2020-05-21 08:32:40,258 DEBUG [reactor-http-nio-1] reactor.netty.http.client.HttpClientConnect: [id: 0x74d8953c, L:/10.177.41.243:61935 - R:adobeioruntimeprod.blob.core.windows.net/52.239.155.196:443] Handler is being applied: {uri=https://adobeioruntimeprod.blob.core.windows.net/runtime-blob-attachments?prefix=directoryName&delimiter=/&restype=container&comp=list, method=GET}
2020-05-21 08:32:40,258 DEBUG [reactor-http-nio-1] reactor.netty.resources.PooledConnectionProvider: [id: 0x74d8953c, L:/10.177.41.243:61935 - R:adobeioruntimeprod.blob.core.windows.net/52.239.155.196:443] onStateChange(GET{uri=/runtime-blob-attachments?prefix=directoryName&delimiter=/&restype=container&comp=list, connection=PooledConnection{channel=[id: 0x74d8953c, L:/10.177.41.243:61935 - R:adobeioruntimeprod.blob.core.windows.net/52.239.155.196:443]}}, [request_prepared])
2020-05-21 08:32:40,259 DEBUG [reactor-http-nio-1] reactor.netty.resources.PooledConnectionProvider: [id: 0x74d8953c, L:/10.177.41.243:61935 - R:adobeioruntimeprod.blob.core.windows.net/52.239.155.196:443] onStateChange(GET{uri=/runtime-blob-attachments?prefix=directoryName&delimiter=/&restype=container&comp=list, connection=PooledConnection{channel=[id: 0x74d8953c, L:/10.177.41.243:61935 - R:adobeioruntimeprod.blob.core.windows.net/52.239.155.196:443]}}, [request_sent])
Thu May 21 08:32:50 PDT 2020 starting2020-05-21 08:32:50,265 DEBUG [reactor-http-nio-2] reactor.netty.resources.PooledConnectionProvider: [id: 0xc692202b] Created a new pooled channel, now 2 active connections and 0 inactive connections
2020-05-21 08:32:50,266 DEBUG [reactor-http-nio-2] reactor.netty.tcp.SslProvider: [id: 0xc692202b] SSL enabled using engine OpenSslEngine and SNI adobeioruntimeprod.blob.core.windows.net:443
2020-05-21 08:32:50,266 DEBUG [reactor-http-nio-2] reactor.netty.channel.BootstrapHandlers: [id: 0xc692202b] Initialized pipeline DefaultChannelPipeline{(reactor.left.sslHandler = io.netty.handler.ssl.SslHandler), (reactor.left.sslReader = reactor.netty.tcp.SslProvider$SslReadHandler), (BootstrapHandlers$BootstrapInitializerHandler#0 = reactor.netty.channel.BootstrapHandlers$BootstrapInitializerHandler), (PooledConnectionProvider$PooledConnectionAllocator$PooledConnectionInitializer#0 = reactor.netty.resources.PooledConnectionProvider$PooledConnectionAllocator$PooledConnectionInitializer), (reactor.left.httpCodec = io.netty.handler.codec.http.HttpClientCodec), (reactor.right.reactiveBridge = reactor.netty.channel.ChannelOperationsHandler)}
2020-05-21 08:32:50,464 DEBUG [reactor-http-nio-2] reactor.netty.resources.PooledConnectionProvider: [id: 0xc692202b, L:/10.177.41.243:61945 - R:adobeioruntimeprod.blob.core.windows.net/52.239.155.196:443] Registering pool release on close event for channel
2020-05-21 08:32:50,465 DEBUG [reactor-http-nio-2] reactor.netty.resources.PooledConnectionProvider: [id: 0xc692202b, L:/10.177.41.243:61945 - R:adobeioruntimeprod.blob.core.windows.net/52.239.155.196:443] Channel connected, now 2 active connections and 0 inactive connections
2020-05-21 08:32:50,653 DEBUG [reactor-http-nio-2] io.netty.handler.ssl.SslHandler: [id: 0xc692202b, L:/10.177.41.243:61945 - R:adobeioruntimeprod.blob.core.windows.net/52.239.155.196:443] HANDSHAKEN: protocol:TLSv1.2 cipher suite:TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
2020-05-21 08:32:50,653 DEBUG [reactor-http-nio-2] reactor.netty.resources.PooledConnectionProvider: [id: 0xc692202b, L:/10.177.41.243:61945 - R:adobeioruntimeprod.blob.core.windows.net/52.239.155.196:443] onStateChange(PooledConnection{channel=[id: 0xc692202b, L:/10.177.41.243:61945 - R:adobeioruntimeprod.blob.core.windows.net/52.239.155.196:443]}, [connected])
2020-05-21 08:32:50,653 DEBUG [reactor-http-nio-2] reactor.netty.resources.PooledConnectionProvider: [id: 0xc692202b, L:/10.177.41.243:61945 - R:adobeioruntimeprod.blob.core.windows.net/52.239.155.196:443] onStateChange(GET{uri=/, connection=PooledConnection{channel=[id: 0xc692202b, L:/10.177.41.243:61945 - R:adobeioruntimeprod.blob.core.windows.net/52.239.155.196:443]}}, [configured])
2020-05-21 08:32:50,653 DEBUG [reactor-http-nio-2] reactor.netty.http.client.HttpClientConnect: [id: 0xc692202b, L:/10.177.41.243:61945 - R:adobeioruntimeprod.blob.core.windows.net/52.239.155.196:443] Handler is being applied: {uri=https://adobeioruntimeprod.blob.core.windows.net/runtime-blob-attachments?prefix=directoryName&delimiter=/&restype=container&comp=list, method=GET}
2020-05-21 08:32:50,653 DEBUG [reactor-http-nio-2] reactor.netty.resources.PooledConnectionProvider: [id: 0xc692202b, L:/10.177.41.243:61945 - R:adobeioruntimeprod.blob.core.windows.net/52.239.155.196:443] onStateChange(GET{uri=/runtime-blob-attachments?prefix=directoryName&delimiter=/&restype=container&comp=list, connection=PooledConnection{channel=[id: 0xc692202b, L:/10.177.41.243:61945 - R:adobeioruntimeprod.blob.core.windows.net/52.239.155.196:443]}}, [request_prepared])
2020-05-21 08:32:50,654 DEBUG [reactor-http-nio-2] reactor.netty.resources.PooledConnectionProvider: [id: 0xc692202b, L:/10.177.41.243:61945 - R:adobeioruntimeprod.blob.core.windows.net/52.239.155.196:443] onStateChange(GET{uri=/runtime-blob-attachments?prefix=directoryName&delimiter=/&restype=container&comp=list, connection=PooledConnection{channel=[id: 0xc692202b, L:/10.177.41.243:61945 - R:adobeioruntimeprod.blob.core.windows.net/52.239.155.196:443]}}, [request_sent])
2020-05-21 08:32:50,740 DEBUG [reactor-http-nio-2] reactor.netty.http.client.HttpClientOperations: [id: 0xc692202b, L:/10.177.41.243:61945 - R:adobeioruntimeprod.blob.core.windows.net/52.239.155.196:443] Received response (auto-read:false) : [Transfer-Encoding=chunked, Content-Type=application/xml, Server=Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0, x-ms-request-id=e92abde1-701e-0042-7085-2f301c000000, x-ms-client-request-id=397c17c6-9c96-453b-a3be-95842e730af9, x-ms-version=2019-07-07, Date=Thu, 21 May 2020 15:32:50 GMT]
2020-05-21 08:32:50,740 DEBUG [reactor-http-nio-2] reactor.netty.resources.PooledConnectionProvider: [id: 0xc692202b, L:/10.177.41.243:61945 - R:adobeioruntimeprod.blob.core.windows.net/52.239.155.196:443] onStateChange(GET{uri=/runtime-blob-attachments?prefix=directoryName&delimiter=/&restype=container&comp=list, connection=PooledConnection{channel=[id: 0xc692202b, L:/10.177.41.243:61945 - R:adobeioruntimeprod.blob.core.windows.net/52.239.155.196:443]}}, [response_received])
2020-05-21 08:32:50,741 DEBUG [reactor-http-nio-2] reactor.netty.channel.FluxReceive: [id: 0xc692202b, L:/10.177.41.243:61945 - R:adobeioruntimeprod.blob.core.windows.net/52.239.155.196:443] Subscribing inbound receiver [pending: 0, cancelled:false, inboundDone: false]
2020-05-21 08:32:50,741 DEBUG [reactor-http-nio-2] reactor.netty.http.client.HttpClientOperations: [id: 0xc692202b, L:/10.177.41.243:61945 - R:adobeioruntimeprod.blob.core.windows.net/52.239.155.196:443] Received last HTTP packet
  Thu May 21 08:32:50 PDT 2020 completed in : 482 
2020-05-21 08:32:50,743 DEBUG [reactor-http-nio-2] reactor.netty.resources.PooledConnectionProvider: [id: 0xc692202b, L:/10.177.41.243:61945 - R:adobeioruntimeprod.blob.core.windows.net/52.239.155.196:443] onStateChange(GET{uri=/runtime-blob-attachments?prefix=directoryName&delimiter=/&restype=container&comp=list, connection=PooledConnection{channel=[id: 0xc692202b, L:/10.177.41.243:61945 - R:adobeioruntimeprod.blob.core.windows.net/52.239.155.196:443]}}, [response_completed])
2020-05-21 08:32:50,743 DEBUG [reactor-http-nio-2] reactor.netty.resources.PooledConnectionProvider: [id: 0xc692202b, L:/10.177.41.243:61945 - R:adobeioruntimeprod.blob.core.windows.net/52.239.155.196:443] onStateChange(GET{uri=/runtime-blob-attachments?prefix=directoryName&delimiter=/&restype=container&comp=list, connection=PooledConnection{channel=[id: 0xc692202b, L:/10.177.41.243:61945 - R:adobeioruntimeprod.blob.core.windows.net/52.239.155.196:443]}}, [disconnecting])
2020-05-21 08:32:50,743 DEBUG [reactor-http-nio-2] reactor.netty.resources.PooledConnectionProvider: [id: 0xc692202b, L:/10.177.41.243:61945 - R:adobeioruntimeprod.blob.core.windows.net/52.239.155.196:443] Releasing channel
2020-05-21 08:32:50,743 DEBUG [reactor-http-nio-2] reactor.netty.resources.PooledConnectionProvider: [id: 0xc692202b, L:/10.177.41.243:61945 - R:adobeioruntimeprod.blob.core.windows.net/52.239.155.196:443] Channel cleaned, now 1 active connections and 1 inactive connections
Thu May 21 08:33:00 PDT 2020 starting2020-05-21 08:33:00,269 DEBUG [reactor-http-nio-2] reactor.netty.resources.PooledConnectionProvider: [id: 0xc692202b, L:/10.177.41.243:61945 - R:adobeioruntimeprod.blob.core.windows.net/52.239.155.196:443] Channel acquired, now 2 active connections and 0 inactive connections
2020-05-21 08:33:00,269 DEBUG [reactor-http-nio-2] reactor.netty.http.client.HttpClientConnect: [id: 0xc692202b, L:/10.177.41.243:61945 - R:adobeioruntimeprod.blob.core.windows.net/52.239.155.196:443] Handler is being applied: {uri=https://adobeioruntimeprod.blob.core.windows.net/runtime-blob-attachments?prefix=directoryName&delimiter=/&restype=container&comp=list, method=GET}
2020-05-21 08:33:00,269 DEBUG [reactor-http-nio-2] reactor.netty.resources.PooledConnectionProvider: [id: 0xc692202b, L:/10.177.41.243:61945 - R:adobeioruntimeprod.blob.core.windows.net/52.239.155.196:443] onStateChange(GET{uri=/runtime-blob-attachments?prefix=directoryName&delimiter=/&restype=container&comp=list, connection=PooledConnection{channel=[id: 0xc692202b, L:/10.177.41.243:61945 - R:adobeioruntimeprod.blob.core.windows.net/52.239.155.196:443]}}, [request_prepared])
2020-05-21 08:33:00,270 DEBUG [reactor-http-nio-2] reactor.netty.resources.PooledConnectionProvider: [id: 0xc692202b, L:/10.177.41.243:61945 - R:adobeioruntimeprod.blob.core.windows.net/52.239.155.196:443] onStateChange(GET{uri=/runtime-blob-attachments?prefix=directoryName&delimiter=/&restype=container&comp=list, connection=PooledConnection{channel=[id: 0xc692202b, L:/10.177.41.243:61945 - R:adobeioruntimeprod.blob.core.windows.net/52.239.155.196:443]}}, [request_sent])
2020-05-21 08:33:00,357 DEBUG [reactor-http-nio-2] reactor.netty.http.client.HttpClientOperations: [id: 0xc692202b, L:/10.177.41.243:61945 - R:adobeioruntimeprod.blob.core.windows.net/52.239.155.196:443] Received response (auto-read:false) : [Transfer-Encoding=chunked, Content-Type=application/xml, Server=Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0, x-ms-request-id=e92acffa-701e-0042-1785-2f301c000000, x-ms-client-request-id=8d82d9f3-2c4e-4f83-b2ce-9ee6982c18d2, x-ms-version=2019-07-07, Date=Thu, 21 May 2020 15:32:59 GMT]
2020-05-21 08:33:00,357 DEBUG [reactor-http-nio-2] reactor.netty.resources.PooledConnectionProvider: [id: 0xc692202b, L:/10.177.41.243:61945 - R:adobeioruntimeprod.blob.core.windows.net/52.239.155.196:443] onStateChange(GET{uri=/runtime-blob-attachments?prefix=directoryName&delimiter=/&restype=container&comp=list, connection=PooledConnection{channel=[id: 0xc692202b, L:/10.177.41.243:61945 - R:adobeioruntimeprod.blob.core.windows.net/52.239.155.196:443]}}, [response_received])
2020-05-21 08:33:00,358 DEBUG [reactor-http-nio-2] reactor.netty.channel.FluxReceive: [id: 0xc692202b, L:/10.177.41.243:61945 - R:adobeioruntimeprod.blob.core.windows.net/52.239.155.196:443] Subscribing inbound receiver [pending: 0, cancelled:false, inboundDone: false]
2020-05-21 08:33:00,358 DEBUG [reactor-http-nio-2] reactor.netty.http.client.HttpClientOperations: [id: 0xc692202b, L:/10.177.41.243:61945 - R:adobeioruntimeprod.blob.core.windows.net/52.239.155.196:443] Received last HTTP packet
  Thu May 21 08:33:00 PDT 2020 completed in : 92 
2020-05-21 08:33:00,359 DEBUG [reactor-http-nio-2] reactor.netty.resources.PooledConnectionProvider: [id: 0xc692202b, L:/10.177.41.243:61945 - R:adobeioruntimeprod.blob.core.windows.net/52.239.155.196:443] onStateChange(GET{uri=/runtime-blob-attachments?prefix=directoryName&delimiter=/&restype=container&comp=list, connection=PooledConnection{channel=[id: 0xc692202b, L:/10.177.41.243:61945 - R:adobeioruntimeprod.blob.core.windows.net/52.239.155.196:443]}}, [response_completed])
2020-05-21 08:33:00,359 DEBUG [reactor-http-nio-2] reactor.netty.resources.PooledConnectionProvider: [id: 0xc692202b, L:/10.177.41.243:61945 - R:adobeioruntimeprod.blob.core.windows.net/52.239.155.196:443] onStateChange(GET{uri=/runtime-blob-attachments?prefix=directoryName&delimiter=/&restype=container&comp=list, connection=PooledConnection{channel=[id: 0xc692202b, L:/10.177.41.243:61945 - R:adobeioruntimeprod.blob.core.windows.net/52.239.155.196:443]}}, [disconnecting])
2020-05-21 08:33:00,359 DEBUG [reactor-http-nio-2] reactor.netty.resources.PooledConnectionProvider: [id: 0xc692202b, L:/10.177.41.243:61945 - R:adobeioruntimeprod.blob.core.windows.net/52.239.155.196:443] Releasing channel
2020-05-21 08:33:00,359 DEBUG [reactor-http-nio-2] reactor.netty.resources.PooledConnectionProvider: [id: 0xc692202b, L:/10.177.41.243:61945 - R:adobeioruntimeprod.blob.core.windows.net/52.239.155.196:443] Channel cleaned, now 1 active connections and 1 inactive connections
2020-05-21 08:33:06,217 WARN  [reactor-http-nio-1] reactor.netty.http.client.HttpClientConnect: [id: 0x74d8953c, L:/10.177.41.243:61935 - R:adobeioruntimeprod.blob.core.windows.net/52.239.155.196:443] The connection observed an error
java.io.IOException: Operation timed out
	at java.base/sun.nio.ch.SocketDispatcher.read0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:47)
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:367)
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1133)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:830)
2020-05-21 08:33:06,223 DEBUG [reactor-http-nio-1] reactor.netty.resources.PooledConnectionProvider: [id: 0x74d8953c, L:/10.177.41.243:61935 ! R:adobeioruntimeprod.blob.core.windows.net/52.239.155.196:443] Channel closed, now 0 active connections and 1 inactive connections
2020-05-21 08:33:06,226 DEBUG [reactor-http-nio-1] reactor.netty.resources.PooledConnectionProvider: [id: 0x74d8953c, L:/10.177.41.243:61935 ! R:adobeioruntimeprod.blob.core.windows.net/52.239.155.196:443] onStateChange(GET{uri=/runtime-blob-attachments?prefix=directoryName&delimiter=/&restype=container&comp=list, connection=PooledConnection{channel=[id: 0x74d8953c, L:/10.177.41.243:61935 ! R:adobeioruntimeprod.blob.core.windows.net/52.239.155.196:443]}}, [disconnecting])

{code}
**To Reproduce**

Run the sample app at https://gist.github.com/tysonnorris/9c82577af0a66aeebe9fdb0dbddc72c8
You will need to set env vars with azure blob connection details.

I'm using mvn dependencies:
{code}
    <dependencies>
        
        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-storage-blob</artifactId>
            <version>12.6.1</version>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>1.2.3</version>
        </dependency>
    </dependencies>
{code}

After some time, note that some access to this listBlobsByHierarchy will be slow as indicated by stdout lines like:
`WARN: LONG RESPONSE TIME 30057 (exceeded 5000)`

Sometimes these long response times are 90+seconds, but vary. Typical response times are much less (<1s).

***Code Snippet***
Add the code snippet that causes the issue.

see simplistic sample app at https://gist.github.com/tysonnorris/9c82577af0a66aeebe9fdb0dbddc72c8

**Expected behavior**

Response times should be more consistent. 
Response times should never exceed 60s. 
Response times seen by client should correlate with response times indicated in diagnostic logs, with some difference typical for network latency between client and region. (we understand that not all network traffic will be consistent, but this probably seems unique to this java client and azure blob store, we don't see similar problems with any other network traffic)  

**Screenshots**
N/A

**Setup (please complete the following information):**
 - IDE : [e.g. IntelliJ]
 - Version of the Library used

com.azure:azure-storage-blob:12.6.1
tried openjdk 1.8 and openjdk 13.

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by rickle-msft** [comment]
Hi, @tysonnorris. Thank you for reporting this issue. I agree that it is odd this operation would sporadically have very high latency. Thank you as well for providing the sample app. I'll work on using it to verify this behavior and get back to you.

**Comment by tysonnorris** [comment]
Thanks @rickle-msft . Note that this may be easier to see when running client in different regions - we see it much more when running a client in southeast asia region, reaching blob container in us east, although we do also see the problem (less frequently) when client runs in us west, reaching blob container in us east.

**Comment by gapra-msft** [comment]
Hi, @tysonnorris. Just wanted to update you on our progress. We are able to verify this behavior and we are looking into what might be causing this sporadic slowness.

**Comment by rickle-msft** [comment]
Hi, @tysonnorris I believe there was a follow up offline here, but if you wouldn't mind letting us know how you are fairing with this issue and if you still need support here, we'd very much appreciate it.

**Comment by rickle-msft** [comment]
I am going to close this issue based on the offline follow up and lack of follow up on this issue.

If you need further support please reach out in the way you feel most appropriate.
