### ISSUE TITLE
[BUG] IOException while trying to download blob to file

### ISSUE THREAD

**Issue by brijesh099** [Azure/azure-sdk-for-java#11596]
**Describe the bug**
IOException: An existing connection was forcibly closed by the remote host.

***Exception or Stack Trace***
2020-05-27 20:39:00 Error occurred while retrieving Container with name: qa-gamma .
reactor.core.Exceptions$ReactiveException: java.io.IOException: An existing connection was forcibly closed by the remote host
        at reactor.core.Exceptions.propagate(Exceptions.java:336)
        at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:91)
        at reactor.core.publisher.Mono.block(Mono.java:1663)
        at com.azure.storage.common.implementation.StorageImplUtils.blockWithOptionalTimeout(StorageImplUtils.java:99)
        at com.azure.storage.blob.BlobContainerClient.existsWithResponse(BlobContainerClient.java:195)
        at com.azure.storage.blob.BlobContainerClient.exists(BlobContainerClient.java:179)
        at FileManager.getClientContainer(FileManager.java:799)
        at FileManager.download(FileManager.java:906)        
        Suppressed: java.lang.Exception: #block terminated with an error
                at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:93)
                ... 26 more
Caused by: java.io.IOException: An existing connection was forcibly closed by the remote host
        at sun.nio.ch.SocketDispatcher.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(Unknown Source)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source)
        at sun.nio.ch.IOUtil.read(Unknown Source)
        at sun.nio.ch.SocketChannelImpl.read(Unknown Source)
        at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:247)
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1147)
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
        at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        ... 1 more

**To Reproduce**
Upload file to blob container.
Use azure-core-http-netty Http Client
BlobClient downloadToFile

***Code Snippet***
Download(String accountName, String accountKey, String containerName, String blobPath, String destinationFilePath) throws Exception {
 
        try {
            //Build the object for StorageSharedKeyCredential
            StorageSharedKeyCredential credential = new StorageSharedKeyCredential(accountName, accountKey);
            String endpoint = String.format("https://%s.blob.core.windows.net", accountName);
            // add create the retry policies on container client.
            Integer maxTries = 4;
            Integer tryTimeout = 300;
            Long retryDelayInMs = TimeUnit.SECONDS.toMillis(60);
            Long maxRetryDelayInMs = TimeUnit.SECONDS.toMillis(300);
            String secondaryHost = null;
            // Create a BlobServiceClient object which will be used to create a container client
            RequestRetryOptions retryOptions = new RequestRetryOptions(RetryPolicyType.EXPONENTIAL, maxTries, tryTimeout, retryDelayInMs, maxRetryDelayInMs, secondaryHost);
            BlobServiceClient blobServiceClient = new BlobServiceClientBuilder().endpoint(endpoint).credential(credential).retryOptions(retryOptions).buildClient();
 
            BlobContainerClient containerClient = blobServiceClient.getBlobContainerClient(containerName);
            if (!containerClient.exists()) {
                containerClient = null;
                throw new Exception(ERROR_STATUS + ": Container does not exist with name: " + containerName);
            }
            //get current Blob
            BlobClient blobClient = containerClient.getBlobClient(blobPath);
            // Download the blob to the specified file path
            blobClient.downloadToFile(destinationFilePath);
        } 
        } catch (Exception e) {
            if (logger != null && logger.getLevel().equals(Level.ERROR)) {
                logger.error("Error occurred while retrieving Container with name: " + containerName + " .", e);
            }
            throw new Exception(ERROR_STATUS + ": Exception errored during retrieving container  with name: " + containerName + " ;Error: " + e.toString());
        }
    }

**Expected behavior**
File downloaded to directory

**Screenshots**

**Setup (please complete the following information):**
 - OS: Windows Server 2016 Standard
 - IDE : NetBeans
 - Version of the Library used
azure-storage-blob version is 12.4.0

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by joshfree** [comment]
@rickle-msft @gapra-msft could you please take a look?

/cc @alzimmermsft

**Comment by rickle-msft** [comment]
@brijesh099 Thank you for reporting this and for sharing some code. Can you please describe your environment a little more and also let us know how frequently you hit this error? Is it every time or only periodically?

**Comment by brijesh099** [comment]
@rickle-msft We are facing issue in both OnPremise and Azure Cloud both are running same OS and JAVA version. 

- Azure Cloud:
> VM Location: West US 2
> OS: Windows (Windows Server 2019 Datacenter)
> VM Size: Standard D8s v3 (8 vcpus, 32 GiB memory)
> Java version "1.8.0_231"

- Onprem:  
> OS: Windows Server 2016 Standard
> java version "1.8.0_241"
> MAchine: Intel(R) Xeon(R) CPU E5-1620 @3.60GHz, 64GB RAM

- Azure Storage:
> Location: West US 2
> Accoutn kind: StorageV2 (general purpose v2)

- Version of the Library used:
> azure-storage-blob version is 12.4.0

This issue is happening periodically right now. But we were not seeing this issue earlier (over a month ago) and we haven't change anything w.r.t local environment or code. This issue is not consistent so upgrading to 12.6.0 version and testing for a day or two will not guarantee that issue is resolved in upgraded version.

**Comment by rickle-msft** [comment]
@brijesh099 I understand. Unfortunately, we don't have enough to go off of with just the code you sent since the error is so intermittent. Because of that, I still believe the best option to be upgrading to 12.6.0 and also enabling logging for the sdk. IOExceptions should be getting retried, and retries do typically help with this sort of thing, so I'd like to confirm that is happening in the logs if at all possible

**Comment by rickle-msft** [comment]
Could you also please share the size of the file you are trying to download?

**Comment by brijesh099** [comment]
I have already implemented retry logic but it didn't help. It is there in sample code I have provided. Can you please provide more detail on "enabling logging for the sdk". I also added  BlobStorageException in catch block. But since IOExceptions is thrown by SDK, catch block for BlobStorageException is not getting used. 

Regarding file size, it happens during downloading large file 1.2GB. But we have also seen the same exception when we try BlobContainerClient.exist() method.

**Comment by rickle-msft** [comment]
The SDK has retry logic that happens internally automatically that should be handling this, and I'd like to see what's going on there. You can find information about how to enable logging [here](https://github.com/Azure/azure-sdk-for-java/wiki/Logging-with-Azure-SDK).

Thank you for the sharing that about container exists. That is interesting you are seeing it there as well.

**Comment by rickle-msft** [comment]
@brijesh099 Please let us know if you need further support here otherwise we will close this issue soon.

**Comment by brijesh099** [comment]
@rickle-msft Upgrading to latest version 12.7.0 of SDK resolved the issue.
