### ISSUE TITLE
Retrieving virtual machine images fails for german region / german regions missing from enum

### ISSUE THREAD

**Issue by selevt** [Azure/azure-sdk-for-java#1161]
Retrieving the list of virtual machine images in the region "GermanyCentral" fails with an NPE. The location/region in the VirtualMachinePublisherImpl is set to null, because the region isn't part of the Region enum.

Using version 1.0.0-beta2.

Stacktrace:
```
java.lang.NullPointerException
	at com.microsoft.azure.management.compute.implementation.VirtualMachineOffersImpl.list(VirtualMachineOffersImpl.java:39)
	at com.microsoft.azure.management.compute.implementation.VirtualMachineImagesImpl$1.loadList(VirtualMachineImagesImpl.java:38)
	at com.microsoft.azure.management.compute.implementation.VirtualMachineImagesImpl$1.loadList(VirtualMachineImagesImpl.java:35)
	at com.microsoft.azure.management.compute.implementation.ChildListFlattener.nextChildList(ChildListFlattener.java:129)
	at com.microsoft.azure.management.compute.implementation.ChildListFlattener.flatten(ChildListFlattener.java:66)
	at com.microsoft.azure.management.compute.implementation.VirtualMachineImagesImpl.listByRegion(VirtualMachineImagesImpl.java:40)
```

**Comment by jianghaolu** [comment]
Fixed and released with beta3.
