### ISSUE TITLE
[BUG] VSCodeCredential throws exception when DAC is run in Container

### ISSUE THREAD

**Issue by jongio** [Azure/azure-sdk-for-java#11649]
Get this error when using DAC in container

For users that don't need VSCodeCredential, include excludeVSCodeCredential in your DAC builder and with beta4, you must also excludeManagedIdentityCredential() #11373 and excludeSharedTokenCacheCredential() is included to ensure we use CliCredential.

```
    DefaultAzureCredential credential = new DefaultAzureCredentialBuilder()
      .excludeManagedIdentityCredential()
      .excludeSharedTokenCacheCredential()
      .excludeVSCodeCredential()
      .build();
```

```
Native library (linux-x86-64/liblibsecret-1.so) not found in resource path ([file:/usr/app/target/sdk-1.0-SNAPSHOT.jar])
sdk_1  |        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:302)
sdk_1  |        at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:455)
sdk_1  |        at com.sun.jna.Library$Handler.<init>(Library.java:192)
sdk_1  |        at com.sun.jna.Native.load(Native.java:596)
sdk_1  |        at com.sun.jna.Native.load(Native.java:570)
sdk_1  |        at com.microsoft.aad.msal4jextensions.persistence.linux.ISecurityLibrary.<clinit>(ISecurityLibrary.java:18)
sdk_1  |        at com.azure.identity.implementation.LinuxKeyRingAccessor.read(LinuxKeyRingAccessor.java:50)
sdk_1  |        at com.azure.identity.implementation.LinuxKeyRingAccessor.read(LinuxKeyRingAccessor.java:70)
sdk_1  |        at com.azure.identity.implementation.VisualStudioCacheAccessor.getCredentials(VisualStudioCacheAccessor.java:132)
sdk_1  |        at com.azure.identity.implementation.IdentityClient.authenticateWithVsCodeCredential(IdentityClient.java:539)
sdk_1  |        at com.azure.identity.VisualStudioCodeCredential.lambda$getToken$2(VisualStudioCodeCredential.java:76)
sdk_1  |        at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44)
sdk_1  |        at reactor.core.publisher.Mono.subscribe(Mono.java:4218)
sdk_1  |        at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FluxSwitchIfEmpty.java:75)
sdk_1  |        at reactor.core.publisher.Operators.complete(Operators.java:135)
sdk_1  |        at reactor.core.publisher.MonoEmpty.subscribe(MonoEmpty.java:45)
sdk_1  |        at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
sdk_1  |        at reactor.core.publisher.Mono.subscribe(Mono.java:4218)
sdk_1  |        at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:418)
sdk_1  |        at reactor.core.publisher.FluxIterable$IterableSubscription.slowPath(FluxIterable.java:267)
sdk_1  |        at reactor.core.publisher.FluxIterable$IterableSubscription.request(FluxIterable.java:225)
sdk_1  |        at reactor.core.publisher.FluxFlatMap$FlatMapMain.onSubscribe(FluxFlatMap.java:363)
sdk_1  |        at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:161)
sdk_1  |        at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:86)
sdk_1  |        at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
sdk_1  |        at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
sdk_1  |        at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
sdk_1  |        at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
sdk_1  |        at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
sdk_1  |        at reactor.core.publisher.MonoDelaySubscription.accept(MonoDelaySubscription.java:52)
sdk_1  |        at reactor.core.publisher.MonoDelaySubscription.accept(MonoDelaySubscription.java:33)
sdk_1  |        at reactor.core.publisher.FluxDelaySubscription$DelaySubscriptionOtherSubscriber.onNext(FluxDelaySubscription.java:123)
sdk_1  |        at reactor.core.publisher.MonoDelay$MonoDelayRunnable.run(MonoDelay.java:117)
sdk_1  |        at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
sdk_1  |        at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
sdk_1  |        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
sdk_1  |        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
sdk_1  |        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
sdk_1  |        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
sdk_1  |        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
sdk_1  |        at java.lang.Thread.run(Thread.java:748)
sdk_1  |        Suppressed: java.lang.UnsatisfiedLinkError: liblibsecret-1.so: cannot open shared object file: No such file or directory
sdk_1  |                at com.sun.jna.Native.open(Native Method)
sdk_1  |                at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:191)
sdk_1  |                ... 40 common frames omitted
sdk_1  |        Suppressed: java.lang.UnsatisfiedLinkError: liblibsecret-1.so: cannot open shared object file: No such file or directory
sdk_1  |                at com.sun.jna.Native.open(Native Method)
sdk_1  |                at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:204)
sdk_1  |                ... 40 common frames omitted
sdk_1  |        Suppressed: java.io.IOException: Native library (linux-x86-64/liblibsecret-1.so) not found in resource path ([file:/usr/app/target/sdk-1.0-SNAPSHOT.jar])
sdk_1  |                at com.sun.jna.Native.extractFromResourcePath(Native.java:1095)
sdk_1  |                at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:276)
sdk_1  |                ... 40 common frames omitted
```

0. az login
1. create new maven project
2. add to pom.xml

```
<?xml version="1.0" encoding="UTF-8" ?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>demo</groupId>
  <artifactId>sdk</artifactId>
  <version>1.0-SNAPSHOT</version>

  <name>sdk</name>
  <!-- FIXME change it to the project's website -->
  <url>http://www.example.com</url>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.source>1.8</maven.compiler.source>
    <maven.compiler.target>1.8</maven.compiler.target>
  </properties>

  <dependencies>

    <dependency>
      <groupId>io.github.cdimascio</groupId>
      <artifactId>java-dotenv</artifactId>
      <version>5.2.0</version>
    </dependency>
    
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
      <version>1.7.30</version>
    </dependency>

    <dependency>
      <groupId>ch.qos.logback</groupId>
      <artifactId>logback-classic</artifactId>
      <version>1.2.3</version>
    </dependency>

    <dependency>
      <groupId>com.azure</groupId>
      <artifactId>azure-storage-blob</artifactId>
      <version>12.6.1</version>
    </dependency>


    <dependency>
      <groupId>com.azure</groupId>
      <artifactId>azure-identity</artifactId>
      <version>1.1.0-beta.4</version>
    </dependency>

    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.11</version>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <pluginManagement>
      <!-- lock down plugins versions to avoid using Maven defaults (may be moved to parent pom) -->
      <plugins>
        <!-- clean lifecycle, see https://maven.apache.org/ref/current/maven-core/lifecycles.html#clean_Lifecycle -->
        <plugin>
          <artifactId>maven-clean-plugin</artifactId>
          <version>3.1.0</version>
        </plugin>
        <!-- default lifecycle, jar packaging: see https://maven.apache.org/ref/current/maven-core/default-bindings.html#Plugin_bindings_for_jar_packaging -->
        <plugin>
          <artifactId>maven-resources-plugin</artifactId>
          <version>3.0.2</version>
        </plugin>
        <plugin>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>3.8.0</version>
        </plugin>
        <plugin>
          <artifactId>maven-surefire-plugin</artifactId>
          <version>2.22.1</version>
        </plugin>
        <plugin>
          <artifactId>maven-jar-plugin</artifactId>
          <version>3.0.2</version>
        </plugin>
        <plugin>
          <artifactId>maven-install-plugin</artifactId>
          <version>2.5.2</version>
        </plugin>
        <plugin>
          <artifactId>maven-deploy-plugin</artifactId>
          <version>2.8.2</version>
        </plugin>
        <!-- site lifecycle, see https://maven.apache.org/ref/current/maven-core/lifecycles.html#site_Lifecycle -->
        <plugin>
          <artifactId>maven-site-plugin</artifactId>
          <version>3.7.1</version>
        </plugin>
        <plugin>
          <artifactId>maven-project-info-reports-plugin</artifactId>
          <version>3.0.0</version>
        </plugin>
        <plugin>
          <artifactId>maven-assembly-plugin</artifactId>
          <executions>
            <execution>
              <phase>package</phase>
              <goals>
                <goal>single</goal>
              </goals>
            </execution>
          </executions>
          <configuration>
            <archive>
              <manifest>
                <addClasspath>true</addClasspath>
                <mainClass>demo.App</mainClass>
              </manifest>
            </archive>
            <descriptorRefs>
              <descriptorRef>jar-with-dependencies</descriptorRef>
            </descriptorRefs>
            <appendAssemblyId>false</appendAssemblyId>
          </configuration>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>
</project>
```

Code
```java
package demo;

import ch.qos.logback.classic.Logger;
import com.azure.identity.DefaultAzureCredential;
import com.azure.identity.DefaultAzureCredentialBuilder;
import com.azure.storage.blob.BlobContainerClient;
import com.azure.storage.blob.BlobServiceClient;
import com.azure.storage.blob.BlobServiceClientBuilder;
import io.github.cdimascio.dotenv.Dotenv;
import org.slf4j.LoggerFactory;

public class App {
  private static final Logger LOGGER = (Logger) LoggerFactory.getLogger("root");

  private static final Dotenv ENV = Dotenv
    .configure()
    .ignoreIfMissing()
    .systemProperties()
    .directory("../../")
    .load();

  public static void main(String[] args) {
    DefaultAzureCredential credential = new DefaultAzureCredentialBuilder()
      .excludeManagedIdentityCredential()
      .excludeSharedTokenCacheCredential()
      //.excludeVSCodeCredential()
      .build();

    BlobServiceClient blobStorageClient = new BlobServiceClientBuilder()
      .endpoint(ENV.get("AZURE_STORAGE_BLOB_URL"))
      .credential(credential)
      .buildClient();

    BlobContainerClient blobContainerClient = blobStorageClient.getBlobContainerClient(
      ENV.get("AZURE_STORAGE_CONTAINER_NAME")
    );

    Boolean exists = blobContainerClient.exists();
    LOGGER.info("Container exists: {}", exists);
  }
}

```

logback.xml
```
<?xml version="1.0" encoding="UTF-8" ?>
<configuration>
    <appender name="Console" class="ch.qos.logback.core.ConsoleAppender">
        <layout class="ch.qos.logback.classic.PatternLayout">
            <Pattern>
        %white(%d{ISO8601}) %white(%-5level) [%white(%t)] %white(%logger{100}): %msg%n%throwable
      </Pattern>
        </layout>
    </appender>
    <root level="trace">
        <appender-ref ref="Console" />
    </root>
    <logger name="reactor.netty" level="info" />
    <logger name="io.netty" level="info" />
</configuration>
```

docker-compose.xml
```yaml
version: '3.4'

services:
  sdk:
    env_file: ../../.env
    volumes: 
      - "${HOME}/.m2:/root/.m2"
      - "${HOME}/.azure:/home/developer/.azure"
    image: sdk
    build: .
```

Dockerfile
```
FROM maven:3-jdk-8-alpine AS build-env
WORKDIR /usr/app/
COPY pom.xml .
RUN mvn dependency:go-offline

COPY src/ /usr/app/src
RUN mvn package -Dmaven.test.skip=true assembly:single

# Build runtime image
FROM openkbs/jre-mvn-py3
RUN pip3 install --user azure-cli
ENV PATH /home/developer/.local/bin/:$PATH

WORKDIR /usr/app/
COPY --from=build-env /usr/app/ .
ENTRYPOINT ["java", "-jar", "target/sdk-1.0-SNAPSHOT.jar"]
```

azsdke2e

**Comment by jongio** [comment]
This is resolved in GA

**Comment by jongio** [comment]
I'm able to repro this with GA bits

Code:
```
   @Test
   public void testVSCodeCredential() {
     VisualStudioCodeCredential cred = new VisualStudioCodeCredentialBuilder()
       .build();
    
     SecretAsyncClient client = new SecretClientBuilder()
       .vaultUrl(vault)
       .credential(cred)
       .buildAsyncClient();

     StepVerifier.create(client.getSecret("hello"))
       .expectError()
       .verify();
   }
```

Log:
```
azidcontainerjava_1  | [main] INFO com.azure.security.keyvault.secrets.SecretAsyncClient - Retrieving secret - hello
azidcontainerjava_1  | [reactor-http-epoll-1] ERROR reactor.netty.channel.ChannelOperationsHandler - [id: 0x4b9aa9dd, L:/172.19.0.2:58396 ! R:jongkv.vault.azure.net/13.66.226.249:443] Error was received while reading the incoming data. The connection will be closed.
azidcontainerjava_1  | java.lang.UnsatisfiedLinkError: Unable to load library 'libsecret-1':
azidcontainerjava_1  | liblibsecret-1.so: cannot open shared object file: No such file or directory
azidcontainerjava_1  | liblibsecret-1.so: cannot open shared object file: No such file or directory
azidcontainerjava_1  | Native library (linux-x86-64/liblibsecret-1.so) not found in resource path ([file:/usr/app/target/surefire/surefirebooter3081959569955579351.jar])
azidcontainerjava_1  |  at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:302)
azidcontainerjava_1  |  at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:455)
azidcontainerjava_1  |  at com.sun.jna.Library$Handler.<init>(Library.java:192)
azidcontainerjava_1  |  at com.sun.jna.Native.load(Native.java:596)
azidcontainerjava_1  |  at com.sun.jna.Native.load(Native.java:570)
azidcontainerjava_1  |  at com.microsoft.aad.msal4jextensions.persistence.linux.ISecurityLibrary.<clinit>(ISecurityLibrary.java:18)
azidcontainerjava_1  |  at com.azure.identity.implementation.LinuxKeyRingAccessor.read(LinuxKeyRingAccessor.java:50)
azidcontainerjava_1  |  at com.azure.identity.implementation.LinuxKeyRingAccessor.read(LinuxKeyRingAccessor.java:70)
azidcontainerjava_1  |  at com.azure.identity.implementation.VisualStudioCacheAccessor.getCredentials(VisualStudioCacheAccessor.java:132)
azidcontainerjava_1  |  at com.azure.identity.implementation.IdentityClient.authenticateWithVsCodeCredential(IdentityClient.java:597)
azidcontainerjava_1  |  at com.azure.identity.VisualStudioCodeCredential.lambda$getToken$2(VisualStudioCodeCredential.java:79)
azidcontainerjava_1  |  at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44)
azidcontainerjava_1  |  at reactor.core.publisher.Mono.subscribe(Mono.java:4218)
azidcontainerjava_1  |  at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FluxSwitchIfEmpty.java:75)
azidcontainerjava_1  |  at reactor.core.publisher.Operators.complete(Operators.java:135)
azidcontainerjava_1  |  at reactor.core.publisher.MonoEmpty.subscribe(MonoEmpty.java:45)
azidcontainerjava_1  |  at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
azidcontainerjava_1  |  at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
azidcontainerjava_1  |  at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
azidcontainerjava_1  |  at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:150)
azidcontainerjava_1  |  at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:121)
azidcontainerjava_1  |  at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:121)
azidcontainerjava_1  |  at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:203)
azidcontainerjava_1  |  at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1755)
azidcontainerjava_1  |  at reactor.core.publisher.MonoSingle$SingleSubscriber.onComplete(MonoSingle.java:171)
azidcontainerjava_1  |  at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2319)
azidcontainerjava_1  |  at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onSubscribeInner(MonoFlatMapMany.java:143)
azidcontainerjava_1  |  at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onNext(MonoFlatMapMany.java:182)
azidcontainerjava_1  |  at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:99)
azidcontainerjava_1  |  at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.onNext(FluxRetryWhen.java:162)
azidcontainerjava_1  |  at reactor.core.publisher.MonoCreate$DefaultMonoSink.success(MonoCreate.java:156)
azidcontainerjava_1  |  at reactor.netty.http.client.HttpClientConnect$HttpIOHandlerObserver.onStateChange(HttpClientConnect.java:431)
azidcontainerjava_1  |  at reactor.netty.ReactorNetty$CompositeConnectionObserver.onStateChange(ReactorNetty.java:514)
azidcontainerjava_1  |  at reactor.netty.resources.PooledConnectionProvider$DisposableAcquire.onStateChange(PooledConnectionProvider.java:540)
azidcontainerjava_1  |  at reactor.netty.resources.PooledConnectionProvider$PooledConnection.onStateChange(PooledConnectionProvider.java:427)
azidcontainerjava_1  |  at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:574)
azidcontainerjava_1  |  at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:96)
azidcontainerjava_1  |  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
azidcontainerjava_1  |  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
azidcontainerjava_1  |  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
azidcontainerjava_1  |  at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
azidcontainerjava_1  |  at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
azidcontainerjava_1  |  at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311)
azidcontainerjava_1  |  at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:425)
azidcontainerjava_1  |  at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
azidcontainerjava_1  |  at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
azidcontainerjava_1  |  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
azidcontainerjava_1  |  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
azidcontainerjava_1  |  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
azidcontainerjava_1  |  at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1526)
azidcontainerjava_1  |  at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1287)
azidcontainerjava_1  |  at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1324)
azidcontainerjava_1  |  at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
azidcontainerjava_1  |  at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
azidcontainerjava_1  |  at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
azidcontainerjava_1  |  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
azidcontainerjava_1  |  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
azidcontainerjava_1  |  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
azidcontainerjava_1  |  at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
azidcontainerjava_1  |  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
azidcontainerjava_1  |  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
azidcontainerjava_1  |  at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
azidcontainerjava_1  |  at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)
azidcontainerjava_1  |  at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475)
azidcontainerjava_1  |  at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
azidcontainerjava_1  |  at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
azidcontainerjava_1  |  at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
azidcontainerjava_1  |  at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
azidcontainerjava_1  |  at java.lang.Thread.run(Thread.java:748)
azidcontainerjava_1  |  Suppressed: java.lang.UnsatisfiedLinkError: liblibsecret-1.so: cannot open shared object file: No such file or directory
azidcontainerjava_1  |          at com.sun.jna.Native.open(Native Method)
azidcontainerjava_1  |          at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:191)
azidcontainerjava_1  |          ... 68 more
azidcontainerjava_1  |  Suppressed: java.lang.UnsatisfiedLinkError: liblibsecret-1.so: cannot open shared object file: No such file or directory
azidcontainerjava_1  |          at com.sun.jna.Native.open(Native Method)
azidcontainerjava_1  |          at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:204)
azidcontainerjava_1  |          ... 68 more
azidcontainerjava_1  |  Suppressed: java.io.IOException: Native library (linux-x86-64/liblibsecret-1.so) not found in resource path ([file:/usr/app/target/surefire/surefirebooter3081959569955579351.jar])
azidcontainerjava_1  |          at com.sun.jna.Native.extractFromResourcePath(Native.java:1095)
azidcontainerjava_1  |          at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:276)
azidcontainerjava_1  |          ... 68 more
azidcontainerjava_1  | [reactor-http-epoll-1] WARN reactor.netty.channel.FluxReceive - [id: 0x4b9aa9dd, L:/172.19.0.2:58396 ! R:jongkv.vault.azure.net/13.66.226.249:443] An exception has been observed post termination, use DEBUG level to see the full stack: java.lang.UnsatisfiedLinkError: Unable to load library 'libsecret-1':
azidcontainerjava_1  | liblibsecret-1.so: cannot open shared object file: No such file or directory
azidcontainerjava_1  | liblibsecret-1.so: cannot open shared object file: No such file or directory
azidcontainerjava_1  | Native library (linux-x86-64/liblibsecret-1.so) not found in resource path ([file:/usr/app/target/surefire/surefirebooter3081959569955579351.jar])
```
