### ISSUE TITLE
DataLakeServiceClient:listFileSystems API hangs on HDI 3.6 with Spark 2.3.0 [BUG]

### ISSUE THREAD

**Issue by hywang203** [Azure/azure-sdk-for-java#11698]
**Describe the bug**
DataLakeServiceClient:listFileSystems API hangs

***Exception or Stack Trace***
java.lang.NoSuchMethodError: io.netty.handler.ssl.SslProvider.isAlpnSupported(Lio/netty/handler/ssl/SslProvider;)Z
	at reactor.netty.http.client.HttpClientSecure.<clinit>(HttpClientSecure.java:79)
	at reactor.netty.http.client.HttpClientConnect$MonoHttpConnect.lambda$subscribe$0(HttpClientConnect.java:298)
	at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:57)
	at reactor.core.publisher.FluxRetryPredicate$RetryPredicateSubscriber.resubscribe(FluxRetryPredicate.java:124)
	at reactor.core.publisher.MonoRetryPredicate.subscribeOrReturn(MonoRetryPredicate.java:51)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:48)
	at reactor.netty.http.client.HttpClientConnect$MonoHttpConnect.subscribe(HttpClientConnect.java:323)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:55)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:55)
	at reactor.core.publisher.MonoDelaySubscription.accept(MonoDelaySubscription.java:52)
	at reactor.core.publisher.MonoDelaySubscription.accept(MonoDelaySubscription.java:33)
	at reactor.core.publisher.FluxDelaySubscription$DelaySubscriptionOtherSubscriber.onNext(FluxDelaySubscription.java:123)
	at reactor.core.publisher.MonoDelay$MonoDelayRunnable.run(MonoDelay.java:117)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**To Reproduce**

***Code Snippet***

```
// Scala code
 val sc = SparkContext.getOrCreate()

    val spark = SparkSession.builder().getOrCreate()
    println(spark.sparkContext.startTime)

    println("main")

    val sasToken = "sasToken"
    val client = new DataLakeServiceClientBuilder().endpoint("https://ADLSg2Account.dfs.core.windows.net/")
      .sasToken(sasToken).buildClient()

    //val getName = ((f:FileSystem) => f.getName()).asJava
    //client.listFileSystems().(((f:FileSystemItem) => println(f.getName())).asJava)
    import scala.collection.JavaConverters._
    var filenames = new ListBuffer[String]()
    for (f : FileSystemItem <- client.listFileSystems().asScala){
      val fName = f.getName()
      println(fName)
      filenames+=fName
    }
    sc.parallelize(filenames).saveAsTextFile("abfs://data@ADLSg2Account.dfs.core.windows.net/code/TLC-0423")
```

**Expected behavior**
List containers without exception

**Screenshots**

**Setup (please complete the following information):**
HDInsight 3.6 with Spark 2.3.0

**Additional context**
My guess is that it's a dependency conflict, so I made a shaded jar. But the issue persists.
This is my pom:

```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.microsoft.<internalProjectName></groupId>
  <artifactId>com.microsoft.<internalProjectName></artifactId>
  <version>1.0-SNAPSHOT</version>
  <properties>
    <spark.version>2.3.2</spark.version>
    <scala.version.major>2.11</scala.version.major>
    <scala.version.minor>8</scala.version.minor>
    <scala.version>${scala.version.major}.${scala.version.minor}</scala.version>
  </properties>

  <dependencies>
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-core</artifactId>
      <version>2.10.1</version>
    </dependency>
    <dependency>
      <groupId>com.azure</groupId>
      <artifactId>azure-storage-file-datalake</artifactId>
      <version>12.1.0</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>io.netty</groupId>
      <artifactId>netty-handler</artifactId>
      <version>4.1.45.Final</version>
    </dependency>
    <dependency>
      <groupId>io.netty</groupId>
      <artifactId>netty-handler-proxy</artifactId>
      <version>4.1.45.Final</version>
    </dependency>
    <dependency>
      <groupId>io.projectreactor.netty</groupId>
      <artifactId>reactor-netty</artifactId>
      <version>0.9.5.RELEASE</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.scala-lang</groupId>
      <artifactId>scala-library</artifactId>
      <version>${scala.version}</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.scalatest</groupId>
      <artifactId>scalatest_2.11</artifactId>
      <version>3.0.0</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.specs</groupId>
      <artifactId>specs</artifactId>
      <version>1.2.5</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.apache.spark</groupId>
      <artifactId>spark-core_${scala.version.major}</artifactId>
      <version>${spark.version}</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.apache.spark</groupId>
      <artifactId>spark-sql_${scala.version.major}</artifactId>
      <version>${spark.version}</version>
      <scope>provided</scope>
    </dependency>
  </dependencies>

  <build>
    <directory>mvn</directory>
    <outputDirectory>${project.build.directory}/classes</outputDirectory>
    <plugins>
      <plugin>
        <artifactId>maven-assembly-plugin</artifactId>
        <executions>
          <execution>
            <phase>package</phase>
            <goals>
              <goal>single</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <descriptorRefs>
            <descriptorRef>jar-with-dependencies</descriptorRef>
          </descriptorRefs>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-shade-plugin</artifactId>
        <version>3.2.3</version>
        <executions>
          <execution>
            <phase>package</phase>
            <goals>
              <goal>shade</goal>
            </goals>
            <configuration>
              <filters>
                <filter>
                  <artifact>*:*</artifact>
                  <excludes>
                    <exclude>META-INF/*.SF</exclude>
                    <exclude>META-INF/*.DSA</exclude>
                    <exclude>META-INF/*.RSA</exclude>
                  </excludes>
                </filter>
              </filters>
              <minimizeJar>false</minimizeJar>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.2</version>
        <configuration>
          <source>1.8</source>
          <target>1.8</target>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>2.18.1</version>
        <configuration>
          <skipTests>true</skipTests>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.scala-tools</groupId>
        <artifactId>maven-scala-plugin</artifactId>
        <version>2.15.0</version>
        <executions>
          <execution>
            <goals>
              <goal>compile</goal>
              <goal>testCompile</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <scalaVersion>${scala.version}</scalaVersion>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.scalatest</groupId>
        <artifactId>scalatest-maven-plugin</artifactId>
        <version>1.0</version>
        <configuration>
          <reportsDirectory>${project.build.directory}/surefire-reports</reportsDirectory>
          <junitxml>.</junitxml>
          <filereports>TestSuite.txt</filereports>
          <forkMode>once</forkMode>
          <environmentVariables>
            <PATH>${env.PATH};${env.JAVA_HOME}/bin</PATH>
          </environmentVariables>
        </configuration>
        <executions>
          <execution>
            <id>test</id>
            <goals>
              <goal>test</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
  <reporting>
    <plugins>
      <plugin>
        <groupId>org.scala-tools</groupId>
        <artifactId>maven-scala-plugin</artifactId>
        <configuration>
          <scalaVersion>${scala.version}</scalaVersion>
        </configuration>
      </plugin>

    </plugins>
  </reporting>
</project>

```

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [y ] Bug Description Added
- [y ] Repro Steps Added
- [y] Setup information Added

**Comment by rickle-msft** [comment]
@hywang203 Thank you for opening this issue. 

@anuchandy Any chance this could be a similar issue as to what's happening with Azure Functions? Jar shading hasn't worked there either, right?

**Comment by anuchandy** [comment]
@rickle-msft - today `Function` team just merged a PR that shade dependencies for function runtime i.e. grpc and netty.

@hywang203 - could you make sure relocation of netty is done as part of shading?

**Comment by hywang203** [comment]
@anuchandy as far as I understand, relocation happens as long as I don't exclude it. Is that not the case? I did not specify relocation for netty.

**Comment by anuchandy** [comment]
Rick and I synced with Haoyuan in teams, this conflict-issue is now resolved with shading.

**Comment by hywang203** [comment]
Need to explicitly add class relocation config during shading, example:
```
              <relocations>
                <relocation>
                  <pattern>io.netty</pattern>
                  <shadedPattern><whatever prefix>.io.netty</shadedPattern>
                </relocation>
              </relocations>
```

**Comment by NabarunDey** [comment]
Hi @hywang203 I am facing the same issue while running my jar on Azure Databricks (All Cluster Versions). Although my code is working in my local environment. Dis you find any solution for this?

**Comment by hywang203** [comment]
@NabarunDey  sorry, I don't check my github messages very often. But I think it is applicable to you as well. It's not really overridden, but more of renaming to avoid class conflict. It should work.
