### ISSUE TITLE
[BUG] BlobContainerClient.exists call fails with NullPointerException

### ISSUE THREAD

**Issue by vanuatoo** [Azure/azure-sdk-for-java#11815]
I have Java EE application which connects to Azure Storage Emulator running on localhost.
The code does not have problem connecting to the server and creating the container.
But if I call exists method to check whether container exists or not it throws the exception

```...
Caused by: java.lang.NullPointerException
        at com.azure.storage.blob.BlobContainerAsyncClient.lambda$getPropertiesWithResponse$8(BlobContainerAsyncClient.java:444)
        at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:107)
        at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1755)
        at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:241)
        at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1755)
        at reactor.core.publisher.MonoIgnoreThen$ThenAcceptInner.onNext(MonoIgnoreThen.java:296)
        at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:67)
        at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114)
        at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1755)
        at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.signalCached(MonoCacheTime.java:320)
        at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.onNext(MonoCacheTime.java:337)
        at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:73)
        at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1755)
        at reactor.core.publisher.MonoCallable.subscribe(MonoCallable.java:61)
        at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
        at reactor.core.publisher.MonoCacheTime.subscribeOrReturn(MonoCacheTime.java:132)
        at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
        at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.drain(MonoIgnoreThen.java:153)
        at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.ignoreDone(MonoIgnoreThen.java:190)
        at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreInner.onComplete(MonoIgnoreThen.java:240)
        at reactor.core.publisher.MonoIgnoreElements$IgnoreElementsSubscriber.onComplete(MonoIgnoreElements.java:81)
        at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:136)
        at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onComplete(FluxDoFinally.java:138)
        at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:136)
        at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:366)
        at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:367)
        at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:423)
        at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:607)
        at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:96)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
        Suppressed: java.lang.Exception: #block terminated with an error
                at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
                at reactor.core.publisher.Mono.block(Mono.java:1678)
                at com.azure.storage.common.implementation.StorageImplUtils.blockWithOptionalTimeout(StorageImplUtils.java:99)
                at com.azure.storage.blob.BlobContainerClient.existsWithResponse(BlobContainerClient.java:195)
                at com.azure.storage.blob.BlobContainerClient.exists(BlobContainerClient.java:179)
...
```

**To Reproduce**
1. Install Azure Storage Emulator
2. Create a Java EE 8 project with maven dependency
```
<dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-storage-blob</artifactId>
            <version>12.6.1</version>
</dependency>
```

***Code Snippet***
```java
blobServiceClient = new BlobServiceClientBuilder().connectionString("UseDevelopmentStorage=true").buildClient();

        BlobContainerClient blobContainerClient = blobServiceClient.getBlobContainerClient("mydir");
        if (!blobContainerClient.exists()) {
            blobServiceClient.createBlobContainer("mydir");
        }
```

**Expected behavior**
I expect the method to return true or false

**Setup (please complete the following information):**
 - OS: Windows 10
 - IDE : NetBeans
 - Version of the Library used: 12.6.1

**Additional context**
Java EE Server: WildFly 18.0.1
JDK: AdoptOpenJDK 1.8.0_252-b09

**Comment by gapra-msft** [comment]
Thank you @vanuatoo for reporting this issue. I'll work on reproducing this issue and get back to you as soon as I can.

**Comment by zycrophat** [comment]
I'm encountering the same problem when using version 12.7.0 of the library together with Storage Emulator 5.10.0.0. However, the exception only seems to occur, when the blob container exists when the exists() method is called. Otherwise the method correctly returns false.

I've also tried Azurite (latest docker image) instead of Storage Emulator. No problems there.

**Comment by javenes** [comment]
This NuGet https://www.nuget.org/packages/Azure.Storage.Blobs/12.4.4 
also fails with: 
1) LinqPad 5.41
2) Visual Studio 2019 v16.6.0  Target .Net Framework 4.7.2

```
BlobContainerClient blobContainer = new BlobContainerClient(cs, blobContainerName);
var ret = blobContainer.Exists();
```

Returns True if container Exist, 
but NullReferenceException if container not Exists.

**Comment by rickle-msft** [comment]
@gapra-msft Did we have any success in reproducing this issue?

**Comment by gapra-msft** [comment]
Hi @vanuatoo Sorry for the delay. We have fixed the issue and it should be available in our next release.
