### ISSUE TITLE
Smoke Tests found error with Key Vault tests on Azure Stack

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-java#11830]
Error creating a secret (might be related to Identity because we're using AAD auth): 

```
[com.azure.App.main()] INFO com.azure.KeyVaultSecrets - Setting a secret...
[com.azure.App.main()] INFO com.azure.security.keyvault.secrets.SecretAsyncClient - Setting secret - MySecretName-e7bb686d-4bde-4102-b1c6-83facefa2d02
[ForkJoinPool.commonPool-worker-3] ERROR com.microsoft.aad.msal4j.ConfidentialClientApplication - [Correlation ID: c7e922bf-32ae-4ca7-956e-fa8229a8b06a] Execution of class com.microsoft.aad.msal4j.AcquireTokenSilentSupplier failed.
com.microsoft.aad.msal4j.MsalServiceException: AADSTS50049: Unknown or invalid instance.
Trace ID: b5998dff-e93a-45cf-b283-3055a0b84d00
Correlation ID: c7e922bf-32ae-4ca7-956e-fa8229a8b06a
Timestamp: 2020-06-05 18:32:57Z
        at com.microsoft.aad.msal4j.AadInstanceDiscoveryProvider.validate(AadInstanceDiscoveryProvider.java:142)
        at com.microsoft.aad.msal4j.AadInstanceDiscoveryProvider.doInstanceDiscoveryAndCache(AadInstanceDiscoveryProvider.java:134)
        at com.microsoft.aad.msal4j.AadInstanceDiscoveryProvider.getMetadataEntry(AadInstanceDiscoveryProvider.java:42)
        at com.microsoft.aad.msal4j.AuthenticationResultSupplier.getAuthorityWithPrefNetworkHost(AuthenticationResultSupplier.java:32)
        at com.microsoft.aad.msal4j.AcquireTokenSilentSupplier.execute(AcquireTokenSilentSupplier.java:21)
        at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:59)
        at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:17)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
[reactor-http-nio-4] WARN com.azure.security.keyvault.secrets.SecretAsyncClient - Failed to set secret - MySecretName-e7bb686d-4bde-4102-b1c6-83facefa2d02
Status code 400, "{"error":{"code":"BadParameter","message":"The specified version (7.1-preview) is not recognized. Consider using the latest supported version (2016-10-01)."}}"
```

Work with @danieljurek to set up repro credentials once this is assigned. Updated smoke test code in: https://github.com/Azure/azure-sdk-for-java/tree/djurek/smoke-stack

**Comment by joshfree** [comment]
This is on our backlog for the 2nd half of this year.

/cc @schaabs @jianghaolu

**Comment by g2vinay** [comment]
This error should be resolved now.
