### ISSUE TITLE
[BUG] InteractiveBrowserCredential will keep running

### ISSUE THREAD

**Issue by xccc-msft** [Azure/azure-sdk-for-java#12273]
**Describe the bug**
The detailed description could be found [here](https://github.com/Azure/azure-libraries-for-java/issues/1221).

***Exception or Stack Trace***
"browser-1" #15 prio=5 os_prio=0 tid=0x0000000027472800 nid=0x4c84 waiting on condition [0x000000002c96e000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0000000716dc2d20> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1081)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**To Reproduce**
Authenticate by InteractiveBrowserCredential

***Code Snippet***
We have code snippet in shared description above.

**Expected behavior**
It should stop running after completing the auth step.

**Screenshots**

**Setup (please complete the following information):**
 - OS: Windows
 - IDE : IntelliJ
 - Version of the Library used: beta.5
 - JDK: 1.8

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by g2vinay** [comment]
@xccc-msft 
I am using the latest identity release and not able to reproduce this issue.
Can you try out the latest release and see if the issue still persists:
```java
<dependency>
  <groupId>com.azure</groupId>
  <artifactId>azure-identity</artifactId>
  <version>1.2.5</version>
</dependency>
```

Let us know if you still need any further assistance on it.
