### ISSUE TITLE
KeyVaultErrorException when trying to retrieve a secret.

### ISSUE THREAD

**Issue by devszr** [Azure/azure-sdk-for-java#1256]
I'm using UserTokenCredentials and trying to retrieve a secret from a Key Vault. I keep getting an exception and not really sure why. I could get the sources and step through the code to see what might be going on, but, thought of first checking if anyone else has seen this before.

Note that, I'm able to use the same UserTokenCredentials object and list the Key Vaults in my subscription. The exception below gets thrown when I call 
KeyVaultClient.getSecret(VAULT_URL, SECRET_NAME). I'm using version 1.0.0-beta3 of the azure-keyvault library.

```
com.microsoft.azure.keyvault.models.KeyVaultErrorException: 
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.microsoft.rest.ServiceResponseBuilder.build(ServiceResponseBuilder.java:148)
	at com.microsoft.azure.keyvault.KeyVaultClientImpl.getSecretDelegate(KeyVaultClientImpl.java:3023)
	at com.microsoft.azure.keyvault.KeyVaultClientImpl.access$1800(KeyVaultClientImpl.java:94)
```

/Dev

**Comment by devszr** [comment]
Made some progress. I was able to get around this problem by extending KeyValueCredentials and acquiring a token user user credentials in the doAuthenticate implementation.

**Comment by martinsawicki** [comment]
the KeyVault client library is not in this repo anymore, so if this is still an issue, it should go there:
https://github.com/azure/azure-keyvault-java
