### ISSUE TITLE
onErrorContinue is called twice when CosmosException ( Eg 404) occurs

### ISSUE THREAD

**Issue by anandsugumaran** [Azure/azure-sdk-for-java#12809]
I am  trying to run the below code. mylist is having 2 object and one of the object is not present in DB.

    Flux.fromIterable(mylist).flatMap(data-> {
      Mono<CosmosItemResponse<MyData>> asyncItemResponseMono = client.readItem(data.id,data.pkey, MyData.class);
      return asyncItemResponseMono;
    }).onErrorContinue((e, i) -> {
      logCosmosError(e);// Log the exception
    }).doOnNext(itemResponse -> {
        logCosmosMetrics(itemResponse);    //Log the metrics
    }).subscribe();

When Cosmos throws 404 for element which is not in DB, my method prints the error message correctly like below

2020-07-05 11:03:19.999 ERROR 20183 --- [or-http-epoll-2] c.n.s.database.abcd: Cosmos error with details **Entity with the specified id does not exist in the system**., 

But after this, we are seeing the below stacktrace as well

2020-07-05 11:03:19.999 ERROR 20183 --- [or-http-epoll-2] c.a.c.i.RxGatewayStoreModel              : Network failure

java.util.NoSuchElementException: Source was empty
	at reactor.core.publisher.MonoSingle$SingleSubscriber.onComplete(MonoSingle.java:165) ~[reactor-core-3.3.6.RELEASE.jar:3.3.6.RELEASE]

And then onErrorContinue is called again and while we are printing the message, we see the exception as null

2020-07-05 11:03:20.000 ERROR 20183 --- [or-http-epoll-2] c.n.s.database.abcd: Cosmos error with details **null**

Can someone help here to understand why onErrorContinue is called twice when CosmosException occurs.

**Comment by kushagraThapar** [comment]
@anandsugumaran - can you enable debug logs and please paste the complete stack trace ?
The way to enable debug logs is listed here : https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/cosmos/azure-cosmos#enable-client-logging

**Comment by anandsugumaran** [comment]
Hey Kushagra, PFB the DEBUG logs

2020-07-12 05:39:05.932 DEBUG 31050 --- [nio-8080-exec-1] c.a.c.i.RxDocumentClientImpl             : Reading a Document. documentLink: [/dbs/xxxx/colls/xxxx/docs/987D9D0A379BEA8799F66B844EE5009370EE00E499B3BB4C5D79604E34705C9F]
2020-07-12 05:39:05.942 DEBUG 31050 --- [nio-8080-exec-1] c.a.c.implementation.caches.AsyncCache   : cache[dbs/xxxx/colls/xxxx] doesn't exist, computing new value
2020-07-12 05:39:05.944 DEBUG 31050 --- [nio-8080-exec-1] c.a.c.implementation.caches.AsyncLazy    : constructor
2020-07-12 05:39:05.949 DEBUG 31050 --- [nio-8080-exec-1] c.a.c.implementation.caches.AsyncLazy    : using Function<Mono<TValue>> com.azure.cosmos.implementation.caches.RxCollectionCache$$Lambda$888/77697127@68a3501b
2020-07-12 05:39:07.500 DEBUG 31050 --- [or-http-epoll-3] c.a.c.implementation.caches.AsyncCache   : set cache[U7N-AMLYxTE=]={"id":"dev_rrs2","indexingPolicy":{"indexingMode":"consistent","automatic":true,"includedPaths":[{"path":"/*"}],"excludedPaths":[{"path":"/\"_etag\"/?"}]},"partitionKey":{"paths":["/pkey"],"kind":"Hash"},"defaultTtl":15768000,"uniqueKeyPolicy":{"uniqueKeys":[]},"conflictResolutionPolicy":{"mode":"LastWriterWins","conflictResolutionPath":"/_ts","conflictResolutionProcedure":""},"geospatialConfig":{"type":"Geography"},"_rid":"U7N-AMLYxTE=","_ts":1591870911,"_self":"dbs/U7N-AA==/colls/U7N-AMLYxTE=/","_etag":"\"00000a00-0000-0100-0000-5ee205bf0000\"","_docs":"docs/","_sprocs":"sprocs/","_triggers":"triggers/","_udfs":"udfs/","_conflicts":"conflicts/"}
2020-07-12 05:39:08.846 ERROR 31050 --- [or-http-epoll-3] c.n.s.d.ShastaCosmosAsyncReactorDatabase : Cosmos error in getAllReputation with details Entity with the specified id does not exist in the system., 
RequestStartTime: 2020-07-12T05:39:08.7550525Z, RequestEndTime: 2020-07-12T05:39:08.7750218Z,  Number of regions attempted:1
ResponseTime: 2020-07-12T05:39:08.7750218Z, StoreResult: StorePhysicalAddress: rntbd://cdb-ms-prod-eastus1-fd25.documents.azure.com:14387/apps/a04b47e5-fda2-42d3-8618-c1c07375b03c/services/78437eb2-bb1a-41e7-9794-99c478425bfa/partitions/cc91d841-9093-40a9-8e3a-c16a05d5ee14/replicas/132384375699834544s/, LSN: 295, GlobalCommittedLsn: 294, PartitionKeyRangeId: 0, IsValid: True, StatusCode: 404, SubStatusCode: 0, RequestCharge: 1, ItemLSN: -1, SessionToken: -1#295, UsingLocalLSN: True, TransportException: null, ResourceType: Document, OperationType: Read
, Microsoft.Azure.Documents.Common/2.11.0, StatusCode: NotFound
2020-07-12 05:39:08.894 ERROR 31050 --- [or-http-epoll-3] c.a.c.i.RxGatewayStoreModel              : Network failure

java.util.NoSuchElementException: Source was empty
	at reactor.core.publisher.MonoSingle$SingleSubscriber.onComplete(MonoSingle.java:165) ~[reactor-core-3.3.6.RELEASE.jar:3.3.6.RELEASE]
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:136) ~[reactor-core-3.3.6.RELEASE.jar:3.3.6.RELEASE]
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FluxSwitchIfEmpty.java:78) ~[reactor-core-3.3.6.RELEASE.jar:3.3.6.RELEASE]
	at reactor.core.publisher.FluxHandle$HandleSubscriber.onComplete(FluxHandle.java:206) ~[reactor-core-3.3.6.RELEASE.jar:3.3.6.RELEASE]
	at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onComplete(FluxMap.java:262) ~[reactor-core-3.3.6.RELEASE.jar:3.3.6.RELEASE]
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onComplete(FluxDoFinally.java:138) ~[reactor-core-3.3.6.RELEASE.jar:3.3.6.RELEASE]
	at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onComplete(FluxHandleFuseable.java:223) ~[reactor-core-3.3.6.RELEASE.jar:3.3.6.RELEASE]
	at reactor.core.publisher.FluxContextStart$ContextStartSubscriber.onComplete(FluxContextStart.java:115) ~[reactor-core-3.3.6.RELEASE.jar:3.3.6.RELEASE]
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1783) ~[reactor-core-3.3.6.RELEASE.jar:3.3.6.RELEASE]
	at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:121) ~[reactor-core-3.3.6.RELEASE.jar:3.3.6.RELEASE]
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:252) ~[reactor-core-3.3.6.RELEASE.jar:3.3.6.RELEASE]
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:136) ~[reactor-core-3.3.6.RELEASE.jar:3.3.6.RELEASE]
	at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:365) ~[reactor-netty-0.9.8.RELEASE.jar:0.9.8.RELEASE]
	at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:368) ~[reactor-netty-0.9.8.RELEASE.jar:0.9.8.RELEASE]
	at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:424) ~[reactor-netty-0.9.8.RELEASE.jar:0.9.8.RELEASE]
	at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:613) ~[reactor-netty-0.9.8.RELEASE.jar:0.9.8.RELEASE]
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:96) ~[reactor-netty-0.9.8.RELEASE.jar:0.9.8.RELEASE]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) ~[netty-transport-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[netty-codec-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[netty-codec-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) ~[netty-transport-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1518) ~[netty-handler-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1279) ~[netty-handler-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1316) ~[netty-handler-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501) ~[netty-codec-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440) ~[netty-codec-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[netty-codec-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792) ~[netty-transport-native-epoll-4.1.50.Final-linux-x86_64.jar:4.1.50.Final]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475) ~[netty-transport-native-epoll-4.1.50.Final-linux-x86_64.jar:4.1.50.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[netty-transport-native-epoll-4.1.50.Final-linux-x86_64.jar:4.1.50.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.50.Final.jar:4.1.50.Final]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_191]

2020-07-12 05:39:08.903 ERROR 31050 --- [or-http-epoll-3] c.n.s.d.ShastaCosmosAsyncReactorDatabase : Cosmos error in getAllReputation with details null

We print the exception details in the logCosmosError method only when this is of exception type CosmosException. We see that second time, it is of type CosmosException but getLocalizedMessage is null while the cause was NoSuchElementException

**Comment by kushagraThapar** [comment]
@anandsugumaran - I investigated this issue and ran some test cases around it. Cosmos SDK only throws one exception. 
The reason you are seeing two exceptions is because the way you are using reactor code. 

In your below example: 

```
Flux.fromIterable(mylist).flatMap(data-> {
  Mono<CosmosItemResponse<MyData>> asyncItemResponseMono = client.readItem(data.id,data.pkey, MyData.class);
  return asyncItemResponseMono;
}).onErrorContinue((e, i) -> {
  logCosmosError(e);// Log the exception
}).doOnNext(itemResponse -> {
    logCosmosMetrics(itemResponse);    //Log the metrics
}).subscribe();
```

You are using onErrorContinue - which is causing the reactor chain to move forward even when there is no element present - which causes the doOnNext call without the actual element, hence the source is empty. 

The recommended way of using this should be like this: 

```

Flux.fromIterable(mylist).flatMap(data-> {
  Mono<CosmosItemResponse<MyData>> asyncItemResponseMono = client.readItem(data.id,data.pkey, MyData.class);
  return asyncItemResponseMono;
}).onErrorResume(throwable -> {
  logger.error("Error occurred while reading item : {}", throwable.getMessage());
  return Mono.error(throwable);
}).doOnNext(item -> {
  logger.info("Item is : {}", item);
}).subscribe();
```

**Comment by anandsugumaran** [comment]
Thanks for the details @kushagraThapar 
But in onErrorResume, the processing gets stopped on error event whereas in my usecase, I want to proceed with other items that might succeed after some error event as well.

Ex, I do 100 write calls and first 60 might pass and next 10 will fail but the rest 30 might pass. If I do onErrorResume, I ll not be able to process the last 30 even if it succeeds.

I basically want to log the errors on failures and move to others.

**Comment by kushagraThapar** [comment]
@anandsugumaran in that case, you can still use `onErrorResume` -> Instead of returning an error, just return empty Flux/Mono. 
```
Flux.fromIterable(mylist).flatMap(data-> {
  Mono<CosmosItemResponse<MyData>> asyncItemResponseMono = client.readItem(data.id,data.pkey, MyData.class);
  return asyncItemResponseMono;
}).onErrorResume(throwable -> {
  logger.error("Error occurred while reading item : {}", throwable.getMessage());
  return Flux.empty();
}).doOnNext(item -> {
  logger.info("Item is : {}", item);
}).subscribe();

```

**Comment by anandsugumaran** [comment]
@kushagraThapar But even if we return an empty flux, the stream does end without processing the rest of the items. Please find below sample to understand our usecase better.

System.out.println("Demo with onErrorResume");
    
    Flux.just(1,2,3,4,5,6,7,8,9,10).map(a -> {
      if (a%2==0) {
        throw new RuntimeException("ERROR");
    }
    return a;
    })
    .doOnNext(item -> {System.out.println("Success for "+item);})
    .onErrorResume(throwable -> {
      System.out.println("OnErrorResume occurred while reading item : "+ throwable.getMessage());
      return Flux.empty();
    })
    .blockLast(); 
    
    System.out.println("Demo with onErrorContinue");
    
    Flux.just(1,2,3,4,5,6,7,8,9,10).map(a -> {
      if (a%2==0) {
        throw new RuntimeException("ERROR");
    }
    return a;
    })
    .doOnNext(item -> {System.out.println("Success for "+item);})
    .onErrorContinue((throwable,item) -> {
      System.out.println("OnErrorContinue occurred while reading item : "+ throwable.getMessage());      
    })
    .subscribe(); 

Output

Demo with onErrorResume

Success for 1
OnErrorResume occurred while reading item : ERROR

Demo with onErrorContinue
Success for 1
OnErrorContinue occurred while reading item : ERROR
Success for 3
OnErrorContinue occurred while reading item : ERROR
Success for 5
OnErrorContinue occurred while reading item : ERROR
Success for 7
OnErrorContinue occurred while reading item : ERROR
Success for 9
OnErrorContinue occurred while reading item : ERROR

We need the same behaviour as onErrorContinue where we process both errors and completed events.

**Comment by kushagraThapar** [comment]
@anandsugumaran - thanks for the example and the explanation, I will investigate the issue further soon.

**Comment by kushagraThapar** [comment]
@anandsugumaran - I found the issue have fixed it, this will be released this week in v4.3.0

**Comment by kushagraThapar** [comment]
This issue is still happening on DIRECT mode.

**Comment by kushagraThapar** [comment]
@anandsugumaran - We investigated this issue in more detail, and found out that `onErrorContinue` operator was messing up with Error handling in the SDK code. 
Since `onErrorContinue` basically intercepts any upstream operator where the error happens, this causes interference with our error handling logic when getting response from the backend - which is a valid case when document is not found. 

So we will not be able to support this operator on Cosmos SDK APIs. 
If you read the description of this operator - https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Flux.html#onErrorContinue-java.util.function.BiConsumer-
you will see that only specific upstream operators support this mode, and unfortunately Cosmos SDK won't support it. 

I think in your case, you could use this operator to delay the error and keep reading / writing other items from your list. 
https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Flux.html#mergeDelayError-int-org.reactivestreams.Publisher...-
Or this one - https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Flux.html#mergeSequentialDelayError-int-org.reactivestreams.Publisher...-

Let me know your thoughts.

**Comment by anandsugumaran** [comment]
@kushagraThapar Thanks for the note. We will take a look on your suggestions. But am not sure how the fix that you made is working with Gateway mode. Can't the same be done with Direct mode ?

**Comment by kushagraThapar** [comment]
@anandsugumaran - We were also able to fix it for DIRECT mode, but we found out yesterday in more debugging that it was just hiding the error and not fixing it properly in both GATEWAY and DIRECT mode. 
Will explain more on the call.
