### ISSUE TITLE
Regenerate Implementation Layer with Interface Scoping Changes

### ISSUE THREAD

**Issue by jspenc4** [Azure/azure-sdk-for-java#12829]
**Query/Question**
how can i solve 
java.security.AccessControlException: access denied ("java.lang.reflect.ReflectPermission" "newProxyInPackage.com.azure.storage.blob.implementation")
     at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
     at java.security.AccessController.checkPermission(AccessController.java:884)
     at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
     at java.lang.reflect.Proxy.checkNewProxyPermission(Proxy.java:770)
     at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:726)
     at com.azure.core.http.rest.RestProxy.create(RestProxy.java:683)
     at com.azure.core.http.rest.RestProxy.create(RestProxy.java:665)
     at com.azure.storage.blob.implementation.ServicesImpl.<init>(ServicesImpl.java:58)
     at com.azure.storage.blob.implementation.AzureBlobStorageImpl.<init>(AzureBlobStorageImpl.java:216)
     at com.azure.storage.blob.implementation.AzureBlobStorageBuilder.build(AzureBlobStorageBuilder.java:93)
     at com.azure.storage.blob.BlobServiceAsyncClient.<init>(BlobServiceAsyncClient.java:110)
     at com.azure.storage.blob.BlobServiceClientBuilder.buildAsyncClient(BlobServiceClientBuilder.java:109)
     at com.azure.storage.blob.BlobServiceClientBuilder.buildClient(BlobServiceClientBuilder.java:82)

***Why is this not a Bug or a feature Request?***
A clear explanation of why is this not a bug or a feature request?

it does seem like a bug to me.  however, hoping i misunderstand.  

my attempts to edit the java.policy file to allow Reflect Permission are failing.
and in any case, my security team will not let me allow it.

**Setup (please complete the following information if applicable):**
 - OS: [e.g. iOS] ios
 - IDE : [e.g. IntelliJ] eclipse or intellij
 - Version of the Library used 12.6
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Query Added
- [x ] Setup information Added

**Comment by alzimmermsft** [comment]
Thank you for submitting this issue @jspenc4, I'll take a look into reproducing it and finding possible solutions when dealing with strict `SecurityManager` configurations.

**Comment by alzimmermsft** [comment]
@YijunXieMS, the AutoRest V4 code generator was updated by @srnagar in the mentioned PR to generate the Swagger interface as public so it doesn't run into this issue anymore. This is a longer term fix that will get resolved as clients regenerate their Swaggers.

**Comment by alzimmermsft** [comment]
Renamed, see #17368 for instructions on resolving this issue.

**Comment by alzimmermsft** [comment]
@rickle-msft @gapra-msft this should be resolved by updating the code generator used.

**Comment by fcofdez** [comment]
Is there any approximate time when this will be tackled? We would like to avoid giving that permission on our security policy.
Thanks!

**Comment by rickle-msft** [comment]
@fcofdez I think the earliest would be in our January release, though I can't say for certain whether it will make it in there. I'll update here as I get more information

**Comment by gapra-msft** [comment]
This will be resolved with this PR https://github.com/Azure/azure-sdk-for-java/pull/18907

**Comment by gapra-msft** [comment]
Hi @fcofdez We recently shipped a beta release of the storage libraries with this fix. Could you please try that out and let me know how it goes?

I believe the version is azure-storage-blob 12.11.0-beta.2 +

**Comment by gapra-msft** [comment]
Closing as the issue was resolved with the latest version of GAd storage libraries
