### ISSUE TITLE
Token not found it the cache[QUERY]

### ISSUE THREAD

**Issue by SherryPan123** [Azure/azure-sdk-for-java#13083]
**Query/Question**
When I authenticate ResourceClient with simple authentication 
https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/management/docs/AUTH.md
I got "Token not found it the cache" exception, the stack is as follows:
```
[ForkJoinPool.commonPool-worker-3] ERROR com.microsoft.aad.msal4j.ConfidentialClientApplication - [Correlation ID: 568500b1-627b-4701-97f0-8b7248c34df4] Execution of class com.microsoft.aad.msal4j.AcquireTokenSilentSupplier failed.
com.microsoft.aad.msal4j.MsalClientException: Token not found it the cache
	at com.microsoft.aad.msal4j.AcquireTokenSilentSupplier.execute(AcquireTokenSilentSupplier.java:58)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:59)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:17)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
14:37:14.353 [ForkJoinPool.commonPool-worker-5] DEBUG reactor.core.publisher.Operators - Duplicate Subscription has been detected
java.lang.IllegalStateException: Spec. Rule 2.12 - Subscriber.onSubscribe MUST NOT be called more than once (based on object equality)
	at reactor.core.Exceptions.duplicateOnSubscribeException(Exceptions.java:181)
	at reactor.core.publisher.Operators.reportSubscriptionSet(Operators.java:1059)
	at reactor.core.publisher.Operators.setOnce(Operators.java:1148)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onSubscribe(MonoFlatMap.java:102)
	at reactor.core.publisher.Operators.reportThrowInSubscribe(Operators.java:201)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:71)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4218)
	at reactor.core.publisher.Mono.block(Mono.java:1677)
	at com.azure.identity.implementation.HttpPipelineAdapter.send(HttpPipelineAdapter.java:59)
	at com.microsoft.aad.msal4j.HttpHelper.executeHttpRequest(HttpHelper.java:33)
	at com.microsoft.aad.msal4j.OAuthHttpRequest.send(OAuthHttpRequest.java:34)
	at com.microsoft.aad.msal4j.TokenRequestExecutor.executeTokenRequest(TokenRequestExecutor.java:35)
	at com.microsoft.aad.msal4j.ClientApplicationBase.acquireTokenCommon(ClientApplicationBase.java:92)
	at com.microsoft.aad.msal4j.AcquireTokenByAuthorizationGrantSupplier.execute(AcquireTokenByAuthorizationGrantSupplier.java:52)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:59)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:17)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

**Setup (please complete the following information if applicable):**
 - OS: Windows
 - IDE : IntelliJ
 - Version of the Library used
```
        <dependency>
            <groupId>com.azure.resourcemanager</groupId>
            <artifactId>azure-resourcemanager-resources</artifactId>
            <version>2.0.0-beta.2</version>
        </dependency>
        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-identity</artifactId>
            <version>1.1.0-beta.5</version>
        </dependency>
        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-core-http-netty</artifactId>
            <version>1.5.2</version>
        </dependency>
```

**Comment by yungezz** [comment]
hi @SherryPan123 the exception could be ignored. It's from MSAL libraries debug info.

**Comment by weidongxu-microsoft** [comment]
azure-identity 1.0.8 will not have this exception print out.
