### ISSUE TITLE
In Beta3, is it possible to set LongRunningOperationRetryTimeout in Azure client?

### ISSUE THREAD

**Issue by DanyangLinda** [Azure/azure-sdk-for-java#1314]
When using beta1, `ResourceManagementClient,` `ComputeManagementClient,` `NetworkManagementClient` and `StorageManagementClient` all provide function `setLongRunningOperationRetryTimeout` to all user to change the socket timeout length. However, in Beta3, I cannot figure out how to change the socket timeout length, and the `Azure` class doesn't provide any similar functions.

When using Beta3, I occasionally ran into Socket timeout exception:

```
java.lang.RuntimeException: java.net.SocketTimeoutException: timeout
	at rx.exceptions.Exceptions.propagate(Exceptions.java:58) ~[rxjava-1.1.8.jar:1.1.8]
	at rx.observables.BlockingObservable.subscribe(BlockingObservable.java:499) ~[rxjava-1.1.8.jar:1.1.8]
	at com.microsoft.azure.management.resources.fluentcore.arm.collection.implementation.GroupableResourcesImpl.delete(GroupableResourcesImpl.java:63) ~[azure-mgmt-resources-1.0.0-beta3.jar:1.0.0-beta3]
```

**Comment by jianghaolu** [comment]
In the latest beta5 you should have `.withConnectionTimeout()` and `.withReadTimeout()`.

**Comment by jianghaolu** [comment]
Assigning myself for `LongRunningOperationRetryTimeout`.

**Comment by martinsawicki** [comment]
available in latest releases of the SDK
