### ISSUE TITLE
Provisioning state "deleting" not covered by ProvisioningState enum

### ISSUE THREAD

**Issue by petergardfjall** [Azure/azure-sdk-for-java#1317]
An Azure VM can be in a `deleting` provisioning state. 

A REST API call that retrieves metadata about a VM being deleted can contain a status similar to:

      "statuses": [
        {
          "code": "ProvisioningState/deleting",
          "level": "Info",
          "displayStatus": "Deleting"
        }

This state is not covered by `com.microsoft.azure.management.batch.ProvisioningState`

```
Caused by: java.lang.IllegalArgumentException: No enum constant com.microsoft.azure.management.batch.ProvisioningState.Deleting
	at java.lang.Enum.valueOf(Enum.java:238) ~[na:1.8.0_111]
	at com.microsoft.azure.management.batch.ProvisioningState.valueOf(ProvisioningState.java:17) ~[azure-mgmt-batch-1.0.0-beta3.jar:1.0.0-beta3]
```

**Comment by petergardfjall** [comment]
Sorry, this was an error on my part.

I used `ProvisioningState.valueOf("Deleting")` when I should have used `ProvisioningState.fromString("Deleting")`.
