### ISSUE TITLE
[Question] EventProcessorClient slow spin up

### ISSUE THREAD

**Issue by the-mod** [Azure/azure-sdk-for-java#13235]
**Query/Question**
I am currently evaluating v5 of the Azure Eventhub SDK. 
I used to run v3 with EventPartitionHost, which went quite well and performed good.

I create my EventProcessorClient like this. Taken from the Samples:

``` java
BlobContainerAsyncClient blobClient = createBlobClient(storageConnectionString, storageContainerName); 

EventProcessorClient processor = new EventProcessorClientBuilder() 
.connectionString(eventHubConnectionString) 
.consumerGroup(consumerGroupName) 
.checkpointStore(new BlobCheckpointStore(blobClient))
.processEventBatch(events -> { 
  logger.debug("Received events on partition {}", events.getPartitionContext().getPartitionId());           
  service.process(events);  
  }, MAX_BATCH_SIZE)  
.processError(context -> {  
  logger.error("received error for {} on Partition {}", NAME,                 
  context.getPartitionContext().getPartitionId(), 
  context.getThrowable()); 
}) 
.processPartitionInitialization(initializationContext -> { 
  logger.info("Opened partition {} on {}",  
  initializationContext.getPartitionContext().getPartitionId(),                   
  initializationContext.getPartitionContext().getEventHubName()); 
}) 
.processPartitionClose(closeContext -> { 
  logger.info("Closed partition {} on {}. Reason: {}",
   closeContext.getPartitionContext().getPartitionId(),
  closeContext.getPartitionContext().getEventHubName(),
  closeContext.getCloseReason()); 
})         
.buildEventProcessorClient();  

processor.start();
```

When I start my application I see in the Logs, the EventProcessorClient takes for every Partition 10 seconds to spin up.
I am connected to two Eventhubs, one with 8 and one with 32 Partitions.
Cause of the 32 Partitions it takes the app over 5 Minutes to spin up listeners to all partitions.

Did I do something wrong here?
5 Minutes is quite a long time, with EPH it was quite faster.

<img width="1044" alt="Bildschirmfoto 2020-07-16 um 15 47 10" src="https://user-images.githubusercontent.com/31224087/87683388-4c1e8a80-c781-11ea-9d89-a7b921880068.png">

**Setup (please complete the following information if applicable):**
 - OS: Win10
 - IDE :  IntelliJ
 - Version of the Library used: azure-messaging-eventhubs 5.1.2 with azure-messaging-eventhubs-checkpointstore-blob
 1.1.2 running together with Spring Boot 2.3.0.RELEASE

**Comment by joshfree** [comment]
@srnagar can you please take a look?

**Comment by srnagar** [comment]
@the-mod Thanks for reaching out. We do have a new feature coming up which is currently in preview that allows you to customize the strategy which speeds up the partition initialization. It also allows you to reduce the interval from 10 seconds to something smaller.

**Comment by the-mod** [comment]
@srnagar Thanks for the quick Answer, I will have a look to the betas you mentioned. Is there a special Reason why it is so time consuming?

**Comment by the-mod** [comment]
@srnagar I included both betas you mentioned and changed my code as follow:

```java
BlobContainerAsyncClient blobClient = createBlobClient(storageConnectionString, storageContainerName); 

EventProcessorClient processor = new EventProcessorClientBuilder() 
.connectionString(eventHubConnectionString) 
.consumerGroup(consumerGroupName) 
.checkpointStore(new BlobCheckpointStore(blobClient))
.loadBalancingUpdateInterval(Duration.ofSeconds(5))
 .partitionOwnershipExpirationInterval(Duration.ofSeconds(5)) 
.loadBalancingStrategy(LoadBalancingStrategy.BALANCED)
.processEventBatch(events -> { 
  logger.debug("Received events on partition {}", events.getPartitionContext().getPartitionId());      
  service.process(events);  
  }, MAX_BATCH_SIZE) 
.processError(context -> {  
  logger.error("received error for {} on Partition {}", NAME,                 
  context.getPartitionContext().getPartitionId(), 
  context.getThrowable()); 
}) 
.processPartitionInitialization(initializationContext -> { 
  logger.info("Opened partition {} on {}",  
  initializationContext.getPartitionContext().getPartitionId(), 
  initializationContext.getPartitionContext().getEventHubName()); 
}) 
.processPartitionClose(closeContext -> { 
  logger.info("Closed partition {} on {}. Reason: {}",
   closeContext.getPartitionContext().getPartitionId(),
  closeContext.getPartitionContext().getEventHubName(),
  closeContext.getCloseReason()); 
})         
.buildEventProcessorClient();  

processor.start();

```


I set the Duration of `LoadBalancingUpdateInterval` and `PartitionOwnershipExpirationInterval` to 5 seconds.
This speeds up the partition initialization.

I did also a test to test the loadBalancing over several Application.
Therefore I set the `LoadBalancingStrategy` to `BALANCED`.
I started  two Instances of my Application to see how the partitions will be shuffel around.

Both App started almost at the same time, but the first one acquired all the Leases.
The second Application got an Error and was not able to get the Ownership of any Partition. 
It tried to claim two Partitions on startup, but after some seconds the following error was thrown (only showing the errors for one partition):

```
[INFO] 2020-07-17T09:25:19,291: reactor-http-nio-2 - com.something.EventHost - Opened partition 21 on eh2-in
...
[ERROR] 2020-07-17T09:25:42,282: boundedElastic-3 - com.something.EventHost - received error for eventhub on Partition 21
com.azure.core.amqp.exception.AmqpException: New receiver 'nil' with higher epoch of '0' is created hence current receiver 'nil' with epoch '0' is getting disconnected. If you are recreating the receiver, make sure a higher epoch is used. TrackingId:<Tracking>, SystemTracker:somename:eventhub:eh2-in~22527|cg, Timestamp:2020-07-17T09:25:33, errorContext[NAMESPACE: somename.servicebus.windows.net, PATH: eh2-in/ConsumerGroups/cg/Partitions/21, REFERENCE_ID: <Reference>, LINK_CREDIT: 0]
        at com.azure.core.amqp.implementation.ExceptionUtil.toException(ExceptionUtil.java:78) ~[azure-core-amqp-1.3.0.jar!/:?]
        at com.azure.core.amqp.implementation.handler.LinkHandler.processOnClose(LinkHandler.java:90) ~[azure-core-amqp-1.3.0.jar!/:?]
        at com.azure.core.amqp.implementation.handler.LinkHandler.handleRemoteLinkClosed(LinkHandler.java:108) ~[azure-core-amqp-1.3.0.jar!/:?]
        at com.azure.core.amqp.implementation.handler.LinkHandler.onLinkRemoteClose(LinkHandler.java:50) ~[azure-core-amqp-1.3.0.jar!/:?]
        at com.azure.core.amqp.implementation.handler.ReceiveLinkHandler.onLinkRemoteClose(ReceiveLinkHandler.java:18) ~[azure-core-amqp-1.3.0.jar!/:?]
        at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:176) ~[proton-j-0.33.4.jar!/:?]
        at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108) ~[proton-j-0.33.4.jar!/:?]
        at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324) ~[proton-j-0.33.4.jar!/:?]
        at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291) ~[proton-j-0.33.4.jar!/:?]
        at com.azure.core.amqp.implementation.ReactorExecutor.run(ReactorExecutor.java:82) ~[azure-core-amqp-1.3.0.jar!/:?]
        at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68) ~[reactor-core-3.3.5.RELEASE.jar!/:3.3.5.RELEASE]
        at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28) ~[reactor-core-3.3.5.RELEASE.jar!/:3.3.5.RELEASE]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:830) [?:?]
[INFO] 2020-07-17T09:25:42,305: boundedElastic-3 - com.something.EventHost - Closed partition 21 on eh2-in. Reason: LOST_PARTITION_OWNERSHIP
```

I let both Apps running for some time, but nothing changed.
Then I killed gracefully App One, but App Two was still not able to acquire Partitions.

So for me it looks like the first started App gets all Partitions, even when they are not initialized by the App.
It will initialize maybe later but steal it from the other app.

Here some logs of a second try.
Watch the Timestamps.
App 2 acquired earlier e.g. Partition 4 on eh1, but App 1 stole it later then.

App 1:
```
[INFO] 2020-07-17T10:21:08,548: main - com.something.Application - Started Application in 15.257 seconds (JVM running for 20.02)
[INFO] 2020-07-17T10:21:10,593: reactor-http-nio-1 - com.something.EventHost - Opened partition 1 on eh1-in
[INFO] 2020-07-17T10:21:10,645: reactor-http-nio-2 - com.something.EventHost - Opened partition 5 on eh2-in
[INFO] 2020-07-17T10:21:14,892: reactor-http-nio-2 - com.something.EventHost - Opened partition 5 on eh1-in
[INFO] 2020-07-17T10:21:15,322: reactor-http-nio-1 - com.something.EventHost - Opened partition 22 on eh2-in
[INFO] 2020-07-17T10:21:20,354: reactor-http-nio-2 - com.something.EventHost - Opened partition 30 on eh2-in
[INFO] 2020-07-17T10:21:24,899: reactor-http-nio-3 - com.something.EventHost - Opened partition 7 on eh1-in
[INFO] 2020-07-17T10:21:25,380: reactor-http-nio-3 - com.something.EventHost - Opened partition 8 on eh2-in
[INFO] 2020-07-17T10:21:30,718: reactor-http-nio-1 - com.something.EventHost - Opened partition 1 on eh2-in
[INFO] 2020-07-17T10:21:35,239: reactor-http-nio-3 - com.something.EventHost - Opened partition 2 on eh1-in
[INFO] 2020-07-17T10:21:35,648: reactor-http-nio-2 - com.something.EventHost - Opened partition 11 on eh2-in
[INFO] 2020-07-17T10:21:40,634: reactor-http-nio-4 - com.something.EventHost - Opened partition 4 on eh2-in
[INFO] 2020-07-17T10:21:45,613: reactor-http-nio-3 - com.something.EventHost - Opened partition 23 on eh2-in
[INFO] 2020-07-17T10:21:55,466: reactor-http-nio-4 - com.something.EventHost - Opened partition 12 on eh2-in
[INFO] 2020-07-17T10:22:00,720: reactor-http-nio-3 - com.something.EventHost - Opened partition 6 on eh2-in
[INFO] 2020-07-17T10:22:10,532: reactor-http-nio-3 - com.something.EventHost - Opened partition 13 on eh2-in
[INFO] 2020-07-17T10:22:20,546: reactor-http-nio-4 - com.something.EventHost - Opened partition 25 on eh2-in
[INFO] 2020-07-17T10:22:35,207: reactor-http-nio-1 - com.something.EventHost - Opened partition 6 on eh1-in
[INFO] 2020-07-17T10:22:35,844: reactor-http-nio-1 - com.something.EventHost - Opened partition 16 on eh2-in
[INFO] 2020-07-17T10:22:45,517: reactor-http-nio-1 - com.something.EventHost - Opened partition 4 on eh1-in
[INFO] 2020-07-17T10:22:50,850: reactor-http-nio-2 - com.something.EventHost - Opened partition 9 on eh2-in
[INFO] 2020-07-17T10:22:55,753: reactor-http-nio-1 - com.something.EventHost - Opened partition 3 on eh1-in
[INFO] 2020-07-17T10:24:13,442: reactor-http-nio-4 - com.something.EventHost - Opened partition 0 on eh2-in
```


App 2:
```
[INFO] 2020-07-17T10:21:34,144: reactor-http-nio-3 - com.something.EventHost - Opened partition 4 on eh1-in
[INFO] 2020-07-17T10:21:34,170: reactor-http-nio-2 - com.something.EventHost - Opened partition 10 on eh2-in
Jul 17, 2020 12:21:36 PM org.apache.coyote.AbstractProtocol stop
INFO: Stopping ProtocolHandler ["http-nio-8080"]
Jul 17, 2020 12:21:36 PM org.apache.coyote.AbstractProtocol destroy
INFO: Destroying ProtocolHandler ["http-nio-8080"]
[ERROR] 2020-07-17T10:22:52,065: boundedElastic-3 - com.something.EventHost - received error for eh1 on Partition 4
com.azure.core.amqp.exception.AmqpException: New receiver 'nil' with higher epoch of '0' is created hence current receiver 'nil' with epoch '0' is getting disconnected. If you are recreating the receiver, make sure a higher epoch is used. TrackingId:<TRACKING>, SystemTracker:<replaced>|cg, Timestamp:2020-07-17T10:22:52, errorContext[NAMESPACE: <NAMESPACE>, PATH: <NAME>/ConsumerGroups/cg/Partitions/4, REFERENCE_ID: <REFERENCE>, LINK_CREDIT: 500]
        at com.azure.core.amqp.implementation.ExceptionUtil.toException(ExceptionUtil.java:78) ~[azure-core-amqp-1.3.0.jar!/:?]
        at com.azure.core.amqp.implementation.handler.LinkHandler.processOnClose(LinkHandler.java:90) ~[azure-core-amqp-1.3.0.jar!/:?]
        at com.azure.core.amqp.implementation.handler.LinkHandler.handleRemoteLinkClosed(LinkHandler.java:108) ~[azure-core-amqp-1.3.0.jar!/:?]
        at com.azure.core.amqp.implementation.handler.LinkHandler.onLinkRemoteClose(LinkHandler.java:50) ~[azure-core-amqp-1.3.0.jar!/:?]
        at com.azure.core.amqp.implementation.handler.ReceiveLinkHandler.onLinkRemoteClose(ReceiveLinkHandler.java:18) ~[azure-core-amqp-1.3.0.jar!/:?]
        at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:176) ~[proton-j-0.33.4.jar!/:?]
        at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108) ~[proton-j-0.33.4.jar!/:?]
        at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324) ~[proton-j-0.33.4.jar!/:?]
        at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291) ~[proton-j-0.33.4.jar!/:?]
        at com.azure.core.amqp.implementation.ReactorExecutor.run(ReactorExecutor.java:82) ~[azure-core-amqp-1.3.0.jar!/:?]
        at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68) ~[reactor-core-3.3.5.RELEASE.jar!/:3.3.5.RELEASE]
        at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28) ~[reactor-core-3.3.5.RELEASE.jar!/:3.3.5.RELEASE]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:830) [?:?]
[INFO] 2020-07-17T10:22:52,082: boundedElastic-3 - com.something.EventHost - Closed partition 4 on eh1. Reason: LOST_PARTITION_OWNERSHIP

**Comment by srnagar** [comment]
@the-mod I think the reason is because your have the partition ownership expiration time set to 5 seconds. So, the ownership expires at the same time as the renewal is expected to happen (every 5 seconds). The `loadBalancingUpdateInterval` is when the load balancing cycle runs and renews partition ownership. `partitionOwnershipExpirationInterval` is how long to wait before a partition's ownership expires if it's not renewed. 

Can you please try setting the expiration time to a longer duration, say 60 seconds?

```java
EventProcessorClient processor = new EventProcessorClientBuilder() 
.connectionString(eventHubConnectionString) 
.consumerGroup(consumerGroupName) 
.checkpointStore(new BlobCheckpointStore(blobClient))
.loadBalancingUpdateInterval(Duration.ofSeconds(5))
 .partitionOwnershipExpirationInterval(Duration.ofSeconds(60)) 
.loadBalancingStrategy(LoadBalancingStrategy.BALANCED)
...      
.buildEventProcessorClient();  
```

**Comment by the-mod** [comment]
@srnagar okay I see. A higher Interval here will do the trick.

So I started one Instance of the App and let it initialize completely.
So all 32 Partitions were owned by this App.
Then I started a second Instance and observed how the Apps will behave.
I did several Runs.

On some Runs I could observe that both Instances were fighting for the Partitions the whole time.
Basically they acquire Partitions and loose them quickly again.
E.g. logs from one Node:

```
[ERROR] 2020-07-20T06:45:05,331: boundedElastic-17 - com.something.EventHost - received error for eh1 on Partition 7
com.azure.core.amqp.exception.AmqpException: New receiver 'nil' with higher epoch of '0' is created hence current receiver 'nil' with epoch '0' is getting disconnected. If you are recreating the receiver, make sure a higher epoch is used. TrackingId:, SystemTracker:eh1|cg, Timestamp:2020-07-20T06:45:05, errorContext[NAMESPACE: eh1.servicebus.windows.net, PATH: eh1/ConsumerGroups/cg/Partitions/7, REFERENCE_ID:, LINK_CREDIT: 499]
        at com.azure.core.amqp.implementation.ExceptionUtil.toException(ExceptionUtil.java:78) ~[azure-core-amqp-1.3.0.jar!/:?]
        at com.azure.core.amqp.implementation.handler.LinkHandler.processOnClose(LinkHandler.java:90) ~[azure-core-amqp-1.3.0.jar!/:?]
        at com.azure.core.amqp.implementation.handler.LinkHandler.handleRemoteLinkClosed(LinkHandler.java:108) ~[azure-core-amqp-1.3.0.jar!/:?]
        at com.azure.core.amqp.implementation.handler.LinkHandler.onLinkRemoteClose(LinkHandler.java:50) ~[azure-core-amqp-1.3.0.jar!/:?]
        at com.azure.core.amqp.implementation.handler.ReceiveLinkHandler.onLinkRemoteClose(ReceiveLinkHandler.java:18) ~[azure-core-amqp-1.3.0.jar!/:?]
        at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:176) ~[proton-j-0.33.4.jar!/:?]
        at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108) ~[proton-j-0.33.4.jar!/:?]
        at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324) ~[proton-j-0.33.4.jar!/:?]
        at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291) ~[proton-j-0.33.4.jar!/:?]
        at com.azure.core.amqp.implementation.ReactorExecutor.run(ReactorExecutor.java:82) ~[azure-core-amqp-1.3.0.jar!/:?]
        at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68) ~[reactor-core-3.3.5.RELEASE.jar!/:3.3.5.RELEASE]
        at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28) ~[reactor-core-3.3.5.RELEASE.jar!/:3.3.5.RELEASE]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:830) [?:?]

[INFO] 2020-07-20T06:45:05,382: boundedElastic-17 - com.something.EventHost - Closed partition 7 on eh1. Reason: LOST_PARTITION_OWNERSHIP

[INFO] 2020-07-20T06:45:18,290: reactor-http-nio-3 - com.something.EventHost - Opened partition 7 on eh1
```

I enabled the Logging for the SDK Stuff via setting `AZURE_LOG_LEVEL=VERBOSE`.
But this is flooding my logs.
Is there a Possibility to get a hook into the Balancing Process or get a notification when it is done?
For me would be interesting to monitor which Node is working on which Partitions.


An other test went fine. So both nodes shared the partition almost equal (15 vs 17 partitions).
When I stoped one Application, the other one was able to acquire them again.

Regarding the Error Log (processError) when a new Receiver toke over:
```
...
received error for eh1 on Partition 7
com.azure.core.amqp.exception.AmqpException: New receiver 'nil' with higher epoch of '0' is created hence current receiver 'nil' with epoch '0' is getting disconnected. If you are recreating the receiver, make sure a higher epoch is used. 
...
```

Is there a way to set here correct values like the id of the receiver and the epoch?

**Comment by srnagar** [comment]
@the-mod The new beta version has a fix for this issue. Could you please try this out?

https://mvnrepository.com/artifact/com.azure/azure-messaging-eventhubs/5.2.0-beta.2
https://mvnrepository.com/artifact/com.azure/azure-messaging-eventhubs-checkpointstore-blob/1.2.0-beta.2

**Comment by srnagar** [comment]
@the-mod The new GA versions are released now.

https://mvnrepository.com/artifact/com.azure/azure-messaging-eventhubs/5.2.0
https://mvnrepository.com/artifact/com.azure/azure-messaging-eventhubs-checkpointstore-blob/1.2.0

**Comment by the-mod** [comment]
@srnagar thx for letting me know. I will check it out

**Comment by AMKovalenko** [comment]
Hello! I faced the same issue with Azure event hubs.

I use:
azure.eventhubs.checkpoint.version -1.10.3
azure.eventhubs.version - 5.10.4

There are a few event hubs, having only one partition for each hub. 
Two consumers for each consumer group.

I got the following error:

2022-05-25 12:00:32.869  WARN c.p.s.c.e.CdcEventErrorHandler   : Error occurred while consuming a message from event-hub 'user', partition '4'.

com.azure.core.amqp.exception.AmqpException: New receiver 'nil' with higher epoch of '0' is created hence current receiver 'nil' with epoch '0' is getting disconnected. If you are recreating the receiver, make sure a higher epoch is used. TrackingId:83d396390001018800008c2f628d9b0a_G14_B9, SystemTracker:***************:eventhub:user~27305|user_consumer_group, Timestamp:2022-05-25T03:00:32, errorContext[NAMESPACE: ***************. ERROR CONTEXT: N/A, PATH: user/ConsumerGroups/user_consumer_group/Partitions/4, REFERENCE_ID: 4_4ad124_1653447434342, LINK_CREDIT: 500]
at com.azure.core.amqp.implementation.ExceptionUtil.toException(ExceptionUtil.java:85)
at com.azure.core.amqp.implementation.handler.LinkHandler.handleRemoteLinkClosed(LinkHandler.java:111)
at com.azure.core.amqp.implementation.handler.LinkHandler.onLinkRemoteCle(LinkHandler.java:59)
at com.azure.core.amqp.implementation.handler.ReceiveLinkHandler.onLinkRemoteClose(ReceiveLinkHandler.java:219)
at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:176)
at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291)
at com.azure.core.amqp.implementation.ReactorExecutor.run(ReactorExecutor.java:91)
at org.springframework.cloud.sleuth.instrument.reactor.ReactorSleuth.lambda$null$6(ReactorSleuth.java:312)
at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)

2022-05-25 12:00:41.959  WARN  c.p.s.c.e.CdcEventErrorHandler   : Error occurred while consuming a message from event-hub 'store', partition '6'.

com.azure.core.amqp.exception.AmqpException: New receiver 'nil' with higher epoch of '0' is created hence current receiver 'nil' with epoch '0' is getting disconnected. If you are recreating the receiver, make sure a higher epoch is used. TrackingId:dd28387a0001018800008c28628d9b09_G5_B9, Timestamp:2022-05-25T03:00:41, errorContext[NAMESPACE: ***************. ERROR CONTEXT: N/A, PATH: store/ConsumerGroups/store_consumer_group/Partitions/6, REFERENCE_ID: 6_c73820_1653447433334, LINK_CREDIT: 500]


@srnagar, could you please help me?
