### ISSUE TITLE
Error while creating new container instance

### ISSUE THREAD

**Issue by Szaraq** [Azure/azure-sdk-for-java#13378]
When I try to create a new container instance, using Azure SDK, I receive one of three results (I cannot see any pattern, it happens randomly):

1. Success and everything is ok (50% cases)
2. "Async operation failed" exception (30% cases)
3. "Resource not found" exception (20% cases)

The strange thing is - in all cases the container is being created successfully and runs properly. So the errors received are just false alarms, but they crashes our application flow. We are using it in Azure Functions, Queue triggered function.

Below the code snippet, that generates the exceptions:
```
Azure.authenticate(new AppServiceMSICredentials(AzureEnvironment.AZURE))
      .withSubscription(AZURE_SUBSCRIPTION_ID)
      .containerGroups()
      .define(engineRunId)
(… defining container properties)
      .createAsync()
      .single()
      .toCompletable()
      .await()
```

And stacktraces for exceptions:

2.
```
Exception: OnErrorThrowable.OnNextValue: OnError while emitting onNext value: com.microsoft.azure.PollingState.class
Stack: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.microsoft.azure.functions.worker.broker.JavaMethodInvokeInfo.invoke(JavaMethodInvokeInfo.java:22)
	at com.microsoft.azure.functions.worker.broker.JavaMethodExecutorImpl.execute(JavaMethodExecutorImpl.java:54)
	at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:53)
	at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:33)
	at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)
	at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:45)
	at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:92)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.microsoft.azure.CloudException: Async operation failed with provisioning state: Canceled
	at com.microsoft.azure.PollingState.throwCloudExceptionIfInFailedState(PollingState.java:543)
	at com.microsoft.azure.AzureClient$5.call(AzureClient.java:203)
	at com.microsoft.azure.AzureClient$5.call(AzureClient.java:200)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.emitScalar(OperatorMerge.java:511)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.tryEmit(OperatorMerge.java:466)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:244)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:148)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.emitScalar(OperatorMerge.java:511)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.tryEmit(OperatorMerge.java:466)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:244)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:148)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
	at retrofit2.adapter.rxjava.CallArbiter.deliverResponse(CallArbiter.java:120)
	at retrofit2.adapter.rxjava.CallArbiter.emitResponse(CallArbiter.java:102)
	at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:46)
	at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:24)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeSingle.call(OnSubscribeSingle.java:81)
	at rx.internal.operators.OnSubscribeSingle.call(OnSubscribeSingle.java:27)
	at rx.internal.operators.SingleToObservable.call(SingleToObservable.java:39)
	at rx.internal.operators.SingleToObservable.call(SingleToObservable.java:27)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.util.ScalarSynchronousObservable$3.call(ScalarSynchronousObservable.java:235)
	at rx.internal.util.ScalarSynchronousObservable$3.call(ScalarSynchronousObservable.java:228)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeRedo$2.call(OnSubscribeRedo.java:273)
	at rx.internal.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.enqueue(TrampolineScheduler.java:73)
	at rx.internal.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.schedule(TrampolineScheduler.java:52)
	at rx.internal.operators.OnSubscribeRedo$5.request(OnSubscribeRedo.java:361)
	at rx.Subscriber.setProducer(Subscriber.java:211)
	at rx.internal.operators.OnSubscribeRedo.call(OnSubscribeRedo.java:353)
	at rx.internal.operators.OnSubscribeRedo.call(OnSubscribeRedo.java:47)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:248)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:148)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
	at rx.internal.producers.SingleProducer.request(SingleProducer.java:65)
	at rx.Subscriber.setProducer(Subscriber.java:211)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102)
	at rx.internal.operators.SingleLiftObservableOperator$WrapSubscriberIntoSingle.onSuccess(SingleLiftObservableOperator.java:76)
	at rx.internal.operators.OnSubscribeSingle$1.onCompleted(OnSubscribeSingle.java:55)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onCompleted(OnSubscribeMap.java:97)
	at retrofit2.adapter.rxjava.CallArbiter.deliverResponse(CallArbiter.java:144)
	at retrofit2.adapter.rxjava.CallArbiter.emitResponse(CallArbiter.java:102)
	at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:46)
	at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:24)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeSingle.call(OnSubscribeSingle.java:81)
	at rx.internal.operators.OnSubscribeSingle.call(OnSubscribeSingle.java:27)
	at rx.internal.operators.SingleToObservable.call(SingleToObservable.java:39)
	at rx.internal.operators.SingleToObservable.call(SingleToObservable.java:27)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.DeferredScalarSubscriber.subscribeTo(DeferredScalarSubscriber.java:153)
	at rx.internal.operators.OnSubscribeTakeLastOne.call(OnSubscribeTakeLastOne.java:32)
	at rx.internal.operators.OnSubscribeTakeLastOne.call(OnSubscribeTakeLastOne.java:22)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	... 3 more
Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: com.microsoft.azure.PollingState.class
	at rx.exceptions.OnErrorThrowable.addValueAsLastCause(OnErrorThrowable.java:118)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:73)
	... 105 more
```

3.
```
com.microsoft.azure.CloudException: The Resource 'Microsoft.ContainerInstance/containerGroups/8bb7ebbe-fcd6-4412-b7eb-befcd614122e' under resource group 'spd2' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix: The Resource 'Microsoft.ContainerInstance/containerGroups/8bb7ebbe-fcd6-4412-b7eb-befcd614122e' under resource group 'spd2' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix 
	at com.microsoft.azure.AzureClient.createExceptionFromResponse(AzureClient.java:771)
	at com.microsoft.azure.AzureClient.access$100(AzureClient.java:33)
	at com.microsoft.azure.AzureClient$25.call(AzureClient.java:747) 
	at com.microsoft.azure.AzureClient$25.call(AzureClient.java:744) 
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
	at retrofit2.adapter.rxjava.CallArbiter.deliverResponse(CallArbiter.java:120) 
	at retrofit2.adapter.rxjava.CallArbiter.emitResponse(CallArbiter.java:102) 
	at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:46) 
	at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:24) 
	at rx.Observable.unsafeSubscribe(Observable.java:10327) 
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48) 
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33) 
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) 
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) 
	at rx.Observable.unsafeSubscribe(Observable.java:10327) 
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48) 
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33) 
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) 
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) 
	at rx.Observable.unsafeSubscribe(Observable.java:10327) 
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:248) 
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:148) 
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77) 
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77) 
	at rx.internal.operators.OperatorMerge$MergeSubscriber.emitScalar(OperatorMerge.java:511) 
	at rx.internal.operators.OperatorMerge$MergeSubscriber.tryEmit(OperatorMerge.java:466) 
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:244) 
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:148) 
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77) 
	at rx.internal.operators.OperatorMerge$MergeSubscriber.emitScalar(OperatorMerge.java:511) 
	at rx.internal.operators.OperatorMerge$MergeSubscriber.tryEmit(OperatorMerge.java:466) 
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:244) 
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:148) 
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77) 
	at retrofit2.adapter.rxjava.CallArbiter.deliverResponse(CallArbiter.java:120) 
	at retrofit2.adapter.rxjava.CallArbiter.emitResponse(CallArbiter.java:102) 
	at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:46) 
	at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:24) 
	at rx.Observable.unsafeSubscribe(Observable.java:10327) 
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48) 
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33) 
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) 
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) 
	at rx.Observable.unsafeSubscribe(Observable.java:10327) 
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48) 
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33) 
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) 
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) 
	at rx.Observable.unsafeSubscribe(Observable.java:10327) 
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48) 
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33) 
	at rx.Observable.unsafeSubscribe(Observable.java:10327) 
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48) 
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33) 
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) 
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) 
	at rx.Observable.unsafeSubscribe(Observable.java:10327) 
	at rx.internal.operators.OnSubscribeSingle.call(OnSubscribeSingle.java:81) 
	at rx.internal.operators.OnSubscribeSingle.call(OnSubscribeSingle.java:27) 
	at rx.internal.operators.SingleToObservable.call(SingleToObservable.java:39) 
	at rx.internal.operators.SingleToObservable.call(SingleToObservable.java:27) 
	at rx.Observable.unsafeSubscribe(Observable.java:10327) 
	at rx.internal.util.ScalarSynchronousObservable$3.call(ScalarSynchronousObservable.java:235) 
	at rx.internal.util.ScalarSynchronousObservable$3.call(ScalarSynchronousObservable.java:228) 
	at rx.Observable.unsafeSubscribe(Observable.java:10327) 
	at rx.internal.operators.OnSubscribeRedo$2.call(OnSubscribeRedo.java:273) 
	at rx.internal.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.enqueue(TrampolineScheduler.java:73) 
	at rx.internal.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.schedule(TrampolineScheduler.java:52) 
	at rx.internal.operators.OnSubscribeRedo$5.request(OnSubscribeRedo.java:361) 
	at rx.Subscriber.setProducer(Subscriber.java:211) 
	at rx.internal.operators.OnSubscribeRedo.call(OnSubscribeRedo.java:353) 
	at rx.internal.operators.OnSubscribeRedo.call(OnSubscribeRedo.java:47) 
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) 
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) 
	at rx.Observable.unsafeSubscribe(Observable.java:10327) 
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:248) 
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:148) 
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77) 
	at rx.internal.producers.SingleProducer.request(SingleProducer.java:65) 
	at rx.Subscriber.setProducer(Subscriber.java:211) 
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102) 
	at rx.internal.operators.SingleLiftObservableOperator$WrapSubscriberIntoSingle.onSuccess(SingleLiftObservableOperator.java:76) 
	at rx.internal.operators.OnSubscribeSingle$1.onCompleted(OnSubscribeSingle.java:55) 
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onCompleted(OnSubscribeMap.java:97) 
	at retrofit2.adapter.rxjava.CallArbiter.deliverResponse(CallArbiter.java:144) 
	at retrofit2.adapter.rxjava.CallArbiter.emitResponse(CallArbiter.java:102) 
	at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:46) 
	at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:24) 
	at rx.Observable.unsafeSubscribe(Observable.java:10327) 
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48) 
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33) 
	at rx.Observable.unsafeSubscribe(Observable.java:10327) 
	at rx.internal.operators.OnSubscribeSingle.call(OnSubscribeSingle.java:81) 
	at rx.internal.operators.OnSubscribeSingle.call(OnSubscribeSingle.java:27) 
	at rx.internal.operators.SingleToObservable.call(SingleToObservable.java:39) 
	at rx.internal.operators.SingleToObservable.call(SingleToObservable.java:27) 
	at rx.Observable.unsafeSubscribe(Observable.java:10327) 
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48) 
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33) 
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) 
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) 
	at rx.Observable.unsafeSubscribe(Observable.java:10327) 
	at rx.internal.operators.DeferredScalarSubscriber.subscribeTo(DeferredScalarSubscriber.java:153) 
	at rx.internal.operators.OnSubscribeTakeLastOne.call(OnSubscribeTakeLastOne.java:32) 
	at rx.internal.operators.OnSubscribeTakeLastOne.call(OnSubscribeTakeLastOne.java:22) 
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) 
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) 
	at rx.Observable.unsafeSubscribe(Observable.java:10327) 
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48) 
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33) 
	at rx.Observable.unsafeSubscribe(Observable.java:10327) 
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48) 
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33) 
	at rx.Observable.unsafeSubscribe(Observable.java:10327) 
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48) 
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33) 
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) 
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) 
	at rx.Observable.unsafeSubscribe(Observable.java:10327) 
	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100) 
	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230) 
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55) 
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) 
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) 
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) 
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) 
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) 
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by rickle-msft** [comment]
Hi, @Szaraq thank you for opening this issue. From the stack traces it looks like you may be using some old versions of the sdk. Would you be able to try upgrading to v12+ and see if that helps resolve the issue?

**Comment by joshfree** [comment]
Potentially related issue https://github.com/Azure/azure-functions-java-worker/issues/381

**Comment by joshfree** [comment]
@anuchandy could you please assist?

**Comment by anuchandy** [comment]
This is track1 management SDK, looks like Fluent SDK for Azure-Containers (based on the usage of `createAsync` API call)

**Comment by anuchandy** [comment]
@weidongxu-microsoft It seems - service is behaving strange here, where a fetch on the Container resource (as part of polling associated with its creation) returns the resource with "ProvisioningState" property as "Cancelled" which from the client side is a failure and converted to an exception. 

Similarly, it also seems sometimes a fetch on the container resource (as part of polling) returns 404, which is also a failure from the client-side.

This should probably a behavior that has to be notified to the service team.

**Comment by Szaraq** [comment]
> This should probably a behavior that has to be notified to the service team.

We have raised a ticket at Azure support, but guys from the Azure containers group advised us to create issue here

**Comment by ChenTanyi** [comment]
```
Caused by: com.microsoft.azure.CloudException: Async operation failed with provisioning state: Canceled
com.microsoft.azure.CloudException: The Resource 'Microsoft.ContainerInstance/containerGroups/8bb7ebbe-fcd6-4412-b7eb-befcd614122e' under resource group 'spd2' was not found.
```

@Szaraq, As for seeing such exception, it seem you have deleted the resource group before the creation complete. Have you done so in your code? These error are all caused by manually change.

**Comment by Szaraq** [comment]
> ```
> Caused by: com.microsoft.azure.CloudException: Async operation failed with provisioning state: Canceled
> com.microsoft.azure.CloudException: The Resource 'Microsoft.ContainerInstance/containerGroups/8bb7ebbe-fcd6-4412-b7eb-befcd614122e' under resource group 'spd2' was not found.
> ```
> 
> @Szaraq, As for seeing such exception, it seem you have deleted the resource group before the creation complete. Have you done so in your code? These error are all caused by manually change.

Hi @ChenTanyi . That's a good question. The manual change is impossible, cause only 2 persons have access to these containers and neither me, nor my collegue removed it manually for sure. We do have a removing logic in our though. Whole process flow looks like that:
-  User triggers Function A, which creates the container (the code, I put in my initial post) and function finishes
- The container runs a script for some time and when it finishes, it puts the message to the queue that it has been finished
- The Function B, which is Queue-triggered function, reads the message from the queue and **removes the container**

In theory Function B can be run before getting response from "create container" Azure REST API. Usually container runs for 10-20 minutes, but it depends on the input data. I just looked into the logs and found that in case of the last "Resource not found" exception, the container ran for 16 seconds. But it would mean, that getting the response from create REST API is much later than creating that in fact. From calling the API to removing the container, we have: provisioning the container, run the script (16 seconds in that case), taking the message from queue by Function B and call remove container API. I would guess it is couple minutes. Is it possible?

**Comment by ChenTanyi** [comment]
@Szaraq It seems the step 2 doesn't relay on the step 1 creation complete. It would cause the problem when the container instance is ready, but step 1 doesn't get the `succeeded` response yet.

The step 1 will check deployment every 30 second until it succeeded. Thus, it may get deployment status after you run step 3. (maybe 16 / 30 ~ 50%)

You'd better do step 3 after the step 1 finish.
Otherwise, you could just use `azure.containerGroups().inner().beginCreateOrUpdate();` if the creation is simple enough. (For new SDK, we will introduce the beginCreate for interface, then it could be more easily to do so.)

**Comment by Szaraq** [comment]
@ChenTanyi the explanation you wrote makes sense, thank you for your help. Do you think, that both exceptions have the same origin?

I would like to try that ```beginCreateOrUpdate()``` method, but I have to configure many different things in that container. This is the whole code snippet:
```
return Azure.authenticate(new AppServiceMSICredentials(AzureEnvironment.AZURE))
      .withSubscription(AZURE_SUBSCRIPTION_ID)
				.containerGroups()
				.define(engineRunId)
				.withRegion(Region.EUROPE_WEST)
				.withExistingResourceGroup(AZURE_RESOURCE_GROUP_NAME)
				.withLinux()
				.withPrivateImageRegistry(
						CONTAINER_IMAGE_REGISTRY_HOST,
						CONTAINER_IMAGE_REGISTRY_USERNAME,
						CONTAINER_IMAGE_REGISTRY_PASSWORD
				)
				.withoutVolume()
				.defineContainerInstance(engineRunId)
				.withImage(CONTAINER_IMAGE_REGISTRY_IMAGE_NAME)
				.withoutPorts()
				.withCpuCoreCount(CONTAINER_CPU_CORE_COUNT)
				.withMemorySizeInGB(CONTAINER_MEMORY_SIZE_IN_GB)
				.withEnvironmentVariables(engineArguments)
				.withEnvironmentVariableWithSecuredValue(engineSecretArguments)
				.attach()
				.withRestartPolicy(ContainerGroupRestartPolicy.NEVER)
				.createAsync();
```
As far as I can see, this method moves the Builder to ```attach()``` stage directly. Do you have any idea how can I use it here?

**Comment by ChenTanyi** [comment]
@Szaraq This is the json of request:
```json
{
	"location": "westeurope",
	"tags": {},
	"properties": {
		"containers": [{
			"name": "container-instance",
			"properties": {
				"image": "CONTAINER_IMAGE_REGISTRY_IMAGE_NAME",
				"environmentVariables": [{
					"name": "environment",
					"value": "value"
				}, {
					"name": "secure-environment",
					"secureValue": "value"
				}],
				"resources": {
					"requests": {
						"memoryInGB": 4.0,
						"cpu": 2.0
					}
				}
			}
		}],
		"imageRegistryCredentials": [{
			"server": "CONTAINER_IMAGE_REGISTRY_HOST",
			"username": "CONTAINER_IMAGE_REGISTRY_USERNAME",
			"password": "CONTAINER_IMAGE_REGISTRY_PASSWORD"
		}],
		"restartPolicy": "Never",
		"osType": "Linux"
	}
}
```

The java code is like:
```java
            ContainerGroupInner containerGroupInner = new ContainerGroupInner()
                    .withContainers(Collections.singletonList(
                            new Container()
                                .withName(engineRunId)
                                .withImage(CONTAINER_IMAGE_REGISTRY_IMAGE_NAME)
                                .withResources(
                                        new ResourceRequirements()
                                            .withRequests(
                                                    new ResourceRequests()
                                                        .withCpu(CONTAINER_CPU_CORE_COUNT)
                                                        .withMemoryInGB(CONTAINER_MEMORY_SIZE_IN_GB)
                                            )
                                )
                                .withEnvironmentVariables(List.of(
                                        new EnvironmentVariable().withName(environmentVariable).withValue(environmentVariableValue),
                                        new EnvironmentVariable().withName(environmentSecretVariable).withSecureValue(environmentSecretVariableValue)
                                ))
                    ))
                    .withImageRegistryCredentials(Collections.singletonList(
                            new ImageRegistryCredential()
                                .withServer(CONTAINER_IMAGE_REGISTRY_HOST)
                                .withUsername(CONTAINER_IMAGE_REGISTRY_USERNAME)
                                .withPassword(CONTAINER_IMAGE_REGISTRY_PASSWORD)
                    ))
                    .withRestartPolicy(ContainerGroupRestartPolicy.NEVER)
                    .withOsType(OperatingSystemTypes.LINUX);
            containerGroupInner.withLocation(Region.EUROPE_WEST.toString());

            azure.containerGroups().inner().beginCreateOrUpdate(resourceGroupName, containerGroupName, containerGroupInner);
```

For beginCreate, its completion doesn't mean the creation is finished, it just send the creation request to API.

**Comment by Szaraq** [comment]
@ChenTanyi Tried your solution and it looks like it solved that issue. Thanks a lot for your help!
