### ISSUE TITLE
[BUG] having trouble connecting to identity client MDS check

### ISSUE THREAD

**Issue by ybjoony** [Azure/azure-sdk-for-java#13391]
**Describe the bug**
Trying to run azure-keyvault-secrets-spring-boot-starter, I run into issues in IMDS client connection

***Exception or Stack Trace***
Caused by: java.net.SocketException: Network is unreachable: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method) ~[?:1.8.0_131]
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85) ~[?:1.8.0_131]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_131]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_131]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_131]
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172) ~[?:1.8.0_131]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_131]
	at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_131]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175) ~[?:1.8.0_131]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463) ~[?:1.8.0_131]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558) ~[?:1.8.0_131]
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242) ~[?:1.8.0_131]
	at sun.net.www.http.HttpClient.New(HttpClient.java:339) ~[?:1.8.0_131]
	at sun.net.www.http.HttpClient.New(HttpClient.java:357) ~[?:1.8.0_131]
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1202) ~[?:1.8.0_131]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138) ~[?:1.8.0_131]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032) ~[?:1.8.0_131]
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:966) ~[?:1.8.0_131]
	at com.azure.identity.implementation.IdentityClient.lambda$checkIMDSAvailable$14(IdentityClient.java:463) ~[azure-identity-1.0.9.jar:?]
	at reactor.core.publisher.MonoCallable.call(MonoCallable.java:91) ~[reactor-core-3.3.6.RELEASE.jar:3.3.6.RELEASE]
	at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:126) ~[reactor-core-3.3.6.RELEASE.jar:3.3.6.RELEASE]

**To Reproduce**
In my case I just ran the application and it threw this error. 

***Code Snippet***
from azure-identity-1.0.9 identityClient.class
private Mono<Boolean> checkIMDSAvailable() {
        StringBuilder payload = new StringBuilder();

        try {
            payload.append("api-version=");
            payload.append(URLEncoder.encode("2018-02-01", "UTF-8"));
        } catch (IOException var3) {
            return Mono.error(var3);
        }

        return Mono.fromCallable(() -> {
            HttpURLConnection connection = null;
            URL url = new URL(String.format("http://169.254.169.254/metadata/identity/oauth2/token?%s", payload.toString()));

            try {
                connection = (HttpURLConnection)url.openConnection();
                connection.setRequestMethod("GET");
                connection.setConnectTimeout(500);
                connection.connect();
            } finally {
                if (connection != null) {
                    connection.disconnect();
                }

            }

            return true;
        });
    }

**Expected behavior**
expect this to pass identity client call since there is nothing from the code that affects this.

**Screenshots**
![image](https://user-images.githubusercontent.com/1686996/88110571-6ccc5300-cb7a-11ea-8750-946c78863634.png)

**Setup (please complete the following information):**
 - OS: Windows 10
 - IDE : Intellij
 - Version of the Library used: spring boot starter 2.3.1, along with these
    <dependency>
      <groupId>com.microsoft.azure</groupId>
      <artifactId>azure-keyvault-secrets-spring-boot-starter</artifactId>
      <version>2.3.1</version>
    </dependency>
    <dependency>
      <groupId>com.azure</groupId>
      <artifactId>azure-identity</artifactId>
      <version>1.0.9</version>
    </dependency>

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by chenrujun** [comment]
Hi, @jianghaolu , please help to check this issue.

Related code: https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/identity/azure-identity/src/main/java/com/azure/identity/implementation/IdentityClient.java#L743

**Comment by joshfree** [comment]
Thanks for reporting this issue in the 1.0.9 package @ybjoony.  @g2vinay could you please take a look for the August sprint?

**Comment by g2vinay** [comment]
@ybjoony 
Thank you for reporting the issue.
This logic runs as part of ManagedIdentityCredential.
If you try to use Managed Identity Credential on non IMDS supported Azure Platforms then you will get this error.

So, where are you running the azure-keyvault-secrets-spring-boot-starter package ?

**Comment by ybjoony** [comment]
as noted above, I have been trying to run that locally in windows with intellij to make sure it works. I would think we should have a way to run this locally then, sounds like this is only runnable in azure platform currently - then how do you test these things?

**Comment by g2vinay** [comment]
> as noted above, I have been trying to run that locally in windows with intellij to make sure it works. I would think we should have a way to run this locally then, sounds like this is only runnable in azure platform currently - then how do you test these things?

@ybjoony 
Correct, IMDS endpoint logic will only work in IMDS supported Azure platforms.
To test the IMDS connection specifically, 
The Managed Identity credential will need to be run in an IMDS supported Azure platform such as an Azure VM.
We normally test these manually in Azure platforms. For IMDS we use a Windows VM.

**Comment by ybjoony** [comment]
hm. so no way to override that to use shared token credential or anything? is this just straight up using ManagedIdentityCredentialBuilder?

**Comment by jianghaolu** [comment]
BTW 1.0.9 version of azure-identity doesn't support authenticating through intelliJ. You will need the latest preview 1.1.0-beta.7 or wait for the stable 1.1.0 coming in August.

**Comment by g2vinay** [comment]
@ybjoony 
If you're looking to just get the spring application to work with the stable identity release: 1.0.9
Then, have you setup your service principal app with required permissions to your KV and passed its details to the spring app with the following configuration described [here](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/spring/azure-spring-boot-starter-keyvault-secrets#custom-settings) in the KV spring boot starter instructions ?

**Comment by g2vinay** [comment]
@ybjoony, let us know if you've any further questions related to this issue or would like to reopen this issue.
Closing this issue.
