### ISSUE TITLE
resource.update().withTags(Tags).apply() hangs

### ISSUE THREAD

**Issue by selvasingh** [Azure/azure-sdk-for-java#1343]
BMC reported ...

We are facing a strange issue with below SDK API. We are using SDK 1.0.0-beta4-SNAPSHOT.

resource.update().withTags(Tags).apply();                                  

When we try to add tags to resource of type “searchResource” using above API, the call never returns and goes in hung state. Whereas the actual action of adding tags takes place and result is visible on Azure portal. This call return after 40 to 60 minutes with below error.

Caused by: java.lang.IllegalStateException: Interrupted while waiting for subscription to complete.
                at rx.internal.util.BlockingUtils.awaitForComplete(BlockingUtils.java:56)
                at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:461)
                at rx.observables.BlockingObservable.last(BlockingObservable.java:227)
                at com.microsoft.azure.management.resources.fluentcore.model.implementation.CreatableUpdatableImpl.apply(CreatableUpdatableImpl.java:178)
                at com.bmc.cloud.provider.azurermconnect.services.impl.AzureTemplateManagerImpl.addTagsToResource(AzureTemplateManagerImpl.java:1045)
                ... 20 more
Caused by: java.lang.InterruptedException
                at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:998)
                at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
                at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
                at rx.internal.util.BlockingUtils.awaitForComplete(BlockingUtils.java:49)
                ... 24 more

We also faced similar issue with below API & sometimes it works fine.
vm.update().withoutDataDisk(diskName).apply(); 

This issue causing failures in our use cases. Can you please help us to resolve this issue.

**Comment by martinsawicki** [comment]
if our collective memory is worth anything, this may have been fixed...
