### ISSUE TITLE
IntegrationTestFailures - ConsistencyTests2 fails on cosmos live integration tests

### ISSUE THREAD

**Issue by kushagraThapar** [Azure/azure-sdk-for-java#13529]
**Describe the bug**
`ConsistencyTests2#validateSessionTokenAsync consistently fails on cosmos live integration tests

***Exception or Stack Trace***
2020-07-25T17:31:31.4801593Z [ERROR] ConsistencyTests2::validateSessionTokenAsync(com.azure.cosmos.implementation.ConsistencyTests2)  Time elapsed: 960.018 s  <<< FAILURE!
2020-07-25T17:31:31.4803427Z org.testng.internal.thread.ThreadTimeoutException: Method com.azure.cosmos.implementation.ConsistencyTests2.validateSessionTokenAsync() didn't finish within the time-out 960000
2020-07-25T17:31:31.4804784Z 	at app//com.azure.cosmos.implementation.ConsistencyTests2.lambda$validateSessionTokenAsync$1(ConsistencyTests2.java:241)
2020-07-25T17:31:31.4805955Z 	at app//com.azure.cosmos.implementation.ConsistencyTests2.validateSessionTokenAsync(ConsistencyTests2.java:266)

**To Reproduce**
Cosmos live integration tests 

**Expected behavior**
Should pass :)

**Comment by kushagraThapar** [comment]
Fixed with : https://github.com/Azure/azure-sdk-for-java/pull/13576
