### ISSUE TITLE
IntegrationTestFailures - GatewayAddressCacheTest fails intermittently on cosmos live CI

### ISSUE THREAD

**Issue by kushagraThapar** [Azure/azure-sdk-for-java#13533]
**Describe the bug**
GatewayAddressCacheTest fails intermittently on cosmos live CI

***Exception or Stack Trace***
2020-07-25T18:45:02.1389162Z [ERROR] GatewayAddressCacheTest::tryGetAddresses_ForMasterPartition_ForceRefresh[Gateway with Session consistency](com.azure.cosmos.implementation.directconnectivity.GatewayAddressCacheTest)  Time elapsed: 0.087 s  <<< FAILURE!
2020-07-25T18:45:02.1398209Z java.lang.AssertionError: 
2020-07-25T18:45:02.1398770Z 
2020-07-25T18:45:02.1399269Z Expecting:
2020-07-25T18:45:02.1401211Z  <https://cdb-ms-prod-eastus2-fd13.documents.azure.com:11602/apps/e53b1549-97df-44b2-8e40-aa7c29dce522/services/8f28869b-4958-4b1b-b31e-81bafc3f1e64/partitions/3b3cf96c-0359-4c40-a4f5-b7d6373faa4a/replicas/132401758025735461p/>
2020-07-25T18:45:02.1402510Z to be equal to:
2020-07-25T18:45:02.1417623Z  <https://cdb-ms-prod-eastus2-fd13.documents.azure.com:11609/apps/e53b1549-97df-44b2-8e40-aa7c29dce522/services/8f28869b-4958-4b1b-b31e-81bafc3f1e64/partitions/3b3cf96c-0359-4c40-a4f5-b7d6373faa4a/replicas/132401730075639411p/>
2020-07-25T18:45:02.1419300Z but was not.
2020-07-25T18:45:02.1435206Z 	at com.azure.cosmos.implementation.directconnectivity.GatewayAddressCacheTest.assertEqual(GatewayAddressCacheTest.java:777)
2020-07-25T18:45:02.1436662Z 	at com.azure.cosmos.implementation.directconnectivity.GatewayAddressCacheTest.assertExactlyEqual(GatewayAddressCacheTest.java:790)
2020-07-25T18:45:02.1437978Z 	at com.azure.cosmos.implementation.directconnectivity.GatewayAddressCacheTest.assertExactlyEqual(GatewayAddressCacheTest.java:784)
2020-07-25T18:45:02.1568658Z 	at com.azure.cosmos.implementation.directconnectivity.GatewayAddressCacheTest.tryGetAddresses_ForMasterPartition_ForceRefresh(GatewayAddressCacheTest.java:560)

**Comment by kushagraThapar** [comment]
Fixed with https://github.com/Azure/azure-sdk-for-java/pull/13576
