### ISSUE TITLE
Beta4: NullPointerException while creating deployment

### ISSUE THREAD

**Issue by dtretyakov** [Azure/azure-sdk-for-java#1362]
After upgrade to beta4 after commits 3c008b79a73e7e41a616d19b9fa3dee8f5e13db0 / 20d734b4d2a74239c1e4e6f86f01fda1a51ebb1c we could not define new deployment due to NPE:

```
java.lang.NullPointerException
	at com.microsoft.azure.management.resources.fluentcore.arm.ResourceId.parseResourceId(ResourceId.java:36)
	at com.microsoft.azure.management.resources.fluentcore.arm.ResourceUtils.groupFromResourceId(ResourceUtils.java:27)
	at com.microsoft.azure.management.resources.implementation.DeploymentImpl.<init>(DeploymentImpl.java:56)
	at com.microsoft.azure.management.resources.implementation.DeploymentsImpl.createFluentModel(DeploymentsImpl.java:111)
	at com.microsoft.azure.management.resources.implementation.DeploymentsImpl.define(DeploymentsImpl.java:102)
	at com.microsoft.azure.management.resources.implementation.DeploymentsImpl.define(DeploymentsImpl.java:27)
```

**Comment by martinsawicki** [comment]
Line 56 of DeploymentImpl.java references the ID in order to extract the group name, regardless of the ID being null. While this logic may look a bit iffy to begin with, this is old code which worked fine. Its unit test is broken now too (`AzureTests.testDeployments()`). 

It looks like previously `ResourceUtils.groupFromResourceId()` returned null as the group name when given a null ID, which would be ok, since the resource group gets set later in the deployment definition anyway. But the refactoring of the resource ID parser (specifically line 27 of ResourceUtils.java) changed this logic - there is no null ID check anymore, so NPE gets hit.

Seeing this, I suspect there may be a number of implementations, especially older ones under ResourceManager, which assume group name from a null resource ID would be null.  Given that a lot of code has been written on the original ID parsing logic, proper null checks should be reinstated here.

I also see that in most of the other ResourceUtils' ID parsing functions, null checks are in place, but besides this one, `resourceProviderFromResourceId()` is also missing it. So I'm guessing it is an accidental omission.

I'm submitting a [PR](https://github.com/Azure/azure-sdk-for-java/pull/1363) for this specific issue as well as `resourceProviderFromResourceId()`. These are very easy fixes. 

This fix will be released in a snapshot build (along with the Networking API version upgrade) that we're preparing for early January.

**Comment by martinsawicki** [comment]
fixed in just released beta4.1
