### ISSUE TITLE
Failed to get subscriptions via proxy with authentication when gateway is down

### ISSUE THREAD

**Issue by MarinaTeper** [Azure/azure-sdk-for-java#13720]
**Describe the bug**
Related to issue : https://github.com/Azure/azure-sdk-for-java/issues/12289 
@jianghaolu  Can you please check the related issue?

When try to get subscriptions by Azure.Authenticated object via proxy that was configured in java System properties, proxy's user and password are not been send to proxy.

Issue partially resolved in case #12289 ,

But still failing when removing gateway , which is going out to internet.
In case I remove authentication from my proxy get subscriptions call success  without gateway as well

***Exception or Stack Trace***
Wrapped by: java.util.concurrent.ExecutionException: java.net.SocketException: Network is unreachable (connect failed)
        at java.util.concurrent.FutureTask.report(Unknown Source)
        at java.util.concurrent.FutureTask.get(Unknown Source)
        at com.microsoft.azure.credentials.ApplicationTokenCredentials.acquireAccessToken(ApplicationTokenCredentials.java:160)
        ... 46 common frames omitted
Wrapped by: java.io.IOException: java.net.SocketException: Network is unreachable (connect failed)
        at com.microsoft.azure.credentials.ApplicationTokenCredentials.acquireAccessToken(ApplicationTokenCredentials.java:174)
        at com.microsoft.azure.credentials.ApplicationTokenCredentials.getToken(ApplicationTokenCredentials.java:139)
        at com.microsoft.azure.credentials.AzureTokenCredentials.getToken(AzureTokenCredentials.java:74)
        at com.microsoft.azure.credentials.AzureTokenCredentialsInterceptor.intercept(AzureTokenCredentialsInterceptor.java:36)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at com.microsoft.azure.management.resources.fluentcore.utils.ResourceManagerThrottlingInterceptor.intercept(ResourceManagerThrottlingInterceptor.java:54)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at com.microsoft.azure.management.resources.fluentcore.utils.ProviderRegistrationInterceptor.intercept(ProviderRegistrationInterceptor.java:40)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at com.microsoft.rest.interceptors.BaseUrlHandler.intercept(BaseUrlHandler.java:43)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at com.microsoft.rest.interceptors.RequestIdHeaderInterceptor.intercept(RequestIdHeaderInterceptor.java:29)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:264)
        at okhttp3.RealCall.execute(RealCall.java:93)
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:188)
        at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:40)
        at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:24)
        at rx.Observable.unsafeSubscribe(Observable.java:10327)
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.Observable.subscribe(Observable.java:10423)
        at rx.Observable.subscribe(Observable.java:10390)
        at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:443)
        ... 14 common frames omitted
Wrapped by: java.lang.RuntimeException: java.io.IOException: java.net.SocketException: Network is unreachable (connect failed)
        at rx.exceptions.Exceptions.propagate(Exceptions.java:57)
        at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:463)
        at rx.observables.BlockingObservable.single(BlockingObservable.java:340)
        at com.microsoft.azure.management.resources.implementation.SubscriptionsInner.list(SubscriptionsInner.java:244)
        at com.microsoft.azure.management.resources.implementation.SubscriptionsImpl.list(SubscriptionsImpl.java:38)
        at com.emc.cloud_dr.cdr.azure_adapter.service.impl.factory.ProxyAzureTest.testAzureCallThroughProxy(ProxyAzureTest.java:58)
        at com.emc.cloud_dr.cdr.azure_adapter.service.impl.factory.ProxyAzureTest.proxyAzureTest(ProxyAzureTest.java:47)

**To Reproduce**
1. create Azure Azure.Authenticated object with withSslSocketFactory as suggested in case 
    https://github.com/Azure/azure-sdk-for-java/issues/12289
2. try to get subscriptions - call succeded
3. Delete gateway that going out to the internet from the machine where java is running(proxy is still reachable and internet is accessible via proxy from this machine, using  "curl -x http://prxyIp:proxyPort  --proxy-user pxuser:prxpass  -I http://google.com" cli command)
4. try to get subscribtions - failing 

***Code Snippet***
ApplicationTokenCredentials credentials = new ApplicationTokenCredentials(clientId, domain, secretKey, AzureEnvironment.AZURE);
        credentials.withSslSocketFactory(new SSLTunnelSocketFactory(host, port, username, password));
        Azure.Authenticated authenticate = Azure.configure().withConnectionTimeout(20, TimeUnit.SECONDS).authenticate(credentials);
        log.debug("authenticate:  " + authenticate.toString());
        PagedList<Subscription> subscriptions = authenticate.subscriptions().list();

**Expected behavior**
connection to proxy should success

**Setup (please complete the following information):**
 - IDE : [e.g. IntelliJ]
 - Version of the Library used

OS: Linux and Windows
IDE : IntelliJ
Version of the Library used: com.microsoft.azure.management:1.33.0

**Comment by joshfree** [comment]
Thanks for filing this issue @MarinaTeper.  Someone from the `Mgmt` team will assist you shortly.  /cc @xccc-msft

**Comment by xccc-msft** [comment]
@jianghaolu Can you please help check this? Thanks.

**Comment by MarinaTeper** [comment]
@jianghaolu  Can you please help

**Comment by MarinaTeper** [comment]
Hello, @jianghaolu  ,we're waiting for reply, can you please help?

**Comment by jianghaolu** [comment]
Hey @MarinaTeper Super sorry for the late reply 😢 

In the currently managed SDKs 2 proxy setups are required - one for authentication, and one for connecting to Resource manager endpoints. You code snippet has handled authentication proxy but you also need proxy configured on the `Azure` instance.

```java
ApplicationTokenCredentials credentials = new ApplicationTokenCredentials(clientId, domain, secretKey, AzureEnvironment.AZURE);
Authenticator proxyAuthenticator = new Authenticator() {
      @Override
      public Request authenticate(Route route, Response response) throws IOException {
             String credential = Credentials.basic(username, password);
             Request request = response.request().newBuilder().header("Proxy-Authorization", credential).build();
             return request;
      }
};
Azure.Authenticated authenticate = Azure.configure()
    .withConnectionTimeout(20, TimeUnit.SECONDS)
    .withProxy(new Proxy(Type.HTTP, new InetSocketAddress(host, port)))
    .withProxyAuthenticator(proxyAuthenticator)
    .authenticate(credentials);
// The next 2 calls must happen after Azure.Authenticated is created. The order is important 
credentials.withProxy(null);
credentials.withSslSocketFactory(new SSLTunnelSocketFactory(host, port, username, password));
PagedList subscriptions = authenticate.subscriptions().list();
```

This is a less than ideal workaround for proxies with authentication. In the next major version of the SDKs you will only need to configure the proxy once.

**Comment by jianghaolu** [comment]
Please verify if this is still an ongoing issue, thanks!
