### ISSUE TITLE
[BUG]Spring starter , server startup issue 

### ISSUE THREAD

**Issue by Abhisar** [Azure/azure-sdk-for-java#13812]
**Describe the bug**
com.azure.data.cosmos.GoneException: The requested resource is no longer available at the server.

***Exception or Stack Trace***
AddressResolutionStatistics{startTime="05 Aug 2020 10:30:27.040", endTime="05 Aug 2020 10:30:28.831", targetEndpoint='https://<url>.documents.azure.com:443/addresses/?$resolveFor=dbs&$filter=protocol%20eq%20rntbd'}

	at com.azure.data.cosmos.BridgeInternal.createCosmosClientException(BridgeInternal.java:346)
	at com.azure.data.cosmos.internal.directconnectivity.GoneAndRetryWithRetryPolicy.shouldRetry(GoneAndRetryWithRetryPolicy.java:88)
	at com.azure.data.cosmos.internal.RetryUtils.lambda$toRetryWithAlternateFunc$4(RetryUtils.java:60)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:88)
	... 84 common frames omitted
Caused by: com.azure.data.cosmos.GoneException: The requested resource is no longer available at the server.
	at com.azure.data.cosmos.internal.directconnectivity.QuorumReader.lambda$waitForReadBarrierAsync$22(QuorumReader.java:518)
	at reactor.core.publisher.FluxDefer.subscribe(FluxDefer.java:46)
	... 59 common frames omitted
**To Reproduce**

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - IDE : [e.g. IntelliJ]
 - Version of the Library used

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by joshfree** [comment]
Thanks for filing this issue, @Abhisar.  Someone from the `azure-spring` team will follow up shortly.

/cc @jialindai

**Comment by zhoufenqin** [comment]
@Abhisar can you provide more details about the issue? like how to reproduce it, version of the library used and so on

**Comment by zhoufenqin** [comment]
closing the issue, duplicate with #13804
