### ISSUE TITLE
cosmosdb threads is not able to kill

### ISSUE THREAD

**Issue by loudywen** [Azure/azure-sdk-for-java#13876]
Scenario (has all CCM setup, has this sample for testing  [https://github.com/sophiaso/spring-cosmosdb-refresh/blob/master/src/main/java/com/example/cosmosdbrefresh/CosmosConfiguration.java](url)  )
steps:
1. update some wrong value for the URL in ccm
   (threads before refresh)
![before](https://user-images.githubusercontent.com/706038/89669797-b076ca80-d8a5-11ea-8e5a-dc349cd62bc7.png)

2. hit the application rest endpoint to trigger refresh
3. application will pick the new URL, refresh the connection and raise exception after some seconds
```
Caused by: reactor.core.Exceptions$ReactiveException: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection timed out: no further information: sql-dev-azure-cosmosdb.documents.azure.com/104.215.113.77:4435
	at reactor.core.Exceptions.propagate(Exceptions.java:336)
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:91)
	at reactor.core.publisher.Mono.block(Mono.java:1663)
	at com.azure.data.cosmos.internal.RxDocumentClientImpl.initializeGatewayConfigurationReader(RxDocumentClientImpl.java:246)
	at com.azure.data.cosmos.internal.RxDocumentClientImpl.init(RxDocumentClientImpl.java:265)
	at com.azure.data.cosmos.internal.AsyncDocumentClient$Builder.build(AsyncDocumentClient.java:185)
	at com.azure.data.cosmos.CosmosClient.<init>(CosmosClient.java:54)
	at com.azure.data.cosmos.CosmosClientBuilder.build(CosmosClientBuilder.java:203)
	at com.microsoft.azure.spring.data.cosmosdb.CosmosDbFactory.getCosmosClient(CosmosDbFactory.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:282)
	at org.springframework.cloud.context.scope.GenericScope$LockedScopedProxyFactoryBean.invoke(GenericScope.java:494)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at com.microsoft.azure.spring.data.cosmosdb.CosmosDbFactory$$EnhancerBySpringCGLIB$$f659ab01.getCosmosClient(<generated>)
	at com.microsoft.azure.spring.data.cosmosdb.core.CosmosTemplate.<init>(CosmosTemplate.java:78)
	at com.walmart.intech.armada.api.DatabaseConfiguration.documentDbTemplate(DatabaseConfiguration.java:52)
	at com.walmart.intech.armada.api.DatabaseConfiguration$$EnhancerBySpringCGLIB$$cb8ee2a6.CGLIB$documentDbTemplate$1(<generated>)
	at com.walmart.intech.armada.api.DatabaseConfiguration$$EnhancerBySpringCGLIB$$cb8ee2a6$$FastClassBySpringCGLIB$$e37f77bc.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363)
	at com.walmart.intech.armada.api.DatabaseConfiguration$$EnhancerBySpringCGLIB$$cb8ee2a6.documentDbTemplate(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 113 common frames omitted
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:93)
		... 141 common frames omitted
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection timed out: no further information: sql-dev-azure-cosmosdb.documents.azure.com/104.215.113.77:4435
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Assembly trace from producer [reactor.core.publisher.MonoCreate] :
	reactor.core.publisher.Mono.create(Mono.java:185)
	reactor.netty.resources.PooledConnectionProvider$PooledConnectionAllocator.connectChannel(PooledConnectionProvider.java:241)
Error has been observed at the following site(s):
	|_        Mono.create ⇢ at reactor.netty.resources.PooledConnectionProvider$PooledConnectionAllocator.connectChannel(PooledConnectionProvider.java:241)
	|_        Mono.create ⇢ at reactor.netty.resources.PooledConnectionProvider.acquire(PooledConnectionProvider.java:135)
	|_        Mono.create ⇢ at reactor.netty.http.client.HttpClientConnect$MonoHttpConnect.subscribe(HttpClientConnect.java:284)
	|_         Mono.retry ⇢ at reactor.netty.http.client.HttpClientConnect$MonoHttpConnect.subscribe(HttpClientConnect.java:321)
	|_   Mono.flatMapMany ⇢ at reactor.netty.http.client.HttpClientFinalizer.responseConnection(HttpClientFinalizer.java:85)
	|_        Flux.single ⇢ at com.azure.data.cosmos.internal.http.ReactorNettyClient.send(ReactorNettyClient.java:106)
	|_       Mono.flatMap ⇢ at com.azure.data.cosmos.internal.directconnectivity.HttpClientUtils.parseResponseAsync(HttpClientUtils.java:19)
	|_           Mono.map ⇢ at com.azure.data.cosmos.internal.directconnectivity.GatewayServiceConfigurationReader.toDatabaseAccountObservable(GatewayServiceConfigurationReader.java:157)
	|_         Mono.error ⇢ at com.azure.data.cosmos.internal.GlobalEndpointManager.lambda$getDatabaseAccountFromAnyLocationsAsync$2(GlobalEndpointManager.java:97)
	|_ Mono.onErrorResume ⇢ at com.azure.data.cosmos.internal.GlobalEndpointManager.getDatabaseAccountFromAnyLocationsAsync(GlobalEndpointManager.java:93)
	|_   Mono.doOnSuccess ⇢ at com.azure.data.cosmos.internal.directconnectivity.GatewayServiceConfigurationReader.initializeReaderAsync(GatewayServiceConfigurationReader.java:142)
Stack trace:
Caused by: java.net.ConnectException: Connection timed out: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:336)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:685)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:632)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:549)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:511)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```
4. at this point new threads are created
![after](https://user-images.githubusercontent.com/706038/89669690-84f3e000-d8a5-11ea-8650-826bab6d5ba2.png)

 now u can see parallel-6 7 8 and cosmos-rntbd-nio-7-* are created and the old parallel-12345 and cosmos-rntbd-nio-2-* still exist. and the parallel-12345 is taking the wrong URL as connection and it will keep trying to connect to the wrong URL after some period in the backend. But the controller is taking the correct URL without issue.

**So, what is the way to kill those old threads before refresh?**

**Comment by joshfree** [comment]
@anuchandy could you please assist?

**Comment by loudywen** [comment]
reference conversation: https://github.com/microsoft/spring-data-cosmosdb/issues/552

**Comment by kushagraThapar** [comment]
@loudywen - the new spring SDK has been released, can you please try out the new version and see if the issue persists ?

Here are the details of the new spring version: 

<groupId>com.azure</groupId>
<artifactId>azure-spring-data-2-3-cosmos</artifactId>
<version>3.0.0-beta.1</version>

Azure-spring-data-2-3-cosmos: https://search.maven.org/artifact/com.azure/azure-spring-data-2-3-cosmos/3.0.0-beta.1/jar

Here are the tutorials to get it started: https://github.com/Azure-Samples/azure-spring-data-cosmos-java-sql-api-getting-started

**Comment by loudywen** [comment]
sure I will test it and let u know the result

**Comment by loudywen** [comment]
@kushagraThapar  @anuchandy  with this new version. the refresscope will raise exception. Would you guys able to provide an sample repo for refresh scope?

**Comment by loudywen** [comment]
@kushagraThapar have you take a look at the issue that the new version is not working with the  `@RefreshScope`?

**Comment by kushagraThapar** [comment]
@loudywen - I believe we have a fix for this scenario - https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/cosmos/azure-cosmos/CHANGELOG.md#440-2020-09-12
Can you please try with the latest version and check if this fixes your issue ?

**Comment by loudywen** [comment]
@kushagraThapar  sure, will let u know after I tested
