### ISSUE TITLE
[BUG] Connection drops after a few hours ("force detached. Code: RenewToken")

### ISSUE THREAD

**Issue by sticksen** [Azure/azure-sdk-for-java#13871]
# Description
I´m using the example in 
https://github.com/Azure-Samples/azure-iot-samples-java/tree/master/iot-hub/Quickstarts/read-d2c-messages
to connect to the IoTHub Eventhub. At first it all works fine, but after a few hours the connection drops with the following error messages in the log.
Neither the `completed`, `error` or any other lambda is called by the Reactive chain, so I don´t see any chance to recover in my code currently.

What is the preferred way to handle this?

```
2020-08-04 18:23:38.923 ERROR 6 --- [       single-1] c.a.c.a.implementation.ReactorReceiver   : connectionId[MF_8603c0_1596534787788] linkName[all_573270_1596534787852-2] entityPath[xxx-iothub-westeurope/ConsumerGroups/$Default/Partitions/2] Error occurred in link.
The link 'all_573270_1596534787852-2' is force detached. Code: RenewToken. Details: Unauthorized access. 'Listen' claim(s) are required to perform this operation. Resource: 'sb://iothub-xxx.servicebus.windows.net/xxx-iothub-westeurope/consumergroups/$default/partitions/2'.. TrackingId:4f81ccfd8dbe4e928c4826d9a782bc5c_G6, SystemTracker:gateway5, Timestamp:2020-08-04T18:23:38, errorContext[NAMESPACE: iothub-xxx.servicebus.windows.net, PATH: xxx-iothub-westeurope/ConsumerGroups/$Default/Partitions/2, REFERENCE_ID: all_573270_1596534787852-2, LINK_CREDIT: 485]
2020-08-04 18:23:38.926 ERROR 6 --- [       single-1] c.a.c.a.i.ReactorDispatcher              : ReactorDispatcher instance is closed.
2020-08-04 18:23:38.927 ERROR 6 --- [       single-1] reactor.core.publisher.Operators         : Operator called default onErrorDropped

java.util.concurrent.RejectedExecutionException: ReactorDispatcher instance is closed.
	at com.azure.core.amqp.implementation.ReactorDispatcher.throwIfSchedulerError(ReactorDispatcher.java:93) ~[azure-core-amqp-1.3.0.jar!/:na]
	at com.azure.core.amqp.implementation.ReactorDispatcher.invoke(ReactorDispatcher.java:68) ~[azure-core-amqp-1.3.0.jar!/:na]
	at com.azure.core.amqp.implementation.ReactorReceiver.dispose(ReactorReceiver.java:169) ~[azure-core-amqp-1.3.0.jar!/:na]
	at com.azure.core.amqp.implementation.ReactorSession$LinkSubscription.dispose(ReactorSession.java:600) ~[azure-core-amqp-1.3.0.jar!/:na]
	at com.azure.core.amqp.implementation.ReactorSession.removeLink(ReactorSession.java:336) ~[azure-core-amqp-1.3.0.jar!/:na]
	at com.azure.core.amqp.implementation.ReactorSession.lambda$getSubscription$28(ReactorSession.java:564) ~[azure-core-amqp-1.3.0.jar!/:na]
	at reactor.core.publisher.LambdaSubscriber.onError(LambdaSubscriber.java:149) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.FluxReplay$SizeBoundReplayBuffer.replayNormal(FluxReplay.java:802) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.FluxReplay$SizeBoundReplayBuffer.replay(FluxReplay.java:898) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.ReplayProcessor.onError(ReplayProcessor.java:460) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.FluxCreate$BaseSink.error(FluxCreate.java:452) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.FluxCreate$SerializedSink.drainLoop(FluxCreate.java:229) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.FluxCreate$SerializedSink.drain(FluxCreate.java:205) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.FluxCreate$SerializedSink.error(FluxCreate.java:181) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at com.azure.core.amqp.implementation.ReactorReceiver.lambda$new$5(ReactorReceiver.java:91) ~[azure-core-amqp-1.3.0.jar!/:na]
	at reactor.core.publisher.LambdaSubscriber.onNext(LambdaSubscriber.java:160) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.UnicastProcessor.drainRegular(UnicastProcessor.java:240) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.UnicastProcessor.drain(UnicastProcessor.java:312) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.UnicastProcessor.onNext(UnicastProcessor.java:386) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.FluxCreate$IgnoreSink.next(FluxCreate.java:618) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.FluxCreate$SerializedSink.next(FluxCreate.java:153) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at com.azure.core.amqp.implementation.handler.Handler.onNext(Handler.java:54) ~[azure-core-amqp-1.3.0.jar!/:na]
	at com.azure.core.amqp.implementation.handler.LinkHandler.processOnClose(LinkHandler.java:93) ~[azure-core-amqp-1.3.0.jar!/:na]
	at com.azure.core.amqp.implementation.handler.LinkHandler.handleRemoteLinkClosed(LinkHandler.java:108) ~[azure-core-amqp-1.3.0.jar!/:na]
	at com.azure.core.amqp.implementation.handler.LinkHandler.onLinkRemoteClose(LinkHandler.java:50) ~[azure-core-amqp-1.3.0.jar!/:na]
	at com.azure.core.amqp.implementation.handler.ReceiveLinkHandler.onLinkRemoteClose(ReceiveLinkHandler.java:18) ~[azure-core-amqp-1.3.0.jar!/:na]
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:176) ~[proton-j-0.33.4.jar!/:na]
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108) ~[proton-j-0.33.4.jar!/:na]
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324) ~[proton-j-0.33.4.jar!/:na]
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291) ~[proton-j-0.33.4.jar!/:na]
	at com.azure.core.amqp.implementation.ReactorExecutor.run(ReactorExecutor.java:82) ~[azure-core-amqp-1.3.0.jar!/:na]
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

2020-08-04 18:23:38.940 ERROR 6 --- [       single-1] c.a.c.a.i.ReactorDispatcher              : ReactorDispatcher instance is closed.
2020-08-04 18:23:38.941 ERROR 6 --- [       single-1] reactor.core.publisher.Operators         : Operator called default onErrorDropped

java.util.concurrent.RejectedExecutionException: ReactorDispatcher instance is closed.
	at com.azure.core.amqp.implementation.ReactorDispatcher.throwIfSchedulerError(ReactorDispatcher.java:93) ~[azure-core-amqp-1.3.0.jar!/:na]
	at com.azure.core.amqp.implementation.ReactorDispatcher.invoke(ReactorDispatcher.java:68) ~[azure-core-amqp-1.3.0.jar!/:na]
	at com.azure.core.amqp.implementation.ReactorReceiver.addCredits(ReactorReceiver.java:119) ~[azure-core-amqp-1.3.0.jar!/:na]
	at com.azure.messaging.eventhubs.implementation.AmqpReceiveLinkProcessor.onNext(AmqpReceiveLinkProcessor.java:156) ~[azure-messaging-eventhubs-5.1.2.jar!/:na]
	at com.azure.messaging.eventhubs.implementation.AmqpReceiveLinkProcessor.onNext(AmqpReceiveLinkProcessor.java:31) ~[azure-messaging-eventhubs-5.1.2.jar!/:na]
	at reactor.core.publisher.FluxRepeatPredicate$RepeatPredicateSubscriber.onNext(FluxRepeatPredicate.java:79) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.Operators$MonoSubscriber.request(Operators.java:1799) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.request(Operators.java:2046) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at com.azure.messaging.eventhubs.implementation.AmqpReceiveLinkProcessor.requestUpstream(AmqpReceiveLinkProcessor.java:357) ~[azure-messaging-eventhubs-5.1.2.jar!/:na]
	at com.azure.messaging.eventhubs.implementation.AmqpReceiveLinkProcessor.lambda$onNext$2(AmqpReceiveLinkProcessor.java:186) ~[azure-messaging-eventhubs-5.1.2.jar!/:na]
	at reactor.core.publisher.LambdaSubscriber.onComplete(LambdaSubscriber.java:132) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.FluxReplay$SizeBoundReplayBuffer.replayNormal(FluxReplay.java:805) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.FluxReplay$SizeBoundReplayBuffer.replay(FluxReplay.java:898) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.ReplayProcessor.onComplete(ReplayProcessor.java:475) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.FluxCreate$BaseSink.complete(FluxCreate.java:438) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.FluxCreate$SerializedSink.drainLoop(FluxCreate.java:239) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.FluxCreate$SerializedSink.drain(FluxCreate.java:205) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.FluxCreate$SerializedSink.complete(FluxCreate.java:196) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at com.azure.core.amqp.implementation.ReactorReceiver.dispose(ReactorReceiver.java:163) ~[azure-core-amqp-1.3.0.jar!/:na]
	at com.azure.core.amqp.implementation.ReactorSession$LinkSubscription.dispose(ReactorSession.java:600) ~[azure-core-amqp-1.3.0.jar!/:na]
	at com.azure.core.amqp.implementation.ReactorSession.lambda$dispose$4(ReactorSession.java:154) ~[azure-core-amqp-1.3.0.jar!/:na]
	at java.base/java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1603) ~[na:na]
	at com.azure.core.amqp.implementation.ReactorSession.dispose(ReactorSession.java:154) ~[azure-core-amqp-1.3.0.jar!/:na]
	at com.azure.core.amqp.implementation.ReactorConnection$SessionSubscription.dispose(ReactorConnection.java:430) ~[azure-core-amqp-1.3.0.jar!/:na]
	at com.azure.core.amqp.implementation.ReactorConnection.removeSession(ReactorConnection.java:259) ~[azure-core-amqp-1.3.0.jar!/:na]
	at com.azure.core.amqp.implementation.ReactorConnection.dispose(ReactorConnection.java:286) ~[azure-core-amqp-1.3.0.jar!/:na]
	at com.azure.messaging.eventhubs.implementation.EventHubReactorAmqpConnection.dispose(EventHubReactorAmqpConnection.java:144) ~[azure-messaging-eventhubs-5.1.2.jar!/:na]
	at com.azure.core.amqp.implementation.AmqpChannelProcessor.close(AmqpChannelProcessor.java:308) ~[azure-core-amqp-1.3.0.jar!/:na]
	at com.azure.core.amqp.implementation.AmqpChannelProcessor.setAndClearChannel(AmqpChannelProcessor.java:297) ~[azure-core-amqp-1.3.0.jar!/:na]
	at com.azure.core.amqp.implementation.AmqpChannelProcessor.lambda$onNext$2(AmqpChannelProcessor.java:103) ~[azure-core-amqp-1.3.0.jar!/:na]
	at reactor.core.publisher.LambdaSubscriber.onError(LambdaSubscriber.java:149) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.FluxReplay$SizeBoundReplayBuffer.replayNormal(FluxReplay.java:802) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.FluxReplay$SizeBoundReplayBuffer.replay(FluxReplay.java:898) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.ReplayProcessor.onError(ReplayProcessor.java:460) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at com.azure.core.amqp.implementation.ReactorConnection$ReactorExceptionHandler.onConnectionError(ReactorConnection.java:382) ~[azure-core-amqp-1.3.0.jar!/:na]
	at com.azure.core.amqp.implementation.ReactorExecutor.run(ReactorExecutor.java:126) ~[azure-core-amqp-1.3.0.jar!/:na]
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

2020-08-04 18:23:38.942 ERROR 6 --- [       single-1] reactor.core.scheduler.Schedulers        : Scheduler worker in group main failed with an uncaught exception

java.util.concurrent.RejectedExecutionException: ReactorDispatcher instance is closed.
	at com.azure.core.amqp.implementation.ReactorDispatcher.throwIfSchedulerError(ReactorDispatcher.java:93) ~[azure-core-amqp-1.3.0.jar!/:na]
	at com.azure.core.amqp.implementation.ReactorDispatcher.invoke(ReactorDispatcher.java:68) ~[azure-core-amqp-1.3.0.jar!/:na]
	at com.azure.core.amqp.implementation.ReactorReceiver.addCredits(ReactorReceiver.java:119) ~[azure-core-amqp-1.3.0.jar!/:na]
	at com.azure.messaging.eventhubs.implementation.AmqpReceiveLinkProcessor.onNext(AmqpReceiveLinkProcessor.java:156) ~[azure-messaging-eventhubs-5.1.2.jar!/:na]
	at com.azure.messaging.eventhubs.implementation.AmqpReceiveLinkProcessor.onNext(AmqpReceiveLinkProcessor.java:31) ~[azure-messaging-eventhubs-5.1.2.jar!/:na]
	at reactor.core.publisher.FluxRepeatPredicate$RepeatPredicateSubscriber.onNext(FluxRepeatPredicate.java:79) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.Operators$MonoSubscriber.request(Operators.java:1799) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.request(Operators.java:2046) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at com.azure.messaging.eventhubs.implementation.AmqpReceiveLinkProcessor.requestUpstream(AmqpReceiveLinkProcessor.java:357) ~[azure-messaging-eventhubs-5.1.2.jar!/:na]
	at com.azure.messaging.eventhubs.implementation.AmqpReceiveLinkProcessor.lambda$onNext$2(AmqpReceiveLinkProcessor.java:186) ~[azure-messaging-eventhubs-5.1.2.jar!/:na]
	at reactor.core.publisher.LambdaSubscriber.onComplete(LambdaSubscriber.java:132) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.FluxReplay$SizeBoundReplayBuffer.replayNormal(FluxReplay.java:805) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.FluxReplay$SizeBoundReplayBuffer.replay(FluxReplay.java:898) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.ReplayProcessor.onComplete(ReplayProcessor.java:475) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.FluxCreate$BaseSink.complete(FluxCreate.java:438) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.FluxCreate$SerializedSink.drainLoop(FluxCreate.java:239) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.FluxCreate$SerializedSink.drain(FluxCreate.java:205) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.FluxCreate$SerializedSink.complete(FluxCreate.java:196) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at com.azure.core.amqp.implementation.ReactorReceiver.dispose(ReactorReceiver.java:163) ~[azure-core-amqp-1.3.0.jar!/:na]
	at com.azure.core.amqp.implementation.ReactorSession$LinkSubscription.dispose(ReactorSession.java:600) ~[azure-core-amqp-1.3.0.jar!/:na]
	at com.azure.core.amqp.implementation.ReactorSession.lambda$dispose$4(ReactorSession.java:154) ~[azure-core-amqp-1.3.0.jar!/:na]
	at java.base/java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1603) ~[na:na]
	at com.azure.core.amqp.implementation.ReactorSession.dispose(ReactorSession.java:154) ~[azure-core-amqp-1.3.0.jar!/:na]
	at com.azure.core.amqp.implementation.ReactorConnection$SessionSubscription.dispose(ReactorConnection.java:430) ~[azure-core-amqp-1.3.0.jar!/:na]
	at com.azure.core.amqp.implementation.ReactorConnection.removeSession(ReactorConnection.java:259) ~[azure-core-amqp-1.3.0.jar!/:na]
	at com.azure.core.amqp.implementation.ReactorConnection.dispose(ReactorConnection.java:286) ~[azure-core-amqp-1.3.0.jar!/:na]
	at com.azure.messaging.eventhubs.implementation.EventHubReactorAmqpConnection.dispose(EventHubReactorAmqpConnection.java:144) ~[azure-messaging-eventhubs-5.1.2.jar!/:na]
	at com.azure.core.amqp.implementation.AmqpChannelProcessor.close(AmqpChannelProcessor.java:308) ~[azure-core-amqp-1.3.0.jar!/:na]
	at com.azure.core.amqp.implementation.AmqpChannelProcessor.setAndClearChannel(AmqpChannelProcessor.java:297) ~[azure-core-amqp-1.3.0.jar!/:na]
	at com.azure.core.amqp.implementation.AmqpChannelProcessor.lambda$onNext$2(AmqpChannelProcessor.java:103) ~[azure-core-amqp-1.3.0.jar!/:na]
	at reactor.core.publisher.LambdaSubscriber.onError(LambdaSubscriber.java:149) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.FluxReplay$SizeBoundReplayBuffer.replayNormal(FluxReplay.java:802) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.FluxReplay$SizeBoundReplayBuffer.replay(FluxReplay.java:898) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.ReplayProcessor.onError(ReplayProcessor.java:460) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at com.azure.core.amqp.implementation.ReactorConnection$ReactorExceptionHandler.onConnectionError(ReactorConnection.java:382) ~[azure-core-amqp-1.3.0.jar!/:na]
	at com.azure.core.amqp.implementation.ReactorExecutor.run(ReactorExecutor.java:126) ~[azure-core-amqp-1.3.0.jar!/:na]
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

2020-08-04 18:31:01.378 ERROR 6 --- [     parallel-1] c.a.c.a.i.ReactorDispatcher              : ReactorDispatcher instance is closed.
2020-08-04 18:31:01.383 ERROR 6 --- [     parallel-1] c.a.c.a.i.ActiveClientTokenManager       : Error occurred while refreshing token that is not retriable. Not scheduling refresh task. Use ActiveClientTokenManager.authorize() to schedule task again. audience[amqp://iothub-xxx.servicebus.windows.net/xxx-iothub-westeurope/ConsumerGroups/$Default/Partitions/0] scopes[amqp://iothub-xxx.servicebus.windows.net/xxx-iothub-westeurope/ConsumerGroups/$Default/Partitions/0]
ReactorDispatcher instance is closed.
2020-08-04 18:31:01.425 ERROR 6 --- [     parallel-1] c.a.c.a.i.ReactorDispatcher              : ReactorDispatcher instance is closed.
2020-08-04 18:31:01.427 ERROR 6 --- [     parallel-1] c.a.c.a.i.ActiveClientTokenManager       : Error occurred while refreshing token that is not retriable. Not scheduling refresh task. Use ActiveClientTokenManager.authorize() to schedule task again. audience[amqp://iothub-xxx.servicebus.windows.net/xxx-iothub-westeurope/ConsumerGroups/$Default/Partitions/1] scopes[amqp://iothub-xxx.servicebus.windows.net/xxx-iothub-westeurope/ConsumerGroups/$Default/Partitions/1]
ReactorDispatcher instance is closed.
```

# Context

- **OS and version used:** Ubuntu
- **Java runtime used:** 11
- **SDK version used:** 5.1.2

**Comment by joshfree** [comment]
Thanks for reporting this issue @sticksen.  @srnagar from the `event hubs` sdk team will follow up shortly.

/cc @conniey

**Comment by srnagar** [comment]
@sticksen It looks like the authorization token expired and requires renewal. How are you authenticating the client?

**Comment by sticksen** [comment]
@srnagar hi! Exactly like it is done in the linked example code above.

**Comment by srnagar** [comment]
@sticksen It might be that the built-in Event Hub compatible connection string available on the portal might have expired or changed. Could you please verify that the connection string is still valid? See the article below:
https://docs.microsoft.com/en-us/samples/azure/azure-sdk-for-net/iothub-connect-to-eventhubs/

**Comment by sticksen** [comment]
@srnagar I can still connect with the same credentials if I restart the application. Additionally, the “old” connection code (as can be seen in https://github.com/Azure-Samples/azure-iot-samples-java/blob/32a3f2fcc2fc7c1604f8e1c8a5269cd055f1cf6b/iot-hub/Quickstarts/read-d2c-messages/src/main/java/com/microsoft/docs/iothub/samples/ReadDeviceToCloudMessages.java) still also works with the same credentials and does not stop after a few hours.

**Comment by samuelkoppes** [comment]
We are investigating this issue and will respond with an update by 11/4/2020.

**Comment by samuelkoppes** [comment]
@sticksen Are you using a token or a SAS key? Can you share details of how you are configuring auth?

**Comment by sticksen** [comment]
@samuelkoppes SAS key, exactly the same way as used in the example code.

**Comment by jonasbark** [comment]
Same happens to me as well.
I'm using a connection string.

**Comment by lgcanto** [comment]
Happened with me as well, after running for 5 hours

**Comment by lgcanto** [comment]
Is there a way to externally handle that exception? So I can programmatically restart the connection to get it to work again. In my case I'm only getting the error logs.

**Comment by conniey** [comment]
In release 5.3.0, we added a watchdog that periodically checks to see if the connection is still alive when using EventProcessorClient. https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/eventhubs/azure-messaging-eventhubs/CHANGELOG.md#530-2020-10-12

Are there any other logs around the errors you can share?

**Comment by lgcanto** [comment]
Thanks. I was using `EventHubConsumerAsyncClient`. My service is now running using the `EventProcessorClient`, still no issues for now, I'll comment again if I see it.

**Comment by ramya-rao-a** [comment]
Is there anything else to do here after your comment above? If not, please add the `issue-addressed` label

**Comment by conniey** [comment]
This should have been fixed by this release. We reconnect correctly on connection loss. At the moment, we have one more reliability fix.
