### ISSUE TITLE
[BUG] java.lang.NoClassDefFoundError: Could not initialize class com.azure.data.cosmos.internal.directconnectivity.rntbd.RntbdConstants$RntbdContextRequestHeader

### ISSUE THREAD

**Issue by eleckner** [Azure/azure-sdk-for-java#13883]
2020-08-07 12:32:17.016  INFO 4628 --- [     parallel-1] c.a.d.c.internal.RxDocumentClientImpl    : Getting database account endpoint from <**REDACTED**>
2020-08-07 12:32:19.788  WARN 4628 --- [s-rntbd-nio-2-2] c.a.d.c.i.d.r.RntbdClientChannelPool     : Channel([id: 0xdeb42d89, L:/192.168.1.104:64590 - R:cdb-ms-prod-eastus2-fd18.documents.azure.com/104.208.231.14:11305]) health check request failed due to:

java.lang.NoClassDefFoundError: Could not initialize class com.azure.data.cosmos.internal.directconnectivity.rntbd.RntbdConstants$RntbdContextRequestHeader
	at com.azure.data.cosmos.internal.directconnectivity.rntbd.RntbdContextRequest$Headers.<init>(RntbdContextRequest.java:126) ~[azure-cosmos-3.7.3.jar:na]
	at com.azure.data.cosmos.internal.directconnectivity.rntbd.RntbdContextRequest$Headers.<init>(RntbdContextRequest.java:118) ~[azure-cosmos-3.7.3.jar:na]
	at com.azure.data.cosmos.internal.directconnectivity.rntbd.RntbdContextRequest.<init>(RntbdContextRequest.java:33) ~[azure-cosmos-3.7.3.jar:na]
	at com.azure.data.cosmos.internal.directconnectivity.rntbd.RntbdContextNegotiator.startRntbdContextRequest(RntbdContextNegotiator.java:77) ~[azure-cosmos-3.7.3.jar:na]
	at com.azure.data.cosmos.internal.directconnectivity.rntbd.RntbdContextNegotiator.write(RntbdContextNegotiator.java:63) ~[azure-cosmos-3.7.3.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:715) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:707) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]

**Comment by eleckner** [comment]
CosmosRepository
   <dependency>
      <groupId>com.microsoft.azure</groupId>
      <artifactId>azure-cosmosdb-spring-boot-starter</artifactId>
      <version>2.3.2</version>
    </dependency>

@Repository
public interface FileLocationEntityRepository
    extends CosmosRepository<FileLocationEntity, Integer> {

  @Nullable
  FileLocationEntity findByFileID(String fileID);

...

}

**Comment by joshfree** [comment]
Thanks for filing this issue, @eleckner.

@anuchandy could you please assist with the NoClassDefFoundError error above?

**Comment by kushagraThapar** [comment]
@eleckner - if you use the new azure-spring-data-cosmos SDK, the issue has been resolved. 

Here is more information on the latest version of the SDK: https://docs.microsoft.com/en-us/azure/cosmos-db/sql-api-sdk-java-spring-v3?tabs=explore
Please reopen the issue if it still exists.
