### ISSUE TITLE
SubscriptionRequestsThrottled on StorageAccountImpl.getKeys

### ISSUE THREAD

**Issue by masarlabs** [Azure/azure-sdk-for-java#1389]
Hi,
I'm writing a script that collect info from Azure, it should do only "read" request but I get a SubscriptionRequestsThrottled when I call StorageAccountImpl.getKeys.
Is getKeys a "write" operation???

Here is a stack trace:
Caught: com.microsoft.azure.CloudException: {"error":{"code":"SubscriptionRequestsThrottled","message":"Number of write requests for subscription '9bf80712-ea01-4ee9-b119-821915e971d8' exceeded the limit of '1200' for time interval '01:00:00'. Please try again after '5' minutes."}}: Number of write requests for subscription '9bf80712-ea01-4ee9-b119-821915e971d8' exceeded the limit of '1200' for time interval '01:00:00'. Please try again after '5' minutes.
com.microsoft.azure.CloudException: {"error":{"code":"SubscriptionRequestsThrottled","message":"Number of write requests for subscription '9bf80712-ea01-4ee9-b119-821915e971d8' exceeded the limit of '1200' for time interval '01:00:00'. Please try again after '5' minutes."}}: Number of write requests for subscription '9bf80712-ea01-4ee9-b119-821915e971d8' exceeded the limit of '1200' for time interval '01:00:00'. Please try again after '5' minutes.
        at com.microsoft.rest.ServiceResponseBuilder.build(ServiceResponseBuilder.java:150)
        at com.microsoft.azure.management.storage.implementation.StorageAccountsInner.listKeysDelegate(StorageAccountsInner.java:803)
        at com.microsoft.azure.management.storage.implementation.StorageAccountsInner.access$700(StorageAccountsInner.java:42)
        at com.microsoft.azure.management.storage.implementation.StorageAccountsInner$27.call(StorageAccountsInner.java:793)
        at com.microsoft.azure.management.storage.implementation.StorageAccountsInner$27.call(StorageAccountsInner.java:789)
        at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
        at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$RequestArbiter.request(RxJavaCallAdapterFactory.java:173)
        at rx.Subscriber.setProducer(Subscriber.java:211)
        at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102)
        at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:152)
        at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:138)
        at rx.Observable.unsafeSubscribe(Observable.java:9861)
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.Observable.subscribe(Observable.java:9957)
        at rx.Observable.subscribe(Observable.java:9924)
        at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:445)
        at rx.observables.BlockingObservable.single(BlockingObservable.java:342)
        at com.microsoft.azure.management.storage.implementation.StorageAccountsInner.listKeys(StorageAccountsInner.java:737)
        at com.microsoft.azure.management.storage.implementation.StorageAccountImpl.getKeys(StorageAccountImpl.java:115)
        at wfVmJson.getBlobData(wfVmJson.groovy:47)

**Comment by anuchandy** [comment]
yes, [storage.getkeys](https://github.com/Azure/azure-rest-api-specs/blob/c97a18ed775029207715b09c80761334724740b9/specification/storage/resource-manager/Microsoft.Storage/2017-06-01/storage.json#L361) is a write (POST) operation.

**Comment by masarlabs** [comment]
Thanks
