### ISSUE TITLE
[BUG] Dependency version problem about okhttp

### ISSUE THREAD

**Issue by yevster** [Azure/azure-sdk-for-java#13942]
**Describe the bug**
A customer attempted to use one of the Azure Spring starters. They pulled in version 1.6.12 of the autorest `client-runtime` jar. The POM has a dependency on `com.squareup.okhttp3:okhttp`, but only the parent POM specifies the version: `3.12.2`.

As a result, it is impossible to predict which version actually gets pulled in. With this customer, the version that was pulled in was `3.8.1`, which was incompatible with the code in our SDK. As a consequence, the application failed to start through no fault of the customer.

***Exception or Stack Trace***

Dependency tree from the customer's build:
```
[INFO] |  +- com.microsoft.azure:azure-keyvault:jar:1.2.2:compile
[INFO] |  |  +- com.microsoft.azure:azure-keyvault-cryptography:jar:1.2.2:compile
[INFO] |  |  |  \- com.microsoft.azure:azure-keyvault-core:jar:1.2.2:compile
[INFO] |  |  +- com.microsoft.azure:azure-keyvault-webkey:jar:1.2.2:compile
[INFO] |  |  \- com.microsoft.rest:client-runtime:jar:1.6.12:compile
[INFO] |  |     +- com.squareup.retrofit2:retrofit:jar:2.5.0:compile
[INFO] |  |     +- com.squareup.okhttp3:okhttp:jar:3.8.1:compile
[INFO] |  |     |  \- com.squareup.okio:okio:jar:1.13.0:compile
[INFO] |  |     +- com.squareup.okhttp3:logging-interceptor:jar:3.8.1:compile
[INFO] |  |     +- com.squareup.okhttp3:okhttp-urlconnection:jar:3.14.8:compile
[INFO] |  |     +- com.squareup.retrofit2:converter-jackson:jar:2.5.0:compile
[INFO] |  |     +- com.fasterxml.jackson.datatype:jackson-datatype-joda:jar:2.11.0:compile
[INFO] |  |     \- com.squareup.retrofit2:adapter-rxjava:jar:2.4.0:compile
```

And the resulting startup failure:
```
at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127)
"	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) 
"	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
"	at com.microsoft.rest.RestClient$Builder.build(RestClient.java:544) 
"	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) 
"	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237) 
"	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) 
"	at retrofit2.Retrofit$Builder.baseUrl(Retrofit.java:458) 
"	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:53) 
"	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
"	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) 
"	at org.springframework.boot.context.config.ConfigFileApplicationListener.onApplicationEvent(ConfigFileApplicationListener.java:188) 
"	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) 
"	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:345) 
"	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) 
"	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:80) 
"	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127) 
"	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) 
"	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) 
"	at com.microsoft.azure.keyvault.spring.KeyVaultEnvironmentPostProcessor.postProcessEnvironment(KeyVaultEnvironmentPostProcessor.java:26) 
"	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 
"	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) 
"java.lang.NoSuchMethodError: okhttp3.HttpUrl.get(Ljava/lang/String;)Lokhttp3/HttpUrl; 
"	at org.springframework.boot.context.config.ConfigFileApplicationListener.onApplicationEnvironmentPreparedEvent(ConfigFileApplicationListener.java:200) 
"	at com.<hidden to protect customer privacy>.Application.main(Application.java:17) 
"	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:80) 
"	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:114) 
"20:03:18.258 [main] ERROR org.springframework.boot.SpringApplication - Application run failed 
"	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:140) 
"	at org.springframework.boot.loader.Launcher.launch(Launcher.java:109) 
"	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) 
"	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.bootstrapServiceContext(BootstrapApplicationListener.java:209) 
"	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) 
"	at java.lang.reflect.Method.invoke(Method.java:498) 
"	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:71) 
"	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:53) 
"	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) 
"	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:345) 
"	at com.microsoft.azure.keyvault.spring.KeyVaultEnvironmentPostProcessorHelper.addKeyVaultPropertySource(KeyVaultEnvironmentPostProcessorHelper.java:61)
"

```

**To Reproduce**
The issue depends on the build environment and the kindness of gremlins living therein.

***Code Snippet***
Pulling in any Maven dependency that has a transitive dependency on `com.microsoft.rest:client-runtime`

**Expected behavior**
The transitive dependencies of the SDK that we tested against will be the ones that the customer ends up downloading when building their pronect.

**Comment by selvasingh** [comment]
@jianghaolu we are requesting the customer to force a specific version in the POM

**Comment by joshfree** [comment]
Thanks for filing the issue, @yevster.  Someone from the `azure-spring` team will follow up with you shortly.  /cc @jialindai

**Comment by jialindai** [comment]
@yevster , is it possible to share the pom file of the project.

client-runtime 1.6.12 depends on okhttp 3.12.2, from the above description it's not clear how okhttp 3.8.1 is pulled in.
