### ISSUE TITLE
[BUG] Azure Identity (DefaultAzureCredential)

### ISSUE THREAD

**Issue by wermerb** [Azure/azure-sdk-for-java#14218]
**Describe the bug**
The DefaultAzureCredential will not go over the pre-configured list of credentials on developer machines.
ManagedIdentityCredential throws a RuntimeExcetion thus breaks the chain.

***Exception or Stack Trace***
```
Suppressed: com.azure.core.exception.ClientAuthenticationException: DefaultAzureCredential authentication failed. ---> ManagedIdentityCredential authentication failed. Error Details: Connection reset
		at com.azure.identity.ChainedTokenCredential.lambda$getToken$1(ChainedTokenCredential.java:51) ~[azure-identity-1.1.0.jar:na]
		at reactor.core.publisher.Mono.lambda$onErrorResume$31(Mono.java:3362) ~[reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]
		at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:88) ~[reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]
		... 50 common frames omitted
	Caused by: java.net.SocketException: Connection reset
		at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
		at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
		at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
		at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
		at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1950)
		at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1945)
		at java.security.AccessController.doPrivileged(Native Method)
		at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1944)
		at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1514)
		at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
		at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
		at com.azure.identity.implementation.IdentityClient.lambda$authenticateToIMDSEndpoint$36(IdentityClient.java:824)
		at reactor.core.publisher.MonoCallable.call(MonoCallable.java:91)
		at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:173)
		... 44 common frames omitted
	Caused by: java.net.SocketException: Connection reset
		at java.net.SocketInputStream.read(SocketInputStream.java:210)
		at java.net.SocketInputStream.read(SocketInputStream.java:141)
		at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
		at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
		at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
		at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:735)
		at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
		at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:706)
		at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1593)
		at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
		at com.azure.identity.implementation.IdentityClient.lambda$authenticateToIMDSEndpoint$36(IdentityClient.java:814)
		... 46 common frames omitted
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99) ~[reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]
		at reactor.core.publisher.Mono.block(Mono.java:1680) ~[reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]
		... 12 common frames omitted
```

***Code Snippet***
`new DefaultAzureCredentialBuilder().build();`

**Expected behavior**
DefaultAzureCredential should not break the chain in case of an unexpected exception.

**Setup (please complete the following information):**
 - OS: Windows
 - IDE : IntelliJ
 - Version of the Library used: Azure Identity 1.1.0

**Comment by joshfree** [comment]
Thanks for reporting this issue in the 1.1.0 azure-identity package, @wermerb.  @g2vinay @jianghaolu can you please investigate for the September update?

**Comment by wermerb** [comment]
Hi @g2vinay,

Thank you very much for the quick response. 
I've tried your example and it indeed works. To have help the investigation i've created a demo app which produces to me the above mentioned issue: [demo.zip](https://github.com/Azure/azure-sdk-for-java/files/5116790/demo.zip).

I'm using Windows 10 and Oracle JDK 11.0.6

**Comment by g2vinay** [comment]
@wermerb 
Thank you for providing your demo spring app as a sample.

I was using and  investigating the demo spring app you provided.

**Underlying issue:**
The  underlying issue is that spring-cloud-azure-appconfiguration-config package doesn't seem to be picking up the AzureCredentials.java class implemented as AppConfigurationCredentialProvider / KeyVaultCredentialProvider.
And due to this credential provider not being picked up,  the spring-cloud-azure-appconfiguration-config package was using Managed Identity Credential by default and not the DefaultAzureCredential specified in the credential provider.

**To fix this issue and ensure that the AppConfigurationCredentialProvider gets used,  the following step needs to be performed:** 

Create a new folder in your resources directory called META-INF. Then in that folder create a file called *spring.factories* and add.

```factories
org.springframework.cloud.bootstrap.BootstrapConfiguration=\
com.example.demo.BeanConfig
```

if the package name is changed ever, then be sure to change it in this file too.

Once this step is performed, the `DefaultAzureCredential` in the AzureCredentials.java implementation will get picked up.
This resolved the issue in the Demo spring app provided.

**Comment by wermerb** [comment]
Hi @g2vinay,

Yup, you are right I've forgot to register the configuration, sorry about that :). However after this fix i got the following stacktrace:

```
java.lang.NullPointerException: null
	at com.azure.core.http.rest.RestProxy.endTracingSpan(RestProxy.java:556) ~[azure-core-1.7.0.jar:na]
	at reactor.core.publisher.FluxDoOnEach$DoOnEachSubscriber.onError(FluxDoOnEach.java:172) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:165) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
	at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:126) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:165) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onError(MonoPeekTerminal.java:251) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onError(MonoPeekTerminal.java:251) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondError(MonoFlatMap.java:185) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onError(MonoFlatMap.java:251) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onError(Operators.java:2021) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
	at reactor.core.publisher.Operators.error(Operators.java:196) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
	at reactor.core.publisher.MonoError.subscribe(MonoError.java:52) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
	at reactor.core.publisher.Mono.subscribe(Mono.java:4213) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FluxSwitchIfEmpty.java:75) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
	at reactor.core.publisher.Operators.complete(Operators.java:135) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
	at reactor.core.publisher.MonoEmpty.subscribe(MonoEmpty.java:45) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:150) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
	at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:76) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
	at reactor.core.publisher.DrainUtils.postCompleteDrain(DrainUtils.java:135) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
	at reactor.core.publisher.DrainUtils.postComplete(DrainUtils.java:186) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
	at reactor.core.publisher.FluxMaterialize$MaterializeSubscriber.onError(FluxMaterialize.java:121) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onError(Operators.java:2021) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
	at reactor.core.publisher.MonoNext$NextSubscriber.onError(MonoNext.java:87) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.checkTerminated(FluxFlatMap.java:834) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:600) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.drain(FluxFlatMap.java:580) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.innerError(FluxFlatMap.java:855) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
	at reactor.core.publisher.FluxFlatMap$FlatMapInner.onError(FluxFlatMap.java:1006) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:100) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
	at reactor.core.publisher.Operators.error(Operators.java:196) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
	at reactor.core.publisher.MonoError.subscribe(MonoError.java:52) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
	at reactor.core.publisher.Mono.subscribe(Mono.java:4213) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:97) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onError(FluxPeekFuseable.java:227) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onError(MonoPeekTerminal.java:251) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableConditionalSubscriber.onError(FluxPeekFuseable.java:545) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onError(MonoPeekTerminal.java:251) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
	at reactor.core.publisher.Operators.error(Operators.java:196) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
	at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:181) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
	at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
	at reactor.core.publisher.Mono.subscribe(Mono.java:4198) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:418) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
	at reactor.core.publisher.FluxIterable$IterableSubscription.slowPath(FluxIterable.java:267) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
	at reactor.core.publisher.FluxIterable$IterableSubscription.request(FluxIterable.java:225) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onSubscribe(FluxFlatMap.java:363) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:161) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:86) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:150) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:121) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2344) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:162) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onSubscribe(MonoFlatMap.java:103) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:90) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
	at reactor.core.publisher.MonoCurrentContext.subscribe(MonoCurrentContext.java:35) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
	at reactor.core.publisher.Flux.subscribe(Flux.java:8325) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
	at reactor.core.publisher.FluxConcatArray$ConcatArraySubscriber.onComplete(FluxConcatArray.java:207) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
	at reactor.core.publisher.FluxConcatArray.subscribe(FluxConcatArray.java:80) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
	at reactor.core.publisher.FluxDefer.subscribe(FluxDefer.java:54) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
	at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
	at com.azure.core.util.paging.ContinuablePagedFluxCore.subscribe(ContinuablePagedFluxCore.java:131) ~[azure-core-1.7.0.jar:na]
	at com.azure.core.http.rest.PagedFluxBase.subscribe(PagedFluxBase.java:126) ~[azure-core-1.7.0.jar:na]
	at reactor.core.publisher.Mono.subscribe(Mono.java:4213) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
	at reactor.core.publisher.Mono.block(Mono.java:1679) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
	at com.microsoft.azure.spring.cloud.config.stores.ClientStore.listSettings(ClientStore.java:145) ~[spring-cloud-azure-appconfiguration-config-1.2.7.jar:1.2.7]
	at com.microsoft.azure.spring.cloud.config.AppConfigurationPropertySource.initProperties(AppConfigurationPropertySource.java:119) ~[spring-cloud-azure-appconfiguration-config-1.2.7.jar:1.2.7]
	at com.microsoft.azure.spring.cloud.config.AppConfigurationPropertySourceLocator.create(AppConfigurationPropertySourceLocator.java:222) ~[spring-cloud-azure-appconfiguration-config-1.2.7.jar:1.2.7]
	at com.microsoft.azure.spring.cloud.config.AppConfigurationPropertySourceLocator.addPropertySource(AppConfigurationPropertySourceLocator.java:150) ~[spring-cloud-azure-appconfiguration-config-1.2.7.jar:1.2.7]
	at com.microsoft.azure.spring.cloud.config.AppConfigurationPropertySourceLocator.locate(AppConfigurationPropertySourceLocator.java:101) ~[spring-cloud-azure-appconfiguration-config-1.2.7.jar:1.2.7]
	at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:98) ~[spring-cloud-context-2.2.0.RELEASE.jar:2.2.0.RELEASE]
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:626) ~[spring-boot-2.3.3.RELEASE.jar:2.3.3.RELEASE]
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:370) ~[spring-boot-2.3.3.RELEASE.jar:2.3.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) ~[spring-boot-2.3.3.RELEASE.jar:2.3.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237) ~[spring-boot-2.3.3.RELEASE.jar:2.3.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) ~[spring-boot-2.3.3.RELEASE.jar:2.3.3.RELEASE]
	at com.example.demo.DemoApplication.main(DemoApplication.java:10) ~[classes/:na]
	Suppressed: com.azure.core.exception.ClientAuthenticationException: DefaultAzureCredential authentication failed. ---> ManagedIdentityCredential authentication failed. Error Details: Connection reset
		at com.azure.identity.ChainedTokenCredential.lambda$getToken$1(ChainedTokenCredential.java:51) ~[azure-identity-1.1.0.jar:na]
		at reactor.core.publisher.Mono.lambda$onErrorResume$31(Mono.java:3362) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
		at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:88) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
		... 50 common frames omitted
	Caused by: java.net.SocketException: Connection reset
		at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
		at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
		at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
		at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
		at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1969)
		at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1964)
		at java.base/java.security.AccessController.doPrivileged(Native Method)
		at java.base/sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1963)
		at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1531)
		at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1515)
		at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
		at com.azure.identity.implementation.IdentityClient.lambda$authenticateToIMDSEndpoint$36(IdentityClient.java:824)
		at reactor.core.publisher.MonoCallable.call(MonoCallable.java:91)
		at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:173)
		... 44 common frames omitted
	Caused by: java.net.SocketException: Connection reset
		at java.base/java.net.SocketInputStream.read(SocketInputStream.java:186)
		at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
		at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:252)
		at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:292)
		at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:351)
		at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:746)
		at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:689)
		at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:717)
		at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1610)
		at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1515)
		at com.azure.identity.implementation.IdentityClient.lambda$authenticateToIMDSEndpoint$36(IdentityClient.java:814)
		... 46 common frames omitted
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
		at reactor.core.publisher.Mono.block(Mono.java:1680) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
		... 12 common frames omitted
```

**Comment by g2vinay** [comment]
@wermerb 

I ran the demo spring application provided on a Windows machine with JDK 11 (to match your environment).
I ensured that no credential requirement is satisfied so Default Azure Credential goes through the entire chain.

This is the output I see:
![image](https://user-images.githubusercontent.com/5430778/91255498-c398ef80-e719-11ea-87a2-4f0c3a534f93.png)


The logs in the output before the exception show the entire chain of credentials in DAC being tried and not being available to authenticate (due to requirements not being satisfied).
The Connection reset issue is not reproducible with the spring app provided.
The proxy could be interfering with the credential behavior on your end.

It would help if you could share the the logs you see before the exception as well in the terminal.

**Comment by wermerb** [comment]
Hi @g2vinay,

Azure CLI Token Credential is the one that i preferred to fall back in our case, which is last in the chain. I suspect that the root cause is indeed the proxy, however i think it would be nice if an unexpected exception would not brake the chain.

**Comment by g2vinay** [comment]
@wermerb 
Using your stack trace, we will be adding the fix with the goal to resolve the issue on your end.
Since the issue is not reproducible on our end, we will need you to help us validate the fix.
I'll send you the instructions soon on how to access and try our the identity package with the fix from our daily dev feed

**Comment by g2vinay** [comment]
@wermerb 
Identity stable release with version 1.1.2 went out last week.

Can you upgrade you identity library version to this and verify if this issue is resolved on your end ?
```maven
<dependency>
  <groupId>com.azure</groupId>
  <artifactId>azure-identity</artifactId>
  <version>1.1.2</version>
</dependency>
```

**Comment by g2vinay** [comment]
@wermerb, let us know if you have any further questions or would like to reopen this issue.
Closing the issue.
