### ISSUE TITLE
[BUG] java.lang.NoSuchFieldError: Companion

### ISSUE THREAD

**Issue by bsikander** [Azure/azure-sdk-for-java#14878]
**Describe the bug**
Initialisation of OkHttp library is failing apparently from azure.core. I have tried changing the version but it didn't work out. I checked the dependency tree of my project and there is only 1 version of okHttp.

```
libraryDependencies += "org.apache.hadoop" % "hadoop-azure-datalake" % "3.2.0" % "provided"
libraryDependencies += "com.microsoft.azure" % "azure-data-lake-store-sdk" % "2.3.3" % "provided"
libraryDependencies += "com.azure" % "azure-storage-file-datalake" % "12.2.0" exclude ("com.azure", "azure-core-http-netty")
libraryDependencies += "com.azure" % "azure-core-http-okhttp" % "1.2.5"
```

***Exception or Stack Trace***
```
Exception in thread "main" java.lang.NoSuchFieldError: Companion
        at okhttp3.internal.Util.<clinit>(Util.kt:70)
        at okhttp3.internal.connection.RealConnectionPool.<clinit>(RealConnectionPool.kt:263)
        at okhttp3.ConnectionPool.<init>(ConnectionPool.kt:37)
        at okhttp3.ConnectionPool.<init>(ConnectionPool.kt:39)
        at okhttp3.OkHttpClient$Builder.<init>(OkHttpClient.kt:438)
        at com.azure.core.http.okhttp.OkHttpAsyncHttpClientBuilder.build(OkHttpAsyncHttpClientBuilder.java:165)
        at com.azure.core.http.okhttp.implementation.OkHttpClientProvider.createInstance(OkHttpClientProvider.java:14)
        at com.azure.core.implementation.http.HttpClientProviders.createInstance(HttpClientProviders.java:37)
        at com.azure.core.http.HttpClient.createDefault(HttpClient.java:27)
        at com.azure.core.http.HttpPipelineBuilder.build(HttpPipelineBuilder.java:60)
        at com.azure.storage.file.datalake.implementation.util.BuilderHelper.buildPipeline(BuilderHelper.java:109)
        at com.azure.storage.file.datalake.DataLakeServiceClientBuilder.buildAsyncClient(DataLakeServiceClientBuilder.java:92)
        at com.azure.storage.file.datalake.DataLakeServiceClientBuilder.buildClient(DataLakeServiceClientBuilder.java:78)
        at com.a.b.c.dor.utils.MyUtil.getGen2Client(MyUtil.scala:118)
        at com.a.b.c.dor.utils.MyUtil.transfer(MyUtil.scala:34)
        at com.a.b.c.dor.pipes.visitorsPipeline.transferFilesToGen1(VisitorsPipeline.scala:360)
        at com.a.b.c.dor.pipes.visitorsPipeline.ignite(VisitorsPipeline.scala:98)
        at com.a.b.c.dor.PipelineApp$.main(PipelineApp.scala:83)
        at com.a.b.c.dor.PipelineApp.main(PipelineApp.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:907)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:198)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:228)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:137)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```
**To Reproduce**

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - OS: 
 - IDE : [e.g. IntelliJ]
 - Version of the Library used

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by alzimmermsft** [comment]
Hi @bsikander, could you include which version of Scala, sbt, and Java you are using as well as a small code sample that reproduces the issue. I tried replicating with the same dependencies you listed but wasn't able to produce the same outcome.
