### ISSUE TITLE
NullPointerException when trying to delete resource that was already deleted on the portal

### ISSUE THREAD

**Issue by lenala** [Azure/azure-sdk-for-java#1520]
When I create a webapp, then delete it from the portal and try to delete it from my code, I get the following exception:

java.lang.NullPointerException
	at com.microsoft.rest.ServiceResponseBuilder.build(ServiceResponseBuilder.java:148)
	at com.microsoft.azure.management.appservice.implementation.WebAppsInner.deleteDelegate(WebAppsInner.java:1964)
	at com.microsoft.azure.management.appservice.implementation.WebAppsInner.access$400(WebAppsInner.java:49)
	at com.microsoft.azure.management.appservice.implementation.WebAppsInner$32.call(WebAppsInner.java:1868)
	at com.microsoft.azure.management.appservice.implementation.WebAppsInner$32.call(WebAppsInner.java:1864)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$RequestArbiter.request(RxJavaCallAdapterFactory.java:173)
	at rx.Subscriber.setProducer(Subscriber.java:211)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102)
	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:152)
	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:138)
	at rx.Observable.unsafeSubscribe(Observable.java:10346)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10346)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10346)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.subscribe(Observable.java:10442)
	at rx.Observable.subscribe(Observable.java:10409)
	at rx.observables.BlockingObservable.subscribe(BlockingObservable.java:479)
	at com.microsoft.azure.management.resources.fluentcore.arm.collection.implementation.GroupableResourcesImpl.deleteByGroup(GroupableResourcesImpl.java:67)
...

This is caused by responseBody being null on line 'String responseContent = responseBody.string();' in ServiceResponseBuilder

**Comment by martinsawicki** [comment]
@jianghaolu 
?

**Comment by jianghaolu** [comment]
@lenala showed me the error. We only handle responses whose body is null but don't handle responses that are null themselves. A null check would be an easy fix but I'd want to dig a little more why a response could be null.
