### ISSUE TITLE
[BUG] An error when downloading file with decryption

### ISSUE THREAD

**Issue by yangchengs** [Azure/azure-sdk-for-java#15282]
**Describe the bug**

A Microsoft cx wants to use EncryptedBlobClient to upload file and download file in separate applications. 
There is no issue when uploading a file and downloading file in sequence with the same EnctyptedBlobClient.

If I commented the lines of uploading blob and the code only has download invoked, one exception is thrown and I don't know how to workaround it.

***Exception or Stack Trace***
2656 [reactor-http-nio-1] INFO com.azure.security.keyvault.keys.cryptography.CryptographyServiceClient - Retrieving key - key1
Exception in thread "main" java.lang.IllegalStateException: block()/blockFirst()/blockLast() are blocking, which is not supported in thread reactor-http-nio-1
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:83)
	at reactor.core.publisher.Mono.block(Mono.java:1680)
	at com.azure.security.keyvault.keys.cryptography.CryptographyAsyncClient.ensureValidKeyAvailable(CryptographyAsyncClient.java:635)
	at com.azure.security.keyvault.keys.cryptography.CryptographyAsyncClient.unwrapKey(CryptographyAsyncClient.java:485)
	at com.azure.security.keyvault.keys.cryptography.CryptographyAsyncClient.lambda$unwrapKey$8(CryptographyAsyncClient.java:475)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:118)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:121)
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2344)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:162)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onSubscribe(MonoFlatMap.java:103)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:90)
	at reactor.core.publisher.MonoCurrentContext.subscribe(MonoCurrentContext.java:35)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:150)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:73)
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2344)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:2152)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onSubscribe(FluxOnErrorResume.java:68)
	at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:54)
	at reactor.core.publisher.Flux.subscribe(Flux.java:8325)
	at com.azure.core.util.FluxUtil.lambda$writeFile$8(FluxUtil.java:334)
	at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:57)
	at reactor.core.publisher.Flux.subscribe(Flux.java:8325)
	at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:199)
	at reactor.core.publisher.FluxFlatMap.subscribeOrReturn(FluxFlatMap.java:92)
	at reactor.core.publisher.Flux.subscribe(Flux.java:8311)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.drain(MonoIgnoreThen.java:172)
	at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:56)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:150)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:73)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1782)
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:241)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1782)
	at reactor.core.publisher.MonoZip$ZipCoordinator.signal(MonoZip.java:247)
	at reactor.core.publisher.MonoZip$ZipInner.onNext(MonoZip.java:329)
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2344)
	at reactor.core.publisher.MonoZip$ZipInner.onSubscribe(MonoZip.java:318)
	at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:54)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4213)
	at reactor.core.publisher.MonoZip.subscribe(MonoZip.java:128)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:150)
	at reactor.core.publisher.MonoSubscribeOn$SubscribeOnSubscriber.onNext(MonoSubscribeOn.java:144)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:121)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:121)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1782)
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:241)
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:67)
	at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onNext(FluxHide.java:127)
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:67)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1782)
	at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.signalCached(MonoCacheTime.java:320)
	at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.onNext(MonoCacheTime.java:337)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:73)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1782)
	at reactor.core.publisher.MonoCallable.subscribe(MonoCallable.java:61)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
	at reactor.core.publisher.MonoCacheTime.subscribeOrReturn(MonoCacheTime.java:132)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4198)
	at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:202)
	at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:150)
	at reactor.core.publisher.FluxContextStart$ContextStartSubscriber.onNext(FluxContextStart.java:96)
	at reactor.core.publisher.FluxDoOnEach$DoOnEachSubscriber.onNext(FluxDoOnEach.java:159)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1782)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:144)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1782)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:144)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:73)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1782)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:144)
	at reactor.core.publisher.FluxDelaySubscription$DelaySubscriptionMainSubscriber.onNext(FluxDelaySubscription.java:180)
	at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:99)
	at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:99)
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.onNext(FluxTimeout.java:173)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:121)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:121)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1782)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:144)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1782)
	at reactor.core.publisher.MonoSingle$SingleSubscriber.onComplete(MonoSingle.java:171)
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2346)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onSubscribeInner(MonoFlatMapMany.java:143)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onNext(MonoFlatMapMany.java:182)
	at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:99)
	at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.onNext(FluxRetryWhen.java:162)
	at reactor.core.publisher.MonoCreate$DefaultMonoSink.success(MonoCreate.java:156)
	at reactor.netty.http.client.HttpClientConnect$HttpIOHandlerObserver.onStateChange(HttpClientConnect.java:431)
	at reactor.netty.ReactorNetty$CompositeConnectionObserver.onStateChange(ReactorNetty.java:514)
	at reactor.netty.resources.PooledConnectionProvider$DisposableAcquire.onStateChange(PooledConnectionProvider.java:540)
	at reactor.netty.resources.PooledConnectionProvider$PooledConnection.onStateChange(PooledConnectionProvider.java:427)
	at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:574)
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:96)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:425)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1526)
	at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1287)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1324)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:832)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
		at reactor.core.publisher.Mono.block(Mono.java:1680)
		at com.azure.storage.common.implementation.StorageImplUtils.blockWithOptionalTimeout(StorageImplUtils.java:99)
		at com.azure.storage.blob.specialized.BlobClientBase.downloadToFileWithResponse(BlobClientBase.java:630)
		at com.azure.storage.blob.specialized.BlobClientBase.downloadToFile(BlobClientBase.java:561)
		at blobclient.BlobEncryptionExample.main(BlobEncryptionExample.java:147)

**To Reproduce**

***Code Snippet***
		//String connectionString ="connectionstring_sharedKey";
		//String containerName = "democontainer"; 
		//String keyId = "https://keyvaultsample.vault.azure.net/keys/key1/guid";
		
		AsyncKeyEncryptionKey akey = new KeyEncryptionKeyClientBuilder()
				  .credential(new DefaultAzureCredentialBuilder().build())
				  .buildAsyncKeyEncryptionKey(keyId).block();
		AsyncKeyEncryptionKeyResolver aKeyResolver = new AsyncKeyEncryptionKeyResolver() {
		      // @Override
		      public Mono<? extends AsyncKeyEncryptionKey> buildAsyncKeyEncryptionKey(String keyId) {
		    	  return Mono.just(akey);
		      }
		    };
		EncryptedBlobClient client = new EncryptedBlobClientBuilder().key(akey, KeyWrapAlgorithm.RSA_OAEP.toString()).keyResolver(aKeyResolver)
		    .connectionString(connectionString)
	        .containerName(containerName).blobName("Test.txt").buildEncryptedBlobClient();
		
//		startTime = System.currentTimeMillis();
//		client.uploadFromFile("c:\\control.txt"); // Upload a local file to storage.
//		endTime = System.currentTimeMillis();
//		System.out.println("Encrypted blob upload time: "+ (double)(endTime-startTime)/1000);
		
		startTime = System.currentTimeMillis();
		client.downloadToFile("c:\\temp\\download.txt", true);
		endTime = System.currentTimeMillis();
		System.out.println("Download and Decrypt zip took time: "+ (double)(endTime-startTime)/1000);

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - IDE : [e.g. IntelliJ]
 - Version of the Library used

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by gapra-msft** [comment]
Hi @yangchengs 

Could you provide details about the version of the library you are using? A bug fix went out recently that fixed a similar issue you are describing. 

Thanks

**Comment by yangchengs** [comment]
> Hi @yangchengs
> 
> Could you provide details about the version of the library you are using? A bug fix went out recently that fixed a similar issue you are describing.
> 
> Thanks

<dependency>
	    <groupId>com.azure</groupId>
	    <artifactId>azure-storage-blob-cryptography</artifactId>
	    <version>12.8.0</version>
	</dependency>
	
  	<dependency>
	    <groupId>com.azure</groupId>
	    <artifactId>azure-security-keyvault-keys</artifactId>
	    <version>4.1.5</version>
	</dependency>
	
  	<dependency>
      <groupId>com.azure</groupId>
      <artifactId>azure-security-keyvault-secrets</artifactId>
      <version>4.1.5</version>
    </dependency>

    <dependency>
      <groupId>com.azure</groupId>
      <artifactId>azure-identity</artifactId>
      <version>1.0.8</version>
    </dependency>

**Comment by yangchengs** [comment]
> Hi @yangchengs
> 
> Could you provide details about the version of the library you are using? A bug fix went out recently that fixed a similar issue you are describing.
> 
> Thanks
____________________________________
<dependency>
	    <groupId>com.azure</groupId>
	    <artifactId>azure-storage-blob-cryptography</artifactId>
	    <version>12.8.0</version>
	</dependency>
	
  	<dependency>
	    <groupId>com.azure</groupId>
	    <artifactId>azure-security-keyvault-keys</artifactId>
	    <version>4.1.5</version>
	</dependency>
	
  	<dependency>
      <groupId>com.azure</groupId>
      <artifactId>azure-security-keyvault-secrets</artifactId>
      <version>4.1.5</version>
    </dependency>

    <dependency>
      <groupId>com.azure</groupId>
      <artifactId>azure-identity</artifactId>
      <version>1.0.8</version>
    </dependency>

**Comment by yangchengs** [comment]
> Hi @yangchengs
> 
> Could you provide details about the version of the library you are using? A bug fix went out recently that fixed a similar issue you are describing.
> 
> Thanks
<><><><>
<dependency>
	    <groupId>com.azure</groupId>
	    <artifactId>azure-storage-blob-cryptography</artifactId>
	    <version>12.8.0</version>
	</dependency>
	
  	<dependency>
	    <groupId>com.azure</groupId>
	    <artifactId>azure-security-keyvault-keys</artifactId>
	    <version>4.1.5</version>
	</dependency>
	
  	<dependency>
      <groupId>com.azure</groupId>
      <artifactId>azure-security-keyvault-secrets</artifactId>
      <version>4.1.5</version>
    </dependency>

    <dependency>
      <groupId>com.azure</groupId>
      <artifactId>azure-identity</artifactId>
      <version>1.0.8</version>
    </dependency>

**Comment by yangchengs** [comment]
> Hi @yangchengs
> 
> Could you provide details about the version of the library you are using? A bug fix went out recently that fixed a similar issue you are describing.
> 
> Thanks

<dependency>
    <groupId>org.slf4j</groupId>
    <artifactId>slf4j-simple</artifactId>
    <version>1.6.1</version>
</dependency>
  	<dependency>
	    <groupId>com.azure</groupId>
	    <artifactId>azure-storage-blob-cryptography</artifactId>
	    <version>12.8.0</version>
	</dependency>
	
  	<dependency>
	    <groupId>com.azure</groupId>
	    <artifactId>azure-security-keyvault-keys</artifactId>
	    <version>4.1.5</version>
	</dependency>
	
  	<dependency>
      <groupId>com.azure</groupId>
      <artifactId>azure-security-keyvault-secrets</artifactId>
      <version>4.1.5</version>
    </dependency>

    <dependency>
      <groupId>com.azure</groupId>
      <artifactId>azure-identity</artifactId>
      <version>1.0.8</version>
    </dependency>

**Comment by yangchengs** [comment]
<dependency>
    <groupId>org.slf4j</groupId>
    <artifactId>slf4j-simple</artifactId>
    <version>1.6.1</version>
</dependency>
  	<dependency>
	    <groupId>com.azure</groupId>
	    <artifactId>azure-storage-blob-cryptography</artifactId>
	    <version>12.8.0</version>
	</dependency>
	
  	<dependency>
	    <groupId>com.azure</groupId>
	    <artifactId>azure-security-keyvault-keys</artifactId>
	    <version>4.1.5</version>
	</dependency>
	
  	<dependency>
      <groupId>com.azure</groupId>
      <artifactId>azure-security-keyvault-secrets</artifactId>
      <version>4.1.5</version>
    </dependency>

    <dependency>
      <groupId>com.azure</groupId>
      <artifactId>azure-identity</artifactId>
      <version>1.0.8</version>
    </dependency>

**Comment by yangchengs** [comment]
> Hi @yangchengs
> 
> Could you provide details about the version of the library you are using? A bug fix went out recently that fixed a similar issue you are describing.
> 
> Thanks
  <dependencies>
  	<dependency>
	    <groupId>com.azure</groupId>
	    <artifactId>azure-storage-blob-cryptography</artifactId>
	    <version>12.8.0</version>
	</dependency>
	
  	<dependency>
	    <groupId>com.azure</groupId>
	    <artifactId>azure-security-keyvault-keys</artifactId>
	    <version>4.1.5</version>
	</dependency>
	
  	<dependency>
      <groupId>com.azure</groupId>
      <artifactId>azure-security-keyvault-secrets</artifactId>
      <version>4.1.5</version>
    </dependency>

    <dependency>
      <groupId>com.azure</groupId>
      <artifactId>azure-identity</artifactId>
      <version>1.0.8</version>
    </dependency>
  </dependencies>

**Comment by gapra-msft** [comment]
This looks to be the same issue as [this ](https://github.com/Azure/azure-sdk-for-java/issues/14482)
@vcolin7 Could you please confirm?

**Comment by yangchengs** [comment]
azure-security-keyvault-keys version 4.1.5 has the issue.
4.2.1 does not have this problem.

**Comment by vcolin7** [comment]
Hi @gapra-msft and @yangchengs, it indeed looks like the issue you mentioned. It's good to know that you didn't find this problem in version `4.2.1`. I will look into what changed in the `CryptograpyhAsyncClient` between releases and check if there are other places this might happen.

**Comment by vcolin7** [comment]
I just had a look and it turns our that we had a change made in beta a while ago to avoid blocking in `ensureValidKeyAvailable()` that was just released as stable in version `4.2.0`. 

@yangchengs Thanks for being in touch with us and sorry for the late reply. Let me know if you encounter any further issues :)
