### ISSUE TITLE
[BUG] Azure context - NullPointerException due to wrong check when MSI is enabled (region is checked instead of subscription id)

### ISSUE THREAD

**Issue by avpines** [Azure/azure-sdk-for-java#15435]
**Describe the bug**
When MSI is enabled even though region is not mandatory, validation accidentally checks for it instead of subscription-id. In AzureProperties.java:
```
if (msiEnabled && Strings.isNullOrEmpty(subscriptionId)) {
    Assert.hasText(this.region, "When msi is enabled, spring.cloud.azure.subscription-id must be provided");
}
```
The assertion should use the subscription id instead of region:
```
Assert.hasText(this.subscriptionId, "When msi is enabled, spring.cloud.azure.subscription-id must be provided");
```
This causes a NullPointerException when region is not given.

***Exception or Stack Trace***
```
Caused by: java.lang.NullPointerException: null
    at com.microsoft.azure.spring.cloud.autoconfigure.servicebus.ServiceBusUtils.getNamespace(ServiceBusUtils.java:12)
    at com.microsoft.azure.spring.cloud.autoconfigure.servicebus.AzureServiceBusQueueAutoConfiguration.queueClientFactory(AzureServiceBusQueueAutoConfiguration.java:60)
    at com.microsoft.azure.spring.cloud.autoconfigure.servicebus.AzureServiceBusQueueAutoConfiguration$$EnhancerBySpringCGLIB$$41f13fa0.CGLIB$queueClientFactory$1(<generated>)
    at com.microsoft.azure.spring.cloud.autoconfigure.servicebus.AzureServiceBusQueueAutoConfiguration$$EnhancerBySpringCGLIB$$41f13fa0$$FastClassBySpringCGLIB$$f041ed51.invoke(<generated>)
    at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
    at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
    at com.microsoft.azure.spring.cloud.autoconfigure.servicebus.AzureServiceBusQueueAutoConfiguration$$EnhancerBySpringCGLIB$$41f13fa0.queueClientFactory(<generated>)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
    ... 58 common frames omitted
```

**To Reproduce**
Create an application.yaml that uses a namespace without a region, e.g.:

```
spring:
  cloud:
    azure:
      msi-enabled: true
      resource-group: discovery
      subscription-id: <subscription_id>
      service-bus:
        namespace: <namespace>
    stream:
      function:
        definition: produce
      bindings:
        produce-out-0:
          destination: my-queue
```

**Expected behavior**
Region should not be enforced when auto-create is enabled.

**Setup (please complete the following information):**
 - OS: Linux on AKS
 - 1.2.7, 1.2.8

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by zhoufenqin** [comment]
hi @avpines, we have fix the problem, but the library will be released a few weeks later

**Comment by avpines** [comment]
@zhoufenqin - Thanks! Do you know when and in what release the fix will be available?

**Comment by zhoufenqin** [comment]
hi @avpines, this may be released in the middle of October(not decided yet), and the release version is 3.0.0, we'll update the Spring Initializr when the package release. Thank you for your feedback

**Comment by avpines** [comment]
@zhoufenqin thanks! Will it be 3.0.0 or 1.3.0 (next release of the Service Bus Spring Cloud Stream binder)?

**Comment by zhoufenqin** [comment]
@saragluna could you follow up on this issue?
