### ISSUE TITLE
[QUERY] Provider com.bea.xml.stream.MXParserFactory not found When initiating ClientCertificateCredential

### ISSUE THREAD

**Issue by thebenwaters** [Azure/azure-sdk-for-java#15486]
**Query/Question**
I seem to be having similar issues to #6313

I'm developing a storage plugin for [Rundeck](https://github.com/rundeck/rundeck) and trying to use the azure-identity and azure-keyvault-secrets sdk

I'm getting the following errors
```
Caused by: javax.xml.stream.FactoryConfigurationError: Provider com.bea.xml.stream.MXParserFactory not found
        at javax.xml.stream.FactoryFinder.newInstance(FactoryFinder.java:72) ~[?:?]
        at javax.xml.stream.FactoryFinder.find(FactoryFinder.java:178) ~[?:?]
        at javax.xml.stream.FactoryFinder.find(FactoryFinder.java:92) ~[?:?]
        at javax.xml.stream.XMLInputFactory.newInstance(XMLInputFactory.java:136) ~[?:?]
        at com.fasterxml.jackson.dataformat.xml.XmlFactory.<init>(XmlFactory.java:113) ~[?:?]
        at com.fasterxml.jackson.dataformat.xml.XmlFactory.<init>(XmlFactory.java:100) ~[?:?]
        at com.fasterxml.jackson.dataformat.xml.XmlFactory.<init>(XmlFactory.java:84) ~[?:?]
        at com.fasterxml.jackson.dataformat.xml.XmlMapper.<init>(XmlMapper.java:122) ~[?:?]
        at com.azure.core.util.serializer.JacksonAdapter.<init>(JacksonAdapter.java:76) ~[?:?]
        at com.azure.core.util.serializer.JacksonAdapter.createDefaultSerializerAdapter(JacksonAdapter.java:112) ~[?:?]
        at com.azure.identity.implementation.IdentityClient.<clinit>(IdentityClient.java:89) ~[?:?]
        at com.azure.identity.implementation.IdentityClientBuilder.build(IdentityClientBuilder.java:99) ~[?:?]
        at com.azure.identity.ClientCertificateCredential.<init>(ClientCertificateCredential.java:50) ~[?:?]
        at com.azure.identity.ClientCertificateCredentialBuilder.build(ClientCertificateCredentialBuilder.java:79) ~[?:?]
```

My gradle config

```
dependencies {
    compile 'org.rundeck:rundeck-storage-api:3.3.3-20200910'
    compile "org.rundeck:rundeck-core:3.3.3-20200910"
    pluginLibs group: "com.azure", name: "azure-identity", version: "1.1.2"
    pluginLibs group: "com.azure", name: "azure-security-keyvault-secrets", version: "4.2.1"
    pluginLibs group: "org.apache.logging.log4j", name: "log4j-slf4j-impl", version: "2.0"
    pluginLibs group: "com.fasterxml.jackson.dataformat", name: "jackson-dataformat-xml", version: "2.11.2"
    pluginLibs group: "com.fasterxml.jackson.core", name: "jackson-databind", version: "2.11.2"
    runtime group: 'org.slf4j', name: 'slf4j-api', version: '1.7.30'
}
```

And my dependency tree

```
+--- org.rundeck:rundeck-storage-api:3.3.3-20200910
+--- org.rundeck:rundeck-core:3.3.3-20200910
|    +--- org.rundeck:rundeck-storage-api:3.3.3-20200910
|    +--- org.rundeck:rundeck-storage-conf:3.3.3-20200910
|    |    \--- org.rundeck:rundeck-storage-data:3.3.3-20200910
|    |         \--- org.rundeck:rundeck-storage-api:3.3.3-20200910
|    +--- org.rundeck:rundeck-authz-api:3.3.3-20200910
|    +--- org.rundeck:rundeck-authz-core:3.3.3-20200910
|    |    \--- org.rundeck:rundeck-authz-api:3.3.3-20200910
|    +--- org.rundeck:rundeck-authz-yaml:3.3.3-20200910
|    |    +--- org.rundeck:rundeck-authz-api:3.3.3-20200910
|    |    +--- org.rundeck:rundeck-authz-core:3.3.3-20200910 (*)
|    |    \--- org.yaml:snakeyaml:1.26
|    +--- com.google.guava:guava:24.1.1-jre
|    |    +--- com.google.code.findbugs:jsr305:1.3.9
|    |    +--- org.checkerframework:checker-compat-qual:2.0.0
|    |    +--- com.google.errorprone:error_prone_annotations:2.1.3
|    |    +--- com.google.j2objc:j2objc-annotations:1.1
|    |    \--- org.codehaus.mojo:animal-sniffer-annotations:1.14
|    +--- org.apache.ant:ant:1.9.15
|    |    \--- org.apache.ant:ant-launcher:1.9.15
|    +--- org.slf4j:slf4j-api:1.7.30
|    +--- commons-codec:commons-codec:1.11
|    +--- commons-beanutils:commons-beanutils:1.9.4
|    |    +--- commons-logging:commons-logging:1.2
|    |    \--- commons-collections:commons-collections:3.2.2
|    +--- commons-collections:commons-collections:3.2.2
|    +--- commons-lang:commons-lang:2.6
|    +--- org.dom4j:dom4j:2.1.3
|    |    +--- jaxen:jaxen:1.1.6
|    |    +--- javax.xml.stream:stax-api:1.0-2
|    |    +--- net.java.dev.msv:xsdlib:2013.6.1
|    |    |    \--- relaxngDatatype:relaxngDatatype:20020414
|    |    +--- javax.xml.bind:jaxb-api:2.2.12
|    |    +--- pull-parser:pull-parser:2
|    |    \--- xpp3:xpp3:1.1.4c
|    +--- jaxen:jaxen:1.1.6
|    +--- commons-cli:commons-cli:1.0
|    |    +--- commons-logging:commons-logging:1.0 -> 1.2
|    |    \--- commons-lang:commons-lang:1.0 -> 2.6
|    +--- org.apache.ant:ant-jsch:1.9.15
|    |    +--- org.apache.ant:ant:1.9.15 (*)
|    |    \--- com.jcraft:jsch:0.1.55
|    +--- com.jcraft:jsch:0.1.55
|    +--- com.jcraft:jsch.agentproxy.jsch:0.0.9
|    |    +--- com.jcraft:jsch:0.1.49 -> 0.1.55
|    |    \--- com.jcraft:jsch.agentproxy.core:0.0.9
|    +--- com.jcraft:jsch.agentproxy.sshagent:0.0.9
|    |    \--- com.jcraft:jsch.agentproxy.core:0.0.9
|    +--- com.jcraft:jsch.agentproxy.usocket-jna:0.0.9
|    |    +--- com.jcraft:jsch.agentproxy.core:0.0.9
|    |    +--- net.java.dev.jna:jna:4.1.0 -> 5.5.0
|    |    \--- net.java.dev.jna:jna-platform:4.1.0 -> 5.5.0
|    |         \--- net.java.dev.jna:jna:5.5.0
|    +--- com.jcraft:jsch.agentproxy.usocket-nc:0.0.9
|    |    \--- com.jcraft:jsch.agentproxy.core:0.0.9
|    +--- com.jcraft:jsch.agentproxy.connector-factory:0.0.9
|    |    +--- com.jcraft:jsch.agentproxy.core:0.0.9
|    |    +--- com.jcraft:jsch.agentproxy.usocket-jna:0.0.9 (*)
|    |    +--- com.jcraft:jsch.agentproxy.usocket-nc:0.0.9 (*)
|    |    +--- com.jcraft:jsch.agentproxy.sshagent:0.0.9 (*)
|    |    \--- com.jcraft:jsch.agentproxy.pageant:0.0.9
|    |         +--- com.jcraft:jsch.agentproxy.core:0.0.9
|    |         +--- net.java.dev.jna:jna:4.1.0 -> 5.5.0
|    |         \--- net.java.dev.jna:jna-platform:4.1.0 -> 5.5.0 (*)
|    +--- com.jcraft:jsch.agentproxy.core:0.0.9
|    +--- com.fasterxml.jackson.core:jackson-databind:2.10.1 -> 2.11.2
|    |    +--- com.fasterxml.jackson.core:jackson-annotations:2.11.2
|    |    \--- com.fasterxml.jackson.core:jackson-core:2.11.2
|    +--- org.yaml:snakeyaml:1.26
|    +--- com.squareup.retrofit2:retrofit:2.7.2
|    |    \--- com.squareup.okhttp3:okhttp:3.14.7
|    |         \--- com.squareup.okio:okio:1.17.2
|    +--- com.squareup.retrofit2:converter-jackson:2.7.2
|    |    +--- com.squareup.retrofit2:retrofit:2.7.2 (*)
|    |    \--- com.fasterxml.jackson.core:jackson-databind:2.10.1 -> 2.11.2 (*)
|    +--- javax.servlet:javax.servlet-api:4.0.1
|    \--- commons-httpclient:commons-httpclient:3.1
|         +--- commons-logging:commons-logging:1.0.4 -> 1.2
|         \--- commons-codec:commons-codec:1.2 -> 1.11
+--- com.azure:azure-identity:1.1.2
|    +--- com.azure:azure-core:1.8.1
|    |    +--- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.11.2
|    |    |    +--- com.fasterxml.jackson.core:jackson-annotations:2.11.2
|    |    |    +--- com.fasterxml.jackson.core:jackson-core:2.11.2
|    |    |    \--- com.fasterxml.jackson.core:jackson-databind:2.11.2 (*)
|    |    +--- com.fasterxml.jackson.dataformat:jackson-dataformat-xml:2.11.2
|    |    |    +--- com.fasterxml.jackson.core:jackson-core:2.11.2
|    |    |    +--- com.fasterxml.jackson.core:jackson-annotations:2.11.2
|    |    |    +--- com.fasterxml.jackson.core:jackson-databind:2.11.2 (*)
|    |    |    +--- com.fasterxml.jackson.module:jackson-module-jaxb-annotations:2.11.2
|    |    |    |    +--- com.fasterxml.jackson.core:jackson-annotations:2.11.2
|    |    |    |    +--- com.fasterxml.jackson.core:jackson-core:2.11.2
|    |    |    |    +--- com.fasterxml.jackson.core:jackson-databind:2.11.2 (*)
|    |    |    |    +--- jakarta.xml.bind:jakarta.xml.bind-api:2.3.2
|    |    |    |    |    \--- jakarta.activation:jakarta.activation-api:1.2.1
|    |    |    |    \--- jakarta.activation:jakarta.activation-api:1.2.1
|    |    |    +--- org.codehaus.woodstox:stax2-api:4.2.1
|    |    |    \--- com.fasterxml.woodstox:woodstox-core:6.2.1
|    |    |         \--- org.codehaus.woodstox:stax2-api:4.2.1
|    |    +--- org.slf4j:slf4j-api:1.7.30
|    |    +--- io.projectreactor:reactor-core:3.3.9.RELEASE
|    |    |    \--- org.reactivestreams:reactive-streams:1.0.3
|    |    \--- io.netty:netty-tcnative-boringssl-static:2.0.31.Final
|    +--- com.microsoft.azure:msal4j:1.6.2
|    |    +--- com.nimbusds:oauth2-oidc-sdk:7.4
|    |    |    +--- com.github.stephenc.jcip:jcip-annotations:1.0-1
|    |    |    +--- com.nimbusds:content-type:2.0
|    |    |    +--- net.minidev:json-smart:[1.3.1,2.3] -> 2.3
|    |    |    |    \--- net.minidev:accessors-smart:1.2
|    |    |    |         \--- org.ow2.asm:asm:5.0.4
|    |    |    +--- com.nimbusds:lang-tag:1.4.4
|    |    |    +--- com.nimbusds:nimbus-jose-jwt:8.14.1
|    |    |    |    +--- com.github.stephenc.jcip:jcip-annotations:1.0-1
|    |    |    |    \--- net.minidev:json-smart:[1.3.1,2.3] -> 2.3 (*)
|    |    |    \--- com.sun.mail:javax.mail:1.6.1
|    |    |         \--- javax.activation:activation:1.1
|    |    +--- org.slf4j:slf4j-api:1.7.28 -> 1.7.30
|    |    \--- com.fasterxml.jackson.core:jackson-databind:2.10.1 -> 2.11.2 (*)
|    +--- com.microsoft.azure:msal4j-persistence-extension:1.0.0
|    |    +--- com.microsoft.azure:msal4j:1.4.0 -> 1.6.2 (*)
|    |    +--- net.java.dev.jna:jna:5.5.0
|    |    +--- net.java.dev.jna:jna-platform:5.5.0 (*)
|    |    \--- org.slf4j:slf4j-api:1.7.7 -> 1.7.30
|    +--- com.nimbusds:oauth2-oidc-sdk:7.1.1 -> 7.4 (*)
|    +--- org.nanohttpd:nanohttpd:2.3.1
|    +--- net.java.dev.jna:jna-platform:5.4.0 -> 5.5.0 (*)
|    \--- org.linguafranca.pwdb:KeePassJava2:2.1.4
|         +--- org.linguafranca.pwdb:KeePassJava2-kdb:2.1.4
|         |    +--- org.linguafranca.pwdb:database:2.1.4
|         |    |    +--- org.jetbrains:annotations:15.0
|         |    |    +--- com.google.guava:guava:19.0 -> 24.1.1-jre (*)
|         |    |    \--- com.madgag.spongycastle:core:1.54.0.0
|         |    \--- org.jetbrains:annotations:15.0
|         +--- org.linguafranca.pwdb:KeePassJava2-dom:2.1.4
|         |    \--- org.linguafranca.pwdb:KeePassJava2-kdbx:2.1.4
|         |         +--- org.linguafranca.pwdb:database:2.1.4 (*)
|         |         +--- commons-codec:commons-codec:1.10 -> 1.11
|         |         \--- org.jetbrains:annotations:15.0
|         +--- org.linguafranca.pwdb:KeePassJava2-jaxb:2.1.4
|         |    \--- org.linguafranca.pwdb:KeePassJava2-kdbx:2.1.4 (*)
|         \--- org.linguafranca.pwdb:KeePassJava2-simple:2.1.4
|              +--- org.linguafranca.pwdb:KeePassJava2-kdbx:2.1.4 (*)
|              +--- org.simpleframework:simple-xml:2.7.1
|              |    +--- stax:stax-api:1.0.1
|              |    +--- stax:stax:1.2.0
|              |    |    \--- stax:stax-api:1.0.1
|              |    \--- xpp3:xpp3:1.1.3.3 -> 1.1.4c
|              +--- org.apache.httpcomponents:httpcore:4.4.5
|              \--- com.fasterxml:aalto-xml:1.0.0
|                   \--- org.codehaus.woodstox:stax2-api:4.0.0 -> 4.2.1
+--- com.azure:azure-security-keyvault-secrets:4.2.1
|    +--- com.azure:azure-core:1.8.1 (*)
|    \--- com.azure:azure-core-http-netty:1.6.1
|         +--- com.azure:azure-core:1.8.1 (*)
|         +--- io.netty:netty-handler:4.1.51.Final
|         |    +--- io.netty:netty-common:4.1.51.Final
|         |    +--- io.netty:netty-resolver:4.1.51.Final
|         |    |    \--- io.netty:netty-common:4.1.51.Final
|         |    +--- io.netty:netty-buffer:4.1.51.Final
|         |    |    \--- io.netty:netty-common:4.1.51.Final
|         |    +--- io.netty:netty-transport:4.1.51.Final
|         |    |    +--- io.netty:netty-common:4.1.51.Final
|         |    |    +--- io.netty:netty-buffer:4.1.51.Final (*)
|         |    |    \--- io.netty:netty-resolver:4.1.51.Final (*)
|         |    \--- io.netty:netty-codec:4.1.51.Final
|         |         +--- io.netty:netty-common:4.1.51.Final
|         |         +--- io.netty:netty-buffer:4.1.51.Final (*)
|         |         \--- io.netty:netty-transport:4.1.51.Final (*)
|         +--- io.netty:netty-handler-proxy:4.1.51.Final
|         |    +--- io.netty:netty-common:4.1.51.Final
|         |    +--- io.netty:netty-buffer:4.1.51.Final (*)
|         |    +--- io.netty:netty-transport:4.1.51.Final (*)
|         |    +--- io.netty:netty-codec:4.1.51.Final (*)
|         |    +--- io.netty:netty-codec-socks:4.1.51.Final
|         |    |    +--- io.netty:netty-common:4.1.51.Final
|         |    |    +--- io.netty:netty-buffer:4.1.51.Final (*)
|         |    |    +--- io.netty:netty-transport:4.1.51.Final (*)
|         |    |    \--- io.netty:netty-codec:4.1.51.Final (*)
|         |    \--- io.netty:netty-codec-http:4.1.51.Final
|         |         +--- io.netty:netty-common:4.1.51.Final
|         |         +--- io.netty:netty-buffer:4.1.51.Final (*)
|         |         +--- io.netty:netty-transport:4.1.51.Final (*)
|         |         +--- io.netty:netty-codec:4.1.51.Final (*)
|         |         \--- io.netty:netty-handler:4.1.51.Final (*)
|         +--- io.netty:netty-buffer:4.1.51.Final (*)
|         +--- io.netty:netty-codec-http:4.1.51.Final (*)
|         +--- io.netty:netty-codec-http2:4.1.51.Final
|         |    +--- io.netty:netty-common:4.1.51.Final
|         |    +--- io.netty:netty-buffer:4.1.51.Final (*)
|         |    +--- io.netty:netty-transport:4.1.51.Final (*)
|         |    +--- io.netty:netty-codec:4.1.51.Final (*)
|         |    +--- io.netty:netty-handler:4.1.51.Final (*)
|         |    \--- io.netty:netty-codec-http:4.1.51.Final (*)
|         +--- io.netty:netty-transport-native-unix-common:4.1.51.Final
|         |    +--- io.netty:netty-common:4.1.51.Final
|         |    +--- io.netty:netty-buffer:4.1.51.Final (*)
|         |    \--- io.netty:netty-transport:4.1.51.Final (*)
|         +--- io.netty:netty-transport-native-epoll:4.1.51.Final
|         |    +--- io.netty:netty-common:4.1.51.Final
|         |    +--- io.netty:netty-buffer:4.1.51.Final (*)
|         |    +--- io.netty:netty-transport:4.1.51.Final (*)
|         |    \--- io.netty:netty-transport-native-unix-common:4.1.51.Final (*)
|         +--- io.netty:netty-transport-native-kqueue:4.1.51.Final
|         |    +--- io.netty:netty-common:4.1.51.Final
|         |    +--- io.netty:netty-buffer:4.1.51.Final (*)
|         |    +--- io.netty:netty-transport:4.1.51.Final (*)
|         |    \--- io.netty:netty-transport-native-unix-common:4.1.51.Final (*)
|         \--- io.projectreactor.netty:reactor-netty:0.9.11.RELEASE
|              +--- io.netty:netty-codec-http:4.1.51.Final (*)
|              +--- io.netty:netty-codec-http2:4.1.51.Final (*)
|              +--- io.netty:netty-handler:4.1.51.Final (*)
|              +--- io.netty:netty-handler-proxy:4.1.51.Final (*)
|              +--- io.netty:netty-transport-native-epoll:4.1.51.Final (*)
|              \--- io.projectreactor:reactor-core:3.3.9.RELEASE (*)
+--- org.apache.logging.log4j:log4j-slf4j-impl:2.0
|    +--- org.slf4j:slf4j-api:1.7.7 -> 1.7.30
|    \--- org.apache.logging.log4j:log4j-api:2.0
+--- com.fasterxml.jackson.dataformat:jackson-dataformat-xml:2.11.2 (*)
+--- com.fasterxml.jackson.core:jackson-databind:2.11.2 (*)
\--- org.slf4j:slf4j-api:1.7.30
```

Any tips on beating this? I tried forcing the version, but it doesn't seem to work

***Why is this not a Bug or a feature Request?***

I have a feeling that it's not a bug and something related to Spring / Rundeck / Plugin Path

**Setup (please complete the following information if applicable):**
 - OS: Windows 10
 - IDE : Intellij
```    pluginLibs group: "com.azure", name: "azure-identity", version: "1.1.2"
    pluginLibs group: "com.azure", name: "azure-security-keyvault-secrets", version: "4.2.1"
```
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Query Added
- [X] Setup information Added

**Comment by thebenwaters** [comment]
Note that Rundeck uses spring 5 / spring boot / grails under the hood

**Comment by alzimmermsft** [comment]
Hi @thebenwaters, it looks like this issue happens while looking for a class in the classpath, do you mind running your repro again with the system property `jaxp.debug` set to `true`? This should add more debugging output to go along with the stack trace.

**Comment by thebenwaters** [comment]
```
[2020-09-23T09:39:12,118] WARN  azurekeyvaultstorage.AzureKeyVaultStoragePlugin - DocumentBuilderFactory implementation: com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderFactoryImpl loaded from: Java Runtime
JAXP: using thread context class loader (org.springframework.boot.loader.LaunchedURLClassLoader@5010be6) for search
JAXP: Looking up system property 'javax.xml.xpath.XPathFactory:http://java.sun.com/jaxp/xpath/dom'
JAXP: The property is undefined.
JAXP: found null in $java.home/conf/jaxp.properties
JAXP: attempting to use the platform default W3C DOM XPath lib
JAXP: factory 'com.sun.org.apache.xpath.internal.jaxp.XPathFactoryImpl' was found for http://java.sun.com/jaxp/xpath/dom
[2020-09-23T09:39:12,131] WARN  azurekeyvaultstorage.AzureKeyVaultStoragePlugin - XPathFactory implementation: com.sun.org.apache.xpath.internal.jaxp.XPathFactoryImpl loaded from: Java Runtime
[2020-09-23T09:39:12,133] WARN  azurekeyvaultstorage.AzureKeyVaultStoragePlugin - TransformerFactory implementation: com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl loaded from: Java Runtime
[2020-09-23T09:39:12,135] WARN  azurekeyvaultstorage.AzureKeyVaultStoragePlugin - SAXParserFactory implementation: com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl loaded from: Java Runtime
```

**Comment by thebenwaters** [comment]
Succeeded

Success!

```
dependencies {
    compile 'org.rundeck:rundeck-storage-api:3.0.27-20191204'
    compile "org.rundeck:rundeck-core:3.0.27-20191204"
    pluginLibs(group: "com.azure", name: "azure-identity", version: "1.1.2"){
        exclude group:'org.slf4j', module: 'slf4j-api'
    }
    pluginLibs group: "com.azure", name: "azure-security-keyvault-secrets", version: "4.2.1"
    pluginLibs group: "org.apache.logging.log4j", name: "log4j-slf4j-impl", version: "2.0"
    pluginLibs group: "com.fasterxml.woodstox", name: "woodstox-core", version: "6.2.1"
    runtime group: 'org.slf4j', name: 'slf4j-api', version: '1.7.30'
    runtime group: "com.fasterxml.woodstox", name: "woodstox-core", version: "6.2.1"
}
```

`def libList = configurations.pluginLibs.findAll({!it.name.contains("stax")}).collect{'lib/'+it.name}.join(' ')`

**Comment by gilangarinata** [comment]
hi, how did u fixed this?

**Comment by beneshed** [comment]
@gilangarinata by adding this line to the gradle file

```def libList = configurations.pluginLibs.findAll({!it.name.contains("stax")}).collect{'lib/'+it.name}.join(' ')```
