### ISSUE TITLE
[QUERY] java.lang.IllegalAccessError: tried to access class reactor.core.publisher.FluxReplay$ReplaySubscription from class reactor.core.publisher.ReplayProcessor

### ISSUE THREAD

**Issue by abmo-x** [Azure/azure-sdk-for-java#15580]
**Query/Question**
Error initilaizing key vault client with access token. running into below error

***Why is this not a Bug or a feature Request?***
Running into this issue ONLY  when running on Azure Synapse. Works fine locally.

```
20/09/24 00:54:55 ERROR ApplicationMaster: User class threw exception: java.lang.IllegalAccessError: tried to access class reactor.core.publisher.FluxReplay$ReplaySubscription from class reactor.core.publisher.ReplayProcessor
java.lang.IllegalAccessError: tried to access class reactor.core.publisher.FluxReplay$ReplaySubscription from class reactor.core.publisher.ReplayProcessor
	at reactor.core.publisher.ReplayProcessor.<clinit>(ReplayProcessor.java:303)
	at com.azure.security.keyvault.secrets.implementation.ScopeTokenCache.<init>(ScopeTokenCache.java:21)
	at com.azure.security.keyvault.secrets.implementation.KeyVaultCredentialPolicy.<init>(KeyVaultCredentialPolicy.java:41)
	at com.azure.security.keyvault.secrets.SecretClientBuilder.buildAsyncClient(SecretClientBuilder.java:153)
	at com.azure.security.keyvault.secrets.SecretClientBuilder.buildClient(SecretClientBuilder.java:104)
```

I am initializing the client as:
```
new SecretClientBuilder()
                    .vaultUrl(keyVaultUrl.toString())
                    .credential(tokenRequestContext -> Mono.just(accessToken))
                    .buildClient();
```

**Setup (please complete the following information if applicable):**
 - OS: Windows
 - IDE : IntelliJ
- Java version: 1.8
 - <dependency>
    <groupId>com.azure</groupId>
    <artifactId>azure-security-keyvault-secrets</artifactId>
    <version>4.2.1</version>
</dependency>

**Comment by joshfree** [comment]
Thanks for filing this issue @abmo-x.  @vcolin7 could you please follow up?

/cc @jianghaolu as this relates to Azure Synapse

**Comment by vcolin7** [comment]
No problem, I will look into this.

**Comment by abmo-x** [comment]
@vcolin7 

I tried to get a token directly and ran into the same error from identity client:

```
Caused by: java.lang.IllegalAccessError: tried to access class reactor.core.publisher.FluxReplay$ReplaySubscription from class reactor.core.publisher.ReplayProcessor
	at reactor.core.publisher.ReplayProcessor.<clinit>(ReplayProcessor.java:303)
	at com.azure.identity.implementation.SynchronizedAccessor.<init>(SynchronizedAccessor.java:21)
	at com.azure.identity.implementation.IdentityClient.<init>(IdentityClient.java:154)
	at com.azure.identity.implementation.IdentityClientBuilder.build(IdentityClientBuilder.java:99)
	at com.azure.identity.ClientSecretCredential.<init>(ClientSecretCredential.java:50)
	at com.azure.identity.ClientSecretCredentialBuilder.build(ClientSecretCredentialBuilder.java:62)
```

```
ClientSecretCredential clientSecretCredential = new ClientSecretCredentialBuilder()
                .clientId(aadAppId)
                .clientSecret(aadAppSecret)
                .tenantId(tenantId)
                .build();
        Mono<AccessToken> token = clientSecretCredential.getToken(new TokenRequestContext().addScopes(scope));
        AccessToken accessToken = token.block(Duration.of(1, ChronoUnit.MINUTES));

```

**Comment by abmo-x** [comment]
@vcolin7 

I was able to resolve the issue by relocating azure sdk and reactor dependencies in my shaded jar as:
```
<relocation>
                                    <pattern>com.azure</pattern>
                                    <shadedPattern>dqs.com.azure</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>reactor</pattern>
                                    <shadedPattern>dqs.reactor</shadedPattern>
                                </relocation>
```

The error was very confusing and i was not able to guess that a version conflict was causing it.

**Comment by vcolin7** [comment]
Hi @abmo-x, I'm glad you were able to find a solution. Usually when an `IllegalAccessError` shows up it's because the class used at runtime is different than the one used at compile time, and the runtime code does not allow access to a given method or parameter (e.g. it's private or package-private). It makes sense that two different versions of the code were in conflict there. Just as a reference for anyone that encounters this issue, [here's a similar one](https://stackoverflow.com/questions/7076414/java-lang-illegalaccesserror-tried-to-access-method) on StackOverflow.
