### ISSUE TITLE
[BUG] com.azure.identity.ClientSecretCredential: Azure Identity => ERROR in getToken() call for scopes [https://vault.azure.net/.default]

### ISSUE THREAD

**Issue by sudharsan2020** [Azure/azure-sdk-for-java#15774]
**Describe the bug**
Getting an exception while trying to fetch the Keyvault secrets from the Keyvault using the library. I am using the **shaded version of the Keyvault library** provided in the link: https://github.com/Azure/azure-sdk-for-java/files/5151818/keyvaultshaded.zip

***Exception or Stack Trace***
```
ERROR [2020-09-28 11:46:15,015] com.azure.identity.ClientSecretCredential: Azure Identity => ERROR in getToken() call for scopes [https://vault.azure.net/.default]: java.util.Collections$SingletonList cannot be cast to java.lang.String
ERROR [2020-09-28 11:46:16,995] com.microsoft.aad.msal4j.ConfidentialClientApplication: [Correlation ID: c43bcbe7-7300-4eaf-adb9-8947f31bb201] Execution of class com.microsoft.aad.msal4j.AcquireTokenByAuthorizationGrantSupplier failed.
! java.lang.ClassCastException: java.util.Collections$SingletonList cannot be cast to java.lang.String
! at com.nimbusds.oauth2.sdk.util.URLUtils.serializeParameters(URLUtils.java:103)
! at com.microsoft.aad.msal4j.TokenRequestExecutor.createOauthHttpRequest(TokenRequestExecutor.java:51)
! at com.microsoft.aad.msal4j.TokenRequestExecutor.executeTokenRequest(TokenRequestExecutor.java:36)
! at com.microsoft.aad.msal4j.AbstractClientApplicationBase.acquireTokenCommon(AbstractClientApplicationBase.java:117)
! at com.microsoft.aad.msal4j.AcquireTokenByAuthorizationGrantSupplier.execute(AcquireTokenByAuthorizationGrantSupplier.java:63)
! at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:59)
! at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:17)
! at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
! at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596)
! at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
! at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
! at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
! at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
```

**To Reproduce**
Attached the 
- **maven dependency tree**: http://collabedit.com/g3a27
- **maven dependency xml**: http://collabedit.com/ss4q5

***Code Snippet***
Definition:

```package com.xyz.utils.core.azure.keyvault;

import com.azure.identity.ClientSecretCredential;
import com.azure.identity.ClientSecretCredentialBuilder;
import com.azure.security.keyvault.secrets.SecretClient;
import com.azure.security.keyvault.secrets.SecretClientBuilder;
import com.azure.security.keyvault.secrets.models.KeyVaultSecret;
import com.xyz.utils.core.models.azure.keyvault.KeyVaultSecretsRequestModel;
import com.xyz.utils.core.storage.blobstore.azure.exceptions.KeyVaultPropsNotSpecifiedException;
import com.xyz.utils.core.storage.blobstore.azure.exceptions.KeyVaultSecretNotSpecifiedException;
import com.microsoft.azure.keyvault.models.KeyVaultErrorException;
import org.apache.commons.lang3.StringUtils;
import java.util.List;
import java.util.stream.Collectors;
import java.util.ArrayList;
import com.azure.identity.DefaultAzureCredentialBuilder;


public class AzureKeyVaultStore {
    /*
     * Function to query the Azure Keyvault against the supplied list of keys
     * @param secretKeysList : List of secret keys to be queried against the Keyvault
     * @return : List of secrets fetched against the keys from the Keyvault
     * @throws Exception
     */
    public List<KeyVaultSecret> queryKeyVaultSecrets(List<String> secretKeysList) throws Exception {

        // Output list
        List<KeyVaultSecret> keyVaultSecretList = new ArrayList<>();

        // Query the environment variables required to connect to the Azure Keyvault
        KeyVaultSecretsRequestModel keyVaultRequestModel = readKeyVaultEnvironmentParameters();

        try {
            // Build the secret client
            SecretClient secretClient = getSecretClient(keyVaultRequestModel);
            return secretKeysList.stream().map(secretClient::getSecret).collect(Collectors.toList());
        } catch (Exception e) {
            throw new Exception();
        }
    }

    /*
     * Frame the KeyVaultSecretsRequestModel to query the Azure Keyvault with the required parameters
     * @return: KeyVaultSecretsRequestModel request to connect to the Azure Keyvault
     */
    private static KeyVaultSecretsRequestModel readKeyVaultEnvironmentParameters() {
        KeyVaultSecretsRequestModel keyVaultRequestModel = new KeyVaultSecretsRequestModel();
        keyVaultRequestModel.setKeyVaultName(String.format("https://%s.vault.azure.net",
                System.getenv("KeyVault__KeyVaultName")));
        keyVaultRequestModel.setAzureClientId(System.getenv("KeyVault__ClientId"));
        keyVaultRequestModel.setAzureClientSecret(System.getenv("KeyVault__ApplicationSecret"));
        keyVaultRequestModel.setAzureTenantId(System.getenv("AZURE_TENANT_ID"));
        return keyVaultRequestModel;
    }

    /*
     * Wrapper function to build and return the instance of Keyvault SecretClient
     * @param keyVaultRequestModel: KeyVaultSecretsRequestModel request to connect to the Azure Keyvault
     * @return
     */
    private static SecretClient getSecretClient(KeyVaultSecretsRequestModel keyVaultRequestModel) {

        // Build the Client credential
        ClientSecretCredential clientSecretCredential = new ClientSecretCredentialBuilder()
                .clientId(keyVaultRequestModel.getAzureClientId())
                .tenantId(keyVaultRequestModel.getAzureTenantId())
                .clientSecret(keyVaultRequestModel.getAzureClientSecret())
                .build();

        // Azure SDK client builders accept the credential as a parameter
        return new SecretClientBuilder()
                .vaultUrl(keyVaultRequestModel.getKeyVaultName())
                .credential(clientSecretCredential)
                .buildClient();
    }
}
```

**Calling Program:**

```
import com.xyz.utils.core.azure.keyvault.AzureKeyVaultStore;
import java.util.Arrays;
import java.util.List;

public class AzureKeyVaultStoreCore {
    public static void main(String[] args) throws Exception {

        // Get individual secret from Vault and print
        List<String> secretKeys = Arrays.asList("EnvironmentDatabaseConnectionString",
                "EnvironmentDatabaseMaxRetryDuration", "EnvironmentDatabaseName",
                "ApplicationInsights--InstrumentationKey");

        AzureKeyVaultStore azureKeyVaultStore = new AzureKeyVaultStore();
        List<KeyVaultSecret> keyVaultSecretList = azureKeyVaultStore.queryKeyVaultSecrets(secretKeys);
        for ( KeyVaultSecret keyVaultSecret : keyVaultSecretList) {
            System.out.println("Fetched secret: " + keyVaultSecret.getValue());
        }
    }
}
```

**Expected behavior**
Secrets should be fetched from the Keyvault

**Setup (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - IDE : IntelliJ
 - Version of the Library used: Java 1.8
    - openjdk version "1.8.0_265"
    - OpenJDK Runtime Environment (build 1.8.0_265-8u265-b01-0ubuntu2~18.04-b01)
    - OpenJDK 64-Bit Server VM (build 25.265-b01, mixed mode)

**Note**
- I've **already tried the steps** mentioned in this thread link: https://github.com/Azure/azure-sdk-for-java/issues/14349#issuecomment-683934682
- While trying to use the shaded package, I am getting into a different issue. 
- **Please help me to resolve the issue as this is impacting a client deliverable**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added:
- [x] Repro Steps Added: 
- [x] Setup information Added:

**Comment by joshfree** [comment]
Thanks for reporting this `Identity` client library issue @sudharsan2020.  @g2vinay can you please follow up?

**Comment by g2vinay** [comment]
Thanks, @sudharsan2020  for reporting this issue. 
I will investigate and update here.

**Comment by g2vinay** [comment]
@sudharsan2020 
I am not able to reproduce this issue with thesample code and the pom file config you provided.
The sample app I created using the code and pom file configuration above is able to fetch the secrets properly with the shaded KeyVault library.

Looking at your stack trace, I believe there is a potential dependency conflict happening in your environment in `oauth2-oidc-sdk` dependency.
Can you add this dependency in your top level pom and see if it resolves your issue ? :
```
        <dependency>
            <groupId>com.nimbusds</groupId>
            <artifactId>oauth2-oidc-sdk</artifactId>
            <version>7.4</version>
        </dependency>
```

**Comment by sudharsan2020** [comment]
@g2vinay Thanks for the update. I was able to fetch the **Keyvaut values successfully** after cleaning up my POM file. Thanks for your support :100:
