### ISSUE TITLE
[BUG] Trying to consume the RoleAssignment create API puts the thread in blocking state forever

### ISSUE THREAD

**Issue by Shabirmean** [Azure/azure-sdk-for-java#15990]
**Describe the bug**
- We are using the Azure SDK for Java (v1.33.1; we tried upgrading it to v1.36.3 too) to create [RoleAssingments](https://docs.microsoft.com/en-us/azure/role-based-access-control/role-assignments-rest) on resource groups in Azure. Since, recently the call shown  under **_"Code Snippet"_** seems to never return in a specific system and is in an ever blocking state. We have not been able to get passed this even with the latest Azure version v1.36.3. Please find the thread dump below

***Exception or Stack Trace***
```java
"schedulerFactory_Worker-6" #64 prio=5 os_prio=0 cpu=1749.39ms elapsed=822.08s tid=0x00007fa99caa9000 nid=0x1fa4 waiting on condition  [0x00007fa9397e5000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@11.0.8/Native Method)
	- parking to wait for  <0x00000000d5f00000> (a java.util.concurrent.CountDownLatch$Sync)
	at java.util.concurrent.locks.LockSupport.park(java.base@11.0.8/LockSupport.java:194)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(java.base@11.0.8/AbstractQueuedSynchronizer.java:885)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(java.base@11.0.8/AbstractQueuedSynchronizer.java:1039)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(java.base@11.0.8/AbstractQueuedSynchronizer.java:1345)
	at java.util.concurrent.CountDownLatch.await(java.base@11.0.8/CountDownLatch.java:232)
	at rx.internal.util.BlockingUtils.awaitForComplete(BlockingUtils.java:47)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:460)
	at rx.observables.BlockingObservable.single(BlockingObservable.java:340)
	at com.microsoft.azure.management.resources.fluentcore.model.implementation.CreatableUpdatableImpl.create(CreatableUpdatableImpl.java:251)
	at com.microsoft.azure.management.resources.fluentcore.model.implementation.CreatableUpdatableImpl.create(CreatableUpdatableImpl.java:33)
	at com.cloudops.mc.plugin.azure.components.AzureManagementController.addUserToEnvironment(AzureManagementController.java:212)
	at com.cloudops.mc.manager.services.async.EnvironmentStages.addUserToServiceEnvironment(EnvironmentStages.java:372)
	at com.cloudops.mc.manager.services.async.EnvironmentStages.lambda$addUserToServiceEnvironment$1(EnvironmentStages.java:114)
	at com.cloudops.mc.manager.services.async.EnvironmentStages$$Lambda$2068/0x0000000841825c40.apply(Unknown Source)
	at com.cloudops.mc.manager.services.chain.StageChecker.execute(StageChecker.java:95)
	at com.cloudops.mc.manager.services.chain.StageCheckerFactory.execute(StageCheckerFactory.java:40)
	at com.cloudops.mc.manager.services.chain.ChainChecker.checkCompletion(ChainChecker.java:74)
	at com.cloudops.mc.service.OperationCompletionPollingJob.execute(OperationCompletionPollingJob.java:89)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)
	- locked <0x00000000cc228028> (a org.quartz.simpl.SimpleThreadPool$WorkerThread)
   Locked ownable synchronizers:
	- None
```

**To Reproduce**
- It seems to be an issue in heavily loaded systems

***Code Snippet***
```java
      RoleAssignment roleAssignment = az.accessManagement().roleAssignments().define(roleAssignmentName)
              .forServicePrincipal(servicePrincipal)
              .withBuiltInRole(BuiltInRole.CONTRIBUTOR)
              .withResourceGroupScope(rg)
              .create();
```

**Expected behavior**
- Should successfully create a RoleAssignment

**Setup:**
 - OS: CentOS Linux
 - IDE : None
 - v1.33.1 and v1.36.3

**Additional context**
- Could it be somethingn to do with the Azure API throttling the requests for specific IPs or systems?

**Information Checklist**
- [ X] Bug Description Added
- [ X] Repro Steps Added
- [ X] Setup information Added

**Comment by joshfree** [comment]
@yungezz could you please help route this issue?

**Comment by yungezz** [comment]
hi @xccc-msft could you pls help on this? thanks

**Comment by Shabirmean** [comment]
Thank you @joshfree @yungezz @xccc-msft 
It seems like the issue was related to conflicting versions of JavaNetCookieJar from deifferent dependencies we have. The logs probably were subsumed due to logback settings  that hide most microsoft package logs
