### ISSUE TITLE
Storage live test pipeline consistently failing Linux Java 8

### ISSUE THREAD

**Issue by gapra-msft** [Azure/azure-sdk-for-java#16113]
I've consistently seen the Java 8 pipeline fail due to

Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M3:test (default-test) on project azure-storage-internal-avro: There are test failures.

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=568476&view=logs&j=4d5db6ce-0b7f-527e-b115-2367ee6e1fef&t=57e6bea7-024e-5230-7282-6992d68e7015

You can see similar instances in other runs of the same pipeline.

**Comment by alzimmermsft** [comment]
@mitchdenny can we roll this into the investigation for better dependency resolution, looks to be a similar/same root cause.

**Comment by mitchdenny** [comment]
I don't see any dependency errors here? The storage tests use Spock don't they so I wonder if a good initial step would be moving to the standard testing framework that the rest of the SDK is using?

**Comment by gapra-msft** [comment]
Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M3:test (default-test) on project azure-storage-internal-avro: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/vsts/work/1/s/sdk/storage/azure-storage-internal-avro/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] There was an error in the forked process
[ERROR] org/apache/maven/surefire/common/junit4/JUnitTestFailureListener
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process
[ERROR] org/apache/maven/surefire/common/junit4/JUnitTestFailureListener
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:657)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:283)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:246)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1161)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1002)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:848)
[ERROR] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR] 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
[ERROR] 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
[ERROR] 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
[ERROR] 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
[ERROR] 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
[ERROR] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

**Comment by gapra-msft** [comment]
@mitchdenny Is there something specific in the stack trace that ties the issue to Spock/Groovy?

**Comment by joshfree** [comment]
@alzimmermsft can you help peel the onion on this one further and dig into the infra a bit more?

**Comment by alzimmermsft** [comment]
@mitchdenny do we have a viable location where we could copy log files for failing runs? It would be good to add a step on pipeline failure to copy `/target` files that are logs, such as the one mentioned in the error message. Once we have a few error logs we can better stitch together the underlying root issue.

**Comment by mitchdenny** [comment]
Actually we can capture the entire repo (including the target directories). Queue the pipeline this variable defined and you'll get an artifact attached to the pipeline with a copy of the state of the repo:

https://github.com/Azure/azure-sdk-for-java/blob/68232ecd10c8b1e0c8fbae4acaf0555742cea170/eng/pipelines/templates/jobs/archetype-sdk-client.yml#L134
