### ISSUE TITLE
[BUG] EventHubProducerAsyncClient throws Exception in RequestResponse links. Disposing and clearing unconfirmed sends.

### ISSUE THREAD

**Issue by tejaswibm** [Azure/azure-sdk-for-java#16147]
**Describe the bug**
We have configured `EventHubProducerAsyncClient` to publish events to EH. The send operation is done via size limited batches as given in the documentation of `EventHubProducerAsyncClient`.
However, intermittently we are getting below error -
```
2020-10-10 13:45:59,643 -  - single-1 [ERROR] - Exception in RequestResponse links. Disposing and clearing unconfirmed sends.
The connection was inactive for more than the allowed 300000 milliseconds and is closed by container 'LinkTracker'. TrackingId:1760e721e4bd4a439b7ed573593f30da_G29, SystemTracker:gateway5, Timestamp:2020-10-10T08:15:59, errorContext[NAMESPACE: <EH_NAMESPACE>.servicebus.windows.net, PATH: $cbs, REFERENCE_ID: cbs:sender, LINK_CREDIT: 96]
```

***Exception or Stack Trace***
Though AMQP logs are enabled we are seeing only below error and no stacktrace as such 
```
2020-10-10 13:45:59,643 -  - single-1 [ERROR] - Exception in RequestResponse links. Disposing and clearing unconfirmed sends.
The connection was inactive for more than the allowed 300000 milliseconds and is closed by container 'LinkTracker'. TrackingId:1760e721e4bd4a439b7ed573593f30da_G29, SystemTracker:gateway5, Timestamp:2020-10-10T08:15:59, errorContext[NAMESPACE: <EH_NAMESPACE>.servicebus.windows.net, PATH: $cbs, REFERENCE_ID: cbs:sender, LINK_CREDIT: 96]
```

Post this error we usually see below exception in all EH producer clients created for our multiple topics. Not sure if both of these are related. But we do not have any sort of info regarding this, since we are not able to establish why the below exception occurs. 
We have observed that this exception is thrown post  `Exception in RequestResponse links` error.
```
Exception in thread "<EH>-pool-7-thread-1" java.lang.IllegalStateException: Timeout on blocking read for 30000 MILLISECONDS
        at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:123)
        at reactor.core.publisher.Mono.block(Mono.java:1704)
        at com.test.AsyncEventHubPublisher.lambda$publishEvents$4(AsyncEventHubPublisher.java:211)
        at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.runFinally(FluxDoFinally.java:156)
        at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onComplete(FluxDoFinally.java:139)
        at reactor.core.publisher.MonoIgnoreElements$IgnoreElementsSubscriber.onComplete(MonoIgnoreElements.java:81)
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.checkTerminated(FluxFlatMap.java:838)
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:600)
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.drain(FluxFlatMap.java:580)
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.onComplete(FluxFlatMap.java:457)
        at reactor.core.publisher.FluxIterable$IterableSubscription.slowPath(FluxIterable.java:289)
        at reactor.core.publisher.FluxIterable$IterableSubscription.request(FluxIterable.java:225)
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.onSubscribe(FluxFlatMap.java:363)
        at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:161)
        at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:86)
        at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
        at reactor.core.publisher.FluxRetryWhen.subscribe(FluxRetryWhen.java:79)
        at reactor.core.publisher.MonoRetryWhen.subscribeOrReturn(MonoRetryWhen.java:46)
        at reactor.core.publisher.Mono.subscribe(Mono.java:4198)
        at reactor.core.publisher.MonoSubscribeOn$SubscribeOnSubscriber.run(MonoSubscribeOn.java:124)
        at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
        at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**To Reproduce**
1. Create `EventHubProducerAsyncClient` to produce events to EH given in the documentation via size limited batches.
2. Keep producing events.
3. There is no pattern of these errors. They occur very randomnly.

***Code Snippet***
```
EventHubProducerAsyncClient ehClient = new EventHubClientBuilder()
                .connectionString(Objects.requireNonNull(connString, "Azure Event Hub connection string cannot be null"))
                .buildAsyncProducerClient();
```
```
final AtomicReference<EventDataBatch> currentBatch = new AtomicReference<>(
                this.eventHubProducerAsyncClient.createBatch().block()
        );

        Flux<EventData> eventDataFlux = Flux.fromIterable(events);

        final Mono<Void> sendOperation = eventDataFlux.flatMap(event -> {
            final EventDataBatch eventDataBatch = currentBatch.get();
            if (eventDataBatch.tryAdd(event)) {
                return Mono.empty();
            }

//            Logger.warn("{} : {} -> 1. Publishing event batch - count :: {} , size :: {}",
//                    CLASS, this.eventHubName, eventDataBatch.getCount(), eventDataBatch.getSizeInBytes());

            // The batch is full, so we create a new batch and send the batch. Mono.when completes when both operations
            // have completed.
            return Mono.when(
                    this.eventHubProducerAsyncClient.send(eventDataBatch),
                    this.eventHubProducerAsyncClient.createBatch().map(newBatch -> {
                        currentBatch.set(newBatch);

                        // Add that event that we couldn't before.
                        if (!newBatch.tryAdd(event)) {
                            throw Exceptions.propagate(new IllegalArgumentException(String.format(
                                    "Event is too large for an empty batch. Max size: %s. Event: %s",
                                    newBatch.getMaxSizeInBytes(), event.getBodyAsString())));
                        }

                        return newBatch;
                    }));
        }, DEFAULT_CONCURRENCY).then().doFinally(signal -> {
            final EventDataBatch batch = currentBatch.getAndSet(null);
            if (batch != null && batch.getCount() > 0) {
//                Logger.warn("{} : {} -> 2. Publishing event batch - count :: {} , size :: {}",
//                        CLASS, this.eventHubName, batch.getCount(), batch.getSizeInBytes());
                this.eventHubProducerAsyncClient.send(batch).block(TIMEOUT);
            }
        }).retryWhen(Retry.backoff(3, Duration.ofMinutes(1)));


        if(isConsumerShutdown) {
            Logger.warn("{} : {} -> START : Blocking push size :: {}; queue size :: {}",
                    CLASS, this.eventHubName, events.size(), this.eventQueue.size());
            sendOperation.subscribeOn(Schedulers.immediate()).block(TIMEOUT);
            Logger.warn("{} : {} -> END : Blocking push", CLASS, this.eventHubName);
        } else {
            sendOperation.subscribeOn(Schedulers.fromExecutorService(this.executorService)).subscribe(
                    unused -> {},
                    error -> Logger.error("{} : {} -> ERROR: Unable to send data of current batch", CLASS, this.eventHubName, error.fillInStackTrace())
            );
        }
```

**Expected behavior**
There should not be any errors like this. We are not sure if we are losing data in the current batch when this error occurs.

**Setup (please complete the following information):**
 - OS: Ubuntu 16.04
 - IDE : IntelliJ
 - "com.azure" % "azure-messaging-eventhubs" % "5.2.0"

**Comment by tejaswibm** [comment]
Below is the stack trace with DEBUG logs on for AMQP. 
[Uploading stacktrace_1.txt…](Pre exception logs)

Error/Exception post above connection close logs.
[Uploading Exception_1.txt…](Exception logs)

Any help regarding this issue would be appreciated.

**Comment by tejaswibm** [comment]
We have switched on `DEBUG` logs for `AMQP` . Below are the logs for the same
[Pre exception logs](https://github.com/Azure/azure-sdk-for-java/files/5369057/stacktrace_1.txt)

Error / Exception post session , link close.
[Exception_1.txt](https://github.com/Azure/azure-sdk-for-java/files/5369056/Exception_1.txt)

Any help regarding this would be appreciated.

**Comment by tejaswibm** [comment]
cc : @srnagar

**Comment by tejaswibm** [comment]
any update on this ? we are facing this issue frequently now.

**Comment by srnagar** [comment]
@tejaswibm - Are you noticing any event batches not getting published because of these errors? The above errors indicate that the connection was idle for a long period (i.e. no events were sent from the producer client). When this happens, the connection is automatically closed by the service but when you try to send events again later, a new connection is established and the events will be sent. 

If you are reporting about the error logs, then these are going to be logged to indicate that there's no activity on the connection and can be ignored. However, if the events are not being sent, then that is an issue we should investigate.

To ensure events are successfully sent, consider adding a log after each call to send the event batch. If a batch failed to send, then you can use the `onError()` to log the batch that failed to send. This will give us information about any batch that was not delivered and we can investigate further on why the batch was not sent.

Here's a sample code snippet to do it:

```java
EventHubProducerAsyncClient producer = new EventHubClientBuilder()
    .connectionString(CONNECTION_STRING)
    .buildAsyncProducerClient();

AtomicReference<EventDataBatch> eventBatch = new AtomicReference<>(producer.createBatch().block());
AtomicReference<String> lastEvent = new AtomicReference<>();
eventsToPublish
    .delayElements(Duration.ofMillis(100))
    .publishOn(Schedulers.boundedElastic())
    .concatMap(event -> {
        if (!eventBatch.get().tryAdd(event)) {
            EventDataBatch batchToSend = eventBatch.get();
            String lastEventToSend = lastEvent.get();
            eventBatch.set(producer.createBatch().block());
            eventBatch.get().tryAdd(event);
            lastEvent.set(event.getBodyAsString());
            System.out.println("Sending batch with last event " + lastEventToSend);
            return producer.send(batchToSend);
        }
        lastEvent.set(event.getBodyAsString());
        return Mono.empty();
    })
    .then(producer.send(eventBatch.get())
        .doOnSubscribe(s -> System.out.println("Sending final batch with last event " + lastEvent.get())))
    .subscribe(unused -> {
        },
        ex -> System.out.println("Error sending event batch. Last event added to batch =  " + lastEvent.get() + ". " +
            "Exception =" + ex),
        () -> System.out.println("Completed sending all events"));
```

**Comment by srnagar** [comment]
@tejaswibm were you able try this out?

**Comment by srnagar** [comment]
Resolving as there is no response.
