### ISSUE TITLE
NPE on powerState during a VM Resource Group Migration

### ISSUE THREAD

**Issue by renutz** [Azure/azure-sdk-for-java#1622]
Hi,

I migrated a deallocated VM to a new resource group using the console.

In this meantime, we had a process that keeps checking the status of this VM. 

`
VirtualMachine vm = azure.virtualMachines().getByGroup(rgname, vmname);
System.out.println("Powerstate: " + vm.powerState());
`

At some point, it generated the following exception:

	at com.microsoft.azure.management.compute.implementation.VirtualMachineImpl$4.call(VirtualMachineImpl.java:334)
	at com.microsoft.azure.management.compute.implementation.VirtualMachineImpl$4.call(VirtualMachineImpl.java:331)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.emitScalar(OperatorMerge.java:511)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.tryEmit(OperatorMerge.java:466)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:244)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:148)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$RequestArbiter.request(RxJavaCallAdapterFactory.java:173)
	at rx.Subscriber.setProducer(Subscriber.java:211)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102)
	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:152)
	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:138)
	at rx.Observable.unsafeSubscribe(Observable.java:10142)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10142)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10142)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10142)
	at rx.internal.operators.DeferredScalarSubscriber.subscribeTo(DeferredScalarSubscriber.java:153)
	at rx.internal.operators.OnSubscribeTakeLastOne.call(OnSubscribeTakeLastOne.java:32)
	at rx.internal.operators.OnSubscribeTakeLastOne.call(OnSubscribeTakeLastOne.java:22)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.subscribe(Observable.java:10238)
	at rx.Observable.subscribe(Observable.java:10205)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:444)
	at rx.observables.BlockingObservable.last(BlockingObservable.java:227)
	at com.microsoft.azure.management.compute.implementation.VirtualMachineImpl.refreshInstanceView(VirtualMachineImpl.java:323)
	at com.microsoft.azure.management.compute.implementation.VirtualMachineImpl.instanceView(VirtualMachineImpl.java:1390)
	at com.microsoft.azure.management.compute.implementation.VirtualMachineImpl.powerState(VirtualMachineImpl.java:1397)
....
`Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: null
	at rx.exceptions.OnErrorThrowable.addValueAsLastCause(OnErrorThrowable.java:118)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:73)
`

**Comment by jianghaolu** [comment]
Hi @renutz which version are you using? We recently added a null check in `refreshInstanceView` for 1.0.0 version of the SDK. Can you verify if you issue still persists in 1.0.0? Thanks!

**Comment by renutz** [comment]
We were using latest 1.0.0-beta6-snapshot. We plan to migrate soon to 1.0.0 and I'll let you know.

Thanks for the answer.

**Comment by anuchandy** [comment]
@renutz please try 1.0.0 or 1.1.0 which has the fix. Closing this, feel free to reopen if you still face the issue.
