### ISSUE TITLE
[BUG] Exception "'Timestamp' must be an OffsetDateTime" when listing Table entities

### ISSUE THREAD

**Issue by gdurandrexel** [Azure/azure-sdk-for-java#16292]
When listing entities of an Azure Storage Table, I receive the exception:

```
12:15:39.877 [vert.x-eventloop-thread-0] ERROR fr.rexel.platform.core.server.toolkit.http.OpenApiOperationsHandler - Request failure with exception
java.lang.IllegalArgumentException: 'Timestamp' must be an OffsetDateTime.
	at com.azure.data.tables.models.TableEntity.validateProperty(TableEntity.java:137) ~[azure-data-tables-12.0.0-beta.2.jar:?]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Assembly trace from producer [reactor.core.publisher.MonoFlatMap] :
	reactor.core.publisher.Mono.flatMap(Mono.java:2748)
	com.azure.data.tables.TableAsyncClient.listEntities(TableAsyncClient.java:616)
Error has been observed at the following site(s):
	|_       Mono.flatMap ⇢ at com.azure.data.tables.TableAsyncClient.listEntities(TableAsyncClient.java:616)
	|_       Mono.flatMap ⇢ at com.azure.core.util.FluxUtil.withContext(FluxUtil.java:203)
	|_          Mono.flux ⇢ at com.azure.core.http.rest.PagedFlux.lambda$new$1(PagedFlux.java:66)
	|_ Flux.switchIfEmpty ⇢ at com.azure.core.util.paging.ContinuablePagedFluxCore.concatFluxOfPage(ContinuablePagedFluxCore.java:170)
	|_      Flux.doOnNext ⇢ at com.azure.core.util.paging.ContinuablePagedFluxCore.concatFluxOfPage(ContinuablePagedFluxCore.java:174)
	|_    Flux.concatWith ⇢ at com.azure.core.util.paging.ContinuablePagedFluxCore.concatFluxOfPage(ContinuablePagedFluxCore.java:175)
	|_         Flux.defer ⇢ at com.azure.core.util.paging.ContinuablePagedFluxCore.byPage(ContinuablePagedFluxCore.java:145)
	|_       Flux.flatMap ⇢ at com.azure.core.util.paging.ContinuablePagedFluxCore.subscribe(ContinuablePagedFluxCore.java:122)
Stack trace:
		at com.azure.data.tables.models.TableEntity.validateProperty(TableEntity.java:137) ~[azure-data-tables-12.0.0-beta.2.jar:?]
		at com.azure.data.tables.models.TableEntity.addProperties(TableEntity.java:121) ~[azure-data-tables-12.0.0-beta.2.jar:?]
		at com.azure.data.tables.implementation.ModelHelper.createEntity(ModelHelper.java:78) ~[azure-data-tables-12.0.0-beta.2.jar:?]
		at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
		at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655) ~[?:?]
		at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
		at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
		at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
		at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
		at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
		at com.azure.data.tables.TableAsyncClient.lambda$listEntities$33(TableAsyncClient.java:630) ~[azure-data-tables-12.0.0-beta.2.jar:?]
		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:118) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
...
```

And indeed the Timestamp property is of type String in the deserialzed response: https://ibb.co/JcShrdb

- OS: Windows
- IDE : IntelliJ IDEA
- kotlin 1.4.10
- azure-data-tables-12.0.0-beta.2

**Comment by bsiegel** [comment]
Hi @gdurandrexel, thanks for this bug report. I think I have a hunch as to what the bug is here. To verify, are you acquiring your `TableAsyncClient` by calling `tableServiceAsyncClient.getTableClient(tableName)`? I can see that in this case, the code does not set the correct serializer and the types coming back from the service are not deserialized from string values.

If this is in fact your situation, can you try changing your code to construct the `TableAsyncClient` by using a `TableClientBuilder` instead? If I'm right about what's causing the bug, this should work correctly for you.

**Comment by gdurandrexel** [comment]
That's what I was doing indeed, and using the TableClientBuilder fixed the problem, thanks.

I have another problem though: I add a property as a byte array, which is serialized as a base64 string. But when deserialized I would expect a byte array but it is still a base64 string. I notice that no odata type is set for this property. I would expect Edm.Binary.

https://ibb.co/c6MW0Ks

Shall I create another issue?

**Comment by bsiegel** [comment]
@gdurandrexel Yes, please do. And if you can include a sample snippet of the code you are using to attach the binary data that would be super helpful.

**Comment by ThibautDelcroix** [comment]
Hello @bsiegel,

I have the same error when I list the entities.

**Stack trace :**
`
java.lang.IllegalArgumentException: 'Timestamp' must be an OffsetDateTime.
	at com.azure.data.tables.models.TableEntity.validateProperty(TableEntity.java:137)
	at com.azure.data.tables.models.TableEntity.addProperties(TableEntity.java:121)
	at com.azure.data.tables.implementation.ModelHelper.createEntity(ModelHelper.java:78)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1380)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.azure.data.tables.TableAsyncClient.lambda$listEntities$33(TableAsyncClient.java:630)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:118)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1782)
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:241)
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:67)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1782)
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:241)
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:67)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1782)
	at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.signalCached(MonoCacheTime.java:320)
	at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.onNext(MonoCacheTime.java:337)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:73)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1782)
	at reactor.core.publisher.MonoCallable.subscribe(MonoCallable.java:61)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
	at reactor.core.publisher.MonoCacheTime.subscribeOrReturn(MonoCacheTime.java:132)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:150)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1782)
	at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.signalCached(MonoCacheTime.java:320)
	at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.onNext(MonoCacheTime.java:337)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1782)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:144)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:123)
	at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:112)
	at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:213)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:123)
	at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:178)
	at reactor.core.publisher.FluxContextStart$ContextStartSubscriber.onNext(FluxContextStart.java:96)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1782)
	at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:121)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:252)
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:136)
	at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:374)
	at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:373)
	at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:429)
	at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:655)
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:96)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1533)
	at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1294)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1331)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.proxy.ProxyHandler.channelRead(ProxyHandler.java:253)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
2020-11-13T17:19:35.188+0100;PO712477;RMI TCP Connection(3)-10.215.183.221;;WARN;;;;;;j.m.r.misc - The server has decided to close this client connection.; 
`

**Code :**
`
TableServiceClient tableServiceClient = new TableServiceClientBuilder()
     .httpClient(httpClient)
     .connectionString(storageConnectionString)
     .buildClient();

tableServiceClient.createTableIfNotExists(tableName);

TableClient tableClient = tableServiceClient.getTableClient(tableName);

tableClient.listEntities();
`

azure-data-tables-12.0.0-beta.3
