### ISSUE TITLE
[BUG] [Service Bus - Creating subscription] Can't instantiate ServiceBusContract object with either ACS or SAS connection string

### ISSUE THREAD

**Issue by onesunvan** [Azure/azure-sdk-for-java#16748]
I'm trying to create a subscription via Java SDK using SAS creds. 
        
```
        Configuration config = ServiceBusConfiguration.configureWithConnectionString(null, new Configuration(), 
                                                                           "Endpoint=sb://<namespace>.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=<PASSWORD>");
        ServiceBusContract service = ServiceBusService.create(config);
        SubscriptionInfo subInfo = new SubscriptionInfo("new-subscription");
        CreateSubscriptionResult result =
            service.createSubscription("mytopic", subInfo);
```
(**namespace** and **password** are replaced with actual values in the code)

Doing so, I received the following stack trace:
```
Caused by: com.microsoft.windowsazure.services.core.utils.ConnectionStringSyntaxException: The key 'SharedAccessKeyName' is not valid for this connection string
	at com.microsoft.windowsazure.services.core.utils.ParsedConnectionString.saveValue(ParsedConnectionString.java:296) ~[microsoft-windowsazure-api-0.4.6.jar:na]
	at com.microsoft.windowsazure.services.core.utils.ParsedConnectionString.matchKeyValuePair(ParsedConnectionString.java:137) ~[microsoft-windowsazure-api-0.4.6.jar:na]
	at com.microsoft.windowsazure.services.core.utils.ParsedConnectionString.matchAttribute(ParsedConnectionString.java:108) ~[microsoft-windowsazure-api-0.4.6.jar:na]
	at com.microsoft.windowsazure.services.core.utils.ParsedConnectionString.matchConnectionString(ParsedConnectionString.java:89) ~[microsoft-windowsazure-api-0.4.6.jar:na]
```

I found a question on StackOverflow describing the same issue - https://stackoverflow.com/questions/27271397/servicebusconfiguration-configurewithconnectionstring-cant-work-error-the-key?rq=1
There was a suggestion to use the ACS approach since SAS is not supported via Java SDK. 

So I tried to use ACS:

```
 Configuration config =
            ServiceBusConfiguration.configureWithWrapAuthentication(
                namespace,
                username,
                password,
                ".servicebus.windows.net",
                "-sb.accesscontrol.windows.net/WRAPv0.9/");
        
        ServiceBusContract service = ServiceBusService.create(config);
        SubscriptionInfo subInfo = new SubscriptionInfo("new-subscription");
        CreateSubscriptionResult result =
            service.createSubscription("mytopic", subInfo);
```

It didn't work out too:

```
Caused by: com.microsoft.windowsazure.services.core.ServiceException: com.sun.jersey.api.client.ClientHandlerException: java.net.UnknownHostException: myservicebus-sb.accesscontrol.windows.net
	at com.microsoft.windowsazure.services.serviceBus.implementation.ServiceBusExceptionProcessor.createSubscription(ServiceBusExceptionProcessor.java:329) ~[microsoft-windowsazure-api-0.4.6.jar:na]
	at com.example.azuresubscriber.TopicSubscriber.init(TopicSubscriber.java:43) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_242]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_242]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_242]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_242]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389) ~[spring-beans-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333) ~[spring-beans-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157) ~[spring-beans-5.2.9.RELEASE.jar:5.2.9.RELEASE]
```

I found this problem here on Github, marked as closed:
https://github.com/Azure/azure-sdk-for-java/issues/437

So neither approach is working.

**Comment by joshfree** [comment]
@yvgopal @hemanttanwar could you please follow up on this question?

**Comment by yvgopal** [comment]
This is very very old service bus SDK that was based on HTTP and we are not maintaining it anymore. Please please switch to the Track 1 SDK. Here is link to the releases https://mvnrepository.com/artifact/com.microsoft.azure/azure-servicebus

As I said, we are not maintaining the old SDK (version 0.9 and older). If we have to spend time on the old SDK, it will take quite sometime.

**Comment by onesunvan** [comment]
Thanks for your response.
Unfortunately, the new library doesn't support creating subscriptions from a java code. 
Docs suggest using management library for those purposes, but I didn't find a way to init management lib with SAS key, only with azure creds. 

Having clients dynamically create subscriptions with different filters would be very convenient, but only if this could be done using SAS key with access to one single topic, not azure creds.

**Comment by yvgopal** [comment]
No.. The latest version from the link I shared in my previous post supports creating subscriptions from java code. CHeck ManagementClient class.
There is one SDK that I shared is GA. One more SDK will soon be coming, which is what you are referring to as the latest.
