### ISSUE TITLE
[BUG] "Max price change not allowed" error when changing vm tag. 

### ISSUE THREAD

**Issue by erzads** [Azure/azure-sdk-for-java#16762]
**Describe the bug**
I have been using this sdk to manage my vms juts fine until this week. I have a feature where users can use my app to change a tag on a vm. 
```
VirtualMachine virtualMachine = azure.virtualMachines().getByResourceGroup(resourceGroup, vmName);
        virtualMachine.update().withTag(tagName, tagValue).apply();
```
This has been working fine until a couple of days ago. Now whenever I do that I get this error:
Max price change is not allowed. For more information, see http://aka.ms/AzureSpot/errormessages

***Exception or Stack Trace***
com.microsoft.azure.CloudException: Max price change is not allowed. For more information, see http://aka.ms/AzureSpot/errormessages 
	at com.microsoft.azure.AzureClient.createExceptionFromResponse(AzureClient.java:771) ~[azure-client-runtime-1.7.0.jar!/:na]
	at com.microsoft.azure.AzureClient.access$100(AzureClient.java:33) ~[azure-client-runtime-1.7.0.jar!/:na]
	at com.microsoft.azure.AzureClient$3.call(AzureClient.java:160) ~[azure-client-runtime-1.7.0.jar!/:na]
	at com.microsoft.azure.AzureClient$3.call(AzureClient.java:157) ~[azure-client-runtime-1.7.0.jar!/:na]
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69) ~[rxjava-1.3.8.jar!/:1.3.8]
	at retrofit2.adapter.rxjava.CallArbiter.deliverResponse(CallArbiter.java:120) ~[adapter-rxjava-2.6.2.jar!/:na]
	at retrofit2.adapter.rxjava.CallArbiter.emitResponse(CallArbiter.java:102) ~[adapter-rxjava-2.6.2.jar!/:na]
	at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:46) ~[adapter-rxjava-2.6.2.jar!/:na]
	at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:24) ~[adapter-rxjava-2.6.2.jar!/:na]
	at rx.Observable.unsafeSubscribe(Observable.java:10327) ~[rxjava-1.3.8.jar!/:1.3.8]
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48) ~[rxjava-1.3.8.jar!/:1.3.8]
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33) ~[rxjava-1.3.8.jar!/:1.3.8]
	at rx.Observable.unsafeSubscribe(Observable.java:10327) ~[rxjava-1.3.8.jar!/:1.3.8]
	at rx.internal.operators.OnSubscribeSingle.call(OnSubscribeSingle.java:81) ~[rxjava-1.3.8.jar!/:1.3.8]
	at rx.internal.operators.OnSubscribeSingle.call(OnSubscribeSingle.java:27) ~[rxjava-1.3.8.jar!/:1.3.8]
	at rx.internal.operators.SingleToObservable.call(SingleToObservable.java:39) ~[rxjava-1.3.8.jar!/:1.3.8]
	at rx.internal.operators.SingleToObservable.call(SingleToObservable.java:27) ~[rxjava-1.3.8.jar!/:1.3.8]
	at rx.Observable.unsafeSubscribe(Observable.java:10327) ~[rxjava-1.3.8.jar!/:1.3.8]
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48) ~[rxjava-1.3.8.jar!/:1.3.8]
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33) ~[rxjava-1.3.8.jar!/:1.3.8]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) ~[rxjava-1.3.8.jar!/:1.3.8]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) ~[rxjava-1.3.8.jar!/:1.3.8]
	at rx.Observable.unsafeSubscribe(Observable.java:10327) ~[rxjava-1.3.8.jar!/:1.3.8]
	at rx.internal.operators.DeferredScalarSubscriber.subscribeTo(DeferredScalarSubscriber.java:153) ~[rxjava-1.3.8.jar!/:1.3.8]
	at rx.internal.operators.OnSubscribeTakeLastOne.call(OnSubscribeTakeLastOne.java:32) ~[rxjava-1.3.8.jar!/:1.3.8]
	at rx.internal.operators.OnSubscribeTakeLastOne.call(OnSubscribeTakeLastOne.java:22) ~[rxjava-1.3.8.jar!/:1.3.8]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) ~[rxjava-1.3.8.jar!/:1.3.8]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) ~[rxjava-1.3.8.jar!/:1.3.8]
	at rx.Observable.unsafeSubscribe(Observable.java:10327) ~[rxjava-1.3.8.jar!/:1.3.8]
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48) ~[rxjava-1.3.8.jar!/:1.3.8]
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33) ~[rxjava-1.3.8.jar!/:1.3.8]
	at rx.Observable.unsafeSubscribe(Observable.java:10327) ~[rxjava-1.3.8.jar!/:1.3.8]
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48) ~[rxjava-1.3.8.jar!/:1.3.8]
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33) ~[rxjava-1.3.8.jar!/:1.3.8]
	at rx.Observable.unsafeSubscribe(Observable.java:10327) ~[rxjava-1.3.8.jar!/:1.3.8]
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48) ~[rxjava-1.3.8.jar!/:1.3.8]
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33) ~[rxjava-1.3.8.jar!/:1.3.8]
	at rx.Observable.unsafeSubscribe(Observable.java:10327) ~[rxjava-1.3.8.jar!/:1.3.8]
	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100) ~[rxjava-1.3.8.jar!/:1.3.8]
	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230) ~[rxjava-1.3.8.jar!/:1.3.8]
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55) ~[rxjava-1.3.8.jar!/:1.3.8]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_242]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_242]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_242]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_242]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_242]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_242]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_242]
Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: retrofit2.Response.class
	at rx.exceptions.OnErrorThrowable.addValueAsLastCause(OnErrorThrowable.java:118) ~[rxjava-1.3.8.jar!/:1.3.8]
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:73) ~[rxjava-1.3.8.jar!/:1.3.8]
	... 43 common frames omitted

**To Reproduce**
VirtualMachine virtualMachine = azure.virtualMachines().getByResourceGroup(resourceGroup, vmName);
        virtualMachine.update().withTag(tagName, tagValue).apply();

***Code Snippet***
VirtualMachine virtualMachine = azure.virtualMachines().getByResourceGroup(resourceGroup, vmName);
        virtualMachine.update().withTag(tagName, tagValue).apply();

**Expected behavior**
Update the vm tag with no error. 

**Screenshots**

**Setup (please complete the following information):**
 - OS: [windows]
 - IDE : [IntelliJ]
 - Version of the Library used 1.33.0

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ x] Bug Description Added
- [x ] Repro Steps Added
- [ x] Setup information Added

**Comment by joshfree** [comment]
@yungezz could you please assist in routing this `Mgmt` plane SDK question?

**Comment by yungezz** [comment]
hi @xccc-msft could you pls help to have a look?

**Comment by xccc-msft** [comment]
@erzads I tried with 1.33.0 while I failed to reproduce.
My test scenario:
- create spot vm with max price value
- update with new tag

```java
VirtualMachine virtualMachine = azure.virtualMachines()
                .define("vmname")
                ...//config other basic settings
                .withPriority(VirtualMachinePriorityTypes.SPOT)
                .withMaxPrice(price)
                .create();

virtualMachine.update()
                .withTag("key1", "value1")
                .apply();
```
Do you have any specific settings on the vm or tag name/value pair? Thanks.

**Comment by erzads** [comment]
@xccc-msft I am not creating the vms, they are being created by someone else.
I don't know if this is important but I am updating existing tags, so in your test you should create the vm with a tag and them change that tag value. 

Also, I just update the sdk version to 1.36.3 but the issue remains.

**Comment by xccc-msft** [comment]
@erzads Thanks for details. I tried again by the scenario you suggested.
- create vm with a tag
- update vm by chaning that tag value
I still cannot reproduce. Can you try to capture your request and response for the GET and UPDATE operation? Thanks.

**Comment by erzads** [comment]
I am struggling to find out where in the sdk I should put a break point to debug the requests.

I did however manage to get an additional log message in the error response.

Code: OperationNotAllowed
Message: Max price change is not allowed when the VM 'vm name' is **currently allocated**. Please deallocate and try again.

**Comment by xccc-msft** [comment]
@erzads Can you check if the max price is the same when you fetch the vm data?
```
VirtualMachine virtualMachine = azure.virtualMachines().getByResourceGroup(resourceGroup, vmName);
```

**Comment by erzads** [comment]
@xccc-msft INFO 172632 --- [           main] a.m.c.VirtualMachines getByResourceGroup : 2181-byte body:
{
  "name": "myVm",
  "id": ...,
  "type": "Microsoft.Compute/virtualMachines",
  "location": ..,
  "tags": {
    ...
  },
  "properties": {
    "vmId": "...",
    "hardwareProfile": {
      "vmSize": "..."
    },
    "storageProfile": {
      ...
    },
    "networkProfile": {...},
    "diagnosticsProfile": {
      ...
    },
    "provisioningState": "Succeeded",
    "priority": "Spot",
    "evictionPolicy": "Deallocate",
    "billingProfile": {
      "maxPrice": -1.0
    }
  },
  "resources": [
    {
      "name": "OmsAgentForLinux",
      "id": "...",
      "type": "Microsoft.Compute/virtualMachines/extensions",
      "location": "...",
      "properties": {
        ...
      }
    }
  ]
}
INFO 172632 --- [           main] a.m.c.VirtualMachines getByResourceGroup : <-- END HTTP

**Comment by xccc-msft** [comment]
@erzads Thanks for sharing. As you get maxPrice as -1 and patch with same value, I just add label of `Service Attention` so the service team could help check if any issue from server end. Thanks.

**Comment by Drewm3** [comment]
@avirishuv, could you have a look at this issue.

**Comment by rajeeshr** [comment]
@erzads we weren't successful either in re-creating  the scenario here, can you help with providing the subId so we can have our engineering team to pull the logs and debug?

**Comment by puggianjv** [comment]
@rajeeshr Hello. I work with him. The subId used is "ca8dfaca-d7f1-484a-bddf-447d4387c00a". We got the same error on a request today.

**Comment by rajeeshr** [comment]
@puggianjv Thanks for reaching out, our back end team is investigating the issue. I will get back to you on the findings.

**Comment by rajeeshr** [comment]
@puggianjv  We pulled out the logs, The error is happening because we do not allow MaxPriceUpdate on a running VM. 

"innererror": {
    "internalErrorCode": "MaxPriceChangeNotAllowed"
  },
  "code": "OperationNotAllowed",
  "message": "Max price change is not allowed. For more information, see http://aka.ms/AzureSpot/errormessages"
}

**Comment by erzads** [comment]
@rajeeshr but we are just trying to update a vm tag. That price change problem should not be happening.
Through the azure portal we can change vm tags successfully even if they are running. 
Do you expect us to shutdown out vms whenever we need to change a tag on them?

**Comment by puggianjv** [comment]
Any update about this problem?

**Comment by rajeeshr** [comment]
Hi @puggianjv, apologies for the delayed response

We have uncovered a bug in our code. When the original create request does not contain a maxPrice but a subsequent PATCH request contains a maxPrice it is concluded as a price change even if the PATCH request contains a maxPrice = -1 which should be the default price when a price is not specified in the PUT request which means there really isn’t a change. you are seeing the failures because,  the VM PATCH operation you are doing to update the tags also contained a maxPrice = -1 

So as a work around until the fix is in place, we wanted you to do what you were doing earlier, that is when you used to do successful VM PATCH operation to update the tags (few weeks back),  don’t include the billingProfile with maxPrice = -1 in the PATCH request to update the tags.

    "billingProfile": {
      "maxPrice": -1.0
    }
Let me know if you have questions.

**Comment by puggianjv** [comment]
Hi @rajeeshr, thanks for the response. 

Actually, we are not changing the billingProfile. This error occurs when we try to change a custom VM tag.

**Comment by rajeeshr** [comment]
@puggianjv 
I see, may be when you try to change the custom VM tag next time, can you try to do this operation with out providing the billingProfile with maxPrice = -1 in the request. It should work.

**Comment by erzads** [comment]
@rajeeshr we are using the azure sdk for Java. The sdk itself is setting that value, not us.

**Comment by xccc-msft** [comment]
@erzads Actually the max price is provided by service end as below description:
```
You can set the maxPrice to -1 to indicate that the Azure Spot VM/VMSS should not be evicted for price reasons. 
Also, the default max price is -1 if it is not provided by you.
```

**Comment by erzads** [comment]
@xccc-msft let's take a step back.

We are using the azure Java sdk as described in my original post. 

This is the code snippet we are running:

VirtualMachine virtualMachine = azure.virtualMachines().getByResourceGroup(resourceGroup, vmName);
        virtualMachine.update().withTag(tagName, tagValue).apply();

This is it. We are not doing anything else. We have no control over the actual payload that is being sent to Azure. 

With all this in mind, how are we supposed to fix this issue? 

Are we actually going to need to stop using the sdk and do the requests by hand? This issue seems like a bug in the sdk.

**Comment by xccc-msft** [comment]
@erzads You might try with below code
```java
azure.virtualMachines().inner().update("resource-group", "vm-name", vmUpdateParams);
```
You need to set the properties inside `VirtualMachineUpdate` for vmUpdateParams.

**Comment by erzads** [comment]
@xccc-msft can you give me an example of how the vmUpdateParams should look like when changing/adding tags?

I have a really hard time debugging the Azure sdk to find this out on my own.

**Comment by erzads** [comment]
Sorry for taking so long. It worked with the last code posted by @xccc-msft . Thank you very much.
