### ISSUE TITLE
1.0.0:-java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.type.TypeBindings.create(Ljava/lang/Class;[Lcom/fasterxml/jackson/databind/JavaType;)Lcom/fasterxml/jackson/databind/type/TypeBindings;

### ISSUE THREAD

**Issue by somnath-infiverve** [Azure/azure-sdk-for-java#1677]
Hi,
I am trying to get list of virtual machines using azure-java-sdk (1.0.0 ) but getting following exception:

**code:**
```java
Azure azure=azure client 
PagedList<VirtualMachine> vmList= azure.virtualMachines().list();
```
**exception:**
SEVERE: Unhandled exception
java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.type.TypeBindings.create(Ljava/lang/Class;[Lcom/fasterxml/jackson/databind/JavaType;)Lcom/fasterxml/jackson/databind/type/TypeBindings;
	at com.microsoft.rest.serializer.JacksonAdapter.constructJavaType(JacksonAdapter.java:119)
	at com.microsoft.rest.serializer.JacksonAdapter.deserialize(JacksonAdapter.java:131)
	at com.microsoft.rest.ServiceResponseBuilder.buildBody(ServiceResponseBuilder.java:215)
	at com.microsoft.rest.ServiceResponseBuilder.build(ServiceResponseBuilder.java:110)
	at com.microsoft.azure.AzureResponseBuilder.build(AzureResponseBuilder.java:56)
	at com.microsoft.azure.management.compute.implementation.VirtualMachinesInner.listDelegate(VirtualMachinesInner.java:1429)
	at com.microsoft.azure.management.compute.implementation.VirtualMachinesInner.access$800(VirtualMachinesInner.java:47)
	at com.microsoft.azure.management.compute.implementation.VirtualMachinesInner$50.call(VirtualMachinesInner.java:1416)
	at com.microsoft.azure.management.compute.implementation.VirtualMachinesInner$50.call(VirtualMachinesInner.java:1412)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$RequestArbiter.request(RxJavaCallAdapterFactory.java:173)
	at rx.Subscriber.setProducer(Subscriber.java:211)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102)
	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:152)
	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:138)
	at rx.Observable.unsafeSubscribe(Observable.java:10142)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.subscribe(Observable.java:10238)
	at rx.Observable.subscribe(Observable.java:10205)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:444)
	at rx.observables.BlockingObservable.single(BlockingObservable.java:341)
	at com.microsoft.azure.management.compute.implementation.VirtualMachinesInner.list(VirtualMachinesInner.java:1336)
	at com.microsoft.azure.management.resources.fluentcore.arm.collection.implementation.TopLevelModifiableResourcesImpl.list(TopLevelModifiableResourcesImpl.java:116)

Thank you in advance!

**Comment by douglasjunior** [comment]
I was able to solve some of the problem by updating the `jackson databind`. Azure uses 2.6.6, I upgraded to 2.7.0.

My `pom.xml`:

```xml
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.7.0</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
            <version>2.7.0</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.dataformat</groupId>
            <artifactId>jackson-dataformat-cbor</artifactId>
            <version>2.7.0</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-joda</artifactId>
            <version>2.7.0</version>
        </dependency>
```

**Comment by martinsawicki** [comment]
let's look at whether we could update this dependency for v2.0 (unsure about breakage)

**Comment by shivamsatija** [comment]
I'm facing a similar issue while fetching resource groups
java.lang.RuntimeException: java.net.SocketException: Connection reset
	at rx.exceptions.Exceptions.propagate(Exceptions.java:58) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:464) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.observables.BlockingObservable.single(BlockingObservable.java:341) ~[rxjava-1.2.4.jar:1.2.4]
	at com.microsoft.azure.management.resources.implementation.ResourceGroupsInner.list(ResourceGroupsInner.java:877) ~[azure-mgmt-resources-1.0.0-beta5.jar:1.0.0-beta5]
	at com.microsoft.azure.management.resources.implementation.ResourceGroupsImpl.list(ResourceGroupsImpl.java:41) ~[azure-mgmt-resources-1.0.0-beta5.jar:1.0.0-beta5].

I'm using jackson version 2.6.2 . Any idea?

**Comment by douglasjunior** [comment]
@shivamsatija this is not similar, but you can try to use jackson 2.7.0.

**Comment by praries880** [comment]
@jianghaolu  is this still an issue or has this been fixed?

**Comment by yungezz** [comment]
hi @xccc-msft could you pls help to confirm is this still a problem? thanks.

**Comment by xccc-msft** [comment]
@somnath-infiverve As it's raised long ago, we just want to check if you are still facing similar issue.

**Comment by xccc-msft** [comment]
@somnath-infiverve Close this as no response. Please feel free to reopen if you still face same issue.
