### ISSUE TITLE
[BUG] When add spring-cloud-stream-binder-eventhubs or serviceubs dependency in pom but don't configure them will throw exception

### ISSUE THREAD

**Issue by saragluna** [Azure/azure-sdk-for-java#16789]
**Describe the bug**
When adding `azure-spring-cloud-eventhubs-stream-binder` or `azure-spring-cloud-servicebus-queue-stream-binder`  `azure-spring-cloud-servicebus-topic-stream-binder` dependency into pom file, without configuring them, will throw IllegalArgumentException  exceptions.

***Exception or Stack Trace***
```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'spring.cloud.azure.eventhub-com.microsoft.azure.spring.cloud.autoconfigure.eventhub.AzureEventHubProperties': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: Either 'spring.cloud.azure.eventhub.namespace' or 'spring.cloud.azure.eventhub.connection-string' should be provided
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:160) ~[spring-beans-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:415) ~[spring-beans-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1786) ~[spring-beans-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594) ~[spring-beans-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516) ~[spring-beans-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324) ~[spring-beans-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322) ~[spring-beans-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) ~[spring-beans-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1307) ~[spring-beans-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1227) ~[spring-beans-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:884) ~[spring-beans-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:788) ~[spring-beans-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	... 48 common frames omitted
Caused by: java.lang.IllegalArgumentException: Either 'spring.cloud.azure.eventhub.namespace' or 'spring.cloud.azure.eventhub.connection-string' should be provided
	at com.microsoft.azure.spring.cloud.autoconfigure.eventhub.AzureEventHubProperties.validate(AzureEventHubProperties.java:75) ~[azure-spring-cloud-autoconfigure-2.0.0-alpha.20201014.0.jar:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389) ~[spring-beans-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333) ~[spring-beans-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157) ~[spring-beans-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	... 61 common frames omitted
```

**To Reproduce**
Create a Spring application and add the dependency 
```xml
      <dependency>
        <groupId>com.azure</groupId>
        <artifactId>azure-spring-cloud-eventhubs-stream-binder</artifactId>
      </dependency>
```

***Code Snippet***
Run the application without setting any properties will reproduce the exception.

**Expected behavior**
Don't throw exceptions when adding the binder to the pom file, but do when want to use the binder without setting such connection-string properties. 

**Setup (please complete the following information):**
 - OS: Any OS
 - IDE : IntelliJ
 - Version of the Library used: Any version will do. 

**Additional context**
N/A 

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by avpines** [comment]
This issue also prevents using multiple different binders in the same application, (e.g. using both the Event Hub and Service Bus Queue binders) since one of them will always treated not configured. This is a blocker for us for going to production, since we have such cases that we need two binders.

**Comment by moarychan** [comment]
Hi @avpines , you can use `spring.cloud.azure.eventhub.enabled=false` or `spring.cloud.azure.servicebus.enabled=false` switch to suppress the bean creation,  please try to add these configuration items.

**Comment by avpines** [comment]
@moarychan thanks, but I'm not sure that I'm following - I need a single application that will use the two binders, e.g. consume events to an Event Hub and publish them to a Service Bus queue. How disabling the bean creation will help in this case?

**Comment by moarychan** [comment]
Hi @avpines , I have passed this usage scenario, send message to event hubs, then transform the message to service bus queue, consume the message in service bus queue, please try the following configuration. Hope to help you!
```yaml
spring:
  cloud:
    azure:
      eventhub:
        type: eventhub
        defaultCandidate: true
        connection-string: "event hubs connection string"
        checkpoint-access-key: "storage key"
        checkpoint-storage-account: "storage account"
        bindings:
          consumer:
      servicebus:
        enabled: false
    stream:
      eventhub:
        bindings:
          uppercase-in-0:
            consumer:
              checkpoint-mode: MANUAL
      poller:
        fixed-delay: 3000
      function:
        definition: eventhub;uppercase;servicebus
      defaultBinder: eventhub
      binders:
        servicebus-queue:
          type: servicebus-queue
          defaultCandidate: false
          environment:
            spring:
              cloud:
                azure:
                  servicebus:
                    enabled: true
                    connection-string: "service bus queue connection string"
                  eventhub:
                    enabled: false
      bindings:
#        eventhub-in-0:
#          destination: event-hub-aa
#          binder: eventhub
#          group: $Default
        eventhub-out-0:
          destination: event-hub-aa
          binder: eventhub
          group: $Default
        uppercase-in-0:
          destination: event-hub-aa
          group: $Default
#          checkpoint-mode: MANUAL
        uppercase-out-0:
          destination: space-1-queue-aa
          binder: servicebus-queue
        servicebus-in-0:
          destination: space-1-queue-aa
          binder: servicebus-queue

```

**Comment by saragluna** [comment]
Hi @avpines, the solution my colleague @moarychan provided is a workaround to make the current version of binders work. But to totally get rid of such checking, we need to move even further. I created this PR to remove the `validate()` in `@PostContruct`. https://github.com/Azure/azure-sdk-for-java/pull/17066

**Comment by avpines** [comment]
Thank you very much for the workaround and detailed example.

Just to make sure that I understand it completely: In each binder you explicitly disable the other binder so it won't throw an exception in `validate()`, so since the default binder is using Event-Hub, you explicitly disable Service-Bus via `spring.cloud.azure.servicebus.enabled=false`, and in the `servicebus-queue` binder you explicitly disable the Event-Hub binder via `spring.cloud.stream.binders.servicebus-queue.environment.spring.cloud.azure.eventhub.enabled=false`. 

Am I correct that this is the only change needed, and once https://github.com/Azure/azure-sdk-for-java/pull/17066 is complete, the explicit checking won't be needed?

**Comment by saragluna** [comment]
Yes. #17066 is merged and we don't need such workaround anymore.
