### ISSUE TITLE
[BUG] Create VirtualMachine: Iterating over a toIterable() / toStream() is blocking

### ISSUE THREAD

**Issue by Zybrion** [Azure/azure-sdk-for-java#16805]
**Describe the bug**
When creating a VirtualMachine with the AzureResourceManager it doesn't create the virtual machine.
The network interface however will be created.

***Stack Trace***
```
java.lang.IllegalStateException: Iterating over a toIterable() / toStream() is blocking, which is not supported in thread reactor-http-nio-2
	at reactor.core.publisher.BlockingIterable$SubscriberIterator.hasNext(BlockingIterable.java:160) ~[reactor-core-3.3.3.RELEASE.jar:3.3.3.RELEASE]
	at java.base/java.lang.Iterable.forEach(Iterable.java:74) ~[na:na]
	at com.azure.resourcemanager.resources.fluentcore.utils.Utils.defaultSubscription(Utils.java:244) ~[azure-resourcemanager-resources-2.0.0-beta.4.jar:2.0.0-beta.4]
	at com.azure.resourcemanager.resources.ResourceManager$AuthenticatedImpl.withDefaultSubscription(ResourceManager.java:203) ~[azure-resourcemanager-resources-2.0.0-beta.4.jar:2.0.0-beta.4]
	at com.azure.resourcemanager.resources.fluentcore.policy.ProviderRegistrationPolicy.lambda$process$1(ProviderRegistrationPolicy.java:70) ~[azure-resourcemanager-resources-2.0.0-beta.4.jar:2.0.0-beta.4]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:118) ~[reactor-core-3.3.3.RELEASE.jar:3.3.3.RELEASE]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:121) ~[reactor-core-3.3.3.RELEASE.jar:3.3.3.RELEASE]
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1705) ~[reactor-core-3.3.3.RELEASE.jar:3.3.3.RELEASE]
	at reactor.core.publisher.MonoCollect$CollectSubscriber.onComplete(MonoCollect.java:160) ~[reactor-core-3.3.3.RELEASE.jar:3.3.3.RELEASE]
	at reactor.core.publisher.FluxReplay$UnboundedReplayBuffer.replayNormal(FluxReplay.java:554) ~[reactor-core-3.3.3.RELEASE.jar:3.3.3.RELEASE]
	at reactor.core.publisher.FluxReplay$UnboundedReplayBuffer.replay(FluxReplay.java:657) ~[reactor-core-3.3.3.RELEASE.jar:3.3.3.RELEASE]
	at reactor.core.publisher.FluxReplay$ReplaySubscriber.onComplete(FluxReplay.java:1253) ~[reactor-core-3.3.3.RELEASE.jar:3.3.3.RELEASE]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onComplete(FluxMapFuseable.java:144) ~[reactor-core-3.3.3.RELEASE.jar:3.3.3.RELEASE]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onComplete(FluxMapFuseable.java:144) ~[reactor-core-3.3.3.RELEASE.jar:3.3.3.RELEASE]
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1706) ~[reactor-core-3.3.3.RELEASE.jar:3.3.3.RELEASE]
	at reactor.core.publisher.MonoCollect$CollectSubscriber.onComplete(MonoCollect.java:160) ~[reactor-core-3.3.3.RELEASE.jar:3.3.3.RELEASE]
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:136) ~[reactor-core-3.3.3.RELEASE.jar:3.3.3.RELEASE]
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onComplete(FluxDoFinally.java:138) ~[reactor-core-3.3.3.RELEASE.jar:3.3.3.RELEASE]
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:136) ~[reactor-core-3.3.3.RELEASE.jar:3.3.3.RELEASE]
	at reactor.netty.channel.FluxReceive.terminateReceiver(FluxReceive.java:419) ~[reactor-netty-0.9.5.RELEASE.jar:0.9.5.RELEASE]
	at reactor.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:209) ~[reactor-netty-0.9.5.RELEASE.jar:0.9.5.RELEASE]
	at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:367) ~[reactor-netty-0.9.5.RELEASE.jar:0.9.5.RELEASE]
	at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:363) ~[reactor-netty-0.9.5.RELEASE.jar:0.9.5.RELEASE]
	at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:412) ~[reactor-netty-0.9.5.RELEASE.jar:0.9.5.RELEASE]
	at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:585) ~[reactor-netty-0.9.5.RELEASE.jar:0.9.5.RELEASE]
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:90) ~[reactor-netty-0.9.5.RELEASE.jar:0.9.5.RELEASE]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321) ~[netty-codec-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295) ~[netty-codec-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1470) ~[netty-handler-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1231) ~[netty-handler-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1268) ~[netty-handler-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:498) ~[netty-codec-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:437) ~[netty-codec-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[netty-codec-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.handler.proxy.ProxyHandler.channelRead(ProxyHandler.java:253) ~[netty-handler-proxy-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.45.Final.jar:4.1.45.Final]
	at java.base/java.lang.Thread.run(Thread.java:832) ~[na:na]
```

**To Reproduce**
Make a REST-Call to the spring RestController. After that retrieve the required resources like ResourceGroup, Network and Subnet.
Then call the createVM method which in turn calls the resourceManager to define a virtual machine.

***Code Snippet***
   
```
public VirtualMachine createVM(Region region, ResourceGroup resourceGroup, Network network, Subnet subnet, KnownWindowsVirtualMachineImage image, VirtualMachineSizeTypes size, String vmName){
        Azure azure = this.getAzureResourceManager();
        VirtualMachine azureVm = azure.virtualMachines()
                .define(vmName)
                .withRegion(region)
                .withExistingResourceGroup(resourceGroup)
                .withExistingPrimaryNetwork(network)
                .withSubnet(subnet.name())
                .withPrimaryPrivateIPAddressDynamic()
                .withoutPrimaryPublicIPAddress()
                .withPopularWindowsImage(image)
                .withAdminUsername("myAdmin")
                .withAdminPassword("superSecretPassword")
                .withSize(size)
                .create();
        return azureVm;
    }
```

```
private Azure getAzureResourceManager(){
        if(this.azure != null){
            return this.azure;
        }
        //Setting AzureProfile
        AzureProfile azureProfile = new AzureProfile(AzureEnvironment.AZURE);
        /*Configuring Proxy*/
        ProxyOptions proxyOptions = new ProxyOptions(ProxyOptions.Type.HTTP, new InetSocketAddress("myProxy", 8080));
        HttpClient httpClient = new NettyAsyncHttpClientBuilder()
                .proxy(proxyOptions)
                .build();

        /*Building Authentication Request*/
        ClientSecretCredential clientSecretCredential = new ClientSecretCredentialBuilder()
                .clientId(this.azureClientId)
                .clientSecret(azureClientSecret)
                .tenantId(azureTenantId)
                .httpClient(httpClient)
                .build();

        /*Getting Azure Service*/
        Azure azure = Azure.configure()
                .withHttpClient(httpClient)
                .authenticate(clientSecretCredential, azureProfile)
                .withSubscription("mySubscriptionGUID");
        this.azure = azure;
        return azure;
    }
```

**Expected behavior**
Expected is that the virtual machine will be created and returned as an object.

**Setup:**
 - OS: Windows
 - IDE : IntelliJ
 - Version of the Library used:
azure-resourcemanager ->2.0.0-beta.4
azure-identity -> 1.1.2
azure-core-http-netty -> 1.6.1
spring-boot -> 2.2.5.RELEASE

**Additional context**

- Retrieving the ResourceGroup, Network and the Subnets of the Network is properly working.

- When creating the virtual machine, it does create the Network Interface which I can see in the Azure Portal in my specified resource group.

- Creating a ResourceGroup for example works perfectly fine.

- I have kind of followed this documentation: https://docs.microsoft.com/en-us/azure/virtual-machines/windows/java#create-the-virtual-machine

If there are any information I can additionally provide, please let me know.

**Comment by joshfree** [comment]
@yungezz could you please help route this issue?

**Comment by yungezz** [comment]
hi @xccc-msft could you pls help to check?

**Comment by nickzhums** [comment]
Hi @Zybrion , thanks fore reporting the issue. We'll take a look at this. 

Would you mind sharing how you have chosen to use this package ? This SDK is actually part of our next generation resource management libraries for Azure, and we are collecting customer feedback. Thanks!

**Comment by ChenTanyi** [comment]
Hi @Zybrion, the BUG is because you don't register `provider` for some resource you want to create and you also don't specify `subscription id` in `AzureProfile`. You can change either of them for a workaround (register `provider` manually or add `subscription id` in `AzureProfile`)

**Comment by Zybrion** [comment]
Hello,
thank you very much everyone for their help, especially @ChenTanyi
It was indeed a layer 8 problem. I hope at least this issue can help more people in the future.

I have made the following changes to the code:

> Old:
```
private Azure getAzureResourceManager(){
        [...]
        //Setting AzureProfile
        AzureProfile azureProfile = new AzureProfile(AzureEnvironment.AZURE);
        [...]
    }
```

> New:
```
private Azure getAzureResourceManager(){
        [...]
        //Setting AzureProfile
        AzureProfile azureProfile = new AzureProfile(azureTenantId, subscriptionId, AzureEnvironment.AZURE);
        [...]
    }
```
After that the original error was gone and a `connection refused` error replaced it.

So the next step is to register the provider:
1. way (Portal):
`Go to azure portal --> select your subscription --> go to "Resource providers" --> select the provider (in my case for VMs it is "Microsoft.Compute" --> register --> done`

2. way (API):
Have your configured `com.azure.resourcemanager.Azure` object (in my case see the Method `getAzureResourceManager()` above)
Then create the following Method and calls:
```
    public Provider registerProvider(String providerName){
        Azure azure = this.getAzureResourceManager();
        azure.providers().register(providerName);
        return azure.providers().getByName(providerName);
    }
```
Call it with `registerProvider("Microsoft.Compute")`

You can check the registration status of all providers by printing the `namespace `and `registrationState `attribute of the `Provider`
```
    public List<Provider> getAllProviders(){
        Azure azure = this.getAzureResourceManager();
        return azure.providers().list().stream().collect(Collectors.toList());
    }
```
After that it all worked for me. If it still doesn't, make sure you have enabled all the providers which are needed for your call (For example the Network or Resources provider.

@nickzhums 
I was searching for a SDK with which I can fluently create and manage Azure objects.
It was important to me that all objects are represented as a Java Class (as opposed to a JSON-Node representation via the normal REST calls). [This ](https://docs.microsoft.com/de-de/azure/virtual-machines/windows/java#create-the-virtual-machine) piece of documentation caught my attention and I knew I wanted to work this way.

I was searching for samples for how to get going. It honestly wasn't that easy to find documentation in google. I then searched this repository which was confusing at first. But I then managed to find [this key piece of documentation](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/resourcemanager#azure-management-client-library-for-java) it has all the dependencies I needed and all the basic setup which was needed to get going. The one thing that was missing was how to do it behind a corporate proxy. [This documentation](https://github.com/Azure/azure-sdk-for-java/wiki/HTTP-clients#example) helped me achieve that.

The code you see above is probably the compilation of all 3 of those documentations.

Thanks again everyone for their help and their effort to create this SDK. I appreciate it.

**Comment by nickzhums** [comment]
@Zybrion thanks so much for providing the insight, just a follow up question, how were you searching for the SDK ? e.g. the search terms you used and what part was confusing? this would be very valuable to our SEO efforts, thanks

**Comment by ChenTanyi** [comment]
@Zybrion Thanks for providing all details about it.

The `connection refused` is due to the [`ProviderRegistrationPolicy`](https://github.com/Azure/azure-sdk-for-java/blob/3a44980/sdk/resourcemanager/azure-resourcemanager-resources/src/main/java/com/azure/resourcemanager/resources/fluentcore/policy/ProviderRegistrationPolicy.java) doesn't go through your proxy. It will be resolved (maybe directly remove it from default pipeline) in the next release.

**Comment by Zybrion** [comment]
@nickzhums sure.
One of the first searches was probably "spring azure java" which lead me to [this documentation](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/) Because I had some experience with the Azure Keyvault I thought that if there are any APIs / SDK, they might also have a spring starter dependency, just like Keyvault. But there wasn't. I then searched along the lines of "create azure vm java". StackOverflow [wasn't](https://stackoverflow.com/questions/52516430/create-azure-vm-using-java) [that](https://stackoverflow.com/questions/27021041/create-virtual-machine-on-azure-with-java-sdk) [much](https://stackoverflow.com/questions/35348635/code-to-create-azure-vm-using-azure-java-sdk) [help](https://stackoverflow.com/questions/20641265/is-there-a-way-to-create-a-virtual-machine-in-microsoft-azure-using-a-java-progr). Most of the answers were old. Some had only partial answers. 

One of the main questions was which dependency I needed to use.
Diving into the [repo ](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk)I got confused. Do I need the authorization and compute aswell as resources and storage and subscription? Even when I went [further ](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/compute) there wasn't a readme or anything to guide me how I could use this SDK.
Checking out the [POM](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/compute/mgmt-v2020_06_01/pom.xml) wasn't really helpful either (obiously). But it makes it seem that I need alot of different dependencies to accomplish my goal.

Of course this repo has the [libraries overview](https://azure.github.io/azure-sdk/releases/latest/java.html). First I didn't see that there are multiple tabs (Client Libraries, Management Libraries, All). They kind of aligned with the table below and blended in. That might be just me though. So took a look at all Client Libraries and didn't find a suitable library. When I revisited it later on I found the Management Libraries tab. That looks promising. But what do I need to create a virtual machine? Only the "Resource Management - Compute" or additionally the Network, Storage, Resources, Authorization aswell? There isn't any library which combines all of them. Going to the [Microsoft Docs](https://docs.microsoft.com/en-us/java/api/overview/azure/resourcemanager-compute-readme?view=azure-java-stable) or [Github](https://github.com/Azure/azure-sdk-for-java/tree/azure-resourcemanager-compute_2.0.0/sdk/resourcemanager/azure-resourcemanager-compute/) doesn't really help either.
I could add the dependency but then what? How do I authenticate? How do I even use the SDK (besides trial and error).
Even if you can find some code online on [how to authenticate](https://docs.microsoft.com/en-us/azure/developer/java/sdk/java-sdk-azure-authenticate), it wasn't really enough because I am behind a proxy. [This](https://docs.microsoft.com/en-us/azure/developer/java/sdk/java-sdk-azure-authenticate) documentation on how to authenticate is really strange.

Over time I gathered the pieces of documentation which I mentioned in the comment above. [This ](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/resourcemanager#azure-management-client-library-for-java) documentation was really good. But it is "buried" in the resourcemanager folder. I definitely would not have googled "azure java sdk resource manager". And even if I do now there is [this](https://github.com/dx-ted-emea/Azure-Resource-Manager-Documentation/blob/master/ARM/SDKs/Java-sdk.md#create-a-virtual-machine) and  [this](https://github.com/Azure/azure-docs-sdk-java/blob/master/docs-ref-services/resources.md). Sadly I wouldn't be able to find it through google. I pretty much have to know that somewhere in the "azure-sdk-for-java" --> "sdk" --> "resourcemanager" (which looks just like another folder for more projects) there is actually the documentation I needed.

The ["old" repo](https://github.com/Azure/azure-libraries-for-java) also came up alot in the search via google. And if you read it very carefully then it says that there is a Next-Generation but it is very easy to glance over that and get stuck examining the [examples](https://github.com/Azure/azure-libraries-for-java#ready-to-run-code-samples-for-virtual-machines) which don't help you to get going with the whole process (Authenticating etc) but is nice for reference after that.

I'd say I am pretty decent at googling and finding what I need and eventually I did of course. But it wasn't as painless as I had hoped. I think a reference from the [main readme](https://github.com/Azure/azure-sdk-for-java) linking to the certain relevant other readmes like the one [which helped me alot](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/resourcemanager) would go a long way.
Or maybe I just wasn't googling the right stuff.

**Comment by nickzhums** [comment]
@Zybrion thank you for the detailed information! This helps a lot on how we can improve our visibility. Just FYI - We do have a link to the "resource manager readme" link that you finally landed on 

https://github.com/Azure/azure-sdk-for-java/blob/master/README.md

In the "Management - New Releases Section", but I think we need to make it more obvious!
