### ISSUE TITLE
Azure Datalake Gen2 Java SDK FileClient Append - Too many open files

### ISSUE THREAD

**Issue by vida-bandara-by** [Azure/azure-sdk-for-java#16931]
We have an application that constantly write to datalake. The `append` method below is called about 1000 times a minutes.
```
public class AdlAppender {

    private static final String datalake = "<<datalake-name>>";
    private static final String url = "https://<<datalake-name>>.dfs.core.windows.net";
    private static final String key = "<<access-key>>";
    private static final String container = "<<container-name>>";
    private static final String fileName = "<<file-path>>";

    final DataLakeFileClient fileClient;

    public AdlAppender() {
        final StorageSharedKeyCredential credential = new StorageSharedKeyCredential(datalake, key);

        final DataLakeServiceClient dataLakeServiceClient = new DataLakeServiceClientBuilder()
            .endpoint(url)
            .credential(credential)
            .buildClient();

        final DataLakeFileSystemClient fileSystemClient = dataLakeServiceClient.getFileSystemClient(container);

        fileClient = fileSystemClient.createFile(fileName);
    }

    public long append(final String content, final long offset) {
        final byte[] bytes = content.getBytes(StandardCharsets.UTF_8);
        final int length = bytes.length;
        final ByteArrayInputStream inputStream = new ByteArrayInputStream(bytes);

        fileClient.append(inputStream, offset, length);

        final long updatedOffset = offset + length;
        fileClient.flush(updatedOffset);

        return updatedOffset;
    }
}
```

Sometimes, running this code continuously for 3-4 days caused running out of file descriptors throughout the application.

Is there a way to make the Datalake client release file descriptors faster?

```
io.netty.channel.ChannelException: io.netty.channel.unix.Errors$NativeIoException: newSocketStream(..) failed: Too many open files
	at io.netty.channel.unix.Socket.newSocketStream0(Socket.java:421) ~[netty-transport-native-unix-common-4.1.50.Final.jar!/:4.1.50.Final]
	at io.netty.channel.epoll.LinuxSocket.newSocketStream(LinuxSocket.java:319) ~[netty-transport-native-epoll-4.1.50.Final-linux-x86_64.jar!/:4.1.50.Final]
	at io.netty.channel.epoll.LinuxSocket.newSocketStream(LinuxSocket.java:323) ~[netty-transport-native-epoll-4.1.50.Final-linux-x86_64.jar!/:4.1.50.Final]
	at io.netty.channel.epoll.EpollSocketChannel.<init>(EpollSocketChannel.java:45) ~[netty-transport-native-epoll-4.1.50.Final-linux-x86_64.jar!/:4.1.50.Final]
	at reactor.netty.resources.DefaultLoopEpoll.getChannel(DefaultLoopEpoll.java:45) ~[reactor-netty-0.9.8.RELEASE.jar!/:0.9.8.RELEASE]
	at reactor.netty.resources.LoopResources.onChannel(LoopResources.java:187) ~[reactor-netty-0.9.8.RELEASE.jar!/:0.9.8.RELEASE]
	at reactor.netty.resources.LoopResources.onChannel(LoopResources.java:169) ~[reactor-netty-0.9.8.RELEASE.jar!/:0.9.8.RELEASE]
	at reactor.netty.tcp.TcpResources.onChannel(TcpResources.java:215) ~[reactor-netty-0.9.8.RELEASE.jar!/:0.9.8.RELEASE]
	at reactor.netty.http.client.HttpClientConnect$HttpTcpClient.connect(HttpClientConnect.java:141) ~[reactor-netty-0.9.8.RELEASE.jar!/:0.9.8.RELEASE]
	at reactor.netty.tcp.TcpClientOperator.connect(TcpClientOperator.java:43) ~[reactor-netty-0.9.8.RELEASE.jar!/:0.9.8.RELEASE]
	at reactor.netty.tcp.TcpClientOperator.connect(TcpClientOperator.java:43) ~[reactor-netty-0.9.8.RELEASE.jar!/:0.9.8.RELEASE]
	at reactor.netty.tcp.TcpClientOperator.connect(TcpClientOperator.java:43) ~[reactor-netty-0.9.8.RELEASE.jar!/:0.9.8.RELEASE]
	at reactor.netty.tcp.TcpClientOperator.connect(TcpClientOperator.java:43) ~[reactor-netty-0.9.8.RELEASE.jar!/:0.9.8.RELEASE]
	at reactor.netty.tcp.TcpClientOperator.connect(TcpClientOperator.java:43) ~[reactor-netty-0.9.8.RELEASE.jar!/:0.9.8.RELEASE]
	at reactor.netty.tcp.TcpClient.connect(TcpClient.java:202) ~[reactor-netty-0.9.8.RELEASE.jar!/:0.9.8.RELEASE]
	at reactor.netty.http.client.HttpClientFinalizer.connect(HttpClientFinalizer.java:77) ~[reactor-netty-0.9.8.RELEASE.jar!/:0.9.8.RELEASE]
	at reactor.netty.http.client.HttpClientFinalizer.responseConnection(HttpClientFinalizer.java:94) ~[reactor-netty-0.9.8.RELEASE.jar!/:0.9.8.RELEASE]
	at com.azure.core.http.netty.NettyAsyncHttpClient.send(NettyAsyncHttpClient.java:76) ~[azure-core-http-netty-1.5.4.jar!/:na]
	at com.azure.core.http.HttpPipelineNextPolicy.process(HttpPipelineNextPolicy.java:44) ~[azure-core-1.7.0.jar!/:na]
	at com.azure.storage.common.policy.ScrubEtagPolicy.process(ScrubEtagPolicy.java:35) ~[azure-storage-common-12.8.0.jar!/:na]
	at com.azure.core.http.HttpPipelineNextPolicy.process(HttpPipelineNextPolicy.java:46) ~[azure-core-1.7.0.jar!/:na]
	at com.azure.core.http.policy.HttpLoggingPolicy.process(HttpLoggingPolicy.java:72) ~[azure-core-1.7.0.jar!/:na]
	at com.azure.core.http.HttpPipelineNextPolicy.process(HttpPipelineNextPolicy.java:46) ~[azure-core-1.7.0.jar!/:na]
	at com.azure.storage.common.policy.ResponseValidationPolicyBuilder$ResponseValidationPolicy.process(ResponseValidationPolicyBuilder.java:77) ~[azure-storage-common-12.8.0.jar!/:na]
	at com.azure.core.http.HttpPipelineNextPolicy.process(HttpPipelineNextPolicy.java:46) ~[azure-core-1.7.0.jar!/:na]
	at com.azure.storage.common.policy.StorageSharedKeyCredentialPolicy.process(StorageSharedKeyCredentialPolicy.java:41) ~[azure-storage-common-12.8.0.jar!/:na]
	at com.azure.core.http.HttpPipelineNextPolicy.process(HttpPipelineNextPolicy.java:46) ~[azure-core-1.7.0.jar!/:na]
	at com.azure.core.http.policy.AddDatePolicy.lambda$process$0(AddDatePolicy.java:29) ~[azure-core-1.7.0.jar!/:na]
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44) ~[reactor-core-3.3.6.RELEASE.jar!/:3.3.6.RELEASE]
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[reactor-core-3.3.6.RELEASE.jar!/:3.3.6.RELEASE]
	at reactor.core.publisher.MonoDelaySubscription.accept(MonoDelaySubscription.java:52) ~[reactor-core-3.3.6.RELEASE.jar!/:3.3.6.RELEASE]
	at reactor.core.publisher.MonoDelaySubscription.accept(MonoDelaySubscription.java:33) ~[reactor-core-3.3.6.RELEASE.jar!/:3.3.6.RELEASE]
	at reactor.core.publisher.FluxDelaySubscription$DelaySubscriptionOtherSubscriber.onNext(FluxDelaySubscription.java:123) ~[reactor-core-3.3.6.RELEASE.jar!/:3.3.6.RELEASE]
	at reactor.core.publisher.MonoDelay$MonoDelayRunnable.run(MonoDelay.java:117) ~[reactor-core-3.3.6.RELEASE.jar!/:3.3.6.RELEASE]
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68) ~[reactor-core-3.3.6.RELEASE.jar!/:3.3.6.RELEASE]
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28) ~[reactor-core-3.3.6.RELEASE.jar!/:3.3.6.RELEASE]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_265]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_265]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_265]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_265]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_265]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_265]
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99) ~[reactor-core-3.3.6.RELEASE.jar!/:3.3.6.RELEASE]
		at reactor.core.publisher.Mono.block(Mono.java:1679) ~[reactor-core-3.3.6.RELEASE.jar!/:3.3.6.RELEASE]
		at com.azure.storage.common.implementation.StorageImplUtils.blockWithOptionalTimeout(StorageImplUtils.java:99) ~[azure-storage-common-12.8.0.jar!/:na]
		at com.azure.storage.blob.specialized.BlobClientBase.getPropertiesWithResponse(BlobClientBase.java:708) ~[azure-storage-blob-12.8.0.jar!/:na]
		at com.azure.storage.file.datalake.DataLakePathClient.lambda$getPropertiesWithResponse$2(DataLakePathClient.java:432) ~[azure-storage-file-datalake-12.2.0.jar!/:na]
		at com.azure.storage.file.datalake.implementation.util.DataLakeImplUtils.returnOrConvertException(DataLakeImplUtils.java:36) ~[azure-storage-file-datalake-12.2.0.jar!/:na]
		at com.azure.storage.file.datalake.DataLakePathClient.getPropertiesWithResponse(DataLakePathClient.java:431) ~[azure-storage-file-datalake-12.2.0.jar!/:na]
		at com.azure.storage.file.datalake.DataLakePathClient.getProperties(DataLakePathClient.java:411) ~[azure-storage-file-datalake-12.2.0.jar!/:na]
		at com.acme.analytics.dl.RetryingAdlClient.getAdlFile(RetryingAdlClient.java:95) ~[classes!/:na]
		at com.acme.analytics.dl.RetryingAdlClient.recoverWrite(RetryingAdlClient.java:169) ~[classes!/:na]
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_265]
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_265]
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_265]
		at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_265]
		at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:282) ~[spring-core-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
		at org.springframework.retry.annotation.RecoverAnnotationRecoveryHandler.recover(RecoverAnnotationRecoveryHandler.java:73) ~[spring-retry-1.2.5.RELEASE.jar!/:na]
		at org.springframework.retry.interceptor.RetryOperationsInterceptor$ItemRecovererCallback.recover(RetryOperationsInterceptor.java:141) ~[spring-retry-1.2.5.RELEASE.jar!/:na]
		at org.springframework.retry.support.RetryTemplate.handleRetryExhausted(RetryTemplate.java:512) ~[spring-retry-1.2.5.RELEASE.jar!/:na]
		at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:351) ~[spring-retry-1.2.5.RELEASE.jar!/:na]
		at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:180) ~[spring-retry-1.2.5.RELEASE.jar!/:na]
		at org.springframework.retry.interceptor.RetryOperationsInterceptor.invoke(RetryOperationsInterceptor.java:115) ~[spring-retry-1.2.5.RELEASE.jar!/:na]
		at org.springframework.retry.annotation.AnnotationAwareRetryOperationsInterceptor.invoke(AnnotationAwareRetryOperationsInterceptor.java:153) ~[spring-retry-1.2.5.RELEASE.jar!/:na]
		at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
		at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
		at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691) ~[spring-aop-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
		at com.acme.analytics.dl.RetryingAdlClient$$EnhancerBySpringCGLIB$$6757b63e.write(<generated>) ~[classes!/:na]
		at sun.reflect.GeneratedMethodAccessor556.invoke(Unknown Source) ~[na:na]
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_265]
		at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_265]
		at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:282) ~[spring-core-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
		at org.springframework.cloud.context.scope.GenericScope$LockedScopedProxyFactoryBean.invoke(GenericScope.java:499) ~[spring-cloud-context-2.2.3.RELEASE.jar!/:2.2.3.RELEASE]
		at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
		at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
		at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691) ~[spring-aop-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
		at com.acme.analytics.dl.RetryingAdlClient$$EnhancerBySpringCGLIB$$b635663a.write(<generated>) ~[classes!/:na]
		at com.acme.analytics.dl.AdlFileAppender.append(AdlFileAppender.java:97) ~[classes!/:na]
		at sun.reflect.GeneratedMethodAccessor557.invoke(Unknown Source) ~[na:na]
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_265]
		at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_265]
		at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:282) ~[spring-core-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
		at org.springframework.cloud.context.scope.GenericScope$LockedScopedProxyFactoryBean.invoke(GenericScope.java:499) ~[spring-cloud-context-2.2.3.RELEASE.jar!/:2.2.3.RELEASE]
		at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
		at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
		at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691) ~[spring-aop-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
		at com.acme.analytics.dl.AdlFileAppender$$EnhancerBySpringCGLIB$$ebd68dec.append(<generated>) ~[classes!/:na]
		at com.acme.analytics.kpi.BaseSynapseSync.writeToDataLake(BaseSynapseSync.java:222) [classes!/:na]
		at com.acme.analytics.kpi.BaseSynapseSync.lambda$sync$0(BaseSynapseSync.java:121) [classes!/:na]
		at com.acme.analytics.common.LoggingExecutor.execute(LoggingExecutor.java:46) ~[classes!/:na]
		at com.acme.analytics.kpi.BaseSynapseSync.sync(BaseSynapseSync.java:120) [classes!/:na]
		at com.acme.analytics.consumer.AnalyticsConsumer.syncSynapse(AnalyticsConsumer.java:283) [classes!/:na]
		at com.acme.analytics.consumer.AnalyticsConsumer.lambda$sendToSynapse$6(AnalyticsConsumer.java:221) [classes!/:na]
		at com.acme.analytics.common.LoggingExecutor.execute(LoggingExecutor.java:46) ~[classes!/:na]
		at com.acme.analytics.consumer.AnalyticsConsumer.sendToSynapse(AnalyticsConsumer.java:220) [classes!/:na]
		at com.acme.analytics.consumer.AnalyticsConsumer.consume(AnalyticsConsumer.java:151) [classes!/:na]
		at com.acme.analytics.consumer.AnalyticsConsumer.listen(AnalyticsConsumer.java:140) [classes!/:na]
		at com.acme.analytics.consumer.AnalyticsConsumer$$FastClassBySpringCGLIB$$99f87259.invoke(<generated>) ~[classes!/:na]
		at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
		at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771) ~[spring-aop-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
		at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
		at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
		at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:100) ~[spring-aop-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
		at com.acme.kafka.KafkaAspect.handleBatchMessageContext(KafkaAspect.java:205) ~[kafkaclient-2020.2.3-rc-46.jar!/:na]
		at sun.reflect.GeneratedMethodAccessor562.invoke(Unknown Source) ~[na:na]
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_265]
		at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_265]
		at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644) ~[spring-aop-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
		at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633) ~[spring-aop-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
		at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70) ~[spring-aop-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
		at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175) ~[spring-aop-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
		at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
		at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95) ~[spring-aop-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
		at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
		at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
		at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691) ~[spring-aop-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
		at com.acme.analytics.consumer.AnalyticsConsumer$$EnhancerBySpringCGLIB$$faf79fc7.listen(<generated>) ~[classes!/:na]
		at sun.reflect.GeneratedMethodAccessor561.invoke(Unknown Source) ~[na:na]
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_265]
		at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_265]
		at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:171) ~[spring-messaging-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
		at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:120) ~[spring-messaging-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
		at org.springframework.kafka.listener.adapter.HandlerAdapter.invoke(HandlerAdapter.java:48) ~[spring-kafka-2.2.4.RELEASE.jar!/:2.2.4.RELEASE]
		at org.springframework.kafka.listener.adapter.MessagingMessageListenerAdapter.invokeHandler(MessagingMessageListenerAdapter.java:283) ~[spring-kafka-2.2.4.RELEASE.jar!/:2.2.4.RELEASE]
		at org.springframework.kafka.listener.adapter.BatchMessagingMessageListenerAdapter.invoke(BatchMessagingMessageListenerAdapter.java:146) ~[spring-kafka-2.2.4.RELEASE.jar!/:2.2.4.RELEASE]
		at org.springframework.kafka.listener.adapter.BatchMessagingMessageListenerAdapter.onMessage(BatchMessagingMessageListenerAdapter.java:138) ~[spring-kafka-2.2.4.RELEASE.jar!/:2.2.4.RELEASE]
		at org.springframework.kafka.listener.adapter.BatchMessagingMessageListenerAdapter.onMessage(BatchMessagingMessageListenerAdapter.java:59) ~[spring-kafka-2.2.4.RELEASE.jar!/:2.2.4.RELEASE]
		at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeBatchOnMessage(KafkaMessageListenerContainer.java:1057) ~[spring-kafka-2.2.4.RELEASE.jar!/:2.2.4.RELEASE]
		at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeBatchOnMessage(KafkaMessageListenerContainer.java:1041) ~[spring-kafka-2.2.4.RELEASE.jar!/:2.2.4.RELEASE]
		at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeBatchListener(KafkaMessageListenerContainer.java:1005) ~[spring-kafka-2.2.4.RELEASE.jar!/:2.2.4.RELEASE]
		at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeBatchListener(KafkaMessageListenerContainer.java:948) ~[spring-kafka-2.2.4.RELEASE.jar!/:2.2.4.RELEASE]
		at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeListener(KafkaMessageListenerContainer.java:931) ~[spring-kafka-2.2.4.RELEASE.jar!/:2.2.4.RELEASE]
		at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.pollAndInvoke(KafkaMessageListenerContainer.java:750) ~[spring-kafka-2.2.4.RELEASE.jar!/:2.2.4.RELEASE]
		at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:699) ~[spring-kafka-2.2.4.RELEASE.jar!/:2.2.4.RELEASE]
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_265]
		at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_265]
		... 1 common frames omitted
Caused by: io.netty.channel.unix.Errors$NativeIoException: newSocketStream(..) failed: Too many open files
```

**Comment by rickle-msft** [comment]
@alzimmermsft @anuchandy Have you guys seen cases where netty runs out of sockets?

**Comment by alzimmermsft** [comment]
This may be a scenario where the underlying operating system has ran out of file descriptors and prevents Netty from opening up another network socket (using another file descriptor).

Looking at the stack trace Reactor Netty 0.9.8 is being used, so this issue may be related to this: https://github.com/reactor/reactor-netty/issues/1152.

**Comment by vida-bandara-by** [comment]
Hi @alzimmermsft ,
Thank you very much for your reply.
I tried
```
gradle dependencyInsight --configuration compile --dependency reactor-netty
```
and got
```
> Task :dependencyInsight
io.projectreactor.netty:reactor-netty:0.9.8.RELEASE (selected by rule)
   variant "runtime" [
      org.gradle.status          = release (not requested)
      org.gradle.usage           = java-runtime (not requested)
      org.gradle.libraryelements = jar (not requested)
      org.gradle.category        = library (not requested)
   ]

io.projectreactor.netty:reactor-netty:0.9.10.RELEASE -> 0.9.8.RELEASE
\--- com.azure:azure-core-http-netty:1.5.4
     \--- com.azure:azure-storage-common:12.8.0
          +--- com.azure:azure-storage-blob:12.8.0
          |    \--- com.azure:azure-storage-file-datalake:12.2.0
          |         \--- compile
          \--- com.azure:azure-storage-internal-avro:12.0.0
               \--- com.azure:azure-storage-blob:12.8.0 (*)
```

Let me try overriding `reactor-netty` to `0.9.9+` as you suggested and get back to you.

Thank you so much again for your help!

**Comment by vida-bandara-by** [comment]
Observed a week after updating `reactor-netty`. No longer see the issue.
Thank you very much, @alzimmermsft!
