### ISSUE TITLE
Cosmos GoneAndRetryWithRetryPolicy  bad log message

### ISSUE THREAD

**Issue by moderakh** [Azure/azure-sdk-for-java#17038]
GoneAndRetryWithPolicy logs failure for 404, Logging in warn level is incorrect and will cause confusion to end users:

```bash
2020-10-30 14:27:28,946       [cosmos-rntbd-nio-2-2] WARN  com.azure.cosmos.implementation.directconnectivity.GoneAndRetryWithRetryPolicy - Operation will NOT be retried. Current attempt 1, Exception: 
com.azure.cosmos.implementation.NotFoundException: ["Resource Not Found"]
	at com.azure.cosmos.implementation.directconnectivity.rntbd.RntbdRequestManager.messageReceived(RntbdRequestManager.java:812) [classes/:?]
	at com.azure.cosmos.implementation.directconnectivity.rntbd.RntbdRequestManager.channelRead(RntbdRequestManager.java:181) [classes/:?]
```

The log level for any failure (e.g. 404) which is not related to GoneAndRetryWithRetryPolicy should be debug not warn. This will be confusing the customers.

**Comment by kushagraThapar** [comment]
This has been fixed, closing it.

**Comment by moderakh** [comment]
@kushagraThapar I am not sure if it is fixed.
Which PR fixed this?

**Comment by kushagraThapar** [comment]
I see it as fixed in master code - https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/directconnectivity/GoneAndRetryWithRetryPolicy.java

Different PRs fixed it.
