### ISSUE TITLE
ContainerService - fail to update when using Kubernetes orchestration

### ISSUE THREAD

**Issue by milismsft** [Azure/azure-sdk-for-java#1736]
Call stack:

[RxIoScheduler-2] INFO com.microsoft.azure.management.compute.ContainerServices createOrUpdate (poll) - <-- END HTTP
servicePrincipalProfile.secret is required and cannot be null.
java.lang.IllegalArgumentException: servicePrincipalProfile.secret is required and cannot be null.
at com.microsoft.rest.Validator.validate(Validator.java:108)
at com.microsoft.azure.management.compute.implementation.ContainerServicesInner.createOrUpdateWithServiceResponseAsync(ContainerServicesInner.java:288)
at com.microsoft.azure.management.compute.implementation.ContainerServicesInner.createOrUpdateAsync(ContainerServicesInner.java:257)
at com.microsoft.azure.management.compute.implementation.ContainerServiceImpl.createResourceAsync(ContainerServiceImpl.java:302)
at com.microsoft.azure.management.resources.fluentcore.model.implementation.CreatableUpdatableImpl.updateResourceAsync(CreatableUpdatableImpl.java:149)
at com.microsoft.azure.management.resources.fluentcore.model.implementation.CreateUpdateTask.executeAsync(CreateUpdateTask.java:65)
at com.microsoft.azure.management.resources.fluentcore.dag.TaskGroupEntry.executeTaskAsync(TaskGroupEntry.java:77)
at com.microsoft.azure.management.resources.fluentcore.dag.TaskGroup.executeTaskAsync(TaskGroup.java:208)
at com.microsoft.azure.management.resources.fluentcore.dag.TaskGroup.executeReadyTasksAsync(TaskGroup.java:168)
at com.microsoft.azure.management.resources.fluentcore.dag.TaskGroup.processCompletedTaskAsync(TaskGroup.java:224)
at com.microsoft.azure.management.resources.fluentcore.dag.TaskGroup.access$100(TaskGroup.java:24)
at com.microsoft.azure.management.resources.fluentcore.dag.TaskGroup$3.call(TaskGroup.java:186)
at com.microsoft.azure.management.resources.fluentcore.dag.TaskGroup$3.call(TaskGroup.java:182)
at rx.internal.operators.OperatorMapNotification$MapNotificationSubscriber.onCompleted(OperatorMapNotification.java:117)
at rx.internal.util.ScalarSynchronousObservable$WeakSingleProducer.request(ScalarSynchronousObservable.java:285)
at rx.internal.operators.OperatorMapNotification$MapNotificationSubscriber.setProducer(OperatorMapNotification.java:136)
at rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call(ScalarSynchronousObservable.java:138)
at rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call(ScalarSynchronousObservable.java:129)
at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
at rx.Observable.unsafeSubscribe(Observable.java:10142)
at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:248)
at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:148)
at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.fastPath(OnSubscribeFromIterable.java:173)
at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.request(OnSubscribeFromIterable.java:86)
at rx.Subscriber.setProducer(Subscriber.java:211)
at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:63)
at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:34)
at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
at rx.Observable.unsafeSubscribe(Observable.java:10142)
at rx.internal.operators.DeferredScalarSubscriber.subscribeTo(DeferredScalarSubscriber.java:153)
at rx.internal.operators.OnSubscribeTakeLastOne.call(OnSubscribeTakeLastOne.java:32)
at rx.internal.operators.OnSubscribeTakeLastOne.call(OnSubscribeTakeLastOne.java:22)
at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
at rx.Observable.unsafeSubscribe(Observable.java:10142)
at rx.internal.operators.DeferredScalarSubscriber.subscribeTo(DeferredScalarSubscriber.java:153)
at rx.internal.operators.OnSubscribeTakeLastOne.call(OnSubscribeTakeLastOne.java:32)
at rx.internal.operators.OnSubscribeTakeLastOne.call(OnSubscribeTakeLastOne.java:22)
at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
at rx.Observable.subscribe(Observable.java:10238)
at rx.Observable.subscribe(Observable.java:10205)
at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:444)
at rx.observables.BlockingObservable.last(BlockingObservable.java:227)
at com.microsoft.azure.management.resources.fluentcore.model.implementation.CreatableUpdatableImpl.apply(CreatableUpdatableImpl.java:144)
at com.microsoft.azure.management.resources.fluentcore.model.implementation.CreatableUpdatableImpl.apply(CreatableUpdatableImpl.java:28)
at com.microsoft.azure.management.compute.samples.ManageContainerService.runSample(ManageContainerService.java:60)
at com.microsoft.azure.management.compute.samples.ManageContainerService.main(ManageContainerService.java:101)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
 
Process finished with exit code 0

**Comment by martinsawicki** [comment]
fixed
