### ISSUE TITLE
[BUG] 'Session lock lost and cannot be used' message

### ISSUE THREAD

**Issue by cristibozga** [Azure/azure-sdk-for-java#17443]
**Describe the bug**
We have a session queue where we receive from time to time the error 'Session lock lost and cannot be used' message'. The result is that in a couple of minutes all the queue listeners are dying, i.e no message is received from that queue and the application blocks
On this queue we process about 350K messages every day.
We are using the version 3.4.0 of the service-bus sdk

***Exception or Stack Trace***
ava.lang.IllegalStateException: Session lock lost and cannot be used. Close this session and accept another session.
 at com.microsoft.azure.servicebus.primitives.CoreMessageReceiver.throwIfInUnusableState(CoreMessageReceiver.java:411) ~[azure-servicebus-3.4.0.jar!/:?] 
at com.microsoft.azure.servicebus.MessageReceiver.lambda$completeAsync$7(MessageReceiver.java:265) ~[azure-servicebus-3.4.0.jar!/:?] 
at com.microsoft.azure.servicebus.MessageReceiver.completeAsync(MessageReceiver.java:253) ~[azure-servicebus-3.4.0.jar!/:?] 
at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456) ~[?:1.8.0_252]
at com.microsoft.azure.servicebus.primitives.CoreMessageReceiver.completeMessageAsync(CoreMessageReceiver.java:897) ~[azure-servicebus-3.4.0.jar!/:?] 
at com.microsoft.azure.servicebus.MessageReceiver.lambda$completeAsync$7(MessageReceiver.java:265) ~[azure-servicebus-3.4.0.jar!/:?] 
at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:995) ~[?:1.8.0_252] 
at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2137) ~[?:1.8.0_252] 
at com.microsoft.azure.servicebus.MessageReceiver.completeAsync(MessageReceiver.java:260) ~[azure-servicebus-3.4.0.jar!/:?] 
at com.microsoft.azure.servicebus.MessageSession.completeAsync(MessageSession.java:14) ~[azure-servicebus-3.4.0.jar!/:?] 
at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:811) ~[?:1.8.0_252] 
at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456) ~[?:1.8.0_252] 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
at com.microsoft.azure.servicebus.primitives.CoreMessageReceiver.updateMessageStateAsync(CoreMessageReceiver.java:990) ~[azure-servicebus-3.4.0.jar!/:?] at com.microsoft.azure.servicebus.primitives.CoreMessageReceiver.completeMessageAsync(CoreMessageReceiver.java:897) ~[azure-servicebus-3.4.0.jar!/:?] 
at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:995) ~[?:1.8.0_252] 
at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2137) ~[?:1.8.0_252] 
at com.microsoft.azure.servicebus.MessageReceiver.completeAsync(MessageReceiver.java:260) ~[azure-servicebus-3.4.0.jar!/:?] 
at com.microsoft.azure.servicebus.MessageSession.completeAsync(MessageSession.java:14) ~[azure-servicebus-3.4.0.jar!/:?] 
at com.microsoft.azure.servicebus.MessageSession.completeAsync(MessageSession.java:14) ~[azure-servicebus-3.4.0.jar!/:?] 
at com.microsoft.azure.servicebus.MessageAndSessionPump.lambda$receiveFromSessionAndPumpMessage$11(MessageAndSessionPump.java:356) ~[azure-servicebus-3.4.0.jar!/:?] 
at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:836) ~[?:1.8.0_252] 
at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:811) ~[?:1.8.0_252] 
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252] 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252] 
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]

**To Reproduce**
I cannot reproduce the error. I don't know how to do it. The other queues that we use do not have this problem

***Code Snippet***
This is the way we create the QueueClient: 
public QueueClient getSessionQueueClient(String queueName, MessageHandler messageHandler, SessionQueueListenerProperties listenerProperties) {
        ConnectionStringBuilder csb = new ConnectionStringBuilder(serviceBusProperties.getConnectionString(),
                                                                  queueName);
        try {
            QueueClient queueClient = new QueueClient(csb, ReceiveMode.PEEKLOCK);

            ServiceBusSessionQueueMessageHandlerAdapter serviceBusMessageHandler =
                    new ServiceBusSessionQueueMessageHandlerAdapter(queueName,
                                                                    messageHandler,
                                                                    serviceBusMessageConverter);
            SessionHandlerOptions messageHandlerOptions =
                    new SessionHandlerOptions(listenerProperties.getMaxConcurrentCalls(),
                                              listenerProperties.getMaxConcurrentCallsPerSession(),
                                              listenerProperties.isAutoComplete(),
                                              Duration.ofSeconds(listenerProperties.getMaxAutoRenewDuration()),
                                              Duration.ofMillis(listenerProperties.getMessageWaitingDuration()));

            queueClient.registerSessionHandler(serviceBusMessageHandler, messageHandlerOptions, executor);
            LOGGER.info("Registered session queue client for queue '{}'", queueName);
            return queueClient;
        } catch (InterruptedException | ServiceBusException e) {
            LOGGER.error("Failed to get session queue client for queue '{}'", queueName);
        }

here there are the default properties for the sessionHandler: 

    boolean autoComplete() default true;
    int maxConcurrentCalls() default 20;
    int maxAutoRenewDuration() default 30;
    int maxConcurrentCallsPerSession() default 1;
    int messageWaitDuration() default 1000;

Here's the implementation of the ISessionHandler: 

  @Override
    public CompletableFuture<Void> onMessageAsync(IMessageSession session, IMessage message) {
        try {
            Message m = messageConverter.convertFromServiceBusMessage(message, queueName);
            messageHandler.handleMessage(m);
        }catch (IllegalStateException ex){
            LOGGER.error("Illegal state exception cought", ex);
            return session.closeAsync();
        }

        return CompletableFuture.completedFuture(null);
    }

    @Override
    public CompletableFuture<Void> OnCloseSessionAsync(IMessageSession session) {
        LOGGER.info("Session {} is closed", session.getSessionId());
        return CompletableFuture.completedFuture(null);
    }

    @Override
    public void notifyException(Throwable exception, ExceptionPhase phase) {
        LOGGER.error("Exception on phase {}", phase, exception);

    }

If there's such an IllegalState exception it will not arrive to the 'onMessageAsync' method, so I cannot close manually the session. 

**Expected behavior**
How can I avoid this problem? And if the problem occurs, how can I handle the problem and where?  

**Screenshots**

**Setup (please complete the following information):**
 - OS: Openshift on Azure
 - IDE : IntekiJ
 - Version of the Library used: 3.4.0

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x ] Bug Description Added
- [x ] Repro Steps Added
- [x ] Setup information Added

As it is my first ticket for  service-bus sdk, please tell me if I have to change or to add something  in its description.

Thanks in advance

**Comment by joshfree** [comment]
@yvgopal could you please help route this reported issue in Service Bus v3?

**Comment by cristibozga** [comment]
I succeeded to reproduce it locally by running some test application on debug mode: 
I sent 2 messages on the same session on the queue. 
I set a breakpoint on CoreMessageReceiver and manually set the  'isSessionLockLost' to 'true' when the first message arrived.
Afterwards put another break on 'onError()' method and wait a couple of seconds

The result was that sometimes the 2 messages were no longer processed on this queue. The queue seems to be blocked.
When I restart the application the 2 messages are processed

here are the logs: 
( a.bus.SessionQueueMessageConsumer is the session handler)

[2020-11-15 15:32:16,276] [pool-1-thread-3] INFO  com.microsoft.azure.servicebus.MessageAndSessionPump  - Completing message with sequence number '3699' failed
java.lang.IllegalStateException: Session lock lost and cannot be used. Close this session and accept another session.
	at com.microsoft.azure.servicebus.primitives.CoreMessageReceiver.throwIfInUnusableState(CoreMessageReceiver.java:411)
	at com.microsoft.azure.servicebus.primitives.CoreMessageReceiver.updateMessageStateAsync(CoreMessageReceiver.java:990)
	at com.microsoft.azure.servicebus.primitives.CoreMessageReceiver.completeMessageAsync(CoreMessageReceiver.java:897)
	at com.microsoft.azure.servicebus.MessageReceiver.lambda$completeAsync$7(MessageReceiver.java:265)
	at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:981)
	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2124)
	at com.microsoft.azure.servicebus.MessageReceiver.completeAsync(MessageReceiver.java:260)
	at com.microsoft.azure.servicebus.MessageSession.completeAsync(MessageSession.java:14)
	at com.microsoft.azure.servicebus.MessageReceiver.completeAsync(MessageReceiver.java:253)
	at com.microsoft.azure.servicebus.MessageSession.completeAsync(MessageSession.java:14)
	at com.microsoft.azure.servicebus.MessageAndSessionPump.lambda$receiveFromSessionAndPumpMessage$11(MessageAndSessionPump.java:356)
	at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:822)
	at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:797)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-11-15 15:32:16,282] [pool-3-thread-1] INFO  a.bus.SessionQueueMessageConsumer  - COMPLETE-java.lang.IllegalStateException: Session lock lost and cannot be used. Close this session and accept another session.
[2020-11-15 15:33:20,868] [ReactorThreadd804288b-db0d-4c3c-a066-4a792d6339f7] INFO  com.microsoft.azure.servicebus.primitives.CoreMessageReceiver  - Receive link 'Receiver_73659f_1629e2174bb54b7090757976e7dfb209_G10' to 'cristisession1', sessionId '0' closed with error.
com.microsoft.azure.servicebus.primitives.SessionLockLostException: The session lock has expired on the MessageSession. Accept a new MessageSession. TrackingId:37d1eea8000093080047a8845fb13be6_G10_B5, SystemTracker:dummy-standard:Queue:cristisession1, Timestamp:2020-11-15T14:32:36
	at com.microsoft.azure.servicebus.primitives.ExceptionUtil.toException(ExceptionUtil.java:63)
	at com.microsoft.azure.servicebus.primitives.CoreMessageReceiver.onClose(CoreMessageReceiver.java:826)
	at com.microsoft.azure.servicebus.amqp.BaseLinkHandler.processOnClose(BaseLinkHandler.java:68)
	at com.microsoft.azure.servicebus.amqp.BaseLinkHandler.onLinkRemoteClose(BaseLinkHandler.java:43)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:176)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291)
	at com.microsoft.azure.servicebus.primitives.MessagingFactory$RunReactor.run(MessagingFactory.java:556)
	at java.lang.Thread.run(Thread.java:748)
[2020-11-15 15:33:20,869] [ReactorThreadd804288b-db0d-4c3c-a066-4a792d6339f7] INFO  com.microsoft.azure.servicebus.primitives.CoreMessageReceiver  - Completeing all updateState operations on the receiver to 'cristisession1'
[2020-11-15 15:33:20,869] [ReactorThreadd804288b-db0d-4c3c-a066-4a792d6339f7] INFO  com.microsoft.azure.servicebus.primitives.CoreMessageReceiver  - SessionId '0' lock lost. Closing receiver.
[2020-11-15 15:33:20,871] [ReactorThreadd804288b-db0d-4c3c-a066-4a792d6339f7] INFO  com.microsoft.azure.servicebus.primitives.CoreMessageReceiver  - Completeing all receive operations on the receiver to 'cristisession1'
[2020-11-15 15:33:20,877] [ReactorThreadd804288b-db0d-4c3c-a066-4a792d6339f7] INFO  com.microsoft.azure.servicebus.primitives.CoreMessageReceiver  - Receive link to 'cristisession1' opened.
[2020-11-15 15:33:20,878] [ReactorThreadd804288b-db0d-4c3c-a066-4a792d6339f7] INFO  com.microsoft.azure.servicebus.primitives.CoreMessageReceiver  - Accepted session with id '0', lockedUntilUtc '2020-11-15T14:33:06.692481500Z' from 'cristisession1'.
[2020-11-15 15:33:22,270] [ReactorThreadd804288b-db0d-4c3c-a066-4a792d6339f7] INFO  com.microsoft.azure.servicebus.primitives.CoreMessageReceiver  - Receive link 'Receiver_06c54b_1629e2174bb54b7090757976e7dfb209_G10' to 'cristisession1', sessionId '0' closed with error.
com.microsoft.azure.servicebus.primitives.SessionLockLostException: The session lock has expired on the MessageSession. Accept a new MessageSession. TrackingId:37d1eea8000093080047a8855fb13c04_G10_B5, SystemTracker:dummy-standard:Queue:cristisession1, Timestamp:2020-11-15T14:33:06
	at com.microsoft.azure.servicebus.primitives.ExceptionUtil.toException(ExceptionUtil.java:63)
	at com.microsoft.azure.servicebus.primitives.CoreMessageReceiver.onClose(CoreMessageReceiver.java:826)
	at com.microsoft.azure.servicebus.amqp.BaseLinkHandler.processOnClose(BaseLinkHandler.java:68)
	at com.microsoft.azure.servicebus.amqp.BaseLinkHandler.onLinkRemoteClose(BaseLinkHandler.java:43)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:176)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291)
	at com.microsoft.azure.servicebus.primitives.MessagingFactory$RunReactor.run(MessagingFactory.java:556)
	at java.lang.Thread.run(Thread.java:748)
[2020-11-15 15:33:22,271] [ReactorThreadd804288b-db0d-4c3c-a066-4a792d6339f7] INFO  com.microsoft.azure.servicebus.primitives.CoreMessageReceiver  - Completeing all updateState operations on the receiver to 'cristisession1'
[2020-11-15 15:33:22,271] [ReactorThreadd804288b-db0d-4c3c-a066-4a792d6339f7] INFO  com.microsoft.azure.servicebus.primitives.CoreMessageReceiver  - SessionId '0' lock lost. Closing receiver.
[2020-11-15 15:33:22,271] [ReactorThreadd804288b-db0d-4c3c-a066-4a792d6339f7] INFO  com.microsoft.azure.servicebus.primitives.CoreMessageReceiver  - Completeing all receive operations on the receiver to 'cristisession1'
[2020-11-15 15:33:22,271] [pool-1-thread-6] INFO  com.microsoft.azure.servicebus.MessageAndSessionPump  - Lock of 'session with id:0' already expired. May be there is clock skew. Still trying to renew lock

**Comment by cristibozga** [comment]
Hre are some detials that were requested by email: 

1.	Please share the name of the Queue for which you are getting above exception.
  **tos_transport_carrier_queu**e 

2.	Please share few time stamps in UTC when you get above exception.
  **2020-11-10 16:46:06 - 10 incidents
  2020-11-10 19:15:2 - 5 incidents
  2020-11-11 01:13:03 – 2 incidents
 2020-11-11 09:12:22 – 2incidents**

**At 09:15:00 the application stopped to receive messages from that queue

Before that at 2020-11-10 08:19:59 we had a big number of errors of type ‘Exception on phase ACCEPTSESSION’** 

3.	Are you using session for any other queues apart from the problematic queue?
  **Yes, we have another session queue without problems: bookinginputqueuefifo. But the number of messages there is not that big**

4.	From where you are running the receiver code? Is it over any VM, App Service, Function App? From where are you reading the message from other queues? Is it the same application for all the queues?
  **We have springboot microservices running in Openshift, in Azure. Different microservcies use different queues; 
 This queue is used by a microservice that uses other normal queues without any problem.** 

5.	Can you try creating a new Queue and use that in place of problematic queue and share the status of the same.
  **As  the problem occurs in production we cannot create a ‘test’ queue tehre. 
But as I commented in the ticket, I arrived to reproduce the problem on another queue, running service-bus-sdk on a local small java application;** 

6.	What is the Lock Duration for the problematic queue? Can you try increasing the same and observe whether it helps you or not?
**Message lock duration is 30 seconds**

**Comment by SaberSeddik** [comment]
We are getting the same issue, what I notice is the issue happening only when we loose the session lock from the server side.
Here an example to reproduce it:
https://github.com/SaberSeddik/service-bus-bug
(provide the connection String for the service created by the terraform in src as argument to the main method.)

**Comment by yvgopal** [comment]
If a message handler takes too long to process the message, session lock will be lost if it is not renewed. This is the expected behavior. I see that your MaxAutoRenewDuration is 30 seconds. Change it to 3 minutes and see if it resolves your issue. That setting tells the session handler how long to renew the session lock. If your onMessage takes more than 30 seconds, session lock will be lost. When you change it to a longer time window, like 3 minutes or 5 minutes, session lock will be renewed for 5 minutes, giving you up to 5 minute to process the message.

**Comment by SaberSeddik** [comment]
SO if we create a SubscriptionClient with max concurrent session let say 5. and we we loose one of the session lock we don't ask for new one ? this seems to me a design flaw. I think the subscription client should check in scheduled based if there are unusable session in his embedded collection close/kill what is not used and create a new one.
Otherwise what do you recommand as an approach to get those session cleaned up and create new ones for the lost ones.

**Comment by yvgopal** [comment]
I think there is a bug in that code. I am reopening the issue. Will post more updates here.

**Comment by yvgopal** [comment]
Fixed in verion 3.6.0.
