### ISSUE TITLE
[BUG]VSCodeCredential doesn't work well in Docker Container

### ISSUE THREAD

**Issue by Luyunmt** [Azure/azure-sdk-for-java#17504]
VSCodeCredential  will hang in Docker Container with newest identity package. It doesn't hang in other environments 
Error as follow:
```
3414 [reactor-http-epoll-1] ERROR com.azure.identity.implementation.VisualStudioCacheAccessor - Failed to read Vs Code credentials from Linux Key Ring.
azidcontainerjava_1 | 3420 [reactor-http-epoll-1] ERROR com.azure.identity.VisualStudioCodeCredential - Azure Identity => ERROR in getToken() call for scopes [https://vault.azure.net/.default]: Failed to read Vs Code credentials from Linux Key Ring.
azidcontainerjava_1 | 5282 [reactor-http-epoll-2] ERROR reactor.netty.channel.ChannelOperationsHandler - [id: 0xc443d507, L:/172.20.0.2:37850 ! R:ruihvault.vault.azure.net/52.247.193.69:443] Error was received while reading the incoming data. The connection will be closed.
azidcontainerjava_1 | java.lang.NoClassDefFoundError: Could not initialize class com.microsoft.aad.msal4jextensions.persistence.linux.ISecurityLibrary
azidcontainerjava_1 | at com.azure.identity.implementation.LinuxKeyRingAccessor.read(LinuxKeyRingAccessor.java:50)
azidcontainerjava_1 | at com.azure.identity.implementation.LinuxKeyRingAccessor.read(LinuxKeyRingAccessor.java:70)
azidcontainerjava_1 | at com.azure.identity.implementation.VisualStudioCacheAccessor.getCredentials(VisualStudioCacheAccessor.java:132)
azidcontainerjava_1 | at com.azure.identity.implementation.IdentityClient.authenticateWithVsCodeCredential(IdentityClient.java:628)
azidcontainerjava_1 | at com.azure.identity.VisualStudioCodeCredential.lambda$getToken$2(VisualStudioCodeCredential.java:79)
azidcontainerjava_1 | at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44)
azidcontainerjava_1 | at reactor.core.publisher.Mono.subscribe(Mono.java:4213)
azidcontainerjava_1 | at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FluxSwitchIfEmpty.java:75)
azidcontainerjava_1 | at reactor.core.publisher.Operators.complete(Operators.java:135)
azidcontainerjava_1 | at reactor.core.publisher.MonoEmpty.subscribe(MonoEmpty.java:45)
azidcontainerjava_1 | at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
azidcontainerjava_1 | at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
azidcontainerjava_1 | at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
azidcontainerjava_1 | at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:150)
azidcontainerjava_1 | at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:121)
azidcontainerjava_1 | at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:121)
azidcontainerjava_1 | at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:203)
azidcontainerjava_1 | at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1782)
azidcontainerjava_1 | at reactor.core.publisher.MonoSingle$SingleSubscriber.onComplete(MonoSingle.java:171)
azidcontainerjava_1 | at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2346)
azidcontainerjava_1 | at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onSubscribeInner(MonoFlatMapMany.java:143)
azidcontainerjava_1 | at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onNext(MonoFlatMapMany.java:182)
azidcontainerjava_1 | at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:99)
azidcontainerjava_1 | at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.onNext(FluxRetryWhen.java:162)
azidcontainerjava_1 | at reactor.core.publisher.MonoCreate$DefaultMonoSink.success(MonoCreate.java:156)
azidcontainerjava_1 | at reactor.netty.http.client.HttpClientConnect$HttpIOHandlerObserver.onStateChange(HttpClientConnect.java:432)
azidcontainerjava_1 | at reactor.netty.ReactorNetty$CompositeConnectionObserver.onStateChange(ReactorNetty.java:518)
azidcontainerjava_1 | at reactor.netty.resources.PooledConnectionProvider$DisposableAcquire.onStateChange(PooledConnectionProvider.java:561)
azidcontainerjava_1 | at reactor.netty.resources.PooledConnectionProvider$PooledConnection.onStateChange(PooledConnectionProvider.java:448)
azidcontainerjava_1 | at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:594)
azidcontainerjava_1 | at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:96)
azidcontainerjava_1 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
azidcontainerjava_1 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
azidcontainerjava_1 | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
azidcontainerjava_1 | at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
azidcontainerjava_1 | at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
azidcontainerjava_1 | at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311)
azidcontainerjava_1 | at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:425)
azidcontainerjava_1 | at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
azidcontainerjava_1 | at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
azidcontainerjava_1 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
azidcontainerjava_1 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
azidcontainerjava_1 | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
azidcontainerjava_1 | at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1526)
azidcontainerjava_1 | at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1287)
azidcontainerjava_1 | at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1324)
azidcontainerjava_1 | at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
azidcontainerjava_1 | at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
azidcontainerjava_1 | at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
azidcontainerjava_1 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
azidcontainerjava_1 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
azidcontainerjava_1 | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
azidcontainerjava_1 | at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
azidcontainerjava_1 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
azidcontainerjava_1 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
azidcontainerjava_1 | at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
azidcontainerjava_1 | at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)
azidcontainerjava_1 | at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475)
azidcontainerjava_1 | at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
azidcontainerjava_1 | at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
azidcontainerjava_1 | at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
azidcontainerjava_1 | at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
azidcontainerjava_1 | at java.lang.Thread.run(Thread.java:748)
azidcontainerjava_1 | 5297 [reactor-http-epoll-2] WARN reactor.netty.channel.FluxReceive - [id: 0xc443d507, L:/172.20.0.2:37850 ! R:ruihvault.vault.azure.net/52.247.193.69:443] An exception has been observed post termination, use DEBUG level to see the full stack: java.lang.NoClassDefFoundError: Could not initialize class com.microsoft.aad.msal4jextensions.persistence.linux.ISecurityLibrary
```
1.create new maven project
2.pom.xml as follow
```
<?xml version="1.0" encoding="UTF-8" ?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.azure</groupId>
  <artifactId>ContainerTest</artifactId>
  <version>1.0-SNAPSHOT</version>

  <name>Test</name>
  <!-- FIXME change it to the project's website -->
  <url>http://www.example.com</url>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.source>1.8</maven.compiler.source>
    <maven.compiler.target>1.8</maven.compiler.target>
  </properties>

  <dependencies>
    <dependency>
      <groupId>com.azure</groupId>
      <artifactId>azure-identity</artifactId>
      <version>1.2.0</version>
    </dependency>
    <dependency>
      <groupId>com.azure</groupId>
      <artifactId>azure-security-keyvault-secrets</artifactId>
      <version>4.2.0</version>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
      <version>1.7.5</version>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-simple</artifactId>
      <version>1.6.4</version>
    </dependency>
    <dependency>
      <groupId>io.github.cdimascio</groupId>
      <artifactId>java-dotenv</artifactId>
      <version>5.2.0</version>
    </dependency>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.13-beta-3</version> <!-- {x-version-update;junit:junit;external_dependency} -->
    </dependency>
    <dependency>
      <groupId>io.projectreactor</groupId>
      <artifactId>reactor-test</artifactId>
      <version>3.3.5.RELEASE</version> <!-- {x-version-update;io.projectreactor:reactor-test;external_dependency} -->
    </dependency>
  </dependencies>

  <build>
    <pluginManagement>
      <!-- lock down plugins versions to avoid using Maven defaults (may be moved to parent pom) -->
      <plugins>
        <!-- clean lifecycle, see https://maven.apache.org/ref/current/maven-core/lifecycles.html#clean_Lifecycle -->
        <plugin>
          <artifactId>maven-clean-plugin</artifactId>
          <version>3.1.0</version>
        </plugin>
        <!-- default lifecycle, jar packaging: see https://maven.apache.org/ref/current/maven-core/default-bindings.html#Plugin_bindings_for_jar_packaging -->
        <plugin>
          <artifactId>maven-resources-plugin</artifactId>
          <version>3.0.2</version>
        </plugin>
        <plugin>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>3.8.0</version>
        </plugin>
        <plugin>
          <artifactId>maven-surefire-plugin</artifactId>
          <version>2.22.1</version>
        </plugin>
        <plugin>
          <artifactId>maven-install-plugin</artifactId>
          <version>2.5.2</version>
        </plugin>
        <plugin>
          <artifactId>maven-deploy-plugin</artifactId>
          <version>2.8.2</version>
        </plugin>
        <!-- site lifecycle, see https://maven.apache.org/ref/current/maven-core/lifecycles.html#site_Lifecycle -->
        <plugin>
          <artifactId>maven-site-plugin</artifactId>
          <version>3.7.1</version>
        </plugin>
        <plugin>
          <artifactId>maven-project-info-reports-plugin</artifactId>
          <version>3.0.0</version>
        </plugin>
        <plugin>
          <artifactId>maven-assembly-plugin</artifactId>
          <executions>
            <execution>
              <phase>package</phase>
              <goals>
                <goal>single</goal>
              </goals>
            </execution>
          </executions>
          <configuration>
            <archive>
              <manifest>
                <addClasspath>true</addClasspath>
                <mainClass>com.azure.Test</mainClass>
              </manifest>
            </archive>
            <descriptorRefs>
              <descriptorRef>jar-with-dependencies</descriptorRef>
            </descriptorRefs>
            <appendAssemblyId>false</appendAssemblyId>
          </configuration>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>
</project>
```

3.code as follow
```
package com.azure;

import org.junit.Test;
import org.junit.Assert;

import reactor.test.StepVerifier;
import io.github.cdimascio.dotenv.Dotenv;

import static org.junit.Assert.assertNotNull;

import com.azure.identity.VisualStudioCodeCredential;
import com.azure.identity.VisualStudioCodeCredentialBuilder;
import com.azure.security.keyvault.secrets.SecretAsyncClient;
import com.azure.security.keyvault.secrets.SecretClientBuilder;


public class ContainerTest {
  private static final Dotenv ENV = Dotenv
  .configure()
  .ignoreIfMissing()
  .systemProperties()
  .directory("../")
  .load();

  private static final String vault = ENV.get("AZURE_KEY_VAULT_ENDPOINT");

 
  @Test
  public void testVSCodeCredential() {
    VisualStudioCodeCredential cred = new VisualStudioCodeCredentialBuilder()
      .build();
    
    SecretAsyncClient client = new SecretClientBuilder()
      .vaultUrl(vault)
      .credential(cred)
      .buildAsyncClient();

    StepVerifier.create(client.getSecret("hello"))
      .expectError()
      .verify();
  }
}
```
4.docker-compose.yml as follow
```
version: '3.4'

services:
  azidcontainerjava:
    image: azidcontainerjava
    volumes: 
      - "${HOME}/.m2:/root/.m2"
      - "${HOME}/.azure:/root/.azure"
    env_file: ../.env
    build:
      context: .
      dockerfile: Dockerfile
```
5.Docker file as follow
```
FROM maven:3.6.3-jdk-8-slim
RUN curl -sL https://aka.ms/InstallAzureCLIDeb | bash

WORKDIR /usr/app/
COPY pom.xml .
COPY src/ /usr/app/src

ENTRYPOINT ["mvn", "test"]
```
6.run `docker-compose up --build`

**Comment by g2vinay** [comment]
This issue should be resolved now, if it still persists let me know.

**Comment by jongio** [comment]
@v-xuto - Please verify that this is resolved.  Thanks

**Comment by Melanie-Ma** [comment]
@jongio  - This issue has been resolved.
