### ISSUE TITLE
Stuck at same event: Error in event processing callback  

### ISSUE THREAD

**Issue by mukeshgulia** [Azure/azure-sdk-for-java#17562]
Updated few reactor-core and io-netty* related libs because of [this issue](https://github.com/Azure/azure-sdk-for-java/issues/17445). See dependency tree in setup below

**Query/Question
question 1: As I understand, after attaching error handler to event processor, any unchecked exception during event processing should be handled by error-handler.  We updated few netty and reactor-core libs to newer version.

question 2: When event is successfully processed, some update at event-hub instance is not happening. Restarting the application again tries to process those events. What could be the cause behind this? 

Here is the eventbuilder

        EventProcessorClientBuilder inEventProcessorClientBuilder = new EventProcessorClientBuilder()
                .transportType(AmqpTransportType.AMQP_WEB_SOCKETS)
                .connectionString(eventhubConnectionString, eventhubname)
                .consumerGroup(EventHubClientBuilder.DEFAULT_CONSUMER_GROUP_NAME)
                .processEvent(IN_EVENT_PROCESSOR)
                .processError(ERROR_HANDLER).checkpointStore(new BlobCheckpointStore(checkpointBlobContainerAsyncClient));

IN_EVENT_PROCESSOR(uses FileTransferEventListener, see in stacktrace) throws an unchecked exception, but it does not go the processError. 

```
com.azure.messaging.eventhubs.implementation.PartitionProcessorException: Error in event processing callback
	at com.azure.messaging.eventhubs.PartitionPumpManager.processEvents(PartitionPumpManager.java:303) ~[azure-messaging-eventhubs-5.3.1.jar:na]
	at com.azure.messaging.eventhubs.PartitionPumpManager.lambda$startPartitionPump$2(PartitionPumpManager.java:216) ~[azure-messaging-eventhubs-5.3.1.jar:na]
	at reactor.core.publisher.LambdaSubscriber.onNext(LambdaSubscriber.java:160) ~[reactor-core-3.3.10.RELEASE.jar:3.3.10.RELEASE]
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runAsync(FluxPublishOn.java:439) ~[reactor-core-3.3.10.RELEASE.jar:3.3.10.RELEASE]
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:526) ~[reactor-core-3.3.10.RELEASE.jar:3.3.10.RELEASE]
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84) [reactor-core-3.3.10.RELEASE.jar:3.3.10.RELEASE]
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37) [reactor-core-3.3.10.RELEASE.jar:3.3.10.RELEASE]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_102]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_102]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_102]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_102]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_102]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_102]
Caused by: com.azure.messaging.eventhubs.implementation.PartitionProcessorException: Error in event processing callback
	at com.azure.messaging.eventhubs.PartitionPumpManager.processEvent(PartitionPumpManager.java:265) ~[azure-messaging-eventhubs-5.3.1.jar:na]
	at com.azure.messaging.eventhubs.PartitionPumpManager.processEvents(PartitionPumpManager.java:299) ~[azure-messaging-eventhubs-5.3.1.jar:na]
	... 12 common frames omitted
Caused by: java.io.UncheckedIOException: java.nio.file.NoSuchFileException: C:\filename.txt
	at com.azure.storage.common.implementation.UploadUtils.uploadFileResourceSupplier(UploadUtils.java:134) ~[azure-storage-common-12.8.0.jar:na]
	at com.azure.storage.common.implementation.UploadUtils.shouldUploadInChunks(UploadUtils.java:108) ~[azure-storage-common-12.8.0.jar:na]
	at com.azure.storage.blob.BlobClient.uploadFromFile(BlobClient.java:258) ~[azure-storage-blob-12.8.0.jar:na]
	at com.azure.storage.blob.BlobClient.uploadFromFile(BlobClient.java:239) ~[azure-storage-blob-12.8.0.jar:na]
	at com.ubs.m4n.filetransferservice.service.FileTransferService.upload(FileTransferService.java:52) ~[classes/:na]
	at com.ubs.m4n.filetransferservice.service.OutFileTransferEventProcessor.lambda$uploadFileToBlobStorage$0(OutFileTransferEventProcessor.java:35) ~[classes/:na]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[na:1.8.0_102]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) ~[na:1.8.0_102]
	at com.ubs.m4n.filetransferservice.service.OutFileTransferEventProcessor.uploadFileToBlobStorage(OutFileTransferEventProcessor.java:34) ~[classes/:na]
	at com.ubs.m4n.filetransferservice.service.OutFileTransferEventProcessor.process(OutFileTransferEventProcessor.java:27) ~[classes/:na]
	at com.ubs.m4n.filetransferservice.service.EventHubAdapter.pipeToOutFileTransferEventProcessor(EventHubAdapter.java:66) ~[classes/:na]
	at com.ubs.m4n.filetransferservice.service.EventHubAdapter.accept(EventHubAdapter.java:43) ~[classes/:na]
	at com.ubs.m4n.filetransferservice.service.FileTransferEventListener.lambda$new$2(FileTransferEventListener.java:112) ~[classes/:na]
	at com.azure.messaging.eventhubs.EventProcessorClientBuilder$1.processEvent(EventProcessorClientBuilder.java:502) ~[azure-messaging-eventhubs-5.3.1.jar:na]
	at com.azure.messaging.eventhubs.PartitionPumpManager.processEvent(PartitionPumpManager.java:255) ~[azure-messaging-eventhubs-5.3.1.jar:na]
	... 13 common frames omitted

```

***Why is this not a Bug or a feature Request?***
Most likely not a bug, because using newer netty and reactor-core dependencies.

**Setup (please complete the following information if applicable):**
 - OS: Windows
 - IDE : IntelliJ
 - Dependency Tree

```
 --- maven-dependency-plugin:3.1.1:tree (default-cli) @ M4N_FileTransferService ---
 com.comp:FileTransferService:jar:1.1.0-45-SNAPSHOT
 +- org.springframework.boot:spring-boot-starter:jar:2.1.6.RELEASE:compile
 |  +- org.springframework.boot:spring-boot:jar:2.1.6.RELEASE:compile
 |  |  \- org.springframework:spring-context:jar:5.1.8.RELEASE:compile
 |  |     +- org.springframework:spring-aop:jar:5.1.8.RELEASE:compile
 |  |     +- org.springframework:spring-beans:jar:5.1.8.RELEASE:compile
 |  |     \- org.springframework:spring-expression:jar:5.1.8.RELEASE:compile
 |  +- org.springframework.boot:spring-boot-autoconfigure:jar:2.1.6.RELEASE:compile
 |  +- org.springframework.boot:spring-boot-starter-logging:jar:2.1.6.RELEASE:compile
 |  |  +- ch.qos.logback:logback-classic:jar:1.1.8:compile
 |  |  |  \- ch.qos.logback:logback-core:jar:1.1.8:compile
 |  |  +- org.apache.logging.log4j:log4j-to-slf4j:jar:2.11.2:compile
 |  |  |  \- org.apache.logging.log4j:log4j-api:jar:2.11.2:compile
 |  |  \- org.slf4j:jul-to-slf4j:jar:1.7.26:compile
 |  +- javax.annotation:javax.annotation-api:jar:1.3.2:compile
 |  +- org.springframework:spring-core:jar:5.1.8.RELEASE:compile
 |  |  \- org.springframework:spring-jcl:jar:5.1.8.RELEASE:compile
 |  \- org.yaml:snakeyaml:jar:1.23:runtime
 +- com.azure:azure-messaging-eventhubs:jar:5.3.1:compile
 |  +- com.azure:azure-core:jar:1.9.0:compile
 |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.9.9:compile
 |  |  |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.9.0:compile
 |  |  |  +- com.fasterxml.jackson.core:jackson-core:jar:2.9.9:compile
 |  |  |  \- com.fasterxml.jackson.core:jackson-databind:jar:2.9.9:compile
 |  |  +- com.fasterxml.jackson.dataformat:jackson-dataformat-xml:jar:2.9.9:compile
 |  |  |  +- com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:2.9.9:compile
 |  |  |  +- org.codehaus.woodstox:stax2-api:jar:3.1.4:compile
 |  |  |  \- com.fasterxml.woodstox:woodstox-core:jar:5.0.3:compile
 |  |  +- org.slf4j:slf4j-api:jar:1.7.26:compile
 |  |  \- io.netty:netty-tcnative-boringssl-static:jar:2.0.25.Final:compile
 |  \- com.azure:azure-core-amqp:jar:1.6.0:compile
 |     +- com.microsoft.azure:qpid-proton-j-extensions:jar:1.2.3:compile
 |     \- org.apache.qpid:proton-j:jar:0.33.4:compile
 +- com.azure:azure-messaging-eventhubs-checkpointstore-blob:jar:1.3.1:compile
 +- com.azure:azure-storage-blob:jar:12.8.0:compile
 |  +- com.azure:azure-storage-common:jar:12.8.0:compile
 |  |  \- com.azure:azure-core-http-netty:jar:1.5.4:compile
 |  |     \- io.netty:netty-transport-native-kqueue:jar:osx-x86_64:4.1.36.Final:compile
 |  \- com.azure:azure-storage-internal-avro:jar:12.0.0:compile
 +- io.projectreactor.netty:reactor-netty:jar:0.9.11.RELEASE:compile
 |  \- io.netty:netty-transport-native-epoll:jar:linux-x86_64:4.1.36.Final:compile
 +- io.netty:netty-buffer:jar:4.1.51.Final:compile
 +- io.netty:netty-codec:jar:4.1.51.Final:compile
 +- io.netty:netty-codec-http:jar:4.1.51.Final:compile
 +- io.netty:netty-codec-http2:jar:4.1.51.Final:compile
 +- io.netty:netty-codec-socks:jar:4.1.51.Final:compile
 +- io.netty:netty-common:jar:4.1.51.Final:compile
 +- io.netty:netty-handler:jar:4.1.51.Final:compile
 +- io.netty:netty-handler-proxy:jar:4.1.51.Final:compile
 +- io.netty:netty-resolver:jar:4.1.51.Final:compile
 +- io.netty:netty-transport:jar:4.1.51.Final:compile
 +- io.netty:netty-transport-native-epoll:jar:4.1.51.Final:compile
 +- io.netty:netty-transport-native-kqueue:jar:4.1.51.Final:compile
 +- io.netty:netty-transport-native-unix-common:jar:4.1.51.Final:compile
 +- io.projectreactor:reactor-core:jar:3.3.10.RELEASE:compile
 |  \- org.reactivestreams:reactive-streams:jar:1.0.2:compile
 +- com.google.code.gson:gson:jar:2.8.6:compile
 +- org.springframework.boot:spring-boot-starter-test:jar:2.1.6.RELEASE:test
 |  +- org.springframework.boot:spring-boot-test:jar:2.1.6.RELEASE:test
 |  +- org.springframework.boot:spring-boot-test-autoconfigure:jar:2.1.6.RELEASE:test
 |  +- com.jayway.jsonpath:json-path:jar:2.4.0:test
 |  |  \- net.minidev:json-smart:jar:2.3:test
 |  |     \- net.minidev:accessors-smart:jar:1.2:test
 |  |        \- org.ow2.asm:asm:jar:5.0.4:test
 |  +- org.assertj:assertj-core:jar:3.8.0:test
 |  +- org.mockito:mockito-core:jar:3.2.4:test
 |  |  +- net.bytebuddy:byte-buddy:jar:1.9.13:test
 |  |  +- net.bytebuddy:byte-buddy-agent:jar:1.9.13:test
 |  |  \- org.objenesis:objenesis:jar:2.6:test
 |  +- org.hamcrest:hamcrest-core:jar:1.3:test
 |  +- org.hamcrest:hamcrest-library:jar:1.3:test
 |  +- org.skyscreamer:jsonassert:jar:1.5.0:test
 |  |  \- com.vaadin.external.google:android-json:jar:0.0.20131108.vaadin1:test
 |  +- org.springframework:spring-test:jar:5.1.8.RELEASE:test
 |  \- org.xmlunit:xmlunit-core:jar:2.6.2:test
 +- org.projectlombok:lombok:jar:1.18.8:compile
 +- junit:junit:jar:4.12:test
 +- org.junit.jupiter:junit-jupiter-api:jar:5.6.2:test
 |  +- org.apiguardian:apiguardian-api:jar:1.1.0:test
 |  +- org.opentest4j:opentest4j:jar:1.2.0:test
 |  \- org.junit.platform:junit-platform-commons:jar:1.3.2:test
 +- org.junit.jupiter:junit-jupiter-params:jar:5.6.2:test
 \- org.springframework.boot:spring-boot-configuration-processor:jar:2.1.6.RELEASE:compile (optional) 

``` 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by joshfree** [comment]
@conniey could you please assist?

**Comment by conniey** [comment]
Thanks for reporting this! 

If you look deep into the call stack, there is an error in your processEvent callback "IN_EVENT_PROCESSOR". We wrap your consumer IN_EVENT_PROCESSOR in a try/catch and then log the error.

```log
Caused by: java.io.UncheckedIOException: java.nio.file.NoSuchFileException: C:\filename.txt
	at com.azure.storage.common.implementation.UploadUtils.uploadFileResourceSupplier(UploadUtils.java:134) ~[azure-storage-common-12.8.0.jar:na]
...
	at com.ubs.m4n.filetransferservice.service.OutFileTransferEventProcessor.uploadFileToBlobStorage(OutFileTransferEventProcessor.java:34) ~[classes/:na]

```

**Comment by mukeshgulia** [comment]
> Thanks for reporting this!
> 
> If you look deep into the call stack, there is an error in your processEvent callback "IN_EVENT_PROCESSOR". We wrap your consumer IN_EVENT_PROCESSOR in a try/catch and then log the error.
> 
> Looks like you're trying to upload a file that doesn't exist... and we're logging that error.
> 
> ```
> Caused by: java.io.UncheckedIOException: java.nio.file.NoSuchFileException: C:\filename.txt
>     at com.azure.storage.common.implementation.UploadUtils.uploadFileResourceSupplier(UploadUtils.java:134) ~[azure-storage-common-12.8.0.jar:na]
> ...
>     at com.ubs.m4n.filetransferservice.service.OutFileTransferEventProcessor.uploadFileToBlobStorage(OutFileTransferEventProcessor.java:34) ~[classes/:na]
> ```

Thanks @conniey  for the reply. I understand that there is an error in my processor. But after logging the error, should the flow not go to ```.processEvent(IN_EVENT_PROCESSOR)```

And regarding question 2:  even if the event is processed successfully, checkpoint container does not seem to update.

**Comment by conniey** [comment]
If you follow the stack trace, we _are_ calling your IN_EVENT_PROCESSOR... which is what is throwing the exception, hence the error message ("Error in event processing callback"). You need to call partitionContext.updateCheckpoint() to update checkpoints.

**Comment by mukeshgulia** [comment]
Thanks @conniey for the feedback. Regarding checkpoint, spot on. Call to checkpoint was wrapped in condition, that wasn't evaluating to true. Fixing that solved it. 
Regarding the exception, we will do the error handling.

**Comment by srnagar** [comment]
Thanks for confirming that the issue is resolved @mukeshgulia.
