### ISSUE TITLE
[BUG] Exception "'Timestamp' must be an OffsetDateTime" when listing table entities

### ISSUE THREAD

**Issue by ThibDeez** [Azure/azure-sdk-for-java#17572]
Hello @bsiegel,

I have the same error as gdurandrexel when I list the entities.

**Related bug report :** 
https://github.com/Azure/azure-sdk-for-java/issues/16292

**Azure data tables version :**
12.0.0-beta.3

**Code :**
```
TableServiceClient tableServiceClient = new TableServiceClientBuilder()
     .httpClient(httpClient)
     .connectionString(storageConnectionString)
     .buildClient();

tableServiceClient.createTableIfNotExists(tableName);

TableClient tableClient = tableServiceClient.getTableClient(tableName);

tableClient.listEntities();
```

**Stack trace :**
```
java.lang.IllegalArgumentException: 'Timestamp' must be an OffsetDateTime.	
at com.azure.data.tables.models.TableEntity.validateProperty(TableEntity.java:137)
at com.azure.data.tables.models.TableEntity.addProperties(TableEntity.java:121)
at com.azure.data.tables.implementation.ModelHelper.createEntity(ModelHelper.java:78)
at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1380)
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
at com.azure.data.tables.TableAsyncClient.lambda$listEntities$33(TableAsyncClient.java:630)
at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:118)
at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1782)
at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:241)
at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:67)
at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1782)
at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:241)
at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:67)
at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114)
at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1782)
at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.signalCached(MonoCacheTime.java:320)
at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.onNext(MonoCacheTime.java:337)
at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:73)
at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1782)
at reactor.core.publisher.MonoCallable.subscribe(MonoCallable.java:61)
at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
at reactor.core.publisher.MonoCacheTime.subscribeOrReturn(MonoCacheTime.java:132)
at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:150)
at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1782)
at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.signalCached(MonoCacheTime.java:320)
at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.onNext(MonoCacheTime.java:337)
at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1782)
at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:144)
at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:123)
at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:112)
at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:213)
at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:123)
at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:178)
at reactor.core.publisher.FluxContextStart$ContextStartSubscriber.onNext(FluxContextStart.java:96)
at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1782)
at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:121)
at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:252)
at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:136)
at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:374)
at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:373)
at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:429)
at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:655)
at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:96)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1533)
at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1294)
at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1331)
at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
at io.netty.handler.proxy.ProxyHandler.channelRead(ProxyHandler.java:253)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.lang.Thread.run(Thread.java:748)
```

**Comment by bsiegel** [comment]
Hi there @ThibDeez, I'm not able to reproduce this locally using 12.0.0-beta.3. However I see in your example you're passing a custom `httpClient`. Can you please include the code which shows how you create this `httpClient`? For reference, my sample code that's working as expected is basically the same as yours, except that I'm not setting a custom `httpClient`:

```java
TableServiceClient tableServiceClient = new TableServiceClientBuilder()
    .connectionString(connectionString)
    .buildClient();

String tableName = "MyTable";
tableServiceClient.createTableIfNotExists(tableName);

TableClient tableClient = tableServiceClient.getTableClient(tableName);

tableClient.createEntity(new TableEntity("Partition1", "Row1"));
tableClient.listEntities();
```

As you can see above, I also added code to create an entity in the table, just to make sure that there is something to deserialize. Regardless of whether the table was empty or contained an entity this code worked as expected.

**Comment by ThibDeez** [comment]
Hi,

I use HttpClient for proxy configuration :

```
    ProxyOptions proxyOptions = getProxyConfiguration();
        HttpClient httpClient = new NettyAsyncHttpClientBuilder()
            .proxy(proxyOptions)
            .build();

    public ProxyOptions getProxyConfiguration() {
        String proxyHost = System.getProperty("https.proxyHost", System.getProperty("http.proxyHost"));
        String proxyPort = System.getProperty("https.proxyPort", System.getProperty("http.proxyPort"));
        String proxyUser = System.getProperty("https.proxyUser", System.getProperty("http.proxyUser"));
        String proxyPassword = System.getProperty("https.proxyPassword", System.getProperty("http.proxyPassword"));
        final ProxyOptions proxyOptions;
        if (proxyHost != null && proxyPort != null) {
            InetSocketAddress proxyAddress = new InetSocketAddress(proxyHost, Integer.valueOf(proxyPort));
            proxyOptions = new ProxyOptions(ProxyOptions.Type.HTTP, proxyAddress);
            if (proxyUser != null) {
                proxyOptions.setCredentials(proxyUser, proxyPassword);
            }
        } else {
            proxyOptions = null;
        }
        return proxyOptions;
    }
```

I did the same for the BlobServiceClient :
```
        StorageSharedKeyCredential credential =
                StorageSharedKeyCredential.fromConnectionString(storageConnectionString);

        String endpoint =
                String.format(Locale.ROOT, "https://%s.blob.core.windows.net", credential.getAccountName());

        ProxyOptions proxyOptions = getProxyConfiguration();
        HttpClient httpClient = new NettyAsyncHttpClientBuilder()
                .proxy(proxyOptions)
                .build();

        BlobServiceClient storageClient = new BlobServiceClientBuilder()
                .httpClient(httpClient)
                .endpoint(endpoint)
                .credential(credential)
                .buildClient();

```

**Comment by bsiegel** [comment]
That looks fine to me. I've updated my test case as below and I'm still not encountering the same error you are. I did set up a local proxy server to see if that could be affecting the results but everything still works as expected here. Could you perhaps bundle up your project as a .zip and attach it? Obviously please strip out any credentials before doing so.

```java
ProxyOptions proxyOptions = getProxyConfiguration();
HttpClient httpClient = new NettyAsyncHttpClientBuilder()
    .proxy(proxyOptions)
    .build();

TableServiceClient tableServiceClient = new TableServiceClientBuilder()
    .httpClient(httpClient)
    .connectionString(connectionString)
    .buildClient();

String tableName = "MyTable";
tableServiceClient.createTableIfNotExists(tableName);

TableClient tableClient = tableServiceClient.getTableClient(tableName);

tableClient.createEntity(new TableEntity("Partition1", "Row1"));
tableClient.listEntities();
```

**Comment by gdurandrexel** [comment]
Hi all,
FYI, I no more have the bug with beta3.

@ThibDeez Are you sure the data in the table you want to read was added using beta3? Versions before beta3 may not have properly set the data type for the timestamp when adding entries.

**Comment by ThibDeez** [comment]
Hi @bsiegel and @gdurandrexel,

My problem is solved but I do not know exactly why. We use our own framework and it has been updated recently. I think it was an addiction issue. I will get back to you if I have more information.
Thanks for your help.
Bug closed.
