### ISSUE TITLE
[FEATURE REQ] Azure Blob Track 2 - Create BlobClient or BlobContainerClient without using container name?

### ISSUE THREAD

**Issue by abhikt48** [Azure/azure-sdk-for-java#17727]
We are migrating old Azure Storage SDK `azure-storage:5.5.0` to new Blob Storage SDK `azure-storage-blob:12.9.0`.

Old SDK provides facilty to create client without defining container or blob name. It provides great facuility for reusabilty. We create one `CloudBlobClient ` and using many places for different containers and blobs. Please refer below sample code

```
CloudBlobClient blobClient = new CloudBlobClient(new URI(BLOB_SAS_OBJECT));
blobClient.getContainerReference(CONTAINER_NAME).getBlockBlobReference(BLOB_NAME);
```

With NEW SDK there is no option to create common client without CONTAINER_NAME or BLOB_NAME. 

```
BlobContainerClient blobContainerClient = new BlobContainerClientBuilder()
    .endpoint("<your-storage-account-url>")
    .containerName("mycontainer")
    .buildClient();
```

I worried about performance and flexibility. I am sure you guyz thought about this.  Could you please suggest your opinion on below queries

1. As we have to perfrom blob operations on Millions  records - Does this impact performance on new BlobContainerClient creation for every blob request ?
2. Do we have any option to create client without Container Or Blob Name?

Please let me know for any information.

Version of the Library used - `azure-storage-blob-12.9.0`

**Comment by rickle-msft** [comment]
Hi, @abhikt48. Thank you for your questions. 

1. The clients are rather lightweight as most of network resources end up being shared, so there's not a lot of overhead to creation. If you are accessing blobs, though, you shouldn't need a new container client per request unless every blob is in a different container.

2. You should be able to create a BlobServiceClient without either of those pieces of information and then use that client to get container and blob clients. BlobServiceClient should be the hierarchical equivalent of a CloudBlobClient; that is, it is the client that corresponds to an account rather than to a container or a blob.

**Comment by abhikt48** [comment]
HI @rachel-msft,

I was also expecting same thing that `BlobServiceClient` should works as `CloudBlobClient`, but it is not working like same. `BlobServiceClient` creates client for only **Service** level resource type. It throws error for  **Object** and **Container** level resource type. Please find below sample class and error logs, and let me know if you need any other information.

Class 
```
package com.test;

import com.azure.storage.blob.BlobServiceClient;
import com.azure.storage.blob.BlobServiceClientBuilder;

public class BlobUtilsSAS {

    public static String BLOB_SAS_OBJECT =
                            "https://XXXX.blob.core.windows.net/?sv=2019-XX-12&ss=b&srt=o&sp=rwdlacx&se=20XX-10-31T21:53:13Z&st=2020-11-19T13:53:13Z&spr=https&sig=XXXXXXXXXXXOVNfq32f54%2FXXXW%2B6w0SfFXXXXX%3D";

    public static void main(String[] args) {
        BlobServiceClient blobServiceClient = new BlobServiceClientBuilder().endpoint(BLOB_SAS_OBJECT).buildClient();
        System.out.println("** Blob Properties **" + blobServiceClient.getProperties());
   }
}
```

Error Log
```
Exception in thread "main" com.azure.storage.blob.models.BlobStorageException: Status code 403, "﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthorizationResourceTypeMismatch</Code><Message>This request is not authorized to perform this operation using this resource type.
RequestId:335ae290-a01e-001e-73c6-c18a23000000
Time:2020-11-23T18:25:33.5284792Z</Message></Error>"
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.azure.core.http.rest.RestProxy.instantiateUnexpectedException(RestProxy.java:334)
	at com.azure.core.http.rest.RestProxy.lambda$ensureExpectedStatus$5(RestProxy.java:375)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:118)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1782)
	at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.signalCached(MonoCacheTime.java:320)
	at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.onNext(MonoCacheTime.java:337)
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2344)
	at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.onSubscribe(MonoCacheTime.java:276)
	at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:191)
	at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at reactor.core.publisher.MonoCacheTime.subscribeOrReturn(MonoCacheTime.java:132)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:150)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:123)
	at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:112)
	at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:213)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:123)
	at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:178)
	at reactor.core.publisher.FluxContextStart$ContextStartSubscriber.onNext(FluxContextStart.java:96)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1782)
	at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:121)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:252)
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:136)
	at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:378)
	at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:373)
	at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:429)
	at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:625)
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:96)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1526)
	at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1287)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1324)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
		at reactor.core.publisher.Mono.block(Mono.java:1680)
		at com.azure.storage.common.implementation.StorageImplUtils.blockWithOptionalTimeout(StorageImplUtils.java:99)
		at com.azure.storage.blob.BlobServiceClient.getPropertiesWithResponse(BlobServiceClient.java:263)
		at com.azure.storage.blob.BlobServiceClient.getProperties(BlobServiceClient.java:244)
		at com.test.BlobUtilsSAS.main(BlobUtilsSAS.java:20)
```

**Comment by rickle-msft** [comment]
I addressed the problems with this code in the other issue. But this would be the same for `CloudBlobClient.getProperties()`. This method also only works with service level permissions.

**Comment by abhikt48** [comment]
@rickle-msft  - `CloudBlobClient ` provides facility  to validate connection irrespective of resource type. This is one of big difference between Old SDK and New SDK. This is a huge change for us. At this moment we are requesting container name for connection validation.

Please find below code snippet to replicate this issue.  Could you please provide same facility in New SDK which will be easy for migration. Please let me know for any other information.

```
public static String BLOB_SAS_OBJECT =
                            "https://XXXX.blob.core.windows.net/?sv=2019-XX-12&ss=b&srt=o&sp=rwdlacx&se=20XX-10-31T21:53:13Z&st=2020-11-19T13:53:13Z&spr=https&sig=XXXXXXXXXXXOVNfq32f54%2FXXXW%2B6w0SfFXXXXX%3D";

CloudBlobClient cloudBlobClient = new CloudBlobClient(new URI(BLOB_SAS_OBJECT));
cloudBlobClient.downloadServiceProperties();
```
```
<dependency>
	<groupId>com.microsoft.azure</groupId>
	<artifactId>azure-storage</artifactId>
	<version>5.5.0</version>
</dependency>	
```

**Comment by rickle-msft** [comment]
@abhikt48 I can confidently say older versions do *not* support this functionality. Request authorization is a feature of the service, not a feature of the SDKs, so this is not actually something that can vary between versions. The error you are seeing is returned by the service and not the sdk as you'll notice that there is a 403 status code. You can see [here](https://docs.microsoft.com/en-us/rest/api/storageservices/create-account-sas#specifying-account-sas-parameters) under the Signed Resource Types row that it explicitly states you need service level permissions to download service properties; object level permissions are insufficient. Moreover, I have copied your code sample and applied it to our own account and have verified that the same error is returned due to insufficient permissions. 

```
String BLOB_SAS_OBJECT =
            "https://xxxxx.blob.core.windows.net/?sv=2019-12-12&ss=b&srt=o&sp=rwdlacx&se=2020-11-25T02:20:16Z&st=2020-11-24T18:20:16Z&spr=https&sig=xxxxxx";

        CloudBlobClient cloudBlobClient = new CloudBlobClient(new URI(BLOB_SAS_OBJECT));
        System.out.println("Service props: " + cloudBlobClient.downloadServiceProperties().getDefaultServiceVersion());
```

```
Exception in thread "main" com.microsoft.azure.storage.StorageException: This request is not authorized to perform this operation using this resource type.
	at com.microsoft.azure.storage.StorageException.translateException(StorageException.java:89)
	at com.microsoft.azure.storage.core.StorageRequest.materializeException(StorageRequest.java:315)
	at com.microsoft.azure.storage.core.ExecutionEngine.executeWithRetry(ExecutionEngine.java:175)
	at com.microsoft.azure.storage.blob.CloudBlobClient.downloadServiceProperties(CloudBlobClient.java:515)
	at com.microsoft.azure.storage.blob.CloudBlobClient.downloadServiceProperties(CloudBlobClient.java:484)
	at Main.main(Main.java:29)
```

Note that the `srt` query parameter is the same. 

If you are not seeing errors when trying to download service properties using the sas you have shared, then the exception is being swallowed in your code somewhere.

Again, this is not behavior that is specific to the version of the client. CloudBlobClient is replaced by BlobServiceClient, and their behavior around being able to perform this request is the same. 

If you have further questions or concerns, please let me know.

**Comment by abhikt48** [comment]
@rickle-msft  Yes, you are right. Sorry for confusion. Will let you know if i have any other migration issues.

**Comment by abhikt48** [comment]
@rickle-msft  Yes, You are right. Sorry for confusion. Will le you know for other migration issues.

**Comment by rickle-msft** [comment]
@abhikt48 No worries! Please do let us know!
