### ISSUE TITLE
[BUG] MacAddressHelper.computeHashedMacAddress() throws NPE on Linux

### ISSUE THREAD

**Issue by ntpan** [Azure/azure-sdk-for-java#17811]
**Describe the bug**
The method of determining the local MAC adress in `com.microsoft.azure.spring.cloud.telemetry.MacAddressHelper.computeHashedMacAddress` does not work on Linux systems and throws a NullPointerException.

```
private static String computeHashedMacAddress() {
    try {
      InetAddress host = InetAddress.getLocalHost();
      byte[] macBytes = NetworkInterface.getByInetAddress(host).getHardwareAddress(); // NetworkInterface.getByInetAddress(host) returns null
```

The error occurs when trying to create an event hub StreamListener. 

***Exception or Stack Trace***
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.microsoft.azure.spring.cloud.autoconfigure.eventhub.AzureEventHubAutoConfiguration': Invocation of init method failed; nested exception is java.lang.ExceptionInInitializerError
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:160) ~[spring-beans-5.2.10.RELEASE.jar:5.2.10.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:415) ~[spring-beans-5.2.10.RELEASE.jar:5.2.10.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1786) ~[spring-beans-5.2.10.RELEASE.jar:5.2.10.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594) ~[spring-beans-5.2.10.RELEASE.jar:5.2.10.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516) ~[spring-beans-5.2.10.RELEASE.jar:5.2.10.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324) ~[spring-beans-5.2.10.RELEASE.jar:5.2.10.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.2.10.RELEASE.jar:5.2.10.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322) ~[spring-beans-5.2.10.RELEASE.jar:5.2.10.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.10.RELEASE.jar:5.2.10.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:897) ~[spring-beans-5.2.10.RELEASE.jar:5.2.10.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:879) ~[spring-context-5.2.10.RELEASE.jar:5.2.10.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551) ~[spring-context-5.2.10.RELEASE.jar:5.2.10.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143) ~[spring-boot-2.3.5.RELEASE.jar:2.3.5.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758) ~[spring-boot-2.3.5.RELEASE.jar:2.3.5.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750) ~[spring-boot-2.3.5.RELEASE.jar:2.3.5.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:405) ~[spring-boot-2.3.5.RELEASE.jar:2.3.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-2.3.5.RELEASE.jar:2.3.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237) ~[spring-boot-2.3.5.RELEASE.jar:2.3.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) ~[spring-boot-2.3.5.RELEASE.jar:2.3.5.RELEASE]
	at de.test.customerconsumer.CustomerConsumerApplication.main(CustomerConsumerApplication.java:10) ~[classes/:na]
Caused by: java.lang.ExceptionInInitializerError: null
	at com.microsoft.azure.spring.cloud.telemetry.TelemetryCollector.buildProperties(TelemetryCollector.java:78) ~[spring-cloud-azure-telemetry-1.2.8.jar:na]
	at com.microsoft.azure.spring.cloud.telemetry.TelemetryCollector.<init>(TelemetryCollector.java:40) ~[spring-cloud-azure-telemetry-1.2.8.jar:na]
	at com.microsoft.azure.spring.cloud.telemetry.TelemetryCollector.<clinit>(TelemetryCollector.java:33) ~[spring-cloud-azure-telemetry-1.2.8.jar:na]
	at com.microsoft.azure.spring.cloud.autoconfigure.eventhub.AzureEventHubAutoConfiguration.collectTelemetry(AzureEventHubAutoConfiguration.java:50) ~[spring-cloud-azure-autoconfigure-1.2.8.jar:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:564) ~[na:na]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389) ~[spring-beans-5.2.10.RELEASE.jar:5.2.10.RELEASE]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333) ~[spring-beans-5.2.10.RELEASE.jar:5.2.10.RELEASE]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157) ~[spring-beans-5.2.10.RELEASE.jar:5.2.10.RELEASE]
	... 19 common frames omitted
Caused by: java.lang.NullPointerException: Cannot invoke "java.net.NetworkInterface.getHardwareAddress()" because the return value of "java.net.NetworkInterface.getByInetAddress(java.net.InetAddress)" is null
	at com.microsoft.azure.spring.cloud.telemetry.MacAddressHelper.computeHashedMacAddress(MacAddressHelper.java:20) ~[spring-cloud-azure-telemetry-1.2.8.jar:na]
	at com.microsoft.azure.spring.cloud.telemetry.MacAddressHelper.<clinit>(MacAddressHelper.java:15) ~[spring-cloud-azure-telemetry-1.2.8.jar:na]
	... 30 common frames omitted


Process finished with exit code 1
```

**To Reproduce**
Create a Spring Boot Application with spring-cloud-azure-eventhubs-stream-binder:1.2.8 and create a StreamListener.
Then try to run the application on a Linux system.

***Code Snippet***
```
@EnableBinding(Sink.class)
public class EventHubSink {
  private static final Logger LOGGER = LoggerFactory.getLogger(EventHubSink.class);

  @StreamListener(Sink.INPUT)
  public void handleMessage(String message, @Header(AzureHeaders.CHECKPOINTER) Checkpointer checkpointer) {
    LOGGER.info("#### New message received: '{}'", message);
  }
}
```

**Setup (please complete the following information):**
 - OS: Ubuntu 20.10
 - spring-cloud-azure-eventhubs-stream-binder:1.2.8

**Comment by han-gao** [comment]
Hi @ntpan, I'm trying to reproduce your problem and will give you feedback as soon.

**Comment by han-gao** [comment]
Hi, @ntpan  The `byte[] macBytes = NetworkInterface.getByInetAddress(host).getHardwareAddress()` meaning is trying to get the MAC address by IP address. IP address exists only when you are connected successfully to the Internet. Otherwise, it will be null. So I think maybe you can try get the IP address of the local machine and make sure the Internet is working.

Can it work?

**Comment by ntpan** [comment]
Hi @han-gao, thanks for getting back to me.
I do have an active internet connection but I also have multiple network adapters.
Might that be an issue?

```
> ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp0s31f6: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc fq_codel state DOWN group default qlen 1000
    link/ether 54:e1:ad:fa:c5:68 brd ff:ff:ff:ff:ff:ff
3: wlp3s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether e4:70:b8:fb:9e:06 brd ff:ff:ff:ff:ff:ff
    inet 192.168.178.24/24 brd 192.168.178.255 scope global dynamic noprefixroute wlp3s0
       valid_lft 855975sec preferred_lft 855975sec
    inet6 2a02:810a:14c0:1140:f877:1d50:f427:af66/64 scope global temporary dynamic 
       valid_lft 4080sec preferred_lft 1380sec
    inet6 2a02:810a:14c0:1140:b35b:462b:afb8:a002/64 scope global dynamic mngtmpaddr noprefixroute 
       valid_lft 4080sec preferred_lft 1380sec
    inet6 fe80::c357:8ac7:9a2d:19c9/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
4: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:9c:97:9e:6f brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
44: vxlan.calico: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1410 qdisc noqueue state UNKNOWN group default 
    link/ether 66:97:66:8b:eb:14 brd ff:ff:ff:ff:ff:ff
    inet 10.1.108.0/32 brd 10.1.108.0 scope global vxlan.calico
       valid_lft forever preferred_lft forever
    inet6 fe80::6497:66ff:fe8b:eb14/64 scope link 
       valid_lft forever preferred_lft forever
45: cali2d438637c71@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1440 qdisc noqueue state UP group default 
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netns cni-a9568fb1-a109-eb9a-15d2-453bf547e01d
    inet6 fe80::ecee:eeff:feee:eeee/64 scope link 
       valid_lft forever preferred_lft forever
```

**Comment by han-gao** [comment]
Hi, @ntpan I found the principle of `InetAddress.getLocalHost()` is to obtain the hostname of the machine and then resolve the hostname to obtain the IP address.  

About `InetAddress.getLocalHost()` returned a wrong IP address. If the hostname points to a wrong IP address in the `/etc/hosts` file of the local machine(The command to open the hosts file is `sudo nano /etc/hosts`), then `InetAddress.getLocalHost()` will return the wrong IP address. I suggest that using the command to view the host name and binding IP mapping.(The command is `hostname -i ` ) and test `NetworkInterface.getByInetAddress(InetAddress.getByName("ipAddress")).getHardwareAddress()` is available.

May I ask are you using a virtual machine.

If it still doesn't work, we are considering other methods to achieve this.

**Comment by ntpan** [comment]
Hi @han-gao, indeed I am using a virtual machine, I should've mentioned that...

- `/etc/hosts` lists the following IPv4 addresses:
  ```
  127.0.0.1       localhost
  127.0.1.1       ubuntu
  ```

- `hostname -i` returns `127.0.1.1`

- `byte[] mac = NetworkInterface.getByInetAddress(InetAddress.getByName("127.0.1.1")).getHardwareAddress();` throws an NPE again

**Comment by han-gao** [comment]
@ntpan because the network configuration of the virtual machine is relatively diverse.

So you can view the hostname(The command is `hostname`) , and find an IP address available for this machine(`NetworkInterface.getByInetAddress(InetAddress.getByName("ipAddress")).getHardwareAddress()`is work) ,
In the `/etc/hosts` file of the virtual machine change their mapping as follows:
![1607499821(1)](https://user-images.githubusercontent.com/34266185/101599967-a1f81580-3a35-11eb-98fd-d2217d531bd8.jpg)
And then maybe `NetworkInterface.getByInetAddress(host).getHardwareAddress()` can work.

**Comment by ntpan** [comment]
@han-gao I edited the hosts file as you said
![hosts](https://user-images.githubusercontent.com/17176836/101601763-56297a00-39fd-11eb-9337-c7a9247198af.png)
and `NetworkInterface.getByInetAddress(host).getHardwareAddress()` is working now!

Is this a satisfying solution though? Editing the hosts file everytime the ip address changes seems a bit odd.

**Comment by han-gao** [comment]
@ntpan  you're right, I am trying a better way to achieve it, I plan to traverse all the network interfaces to find the available ipAddress to avoid the situation just now~.~.
