### ISSUE TITLE
NPE and ConcurrentModificationException during working with one client (ComputeManagementClient/ResourceManagementClient/StorageManagementClient/)

### ISSUE THREAD

**Issue by LinaKorn** [Azure/azure-sdk-for-java#1782]
We have exceptions during work with ComputeManagementClient/ResourceManagementClient/StorageManagementClient/..  
We don't create a new client per each request. We recreate client only if azure token has expired.
As result we can have a different exceptions which are related with modifications of the same data in Azure SDK.
**NPE**
`Caused by: java.lang.NullPointerException: null	
at java.util.LinkedList$ListItr.next(LinkedList.java:893)	
at com.microsoft.windowsazure.core.pipeline.apache.HttpRequestInterceptorAdapter.process(HttpRequestInterceptorAdapter.java:42)	
at org.apache.http.protocol.ImmutableHttpProcessor.process(ImmutableHttpProcessor.java:133)	
at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:182)	
at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)	
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)	
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)	
at com.microsoft.azure.management.compute.VirtualMachineOperationsImpl.beginCreatingOrUpdating(VirtualMachineOperationsImpl.java:1247)	
at com.microsoft.azure.management.compute.VirtualMachineOperationsImpl$2.call(VirtualMachineOperationsImpl.java:311)	
at com.microsoft.azure.management.compute.VirtualMachineOperationsImpl$2.call(VirtualMachineOperationsImpl.java:308)	
at java.util.concurrent.FutureTask.run(FutureTask.java:266)	
... 3 common frames omitted
`

**ConcurrentModificationException**
`java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.ConcurrentModificationException: null
	at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:966)
	at java.util.LinkedList$ListItr.next(LinkedList.java:888)
	at org.apache.http.impl.client.HttpClientBuilder.build(HttpClientBuilder.java:1119)
	at com.microsoft.windowsazure.core.ServiceClient.getHttpClient(ServiceClient.java:56)
	at com.microsoft.azure.management.network.NetworkInterfaceOperationsImpl.beginCreateOrUpdating(NetworkInterfaceOperationsImpl.java:397)
	at com.microsoft.azure.management.network.NetworkInterfaceOperationsImpl$1.call(NetworkInterfaceOperationsImpl.java:110)
	at com.microsoft.azure.management.network.NetworkInterfaceOperationsImpl$1.call(NetworkInterfaceOperationsImpl.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 common frames omitted`

We solved it in our application. Now per each request we create a new client, but this is not very effective.

Does current problem solved in SDK version 1.0.0 or will be solved in 0.9.7?

**Comment by anuchandy** [comment]
@LinaKorn looks like you are using very old version of SDK 0.9.7. Do you think your application can modified to use the latest version of SDK? There are drastic improvements we made in the sdk after 0.9.*. We have improved support for all the services you are using (compute/storage/resource), which includes fluent typing experience, better throughput since the sdk takes care of many of the concurrency stuff. For example following code is all you need to create a virtual machine.
```java
VirtualMachine linuxVM = azure.virtualMachines().define("myLinuxVM")
	.withRegion(Region.US_EAST)
	.withNewResourceGroup(rgName)
	.withNewPrimaryNetwork("10.0.0.0/28")
	.withPrimaryPrivateIPAddressDynamic()
	.withNewPrimaryPublicIPAddress("mylinuxvmdns")
	.withPopularLinuxImage(KnownLinuxVirtualMachineImage.UBUNTU_SERVER_16_04_LTS)
	.withRootUsername("tirekicker")
	.withSsh(sshKey)
	.withSize(VirtualMachineSizeTypes.STANDARD_D3_V2)
	.create();
```

You don't have to worry about creating storage account, PIP, NIC or VNET in this case, SDK will do it for you as part of VM creation. If you need better control such as using existing or creating these dependency resources then sdk allows that as well.

 Refer the samples https://github.com/Azure/azure-sdk-for-java#sample-code here for more info. Let us know if you have any questions or suggestions about the new experience.

**Comment by LinaKorn** [comment]
Thanks for the answer @anuchandy . You write that SDK will create resources for us as part of VM creation, so does it makes via one API request?

**Comment by anuchandy** [comment]
SDK makes separate requests to create each resource. Some calls happens concurrently if the resources are not directly depends on each other.
