### ISSUE TITLE
AZURE Cosmos DB SDK client creation 

### ISSUE THREAD

**Issue by saralpa** [Azure/azure-sdk-for-java#17866]
Trying to create the cosmos DB client in azure function.  Sometimes it throws runtimeexception

java.lang.RuntimeException: Client initialization failed. Check if the endpoint is reachable and if your auth token is valid

Create a azure function. Trigger it using service bus topic and subscription. Create a cosmos db client .

CosmosClient client =
          MetaDataStoreCosmosClientBuilderUtil.getClientBuilder()
              .endpoint(COSMOSURL.toString())
              .key(key)
              .gatewayMode(gatewayConnectionConfig)
              .consistencyLevel(ConsistencyLevel.EVENTUAL)
              .buildClient();

**Expected behavior**
It should be able to create client successfully

**Screenshots**

**Setup (please complete the following information):**
 - IDE : [e.g. IntelliJ]
 - compile(group: 'com.azure',  name: 'azure-cosmos', version: '4.8.0')

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by kushagraThapar** [comment]
@saralpa - can you please make sure you are passing the correct credentials ?
If it is intermittent issue, it could be possible that client is getting initialized before credentials are passed in.

**Comment by kushagraThapar** [comment]
Closing this issue because of inactivity. @saralpa - please re-open the issue if you are still facing this error.

**Comment by zzgzy** [comment]
Having the same issue. I am using the CosmosClientBuilder from the most recent azure-cosmos-4.12.0.jar 

```
    val sp = new ClientSecretCredentialBuilder()
      .authorityHost(AzureAuthorityHosts.AZURE_PUBLIC_CLOUD)
      .tenantId(tenantId)
      .clientId(appId)
      .clientSecret(appSecret)
      .build()

    val endpoint = "https://mycosmosDB.documents.azure.com:443/"

    val client = new CosmosClientBuilder().endpoint(endpoint).credential(sp)
      .endpointDiscoveryEnabled(false)
      .directMode(directConnConfig)
      .consistencyLevel(ConsistencyLevel.SESSION)
      .buildAsyncClient()
```

The AppId and secret are correct as I double checked. Could anyone please help take a look? Thanks!

**Comment by kushagraThapar** [comment]
@zzgzy - the above issue only happens if the client is not able to connect to cosmos db endpoint. Can you please make sure that your cosmosdb account is reachable. 
Also, worth trying with gateway mode to see if you are only seeing the issue in Direct connection mode.

**Comment by saralpa** [comment]
This issue also occurs when we try to create multiple clients of cosmos DB.

**Comment by zzgzy** [comment]
Thank you @kushagraThapar for such a quick reply! I think the endpoint is reachable as I also used the .NET package preview version to test and it's able to connect and read database from cosmosDB.

I also tried to use the gatewaymode and the error I got this time is
```User class threw exception: java.lang.IllegalStateException: Timeout on blocking read for 120000 MILLISECONDS at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:123) at reactor.core.publisher.Mono.block(Mono.java:1709) at com.azure.cosmos.implementation.GlobalEndpointManager.init(GlobalEndpointManager.java:77) at com.azure.cosmos.implementation.RxDocumentClientImpl.init(RxDocumentClientImpl.java:393) at com.azure.cosmos.implementation.AsyncDocumentClient$Builder.build(AsyncDocumentClient.java:229) at com.azure.cosmos.CosmosAsyncClient.<init>(CosmosAsyncClient.java:104) at com.azure.cosmos.CosmosClientBuilder.buildAsyncClient(CosmosClientBuilder.java:729)``` 
 

The code snippet for client builder:
```
 val client = new CosmosClientBuilder()
      .endpoint(endpoint)
      .credential(sp)
      .endpointDiscoveryEnabled(false)
      .gatewayMode()
      .consistencyLevel(ConsistencyLevel.SESSION)
      .buildAsyncClient()

    client.readAllDatabases();
  }
```

**Comment by zzgzy** [comment]
Update: I am able to test it in JAVA code. Everything work, with Key or with the `ClientSecretCredential `created using AppID and secret. Since my use case is running the code in spark app on a HDInsight cluster, the current assumption is that the cluster has firewall issue so it block the connection to the cosmos endpoint. Anyway, it has nothing to do with the cosmosDB SDK or identity SDK.

**Comment by kushagraThapar** [comment]
Thanks for the detailed explanation @zzgzy

**Comment by moarychan** [comment]
Hi @kushagraThapar , I got the same exception using `azure-spring-data-cosmos:3.9.0`, could you help to take a look?
```java
public class CosmosDemo {
    public static void main(String[] args) {
        CosmosClientBuilder clientBuilder = new CosmosClientBuilder();
        final ClientSecretCredentialBuilder builder = new ClientSecretCredentialBuilder()
//            .authorityHost(AzureAuthorityHosts.AZURE_PUBLIC_CLOUD)
            .tenantId("tenant-id")
            .clientId("service-pricipal-id")
            .clientSecret("service-pricipal-secert");
        clientBuilder.endpoint("https://moaryc-cosmos.documents.azure.com:443/")
                     .gatewayMode(GatewayConnectionConfig.getDefaultConfig())
                     .credential(builder.build())
//                     .endpointDiscoveryEnabled(false)
//                     .consistencyLevel(ConsistencyLevel.SESSION)
        ;
        CosmosClient cosmosClient = clientBuilder.buildClient();
        System.out.println(cosmosClient.readAllDatabases());
    }
}
```
the service principal has been added as `owner` role for cosmos databases.
then found the following exception:
```text
10:45:53.487 [reactor-http-nio-3] ERROR com.azure.cosmos.implementation.GlobalEndpointManager - startRefreshLocationTimerAsync() - Unable to refresh database account from any location. Exception: {"ClassName":"CosmosException","userAgent":"azsdk-java-cosmos/4.17.0 Windows10/10.0 JRE/11.0.7","statusCode":403,"resourceAddress":"https://moaryc-cosmos.documents.azure.com:443/","error":"{\"code\":\"Forbidden\",\"message\":\"Request blocked by Auth moaryc-cosmos : Request is blocked because principal [0dfd3115-09fb-442f-9798-c91a139a53be] does not have required RBAC permissions to perform action [Microsoft.DocumentDB/databaseAccounts/readMetadata] on resource [/]. Learn more: https://aka.ms/cosmos-native-rbac.\\r\\nActivityId: 98a4fd96-9215-47aa-8a9f-d4049d57ec67, Microsoft.Azure.Documents.Common/2.14.0, StatusCode: Forbidden\",\"additionalErrorInfo\":null}","innerErrorMessage":"Request blocked by Auth moaryc-cosmos : Request is blocked because principal [0dfd3115-09fb-442f-9798-c91a139a53be] does not have required RBAC permissions to perform action [Microsoft.DocumentDB/databaseAccounts/readMetadata] on resource [/]. Learn more: https://aka.ms/cosmos-native-rbac.\r\nActivityId: 98a4fd96-9215-47aa-8a9f-d4049d57ec67, Microsoft.Azure.Documents.Common/2.14.0, StatusCode: Forbidden","causeInfo":null,"responseHeaders":"{Transfer-Encoding=chunked, Strict-Transport-Security=max-age=31536000, Server=Microsoft-HTTPAPI/2.0, Content-Location=https://moaryc-cosmos.documents.azure.com/, x-ms-gatewayversion=version=2.14.0, Date=Fri, 30 Jul 2021 02:45:52 GMT, x-ms-activity-id=98a4fd96-9215-47aa-8a9f-d4049d57ec67, Content-Type=application/json, x-ms-substatus=5301}","requestHeaders":"[Accept=application/json, x-ms-date=Fri, 30 Jul 2021 02:45:47 GMT]","cosmosDiagnostics":{"userAgent":"azsdk-java-cosmos/4.17.0 Windows10/10.0 JRE/11.0.7","requestLatencyInMs":1177,"requestStartTimeUTC":"2021-07-30T02:45:52.195778300Z","requestEndTimeUTC":"2021-07-30T02:45:53.372858100Z","responseStatisticsList":[],"supplementalResponseStatisticsList":[],"addressResolutionStatistics":{},"regionsContacted":[],"retryContext":{"statusAndSubStatusCodes":null,"retryLatency":0,"retryCount":0},"metadataDiagnosticsContext":{"metadataDiagnosticList":null},"serializationDiagnosticsContext":{"serializationDiagnosticsList":null},"gatewayStatistics":{"sessionToken":null,"operationType":"Read","resourceType":"DatabaseAccount","statusCode":403,"subStatusCode":5301,"requestCharge":null,"requestTimeline":[{"eventName":"connectionCreated","startTimeUTC":"2021-07-30T02:45:52.217778200Z","durationInMicroSec":848733},{"eventName":"connectionConfigured","startTimeUTC":"2021-07-30T02:45:53.066511500Z","durationInMicroSec":0},{"eventName":"requestSent","startTimeUTC":"2021-07-30T02:45:53.066511500Z","durationInMicroSec":13000},{"eventName":"transitTime","startTimeUTC":"2021-07-30T02:45:53.079511700Z","durationInMicroSec":252728},{"eventName":"received","startTimeUTC":"2021-07-30T02:45:53.332240100Z","durationInMicroSec":0}]},"systemInformation":{"usedMemory":"30366 KB","availableMemory":"2036066 KB","systemCpuLoad":"(2021-07-30T02:45:52.074781400Z 89.7%)","availableProcessors":4},"clientCfgs":{"id":0,"connectionMode":"GATEWAY","numberOfClients":1,"connCfg":{"rntbd":null,"gw":"(cps:1000, rto:PT5S, icto:PT1M, p:false)","other":"(ed: true, cs: false)"},"consistencyCfg":"(consistency: null, mm: true, prgns: [])"}}}
com.azure.cosmos.CosmosException: {"innerErrorMessage":"Request blocked by Auth moaryc-cosmos : Request is blocked because principal [0dfd3115-09fb-442f-9798-c91a139a53be] does not have required RBAC permissions to perform action [Microsoft.DocumentDB/databaseAccounts/readMetadata] on resource [/]. Learn more: https://aka.ms/cosmos-native-rbac.\r\nActivityId: 98a4fd96-9215-47aa-8a9f-d4049d57ec67, Microsoft.Azure.Documents.Common/2.14.0, StatusCode: Forbidden","cosmosDiagnostics":{"userAgent":"azsdk-java-cosmos/4.17.0 Windows10/10.0 JRE/11.0.7","requestLatencyInMs":1177,"requestStartTimeUTC":"2021-07-30T02:45:52.195778300Z","requestEndTimeUTC":"2021-07-30T02:45:53.372858100Z","responseStatisticsList":[],"supplementalResponseStatisticsList":[],"addressResolutionStatistics":{},"regionsContacted":[],"retryContext":{"statusAndSubStatusCodes":null,"retryLatency":0,"retryCount":0},"metadataDiagnosticsContext":{"metadataDiagnosticList":null},"serializationDiagnosticsContext":{"serializationDiagnosticsList":null},"gatewayStatistics":{"sessionToken":null,"operationType":"Read","resourceType":"DatabaseAccount","statusCode":403,"subStatusCode":5301,"requestCharge":null,"requestTimeline":[{"eventName":"connectionCreated","startTimeUTC":"2021-07-30T02:45:52.217778200Z","durationInMicroSec":848733},{"eventName":"connectionConfigured","startTimeUTC":"2021-07-30T02:45:53.066511500Z","durationInMicroSec":0},{"eventName":"requestSent","startTimeUTC":"2021-07-30T02:45:53.066511500Z","durationInMicroSec":13000},{"eventName":"transitTime","startTimeUTC":"2021-07-30T02:45:53.079511700Z","durationInMicroSec":252728},{"eventName":"received","startTimeUTC":"2021-07-30T02:45:53.332240100Z","durationInMicroSec":0}]},"systemInformation":{"usedMemory":"30407 KB","availableMemory":"2036025 KB","systemCpuLoad":"(2021-07-30T02:45:52.074781400Z 89.7%)","availableProcessors":4},"clientCfgs":{"id":0,"connectionMode":"GATEWAY","numberOfClients":1,"connCfg":{"rntbd":null,"gw":"(cps:1000, rto:PT5S, icto:PT1M, p:false)","other":"(ed: true, cs: false)"},"consistencyCfg":"(consistency: null, mm: true, prgns: [])"}}}
	at com.azure.cosmos.BridgeInternal.createCosmosException(BridgeInternal.java:463)
	at com.azure.cosmos.implementation.RxGatewayStoreModel.validateOrThrow(RxGatewayStoreModel.java:365)
	at com.azure.cosmos.implementation.RxGatewayStoreModel.lambda$toDocumentServiceResponse$0(RxGatewayStoreModel.java:294)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:106)
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:73)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:199)
	at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:118)
	at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:220)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:130)
	at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:184)
	at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1815)
	at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:128)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:259)
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:142)
	at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:401)
	at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:416)
	at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:470)
	at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:685)
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:94)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1368)
	at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1245)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1282)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
10:45:53.487 [reactor-http-nio-3] DEBUG com.azure.cosmos.implementation.GlobalEndpointManager - registering a refresh in [300000] ms
10:45:53.487 [reactor-http-nio-3] DEBUG reactor.netty.resources.DefaultPooledConnectionProvider - [id:dc49cbd8, L:/100.64.171.203:59002 - R:moaryc-cosmos.documents.azure.com/13.75.34.2:443] onStateChange(GET{uri=/, connection=PooledConnection{channel=[id: 0xdc49cbd8, L:/100.64.171.203:59002 - R:moaryc-cosmos.documents.azure.com/13.75.34.2:443]}}, [response_completed])
10:45:53.488 [reactor-http-nio-3] DEBUG reactor.netty.ReactorNetty - [id:dc49cbd8, L:/100.64.171.203:59002 - R:moaryc-cosmos.documents.azure.com/13.75.34.2:443] Removed handler: reactor.left.responseTimeoutHandler, pipeline: DefaultChannelPipeline{(reactor.left.sslHandler = io.netty.handler.ssl.SslHandler), (reactor.left.httpCodec = io.netty.handler.codec.http.HttpClientCodec), (reactor.right.reactiveBridge = reactor.netty.channel.ChannelOperationsHandler)}
10:45:53.488 [reactor-http-nio-3] DEBUG reactor.netty.resources.DefaultPooledConnectionProvider - [id:dc49cbd8, L:/100.64.171.203:59002 - R:moaryc-cosmos.documents.azure.com/13.75.34.2:443] onStateChange(GET{uri=/, connection=PooledConnection{channel=[id: 0xdc49cbd8, L:/100.64.171.203:59002 - R:moaryc-cosmos.documents.azure.com/13.75.34.2:443]}}, [disconnecting])
10:45:53.488 [reactor-http-nio-3] DEBUG reactor.netty.resources.DefaultPooledConnectionProvider - [id:dc49cbd8, L:/100.64.171.203:59002 - R:moaryc-cosmos.documents.azure.com/13.75.34.2:443] Releasing channel
10:45:53.489 [reactor-http-nio-3] DEBUG reactor.netty.resources.PooledConnectionProvider - [id:dc49cbd8, L:/100.64.171.203:59002 - R:moaryc-cosmos.documents.azure.com/13.75.34.2:443] Channel cleaned, now: 0 active connections, 1 inactive connections and 0 pending acquire requests.
10:45:53.490 [main] ERROR com.azure.cosmos.implementation.RxDocumentClientImpl - Client initialization failed. Check if the endpoint is reachable and if your auth token is valid
10:45:53.490 [main] ERROR com.azure.cosmos.implementation.RxDocumentClientImpl - unexpected failure in initializing client.
java.lang.RuntimeException: Client initialization failed. Check if the endpoint is reachable and if your auth token is valid
	at com.azure.cosmos.implementation.RxDocumentClientImpl.initializeGatewayConfigurationReader(RxDocumentClientImpl.java:391)
	at com.azure.cosmos.implementation.RxDocumentClientImpl.init(RxDocumentClientImpl.java:418)
	at com.azure.cosmos.implementation.AsyncDocumentClient$Builder.build(AsyncDocumentClient.java:241)
	at com.azure.cosmos.CosmosAsyncClient.<init>(CosmosAsyncClient.java:123)
	at com.azure.cosmos.CosmosClientBuilder.buildAsyncClient(CosmosClientBuilder.java:741)
	at com.azure.cosmos.CosmosClient.<init>(CosmosClient.java:32)
	at com.azure.cosmos.CosmosClientBuilder.buildClient(CosmosClientBuilder.java:753)
	at com.azure.spring.sample.cosmos.CosmosDemo.main(CosmosDemo.java:25)
10:45:53.490 [main] INFO com.azure.cosmos.implementation.RxDocumentClientImpl - Attempting to close client 0
10:45:53.490 [main] INFO com.azure.cosmos.implementation.RxDocumentClientImpl - Shutting down ...

```

**Comment by fatagun** [comment]
yes shit doesnt work.

**Comment by yatw** [comment]
I am also having the same problem 
Trying to connect from spring boot project to Azure Cosmos Emulator on Mac
`
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'cbnpathfinderScenarioApplication': Unsatisfied dependency expressed through field 'repository'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'userRepository' defined in com.jll.cbnpathfinderscenario.UserRepository defined in @EnableReactiveCosmosRepositories declared on CosmosReactiveRepositoriesAutoConfigureRegistrar.EnableCosmosReactiveRepositoriesConfiguration: Cannot resolve reference to bean 'reactiveCosmosTemplate' while setting bean property 'reactiveCosmosOperations'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'reactiveCosmosTemplate' defined in class path resource [com/azure/spring/autoconfigure/cosmos/CosmosAutoConfiguration.class]: Unsatisfied dependency expressed through method 'reactiveCosmosTemplate' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'cosmosFactory' defined in class path resource [com/azure/spring/autoconfigure/cosmos/CosmosAutoConfiguration.class]: Unsatisfied dependency expressed through method 'cosmosFactory' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cosmosAsyncClient' defined in class path resource [com/azure/spring/autoconfigure/cosmos/CosmosAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.azure.cosmos.CosmosAsyncClient]: Factory method 'cosmosAsyncClient' threw exception; nested exception is java.lang.RuntimeException: Client initialization failed. Check if the endpoint is reachable and if your auth token is valid. More info: https://aka.ms/cosmosdb-tsg-service-unavailable-java
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:659) ~[spring-beans-5.3.14.jar:5.3.14]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:639) ~[spring-beans-5.3.14.jar:5.3.14]
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119) ~[spring-beans-5.3.14.jar:5.3.14]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399) ~[spring-beans-5.3.14.jar:5.3.14]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1431) ~[spring-beans-5.3.14.jar:5.3.14]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619) ~[spring-beans-5.3.14.jar:5.3.14]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.14.jar:5.3.14]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.14.jar:5.3.14]
	at <unknown class>.getObject(Unknown Source) ~[na:na]`

	I have an emulator running locally
<img width="1124" alt="Screen Shot 2022-01-25 at 16 20 20" src="https://user-images.githubusercontent.com/19565177/151081794-3783e092-44ad-401a-9d1e-2a920647ffde.png">

	and properties
`
# Specify the DNS URI of your Azure Cosmos DB.
azure.cosmos.uri=https://localhost:8081

# Specify the access key for your database.
azure.cosmos.key=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==

# Specify the name of your database.
azure.cosmos.database=localhost
azure.cosmos.populateQueryMetrics=true`

also added certificate to keystore
`sudo keytool -importcert -file ./emulatorcert.crt -keystore "$JAVA_HOME"/lib/security/cacerts -alias "cosmosdb" --storepass changeit -noprompt 
Certificate was added to keystore
`

Please help

**Comment by IsmaelRP-apm** [comment]
> 

Im facing the same issue, any update? I added cosmosdb certificate to my own java jdk and intellij jdk, and tried to connect the same way:

azure:
  cosmos:
    uri: https://localhost:8081
    key: C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==
    database: dbname
    populate-query-metrics: true

**Comment by kushagraThapar** [comment]
@fatagun @yatw @IsmaelRP-apm  - with emulator on macOs, instead of using `localhost`, you should use the IP address that you configured per our public documentation here - https://docs.microsoft.com/en-us/azure/cosmos-db/linux-emulator?tabs=ssl-netstd21#run-on-macos

**Comment by IsmaelRP-apm** [comment]
> 

Thanks for your reply, I am currently using windows 10 with Azure Cosmos DB Emulator and trying to connect to a spring boot application.

**Comment by yatw** [comment]
Just to verify, the azure.cosmos.uri in properties should be mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator instead? I don't see other IP address.

**Comment by kushagraThapar** [comment]
> > 
> 
> Thanks for your reply, I am currently using windows 10 with Azure Cosmos DB Emulator and trying to connect to a spring boot application.

That should work out of the box, given you have installed certificates in java security libs correctly. We run our spring CI with emulator.

**Comment by milismsft** [comment]
@moarychan there are different roles and scopes related to service principals and Azure Cosmos DB service, depending on the type of scenario you are running. If you need a "control plane" role, where creating a database and container, adjusting the RU on the fly and other such operations are needed, please look at https://docs.microsoft.com/en-us/azure/cosmos-db/role-based-access-control.
For regular day to day SDK API calls please make sure you follow https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-setup-rbac on how to configure the service principal with the right roles and scopes.

@yatw I'm not sure I understand your question, and while will the azure.cosmos.uri in your case should point at the Docker image link? That particular configuration value should be set to reflect the emulator's endpoint and on MacOS that will be "https://$ipaddr:8081/" per our documentation and steps (see https://docs.microsoft.com/en-us/azure/cosmos-db/linux-emulator?tabs=ssl-netstd21#consume-endpoint-ui). Please make sure you follow all the steps, including the .PEM retrieval and later adding it to the Java's CACERTS.

@IsmaelRP-apm it's not very clear from your comment which emulator are you running, is it the MSI, the Linux emulator hosted on WSL? For the later please refer to my previous comment, make sure you use the IP address override and access the emulator as such; confirm that you can see the Data Explorer page and that you can download the .PEM content.
For the MSI, please refer to https://docs.microsoft.com/en-us/azure/cosmos-db/local-emulator-export-ssl-certificates#use-the-certificate-with-java-apps

**Comment by IsmaelRP-apm** [comment]
@kushagraThapar , @milismsft , sorry for my late answer, I really don't know if the installation of the certificates in the jdk helped, what solved the problem in the end were these two lines:
System.setProperty("javax.net.ssl.trustStore", "NUL");
System.setProperty("javax.net.ssl.trustStoreType", "Windows-ROOT");

I am currently using windows 10 with the native cosmosdb emulator for windows and as a reactive spring boot client.
