### ISSUE TITLE
[BUG][MoonCake] Identify report com.microsoft.aad.msal4j.MsalClientException: No Authorization code was returned from the server

### ISSUE THREAD

**Issue by andxu** [Azure/azure-sdk-for-java#17914]
When I am using Identify to auth using InteractiveBrowserCredential for AZURE_CHINA, it will report error:
```
Azure Identity => ERROR in getToken() call for scopes [https://management.core.chinacloudapi.cn/.default]: Failed to acquire token with Interactive Browser Authentication.
[Correlation ID: 3ee5b749-34a3-45d9-93d9-ed2edb2358d3] Execution of class com.microsoft.aad.msal4j.AcquireTokenByInteractiveFlowSupplier failed.
com.microsoft.aad.msal4j.MsalClientException: No Authorization code was returned from the server
	at com.microsoft.aad.msal4j.AcquireTokenByInteractiveFlowSupplier.getAuthorizationResultFromHttpListener(AcquireTokenByInteractiveFlowSupplier.java:140)
	at com.microsoft.aad.msal4j.AcquireTokenByInteractiveFlowSupplier.getAuthorizationResult(AcquireTokenByInteractiveFlowSupplier.java:64)
	at com.microsoft.aad.msal4j.AcquireTokenByInteractiveFlowSupplier.execute(AcquireTokenByInteractiveFlowSupplier.java:37)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:59)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:17)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Azure Identity => ERROR in getToken() call for scopes [https://management.core.chinacloudapi.cn/.default]: Failed to acquire token with Interactive Browser Authentication.
```
Here is my code:
```java
AzureProfile profile = new AzureProfile(AzureEnvironment.AZURE_CHINA);
            InteractiveBrowserCredential interactiveBrowserCredential = new InteractiveBrowserCredentialBuilder()
                    .clientId(AZ_CLI_CLIENT_ID)
                    .redirectUrl("http://localhost:" + 6111)
                    .build();

            PagedIterable<Subscription> client = AzureResourceManager
                    .configure()
                    .withLogLevel(HttpLogDetailLevel.BODY_AND_HEADERS)
                    .authenticate(interactiveBrowserCredential, profile)
                    .subscriptions().list();
            System.out.println(client.stream().count());

```

**Comment by andxu** [comment]
I need to configuration global env,  add the following statement will fix this error, my question is why  `authenticate(interactiveBrowserCredential, profile)` doesn't work?

```
Configuration.getGlobalConfiguration().put(Configuration.PROPERTY_AZURE_AUTHORITY_HOST, AzureAuthorityHosts.AZURE_CHINA);
```

**Comment by g2vinay** [comment]
@andxu 

When you select a different cloud, you also need to configure it in the Credential. 
Configuration is just one way to do it.
You  can do it programmatically too as follows:

```
        InteractiveBrowserCredential interactiveBrowserCredential = new InteractiveBrowserCredentialBuilder()
                .clientId(AZ_CLI_CLIENT_ID)
                .authorityHost(AzureAuthorityHosts.AZURE_CHINA)
                .redirectUrl("http://localhost:" + 6111)
                .build();
```

The credential needs to know about the cloud env too, by default it authenticates against public cloud.

Let us know if you need further help on this issue.
