### ISSUE TITLE
[BUG] CosmosException when using azure-spring-data-cosmos query methods with repeated parameters

### ISSUE THREAD

**Issue by dsibilio** [Azure/azure-sdk-for-java#17961]
**Describe the bug**

When defining a repository with a query method containing repeated parameters, the query execution will throw a `CosmosException` with error message: `Invalid query. Specified duplicate parameter name '@nameOfTheRepeatedParameter'`.

***Exception or Stack Trace***
```
com.azure.spring.data.cosmos.exception.CosmosAccessException: Failed to find items; nested exception is CosmosException{userAgent=azsdk-java-cosmos/4.9.0-beta.1 Windows10/10.0 JRE/1.8.0_201, error={"code":"BadRequest","message":"Gateway Failed to Retrieve Query Plan: Message: {\"Errors\":[\"Invalid query. Specified duplicate parameter name '@name'.\"]}\r\nActivityId: f275aed7-ee00-4805-9738-4efb517367e7, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, StatusCode: BadRequest","additionalErrorInfo":null}, resourceAddress='https://cosmos-integration-test-switzerlandnorth.documents.azure.com:443/dbs/testdb/colls/Project/docs, statusCode=400, message=Gateway Failed to Retrieve Query Plan: Message: {"Errors":["Invalid query. Specified duplicate parameter name '@name'."]}
ActivityId: f275aed7-ee00-4805-9738-4efb517367e7, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, StatusCode: BadRequest, {"userAgent":"azsdk-java-cosmos/4.9.0-beta.1 Windows10/10.0 JRE/1.8.0_201","requestLatencyInMs":72,"requestStartTimeUTC":"2020-12-03T15:41:06.746Z","requestEndTimeUTC":"2020-12-03T15:41:06.818Z","connectionMode":"GATEWAY","responseStatisticsList":[],"supplementalResponseStatisticsList":[],"addressResolutionStatistics":{},"regionsContacted":["https://cosmos-integration-test-switzerlandnorth.documents.azure.com:443/"],"retryContext":{"retryCount":0,"statusAndSubStatusCodes":null,"retryLatency":0},"metadataDiagnosticsContext":{"metadataDiagnosticList":null},"serializationDiagnosticsContext":{"serializationDiagnosticsList":null},"gatewayStatistics":{"sessionToken":null,"operationType":"QueryPlan","statusCode":400,"subStatusCode":0,"requestCharge":null,"requestTimeline":[{"eventName":"connectionCreated","startTimeUTC":"2020-12-03T15:41:06.750Z","durationInMicroSec":0},{"eventName":"connectionConfigured","startTimeUTC":"2020-12-03T15:41:06.750Z","durationInMicroSec":0},{"eventName":"requestSent","startTimeUTC":"2020-12-03T15:41:06.750Z","durationInMicroSec":1000},{"eventName":"transitTime","startTimeUTC":"2020-12-03T15:41:06.751Z","durationInMicroSec":66000},{"eventName":"received","startTimeUTC":"2020-12-03T15:41:06.817Z","durationInMicroSec":0}]},"systemInformation":{"usedMemory":"96444 KB","availableMemory":"3622724 KB","systemCpuLoad":"empty"},"clientCfgs":{"id":0,"numberOfClients":1,"connCfg":{"rntbd":"(cto:PT5S, rto:PT5S, icto:PT0S, ieto:PT1H, mcpe:130, mrpc:30, cer:false)","gw":"(cps:1000, rto:PT5S, icto:null, p:false)","other":"(ed: true, cs: false)"},"consistencyCfg":"(consistency: null, mm: true, prgns: [])"}}, causeInfo=null, responseHeaders={Transfer-Encoding=chunked, Strict-Transport-Security=max-age=31536000, Server=Microsoft-HTTPAPI/2.0, x-ms-gatewayversion=version=2.11.0, Date=Thu, 03 Dec 2020 15:41:06 GMT, x-ms-activity-id=f275aed7-ee00-4805-9738-4efb517367e7, Content-Type=application/json}, requestHeaders=[Accept=application/json, x-ms-cosmos-is-query-plan-request=True, x-ms-date=Thu, 03 Dec 2020 15:41:06 GMT, x-ms-cosmos-supported-query-features=Aggregate, CompositeAggregate, MultipleOrderBy, MultipleAggregates, OrderBy, OffsetAndLimit, Distinct, GroupBy, Top, NonValueAggregate, x-ms-cosmos-query-version=1.0, Content-Type=application/query+json]}
	at com.azure.spring.data.cosmos.exception.CosmosExceptionUtils.exceptionHandler(CosmosExceptionUtils.java:30)
	at com.azure.spring.data.cosmos.core.CosmosTemplate.lambda$27(CosmosTemplate.java:781)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:88)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.checkTerminated(FluxFlatMap.java:834)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:600)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.drain(FluxFlatMap.java:580)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onError(FluxFlatMap.java:443)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.doError(FluxPublishOn.java:510)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.checkTerminated(FluxPublishOn.java:548)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runAsync(FluxPublishOn.java:431)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:526)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: CosmosException{userAgent=azsdk-java-cosmos/4.9.0-beta.1 Windows10/10.0 JRE/1.8.0_201, error={"code":"BadRequest","message":"Gateway Failed to Retrieve Query Plan: Message: {\"Errors\":[\"Invalid query. Specified duplicate parameter name '@name'.\"]}\r\nActivityId: f275aed7-ee00-4805-9738-4efb517367e7, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, StatusCode: BadRequest","additionalErrorInfo":null}, resourceAddress='https://cosmos-integration-test-switzerlandnorth.documents.azure.com:443/dbs/testdb/colls/Project/docs, statusCode=400, message=Gateway Failed to Retrieve Query Plan: Message: {"Errors":["Invalid query. Specified duplicate parameter name '@name'."]}
ActivityId: f275aed7-ee00-4805-9738-4efb517367e7, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, StatusCode: BadRequest, {"userAgent":"azsdk-java-cosmos/4.9.0-beta.1 Windows10/10.0 JRE/1.8.0_201","requestLatencyInMs":72,"requestStartTimeUTC":"2020-12-03T15:41:06.746Z","requestEndTimeUTC":"2020-12-03T15:41:06.818Z","connectionMode":"GATEWAY","responseStatisticsList":[],"supplementalResponseStatisticsList":[],"addressResolutionStatistics":{},"regionsContacted":["https://cosmos-integration-test-switzerlandnorth.documents.azure.com:443/"],"retryContext":{"retryCount":0,"statusAndSubStatusCodes":null,"retryLatency":0},"metadataDiagnosticsContext":{"metadataDiagnosticList":null},"serializationDiagnosticsContext":{"serializationDiagnosticsList":null},"gatewayStatistics":{"sessionToken":null,"operationType":"QueryPlan","statusCode":400,"subStatusCode":0,"requestCharge":null,"requestTimeline":[{"eventName":"connectionCreated","startTimeUTC":"2020-12-03T15:41:06.750Z","durationInMicroSec":0},{"eventName":"connectionConfigured","startTimeUTC":"2020-12-03T15:41:06.750Z","durationInMicroSec":0},{"eventName":"requestSent","startTimeUTC":"2020-12-03T15:41:06.750Z","durationInMicroSec":1000},{"eventName":"transitTime","startTimeUTC":"2020-12-03T15:41:06.751Z","durationInMicroSec":66000},{"eventName":"received","startTimeUTC":"2020-12-03T15:41:06.817Z","durationInMicroSec":0}]},"systemInformation":{"usedMemory":"96444 KB","availableMemory":"3622724 KB","systemCpuLoad":"empty"},"clientCfgs":{"id":0,"numberOfClients":1,"connCfg":{"rntbd":"(cto:PT5S, rto:PT5S, icto:PT0S, ieto:PT1H, mcpe:130, mrpc:30, cer:false)","gw":"(cps:1000, rto:PT5S, icto:null, p:false)","other":"(ed: true, cs: false)"},"consistencyCfg":"(consistency: null, mm: true, prgns: [])"}}, causeInfo=null, responseHeaders={Transfer-Encoding=chunked, Strict-Transport-Security=max-age=31536000, Server=Microsoft-HTTPAPI/2.0, x-ms-gatewayversion=version=2.11.0, Date=Thu, 03 Dec 2020 15:41:06 GMT, x-ms-activity-id=f275aed7-ee00-4805-9738-4efb517367e7, Content-Type=application/json}, requestHeaders=[Accept=application/json, x-ms-cosmos-is-query-plan-request=True, x-ms-date=Thu, 03 Dec 2020 15:41:06 GMT, x-ms-cosmos-supported-query-features=Aggregate, CompositeAggregate, MultipleOrderBy, MultipleAggregates, OrderBy, OffsetAndLimit, Distinct, GroupBy, Top, NonValueAggregate, x-ms-cosmos-query-version=1.0, Content-Type=application/query+json]}
		at com.azure.cosmos.BridgeInternal.createCosmosException(BridgeInternal.java:423)
		at com.azure.cosmos.implementation.RxGatewayStoreModel.validateOrThrow(RxGatewayStoreModel.java:346)
		at com.azure.cosmos.implementation.RxGatewayStoreModel.lambda$null$0(RxGatewayStoreModel.java:275)
		at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:100)
		at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:67)
		at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:192)
		at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:112)
		at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:213)
		at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:123)
		at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:178)
		at reactor.core.publisher.FluxContextStart$ContextStartSubscriber.onNext(FluxContextStart.java:96)
		at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1782)
		at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:121)
		at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:252)
		at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:136)
		at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:378)
		at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:373)
		at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:429)
		at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:645)
		at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:96)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
		at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
		at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
		at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
		at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
		at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
		at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1526)
		at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1287)
		at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1324)
		at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
		at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
		at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
		at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
		at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
		at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
		at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
		at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
		at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
		at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
		... 1 more
	[CIRCULAR REFERENCE:CosmosException{userAgent=azsdk-java-cosmos/4.9.0-beta.1 Windows10/10.0 JRE/1.8.0_201, error={"code":"BadRequest","message":"Gateway Failed to Retrieve Query Plan: Message: {\"Errors\":[\"Invalid query. Specified duplicate parameter name '@name'.\"]}\r\nActivityId: f275aed7-ee00-4805-9738-4efb517367e7, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, StatusCode: BadRequest","additionalErrorInfo":null}, resourceAddress='https://cosmos-integration-test-switzerlandnorth.documents.azure.com:443/dbs/testdb/colls/Project/docs, statusCode=400, message=Gateway Failed to Retrieve Query Plan: Message: {"Errors":["Invalid query. Specified duplicate parameter name '@name'."]}
ActivityId: f275aed7-ee00-4805-9738-4efb517367e7, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, StatusCode: BadRequest, {"userAgent":"azsdk-java-cosmos/4.9.0-beta.1 Windows10/10.0 JRE/1.8.0_201","requestLatencyInMs":72,"requestStartTimeUTC":"2020-12-03T15:41:06.746Z","requestEndTimeUTC":"2020-12-03T15:41:06.818Z","connectionMode":"GATEWAY","responseStatisticsList":[],"supplementalResponseStatisticsList":[],"addressResolutionStatistics":{},"regionsContacted":["https://cosmos-integration-test-switzerlandnorth.documents.azure.com:443/"],"retryContext":{"retryCount":0,"statusAndSubStatusCodes":null,"retryLatency":0},"metadataDiagnosticsContext":{"metadataDiagnosticList":null},"serializationDiagnosticsContext":{"serializationDiagnosticsList":null},"gatewayStatistics":{"sessionToken":null,"operationType":"QueryPlan","statusCode":400,"subStatusCode":0,"requestCharge":null,"requestTimeline":[{"eventName":"connectionCreated","startTimeUTC":"2020-12-03T15:41:06.750Z","durationInMicroSec":0},{"eventName":"connectionConfigured","startTimeUTC":"2020-12-03T15:41:06.750Z","durationInMicroSec":0},{"eventName":"requestSent","startTimeUTC":"2020-12-03T15:41:06.750Z","durationInMicroSec":1000},{"eventName":"transitTime","startTimeUTC":"2020-12-03T15:41:06.751Z","durationInMicroSec":66000},{"eventName":"received","startTimeUTC":"2020-12-03T15:41:06.817Z","durationInMicroSec":0}]},"systemInformation":{"usedMemory":"96444 KB","availableMemory":"3622724 KB","systemCpuLoad":"empty"},"clientCfgs":{"id":0,"numberOfClients":1,"connCfg":{"rntbd":"(cto:PT5S, rto:PT5S, icto:PT0S, ieto:PT1H, mcpe:130, mrpc:30, cer:false)","gw":"(cps:1000, rto:PT5S, icto:null, p:false)","other":"(ed: true, cs: false)"},"consistencyCfg":"(consistency: null, mm: true, prgns: [])"}}, causeInfo=null, responseHeaders={Transfer-Encoding=chunked, Strict-Transport-Security=max-age=31536000, Server=Microsoft-HTTPAPI/2.0, x-ms-gatewayversion=version=2.11.0, Date=Thu, 03 Dec 2020 15:41:06 GMT, x-ms-activity-id=f275aed7-ee00-4805-9738-4efb517367e7, Content-Type=application/json}, requestHeaders=[Accept=application/json, x-ms-cosmos-is-query-plan-request=True, x-ms-date=Thu, 03 Dec 2020 15:41:06 GMT, x-ms-cosmos-supported-query-features=Aggregate, CompositeAggregate, MultipleOrderBy, MultipleAggregates, OrderBy, OffsetAndLimit, Distinct, GroupBy, Top, NonValueAggregate, x-ms-cosmos-query-version=1.0, Content-Type=application/query+json]}]


```

**To Reproduce**

Implement an azure-spring-data-cosmos repository containing a query method that uses repeated parameters to filter entities, eg.:

```java
public interface ProjectRepository extends CosmosRepository<Project, String> {
    Iterable<Project> findByNameAndCreatorOrNameAndCreator(String name, String creator, String name2, String creator2);
}
```

and invoke such method.

***Code Snippet***

The issue seems to lie within the [com.azure.spring.data.cosmos.core.generator.AbstractQueryGenerator.generateQueryParameter(String)](https://github.com/Azure/azure-sdk-for-java/blob/62ab2af8edd9e94263668afe287e19e5088e31e0/sdk/cosmos/azure-spring-data-cosmos/src/main/java/com/azure/spring/data/cosmos/core/generator/AbstractQueryGenerator.java#L33-L35)  method that is used to provide an alias starting from a parameter name. It does not include any implementation logic to make sure that such parameter names be unique in case of a parameter being present more than once in the same query filter.

**Expected behavior**

**Setup (please complete the following information):**
 - OS: Windows 10 64-bit
 - IDE : Eclipse 2019-06
 - Version of the Library used: com.azure:azure-spring-data-cosmos:3.2.0-beta.1 _(master)_

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by kushagraThapar** [comment]
@dsibilio - Since the PR is merged, it will be released when we ship next version. Closing this issue now.
