### ISSUE TITLE
[BUG] blob - A request was made to load the default HttpClient provider but one could not be found on the classpath

### ISSUE THREAD

**Issue by tooptoop4** [Azure/azure-sdk-for-java#17970]
Following https://docs.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-java?tabs=powershell get this error:

Caused by: java.lang.IllegalStateException: A request was made to load the default HttpClient provider but one could not be found on the classpath. If you are using a dependency manager, consider including a dependency on azure-core-http-netty or azure-core-http-okhttp. Depending on your existing dependencies, you have the choice of Netty or OkHttp implementations. Additionally, refer to https://aka.ms/azsdk/java/docs/custom-httpclient to learn about writing your own implementation.
at com.azure.core.implementation.http.HttpClientProviders.createInstance(HttpClientProviders.java:37)
at com.azure.core.http.HttpClient.createDefault(HttpClient.java:27)
at com.azure.core.http.HttpPipelineBuilder.build(HttpPipelineBuilder.java:60)
at com.azure.storage.blob.implementation.util.BuilderHelper.buildPipeline(BuilderHelper.java:110)
at com.azure.storage.blob.BlobServiceClientBuilder.buildAsyncClient(BlobServiceClientBuilder.java:107)
at com.azure.storage.blob.BlobServiceClientBuilder.buildClient(BlobServiceClientBuilder.java:84)

**Comment by tooptoop4** [comment]
error thrown by:
BlobServiceClient blobServiceClient = new BlobServiceClientBuilder().endpoint("https://azuremlexamples.blob.core.windows.net").buildClient();

**Comment by joshfree** [comment]
Thanks for reporting the issue with the QuickStart @tooptoop4.  @alzimmermsft could you help correct the doc (and perhaps update it to reference 12.9 instead of 12.6).

**Comment by alzimmermsft** [comment]
@tooptoop4 which version of `azure-storage-blob` did you use when running the sample? The error message you included is from a newer version (12.9.0). Looking to scope the investigation as running the sample verbatim it was able to work for me.

**Comment by tooptoop4** [comment]
maybe close this and track under https://github.com/Azure/azure-sdk-for-java/issues/17982. I am not running Quickstart verbatim as I am trying BlobServiceClient blobServiceClient = new BlobServiceClientBuilder().endpoint("https://azuremlexamples.blob.core.windows.net").buildClient();

**Comment by tooptoop4** [comment]
https://stackoverflow.com/a/65179461/8874837 works
