### ISSUE TITLE
Spring Side-by-Side Support

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#17986]
This issue will contain the discussion around how we plan to support multiple Spring Framework versions side-by-side within the repository.

**Comment by chenrujun** [comment]
2 options appeared in my mind:
1. Let `spring-boot-starter-xxx:3.0.x`  only support `spring-boot:2.4.x`, not support `spring-boot:2.3.x`.
2. Let `azure-core` and `azure-core-netty` support multiple versions of (`netty` and `reactor`) at the same time.

I prefer 1. Because 2 is hard is not easy to implement and maintain.

**Comment by jialindai** [comment]
The latest version of Spring integration module and sdk library can only work with Spring boot 2.4.x is not a very good developer experience.

For options from @chenrujun , I think option 1 is more practical. 

We will need a branch though for Spring integration modules 2.x.x which works with Spring boot 2.2.x and 2.3.x. This branch is for potential bug fix and feature back port.

Another direction we can explore is if explicitly specify the reactor library version can make the Spring module (and sdk library) work in Spring boot 2.2.x and 2.3.x.

**Comment by chenrujun** [comment]
Hi, @jialindai ,

> Another direction we can explore is if explicitly specify the reactor library version can make the Spring module (and sdk library) work in Spring boot 2.2.x and 2.3.x.

I created a PR to test it: https://github.com/Azure/azure-sdk-for-java/pull/18009

My concern is that even if `java - cosmos - tests` pipeline passed, we can not make sure our customer can use it without problem. Because the pipeline can not cover all execute path.

**Comment by chenrujun** [comment]
@jialindai ,FYI: 

The pipeline failed. Because current sdk code does not support the new version of reactor and netty.

I think we can test it after https://github.com/Azure/azure-sdk-for-java/pull/17905 merged.

If we need use branch to support multiple spring-boot, we should create branch before https://github.com/Azure/azure-sdk-for-java/pull/17905 merged. 

Sure, we can create branch from specific commit id, it's harder to create branch from commit than create branch from branch, because it's not easy to find the target commit id.

**Comment by saragluna** [comment]
https://github.com/Azure/azure-sdk-for-java/issues/15512, the issue to track the eng-related effort.

**Comment by moarychan** [comment]
## Overview

Support more major Spring Boot versions.
- Demonstrate how much modification is needed to achieve this purpose.
- Lots of Azure Spring developers would like to use the latest Azure SDK features in their SpringBoot versions, which means the SpringBoot version is not the latest version.

## Scenario Scope
- Supported Scenarios
  - Support multiple service directories for the same azure service with different versions.
- Not-Supported Scenarios
  - Under different service directories of the same service, cross-dependent is not supported.
  - Modules in multi-version of the same service can not be cross-dependent.
  - Project `azure-spring-boot-bom` does not contain the sample project with multiple versions, even in different service directories
  - Project `jacoco-test-coverage` does not contain the sample project with multiple versions, even in different service directories
  

## Solution Analysis
We focus on the `spring` service directory.

The service directory `spring` will support the latest feature and the latest SpringBoot versions, another service directory `spring-2-3` will support the latest major version of SpringBoot 2.3.x, maybe the name `spring-lts` better, they will use the same Azure SDK dependencies at the same time.



### Achieve the goal from the following 3 aspects and its steps:
#### Azure SDK side

Each SDK module should comply with depending on third-party interfaces and avoid depending on the specific implementations so that it can be used normally in multi major versions of SpringBoot.


#### Azure Spring side
- Version number planning for other non-major versions

This is important for developers to easily find out the version they want to use.

- Source code
  Check out the tag from the last release version based on Spring boot 2.3.x.
  1. Add the new service directory `spring-2-3`.
  2. Check out from tag `azure-spring-boot_3.2.0` which is based on spring boot version `2.3.5.RELEASE` version.
  3. Upgrade spring boot version to `2.3.10.RELEASE`.
  4. Use the new version number for the modules under the `spring-2-3` service directory.

- Version tag
  
  Add a new tag for the versions of the `spring-2-3` service directory depended on.

- CI and live test job

  The CI and test job should distinguish the same projects under the special service directory.

  Add new *ci.yml* for the `spring-2-3` service directory, for the duplicate modules, we should add the extra property `path` for each project, the eng side will use this path value to construct the special project coordinate.
  
  Pipeline command:

  | CI  | Live tests |
  |--|--|
  | /azp run java - spring - ci | /azp run java - spring - tests |
  | /azp run java - spring-2-3 - ci | /azp run java - spring-2-3 - tests |

  Note: Each new service directory should pass the ci and tests checking at least.

#### Eng side

- Extend the `Artifacts` structure to support the definition of the relative path of the project

  When the relative path is configured, you should use the relative path of the project to assemble the `-pl` parameter value.

  `mvn -f pom.xml xxx -Drevapi.skip=true -pl ,com.azure.spring:azure-identity-spring`
  update to:
  `mvn -f pom.xml xxx -Drevapi.skip=true -pl ,./sdk/spring/azure-identity-spring`
  `mvn -f pom.xml xxx -Drevapi.skip=true -pl ,./sdk/spring-2-3/azure-identity-spring`

  You can refer to [Maven CLI Options](https://maven.apache.org/ref/3.6.1/maven-embedder/cli.html) for more detail about `-pl`.

- Extend the `generate-project-list.yml` script to support a mixed list of the project list

  The demo version is [here](https://github.com/moarychan/azure-sdk-for-java/blob/feature/add-spring-boot-2.3.x-version/eng/pipelines/templates/steps/generate-project-list.yml).
  
  There are 3 combinations 
  `-pl ,com.azure.spring:azure-spring-data-gremlin,com.azure.spring:azure-spring-data-gremlin`
  
  `-pl ,./sdk/spring-2-3/azure-spring-data-gremlin,./sdk/spring-2-3/azure-spring-boot-starter-active-directory`

  `-pl ,com.azure.spring:azure-spring-data-gremlin,./sdk/spring-2-3/azure-spring-boot-starter-active-directory`
  

- Extend `pom_file_version_scanner.ps1` script

  Support the multiple version tag can be found when the default value of combination group id and artifact id can not be found.

  The demo version is [here](https://github.com/moarychan/azure-sdk-for-java/blob/feature/add-spring-boot-2.3.x-version/eng/versioning/pom_file_version_scanner.ps1).

- Extend `generate_from_source_pom.py` script

  The demo version is [here](https://github.com/moarychan/azure-sdk-for-java/blob/feature/add-spring-boot-2.3.x-version/eng/pipelines/scripts/generate_overview_from_readme.py).

  - Identify the current service directory, avoid being rewritten
      
      This means the same project under different service directory only one item will be found, and another service directory will be ignored. 
      E.g, if we find the `azure-spring-boot-starter-active-directory` coordinate, the current service directory is `spring-2-3`, 
      then the `./sdk/spring/azure-spring-boot-starter-active-directory` coordinate will be ignored.
      
  - Identify different versions of the same project in multiple service directory

      This script will temporarily generate the *ClientFromSourcePom.xml* based on the variable `$(ProjectList)`, 
      then build the project locally based on this file. The relative path of the project coordinate will be read and searched.
  
      E.g, for `java - servicebus - ci` command, the below snippet will be generated.
      ```xml
      <modules>
        <module>/sdk/servicebus/azure-messaging-servicebus</module>
        <module>/sdk/spring-2-3/azure-spring-boot-samples/azure-spring-boot-sample-servicebus</module>
        <module>/sdk/spring/azure-spring-boot-samples/azure-spring-boot-sample-servicebus</module>
        <module>/sdk/storage/azure-storage-blob</module>
      </modules>
      ```
  

## Architecture/Workflow Diagram

high-level architecture based on cosmos

![support-multi-version](https://user-images.githubusercontent.com/19926623/120420950-f6060600-c397-11eb-82a2-6ebb8f2c2de3.png)


## Impacts to Current System

More test resource cost and time-consuming to build.

## Testability and Test Plan

We use this [PR](https://github.com/Azure/azure-sdk-for-java/pull/21258) to test our design and provide a reference for follow-up work.

## Upgrading Plan

**TBC**

## Release Process

**TBC**

## Open Issues

Current issue.

Exception found in `spring-2-3` modules when upgrading to the same Azure SDK version.
### reactor-core conflicts in Cosmos, KeyVault, ServiceBus, Storage

#### Exception stack(Azure Cosmos)

```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.azure.cosmos.CosmosAsyncClient]: Factory method 'cosmosAsyncClient' threw exception; nested exception is java.lang.NoClassDefFoundError: reactor/util/context/ContextView
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:652)
	... 77 more
Caused by: java.lang.NoClassDefFoundError: reactor/util/context/ContextView
	at com.azure.cosmos.implementation.http.HttpClient.createFixed(HttpClient.java:61)
	at com.azure.cosmos.implementation.RxDocumentClientImpl.httpClient(RxDocumentClientImpl.java:536)
	at com.azure.cosmos.implementation.RxDocumentClientImpl.<init>(RxDocumentClientImpl.java:355)
	at com.azure.cosmos.implementation.RxDocumentClientImpl.<init>(RxDocumentClientImpl.java:224)
	at com.azure.cosmos.implementation.RxDocumentClientImpl.<init>(RxDocumentClientImpl.java:207)
	at com.azure.cosmos.implementation.AsyncDocumentClient$Builder.build(AsyncDocumentClient.java:227)
	at com.azure.cosmos.CosmosAsyncClient.<init>(CosmosAsyncClient.java:123)
	at com.azure.cosmos.CosmosClientBuilder.buildAsyncClient(CosmosClientBuilder.java:741)
	at com.azure.spring.data.cosmos.CosmosFactory.createCosmosAsyncClient(CosmosFactory.java:70)
	at com.azure.spring.data.cosmos.config.AbstractCosmosConfiguration.cosmosAsyncClient(AbstractCosmosConfiguration.java:57)
	at com.azure.spring.autoconfigure.cosmos.CosmosAutoConfiguration$$EnhancerBySpringCGLIB$$62385660.CGLIB$cosmosAsyncClient$5(<generated>)
	at com.azure.spring.autoconfigure.cosmos.CosmosAutoConfiguration$$EnhancerBySpringCGLIB$$62385660$$FastClassBySpringCGLIB$$bfbadc10.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
	at com.azure.spring.autoconfigure.cosmos.CosmosAutoConfiguration$$EnhancerBySpringCGLIB$$62385660.cosmosAsyncClient(<generated>)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 78 more
Caused by: java.lang.ClassNotFoundException: reactor.util.context.ContextView
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 98 more

```

#### Solution
In fact, the developers should deal with the version conflicts when using this starter based on `spring-boot-starter-parent`.  **azure-core** does depend on the correct version of `reactor-core`, but the `spring-boot-dependencies` locks a low version, so we only can override the version property **reactor-bom.version**.

```xml
<properties>
  <!-- Change reactor-bom version from Dysprosium-SR19 to 2020.0.6-->
  <reactor-bom.version>2020.0.6</reactor-bom.version>
</properties>
```

### reactor-core conflicts in EventHubs binder

#### Exception stack
```
Caused by: org.springframework.context.ApplicationContextException: Failed to start bean 'inputBindingLifecycle'; nested exception is java.lang.NoClassDefFoundError: reactor/util/context/ContextView
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:185)
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:53)
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:360)
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:158)
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:122)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:895)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:554)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:755)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:402)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312)
	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:120)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:99)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:124)
	... 54 more
Caused by: java.lang.NoClassDefFoundError: reactor/util/context/ContextView
	at com.azure.storage.blob.implementation.ServicesImpl.<init>(ServicesImpl.java:62)
	at com.azure.storage.blob.implementation.AzureBlobStorageImpl.<init>(AzureBlobStorageImpl.java:216)
	at com.azure.storage.blob.implementation.AzureBlobStorageBuilder.build(AzureBlobStorageBuilder.java:93)
	at com.azure.storage.blob.BlobContainerAsyncClient.<init>(BlobContainerAsyncClient.java:130)
	at com.azure.storage.blob.BlobContainerClientBuilder.buildAsyncClient(BlobContainerClientBuilder.java:132)
	at com.azure.spring.integration.eventhub.factory.DefaultEventHubClientFactory.createEventProcessorClientInternal(DefaultEventHubClientFactory.java:97)
	at com.azure.spring.integration.eventhub.factory.DefaultEventHubClientFactory.lambda$createEventProcessorClient$1(DefaultEventHubClientFactory.java:149)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at com.azure.spring.integration.eventhub.factory.DefaultEventHubClientFactory.createEventProcessorClient(DefaultEventHubClientFactory.java:148)
	at com.azure.spring.integration.eventhub.impl.AbstractEventHubTemplate.createEventProcessorClient(AbstractEventHubTemplate.java:102)
	at com.azure.spring.integration.eventhub.impl.EventHubTemplate.subscribe(EventHubTemplate.java:38)
	at com.azure.spring.integration.core.api.SubscribeByGroupOperation.subscribe(SubscribeByGroupOperation.java:30)
	at com.azure.spring.integration.core.AbstractInboundChannelAdapter.doStart(AbstractInboundChannelAdapter.java:58)
	at org.springframework.integration.endpoint.AbstractEndpoint.start(AbstractEndpoint.java:154)
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindConsumer(AbstractMessageChannelBinder.java:414)
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindConsumer(AbstractMessageChannelBinder.java:90)
	at org.springframework.cloud.stream.binder.AbstractBinder.bindConsumer(AbstractBinder.java:143)
	at org.springframework.cloud.stream.binding.BindingService.doBindConsumer(BindingService.java:176)
	at org.springframework.cloud.stream.binding.BindingService.bindConsumer(BindingService.java:133)
	at org.springframework.cloud.stream.binding.AbstractBindableProxyFactory.createAndBindInputs(AbstractBindableProxyFactory.java:112)
	at org.springframework.cloud.stream.binding.InputBindingLifecycle.doStartWithBindable(InputBindingLifecycle.java:58)
	at java.base/java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608)
	at org.springframework.cloud.stream.binding.AbstractBindingLifecycle.start(AbstractBindingLifecycle.java:57)
	at org.springframework.cloud.stream.binding.InputBindingLifecycle.start(InputBindingLifecycle.java:34)
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:182)
	... 67 more
Caused by: java.lang.ClassNotFoundException: reactor.util.context.ContextView
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 92 more
```

#### Sulution
Upgrade reactor-bom version configurations.
```xml
<properties>
  <!-- Change reactor-bom version from Dysprosium-SR19 to 2020.0.6-->
  <reactor-bom.version>2020.0.6</reactor-bom.version>
</properties>
```

**Comment by saragluna** [comment]
After discussing with the engineering team, we decided to perform hotfix or feature releases from the latest tags to support other active Spring Boot versions instead of supporting them side-by-side. I documented it in a [wiki page](https://github.com/Azure/azure-sdk-for-java/wiki/Spring:-Support-Multiple-Spring-Versions).

**Comment by mrm9084** [comment]
@saragluna will we be updating that info it seems to be quite a bit out of date. For example we currently support Spring Boot 2.5.

**Comment by saragluna** [comment]
@mrm9084 do you mean this one https://github.com/Azure/azure-sdk-for-java/wiki/Spring%3A-Spring-Boot-Dependency-Mapping?

**Comment by mrm9084** [comment]
@saragluna Yes, and https://github.com/Azure/azure-sdk-for-java/wiki/Spring:-Support-Multiple-Spring-Versions#spring-boot

**Comment by saragluna** [comment]
@mrm9084 yes, will update it now.

**Comment by saragluna** [comment]
I'm closing this issue now @alzimmermsft for there's a converged design on this.
