### ISSUE TITLE
[BUG] Cosmos ChangeFeedProcessor errors with invalid JSON when item already has the `_lsn` property 

### ISSUE THREAD

**Issue by sivamu** [Azure/azure-sdk-for-java#18091]
**Describe the bug**
I'm using the Cosmos ChangeFeedProcessor to read the changefeed for a specific container. If I insert a new item with the `_lsn` property defined, the Processor fails due to an InvalidJson object.

I am aware that the `_lsn` property is a hidden/private property but for our use case (Kafka Connectors), this is a plausible situation.

***Exception or Stack Trace***
```
[2020-12-11 19:49:02,933] WARN Unexpected exception from thread 195 (com.azure.cosmos.implementation.changefeed.implementation.PartitionProcessorImpl)
java.lang.IllegalStateException: Unable to parse JSON [123, 34, 95, 114, 105, 100, 34, 58, 34, 104, 119, 107, 113, 65, 75, 48, 85, 52, 52, 111, 61, 34, 44, 34, 68, 111, 99, 117, 109, 101, 110, 116, 115, 34, 58, 91, 123, 34, 105, 100, 34, 58, 34, 104, 52, 34, 44, 34, 95, 108, 115, 110, 34, 58, 53, 44, 34, 95, 114, 105, 100, 34, 58, 34, 104, 119, 107, 113, 65, 75, 48, 85, 52, 52, 111, 71, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 61, 61, 34, 44, 34, 95, 115, 101, 108, 102, 34, 58, 34, 100, 98, 115, 92, 47, 104, 119, 107, 113, 65, 65, 61, 61, 92, 47, 99, 111, 108, 108, 115, 92, 47, 104, 119, 107, 113, 65, 75, 48, 85, 52, 52, 111, 61, 92, 47, 100, 111, 99, 115, 92, 47, 104, 119, 107, 113, 65, 75, 48, 85, 52, 52, 111, 71, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 61, 61, 92, 47, 34, 44, 34, 95, 101, 116, 97, 103, 34, 58, 34, 92, 34, 99, 48, 48, 48, 50, 101, 48, 101, 45, 48, 48, 48, 48, 45, 48, 56, 48, 48, 45, 48, 48, 48, 48, 45, 53, 102, 100, 51, 99, 100, 50, 57, 48, 48, 48, 48, 92, 34, 34, 44, 34, 95, 97, 116, 116, 97, 99, 104, 109, 101, 110, 116, 115, 34, 58, 34, 97, 116, 116, 97, 99, 104, 109, 101, 110, 116, 115, 92, 47, 34, 44, 34, 95, 116, 115, 34, 58, 49, 54, 48, 55, 55, 49, 54, 49, 51, 55, 44, 34, 95, 108, 115, 110, 34, 58, 57, 125, 93, 44, 34, 95, 99, 111, 117, 110, 116, 34, 58, 49, 125]
        at com.azure.cosmos.implementation.RxDocumentServiceResponse.fromJson(RxDocumentServiceResponse.java:174)
        at com.azure.cosmos.implementation.RxDocumentServiceResponse.getQueryResponse(RxDocumentServiceResponse.java:124)
        at com.azure.cosmos.models.ModelBridgeInternal.toChaneFeedResponsePage(ModelBridgeInternal.java:324)
        at com.azure.cosmos.BridgeInternal.toChangeFeedResponsePage(BridgeInternal.java:108)
...
...
Caused by: com.fasterxml.jackson.core.JsonParseException: Duplicate field '_lsn'
 at [Source: (byte[])"{"_rid":"hwkqAK0U44o=","Documents":[{"id":"h4","_lsn":5,"_rid":"hwkqAK0U44oGAAAAAAAAAA==","_self":"dbs\/hwkqAA==\/colls\/hwkqAK0U44o=\/docs\/hwkqAK0U44oGAAAAAAAAAA==\/","_etag":"\"c0002e0e-0000-0800-0000-5fd3cd290000\"","_attachments":"attachments\/","_ts":1607716137,"_lsn":9}],"_count":1}"; line: 1, column: 275]
        at com.fasterxml.jackson.core.json.JsonReadContext._checkDup(JsonReadContext.java:204)
        at com.fasterxml.jackson.core.json.JsonReadContext.setCurrentName(JsonReadContext.java:198)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextFieldName(UTF8StreamJsonParser.java:1039)
        at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:250)
        at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeArray(JsonNodeDeserializer.java:437)
        at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:261)
        at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:68)
        at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:15)
        at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4576)
        at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2986)
        at com.azure.cosmos.implementation.RxDocumentServiceResponse.fromJson(RxDocumentServiceResponse.java:172)
        ... 71 more
```

**To Reproduce**

- Clone and setup the [sample ChangeFeedProcessor application](https://github.com/Azure-Samples/azure-cosmos-java-sql-app-example)
- Add `_lsn` property with an integer value [here](https://github.com/Azure-Samples/azure-cosmos-java-sql-app-example/blob/main/src/main/java/com/azure/cosmos/workedappexample/SampleGroceryStore.java#L297)
Result should look like:
```java

            String jsonString =    "{\"id\" : \"" + id + "\""
                                 + ","
                                 + "\"brand\" : \"" + brands.get(i) + "\""
                                 + ","
                                 + "\"type\" : \"" + types.get(i) + "\""
                                 + ","
                                 + "\"quantity\" : \"" + quantities.get(i) + "\""
                                 + ","
                                 + "\"_lsn\" : 5"
                                 + "}";

```
- Run the sample application. The application will error out when new items are being inserted

***Code Snippet***
As mentioned above, simply modify the Sample code as such:

Add `_lsn` property with an integer value [here](https://github.com/Azure-Samples/azure-cosmos-java-sql-app-example/blob/main/src/main/java/com/azure/cosmos/workedappexample/SampleGroceryStore.java#L297)
Result should look like:
```java

            String jsonString =    "{\"id\" : \"" + id + "\""
                                 + ","
                                 + "\"brand\" : \"" + brands.get(i) + "\""
                                 + ","
                                 + "\"type\" : \"" + types.get(i) + "\""
                                 + ","
                                 + "\"quantity\" : \"" + quantities.get(i) + "\""
                                 + ","
                                 + "\"_lsn\" : 5"
                                 + "}";

```

**Expected behavior**
SDK should update the `_lsn` property if it exists in the item body, rather than trying to add it again. Otherwise, the resulting object will end up with two `_lsn` fields, and thus being invalid JSON.

**Screenshots**
N/A

**Setup (please complete the following information):**
 - OS: Ubuntu (Codespaces specifically)
 - IDE : VSCode
 - Version of the Library used: `azure-cosmos 4.8.0`

**Additional context**
N/A

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by kushagraThapar** [comment]
@milismsft please take a look at this.

**Comment by kushagraThapar** [comment]
@milismsft - any updates on this issue ?

**Comment by kushagraThapar** [comment]
Closing this because of inactivity, @sivamu  pls re-open if the issue still persists.
