### ISSUE TITLE
[BUG] Sending message stop after certain period of time

### ISSUE THREAD

**Issue by kekatahi** [Azure/azure-sdk-for-java#18293]
**Describe the bug**
When the device send messages on a regular basis, sending messages will stop after a certain period of time.
Although this device also do the receive operation from other device, receiving operation also stop when this issue happen.

***Exception or Stack Trace***
```
com.azure.messaging.servicebus.ServiceBusException: Did not observe any item or terminal signal within 60000ms in 'takeUntil' (and no fallback has been configured)
        at com.azure.messaging.servicebus.ServiceBusSenderAsyncClient.mapError(ServiceBusSenderAsyncClient.java:734)
        at com.azure.messaging.servicebus.ServiceBusSenderAsyncClient.lambda$sdnkNTfOSsjt71Sge2CDNDwGsp8(Unknown Source:0)
        at com.azure.messaging.servicebus.-$$Lambda$ServiceBusSenderAsyncClient$sdnkNTfOSsjt71Sge2CDNDwGsp8.apply(Unknown Source:4)
        at reactor.core.publisher.Mono.lambda$onErrorMap$30(Mono.java:3286)
        at reactor.core.publisher.-$$Lambda$Mono$XLTmz-olhTxwhVTbz1w4HO4CnSc.apply(Unknown Source:4)
        at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:88)
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:165)
        at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onError(FluxPeekFuseable.java:227)
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondError(MonoFlatMap.java:185)
        at reactor.core.publisher.MonoFlatMap$FlatMapInner.onError(MonoFlatMap.java:251)
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondError(MonoFlatMap.java:185)
        at reactor.core.publisher.MonoFlatMap$FlatMapInner.onError(MonoFlatMap.java:251)
        at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onError(FluxMapFuseable.java:134)
        at reactor.core.publisher.Operators$MonoSubscriber.onError(Operators.java:1829)
        at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreInner.onError(MonoIgnoreThen.java:235)
        at reactor.core.publisher.SerializedSubscriber.onError(SerializedSubscriber.java:124)
        at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.whenError(FluxRetryWhen.java:213)
        at reactor.core.publisher.FluxRetryWhen$RetryWhenOtherSubscriber.onError(FluxRetryWhen.java:255)
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.checkTerminated(FluxFlatMap.java:834)
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:600)
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.drain(FluxFlatMap.java:580)
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.onError(FluxFlatMap.java:443)
        at reactor.core.publisher.FluxZip$ZipCoordinator.drain(FluxZip.java:747)
        at reactor.core.publisher.FluxZip$ZipInner.onNext(FluxZip.java:911)
        at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114)
        at reactor.core.publisher.DirectProcessor$DirectInner.onNext(DirectProcessor.java:339)
        at reactor.core.publisher.DirectProcessor.onNext(DirectProcessor.java:148)
        at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:99)
        at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.onError(FluxRetryWhen.java:180)
        at reactor.core.publisher.SerializedSubscriber.onError(SerializedSubscriber.java:124)
        at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.handleTimeout(FluxTimeout.java:288)
        at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.doTimeout(FluxTimeout.java:273)
        at reactor.core.publisher.FluxTimeout$TimeoutTimeoutSubscriber.onNext(FluxTimeout.java:395)
        at reactor.core.publisher.StrictSubscriber.onNext(StrictSubscriber.java:89)
        at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:73)
        at reactor.core.publisher.MonoDelay$MonoDelayRunnable.run(MonoDelay.java:117)
        at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
        at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 60000ms in 'takeUntil' (and no fallback has
```

```
java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 3000ms in 'onErrorResume' (and no fallback has been configured)
        at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.handleTimeout(FluxTimeout.java:288)
        at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.doTimeout(FluxTimeout.java:273)
        at reactor.core.publisher.FluxTimeout$TimeoutTimeoutSubscriber.onNext(FluxTimeout.java:395)
        at reactor.core.publisher.StrictSubscriber.onNext(StrictSubscriber.java:89)
        at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:73)
        at reactor.core.publisher.MonoDelay$MonoDelayRunnable.run(MonoDelay.java:117)
        at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
        at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

**To Reproduce**
1.Sending a message (async) to the specified topic every 3 seconds.
2.The message is initially sent as expected.
3.After a while (2-5 minutes), sending message will stop.

Just wait a few minutes and we'll be able to send the message again.
(It has not been resolved. Sending will stop after a certain period of time.)
The sending function seems to be executed, but it looks like that  the completion flow doesn't run, we guess.

***Code Snippet***
1.Creat Client
```
    public ServiceBusSenderAsyncClient getSenderClient(String topicName) {
        return new ServiceBusClientBuilder()
                .connectionString(rootConnectionString)
                .sender()
                .topicName(topicName)
                .buildAsyncClient();
    }
```

2.Sending message
```
protected void sendMessage(ServiceBusSenderAsyncClient sender, String messageText, String userName) {
        try {
            String deviceId = "xxxx-xxxx-xxxx-xxxx";
            ServiceBusMessage m = new ServiceBusMessage(messageText.getBytes())
                    .setSubject(userName)
                    .setCorrelationId(deviceId)
                    .setContentType("application/json");            
            // Sending message
            sender.sendMessage(m).subscribe(unused -> {
                }, error -> {
                    Log.e("[Failed to send message]", Log.getStackTraceString(error));
                }, () -> {
                    Log.i("[Completed]", "Completed to send message");
            });
    }
```
3.Sending message on a regular basis.
We use the startService(new Intent(packageContext, serviceClassName)) for starting the service. 
```
    public int onStartCommand(Intent intent, int flags, int startId) {
        super.onStartCommand( intent, flags, startId );
        // executed another thred
        schedule = Executors.newSingleThreadScheduledExecutor();
        schedule.scheduleAtFixedRate(new Runnable() {
            @Override
            public void run() {
                // send message
                String message = "";
                try {
                    sendMessage(sender, message);
                } catch (IllegalStateException e) {
                    Log.e("UnSent", Log.getStackTraceString(e));
                    sender.close();
                    sender = getSenderClient(topic);
                }
            }
        }, 0, interval, TimeUnit.MILLISECONDS);
        return START_STICKY_COMPATIBILITY;
    }
```

**Expected behavior**
We can send the message without stopping

**Setup (please complete the following information):**
 - OS: Android 9（Lenovo TB X606X）
 - Version of the Library used
 azure-messaging-servicebus : 7.0.0
minSdkVersion : 26

**Comment by hemanttanwar** [comment]
@kekatahi  I am looking into it and will update you after I try to replicate it. Meanwhile I have a question.
Have you seen this issue on Windows/Linux using Java 9 or Java 11 ? Or your use case is to run on  Mobile App using "Android 9" ?

**Comment by kekatahi** [comment]
I haven't seen similar issue Java 9 ,11. Yes , true. Customer use Android 9 on their mobile app.
Customer agreed to close the case because they use the rest api and this issue never happened so far.
Before the case close , I hope I could follow up the issue.

Thanks,
Kentaro

**Comment by hemanttanwar** [comment]
@kekatahi I was able to run a sample android application  which ran for 10 minutes and sent one message every 5 seconds  and 122 messages in-total.   I am not able to replicate the issue.
My setting is following. 
minSdkVersion 26
JDK 1.8
Android Studio 4.1

I am not android expert, but talking to someone, the scheduling of thread which run your service is controlled and android OS controls it and it can stop it as well.  You might want to implement following call back to understand what is happening.

```java
   @Override
    public void onDestroy() {
      // Log this.
    }
```
From SDK point of view: By default if there is no activity by sender for 60 seconds , it will close underlaying connections, that is what I see in your exception. You can follow that discussion here also https://github.com/Azure/azure-sdk-for-java/issues/18123

**Comment by hemanttanwar** [comment]
Since we found no issue, I am closing it. If you need more clarification, you can reopen it or create new issue
