### ISSUE TITLE
[BUG] uploadWithResponse throws an exception rather than returning the error status code

### ISSUE THREAD

**Issue by clarkbreyman-yammer** [Azure/azure-sdk-for-java#18437]
**Describe the bug**
I'm calling `BlobClient.uploadWithResponse` with the hope that the xWithResponse methods return Responses with error status codes instead of throwing exceptions, yet on CONFLICT an exception is throws rather than returning a 409 response.  

***Exception or Stack Trace***
Add the exception log and stack trace if available
```
com.azure.storage.blob.models.BlobStorageException: Status code 409, "﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>BlobAlreadyExists</Code><Message>The specified blob already exists.
RequestId:fcc21d97-001e-0037-221b-e3653f000000
Time:2021-01-05T04:31:56.6208571Z</Message></Error>"
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_212]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_212]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_212]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_212]
	at com.azure.core.http.rest.RestProxy.instantiateUnexpectedException(RestProxy.java:334) ~[app.jar:1.1.190-SNAPSHOT]
	at com.azure.core.http.rest.RestProxy.lambda$ensureExpectedStatus$5(RestProxy.java:375) ~[app.jar:1.1.190-SNAPSHOT]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:118) ~[app.jar:1.1.190-SNAPSHOT]
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1782) ~[app.jar:1.1.190-SNAPSHOT]
	at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.signalCached(MonoCacheTime.java:320) ~[app.jar:1.1.190-SNAPSHOT]
	at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.onNext(MonoCacheTime.java:337) ~[app.jar:1.1.190-SNAPSHOT]
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2344) ~[app.jar:1.1.190-SNAPSHOT]
	at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.onSubscribe(MonoCacheTime.java:276) ~[app.jar:1.1.190-SNAPSHOT]
	at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:191) ~[app.jar:1.1.190-SNAPSHOT]
	at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53) ~[app.jar:1.1.190-SNAPSHOT]
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57) ~[app.jar:1.1.190-SNAPSHOT]
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) ~[app.jar:1.1.190-SNAPSHOT]
	at reactor.core.publisher.MonoCacheTime.subscribeOrReturn(MonoCacheTime.java:132) ~[app.jar:1.1.190-SNAPSHOT]
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57) ~[app.jar:1.1.190-SNAPSHOT]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:150) ~[app.jar:1.1.190-SNAPSHOT]
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:123) ~[app.jar:1.1.190-SNAPSHOT]
	at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:112) ~[app.jar:1.1.190-SNAPSHOT]
	at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:213) ~[app.jar:1.1.190-SNAPSHOT]
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:123) ~[app.jar:1.1.190-SNAPSHOT]
	at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:178) ~[app.jar:1.1.190-SNAPSHOT]
	at reactor.core.publisher.FluxContextStart$ContextStartSubscriber.onNext(FluxContextStart.java:96) ~[app.jar:1.1.190-SNAPSHOT]
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1782) ~[app.jar:1.1.190-SNAPSHOT]
	at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:121) ~[app.jar:1.1.190-SNAPSHOT]
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:252) ~[app.jar:1.1.190-SNAPSHOT]
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:136) ~[app.jar:1.1.190-SNAPSHOT]
	at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:374) ~[app.jar:1.1.190-SNAPSHOT]
	at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:373) ~[app.jar:1.1.190-SNAPSHOT]
	at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:429) ~[app.jar:1.1.190-SNAPSHOT]
	at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:655) ~[app.jar:1.1.190-SNAPSHOT]
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:96) ~[app.jar:1.1.190-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[app.jar:1.1.190-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[app.jar:1.1.190-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[app.jar:1.1.190-SNAPSHOT]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) ~[app.jar:1.1.190-SNAPSHOT]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[app.jar:1.1.190-SNAPSHOT]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[app.jar:1.1.190-SNAPSHOT]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) ~[app.jar:1.1.190-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[app.jar:1.1.190-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[app.jar:1.1.190-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[app.jar:1.1.190-SNAPSHOT]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1526) ~[app.jar:1.1.190-SNAPSHOT]
	at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1287) ~[app.jar:1.1.190-SNAPSHOT]
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1324) ~[app.jar:1.1.190-SNAPSHOT]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501) ~[app.jar:1.1.190-SNAPSHOT]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440) ~[app.jar:1.1.190-SNAPSHOT]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[app.jar:1.1.190-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[app.jar:1.1.190-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[app.jar:1.1.190-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[app.jar:1.1.190-SNAPSHOT]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[app.jar:1.1.190-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[app.jar:1.1.190-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[app.jar:1.1.190-SNAPSHOT]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[app.jar:1.1.190-SNAPSHOT]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) ~[app.jar:1.1.190-SNAPSHOT]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475) ~[app.jar:1.1.190-SNAPSHOT]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[app.jar:1.1.190-SNAPSHOT]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[app.jar:1.1.190-SNAPSHOT]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[app.jar:1.1.190-SNAPSHOT]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[app.jar:1.1.190-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_212]
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:139) ~[app.jar:1.1.190-SNAPSHOT]
		at reactor.core.publisher.Mono.block(Mono.java:1704) ~[app.jar:1.1.190-SNAPSHOT]
		at com.azure.storage.common.implementation.StorageImplUtils.blockWithOptionalTimeout(StorageImplUtils.java:101) ~[app.jar:1.1.190-SNAPSHOT]
		at com.azure.storage.blob.BlobClient.uploadWithResponse(BlobClient.java:231) ~[app.jar:1.1.190-SNAPSHOT]

```

**To Reproduce**
Attempt to write to a blob that exists with the `.setRequestConditions(NO_OVERWRITE)` set in ParallelUploadOptions.

***Code Snippet***
```
      byte[] leaseData = "lock".getBytes(StandardCharsets.UTF_8);
      BlobClient leaseBlob = container.getBlobClient(schema.lease());
      Response<BlockBlobItem> response =
          leaseBlob.uploadWithResponse(
              new BlobParallelUploadOptions(new ByteArrayInputStream(leaseData), leaseData.length)
                  .setRequestConditions(NO_OVERWRITE),
              Duration.ofMillis(500),
              null);
      if (!success(response) && response.getStatusCode() != HTTP_CONFLICT) {
        LOG.error("Create lease blob {} returns {}", schema.lease(), response.getStatusCode());
        throw new FailedUploadException(new Exception("Cannot create lease blob"));
      }
      BlobLeaseClient leaseClient = new BlobLeaseClientBuilder().blobClient(leaseBlob).buildClient();
      leaseClient.acquireLease(LEASE_SECONDS);
      return leaseClient;
```

**Expected behavior**
I would expect a 409 status `response` to be returned on conflict (meaning the blob exists) and I would allow that and attempt to acquire the lease. Instead an exception is thrown. 

**Screenshots**

**Setup (please complete the following information):**
 - OS: Linux (several)
 - IDE : IntelliJ
 - Version of the Library used: 12.9.0

**Additional context**
n/a

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by gapra-msft** [comment]
Hi @clarkbreyman-yammer Thank you for posting this issue. 

Throwing an exception on a 409 is by design as it is a blob service error code. I would recommend following this [sample](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/storage/azure-storage-blob/src/samples/java/com/azure/storage/blob/StorageErrorHandlingExample.java) to appropriately handle the 409 and acquire the lease.
