### ISSUE TITLE
[BUG]Android mobile app getting crashed due to Class Definetion not found for class java.time.Duration

### ISSUE THREAD

**Issue by krunalshah-insigmainc** [Azure/azure-sdk-for-java#18555]
**Describe the bug**
Android mobile application is crashing on belo line of code,
```
EventHubConsumerAsyncClient consumer = new EventHubClientBuilder()
                .connectionString(QA_endPointConnectionString)
                .consumerGroup(consumerGroup[consumerGroupPosition])
                .buildAsyncConsumerClient();
```

***Exception or Stack Trace***
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/Duration;
	at com.azure.core.amqp.AmqpRetryOptions.<init>(AmqpRetryOptions.java:27)
	at com.azure.messaging.eventhubs.EventHubClientBuilder.<clinit>(EventHubClientBuilder.java:124)
	at com.ebestiot.vending.mqttservice.MQTTHelper.initEventHub(MQTTHelper.java:246)
	at com.ebestiot.vending.mqttservice.MQTTHelper.createEventHub(MQTTHelper.java:240)
	at com.ebestiot.vending.transaction.TransactionActivity.unlockDoor(TransactionActivity.java:180)
	at com.ebestiot.vending.transaction.TransactionActivity.onConnectionOpen(TransactionActivity.java:168)
	at com.ebestiot.vending.mqttservice.MQTTHelper$1.onSuccess(MQTTHelper.java:87)
	at com.ebestiot.vending.mqttservice.MQTTHelper$1.onSuccess(MQTTHelper.java:78)

**To Reproduce**
Device configuration:
OS: 7.0
Device Model: MI MAX (helium) (MI MAX)

**Comment by anuchandy** [comment]
@krunalshah-insigmainc - the `java.time.Duration` is a native android platform package, which is only available starting from android API level 26 [ref](https://developer.android.com/reference/java/time/package-summary), I suspect you're using EH-library in an application that targets api level lower then 26.

**Comment by krunalshah-insigmainc** [comment]
What should I have to do for support the android version from 21.


Thank you,

Krunal Shah - Sr. Android Developer

Insigma Inc.

(m)  +91 9429162090

(skype)  live:f7b400cb9a83b761


________________________________

**Comment by krunalshah-insigmainc** [comment]
@anuchandy Could you please reply?

**Comment by anuchandy** [comment]
Please see this comment https://github.com/Azure/azure-sdk-for-java/issues/35756#issuecomment-1627833991 Currently Android API version 26, or above, may work with the Java SDKs. But Android is still officially unsupported by the Azure SDK for Java repository.
