### ISSUE TITLE
[BUG]EventHubChannelResourceManagerProvisioner->validateOrCreateForConsumer-ProvisioningException in Azure Spring Cloud Stream Binder

### ISSUE THREAD

**Issue by pdp5210** [Azure/azure-sdk-for-java#18658]
**Describe the bug**
spring.cloud.stream.bindings.output.destination is getting created but not the input destination when used below configuration
spring.cloud.azure.auto-create-resources=true

***Exception or Stack Trace***

2021-01-17 22:05:42.632  INFO 1839 --- [           main] c.a.s.c.context.core.impl.AzureManager   : Fetching EventHubNamespace with name 'event-hub-spring-cloud-test' ...
2021-01-17 22:05:42.673  INFO 1839 --- [           main] c.a.s.c.context.core.impl.AzureManager   : Fetching EventHubNamespace with name 'event-hub-spring-cloud-test' finished in 0 seconds
2021-01-17 22:05:42.674  INFO 1839 --- [           main] c.a.s.c.context.core.impl.AzureManager   : Fetching EventHub with name 'toUpperCase-out-0' ...
2021-01-17 22:05:43.603  INFO 1839 --- [           main] c.a.s.c.context.core.impl.AzureManager   : Fetching EventHub with name 'toUpperCase-out-0' finished in 0 seconds
2021-01-17 22:05:43.603  INFO 1839 --- [           main] c.a.s.c.context.core.impl.AzureManager   : Creating EventHub with name 'toUpperCase-out-0' ...
2021-01-17 22:05:46.063  INFO 1839 --- [           main] c.a.s.c.context.core.impl.AzureManager   : Creating EventHub with name 'toUpperCase-out-0' finished in 2 seconds
2021-01-17 22:05:46.066  INFO 1839 --- [           main] c.a.s.i.c.a.r.DefaultMessageHandler      : DefaultMessageHandler sync becomes: false
2021-01-17 22:05:46.066  INFO 1839 --- [           main] c.a.s.i.c.a.r.DefaultMessageHandler      : DefaultMessageHandler syncTimeout becomes: ValueExpression [value=10000]
2021-01-17 22:05:46.067  INFO 1839 --- [           main] c.a.s.i.c.a.r.DefaultMessageHandler      : Started DefaultMessageHandler with properties: {sendTimeout=ValueExpression [value=10000], destination=toUpperCase-out-0, sync=false}
2021-01-17 22:05:46.067  INFO 1839 --- [           main] o.s.c.s.m.DirectWithAttributesChannel    : Channel 'application.toUpperCase-out-0' has 1 subscriber(s).
2021-01-17 22:05:46.068  INFO 1839 --- [           main] o.s.c.s.binder.DefaultBinderFactory      : Retrieving cached binder: eventhub
2021-01-17 22:05:46.083  INFO 1839 --- [           main] c.a.s.c.context.core.impl.AzureManager   : Fetching EventHubNamespace with name 'event-hub-spring-cloud-test' ...
2021-01-17 22:05:46.150  INFO 1839 --- [           main] c.a.s.c.context.core.impl.AzureManager   : Fetching EventHubNamespace with name 'event-hub-spring-cloud-test' finished in 0 seconds
2021-01-17 22:05:46.150  INFO 1839 --- [           main] c.a.s.c.context.core.impl.AzureManager   : Fetching EventHub with name 'toUpperCase-in-0' ...
2021-01-17 22:05:47.081  INFO 1839 --- [           main] c.a.s.c.context.core.impl.AzureManager   : Fetching EventHub with name 'toUpperCase-in-0' finished in 0 seconds
2021-01-17 22:05:47.086 ERROR 1839 --- [           main] o.s.cloud.stream.binding.BindingService  : Failed to create consumer binding; retrying in 30 seconds

org.springframework.cloud.stream.provisioning.ProvisioningException: Event hub with name 'toUpperCase-in-0' in namespace 'event-hub-spring-cloud-test' not existed
	at com.azure.spring.eventhub.stream.binder.provisioning.EventHubChannelResourceManagerProvisioner.validateOrCreateForConsumer(EventHubChannelResourceManagerProvisioner.java:35) ~[azure-spring-cloud-stream-binder-eventhubs-2.0.0-beta.1.jar:na]
	at com.azure.spring.eventhub.stream.binder.provisioning.EventHubChannelProvisioner.provisionConsumerDestination(EventHubChannelProvisioner.java:32) ~[azure-spring-cloud-stream-binder-eventhubs-2.0.0-beta.1.jar:na]
	at com.azure.spring.eventhub.stream.binder.provisioning.EventHubChannelProvisioner.provisionConsumerDestination(EventHubChannelProvisioner.java:18) ~[azure-spring-cloud-stream-binder-eventhubs-2.0.0-beta.1.jar:na]
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindConsumer(AbstractMessageChannelBinder.java:402) ~[spring-cloud-stream-3.0.8.RELEASE.jar:3.0.8.RELEASE]
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindConsumer(AbstractMessageChannelBinder.java:90) ~[spring-cloud-stream-3.0.8.RELEASE.jar:3.0.8.RELEASE]
	at org.springframework.cloud.stream.binder.AbstractBinder.bindConsumer(AbstractBinder.java:143) ~[spring-cloud-stream-3.0.8.RELEASE.jar:3.0.8.RELEASE]
	at org.springframework.cloud.stream.binding.BindingService.doBindConsumer(BindingService.java:176) [spring-cloud-stream-3.0.8.RELEASE.jar:3.0.8.RELEASE]
	at org.springframework.cloud.stream.binding.BindingService.bindConsumer(BindingService.java:133) [spring-cloud-stream-3.0.8.RELEASE.jar:3.0.8.RELEASE]
	at org.springframework.cloud.stream.binding.AbstractBindableProxyFactory.createAndBindInputs(AbstractBindableProxyFactory.java:112) [spring-cloud-stream-3.0.8.RELEASE.jar:3.0.8.RELEASE]
	at org.springframework.cloud.stream.binding.InputBindingLifecycle.doStartWithBindable(InputBindingLifecycle.java:58) [spring-cloud-stream-3.0.8.RELEASE.jar:3.0.8.RELEASE]
	at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608) ~[na:1.8.0_152]
	at org.springframework.cloud.stream.binding.AbstractBindingLifecycle.start(AbstractBindingLifecycle.java:57) ~[spring-cloud-stream-3.0.8.RELEASE.jar:3.0.8.RELEASE]
	at org.springframework.cloud.stream.binding.InputBindingLifecycle.start(InputBindingLifecycle.java:34) [spring-cloud-stream-3.0.8.RELEASE.jar:3.0.8.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:182) ~[spring-context-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:53) ~[spring-context-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:360) ~[spring-context-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:158) ~[spring-context-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:122) ~[spring-context-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:895) ~[spring-context-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:554) ~[spring-context-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758) ~[spring-boot-2.3.7.RELEASE.jar:2.3.7.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750) ~[spring-boot-2.3.7.RELEASE.jar:2.3.7.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:405) ~[spring-boot-2.3.7.RELEASE.jar:2.3.7.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-2.3.7.RELEASE.jar:2.3.7.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237) ~[spring-boot-2.3.7.RELEASE.jar:2.3.7.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) ~[spring-boot-2.3.7.RELEASE.jar:2.3.7.RELEASE]
	at com.spring.cloudstream.CloudStreamApplication.main(CloudStreamApplication.java:13) ~[classes/:na]

**To Reproduce**
Use below sample project with Azure event hub (From Spring One conference 2019)
https://github.com/schacko-samples/s1p-2019-scst-kafka-talk/tree/master/hello-streams-application

I have used below Microsoft document to create the event hub example and worked fine
https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-cloud-stream-binder-java-app-azure-event-hub

But not working with latest spring cloud stream code, I'm using latest version from azure which has latest spring cloud stream dependency
<dependency>
			<groupId>com.microsoft.azure</groupId>
			<artifactId>spring-cloud-azure-eventhubs-stream-binder</artifactId>
			<version>2.0.0-beta.1</version>
		</dependency>

***Code Snippet***
application.properties used:
spring.cloud.azure.credential-file-path=my.azureauth
spring.cloud.azure.resource-group=spring-cloud-test
spring.cloud.azure.AzureEnvironment=Azure
spring.cloud.azure.region=southcentralus
spring.cloud.azure.auto-create-resources=true
spring.cloud.azure.eventhub.namespace=event-hub-spring-cloud-test
spring.cloud.azure.eventhub.checkpoint-storage-account=springcloudteststorage
spring.cloud.stream.bindings.input.group=$Default
spring.cloud.stream.eventhub.bindings.input.consumer.checkpoint-mode=MANUAL

**Expected behavior**
I should be able to test the event hub with latest spring cloud stream dependency
<dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-stream</artifactId>
      <version>3.0.8.RELEASE</version> 
    </dependency>

**Screenshots**

**Setup (please complete the following information):**
 - OS: iOS
 - IDE : IntelliJ
 - Version of the Library used
 - spring-cloud-stream (3.0.8.RELEASE)
 - spring-cloud-azure-eventhubs-stream-binder (2.0.0-beta.1)

**Additional context**
Try to avoid boiler plate code and want to see if I can avoid source and sink configuration

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by joshfree** [comment]
@jialindai could you please help route this issue?

**Comment by saragluna** [comment]
Hi @pdp5210, sorry for the late reply. are you using the functional programming model? From this `'toUpperCase-in-0`, it's the default binding name for an event hub consumer. You could follow this sample, we've just applied the functional programming model for it. https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/spring/azure-spring-boot-samples/azure-spring-cloud-sample-eventhubs-binder

**Comment by pdp5210** [comment]
Thanks Dai for the response, will try out the sample and will update you.

Thanks,
Pradeep

**Comment by pdp5210** [comment]
Good afternoon,

Is there an option to download the specific Azure maven dependency when
running the sample? My organization has an artifact repository which allows
to download the maven central if not found and azure sdk repositories are
not listed. It worked out fine in my personal laptop as I built the
complete azure java sdk before running the sample. Please suggest

Sample: azure-spring-cloud-sample-eventhubs-binder, it's failing to
download below dependencies also attached the error in below email

<dependency>
  <groupId>com.azure.spring</groupId>
  <artifactId>azure-spring-cloud-stream-binder-eventhubs</artifactId>
  <version>2.2.0-beta.1</version> 
</dependency>

<dependency>
  <groupId>com.azure.spring</groupId>
  <artifactId>azure-spring-cloud-storage</artifactId>
  <version>2.2.0-beta.1</version> 
</dependency>


[ERROR] Failed to execute goal on project
azure-spring-cloud-sample-eventhubs-binder: Could not resolve dependencies
for project com.azure.spring:azure-spring-cloud-sample-eventhubs-bi
nder:jar:1.0.0: The following artifacts could not be resolved:
com.azure.spring:azure-spring-cloud-stream-binder-eventhubs:jar:2.2.0-beta.1,
com.azure.spring:azure-spring-cloud-storage
:jar:2.2.0-beta.1: Could not find artifact
com.azure.spring:azure-spring-cloud-stream-binder-eventhubs:jar:2.2.0-beta.1
in XXXXXXX (organization artifact repo)


Thanks,
Pradeep

**Comment by saragluna** [comment]
Hi @pdp5210, you could use this version instead https://github.com/Azure/azure-sdk-for-java/blob/azure-spring-cloud-stream-binder-servicebus-queue_2.1.0/sdk/spring/azure-spring-boot-samples/azure-spring-cloud-sample-eventhubs-binder/pom.xml#L32-L42.

**Comment by pdp5210** [comment]
just realized the example shared was azure-spring-cloud sample, do you have an example where i can use azure event hub or azure event hub with kafka under azure spring boot samples. My example runs on AKS on a container and i dont need azure spring cloud rather a spring boot sample with eventhub.

https://github.com/Azure/azure-sdk-for-java/tree/azure-spring-cloud-stream-binder-servicebus-queue_2.1.0/sdk/spring/azure-spring-boot-samples

Appreciate your help.

Thanks,
Pradeep

**Comment by pdp5210** [comment]
I'm assuming below examples should work out fine with latest functional code similar to Spring cloud stream example

https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-cloud-stream-binder-java-app-azure-event-hub#add-sample-code-to-implement-basic-event-hub-functionality

https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-cloud-stream-binder-java-app-kafka-azure-event-hub

**Comment by yiliuTo** [comment]
Closing this issure because no response from the customer.
