### ISSUE TITLE
[BUG] UnrecognizedPropertyException thrown while attaching disk to VM and while creating VM from marketplaceimage

### ISSUE THREAD

**Issue by Prudvidhard** [Azure/azure-sdk-for-java#18732]
**Describe the bug**
We observed UnrecognizedPropertyException few times on azure API calls. Please let us why do we see this exception.

***Exception or Stack Trace***
java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "evaluationDetails" (class com.microsoft.azure.PolicyViolationErrorInfo), not marked as ignorable (13 known properties: "policyDefinitionId", "policyDefinitionReferenceId", "policyDefinitionDisplayName", "policyAssignmentParameters", "policyAssignmentName", "policySetDefinitionName", "policyDefinitionName", "policyAssignmentScope", "policyDefinitionEffect", "policyAssignmentId", "policySetDefinitionId", "policySetDefinitionDisplayName", "policyAssignmentDisplayName"]) 

at [Source: (String)"{"policyDefinitionDisplayName":"Allowed virtual machine size SKUs","evaluationDetails":{"evaluatedExpressions":[{"result":"True","expressionKind":"Field","expression":"type","path":"type","expressionValue":"Microsoft.Compute/virtualMachines","targetValue":"Microsoft.Compute/virtualMachines","operator":"Equals"},{"result":"False","expressionKind":"Field","expression":"Microsoft.Compute/virtualMachines/sku.name","path":"properties.hardwareProfile.vmSize","expressionValue":"Standard_D2s_v3","target"[truncated 680 chars]; line: 1, column: 89] (through reference chain: com.microsoft.azure.CloudError["additionalInfo"]->java.util.ArrayList[0]->com.microsoft.azure.PolicyViolationErrorInfo["evaluationDetails"]) 
at rx.exceptions.Exceptions.propagate(Exceptions.java:57) 
at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:463) 
at rx.observables.BlockingObservable.last(BlockingObservable.java:226) 
at com.microsoft.azure.management.resources.fluentcore.model.implementation.CreatableUpdatableImpl.apply(CreatableUpdatableImpl.java:256) 
at com.microsoft.azure.management.resources.fluentcore.model.implementation.CreatableUpdatableImpl.apply(CreatableUpdatableImpl.java:33) 

at [Source: (String)"{"policyDefinitionDisplayName":"Allowed virtual machine size SKUs","evaluationDetails":{"evaluatedExpressions":[{"result":"True","expressionKind":"Field","expression":"type","path":"type","expressionValue":"Microsoft.Compute/virtualMachines","targetValue":"Microsoft.Compute/virtualMachines","operator":"Equals"},{"result":"False","expressionKind":"Field","expression":"Microsoft.Compute/virtualMachines/sku.name","path":"properties.hardwareProfile.vmSize","expressionValue":"Standard_D2s_v3","target"[truncated 680 chars]; line: 1, column: 89] (through reference chain: com.microsoft.azure.CloudError["additionalInfo"]->java.util.ArrayList[0]->com.microsoft.azure.PolicyViolationErrorInfo["evaluationDetails"])
		at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
		at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:840)
		at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1179)
		at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1592)
		at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1570)
		at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:294)
		at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4202)
		at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3205)
		at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3173)
		at com.microsoft.azure.PolicyViolation.<init>(PolicyViolation.java:38)
		at com.microsoft.azure.serializer.TypedErrorInfoDeserializer.deserialize(TypedErrorInfoDeserializer.java:61)
		at com.microsoft.azure.serializer.TypedErrorInfoDeserializer.deserialize(TypedErrorInfoDeserializer.java:24)
		at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286)
		at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
		at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
		at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138)
		at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
		at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
		at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
		at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4173)
		at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2467)
		at com.fasterxml.jackson.core.JsonParser.readValueAs(JsonParser.java:1765)
		at com.microsoft.azure.serializer.CloudErrorDeserializer.deserialize(CloudErrorDeserializer.java:65)
		at com.microsoft.azure.serializer.CloudErrorDeserializer.deserialize(CloudErrorDeserializer.java:24)
		at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4202)
		at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3205)
		at com.microsoft.rest.serializer.JacksonAdapter.deserialize(JacksonAdapter.java:137)
		at com.microsoft.azure.management.resources.fluentcore.utils.ProviderRegistrationInterceptor.intercept(ProviderRegistrationInterceptor.java:44)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
		at com.microsoft.rest.interceptors.BaseUrlHandler.intercept(BaseUrlHandler.java:43)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
		at com.microsoft.rest.interceptors.RequestIdHeaderInterceptor.intercept(RequestIdHeaderInterceptor.java:29)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
		at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:257)
		at okhttp3.RealCall.execute(RealCall.java:93)
		at retrofit2.OkHttpCall.execute(OkHttpCall.java:186)
		at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:40)
		at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:24)
		at rx.Observable.unsafeSubscribe(Observable.java:10327)
		at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
		at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
		at rx.Observable.unsafeSubscribe(Observable.java:10327)
		at rx.internal.operators.OnSubscribeSingle.call(OnSubscribeSingle.java:81)
		at rx.internal.operators.OnSubscribeSingle.call(OnSubscribeSingle.java:27)
		at rx.internal.operators.SingleToObservable.call(SingleToObservable.java:39)
		at rx.internal.operators.SingleToObservable.call(SingleToObservable.java:27)
		at rx.Observable.unsafeSubscribe(Observable.java:10327)
		at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
		at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
		at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
		at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
		at rx.Observable.unsafeSubscribe(Observable.java:10327)
		at rx.internal.operators.DeferredScalarSubscriber.subscribeTo(DeferredScalarSubscriber.java:153)
		at rx.internal.operators.OnSubscribeTakeLastOne.call(OnSubscribeTakeLastOne.java:32)
		at rx.internal.operators.OnSubscribeTakeLastOne.call(OnSubscribeTakeLastOne.java:22)
		at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
		at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
		at rx.Observable.unsafeSubscribe(Observable.java:10327)
		at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
		at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
		at rx.Observable.unsafeSubscribe(Observable.java:10327)
		at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
		at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
		at rx.Observable.unsafeSubscribe(Observable.java:10327)
		at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
		at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
		at rx.Observable.unsafeSubscribe(Observable.java:10327)
		at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
		at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
		at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
		... 3 more

**To Reproduce**
This is not occurring on every API call. It is occurring rarely. We saw it few times on 15th Jan, 17th Jan

***Code Snippet***
VirtualMachine machine = azureInstance.virtualMachines().getById(vmUuid);
Below line caused exception
machine.inner().storageProfile().osDisk().withName(diskProperName).managedDisk().withId(disk.id());

**Expected behavior**
No exception

**Screenshots**
NA

**Setup (please complete the following information):**
 - OS: [e.g. iOS] - On our production environment
 - IDE : [e.g. IntelliJ] NA
 - Version of the Library used - com.microsoft.azure.azure - 1.33.0

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by joshfree** [comment]
Thanks for filing this github issue, @Prudvidhard.  @yungezz could you please help route this on the `Mgmt` team?

**Comment by yungezz** [comment]
hi @xccc-msft could you pls help?

**Comment by xccc-msft** [comment]
@Prudvidhard It looks this has been fixed [Azure/azure-libraries-for-java#1305](https://github.com/Azure/azure-libraries-for-java/pull/1305). The root cause would be that some responses with CloudError are not in JSON format. Could you please try to upgrade latest version? Thanks.
