### ISSUE TITLE
Concurrent modification exception when querying Virtual Machines using Azure fluent APIs

### ISSUE THREAD

**Issue by luijar** [Azure/azure-sdk-for-java#1877]
The following code to query for virtual machines under a subscription:

`
Azure.authenticate(atc).withDefaultSubscription().virtualMachines().list().stream();
`

Yields a Concurrent modification exception: 

`
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at com.microsoft.azure.PagedList$ListItr.next(PagedList.java:170)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
`

This started to occur after I upgraded to 1.1.2 of the Java Azure SDK. We're using Java 8

**Comment by LinaKorn** [comment]
We are using java 8 and Azure SDK 0.9.7 and we have the same problem [NPE and ConcurrentModificationException during working with one client (ComputeManagementClient/ResourceManagementClient/StorageManagementClient/)](https://github.com/Azure/azure-sdk-for-java/issues/1782)

**Comment by martinsawicki** [comment]
Since the SDK is built against Java 7, its ability to work with Java 8's stream is not tested nor designed for.
When Java 8 becomes the min pre-req for the SDK at some point in the future, this should just work. Not sure about the timeline at this point though.

**Comment by igolikov** [comment]
That doesn't look like Java 8 issue (and how it may be). The exception says that collection was modified during iteration in the stream. The Same Exception may occur during using old-style iterators.

**Comment by anuchandy** [comment]
@igolikov, there is similar question that @ImranBijapuri raised [here](https://github.com/Azure/azure-sdk-for-java/issues/1942), I provided a workaround there. Please take a look.

**Comment by anuchandy** [comment]
Runtime with fix has been released v1.1.1 https://github.com/Azure/autorest-clientruntime-for-java/tree/v1.1.1
