### ISSUE TITLE
[BUG] Can not upload/download file after change to new Azure File Share client library for Java

### ISSUE THREAD

**Issue by chaien0609** [Azure/azure-sdk-for-java#18802]
**Describe the bug**
Call uploadFromFile() or downloadToFile() method from ShareFileClient returns in error as:
java.lang.NoSuchMethodError: 'reactor.core.publisher.Mono reactor.core.publisher.Mono.retry(long, java.util.function.Predicate)'

***Exception or Stack Trace***
```
java.lang.NoSuchMethodError: 'reactor.core.publisher.Mono reactor.core.publisher.Mono.retry(long, java.util.function.Predicate)'
	at com.azure.storage.file.share.ShareFileAsyncClient.lambda$uploadFromFile$32(ShareFileAsyncClient.java:1538)
ShareFileAsyncClient.java:1538
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:385)
FluxFlatMap.java:385
	at reactor.core.publisher.FluxIterable$IterableSubscription.slowPath(FluxIterable.java:270)
FluxIterable.java:270
	at reactor.core.publisher.FluxIterable$IterableSubscription.request(FluxIterable.java:228)
FluxIterable.java:228
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onSubscribe(FluxFlatMap.java:370)
FluxFlatMap.java:370
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:164)
FluxIterable.java:164
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:86)
FluxIterable.java:86
	at reactor.core.publisher.MonoFromFluxOperator.subscribe(MonoFromFluxOperator.java:81)
MonoFromFluxOperator.java:81
	at reactor.core.publisher.MonoUsing.subscribe(MonoUsing.java:109)
MonoUsing.java:109
	at reactor.core.publisher.Mono.subscribe(Mono.java:4046)
Mono.java:4046
	at reactor.core.publisher.Mono.block(Mono.java:1702)
Mono.java:1702
	at com.azure.storage.file.share.ShareFileClient.uploadFromFile(ShareFileClient.java:1181)
ShareFileClient.java:1181
	at com.azure.storage.file.share.ShareFileClient.uploadFromFile(ShareFileClient.java:1160)
ShareFileClient.java:1160
```

***Code Snippet***
```java
File[] files = dir.listFiles();
for (File file : files) {
    if (file.isDirectory()) {
        ShareDirectoryClient subDir = uploadDir.getSubdirectoryClient(file.getName());
        if (!subDir.exists().booleanValue()) {
            subDir.create();
        }
        uploadFromDirectory(file, subDir, true);
        continue;
    }

    ShareFileClient uploadFile = uploadDir.getFileClient(file.getName());
    uploadFile.uploadFromFile(file.getPath());
    if (file.exists() && !file.delete()) {
        log.error("Can not delete file {} after uploading.", file.getName());
    }
}
```

**Comment by alzimmermsft** [comment]
Hi @chaien0609, thank you for filing this issue.

Could you include a `dependency:tree` resolution for your application? Or, is your application using `reactor-core` `3.4.0` or above or Spring Framework `2.4.0` or above? This error indicates to me that `reactor-core` is being resolved to `3.4.0` while the Azure SDKs are currently on their `3.3.x` track and this method was removed between the minor versions.

**Comment by chaien0609** [comment]
I'm so sorry for this lately reply.
I would like to send you dependency:tree output as below:
```
[INFO] +- org.apache.commons:commons-lang3:jar:3.0:compile
[INFO] +- org.springframework.boot:spring-boot-starter-batch:jar:2.4.0:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter:jar:2.4.0:compile
[INFO] |  |  +- org.springframework.boot:spring-boot-starter-logging:jar:2.4.0:compile
[INFO] |  |  |  +- ch.qos.logback:logback-classic:jar:1.2.3:compile
[INFO] |  |  |  |  \- ch.qos.logback:logback-core:jar:1.2.3:compile
[INFO] |  |  |  +- org.apache.logging.log4j:log4j-to-slf4j:jar:2.13.3:compile
[INFO] |  |  |  |  \- org.apache.logging.log4j:log4j-api:jar:2.13.3:compile
[INFO] |  |  |  \- org.slf4j:jul-to-slf4j:jar:1.7.30:compile
[INFO] |  |  +- jakarta.annotation:jakarta.annotation-api:jar:1.3.5:compile
[INFO] |  |  \- org.yaml:snakeyaml:jar:1.27:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-jdbc:jar:2.4.0:compile
[INFO] |  |  \- com.zaxxer:HikariCP:jar:3.4.5:compile
[INFO] |  \- org.springframework.batch:spring-batch-core:jar:4.3.0:compile
[INFO] |     +- com.fasterxml.jackson.core:jackson-databind:jar:2.11.3:compile
[INFO] |     |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.11.3:compile
[INFO] |     |  \- com.fasterxml.jackson.core:jackson-core:jar:2.11.3:compile
[INFO] |     +- io.micrometer:micrometer-core:jar:1.6.1:compile
[INFO] |     |  +- org.hdrhistogram:HdrHistogram:jar:2.1.12:compile
[INFO] |     |  \- org.latencyutils:LatencyUtils:jar:2.0.3:runtime
[INFO] |     +- javax.batch:javax.batch-api:jar:1.0:compile
[INFO] |     +- org.codehaus.jettison:jettison:jar:1.2:compile
[INFO] |     +- org.springframework.batch:spring-batch-infrastructure:jar:4.3.0:compile
[INFO] |     |  \- org.springframework.retry:spring-retry:jar:1.3.0:compile
[INFO] |     |     \- javax.annotation:javax.annotation-api:jar:1.3.2:compile
[INFO] |     +- org.springframework:spring-aop:jar:5.3.1:compile
[INFO] |     +- org.springframework:spring-beans:jar:5.3.1:compile
[INFO] |     +- org.springframework:spring-context:jar:5.3.1:compile
[INFO] |     \- org.springframework:spring-tx:jar:5.3.1:compile
[INFO] +- org.springframework.boot:spring-boot-starter-web:jar:2.4.0:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-json:jar:2.4.0:compile
[INFO] |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jdk8:jar:2.11.3:compile
[INFO] |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.11.3:compile
[INFO] |  |  \- com.fasterxml.jackson.module:jackson-module-parameter-names:jar:2.11.3:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-tomcat:jar:2.4.0:compile
[INFO] |  |  +- org.apache.tomcat.embed:tomcat-embed-core:jar:9.0.39:compile
[INFO] |  |  +- org.glassfish:jakarta.el:jar:3.0.3:compile
[INFO] |  |  \- org.apache.tomcat.embed:tomcat-embed-websocket:jar:9.0.39:compile
[INFO] |  +- org.springframework:spring-web:jar:5.3.1:compile
[INFO] |  \- org.springframework:spring-webmvc:jar:5.3.1:compile
[INFO] |     \- org.springframework:spring-expression:jar:5.3.1:compile
[INFO] +- org.springframework.boot:spring-boot-devtools:jar:2.4.0:runtime (optional)
[INFO] |  +- org.springframework.boot:spring-boot:jar:2.4.0:compile
[INFO] |  \- org.springframework.boot:spring-boot-autoconfigure:jar:2.4.0:compile
[INFO] +- com.h2database:h2:jar:1.4.200:runtime
[INFO] +- org.projectlombok:lombok:jar:1.18.16:compile (optional) 
[INFO] +- org.springframework.boot:spring-boot-starter-test:jar:2.4.0:test
[INFO] |  +- org.springframework.boot:spring-boot-test:jar:2.4.0:test
[INFO] |  +- org.springframework.boot:spring-boot-test-autoconfigure:jar:2.4.0:test
[INFO] |  +- com.jayway.jsonpath:json-path:jar:2.4.0:test
[INFO] |  |  +- net.minidev:json-smart:jar:2.3:test
[INFO] |  |  |  \- net.minidev:accessors-smart:jar:1.2:test
[INFO] |  |  |     \- org.ow2.asm:asm:jar:5.0.4:test
[INFO] |  |  \- org.slf4j:slf4j-api:jar:1.7.30:compile
[INFO] |  +- jakarta.xml.bind:jakarta.xml.bind-api:jar:2.3.3:compile
[INFO] |  |  \- jakarta.activation:jakarta.activation-api:jar:1.2.2:compile
[INFO] |  +- org.assertj:assertj-core:jar:3.18.1:test
[INFO] |  +- org.hamcrest:hamcrest:jar:2.2:test
[INFO] |  +- org.junit.jupiter:junit-jupiter:jar:5.7.0:test
[INFO] |  |  +- org.junit.jupiter:junit-jupiter-api:jar:5.7.0:test
[INFO] |  |  |  +- org.apiguardian:apiguardian-api:jar:1.1.0:test
[INFO] |  |  |  +- org.opentest4j:opentest4j:jar:1.2.0:test
[INFO] |  |  |  \- org.junit.platform:junit-platform-commons:jar:1.7.0:test
[INFO] |  |  +- org.junit.jupiter:junit-jupiter-params:jar:5.7.0:test
[INFO] |  |  \- org.junit.jupiter:junit-jupiter-engine:jar:5.7.0:test
[INFO] |  |     \- org.junit.platform:junit-platform-engine:jar:1.7.0:test
[INFO] |  +- org.mockito:mockito-core:jar:3.6.0:test
[INFO] |  |  +- net.bytebuddy:byte-buddy:jar:1.10.18:test
[INFO] |  |  +- net.bytebuddy:byte-buddy-agent:jar:1.10.18:test
[INFO] |  |  \- org.objenesis:objenesis:jar:3.1:test
[INFO] |  +- org.mockito:mockito-junit-jupiter:jar:3.6.0:test
[INFO] |  +- org.skyscreamer:jsonassert:jar:1.5.0:test
[INFO] |  |  \- com.vaadin.external.google:android-json:jar:0.0.20131108.vaadin1:test
[INFO] |  +- org.springframework:spring-core:jar:5.3.1:compile
[INFO] |  |  \- org.springframework:spring-jcl:jar:5.3.1:compile
[INFO] |  +- org.springframework:spring-test:jar:5.3.1:test
[INFO] |  \- org.xmlunit:xmlunit-core:jar:2.7.0:test
[INFO] +- org.springframework.batch:spring-batch-test:jar:4.3.0:test
[INFO] |  +- junit:junit:jar:4.13.1:test
[INFO] |  |  \- org.hamcrest:hamcrest-core:jar:2.2:test
[INFO] |  \- org.springframework:spring-jdbc:jar:5.3.1:compile
[INFO] +- org.springframework.boot:spring-boot-starter-mail:jar:2.4.0:compile
[INFO] |  +- org.springframework:spring-context-support:jar:5.3.1:compile
[INFO] |  \- com.sun.mail:jakarta.mail:jar:1.6.5:compile
[INFO] |     \- com.sun.activation:jakarta.activation:jar:1.2.2:compile
[INFO] +- com.azure:azure-storage-file-share:jar:12.8.0:compile
[INFO] |  \- com.azure:azure-storage-common:jar:12.10.0:compile
[INFO] |     +- com.azure:azure-core:jar:1.12.0:compile
[INFO] |     |  +- com.fasterxml.jackson.dataformat:jackson-dataformat-xml:jar:2.11.3:compile
[INFO] |     |  |  +- com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:2.11.3:compile
[INFO] |     |  |  +- org.codehaus.woodstox:stax2-api:jar:4.2.1:compile
[INFO] |     |  |  \- com.fasterxml.woodstox:woodstox-core:jar:6.2.1:compile
[INFO] |     |  +- io.projectreactor:reactor-core:jar:3.4.0:compile
[INFO] |     |  |  \- org.reactivestreams:reactive-streams:jar:1.0.3:compile
[INFO] |     |  \- io.netty:netty-tcnative-boringssl-static:jar:2.0.34.Final:compile
[INFO] |     \- com.azure:azure-core-http-netty:jar:1.7.1:compile
[INFO] |        +- io.netty:netty-handler:jar:4.1.54.Final:compile
[INFO] |        |  +- io.netty:netty-common:jar:4.1.54.Final:compile
[INFO] |        |  +- io.netty:netty-resolver:jar:4.1.54.Final:compile
[INFO] |        |  +- io.netty:netty-transport:jar:4.1.54.Final:compile
[INFO] |        |  \- io.netty:netty-codec:jar:4.1.54.Final:compile
[INFO] |        +- io.netty:netty-handler-proxy:jar:4.1.54.Final:compile
[INFO] |        |  \- io.netty:netty-codec-socks:jar:4.1.54.Final:compile
[INFO] |        +- io.netty:netty-buffer:jar:4.1.54.Final:compile
[INFO] |        +- io.netty:netty-codec-http:jar:4.1.54.Final:compile
[INFO] |        +- io.netty:netty-codec-http2:jar:4.1.54.Final:compile
[INFO] |        +- io.netty:netty-transport-native-unix-common:jar:4.1.54.Final:compile
[INFO] |        +- io.netty:netty-transport-native-epoll:jar:linux-x86_64:4.1.54.Final:compile
[INFO] |        +- io.netty:netty-transport-native-kqueue:jar:osx-x86_64:4.1.54.Final:compile
[INFO] |        \- io.projectreactor.netty:reactor-netty:jar:1.0.1:compile
[INFO] |           +- io.projectreactor.netty:reactor-netty-core:jar:1.0.1:compile
[INFO] |           |  \- io.netty:netty-resolver-dns:jar:4.1.54.Final:compile
[INFO] |           |     \- io.netty:netty-codec-dns:jar:4.1.54.Final:compile
[INFO] |           +- io.projectreactor.netty:reactor-netty-http:jar:1.0.1:compile
[INFO] |           \- io.projectreactor.netty:reactor-netty-http-brave:jar:1.0.1:runtime
[INFO] |              \- io.zipkin.brave:brave-instrumentation-http:jar:5.13.1:runtime
[INFO] |                 \- io.zipkin.brave:brave:jar:5.13.1:runtime
[INFO] |                    \- io.zipkin.reporter2:zipkin-reporter-brave:jar:2.16.0:runtime
[INFO] |                       \- io.zipkin.reporter2:zipkin-reporter:jar:2.16.0:runtime
[INFO] |                          \- io.zipkin.zipkin2:zipkin:jar:2.22.2:runtime
[INFO] +- javax.json:javax.json-api:jar:1.1.4:compile
[INFO] \- org.glassfish:javax.json:jar:1.1:compile
```

I use Spring Framework 2.4.0 (reactor-core is 3.4.0 as dependency) and azure-storage-file-share 12.8.0.

**Comment by rickle-msft** [comment]
@chaien0609 Could you try pinning your reactor core dependency to 3.3.x to see if that resolves the issue?

Although, @alzimmermsft it looks like azure-core is bringing in reactor-core 3.4.0?

**Comment by chaien0609** [comment]
@rickle-msft thank you for your response.
I have tried to change reactor core to 3.3.14.RELEASE and below but it ran into new issue as below:
```
	at reactor.netty.resources.PooledConnectionProvider$PoolFactory.newPool(PooledConnectionProvider.java:250)
PooledConnectionProvider.java:250
	at reactor.netty.resources.DefaultPooledConnectionProvider$PooledConnectionAllocator.<init>(DefaultPooledConnectionProvider.java:517)
DefaultPooledConnectionProvider.java:517
	at reactor.netty.resources.DefaultPooledConnectionProvider.createPool(DefaultPooledConnectionProvider.java:98)
DefaultPooledConnectionProvider.java:98
	at reactor.netty.resources.PooledConnectionProvider.lambda$acquire$0(PooledConnectionProvider.java:104)
PooledConnectionProvider.java:104
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
ConcurrentHashMap.java:1705
	at reactor.netty.resources.PooledConnectionProvider.lambda$acquire$1(PooledConnectionProvider.java:99)
PooledConnectionProvider.java:99
	at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:57)
MonoCreate.java:57
	at reactor.netty.http.client.HttpClientConnect$MonoHttpConnect.lambda$subscribe$0(HttpClientConnect.java:260)
HttpClientConnect.java:260
	at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:57)
MonoCreate.java:57
	at reactor.core.publisher.FluxRetryWhen.subscribe(FluxRetryWhen.java:79)
FluxRetryWhen.java:79
	at reactor.core.publisher.MonoRetryWhen.subscribeOrReturn(MonoRetryWhen.java:46)
MonoRetryWhen.java:46
```

It seem that reactor.util.context.ContextView is added later on reactor-core 3.4.0.

I would like to provide pom.xml's dependencies as below also:
```
<dependencies>
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-lang3</artifactId>
			<version>3.0</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-batch</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-devtools</artifactId>
			<scope>runtime</scope>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>com.h2database</groupId>
			<artifactId>h2</artifactId>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.batch</groupId>
			<artifactId>spring-batch-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-mail</artifactId>
		</dependency>
		<dependency>
			<groupId>com.azure</groupId>
			<artifactId>azure-storage-file-share</artifactId>
			<version>12.8.0</version>
		</dependency>
		<dependency>
			<groupId>io.projectreactor</groupId>
			<artifactId>reactor-core</artifactId>
			<version>3.3.14.RELEASE</version>
		</dependency>
		<dependency>
			<groupId>javax.json</groupId>
			<artifactId>javax.json-api</artifactId>
			<version>1.1.4</version>
		</dependency>
		<dependency>
			<groupId>org.glassfish</groupId>
			<artifactId>javax.json</artifactId>
			<version>1.1</version>
		</dependency>
	</dependencies>
```

**Comment by rickle-msft** [comment]
@chaien0609 Thank you for sharing this information. @alzimmermsft it seems 3.3.x and 3.4.x both present a NoClassDefError. Any thoughts on how to resolve this?

**Comment by alzimmermsft** [comment]
Unfortunately, this is a case where the Azure SDKs haven't been upgraded to support Spring Framework 2.4. This is actively being worked on and should hopefully be resolved in a few weeks.

For additional background context, Spring Framework 2.4 also has another major breaking change from Spring Framework 2.3 with upgrading `reactor-netty` from `0.9.x` to `1.0.x` which contains backwards incompatible changes.

**Comment by gapra-msft** [comment]
@chaien0609 The recent azure-storage releases should be compatible with Spring 2.4 as we updated a number of dependencies in that release. Could you please try that and let us know if that helps resolve your issue?

I believe you are using azure-storage-file-share. Here is a link to the latest package that released last week.  https://search.maven.org/artifact/com.azure/azure-storage-file-share/12.9.0/jar
