### ISSUE TITLE
[BUG] OOM issue when using com.azure.azure-storage-file-datalake-12.3.0.jar

### ISSUE THREAD

**Issue by suncityxmu** [Azure/azure-sdk-for-java#18893]
**Describe the bug**
This is a customer report issue.

Informatica is using a customized version Java sdk in their production, recently they want to use official sdk to replace the old sdk.

Their performance team found one issue when uploading a big file (7G) file with option 8MB block size and 64M max heap, there is OOM exception, the option 2MB block size with 64M max heap works fine.

Dump file:

https://yangshendevops002.blob.core.windows.net/forupload/ADLS_G2_OOM%20(1).zip?sp=r&st=2021-02-01T03:12:40Z&se=2022-02-01T11:12:40Z&spr=https&sv=2019-12-12&sr=b&sig=Zjx6zX2DvHyHovLxin%2Bu8yASrtMBfzKc5mPEcIdSdFY%3D

The thread java.lang.Thread @ 0xfcd63e90 Thread-16 keeps local variables with total size 6,996,624 (13.55%) bytes.
The memory is accumulated in one instance of "okio.Segment", loaded by "sun.misc.Launcher$AppClassLoader @ 0xfc31f140", which occupies 6,928,320 (13.42%) bytes.
The stacktrace of this Thread is available. See stacktrace. See stacktrace with involved local variables.

Keywords
okio.Segment
sun.misc.Launcher$AppClassLoader @ 0xfc31f140
com.azure.core.util.FluxUtil$FileReadFlux$FileReadSubscription.doRead()V
FluxUtil.java:601
com.azure.core.util.FluxUtil$FileReadFlux$FileReadSubscription.drain()V
FluxUtil.java:588
com.azure.core.util.FluxUtil$FileReadFlux$FileReadSubscription.completed(Ljava/lang/Integer;Ljava/nio/ByteBuffer;)V
FluxUtil.java:532
com.azure.core.util.FluxUtil$FileReadFlux$FileReadSubscription.completed(Ljava/lang/Object;Ljava/lang/Object;)V
FluxUtil.java:455
sun.nio.ch.Invoker.invokeUnchecked(Ljava/nio/channels/CompletionHandler;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Throwable;)V
Unknow

Thread Stack

Thread-16
  at java.lang.OutOfMemoryError.<init>()V (Unknown Source)
  at java.nio.HeapByteBuffer.<init>(II)V (Unknown Source)
  at java.nio.ByteBuffer.allocate(I)Ljava/nio/ByteBuffer; (Unknown Source)
  at com.azure.core.util.FluxUtil$FileReadFlux$FileReadSubscription.doRead()V (FluxUtil.java:601)
  at com.azure.core.util.FluxUtil$FileReadFlux$FileReadSubscription.drain()V (FluxUtil.java:588)
  at com.azure.core.util.FluxUtil$FileReadFlux$FileReadSubscription.completed(Ljava/lang/Integer;Ljava/nio/ByteBuffer;)V (FluxUtil.java:532)
  at com.azure.core.util.FluxUtil$FileReadFlux$FileReadSubscription.completed(Ljava/lang/Object;Ljava/lang/Object;)V (FluxUtil.java:455)
  at sun.nio.ch.Invoker.invokeUnchecked(Ljava/nio/channels/CompletionHandler;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Throwable;)V (Unknown Source)
  at sun.nio.ch.Invoker$2.run()V (Unknown Source)
  at sun.nio.ch.AsynchronousChannelGroupImpl$1.run()V (Unknown Source)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(Ljava/util/concurrent/ThreadPoolExecutor$Worker;)V (Unknown Source)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run()V (Unknown Source)
  at java.lang.Thread.run()V (Unknown Source)

**Setup (please complete the following information):**
 - OS: Linux
 - Version of the Library used : com.azure.azure-storage-file-datalake-12.3.0

**Comment by rickle-msft** [comment]
Hi, @suncityxmu. Thank you for opening this issue. A 64mb heap is pretty small and if the block size is 8mb, we'll allocate two blocks which is, 16mb. And depending on the upload method used, we may have to do another copy of the data as well, so I'm not surprised about the oom with those numbers.

It seems the customer found a configuration that does work for them, though. Is there a reason why that configuration is insufficient?

**Comment by suncityxmu** [comment]
If using 2MB block size, there will be limitation of the file size because the max block size is 50000, so the max file size will be limited to 100G.

The 64mb max heap is the setting for Informatica customer with the custom Java sdk, it is better for them to keep this value.

Any suggestion for the value from product group? For example,

128MB max heap with 8MB block size
or 256MB max heap with 16MB block size?

**Comment by suncityxmu** [comment]
I tried to use the sample code to call stageBlock but meet one exception, do you know what header is missing?

Exception in thread "main" com.azure.storage.blob.models.BlobStorageException: Status code 400, "{"error":{"code":"MissingRequiredHeader","message":"An HTTP header that's mandatory for this request is not specified.\nRequestId:26214473-501f-0084-4aea-f9709a000000\nTime:2021-02-03T05:05:55.6417612Z"}}"
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at com.azure.core.http.rest.RestProxy.instantiateUnexpectedException(RestProxy.java:337)
	at com.azure.core.http.rest.RestProxy.lambda$ensureExpectedStatus$5(RestProxy.java:378)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:118)

**Sample Code:**

        File largeFile = createTempEmptyFile(filename);
        long fileSize = 1 * 1024 * 1024 * 1024L;
        
        BlockBlobClient client = new SpecializedBlobClientBuilder().endpoint(endPoint).credential(credential).containerName("dir1").blobName("1.bin").buildBlockBlobClient();
        InputStream inputStream = new FileInputStream(largeFile);
        BufferedInputStream str = new BufferedInputStream(inputStream);
        
        client.stageBlock("YmxvY2tpZDEyMw==", str, fileSize);
        client.commitBlockList(Collections.singletonList("YmxvY2tpZDEyMw==")).getLastModified();

**Comment by rickle-msft** [comment]
I'm not able to tell from what you've shared here. I would suggest either looking at the outgoing request (either via logs or setting a breakpoint in the code) and comparing the set headers to the required ones [here](https://docs.microsoft.com/en-us/rest/api/storageservices/put-block) and [here](https://docs.microsoft.com/en-us/rest/api/storageservices/put-block-list). Or if you catch the exception, usually (though I could be wrong here), the extended information should tell you what header is missing.

**Comment by suncityxmu** [comment]
Thanks rickle, this issue can be closed.
