### ISSUE TITLE
Getting error while executing MVN Project

### ISSUE THREAD

**Issue by sbhuttan** [Azure/azure-sdk-for-java#19021]
I am getting following error when executing the project. Project compiles successfully. While debugging it is able to authenticate against Azure and get reference to azure variable. The error occurs while executing Create VM method. 
I have verified, all the variables provided are correct. 

Here is the error  - 
```
Exception in thread "RxIoScheduler-2" java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:59)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchMethodError: com.fasterxml.jackson.core.JsonGenerator.writeStartObject(Ljava/lang/Object;)V
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:151)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1396)
	at com.fasterxml.jackson.databind.ObjectWriter._configAndWriteValue(ObjectWriter.java:1120)
	at com.fasterxml.jackson.databind.ObjectWriter.writeValueAsBytes(ObjectWriter.java:1017)
	at com.microsoft.rest.serializer.JacksonConverterFactory$JacksonRequestBodyConverter.convert(JacksonConverterFactory.java:78)
	at com.microsoft.rest.serializer.JacksonConverterFactory$JacksonRequestBodyConverter.convert(JacksonConverterFactory.java:69)
	at retrofit2.ParameterHandler$Body.apply(ParameterHandler.java:355)
	at retrofit2.ServiceMethod.toCall(ServiceMethod.java:110)
	at retrofit2.OkHttpCall.createRawCall(OkHttpCall.java:184)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:167)
	at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:40)
	at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:24)
	at rx.Observable.unsafeSubscribe(Observable.java:10142)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10142)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10142)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10142)
	at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99a30d24-e429-8543-0ae6-5a2178a2f205
* Version Independent ID: 45408a1b-6fb6-926c-1dd2-1a40811731c4
* Content: [Get started with the Azure libraries for Java](https://docs.microsoft.com/en-us/java/azure/java-sdk-azure-get-started?view=azure-java-stable)
* Content Source: [docs-ref-conceptual/java-sdk-azure-get-started.md](https://github.com/Azure/azure-docs-sdk-java/blob/master/docs-ref-conceptual/java-sdk-azure-get-started.md)
* Service: **multiple**
* Product: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by joshfree** [comment]
@yungezz could you please assist in following up on this old samples issue that was filed in the docs repo (just ported to azure-sdk-for-java).  Thank you

**Comment by yungezz** [comment]
thanks @joshfree . hi @weidongxu-microsoft could you pls help here? thanks.

**Comment by weidongxu-microsoft** [comment]
@sbhuttan 

This is likely caused by incompatible jackson dependency in your maven. Please try fix jackson version to 2.11.3 (if you have other line of dependency to jackson).
Ref: https://stackoverflow.com/questions/40051253/java-lang-nosuchmethoderror-using-jackson-core-streaming-api

**Comment by weidongxu-microsoft** [comment]
The content on https://docs.microsoft.com/en-us/azure/developer/java/sdk/get-started?view=azure-java-stable is updated to use new generation of Azure SDKs.

**Comment by weidongxu-microsoft** [comment]
@haolingdong-msft
Please update https://docs.microsoft.com/en-us/azure/developer/java/sdk/get-started?view=azure-java-stable to use 2.6.0 SDK and latest azure-identity (1.3.2).

Read https://aka.ms/azsdk/java/mgmt first.

**Comment by haolingdong-msft** [comment]
> @haolingdong-msft
> Please update https://docs.microsoft.com/en-us/azure/developer/java/sdk/get-started?view=azure-java-stable to use 2.6.0 SDK and latest azure-identity (1.3.2).
> Meanwhile try out the few samples there.
> 
> Read https://aka.ms/azsdk/java/mgmt first.

The content of document https://docs.microsoft.com/en-us/azure/developer/java/sdk/get-started?view=azure-java-stable is updated based on below:
1. update pom.xml in 'Create a new Maven project' section: update azure-identity and azure-resourcemanager lib version, add version for 'exec-maven-plugin' to avoid maven missing version exception
2. update command to browse webapp in 'Deploy a web app from a GitHub repo' section
3. update example code to avoid compile error
