### ISSUE TITLE
NPE in SqlDatabaseOperationsImpl.listBySqlServer

### ISSUE THREAD

**Issue by igolikov** [Azure/azure-sdk-for-java#19055]
Hi, sporadically NPE happens here (pretty rare), there is no way to reproduce 

```
 java.lang.NullPointerException
     at com.microsoft.azure.management.sql.implementation.SqlDatabaseOperationsImpl.listBySqlServer(SqlDatabaseOperationsImpl.java:162)
     at com.microsoft.azure.management.sql.implementation.SqlDatabaseOperationsImpl.list(SqlDatabaseOperationsImpl.java:218)
```
     
 Azure SDK for Java 1.30.0

**Comment by joshfree** [comment]
Thanks for filing this issue @igolikov.  @yungezz could you please assist routing this `Mgmt` plane sdk issue?

**Comment by yungezz** [comment]
thanks Josh. @weidongxu-microsoft could you pls help to take a look? thanks

**Comment by weidongxu-microsoft** [comment]
@igolikov

This would likely caused by a 404 from server response. Track1 SDK cannot distinguish it from empty response. I will add a protection to return empty list in this case.
