### ISSUE TITLE
Sorting and Paging for ReactiveCosmosRepository

### ISSUE THREAD

**Issue by luissalgadofreire** [Azure/azure-sdk-for-java#19138]
I am working with:
* Java 11
* Spring Boot version 2.3.3
* Azure Spring Data Cosmos version 3.3.0 
* ReactiveCosmosRepository

**Situation**

I understand there is support for pagination in **Sync** Spring Data Cosmos DB as per this [sample](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/cosmos/azure-spring-data-cosmos/src/samples/java/com/azure/spring/data/cosmos/PageableRepositoryCodeSnippet.java) and this [tutorial](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/how-to-guides-spring-data-cosmosdb#pagination-and-sorting).

I also understand there is support for pagination using a continuation token in the plain Java Async SDK as per this [page](https://docs.microsoft.com/en-us/azure/developer/java/sdk/pagination#asynchronously-observe-pages-and-individual-elements). Using this, however, requires using two different clients in a spring application: one for async paginated calls and another for the rest.

**Problem**

However, support is restricted to a non-reactive spring repository and to the plain java SDK, as the underlying repository being used in the former is the standard Spring PagingAndSortingRepository:

```
import com.azure.spring.data.cosmos.core.query.CosmosPageRequest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.repository.PagingAndSortingRepository;

import java.util.List;

public class PageableRepositoryCodeSnippet<T> {

    @Autowired
    private PagingAndSortingRepository<T, String> repository;

    private List<T> findAllWithPageSize(int pageSize) {

        final CosmosPageRequest pageRequest = new CosmosPageRequest(0, pageSize, null);
        Page<T> page = repository.findAll(pageRequest); // <-- this would be a blocking call
        List<T> pageContent = page.getContent();
        while (page.hasNext()) {
            Pageable nextPageable = page.nextPageable();
            page = repository.findAll(nextPageable);
            pageContent = page.getContent();
        }
        return pageContent;
    }
}
```

So, no clear support exists for ReactiveCosmosRepository.

**Similar Solution in Spring Data**

As per this stackoverflow accepted [response](https://stackoverflow.com/questions/45924505/is-there-any-way-to-implement-pagination-in-spring-webflux-and-spring-data-react):

> The reactive support in Spring Data does not provide means of a Page return type. Still, the Pageable parameter is supported in method signatures passing on limit and offset to the drivers and therefore the store itself, returning a Flux<T> that emits the range requested.
> 
> ```
> Flux<Person> findByFirstname(String firstname, Pageable pageable);
> ```

As per this [tutorial](https://thepracticaldeveloper.com/full-reactive-stack-2-backend-webflux/), we could have something like this in the repository:

```
package com.thepracticaldeveloper.reactiveweb.repository;

import com.thepracticaldeveloper.reactiveweb.domain.Quote;

import org.springframework.data.domain.Pageable;
import org.springframework.data.repository.reactive.ReactiveSortingRepository;

import reactor.core.publisher.Flux;

public interface QuoteMongoReactiveRepository extends ReactiveSortingRepository<Quote, String> {

    Flux<Quote> findAllByIdNotNullOrderByIdAsc(final Pageable page);
}
```

And then something like this in the controller:

```
package com.thepracticaldeveloper.reactiveweb.controller;

import com.thepracticaldeveloper.reactiveweb.domain.Quote;
import com.thepracticaldeveloper.reactiveweb.repository.QuoteMongoReactiveRepository;
import org.springframework.data.domain.PageRequest;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import reactor.core.publisher.Flux;

import java.time.Duration;

@RestController
public class QuoteReactiveController {

    private static final int DELAY_PER_ITEM_MS = 100;

    private final QuoteMongoReactiveRepository quoteMongoReactiveRepository;

    public QuoteReactiveController(final QuoteMongoReactiveRepository quoteMongoReactiveRepository) {
        this.quoteMongoReactiveRepository = quoteMongoReactiveRepository;
    }

    ...

    @GetMapping("/quotes-reactive-paged")
    public Flux<Quote> getQuoteFlux(final @RequestParam(name = "page") int page,
                                    final @RequestParam(name = "size") int size) {
        return quoteMongoReactiveRepository.findAllByIdNotNullOrderByIdAsc(PageRequest.of(page, size))
                .delayElements(Duration.ofMillis(DELAY_PER_ITEM_MS));
    }

}
```

As stated, the suggestion is to replicate a similar API in ReactiveCosmosRepository providing support for Pageable as with WebFlux ReactiveSortingRepository. 

**Important**: given the potential performance limitations of offset limit as opposed to using a continuation token, perhaps a better alternative would be to adjust the logic of the already mentioned spring data cosmos **sync** solution to a reactive repository using Flux or PagedFlux instead.

**EDIT1**: The more I think about it, it seems the best would be to bring PagedFlux and byPage from the Async Java SDK into ReactiveCosmosRepository, that is, bringing the concept from [here](https://docs.microsoft.com/en-us/azure/developer/java/sdk/pagination#observe-pages) into ReactiveCosmosRepository.

> Observe pages
> 
> The following example shows how the PagedFlux API lets you observe each page asynchronously, again by using a byPage() API and by providing a consumer, error consumer, and a completion consumer.
> 
> ```
> asyncClient.listSecrets().byPage()
>   .subscribe(page -> {
>           System.out.println("Response code: " + page.getStatusCode());
>           System.out.println("Continuation Token: " + page.getContinuationToken());
>           page.getElements().forEach(secret -> System.out.println("Secret value: " + secret))
>       },
>       ex -> System.out.println("Error listing pages with secret: " + ex.getMessage()),
>       () -> System.out.println("Successfully listed all pages with secret"));
> ```

Perhaps allowing a findAll method that returns a PagedFlux instead of a Flux:

```
@NoRepositoryBean
public interface ReactiveCosmosDerivedRepository<T, K> extends ReactiveCosmosRepository<T, K> {

    PagedFlux<T> findAllByIsDeleted(boolean b);

}
```

This would be a very clean and elegant API for paged requests in ReactiveCosmosRepository.

**Alternative**
If there is a different and recommended way to support sorting and pagination with ReactiveCosmosRepository, may I suggest adding it to the documentation just as the example provided for non-reactive repositories.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Description Added
- [X] Expected solution specified

**Comment by nisha-bhatia** [comment]
Thank you for your feedback. Tagging and routing to the team member best able to assist.

**Comment by joshfree** [comment]
@nisha-bhatia should this actually be routed to @kushagraThapar and not @yungezz?

**Comment by kushagraThapar** [comment]
@joshfree - correct, I will look into this, thanks!

**Comment by luissalgadofreire** [comment]
In the meantime, I'm trying to work with [CosmosPagedFlux](https://docs.microsoft.com/en-us/java/api/com.azure.cosmos.util.cosmospagedflux?view=azure-java-stable) by creating custom methods in a persistence adapter that I created to map persistence entities to domain entities.

For normal methods that return a Flux, I do something like:

```
public Flux<D> findAll() {
        return this.reactiveRepository
                .findAllByIsDeleted(false)
                .map(map::toDomain);
}
```

This iterates over the input Flux<E> (of persistence entities) and returns a Flux<D> (of domain entities), using method map.toDomain(entity).

I'm now trying to introduce a CosmosPagedFlux similar to the above but paginated. I wonder, though, if it is possible to receive an input CosmosPagedFlux<D> and produce an output CosmosPagedFlux<E>?

**Comment by kushagraThapar** [comment]
@luissalgadofreire - it is possible to create `CosmosPagedFlux` through existing `CosmosPagedFlux` by using the `handle()` API. 

```
/**
     * Handle for invoking "side-effects" on each FeedResponse returned by CosmosPagedFlux
     *
     * @param feedResponseConsumer handler
     * @return CosmosPagedFlux instance with attached handler
     */
    @Beta(value = Beta.SinceVersion.V4_6_0, warningText = Beta.PREVIEW_SUBJECT_TO_CHANGE_WARNING)
    public CosmosPagedFlux<T> handle(Consumer<FeedResponse<T>> feedResponseConsumer) {
        return new CosmosPagedFlux<T>(this.optionsFluxFunction, feedResponseConsumer);
    }
```
This API was introduced for exactly the same situation that you have mentioned above. 
This API is present on `CosmosPagedFlux` here - https://docs.microsoft.com/en-us/java/api/com.azure.cosmos.util.cosmospagedflux.handle?view=azure-java-stable#com_azure_cosmos_util_CosmosPagedFlux_handle_java_util_function_Consumer_com_azure_cosmos_models_FeedResponse_T___

Regarding your original question, I am looking at it.

**Comment by luissalgadofreire** [comment]
Thanks for the reply @kushagraThapar.

I'm trying to take advantage of the handle() method but without success. An example of its usage would be much appreciated.

**Comment by luissalgadofreire** [comment]
I saw the test cases:

```
@Test(groups = { "simple" }, timeOut = TIMEOUT)
    public void readAllItemsByPageWithCosmosPagedFluxHandler() throws Exception {
        CosmosQueryRequestOptions cosmosQueryRequestOptions = new CosmosQueryRequestOptions();

        CosmosPagedFlux<InternalObjectNode> cosmosPagedFlux =
            cosmosAsyncContainer.readAllItems(cosmosQueryRequestOptions, InternalObjectNode.class);

        AtomicInteger handleCount = new AtomicInteger();
        cosmosPagedFlux = cosmosPagedFlux.handle(feedResponse -> {
            CosmosDiagnostics cosmosDiagnostics = feedResponse.getCosmosDiagnostics();
            if (cosmosDiagnostics != null) {
                handleCount.incrementAndGet();
            }
        });

        AtomicInteger itemCount = new AtomicInteger();
        AtomicInteger feedResponseCount = new AtomicInteger();
        cosmosPagedFlux.byPage().toIterable().forEach(feedResponse -> {
            feedResponseCount.incrementAndGet();
            int size = feedResponse.getResults().size();
            itemCount.addAndGet(size);
        });

        assertThat(handleCount.get() >= 1).isTrue();
        assertThat(handleCount.get()).isEqualTo(feedResponseCount.get());
        assertThat(itemCount.get()).isEqualTo(NUM_OF_ITEMS);
    }
```

It doesn't seem to apply to my needs, though. It doesn't seem to allow for the use case I mentioned. Converting a full CosmosPagedFlux<E> to CosmosPagedFlux<D> in a manner equivalent to the example given for Flux<E> to Flux<D>. I may explore other ways but it would be interesting to be able to use CosmosPagedFlux directly to achieve that goal, which is to allow for entity conversion on the fly in a reactive style.

**Comment by Blackbaud-MikeLueders** [comment]
Supporting this syntax
> Flux<Person> findByFirstname(String firstname, Pageable pageable);
should be very easy - most of the code to support this was recently added to the non-reactive api in this PR https://github.com/Azure/azure-sdk-for-java/pull/19527.  I'm working on something else at the moment but should be able to get this in shortly.

Re: full support for a PagedFlux, I'll leave that to those more familiar with the reactive implementation.

**Comment by kushagraThapar** [comment]
@Blackbaud-MikeLueders - Thanks for the help, that would be great. Support for `Pageable` for reactive API should be enough to unblock most of our customers who have the paging requirements on reactive APIs. 

@luissalgadofreire - as mentioned in other issue regarding `mapPage()` API, let's keep this issue confined to `paging` discussion on reactive API. And we can continue to discuss the mapPage concept on the other issue.

**Comment by luissalgadofreire** [comment]
Agree, @kushagraThapar, thanks.

**Comment by Blackbaud-MikeLueders** [comment]
So I looked into this a bit more and, while I don't think the implementation would be difficult, I'm not sure it's the right thing to do.  The main issue is there is no Page returned so there's no way to pass back the continuation token.  This is not really an issue for something like spring-data-jpa b/c it handles offsets efficiently.  Cosmos does not inherently support an offset, it supports a continuation token.  It works around this and *seems* to support an offset by internally executing the query and paging through the results on the server until the offset is reached and then returns the results, with an increased RU cost relative to the offset size (at least I believe that's what it's doing, please correct me if i'm wrong on this point).  

If clients were to implement offset-based paging with cosmos, they might incur unexpected costs as well as degraded performance, depending on their paging requirements.  My primary concern with implementing this strategy is that it would encourage clients to use cosmos in a way that it is not fundamentally intended to be used.  Cosmos is not intended to be paged in the traditional manner - the results are intended to be streamed (e.g. infinite scroll).  

@kushagraThapar @luissalgadofreire Thoughts?

**Comment by luissalgadofreire** [comment]
@Blackbaud-MikeLueders, agree.

That’s what I was trying to convey. It is possible to use OFFSET LIMIT for pagination but it’s not advised because every new page will increase the offset and cost more than the previous page. I agree that introducing it as out-of-the-box feature may encourage users to use it at an extra cost.

I would say best practice in this case would always be something based on continuation token.

**Comment by kushagraThapar** [comment]
@Blackbaud-MikeLueders @luissalgadofreire - yes that theory is correct, and that is one of the main reasons we don't want clients to pay extra cost for OFFSET and LIMIT query features, as they will drain all the records, and will cost high RUs and degraded performance. 
Continuation token is the best / and only (performance wise) way to go here.

**Comment by kushagraThapar** [comment]
Closing this issue because of no activity. Please re-open it if the issue still exists.

**Comment by MattiNieminen** [comment]
Also interested in this one. What would be the best workaround for now and what is the long term goal?

**Comment by fatagun** [comment]
@MattiNieminen the best work around is not to use cosmosdb. That is what I did. I have figured out pagination and efficient data retrieval with reactive approach. However, there is lack of documentation and examples.

**Comment by kushagraThapar** [comment]
@fatagun / @MattiNieminen  - the reason this was closed is described here - https://github.com/Azure/azure-sdk-for-java/issues/19138#issuecomment-792876105

@fatagun - if you have examples for efficient data retrieval using reactive approach while still supporting pagination using offset, can you please share those? It may help other customer as well, thanks!

**Comment by luissalgadofreire** [comment]
I still think `CosmosPagedFlux` should strive to mirror [PagedFlux](https://docs.microsoft.com/en-us/java/api/com.azure.core.http.rest.pagedflux?view=azure-java-stable) from the Azure Java SDK. It has both `byPage` method for pagination and `mapPage`, important reactive constructs that `CosmosPagedFlux` is missing.

**Comment by kushagraThapar** [comment]
@luissalgadofreire  - I believe so, it should be straightforward to implement. I will try it out sometime next week and will post an update here!

**Comment by trande4884** [comment]
In looking into this more I do not think we can return an object which extends Flux.

I created a basic class:
`public class BasicFlux<T> extends Flux {
    @Override
    public void subscribe(CoreSubscriber coreSubscriber) {

    }
}`

When I try to return this as a type:
`BasicFlux<ReactiveTeacher> findAllByFirstName(String firstName);`

I get the following error:
`java.lang.ClassCastException: class reactor.core.publisher.FluxUsingWhen cannot be cast to class com.azure.spring.data.cosmos.common.BasicFlux (reactor.core.publisher.FluxUsingWhen and com.azure.spring.data.cosmos.common.BasicFlux are in unnamed module of loader 'app')

	at com.sun.proxy.$Proxy77.findAllByFirstName(Unknown Source)
	at com.azure.spring.data.cosmos.repository.integration.ReactiveTeacherRepositoryIT.testFindAllItemsOnePage(ReactiveTeacherRepositoryIT.java:83)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestExecutionCallbacks.evaluate(RunBeforeTestExecutionCallbacks.java:74)
	at org.springframework.test.context.junit4.statements.RunAfterTestExecutionCallbacks.evaluate(RunAfterTestExecutionCallbacks.java:84)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:251)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at com.azure.spring.data.cosmos.AbstractIntegrationTestCollectionManager$1.evaluate(AbstractIntegrationTestCollectionManager.java:122)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)`
