### ISSUE TITLE
Can't instantiate a client when newer version of reactor-netty is on the classpath

### ISSUE THREAD

**Issue by erdinc-gopuff** [Azure/azure-sdk-for-java#19418]
**Describe the bug**
I am working on an app that is using the micronaut framework that brings version 1.0.3 of the reactor-netty jar as a dependency. On this version, the reactor.netty.resources.ConnectionProvider class does not have a "fixed" method any longer. In latest version of HttpClient class in azure-cosmos, it still calls the "fixed" method that is clearly marked as deprecated. It looks like netty folks finally removed this method. If you have version 1.x of reactor-netty on your classpath, you can't initialize the CosmosClient.

***Exception or Stack Trace***
Exception in thread "main" java.lang.NoSuchMethodError: 'reactor.netty.resources.ConnectionProvider reactor.netty.resources.ConnectionProvider.fixed(java.lang.String, int, long, java.time.Duration)'
	at com.azure.cosmos.implementation.http.HttpClient.createFixed(HttpClient.java:56)
	at com.azure.cosmos.implementation.RxDocumentClientImpl.httpClient(RxDocumentClientImpl.java:497)
	at com.azure.cosmos.implementation.RxDocumentClientImpl.<init>(RxDocumentClientImpl.java:341)
	at com.azure.cosmos.implementation.RxDocumentClientImpl.<init>(RxDocumentClientImpl.java:214)
	at com.azure.cosmos.implementation.RxDocumentClientImpl.<init>(RxDocumentClientImpl.java:198)
	at com.azure.cosmos.implementation.AsyncDocumentClient$Builder.build(AsyncDocumentClient.java:216)
	at com.azure.cosmos.CosmosAsyncClient.<init>(CosmosAsyncClient.java:104)
	at com.azure.cosmos.CosmosClientBuilder.buildAsyncClient(CosmosClientBuilder.java:729)

**To Reproduce**
Add a 1.x version of reactor-netty-core in the classpath

**Comment by erdinc-gopuff** [comment]
The offending line is below:
https://github.com/Azure/azure-sdk-for-java/blob/c3d44f7f90dbd0d03c4913e4f87dfef386440fd7/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/http/HttpClient.java#L56

The call to this deprecated method is no longer supported.

**Comment by kushagraThapar** [comment]
@erdinc-gopuff - We are currently in works of supporting new major versions of reactor-core and reactor-netty, we plan to release updated SDK in March.
