### ISSUE TITLE
Methods marked as Async are blocking

### ISSUE THREAD

**Issue by asavov** [Azure/azure-sdk-for-java#1956]
It seems that Azure Java SDK calls marked as Async (such as deallocateAsync) are kind of non-async/blocking.
One “blocking” (not-pure-async) call is captured by this call/stack trace/thread dump:
  
at java.net.SocketInputStream.socketRead0(Native Method)
at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
at java.net.SocketInputStream.read(SocketInputStream.java:171)
at java.net.SocketInputStream.read(SocketInputStream.java:141)
at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
at sun.security.ssl.InputRecord.read(InputRecord.java:503)
at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
locked <0x00000000f53fd8c8> (a java.lang.Object)
at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
locked <0x00000000f53fd888> (a java.lang.Object)
at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
at okhttp3.internal.io.RealConnection.connectTls(RealConnection.java:239)
at okhttp3.internal.io.RealConnection.establishProtocol(RealConnection.java:196)
at okhttp3.internal.io.RealConnection.buildConnection(RealConnection.java:171)
at okhttp3.internal.io.RealConnection.connect(RealConnection.java:111)
at okhttp3.internal.http.StreamAllocation.findConnection(StreamAllocation.java:187)
at okhttp3.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:123)
at okhttp3.internal.http.StreamAllocation.newStream(StreamAllocation.java:93)
at okhttp3.internal.http.HttpEngine.connect(HttpEngine.java:296)
at okhttp3.internal.http.HttpEngine.sendRequest(HttpEngine.java:248)
at okhttp3.RealCall.getResponse(RealCall.java:243)
at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:201)
at com.microsoft.rest.retry.RetryHandler.intercept(RetryHandler.java:75)
at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:190)
at com.microsoft.rest.interceptors.CustomHeadersInterceptor.intercept(CustomHeadersInterceptor.java:140)
at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:190)
at com.microsoft.rest.interceptors.UserAgentInterceptor.intercept(UserAgentInterceptor.java:83)
at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:190)
at com.microsoft.azure.credentials.AzureTokenCredentialsInterceptor.intercept(AzureTokenCredentialsInterceptor.java:40)
at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:190)
at com.microsoft.rest.interceptors.BaseUrlHandler.intercept(BaseUrlHandler.java:43)
at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:190)
at com.microsoft.rest.interceptors.RequestIdHeaderInterceptor.intercept(RequestIdHeaderInterceptor.java:29)
at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:190)
at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:163)
at okhttp3.RealCall.execute(RealCall.java:57)
at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$RequestArbiter.request(RxJavaCallAdapterFactory.java:171)
at rx.Subscriber.setProducer(Subscriber.java:211)
at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102)
at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:152)
at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:138)
at rx.Observable.unsafeSubscribe(Observable.java:10142)
at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
at rx.Observable.unsafeSubscribe(Observable.java:10142)
at rx.internal.operators.DeferredScalarSubscriber.subscribeTo(DeferredScalarSubscriber.java:153)
at rx.internal.operators.OnSubscribeTakeLastOne.call(OnSubscribeTakeLastOne.java:32)
at rx.internal.operators.OnSubscribeTakeLastOne.call(OnSubscribeTakeLastOne.java:22)
at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
at rx.Observable.subscribe(Observable.java:10238)
at rx.Observable.subscribe(Observable.java:10205)
at rx.Observable.subscribe(Observable.java:10045)
at com.microsoft.rest.ServiceFuture.fromResponse(ServiceFuture.java:67)
at com.microsoft.azure.management.compute.implementation.VirtualMachinesInner.deallocateAsync(VirtualMachinesInner.java:1002)
 
VirtualMachinesInner.deallocateAsync (called by our code which is VERY sensitive to threads utilization) is expected to be Async (return almost immediately), still internally it initiates a HTTP request (see SSL handshake that waits on socket.read) which is blocking. And that causes our System lots of problems, cause the System thread pool is being blocked and thus exhausted.

Please advise is this expected and how to overcome it. Currently we are using a separate Thread pool to execute and isolate ~14 Azure SDK xxxAsync methods to prevent our core threads pool, still IMO this does not seem to be the right solution.

Regards,
-Alex

**Comment by anuchandy** [comment]
@asavov are you saying that `Observable<OperationStatusResponseInner> VirtualMachinesInner.deallocateAsync(rg-name, vm-name)` initiate an HTTP request even before subscribing to it? if that is the case then you can put the api call inside defer which ensure HTTP call get initialized only when we subscribe to it.

```java
Observable<OperationStatusResponseInner> deferredDeallocateAsync = Observable.defer(new 
Func0<Observable<OperationStatusResponseInner>() {
            @Override
            public Observable<OperationStatusResponseInner> call() {
                return VirtualMachinesInner.deallocateAsync("<rg-name>", "<vm-name>");
            }
        });
```

If your concern is about blocking after the rx subscription then we don't have a solution right now other than running call in a separate thread (in rx `deferredDeallocateAsync().subscribeOn(Scheduler.io)`) , looking into the stack track it seems it is OkHttp Library which makes blocking JDK `socket.read` call. 

We are working on moving to netty based http client which uses JDK NIO underneath, the work is in progress https://github.com/Azure/autorest-clientruntime-for-java/tree/v2.

**Comment by asavov** [comment]
@anuchandy: We are using `ServiceFuture<OperationStatusResponseInner> VirtualMachinesInner.deallocateAsync(rgName, vmName, ServiceCallback<OperationStatusResponseInner> serviceCallback)` passing a `ServiceCallback` to get notified. The returned `ServiceFuture<OperationStatusResponseInner>` is not ref'd at all, neither any `Rx` code is being called by us.

Yep, that's our understanding too, that 

```
at okhttp3.RealCall.execute(RealCall.java:57)
at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
```

initiates the external call.

What you propose (running call in a separate thread) is exactly what we do right now for the calls that happened to be problematic.

The WIP you mentioned, states that "This package depends on Retrofit, OkHttp, Jackson, RxJava for making and processing REST requests." So the plan is to replace OkHttp (the suspect for the problem) to Netty. When you expect this to be publicly available so we can plan and execute accordingly.

Thanks,
-AlexS

**Comment by anuchandy** [comment]
Hi Alex, our plan is to switch to new runtime early next year (2018 Jan-March).

**Comment by anuchandy** [comment]
@asavov you mentioned that you are using service call back based methods - the reason I mentioned in the previous comment is applicable for service call back overload as well since all async variants uses OkHttp underneath. Our current work to transition from okhttp to netty will fix this problem, which as I mentioned above planned for early next year.

**Comment by niteshjain1** [comment]
Just to confirm, if this is the same scenario.
```
  final Completable deleteHandler = clientMds.getAzureClient().virtualMachines().deleteByIdAsync(vmToDelete);
        Thread.sleep(10 * 1000);

        deleteHandler.subscribe(new Action0() {
            @Override
            public void call() {
                System.out.println("YEAH");
            }
        }, new Action1<Throwable>() {
            @Override
            public void call(final Throwable throwable) {
                System.out.println("FAILED");
            }
        });
        Thread.sleep(50 * 1000);
        deleteHandler.await();
```
The thread blocks on subscribe call (in v1.3.0), whereas it was non-blocking till v1.1.0

**Comment by asavov** [comment]
@niteshjain1 The prev post...who are you asking? Could you elaborate a bit. I'm not understanding the question.

We are using ServiceFuture<OperationStatusResponseInner> VirtualMachinesInner.deallocateAsync(rgName, vmName, ServiceCallback<OperationStatusResponseInner> serviceCallback) passing a **ServiceCallback** to get notified. The returned ServiceFuture<OperationStatusResponseInner> is not ref'd at all, neither any Rx code is being called by us.

**Comment by niteshjain1** [comment]
@asaov asking both you and @anuchandy .
The issue seems to be the similar to what I observed. Recently upgraded to sdk v1.3.0 from v.1.1.0 and observed this.  The mentioned call became blocking.

**Comment by anuchandy** [comment]
@niteshjain1 interesting, we need to check anything changed in the runtime. Meantime, you can explicitly use `subscribeOn()` to make the call async.
```java
final Completable deleteHandler = clientMds.getAzureClient()
.virtualMachines()
.deleteByIdAsync(vmToDelete)
.subscribeOn(Schedulers.io());
```

**Comment by anuchandy** [comment]
@niteshjain1 we found that in runtime we moved from io to immediate scheduler for LRO. I have fixed the issue in the SDK level and opened a PR, this will be available in v1.4. Thanks for reporting this!

@asaov just wanted to clarify, as mentioned previously the work of moving to nio is scheduled for early next year, this PR has nothing to do with that.

**Comment by niteshjain1** [comment]
@anuchandy thanks for the quick fix. What is the expected timeline for v1.4 ?

**Comment by anuchandy** [comment]
niteshjain1,  targeting for Nov-15 provided we don’t come across any last minute bug.

**Comment by davidbairdala** [comment]
I am experiencing a similar problem with virtualMachine.refreshInstanceViewAsync() in that the observable seems to block on the call to subscribe(). I am using version 1.6.0 of the Java SDK

**Comment by praries880** [comment]
@anuchandy has this issue been fixed? I see that you mentioned that this issue was going to be fixed in early 2018.

**Comment by anuchandy** [comment]
The core update needed for this is there via pluggable Netty client. We're working on next versions (track2) of mgmt SDK which uses this async client. Will update this issue once the track2 are out. assigning this to the new owner - @yaohaizh

**Comment by yungezz** [comment]
hi @weidongxu-microsoft could you pls help to look at it S170? thanks

**Comment by weidongxu-microsoft** [comment]
On track2, http is handled by azure-core, azure-core-http-.
