### ISSUE TITLE
Deserialization exception when using app service certificate orders

### ISSUE THREAD

**Issue by npeuser** [Azure/azure-sdk-for-java#1959]
Hey all,

I'm trying to use this awesome SDK to create autodeployed SSL WebApps and unfortunately am running into an issue when trying to use an existing AppServiceCertificateOrder.
Because AppServiceCertificateOrderInner.java uses 

`@JsonProperty(value = "properties.certificates")`
`private Map<String, AppServiceCertificate> certificates;`

for its definition, when trying to make the following call

`AppServiceCertificateOrder certificateOrder = azure.appServices().certificateOrders().getById(APPSERVICE_CERT_ORDER_ID);`

I get this jackson deserialization exception instead (JSON content removed because it contains sensitive data):

`Caused by: com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of com.microsoft.azure.management.appservice.AppServiceCertificate, problem: abstract types either need to be mapped to concrete types, have custom deserializer, or be instantiated with additional type information
 at [Source: {"id":"..."}}; line: 1, column: 9156] (through reference chain: com.microsoft.azure.management.appservice.implementation.AppServiceCertificateOrderInner["properties.certificates"]->java.util.LinkedHashMap["igxcwildcard"])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:216)
	at com.fasterxml.jackson.databind.DeserializationContext.instantiationException(DeserializationContext.java:908)
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserialize(AbstractDeserializer.java:150)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringMap(MapDeserializer.java:495)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:341)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:26)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:490)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:101)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:260)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125)
	at com.microsoft.rest.serializer.FlatteningDeserializer.deserialize(FlatteningDeserializer.java:109)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3789)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2817)
	at com.microsoft.rest.serializer.JacksonAdapter.deserialize(JacksonAdapter.java:131)
	at com.microsoft.rest.ServiceResponseBuilder.buildBody(ServiceResponseBuilder.java:216)
	at com.microsoft.rest.ServiceResponseBuilder.build(ServiceResponseBuilder.java:110)
	at com.microsoft.azure.AzureResponseBuilder.build(AzureResponseBuilder.java:56)
	at com.microsoft.azure.management.appservice.implementation.AppServiceCertificateOrdersInner.getByResourceGroupDelegate(AppServiceCertificateOrdersInner.java:556)
	at com.microsoft.azure.management.appservice.implementation.AppServiceCertificateOrdersInner.access$300(AppServiceCertificateOrdersInner.java:46)
	at com.microsoft.azure.management.appservice.implementation.AppServiceCertificateOrdersInner$17.call(AppServiceCertificateOrdersInner.java:543)
	at com.microsoft.azure.management.appservice.implementation.AppServiceCertificateOrdersInner$17.call(AppServiceCertificateOrdersInner.java:539)`

Any ideas would be greatly appreciated, as I need to get this project along and the code as is seems to break every use of AppServiceCertificateOrders with contained certificates.

**Comment by martinsawicki** [comment]
any chance we could BODY_AND_HEADERS logging turned on and have the log attached here?  (remove sensitive info - token, urls the cert is bound to, etc)
