### ISSUE TITLE
NPE while trying to list VM Extensions

### ISSUE THREAD

**Issue by ImranBijapuri** [Azure/azure-sdk-for-java#1967]
I was trying to list VM Extensions but for some reason the call ended up in an NPE. Below is the stack trace and we are using v 1.1.2

java.lang.NullPointerException
	at com.microsoft.azure.management.compute.implementation.VirtualMachineExtensionImpl.initializeSettings(VirtualMachineExtensionImpl.java:319) ~[azure-mgmt-compute-1.1.2.jar:1.1.2]
	at com.microsoft.azure.management.compute.implementation.VirtualMachineExtensionImpl.<init>(VirtualMachineExtensionImpl.java:49) ~[azure-mgmt-compute-1.1.2.jar:1.1.2]
	at com.microsoft.azure.management.compute.implementation.VirtualMachineExtensionsImpl$3$1.call(VirtualMachineExtensionsImpl.java:93) ~[azure-mgmt-compute-1.1.2.jar:1.1.2]
	at com.microsoft.azure.management.compute.implementation.VirtualMachineExtensionsImpl$3$1.call(VirtualMachineExtensionsImpl.java:90) ~[azure-mgmt-compute-1.1.2.jar:1.1.2]
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.internal.operators.OperatorMerge$MergeSubscriber.emitScalar(OperatorMerge.java:511) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.internal.operators.OperatorMerge$MergeSubscriber.tryEmit(OperatorMerge.java:466) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:244) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:148) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77) ~[rxjava-1.2.4.jar:1.2.4]
	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$RequestArbiter.request(RxJavaCallAdapterFactory.java:173) ~[adapter-rxjava-2.1.0.jar:?]
	at rx.Subscriber.setProducer(Subscriber.java:211) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102) ~[rxjava-1.2.4.jar:1.2.4]
	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:152) ~[adapter-rxjava-2.1.0.jar:?]
	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:138) ~[adapter-rxjava-2.1.0.jar:?]
	at rx.Observable.unsafeSubscribe(Observable.java:10142) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.Observable.unsafeSubscribe(Observable.java:10142) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.Observable.unsafeSubscribe(Observable.java:10142) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.Observable.unsafeSubscribe(Observable.java:10142) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:248) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:148) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.internal.operators.OnSubscribeFilter$FilterSubscriber.onNext(OnSubscribeFilter.java:76) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.fastPath(OnSubscribeFromIterable.java:173) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.request(OnSubscribeFromIterable.java:86) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.Subscriber.setProducer(Subscriber.java:211) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.internal.operators.OnSubscribeFilter$FilterSubscriber.setProducer(OnSubscribeFilter.java:104) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:63) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:34) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.Observable.unsafeSubscribe(Observable.java:10142) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.internal.operators.OnSubscribeFilter.call(OnSubscribeFilter.java:45) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.internal.operators.OnSubscribeFilter.call(OnSubscribeFilter.java:30) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.Observable.unsafeSubscribe(Observable.java:10142) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.Observable.unsafeSubscribe(Observable.java:10142) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.internal.operators.OnSubscribeConcatMap$ConcatMapSubscriber.drain(OnSubscribeConcatMap.java:286) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.internal.operators.OnSubscribeConcatMap$ConcatMapSubscriber.onNext(OnSubscribeConcatMap.java:144) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.internal.operators.OnSubscribeFromArray$FromArrayProducer.slowPath(OnSubscribeFromArray.java:100) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.internal.operators.OnSubscribeFromArray$FromArrayProducer.request(OnSubscribeFromArray.java:63) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.Subscriber.setProducer(Subscriber.java:211) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.internal.operators.OnSubscribeFromArray.call(OnSubscribeFromArray.java:32) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.internal.operators.OnSubscribeFromArray.call(OnSubscribeFromArray.java:24) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.Observable.unsafeSubscribe(Observable.java:10142) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.internal.operators.OnSubscribeConcatMap.call(OnSubscribeConcatMap.java:94) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.internal.operators.OnSubscribeConcatMap.call(OnSubscribeConcatMap.java:42) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.Observable.unsafeSubscribe(Observable.java:10142) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.internal.operators.DeferredScalarSubscriber.subscribeTo(DeferredScalarSubscriber.java:153) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.internal.operators.OnSubscribeCollect.call(OnSubscribeCollect.java:50) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.internal.operators.OnSubscribeCollect.call(OnSubscribeCollect.java:24) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.Observable.unsafeSubscribe(Observable.java:10142) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.internal.operators.DeferredScalarSubscriber.subscribeTo(DeferredScalarSubscriber.java:153) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.internal.operators.OnSubscribeTakeLastOne.call(OnSubscribeTakeLastOne.java:32) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.internal.operators.OnSubscribeTakeLastOne.call(OnSubscribeTakeLastOne.java:22) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.Observable.subscribe(Observable.java:10238) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.Observable.subscribe(Observable.java:10205) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:444) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.observables.BlockingObservable.last(BlockingObservable.java:227) ~[rxjava-1.2.4.jar:1.2.4]
	at com.microsoft.azure.management.compute.implementation.VirtualMachineExtensionsImpl.asMap(VirtualMachineExtensionsImpl.java:51) ~[azure-mgmt-compute-1.1.2.jar:1.1.2]
	at com.microsoft.azure.management.compute.implementation.VirtualMachineImpl.listExtensions(VirtualMachineImpl.java:1369) ~[azure-mgmt-compute-1.1.2.jar:1.1.2]
	at com.vmturbo.mediation.azure.monitoring.AzureVMSDKMonitor.monitor(AzureVMSDKMonitor.java:133) ~[com.vmturbo.mediation.azure-6.0.1.jar:?]
	at com.vmturbo.mediation.azure.monitoring.AzureVMMonitor.monitor(AzureVMMonitor.java:38) ~[com.vmturbo.mediation.azure-6.0.1.jar:?]
	at com.vmturbo.mediation.azure.AzureDiscoveryController.discover(AzureDiscoveryController.java:213) ~[com.vmturbo.mediation.azure-6.0.1.jar:?]
	at com.vmturbo.mediation.azure.AzureProbe.discoverTarget(AzureProbe.java:69) ~[com.vmturbo.mediation.azure-6.0.1.jar:?]
	at com.vmturbo.mediation.azure.AzureProbe.discoverTarget(AzureProbe.java:40) ~[com.vmturbo.mediation.azure-6.0.1.jar:?]
	at com.vmturbo.mediation.common.RemoteMediationWorker$6.call(RemoteMediationWorker.java:520) ~[com.vmturbo.mediation.common-6.0.1.jar:?]
	at com.vmturbo.mediation.common.RemoteMediationWorker$6.call(RemoteMediationWorker.java:515) ~[com.vmturbo.mediation.common-6.0.1.jar:?]
	at com.vmturbo.mediation.common.ProbeProperties.doWithinClassLoader(ProbeProperties.java:198) ~[com.vmturbo.mediation.common-6.0.1.jar:?]
	at com.vmturbo.mediation.common.ProbeProperties.doWithinProbe(ProbeProperties.java:179) ~[com.vmturbo.mediation.common-6.0.1.jar:?]
	at com.vmturbo.mediation.common.RemoteMediationWorker.processDiscoveryRequestInternal(RemoteMediationWorker.java:515) ~[com.vmturbo.mediation.common-6.0.1.jar:?]
	at com.vmturbo.mediation.common.RemoteMediationWorker.processDiscoveryRequest(RemoteMediationWorker.java:457) ~[com.vmturbo.mediation.common-6.0.1.jar:?]
	at com.vmturbo.mediation.common.RemoteMediationWorker.access$100(RemoteMediationWorker.java:54) ~[com.vmturbo.mediation.common-6.0.1.jar:?]
	at com.vmturbo.mediation.common.RemoteMediationWorker$3.handleMessage(RemoteMediationWorker.java:243) ~[com.vmturbo.mediation.common-6.0.1.jar:?]
	at com.vmturbo.mediation.common.RemoteMediationWorker.lambda$onMessageReceived$0(RemoteMediationWorker.java:170) ~[com.vmturbo.mediation.common-6.0.1.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: null
	at rx.exceptions.OnErrorThrowable.addValueAsLastCause(OnErrorThrowable.java:118) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:73) ~[rxjava-1.2.4.jar:1.2.4]

**Comment by anuchandy** [comment]
@ImranBijapuri I am trying to repro this. I have few questions, could you please help here - 

1. How is the VM retrieved - 
       a. VirtualMachines.GetById()/VirtualMachines.GetByResourceGroup()
       b. VirtualMachines.List() 
i.e. is the VM retrieved as part of (b) listing or (a) individual VM get call?

2. Could you also share the code and its log which shows payload of 1.a or 1.b (based on your scenario) and list extension? Logging can enabled as: 

```java
 Azure azure = Azure.configure()
    .withLogLevel(LogLevel.BODY_AND_HEADERS)
    .authenticate(credFile)
    .withDefaultSubscription();
```

**Comment by ImranBijapuri** [comment]
The VM is retrieved using 1.b 

I am sorry but I don't have access to this environment to toggle the logging.

**Comment by igolikov** [comment]
Is there any update?

**Comment by renutz** [comment]
Same error here. Using 1.1.3

1. When we get the instance through its name and RG, it works:

instance = ...virtualMachines().getByResourceGroup(rgname, instancename)

2. When we get the instance through listing, it doesn't work:

for (VirtualMachine instance: azureContext.getAzureAPIs().virtualMachines().list()) {
...
}

3. Getting the extension on both scenarios:

for (Map.Entry<String, VirtualMachineExtension> extensionEntry : instance.listExtensions().entrySet()) {
}

It generates the same exception.

Thanks

**Comment by esara** [comment]
@anuchandy is there an update? We have the same problem with the extensions throwing an NPE with another large Azure customer.

**Comment by yaohaizh** [comment]
@esara are you still seesing this issue?

**Comment by esara** [comment]
@yaohaizh yes, we continue to wrap the virtualMachine.getExtensions() call with a big try catch, because it continues to throw an NPE across our customers.

**Comment by rurychen** [comment]
I am getting the same issue on vm.listExtensions().
SDK version 1.22.0
a. VirtualMachines.GetById()/VirtualMachines.GetByResourceGroup()
-> No issue.
b. VirtualMachines.List()
-> NPE

I add debuging on the API call

Analyzing OkHttpCall.execute() for url: https://management.azure.com/subscriptions/xxxxxx/resourceGroups/xxxxxx/providers/Microsoft.Compute/virtualMachines/xxxxxx?api-version=2018-10-01
[pool-3-thread-1] INFO com.microsoft.aad.adal4j.AuthenticationAuthority - [Correlation ID: xxxxxx] Instance discovery was successful
Analyzing OkHttpCall.parseResponse() for url: https://management.azure.com/subscriptions/xxxxxx/resourceGroups/xxxxxx/providers/Microsoft.Compute/virtualMachines/xxxxxx?api-version=2018-10-01
Get vm by getByResourceGroup. listExtensions::1
vmid:::/subscriptions/xxxxxx/resourceGroups/xxxxxx/providers/Microsoft.Compute/virtualMachines/xxxxxx
Analyzing OkHttpCall instance ...
Analyzing OkHttpCall.execute() for url: https://management.azure.com/subscriptions/xxxxxx/resourceGroups/xxxxxx/providers/Microsoft.Compute/virtualMachines/xxxxxx?api-version=2018-10-01
Analyzing OkHttpCall.parseResponse() for url: https://management.azure.com/subscriptions/xxxxxx/resourceGroups/xxxxxx/providers/Microsoft.Compute/virtualMachines/xxxxxx?api-version=2018-10-01
Get vm by getById. listExtensions::1

List vm---------
Analyzing OkHttpCall instance ...
Analyzing OkHttpCall.execute() for url: https://management.azure.com/subscriptions/xxxxxx/providers/Microsoft.Compute/virtualMachines?api-version=2018-10-01
Analyzing OkHttpCall.parseResponse() for url: https://management.azure.com/subscriptions/xxxxxx/providers/Microsoft.Compute/virtualMachines?api-version=2018-10-01
Analyzing OkHttpCall instance ...
Analyzing OkHttpCall.execute() for url: https://management.azure.com/subscriptions/xxxxxx/resourceGroups/xxxxxx/providers/Microsoft.Compute/virtualMachines/xxxxxx/extensions/OmsAgentForLinux?api-version=2018-10-01
Analyzing OkHttpCall.parseResponse() for url: https://management.azure.com/subscriptions/xxxxxx/resourceGroups/xxxxxx/providers/Microsoft.Compute/virtualMachines/xxxxxx/extensions/OmsAgentForLinux?api-version=2018-10-01


java.lang.NullPointerException
	at com.microsoft.azure.management.compute.implementation.VirtualMachineExtensionImpl.initializeSettings(VirtualMachineExtensionImpl.java:323)
	at com.microsoft.azure.management.compute.implementation.VirtualMachineExtensionImpl.<init>(VirtualMachineExtensionImpl.java:48)
	at com.microsoft.azure.management.compute.implementation.VirtualMachineExtensionsImpl$3$1.call(VirtualMachineExtensionsImpl.java:93)
	at com.microsoft.azure.management.compute.implementation.VirtualMachineExtensionsImpl$3$1.call(VirtualMachineExtensionsImpl.java:90)


It got ResourceNotFound response for gettting extensions:
`https://management.azure.com/subscriptions/xxxxxx/resourceGroups/xxxxxx/providers/Microsoft.Compute/virtualMachines/xxxxxx/extensions/OmsAgentForLinux?api-version=2018-10-01`

{"error":{"code":"ResourceNotFound","message":"The Resource 'Microsoft.Compute/virtualMachines/xxxx/extensions/OmsAgentForLinux' under resource group 'XXXX' was not found."}}

**Comment by ChenTanyi** [comment]
@rurychen Thanks for you code snippet and log, I'll fix it later

**Comment by popocoo** [comment]
> @rurychen Thanks for you code snippet and log, I'll fix it later

Thank you very much.

**Comment by rurychen** [comment]
@ChenTanyi  Thanks for your help, I appreciate it.
