### ISSUE TITLE
java.lang.IllegalArgumentException: Parameter resourceGroupName is required and cannot be null.

### ISSUE THREAD

**Issue by menih** [Azure/azure-sdk-for-java#1971]
A simple call to azure.routeTables().getById(id);

throws the following stack.

java.lang.IllegalArgumentException: Parameter resourceGroupName is required and cannot be null.
	at com.microsoft.azure.management.network.implementation.RouteTablesInner.getByResourceGroupWithServiceResponseAsync(RouteTablesInner.java:310) ~[factory.jar:1.2]
	at com.microsoft.azure.management.network.implementation.RouteTablesInner.getByResourceGroupAsync(RouteTablesInner.java:292) ~[factory.jar:1.2]
	at com.microsoft.azure.management.resources.fluentcore.arm.collection.implementation.TopLevelModifiableResourcesImpl.getInnerAsync(TopLevelModifiableResourcesImpl.java:64) ~[factory.jar:1.2]
	at com.microsoft.azure.management.resources.fluentcore.arm.collection.implementation.GroupableResourcesImpl.getByResourceGroupAsync(GroupableResourcesImpl.java:114) ~[factory.jar:1.2]
	at com.microsoft.azure.management.resources.fluentcore.arm.collection.implementation.GroupableResourcesImpl.getByIdAsync(GroupableResourcesImpl.java:79) ~[factory.jar:1.2]
	at com.microsoft.azure.management.resources.fluentcore.arm.collection.implementation.GroupableResourcesImpl.getById(GroupableResourcesImpl.java:68) ~[factory.jar:1.2]
	at com.microsoft.azure.management.resources.fluentcore.arm.collection.implementation.GroupableResourcesImpl.getById(GroupableResourcesImpl.java:33) ~[factory.jar:1.2]

**Comment by anuchandy** [comment]
@menih Could you please share the route table resource id for which this exception is happening? you can replace the subscription id chars with zeros but don't make any other modifications. don't trim any slashes.

**Comment by menih** [comment]
You just hinted what the issue could be... resource group case sensitivity.
The ID returned from routeTables().getById(id) and routeTables().list() is
different! Already created an issue on that. The whole case sensitivity of
a an identifier is a bad design in my opinion...

On Sun, Nov 12, 2017 at 8:19 PM, Anu Thomas Chandy <notifications@github.com

**Comment by anuchandy** [comment]
Yes, you and few other users raised id case sensitivty issue, we had a discussion with service team and opened an internal ticket.


But, this specific exception IllegalArgument NPE error is thrown by the client library before sending  request to service. I am not sure how it is related to case sensitivity issue. Any chance you can share the id causing the problem as I mentioned in the previous comment?

**Comment by menih** [comment]
I don't have the actual ID... I'll add a log and wait for it to reproduce...

**Comment by martinsawicki** [comment]
related: https://github.com/Azure/azure-sdk-for-java/issues/1924

**Comment by anuchandy** [comment]
@menih were you able to repro this? our tests for parsing and using arm ids are passing. Wonder what is special about id in your case.

**Comment by menih** [comment]
Was not able to reproduce yet... I have a feeling it is different IDs
returning from routeTables().list() and routeTables().getById(). Create a
RG that has mix upper and lower, and then create a route table within that
RG.

On Wed, Nov 15, 2017 at 9:06 AM, Anu Thomas Chandy <notifications@github.com
