### ISSUE TITLE
Enable autoscaling for VMSS

### ISSUE THREAD

**Issue by niteshjain1** [Azure/azure-sdk-for-java#1972]
Was trying to use VMSS, but could not find any api to enable autoscaling. Could someone confirm if this is available in the current release (if yes,some examples would be helpful).  From the template model it seems it should be part of insights api, not sure but.

**Comment by anuchandy** [comment]
+ @hovsepm for Monitoring Service.

@niteshjain1 

It seems VMSS autoscaling is enabled by creating an AutoScalingSettings in Azure Monitor, found it here https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-autoscale-cli

I just tried to port the cli snippet in the above doc page to Java, I did not run it assuming the documentation is correct. 

```java
import com.microsoft.azure.credentials.ApplicationTokenCredentials;
import com.microsoft.azure.management.monitor.implementation.AutoscaleSettingResourceInner;
import com.microsoft.azure.management.monitor.implementation.MonitorManager;
import com.microsoft.azure.management.resources.fluentcore.arm.Region;
import org.joda.time.Period;

import java.io.File;
import java.util.ArrayList;
import java.util.List;

        final File credFile = new File(System.getenv("AZURE_AUTH_LOCATION"));
        ApplicationTokenCredentials credentials = ApplicationTokenCredentials.fromFile(credFile);
        MonitorManager monitorManager = MonitorManager.authenticate(credentials, credentials.defaultSubscriptionId());

        String rgName = "";
        String scaleSetId = "";
        String location = Region.US_EAST2.name();
        String autoscaleSettingResourceName = "autoscale";

        ScaleRule rule1 = new ScaleRule();
        rule1.withMetricTrigger(new MetricTrigger()
                .withMetricName("Percentage CPU")
                .withMetricResourceUri(scaleSetId)
                .withTimeGrain(new Period("PT1M"))
                .withStatistic(MetricStatisticType.AVERAGE)
                .withTimeWindow(new Period("PT10M"))
                .withTimeAggregation(TimeAggregationType.AVERAGE)
                .withOperator(ComparisonOperationType.GREATER_THAN)
                .withThreshold(70))
             .withScaleAction(new ScaleAction()
                .withDirection(ScaleDirection.INCREASE)
                .withType(ScaleType.PERCENT_CHANGE_COUNT)
                .withValue("20")
                .withCooldown(new Period("PT5M")));

        ScaleRule rule2 = new ScaleRule();
        rule2.withMetricTrigger(new MetricTrigger()
                .withMetricName("Percentage CPU")
                .withMetricResourceUri(scaleSetId)
                .withTimeGrain(new Period("PT1M"))
                .withStatistic(MetricStatisticType.AVERAGE)
                .withTimeWindow(new Period("PT10M"))
                .withTimeAggregation(TimeAggregationType.AVERAGE)
                .withOperator(ComparisonOperationType.LESS_THAN)
                .withThreshold(30))
                .withScaleAction(new ScaleAction()
                        .withDirection(ScaleDirection.DECREASE)
                        .withType(ScaleType.PERCENT_CHANGE_COUNT)
                        .withValue("20")
                        .withCooldown(new Period("PT5M")));

        List<ScaleRule> rules = new ArrayList<>();
        rules.add(rule1);
        rules.add(rule2);

        AutoscaleProfile autoscaleProfile = new AutoscaleProfile();
        autoscaleProfile.withName("autoscale by percentage based on CPU usage")
                .withCapacity(new ScaleCapacity().withMinimum("2").withMaximum("2").withDefaultProperty("2"))
                .withRules(rules);

        List<AutoscaleProfile> profiles = new ArrayList<>();
        profiles.add(autoscaleProfile);

        AutoscaleSettingResourceInner autoScaleSettings = new AutoscaleSettingResourceInner();

        autoScaleSettings.withEnabled(true)
                .withAutoscaleSettingResourceName(autoscaleSettingResourceName)
                .withNotifications(new ArrayList<AutoscaleNotification>())
                .withProfiles(profiles)
                .withTargetResourceUri(scaleSetId)
                .withLocation(location);

        monitorManager
                .inner()
                .autoscaleSettings()
                .createOrUpdate(rgName, autoscaleSettingResourceName, autoScaleSettings);
```

**Comment by niteshjain1** [comment]
@anuchandy I wished to scale to specific instance count, but cannot find a way to set it. I can specify a exact scale count but cannot create autoscale profile without a metric trigger.
thanks in advance

**Comment by anuchandy** [comment]
Adding John from monitoring service team. @johnkemnetz, could you help here by sharing the configuration for what Nitesh is trying to achieve?

**Comment by george-moussa** [comment]
@niteshjain1 you can create a profile with no rules, then set max/min/default to the desired instances count.

**Comment by niteshjain1** [comment]
I tried creating a profile with no rule but got the following error

`

           Exception in thread "main" java.lang.IllegalArgumentException: profiles.rules is required and cannot be null.
	at com.microsoft.rest.Validator.validate(Validator.java:109)
	
       at com.microsoft.azure.management.monitor.implementation.AutoscaleSettingsInner.createOrUpdateWithServiceResponseAsync(AutoscaleSettingsInner.java:275)
	
      at com.microsoft.azure.management.monitor.implementation.AutoscaleSettingsInner.createOrUpdate(AutoscaleSettingsInner.java:218)
`

**Comment by anuchandy** [comment]
@niteshjain1 rules property is marked as required in the api spec. Could you give a try with empty rules collection in the profile?

```java
autoscaleProfile.withName(...)
    .withCapacity(...)
    .withRules(new ArrayList<ScaleRule>());
```

**Comment by niteshjain1** [comment]
That did not work either
`Exception in thread "main" java.lang.IllegalArgumentException: profiles.rules.metricTrigger is required and cannot be null.
	at com.microsoft.rest.Validator.validate(Validator.java:109)
	at com.microsoft.azure.management.monitor.implementation.AutoscaleSettingsInner.createOrUpdateWithServiceResponseAsync(AutoscaleSettingsInner.java:275)
	at com.microsoft.azure.management.monitor.implementation.AutoscaleSettingsInner.createOrUpdate(AutoscaleSettingsInner.java:218)
`

**Comment by anuchandy** [comment]
@george-moussa - it seems due to the constraints specified in the swagger spec, one cannot create profile with no rules.

**Comment by gucalder** [comment]
It is correct that rules is specified as required in the Swagger spec. 
I can correct that, but it will take some time before the customer sees the new SDK.
As mitigation, try creating a rule that cannot fire.

**Comment by anuchandy** [comment]
@gucalder thank you, could you share sample json representation of rule that cannot be fired?

**Comment by gucalder** [comment]
I send some examples for the structure of a rule. I do not have the details to write a valid rule, but that will guide the process. I am asking George about the validity of those approaches since he is the expert.

Background:
I meant a rule the checks and existing metrics that would never get the value used in the condition. For instance: check # requests to a website and check that is < 0.
So the rule exists, but it is impossible that a website sees less than 0 requests, so the rule cannot fire. So the action the rule takes is not relevant.

Another way would be to use a rule that always fires. The action here will be to take the # of instances to the number desired or to increase/decrease until we hit the desired number.

**Comment by niteshjain1** [comment]
Created a rule to increase instances to required count and metric as cpu usage > 0. Working fine for now. 
Will be waiting for monitor libraries to move to GA
