### ISSUE TITLE
gov enviorment: define new disk throws error. 

### ISSUE THREAD

**Issue by nwarriorch** [Azure/azure-sdk-for-java#1980]
I am trying to run the following code with Azure gov environment. 

```
credentials = new ApplicationTokenCredentials(sPId, azureTenantId, sPKey, AzureEnvironment.AZURE_US_GOVERNMENT);

azure = Azure.authenticate(credentials).withSubscription(subscriptionID);



VirtualMachine vm = azure.virtualMachines().getById(vmID);
vm.update()
                    .defineNewDataDisk(diskLabel)
                    .withSizeInGB(sizeGB)
                    .storeAt(storageAccount, container, diskLabel)
                    .withLun(lun)
                    .withCaching(CachingTypes.NONE)
                    .attach()
                    .apply();
```

It fails with an exception with the message. 

`The blob URL's domain must be blob.core.usgovcloudapi.net`

Full exception

```
ERROR ~ The blob URL's domain must be blob.core.usgovcloudapi.net.
ERROR ~ com.microsoft.azure.CloudException: The blob URL's domain must be blob.core.usgovcloudapi.net.: The blob URL's domain must be blob.core.usgovcloudapi.net.
	at com.microsoft.azure.AzureClient.createExceptionFromResponse(AzureClient.java:524)
	at com.microsoft.azure.AzureClient.access$000(AzureClient.java:33)
	at com.microsoft.azure.AzureClient$1.call(AzureClient.java:132)
	at com.microsoft.azure.AzureClient$1.call(AzureClient.java:129)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$RequestArbiter.request(RxJavaCallAdapterFactory.java:173)
	at rx.Subscriber.setProducer(Subscriber.java:211)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102)
	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:152)
	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:138)
	at rx.Observable.unsafeSubscribe(Observable.java:9861)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:9861)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:9861)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:9861)
	at rx.internal.util.ScalarSynchronousObservable$3.call(ScalarSynchronousObservable.java:235)
	at rx.internal.util.ScalarSynchronousObservable$3.call(ScalarSynchronousObservable.java:228)
	at rx.Observable.unsafeSubscribe(Observable.java:9861)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:9861)
	at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:221)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)



```

**Comment by nwarriorch** [comment]
Looks like storage URL has been hardcoded in my version. The new version fixes it. 
```
// Future: Get the storage domain from the environment
https://" + storageAccountName + ".blob.core.windows.net" + "/" + containerName + "/" + blobName;
```
