### ISSUE TITLE
get NPE when calling Azure.webApps().list()

### ISSUE THREAD

**Issue by jdneo** [Azure/azure-sdk-for-java#2003]
sdk version: 
![e9d8778b](https://user-images.githubusercontent.com/6193897/34555956-607f64a8-f16f-11e7-9769-7235ff9088dd.PNG)

stacktrace:

```
java.lang.NullPointerException
	at com.microsoft.azure.management.appservice.implementation.WebAppsImpl$1.filter(WebAppsImpl.java:47)
	at com.microsoft.azure.management.appservice.implementation.WebAppsImpl$1.filter(WebAppsImpl.java:38)
	at com.microsoft.azure.management.resources.fluentcore.utils.PagedListConverter.convert(PagedListConverter.java:65)
	at com.microsoft.azure.management.appservice.implementation.WebAppsImpl.wrapList(WebAppsImpl.java:91)
	at com.microsoft.azure.management.resources.fluentcore.arm.collection.implementation.TopLevelModifiableResourcesImpl.list(TopLevelModifiableResourcesImpl.java:118)
	at com.microsoft.azuretools.core.mvp.model.webapp.AzureWebAppMvpModel.listWebAppsBySubscriptionId(AzureWebAppMvpModel.java:335)
	at com.microsoft.azuretools.core.mvp.model.webapp.AzureWebAppMvpModel.listWebApps(AzureWebAppMvpModel.java:354)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.webapp.WebAppModulePresenter.onModuleRefresh(WebAppModulePresenter.java:32)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.webapp.WebAppModule.refreshItems(WebAppModule.java:35)
	at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNode.refreshItems(RefreshableNode.java:92)
	at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNode$2.run(RefreshableNode.java:130)
	at com.microsoft.azuretools.core.azureexplorer.helpers.IDEHelperImpl$1.run(IDEHelperImpl.java:55)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
```

The subscription used is in MoonCake.

**Comment by Eskibear** [comment]
Same with SDK version 1.5.1:

![image](https://user-images.githubusercontent.com/2351748/34594497-66b568ac-f20c-11e7-95a2-72f0e33fd3b3.png)

```
    protected boolean filter(SiteInner inner) {
        List<String> kinds = Arrays.asList(inner.kind().split(","));    <--- NPE here
        return kinds.contains("app");
    }
```

**Comment by hovsepm** [comment]
@jdneo @Eskibear please move this issue to https://github.com/Azure/azure-libraries-for-java
