### ISSUE TITLE
How to set proxy for the CloudBlobContainer ?

### ISSUE THREAD

**Issue by giridharkn** [Azure/azure-sdk-for-java#2008]
Hi,

Facing issue to set proxy for CloudBlobContainer. I am working on code to download the blob file into outputstream. Without proxy its fine. With proxy i have to write the code. 
Please help me with the details for the proxy settings,

Please check following code snippets which i tried.

try1:   with default proxy:                        
                        CloudStorageAccount storageAccount = CloudStorageAccount.parse(storageConnectionString);
                        CloudBlobClient blobClient = storageAccount.createCloudBlobClient();
                        CloudBlobContainer container = blobClient
                                    .getContainerReference(AzureConstant.AZURE_FLOW_LOG_CONTAINER_NAME);
                        OperationContext.setDefaultProxy(new Proxy(Proxy.Type.HTTP, new InetSocketAddress(ePOProxy.getServerName(),ePOProxy.getPort())));
blob.exists()
--- Exception at blob.exists() please check below excpetion

Try 2: with setProxy method

    CloudStorageAccount storageAccount = CloudStorageAccount.parse(storageConnectionString);
                        CloudBlobClient blobClient = storageAccount.createCloudBlobClient();
                        CloudBlobContainer container = blobClient
                                    .getContainerReference(AzureConstant.AZURE_FLOW_LOG_CONTAINER_NAME);
OperationContext op = new OperationContext();
                        op.setProxy(new Proxy(Proxy.Type.HTTP, new InetSocketAddress(ePOProxy.getServerName(),ePOProxy.getPort())));
blob.exists(null,null,op)

--- again same exception as below.

Exception:

com.microsoft.azure.storage.StorageException: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
2018-01-12 05:37:56,299 ERROR [core-CommandInvoker-thread-4] server.OrionLogging  -             at com.microsoft.azure.storage.StorageException.translateFromHttpStatus(StorageException.java:175)
2018-01-12 05:37:56,299 ERROR [core-CommandInvoker-thread-4] server.OrionLogging  -             at com.microsoft.azure.storage.StorageException.translateException(StorageException.java:94)
2018-01-12 05:37:56,299 ERROR [core-CommandInvoker-thread-4] server.OrionLogging  -             at com.microsoft.azure.storage.core.StorageRequest.materializeException(StorageRequest.java:305)
2018-01-12 05:37:56,299 ERROR [core-CommandInvoker-thread-4] server.OrionLogging  -             at com.microsoft.azure.storage.core.ExecutionEngine.executeWithRetry(ExecutionEngine.java:175)
2018-01-12 05:37:56,299 ERROR [core-CommandInvoker-thread-4] server.OrionLogging  -             at com.microsoft.azure.storage.blob.CloudBlob.exists(CloudBlob.java:1856)
2018-01-12 05:37:56,299 ERROR [core-CommandInvoker-thread-4] server.OrionLogging  -             at com.microsoft.azure.storage.blob.CloudBlob.exists(CloudBlob.java:1843)
2018-01-12 05:37:56,299 ERROR [core-CommandInvoker-thread-4] server.OrionLogging  -             at com.microsoft.azure.storage.blob.CloudBlob.exists(CloudBlob.java:1818)

---------------------------------\
Please let me help the details.

**Comment by jianghaolu** [comment]
@giridharkn You will find the storage experts in here: https://github.com/Azure/azure-storage-java.

**Comment by giridharkn** [comment]
Thanks @jianghaolu  i could able to fix it. thanks
