### ISSUE TITLE
Creation of VM fail with "The value of parameter linuxConfiguration is invalid."

### ISSUE THREAD

**Issue by menih** [Azure/azure-sdk-for-java#2009]
com.microsoft.azure.CloudException: The value of parameter linuxConfiguration is invalid.
        at com.microsoft.azure.AzureClient.createExceptionFromResponse(AzureClient.java:724) ~[factory.jar:0.0.0]
        at com.microsoft.azure.AzureClient.access$100(AzureClient.java:33) ~[factory.jar:0.0.0]
        at com.microsoft.azure.AzureClient$3.call(AzureClient.java:160) ~[factory.jar:0.0.0]
        at com.microsoft.azure.AzureClient$3.call(AzureClient.java:157) ~[factory.jar:0.0.0]
        at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69) ~[factory.jar:0.0.0]
        at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$RequestArbiter.request(RxJavaCallAdapterFactory.java:173) ~[factory.jar:0.0.0]
        at rx.Subscriber.setProducer(Subscriber.java:211) ~[factory.jar:0.0.0]
        at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102) ~[factory.jar:0.0.0]
        at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:152) ~[factory.jar:0.0.0]
        at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:138) ~[factory.jar:0.0.0]
        at rx.Observable.unsafeSubscribe(Observable.java:10142) ~[factory.jar:0.0.0]
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48) ~[factory.jar:0.0.0]
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33) ~[factory.jar:0.0.0]
        at rx.Observable.unsafeSubscribe(Observable.java:10142) ~[factory.jar:0.0.0]
        at rx.internal.operators.OnSubscribeSingle.call(OnSubscribeSingle.java:81) ~[factory.jar:0.0.0]
        at rx.internal.operators.OnSubscribeSingle.call(OnSubscribeSingle.java:27) ~[factory.jar:0.0.0]
        at rx.internal.operators.SingleToObservable.call(SingleToObservable.java:39) ~[factory.jar:0.0.0]
        at rx.internal.operators.SingleToObservable.call(SingleToObservable.java:27) ~[factory.jar:0.0.0]
        at rx.Observable.unsafeSubscribe(Observable.java:10142) ~[factory.jar:0.0.0]
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48) ~[factory.jar:0.0.0]
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33) ~[factory.jar:0.0.0]
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) ~[factory.jar:0.0.0]
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) ~[factory.jar:0.0.0]
        at rx.Observable.unsafeSubscribe(Observable.java:10142) ~[factory.jar:0.0.0]
        at rx.internal.operators.DeferredScalarSubscriber.subscribeTo(DeferredScalarSubscriber.java:153) ~[factory.jar:0.0.0]
        at rx.internal.operators.OnSubscribeTakeLastOne.call(OnSubscribeTakeLastOne.java:32) ~[factory.jar:0.0.0]
        at rx.internal.operators.OnSubscribeTakeLastOne.call(OnSubscribeTakeLastOne.java:22) ~[factory.jar:0.0.0]
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) ~[factory.jar:0.0.0]
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) ~[factory.jar:0.0.0]
        at rx.Observable.unsafeSubscribe(Observable.java:10142) ~[factory.jar:0.0.0]
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48) ~[factory.jar:0.0.0]
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33) ~[factory.jar:0.0.0]
        at rx.Observable.unsafeSubscribe(Observable.java:10142) ~[factory.jar:0.0.0]
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48) ~[factory.jar:0.0.0]
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33) ~[factory.jar:0.0.0]
        at rx.Observable.unsafeSubscribe(Observable.java:10142) ~[factory.jar:0.0.0]
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48) ~[factory.jar:0.0.0]
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33) ~[factory.jar:0.0.0]
        at rx.Observable.unsafeSubscribe(Observable.java:10142) ~[factory.jar:0.0.0]
        at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94) ~[factory.jar:0.0.0]
        at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230) ~[factory.jar:0.0.0]
        at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55) ~[factory.jar:0.0.0]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_141]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_141]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_141]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:1.8.0_141]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_141]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_141]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: retrofit2.Response.class
        at rx.exceptions.OnErrorThrowable.addValueAsLastCause(OnErrorThrowable.java:118) ~[factory.jar:0.0.0]
        at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:73) ~[factory.jar:0.0.0]
        ... 44 more

I've enabled azure logging and the payload looks like this

```json
{
	"properties": {
		"hardwareProfile": {
			"vmSize": "Standard_F4s"
		},
		"storageProfile": {
			"imageReference": {
				"id": "/subscriptions/26369c0f-46a0-43ef-a37b-6cc584450f37/resourceGroups/MENI/providers/Microsoft.Compute/images/shieldx-dp-master"
			},
			"osDisk": {
				"caching": "ReadWrite",
				"createOption": "FromImage",
				"managedDisk": {
					"storageAccountType": "Standard_LRS"
				}
			}
		},
		"osProfile": {
			"computerName": "meni-dp-FI-433",
			"adminUsername": "shieldx",
			"customData": "ewogICJ2ZXJzaW9uIiA6IDEsCiAgInR5cGUiIDogIkZTTkkiLAogICJpbWFnZVJlZ2lzdHJ5IiA6ICIxMC4yLjIuNDo1MDAwIiwKICAiaG9zdG5hbWUiIDogIm1lbmktZHAtRkktNDMzIiwKICAibWFuYWdlbWVudCIgOiB7CiAgICAidHlwZSIgOiAic3RhdGljIiwKICAgICJnYXRld2F5IiA6ICIxMC4yLjIuMSIsCiAgICAibXR1IiA6IDE1MDAsCiAgICAibmljX2luZGV4IiA6IDAsCiAgICAiaXBfYWRkcmVzcyIgOiAiMTAuMi4yLjkvMjQiLAogICAgImlwX2FkZHJlc3NlcyIgOiBbICIxMC4yLjIuOS8yNCIgXQogIH0sCiAgImJhY2twbGFuZURwZGsiIDogewogICAgInR5cGUiIDogInN0YXRpYyIsCiAgICAiZ2F0ZXdheSIgOiAiMTAuMTAuMS4xIiwKICAgICJtdHUiIDogMTUwMCwKICAgICJuaWNfaW5kZXgiIDogMSwKICAgICJpcF9hZGRyZXNzIiA6ICIxMC4xMC4xLjExLzI0IiwKICAgICJpcF9hZGRyZXNzZXMiIDogWyAiMTAuMTAuMS4xMS8yNCIsICIxMC4xMC4xLjEwLzI0IiBdCiAgfSwKICAicG9vbHMiIDogewogICAgIktFWV9WQUxVRV9TVE9SRSIgOiB7CiAgICAgICJwdWJsaWNDb25uZWN0aW9ucyIgOiBbICIxMC4yLjIuNCIgXSwKICAgICAgInByaXZhdGVDb25uZWN0aW9ucyIgOiBbICIxNjkuMjU0LjAuOCIgXQogICAgfSwKICAgICJNRVNTQUdFX0JVU19TWU5DIiA6IHsKICAgICAgInB1YmxpY0Nvbm5lY3Rpb25zIiA6IFsgIjEwLjIuMi40IiBdLAogICAgICAicHJpdmF0ZUNvbm5lY3Rpb25zIiA6IFsgIjE2OS4yNTQuMC4xMCIgXQogICAgfSwKICAgICJNRVNTQUdFX0JVUyIgOiB7CiAgICAgICJwdWJsaWNDb25uZWN0aW9ucyIgOiBbICIxMC4yLjIuNCIgXSwKICAgICAgInByaXZhdGVDb25uZWN0aW9ucyIgOiBbICIxNjkuMjU0LjAuNyIgXQogICAgfQogIH0sCiAgIm1pY3Jvc2VydmljZWlkIiA6IDQzMywKICAiY2hhc3Npc2lkIiA6IDM1LAogICJwbGF0Zm9ybSIgOiB7CiAgICAibm9uY2UiIDogIkU5Qjl2S0dRb2FaMWpJYk5SN2t1QkJ6WDlrTW5hRFVOOFpReVdWTGRyUUNEay95c2QweFdIRUhiUXVSYnBvZ3BLZmtKYnJ6UWNPOGZPOEVWcDVTN1lQQnk3OTFqbndLTWsvb29RMlZTaEZJSUVTWURDdUt6ZFpESEJZTjN6MkFlc0luQ0lTNmxZRU84MTlYbWFrRHZMeEFzdk1XeGRMWDdreGtpMk5aeXdTWFgrZDdHbWhXb2RHb0hUMEg5a0NzQWpremZjNzdUajBBOG9waCtjZTN3OGtHeTMvUVN3S0lwOGNWVFM3aTFHVndqM2VRS0JwUXVyWk5zcXU2cEl6TW9KNnBWc3JVVGdOY2F3VzlTdExDakM5ZmZQTldqWkFzRU1NYmtsUDdNNkF1enZTV2VRcTJpWElqTTBqb3NSN2hsc0NRSkNKOCtVbWgwT3hYWHhuWGRpUT09IiwKICAgICJzc2giIDogewogICAgICAicHVibGlja2V5IiA6ICJzc2gtcnNhIEFBQUFCM056YUMxeWMyRUFBQUFEQVFBQkFBQUJBUUMwbjlZYU1WUmFoNm9wRkN6MnlwWkE2NTRyZFJZdlE4UUs4cUM5TWNsOFpNYlgvd2hkSkR0QllVZ21GRmtnSC9zRU9xTnEvUTFtQ1ppWXdLVmpXWXRIKzN6SlB2cXFBT29zRkhmaGZuYUpPaGdJdmhHaHVKNEppZFl2SFBWSmY2MXZnc2g3dmxsMEZKN2pVQU9ZVzVpaWpTVGVJVEZOQXF3UWx5SHo5Q2JtcUwzcDdjR2UrUVRmMlpvUGh5U0gwV3U5LytmRmFVbHVLMDhUdFZjUCtQdWRWenNPMG10WHJMMjdubExrMGNEcEVwVkVERS9ncHdjOXh1MGRrRjVUR2Y0RVpvblB4UXBhTUhBUEUwS240WE1CV2tSR3ZZZjFxNUdtdEtyZ0s4ZkRLVnhDYlVpT085OFJmUXZLOWwvL0dNSmxDbG0xVGd2ejZIQXVMM1paMmVhMSBzaGllbGR4IiwKICAgICAgInVzZXJuYW1lIiA6ICJzaGllbGR4IgogICAgfQogIH0sCiAgIkZTTkkiIDogewogICAgImJ5dGVzX3Blcl9zZWNvbmQiIDogNDAyNjUzMTg0CiAgfQp9",
			"linuxConfiguration": {
				"disablePasswordAuthentication": true,
				"ssh": {
					"publicKeys": [{
						"path": "/home/shieldx/.ssh/authorized_keys",
						"keyData": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0n9YaMVRah6opFCz2ypZA654rdRYvQ8QK8qC9Mcl8ZMbX/whdJDtBYUgmFFkgH/sEOqNq/Q1mCZiYwKVjWYtH+3zJPvqqAOosFHfhfnaJOhgIvhGhuJ4JidYvHPVJf61vgsh7vll0FJ7jUAOYW5iijSTeITFNAqwQlyHz9CbmqL3p7cGe+QTf2ZoPhySH0Wu9/+fFaUluK08TtVcP+PudVzsO0mtXrL27nlLk0cDpEpVEDE/gpwc9xu0dkF5TGf4EZonPxQpaMHAPE0Kn4XMBWkRGvYf1q5GmtKrgK8fDKVxCbUiOO98RfQvK9l//GMJlClm1Tgvz6HAuL3ZZ2ea1 shieldx"
					}]
				}
			}
		},
		"networkProfile": {
			"networkInterfaces": [{
				"properties": {
					"primary": true
				},
				"id": "/subscriptions/26369c0f-46a0-43ef-a37b-6cc584450f37/resourceGroups/MENI-DP/providers/Microsoft.Network/networkInterfaces/meni-dp-FI-433_MGMT"
			},
			{
				"properties": {
					"primary": false
				},
				"id": "/subscriptions/26369c0f-46a0-43ef-a37b-6cc584450f37/resourceGroups/MENI-DP/providers/Microsoft.Network/networkInterfaces/meni-dp-FI-433_BP_DPDK"
			},
			{
				"properties": {
					"primary": false
				},
				"id": "/subscriptions/26369c0f-46a0-43ef-a37b-6cc584450f37/resourceGroups/MENI-DP/providers/Microsoft.Network/networkInterfaces/meni-dp-FI-433_OUTSIDE"
			},
			{
				"properties": {
					"primary": false
				},
				"id": "/subscriptions/26369c0f-46a0-43ef-a37b-6cc584450f37/resourceGroups/MENI-DP/providers/Microsoft.Network/networkInterfaces/meni-dp-FI-433_INSIDE"
			}]
		},
		"diagnosticsProfile": {
			"bootDiagnostics": {
				"enabled": true,
				"storageUri": "https://menidp.blob.core.windows.net/"
			}
		},
		"availabilitySet": {
			"id": "/subscriptions/26369c0f-46a0-43ef-a37b-6cc584450f37/resourceGroups/MENI-DP/providers/Microsoft.Compute/availabilitySets/meni-dp_34_SX_NS_AS"
		}
	},
	"location": "westus",
	"tags": {
		
	}
}
```
I see nothing that would suggest anything under linuxConfiguration is invalid... what is further puzzling is that it WORKS with another image. What sort of validation is being applied here...?!

**Comment by anuchandy** [comment]
I wonder the user image `/subscriptions/26369c0f-46a0-43ef-a37b-6cc584450f37/resourceGroups/MENI/providers/Microsoft.Compute/images/shieldx-dp-master` is the culprit here. How did you prepare this image? The way I create the user image is:

1. Create an Azure virtual machine with the base image (from azure image gallery) 
2. Login the vm and configure it (e.g. install the softwares)
3. Sysprep the virtual machine
4. Deallocate the  virtual machine using Deallocate API
5. Generalize the virtual machine using Generalize API
6. Capture the virtual machine using Capture API which produce the image.

Here is the [documentation](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/capture-image-resource)

Can you check the image is prepared following the above steps? If a image resource is captured without sysprep-ing it then it cannot be used as a source image to create multiple vms.

**Comment by menih** [comment]
Our image is custom Linux image. This is not windows image.

**Comment by anuchandy** [comment]
I see, sorry for wrong doc link. If you are preparing linux image then step 3 would be `sudo waagent –deprovision+user`

**Comment by menih** [comment]
Yes. We know that. There is nothing wrong with the image...it deploys but
sometimes we get this error. So it is not the image...

On Tue, Jan 16, 2018 at 1:23 PM, Anu Thomas Chandy <notifications@github.com

**Comment by hovsepm** [comment]
@menih Could you provide HTTP message headers (excluding Bearer token) of the failed call? We will need to contact back-end service for the further investigation to find the root cause of the intermittent failures in your scenario.

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please reopen this issue if it is still a concern.
