### ISSUE TITLE
[BUG] ClassCastException: MonoSingle$SingleSubscriber cannot be cast to Fuseable$QueueSubscription on 4.13.1

### ISSUE THREAD

**Issue by kuaw26** [Azure/azure-sdk-for-java#20106]
**Describe the bug**
Updated azure-cosmos from 4.7.1 to 4.13.1
Code was not changed.
After service started I've got exception: **Cannot cast 'reactor.core.publisher.MonoSingle$SingleSubscriber' to 'reactor.core.Fuseable$QueueSubscription'**

***Exception or Stack Trace***
```
Caused by: java.lang.ClassCastException: reactor.core.publisher.MonoSingle$SingleSubscriber cannot be cast to reactor.core.Fuseable$QueueSubscription
at reactor.core.publisher.FluxPeekFuseable$PeekFuseableConditionalSubscriber.onSubscribe(FluxPeekFuseable.java:470)
at reactor.core.publisher.MonoSingle$SingleSubscriber.onSubscribe(MonoSingle.java:115)
at reactor.core.publisher.FluxMap$MapSubscriber.onSubscribe(FluxMap.java:92)
at reactor.core.publisher.SerializedSubscriber.onSubscribe(SerializedSubscriber.java:65)
at reactor.core.publisher.FluxRetryWhen.subscribe(FluxRetryWhen.java:63)
at reactor.core.publisher.MonoRetryWhen.subscribeOrReturn(MonoRetryWhen.java:46)
at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
at reactor.core.publisher.MonoDeferContextual.subscribe(MonoDeferContextual.java:55)
at reactor.core.publisher.Mono.subscribe(Mono.java:4099)
at reactor.core.publisher.Mono.block(Mono.java:1702)
at com.azure.cosmos.CosmosContainer.blockItemResponse(CosmosContainer.java:235)
at com.azure.cosmos.CosmosContainer.upsertItem(CosmosContainer.java:211)
```

**Expected behavior**
Code should work in the same way on 4.13.1 as on 4.7.1 

**Setup (please complete the following information):**
 - OS: iOS
 - IDE : IntelliJ
 - Version of the Library used: 4.13.1

**Additional context**
Spring Boot 2.4.4

**Comment by luczsoma** [comment]
@kuaw26 I'm experiencing the same with Spring Boot 2.4.4. However, with 2.4.3, both 4.13.0 and 4.13.1 seems to work fine.

**Comment by kuaw26** [comment]
@luczsoma Thanks! Now it works as expected.

I can see that Spring Boot **2.4.4** reactore-core **3.4.4** is used and with Spring Boot **2.4.3** reactore-core **3.4.3** is used.

So, something changed in reactore-core between 3.4.3 & 3.4.4.

**Comment by alzimmermsft** [comment]
@luczsoma, @kuaw26, it looks like the class hierarchy changed between `3.4.3` and `3.4.4`: https://github.com/reactor/reactor-core/pull/2632/files#diff-35c8c931d89d8295d122990bede4310bee629c3f2473686402ab965a524ba86cR62

FYI: @kushagraThapar

**Comment by sebashepin** [comment]
Can easily repro on 4.13.1 whenever the observer chain gets an internal error. 

Seems to be related to https://github.com/reactor/reactor-core/issues/2152, reactor team says its fixed on 3.3.6

**Comment by aliakhtar** [comment]
+1 - encountered this in new project using 2.4.4 - downgrading to 2.4.3 fixes this issue.

**Comment by alzimmermsft** [comment]
Closing this as resolved by Reactor Core in newer releases, their issue: https://github.com/reactor/reactor-core/issues/2663
