### ISSUE TITLE
Configuring socket timeout for Azure client

### ISSUE THREAD

**Issue by dharshanr** [Azure/azure-sdk-for-java#2013]
Hi,

Is there a way to configure socket timeout for the Azure client? We are intermittently seeing some socket timeout errors like this

 ERROR ~ java.lang.RuntimeException: java.net.SocketTimeoutException: Read timed out
at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:464)
at rx.observables.BlockingObservable.last(BlockingObservable.java:227)
at com.microsoft.azure.management.resources.fluentcore.arm.collection.implementation.GroupableResourcesImpl.getById(GroupableResourcesImpl.java:68)
at com.microsoft.azure.management.resources.fluentcore.arm.collection.implementation.GroupableResourcesImpl.getById(GroupableResourcesImpl.java:33)

**Comment by yungezz** [comment]
hi @ChenTanyi could you pls have a look? thanks.

**Comment by ChenTanyi** [comment]
@dharshanr The `withConnectionTimeout` and `withReadTimeout` have been added 4 years ago. Did you miss it? https://github.com/Azure/azure-libraries-for-java/blame/bc5a8263bb43d6f03ef6cc74d99efe8f1c925b29/azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/fluentcore/arm/AzureConfigurable.java#L74

Example:
```java
Azure.configure().withConnectionTimeout(20, TimeUnit.SECONDS).authenticate(...)
```

If the above example doesn't solve your problem, feel free to reopen the issue.
