### ISSUE TITLE
[BUG] Failed to write to cosmosdb with cosmosdb-spark connector due to nullpointer in createReplacingDocumentProducersOnSplit

### ISSUE THREAD

**Issue by tritm78** [Azure/azure-sdk-for-java#20201]
**Describe the bug**
we have been using cosmosdb-spark connector to write spark dataframe data to cosmosdb in batch from Databricks, and have no issue with old version azure-cosmosdb-spark_2.4.0_2.11:3.3.0. Recently, need to upgrade Databricks to newer runtime 7.6, therefore use the new version azure-cosmos-spark_3-1_2-12:4.0.0-beta.1. The new version needs to update the write configuration with new key/values, testing with small data set seems fine, but when running with the job, the write API is failing with java.lang.NullPointerException in azure_cosmos_spark.com.azure.cosmos.implementation.query.DocumentProducer.createReplacingDocumentProducersOnSplit(DocumentProducer.java:234)

***Exception or Stack Trace***
```
/local_disk0/spark-2e303c88-55eb-424a-9b14-2b5365c0e157/userFiles-b61262eb-3f8b-4139-86a0-c3a25e60717b/preprovisionpredict_adhoc.trtran.20210328.154641.zip/preprovisionpredict/shared/CosmosDBClientWrapperV4.py in create_container_and_update_index(self, database_link, data_container_name, data_partition_key, data_entities, index_container_name, index_partition_key, index_entity, write_batch_size, max_retry_cnt, wait_between_retry, rename_container, max_containers_to_keep, cosmosdb_jar_spark3)
    276         # 3. Write data to the container
    277         if cosmosdb_jar_spark3:
--> 278             self.write_cosmosdb_in_bulk_spark3(database_link, data_container_name, data_entities, write_batch_size)
    279         else:
    280             self.write_cosmosdb_in_bulk(database_link, data_container_name, data_entities, write_batch_size)

/local_disk0/spark-2e303c88-55eb-424a-9b14-2b5365c0e157/userFiles-b61262eb-3f8b-4139-86a0-c3a25e60717b/preprovisionpredict_adhoc.trtran.20210328.154641.zip/preprovisionpredict/shared/CosmosDBClientWrapperV4.py in write_cosmosdb_in_bulk_spark3(self, database_link, container_id, spark_df_entities, write_batch_size)
    132 
    133         logger.info("Writing spark dataframe dataset of {0} rows in bulk with writeConfig = {1}".format(spark_df_entities.count(), writeConfig))
--> 134         spark_df_entities.write.format("cosmos.items").options(**writeConfig).mode("append").save()
    135         logger.info("Elapsed time: {}".format(time.time() - start))
    136 

/databricks/spark/python/pyspark/sql/readwriter.py in save(self, path, format, mode, partitionBy, **options)
    826             self.format(format)
    827         if path is None:
--> 828             self._jwrite.save()
    829         else:
    830             self._jwrite.save(path)

/databricks/spark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1303         answer = self.gateway_client.send_command(command)
   1304         return_value = get_return_value(
-> 1305             answer, self.gateway_client, self.target_id, self.name)
   1306 
   1307         for temp_arg in temp_args:

/databricks/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
    125     def deco(*a, **kw):
    126         try:
--> 127             return f(*a, **kw)
    128         except py4j.protocol.Py4JJavaError as e:
    129             converted = convert_exception(e.java_exception)

/databricks/spark/python/lib/py4j-0.10.9-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:
    330                 raise Py4JError(
Py4JJavaError: An error occurred while calling o1516.save.
: java.lang.NullPointerException
	at azure_cosmos_spark.com.azure.cosmos.implementation.query.DocumentProducer.createReplacingDocumentProducersOnSplit(DocumentProducer.java:234)
	at azure_cosmos_spark.com.azure.cosmos.implementation.query.DocumentProducer.lambda$splitProof$5(DocumentProducer.java:221)
	at azure_cosmos_spark.reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:378)
	at azure_cosmos_spark.reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:121)
	at azure_cosmos_spark.reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1782)
	at azure_cosmos_spark.reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:241)
	at azure_cosmos_spark.reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:73)
	at azure_cosmos_spark.reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2344)
	at azure_cosmos_spark.reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:2152)
	at azure_cosmos_spark.reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onSubscribe(FluxOnErrorResume.java:68)
	at azure_cosmos_spark.reactor.core.publisher.MonoJust.subscribe(MonoJust.java:54)
	at azure_cosmos_spark.reactor.core.publisher.Mono.subscribe(Mono.java:4252)
	at azure_cosmos_spark.reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:97)
	at azure_cosmos_spark.reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onError(FluxMapFuseable.java:134)
	at azure_cosmos_spark.reactor.core.publisher.MonoSingle$SingleSubscriber.onError(MonoSingle.java:141)
	at azure_cosmos_spark.reactor.core.publisher.FluxFlatMap$FlatMapMain.checkTerminated(FluxFlatMap.java:834)
	at azure_cosmos_spark.reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:600)
	at azure_cosmos_spark.reactor.core.publisher.FluxFlatMap$FlatMapMain.drain(FluxFlatMap.java:580)
	at azure_cosmos_spark.reactor.core.publisher.FluxFlatMap$FlatMapMain.innerError(FluxFlatMap.java:855)
	at azure_cosmos_spark.reactor.core.publisher.FluxFlatMap$FlatMapInner.onError(FluxFlatMap.java:1006)
	at azure_cosmos_spark.reactor.core.publisher.Operators$MonoSubscriber.onError(Operators.java:1829)
	at azure_cosmos_spark.reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.signalCached(MonoCacheTime.java:323)
	at azure_cosmos_spark.reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.onError(MonoCacheTime.java:346)
	at azure_cosmos_spark.reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onError(MonoPeekTerminal.java:251)
	at azure_cosmos_spark.reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onError(MonoPeekTerminal.java:251)
	at azure_cosmos_spark.reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:165)
	at azure_cosmos_spark.reactor.core.publisher.MonoFlatMap$FlatMapMain.secondError(MonoFlatMap.java:185)
	at azure_cosmos_spark.reactor.core.publisher.MonoFlatMap$FlatMapInner.onError(MonoFlatMap.java:251)
	at azure_cosmos_spark.reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onError(MonoCollectList.java:106)
	at azure_cosmos_spark.reactor.core.publisher.FluxFlatMap$FlatMapMain.checkTerminated(FluxFlatMap.java:834)
	at azure_cosmos_spark.reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:600)
	at azure_cosmos_spark.reactor.core.publisher.FluxFlatMap$FlatMapMain.drain(FluxFlatMap.java:580)
	at azure_cosmos_spark.reactor.core.publisher.FluxFlatMap$FlatMapMain.onError(FluxFlatMap.java:443)
	at azure_cosmos_spark.reactor.core.publisher.FluxMergeSequential$MergeSequentialMain.drain(FluxMergeSequential.java:345)
	at azure_cosmos_spark.reactor.core.publisher.FluxMergeSequential$MergeSequentialMain.innerError(FluxMergeSequential.java:312)
	at azure_cosmos_spark.reactor.core.publisher.FluxMergeSequential$MergeSequentialInner.onError(FluxMergeSequential.java:571)
	at azure_cosmos_spark.reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:126)
	at azure_cosmos_spark.reactor.core.publisher.SerializedSubscriber.onError(SerializedSubscriber.java:124)
	at azure_cosmos_spark.reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.whenError(FluxRetryWhen.java:213)
	at azure_cosmos_spark.reactor.core.publisher.FluxRetryWhen$RetryWhenOtherSubscriber.onError(FluxRetryWhen.java:255)
	at azure_cosmos_spark.reactor.core.publisher.FluxFlatMap$FlatMapMain.checkTerminated(FluxFlatMap.java:834)
	at azure_cosmos_spark.reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:600)
	at azure_cosmos_spark.reactor.core.publisher.FluxFlatMap$FlatMapMain.drain(FluxFlatMap.java:580)
	at azure_cosmos_spark.reactor.core.publisher.FluxFlatMap$FlatMapMain.innerError(FluxFlatMap.java:855)
	at azure_cosmos_spark.reactor.core.publisher.FluxFlatMap$FlatMapInner.onError(FluxFlatMap.java:1006)
	at azure_cosmos_spark.reactor.core.publisher.FluxFlatMap$FlatMapMain.checkTerminated(FluxFlatMap.java:834)
	at azure_cosmos_spark.reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:600)
	at azure_cosmos_spark.reactor.core.publisher.FluxFlatMap$FlatMapMain.drain(FluxFlatMap.java:580)
	at azure_cosmos_spark.reactor.core.publisher.FluxFlatMap$FlatMapMain.onError(FluxFlatMap.java:443)
	at azure_cosmos_spark.reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:408)
	at azure_cosmos_spark.reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2344)
	at azure_cosmos_spark.reactor.core.publisher.FluxFlatMap$FlatMapMain.onSubscribe(FluxFlatMap.java:363)
	at azure_cosmos_spark.reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:191)
	at azure_cosmos_spark.reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53)
	at azure_cosmos_spark.reactor.core.publisher.Flux.subscribe(Flux.java:8343)
	at azure_cosmos_spark.reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:418)
	at azure_cosmos_spark.reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114)
	at azure_cosmos_spark.reactor.core.publisher.DirectProcessor$DirectInner.onNext(DirectProcessor.java:339)
	at azure_cosmos_spark.reactor.core.publisher.DirectProcessor.onNext(DirectProcessor.java:148)
	at azure_cosmos_spark.reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:99)
	at azure_cosmos_spark.reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.onError(FluxRetryWhen.java:180)
	at azure_cosmos_spark.reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onError(FluxMapFuseable.java:134)
	at azure_cosmos_spark.reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onError(FluxHide.java:132)
	at azure_cosmos_spark.reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:126)
	at azure_cosmos_spark.reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:100)
	at azure_cosmos_spark.reactor.core.publisher.Operators.error(Operators.java:196)
	at azure_cosmos_spark.reactor.core.publisher.MonoError.subscribe(MonoError.java:52)
	at azure_cosmos_spark.reactor.core.publisher.Mono.subscribe(Mono.java:4252)
	at azure_cosmos_spark.reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:97)
	at azure_cosmos_spark.reactor.core.publisher.SerializedSubscriber.onError(SerializedSubscriber.java:124)
	at azure_cosmos_spark.reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.whenError(FluxRetryWhen.java:213)
	at azure_cosmos_spark.reactor.core.publisher.FluxRetryWhen$RetryWhenOtherSubscriber.onError(FluxRetryWhen.java:255)
	at azure_cosmos_spark.reactor.core.publisher.FluxFlatMap$FlatMapMain.checkTerminated(FluxFlatMap.java:834)
	at azure_cosmos_spark.reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:600)
	at azure_cosmos_spark.reactor.core.publisher.FluxFlatMap$FlatMapMain.drain(FluxFlatMap.java:580)
	at azure_cosmos_spark.reactor.core.publisher.FluxFlatMap$FlatMapMain.innerError(FluxFlatMap.java:855)
	at azure_cosmos_spark.reactor.core.publisher.FluxFlatMap$FlatMapInner.onError(FluxFlatMap.java:1006)
	at azure_cosmos_spark.reactor.core.publisher.Operators.error(Operators.java:196)
	at azure_cosmos_spark.reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:181)
	at azure_cosmos_spark.reactor.core.publisher.FluxFlatMap.subscribeOrReturn(FluxFlatMap.java:92)
	at azure_cosmos_spark.reactor.core.publisher.Flux.subscribe(Flux.java:8343)
	at azure_cosmos_spark.reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:418)
	at azure_cosmos_spark.reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114)
	at azure_cosmos_spark.reactor.core.publisher.DirectProcessor$DirectInner.onNext(DirectProcessor.java:339)
	at azure_cosmos_spark.reactor.core.publisher.DirectProcessor.onNext(DirectProcessor.java:148)
	at azure_cosmos_spark.reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:99)
	at azure_cosmos_spark.reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.onError(FluxRetryWhen.java:180)
	at azure_cosmos_spark.reactor.core.publisher.MonoSingle$SingleSubscriber.onError(MonoSingle.java:141)
	at azure_cosmos_spark.reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:100)
	at azure_cosmos_spark.reactor.core.publisher.Operators.error(Operators.java:196)
	at azure_cosmos_spark.reactor.core.publisher.MonoError.subscribe(MonoError.java:52)
	at azure_cosmos_spark.reactor.core.publisher.Mono.subscribe(Mono.java:4252)
	at azure_cosmos_spark.reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:97)
	at azure_cosmos_spark.reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onError(FluxMapFuseable.java:134)
	at azure_cosmos_spark.reactor.core.publisher.MonoFlatMap$FlatMapMain.secondError(MonoFlatMap.java:185)
	at azure_cosmos_spark.reactor.core.publisher.MonoFlatMap$FlatMapInner.onError(MonoFlatMap.java:251)
	at azure_cosmos_spark.reactor.core.publisher.MonoSingle$SingleSubscriber.onError(MonoSingle.java:141)
	at azure_cosmos_spark.reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:126)
	at azure_cosmos_spark.reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:106)
	at azure_cosmos_spark.reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:67)
	at azure_cosmos_spark.reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:192)
	at azure_cosmos_spark.reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:112)
	at azure_cosmos_spark.reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:213)
	at azure_cosmos_spark.reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:123)
	at azure_cosmos_spark.reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:178)
	at azure_cosmos_spark.reactor.core.publisher.FluxContextStart$ContextStartSubscriber.onNext(FluxContextStart.java:96)
	at azure_cosmos_spark.reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1782)
	at azure_cosmos_spark.reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:121)
	at azure_cosmos_spark.reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:252)
	at azure_cosmos_spark.reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:136)
	at azure_cosmos_spark.reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:383)
	at azure_cosmos_spark.reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:373)
	at azure_cosmos_spark.reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:429)
	at azure_cosmos_spark.reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:655)
	at azure_cosmos_spark.reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:96)
	at azure_cosmos_spark.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at azure_cosmos_spark.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at azure_cosmos_spark.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at azure_cosmos_spark.io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at azure_cosmos_spark.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at azure_cosmos_spark.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at azure_cosmos_spark.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at azure_cosmos_spark.io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at azure_cosmos_spark.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at azure_cosmos_spark.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at azure_cosmos_spark.io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at azure_cosmos_spark.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at azure_cosmos_spark.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at azure_cosmos_spark.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at azure_cosmos_spark.io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1533)
	at azure_cosmos_spark.io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1282)
	at azure_cosmos_spark.io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1329)
	at azure_cosmos_spark.io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
	at azure_cosmos_spark.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
	at azure_cosmos_spark.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at azure_cosmos_spark.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at azure_cosmos_spark.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at azure_cosmos_spark.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at azure_cosmos_spark.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at azure_cosmos_spark.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at azure_cosmos_spark.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at azure_cosmos_spark.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at azure_cosmos_spark.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at azure_cosmos_spark.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at azure_cosmos_spark.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at azure_cosmos_spark.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at azure_cosmos_spark.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at azure_cosmos_spark.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at azure_cosmos_spark.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at azure_cosmos_spark.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: java.lang.Exception: #block terminated with an error
		at azure_cosmos_spark.reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
		at azure_cosmos_spark.reactor.core.publisher.Mono.block(Mono.java:1685)
		at com.azure.cosmos.spark.CosmosTableSchemaInferrer$.inferSchema(CosmosTableSchemaInferrer.scala:86)
		at com.azure.cosmos.spark.ItemsTable.inferSchema(ItemsTable.scala:94)
		at com.azure.cosmos.spark.ItemsTable.$anonfun$schema$1(ItemsTable.scala:85)
		at scala.Option.getOrElse(Option.scala:189)
		at com.azure.cosmos.spark.ItemsTable.schema(ItemsTable.scala:85)
		at com.azure.cosmos.spark.CosmosItemsDataSource.inferSchema(CosmosItemsDataSource.scala:31)
		at org.apache.spark.sql.execution.datasources.v2.DataSourceV2Utils$.getTableFromProvider(DataSourceV2Utils.scala:81)
		at org.apache.spark.sql.DataFrameWriter.getTable$1(DataFrameWriter.scala:347)
		at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:363)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
		at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)
		at py4j.Gateway.invoke(Gateway.java:295)
		at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
		at py4j.commands.CallCommand.execute(CallCommand.java:79)
		at py4j.GatewayConnection.run(GatewayConnection.java:251)
		... 1 more
```

**To Reproduce**
1. create a spark dataframe with many records (my failed case has about 5500 rows)
2. call to the code to write the spark dataframe to cosmosdb

***Code Snippet to reproduce***
`        # set up Write configuration
        writeConfig = {
            "spark.cosmos.accountEndpoint" : self.url_connection,
            "spark.cosmos.accountKey" : self.client_secret, 
            "spark.cosmos.database" : database_name,
            "spark.cosmos.container" : container_id,
            "spark.cosmos.write.strategy" : "ItemOverwrite", # upsert
            "spark.cosmos.write.maxConcurrency" : 3
        }

        logger.info("Writing spark dataframe dataset of {0} rows in bulk with writeConfig = {1}".format(spark_df_entities.count(), writeConfig))
        spark_df_entities.write.format("cosmos.items").options(**writeConfig).mode("append").save()`

**Expected behavior**
It should write data to cosmosdb successfully with the above code snippet.

**Setup info**
Databricks and Pyspark
library: https://github.com/Azure/azure-sdk-for-java/blob/feature/cosmos/spark30/sdk/cosmos/azure-cosmos-spark_3-1_2-12/docs/quick-start.md

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by joshfree** [comment]
@kushagraThapar could you please take a look

**Comment by kushagraThapar** [comment]
Routing this to @moderakh  - please take a look at this issue with the latest preview of spark connector.

**Comment by moderakh** [comment]
Thank you @kushagraThapar. Let's use "cosmos:spark3" tag for the spark related issues?

**Comment by moderakh** [comment]
@mbhaskar the NPE is coming from the query stack of cosmos core sdk.

```
: java.lang.NullPointerException
	at azure_cosmos_spark.com.azure.cosmos.implementation.query.DocumentProducer.createReplacingDocumentProducersOnSplit(DocumentProducer.java:234)
	at azure_cosmos_spark.com.azure.cosmos.implementation.query.DocumentProducer.lambda$splitProof$5(DocumentProducer.java:221)
```

**Comment by moderakh** [comment]
@tritm78 could you please upgrade to spark 3.1.1, Databricks Runtime 8.x?

There is a bug in spark 3.0.x runtime which invokes schema inference on the write path. Cosmos DB connector has a corner case scenario bug in handling query for schema inference. 

If you move to spark 3.1.1, the schema inference won't be invoked on the write path and hence you won't hit the connector query bug during ingestion workload.

**Comment by tritm78** [comment]
@moderakh, thank you for taking a look at the issue.

I will try to upgrade to Spark 3.1.1, Databricks Runtime 8.x and report back.

**Comment by moderakh** [comment]
@tritm78 also I am assuming the cosmos container exists and is pre-created by you before you try to ingest to it.

could you please confirm?

**Comment by xinlian12** [comment]
Close due to inactivity.
