### ISSUE TITLE
[BUG] CosmoDB health check via Mongo driver reports an "internal error"

### ISSUE THREAD

**Issue by jakubnabrdalik** [Azure/azure-sdk-for-java#20249]
**Describe the bug**

We are using CosmoDB via a MongoDB Reactive driver on a brand new Spring Boot app (boot version 2.3.9.RELEASE)
Libs version:
org.springframework.boot:spring-boot-starter-data-mongodb-reactive -> 2.3.9.RELEASE
org.mongodb:mongodb-driver-reactivestreams:4.0.5

On regular basis we get an "Internal error" from CosmoDB when the driver performs a health check.

***Exception or Stack Trace***

```
2021-03-30 08:29:35.635  WARN 1 --- [ntLoopGroup-2-6] o.s.b.a.m.MongoReactiveHealthIndicator   : Mongo health check failed

org.springframework.data.mongodb.UncategorizedMongoDbException: Command failed with error 1 (InternalError): '[ActivityId=f858da39-395e-4e92-962f-b3e9e4029ca9] Internal error.' on server cdb-ms-prod-westeurope1-cm5.documents.azure.com:10255. The full response is {"ok": 0.0, "errmsg": "[ActivityId=f858da39-395e-4e92-962f-b3e9e4029ca9] Internal error.", "code": 1, "codeName": "InternalError"}; nested exception is com.mongodb.MongoCommandException: Command failed with error 1 (InternalError): '[ActivityId=f858da39-395e-4e92-962f-b3e9e4029ca9] Internal error.' on server cdb-ms-prod-westeurope1-cm5.documents.azure.com:10255. The full response is {"ok": 0.0, "errmsg": "[ActivityId=f858da39-395e-4e92-962f-b3e9e4029ca9] Internal error.", "code": 1, "codeName": "InternalError"}
        at org.springframework.data.mongodb.core.MongoExceptionTranslator.translateExceptionIfPossible(MongoExceptionTranslator.java:133) ~[spring-data-mongodb-3.0.7.RELEASE.jar!/:3.0.7.RELEASE]
        Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
Assembly trace from producer [reactor.core.publisher.FluxOnErrorResume] :
        reactor.core.publisher.Flux.onErrorMap
        org.springframework.data.mongodb.core.ReactiveMongoTemplate.createFlux(ReactiveMongoTemplate.java:619)
Error has been observed at the following site(s):
        |_ Flux.onErrorMap ⇢ at org.springframework.data.mongodb.core.ReactiveMongoTemplate.createFlux(ReactiveMongoTemplate.java:619)
        |_       Flux.next ⇢ at org.springframework.data.mongodb.core.ReactiveMongoTemplate.executeCommand(ReactiveMongoTemplate.java:472)
        |_                 ⇢ at org.springframework.data.mongodb.core.ReactiveMongoTemplate.executeCommand(ReactiveMongoTemplate.java:460)
        |_                 ⇢ at org.springframework.data.mongodb.core.ReactiveMongoTemplate.executeCommand(ReactiveMongoTemplate.java:452)
        |_        Mono.map ⇢ at org.springframework.boot.actuate.mongo.MongoReactiveHealthIndicator.doHealthCheck(MongoReactiveHealthIndicator.java:47)
Stack trace:
                at org.springframework.data.mongodb.core.MongoExceptionTranslator.translateExceptionIfPossible(MongoExceptionTranslator.java:133) ~[spring-data-mongodb-3.0.7.RELEASE.jar!/:3.0.7.RELEASE]
                at org.springframework.data.mongodb.core.ReactiveMongoTemplate.potentiallyConvertRuntimeException(ReactiveMongoTemplate.java:2814) ~[spring-data-mongodb-3.0.7.RELEASE.jar!/:3.0.7.RELEASE]
                at org.springframework.data.mongodb.core.ReactiveMongoTemplate.lambda$translateException$90(ReactiveMongoTemplate.java:2797) ~[spring-data-mongodb-3.0.7.RELEASE.jar!/:3.0.7.RELEASE]
                at reactor.core.publisher.Flux.lambda$onErrorMap$28(Flux.java:6536) ~[reactor-core-3.3.14.RELEASE.jar!/:3.3.14.RELEASE]
                at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:88) ~[reactor-core-3.3.14.RELEASE.jar!/:3.3.14.RELEASE]
                at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onError(MonoFlatMapMany.java:247) ~[reactor-core-3.3.14.RELEASE.jar!/:3.3.14.RELEASE]
                at com.mongodb.reactivestreams.client.internal.AbstractSubscription.onError(AbstractSubscription.java:142) ~[mongodb-driver-reactivestreams-4.0.5.jar!/:na]
                at com.mongodb.reactivestreams.client.internal.SingleResultCallbackSubscription.lambda$requestInitialData$0(SingleResultCallbackSubscription.java:41) ~[mongodb-driver-reactivestreams-4.0.5.jar!/:na]
                at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:48) ~[mongodb-driver-core-4.0.5.jar!/:na]
                at com.mongodb.internal.async.client.OperationExecutorImpl$1$1$1.onResult(OperationExecutorImpl.java:92) ~[mongodb-driver-core-4.0.5.jar!/:na]
                at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:48) ~[mongodb-driver-core-4.0.5.jar!/:na]
                at com.mongodb.internal.operation.OperationHelper$ReferenceCountedReleasingWrappedCallback.onResult(OperationHelper.java:411) ~[mongodb-driver-core-4.0.5.jar!/:na]
                at com.mongodb.internal.operation.CommandOperationHelper$8.call(CommandOperationHelper.java:413) ~[mongodb-driver-core-4.0.5.jar!/:na]
                at com.mongodb.internal.operation.OperationHelper$7.onResult(OperationHelper.java:613) ~[mongodb-driver-core-4.0.5.jar!/:na]
                at com.mongodb.internal.operation.OperationHelper$7.onResult(OperationHelper.java:610) ~[mongodb-driver-core-4.0.5.jar!/:na]
                at com.mongodb.internal.connection.DefaultServer$1.onResult(DefaultServer.java:112) ~[mongodb-driver-core-4.0.5.jar!/:na]
                at com.mongodb.internal.connection.DefaultServer$1.onResult(DefaultServer.java:103) ~[mongodb-driver-core-4.0.5.jar!/:na]
                at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:48) ~[mongodb-driver-core-4.0.5.jar!/:na]
                at com.mongodb.internal.connection.DefaultConnectionPool$2.onResult(DefaultConnectionPool.java:217) ~[mongodb-driver-core-4.0.5.jar!/:na]
                at com.mongodb.internal.connection.DefaultConnectionPool$2.onResult(DefaultConnectionPool.java:207) ~[mongodb-driver-core-4.0.5.jar!/:na]
                at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection$1.onResult(DefaultConnectionPool.java:448) ~[mongodb-driver-core-4.0.5.jar!/:na]
                at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection$1.onResult(DefaultConnectionPool.java:442) ~[mongodb-driver-core-4.0.5.jar!/:na]
                at com.mongodb.internal.connection.UsageTrackingInternalConnection$1.onResult(UsageTrackingInternalConnection.java:61) ~[mongodb-driver-core-4.0.5.jar!/:na]
                at com.mongodb.internal.connection.UsageTrackingInternalConnection$1.onResult(UsageTrackingInternalConnection.java:57) ~[mongodb-driver-core-4.0.5.jar!/:na]
                at com.mongodb.internal.connection.InternalStreamConnection$1$1.onResult(InternalStreamConnection.java:159) ~[mongodb-driver-core-4.0.5.jar!/:na]
                at com.mongodb.internal.connection.InternalStreamConnection$1$1.onResult(InternalStreamConnection.java:154) ~[mongodb-driver-core-4.0.5.jar!/:na]
                at com.mongodb.internal.connection.InternalStreamConnectionInitializer$1.onResult(InternalStreamConnectionInitializer.java:77) ~[mongodb-driver-core-4.0.5.jar!/:na]
                at com.mongodb.internal.connection.InternalStreamConnectionInitializer$1.onResult(InternalStreamConnectionInitializer.java:73) ~[mongodb-driver-core-4.0.5.jar!/:na]
                at com.mongodb.internal.connection.InternalStreamConnectionInitializer$2.onResult(InternalStreamConnectionInitializer.java:169) ~[mongodb-driver-core-4.0.5.jar!/:na]
                at com.mongodb.internal.connection.InternalStreamConnectionInitializer$2.onResult(InternalStreamConnectionInitializer.java:159) ~[mongodb-driver-core-4.0.5.jar!/:na]
                at com.mongodb.internal.connection.CommandHelper$1.onResult(CommandHelper.java:57) ~[mongodb-driver-core-4.0.5.jar!/:na]
                at com.mongodb.internal.connection.CommandHelper$1.onResult(CommandHelper.java:53) ~[mongodb-driver-core-4.0.5.jar!/:na]
                at com.mongodb.internal.connection.InternalStreamConnection$2$1.onResult(InternalStreamConnection.java:400) ~[mongodb-driver-core-4.0.5.jar!/:na]
                at com.mongodb.internal.connection.InternalStreamConnection$2$1.onResult(InternalStreamConnection.java:375) ~[mongodb-driver-core-4.0.5.jar!/:na]
                at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback$MessageCallback.onResult(InternalStreamConnection.java:676) ~[mongodb-driver-core-4.0.5.jar!/:na]
                at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback$MessageCallback.onResult(InternalStreamConnection.java:643) ~[mongodb-driver-core-4.0.5.jar!/:na]
                at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:513) ~[mongodb-driver-core-4.0.5.jar!/:na]
                at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:510) ~[mongodb-driver-core-4.0.5.jar!/:na]
                at com.mongodb.connection.netty.NettyStream.readAsync(NettyStream.java:232) ~[mongodb-driver-core-4.0.5.jar!/:na]
                at com.mongodb.internal.connection.InternalStreamConnection.readAsync(InternalStreamConnection.java:510) ~[mongodb-driver-core-4.0.5.jar!/:na]
                at com.mongodb.internal.connection.InternalStreamConnection.access$1000(InternalStreamConnection.java:75) ~[mongodb-driver-core-4.0.5.jar!/:na]
                at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback.onResult(InternalStreamConnection.java:633) ~[mongodb-driver-core-4.0.5.jar!/:na]
                at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback.onResult(InternalStreamConnection.java:618) ~[mongodb-driver-core-4.0.5.jar!/:na]
                at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:513) ~[mongodb-driver-core-4.0.5.jar!/:na]
                at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:510) ~[mongodb-driver-core-4.0.5.jar!/:na]
                at com.mongodb.connection.netty.NettyStream.readAsync(NettyStream.java:232) ~[mongodb-driver-core-4.0.5.jar!/:na]
                at com.mongodb.connection.netty.NettyStream.handleReadResponse(NettyStream.java:262) ~[mongodb-driver-core-4.0.5.jar!/:na]
                at com.mongodb.connection.netty.NettyStream.access$800(NettyStream.java:69) ~[mongodb-driver-core-4.0.5.jar!/:na]
                at com.mongodb.connection.netty.NettyStream$InboundBufferHandler.channelRead0(NettyStream.java:321) ~[mongodb-driver-core-4.0.5.jar!/:na]
                at com.mongodb.connection.netty.NettyStream$InboundBufferHandler.channelRead0(NettyStream.java:318) ~[mongodb-driver-core-4.0.5.jar!/:na]
                at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[netty-transport-4.1.59.Final.jar!/:4.1.59.Final]
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.59.Final.jar!/:4.1.59.Final]
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.59.Final.jar!/:4.1.59.Final]
                at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.59.Final.jar!/:4.1.59.Final]
                at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1533) ~[netty-handler-4.1.59.Final.jar!/:4.1.59.Final]
                at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1282) ~[netty-handler-4.1.59.Final.jar!/:4.1.59.Final]
                at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1329) ~[netty-handler-4.1.59.Final.jar!/:4.1.59.Final]
                at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:508) ~[netty-codec-4.1.59.Final.jar!/:4.1.59.Final]
                at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:447) ~[netty-codec-4.1.59.Final.jar!/:4.1.59.Final]
                at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[netty-codec-4.1.59.Final.jar!/:4.1.59.Final]
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.59.Final.jar!/:4.1.59.Final]
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.59.Final.jar!/:4.1.59.Final]
                at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.59.Final.jar!/:4.1.59.Final]
                at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.59.Final.jar!/:4.1.59.Final]
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.59.Final.jar!/:4.1.59.Final]
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.59.Final.jar!/:4.1.59.Final]
                at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.59.Final.jar!/:4.1.59.Final]
                at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[netty-transport-4.1.59.Final.jar!/:4.1.59.Final]
                at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) ~[netty-transport-4.1.59.Final.jar!/:4.1.59.Final]
                at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) ~[netty-transport-4.1.59.Final.jar!/:4.1.59.Final]
                at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) ~[netty-transport-4.1.59.Final.jar!/:4.1.59.Final]
                at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[netty-transport-4.1.59.Final.jar!/:4.1.59.Final]
                at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.59.Final.jar!/:4.1.59.Final]
                at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.59.Final.jar!/:4.1.59.Final]
                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.59.Final.jar!/:4.1.59.Final]
                at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
Caused by: com.mongodb.MongoCommandException: Command failed with error 1 (InternalError): '[ActivityId=f858da39-395e-4e92-962f-b3e9e4029ca9] Internal error.' on server cdb-ms-prod-westeurope1-cm5.documents.azure.com:10255. The full response is {"ok": 0.0, "errmsg": "[ActivityId=f858da39-395e-4e92-962f-b3e9e4029ca9] Internal error.", "code": 1, "codeName": "InternalError"}
        at com.mongodb.internal.connection.ProtocolHelper.getCommandFailureException(ProtocolHelper.java:175) ~[mongodb-driver-core-4.0.5.jar!/:na]
        Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
Assembly trace from producer [reactor.core.publisher.MonoFlatMapMany] :
        reactor.core.publisher.Mono.flatMapMany
        org.springframework.data.mongodb.core.ReactiveMongoTemplate.createFlux(ReactiveMongoTemplate.java:618)
Error has been observed at the following site(s):
        |_ Mono.flatMapMany ⇢ at org.springframework.data.mongodb.core.ReactiveMongoTemplate.createFlux(ReactiveMongoTemplate.java:618)
Stack trace:
                at com.mongodb.internal.connection.ProtocolHelper.getCommandFailureException(ProtocolHelper.java:175) ~[mongodb-driver-core-4.0.5.jar!/:na]
                at com.mongodb.internal.connection.InternalStreamConnection$2$1.onResult(InternalStreamConnection.java:389) ~[mongodb-driver-core-4.0.5.jar!/:na]
                at com.mongodb.internal.connection.InternalStreamConnection$2$1.onResult(InternalStreamConnection.java:375) ~[mongodb-driver-core-4.0.5.jar!/:na]
                at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback$MessageCallback.onResult(InternalStreamConnection.java:676) ~[mongodb-driver-core-4.0.5.jar!/:na]
                at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback$MessageCallback.onResult(InternalStreamConnection.java:643) ~[mongodb-driver-core-4.0.5.jar!/:na]
                at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:513) ~[mongodb-driver-core-4.0.5.jar!/:na]
                at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:510) ~[mongodb-driver-core-4.0.5.jar!/:na]
                at com.mongodb.connection.netty.NettyStream.readAsync(NettyStream.java:232) ~[mongodb-driver-core-4.0.5.jar!/:na]
                at com.mongodb.internal.connection.InternalStreamConnection.readAsync(InternalStreamConnection.java:510) ~[mongodb-driver-core-4.0.5.jar!/:na]
                at com.mongodb.internal.connection.InternalStreamConnection.access$1000(InternalStreamConnection.java:75) ~[mongodb-driver-core-4.0.5.jar!/:na]
                at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback.onResult(InternalStreamConnection.java:633) ~[mongodb-driver-core-4.0.5.jar!/:na]
                at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback.onResult(InternalStreamConnection.java:618) ~[mongodb-driver-core-4.0.5.jar!/:na]
                at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:513) ~[mongodb-driver-core-4.0.5.jar!/:na]
                at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:510) ~[mongodb-driver-core-4.0.5.jar!/:na]
                at com.mongodb.connection.netty.NettyStream.readAsync(NettyStream.java:232) ~[mongodb-driver-core-4.0.5.jar!/:na]
                at com.mongodb.connection.netty.NettyStream.handleReadResponse(NettyStream.java:262) ~[mongodb-driver-core-4.0.5.jar!/:na]
                at com.mongodb.connection.netty.NettyStream.access$800(NettyStream.java:69) ~[mongodb-driver-core-4.0.5.jar!/:na]
                at com.mongodb.connection.netty.NettyStream$InboundBufferHandler.channelRead0(NettyStream.java:321) ~[mongodb-driver-core-4.0.5.jar!/:na]
                at com.mongodb.connection.netty.NettyStream$InboundBufferHandler.channelRead0(NettyStream.java:318) ~[mongodb-driver-core-4.0.5.jar!/:na]
                at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[netty-transport-4.1.59.Final.jar!/:4.1.59.Final]
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.59.Final.jar!/:4.1.59.Final]
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.59.Final.jar!/:4.1.59.Final]
                at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.59.Final.jar!/:4.1.59.Final]
                at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1533) ~[netty-handler-4.1.59.Final.jar!/:4.1.59.Final]
                at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1282) ~[netty-handler-4.1.59.Final.jar!/:4.1.59.Final]
                at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1329) ~[netty-handler-4.1.59.Final.jar!/:4.1.59.Final]
                at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:508) ~[netty-codec-4.1.59.Final.jar!/:4.1.59.Final]
                at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:447) ~[netty-codec-4.1.59.Final.jar!/:4.1.59.Final]
                at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[netty-codec-4.1.59.Final.jar!/:4.1.59.Final]
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.59.Final.jar!/:4.1.59.Final]
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.59.Final.jar!/:4.1.59.Final]
                at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.59.Final.jar!/:4.1.59.Final]
                at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.59.Final.jar!/:4.1.59.Final]
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.59.Final.jar!/:4.1.59.Final]
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.59.Final.jar!/:4.1.59.Final]
                at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.59.Final.jar!/:4.1.59.Final]
                at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[netty-transport-4.1.59.Final.jar!/:4.1.59.Final]
                at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) ~[netty-transport-4.1.59.Final.jar!/:4.1.59.Final]
                at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) ~[netty-transport-4.1.59.Final.jar!/:4.1.59.Final]
                at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) ~[netty-transport-4.1.59.Final.jar!/:4.1.59.Final]
                at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[netty-transport-4.1.59.Final.jar!/:4.1.59.Final]
                at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.59.Final.jar!/:4.1.59.Final]
                at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.59.Final.jar!/:4.1.59.Final]
                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.59.Final.jar!/:4.1.59.Final]
                at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
```
Add the exception log and stack trace if available

**To Reproduce**

1. Create a new app via start.spring.io with Spring Boot  2.3.9.RELEASE and spring-boot-starter-data-mongodb-reactive
2. Configure DB access to CosmoDB
3. see periodic warnings in logs

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**

Health check should work

**Setup (please complete the following information):**
 - OS: docker build on openjdk:11-jre
 - IDE : none
 - Version of the Library used: Spring Boot 2.3.9.RELEASE,  spring-boot-starter-data-mongodb-reactive:2.3.9.RELEASE, org.mongodb:mongodb-driver-reactivestreams:4.0.5

**Additional context**

**Comment by joshfree** [comment]
@stliu @kushagraThapar could you please help route this?

**Comment by stliu** [comment]
From the exception message, it seems a server error, @kushagraThapar , could you help on this?
