### ISSUE TITLE
[Bug] Could not initialize class com.azure.identity.implementation.IdentityClient

### ISSUE THREAD

**Issue by NadiaBuf** [Azure/azure-sdk-for-java#20428]
Hello,

I have an error when i m trying to connect to miscrosoft graph using this code: 

```
  final ClientSecretCredential clientSecretCredential = new ClientSecretCredentialBuilder()
        .clientId(CLIENT_ID)
        .clientSecret(CLIENT_SECRET)
        .tenantId(TENANT_GUID)
        .build();
  final TokenCredentialAuthProvider tokenCredAuthProvider = new TokenCredentialAuthProvider(SCOPES, clientSecretCredential);
  final GraphServiceClient graphClient = GraphServiceClient
				.builder()
				.authenticationProvider(tokenCredAuthProvider)
				.buildClient();
   final com.microsoft.graph.models.User user = graphClient.me().buildRequest().get();
```

Error message:
```
   java.lang.NoClassDefFoundError: Could not initialize class com.azure.identity.implementation.IdentityClient
	at com.azure.identity.implementation.IdentityClientBuilder.build(IdentityClientBuilder.java:113)
	at com.azure.identity.ClientSecretCredential.<init>(ClientSecretCredential.java:50)
	at com.azure.identity.ClientSecretCredentialBuilder.build(ClientSecretCredentialBuilder.java:62)
	at com.test.testmsgrah.SampleBean.toString(SampleBean.java:76)
	at java.lang.String.valueOf(String.java:2994)
	at org.apache.jasper.runtime.JspWriterImpl.print(JspWriterImpl.java:614)
	at org.apache.jsp.UseBean_jsp._jspService(UseBean_jsp.java:76)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:111)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:411)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:473)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:377)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1682)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:318)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:734)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:673)
	at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:174)
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:415)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:282)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:459)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:167)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:201)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:175)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:561)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:565)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:545)
	at java.lang.Thread.run(Thread.java:748)
```

**Current dependencies used**
 ```   
    <dependencies>
        
        <dependency>
            <groupId>javax</groupId>
            <artifactId>javaee-web-api</artifactId>
            <version>7.0</version>
            <scope>provided</scope>
        </dependency>
        
       <dependency>
            <groupId>com.microsoft.graph</groupId>
            <artifactId>microsoft-graph</artifactId>
             <version>3.2.0</version>
          </dependency>
        
    </dependencies>
```
**Setup :** 

    OS: Windows10
    IDE : NetBeans 
    Java : 1.8.0_271

**Comment by joshfree** [comment]
@g2vinay PTAL

**Comment by g2vinay** [comment]
@NadiaBuf 

Thanks for reporting this issue.
This looks like a dependency conflict in your environment.
Can you add the azure-identity dependency directly in your pom file and see if the error still persists:

```
<dependency>
  <groupId>com.azure</groupId>
  <artifactId>azure-identity</artifactId>
  <version>1.2.5</version>
</dependency>
```

**Comment by mas9002** [comment]
@NadiaBuf @g2vinay I also face similar issue. Created  an isssue https://github.com/Azure/azure-sdk-for-java/issues/22028

**Comment by dincciftci** [comment]
@NadiaBuf my team has unfortunately encountered this issue before when introducing a dependency on the Azure SDK for Java. Luckily, we have a fix!

The problem for us was caused by a behavior in Spring where certain `MessageConverter` classes (which determine how serialized requests/responses such as JSON and XML are handled) are loaded. Spring looks at what's on the classpath and instantiates MessageConverter instances based on that. Azure brings in a dependency on a Jackson library, which inserts MappingJackson2XmlHttpMessageConverter as a high-priority message converter to be used for XML marshaling. Chances are that your app expects to use Jaxb2RootElementHttpMessageConverter (which is now lower priority and potentially unused).

The fix for us was to override the MessageConverters for our apps (via [this method](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/servlet/config/annotation/WebMvcConfigurationSupport.html#configureMessageConverters-java.util.List-)) and explicitly swap out the jackson-variant of the XML message converter. 

This page details out which message converters are enabled by default and when: https://www.baeldung.com/spring-httpmessageconverter-rest#2-the-default-message-converters

Hope this helps!

**Comment by g2vinay** [comment]
@NadiaBuf 
It appears that jackson libraries being used by JVM at build time are conflicting and not compatible.
I'd recommend to add Jackson dependencies being used by azure-identity directly in your pom file.

Let us know if you are still running into this issue, we can repoen it.
