### ISSUE TITLE
Azure Blob - Caller Class level stack trace hierarchy are getting Suppressed

### ISSUE THREAD

**Issue by abhikt48** [Azure/azure-sdk-for-java#20460]
We are migrating blob component from old SDK `azure-storage-5.5.0` to new SDK `azure-storage-blob-12.10.0`.  We developed blob component for integration with Mule ESB.

We are facing huge problem in error identification due to latest error StackTrace class hierarchy.

Problem - NEW Blob SDK add caller class level error hierarchy in **Suppressed section** which makes difficult in error identification. 

As we are using this component with Mule ESB, and Mule ESB by default does not print suppressed log at INFO level. We can't enable DEBUG mode in production system due to huge log entries.

As per my opinion - Caller class level error hierarchy should appear in actual StackTrace instead of Suppressed section. 

Please refer below ScreenShot, as you can see caller class level details are in Suppressed section. 

NOTE - 1) I observed this behaviour in approximately all blob operations upload, download etc.
            2) Please refer ScreenShot of **OLD SDK** as well, where we can clearly see caller class level hierarchy in top section.

Can I request you to take a look on this issue and let me know for any queries.

**New SDK- Sample Code to reproduce**
```
BlobContainerClient blobContainerClient = new BlobContainerClientBuilder().endpoint(BlobUtils.BLOB_SAS)
                                .containerName("test").buildClient();
BlobClient blobClient = blobContainerClient.getBlobClient("Unknown");
BlobInputStream blobInputStream = blobClient.openInputStream();
String downloadedBlobAsText = IOUtils.toString(blobInputStream, StandardCharsets.UTF_8);
System.out.println("** downloadedBlobAsText **" + downloadedBlobAsText);
```

**New SDK- StackTrace ScreenShot**
![image](https://user-images.githubusercontent.com/22897837/114016518-d56f7300-9862-11eb-86c7-2fdd2e569d1d.png)

**NEW SDK-Complete Error StackTrace**
```
com.azure.storage.blob.models.BlobStorageException: Status code 404, (BlobNotFound)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.azure.core.http.rest.RestProxy.instantiateUnexpectedException(RestProxy.java:337)
	at com.azure.core.http.rest.RestProxy.lambda$ensureExpectedStatus$8(RestProxy.java:398)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4252)
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FluxSwitchIfEmpty.java:75)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onComplete(MonoFlatMap.java:174)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onComplete(FluxDoFinally.java:138)
	at reactor.core.publisher.FluxHandle$HandleSubscriber.onComplete(FluxHandle.java:206)
	at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onComplete(FluxMap.java:262)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onComplete(FluxDoFinally.java:138)
	at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:195)
	at reactor.core.publisher.FluxContextStart$ContextStartSubscriber.onNext(FluxContextStart.java:96)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1782)
	at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:121)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:252)
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:136)
	at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:383)
	at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:373)
	at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:429)
	at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:655)
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:96)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1533)
	at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1294)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1331)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
		at reactor.core.publisher.Mono.block(Mono.java:1685)
		at com.azure.storage.common.implementation.StorageImplUtils.blockWithOptionalTimeout(StorageImplUtils.java:131)
		at com.azure.storage.blob.specialized.BlobClientBase.getPropertiesWithResponse(BlobClientBase.java:806)
		at com.azure.storage.blob.specialized.BlobClientBase.getProperties(BlobClientBase.java:784)
		at com.azure.storage.blob.specialized.BlobClientBase.openInputStream(BlobClientBase.java:265)
		at com.azure.storage.blob.specialized.BlobClientBase.openInputStream(BlobClientBase.java:252)
		at com.azure.storage.blob.specialized.BlobClientBase.openInputStream(BlobClientBase.java:238)
		at com.blob.test.BlobAllOperations.downloadBlobTest(BlobAllOperations.java:125)
		at com.blob.test.BlobAllOperations.main(BlobAllOperations.java:235)
```

**Old SDK Code to reproduce**
```
CloudBlobClient cloudBlobClient = new CloudBlobClient(new URI(BLOB_SAS_SERVICE));	
	CloudBlobContainer container = cloudBlobClient.getContainerReference("test");
	CloudBlockBlob blockBlob = container.getBlockBlobReference("Unknown");
	blockBlob.downloadText();
```

**OLD SDK Error StackTrace**
![image](https://user-images.githubusercontent.com/22897837/114017033-6c3c2f80-9863-11eb-8224-f345d5182389.png)

**Setup (please complete the following information if applicable):**
OS: window
IDE : eclipse
Version of the Library used: `azure-storage-blob-12.10.0`

**Comment by gapra-msft** [comment]
Hi @abhikt48 
Thank you for your question. 

Unfortunately there isn't much we can do here as I believe unsuppressing the error would make the stacktrace even more confusing to interpret. Fortunately, it looks like the stack trace in the new SDK does contain all the information you need to debug your issue.

**Comment by abhikt48** [comment]
Hi @gapra-msft , Thanks for your quick reply. I agreed that we are getting more details than earlier.

There are two point of view - 
1. From user prospective - For solving immediate issue they are mostly worried about caller class details with immediate SDK call hierarchy and correct error message. From this information mostly 70-80% problem will be resolved. 
2. From SDK developer prospective - They need complete information to fix/identify any issues. 

As per my opinion - every stacktrace should have actual caller class information instead in suppress section. 

I would like to propose you one solution for this issue - Please introduce one System variable or Configuration level variable from which user can control detail stack trace details. 
If user needs deep details then they can enable custom settings.

Providing options to user will be great benefits for all. 

Please let me know your opinion.

**Comment by gapra-msft** [comment]
@alzimmermsft Is there a way customers can choose to enable not suppressing the error messages?

**Comment by abhikt48** [comment]
@alzimmermsft  could you please update us on this issue ?

**Comment by alzimmermsft** [comment]
Unfortunately this is how Reactor, what handles SDK calls underneath the API, propagates exceptions. 

The approach it appears they are using is to make the exception caught within the thread running the SDK call the top level exception but also to retain the call stack leading to the API call as a suppressed exception.
