### ISSUE TITLE
InteractiveBrowserCredential usage throws error

### ISSUE THREAD

**Issue by Noushed** [Azure/azure-sdk-for-java#20546]
InteractiveBrowserCredential usage is throwing "Caused by: com.microsoft.aad.msal4j.MsalClientException: No Authorization code was returned from the server"

# Steps to reproduce
microsoft-graph version: 2.10.0 or 2.9.0
microsoft-graph-auth version: 0.3.0

```
	private static GraphServiceClient createClient() throws IOException {
		if (authProvider == null) {
			final InteractiveBrowserCredential interactiveBrowserCredential = new InteractiveBrowserCredentialBuilder()
					.clientId(OneDriveConstants.CLIENT_ID).redirectUrl(OneDriveConstants.REDIRECT_URI).build();
			authProvider = new TokenCredentialAuthProvider(
					List.of("Files.ReadWrite.All", "offline_access", "User.Read"), interactiveBrowserCredential);

		}
		
		return GraphServiceClient
			.builder()
			.authenticationProvider(authProvider)
			.buildClient();
	}
```

```
Caused by: java.io.IOException: java.util.concurrent.ExecutionException: com.azure.core.exception.ClientAuthenticationException: Failed to acquire token with Interactive Browser Authentication.
	at com.microsoft.graph.httpcore.AuthenticationHandler.intercept(AuthenticationHandler.java:65)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at com.microsoft.graph.httpcore.TelemetryHandler.intercept(TelemetryHandler.java:69)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at com.microsoft.graph.http.CoreHttpProvider.sendRequestInternal(CoreHttpProvider.java:385)
	... 69 more
Caused by: java.util.concurrent.ExecutionException: com.azure.core.exception.ClientAuthenticationException: Failed to acquire token with Interactive Browser Authentication.
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
	at com.microsoft.graph.httpcore.AuthenticationHandler.intercept(AuthenticationHandler.java:55)
	... 75 more
Caused by: com.azure.core.exception.ClientAuthenticationException: Failed to acquire token with Interactive Browser Authentication.
	at com.azure.identity.implementation.IdentityClient.lambda$authenticateWithBrowserInteraction$28(IdentityClient.java:697)
	at reactor.core.publisher.Mono.lambda$onErrorMap$30(Mono.java:3325)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:88)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondError(MonoFlatMap.java:185)
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onError(MonoFlatMap.java:251)
	at reactor.core.publisher.MonoCompletionStage.lambda$subscribe$0(MonoCompletionStage.java:80)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1705)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: com.microsoft.aad.msal4j.MsalClientException: No Authorization code was returned from the server
	at com.microsoft.aad.msal4j.AcquireTokenByInteractiveFlowSupplier.getAuthorizationResultFromHttpListener(AcquireTokenByInteractiveFlowSupplier.java:140)
	at com.microsoft.aad.msal4j.AcquireTokenByInteractiveFlowSupplier.getAuthorizationResult(AcquireTokenByInteractiveFlowSupplier.java:64)
```

**Comment by joshfree** [comment]
@g2vinay PTAL

**Comment by g2vinay** [comment]
@Noushed 
Thank you for posting this issue.
Were you prompted to login in the browser when the above code executed ?

**Comment by g2vinay** [comment]
@Noushed 
Let us know if you need any further assistance here.
Closing this.
