### ISSUE TITLE
[Event Hub]Intermittent connectivity problems when sending events.

### ISSUE THREAD

**Issue by v-japate** [Azure/azure-sdk-for-java#20557]
Getting below error intermittently while sending events to the event hub. 

Exception:
```
**ERROR  [02:51:06.587] [dw-2960 - POST /azure/solarwind] i.d.j.e.LoggingExceptionMapper -  Error handling a request: 546244e357cc512d
java.lang.IllegalStateException: Timeout on blocking read for 60000 MILLISECONDS
        at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:117) ~[azure-webhook-0.0.1-SNAPSHOT.jar:na]
        at reactor.core.publisher.Mono.block(Mono.java:1687) ~[azure-webhook-0.0.1-SNAPSHOT.jar:na]
        at com.azure.messaging.eventhubs.EventHubProducerClient.createBatch(EventHubProducerClient.java:127) ~[azure-webhook-0.0.1-SNAPSHOT.jar:na]**
        at com.rockwell.uptime.webhook.service.DefaultWebhookService.postSolarwindDataToKafka(DefaultWebhookService.java:324) ~[azure-webhook-0.0.1-SNAPSHOT.jar:na]
        at sun.reflect.GeneratedMethodAccessor27.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_131]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_131]
        at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60) ~[azure-webhook-0.0.1-SNAPSHOT.jar:na]
        at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205) ~[azure-webhook-0.0.1-SNAPSHOT.jar:na]
        at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75) ~[azure-webhook-0.0.1-SNAPSHOT.jar:na]
        at io.dropwizard.jersey.guava.OptionalResourceMethodDispatchAdapter$OptionalRequestDispatcher.dispatch(OptionalResourceMethodDispatchAdapter.java:37) ~[azure-webhook-0.0.1-SNAPSHOT.jar:na]
        at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302) ~[azure-webhook-0.0.1-SNAPSHOT.jar:na]
        at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147) ~[azure-webhook-0.0.1-SNAPSHOT.jar:na]
        at com.sun.jersey.server.impl.uri.rules.ResourceObjectRule.accept(ResourceObjectRule.java:100) ~[azure-webhook-0.0.1-SNAPSHOT.jar:na]
        at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147) ~[azure-webhook-0.0.1-SNAPSHOT.jar:na]
        at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84) ~[azure-webhook-0.0.1-SNAPSHOT.jar:na]
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542) [azure-webhook-0.0.1-SNAPSHOT.jar:na]
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473) [azure-webhook-0.0.1-SNAPSHOT.jar:na]
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419) [azure-webhook-0.0.1-SNAPSHOT.jar:na]
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409) [azure-webhook-0.0.1-SNAPSHOT.jar:na]
        at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409) [azure-webhook-0.0.1-SNAPSHOT.jar:na]
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:540) [azure-webhook-0.0.1-SNAPSHOT.jar:na]
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:715) [azure-webhook-0.0.1-SNAPSHOT.jar:na]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) [azure-webhook-0.0.1-SNAPSHOT.jar:na]
        at io.dropwizard.jetty.NonblockingServletHolder.handle(NonblockingServletHolder.java:49) [azure-webhook-0.0.1-SNAPSHOT.jar:na]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1515) [azure-webhook-0.0.1-SNAPSHOT.jar:na]
        at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83) [azure-webhook-0.0.1-SNAPSHOT.jar:na]
        at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:295) [azure-webhook-0.0.1-SNAPSHOT.jar:na]
        at io.dropwizard.jetty.BiDiGzipFilter.doFilter(BiDiGzipFilter.java:127) [azure-webhook-0.0.1-SNAPSHOT.jar:na]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486) [azure-webhook-0.0.1-SNAPSHOT.jar:na]
        at io.dropwizard.servlets.ThreadNameFilter.doFilter(ThreadNameFilter.java:29) [azure-webhook-0.0.1-SNAPSHOT.jar:na]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486) [azure-webhook-0.0.1-SNAPSHOT.jar:na]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:519) [azure-webhook-0.0.1-SNAPSHOT.jar:na]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1097) [azure-webhook-0.0.1-SNAPSHOT.jar:na]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:448) [azure-webhook-0.0.1-SNAPSHOT.jar:na]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1031) [azure-webhook-0.0.1-SNAPSHOT.jar:na]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136) [azure-webhook-0.0.1-SNAPSHOT.jar:na]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [azure-webhook-0.0.1-SNAPSHOT.jar:na]
        at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:173) [azure-webhook-0.0.1-SNAPSHOT.jar:na]
        at io.dropwizard.jetty.RoutingHandler.handle(RoutingHandler.java:51) [azure-webhook-0.0.1-SNAPSHOT.jar:na]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [azure-webhook-0.0.1-SNAPSHOT.jar:na]
        at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:92) [azure-webhook-0.0.1-SNAPSHOT.jar:na]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [azure-webhook-0.0.1-SNAPSHOT.jar:na]
        at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:162) [azure-webhook-0.0.1-SNAPSHOT.jar:na]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [azure-webhook-0.0.1-SNAPSHOT.jar:na]
        at org.eclipse.jetty.server.Server.handle(Server.java:446) [azure-webhook-0.0.1-SNAPSHOT.jar:na]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:271) [azure-webhook-0.0.1-SNAPSHOT.jar:na]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:246) [azure-webhook-0.0.1-SNAPSHOT.jar:na]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358) [azure-webhook-0.0.1-SNAPSHOT.jar:na]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601) [azure-webhook-0.0.1-SNAPSHOT.jar:na]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532) [azure-webhook-0.0.1-SNAPSHOT.jar:na]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
```

Below is the SDK and version using:
```

<dependency>
<groupId>com.azure</groupId>
<artifactId>azure-messaging-eventhubs</artifactId>
<version>5.5.0</version>
</dependency>
```

**Comment by joshfree** [comment]
@conniey PTAL

**Comment by conniey** [comment]
Do you have logs to go along with this? You can enable Azure SDK logging (https://github.com/Azure/azure-sdk-for-java/wiki/Logging-with-Azure-SDK) with these instructions. If you set the log level to Info, it would give us more insights as to why it is failing.

**Comment by v-japate** [comment]
@conniey Thank you for looking into this. I am working to get the logs.
