### ISSUE TITLE
[BUG] Get Exception in thread "main" java.lang.NoSuchMethodError: 'java.lang.String com.azure.core.util.CoreUtils.getApplicationId(com.azure.core.util.ClientOptions, com.azure.core.http.policy.HttpLogOptions)' when create the client

### ISSUE THREAD

**Issue by jinyanghuang** [Azure/azure-sdk-for-java#20569]
**Describe the bug**
I followed the step to create the client, my code is as follow
```
String tableConnectionString = "DefaultEndpointsProtocol=https;AccountName=xxx;AccountKey=xxx;EndpointSuffix=core.windows.net";
		TableServiceClient tableServiceClient = new TableServiceClientBuilder()
				.connectionString(tableConnectionString )
				.buildClient();
```

***Exception or Stack Trace***
```
Exception in thread "main" java.lang.NoSuchMethodError: 'java.lang.String com.azure.core.util.CoreUtils.getApplicationId(com.azure.core.util.ClientOptions, com.azure.core.http.policy.HttpLogOptions)'
	at com.azure.data.tables.BuilderHelper.buildPipeline(BuilderHelper.java:62)
	at com.azure.data.tables.TableServiceClientBuilder.buildAsyncClient(TableServiceClientBuilder.java:79)
	at com.azure.data.tables.TableServiceClientBuilder.buildClient(TableServiceClientBuilder.java:67)
	at com.molex.dublin.DublinApplication.main(DublinApplication.java:18)
```

This happen in Beta 5, but not in Beta 4

**Comment by alzimmermsft** [comment]
Thank you for submitting this issue @jinyanghuang, do you mind including which dependencies you are using? The method not being found was added in a more recent release of the `azure-core` library which both beta 4 and 5 of Tables should be using, this leads me to think that azure-core is being resolved to an older version. Using this functionality was added in beta 5 which is why this isn't being seen when beta 4 is used.

@vcolin7 FYI

**Comment by jinyanghuang** [comment]
Hi sorry for the late reply. The dependencies I am using are
```
<dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-digitaltwins-core</artifactId>
            <version>1.0.1</version>
        </dependency>
```

**Comment by jinyanghuang** [comment]
Thanks I guess upgrading the azure-digitaltwins-core version to 1.0.3 solved this issue
