### ISSUE TITLE
Azure Blob - leaseID mandatory for deleting leased blob with new SDK?

### ISSUE THREAD

**Issue by abhikt48** [Azure/azure-sdk-for-java#20620]
We are migrating blob component from old SDK `azure-storage-5.5.0` to new SDK `azure-storage-blob-12.10.2`. 

Problem - We were able to delete **leased** blob with old sdk without providing leaseID, but in NEW SDK it's mandatory to provide leaseID to delete leased blob. 

Please find below details and suggest your opinion on this issue?

**OLD SDK**
```
CloudBlockBlob blockBlob = getBlobClient().getContainerReference(containerName).getBlockBlobReference(blobName);
// Blob Lease Status
blockBlob.downloadAttributes();
String leaseStatus = blockBlob.getProperties().getLeaseStatus().toString();
if (LOCKED.equalsIgnoreCase(leaseStatus)) {
	blockBlob.breakLease(0);
}
blockBlob.delete();
```

**NEW SDK**
```
public static void aquireRelease() {
        String blobName = "**.txt";
        String containerName = "***";
        
        //First Acquire Lease on Blob
        BlobServiceClient blobServiceClient = new BlobServiceClientBuilder().endpoint(BLOB_SAS).buildClient();
        BlobClient blobClient = blobServiceClient.getBlobContainerClient(containerName).getBlobClient(blobName);
        BlobLeaseClient blobLeaseClient = new BlobLeaseClientBuilder().blobClient(blobClient).buildClient();
        
        String leaseID = blobLeaseClient.acquireLease(60);
        LOGGER.info("** Blob '{}' leaseID '{}' ***", blobName, leaseID);
        
        //Delete blob after releasing lease
        BlobServiceClient deleteBlobServiceClient = new BlobServiceClientBuilder().endpoint(BLOB_SAS).buildClient();
        BlobClient deleteBlobClient = deleteBlobServiceClient.getBlobContainerClient(containerName).getBlobClient(blobName);
        
        BlobLeaseClient deleteBlobLeaseClient = new BlobLeaseClientBuilder()
                                                .blobClient(deleteBlobClient)
                                                //.leaseId(leaseID)
                                                .buildClient();
        deleteBlobLeaseClient.releaseLease();
        
        deleteBlobClient.delete();
        
        LOGGER.info("** Blob '{}' deleted after releasing lease***", blobName);
    }
```

**NEW SDK Exception**
```
com.azure.storage.blob.models.BlobStorageException: Status code 409, "﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>LeaseIdMismatchWithLeaseOperation</Code><Message>The lease ID specified did not match the lease ID for the blob.
RequestId:***
Time:2021-04-13T16:28:52.9970333Z</Message></Error>"
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.azure.core.http.rest.RestProxy.instantiateUnexpectedException(RestProxy.java:337)
	at com.azure.core.http.rest.RestProxy.lambda$ensureExpectedStatus$5(RestProxy.java:378)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:118)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1782)
	at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.signalCached(MonoCacheTime.java:320)
	at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.onNext(MonoCacheTime.java:337)
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2344)
	at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.onSubscribe(MonoCacheTime.java:276)
	at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:191)
	at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at reactor.core.publisher.MonoCacheTime.subscribeOrReturn(MonoCacheTime.java:132)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:150)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:123)
	at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:112)
	at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:213)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:123)
	at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:178)
	at reactor.core.publisher.FluxContextStart$ContextStartSubscriber.onNext(FluxContextStart.java:96)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1782)
	at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:121)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:252)
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:136)
	at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:383)
	at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:373)
	at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:429)
	at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:655)
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:96)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1533)
	at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1294)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1331)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
		at reactor.core.publisher.Mono.block(Mono.java:1685)
		at com.azure.storage.common.implementation.StorageImplUtils.blockWithOptionalTimeout(StorageImplUtils.java:128)
		at com.azure.storage.blob.specialized.BlobLeaseClient.releaseLeaseWithResponse(BlobLeaseClient.java:234)
		at com.azure.storage.blob.specialized.BlobLeaseClient.releaseLeaseWithResponse(BlobLeaseClient.java:214)
		at com.azure.storage.blob.specialized.BlobLeaseClient.releaseLease(BlobLeaseClient.java:194)
		at com.blob.test.BlobAllOperations.aquireRelease(BlobAllOperations.java:119)
		at com.blob.test.BlobAllOperations.main(BlobAllOperations.java:331)
```

**Setup (please complete the following information if applicable):**
OS: window
IDE : eclipse
Version of the Library used: `azure-storage-blob-12.10.2`

**Comment by gapra-msft** [comment]
Hi @abhikt48 
Thank you for posting this issue. We will take a look and get back to you.

**Comment by jaschrep-msft** [comment]
@abhikt48  It looks like you were relying on the design of the older libraries where `CloudBlob` instances maintained a state that mirrored service state. This design was discarded in newer libraries for a variety of reasons, and with it went automatic management of lease IDs. `LeaseClient`s were introduced to provide a client that maintained the relevant info on a lease for you, so all you would have to worry about is holding onto the `LeaseClient` until you're ready to act on the lease again, as opposed to the code sample you provide where you build your lease client up from scratch every time you want to use it.

In general, I would recommend holding onto your clients if you still intend to use them later in your code. Not only is it easier to ensure your client will behave the same way, but constructing clients from scratch with a `XxxClientBuilder` is not as lightweight an operation as it may seem, and holding onto clients will result in more efficient code.

**Comment by abhikt48** [comment]
Hi @jaschrep-msft , Thanks a lot for quick reply and detail insight.  We developed blob component for Mule Enterprise Service Bus, where we are providing features to perform actions in chunk such as download, upload, delete etc as separate functionality. So we can't merge all functionality into one and can't reuse same `BlobClient `for all operations due to **different blob name everytime**. I am reusing `BlobServiceClient ` everywhere but need to create `BlobClient `on all operations everytime due to blob name changes. It's good that you pointed out this issue. I will share one small class and used pattern, so you can suggest me expensive operations. It will be very helpful for us to improve performance.

I don't have any concern on latest design approach. I raised ticket to make sure that I am doing expected things from NEW SDK prospective.

I did testing again and looks like `leaseID ` is mandatory for `releaseLease()`. 

Suggestion - If  `leaseID` is mandatory to release lease then `releaseLease()` operation should have mandatory `leaseID ` argument. With this way, user will have more clarity.
We are using `BlobLeaseClient `for breaking lease as well, where leaseID is not mandatory for infinite duration (at this moment, raised another issue - https://github.com/Azure/azure-sdk-for-java/issues/20621)

```
BlobLeaseClient deleteBlobLeaseClient = new BlobLeaseClientBuilder()
                                                .blobClient(deleteBlobClient)
                                                //.leaseId(leaseID)
                                                .buildClient();
deleteBlobLeaseClient.releaseLease(); // Mandatory to provide leaseID
```

**One Question** - If we lost leaseID after aquiring lease then do we have any way to get leaseID back? 
I found only one alternative - **break lease** and perform all required operations.  I tried to get lease ID with `getLeaseBlobLeaseClient.getLeaseId()` but this is returning different leaseID as compared to acqired lease ID. Please find below sample code.

Could you please suggest your opinion on below query-
1. Do we have any option to retrieve lost leaseID ?
2. Why `BlobLeaseClient.getLeaseId()` is returning different lease ID?

```
public static void getLeaseIDAfterAcquireBlob() {
        String blobName = "**.txt";
        String containerName = "**";
        
        //First Acquire Lease on Blob
        BlobServiceClient blobServiceClient = new BlobServiceClientBuilder().endpoint(BLOB_SAS).buildClient();
        BlobClient blobClient = blobServiceClient.getBlobContainerClient(containerName).getBlobClient(blobName);
        
        BlobLeaseClient blobLeaseClient = new BlobLeaseClientBuilder().blobClient(blobClient).buildClient();
        String leaseID = blobLeaseClient.acquireLease(30); 
        LOGGER.info("** Blob '{}' acquired leaseID '{}' ***", blobName, leaseID);
        
        // lost leaseID due to UNKNOWN issue
        leaseID = null;
        
        // Get LeaseID
        BlobLeaseClient getLeaseBlobLeaseClient = new BlobLeaseClientBuilder().blobClient(blobClient).buildClient();
        String retrievedLeaseID = getLeaseBlobLeaseClient.getLeaseId();
        LOGGER.info("** Blob '{}' retrievedLeaseID '{}' ***", blobName, retrievedLeaseID);
        
        //Release Lease
        BlobLeaseClient releaseBlobLeaseClient = new BlobLeaseClientBuilder().leaseId(retrievedLeaseID).blobClient(blobClient).buildClient();
        releaseBlobLeaseClient.releaseLease();
        LOGGER.info("** Blob '{}' released lease '{}' ***", blobName);

        //Delete Blob
        blobClient.delete();
        LOGGER.info("** Blob '{}' deleted ***", blobName);
    }
```

**Comment by jaschrep-msft** [comment]
There is a fair amount of confusion regarding exactly what the lease client is doing, hence the investigation into a more cohesive experience. getLeaseId() is a field getter; you've generated a new lease client and it has a new random ID to try and create a lease with. Your new client doesn't point to the same lease that you've lost. Actually, looking further into how that works, it appears you actually can use the same lease client for acquire/release/break lease (but a changelease will not work as desired). So you can create a lease client, acquireLease(), hold onto that client, release/renew/break lease with that client, without ever having to worry about the lease ID. The acquire function will return the lease ID in case you have need of it, but otherwise you don't need that response value as it's stored in the client. If you acquire a lease and then immediately call getLeaseId(), you'll note the responses are the same.

I realize this slightly contradicts what I said in an earlier message and apologize for the confusion.

Don't lose your lease ID (or the client holding that ID). You can't get it back and will need to break.

**Comment by jaschrep-msft** [comment]
We've merged in a new feature that will better manage lease ID on the lease client, available on next release. Hopefully we've answered your questions. Feel free to reopen if you think this issue isn't resolved.
