### ISSUE TITLE
[BUG] Azure-storage-blob Hitting PoolAcquireTimeoutException on getAccountInfo call.

### ISSUE THREAD

**Issue by vmaheshw** [Azure/azure-sdk-for-java#20624]
**Describe the bug**

***Exception or Stack Trace***
`reactor.core.Exceptions.ReactiveException: reactor.netty.internal.shaded.reactor.pool.PoolAcquireTimeoutException: Pool#acquire(Duration) has been pending for more than the configured timeout of 45000ms
reactor.netty.internal.shaded.reactor.pool.PoolAcquireTimeoutException: Pool#acquire(Duration) has been pending for more than the configured timeout of 45000ms,`

`Caused by: reactor.core.Exceptions$ReactiveException: reactor.netty.internal.shaded.reactor.pool.PoolAcquireTimeoutException: Pool#acquire(Duration) has been pending for more than the configured timeout of 45000ms
        at reactor.core.Exceptions.propagate(Exceptions.java:336) ~[reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
        at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:91) ~[reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
        at reactor.core.publisher.Mono.block(Mono.java:1663) ~[reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
        at 

        Suppressed: java.lang.Exception: #block terminated with an error
                at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:93) ~[reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
                at reactor.core.publisher.Mono.block(Mono.java:1663) ~[reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]`
                
              
`Caused by: reactor.netty.internal.shaded.reactor.pool.PoolAcquireTimeoutException: Pool#acquire(Duration) has been pending for more than the configured timeout of 45000ms
        at reactor.netty.internal.shaded.reactor.pool.AbstractPool$Borrower.run(AbstractPool.java:317) ~[reactor-netty-0.9.0.RELEASE.jar:0.9.0.RELEASE]
        at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68) ~[reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
        at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28) ~[reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_172]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_172]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:1.8.0_172]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_172]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_172]
        ... 1 more`

**To Reproduce**
`SkuName accountType = storageClient.getAccountInfo().block().getSkuName(); `

The exception is coming in above code. We kill the thread on the exception and create a new thread which retry this and fails again. The issue does not recover till the host is restarted.

***Code Snippet***
`SkuName accountType = storageClient.getAccountInfo().block().getSkuName(); `

**Expected behavior**
A transient error should not cause the host to go in bad state and a new thread should not stuck in this error loop.

**Screenshots**

**Setup (please complete the following information):**
 - IDE : [e.g. IntelliJ]
 - Version of the Library used:  azure-storage-blob 12.0.1

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by alzimmermsft** [comment]
Thank you for submitting this issue @vmaheshw! I'll take a look into it and get back to you.

**Comment by alzimmermsft** [comment]
This error happens when all connections in the Reactor Netty connection pool are actively being consumed, when this happens all additional connection requests are added into a queue with a timeout period to trigger this error if they are enqueued too long before acquiring a connection. The most common case for this happening is when the HTTP client is fielding more requests than it is capable of processing (I've seen cases where 100s of thousands of requests were being funneled into a 500 connection pool leading to this error). 

To view status of the connection pools state, active connections, total connections, queued connections, etc, you can enable verbose logging for Reactor Netty to log this information every time a new connection request is received. This will help determine if the connection pool is seeing too many requests, or it could show connections are reaching a bad state and either aren't being released or aren't being terminated properly.

One thing I will call out is `azure-storage-blob` `12.0.1` is a much older version of the SDK and there have been a few improvements and bug fixes to the HTTP client area. So, you may being seeing the same errors that were fixed in newer versions of the SDK (connections not terminating when a server kills the connection without a RST/FIN [#13845], retried requests not consuming the entire exception response before retrying [#16607]).

Upgrading to a newer version of the SDKs may resolve this issue. For upgrading my recommendation is using the latest version of [`azure-sdk-bom`](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/boms/azure-sdk-bom) as a dependency manager and leveraging that to include `azure-storage-blob` and any other Azure SDKs into your project.

**Comment by alzimmermsft** [comment]
@vmaheshw is this issue still on-going? I reached out to the Reactor Netty team and it appears the in either their latest or second to latest release they've added support for logging the number of connection requests actively queued for a connection pool. From this it should be possible to upgrade just the Reactor Netty dependency to enable this logging to determine if this issue is related to connection queuing or is occurring due to another issue.
