### ISSUE TITLE
Azure Blob - failed to delete blob with breakLease - 'There is currently a lease on the blob and no lease ID was specified in the request. RequestId'

### ISSUE THREAD

**Issue by abhikt48** [Azure/azure-sdk-for-java#20621]
We are migrating blob component from old SDK `azure-storage-5.5.0` to new SDK `azure-storage-blob-12.10.2`. 

Problem - I am not able to delete blob with `BlobLeaseClient.breakLease()` operation, but able to delete blob with `BlobLeaseClient.releaseLease()` operation. I was able to delete blob after breaking lease with OLD SDK but not with NEW SDK.

Is this correct expectation? Could you please check and confirm?

**OLD SDK**
```
CloudBlockBlob blockBlob = getBlobClient().getContainerReference(containerName).getBlockBlobReference(blobName);
// Blob Lease Status
blockBlob.downloadAttributes();
String leaseStatus = blockBlob.getProperties().getLeaseStatus().toString();
if (LOCKED.equalsIgnoreCase(leaseStatus)) {
	blockBlob.breakLease(0);
}
blockBlob.delete();
```

**NEW SDK**
```
public static void aquireRelease() {
        String blobName = "**.txt";
        String containerName = "**";
        
        //First Acquire Lease on Blob
        BlobServiceClient blobServiceClient = new BlobServiceClientBuilder().endpoint(BLOB_SAS).buildClient();
        BlobClient blobClient = blobServiceClient.getBlobContainerClient(containerName).getBlobClient(blobName);
        BlobLeaseClient blobLeaseClient = new BlobLeaseClientBuilder().blobClient(blobClient).buildClient();
        
        String leaseID = blobLeaseClient.acquireLease(60);
        LOGGER.info("** Blob '{}' leaseID '{}' ***", blobName, leaseID);
        
        //Delete blob after releasing lease
        BlobServiceClient deleteBlobServiceClient = new BlobServiceClientBuilder().endpoint(BLOB_SAS).buildClient();
        BlobClient deleteBlobClient = deleteBlobServiceClient.getBlobContainerClient(containerName).getBlobClient(blobName);
        
        BlobLeaseClient deleteBlobLeaseClient = new BlobLeaseClientBuilder()
                                                .blobClient(deleteBlobClient)
                                                .leaseId(leaseID)
                                                .buildClient();
        //deleteBlobLeaseClient.releaseLease(); // Working fine 
        deleteBlobLeaseClient.breakLease(); // Failed to delete
        
        deleteBlobClient.delete();
        
        LOGGER.info("** Blob '{}' deleted after releasing lease***", blobName);
    }
```

**NEW SDK Exception**
```
com.azure.storage.blob.models.BlobStorageException: Status code 412, "﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>LeaseIdMissing</Code><Message>There is currently a lease on the blob and no lease ID was specified in the request.
RequestId:***
Time:2021-04-13T16:46:10.3434752Z</Message></Error>"
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.azure.core.http.rest.RestProxy.instantiateUnexpectedException(RestProxy.java:337)
	at com.azure.core.http.rest.RestProxy.lambda$ensureExpectedStatus$5(RestProxy.java:378)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:118)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1782)
	at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.signalCached(MonoCacheTime.java:320)
	at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.onNext(MonoCacheTime.java:337)
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2344)
	at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.onSubscribe(MonoCacheTime.java:276)
	at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:191)
	at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at reactor.core.publisher.MonoCacheTime.subscribeOrReturn(MonoCacheTime.java:132)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:150)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:123)
	at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:112)
	at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:213)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:123)
	at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:178)
	at reactor.core.publisher.FluxContextStart$ContextStartSubscriber.onNext(FluxContextStart.java:96)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1782)
	at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:121)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:252)
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:136)
	at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:383)
	at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:373)
	at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:429)
	at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:655)
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:96)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1533)
	at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1294)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1331)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
		at reactor.core.publisher.Mono.block(Mono.java:1685)
		at com.azure.storage.common.implementation.StorageImplUtils.blockWithOptionalTimeout(StorageImplUtils.java:128)
		at com.azure.storage.blob.specialized.BlobClientBase.deleteWithResponse(BlobClientBase.java:768)
		at com.azure.storage.blob.specialized.BlobClientBase.delete(BlobClientBase.java:742)
		at com.blob.test.BlobAllOperations.aquireRelease(BlobAllOperations.java:122)
		at com.blob.test.BlobAllOperations.main(BlobAllOperations.java:332)
```

**Setup (please complete the following information if applicable):**
OS: window
IDE : eclipse
Version of the Library used: `azure-storage-blob-12.10.2`

**Comment by gapra-msft** [comment]
Hi @abhikt48 
Thank you for posting this issue. We will take a look and get back to you.

**Comment by abhikt48** [comment]
Hi @gapra-msft  , I did testing again and found that breaklease is working fine for infinite lease duration `blobLeaseClient.acquireLease(-1)` but it is not working fine with 15-60 seconds `blobLeaseClient.acquireLease(30)`.

I think this is a defect, please take a look and let me know your opinion.

```
String blobName = "**.txt";
String containerName = "**";

//First Acquire Lease on Blob
BlobServiceClient blobServiceClient = new BlobServiceClientBuilder().endpoint(BLOB_SAS).buildClient();
BlobClient blobClient = blobServiceClient.getBlobContainerClient(containerName).getBlobClient(blobName);

BlobLeaseClient blobLeaseClient = new BlobLeaseClientBuilder().blobClient(blobClient).buildClient();
//String leaseID = blobLeaseClient.acquireLease(-1); // Works fine
String leaseID = blobLeaseClient.acquireLease(30); // Failed to breakLease 
LOGGER.info("** Blob '{}' leaseID '{}' ***", blobName, leaseID);

//BlobLeaseClient blobLeaseClient1 = new BlobLeaseClientBuilder().blobClient(blobClient).leaseId(leaseID).buildClient();
BlobLeaseClient blobLeaseClient1 = new BlobLeaseClientBuilder().blobClient(blobClient).buildClient();
Integer breakLeaseResponse = blobLeaseClient1.breakLease();
LOGGER.info("** Blob '{}' breakRelease '{}' ***", blobName, breakLeaseResponse);

blobClient.delete();

LOGGER.info("** Blob '{}' deleted ***", blobName);
```

**Comment by gapra-msft** [comment]
Hi @abhikt48 Thanks for the additional information. I will run your repro code and let you know what I find.

**Comment by gapra-msft** [comment]
Hi @abhikt48 

I think I understand what is happening now. As indicated in the rest [docs](https://docs.microsoft.com/en-us/rest/api/storageservices/lease-blob#response-headers), when you break a lease it is not immediate. The time returned to you as `breakLeaseResponse` is the "Approximate time remaining in the lease period, in seconds. This header is returned only for a successful request to break the lease. If the break is immediate, 0 is returned."

So the mitigation in this case would be to design application code to wait breakLeaseResponse seconds before performing any operations. 

The reason breakLease worked with an infinite lease was because the breakLeaseResponse is 0, but for any other lease time, you were likely getting some number of seconds higher than 0.

Hope this helps!

**Comment by abhikt48** [comment]
HI @gapra-msft , Thanks for quick reply.

I tested again and i am able to break lease immediately with below method. 

`BlobLeaseClient.breakLeaseWithResponse(0, null, null, Context.NONE).getValue();`
