### ISSUE TITLE
[FEATURE REQ] [Identity] Support cancel in device code login

### ISSUE THREAD

**Issue by andxu** [Azure/azure-sdk-for-java#20686]
We are using identity in intellij plugin, with cancelable button in device code dialog, in current implementation, the only way to shutdown then endless loop inside device code workflow is calling `shutdownNow` to the executorService, but will result in a not friendly system error:

![image](https://user-images.githubusercontent.com/17075863/114798037-0998e580-9dc7-11eb-8fd7-f21232494aa2.png)

![image](https://user-images.githubusercontent.com/17075863/114798204-6ac0b900-9dc7-11eb-889e-5a47e5330eb1.png)

2021-04-15 08:48:00,763 [ 155502]  ERROR - actor.core.publisher.Operators - Operator called default onErrorDropped 
reactor.core.Exceptions$ErrorCallbackNotImplemented: com.azure.core.exception.ClientAuthenticationException: Failed to acquire token with device code
Caused by: com.azure.core.exception.ClientAuthenticationException: Failed to acquire token with device code
	at com.azure.identity.implementation.IdentityClient.lambda$authenticateWithDeviceCode$23(IdentityClient.java:606)
	at reactor.core.publisher.Mono.lambda$onErrorMap$30(Mono.java:3384)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94)
	at reactor.core.publisher.MonoCompletionStage.lambda$subscribe$0(MonoCompletionStage.java:76)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1705)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.InterruptedException: sleep interrupted
	at java.base/java.lang.Thread.sleep(Native Method)
	at java.base/java.lang.Thread.sleep(Thread.java:339)
	at java.base/java.util.concurrent.TimeUnit.sleep(TimeUnit.java:446)
	at com.microsoft.aad.msal4j.AcquireTokenByDeviceCodeFlowSupplier.acquireTokenWithDeviceCode(AcquireTokenByDeviceCodeFlowSupplier.java:62)
	at com.microsoft.aad.msal4j.AcquireTokenByDeviceCodeFlowSupplier.execute(AcquireTokenByDeviceCodeFlowSupplier.java:27)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:59)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:17)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	... 3 more

**Comment by g2vinay** [comment]
@andxu 

To cancel the authentication you can use this flow:

```java

// Subscribe asynchronously on the getToken output.
        Disposable deviceCodeSubscription = deviceCodeCredential.getToken(new TokenRequestContext().addScopes("scopes"))
                .subscribe(accessToken -> {
                    //logic to process accessToken;
                    System.out.println("accessToken");
                });

// When the user cancels the operation, you can dispose of the subscription to cancel the operation.
        deviceCodeSubscription.dispose();
```java

**Comment by g2vinay** [comment]
Let us know if the issue still persists or if further assistance is needed.

**Comment by andxu** [comment]
![image](https://user-images.githubusercontent.com/17075863/117532782-e6ef9a80-b01b-11eb-8579-8dcb9e05daa7.png)

**Comment by andxu** [comment]
The deep reason of this is Mono.fromFuture will not cancel the future when the subscription is cancelled:
```java
 public static void main( String[] args ) throws InterruptedException {
        CompletableFuture<String> future = CompletableFuture.supplyAsync(() -> {
            try {
                Thread.sleep(5000);
                System.out.println("Wait 5 seconds");
                return "test";
            } catch (InterruptedException e) {
                throw new RuntimeException(e);
            }
        });
        Mono<String> mono = Mono.fromFuture(future);
        Disposable subscribe = mono.subscribe();
        Thread.sleep(2000);
        subscribe.dispose();
        Thread.sleep(1000);
        System.out.println(future.isCancelled());
        Thread.sleep(20000000);
}
```

Above code will print:
```
false
Wait 5 seconds

```
