### ISSUE TITLE
[BUG] Spring Service Bus Topic Auto Create Subscriptions

### ISSUE THREAD

**Issue by mrm9084** [Azure/azure-sdk-for-java#20683]
**Describe the bug**
When following this https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/spring/azure-spring-boot-samples/azure-spring-cloud-sample-servicebus-topic-binder/README.md#enable-auto-create I expect it to create a topic subscription if one  doesn't already exist.

The use case is Scaling Out on Azure App Service. I am unable to know the name or number of subscriptions needed with Auto Scaling on as each instance needs its own Subscription as all instances need to be notified.

***Exception or Stack Trace***
Caused by: com.microsoft.azure.servicebus.primitives.MessagingEntityNotFoundException: The messaging entity '<name of my serivce bus>:Topic:springcloudbus|sub-00-test' could not be found. To know more visit https://aka.ms/sbResourceMgrExceptions.  TrackingId:284d5dda-c52e-4bff-849a-de02de5a8678_B2, SystemTracker:<name of my serivce bus>:Topic:springcloudbus|sub-00-test, Timestamp:2021-04-14T23:34:33 TrackingId:a9ae850c29b743fabb2f08c08b482b1d_G4, SystemTracker:gateway7, Timestamp:2021-04-14T23:34:33, errorContext[NS: <name of my serivce bus>.servicebus.windows.net, PATH: springCloudBus/subscriptions/sub-00-test, REFERENCE_ID: Receiver_892843_a9ae850c29b743fabb2f08c08b482b1d_G4, PREFETCH_Q_LEN: 0]
	at com.microsoft.azure.servicebus.primitives.ExceptionUtil.toException(ExceptionUtil.java:29) ~[azure-servicebus-3.6.1.jar:na]
	at com.microsoft.azure.servicebus.primitives.CoreMessageReceiver.onClose(CoreMessageReceiver.java:826) ~[azure-servicebus-3.6.1.jar:na]
	at com.microsoft.azure.servicebus.amqp.BaseLinkHandler.processOnClose(BaseLinkHandler.java:68) ~[azure-servicebus-3.6.1.jar:na]
	at com.microsoft.azure.servicebus.amqp.BaseLinkHandler.onLinkRemoteClose(BaseLinkHandler.java:43) ~[azure-servicebus-3.6.1.jar:na]
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:176) ~[proton-j-0.33.4.jar:na]
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108) ~[proton-j-0.33.4.jar:na]
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324) ~[proton-j-0.33.4.jar:na]
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291) ~[proton-j-0.33.4.jar:na]
	at com.microsoft.azure.servicebus.primitives.MessagingFactory$RunReactor.run(MessagingFactory.java:556) ~[azure-servicebus-3.6.1.jar:na]
	... 1 common frames omitted

**To Reproduce**
Follow the steps from the sample and enable auto create, but give a sub that doesn't exist.

**Setup (please complete the following information):**
 - OS: Windows 10
 - IDE : Eclipse
 - Version of the Library used: 
<dependency>
    <groupId>com.azure.spring</groupId>
    <artifactId>azure-spring-cloud-stream-binder-servicebus-topic</artifactId>
    <version>2.3.0</version>
</dependency>

**Comment by mrm9084** [comment]
@backwind1233 Any update on this?

**Comment by backwind1233** [comment]
@yiliuTo I think it is a feature that need to be implemented

**Comment by stliu** [comment]
is this a bug or feature request, it shouldn't be both
this issue has been labeled with both **bug** and **feature request**

**Comment by saragluna** [comment]
@yiliuTo is this still an issue in our 4.0?

**Comment by yiliuTo** [comment]
@saragluna  good point, for 4.0 we have removed the function and property of auto creating resources , and do we need to fix it in 3.x.x?

**Comment by mrm9084** [comment]
@yiliuTo Are you saying this isn't a function in the 4.0 version. If so, then this is a feature request. Being able to auto create subscriptions is useful or auto scaling.

**Comment by yiliuTo** [comment]
@mrm9084, well I didn't make myself clear. In 4.0, the auto creation of resources are not supported in level 1 libraries, but for the Spring Cloud Stream binder libraries, this feature is also part of the Spring Cloud Stream specification, and we have supported it in 4.0 version. So, for the library of com.azure.spring:spring-cloud-azure-stream-binder-servicebus:4.0.0-beta.x, the bug of not creating subscriptions have been fixed. 

You need to add below configuration options for the auto creation.
```
spring.cloud.azure.profile.subscription-id
spring.cloud.azure.servicebus.resource.resource-group
```

**Comment by yiliuTo** [comment]
And for this bug, we have fixed it in the latest version of 2.12.0, you can upgrade to version 2.12.0 for the auto creation of subscription.
