### ISSUE TITLE
[BUG] NoClassDefFoundError: com/azure/core/util/Binary with EventHubAsyncConsumer

### ISSUE THREAD

**Issue by jinyanghuang** [Azure/azure-sdk-for-java#20707]
**Describe the bug**
I followed the document to create a eventHubAsyncConsumer to consume events. That is the link [EventHubConsumerAsyncClient Class](https://docs.microsoft.com/en-us/java/api/com.azure.messaging.eventhubs.eventhubconsumerasyncclient?view=azure-java-stable)
However, I always got java.lang.NoClassDefFoundError: com/azure/core/util/BinaryData exception

***Exception or Stack Trace***
11:35:52.467 [reactor-executor-1] ERROR reactor.core.scheduler.Schedulers - Scheduler worker in group main failed with an uncaught exception
java.lang.NoClassDefFoundError: com/azure/core/util/BinaryData
	at com.azure.messaging.eventhubs.EventHubMessageSerializer.deserializeEventData(EventHubMessageSerializer.java:231)
	at com.azure.messaging.eventhubs.EventHubMessageSerializer.deserialize(EventHubMessageSerializer.java:131)
	at com.azure.messaging.eventhubs.EventHubPartitionAsyncConsumer.onMessageReceived(EventHubPartitionAsyncConsumer.java:125)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:100)
	at com.azure.messaging.eventhubs.implementation.AmqpReceiveLinkProcessor.drainQueue(AmqpReceiveLinkProcessor.java:442)
	at com.azure.messaging.eventhubs.implementation.AmqpReceiveLinkProcessor.drain(AmqpReceiveLinkProcessor.java:403)
	at com.azure.messaging.eventhubs.implementation.AmqpReceiveLinkProcessor.lambda$onNext$3(AmqpReceiveLinkProcessor.java:209)
	at reactor.core.publisher.LambdaSubscriber.onNext(LambdaSubscriber.java:160)
	at reactor.core.publisher.EmitterProcessor.drain(EmitterProcessor.java:426)
	at reactor.core.publisher.EmitterProcessor.onNext(EmitterProcessor.java:268)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:192)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:192)
	at reactor.core.publisher.DirectProcessor$DirectInner.onNext(DirectProcessor.java:333)
	at reactor.core.publisher.DirectProcessor.onNext(DirectProcessor.java:142)
	at reactor.core.publisher.FluxCreate$IgnoreSink.next(FluxCreate.java:618)
	at reactor.core.publisher.FluxCreate$SerializedSink.next(FluxCreate.java:153)
	at com.azure.core.amqp.implementation.handler.ReceiveLinkHandler.onDelivery(ReceiveLinkHandler.java:125)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:185)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291)
	at com.azure.core.amqp.implementation.ReactorExecutor.run(ReactorExecutor.java:82)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.ClassNotFoundException: com.azure.core.util.BinaryData
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 30 common frames omitted

**To Reproduce**
```
                String eventHubConnectionString = "xxx";
		String consumerGroup = "xxx";

		EventHubConsumerAsyncClient consumer = new EventHubClientBuilder()
				.connectionString(eventHubConnectionString)
				.consumerGroup(consumerGroup)
				.buildAsyncConsumerClient();
		consumer.receive(true).subscribe(partitionEvent -> {
                        PartitionContext context = partitionEvent.getPartitionContext();
                        EventData event = partitionEvent.getData();
                        System.out.printf("Event %s is from partition %s%n.", event.getSequenceNumber(), context.getPartitionId());
		});
```

**Expected behavior**
Want to read the event

**Setup (please complete the following information):**
 - IDE : [e.g. IntelliJ]
 - Version of the Library used
 ```
<dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-messaging-eventhubs</artifactId>
            <version>5.6.0</version>
        </dependency>
<dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-digitaltwins-core</artifactId>
            <version>1.0.1</version>
        </dependency>

        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-identity</artifactId>
            <version>1.1.3</version>
        </dependency>
```

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by jinyanghuang** [comment]
Fixed it by upgrade the azure-digitaltwins-core version
```
<dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-digitaltwins-core</artifactId>
            <version>1.0.3</version>
        </dependency>
```
