### ISSUE TITLE
[QUERY] Spring Data Cosmos deleteById throw exception

### ISSUE THREAD

**Issue by saragluna** [Azure/azure-sdk-for-java#20727]
**Query/Question**
When I use `azure-spring-data-cosmos` and define my entity as:
```java
@Container(containerName = "myContainer", ru = "400")
public class User {

    @Id
    @PartitionKey
    private String id; // the id field is annotated with both @Id and @PartitionKey
    private String firstName;
    private String lastName;
}
```
and then call 
```java
userRepository.deleteById("my-id");
```

It will throw below exception:
```
Caused by: com.azure.cosmos.implementation.NotFoundException: {"innerErrorMessage":"[\"Resource Not Found. Learn more: https://aka.ms/cosmosdb-tsg-not-found\"]","cosmosDiagnostics":{"userAgent":"azsdk-java-cosmos/4.12.0 MacOSX/10.15.7 JRE/11.0.10","requestLatencyInMs":121,"requestStartTimeUTC":"2021-04-16T05:11:15.828763Z","requestEndTimeUTC":"2021-04-16T05:11:15.950487Z","connectionMode":"DIRECT","responseStatisticsList":[{"storeResult":{"storePhysicalAddress":"rntbd://cdb-ms-prod-eastasia1-fd3.documents.azure.com:14419/apps/11a0ed02-e46d-4632-bc0e-f175cd939f80/services/c8070b2f-10bd-4393-9f80-e76ea32d7c2f/partitions/9229fa93-2348-4bb7-902e-4a702dd4a1eb/replicas/132629445140531227p/","lsn":18,"globalCommittedLsn":18,"partitionKeyRangeId":"0","isValid":true,"statusCode":404,"subStatusCode":0,"isGone":false,"isNotFound":true,"isInvalidPartition":false,"requestCharge":1.24,"itemLSN":-1,"sessionToken":"-1#18","exception":"[\"Resource Not Found. Learn more: https://aka.ms/cosmosdb-tsg-not-found\"]","transportRequestTimeline":[{"eventName":"created","startTimeUTC":"2021-04-16T05:11:15.830576Z","durationInMicroSec":25},{"eventName":"queued","startTimeUTC":"2021-04-16T05:11:15.830601Z","durationInMicroSec":1},{"eventName":"channelAcquisitionStarted","startTimeUTC":"2021-04-16T05:11:15.830602Z","durationInMicroSec":770},{"eventName":"pipelined","startTimeUTC":"2021-04-16T05:11:15.831372Z","durationInMicroSec":976},{"eventName":"transitTime","startTimeUTC":"2021-04-16T05:11:15.832348Z","durationInMicroSec":101403},{"eventName":"received","startTimeUTC":"2021-04-16T05:11:15.933751Z","durationInMicroSec":13250},{"eventName":"completed","startTimeUTC":"2021-04-16T05:11:15.947001Z","durationInMicroSec":9293}],"rntbdRequestLengthInBytes":415,"rntbdResponseLengthInBytes":292,"requestPayloadLengthInBytes":0,"responsePayloadLengthInBytes":null,"channelTaskQueueSize":1,"pendingRequestsCount":1,"serviceEndpointStatistics":{"availableChannels":1,"acquiredChannels":0,"executorTaskQueueSize":0,"inflightRequests":1,"lastSuccessfulRequestTime":"2021-04-16T05:11:15.810Z","lastRequestTime":"2021-04-16T05:11:15.265Z","createdTime":"2021-04-16T05:11:15.265346Z","isClosed":false}},"requestResponseTimeUTC":"2021-04-16T05:11:15.950487Z","requestResourceType":"Document","requestOperationType":"Delete"}],"supplementalResponseStatisticsList":[],"addressResolutionStatistics":{},"regionsContacted":["https://xiada-cosmos-eastasia.documents.azure.com:443/"],"retryContext":{"retryCount":0,"statusAndSubStatusCodes":null,"retryLatency":0},"metadataDiagnosticsContext":{"metadataDiagnosticList":null},"serializationDiagnosticsContext":{"serializationDiagnosticsList":null},"gatewayStatistics":null,"systemInformation":{"usedMemory":"103576 KB","availableMemory":"4090728 KB","systemCpuLoad":"(2021-04-16T05:11:15.381616Z 26.5%)"},"clientCfgs":{"id":0,"numberOfClients":1,"connCfg":{"rntbd":"(cto:PT5S, rto:PT5S, icto:PT0S, ieto:PT1H, mcpe:130, mrpc:30, cer:false)","gw":"(cps:1000, rto:PT5S, icto:null, p:false)","other":"(ed: true, cs: false)"},"consistencyCfg":"(consistency: null, mm: true, prgns: [])"}}}
	at com.azure.cosmos.implementation.directconnectivity.rntbd.RntbdRequestManager.messageReceived(RntbdRequestManager.java:818) ~[azure-cosmos-4.12.0.jar:na]
	at com.azure.cosmos.implementation.directconnectivity.rntbd.RntbdRequestManager.channelRead(RntbdRequestManager.java:181) ~[azure-cosmos-4.12.0.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[netty-codec-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[netty-codec-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[netty-handler-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1526) ~[netty-handler-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1275) ~[netty-handler-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1322) ~[netty-handler-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501) ~[netty-codec-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440) ~[netty-codec-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[netty-codec-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.51.Final.jar:4.1.51.Final]
	... 1 common frames omitted
```

***Why is this not a Bug or a feature Request?***
I'm wondering if the user provides the partition key info by annotating the Id field, should we generate the partition key when the user calls `deleteById()` function.

https://github.com/Azure/azure-sdk-for-java/blob/ae5c9267b858d91b96036c750f11b7072f3794ad/sdk/cosmos/azure-spring-data-cosmos/src/main/java/com/azure/spring/data/cosmos/repository/support/SimpleCosmosRepository.java#L188-L193

**Setup (please complete the following information if applicable):**
 - OS: Any
 - IDE : Intellij
 - Version of the Library used: Spring Boot 2.3.x and azure-spring-data-cosmos 3.4.0
 - Could reproduce this issue by using [this sample](https://github.com/Azure-Samples/azure-spring-data-cosmos-java-sql-api-getting-started/blob/003b96491a524d7d910838f675d9763a4d8ab252/azure-spring-data-cosmos-java-getting-started/src/main/java/com/azure/spring/data/cosmostutorial/SampleApplication.java)
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by saragluna** [comment]
@kushagraThapar could you please take a look at this issue?

**Comment by saragluna** [comment]
@backwind1233 @zhoufenqin FYI

**Comment by kushagraThapar** [comment]
@saragluna - `deleteById(ID id)` - should be not be used, and it has been implemented just to support the spring-data framework. 
I don't see a way to extract partition key, given only the Id of the entity, and not the entity itself. 

For this reason, we exposed the another API - which is `deleteById(ID id, PartitionKey partitionKey)`

**Comment by kushagraThapar** [comment]
@saragluna - I am closing this issue as per my above comment. Please feel free to comment or re-open the issue if you think otherwise.
