### ISSUE TITLE
JsonParseException when using azure-spring-boot-starter-servicebus-jms

### ISSUE THREAD

**Issue by razibrath** [Azure/azure-sdk-for-java#21016]
Application is working fine while running from eclipse but throwing following error while running as jar file.

```
16:55:53.856 [main] ERROR org.springframework.boot.SpringApplication - Application startup failed
java.lang.IllegalArgumentException: Unable to instantiate factory class: org.springframework.boot.env.EnvironmentPostProcessor
	at org.springframework.core.io.support.SpringFactoriesLoader.instantiateFactory(SpringFactoriesLoader.java:142)
	at org.springframework.core.io.support.SpringFactoriesLoader.loadFactories(SpringFactoriesLoader.java:93)
	at org.springframework.boot.context.config.ConfigFileApplicationListener.loadPostProcessors(ConfigFileApplicationListener.java:177)
	at org.springframework.boot.context.config.ConfigFileApplicationListener.onApplicationEnvironmentPreparedEvent(ConfigFileApplicationListener.java:167)
	at org.springframework.boot.context.config.ConfigFileApplicationListener.onApplicationEvent(ConfigFileApplicationListener.java:157)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:167)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:122)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:73)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:54)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:336)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
	at com.pathpresenter.conference.Application.main(Application.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.lang.NoClassDefFoundError: org/springframework/boot/json/JsonParseException
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.getDeclaredConstructor(Class.java:2178)
	at org.springframework.core.io.support.SpringFactoriesLoader.instantiateFactory(SpringFactoriesLoader.java:137)
	... 20 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.springframework.boot.json.JsonParseException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:94)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 25 common frames omitted
```

**************************
below is my build.gradle file

```gradle
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'org.springframework.boot:spring-boot-gradle-plugin:1.5.3.RELEASE'
        classpath 'org.flywaydb:flyway-gradle-plugin:4.2.0'
        classpath 'net.saliman:gradle-properties-plugin:1.4.2'
        classpath 'org.hidetake:gradle-ssh-plugin:1.1.5'
    }
}

apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'idea'
apply plugin: 'org.springframework.boot'
apply plugin: 'org.hidetake.ssh'
// apply plugin: 'jar'

//mainClassName = 'com.bits.agis.Application'


jar {
    baseName = 'pp-conference'
    version =  '0.1.0'
}

//war {
  //  baseName = 'ROOT'
    
//}

repositories {
    mavenCentral()
}

sourceCompatibility = 1.8
targetCompatibility = 1.8

configurations {

    providedRuntime

}

dependencies {
    compile( 'org.springframework.boot:spring-boot-starter-web:1.2.0.RELEASE',
             'org.springframework.boot:spring-boot-starter-actuator:1.2.0.RELEASE',
             'org.springframework.boot:spring-boot-starter-data-jpa:1.2.0.RELEASE',
             'org.springframework:spring-context-support:3.2.8.RELEASE',
             'org.springframework.boot:spring-boot-starter-security:1.2.0.RELEASE',
             'org.springframework.boot:spring-boot-starter-test',
             'joda-time:joda-time:2.9.9',
             'org.jadira.usertype:usertype.jodatime:2.0.1',
             'io.springfox:springfox-swagger-ui:2.7.0',
             'io.springfox:springfox-data-rest:2.7.0',
             'io.springfox:springfox-swagger2:2.7.0',
             'commons-lang:commons-lang:2.6',
             'com.google.code.gson:gson:2.8.1',
             'mysql:mysql-connector-java',
             'com.amazonaws:aws-java-sdk-s3:1.11.160',
             'commons-fileupload:commons-fileupload:1.3.3',
			 'org.springframework.boot:spring-boot-starter-mail:1.5.6.RELEASE',
			 'org.springframework.boot:spring-boot-starter-thymeleaf:1.5.6.RELEASE',
             'com.itextpdf:itextpdf:5.0.6',
             'org.apache.commons:commons-csv:1.5',
             'org.apache.poi:poi:3.16',
             'org.apache.poi:poi-ooxml:3.16',
             'com.itextpdf.tool:xmlworker:5.5.13',
             'io.jsonwebtoken:jjwt:0.9.0',
             'com.zaxxer:HikariCP:3.2.0',
             'com.microsoft.azure:azure-storage:8.0.0',
             'org.springframework.boot:spring-boot-starter-actuator',
             'org.bouncycastle:bcpkix-jdk15on:1.47',
             'com.microsoft.azure:azure-servicebus:3.1.2',
             'org.flywaydb:flyway-core:5.2.4'

        )
        compile group: 'org.apache.poi', name: 'poi', version: '3.9'
        compile group: 'org.apache.poi', name: 'poi-ooxml', version: '3.9'
    compile group: 'org.apache.commons', name: 'commons-lang3', version: '3.5'
    compile group: 'org.apache.commons', name: 'commons-io', version: '1.3.2'
    compile 'com.google.api-client:google-api-client:1.23.0'
	compile 'com.google.apis:google-api-services-calendar:v3-rev305-1.23.0'
	compile group: 'commons-logging', name: 'commons-logging', version: '1.1.1'
    compile group: 'net.sf.biweekly', name: 'biweekly', version: '0.6.5'
    compile group: 'com.sendgrid', name: 'sendgrid-java', version: '4.7.1'
    compile group: 'org.asynchttpclient', name: 'async-http-client', version: '2.12.3'
    compile group: 'com.microsoft.azure', name: 'azure-servicebus-jms-spring-boot-starter', version: '2.3.5'
    
 providedRuntime (
        'org.springframework.boot:spring-boot-starter-tomcat:1.2.0.RELEASE'
    )
}
```
Java Code
*************
@JmsListener(destination = TOPIC_NAME, containerFactory = "topicJmsListenerContainerFactory", subscription = SUBSCRIPTION_NAME)
	public void receiveMessage(Object message) throws JMSException {
	
       /* Business logic goes here */
      
	}

NOTE:
--------
Tested with all the available version of Azure Spring Boot Starter For Azure Service Bus JMS in [https://mvnrepository.com/artifact/com.microsoft.azure/azure-servicebus-jms-spring-boot-starter](url) .. still facing same issue.

It is working perfectly fine with latest spring-boot version but problem occurring for lower spring-boot version like  1.2.0.RELEASE.

**Comment by saragluna** [comment]
@yiliuTo could you take a look at this?

**Comment by yiliuTo** [comment]
Hi @razibrath , there are dependency conflicts between the version of azure-spring-boot-starter-servicebus-jms and that of Spring Boot you selected. For the jms starter of 2.3.5, please use Spring Boot 2.3.x. And also we don't have starters compatible with Spring Boot 1.x.x.

For more details about dependency mapping between our starters and Spring Boot, please refer to https://github.com/Azure/azure-sdk-for-java/wiki/Spring-Boot-Dependency-Mapping

**Comment by razibrath** [comment]
> Hi @razibrath , there are dependency conflicts between the version of azure-spring-boot-starter-servicebus-jms and that of Spring Boot you selected. For the jms starter of 2.3.5, please use Spring Boot 2.3.x. And also we don't have starters compatible with Spring Boot 1.x.x.
> 
> For more details about dependency mapping between our starters and Spring Boot, please refer to https://github.com/Azure/azure-sdk-for-java/wiki/Spring-Boot-Dependency-Mapping

Hi @yiliuTo Thanks for the response. I am facing same issue even with jms starter 2.1.7. Is there any workaround for this .. Since our project is on springboot 1.x.x. it will be very difficult to upgrade.

**Comment by yiliuTo** [comment]
Hi @razibrath , due to that Spring Boot 1.x.x. is out of our support which is an EOL version of Spring Boot also, thus we don't have plans to publish releases compatible with 1.x.x. 

And if you still expect the function of our jms starter, my suggestion is that you could directly configure those beans provided by our starter, because all beans you need to define are only a [ConnectionFactory ](https://github.com/Azure/azure-sdk-for-java/blob/407b4e0bffbb75b461c0512e669a6d43376fa7ab/sdk/spring/azure-spring-boot/src/main/java/com/microsoft/azure/spring/autoconfigure/jms/ServiceBusJMSAutoConfiguration.java#L32) and a [JmsListenerContainerFactory](https://github.com/Azure/azure-sdk-for-java/blob/407b4e0bffbb75b461c0512e669a6d43376fa7ab/sdk/spring/azure-spring-boot/src/main/java/com/microsoft/azure/spring/autoconfigure/jms/ServiceBusJMSAutoConfiguration.java#L68).  The Connectionfactory we use is to build a cache for connections, sessions, producers and consumers. The JmsListenerContainerFactory is just a default container factory that binds to the connection factory.

**Comment by saragluna** [comment]
Closing this issue for no response, please reopen it if you have further questions.
