### ISSUE TITLE
[BUG] azure-spring-boot netty incompatibility with blob storage

### ISSUE THREAD

**Issue by bilak** [Azure/azure-sdk-for-java#21105]
**Describe the bug**
After upgrade to `azure-spring-boot-bom:3.4.0` and `spring-boot:2.4.5` there seems to be an issue with storage accounts and netty libraries.  

***Exception or Stack Trace***
```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'blobServiceClient' defined in class path resource [com/example/serviceapi/imports/config/AzureConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.azure.storage.blob.BlobServiceClient]: Factory method 'blobServiceClient' threw exception; nested exception is java.lang.NoClassDefFoundError: reactor/netty/channel/BootstrapHandlers
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:658)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:638)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1334)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1380)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1300)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
	... 116 more
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.azure.storage.blob.BlobServiceClient]: Factory method 'blobServiceClient' threw exception; nested exception is java.lang.NoClassDefFoundError: reactor/netty/channel/BootstrapHandlers
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
	... 130 more
Caused by: java.lang.NoClassDefFoundError: reactor/netty/channel/BootstrapHandlers
	at com.azure.core.http.netty.NettyAsyncHttpClientBuilder.lambda$build$4(NettyAsyncHttpClientBuilder.java:135)
	at reactor.netty.tcp.TcpClient.bootstrap(TcpClient.java:187)
	at com.azure.core.http.netty.NettyAsyncHttpClientBuilder.lambda$build$7(NettyAsyncHttpClientBuilder.java:135)
	at reactor.netty.http.client.HttpClient.tcpConfiguration(HttpClient.java:1466)
	at com.azure.core.http.netty.NettyAsyncHttpClientBuilder.build(NettyAsyncHttpClientBuilder.java:121)
	at com.azure.core.http.netty.implementation.ReactorNettyClientProvider.createInstance(ReactorNettyClientProvider.java:14)
	at com.azure.core.implementation.http.HttpClientProviders.createInstance(HttpClientProviders.java:51)
	at com.azure.core.http.HttpClient.createDefault(HttpClient.java:50)
	at com.azure.core.http.HttpClient.createDefault(HttpClient.java:40)
	at com.azure.core.http.HttpPipelineBuilder.build(HttpPipelineBuilder.java:62)
	at com.azure.storage.blob.implementation.util.BuilderHelper.buildPipeline(BuilderHelper.java:133)
	at com.azure.storage.blob.BlobServiceClientBuilder.buildAsyncClient(BlobServiceClientBuilder.java:113)
	at com.azure.storage.blob.BlobServiceClientBuilder.buildClient(BlobServiceClientBuilder.java:89)
	at com.example.serviceapi.imports.config.AzureConfiguration.blobServiceClient(AzureConfiguration.java:14)
	at com.example.serviceapi.imports.config.AzureConfiguration$$EnhancerBySpringCGLIB$$70a8f185.CGLIB$blobServiceClient$0(<generated>)
	at com.example.serviceapi.imports.config.AzureConfiguration$$EnhancerBySpringCGLIB$$70a8f185$$FastClassBySpringCGLIB$$ed6ee5ec.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
	at com.example.serviceapi.imports.config.AzureConfiguration$$EnhancerBySpringCGLIB$$70a8f185.blobServiceClient(<generated>)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 131 more
Caused by: java.lang.ClassNotFoundException: reactor.netty.channel.BootstrapHandlers
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 155 more
```

**To Reproduce**
Extend spring-boot-parent
```
<parent>
  <groupId>org.springframework.boot</groupId>
  <artifactId>spring-boot-starter-parent</artifactId>
  <version>2.4.5</version>
  <relativePath/>
</parent>
```

import 
```
<dependency>
    <groupId>com.azure.spring</groupId>
    <artifactId>azure-spring-boot-bom</artifactId>
    <version>${azure-spring-boot.version}</version>
    <type>pom</type>
    <scope>import</scope>
</dependency>
```

and then try to instantiate `BlobServiceClient`

something like this
```
@Bean
  public BlobServiceClient blobServiceClient(AzureStorageConfig azureStorageConfig) {
    return new BlobServiceClientBuilder().connectionString(azureStorageConfig.getConnectionString()).buildClient();
  }
```

**Expected behavior**
There won't be an dependency issue.

**Setup (please complete the following information):**
 - OS: [e.g. iOS] linux
 - IDE : [e.g. IntelliJ] intellij also maven command line
 - Version of the Library used - defined by bom (blob storage `12.10.2`)

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ x] Bug Description Added
- [ x] Repro Steps Added
- [ x] Setup information Added

**Comment by bilak** [comment]
problem seems to be old version of `azure-core-http-netty`. Here I'm getting version `1.7.1` but when I upgrade to `1.9.1` looks like it's resolved. Is this the correct workaround?

**Comment by bilak** [comment]
Ahh no, you probably forgot to upgrade storage right? So `azure.storage.blob.version` in your bom should be `12.11.0`? Quite a mess :D

**Comment by stliu** [comment]
I tried locally but failed to reproduce it, here is the pom i'm using

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.4.5</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
	<groupId>com.example</groupId>
	<artifactId>demo</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>demo</name>
	<description>Demo project for Spring Boot</description>
	<properties>
		<java.version>11</java.version>
		<azure-spring-boot.version>3.4.0</azure-spring-boot.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-webflux</artifactId>
		</dependency>
		<dependency>
			<groupId>com.azure</groupId>
			<artifactId>azure-storage-blob</artifactId>
		</dependency>
		<dependency>
			<groupId>com.azure.spring</groupId>
			<artifactId>azure-spring-boot-starter-storage</artifactId>
		</dependency>
		<dependency>
			<groupId>com.azure.spring</groupId>
			<artifactId>azure-spring-boot-starter</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>com.azure.spring</groupId>
				<artifactId>azure-spring-boot-bom</artifactId>
				<version>${azure-spring-boot.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

</project>
```

and I have a simple code

```
@SpringBootApplication
public class DemoApplication {

	public static void main(String[] args) {
		SpringApplication.run(DemoApplication.class, args);
	}
	@Bean
	public BlobServiceClient blobServiceClient() {

		return new BlobServiceClientBuilder()
			.endpoint("<<ENDPOINT>>")
			.sasToken("<<SAS TOKEN>>")
			.buildClient();
	}
}

```
