### ISSUE TITLE
[BUG] [azure-identity] InteractiveBrowserCredential not working with most popular browsers on OSX

### ISSUE THREAD

**Issue by raniemi** [Azure/azure-sdk-for-java#21166]
**Describe the bug**
When trying to authenticate with Azure via Interactive Browser from a Java/Sprint application, the following error is thrown:
```
...
Caused by: com.azure.core.exception.ClientAuthenticationException: Failed to acquire token with Interactive Browser Authentication.
        at com.azure.identity.implementation.IdentityClient.lambda$authenticateWithBrowserInteraction$28(IdentityClient.java:703)
...
Caused by: com.microsoft.aad.msal4j.MsalClientException: Unable to open default system browser
        at com.microsoft.aad.msal4j.AcquireTokenByInteractiveFlowSupplier.openDefaultSystemBrowser(AcquireTokenByInteractiveFlowSupplier.java:116)
...
```
And the application halts.

**To Reproduce**
* This was ran many times in OSX with the default browser (in the OS) set to Safari, Chrome or Edge.

***Code Snippet***
```groovy
        // i.e. scopes = [ 'https://graph.microsoft.com/.default' ]
        final InteractiveBrowserCredential interactiveBrowserCredential = new InteractiveBrowserCredentialBuilder()
                .clientId(clientId)
                .tenantId(tenantId)
                .redirectUrl(redirectUrl)
                .build()

        final TokenCredentialAuthProvider tokenCredentialAuthProvider =
                new TokenCredentialAuthProvider(scopes, interactiveBrowserCredential);

        // For illustration purposes
        GraphServiceClient
                .builder()
                .authenticationProvider(tokenCredentialAuthProvider)
                .buildClient()
```

**Expected behavior**
For my Java/Spring application to be able to use the default/any browser to construct a usable `TokenCredentialAuthProvider` so that I can use other Microsoft clients like Microsoft Graph.

**Setup (please complete the following information):**
 - OS: OSX Big Sur
 - aws-identity: 1.2.5 

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by joshfree** [comment]
@g2vinay could you please take a look?
