### ISSUE TITLE
[BUG] App Configuration SDK - getClientFIlters breaks if ClientFilter is null

### ISSUE THREAD

**Issue by mrm9084** [Azure/azure-sdk-for-java#21210]
**Describe the bug**
By default `clientFilters` isn't set, so it is defaulted to null.

```java
private List<FeatureFlagFilter> clientFilters;
```

Doing the following:
```java
FeatureFlagConfigurationSetting featureFlag = new FeatureFlagConfigurationSetting("Beta",true);
featureFlag.getClientFilters();
```

Results in a NullPointerException.

***Exception or Stack Trace***
java.lang.NullPointerException
	at java.base/java.util.Collections$UnmodifiableCollection.<init>(Collections.java:1028)
	at java.base/java.util.Collections$UnmodifiableList.<init>(Collections.java:1301)
	at java.base/java.util.Collections.unmodifiableList(Collections.java:1288)
	at com.azure.data.appconfiguration.models.FeatureFlagConfigurationSetting.getClientFilters(FeatureFlagConfigurationSetting.java:187)
	at com.microsoft.azure.spring.cloud.config.feature.management.entity.Feature.<init>(Feature.java:30)
	at com.microsoft.azure.spring.cloud.config.AppConfigurationPropertySource.createFeature(AppConfigurationPropertySource.java:276)
	at com.microsoft.azure.spring.cloud.config.AppConfigurationPropertySource.addToFeatureSet(AppConfigurationPropertySource.java:250)
	at com.microsoft.azure.spring.cloud.config.AppConfigurationPropertySource.initProperties(AppConfigurationPropertySource.java:191)
	at com.microsoft.azure.spring.cloud.config.AppConfigurationPropertySourceTest.testFeatureFlagBuildError(AppConfigurationPropertySourceTest.java:321)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:42)
	at org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:80)
	at org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:72)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:95)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:91)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:60)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestReference.run(JUnit5TestReference.java:98)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:768)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

**To Reproduce**
```java
FeatureFlagConfigurationSetting featureFlag = new FeatureFlagConfigurationSetting("Beta",true);
featureFlag.getClientFilters();
```

***Code Snippet***
See Above.

**Expected behavior**
Should return null.

**Screenshots**
N/A

**Setup (please complete the following information):**
 - OS: Windows
 - IDE : Eclipse
 - Version of the Library used: 1.2.0-beta.1

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X ] Bug Description Added
- [X ] Repro Steps Added
- [X ] Setup information Added

**Comment by mrm9084** [comment]
Looking at this a bit more the addClientFilter has a similar issue.
public FeatureFlagConfigurationSetting addClientFilter(FeatureFlagFilter clientFilter) {
        clientFilters.add(clientFilter);
        return this;
    }

Because of this the only way  to tell if you have any client filters is by getting the null pointer thrown. Then calling the set method.

**Comment by mrm9084** [comment]
@mssfang Any update on this?
