### ISSUE TITLE
[BUG] HDInsights cluster creation fails with 500 An error has occurred

### ISSUE THREAD

**Issue by medvedzver** [Azure/azure-sdk-for-java#21620]
Trying to create HDInsights spark cluster 4.0 using  code from [CreateSparkClusterSample](https://github.com/Azure-Samples/hdinsight-java-sdk-samples/blob/main/management/src/main/java/com/microsoft/azure/hdinsight/samples/CreateSparkClusterSample.java) 
Only change I have is having "withVirtualNetworkProfile"  for head and work nodes. 

Fails with the following stacktrace. 
`Exception in thread "main" com.microsoft.azure.CloudException: An error has occurred.: An error has occurred.
	at com.microsoft.azure.AzureClient.createExceptionFromResponse(AzureClient.java:771)
	at com.microsoft.azure.AzureClient.access$100(AzureClient.java:33)
	at com.microsoft.azure.AzureClient$3.call(AzureClient.java:160)
	at com.microsoft.azure.AzureClient$3.call(AzureClient.java:157)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
	at retrofit2.adapter.rxjava.CallArbiter.deliverResponse(CallArbiter.java:120)
	at retrofit2.adapter.rxjava.CallArbiter.emitResponse(CallArbiter.java:102)
	at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:46)
	at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:24)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeSingle.call(OnSubscribeSingle.java:81)
	at rx.internal.operators.OnSubscribeSingle.call(OnSubscribeSingle.java:27)
	at rx.internal.operators.SingleToObservable.call(SingleToObservable.java:39)
	at rx.internal.operators.SingleToObservable.call(SingleToObservable.java:27)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.DeferredScalarSubscriber.subscribeTo(DeferredScalarSubscriber.java:153)
	at rx.internal.operators.OnSubscribeTakeLastOne.call(OnSubscribeTakeLastOne.java:32)
	at rx.internal.operators.OnSubscribeTakeLastOne.call(OnSubscribeTakeLastOne.java:22)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.DeferredScalarSubscriber.subscribeTo(DeferredScalarSubscriber.java:153)
	at rx.internal.operators.OnSubscribeTakeLastOne.call(OnSubscribeTakeLastOne.java:32)
	at rx.internal.operators.OnSubscribeTakeLastOne.call(OnSubscribeTakeLastOne.java:22)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.subscribe(Observable.java:10423)
	at rx.Observable.subscribe(Observable.java:10390)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:443)
	at rx.observables.BlockingObservable.last(BlockingObservable.java:226)
	at com.microsoft.azure.management.hdinsight.v2018_06_01_preview.implementation.ClustersInner.create(ClustersInner.java:176)
	at com.linkedin.jitoffline.impl.Main.main(Main.java:142)
Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: retrofit2.Response.class
	at rx.exceptions.OnErrorThrowable.addValueAsLastCause(OnErrorThrowable.java:118)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:73)
	... 38 more
`

Libs I'm using:
`com.microsoft.azure:azure-client-authentication:1.7.0`
`com.microsoft.azure.hdinsight.v2018_06_01_preview:azure-mgmt-hdinsight:1.3.8`
`com.microsoft.azure:azure:1.30.0`

**I've contacted azure support via ICM ticket and this was response from support:**
I see several 500 response coming from your subscription, focusing more on the cluster attempts for "clusterwithfullvnet" and "clusterwithshortvnet2", I took the ActivityId and cross-reference those with our LogEntry and kept seeing the same message popup:

[Microsoft.Identity.ServerAuthorization] [16515178] [Decision: Deny] [Certificate:DF4D2C02B7F733BB44849D827A5BC6AFA11B316C SHA256:fafcc31632829dc112aafcdf834010fe299025a7fd4074643faf96551baf7d1c SigAlgo:sha256RSA [Subject:serviceclientcert.management.azure.com Issuer:Microsoft RSA TLS CA 01]] [Reason: NotInAllowedSubjectNames] [Cached: 2021-05-08T02:10:56.5896815Z]

Could not validate cert using San and Issuer.Falling back to thumbprint based validation for cert DF4D2C02B7F733BB44849D827A5BC6AFA11B316C

I'm not sure where this error is coming from , or what is that certificate. 
Are we missing something on our end? 

Thank you!

**Comment by joshfree** [comment]
@yungezz could you please follow up with @medvedzver

**Comment by yungezz** [comment]
hi @weidongxu-microsoft could you help on this? hanks

**Comment by weidongxu-microsoft** [comment]
@medvedzver 

Please use this new SDK https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/hdinsight/azure-resourcemanager-hdinsight

I've added a test case with same functionality of this sample (+ virtual network). I do not see any error.
https://github.com/Azure/azure-sdk-for-java/pull/21624/files

**Comment by medvedzver** [comment]
@weidongxu-microsoft  THanks for the quick response. Will try today and let you know!

**Comment by medvedzver** [comment]
Verified - was able to create cluster using SDK you've provided.
Thanks!
