### ISSUE TITLE
[BUG] azure-media and Spring Boot 2.4.x

### ISSUE THREAD

**Issue by insx** [Azure/azure-sdk-for-java#21679]
**Description**
azure-media 0.9.8 with Spring Boot 2.4.5 fails with error `java.lang.NoClassDefFoundError: com/nimbusds/oauth2/sdk/http/CommonContentTypes`

**To Reproduce**
For example, if we run Sample for Azure Media Services Spring Boot client library for Java (azure-spring-boot-sample-mediaservices), it fails with a stack trace:
```
2021-05-20 16:24:09.240  WARN 10964 --- [           main] c.m.w.services.media.MediaContract       : com.sun.jersey.api.client.ClientHandlerException: Failed to acquire access token

com.sun.jersey.api.client.ClientHandlerException: Failed to acquire access token
	at com.microsoft.windowsazure.services.media.implementation.OAuthFilter.doHandle(OAuthFilter.java:58) ~[azure-media-0.9.8.jar:na]
	at com.microsoft.windowsazure.core.pipeline.jersey.IdempotentClientFilter.handle(IdempotentClientFilter.java:44) ~[azure-core-0.9.8.jar:na]
	at com.microsoft.windowsazure.services.media.implementation.VersionHeadersFilter.doHandle(VersionHeadersFilter.java:44) ~[azure-media-0.9.8.jar:na]
	at com.microsoft.windowsazure.core.pipeline.jersey.IdempotentClientFilter.handle(IdempotentClientFilter.java:44) ~[azure-core-0.9.8.jar:na]
	at com.microsoft.windowsazure.core.pipeline.jersey.ClientFilterRequestAdapter.handle(ClientFilterRequestAdapter.java:35) ~[azure-core-0.9.8.jar:na]
	at com.sun.jersey.api.client.Client.handle(Client.java:652) ~[jersey-client-1.19.jar:1.19]
	at com.sun.jersey.api.client.WebResource.handle(WebResource.java:682) ~[jersey-client-1.19.jar:1.19]
	at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74) ~[jersey-client-1.19.jar:1.19]
	at com.sun.jersey.api.client.WebResource$Builder.post(WebResource.java:570) ~[jersey-client-1.19.jar:1.19]
	at com.microsoft.windowsazure.services.media.entityoperations.EntityRestProxy.create(EntityRestProxy.java:136) ~[azure-media-0.9.8.jar:na]
	at com.microsoft.windowsazure.services.media.implementation.MediaExceptionProcessor.create(MediaExceptionProcessor.java:140) ~[azure-media-0.9.8.jar:na]
	at com.azure.spring.sample.mediaservices.MediaServicesSampleApplication.uploadFileAndCreateAsset(MediaServicesSampleApplication.java:51) ~[classes/:na]
	at com.azure.spring.sample.mediaservices.MediaServicesSampleApplication.run(MediaServicesSampleApplication.java:37) ~[classes/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:819) ~[spring-boot-2.4.5.jar:2.4.5]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:803) ~[spring-boot-2.4.5.jar:2.4.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:346) ~[spring-boot-2.4.5.jar:2.4.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1340) ~[spring-boot-2.4.5.jar:2.4.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1329) ~[spring-boot-2.4.5.jar:2.4.5]
	at com.azure.spring.sample.mediaservices.MediaServicesSampleApplication.main(MediaServicesSampleApplication.java:27) ~[classes/:na]
Caused by: java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: com/nimbusds/oauth2/sdk/http/CommonContentTypes
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191) ~[na:na]
	at com.microsoft.windowsazure.services.media.authentication.AzureAdTokenProvider.acquireAccessToken(AzureAdTokenProvider.java:53) ~[azure-media-0.9.8.jar:na]
	at com.microsoft.windowsazure.services.media.implementation.OAuthFilter.doHandle(OAuthFilter.java:56) ~[azure-media-0.9.8.jar:na]
	... 18 common frames omitted
Caused by: java.lang.NoClassDefFoundError: com/nimbusds/oauth2/sdk/http/CommonContentTypes
	at com.microsoft.aad.adal4j.AdalTokenRequest.toOAuthRequest(AdalTokenRequest.java:128) ~[adal4j-1.2.0.jar:1.2.0]
	at com.microsoft.aad.adal4j.AdalTokenRequest.executeOAuthRequestAndProcessResponse(AdalTokenRequest.java:78) ~[adal4j-1.2.0.jar:1.2.0]
	at com.microsoft.aad.adal4j.AuthenticationContext.acquireTokenCommon(AuthenticationContext.java:816) ~[adal4j-1.2.0.jar:1.2.0]
	at com.microsoft.aad.adal4j.AuthenticationContext.access$100(AuthenticationContext.java:64) ~[adal4j-1.2.0.jar:1.2.0]
	at com.microsoft.aad.adal4j.AuthenticationContext$1.call(AuthenticationContext.java:172) ~[adal4j-1.2.0.jar:1.2.0]
	at com.microsoft.aad.adal4j.AuthenticationContext$1.call(AuthenticationContext.java:161) ~[adal4j-1.2.0.jar:1.2.0]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:832) ~[na:na]
Caused by: java.lang.ClassNotFoundException: com.nimbusds.oauth2.sdk.http.CommonContentTypes
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[na:na]
	... 10 common frames omitted
```
**Setup**
 - OS: Windows 10 / Debian 
 - IDE : Intellij Idea
 - Version of the Library used:
   - azure-media 0.9.8 
   - Spring Boot 2.4.5

**Additional context**
The last working Spring Boot version seems to be 2.2.13.RELEASE, which I can not downgrade to. How can I hotfix it?

**Comment by joshfree** [comment]
@stliu could you please help route @insx 's issue

**Comment by yiliuTo** [comment]
Hi @insx , thanks for your reporting. The com.microsoft.azure:azure-media;0.9.8 uses com.microsoft.azure:adal4j;1.2.0 which has version conflicts with Spring Boot 2.4.x. So you could rollback the version of the conflicted library com.nimbusds:oauth2-oidc-sdk to 5.x.x.

For example, add following library in the pom.xml of the sample project:
```
    <dependency>
      <groupId>com.nimbusds</groupId>
      <artifactId>oauth2-oidc-sdk</artifactId>
      <version>5.64.4</version>
      <scope>runtime</scope>
    </dependency>
```
And we will update our sample soon.

**Comment by insx** [comment]
Thanks, @yiliuTo ! It works for me.
