### ISSUE TITLE
Fix pipeline failure about keyvault-ci

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#21677]
1. https://dev.azure.com/azure-sdk/public/_build/results?buildId=904506&view=results

```
[ERROR] signVerifyEcLocal  Time elapsed: 0.005 s  <<< ERROR!
java.lang.IllegalArgumentException: missing provider
	at java.base/sun.security.jca.GetInstance.getService(GetInstance.java:96)
	at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:218)
	at java.base/java.security.KeyPairGenerator.getInstance(KeyPairGenerator.java:340)
	at com.azure.security.keyvault.keys@4.3.0-beta.9/com.azure.security.keyvault.keys.cryptography.CryptographyClientTest.signVerifyEcLocal(CryptographyClientTest.java:265)
```

**Comment by chenrujun** [comment]
Hi, @vcolin7 , could you please help to fix the pipeline failure?
