### ISSUE TITLE
[Question] Using ManagedIdentityCredential with EncryptedBlobClientBuilder

### ISSUE THREAD

**Issue by ChimneyCake** [Azure/azure-sdk-for-java#21767]
**Query/Question**
Is there a way to use ManagedIdentityCredential class to authenticate on Azure Storage using EncryptedBlobClientBuilder?
I am getting exception :

> c.a.identity.ManagedIdentityCredential   : Azure Identity => ERROR in getToken() call for scopes [https://accountName.blob.core.windows.net/.default]: ManagedIdentityCredential authentication unavailable. Connection to IMDS endpoint cannot be established, connect timed out. 
and
> java.lang.RuntimeException: MSI: Failed to acquire tokens after retrying 3 times at com.azure.identity.implementation.IdentityClient.lambda$authenticateToIMDSEndpoint$36(IdentityClient.java:1073)

***Why is this not a Bug or a feature Request?***
This is a question regarding exception I am getting while using ManagedIdentityCredential with EncryptedBlobClientBuilder

**Setup (please complete the following information if applicable):**
 I am using IntelliJ on macOS Catalina and following dependencies:
 `<dependency>
      <groupId>com.azure</groupId>
      <artifactId>azure-identity</artifactId>
      <version>1.2.1</version>
    </dependency>
<dependency>
      <groupId>com.azure</groupId>
      <artifactId>azure-storage-blob</artifactId>
      <version>12.6.1</version>
    </dependency>
    <dependency>
      <groupId>com.azure</groupId>
      <artifactId>azure-storage-blob-cryptography</artifactId>
      <version>12.6.1</version>
    </dependency> `

Also, my code looks like this:
`new EncryptedBlobClientBuilder().key(encKey, KeyWrapAlgorithm.A256KW.toString())
                .keyResolver(resolver)
                .containerName(containerName)
                .endpoint("https://accountName.blob.core.windows.net/containerName"),
                .credential(new ManagedIdentityCredentialBuilder().clientId(clientId).build());`

 Please advise on how to proceed.

 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by joshfree** [comment]
@gapra-msft could you please follow up with @ChimneyCake

**Comment by gapra-msft** [comment]
Hi @ChimneyCake, ManagedIdentity credential should work. It looks like the identity SDK is failing to acquire the Token.

@g2vinay could you take a look?

**Comment by g2vinay** [comment]
@ChimneyCake 
The ManafgedIdentityCredential won't work on the local development machine, it works only on Azure Hosted Machines/Services.

For Local use, I recommend using `[ClientSecretCredential](https://docs.microsoft.com/en-us/azure/developer/java/sdk/identity-service-principal-auth#client-secret-credential)` which uses service Principal Authentication or one of the credentials which support [Authentication in Development environments](https://docs.microsoft.com/en-us/azure/developer/java/sdk/identity-dev-env-auth).

**Comment by ChimneyCake** [comment]
@g2vinay 
Except in local machine, I tried on Production environment. I'd like to replace storage account key with authentication using Managed Identities. I already have Storage Account and Managed Identities created and I would like to make sure that Storage is only accessible to roles defined in the Managed Identity. What do you propose for that purpose?

**Comment by g2vinay** [comment]
@ChimneyCake 
On which Azure Resource (Production env) are you running the application/code on?

Assuming you're running this on Azure VM, 
you will need to enable Managed Identity on the Azure VM first, in order to use `ManagedIdentityCredential`
You can use System Assigned or User Assigned Identity with the Azure VM.

Follow detailed Instructions [here](https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/qs-configure-portal-windows-vm). 

I notice you're passing a `clientId` to `ManagedIdentityCredential` in your code, what resource is represented by this clientId here?
`new ManagedIdentityCredentialBuilder().clientId(clientId)`

Once you've enabled Managed Identity on the Azure VM, In your storage account resource, assign RBAC access to the Azure VM System/User assigned Identity via IAM.

With this setup, the `ManagedIdentityCredential` should work fine.

**Comment by ChimneyCake** [comment]
@g2vinay 

ClientId I am passing is clientId of Managed Identity resource I have.

I have successfully generated an access token(having `Azure Identity => getToken() result for scopes [https://accountName.blob.core.windows.net/.default]: SUCCESS` in my log) but I started getting an exception related to storage access:

`
com.azure.storage.blob.models.BlobStorageException: Status code 403, (empty body)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.azure.core.http.rest.RestProxy.instantiateUnexpectedException(RestProxy.java:357)
	at com.azure.core.http.rest.RestProxy.lambda$ensureExpectedStatus$6(RestProxy.java:420)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4213)
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FluxSwitchIfEmpty.java:75)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onComplete(MonoFlatMap.java:174)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onComplete(FluxDoFinally.java:138)
	at reactor.core.publisher.FluxHandle$HandleSubscriber.onComplete(FluxHandle.java:206)
	at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onComplete(FluxMap.java:262)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onComplete(FluxDoFinally.java:138)
	at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:195)
	at reactor.core.publisher.FluxContextStart$ContextStartSubscriber.onNext(FluxContextStart.java:96)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1782)
	at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:121)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:252)
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:136)
	at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:378)
	at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:373)
	at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:429)
	at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:625)
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:96)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1526)
	at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1287)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1324)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
		at reactor.core.publisher.Mono.block(Mono.java:1680)
		at com.azure.storage.common.implementation.StorageImplUtils.blockWithOptionalTimeout(StorageImplUtils.java:99)
		at com.azure.storage.blob.specialized.BlobClientBase.existsWithResponse(BlobClientBase.java:233)
		at com.azure.storage.blob.specialized.BlobClientBase.exists(BlobClientBase.java:216)
` 

What could be the reason for seeing this? Is there any additional configuration I should have to make this work as a whole?
Before adding ManagedIdentityCredential everything worked as it should, and adding ManagedIdentityCredential is the only change.

**Comment by gapra-msft** [comment]
Hi @ChimneyCake 

Could you share the permissions on the Managed Identity Credential? You could be missing some permissions. 

In addition to that sharing the x-ms-requestid for the failed storage call would also help me identify why the storage service is throwing this error.

**Comment by ChimneyCake** [comment]
@gapra-msft 

You are right, I was missing some of the permissions. Now, I have added Storage Blob Data Contributor role to my Managed Identity, and it works as it should.

Thank you all for help!

**Comment by gapra-msft** [comment]
Great! I will go ahead and close this issue as I believe its been resolved. Feel free to re-open/open a new issue if you hit other problems.
