### ISSUE TITLE
[BUG] Spring Cloud Stream for Event Hubs does not work with kotlin consumer functions

### ISSUE THREAD

**Issue by vbef-finatix** [Azure/azure-sdk-for-java#21815]
**Describe the bug**
The spring cloud stream binder for the eventhub doesn't appear to support kotlin consumers.

***Exception or Stack Trace***
```
2021-05-25 08:57:59.213  WARN 9642 --- [tition-pump-0-5] c.a.s.i.e.c.EventHubMessageConverter     : System property azure_eventhub_sequence_number(2078) is not allowed to be defined and will be ignored.
2021-05-25 08:57:59.214  WARN 9642 --- [tition-pump-0-5] c.a.s.i.e.c.EventHubMessageConverter     : System property azure_eventhub_enqueued_time(2021-05-25T06:57:59.042Z) is not allowed to be defined and will be ignored.
2021-05-25 08:57:59.214  WARN 9642 --- [tition-pump-0-5] c.a.s.i.e.c.EventHubMessageConverter     : System property azure_eventhub_offset(8590988336) is not allowed to be defined and will be ignored.
2021-05-25 08:57:59.215 ERROR 9642 --- [tition-pump-0-5] c.a.m.eventhubs.EventHubClientBuilder    : 'connectionString' contains an Event Hub name [xxxxxx] and it does not match the given 'eventHubName' parameter [consume-out-0]. Please use the credentials(String connectionString) overload. Or supply a 'connectionString' without 'EntityPath' in it.
2021-05-25 08:57:59.219 ERROR 9642 --- [tition-pump-0-5] o.s.integration.handler.LoggingHandler   : org.springframework.messaging.MessageHandlingException: error occurred in message handler [com.azure.spring.integration.core.api.reactor.DefaultMessageHandler@5237edf1]; nested exception is java.lang.IllegalArgumentException: 'connectionString' contains an Event Hub name [xxxxxxxxxxxx] and it does not match the given 'eventHubName' parameter [consume-out-0]. Please use the credentials(String connectionString) overload. Or supply a 'connectionString' without 'EntityPath' in it., failedMessage=GenericMessage [payload=byte[2], headers={$.cdid=MyDevice01, azure_checkpointer=com.azure.spring.integration.core.api.reactor.AzureCheckpointer@429af3f7, temperatureAlert=false, azure_raw_partition_id=0, azure_eventhub_sequence_number=2078, azure_eventhub_enqueued_time=2021-05-25T06:57:59.042Z, id=e46a7853-22d9-b9cf-14ff-3dde14d39ad5, azure_eventhub_offset=8590988336, contentType=application/json, target-protocol=kafka, timestamp=1621925879211}]
	at org.springframework.integration.support.utils.IntegrationUtils.wrapInHandlingExceptionIfNecessary(IntegrationUtils.java:192)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:65)
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder$SendingHandler.handleMessageInternal(AbstractMessageChannelBinder.java:1041)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:56)
	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:115)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:133)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:106)
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:72)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:317)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:272)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47)
	at org.springframework.messaging.core.AbstractDestinationResolvingMessagingTemplate.send(AbstractDestinationResolvingMessagingTemplate.java:72)
	at org.springframework.cloud.stream.function.FunctionConfiguration$FunctionToDestinationBinder$1.doSendMessage(FunctionConfiguration.java:585)
	at org.springframework.cloud.stream.function.FunctionConfiguration$FunctionToDestinationBinder$1.handleMessageInternal(FunctionConfiguration.java:571)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:56)
	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:115)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:133)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:106)
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:72)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:317)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:272)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47)
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109)
	at org.springframework.integration.endpoint.MessageProducerSupport.sendMessage(MessageProducerSupport.java:208)
	at com.azure.spring.integration.core.AbstractInboundChannelAdapter.receiveMessage(AbstractInboundChannelAdapter.java:65)
	at com.azure.spring.integration.eventhub.impl.EventHubProcessor.onEvent(EventHubProcessor.java:74)
	at com.azure.messaging.eventhubs.EventProcessorClientBuilder$1.processEvent(EventProcessorClientBuilder.java:535)
	at com.azure.messaging.eventhubs.PartitionPumpManager.processEvent(PartitionPumpManager.java:270)
	at com.azure.messaging.eventhubs.PartitionPumpManager.processEvents(PartitionPumpManager.java:314)
	at com.azure.messaging.eventhubs.PartitionPumpManager.lambda$startPartitionPump$2(PartitionPumpManager.java:231)
	at reactor.core.publisher.LambdaSubscriber.onNext(LambdaSubscriber.java:160)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runAsync(FluxPublishOn.java:440)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:527)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalArgumentException: 'connectionString' contains an Event Hub name [xxxxxxx] and it does not match the given 'eventHubName' parameter [consume-out-0]. Please use the credentials(String connectionString) overload. Or supply a 'connectionString' without 'EntityPath' in it.
	at com.azure.messaging.eventhubs.EventHubClientBuilder.connectionString(EventHubClientBuilder.java:248)
	at com.azure.spring.integration.eventhub.factory.DefaultEventHubClientFactory.createProducerClient(DefaultEventHubClientFactory.java:81)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at com.azure.spring.cloud.context.core.util.Memoizer.lambda$memoize$1(Memoizer.java:24)
	at com.azure.spring.integration.eventhub.factory.DefaultEventHubClientFactory.getOrCreateProducerClient(DefaultEventHubClientFactory.java:142)
Caused by: java.lang.IllegalArgumentException: 'connectionString' contains an Event Hub name [xxxxxx] and it does not match the given 'eventHubName' parameter [consume-out-0]. Please use the credentials(String connectionString) overload. Or supply a 'connectionString' without 'EntityPath' in it.

	at com.azure.spring.integration.eventhub.impl.AbstractEventHubTemplate.doSend(AbstractEventHubTemplate.java:78)
	at com.azure.spring.integration.eventhub.impl.AbstractEventHubTemplate.sendAsync(AbstractEventHubTemplate.java:72)
	at com.azure.spring.integration.eventhub.impl.AbstractEventHubTemplate.sendAsync(AbstractEventHubTemplate.java:64)
	at com.azure.spring.integration.core.api.reactor.DefaultMessageHandler.handleMessageInternal(DefaultMessageHandler.java:77)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:56)
	... 42 more

2021-05-25 08:57:59.220 ERROR 9642 --- [tition-pump-0-5] c.a.m.eventhubs.PartitionPumpManager     : Error in event processing callback
2021-05-25 08:57:59.220 ERROR 9642 --- [tition-pump-0-5] c.a.m.eventhubs.PartitionPumpManager     : Error in event processing callback
```

**To Reproduce**
The error occurs when I rewrite my Java consumer
```java
@Bean
fun consume(): Consumer<Message<String>> {
    return Consumer<Message<String>> { msg ->
        println(msg)
    }
}
```
to a Kotlin consumer
```kotlin
@Bean
fun consume(): (Message<String>) -> Unit =
    { msg ->
        println(msg)
    }
```

**Setup (please complete the following information):**
 - Version of ibraries used
   - "org.springframework.boot:spring-boot-starter-web:2.4.4"
   - "org.springframework.cloud:spring-cloud-stream:3.1.1"
   - "com.azure.spring:azure-spring-cloud-stream-binder-eventhubs:2.4.0"
   - "org.springframework.cloud:spring-cloud-function-kotlin:3.1.2"

**Additional context**
Possibly it is related to this ticket: https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/795

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by saragluna** [comment]
@yiliuTo could you please take a look at this?

**Comment by yiliuTo** [comment]
@vbef-finatix thanks for your reporting. And as you could see [here](https://github.com/spring-cloud/spring-cloud-stream/issues/1935), this feature needs support from Spring Cloud Stream to cover Kotlin lambdas for binding functions.

**Comment by stliu** [comment]
@yiliuTo I think we should keep this one open until the spring issue fixed?

**Comment by yiliuTo** [comment]
Agree, will remove the tag to close issues automatically.

**Comment by stliu** [comment]
blocked by https://github.com/spring-cloud/spring-cloud-stream/issues/1935
