### ISSUE TITLE
[BUG] FormRecognizer SDK throws NullPointerException when parsing invoice table items.

### ISSUE THREAD

**Issue by kpentaris** [Azure/azure-sdk-for-java#21929]
**Description**
The SDK throws a NullPointerException when attempting to parse **invoice** table items that are partial or not properly understood by the Form Recognizer engine. The reason is that the SDK is not expecting to get a null object when querying a FieldValue of type object, which is possible as shown in our tests.

***Stack Trace***
```
Caused by: java.lang.NullPointerException
	at com.azure.ai.formrecognizer.Transforms.toFieldValueObject(Transforms.java:435)
	at com.azure.ai.formrecognizer.Transforms.setFormField(Transforms.java:384)
	at com.azure.ai.formrecognizer.Transforms.lambda$toFieldValueArray$8(Transforms.java:469)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.azure.ai.formrecognizer.Transforms.toFieldValueArray(Transforms.java:471)
	at com.azure.ai.formrecognizer.Transforms.setFormField(Transforms.java:380)
	at com.azure.ai.formrecognizer.Transforms.lambda$getLabeledFieldMap$6(Transforms.java:320)
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	at com.azure.ai.formrecognizer.Transforms.getLabeledFieldMap(Transforms.java:304)
	at com.azure.ai.formrecognizer.Transforms.toRecognizedForm(Transforms.java:98)
	at com.azure.ai.formrecognizer.FormRecognizerAsyncClient.lambda$beginRecognizeInvoices$87(FormRecognizerAsyncClient.java:1249)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:113)
	... 91 more
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onComplete(FluxDoFinally.java:145) [reactor-core-3.4.5.jar:3.4.5]
	at reactor.core.publisher.FluxHandle$HandleSubscriber.onComplete(FluxHandle.java:212) [reactor-core-3.4.5.jar:3.4.5]
	at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onComplete(FluxMap.java:269) [reactor-core-3.4.5.jar:3.4.5]
	at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:401) [reactor-netty-core-1.0.6.jar:1.0.6]
	at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:416) [reactor-netty-core-1.0.6.jar:1.0.6]
	at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:470) [reactor-netty-core-1.0.6.jar:1.0.6]
	at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:685) [reactor-netty-http-1.0.6.jar:1.0.6]
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:94) [reactor-netty-core-1.0.6.jar:1.0.6]
```

**To Reproduce**
- Use the Invoice Model to parse an invoice with table fields
- Sample invoice can be found here: https://drive.google.com/file/d/13b_MApmjXubzHyO5M0TgOXh0Q7HGf5He/view?usp=sharing
- The problem happens when using `FormRecognizerAsyncClient.beginRecognizeInvoices` method with fields elements included in the options.

**Expected behavior**
The SDK expected behavior would be to address the lack of an object value in this case, bypass it and keep parsing the rest of the results. The FormRecognizer service has *not* failed in this case, it has done a best effort and has returned multiple values for which we care about. The SDK, throwing the NPE, ends up discarding the rest of the work that has been done by the FormRecognizer for which we would like to have access to.

**Setup (please complete the following information):**
 - Windows 10 Home/Pro
 - IDE: N/A
 - Azure AI Form Recognizer SDK version 3.1.0

**Additional context**
Unfortunately the official image that triggers this behavior cannot be provided due to NDA concerns. The provided image is a custom made image but the behavior was reproducible with it.

**Comment by joshfree** [comment]
Thanks for reporting this @kpentaris.  @samvaity can you please investigate?

**Comment by samvaity** [comment]
Hey @kpentaris, thank you for reporting this.

I believe your finding is correct `The reason is that the SDK is not expecting to get a null object when querying a FieldValue of type object, which is possible as shown in our tests.` 

The SDK does require the `FieldValueType` and its corresponding object to be non-null for valid results.
In this specific case, I think the service is returning a `type = object` with `valueObject = null` 
![image](https://user-images.githubusercontent.com/16845631/120698730-49458a80-c464-11eb-996f-220a04129c10.png)

@ramparab Could you look more into this and see if this could be a service bug?

**Comment by samvaity** [comment]
Hello @kpentaris Thank you for finding this bug. It has been fixed in the latest released package of the SDK https://mvnrepository.com/artifact/com.azure/azure-ai-formrecognizer/3.1.1

Do let us know if it works for you.

**Comment by kpentaris** [comment]
Hi again @samvaity The bug has been fixed with the new version. Thank you for addressing this issue and with 0 extra input from me 👍
