### ISSUE TITLE
[BUG] Authentication error using Azure Identity SDK v1.2.5

### ISSUE THREAD

**Issue by mjmadhu** [Azure/azure-sdk-for-java#21952]
**Describe the bug**
I'm using VS Code v1.56.2 (not IntelliJ) and have set all the required env variables, but the stack trace mentions the client is looking credentials for IntelliJ setup.

***Exception or Stack Trace***
`2021-05-29 17:41:07.422 DEBUG 11840 --- [           main] c.azure.identity.EnvironmentCredential   : Azure Identity 
=> Found the following environment variables: AZURE_CLIENT_ID, AZURE_TENANT_ID, AZURE_CLIENT_SECRET, AZURE_USERNAME 
2021-05-29 17:41:07.426  INFO 11840 --- [           main] c.azure.identity.EnvironmentCredential   : Azure Identity 
=> EnvironmentCredential invoking ClientSecretCredential
2021-05-29 17:41:08.550 ERROR 11840 --- [           main] c.azure.identity.EnvironmentCredential   : Azure Identity 
=> ERROR in EnvironmentCredential: Failed to create a UsernamePasswordCredential. Missing required environment variable AZURE_PASSWORD
2021-05-29 17:41:08.616 DEBUG 11840 --- [           main] c.a.identity.ManagedIdentityCredential   : Azure Identity 
=> Found the following environment variables: AZURE_CLIENT_ID, AZURE_TENANT_ID, AZURE_CLIENT_SECRET, AZURE_USERNAME 
2021-05-29 17:41:08.646 DEBUG 11840 --- [           main] c.a.identity.SharedTokenCacheCredential  : Azure Identity 
=> Found the following environment variables: AZURE_CLIENT_ID, AZURE_TENANT_ID, AZURE_CLIENT_SECRET, AZURE_USERNAME 
2021-05-29 17:41:08.727 ERROR 11840 --- [           main] c.a.i.i.IntelliJCacheAccessor            : IntelliJ Authentication not available. Please log in with Azure Tools for IntelliJ plugin in the IDE.
com.azure.identity.CredentialUnavailableException: IntelliJ Authentication not available. Please log in with Azure Tools for IntelliJ plugin in the IDE.
        at com.azure.identity.implementation.IntelliJCacheAccessor.getAuthDetailsIfAvailable(IntelliJCacheAccessor.java:243) ~[azure-identity-1.2.5.jar:na]
        at com.azure.identity.IntelliJCredential.<init>(IntelliJCredential.java:51) ~[azure-identity-1.2.5.jar:na]  
        at com.azure.identity.DefaultAzureCredentialBuilder.getCredentialsChain(DefaultAzureCredentialBuilder.java:132) ~[azure-identity-1.2.5.jar:na]
        at com.azure.identity.DefaultAzureCredentialBuilder.build(DefaultAzureCredentialBuilder.java:123) ~[azure-identity-1.2.5.jar:na]
        .......`

**To Reproduce**
Use DefaultAzureCredential() Java SDK on VS Code

***Code Snippet***
`// pom.xml dependency definition
<dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-identity</artifactId>
            <version>1.2.5</version>
</dependency>
// Creation of Client
public void retrieveSecret(@Value("${key.vault.name}") String keyVaultName) {
    String keyVaultUrl = "https://" + keyVaultName + ".vault.azure.net";
        DefaultAzureCredential credential = new DefaultAzureCredentialBuilder().build();
    secretClient = new SecretClientBuilder().vaultUrl(keyVaultUrl)
                                                    .credential(credential).buildClient();
}`

**Expected behavior**
Successful authentication.

**Setup (please complete the following information):**
 - OS: Windows 10
 - IDE : VS Code v1.56.2
 - Version of the Library used - 1.2.5

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by Saljack** [comment]
We have these messages in our production applications too. We simply do:
```java
new DefaultAzureCredentialBuilder().build()
```
I do not see any reason why this is a part of azure-identity library. This should be excluded from there. There is no excuse for adding IDE specific things into this library.

**Comment by g2vinay** [comment]
@mjmadhu 
The authentication is attempted by the DefaultAzureCredential in the following order, regardless of the platform the code is running on. 

![image](https://user-images.githubusercontent.com/5430778/120231688-c1167980-c206-11eb-860c-99f7128a50b9.png)

It first tries IntelliJ authentication and if it is not available then moves on to VS Code authentication.

The above stack trace looks incomplete, as it doesn't show details after IntelliJAuthentication is attempted.

Alternatively, if you want only VS Code authentication to be tried in this scenario, 
Then you can use `VSCodeCredential` directly.

```java
VisualStudioCodeCredential codeCredential = new VisualStudioCodeCredentialBuilder().build();
SecretClient secretClient = new SecretClientBuilder().vaultUrl(keyVaultUrl).credential(codeCredential).buildClient();
```

**Comment by mjmadhu** [comment]
Thanks for the information @g2vinay 
The target is to use DefaultAzureCredential so that the app can be used locally as well as on any environment like app service using different credentials based on available env variables.

We might want to use Managed Identity Credential for Azure platforms but for testing on local we're resorting to service principal with secret way, hence we had set the following env variables locally - AZURE_CLIENT_ID, AZURE_TENANT_ID, AZURE_CLIENT_SECRET

So not sure according to the preference flow you provided, why would it fall to IDE specific creds if Env Cred are available. Also as per the logs, it doesn't seem like it's falling to VS Code Creds (IDE that we're using).

This was the only stacktrace from identity sdk, post which we have application log trace.
Later somehow, we're able to access Azure Key vault (the target azure resource) using this same credential object which seems to be working but not sure how since these logs are still there (and the creds object still shows "authentication failed..." in debug mode). Is this the expected behavior or are we missing anything here?

`DefaultAzureCredential@48
credentials:Collections$UnmodifiableRandomAccessList@58 size=6
logger:ClientLogger@59
unavailableError:"DefaultAzureCredential authentication failed. ---> "`

Complete Stack trace:

`2021-06-01 09:16:59.136 ERROR 28668 --- [           main] c.a.i.i.IntelliJCacheAccessor            : IntelliJ Authentication not available. Please log in with Azure Tools for IntelliJ plugin in the IDE.

com.azure.identity.CredentialUnavailableException: IntelliJ Authentication not available. Please log in with Azure Tools for IntelliJ plugin in the IDE.   
        at com.azure.identity.implementation.IntelliJCacheAccessor.getAuthDetailsIfAvailable(IntelliJCacheAccessor.java:243) ~[azure-identity-1.2.5.jar:na]        at com.azure.identity.IntelliJCredential.<init>(IntelliJCredential.java:51) ~[azure-identity-1.2.5.jar:na]
        at com.azure.identity.DefaultAzureCredentialBuilder.getCredentialsChain(DefaultAzureCredentialBuilder.java:132) ~[azure-identity-1.2.5.jar:na]     
        at com.azure.identity.DefaultAzureCredentialBuilder.build(DefaultAzureCredentialBuilder.java:123) ~[azure-identity-1.2.5.jar:na]
        at com.xxx.xxxxx.service.KeyVaultService.<init>(KeyVaultService.java:27) ~[classes/:na]
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:64) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:na]
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[na:na]
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481) ~[na:na]
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:212) ~[spring-beans-5.3.3.jar:5.3.3]
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:117) ~[spring-beans-5.3.3.jar:5.3.3]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:311) ~[spring-beans-5.3.3.jar:5.3.3]
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:296) ~[spring-beans-5.3.3.jar:5.3.3] 
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1356) ~[spring-beans-5.3.3.jar:5.3.3]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1206) ~[spring-beans-5.3.3.jar:5.3.3]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:571) ~[spring-beans-5.3.3.jar:5.3.3]
ableBeanFactory.java:944) ~[spring-beans-5.3.3.jar:5.3.3]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:923) ~[spring-context-5.3.3.jar:5.3.3]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:588) ~[spring-context-5.3.3.jar:5.3.3]   
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:144) ~[spring-boot-2.4.2.jar:2.4.2]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:767) ~[spring-boot-2.4.2.jar:2.4.2]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759) ~[spring-boot-2.4.2.jar:2.4.2]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:426) ~[spring-boot-2.4.2.jar:2.4.2]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:326) ~[spring-boot-2.4.2.jar:2.4.2]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1311) ~[spring-boot-2.4.2.jar:2.4.2]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300) ~[spring-boot-2.4.2.jar:2.4.2]
        at com.xxx.xxxxx.xxxxxxx.main(xxxxxxxx.java:10) ~[classes/:na]`
