### ISSUE TITLE
[BUG] [Azure-Identity] IntelliJCredential fails with unrecognized field

### ISSUE THREAD

**Issue by TzurTurkenitz** [Azure/azure-sdk-for-java#22429]
**Setup**
IntelliJ IDEA 2021.1.2, Build #IC-211.7442.40, built on May 31, 2021
OS: Windows 10
Azure Toolkit for IntelliJ 3.53.0
Library: azure-security-keyvault-secrets 4.3.0, azure-identity 1.3.1

**Describe the bug**
Signed-In user with Oauth2, Device Sign-In or CLI Sign-In fails to authenticate with `DefaultAzureCredentialBuilder` when using IntelliJCredential.

***Exception or Stack Trace***
```
Caused by: java.lang.RuntimeException: Max retries 3 times exceeded. Error Details: DefaultAzureCredential authentication failed. ---> IntelliJCredential authentication failed. Error Details: Unrecognized field "tenantId" (class com.azure.identity.implementation.IntelliJAuthMethodDetails), not marked as ignorable (4 known properties: "authMethod", "azureEnv", "accountEmail", "credFilePath"])
 at [Source: (File); line: 1, column: 58] (through reference chain: com.azure.identity.implementation.IntelliJAuthMethodDetails["tenantId"])
	at com.azure.core.http.policy.RetryPolicy.lambda$attemptAsync$1(RetryPolicy.java:127) ~[azure-core-1.17.0.jar:na]
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94) ~[reactor-core-3.4.0.jar:3.4.0]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:172) ~[reactor-core-3.4.0.jar:3.4.0]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:172) ~[reactor-core-3.4.0.jar:3.4.0]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondError(MonoFlatMap.java:192) ~[reactor-core-3.4.0.jar:3.4.0]
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onError(MonoFlatMap.java:259) ~[reactor-core-3.4.0.jar:3.4.0]
	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onError(MonoPeekTerminal.java:258) ~[reactor-core-3.4.0.jar:3.4.0]
	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onError(MonoPeekTerminal.java:258) ~[reactor-core-3.4.0.jar:3.4.0]
	at reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onError(FluxPeekFuseable.java:903) ~[reactor-core-3.4.0.jar:3.4.0]
	at reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onError(FluxPeekFuseable.java:903) ~[reactor-core-3.4.0.jar:3.4.0]
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onError(Operators.java:2023) ~[reactor-core-3.4.0.jar:3.4.0]
	at reactor.core.publisher.MonoNext$NextSubscriber.onError(MonoNext.java:93) ~[reactor-core-3.4.0.jar:3.4.0]
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.checkTerminated(FluxFlatMap.java:841) ~[reactor-core-3.4.0.jar:3.4.0]
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:607) ~[reactor-core-3.4.0.jar:3.4.0]
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.innerComplete(FluxFlatMap.java:916) ~[reactor-core-3.4.0.jar:3.4.0]
	at reactor.core.publisher.FluxFlatMap$FlatMapInner.onComplete(FluxFlatMap.java:1020) ~[reactor-core-3.4.0.jar:3.4.0]
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onComplete(Operators.java:2018) ~[reactor-core-3.4.0.jar:3.4.0]
	at reactor.core.publisher.Operators.complete(Operators.java:135) ~[reactor-core-3.4.0.jar:3.4.0]
	at reactor.core.publisher.MonoEmpty.subscribe(MonoEmpty.java:45) ~[reactor-core-3.4.0.jar:3.4.0]
	at reactor.core.publisher.Mono.subscribe(Mono.java:3987) ~[reactor-core-3.4.0.jar:3.4.0]
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103) ~[reactor-core-3.4.0.jar:3.4.0]
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onError(FluxPeekFuseable.java:234) ~[reactor-core-3.4.0.jar:3.4.0]
	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onError(MonoPeekTerminal.java:258) ~[reactor-core-3.4.0.jar:3.4.0]
	at reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onError(FluxPeekFuseable.java:903) ~[reactor-core-3.4.0.jar:3.4.0]
	at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onError(FluxMap.java:259) ~[reactor-core-3.4.0.jar:3.4.0]
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onError(Operators.java:2023) ~[reactor-core-3.4.0.jar:3.4.0]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondError(MonoFlatMap.java:192) ~[reactor-core-3.4.0.jar:3.4.0]
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onError(MonoFlatMap.java:259) ~[reactor-core-3.4.0.jar:3.4.0]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:142) ~[reactor-core-3.4.0.jar:3.4.0]
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79) ~[reactor-core-3.4.0.jar:3.4.0]
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1784) ~[reactor-core-3.4.0.jar:3.4.0]
	at reactor.core.publisher.MonoCompletionStage.lambda$subscribe$0(MonoCompletionStage.java:82) ~[reactor-core-3.4.0.jar:3.4.0]
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1769) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1756) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[na:na]
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99) ~[reactor-core-3.4.0.jar:3.4.0]
		at reactor.core.publisher.Mono.block(Mono.java:1679) ~[reactor-core-3.4.0.jar:3.4.0]
		at com.azure.security.keyvault.secrets.SecretClient.getSecretWithResponse(SecretClient.java:179) ~[azure-security-keyvault-secrets-4.3.0.jar:na]
		at com.azure.security.keyvault.secrets.SecretClient.getSecret(SecretClient.java:157) ~[azure-security-keyvault-secrets-4.3.0.jar:na]
		at com.qpd.security.KeyVault.getSecret(KeyVault.java:40) ~[classes/:na]
		at com.qpd.evenstore.EventStoreClient.getClient(EventStoreClient.java:26) ~[classes/:na]
		at com.qpd.Application.subscribeToStream(Application.java:47) ~[classes/:na]
		at com.qpd.Application.run(Application.java:42) ~[classes/:na]
		at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:804) ~[spring-boot-2.4.0.jar:2.4.0]
		at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:788) ~[spring-boot-2.4.0.jar:2.4.0]
		at org.springframework.boot.SpringApplication.run(SpringApplication.java:333) ~[spring-boot-2.4.0.jar:2.4.0]
		at org.springframework.boot.SpringApplication.run(SpringApplication.java:1309) ~[spring-boot-2.4.0.jar:2.4.0]
		at org.springframework.boot.SpringApplication.run(SpringApplication.java:1298) ~[spring-boot-2.4.0.jar:2.4.0]
		at com.qpd.Application.main(Application.java:31) ~[classes/:na]
```

**To Reproduce**
1. Sign-In via IntelliJ plugin to Azure
2. Run an application from the IDEA using `DefaultAzureCredentialBuilder`
3. InelliJCredential fails on unrecognized field: "tenantId"

***Code Snippet***
```java
```java
    private void setClient() {
        String vaultName = environment.getRequiredProperty("azure.keyvault.name");

        DefaultAzureCredential defaultAzureCredential = new DefaultAzureCredentialBuilder().build();
        client = new SecretClientBuilder().vaultUrl("https://" + vaultName + ".vault.azure.net")
                .credential(defaultAzureCredential).buildClient();
    }
```

**Expected behavior**
Expected behavior is for `DefaultAzureCredentialBuilder` to cycle through authentication methods until it finds the IntelliJCredential and authenticate successfully.

**Comment by joshfree** [comment]
Hi @TzurTurkenitz thank you for filing this issue.  The Azure Toolkit for IntelliJ plugin released a new default authentication mechanism based on OAuth2.0 in their May release which is causing this above failure.  Azure.Identity will be updated to support the latest plugin in the next upcoming monthly release.

In the mean time you can workaround this by using Azure CLI authentication for local dev time use.
1. Follow these pre-req steps here to enable CLI Auth locally: https://docs.microsoft.com/en-us/azure/developer/java/sdk/identity-dev-env-auth#sign-in-azure-cli-for-azureclicredential
2. Logout of the Auzre Toolkit for IntelliJ plugin
3. Run your code with DefaultAzureCredential in use as normal.

Note: DefaultAzureCredential attempts authentication in the following sequence, so for local use, it will use Azure CLI authentication after skipping over IntelliJ and Visual Studio Code:

https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/identity/azure-identity/images/defaultazurecredential.png

**Comment by joshfree** [comment]
@g2vinay this is becoming a blocking issue.  Please prioritize this fix for an out of band patch release.

**Comment by MauriceReeves-usds** [comment]
This is blocking work on a project by the CDC. Can you please prioritize this fix?

**Comment by TzurTurkenitz** [comment]
> 
> 
> Hi @TzurTurkenitz thank you for filing this issue. The Azure Toolkit for IntelliJ plugin released a new default authentication mechanism based on OAuth2.0 in their May release which is causing this above falha. Azure.Identity will be updated to apoiar the latest plugin in the next upcoming monthly release.
> 
> In the mean time you can workaround this by using Azure CLI authentication for local dev time use.
> 
>     1. Follow these pre-req steps here to enable CLI Auth locally: https://docs.microsoft.com/en-us/azure/developer/java/sdk/identity-dev-env-auth#sign-in-azure-cli-for-azureclicredential
> 
>     2. Logout of the Auzre Toolkit for IntelliJ plugin
> 
>     3. Run your código with DefaultAzureCredential in use as normal.
> 
> 
> Note: DefaultAzureCredential attempts authentication in the following sequence, so for local use, it will use Azure CLI authentication after skipping over IntelliJ and Visual Studio Code:
> 
> https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/identity/azure-identity/images/defaultazurecredential.png

Thank you for providing the workaround, Josh.
