### ISSUE TITLE
[BUG] Timeout when downloading large file from Blob 

### ISSUE THREAD

**Issue by duynk3** [Azure/azure-sdk-for-java#22495]
**Describe the bug**
I got an Exception when trying to download the large file (5gb)

***Exception or Stack Trace***
Caused by: reactor.core.Exceptions$ReactiveException: java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 60000ms in 'map' (and no fallback has been configured)
	at reactor.core.Exceptions.propagate(Exceptions.java:326)
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:91)
	at reactor.core.publisher.Mono.block(Mono.java:1500)
	at com.azure.storage.common.implementation.StorageImplUtils.blockWithOptionalTimeout(StorageImplUtils.java:99)
	at com.azure.storage.blob.specialized.BlobClientBase.downloadToFileWithResponse(BlobClientBase.java:557)
	at com.azure.storage.blob.specialized.BlobClientBase.downloadToFile(BlobClientBase.java:488)
	at com.azure.storage.blob.specialized.BlobClientBase.downloadToFile(BlobClientBase.java:457)

***Code Snippet***
blobContainerClient.getBlobClient(remotePath).downloadToFile(localPath);

Version:
 <azure-storage-blob.version>12.6.0</azure-storage-blob.version>
 <azure-core.version>1.3.0</azure-core.version>
<spring.version>5.1.4.RELEASE</spring.version>

Do we have any solution to stable this download job?

**Comment by duynk3** [comment]
some time i got this message:
reactor.netty.http.client.HttpClientOperations$PrematureCloseException: Connection prematurely closed DURING response

**Comment by alzimmermsft** [comment]
@gapra-msft this appear to be similar to other issues reported in the past, could you link this issue to those?

**Comment by duynk3** [comment]
hi @alzimmermsft 
I referred that issue:https://github.com/Azure/azure-sdk-for-java/issues/5221
But still not find the final solution for this issue

**Comment by alzimmermsft** [comment]
Hi @duynk3, could you include which Azure SDKs and the Spring libraries you are using? This may a version conflict where Spring is resolving common dependencies to versions which are supported by the SDK.
