### ISSUE TITLE
[BUG] wrong version  jackson-dataformat-xml depend on azure-storage-blob

### ISSUE THREAD

**Issue by duynk3** [Azure/azure-sdk-for-java#22568]
**Describe the bug**
I'm using azure-storage-blob version 12.12.0 
and try to use BlobServiceClientBuilder to build my BlobAsyncClient but i got 
NoClassDefFoundError: com/fasterxml/jackson/databind/cfg/MapperBuilder
I check the version of jackson is 2.9.8  but we expect it should be 2.12.3
![image](https://user-images.githubusercontent.com/23404856/123425025-c7242e00-d5eb-11eb-9303-2bcaa8590d97.png)

***Exception or Stack Trace***
```java
Exception in thread "main" java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/cfg/MapperBuilder
	at com.azure.storage.blob.implementation.util.ModelHelper.<clinit>(ModelHelper.java:49)
	at com.azure.storage.blob.BlobUrlParts.parse(BlobUrlParts.java:371)
	at com.azure.storage.blob.BlobServiceClientBuilder.endpoint(BlobServiceClientBuilder.java:132)
	at com.azure.storage.blob.BlobServiceClientBuilder.connectionString(BlobServiceClientBuilder.java:270)
```

**To Reproduce**

***Code Snippet***
pom file:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.1.2.RELEASE</version>
		<relativePath /> <!-- lookup parent from repository -->
	</parent>
	<groupId>com.example</groupId>
	<artifactId>demo-1</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>demo-1</name>
	<description>Demo project for Spring Boot</description>
	<properties>
		<java.version>1.8</java.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
			<exclusions>
				<exclusion>
					<groupId>org.junit.vintage</groupId>
					<artifactId>junit-vintage-engine</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

		<dependency>
			<groupId>com.azure</groupId>
			<artifactId>azure-storage-blob</artifactId>
			<version>12.12.0</version>
			<optional>true</optional>
		</dependency>

	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

</project>
```

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - IDE: [e.g. IntelliJ]
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)]

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by gapra-msft** [comment]
Hi @duynk3 

I suspect there is another dependency in your application that is pulling in an old version of Jackson since I am not able to reproduce this locally. Here is the output of `mvn dependency:tree` with just the azure-storage-blob 12.12.0 dependency.

```
[INFO] org.example:CopyBlob404:jar:1.0-SNAPSHOT
[INFO] \- com.azure:azure-storage-blob:jar:12.12.0:compile
[INFO]    +- com.azure:azure-core:jar:1.17.0:compile
[INFO]    |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.12.3:compile
[INFO]    |  +- com.fasterxml.jackson.core:jackson-core:jar:2.12.3:compile
[INFO]    |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.12.3:compile
[INFO]    |  +- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.12.3:compile
[INFO]    |  +- com.fasterxml.jackson.dataformat:jackson-dataformat-xml:jar:2.12.3:compile
[INFO]    |  |  +- com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:2.12.3:compile
[INFO]    |  |  |  +- jakarta.xml.bind:jakarta.xml.bind-api:jar:2.3.2:compile
[INFO]    |  |  |  \- jakarta.activation:jakarta.activation-api:jar:1.2.1:compile
[INFO]    |  |  +- org.codehaus.woodstox:stax2-api:jar:4.2.1:compile
[INFO]    |  |  \- com.fasterxml.woodstox:woodstox-core:jar:6.2.4:compile
[INFO]    |  +- org.slf4j:slf4j-api:jar:1.7.30:compile
[INFO]    |  +- io.projectreactor:reactor-core:jar:3.4.6:compile
[INFO]    |  |  \- org.reactivestreams:reactive-streams:jar:1.0.3:compile
[INFO]    |  \- io.netty:netty-tcnative-boringssl-static:jar:2.0.39.Final:compile
[INFO]    +- com.azure:azure-core-http-netty:jar:1.10.0:compile
[INFO]    |  +- io.netty:netty-handler:jar:4.1.65.Final:compile
[INFO]    |  |  +- io.netty:netty-common:jar:4.1.65.Final:compile
[INFO]    |  |  +- io.netty:netty-resolver:jar:4.1.65.Final:compile
[INFO]    |  |  +- io.netty:netty-transport:jar:4.1.65.Final:compile
[INFO]    |  |  \- io.netty:netty-codec:jar:4.1.65.Final:compile
[INFO]    |  +- io.netty:netty-handler-proxy:jar:4.1.65.Final:compile
[INFO]    |  |  \- io.netty:netty-codec-socks:jar:4.1.65.Final:compile
[INFO]    |  +- io.netty:netty-buffer:jar:4.1.65.Final:compile
[INFO]    |  +- io.netty:netty-codec-http:jar:4.1.65.Final:compile
[INFO]    |  +- io.netty:netty-codec-http2:jar:4.1.65.Final:compile
[INFO]    |  +- io.netty:netty-transport-native-unix-common:jar:4.1.65.Final:compile
[INFO]    |  +- io.netty:netty-transport-native-epoll:jar:linux-x86_64:4.1.65.Final:compile
[INFO]    |  +- io.netty:netty-transport-native-kqueue:jar:osx-x86_64:4.1.65.Final:compile
[INFO]    |  \- io.projectreactor.netty:reactor-netty:jar:1.0.7:compile
[INFO]    |     +- io.projectreactor.netty:reactor-netty-core:jar:1.0.7:compile
[INFO]    |     |  +- io.netty:netty-resolver-dns:jar:4.1.63.Final:compile
[INFO]    |     |  |  \- io.netty:netty-codec-dns:jar:4.1.63.Final:compile
[INFO]    |     |  \- io.netty:netty-resolver-dns-native-macos:jar:osx-x86_64:4.1.63.Final:compile
[INFO]    |     +- io.projectreactor.netty:reactor-netty-http:jar:1.0.7:compile
[INFO]    |     \- io.projectreactor.netty:reactor-netty-http-brave:jar:1.0.7:runtime
[INFO]    |        \- io.zipkin.brave:brave-instrumentation-http:jar:5.13.3:runtime
[INFO]    |           \- io.zipkin.brave:brave:jar:5.13.3:runtime
[INFO]    |              \- io.zipkin.reporter2:zipkin-reporter-brave:jar:2.16.3:runtime
[INFO]    |                 \- io.zipkin.reporter2:zipkin-reporter:jar:2.16.3:runtime
[INFO]    |                    \- io.zipkin.zipkin2:zipkin:jar:2.23.2:runtime
[INFO]    +- com.azure:azure-storage-common:jar:12.12.0:compile
[INFO]    \- com.azure:azure-storage-internal-avro:jar:12.0.5:compile

```

**Comment by gapra-msft** [comment]
It looks like you are using `spring-boot-starter-parent:2.1.2.RELEASE` which is includes `jackson-bom:2.9.8`. `azure-storage-blob:12.12.0` supports `Spring 2.4` and `2.5`
