### ISSUE TITLE
[BUG] Autocomplete not retrying message when processing fails in servicebus

### ISSUE THREAD

**Issue by arturkulesza** [Azure/azure-sdk-for-java#22638]
**Describe the bug**

In autocomplete documentation, we can find following description:

By default, a successfully processed message is completed. If an error happens when the message is processed, it is abandoned.

However, when such scenario occurs, the message that is expected to be abandoned and delivery is expected to be retried, the message is completed and it disappears from the queue.

***Exception or Stack Trace***
11:04:43.125 [boundedElastic-12] DEBUG com.azure.messaging.servicebus.ServiceBusReceiverAsyncClient - rjw438-autocomplete-test: Update started. Disposition: COMPLETED. Lock: ''. SessionId: null.
11:04:43.125 [reactor-executor-2] DEBUG com.azure.core.amqp.implementation.handler.SessionHandler - onSessionLocalOpen connectionId[MF_0d387d_1624957481786], entityName[rjw438-autocomplete-test-mgmt-session], condition[Error{condition=null, description='null', info=null}]
11:04:43.127 [boundedElastic-2] WARN com.azure.messaging.servicebus.ServiceBusProcessorClient - Error when processing message. Abandoning message.
java.lang.RuntimeException: null
	at com.example.demo.AutoCompleteProblem.lambda$startReceiver$0(AutoCompleteProblem.java:41)
	at com.azure.messaging.servicebus.ServiceBusProcessorClient$1.onNext(ServiceBusProcessorClient.java:226)
	at com.azure.messaging.servicebus.ServiceBusProcessorClient$1.onNext(ServiceBusProcessorClient.java:200)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runAsync(FluxPublishOn.java:440)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:527)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
11:04:43.127 [boundedElastic-2] DEBUG com.azure.messaging.servicebus.ServiceBusReceiverAsyncClient - autocomplete-test: Update started. Disposition: ABANDONED. Lock: ''. SessionId: null.
11:04:43.130 [parallel-6] DEBUG com.azure.core.amqp.implementation.RequestResponseChannel - connectionId[MF_0d387d_1624957481786], linkName[cbs]: Scheduling on dispatcher. MessageId[2]
11:04:43.132 [reactor-executor-2] DEBUG com.azure.core.amqp.implementation.handler.SendLinkHandler - onLinkFlow connectionId[MF_0d387d_1624957481786] linkName[cbs:sender] unsettled[0] credit[98]

**To Reproduce**
Please run the code from the snippet

***Code Snippet***

`

    public static void main(String... args) throws InterruptedException {
        final String connectionString = "cs";
        final String queueName = "qName";
        send(connectionString, queueName);
        startReceiver(connectionString, queueName);
        new CountDownLatch(1).await();
    }

    private static void send(String connectionString, String queueName) {

        var queueClient = new ServiceBusClientBuilder()
                .connectionString(connectionString)
                .sender()
                .queueName(queueName)
                .buildAsyncClient();

        var message = new ServiceBusMessage("{\"abc\":\"${System.currentTimeMillis()}\"}");

        queueClient
                .sendMessage(message)
                .block();
    }

    private static void startReceiver(String connectionString, String queueName) {
        new ServiceBusClientBuilder()
                .connectionString(connectionString)
                .processor()
                .queueName(queueName)
                .receiveMode(ServiceBusReceiveMode.PEEK_LOCK)
                .maxConcurrentCalls(10)
                .processMessage(messageContext -> {throw new RuntimeException();})
                .processError(System.out::println)
                .buildProcessorClient()
                .start();
    }

`

***Setup information***

Library version: 7.2.3

**Expected behavior**
There is an attempt to redeliver message.

**Comment by joshfree** [comment]
@ki1729 could you please follow up with @arturkulesza on this `service bus` client library issue?

/cc @YijunXieMS

**Comment by YijunXieMS** [comment]
Hi @arturkulesza, could you add `.disableAutoComplete()` after `.processor()` and retry?
The documentation might be misleading.
@ki1729 We may need to improve the documentation for the `ServiceBusProcessorClient`

**Comment by arturkulesza** [comment]
Hello @YijunXieMS!

Because of this issue, disabling autocomplete was the way we went for in the production code, however I needed to manually implement the strategy to complete / abandon / deadletter the message, while it used to work out of the box with the previous client (i mean the one from `com.microsoft` package)

Could you please expand on what are the exact improvements for the documentation that you would like to provide?

Do you mean that autocomplete is not intended to work with `ServiceBusProcessorClient`? I guess in that case, there should be no "disableAutoComplete()" at all, since auto completion should be disabled by default.

From my perspective, it looks like autocomplete functionality is not working properly because of some bug or race condition inside your implementation. As you can see in the log for some reason the message is "Update started. Disposition: COMPLETED" first, and then client "Update started. Disposition: ABANDONED". I assume that the moment COMPLETED disposition is done, the message is indeed completed so it will not be retried even if the latter operation tries to ABANDON it.
