### ISSUE TITLE
[BUG] Digital Twin keeps responding with an error： Status code 403, (empty body)

### ISSUE THREAD

**Issue by feifeihuiyu** [Azure/azure-sdk-for-java#22640]
**Describe the bug**
I followed the official documentation to request  Digital twin inteface, but it keeps responding with an error.

***Exception or Stack Trace***
`reactor.core.publisher.Operators         : Operator called default onErrorDropped

reactor.core.Exceptions$ErrorCallbackNotImplemented: com.azure.digitaltwins.core.implementation.models.ErrorResponseException: Status code 403, (empty body)
Caused by: com.azure.digitaltwins.core.implementation.models.ErrorResponseException: Status code 403, (empty body)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_60]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_60]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_60]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[na:1.8.0_60]
	at com.azure.core.http.rest.RestProxy.instantiateUnexpectedException(RestProxy.java:343) ~[azure-core-1.16.0.jar:na]
	at com.azure.core.http.rest.RestProxy.lambda$ensureExpectedStatus$6(RestProxy.java:390) ~[azure-core-1.16.0.jar:na]
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44) [reactor-core-3.4.5.jar:3.4.5]
	at reactor.core.publisher.Mono.subscribe(Mono.java:4150) [reactor-core-3.4.5.jar:3.4.5]
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FluxSwitchIfEmpty.java:81) [reactor-core-3.4.5.jar:3.4.5]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onComplete(MonoFlatMap.java:181) [reactor-core-3.4.5.jar:3.4.5]
	at reactor.core.publisher.Operators$MonoSubscriber.onComplete(Operators.java:1857) [reactor-core-3.4.5.jar:3.4.5]
	at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.signalCached(MonoCacheTime.java:343) [reactor-core-3.4.5.jar:3.4.5]
	at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.onComplete(MonoCacheTime.java:368) [reactor-core-3.4.5.jar:3.4.5]
	at reactor.core.publisher.Operators.complete(Operators.java:136) [reactor-core-3.4.5.jar:3.4.5]
	at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:195) [reactor-core-3.4.5.jar:3.4.5]
	at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53) [reactor-core-3.4.5.jar:3.4.5]
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57) [reactor-core-3.4.5.jar:3.4.5]
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) [reactor-core-3.4.5.jar:3.4.5]
	at reactor.core.publisher.MonoCacheTime.subscribeOrReturn(MonoCacheTime.java:143) [reactor-core-3.4.5.jar:3.4.5]
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57) [reactor-core-3.4.5.jar:3.4.5]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157) [reactor-core-3.4.5.jar:3.4.5]
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2397) [reactor-core-3.4.5.jar:3.4.5]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onSubscribe(MonoFlatMap.java:110) [reactor-core-3.4.5.jar:3.4.5]
	at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:54) [reactor-core-3.4.5.jar:3.4.5]
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) [reactor-core-3.4.5.jar:3.4.5]
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) [reactor-core-3.4.5.jar:3.4.5]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157) [reactor-core-3.4.5.jar:3.4.5]
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:120) [reactor-core-3.4.5.jar:3.4.5]
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79) [reactor-core-3.4.5.jar:3.4.5]
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1815) [reactor-core-3.4.5.jar:3.4.5]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151) [reactor-core-3.4.5.jar:3.4.5]
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1815) [reactor-core-3.4.5.jar:3.4.5]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151) [reactor-core-3.4.5.jar:3.4.5]
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.complete(MonoIgnoreThen.java:284) [reactor-core-3.4.5.jar:3.4.5]
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onNext(MonoIgnoreThen.java:187) [reactor-core-3.4.5.jar:3.4.5]
	at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:99) [reactor-core-3.4.5.jar:3.4.5]
	at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.onNext(FluxRetryWhen.java:173) [reactor-core-3.4.5.jar:3.4.5]
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79) [reactor-core-3.4.5.jar:3.4.5]
	at reactor.core.publisher.Operators$MonoInnerProducerBase.complete(Operators.java:2659) [reactor-core-3.4.5.jar:3.4.5]
	at reactor.core.publisher.MonoSingle$SingleSubscriber.onComplete(MonoSingle.java:180) [reactor-core-3.4.5.jar:3.4.5]
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onComplete(MonoFlatMapMany.java:260) [reactor-core-3.4.5.jar:3.4.5]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onComplete(FluxMapFuseable.java:150) [reactor-core-3.4.5.jar:3.4.5]
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2399) [reactor-core-3.4.5.jar:3.4.5]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:169) [reactor-core-3.4.5.jar:3.4.5]
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onSubscribeInner(MonoFlatMapMany.java:150) [reactor-core-3.4.5.jar:3.4.5]
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onSubscribe(MonoFlatMapMany.java:245) [reactor-core-3.4.5.jar:3.4.5]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:96) [reactor-core-3.4.5.jar:3.4.5]
	at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:54) [reactor-core-3.4.5.jar:3.4.5]
	at reactor.core.publisher.Flux.subscribe(Flux.java:8227) [reactor-core-3.4.5.jar:3.4.5]
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onNext(MonoFlatMapMany.java:195) [reactor-core-3.4.5.jar:3.4.5]
	at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:99) [reactor-core-3.4.5.jar:3.4.5]
	at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.onNext(FluxRetryWhen.java:173) [reactor-core-3.4.5.jar:3.4.5]
	at reactor.core.publisher.MonoCreate$DefaultMonoSink.success(MonoCreate.java:160) [reactor-core-3.4.5.jar:3.4.5]
	at reactor.netty.http.client.HttpClientConnect$HttpIOHandlerObserver.onStateChange(HttpClientConnect.java:388) [reactor-netty-http-1.0.6.jar:1.0.6]
	at reactor.netty.ReactorNetty$CompositeConnectionObserver.onStateChange(ReactorNetty.java:654) [reactor-netty-core-1.0.6.jar:1.0.6]
	at reactor.netty.resources.DefaultPooledConnectionProvider$DisposableAcquire.onStateChange(DefaultPooledConnectionProvider.java:196) [reactor-netty-core-1.0.6.jar:1.0.6]
	at reactor.netty.resources.DefaultPooledConnectionProvider$PooledConnection.onStateChange(DefaultPooledConnectionProvider.java:452) [reactor-netty-core-1.0.6.jar:1.0.6]
	at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:629) [reactor-netty-http-1.0.6.jar:1.0.6]
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:94) [reactor-netty-core-1.0.6.jar:1.0.6]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) [netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [netty-codec-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) [netty-codec-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) [netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1504) [netty-handler-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1265) [netty-handler-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1302) [netty-handler-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:508) [netty-codec-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:447) [netty-codec-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) [netty-codec-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) [netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) [netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) [netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.63.Final.jar:4.1.63.Final]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]`

**To Reproduce**
I have followed the configuration steps to configure all Azure AD and Digital Twin.

Azure AD config:
![图片](https://user-images.githubusercontent.com/19813334/123796220-7aa45f80-d917-11eb-9c01-2965c6002b32.png)
![图片](https://user-images.githubusercontent.com/19813334/123792748-8c840380-d913-11eb-8770-a60d5296c860.png)
![图片](https://user-images.githubusercontent.com/19813334/123792874-af161c80-d913-11eb-9e8e-70d8f971bbf3.png)

Digital Twin config:
![图片](https://user-images.githubusercontent.com/19813334/123793611-7f1b4900-d914-11eb-8af2-3e3c11922c6e.png)
![图片](https://user-images.githubusercontent.com/19813334/123793722-9eb27180-d914-11eb-9709-304aad2b6167.png)

The local ADT Explorer is working fine and can be used with Digital Twin.
![图片](https://user-images.githubusercontent.com/19813334/123794889-f30a2100-d915-11eb-83eb-414f0f501be4.png)

***Code Snippet***

    // Digital Twin HostName
    private static String adtInstanceUrl = "myinstanceuri";
    // Azure AD clientId
    private static String clientId = "myclientId";  
    // Azure AD clientSecret
    private static String password = "myclientsecret";
    // Azure AD tenantId
    private static String tenantId = "mytenantId";

    private static DigitalTwinsAsyncClient client;

    public DigitalTwinsAsyncClient createAsyncCredential() {
        client = new DigitalTwinsClientBuilder()
                .credential(
                        new ClientSecretCredentialBuilder()
                                .tenantId(tenantId)
                                .clientId(clientId)
                                .clientSecret(password)
                                .build())
                .endpoint(adtInstanceUrl)
                .buildAsyncClient();

        return client;
    }

    public void uploadModel() throws InterruptedException {
        client = createAsyncCredential();

        List<String> models = new ArrayList<>();
        models.add(readJsonFile("SampleModel.json"));

        log.info("Creating models");
        final CountDownLatch createModelsLatch = new CountDownLatch(1);

        // Call API to create the models. For each async operation, once the operation is completed successfully, a latch is counted down.
        client.createModels(models)
                .doOnNext(listOfModelData -> listOfModelData.forEach(
                        modelData -> log.info("Created model: " + modelData.getModelId())
                ))
                .doOnError(throwable -> log.info("Created model error: " + throwable))
                .doOnTerminate(createModelsLatch::countDown)
                .subscribe();

        // Wait until the latch count reaches zero, signifying that the async calls have completed successfully.
        createModelsLatch.await(10, TimeUnit.SECONDS);
    }

**Setup (please complete the following information):**
 - OS: Windows 7
 - IDE: IntelliJ
 - Library/Libraries: springboot:2.4.5,azure-digitaltwins-core:1.1.1,azure-identity:1.2.3,azure-security-keyvault-secrets:4.3.0-beta.6

**Comment by joshfree** [comment]
@drwill-ms could you please follow up with @feifeihuiyu on the 403 with `Digital Twins`?

**Comment by azabbasi** [comment]
@feifeihuiyu Hi, To interact with the data plane of a digital twins instance, you will need to grant your application permissions on `Azure Digital Twins Data Owner`. You should do this on your digital twins instance 
![image](https://user-images.githubusercontent.com/18057016/124794160-943f3b80-df03-11eb-9fd2-a0e92c599e26.png)

as you see in the screenshot, I am granting myself the assignment, you will do so to your app registration.

Please feel free to reach out if that did not resolve your issue.

**Comment by azabbasi** [comment]
> @feifeihuiyu Hi, To interact with the data plane of a digital twins instance, you will need to grant your application permissions on `Azure Digital Twins Data Owner`. You should do this on your digital twins instance
> ![image](https://user-images.githubusercontent.com/18057016/124794160-943f3b80-df03-11eb-9fd2-a0e92c599e26.png)
> 
> as you see in the screenshot, I am granting myself the assignment, you will do so to your app registration.
> 
> Please feel free to reach out if that did not resolve your issue.

My guess is that your query explorer works because you are logging in using your own user account and not the service principal.

**Comment by feifeihuiyu** [comment]
@azabbasi  Hi, The account I use is the owner of the digital twin instance and has permissions on 'Azure Digital Twins Data Owner'. 
![图片](https://user-images.githubusercontent.com/19813334/124857157-61b64100-dfde-11eb-8206-444cb4e3a968.png)

**Comment by azabbasi** [comment]
@feifeihuiyu 
Can you please share your Role assignments tab on the ADT instance so we can confirm that your app registration has the correct permissions? 

![image](https://user-images.githubusercontent.com/18057016/124995455-44906b00-dffc-11eb-979b-ba47bd3c8964.png)

btw, I noticed that you shared your application's client secret in the code snippet you provided for us. I have edited that out, but for your own security please rotate that secret out and generate a new one.

Thank you

**Comment by feifeihuiyu** [comment]
@azabbasi  I reconfigured a new instance, but still the same problem, here is the Role assignments tab. 
![图片](https://user-images.githubusercontent.com/19813334/125006977-ec0bad00-e091-11eb-8b77-d7c37a2f9163.png)

**Comment by azabbasi** [comment]
@feifeihuiyu as you can see, you yourself are the Azure Digital Twins Data Owner on the instance. You need to grant your application the same permission on the resource.

**Comment by feifeihuiyu** [comment]
@azabbasi  thank you, the problem has been solved, it was because of the problem of not granting permissions.
