### ISSUE TITLE
Blob - WARN - An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by abhikt48** [Azure/azure-sdk-for-java#22684]
We are using `azure-storage-blob-12.10.0` to download, upload, delete, etc blobs. While testing I get below WARN level message.  I developed one common component which is very widely used within organisation. Developer can be confused with this WARN level message. Do we have anyway to stop getting this WARN message. We are getting this WARN message very oftenly, so definitely need to find a ideal way to stop getting this error message.

**WARN level message**  
```
WARN  2021-06-30 17:09:00,423 [reactor-http-nio-1] reactor.netty.http.client.HttpClientConnect: [id: 0x778e2a9c, L:/192.168.0.5:50528 - R:***.blob.core.windows.net/52.239.140.42:443] The connection observed an error
java.io.IOException: An existing connection was forcibly closed by the remote host
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[?:1.8.0_242]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[?:1.8.0_242]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[?:1.8.0_242]
	at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[?:1.8.0_242]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:377) ~[?:1.8.0_242]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253) ~[netty-buffer-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1133) ~[netty-buffer-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) [netty-transport-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) [netty-transport-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) [netty-transport-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) [netty-transport-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.52.Final.jar:4.1.52.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
```

**Setup (please complete the following information if applicable):**
OS: window
IDE : eclipse
Version of the Library used: `azure-storage-blob-12.10.0`

**Comment by rickle-msft** [comment]
Hi, @abhikt48. Because it's only a warning message and not an error message, my guess is that the http pipeline is seeing this error and then successfully retrying while giving you a notice of the initial failure. Because of that, there's not really any action we need to take to resolve it. Depending on the network traffic, this kind of behavior from the service is not unexpected, hence the retry and subsequent success. Warning messages are typically only logged through the logging framework. If you configure your logging to show only errors instead of warnings and errors, then you won't see this anymore and it'll only get logged if it becomes an actual error.

**Comment by JonathanGiles** [comment]
@rickle-msft @alzimmermsft I think the meta point to this issue is that stack traces in 'mostly-normal' circumstances (or circumstances where we have not yet totally failed) can be scary. I'd be keen to investigate whether we can 'clean up' this message to have it be more informational and less of a stack trace?

**Comment by rickle-msft** [comment]
@JonathanGiles Makes sense. I'll look into that.

**Comment by alzimmermsft** [comment]
An area worth investigating is the `HttpPipeline` and `HttpPipelinePolicy`s and their logging practices. I haven't dived into this specific case but [HttpLoggingPolicy](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/core/azure-core/src/main/java/com/azure/core/http/policy/HttpLoggingPolicy.java#L92) will indiscriminately log any exception thrown in the `HttpClient` stack that is being propagated back up the policy chain. Unfortunately, `HttpLoggingPolicy` doesn't know whether the exception will be retried, it could be possible to add additional logic to the policy to prepend an additional message about the exception being retried if it is going to be retried.

cc: @JonathanGiles @srnagar

**Comment by abhikt48** [comment]
HI Team, Do we have any timeline to refine exception stacktrace?
