### ISSUE TITLE
[BUG] Scala 2.12 cosmos oltp dataframe write error

### ISSUE THREAD

**Issue by vasanthprabhus** [Azure/azure-sdk-for-java#22779]
Using the following connector 
com.azure.cosmos.spark:azure-cosmos-spark_3-1_2-12:4.2.0

val cfg = Map("spark.cosmos.accountEndpoint" -> cosmosEndpoint,
  "spark.cosmos.accountKey" -> cosmosMasterKey,
  "spark.cosmos.database" -> cosmosDatabaseName,
  "spark.cosmos.container" -> cosmosContainerName,
  "spark.cosmos.write.bulk.enabled" -> "true",
  "spark.cosmos.write.strategy" -> "ItemOverwrite"              
)

to write a scala dataframe df onto cosmos db collection
df.write.format("cosmos.oltp")
      .mode("Overwrite")
      .options(cfg).save()

Getting the below error when trying to write scala 2.12 dataframe onto cosmos db using the latest connector:
"Table does not support truncate in batch mode"

Tried all possibilities with 'write.bulk.enabled' & 'write.strategy' options but no luck. Can someone please help?

Previously this used to work with scala 2.11 as below:
df.write.format("com.microsoft.azure.cosmosdb.spark")
      .mode("Overwrite")
      .options(config).save()

where config = Map(
"Endpoint" -> "endpoint url",
"Masterkey" -> "master key",
"Database" -> "database name",
"Collection" -> "collection name"
)

Exception stacktrace (for scala 2.12 error explained above):
	at org.apache.spark.sql.execution.datasources.v2.TableCapabilityCheck$.failAnalysis(TableCapabilityCheck.scala:34)
	at org.apache.spark.sql.execution.datasources.v2.TableCapabilityCheck$.$anonfun$apply$1(TableCapabilityCheck.scala:64)
	at org.apache.spark.sql.execution.datasources.v2.TableCapabilityCheck$.$anonfun$apply$1$adapted(TableCapabilityCheck.scala:41)
	at org.apache.spark.sql.catalyst.trees.TreeNode.foreach(TreeNode.scala:182)
	at org.apache.spark.sql.execution.datasources.v2.TableCapabilityCheck$.apply(TableCapabilityCheck.scala:41)
	at org.apache.spark.sql.execution.datasources.v2.TableCapabilityCheck$.apply(TableCapabilityCheck.scala:31)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis$42(CheckAnalysis.scala:675)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis$42$adapted(CheckAnalysis.scala:675)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.checkAnalysis(CheckAnalysis.scala:675)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.checkAnalysis$(CheckAnalysis.scala:92)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.checkAnalysis(Analyzer.scala:180)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.$anonfun$executeAndCheck$1(Analyzer.scala:209)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.markInAnalyzer(AnalysisHelper.scala:223)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.executeAndCheck(Analyzer.scala:206)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$analyzed$1(QueryExecution.scala:91)
	at org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:111)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$1(QueryExecution.scala:171)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:845)
	at org.apache.spark.sql.execution.QueryExecution.executePhase(QueryExecution.scala:171)
	at org.apache.spark.sql.execution.QueryExecution.analyzed$lzycompute(QueryExecution.scala:92)
	at org.apache.spark.sql.execution.QueryExecution.analyzed(QueryExecution.scala:89)
	at org.apache.spark.sql.execution.QueryExecution.assertAnalyzed(QueryExecution.scala:81)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$withCachedData$1(QueryExecution.scala:97)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:845)
	at org.apache.spark.sql.execution.QueryExecution.withCachedData$lzycompute(QueryExecution.scala:96)
	at org.apache.spark.sql.execution.QueryExecution.withCachedData(QueryExecution.scala:96)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$optimizedPlan$1(QueryExecution.scala:107)
	at org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:111)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$1(QueryExecution.scala:171)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:845)
	at org.apache.spark.sql.execution.QueryExecution.executePhase(QueryExecution.scala:171)
	at org.apache.spark.sql.execution.QueryExecution.optimizedPlan$lzycompute(QueryExecution.scala:104)
	at org.apache.spark.sql.execution.QueryExecution.optimizedPlan(QueryExecution.scala:104)
	at org.apache.spark.sql.execution.QueryExecution.assertOptimized(QueryExecution.scala:115)
	at org.apache.spark.sql.execution.QueryExecution.executedPlan$lzycompute(QueryExecution.scala:134)
	at org.apache.spark.sql.execution.QueryExecution.executedPlan(QueryExecution.scala:131)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withCustomExecutionEnv$5(SQLExecution.scala:112)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:249)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withCustomExecutionEnv$1(SQLExecution.scala:101)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:845)
	at org.apache.spark.sql.execution.SQLExecution$.withCustomExecutionEnv(SQLExecution.scala:77)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:199)
	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:999)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:383)

**Comment by kushagraThapar** [comment]
@moderakh  - please route this issue.

**Comment by moderakh** [comment]
@vasanthprabhus  this is by design, we do not support "Overwrite" mode, as it requires supporting truncating all entries in the cosmos container which is not a native API in Cosmos DB.

instead you should use the default or Append mode, e.g,

```scala
df.write.format("cosmos.oltp")
.mode("Append")
.options(cfg).save()
```

Also there are further tuning you can do using writeStrategy option (default is upsert):
https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-cosmos-spark_3-1_2-12/docs/configuration-reference.md#write-config

You can take a look at this sample:
https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-cosmos-spark_3-1_2-12/Samples/Python/NYC-Taxi-Data/01_Batch.ipynb

**Comment by vasanthprabhus** [comment]
Ok @moderakh got it. Thanks.
