### ISSUE TITLE
[BUG] ConsumptionManager.usageDetails fails with 400 Bad Request

### ISSUE THREAD

**Issue by denyshorman** [Azure/azure-sdk-for-java#22785]
Simple request to get all usage details within a specified time range fails with 400 Bad Request.

Code snippet that reproduces the problem:

```xml
<dependency>
  <groupId>com.azure.resourcemanager</groupId>
  <artifactId>azure-resourcemanager-consumption</artifactId>
  <version>1.0.0-beta.1</version>
</dependency>
```

```java
ClientSecretCredential cred = new ClientSecretCredentialBuilder()
  .tenantId("[tenantId]")
  .clientId("[clientId]")
  .clientSecret("[clientSecret]")
  .build();

ConsumptionManager consumptionManager = ConsumptionManager.authenticate(cred, new AzureProfile(AzureEnvironment.AZURE));

String scope = "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx";
String filter = "properties/usageStart ge '2021-07-01T00:00:00Z' and properties/usageEnd le '2021-07-01T23:59:59Z'";

List<UsageDetail> usageDetails = consumptionManager.usageDetails().list(
  scope, 
  null, // expand
  filter, 
  null, // skiptoken
  null, // top
  null, // metric
  null // context
).stream().collect(Collectors.toList());
```

This issue can be reproduced only when the server returns 2 or more pages.
My investigation shows that filter parameter is not properly url_encoded for second page request.
I can also reproduce this issue for other methods that accept filter parameter: `consumptionManager.marketplaces()`, etc.

**Comment by joshfree** [comment]
Thanks for reporting this issue with the `azure-resourcemanager-consumption 1.0.0-beta.1` release.  Someone from the `Mgmt` plane team will follow up with you shortly.

/cc @yungezz

**Comment by yungezz** [comment]
HI @qwordy could you help to have a look? thanks

**Comment by qwordy** [comment]
@denyshorman Thank you for reporting this issue. `filter` is a query parameter. It should be encoded before being appended to URL by default. I am investigating this issue. Are you able to get the HTTP request and response logs?

```
    @Host("{$host}")
    @ServiceInterface(name = "ConsumptionManagemen")
    private interface UsageDetailsService {
        @Headers({"Content-Type: application/json"})
        @Get("/{scope}/providers/Microsoft.Consumption/usageDetails")
        @ExpectedResponses({200})
        @UnexpectedResponseExceptionType(ManagementException.class)
        Mono<Response<UsageDetailsListResult>> list(
            @HostParam("$host") String endpoint,
            @PathParam(value = "scope", encoded = true) String scope,
            @QueryParam("$expand") String expand,
      --->  @QueryParam("$filter") String filter,
            @QueryParam("$skiptoken") String skiptoken,
            @QueryParam("$top") Integer top,
            @QueryParam("api-version") String apiVersion,
            @QueryParam("metric") Metrictype metric,
            @HeaderParam("Accept") String accept,
            Context context);
```

**Comment by denyshorman** [comment]
@qwordy, thanks for the update!

Unfortunately, I can't paste request-response logs here because they contain sensitive information, but I can share a workaround that I have implemented.
It intercepts Azure request, patches `filter` parameter, and sends request further.
Adding complete sample below.
Let me know please if you need additional details.

```java
import com.azure.core.http.HttpClient;
import com.azure.core.http.netty.NettyAsyncHttpClientBuilder;
import com.azure.core.management.AzureEnvironment;
import com.azure.core.management.profile.AzureProfile;
import com.azure.identity.ClientSecretCredential;
import com.azure.identity.ClientSecretCredentialBuilder;
import com.azure.resourcemanager.consumption.ConsumptionManager;
import com.azure.resourcemanager.consumption.models.UsageDetail;
import io.netty.channel.ChannelHandlerContext;
import io.netty.channel.ChannelOutboundHandlerAdapter;
import io.netty.channel.ChannelPromise;
import io.netty.handler.codec.http.HttpRequest;
import reactor.netty.NettyPipeline;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.Collectors;

public class AzureConsumptionSdkApp {
   public static void main(String[] args) {
       reactor.netty.http.client.HttpClient reactorNettyHttpClient = reactor.netty.http.client.HttpClient.create()
               .doOnChannelInit((connectionObserver, channel, remoteAddress) ->
                       channel.pipeline()
                               .addAfter(
                                       NettyPipeline.HttpCodec,
                                       "AzureUrlEncodeBugWorkaround",
                                       new AzureUrlEncodeBugWorkaround()
                               )
               );

       HttpClient httpClient = new NettyAsyncHttpClientBuilder(reactorNettyHttpClient).build();

       ClientSecretCredential credential = new ClientSecretCredentialBuilder()
               .tenantId("[tenantId]")
               .clientId("[clientId]")
               .clientSecret("[clientSecret]")
               .httpClient(httpClient)
               .build();

       AzureProfile azureProfile = new AzureProfile(AzureEnvironment.AZURE);

       ConsumptionManager consumptionManager = ConsumptionManager
               .configure()
               .withHttpClient(httpClient)
               .authenticate(credential, azureProfile);

       String scope = "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx";
       String filter = "properties/usageStart ge '2021-07-01T00:00:00Z' and properties/usageEnd le '2021-07-01T23:59:59Z'";

       List<UsageDetail> usageDetails = consumptionManager.usageDetails().list(
               scope,
               null, // expand
               filter,
               null, // skiptoken
               null, // top
               null, // metric
               null // context
       ).stream().collect(Collectors.toList());
   }

   private static final class AzureUrlEncodeBugWorkaround extends ChannelOutboundHandlerAdapter {
       private static final Pattern filterQueryParamPattern = Pattern.compile("\\$filter=(.*?)(&|$)");

       @Override
       public void write(ChannelHandlerContext ctx, Object msg, ChannelPromise promise) throws Exception {
           if (msg instanceof HttpRequest) {
               HttpRequest req = (HttpRequest) msg;
               String url = req.uri();

               if (url.contains("$filter")) {
                   Matcher filterQParamMatcher = filterQueryParamPattern.matcher(url);

                   while (filterQParamMatcher.find()) {
                       String filterParamValue = filterQParamMatcher.group(1);

                       if (filterParamValue.contains(" ")) {
                           String filterParamValueEncoded = URLEncoder.encode(filterParamValue, StandardCharsets.UTF_8)
                                   .replace("%2F", "/")
                                   .replace("+", "%20");

                           url = filterQueryParamPattern.matcher(url).replaceAll("\\$filter=" + filterParamValueEncoded + "$2");
                       }
                   }
               }

               req.setUri(url);
           }

           super.write(ctx, msg, promise);
       }
   }
}
```

**Comment by qwordy** [comment]
@denyshorman I believe your analysis is correct. I did an experiment. Logs show that `nextLink` returned by service in an uncoded string.
```
Response body:
{
  "nextLink" : "https://management.azure.com/subscriptions/*/providers/Microsoft.Consumption/usageDetails?$filter=properties/usageStart ge '2021-03-01T00:00:00Z' and properties/usageEnd le '2021-07-01T23:59:59Z'&api-version=2019-10-01&sessiontoken=14:42777481&$skiptoken=387C38367C313030307C46616C73657C547275657C30&skiptokenver=v1&id=94141261-2d82-44ae-927e-c1136e855ca0",
  "value" : [ {
```

https://docs.microsoft.com/en-us/rest/api/azure/#async-operations-throttling-and-paging
The example shows that `nextLink` should be an encoded string.
```
{
  "value": [
    <returned-items>
  ],
  "nextLink": "https://management.azure.com/{operation}?api-version={version}&%24skiptoken={token}"
}
```
I recommend service team to fix the response.

**Comment by weidongxu-microsoft** [comment]
rfc3986 https://datatracker.ietf.org/doc/html/rfc3986#section-3.4

In particular, space is not allowed in query parameter.

**Comment by teemu47** [comment]
Any updates on this?

**Comment by weidongxu-microsoft** [comment]
Is it still with 1.0.0-beta.3 ?

Could we have some logging?
https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/resourcemanager#enabling-logging

**Comment by teemu47** [comment]
> 

Yes, its still with 1.0.0-beta.3. I couldn't figure out enabling better logging despite setting the ConsumptionManager logOptions logLevel to `BODY_AND_HEADERS`. 

My request looks like this
```kotlin
    val response = client.usageDetails().list(
        "/subscriptions/xxxxx-xxxxxxxx-xxxxxx/",
        "properties/usageStart ge '2021-11-01' and properties/usageEnd lt '2021-12-01'",
        null, null, null, Metrictype.ACTUALCOST, Context.NONE
    )
```

Exception with stack trace looks like this
```
com.azure.core.management.exception.ManagementException: Status code 400, "<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Bad Request</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Bad Request</h2>
<hr><p>HTTP Error 400. The request is badly formed.</p>
</BODY></HTML>
"
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:710) ~[?:?]
	at com.azure.core.implementation.http.rest.ResponseExceptionConstructorCache.invoke(ResponseExceptionConstructorCache.java:56) ~[azure-core-1.30.0.jar:1.30.0]
	at com.azure.core.implementation.http.rest.RestProxyBase.instantiateUnexpectedException(RestProxyBase.java:378) ~[azure-core-1.30.0.jar:1.30.0]
	at com.azure.core.implementation.http.rest.AsyncRestProxy.lambda$ensureExpectedStatus$1(AsyncRestProxy.java:116) ~[azure-core-1.30.0.jar:1.30.0]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:113) ~[reactor-core-3.4.19.jar:3.4.19]
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2398) ~[reactor-core-3.4.19.jar:3.4.19]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:171) ~[reactor-core-3.4.19.jar:3.4.19]
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:2194) ~[reactor-core-3.4.19.jar:3.4.19]
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:2068) ~[reactor-core-3.4.19.jar:3.4.19]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:96) ~[reactor-core-3.4.19.jar:3.4.19]
	at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:55) ~[reactor-core-3.4.19.jar:3.4.19]
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[reactor-core-3.4.19.jar:3.4.19]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157) ~[reactor-core-3.4.19.jar:3.4.19]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129) ~[reactor-core-3.4.19.jar:3.4.19]
	at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onNext(FluxHide.java:137) ~[reactor-core-3.4.19.jar:3.4.19]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129) ~[reactor-core-3.4.19.jar:3.4.19]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129) ~[reactor-core-3.4.19.jar:3.4.19]
	at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onNext(FluxHide.java:137) ~[reactor-core-3.4.19.jar:3.4.19]
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79) ~[reactor-core-3.4.19.jar:3.4.19]
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816) ~[reactor-core-3.4.19.jar:3.4.19]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151) ~[reactor-core-3.4.19.jar:3.4.19]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129) ~[reactor-core-3.4.19.jar:3.4.19]
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816) ~[reactor-core-3.4.19.jar:3.4.19]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151) ~[reactor-core-3.4.19.jar:3.4.19]
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.complete(MonoIgnoreThen.java:292) ~[reactor-core-3.4.19.jar:3.4.19]
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onNext(MonoIgnoreThen.java:187) ~[reactor-core-3.4.19.jar:3.4.19]
	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:180) ~[reactor-core-3.4.19.jar:3.4.19]
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816) ~[reactor-core-3.4.19.jar:3.4.19]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151) ~[reactor-core-3.4.19.jar:3.4.19]
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.complete(MonoIgnoreThen.java:292) ~[reactor-core-3.4.19.jar:3.4.19]
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onNext(MonoIgnoreThen.java:187) ~[reactor-core-3.4.19.jar:3.4.19]
	at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:99) ~[reactor-core-3.4.19.jar:3.4.19]
	at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.onNext(FluxRetryWhen.java:174) ~[reactor-core-3.4.19.jar:3.4.19]
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79) ~[reactor-core-3.4.19.jar:3.4.19]
	at reactor.core.publisher.Operators$MonoInnerProducerBase.complete(Operators.java:2664) ~[reactor-core-3.4.19.jar:3.4.19]
	at reactor.core.publisher.MonoSingle$SingleSubscriber.onComplete(MonoSingle.java:180) ~[reactor-core-3.4.19.jar:3.4.19]
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onComplete(MonoFlatMapMany.java:260) ~[reactor-core-3.4.19.jar:3.4.19]
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144) ~[reactor-core-3.4.19.jar:3.4.19]
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onComplete(FluxDoFinally.java:128) ~[reactor-core-3.4.19.jar:3.4.19]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onComplete(FluxMapFuseable.java:152) ~[reactor-core-3.4.19.jar:3.4.19]
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1817) ~[reactor-core-3.4.19.jar:3.4.19]
	at reactor.core.publisher.MonoCollect$CollectSubscriber.onComplete(MonoCollect.java:160) ~[reactor-core-3.4.19.jar:3.4.19]
	at reactor.core.publisher.FluxHandle$HandleSubscriber.onComplete(FluxHandle.java:220) ~[reactor-core-3.4.19.jar:3.4.19]
	at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onComplete(FluxMap.java:275) ~[reactor-core-3.4.19.jar:3.4.19]
	at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:400) ~[reactor-netty-core-1.0.20.jar:1.0.20]
	at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:419) ~[reactor-netty-core-1.0.20.jar:1.0.20]
	at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:473) ~[reactor-netty-core-1.0.20.jar:1.0.20]
	at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:703) ~[reactor-netty-http-1.0.20.jar:1.0.20]
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:93) ~[reactor-netty-core-1.0.20.jar:1.0.20]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.78.Final.jar:4.1.78.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.78.Final.jar:4.1.78.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.78.Final.jar:4.1.78.Final]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) ~[netty-transport-4.1.78.Final.jar:4.1.78.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) ~[netty-codec-4.1.78.Final.jar:4.1.78.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) ~[netty-codec-4.1.78.Final.jar:4.1.78.Final]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) ~[netty-transport-4.1.78.Final.jar:4.1.78.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.78.Final.jar:4.1.78.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.78.Final.jar:4.1.78.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.78.Final.jar:4.1.78.Final]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1373) ~[netty-handler-4.1.78.Final.jar:4.1.78.Final]
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1236) ~[netty-handler-4.1.78.Final.jar:4.1.78.Final]
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1285) ~[netty-handler-4.1.78.Final.jar:4.1.78.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510) ~[netty-codec-4.1.78.Final.jar:4.1.78.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449) ~[netty-codec-4.1.78.Final.jar:4.1.78.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279) ~[netty-codec-4.1.78.Final.jar:4.1.78.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.78.Final.jar:4.1.78.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.78.Final.jar:4.1.78.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.78.Final.jar:4.1.78.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.78.Final.jar:4.1.78.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.78.Final.jar:4.1.78.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.78.Final.jar:4.1.78.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.78.Final.jar:4.1.78.Final]
	at io.netty.channel.kqueue.AbstractKQueueStreamChannel$KQueueStreamUnsafe.readReady(AbstractKQueueStreamChannel.java:544) ~[netty-transport-classes-kqueue-4.1.78.Final.jar:4.1.78.Final]
	at io.netty.channel.kqueue.AbstractKQueueChannel$AbstractKQueueUnsafe.readEOF(AbstractKQueueChannel.java:485) ~[netty-transport-classes-kqueue-4.1.78.Final.jar:4.1.78.Final]
	at io.netty.channel.kqueue.KQueueEventLoop.processReady(KQueueEventLoop.java:213) ~[netty-transport-classes-kqueue-4.1.78.Final.jar:4.1.78.Final]
	at io.netty.channel.kqueue.KQueueEventLoop.run(KQueueEventLoop.java:289) ~[netty-transport-classes-kqueue-4.1.78.Final.jar:4.1.78.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.78.Final.jar:4.1.78.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.78.Final.jar:4.1.78.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.78.Final.jar:4.1.78.Final]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99) ~[reactor-core-3.4.19.jar:3.4.19]
		at reactor.core.publisher.Flux.blockLast(Flux.java:2645) ~[reactor-core-3.4.19.jar:3.4.19]
		at com.azure.core.util.paging.ContinuablePagedByIteratorBase.requestPage(ContinuablePagedByIteratorBase.java:94) ~[azure-core-1.30.0.jar:1.30.0]
		at com.azure.core.util.paging.ContinuablePagedByIteratorBase.hasNext(ContinuablePagedByIteratorBase.java:53) ~[azure-core-1.30.0.jar:1.30.0]
		at com.azure.resourcemanager.consumption.implementation.Utils$IteratorImpl.hasNext(Utils.java:175) ~[azure-resourcemanager-consumption-1.0.0-beta.3.jar:1.0.0-beta.3]
```

**Comment by weidongxu-microsoft** [comment]
@teemu47

Do you have the log before this error?

Should be something like "GET ...". Wish to see the URL of the request.

**Comment by teemu47** [comment]
Ok, got at least some logging to work by disabling slf4j. Here's the log:
```
[ForkJoinPool.commonPool-worker-5] INFO com.azure.identity.ClientSecretCredential - Azure Identity => getToken() result for scopes [https://management.core.windows.net//.default]: SUCCESS
[ForkJoinPool.commonPool-worker-5] INFO com.azure.core.implementation.AccessTokenCache - Acquired a new access token.
[ForkJoinPool.commonPool-worker-5] INFO com.azure.resourcemanager.consumption.implementation.UsageDetailsClientImpl$UsageDetailsService.list - {"az.sdk.message":"HTTP request","method":"GET","url":"https://management.azure.com//subscriptions/xxx-xxxx-xxxx/providers/Microsoft.Consumption/usageDetails?$expand=REDACTED&api-version=2021-10-01&metric=REDACTED","tryCount":"1","contentLength":0}
[reactor-http-kqueue-2] INFO com.azure.resourcemanager.consumption.implementation.UsageDetailsClientImpl$UsageDetailsService.list - {"az.sdk.message":"HTTP response","contentLength":"2627181","statusCode":200,"url":"https://management.azure.com//subscriptions/xxxx-xxxxx-xxxx/providers/Microsoft.Consumption/usageDetails?$expand=REDACTED&api-version=2021-10-01&metric=REDACTED","durationMs":2664}
[Thread-0] INFO com.azure.resourcemanager.consumption.implementation.UsageDetailsClientImpl$UsageDetailsService.listNext - {"az.sdk.message":"HTTP request","method":"GET","url":"https://management.azure.com/subscriptions/xxxx-xxxx-xxxx/providers/Microsoft.Consumption/usageDetails?$expand=REDACTED&api-version=2021-10-01&metric=REDACTED&sessiontoken=REDACTED&$skiptoken=REDACTED&skiptokenver=REDACTED&id=REDACTED","tryCount":"1","contentLength":0}
[reactor-http-kqueue-2] INFO com.azure.resourcemanager.consumption.implementation.UsageDetailsClientImpl$UsageDetailsService.listNext - {"az.sdk.message":"HTTP response","contentLength":"311","statusCode":400,"url":"https://management.azure.com/subscriptions/xxx-xxxx-xxxx/providers/Microsoft.Consumption/usageDetails?$expand=REDACTED&api-version=2021-10-01&metric=REDACTED&sessiontoken=REDACTED&$skiptoken=REDACTED&skiptokenver=REDACTED&id=REDACTED","durationMs":14}
[reactor-http-kqueue-2] WARN com.azure.core.implementation.serializer.HttpResponseBodyDecoder - Failed to deserialize the error entity.
Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
at [Source: (byte[])"<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
```

**Comment by XiaofeiCao** [comment]
Hi @teemu47 , seems like some key information's been redacted from the log.

Please use the following code snippet of http options to prevent redacting `skiptoken`, `skiptokenver`, `$expand` and `$filter` in query parameters and log again:
```java
ConsumptionManager manager = ConsumptionManager
  .configure()
  .withLogOptions(
    new HttpLogOptions()
        .addAllowedQueryParamName("skiptoken")
        .addAllowedQueryParamName("skiptokenver")
        .addAllowedQueryParamName("$expand")
        .addAllowedQueryParamName("$filter")
        .setLogLevel(HttpLogDetailLevel.BODY_AND_HEADERS))
  .authenticate(new DefaultAzureCredentialBuilder().build(), new AzureProfile(AzureEnvironment.AZURE));
``` 

Thanks.

**Comment by teemu47** [comment]
@XiaofeiCao Here you go
```
[ForkJoinPool.commonPool-worker-9] INFO com.azure.resourcemanager.consumption.implementation.UsageDetailsClientImpl$UsageDetailsService.list - {"az.sdk.message":"HTTP request","method":"GET","url":"https://management.azure.com//subscriptions/xxx-xxx/providers/Microsoft.Consumption/usageDetails?$expand=properties/usageStart%20ge%20%272021-11-01%27%20and%20properties/usageEnd%20lt%20%272021-12-01%27&api-version=2021-10-01&metric=REDACTED","tryCount":"1","contentLength":0}
[reactor-http-kqueue-20] INFO com.azure.resourcemanager.consumption.implementation.UsageDetailsClientImpl$UsageDetailsService.list - {"az.sdk.message":"HTTP response","contentLength":"2624310","statusCode":200,"url":"https://management.azure.com//subscriptions/xxx-xxx/providers/Microsoft.Consumption/usageDetails?$expand=properties/usageStart%20ge%20%272021-11-01%27%20and%20properties/usageEnd%20lt%20%272021-12-01%27&api-version=2021-10-01&metric=REDACTED","durationMs":11523}
[Thread-0] INFO com.azure.resourcemanager.consumption.implementation.UsageDetailsClientImpl$UsageDetailsService.listNext - {"az.sdk.message":"HTTP request","method":"GET","url":"https://management.azure.com/subscriptions/xxx-xxx/providers/Microsoft.Consumption/usageDetails?$expand=properties/usageStart ge '2021-11-01' and properties/usageEnd lt '2021-12-01'&api-version=2021-10-01&metric=REDACTED&sessiontoken=REDACTED&$skiptoken=317C313030307C313030307C46616C73657C547275657C30&skiptokenver=v1&id=REDACTED","tryCount":"1","contentLength":0}
[reactor-http-kqueue-20] WARN com.azure.core.implementation.serializer.HttpResponseBodyDecoder - Failed to deserialize the error entity.
Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (byte[])"<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Bad Request</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Bad Request</h2>
<hr><p>HTTP Error 400. The request is badly formed.</p>
</BODY></HTML>
"; line: 1, column: 2]
[reactor-http-kqueue-20] INFO com.azure.resourcemanager.consumption.implementation.UsageDetailsClientImpl$UsageDetailsService.listNext - {"az.sdk.message":"HTTP response","contentLength":"311","statusCode":400,"url":"https://management.azure.com/subscriptions/xxx-xxx/providers/Microsoft.Consumption/usageDetails?$expand=properties/usageStart ge '2021-11-01' and properties/usageEnd lt '2021-12-01'&api-version=2021-10-01&metric=REDACTED&sessiontoken=REDACTED&$skiptoken=317C313030307C313030307C46616C73657C547275657C30&skiptokenver=v1&id=REDACTED","durationMs":13,"body":"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN\"\"http://www.w3.org/TR/html4/strict.dtd\">\r\n<HTML><HEAD><TITLE>Bad Request</TITLE>\r\n<META HTTP-EQUIV=\"Content-Type\" Content=\"text/html; charset=us-ascii\"></HEAD>\r\n<BODY><h2>Bad Request</h2>\r\n<hr><p>HTTP Error 400. The request is badly formed.</p>\r\n</BODY></HTML>\r\n"}

```

**Comment by weidongxu-microsoft** [comment]
@XiaofeiCao Seems they still have space in nextLink URL and it is malformed. Please add "service attention" label.

Also ping their release owner https://github.com/Azure/sdk-release-request/issues/2291
