### ISSUE TITLE
Azure Spring Stream Binder Service Bus Topic - azure_service_bus_time_to_live header problem

### ISSUE THREAD

**Issue by MrStrik3** [Azure/azure-sdk-for-java#22893]
**Describe the bug**
Azure Spring Integration automatically adds an "azure_service_bus_time_to_live" header to the message. The type of the header is java.util.Duration. When the message is sent/stored to an Azure service bus Topic, the Duration object is converted into a String representation which looks like "PT336H". Which makes sense.

When it retrieves this message, Azure Service Bus Spring integration isn't able to convert back the String representation into a Duration object. An error is thrown. Does anyone know a way to fix that ?

The buggy code line seems to be located in com.azure.spring.integration.servicebus.converter.ServiceBusMessageConverter, line 49:
Optional.ofNullable(**(Duration) headers.get(TIME_TO_LIVE)**).ifPresent(message::setTimeToLive); 

It cannot cast "headers.get(TIME_TO_LIVE)"(String) into Duration

Thank you

***Exception or Stack Trace***
2021-07-09 09:58:40.904 ERROR 32966 --- [oundedElastic-2] o.s.integration.handler.LoggingHandler : org.springframework.messaging.MessageHandlingException: error occurred in message handler [com.azure.spring.integration.core.DefaultMessageHandler@248a3912]; nested exception is java.lang.ClassCastException: class java.lang.String cannot be cast to class java.time.Duration (java.lang.String and java.time.Duration are in module java.base of loader 'bootstrap'), failedMessage=GenericMessage [payload=byte[997], headers={azure_service_bus_time_to_live=PT336H, raw_id=1dd5d9fd-00f0-a662-1b64-9576c66ed753, azure_checkpointer=com.azure.spring.integration.core.AzureCheckpointer@5299eb8a, azure_service_bus_received_message_context=com.azure.messaging.servicebus.ServiceBusReceivedMessageContext@3f71038e, azure_service_bus_message_id=1dd5d9fd-00f0-a662-1b64-9576c66ed753, id=54a5a704-4b6e-061f-37a2-7692a106e0b6, contentType=application/json, azure_service_bus_partition_key=763290660, target-protocol=kafka, timestamp=1625839066772}] at org.springframework.integration.support.utils.IntegrationUtils.wrapInHandlingExceptionIfNecessary(IntegrationUtils.java:192) at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:65) at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder$SendingHandler.handleMessageInternal(AbstractMessageChannelBinder.java:1041) at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:56) at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:115) at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:133) at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:106) at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:72) at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:317) at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:272) at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187) at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166) at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47) at org.springframework.messaging.core.AbstractDestinationResolvingMessagingTemplate.send(AbstractDestinationResolvingMessagingTemplate.java:72) at org.springframework.cloud.stream.function.FunctionConfiguration$FunctionToDestinationBinder$1.doSendMessage(FunctionConfiguration.java:589) at org.springframework.cloud.stream.function.FunctionConfiguration$FunctionToDestinationBinder$1.handleMessageInternal(FunctionConfiguration.java:575) at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:56) at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:115) at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:133) at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:106) at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:72) at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:317) at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:272) at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187) at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166) at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47) at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109) at org.springframework.integration.endpoint.MessageProducerSupport.sendMessage(MessageProducerSupport.java:208) at com.azure.spring.integration.core.AbstractInboundChannelAdapter.receiveMessage(AbstractInboundChannelAdapter.java:61) at com.azure.spring.integration.servicebus.DefaultServiceBusMessageProcessor.lambda$processMessage$4(DefaultServiceBusMessageProcessor.java:70) at com.azure.messaging.servicebus.ServiceBusProcessorClient$1.onNext(ServiceBusProcessorClient.java:226) at com.azure.messaging.servicebus.ServiceBusProcessorClient$1.onNext(ServiceBusProcessorClient.java:200) at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runAsync(FluxPublishOn.java:440) at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:527) at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84) at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37) at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264) at java.base/java.util.concurrent.FutureTask.run(FutureTask.java) at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) at java.base/java.lang.Thread.run(Thread.java:829) Caused by: java.lang.ClassCastException: class java.lang.String cannot be cast to class java.time.Duration (java.lang.String and java.time.Duration are in module java.base of loader 'bootstrap') at com.azure.spring.integration.servicebus.converter.ServiceBusMessageConverter.setCustomHeaders(ServiceBusMessageConverter.java:91) at com.azure.spring.integration.servicebus.converter.ServiceBusMessageConverter.setCustomHeaders(ServiceBusMessageConverter.java:39) at com.azure.spring.integration.core.converter.AbstractAzureMessageConverter.fromMessage(AbstractAzureMessageConverter.java:72) at com.azure.spring.integration.servicebus.ServiceBusTemplate.sendAsync(ServiceBusTemplate.java:57) at com.azure.spring.integration.core.DefaultMessageHandler.handleMessageInternal(DefaultMessageHandler.java:74) at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:56) ... 40 more

**To Reproduce**
1. Retrieve a message from a Azure Service Bus Topic
2. Store it in an other Azure Service Bus Topic
3. When it's retrieved again, it will throw the exception/error

**Expected behavior**
Be able to retrieve a message from a topic without crashing

**Setup (please complete the following information):**
 - OS: Linux / Windows
 - IDE: IntelliJ
 - Library/Libraries:
com.azure.spring:azure-spring-cloud-stream-binder-servicebus-topic:2.6.0
com.azure.spring:azure-spring-integration-servicebus:2.6.0
'org.springframework.boot' version '2.5.2'
Java 11 - Openjdk

**Comment by joshfree** [comment]
@yiliuTo @chenrujun could you please take a look?

**Comment by yiliuTo** [comment]
@MrStrik3 thanks for your reporting, we will look into it soon

**Comment by yiliuTo** [comment]
Hi @MrStrik3 , this bug has been fixed in #22939, you can wait for the next release of 2.7.0 for the fix.
