### ISSUE TITLE
[BUG] FormRecognizer SDK throws RuntimeException when trying to parse dates in the format dd.MM.yyyy

### ISSUE THREAD

**Issue by kpentaris** [Azure/azure-sdk-for-java#22892]
**Describe the bug**
Providing an invoice image with the date _16.04.2019_ throws an exception from the SDK even though the engine properly understands that it is a date and properly extracts its textual representation.

***Exception or Stack Trace***
`java.lang.RuntimeException: Value was extracted from the form, but cannot be normalized to date type. Consider accessing the `valueData.text` property for a textual representation of the value.
	at com.azure.ai.formrecognizer.Transforms.setFormField(Transforms.java:370) ~[azure-ai-formrecognizer-3.1.1.jar:?]
	at com.azure.ai.formrecognizer.Transforms.lambda$getLabeledFieldMap$6(Transforms.java:322) ~[azure-ai-formrecognizer-3.1.1.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684) ~[?:1.8.0_281]
	at com.azure.ai.formrecognizer.Transforms.getLabeledFieldMap(Transforms.java:307) ~[azure-ai-formrecognizer-3.1.1.jar:?]
	at com.azure.ai.formrecognizer.Transforms.toRecognizedForm(Transforms.java:101) ~[azure-ai-formrecognizer-3.1.1.jar:?]
	at com.azure.ai.formrecognizer.FormRecognizerAsyncClient.lambda$beginRecognizeInvoices$87(FormRecognizerAsyncClient.java:1249) ~[azure-ai-formrecognizer-3.1.1.jar:?]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:113) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1815) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:249) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:73) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1815) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:249) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1815) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:249) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1815) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.MonoCallable.subscribe(MonoCallable.java:61) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:73) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2397) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:2193) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:2067) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:54) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1815) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.signalCached(MonoCacheTime.java:337) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.onNext(MonoCacheTime.java:354) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1815) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2397) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onSubscribe(MonoFlatMap.java:110) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:54) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.MonoCacheTime.subscribeOrReturn(MonoCacheTime.java:143) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.FluxDoOnEach$DoOnEachSubscriber.onNext(FluxDoOnEach.java:173) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1815) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:120) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1815) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:99) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.onNext(FluxRetryWhen.java:173) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.Operators$MonoInnerProducerBase.complete(Operators.java:2663) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.MonoSingle$SingleSubscriber.onComplete(MonoSingle.java:180) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onComplete(MonoFlatMapMany.java:260) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onComplete(FluxMapFuseable.java:150) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onComplete(FluxMapFuseable.java:150) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.MonoCollect$CollectSubscriber.onComplete(MonoCollect.java:159) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onComplete(FluxDoFinally.java:145) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.FluxHandle$HandleSubscriber.onComplete(FluxHandle.java:212) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onComplete(FluxMap.java:269) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:401) [reactor-netty-core-1.0.7.jar:1.0.7]
	at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:416) [reactor-netty-core-1.0.7.jar:1.0.7]
	at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:470) [reactor-netty-core-1.0.7.jar:1.0.7]
	at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:685) [reactor-netty-http-1.0.7.jar:1.0.7]
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:94) [reactor-netty-core-1.0.7.jar:1.0.7]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [netty-codec-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) [netty-codec-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1368) [netty-handler-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1245) [netty-handler-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1282) [netty-handler-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507) [netty-codec-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446) [netty-codec-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) [netty-codec-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_281]
2021-07-09T14:59:42,293 ERROR [reactor-http-nio-6] {} reactor.core.publisher.Operators - Operator called default onErrorDropped
reactor.core.Exceptions$ErrorCallbackNotImplemented: java.lang.RuntimeException: Value was extracted from the form, but cannot be normalized to date type. Consider accessing the `valueData.text` property for a textual representation of the value.
Caused by: java.lang.RuntimeException: Value was extracted from the form, but cannot be normalized to date type. Consider accessing the `valueData.text` property for a textual representation of the value.
	at com.azure.ai.formrecognizer.Transforms.setFormField(Transforms.java:370) ~[azure-ai-formrecognizer-3.1.1.jar:?]
	at com.azure.ai.formrecognizer.Transforms.lambda$getLabeledFieldMap$6(Transforms.java:322) ~[azure-ai-formrecognizer-3.1.1.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684) ~[?:1.8.0_281]
	at com.azure.ai.formrecognizer.Transforms.getLabeledFieldMap(Transforms.java:307) ~[azure-ai-formrecognizer-3.1.1.jar:?]
	at com.azure.ai.formrecognizer.Transforms.toRecognizedForm(Transforms.java:101) ~[azure-ai-formrecognizer-3.1.1.jar:?]
	at com.azure.ai.formrecognizer.FormRecognizerAsyncClient.lambda$beginRecognizeInvoices$87(FormRecognizerAsyncClient.java:1249) ~[azure-ai-formrecognizer-3.1.1.jar:?]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:113) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1815) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:249) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:73) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1815) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:249) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1815) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:249) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1815) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.MonoCallable.subscribe(MonoCallable.java:61) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:73) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2397) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:2193) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:2067) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:54) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1815) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.signalCached(MonoCacheTime.java:337) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.onNext(MonoCacheTime.java:354) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1815) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2397) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onSubscribe(MonoFlatMap.java:110) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:54) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.MonoCacheTime.subscribeOrReturn(MonoCacheTime.java:143) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.FluxDoOnEach$DoOnEachSubscriber.onNext(FluxDoOnEach.java:173) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1815) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:120) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1815) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:99) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.onNext(FluxRetryWhen.java:173) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.Operators$MonoInnerProducerBase.complete(Operators.java:2663) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.MonoSingle$SingleSubscriber.onComplete(MonoSingle.java:180) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onComplete(MonoFlatMapMany.java:260) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onComplete(FluxMapFuseable.java:150) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onComplete(FluxMapFuseable.java:150) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.MonoCollect$CollectSubscriber.onComplete(MonoCollect.java:159) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onComplete(FluxDoFinally.java:145) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.FluxHandle$HandleSubscriber.onComplete(FluxHandle.java:212) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onComplete(FluxMap.java:269) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:401) [reactor-netty-core-1.0.7.jar:1.0.7]
	at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:416) [reactor-netty-core-1.0.7.jar:1.0.7]
	at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:470) [reactor-netty-core-1.0.7.jar:1.0.7]
	at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:685) [reactor-netty-http-1.0.7.jar:1.0.7]
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:94) [reactor-netty-core-1.0.7.jar:1.0.7]`

**To Reproduce**
Provide an invoice image to the Invoice model with a date with the format `dd.MM.yyyy`

***Code Snippet***
N/A

**Expected behavior**
Not sure if this is considered a valid or invalid format but it should be parsable. If not then at least a hook where we can provide our own conversion _to the SDK_ should be available.

**Screenshots**
N/A

**Setup (please complete the following information):**
 - OS: Win 10
 - Library/Libraries: com.azure:azure-ai-formrecognizer:3.1.1

**Additional context**
This issue did not seem to be present in previous versions of the SDK, e.g. 3.1.0-beta

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ✓] Bug Description Added
- [ ✓] Repro Steps Added
- [ ✓] Setup information Added

**Comment by joshfree** [comment]
@samvaity could you please take a look?  We should add more localized test cases here.

**Comment by samvaity** [comment]
Hey @kpentaris, thanks for bringing this bug to our attention.
I believe we have resolved this bug as a part of our [azure-ai-formrecognizer-3.1.2](https://oss.sonatype.org/#nexus-search;quick~azure-ai-formrecognizer) latest release.

Do give it a try and let us know if that works.

**Comment by kpentaris** [comment]
Hello @samvaity, I have just tested with version 3.1.2 and it seems to work
fine. Unlucky the version became available (on maven repo) the same day I
posted the issue.

Thanks again for your prompt response!

**Comment by samvaity** [comment]
@kpentaris I am so glad it worked for you.
Thanks again for giving it a try.
