### ISSUE TITLE
[BUG] ARM CognitiveServices - 400 subscription does not have QuotaId/Feature required by SKU 'F0'.

### ISSUE THREAD

**Issue by v-jaswel** [Azure/azure-sdk-for-java#22894]
**Describe the bug**
When I use the Azure Resource Manager CognitiveServices client library for Java to create a Text Translation resource, I get the following error.
```
The subscription does not have QuotaId/Feature required by SKU 'F0'.
```

***Exception or Stack Trace***
```
Jul 09, 2021 3:23:31 PM com.azure.core.util.logging.ClientLogger performLogging
INFO: Azure Identity => getToken() result for scopes [https://management.core.windows.net//.default]: SUCCESS
Jul 09, 2021 3:23:31 PM com.azure.core.util.logging.ClientLogger info
INFO: Acquired a new access token.
Exception in thread "main" com.azure.core.management.exception.ManagementException: Status code 400, "{"error":{"code":"SpecialFeatureOrQuotaIdRequired","message":"The subscription does not have QuotaId/Feature required by SKU 'F0'."}}": The subscription does not have QuotaId/Feature required by SKU 'F0'.
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at com.azure.core.http.rest.RestProxy.instantiateUnexpectedException(RestProxy.java:343)
        at com.azure.core.http.rest.RestProxy.lambda$ensureExpectedStatus$5(RestProxy.java:382)
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:125)
        at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1815)
        at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.signalCached(MonoCacheTime.java:337)
        at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.onNext(MonoCacheTime.java:354)
        at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2397)
        at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.onSubscribe(MonoCacheTime.java:293)
        at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:192)
        at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53)
        at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
        at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
        at reactor.core.publisher.MonoCacheTime.subscribeOrReturn(MonoCacheTime.java:143)
        at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157)
        at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:130)
        at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:118)
        at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:220)
        at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:130)
        at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:184)
        at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107)
        at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1815)
        at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:128)
        at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:259)
        at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:142)
        at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:401)
        at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:416)
        at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:470)
        at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:685)
        at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:94)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1368)
        at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1245)
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1282)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
        Suppressed: java.lang.Exception: #block terminated with an error
                at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
                at reactor.core.publisher.Mono.block(Mono.java:1703)
                at com.azure.resourcemanager.cognitiveservices.implementation.AccountsClientImpl.create(AccountsClientImpl.java:521)
                at com.azure.resourcemanager.cognitiveservices.implementation.AccountImpl.create(AccountImpl.java:105)
                at Quickstart.create_resource(Quickstart.java:147)
                at Quickstart.main(Quickstart.java:105)
```

**To Reproduce**
1. Create a Service Principal.
1. Save the code snippets given in the next section.
1. Insert the following information into the Quickstart.java file:
- Your Service Principal application ID
- Your Service Principal secret
- Your Azure subscription ID
- Your Azure Active Directory tenant ID
- A resource group name in which to create the resource
- A custom subdomain name for the resource
1. Run:
```
mvn dependency:copy-dependencies
```
1. Run (Windows):
```
javac Quickstart.java -cp .;lib\*
java -cp .;lib\* Quickstart
```
1. Run (Linux):
```
javac -classpath .:./lib/* Quickstart.java
java -classpath .:./lib/* Quickstart
```

***Code Snippet***

Save the following to a file named pom.xml:
```
<?xml version="1.0" encoding="utf-8"?>
<!--
Source: https://gist.github.com/statico/547434f630d589651afcbe3f132b91d9
Run with: mvn clean dependency:copy-dependencies
-->
<project
    xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.foo</groupId>
  <artifactId>bar</artifactId>
  <version>0.0.1-SNAPSHOT</version>

  <dependencies>

    <!-- https://mvnrepository.com/artifact/com.azure/azure-identity -->
    <dependency>
        <groupId>com.azure</groupId>
        <artifactId>azure-identity</artifactId>
        <version>1.3.2</version>
        <scope>test</scope>
    </dependency>

    <!-- https://mvnrepository.com/artifact/com.azure.resourcemanager/azure-resourcemanager-cognitiveservices -->
    <dependency>
        <groupId>com.azure.resourcemanager</groupId>
        <artifactId>azure-resourcemanager-cognitiveservices</artifactId>
        <version>1.0.0-beta.2</version>
    </dependency>

    <!-- This fixes an error stating that the JacksonFeature class is missing. -->
    <!-- https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-core -->
    <dependency>
        <groupId>com.fasterxml.jackson.core</groupId>
        <artifactId>jackson-core</artifactId>
        <version>2.12.4</version>
    </dependency>

    <!-- This fixes the following runtime warnings:
    SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
    SLF4J: Defaulting to no-operation (NOP) logger implementation
    SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
    -->
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-jdk14</artifactId>
      <version>1.7.25</version>
    </dependency>

  </dependencies>

  <build>
    <directory>lib</directory>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
        <configuration>
          <outputDirectory>
            ${project.build.directory}
          </outputDirectory>
        </configuration>
      </plugin>
    </plugins>
  </build>

</project>
```

Save the following to a file named Quickstart.java:
```
import com.azure.core.management.*;
import com.azure.core.management.profile.*;
import com.azure.identity.*;
import com.azure.resourcemanager.cognitiveservices.*;
import com.azure.resourcemanager.cognitiveservices.implementation.*;
import com.azure.resourcemanager.cognitiveservices.models.*;

import java.io.*;
import java.lang.Object.*;
import java.util.*;
import java.net.*;

public class Quickstart {
    /*
    The application ID and secret of the service principal you are using to connect to the Azure Management Service.

    To create a service principal with the Azure CLI, see:
    https://docs.microsoft.com/en-us/cli/azure/create-an-azure-service-principal-azure-cli?view=azure-cli-latest
    To install the Azure CLI, see:
    https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest

    To create a service principal with Azure PowerShell, see: 
    https://docs.microsoft.com/en-us/powershell/azure/create-azure-service-principal-azureps?view=azps-3.3.0
    To install Azure PowerShell, see:
    https://github.com/Azure/azure-powershell

    When you create a service principal, you will see it has both an ID and an application ID.
    For example, if you create a service principal with Azure PowerShell, it should look like the following:

    Secret                : System.Security.SecureString
    ServicePrincipalNames : {<application ID>, <application URL>}
    ApplicationId         : <application ID>
    ObjectType            : ServicePrincipal
    DisplayName           : <name>
    Id                    : <ID>
    Type                  :
    */

    /*
    Be sure to use the service pricipal application ID, not simply the ID. 
    */
    private static String applicationId = "PASTE_YOUR_SERVICE_PRINCIPAL_APPLICATION_ID_HERE";
    private static String applicationSecret = "PASTE_YOUR_SERVICE_PRINCIPAL_SECRET_HERE";

    /* The ID of your Azure subscription. You can find this in the Azure Dashboard under Home > Subscriptions. */
    private static String subscriptionId = "PASTE_YOUR_SUBSCRIPTION_ID_HERE";

    /* The Active Directory tenant ID. You can find this in the Azure Dashboard under Home > Azure Active Directory. */
    private static String tenantId = "PASTE_YOUR_TENANT_ID_HERE";

    /* The name of the Azure resource group in which you want to create the resource.
    You can find resource groups in the Azure Dashboard under Home > Resource groups. */
    private static String resourceGroupName = "PASTE_YOUR_RESOURCE_GROUP_NAME_HERE";

    /* The name of the custom subdomain to use when you create the resource. This is optional.
    For example, if you create a Bing Search v7 resource with the custom subdomain name 'my-search-resource',
    your resource would have the endpoint https://my-search-resource.cognitiveservices.azure.com/.
    Note not all Cognitive Services allow custom subdomain names. */
    private static String subDomainName = "PASTE_YOUR_SUBDOMAIN_NAME_HERE";

    public static void main(String[] args) {

        /* For more information see:
        https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/resourcemanager/docs/AUTH.md
        */

        ClientSecretCredential credential = new ClientSecretCredentialBuilder()
            .clientId(applicationId)
            .clientSecret(applicationSecret)
            .tenantId(tenantId)
            .build();
        AzureProfile profile = new AzureProfile(tenantId, subscriptionId, AzureEnvironment.AZURE);

        CognitiveServicesManager client = CognitiveServicesManager.authenticate(credential, profile);
        // </snippet_auth>

        // <snippet_calls>
        String resourceName = "test_resource";
        String resourceKind = "TextTranslation";
        String resourceSku = "F0";
        Region resourceRegion = Region.US_WEST;

        // Create a resource with kind Text Translation, SKU F0 (free tier), location US West.
        String resourceId = create_resource (client, resourceName, resourceGroupName, resourceKind, resourceSku, resourceRegion);

        // Delete the resource.
        delete_resource (client, resourceId);

        /* NOTE: When you delete a resource, it is only soft-deleted. You must also purge it. Otherwise, if you try to create another
        resource with the same name or custom subdomain, you will receive an error stating that such a resource already exists. */
        purge_resource (client, resourceName, resourceGroupName, resourceRegion);
    }

    // Note: Region values are listed in:
    // https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/core/azure-core-management/src/main/java/com/azure/core/management/Region.java
    public static String create_resource (CognitiveServicesManager client, String resourceName, String resourceGroupName, String resourceKind, String resourceSku, Region resourceRegion) {
        System.out.println ("Creating resource: " + resourceName + "...");

        /* NOTE: If you do not want to use a custom subdomain name, remove the withCustomSubDomainName
        setter from the AccountProperties object. */
        Account result = client.accounts().define(resourceName)
            .withExistingResourceGroup(resourceGroupName)
            // Note: Do not call withRegion() first, as it does not exist on the Blank interface returned by define().
            .withRegion(resourceRegion)
            .withKind(resourceKind)
            .withSku(new Sku().withName(resourceSku))
            .withProperties(new AccountProperties().withCustomSubDomainName(subDomainName))
            .create();

        System.out.println ("Resource created.");
        System.out.println ("ID: " + result.id());
        System.out.println ("Provisioning state: " + result.properties().provisioningState().toString());
        System.out.println ();

        return result.id();
    }

    public static void delete_resource (CognitiveServicesManager client, String resourceId) {
        System.out.println ("Deleting resource: " + resourceId + "...");
        client.accounts().deleteById (resourceId);
        System.out.println ("Resource deleted.");
        System.out.println ();
    }

    public static void purge_resource (CognitiveServicesManager client, String resourceName, String resourceGroupName, Region resourceRegion) {
        System.out.println ("Purging resource: " + resourceName + "...");
        client.deletedAccounts().purge(resourceRegion.toString(), resourceGroupName, resourceName, null);
        System.out.println ("Resource purged.");
        System.out.println ();        
    }
}
```

**Expected behavior**

A Text Translation resource is created, deleted, and purged.

**Setup (please complete the following information):**
 - OS: Debian 10
 - IDE: None
 - Library/Libraries: See pom.xml above. No other libraries are installed except for those and their dependencies.

**Additional context**

I am able to create a Text Translation resource using the Python SDK without receiving this error.

The only information I have been able to find about this error is:

https://blog.jongallant.com/2021/04/solution-subscription-does-not-have-quotaid-feature-required-by-sku/

However, that concerns Text Analytics, not Text Translation, and the S0-S4 SKUs, not the F0 SKU.
Based on his solution, I tried changing the F0 SKU to just "F", but received an error stating that SKU is not valid.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by joshfree** [comment]
Thanks for filing this issue, @v-jaswel, someone from the `Mgmt` plane client library team will follow up with you shortly.

/cc @yungezz

**Comment by yungezz** [comment]
hi @qwordy could you pls have a look? thanks
