### ISSUE TITLE
Serialization warnings in com.azure.cosmos.implementation.ClientSideRequestStatistics

### ISSUE THREAD

**Issue by deepub** [Azure/azure-sdk-for-java#22974]
**Describe the bug**
Serialization error in com.azure.cosmos.implementation.ClientSideRequestStatistics. Seems related to
https://github.com/Azure/azure-sdk-for-java/issues/8281

***Exception or Stack Trace***

Jul 14, 2021 10:00:25 PM com.fasterxml.jackson.module.afterburner.ser.OptimizedBeanPropertyWriter _reportProblem
WARNING: Disabling Afterburner serialization for class com.azure.cosmos.implementation.ClientSideRequestStatistics$SystemInformation (field #1; mutator com.fasterxml.jackson.module.afterburner.ser.StringMethodPropertyWriter), due to access error (type java.lang.IllegalAccessError, message=failed to access class com.azure.cosmos.implementation.ClientSideRequestStatistics$SystemInformation from class com.azure.cosmos.implementation.ClientSideRequestStatistics$SystemInformation$Access4JacksonSerializer204a439f (com.azure.cosmos.implementation.ClientSideRequestStatistics$SystemInformation is in unnamed module of loader 'app'; com.azure.cosmos.implementation.ClientSideRequestStatistics$SystemInformation$Access4JacksonSerializer204a439f is in unnamed module of loader com.fasterxml.jackson.module.afterburner.util.MyClassLoader @780ec4a5))

java.lang.IllegalAccessError: failed to access class com.azure.cosmos.implementation.ClientSideRequestStatistics$SystemInformation from class com.azure.cosmos.implementation.ClientSideRequestStatistics$SystemInformation$Access4JacksonSerializer204a439f (com.azure.cosmos.implementation.ClientSideRequestStatistics$SystemInformation is in unnamed module of loader 'app'; com.azure.cosmos.implementation.ClientSideRequestStatistics$SystemInformation$Access4JacksonSerializer204a439f is in unnamed module of loader com.fasterxml.jackson.module.afterburner.util.MyClassLoader @780ec4a5)
	at com.azure.cosmos.implementation.ClientSideRequestStatistics$SystemInformation$Access4JacksonSerializer204a439f.stringGetter(com/azure/cosmos/implementation/ClientSideRequestStatistics$SystemInformation$Access4JacksonSerializer.java)
	at com.fasterxml.jackson.module.afterburner.ser.StringMethodPropertyWriter.serializeAsField(StringMethodPropertyWriter.java:44)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:770)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:3126)
	at com.fasterxml.jackson.core.base.GeneratorBase.writeObject(GeneratorBase.java:388)
	at com.fasterxml.jackson.core.JsonGenerator.writeObjectField(JsonGenerator.java:2332)
	at com.azure.cosmos.implementation.ClientSideRequestStatistics$ClientSideRequestStatisticsSerializer.serialize(ClientSideRequestStatistics.java:314)
	at com.azure.cosmos.implementation.ClientSideRequestStatistics$ClientSideRequestStatisticsSerializer.serialize(ClientSideRequestStatistics.java:262)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:119)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4487)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:3742)
	at com.azure.cosmos.implementation.FeedResponseDiagnostics.toString(FeedResponseDiagnostics.java:79)
	at java.base/java.lang.String.valueOf(String.java:3042)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:168)
	at com.azure.cosmos.CosmosDiagnostics.fillCosmosDiagnostics(CosmosDiagnostics.java:106)
	at com.azure.cosmos.CosmosDiagnostics.toString(CosmosDiagnostics.java:62)
	at java.base/java.lang.String.valueOf(String.java:3042)
	at java.base/java.io.PrintStream.println(PrintStream.java:897)
	at com.csconsulting.cosmos.demo.CRUDDemo.lambda$queryDocs$1(CRUDDemo.java:125)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at com.csconsulting.cosmos.demo.CRUDDemo.lambda$queryDocs$2(CRUDDemo.java:121)
	at java.base/java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104)
	at java.base/java.util.stream.IntPipeline$Head.forEach(IntPipeline.java:593)
	at com.csconsulting.cosmos.demo.CRUDDemo.queryDocs(CRUDDemo.java:112)
	at com.csconsulting.cosmos.demo.CRUDDemo.main(CRUDDemo.java:28)

**To Reproduce**
Occurs when I attempt to add the following line of code using v4.16.0 SDK:
System.out.println(jsonNodeFeedResponse.getCosmosDiagnostics());
I am able to reproduce this issue in the v4.17.0 SDK too.

***Code Snippet***
   private static void queryDocs(CosmosContainer container, int count) {

        IntStream.range(1, count)
                .forEach(
                        counter -> {
                            CosmosQueryRequestOptions queryOptions = new CosmosQueryRequestOptions();
                            queryOptions.setQueryMetricsEnabled(true);
                            String sql = "SELECT * FROM coll WHERE coll.id = " + "\"" + CONST_KEY_PREFIX + counter + "\"";
                            System.out.println(sql);
                            CosmosPagedIterable<JsonNode> pagedIterable = container.queryItems(sql, queryOptions, JsonNode.class);
                            pagedIterable.iterableByPage(10)
                                    .forEach(jsonNodeFeedResponse -> {
                                        System.out.println(jsonNodeFeedResponse.getResults().get(0));
                                        System.out.println("Request Charges = " + jsonNodeFeedResponse.getRequestCharge() + "RUs"
                                        + " and Duration = " + jsonNodeFeedResponse.getCosmosDiagnostics().getDuration());

                                        //Offending line of code below. Commenting out this line eliminates the warnings
                                        System.out.println(jsonNodeFeedResponse.getCosmosDiagnostics());

                            });

                        }
                );

**Expected behavior**
Adding the getCosmosDiagnostics() call shouldn't result in warnings. 

**Screenshots**

**Setup (please complete the following information):**
 - OS: [macOS]
 - IDE: [IntelliJ]
 - Library/Libraries: [com.azureazure-cosmos:4.17.0]

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by joshfree** [comment]
@simplynaveen20 / @kushagraThapar could you please follow up?

**Comment by kushagraThapar** [comment]
@simplynaveen20  - can you please take a look at this ?

@deepub  - what Java version are you using ?
I am on Java 11 and unable to reproduce this on my local macOS machine.

**Comment by deepub** [comment]
Hi @kushagraThapar ,

I am running Java 16 on my macOS laptop.

openjdk 16 2021-03-16
OpenJDK Runtime Environment (build 16+36-2231)
OpenJDK 64-Bit Server VM (build 16+36-2231, mixed mode, sharing)

**Comment by deepub** [comment]
Hi @kushagraThapar , @simplynaveen20 ,
Any updates on this? Do you folks see this issue on jdk 16?

Thanks!

**Comment by simplynaveen20** [comment]
Looking into it today

**Comment by deepub** [comment]
Thanks @simplynaveen20 and @kushagraThapar !
