### ISSUE TITLE
Blob - Listing versions and using a delimiter are mutually exclusive

### ISSUE THREAD

**Issue by abhikt48** [Azure/azure-sdk-for-java#22982]
We are using `azure-storage-blob-12.10.0` to list blobs. While testing I am getting error - `Listing versions and using a delimiter are mutually exclusive`.  

We have requirement to 
1. list all blobs from directory but do not include blobs from child directory
2. Extract all available metadata including versions

For achieving above requirements - I included `/` delimiter while listing - `listBlobsByHierarchy("/", listBlobsOptions , null)` and set `blobListDetails.setRetrieveVersions(true)` to retrieve versions.

I am able to retrieve blob versions without delimiter. Could you please suggest - Is this expected behaviour?

**Sample Code**
```
public static void listBlobsWithVersion() {
        
        System.out.println("** List with versions start **");
        
        String directoryName = "test";
        
        ListBlobsOptions listBlobsOptions = new ListBlobsOptions();
        listBlobsOptions.setPrefix(directoryName);
        listBlobsOptions.setMaxResultsPerPage(100);
        
        BlobListDetails blobListDetails = new BlobListDetails();
        blobListDetails.setRetrieveMetadata(true);
        blobListDetails.setRetrieveVersions(true);
        
        listBlobsOptions.setDetails(blobListDetails);
        
        BlobContainerClient blobContainerClient = new BlobContainerClientBuilder().endpoint(BLOB_SAS_SERVICE).containerName(CONTAINER_NAME).buildClient();
        
        Iterator<BlobItem> iterator = blobContainerClient.listBlobsByHierarchy("/", listBlobsOptions , null).iterator();;
        
        while(iterator.hasNext()) {
            BlobItem blobItem = iterator.next();
            System.out.println("isPrefix " + blobItem.isPrefix() + ", blobName - " + blobItem.getName());
        }
        
        System.out.println("** List with versions finished **");
        
    }
```

**Error message**  
```
Exception in thread "main" com.azure.storage.blob.models.BlobStorageException: Status code 400, "﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidQueryParameterValue</Code><Message>Value for one of the query parameters specified in the request URI is invalid.
RequestId:adfa1dc5-a01e-****-418d-***000000
Time:2021-07-15T15:26:31.9913953Z</Message><QueryParameterName>include</QueryParameterName><QueryParameterValue>versions</QueryParameterValue><Reason>Listing versions and using a delimiter are mutually exclusive.</Reason></Error>"
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.azure.core.http.rest.RestProxy.instantiateUnexpectedException(RestProxy.java:337)
	at com.azure.core.http.rest.RestProxy.lambda$ensureExpectedStatus$5(RestProxy.java:378)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:118)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1782)
	at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.signalCached(MonoCacheTime.java:320)
	at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.onNext(MonoCacheTime.java:337)
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2344)
	at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.onSubscribe(MonoCacheTime.java:276)
	at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:191)
	at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at reactor.core.publisher.MonoCacheTime.subscribeOrReturn(MonoCacheTime.java:132)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:150)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:123)
	at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:112)
	at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:213)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:123)
	at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:178)
	at reactor.core.publisher.FluxContextStart$ContextStartSubscriber.onNext(FluxContextStart.java:96)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1782)
	at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:121)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:252)
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:136)
	at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:374)
	at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:373)
	at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:429)
	at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:655)
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:96)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1526)
	at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1287)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1324)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
		at reactor.core.publisher.Flux.blockLast(Flux.java:2497)
		at com.azure.core.util.paging.ContinuablePagedByIteratorBase.requestPage(ContinuablePagedByIteratorBase.java:94)
		at com.azure.core.util.paging.ContinuablePagedByItemIterable$ContinuablePagedByItemIterator.<init>(ContinuablePagedByItemIterable.java:50)
		at com.azure.core.util.paging.ContinuablePagedByItemIterable.iterator(ContinuablePagedByItemIterable.java:37)
		at com.azure.core.util.paging.ContinuablePagedIterable.iterator(ContinuablePagedIterable.java:106)
		at com.abc.blob.Test.listBlobsOptionsWithVersion(Test.java:254)
		at com.abc.blob.Test.main(Test.java:269)

```

**Setup (please complete the following information if applicable):**
OS: window
IDE : eclipse
Version of the Library used: `azure-storage-blob-12.10.0`

**Comment by joshfree** [comment]
Related https://github.com/Azure/azure-sdk-for-java/issues/19335 and https://github.com/Azure/azure-sdk-for-java/issues/19486

**Comment by joshfree** [comment]
@rickle-msft could you please follow up with @abhikt48

**Comment by rickle-msft** [comment]
Hi, @abhikt48. Thanks for your question. As mentioned in the linked issues above, listing versions with a delimiter is not a feature that is supported by the service, so there's not much we can do from the sdk side. If you would like, we can help brainstorm alternative solutions to your scenario.

**Comment by abhikt48** [comment]
Hi @rickle-msft , Sure please. It will be great if you can provide alternative solutions.

**Comment by rickle-msft** [comment]
Sure. Can you give some more insight into your scenario and its parameters? The easiest place to start is to do a client side filter. i.e. list all the blobs in the container and include versions. Then, filter out any blobs whose name indicates a subdirectory. This may be untenable if your container has a prohibitively large number of blobs you were hoping to filter out with the delimited listing, but it can be alright if your virtual directory structure isn't especially large. Can you comment on how that might work for you?

I also want to mention that because this is a service limitation, this can serve as a brainstorming session to think about possible workarounds for that behavior, but it is unlikely we will be able to amend the behavior to fit your scenario exactly.

**Comment by abhikt48** [comment]
HI @rickle-msft , Thanks for details. We don't have control over size of sub-directories, it could be large for some scenarios. 
We can't go ahead to filter sub-directories blobs due to performance factor. 

As this is Service limitation, so we can't do much.  Is possible for you to raise request to service team to provide this feature?

Our Requirement - We need to list over directory and provide all available metadata to user.

Regards,
Abhishek Kumar

**Comment by rickle-msft** [comment]
Yes, I can raise this request to the service team. Once that's done, are you ok if I close this issue?

**Comment by abhikt48** [comment]
Sure.. thanks @rickle-msft
