### ISSUE TITLE
[BUG] spring-boot-starter-activedirectory-b2c baseUri is missing in the sample configurations in the README

### ISSUE THREAD

**Issue by totakura** [Azure/azure-sdk-for-java#23082]
**Describe the bug**
The README doesn't use `baseUri` in some of the configuration samples shown in the project's README (https://github.com/Azure/azure-sdk-for-java/tree/azure-spring-boot-starter-active-directory-b2c_3.6.1/sdk/spring/azure-spring-boot-starter-active-directory-b2c). For example, refer to the point 4 of this section: https://github.com/Azure/azure-sdk-for-java/tree/azure-spring-boot-starter-active-directory-b2c_3.6.1/sdk/spring/azure-spring-boot-starter-active-directory-b2c#accessing-a-resource-server

Missing `baseUri` causes the following stack trace:

***Exception or Stack Trace***

```
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'jwtProcessor' defined in class path resource [com/azure/spring/autoconfigure/b2c/AADB2CResourceServerAutoConfiguration.class]: Unsatisfied dependency expressed through method 'jwtProcessor' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'aadIssuerJWSKeySelector' defined in class path resource [com/azure/spring/autoconfigure/b2c/AADB2CResourceServerAutoConfiguration.class]: Unsatisfied dependency expressed through method 'aadIssuerJWSKeySelector' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'trustedIssuerRepository' defined in class path resource [com/azure/spring/autoconfigure/b2c/AADB2CResourceServerAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.azure.spring.aad.AADTrustedIssuerRepository]: Factory method 'trustedIssuerRepository' threw exception; nested exception is java.lang.IllegalArgumentException: baseUri cannot be null
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:541)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1334)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1380)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1300)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
```

**To Reproduce**

1. Create a new Spring boot project.
2. Add azure-spring-boot-starter-activedirectory-b2c-3.6.1 as a dependency
3. Follow the instructions of this section for creating a resource server: https://github.com/Azure/azure-sdk-for-java/tree/azure-spring-boot-starter-active-directory-b2c_3.6.1/sdk/spring/azure-spring-boot-starter-active-directory-b2c#accessing-a-resource-server
4. Try to run the project

**Expected behavior**
README to be corrected to include `baseUri` as part of the configuration snipped.

**Setup (please complete the following information):**
 - OS: ArchLinux (uname: `Linux iris 5.12.12-arch1-1 #1 SMP PREEMPT Fri, 18 Jun 2021 21:59:22 +0000 x86_64 GNU/Linux`)
 - Library/Libraries: azure-spring-boot-starter-activedirectory-b2c-3.6.1

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by joshfree** [comment]
@chenrujun could you please follow up with @totakura?

**Comment by chenrujun** [comment]
Related issue: https://github.com/Azure/azure-sdk-for-java/issues/23134
