### ISSUE TITLE
[BUG] Jackson afterburner warning messages when using FeedResponseDiagnostics

### ISSUE THREAD

**Issue by chetanmeh** [Azure/azure-sdk-for-java#23109]
**Describe the bug**
Jackson afterburner warning messages when converting FeedResponseDiagnostics to string. Related to #18215, #19847 

***Exception or Stack Trace***

```
16:56:42  java.lang.IllegalAccessError: failed to access class com.azure.cosmos.implementation.ClientSideRequestStatistics$SystemInformation from class com.azure.cosmos.implementation.ClientSideRequestStatistics$SystemInformation$Access4JacksonSerializer204a439f (com.azure.cosmos.implementation.ClientSideRequestStatistics$SystemInformation is in unnamed module of loader 'app'; com.azure.cosmos.implementation.ClientSideRequestStatistics$SystemInformation$Access4JacksonSerializer204a439f is in unnamed module of loader com.fasterxml.jackson.module.afterburner.util.MyClassLoader @fc4b9d)
16:56:42  	at com.azure.cosmos.implementation.ClientSideRequestStatistics$SystemInformation$Access4JacksonSerializer204a439f.stringGetter(com/azure/cosmos/implementation/ClientSideRequestStatistics$SystemInformation$Access4JacksonSerializer.java)
16:56:42  	at com.fasterxml.jackson.module.afterburner.ser.StringMethodPropertyWriter.serializeAsField(StringMethodPropertyWriter.java:44)
16:56:42  	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:770)
16:56:42  	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
16:56:42  	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
16:56:42  	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
16:56:42  	at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:3126)
16:56:42  	at com.fasterxml.jackson.core.base.GeneratorBase.writeObject(GeneratorBase.java:388)
16:56:42  	at com.fasterxml.jackson.core.JsonGenerator.writeObjectField(JsonGenerator.java:2332)
16:56:42  	at com.azure.cosmos.implementation.ClientSideRequestStatistics$ClientSideRequestStatisticsSerializer.serialize(ClientSideRequestStatistics.java:314)
16:56:42  	at com.azure.cosmos.implementation.ClientSideRequestStatistics$ClientSideRequestStatisticsSerializer.serialize(ClientSideRequestStatistics.java:262)
16:56:42  	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:119)
16:56:42  	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79)
16:56:42  	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18)
16:56:42  	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
16:56:42  	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
16:56:42  	at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4487)
16:56:42  	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:3742)
16:56:42  	at com.azure.cosmos.implementation.FeedResponseDiagnostics.toString(FeedResponseDiagnostics.java:79)
16:56:42  	at java.base/java.lang.String.valueOf(String.java:2951)
16:56:42  	at java.base/java.lang.StringBuilder.append(StringBuilder.java:168)
16:56:42  	at com.azure.cosmos.CosmosDiagnostics.fillCosmosDiagnostics(CosmosDiagnostics.java:103)
16:56:42  	at com.azure.cosmos.CosmosDiagnostics.toString(CosmosDiagnostics.java:59)
```

**To Reproduce**

***Code Snippet***

**Expected behavior**
This warning should not be logged

**Setup (please complete the following information):**
 - OS: Linux
 - IDE: IntelliJ
 - Library/Libraries: azure-cosmos library version : 4.16.0

**Additional context**
For detailed logging in some cases we need to access `CosmosDiagnostics` for query operations.

Looking at current flow I see that `FeedResponseDiagnostics` still uses `Utils.getSimpleObjectMapper()`. Looking at discussion in other issues  #19847 I think this would cause issue as this mapper as AfterBurner module configured

https://github.com/Azure/azure-sdk-for-java/blob/a292286161a4d817165a2529ad7cec75f8d3886c/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/FeedResponseDiagnostics.java#L88-L93

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [ ] Repro Steps Added
- [x] Setup information Added

**Comment by joshfree** [comment]
Related issue https://github.com/Azure/azure-sdk-for-java/issues/23005

**Comment by joshfree** [comment]
@kushagraThapar could you please help route this?

**Comment by kushagraThapar** [comment]
@chetanmeh - thanks for opening this issue, it has been already fixed in master branch, will be shipped as part of our release in August first week.

**Comment by simplynaveen20** [comment]
Fixed in new release https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-cosmos/CHANGELOG.md#4180-2021-08-16
