### ISSUE TITLE
Blob - renewLease - The lease ID specified did not match the lease ID for the blob.

### ISSUE THREAD

**Issue by abhikt48** [Azure/azure-sdk-for-java#23140]
We are using `azure-storage-blob-12.10.2` to append blobs.  We are exploring option to apply lease while appending blob in multithreaded environments.

I tried to renew blob with below sample code but getting this error - **The lease ID specified did not match the lease ID for the blob.**

`blobLeaseClient.renewLease()` doesn't have any option to specify existing leaseID but still getting `did not match the lease ID ` error. 

Could you please suggest how can we renewLease()?  

**NOTE** - As we are using this in multithreaded environment, so `BlobLeaseClient ` object will be different for acquiring and renewing the blob.

**Sample Code**
```
public static void appendBlob(String appendBlobWithLeaseID) {
        LOGGER.info("** Append Blob Start **");
        BlobContainerClient blobContainerClient = new BlobContainerClientBuilder().endpoint(BLOB_SAS_SERVICE).containerName(BLOB_CONTAINER_NAME).buildClient();

        BlobClient blobClient = blobContainerClient.getBlobClient(BLOB_NAME);
        AppendBlobClient appendBlobClient = blobClient.getAppendBlobClient();
        
        if (!appendBlobClient.exists()) {
            appendBlobClient.create(false);
        }

        InputStream payloadAsInputStream = new ByteArrayInputStream(TEST_MESSAGE.getBytes());
        int blobLength = TEST_MESSAGE.length();
        
        AppendBlobRequestConditions appendBlobRequestConditions = new AppendBlobRequestConditions();
        
        BlobLeaseClient blobLeaseClient = new BlobLeaseClientBuilder().blobClient(blobClient).buildClient();
        
        String leaseStatus = blobClient.getProperties().getLeaseStatus().toString();
        boolean isBlobLeased = LOCKED.equalsIgnoreCase(leaseStatus);
        
        LOGGER.info("** isBlobLeased '{}' , leaseStatus '{}'  ***", isBlobLeased, leaseStatus);
        
        String renewLeaseID = blobLeaseClient.renewLease();
        LOGGER.info("** renewLease '{}'  ***", renewLeaseID);
        
        appendBlobRequestConditions.setLeaseId(renewLeaseID);
        
        appendBlobClient.appendBlockWithResponse(payloadAsInputStream, blobLength, null, appendBlobRequestConditions , null, Context.NONE);
        
        LOGGER.info("** Append Blob '{}' successfully ***", BLOB_NAME);
    }
```

**Error Logs**
```
INFO  2021-07-22 18:37:48,418 [main] com.test.blob.BlobAppendOperation: ** Append Blob Start **
INFO  2021-07-22 18:37:52,499 [main] com.test.blob.BlobAppendOperation: ** isBlobLeased 'false' , leaseStatus 'unlocked'  ***
Exception in thread "main" com.azure.storage.blob.models.BlobStorageException: Status code 409, "<?xml version="1.0" encoding="utf-8"?><Error><Code>LeaseIdMismatchWithLeaseOperation</Code><Message>The lease ID specified did not match the lease ID for the blob.
RequestId:ece1bXXX****
Time:2021-07-22T17:37:52.5201856Z</Message></Error>"
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.azure.core.http.rest.RestProxy.instantiateUnexpectedException(RestProxy.java:337)
	at com.azure.core.http.rest.RestProxy.lambda$ensureExpectedStatus$5(RestProxy.java:378)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:118)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1782)
	at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.signalCached(MonoCacheTime.java:320)
	at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.onNext(MonoCacheTime.java:337)
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2344)
	at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.onSubscribe(MonoCacheTime.java:276)
	at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:191)
	at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at reactor.core.publisher.MonoCacheTime.subscribeOrReturn(MonoCacheTime.java:132)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:150)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:123)
	at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:112)
	at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:213)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:123)
	at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:178)
	at reactor.core.publisher.FluxContextStart$ContextStartSubscriber.onNext(FluxContextStart.java:96)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1782)
	at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:121)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:252)
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:136)
	at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:374)
	at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:373)
	at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:429)
	at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:655)
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:96)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1526)
	at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1287)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1324)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
		at reactor.core.publisher.Mono.block(Mono.java:1685)
		at com.azure.storage.common.implementation.StorageImplUtils.blockWithOptionalTimeout(StorageImplUtils.java:131)
		at com.azure.storage.blob.specialized.BlobLeaseClient.renewLeaseWithResponse(BlobLeaseClient.java:182)
		at com.azure.storage.blob.specialized.BlobLeaseClient.renewLeaseWithResponse(BlobLeaseClient.java:162)
		at com.azure.storage.blob.specialized.BlobLeaseClient.renewLease(BlobLeaseClient.java:142)
		at com.test.blob.BlobAppendOperation.appendBlob(BlobAppendOperation.java:117)
		at com.test.blob.BlobAppendOperation.main(BlobAppendOperation.java:130)

```
**Setup (please complete the following information if applicable):**
OS: window
IDE : eclipse based
Version of the Library used: `azure-storage-blob-12.10.2`

**Comment by joshfree** [comment]
@rickle-msft could you please follow up with @abhikt48?

**Comment by rickle-msft** [comment]
Hi, @abhikt48.

I think where we need to start is that you have to make an initial call to acquire a lease before you can do anything else with it. You only use renew to extend the lifetime of a lease you have previously acquired. Is there another part of your code that calls `BlobLeaseClient.acquireLease()`?

**Comment by rickle-msft** [comment]
[This](https://docs.microsoft.com/en-us/rest/api/storageservices/lease-blob#remarks) section and [this](https://docs.microsoft.com/en-us/azure/storage/blobs/concurrency-manage?tabs=dotnet#pessimistic-concurrency-for-blobs) section might be helpful for understanding the life cycle of blob leases if you haven't seen them already

**Comment by abhikt48** [comment]
@rickle-msft thanks for sharing documents. Will go through and let you know for any questions.

**Comment by abhikt48** [comment]
@rickle-msft  - Yes correct, `BlobLeaseClient.acquireLease()` will get call from another process. 

`BlobLeaseClient.acquireLease()` doesn't accept lease ID, neither `BlobLeaseClient.renewLease()`. Also checked option in `BlobClient` to set leaseID , but I didn't find any option to set leaseID .

We are not sharing `BlobClient` with any other process becuase `BlobClient` will be unique for every blobName, and we can't preserve `BlobClient `due to large number of blobs and reusability point of view.

So can you please provide anyway to renew lease from different `BlobClient` and `BlobLeaseClient` object. If this option is not available yet, then can you please accept this as feature request?

Please find below sample code to replicate this issue and let me know for any queries.

**Sample Code**
```
public static void appendBlob() {
        LOGGER.info("** Append Blob Start **");
        BlobContainerClient blobContainerClient = new BlobContainerClientBuilder().endpoint(BLOB_SAS_SERVICE).containerName(BLOB_CONTAINER_NAME).buildClient();

        InputStream payloadAsInputStream = new ByteArrayInputStream(TEST_MESSAGE.getBytes());
        int blobLength = TEST_MESSAGE.length();
        
        AppendBlobRequestConditions appendBlobRequestConditions = new AppendBlobRequestConditions();
        
        BlobClient blobClient = blobContainerClient.getBlobClient(BLOB_NAME);
        AppendBlobClient appendBlobClient = blobClient.getAppendBlobClient();
        
        BlobLeaseClient blobLeaseClient = new BlobLeaseClientBuilder().blobClient(blobClient).buildClient();
               
        String acquireLeaseId = blobLeaseClient.acquireLease(60);
        LOGGER.info("** acquireLeaseId '{}'  ***", acquireLeaseId);
        
        BlobClient blobClientForRenew = blobContainerClient.getBlobClient(BLOB_NAME);
        
        BlobLeaseClient blobLeaseClientForRenew = new BlobLeaseClientBuilder().blobClient(blobClientForRenew).buildClient();
        String renewLeaseID = blobLeaseClientForRenew.renewLease();
        LOGGER.info("** renewLease '{}'  ***", renewLeaseID);
        
        appendBlobRequestConditions.setLeaseId(renewLeaseID);
        appendBlobClient.appendBlockWithResponse(payloadAsInputStream, blobLength, null, appendBlobRequestConditions , null, Context.NONE);
        
        LOGGER.info("** Append Blob '{}'  successfully ***", BLOB_NAME);
    }
```

**Comment by rickle-msft** [comment]
@abhikt48 There is an option to set the leaseId on the LeaseClientBuilder. It must be the same as the id received when the lease was acquired. You can also use the same LeaseClient used to acquire the lease as the client will internally the store the lease for future operations. You will need to use one of these methods to renew the lease. 

Note that if you are trying to renew the lease from a process that is separate from where the lease was acquired, the lease will either need to be broken and reaquired in the new process before being renewed, or the lease id needs to be communicated to the new process

**Comment by abhikt48** [comment]
Hi @rachel-msft , Thanks for quick reply. Yes i am able to renew lease now. Thanks for information.
