### ISSUE TITLE
[BUG] disabling AAD authentication no longer possible through configuration

### ISSUE THREAD

**Issue by dvut** [Azure/azure-sdk-for-java#23154]
**Describe the bug**
Since azure-spring-boot-starter-active-directory 3.7.0 is it no longer possible to disable authentication using configuration properties.

Before 3.7.0 it was possible to disable authentication by removing the following configuration properties.
- azure.activedirectory.client-id
- azure.activedirectory.client-secret
- azure.activedirectory.tenant-id

This behavior was added to previous versions of the documentation here:
https://github.com/Azure/azure-sdk-for-java/pull/12645/files#diff-753fe17d65310e2021a1acac79cda656615c652a705526d439f86bd28cfba87f

Use case is an application where azure authentication can be enabled/disabled through configuration properties.

***Exception or Stack Trace***
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'azure.activedirectory-com.azure.spring.autoconfigure.aad.AADAuthenticationProperties': Invocation of init method failed; nested exception is java.lang.IllegalStateException: 'azure.activedirectory.client-id' must be configured when application type is 'web_application', 'resource_server_with_obo' or 'web_application_and_resource_server'.
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1786) ~[spring-beans-5.3.8.jar:5.3.8]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:602) ~[spring-beans-5.3.8.jar:5.3.8]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524) ~[spring-beans-5.3.8.jar:5.3.8]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.8.jar:5.3.8]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.8.jar:5.3.8]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.8.jar:5.3.8]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.8.jar:5.3.8]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944) ~[spring-beans-5.3.8.jar:5.3.8]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.8.jar:5.3.8]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.8.jar:5.3.8]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:144) ~[spring-boot-2.4.8.jar:2.4.8]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:771) ~[spring-boot-2.4.8.jar:2.4.8]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:763) [spring-boot-2.4.8.jar:2.4.8]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:438) [spring-boot-2.4.8.jar:2.4.8]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:339) [spring-boot-2.4.8.jar:2.4.8]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1329) [spring-boot-2.4.8.jar:2.4.8]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1318) [spring-boot-2.4.8.jar:2.4.8]
	at nl.utwente.utspringmvc.UtSpringBootApplication.main(UtSpringBootApplication.java:18) [classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) [spring-boot-devtools-2.4.8.jar:2.4.8]
Caused by: java.lang.IllegalStateException: 'azure.activedirectory.client-id' must be configured when application type is 'web_application', 'resource_server_with_obo' or 'web_application_and_resource_server'.
	at com.azure.spring.autoconfigure.aad.AADAuthenticationProperties.validateClientId(AADAuthenticationProperties.java:472) ~[azure-spring-boot-3.7.0.jar:3.7.0]
	at com.azure.spring.autoconfigure.aad.AADAuthenticationProperties.afterPropertiesSet(AADAuthenticationProperties.java:459) ~[azure-spring-boot-3.7.0.jar:3.7.0]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1845) ~[spring-beans-5.3.8.jar:5.3.8]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1782) ~[spring-beans-5.3.8.jar:5.3.8]
	... 22 more
```

**To Reproduce**
1. create a spring boot web application with "web_application" type authentication
2. make the config class conditional using an annotation such as: @ConditionalOnProperty(prefix = "azure.activedirectory", value = "tenant-id")
3. start it and test if server sider azure auth works
4. remove the azure.activedirectory.client-id / azure.activedirectory.client-secret / azure.activedirectory.tenant-id properties
5. instead of disabling azure server side auth, an exception occurs when starting the application

**Expected behavior**
Expected behavior is that removing azure configuration properties will disable the auto configuration of AAD authentication.

This behavior was added to previous versions of the documentation here:
https://github.com/Azure/azure-sdk-for-java/pull/12645/files#diff-753fe17d65310e2021a1acac79cda656615c652a705526d439f86bd28cfba87f

Alternatively, a different configuration property could be made available to disable auto configuration of AAD authentication.

**Setup (please complete the following information):**
 - OS: Windows
 - IDE: IntelliJ
 - Library/Libraries: azure-spring-boot-starter-active-directory:3.7.0 with Spring Boot 2.4.8 or 2.5.3

**Comment by joshfree** [comment]
@chenrujun could you please follow up on this issue?

**Comment by chenrujun** [comment]
Hi, @moarychan , could you please fix this issue?
