### ISSUE TITLE
Connecting with HTTPS Proxy Cause to status 403 forbidden

### ISSUE THREAD

**Issue by ihudedi** [Azure/azure-sdk-for-java#23293]
Hi
The ProxyOptions class is use with HTTP type and not HTTPS
How can I connect to azure with proxy that is HTTPS
ProxyOptions proxyOptions = new ProxyOptions(ProxyOptions.Type.HTTP, new InetSocketAddress(proxyHost, proxyPort));

The stack trace is :
2021-08-02 13:13:52,397 DEBUG [reactor-http-epoll-3] (TransportConnector:244) -  [id:c80867f8] Connecting to [gscd1weustaoe2020crit019blob.core.sdh.cloud.aacc.dev.corp:443].
2021-08-02 13:13:52,398 DEBUG [reactor-http-epoll-3] (DefaultPooledConnectionProvider:249) -  [id:6a7c5e14, L:/22.72.14.235:59184 ! R:proxywhitesscc.gsnet.corp/22.0.20.61:8080] onStateChange(PooledConnection{channel=[id:
0x6a7c5e14, L:/22.72.14.235:59184 ! R:proxywhitesscc.gsnet.corp/22.0.20.61:8080]}, [disconnecting])
2021-08-02 13:13:52,406 DEBUG [reactor-http-epoll-3] (DefaultPooledConnectionProvider:244) -  [id:c80867f8, L:/22.72.14.235:59186 - R:proxywhitesscc.gsnet.corp/22.0.20.61:8080] Registering pool release on close event for
channel
2021-08-02 13:13:52,406 DEBUG [reactor-http-epoll-3] (PooledConnectionProvider:249) -  [id:c80867f8, L:/22.72.14.235:59186 - R:proxywhitesscc.gsnet.corp/22.0.20.61:8080] Channel connected, now: 1 active connections, 0 in
active connections and 0 pending acquire requests.
2021-08-02 13:13:52,688 WARN [reactor-http-epoll-3] (HttpClientConnect:294) -  [id:c80867f8, L:/22.72.14.235:59186 - **R:proxywhitesscc.gsnet.corp/22.0.20.61:8080] The connection observed an error
javax.net.ssl.SSLException: failure when writing TLS control frames**
        at io.netty.handler.ssl.SslHandler.setHandshakeFailureTransportFailure(SslHandler.java:1811) [netty-handler-4.1.65.Final.jar!/:4.1.65.Final]
        at io.netty.handler.ssl.SslHandler.access$600(SslHandler.java:171) [netty-handler-4.1.65.Final.jar!/:4.1.65.Final]
        at io.netty.handler.ssl.SslHandler$2.operationComplete(SslHandler.java:932) [netty-handler-4.1.65.Final.jar!/:4.1.65.Final]
        at io.netty.handler.ssl.SslHandler$2.operationComplete(SslHandler.java:927) [netty-handler-4.1.65.Final.jar!/:4.1.65.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578) [netty-common-4.1.65.Final.jar!/:4.1.65.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552) [netty-common-4.1.65.Final.jar!/:4.1.65.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491) [netty-common-4.1.65.Final.jar!/:4.1.65.Final]
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616) [netty-common-4.1.65.Final.jar!/:4.1.65.Final]
        at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609) [netty-common-4.1.65.Final.jar!/:4.1.65.Final]
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117) [netty-common-4.1.65.Final.jar!/:4.1.65.Final]
        at io.netty.channel.PendingWriteQueue.safeFail(PendingWriteQueue.java:288) [netty-transport-4.1.65.Final.jar!/:4.1.65.Final]
        at io.netty.channel.PendingWriteQueue.removeAndFailAll(PendingWriteQueue.java:186) [netty-transport-4.1.65.Final.jar!/:4.1.65.Final]
        at io.netty.handler.proxy.ProxyHandler.failPendingWrites(ProxyHandler.java:435) [netty-handler-proxy-4.1.65.Final.jar!/:4.1.65.Final]
        at io.netty.handler.proxy.ProxyHandler.failPendingWritesAndClose(ProxyHandler.java:352) [netty-handler-proxy-4.1.65.Final.jar!/:4.1.65.Final]
        at io.netty.handler.proxy.ProxyHandler.setConnectFailure(ProxyHandler.java:347) [netty-handler-proxy-4.1.65.Final.jar!/:4.1.65.Final]
        at io.netty.handler.proxy.ProxyHandler.channelRead(ProxyHandler.java:267) [netty-handler-proxy-4.1.65.Final.jar!/:4.1.65.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.65.Final.jar!/:4.1.65.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.65.Final.jar!/:4.1.65.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.65.Final.jar!/:4.1.65.Final]
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) [netty-transport-4.1.65.Final.jar!/:4.1.65.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [netty-codec-4.1.65.Final.jar!/:4.1.65.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) [netty-codec-4.1.65.Final.jar!/:4.1.65.Final]
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) [netty-transport-4.1.65.Final.jar!/:4.1.65.Final]
        at io.netty.handler.proxy.HttpProxyHandler$HttpClientCodecWrapper.channelRead(HttpProxyHandler.java:272) [netty-handler-proxy-4.1.65.Final.jar!/:4.1.65.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.65.Final.jar!/:4.1.65.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.65.Final.jar!/:4.1.65.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.65.Final.jar!/:4.1.65.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.65.Final.jar!/:4.1.65.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.65.Final.jar!/:4.1.65.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.65.Final.jar!/:4.1.65.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.65.Final.jar!/:4.1.65.Final]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) [netty-transport-native-epoll-4.1.65.Final-linux-x86_64.jar!/:4.1.65.Final]
        at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$1.run(AbstractEpollChannel.java:425) [netty-transport-native-epoll-4.1.65.Final-linux-x86_64.jar!/:4.1.65.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [netty-common-4.1.65.Final.jar!/:4.1.65.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) [netty-common-4.1.65.Final.jar!/:4.1.65.Final]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384) [netty-transport-native-epoll-4.1.65.Final-linux-x86_64.jar!/:4.1.65.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.65.Final.jar!/:4.1.65.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.65.Final.jar!/:4.1.65.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.65.Final.jar!/:4.1.65.Final]
        at java.lang.Thread.run(Thread.java:834) [?:?]
**Caused by: io.netty.handler.proxy.HttpProxyHandler$HttpProxyConnectException: http, none, proxywhitesscc.gsnet.corp/22.0.20.61:8080 => gscd1weustaoe2020crit019blob.core.sdh.cloud.aacc.dev.corp:443, status: 403** Forbidden
        at io.netty.handler.proxy.HttpProxyHandler.handleResponse(HttpProxyHandler.java:200) ~[netty-handler-proxy-4.1.65.Final.jar!/:4.1.65.Final]
        at io.netty.handler.proxy.ProxyHandler.channelRead(ProxyHandler.java:258) ~[netty-handler-proxy-4.1.65.Final.jar!/:4.1.65.Final]
        ... 24 more

Thanks,
Itay

**Comment by joshfree** [comment]
@alzimmermsft can you please follow up with @ihudedi's question on ProxyOptions?

**Comment by alzimmermsft** [comment]
Hi @ihudedi, `ProxyOptions` does support using an HTTPS proxy. `ProxyOptions.Type.HTTP` is used as an abstraction of the underlying network stacks handling for proxies, in Netty it converts to [this](https://projectreactor.io/docs/netty/release/api/reactor/netty/transport/ProxyProvider.Proxy.html#HTTP) and for OkHttp is converts to [this](https://docs.oracle.com/javase/8/docs/api/java/net/Proxy.Type.html#HTTP) (OkHttp uses Java's `Proxy.Type`). Both support the use of HTTP or HTTPS when using the type `HTTP`.

**Comment by alzimmermsft** [comment]
@ihudedi is the proxy you're using require authentication? This documentation goes over adding authentication information to the proxy which should help alleviate the 403 responses: https://docs.microsoft.com/en-us/azure/developer/java/sdk/proxying

**Comment by ihudedi** [comment]
Hi @alzimmermsft 
I am using ProxyOptions without authentication.
I can connect to azure via proxy throghu REST API and not via Java code.

**Comment by ihudedi** [comment]
Hi @alzimmermsft 
Any idea why the proxy can connect to login.microsoft.com in order to get access token
but failed to connect to azure blob storage.
When using azure cli he can connect via the proxy to the blob storage without any issues.
Is there anything in the log I can find?
We are getting Connection reset.
Thank,
Itay

**Comment by alzimmermsft** [comment]
Hi @ihudedi, I've investigated this further on my side. What I was able to find is that when using a proxy and attempting to connect to a remote that has a certificate that isn't trusted I was able to replicate both the "Connection reset" and "SSL handshake timeout" errors you've reported. Unfortunately, I haven't found a good way to get this information logged, I was able to create logs which produce what you're already seeing but nothing more clearly indicating that this could be a certificate issue.

From that, to connect to the Private Endpoint are there any additional certificates that need to be included in Java's trust store which may be included in the OS level store? This may be the reason why they're able to connect using the CLI and not in Java, due to the difference in stores being used and the certificates trusted within the stores.

**Comment by ihudedi** [comment]
Hi @alzimmermsft
So in order to solve the issue the certificate in the azure endpoint should be trusted and it's worked?
How do i do that and what is to add the certificate in os level store? Where on the machine that run the java or in the proxy machine.
Thanks,
Itay

**Comment by ihudedi** [comment]
Hi @alzimmermsft 
I checked with the customer and his certificates is trusted certificate.
Should I add his certificate to the Java's trust store and to OS level store?
When I connect to azure blob storage (public endpoint ) I don't need to perform anything.
Please elaborate more information.
In case I will send the certificates will it helo?
Thanks,
Itay

**Comment by alzimmermsft** [comment]
> Should I add his certificate to the Java's trust store and to OS level store?

From what I test I needed to add it to Java's trust store to have the request succeed.

> In case I will send the certificates will it help?

Not need to send the certificates as they may be associated to their specific Private Endpoint.

**Comment by ihudedi** [comment]
Hi @alzimmermsft
The customer add his certificate to the java trust store.
He succeded to work with his private endpoint but without proxy.when he use proxy same issue occur.cant connect to the azure endpoint while via rest api he succeeded.What else can we do to solve this issue via proxy?
Is there anything needs to be done in the proxy server?
Thanks,
Itay

**Comment by alzimmermsft** [comment]
> He succeded to work with his private endpoint but without proxy.

Just to make sure, is this an improvement from before or was connecting directly to Storage using the Java SDK always possible?

> Is there anything needs to be done in the proxy server?

The proxy server itself will also need to trust the certificate if it is self-signed.

**Comment by ihudedi** [comment]
Hi @alzimmermsft
When connecting to azure via 
Proxy it will fail.without pROx5

**Comment by alzimmermsft** [comment]
Hi @ihudedi, so when included the certificate as trusted on the proxy server the request continues to fail?

**Comment by ihudedi** [comment]
Hi @alzimmermsft
The customer included the certificate in the machine that perform call to azure endpoint in thejava trust store and it solved to connect to private endpoint.when he connect via proxy should he need to add this certificate to the java trust store in proxy server?
Thanks,
Itay

**Comment by ihudedi** [comment]
Hi @alzimmermsft 
Do you have any updates ???

**Comment by alzimmermsft** [comment]
> The customer included the certificate in the machine that perform call to azure endpoint in the java trust store and it solved to connect to private endpoint without proxy.

For verification, before adding the certificate into the trust store were they able to use the SDK to successfully make calls to storage? The reason I'm asking is so that if others run into an issue like this there will be some guidance available.



> When he connect via proxy should he also need to add this certificate to the java trust store in proxy server?

I'm not certain I'll be able answer this as it depends on what is doing the proxying. If it is a proxy application built using Java it may need the certificate in the trust store on the proxy server. This will be dependent on their configuration.



> Which java trust store he needs to insert?

If there are multiple Java applications, it'll likely need to be added to all of them as Java won't trust the SSL connection otherwise.



> If the proxy server not running with java where should I add the certificate?

That will be dependent on where the proxy server is looking to verify the certificate.



A few questions on the current state of the application being ran:

1. When attempting to make a network call through the proxy server what is the error returned? Is it still the same as before with a mix of SSL handshake timeouts and connection resets?

2. Is it possible to log the requests being made and the responses received by the proxy server to better understand what is happening there. For example, are the proxy server requests resulting in a certificate error but the proxy server is responding to the SDK with SSL handshake timeouts or resetting the connection (this is what I've seen from my testing).

**Comment by ihudedi** [comment]
Hi @alzimmermsft
When not using proxy and not store the certificate in java trust store we get error with certificate chain not resolved or found.
When use proxy he fail only in connection reset.when using okhttp this is the error and when usin netty its ssl handshake timeout.
If the proxy run on specific java shouldnt i need to add the cerificate only for this java?
I Will ask the customer for proxy server logs of requests and responses.
If I unferstood in case proxy servrer has many java procees needs to add all if one add only him.
Thanks,
Itay

**Comment by ihudedi** [comment]
Hi @alzimmermsft 
problem solved when setting noProxyHosts in okHttp
Thanks,
Itay

**Comment by alzimmermsft** [comment]
Closing as this appears to be resolved based on comments.
