### ISSUE TITLE
Blob - how to get exact remaining lease duration?

### ISSUE THREAD

**Issue by abhikt48** [Azure/azure-sdk-for-java#23294]
We are using `azure-storage-blob-12.10.2` to lease blobs.  We need to get exact lease duration, so we can wait upto remaining lease duration and apply lease again.

`BlobClient.getProperties().getLeaseDuration()` returns only lease type either  `fixed ` or `infinite` . It doesn't give us exact lease duration in seconds. e.g. 15-60s

Do we have anyway to get exact lease duration?

**Sample code** 
```
BlobClient blobClient = blobContainerClient.getBlobClient(BLOB_NAME);
AppendBlobClient appendBlobClient = blobClient.getAppendBlobClient();
BlobLeaseClient blobLeaseClient = new BlobLeaseClientBuilder().blobClient(blobClient).buildClient();
String acquireLeaseId = blobLeaseClient.acquireLease(50);
LOGGER.info("** newly getLeaseDuration '{}'  ***", blobClient.getProperties().getLeaseDuration());

```

**Setup (please complete the following information if applicable):**
OS: window
IDE : eclipse
Version of the Library used: `azure-storage-blob-12.10.2`

**Comment by rickle-msft** [comment]
Hi, @abhikt48. There is not a way to get the exact time of the lease duration. This would not be a meaningful value anyway as it would be incorrect by a variable amount depending on how long it took the response to return from the service. Instead of waiting for a lease to expire, you should consider breaking the lease outright or waiting the full 60 seconds to ensure it is lapsed.

**Comment by abhikt48** [comment]
HI @rickle-msft - Thanks for quick reply.

Our use case is - Acquire lease after expiration of current lease (fixed time lease upto 60s).

I started using custom wait duration for expiration of current lease, so I can acquire lease again. I am getting **There is already a lease present** error after expiration of lease.  Expectation - As blob is unlocked so `acquireLease(20)` should work stright after expiration of lease.

Looks like i need to wait more to acquireLease.

Please find below sample code (refer waitToLeaseBlob(..) method) and error details. Could you please suggest best solution to fix this issue.

**Sample Code**
```
public static void leaseBlockBlob() {
        LOGGER.info("leaseBlockBlob :: start");
        BlobContainerClient blobContainerClient = new BlobContainerClientBuilder().endpoint(BLOB_SAS_SERVICE).containerName(BLOB_CONTAINER_NAME).buildClient();
        BlobClient blobClient = blobContainerClient.getBlobClient(BLOB_NAME);
        BlobLeaseClient blobLeaseClient = new BlobLeaseClientBuilder().blobClient(blobClient).buildClient();
        String leaseID = blobLeaseClient.acquireLease(20);
        LOGGER.info("leaseBlockBlob :: leaseID '{}', lease duration type '{}', blobTypes '{}'", leaseID, blobClient.getProperties().getLeaseDuration(), blobClient.getProperties().getBlobType().toString());
        LOGGER.info("leaseBlockBlob :: end");
    }
    
    public static void waitToLeaseBlob(boolean waitToLeaseBlob) throws InterruptedException {
        LOGGER.info("waitToLeaseBlob :: start");
        
        BlobContainerClient blobContainerClient = new BlobContainerClientBuilder().endpoint(BLOB_SAS_SERVICE).containerName(BLOB_CONTAINER_NAME).buildClient();
        BlobClient blobClient = blobContainerClient.getBlobClient(BLOB_NAME);
        BlobLeaseClient blobLeaseClient = new BlobLeaseClientBuilder().blobClient(blobClient).buildClient();
        
        String leaseID = null;
        
        if(waitToLeaseBlob) {
            String leaseStatus = blobClient.getProperties().getLeaseStatus().toString();
            boolean isBlobLeased = LOCKED.equalsIgnoreCase(leaseStatus);
            LOGGER.info("Before isBlobLeased '{}'", isBlobLeased);
            while(isBlobLeased && blobClient.getProperties().getLeaseDuration().equals(LeaseDurationType.FIXED)) {
                Thread.sleep(1000);
                leaseStatus = blobClient.getProperties().getLeaseStatus().toString();
                isBlobLeased = leaseStatus.equalsIgnoreCase(LOCKED);
                LOGGER.info("After waiting of 1s- isBlobLeased '{}', leaseStatus '{}'", isBlobLeased, leaseStatus);
            }
            
            leaseID = blobLeaseClient.acquireLease(30);
        }else {
            leaseID = blobLeaseClient.acquireLease(30);
        }
        
        LOGGER.info("waitToLeaseBlob :: leaseID '{}', lease duration type '{}', blobTypes '{}'", leaseID, blobClient.getProperties().getLeaseDuration(), blobClient.getProperties().getBlobType().toString());
        LOGGER.info("waitToLeaseBlob :: end");
    }
    
    public static void main(String[] args) throws InterruptedException {
        leaseBlockBlob();
        waitToLeaseBlob(true);
    }
```

**Error Stacktrace**
```
INFO  2021-08-02 17:24:16,387 [main] com.test.blob.BlobAppendOperation: leaseBlockBlob :: start
INFO  2021-08-02 17:24:20,189 [main] com.test.blob.BlobAppendOperation: leaseBlockBlob :: leaseID '****4d10a6b1579', lease duration type 'fixed', blobTypes 'BlockBlob'
INFO  2021-08-02 17:24:20,189 [main] com.test.blob.BlobAppendOperation: leaseBlockBlob :: end
INFO  2021-08-02 17:24:20,189 [main] com.test.blob.BlobAppendOperation: waitToLeaseBlob :: start
INFO  2021-08-02 17:24:20,222 [main] com.test.blob.BlobAppendOperation: Before isBlobLeased 'true'
INFO  2021-08-02 17:24:21,245 [main] com.test.blob.BlobAppendOperation: After waiting of 1s- isBlobLeased 'true', leaseStatus 'locked'
...
INFO  2021-08-02 17:24:38,845 [main] com.test.blob.BlobAppendOperation: After waiting of 1s- isBlobLeased 'true', leaseStatus 'locked'
INFO  2021-08-02 17:24:39,880 [main] com.test.blob.BlobAppendOperation: After waiting of 1s- isBlobLeased 'false', leaseStatus 'unlocked'
Exception in thread "main" com.azure.storage.blob.models.BlobStorageException: Status code 409, "﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>LeaseAlreadyPresent</Code><Message>There is already a lease present.
RequestId:***a-87f299000000
Time:2021-08-02T16:24:39.8949388Z</Message></Error>"
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.azure.core.http.rest.RestProxy.instantiateUnexpectedException(RestProxy.java:337)
	at com.azure.core.http.rest.RestProxy.lambda$ensureExpectedStatus$5(RestProxy.java:378)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:118)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1782)
	at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.signalCached(MonoCacheTime.java:320)
	at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.onNext(MonoCacheTime.java:337)
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2344)
	at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.onSubscribe(MonoCacheTime.java:276)
	at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:191)
	at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at reactor.core.publisher.MonoCacheTime.subscribeOrReturn(MonoCacheTime.java:132)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:150)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:123)
	at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:112)
	at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:213)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:123)
	at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:178)
	at reactor.core.publisher.FluxContextStart$ContextStartSubscriber.onNext(FluxContextStart.java:96)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1782)
	at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:121)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:252)
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:136)
	at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:374)
	at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:373)
	at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:429)
	at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:655)
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:96)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1526)
	at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1287)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1324)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
		at reactor.core.publisher.Mono.block(Mono.java:1685)
		at com.azure.storage.common.implementation.StorageImplUtils.blockWithOptionalTimeout(StorageImplUtils.java:131)
		at com.azure.storage.blob.specialized.BlobLeaseClient.acquireLeaseWithResponse(BlobLeaseClient.java:127)
		at com.azure.storage.blob.specialized.BlobLeaseClient.acquireLeaseWithResponse(BlobLeaseClient.java:106)
		at com.azure.storage.blob.specialized.BlobLeaseClient.acquireLease(BlobLeaseClient.java:84)
		at com.test.blob.LeaseBlobs.waitToLeaseBlob(LeaseBlobs.java:77)
		at com.test.blob.LeaseBlobs.main(LeaseBlobs.java:92)

```

**Comment by rickle-msft** [comment]
From the lease docs: 
If a lease expires rather than being explicitly released, a client may need to wait up to one minute before a new lease can be acquired for the blob. However, the client can renew the lease with their lease ID immediately if the blob has not been modified.

That is why you are seeing the lease status as unlocked but still getting this error. If you switch to reading the lease state, I suspect you would find that the lease state is expired, which carries this extra condition.

A question about your application. Is it 
a) Process A acquires lease. Process B also wants a lease and waits for lease to expire to acquire its own lease?
or
b) Process A acquires lease. Process A wants to extend its lease and is waiting for it to expire to acquire a new one?

**Comment by abhikt48** [comment]
@rickle-msft  - Thanks for quick reply. LeaseState worked for me to check lease status.

We have below requirement - 
a) Process A acquires lease. Process B also wants a lease and waits for lease to expire to acquire its own lease..
