### ISSUE TITLE
tried multiple options still facing error : com.fasterxml.jackson.dataformat.xml.XmlMapper.coercionConfigDefaults()Lcom/fasterxml/jackson/databind/cfg/MutableCoercionConfig;

### ISSUE THREAD

**Issue by saiprasadcrown** [Azure/azure-sdk-for-java#23609]
I'm new to the java library, I learnt that azure Java SDK can be used in the scala environment, 
So I have tried using the azure identity library in the databricks environment 

DBR Version 7.3 LTS 
scala 2.12 
maven coordinate com.azure:azure-identity:1.3.5

pls help me resolve the error, 

here is the code : 

import com.azure.identity._;
import com.azure.identity.DefaultAzureCredentialBuilder;

// https://docs.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-directory-file-acl-java
val clientID = dbutils.secrets.get(scope=****",key="****")
val ClientSecret = dbutils.secrets.get(scope="****",key="****")
val tenantID = dbutils.secrets.get(scope="****",key="****")
val endpoint = "****" 

// val endpoint = "https://" + accountName + ".dfs.core.windows.net";
    
val clientSecretCredential:ClientSecretCredential = new ClientSecretCredentialBuilder()
     .tenantId(tenantID)
     .clientId(clientID)
     .clientSecret(ClientSecret)
     .build();

here is the error i face
**java.lang.NoSuchMethodError: com.fasterxml.jackson.dataformat.xml.XmlMapper.coercionConfigDefaults()Lcom/fasterxml/jackson/databind/cfg/MutableCoercionConfig**

at com.fasterxml.jackson.dataformat.xml.XmlMapper.<init>(XmlMapper.java:176)
	at com.fasterxml.jackson.dataformat.xml.XmlMapper.<init>(XmlMapper.java:145)
	at com.fasterxml.jackson.dataformat.xml.XmlMapper.<init>(XmlMapper.java:127)
	at com.fasterxml.jackson.dataformat.xml.XmlMapper.builder(XmlMapper.java:218)
	at com.azure.core.util.serializer.JacksonAdapter.<init>(JacksonAdapter.java:137)
	at com.azure.core.util.serializer.JacksonAdapter.createDefaultSerializerAdapter(JacksonAdapter.java:189)
	at com.azure.identity.implementation.IdentityClient.<clinit>(IdentityClient.java:96)
	at com.azure.identity.implementation.IdentityClientBuilder.build(IdentityClientBuilder.java:113)
	at com.azure.identity.ClientSecretCredential.<init>(ClientSecretCredential.java:50)
	at com.azure.identity.ClientSecretCredentialBuilder.build(ClientSecretCredentialBuilder.java:76)
	at linea34e0846b16045d09ff78af8b346393c25.$read$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-626790621540495:18)
	at linea34e0846b16045d09ff78af8b346393c25.$read$$iw$$iw$$iw$$iw$$iw.<init>(command-626790621540495:68)
	at linea34e0846b16045d09ff78af8b346393c25.$read$$iw$$iw$$iw$$iw.<init>(command-626790621540495:70)
	at linea34e0846b16045d09ff78af8b346393c25.$read$$iw$$iw$$iw.<init>(command-626790621540495:72)
	at linea34e0846b16045d09ff78af8b346393c25.$read$$iw$$iw.<init>(command-626790621540495:74)
	at linea34e0846b16045d09ff78af8b346393c25.$read$$iw.<init>(command-626790621540495:76)
	at linea34e0846b16045d09ff78af8b346393c25.$read.<init>(command-626790621540495:78)
	at linea34e0846b16045d09ff78af8b346393c25.$read$.<init>(command-626790621540495:82)
	at linea34e0846b16045d09ff78af8b346393c25.$read$.<clinit>(command-626790621540495)
	at linea34e0846b16045d09ff78af8b346393c25.$eval$.$print$lzycompute(<notebook>:7)
	at linea34e0846b16045d09ff78af8b346393c25.$eval$.$print(<notebook>:6)
	at linea34e0846b16045d09ff78af8b346393c25.$eval.$print(<notebook>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:745)
	at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:1021)
	at scala.tools.nsc.interpreter.IMain.$anonfun$interpret$1(IMain.scala:574)
	at scala.reflect.internal.util.ScalaClassLoader.asContext(ScalaClassLoader.scala:41)
	at scala.reflect.internal.util.ScalaClassLoader.asContext$(ScalaClassLoader.scala:37)
	at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:41)
	at scala.tools.nsc.interpreter.IMain.loadAndRunReq$1(IMain.scala:573)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:600)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:570)
	at com.databricks.backend.daemon.driver.DriverILoop.execute(DriverILoop.scala:219)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal.$anonfun$repl$1(ScalaDriverLocal.scala:204)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.databricks.backend.daemon.driver.DriverLocal$TrapExitInternal$.trapExit(DriverLocal.scala:789)
	at com.databricks.backend.daemon.driver.DriverLocal$TrapExit$.apply(DriverLocal.scala:742)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal.repl(ScalaDriverLocal.scala:204)
	at com.databricks.backend.daemon.driver.DriverLocal.$anonfun$execute$10(DriverLocal.scala:431)
	at com.databricks.logging.UsageLogging.$anonfun$withAttributionContext$1(UsageLogging.scala:239)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at com.databricks.logging.UsageLogging.withAttributionContext(UsageLogging.scala:234)
	at com.databricks.logging.UsageLogging.withAttributionContext$(UsageLogging.scala:231)
	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionContext(DriverLocal.scala:48)
	at com.databricks.logging.UsageLogging.withAttributionTags(UsageLogging.scala:276)
	at com.databricks.logging.UsageLogging.withAttributionTags$(UsageLogging.scala:269)
	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionTags(DriverLocal.scala:48)
	at com.databricks.backend.daemon.driver.DriverLocal.execute(DriverLocal.scala:408)
	at com.databricks.backend.daemon.driver.DriverWrapper.$anonfun$tryExecutingCommand$1(DriverWrapper.scala:653)
	at scala.util.Try$.apply(Try.scala:213)
	at com.databricks.backend.daemon.driver.DriverWrapper.tryExecutingCommand(DriverWrapper.scala:645)
	at com.databricks.backend.daemon.driver.DriverWrapper.getCommandOutputAndError(DriverWrapper.scala:486)
	at com.databricks.backend.daemon.driver.DriverWrapper.executeCommand(DriverWrapper.scala:598)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInnerLoop(DriverWrapper.scala:391)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInner(DriverWrapper.scala:337)
	at com.databricks.backend.daemon.driver.DriverWrapper.run(DriverWrapper.scala:219)
	at java.lang.Thread.run(Thread.java:748)

**Comment by alzimmermsft** [comment]
Hi @saiprasadcrown, thank you for filing this issue. Have you tried using [this guide](https://github.com/Azure/azure-sdk-for-java/wiki/Frequently-Asked-Questions#how-to-manage-dependencies-of-my-application-running-on-azure-data-bricks) on resolving Jackson dependency conflict when using DataBricks?

**Comment by saiprasadcrown** [comment]
@alzimmermsft thank you for the feedback, I understand the error, ill try it out and get back to you
