### ISSUE TITLE
[BUG][Identity]Cannot save token on mac due to error: Could not initialize class com.microsoft.aad.msal4jextensions.persistence.mac.ISecurityLibrary

### ISSUE THREAD

**Issue by andxu** [Azure/azure-sdk-for-java#23622]
**Describe the bug**
An azure toolkit intellj plugin user reports this error when he is trying to sign-in in azure toolkit intellj.

***Exception or Stack Trace***
2021-05-19 18:39:36,715 [20470713]   INFO -                         STDERR - Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.microsoft.aad.msal4jextensions.persistence.mac.ISecurityLibrary 
2021-05-19 18:39:36,715 [20470713]   INFO -                         STDERR - 	at com.microsoft.aad.msal4jextensions.persistence.mac.KeyChainAccessor.read(KeyChainAccessor.java:49) 
2021-05-19 18:39:36,715 [20470713]   INFO -                         STDERR - 	at com.microsoft.aad.msal4jextensions.PersistenceTokenCacheAccessAspect.beforeCacheAccess(PersistenceTokenCacheAccessAspect.java:125) 
2021-05-19 18:39:36,715 [20470713]   INFO -                         STDERR - 	at com.azure.identity.implementation.PersistentTokenCacheImpl.beforeCacheAccess(PersistentTokenCacheImpl.java:68) 
2021-05-19 18:39:36,715 [20470713]   INFO -                         STDERR - 	at com.microsoft.aad.msal4j.TokenCache$CacheAspect.<init>(TokenCache.java:165) 
2021-05-19 18:39:36,715 [20470713]   INFO -                         STDERR - 	at com.microsoft.aad.msal4j.TokenCache.saveTokens(TokenCache.java:182) 
2021-05-19 18:39:36,715 [20470713]   INFO -                         STDERR - 	at com.microsoft.aad.msal4j.AbstractClientApplicationBase.acquireTokenCommon(AbstractClientApplicationBase.java:123) 
2021-05-19 18:39:36,715 [20470713]   INFO -                         STDERR - 	at com.microsoft.aad.msal4j.AcquireTokenByAuthorizationGrantSupplier.execute(AcquireTokenByAuthorizationGrantSupplier.java:63) 
2021-05-19 18:39:36,715 [20470713]   INFO -                         STDERR - 	at com.microsoft.aad.msal4j.AcquireTokenByInteractiveFlowSupplier.acquireTokenWithAuthorizationCode(AcquireTokenByInteractiveFlowSupplier.java:166) 
2021-05-19 18:39:36,715 [20470713]   INFO -                         STDERR - 	at com.microsoft.aad.msal4j.AcquireTokenByInteractiveFlowSupplier.execute(AcquireTokenByInteractiveFlowSupplier.java:39) 
2021-05-19 18:39:36,715 [20470713]   INFO -                         STDERR - 	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:59) 
2021-05-19 18:39:36,715 [20470713]   INFO -                         STDERR - 	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:17) 

**To Reproduce**
I cannot reproduce.

The original issue is:
https://github.com/microsoft/azure-tools-for-java/issues/5206

**Comment by joshfree** [comment]
Adding more details from the original poster, @MySelfSivaKrishna:

```
Setup
IntelliJ build version: 2021.1.1 IC-211.7142.45
OS: Mac OS X
JDK: JetBrains s.r.o. 11.0.10
Plugin version: 3.52.0-2021.1

```


@myselfsivakrishna, could you take a look at https://github.com/Azure/azure-sdk-for-java/wiki/Frequently-Asked-Questions#dependency-conflict and share the dependency tree from running `mvn dependency:tree -Dverbose`?

**Comment by g2vinay** [comment]
Closing this issue, due to no activity/response, 
We can always reopen it, if you still run into this issue.

**Comment by andxu** [comment]
The issue still exists on Mac M1, while we enable persistence:
DeviceCodeCredentialBuilder builder = new DeviceCodeCredentialBuilder();
builder.tokenCachePersistenceOptions(new TokenCachePersistenceOptions().setName(TOOLKIT_TOKEN_CACHE_NAME));

It will encounter the error , see the user reported issue: https://github.com/microsoft/azure-tools-for-java/issues/5246, 

Repo step:
create a simple java project(maven or gradle) and add this dependency : https://mvnrepository.com/artifact/com.microsoft.azure/msal4j-persistence-extension/1.1.0

```java
package com.example.sample;

import com.microsoft.aad.msal4jextensions.persistence.mac.ISecurityLibrary;

public class App {
    public static void main(String[] args) {
        ISecurityLibrary.library.CFRelease(null);
    }
}
```

The ISecurityLibrary will report error of `Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.microsoft.aad.msal4jextensions.persistence.mac.ISecurityLibrary`

very similar to https://github.com/Azure/azure-sdk-for-java/issues/11649. Seems it is caused by  this repo: `microsoft-authentication-extensions-for-java`*(https://github.com/AzureAD/microsoft-authentication-extensions-for-java), but it seems there are nobody maintaining this repo, why azure-identity uses this library to persistent access tokens?

**Comment by Flanker32** [comment]
@joshfree @g2vinay Thanks for your help, but this issue still exists on Mac M1, and we found the issue occurs more than 3k times in last month according to our telemetry, so could you please help re-open the issue? Many thanks!
