### ISSUE TITLE
[BUG] Out of memory issues when sending messages to Event Hub

### ISSUE THREAD

**Issue by master-mck** [Azure/azure-sdk-for-java#23848]
**Describe the bug**
We run two Kubernetes cluster (INT & PROD) where we have a service which sends on four Event Hubs. On INT we get  a OutOfMemory every few weeks. Our analyzes of the heap dump showed us, that two of the four com.azure.messaging.eventhubs.implementation.EventHubConnectionProcessor seem to "collect" Nodes in their ConcurrentLinkedDeque. They send the messages to the Event Hubs but do not remove the Nodes from the deque and release the memory. 

Those Node instances contain org.apache.qpid.proton.engine.impl.TransportImpl subscriber for one EventHubConnectionProcessor and datadog.trace.instrumentation.reactor.core.TracingSubscriber for the other. But it seems those subscribers aren't the problem since the two other EventHubConnectionProcessor instances have the same subscriber types and there we have no problems with them.

Remarkable is the fact, that the two EventHubConnectionProcessor, which make problems, have the lowest data throughput. The other two EventHubConnectionProcessor's on INT and all four EventHubConnectionProcessor's on PROD cluster have much more data to handle but work fine. 

**Stack Trace**
```
java.lang.OutOfMemoryError: Java heap space
	at com.azure.core.amqp.implementation.ReactorSender.lambda$send$10(ReactorSender.java:241)
	at com.azure.core.amqp.implementation.ReactorSender$$Lambda$1609/328835047.apply(Unknown Source)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:125)
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2397)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onSubscribe(MonoFlatMap.java:110)
	at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:54)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157)
	at datadog.trace.instrumentation.reactor.core.TracingSubscriber.lambda$onNext$0(TracingSubscriber.java:38)
	at datadog.trace.instrumentation.reactor.core.TracingSubscriber$$Lambda$602/1872410525.run(Unknown Source)
	at datadog.trace.instrumentation.reactor.core.TracingSubscriber.withActiveSpan(TracingSubscriber.java:60)
	at datadog.trace.instrumentation.reactor.core.TracingSubscriber.onNext(TracingSubscriber.java:38)
	at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onNext(FluxHide.java:136)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1815)
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:249)
	at datadog.trace.instrumentation.reactor.core.TracingSubscriber.lambda$onNext$0(TracingSubscriber.java:38)
	at datadog.trace.instrumentation.reactor.core.TracingSubscriber$$Lambda$602/1872410525.run(Unknown Source)
	at datadog.trace.instrumentation.reactor.core.TracingSubscriber.withActiveSpan(TracingSubscriber.java:60)
	at datadog.trace.instrumentation.reactor.core.TracingSubscriber.onNext(TracingSubscriber.java:38)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1815)
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:249)
	at datadog.trace.instrumentation.reactor.core.TracingSubscriber.lambda$onNext$0(TracingSubscriber.java:38)
	at datadog.trace.instrumentation.reactor.core.TracingSubscriber$$Lambda$602/1872410525.run(Unknown Source)
	at datadog.trace.instrumentation.reactor.core.TracingSubscriber.withActiveSpan(TracingSubscriber.java:60)
	at datadog.trace.instrumentation.reactor.core.TracingSubscriber.onNext(TracingSubscriber.java:38)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:120)
	at datadog.trace.instrumentation.reactor.core.TracingSubscriber.lambda$onNext$0(TracingSubscriber.java:38)
	at datadog.trace.instrumentation.reactor.core.TracingSubscriber$$Lambda$602/1872410525.run(Unknown Source)
	at datadog.trace.instrumentation.reactor.core.TracingSubscriber.withActiveSpan(TracingSubscriber.java:60)
	at datadog.trace.instrumentation.reactor.core.TracingSubscriber.onNext(TracingSubscriber.java:38)
	at reactor.core.publisher.FluxFirstWithSignal$FirstEmittingSubscriber.onNext(FluxFirstWithSignal.java:329)
	at datadog.trace.instrumentation.reactor.core.TracingSubscriber.lambda$onNext$0(TracingSubscriber.java:38)
```

**Code Snippet**
For working with the Event Hubs we use com.azure.messaging.eventhubs.EventHubProducerAsyncClient.

We use it like this:
```
eventHubClient.send(data).toFuture().whenComplete((msg, ex) -> {
            if (ex != null) {
                log.error("Error while sending data", ex);
                messageCounterRegistry.increaseSentFailed(ehClass, data.size());
                throw new CompletionException("Error occurred sending batch of event class: " + ehClass, ex);
            } else {
                messageCounterRegistry.increaseSentMessages(ehClass, data.size());
                MessageDeduplication.add(trackingIds);
            }
        });
```
We cannot see any failed sendings in our counter registry or logs.

**To Reproduce**
We cannot reproduce the OOM manually but every 6 weeks (+/-) it happens.

**Expected behavior**
The two mentioned EventHubConnectionProcessor instances should release the memory by removing the subscribers from their ConcurrentLinkedDeque after sending the messages to the Event Hubs.

**Setup (please complete the following information):**
 - OS: Ubuntu 20.04
 - Library/Libraries: 
   com.azure:azure-identity:1.2.5
   com.azure:azure-messaging-eventhubs:5.7.0
 - Java version: 1.8.0_292 Zulu JDK
 - Environment: Container on Kubernetes
 - Frameworks: Spring Boot 2.3.9.RELEASE

Sorry, that I can't be more specific, but this is all I see from my point of view.

**Comment by joshfree** [comment]
> OutOfMemoryError
> We cannot reproduce the OOM manually but every 6 weeks (+/-) it happens.


@anuchandy could you please follow up with @master-mck on this issue?

**Comment by conniey** [comment]
Hm... We did fix an OOM issue in 5.10.0 where we were not closing our ReactorExecutors and Send/Receive links. [CHANGELOG](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/core/azure-core-amqp/CHANGELOG.md#231-2021-08-19) for that release.

**Comment by master-mck** [comment]
@conniey 
Thanks for the information. I updated the version to 5.10.0. We will see, if this fixes our OOM problem. But of course this will take some weeks until the memory leak could potentially occur. I will give feedback then.

**Comment by ramya-rao-a** [comment]
Thanks @master-mck 

We will close this issue for now. Please feel free to open a new one if you see issues after the upgrade
