### ISSUE TITLE
[BUG] SSL Exception with spring-data-cosmosdb SDK version “3.6.0” 

### ISSUE THREAD

**Issue by poojadubey0809** [Azure/azure-sdk-for-java#23939]
We have few microservice in JAVA Spring boot deployed on AKS and we are using spring-data-cosmosdb SDK version “2.3.0” to save data in cosmosDB asynchronously. Below are the dependencies that we are using in pom.xml.

    <parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.4.3</version>
	</parent>
	
	<dependency>
			<groupId>com.azure</groupId>
			<artifactId>azure-spring-data-cosmos</artifactId>
			<version>3.6.0</version>
	</dependency>
	
Gives below noise:
javax.net.ssl.SSLException: SSLEngine closed already

SSLEngine closed already comes after one hour of initial request made to cosmos db

If changed cosmosDB IdleEndPointTimeout to 10 mins, then  this exception is occurs after 10 mins of initial request made to cosmos db

```
io.netty.handler.ssl.SslClosedEngineException: SSLEngine closed already
	at io.netty.handler.ssl.SslHandler.wrap(SslHandler.java:854)
	at io.netty.handler.ssl.SslHandler.wrapAndFlush(SslHandler.java:811)
	at io.netty.handler.ssl.SslHandler.flush(SslHandler.java:792)
	at io.netty.handler.ssl.SslHandler.flush(SslHandler.java:1953)
	at io.netty.handler.ssl.SslHandler.closeOutbound0(SslHandler.java:668)
	at io.netty.handler.ssl.SslHandler.closeOutbound(SslHandler.java:652)
	at io.netty.handler.ssl.SslHandler.closeOutbound(SslHandler.java:640)
	at com.azure.cosmos.implementation.directconnectivity.rntbd.RntbdRequestManager.close(RntbdRequestManager.java:400)
	at io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:622)
	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:606)
	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:472)
	at io.netty.channel.DefaultChannelPipeline.close(DefaultChannelPipeline.java:957)
	at io.netty.channel.AbstractChannel.close(AbstractChannel.java:232)
	at com.azure.cosmos.implementation.directconnectivity.rntbd.RntbdClientChannelPool.closeChannel(RntbdClientChannelPool.java:731)
	at com.azure.cosmos.implementation.directconnectivity.rntbd.RntbdClientChannelPool.safeCloseChannel(RntbdClientChannelPool.java:1017)
	at com.azure.cosmos.implementation.directconnectivity.rntbd.RntbdClientChannelPool.lambda$notifyChannelConnect$18(RntbdClientChannelPool.java:1056)
	at io.opentelemetry.javaagent.instrumentation.netty.v4_1.WrappedFutureListener.operationComplete(WrappedFutureListener.java:25)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
	at io.netty.channel.AbstractChannel$CloseFuture.setClosed(AbstractChannel.java:1174)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.doClose0(AbstractChannel.java:761)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:737)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:608)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.closeOnRead(AbstractNioByteChannel.java:105)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:174)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
```
	
similar to https://github.com/Azure/azure-sdk-for-java/issues/18656

**Comment by saragluna** [comment]
@mbhaskar - can you please help on this issue ?

**Comment by poojadubey0809** [comment]
On updating version as below

```
[<parent>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-parent</artifactId>
	<version>2.4.3</version>
</parent>

<dependency>
		<groupId>com.azure</groupId>
		<artifactId>azure-spring-data-cosmos</artifactId>
		<version>3.10.0</version>
</dependency>]([url](url))
```

now error is as below  

`io.netty.channel.StacklessClosedChannelException
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source)`


Same by default error occurs on 1 hour of initial DB call
and on updating as (**IdleEndPointTimeout** of _DirectConnectionConfig_ to x minutes error will comes occur after x minutes of DB Call)


Please check this, As these errors are huge in numbers (> 1k per hour) harmless but This huge number of logs create noise during log analysis.

**Comment by saksham-boot** [comment]
I am facing this similar issue on on SDK version “2.3.0” to save data in cosmosDB asynchronously , please provide your comments.

**Comment by kushagraThapar** [comment]
This issue has been fixed in the latest version of the spring-data-cosmos SDK, please update to the latest and feel free to re-open the issue in case the error still persists.
