### ISSUE TITLE
[BUG] Custom OFFSET LIMIT query with Pageable throws IndexOutOfBoundsException

### ISSUE THREAD

**Issue by zhoujia1974** [Azure/azure-sdk-for-java#24013]
**Describe the bug**
I have a project using azure spring data cosmos. I have a custom query method using OFFSET LIMIT together with Pageable.

`@Query( "SELECT * FROM c WHERE c.partitionKey = @partitionKey ORDER BY c.key OFFSET @offset LIMIT @limit") Page<SomeEntity> find( @Param("partitionKey") String partitionKey, @Param("offset") int offset, @Param("limit") int limit, Pageable pageable);`

I found the query doesn't work correctly. My test case contains two documents that matching the partition key. 
Test 1:
offset = 0, limit = 1, pageable has page = 0 and size = 1

`Page<SomeEntity> page = repository.find(partitionKey, 0, 1, new CosmosPageRequest(0, 1, null));`
`while (page.hasNext()) { page = repository.find(partitionKey, 0, 1, page.nextPageable());`

For this test , the first find call returns a page with one document. This is correct. Then find is called one more time since page.hasNext() returns true and the second page returns contain the same document from the first page. This is not as expected since there should be only 1 page with limit set to 1.

Test 2:
offset = 1, limit = 1, pageable has page = 0 and size = 1

`Page<SomeEntity> page = repository.find(partitionKey, 1, 1, new CosmosPageRequest(0, 1, null));`
`while (page.hasNext()) { page = repository.find(partitionKey, 1, 1, page.nextPageable());`

For this test , the first find call throws the following exception. I would expect this should return one page with one document.

> Caused by: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[na:na]
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[na:na]
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248) ~[na:na]
        at java.base/java.util.Objects.checkIndex(Objects.java:372) ~[na:na]
        at java.base/java.util.ArrayList.get(ArrayList.java:458) ~[na:na]
        at com.azure.spring.data.cosmos.core.CosmosTemplate.lambda$getCountValue$26(CosmosTemplate.java:826) ~[azure-spring-data-cosmos-3.8.0.jar:na]
        at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:106) ~[reactor-core-3.4.8.jar:3.4.8]
        at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:82) ~[reactor-core-3.4.8.jar:3.4.8]
        at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:200) ~[reactor-core-3.4.8.jar:3.4.8]
        at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79) ~[reactor-core-3.4.8.jar:3.4.8]
        at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runAsync(FluxPublishOn.java:440) ~[reactor-core-3.4.8.jar:3.4.8]
        at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:527) ~[reactor-core-3.4.8.jar:3.4.8]
        at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84) ~[reactor-core-3.4.8.jar:3.4.8]
        at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37) ~[reactor-core-3.4.8.jar:3.4.8]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        ... 1 common frames omitted
        Suppressed: java.lang.Exception: #block terminated with an error
                at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99) ~[reactor-core-3.4.8.jar:3.4.8]
                at reactor.core.publisher.Mono.block(Mono.java:1704) ~[reactor-core-3.4.8.jar:3.4.8]
                at com.azure.spring.data.cosmos.core.CosmosTemplate.getCountValue(CosmosTemplate.java:827) ~[azure-spring-data-cosmos-3.8.0.jar:na]
                at com.azure.spring.data.cosmos.core.CosmosTemplate.paginationQuery(CosmosTemplate.java:677) ~[azure-spring-data-cosmos-3.8.0.jar:na]
                at com.azure.spring.data.cosmos.core.CosmosTemplate.runPaginationQuery(CosmosTemplate.java:657) ~[azure-spring-data-cosmos-3.8.0.jar:na]
                at com.azure.spring.data.cosmos.repository.support.StringBasedCosmosQuery.execute(StringBasedCosmosQuery.java:60) ~[azure-spring-data-cosmos-3.8.0.jar:na]
                at org.springframework.data.repository.core.support.RepositoryMethodInvoker.doInvoke(RepositoryMethodInvoker.java:137) ~[spring-data-commons-2.5.3.jar:2.5.3]
                at org.springframework.data.repository.core.support.RepositoryMethodInvoker.invoke(RepositoryMethodInvoker.java:121) ~[spring-data-commons-2.5.3.jar:2.5.3]
                at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:159) ~[spring-data-commons-2.5.3.jar:2.5.3]
                at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:138) ~[spring-data-commons-2.5.3.jar:2.5.3]
                at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.9.jar:5.3.9]
                at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97) ~[spring-aop-5.3.9.jar:5.3.9]
                at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.9.jar:5.3.9]
                at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215) ~[spring-aop-5.3.9.jar:5.3.9]

***Exception or Stack Trace***

**To Reproduce**

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**
I expected the paging query should not throw exception and should return correct number of documents as specified in limit.

**Screenshots**

**Setup (please complete the following information):**
 - OS: Windows 10
 - IDE: Eclipse
 - Library/Libraries: com.azure.spring:azure-spring-boot-starter-cosmos:3.6.0
 - Java version: java 11 
 - App Server/Environment: Tomcat
 - Frameworks: Spring Boot

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please provide
- dependency tree (`mvn dependency:tree`)
  
**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ x] Bug Description Added
- [ x] Repro Steps Added
- [ x] Setup information Added

**Comment by saragluna** [comment]
@mbhaskar - can you please help on this issue ?

**Comment by Blackbaud-MikeLueders** [comment]
Regarding the first test case, this is working as expected.  The first thing to understand is that cosmos is not sql - it has a sql api but that is only a familiar facade - it is not sql under the covers.  It CAN do things like offset and limit but it does them very poorly (as in, if you set an offset of 10000, the server will iterate over 10000 records and then return your result).  

What it is really optimized for is something like infinite scroll.  When you execute a query against cosmos, it will actually return a continuation token which can be used to very efficient fetch the next set of results.  Under the covers, that is how the library functions - the method that accepts page.nextPageable() is only looking for the continuation token as a hint of where to pick up the query.  Now, in this particular case, there is no continuation token - because you've specified this in the query (you can observe this in debugger, if you inspect the returned page object, the "requestContinuation" variable of the next pageable will be null).  That is, when you specify a query with offset of 0 and limit of 1, you've told cosmos that you only want a single result.  So the continuation token will be null - you will never get more than one result from that query because the query itself is limited to a single result.  When you issue the query again, you are specifying an offset of 0, a limit of 1, and a null continuation token.  So you get the same result. 

Regarding the second test case, this is interesting and someone from MS will probably need to chime in.  It looks like count and offset have an interesting interaction.  If you go into the azure portal and execute the ad-hoc query 
`select value count(1)  from c`
You'll get the expected response - the number of items in the collection.  However, if you execute this ad-hoc query
`select value count(1)  from c offset 1`
You'll get a response of `0 - 0`

I have no idea why - i would have expected you'd get the number of items in the collection - 1.  The library should probably handle this better than an index out of bounds exception but cosmos itself is not returning results for this query for whatever reason (hopefully someone from MS can chime in and explain).

All that said, you can do what you want, you'll just have to do it manually and ignore the pageable and keep track of the offset + page size yourself...
`repository.find(partitionKey, 0, 1);`
`repository.find(partitionKey, 1, 2);`
`repository.find(partitionKey, 2, 3);`

I should point out though that the larger the offset, the longer the query will take and the more expensive it will be.

**Comment by zhoujia1974** [comment]
@Blackbaud-MikeLueders Thanks for the reply. Regarding test case 1, based on what your explained, wouldn't the code will cause an infinite loop if page.nextPageable always return a new page with offset 0, limit 1, and null continuation token because it is exactly like the initial find call. What makes the first returned page that page.hasNext return true and the next page returned get page.hasNext returns false?

**Comment by Blackbaud-MikeLueders** [comment]
It's because of two things.  

First, the count operation seems to behave differently than a straight query, in that it seems to ignore limit.  You can see this for yourself by going to the cosmos data explorer and populating a collection with 3 or more elements, then executing the following query...
`SELECT * FROM c offset 0 limit 2`
This should return 2 elements.  Though you can't see it in the console, if you were to execute this query via code, you could inspect the return headers (or the returned Page) and see there is no continuation token.
Now execute the this query...
`SELECT count(1) FROM c offset 0 limit 2`
And you'll get a value equal to the total elements in the collection, not 2 as you would expect if the query were truly limited.  So, in my mind there's a disconnect between a straight query and a count query where limit is concerned.  I would expect that either limit should affect count, or that the query should return a continuation token when limit is employed and there are additional results.  

Second, https://github.com/Azure/azure-sdk-for-java/blob/3f31d68eed6fbe11516ca3afe3955c8840a6e974/sdk/cosmos/azure-spring-data-cosmos/src/main/java/com/azure/spring/data/cosmos/core/query/CosmosPageImpl.java#L49 
The implementation of the returned page does not look at the continuation token, only the offset/current result size/total count comparison. 


On further investigation, I discovered something interesting... 
`SELECT * FROM c offset 0 limit 2` returns no continuation token
`SELECT * FROM c offset 2 limit 4` DOES return a continuation token. 
I can't explain why.  So it's possible my assumptions about limit and query are wrong - I am basing them off of observations rather than the documentation because I can't find any documentation detailing this.  Perhaps this is a bug in cosmos?  Or maybe in the client?

**Comment by trande4884** [comment]
@zhoujia1974 the root of your problem is a misunderstanding of how the pageable is used. Pageable will be used to apply the offset and limit, where limit will be equal to the page size. By adding offset and limit to your annotated query and passing in the pageable object I wouldn't expect things to work correctly, more than likely offset and limit are being applied twice. I would recommend removing offset and limit from your query definition and just passing in the pageable with offset and page size passed in as needed, or if you want to keep offset and limit in your definition you should remove the pageable parameter.
