### ISSUE TITLE
ClassCastException when sending Spring message to Service Bus using Spring Cloud Stream

### ISSUE THREAD

**Issue by ahmedmq** [Azure/azure-sdk-for-java#24114]
Using Spring Cloud Stream we have written a `Function<Message<String>,Message<String>>` to consume and send a message to a Service Bus topic. The message is successfully consume but when sending it to a topic it reports a `ClassCastException` show below

```
2021-09-14 10:05:46.507 ERROR 15192 --- [oundedElastic-2] o.s.integration.handler.LoggingHandler   : org.springframework.messaging.MessageHandlingException: error occurred in message handler [com.azure.spring.integration.core.DefaultMessageHandler@3f278a9]; nested exception is java.lang.ClassCastException: Cannot cast java.time.OffsetDateTime to java.time.Instant, failedMessage=GenericMessage [payload=byte[1761], headers={raw_id=6d3599a5bfd74bd7b78dc3ec814f7c4d, X-URL-Category=Software/Hardware, azure_service_bus_received_message_context=com.azure.messaging.servicebus.ServiceBusReceivedMessageContext@649195ea, azure_service_bus_message_id=6d3599a5bfd74bd7b78dc3ec814f7c4d, Sec-Fetch-Dest=empty, Sec-Fetch-Site=cross-site, Sec-Fetch-Mode=cors, target-protocol=kafka, azure_service_bus_time_to_live=PT336H, id=508ebab2-1334-9c0a-2482-ff7db63234bd, contentType=application/json, azure_service_bus_scheduled_enqueue_time=2021-09-14T04:32:00.021Z, timestamp=1631594146506}]
	at org.springframework.integration.support.utils.IntegrationUtils.wrapInHandlingExceptionIfNecessary(IntegrationUtils.java:192)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:65)
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder$SendingHandler.handleMessageInternal(AbstractMessageChannelBinder.java:1049)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:56)
	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:115)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:133)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:106)
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:72)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:317)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:272)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47)
	at org.springframework.messaging.core.AbstractDestinationResolvingMessagingTemplate.send(AbstractDestinationResolvingMessagingTemplate.java:72)
	at org.springframework.cloud.stream.function.FunctionConfiguration$FunctionToDestinationBinder$1.doSendMessage(FunctionConfiguration.java:593)
	at org.springframework.cloud.stream.function.FunctionConfiguration$FunctionToDestinationBinder$1.handleMessageInternal(FunctionConfiguration.java:576)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:56)
	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:115)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:133)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:106)
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:72)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:317)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:272)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47)
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109)
	at org.springframework.integration.endpoint.MessageProducerSupport.sendMessage(MessageProducerSupport.java:208)
	at com.azure.spring.integration.core.AbstractInboundChannelAdapter.receiveMessage(AbstractInboundChannelAdapter.java:61)
	at com.azure.spring.integration.servicebus.DefaultServiceBusMessageProcessor.lambda$processMessage$4(DefaultServiceBusMessageProcessor.java:70)
	at com.azure.messaging.servicebus.ServiceBusProcessorClient$1.onNext(ServiceBusProcessorClient.java:226)
	at com.azure.messaging.servicebus.ServiceBusProcessorClient$1.onNext(ServiceBusProcessorClient.java:200)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runAsync(FluxPublishOn.java:440)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:527)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassCastException: Cannot cast java.time.OffsetDateTime to java.time.Instant
	at java.lang.Class.cast(Class.java:3369)
	at com.azure.spring.integration.servicebus.converter.ServiceBusMessageConverter.getAndRemove(ServiceBusMessageConverter.java:190)
	at com.azure.spring.integration.servicebus.converter.ServiceBusMessageConverter.setCustomHeaders(ServiceBusMessageConverter.java:109)
	at com.azure.spring.integration.servicebus.converter.ServiceBusMessageConverter.setCustomHeaders(ServiceBusMessageConverter.java:43)
	at com.azure.spring.integration.core.converter.AbstractAzureMessageConverter.fromMessage(AbstractAzureMessageConverter.java:72)
	at com.azure.spring.integration.servicebus.ServiceBusTemplate.sendAsync(ServiceBusTemplate.java:62)
	at com.azure.spring.integration.core.DefaultMessageHandler.handleMessageInternal(DefaultMessageHandler.java:74)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:56)
	... 40 more
```

It looks like the library is adding a header as `ServiceBusMessageHeaders.SCHEDULED_ENQUEUE_TIME` with a `OfsetDateTime` type and during the message conversion in `ServiceMessageConverter` fails in converting to `Instant` type. The actual code of `ServiceMessageConverter` is shown below

```
 getAndRemove(copySpringMessageHeaders, SCHEDULED_ENQUEUE_TIME, Instant.class)
            .map((ins) -> OffsetDateTime.ofInstant(ins, ZoneId.systemDefault()))
            .ifPresent(val -> {
                message.setScheduledEnqueueTime(val);
                logOverriddenHeaders(SCHEDULED_ENQUEUE_TIME, AzureHeaders.SCHEDULED_ENQUEUE_MESSAGE, headers);
            });
```

We could send the message to the Service bus topic by manually adding the header when returning the Spring `Message` in the `Function<Message<String>,Message<String>>`
```
Message<String> outboundEvent =  MessageBuilder
               .withPayload("Hello")
                .setHeader(ServiceBusMessageHeaders.SCHEDULED_ENQUEUE_TIME, Instant.now()).build();
```

 - Spring Boot v2.5.4
 - Spring-cloud-stream-binder-servicebus-topic:2.8.0

**Comment by joshfree** [comment]
@yiliuTo could you please follow up with @ahmedmq?

**Comment by yiliuTo** [comment]
Hi @ahmedmq , thanks for your reporting, we will fix the bug by modifying the header value type from `Instant` to `OffsetDateTime`, which also can stay align with the Service Bus Java SDK.

**Comment by yiliuTo** [comment]
Hi @ahmedmq this bug has been fixed and you could wait for the next release for the fix.
