### ISSUE TITLE
GenericResource.update throws com.microsoft.azure.CloudException

### ISSUE THREAD

**Issue by zlishaojiez** [Azure/azure-sdk-for-java#24150]
**Describe the bug**
GenericResource.update throws com.microsoft.azure.CloudException, and the genericreource.property is null which get by genericResources().listByResourceGroup

***Exception or Stack Trace***
com.microsoft.azure.CloudException: Required parameter 'disk.Properties' is missing (null).
	at com.microsoft.azure.AzureClient.createExceptionFromResponse(AzureClient.java:822)
	at com.microsoft.azure.AzureClient.access$100(AzureClient.java:34)
	at com.microsoft.azure.AzureClient$4.call(AzureClient.java:172)
	at com.microsoft.azure.AzureClient$4.call(AzureClient.java:169)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
	at retrofit2.adapter.rxjava.CallArbiter.deliverResponse(CallArbiter.java:120)
	at retrofit2.adapter.rxjava.CallArbiter.emitResponse(CallArbiter.java:102)
	at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:46)
	at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:24)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeSingle.call(OnSubscribeSingle.java:81)
	at rx.internal.operators.OnSubscribeSingle.call(OnSubscribeSingle.java:27)
	at rx.internal.operators.SingleToObservable.call(SingleToObservable.java:39)
	at rx.internal.operators.SingleToObservable.call(SingleToObservable.java:27)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.DeferredScalarSubscriber.subscribeTo(DeferredScalarSubscriber.java:153)
	at rx.internal.operators.OnSubscribeTakeLastOne.call(OnSubscribeTakeLastOne.java:32)
	at rx.internal.operators.OnSubscribeTakeLastOne.call(OnSubscribeTakeLastOne.java:22)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: retrofit2.Response.class
	at rx.exceptions.OnErrorThrowable.addValueAsLastCause(OnErrorThrowable.java:118)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:73)
	... 44 common frames omitted

**To Reproduce**
1. Use genericResources().listByResourceGroup of the resource group
2. Use genericResource.update().withTags(tags).apply(); to update the resource

***Code Snippet***
        PagedList<GenericResource> genericResources =
                azure.genericResources().listByResourceGroup(resGroup);
        genericResources.currentPage().items().forEach(r -> {
            log.info("*********************************");
            log.info("properties {}", r.properties());
            log.info("resourceproviderNamespace {}", r.resourceProviderNamespace());
            log.info("type {}", r.type());
            log.info("resourceType {}", r.resourceType());
            log.info("apiVersion {}", r.apiVersion());
            log.info("inner properties {}", r.inner().properties());
            log.info("*********************************");
            log.info("update tags for resource {}", r.name());
            r.update()
                    .withTags(tags)
                    .apply();
        });

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - IDE: [e.g. IntelliJ]
 - Library/Libraries: [om.microsoft.azure:azure:1.41.2 (groupId:artifactId:version)]
 - Java version: [11] 
 - App Server/Environment: [e.g. Tomcat, WildFly, Azure Function, Apache Spark, Databricks, IDE plugin or anything special]
 - Frameworks: [Spring Boot] 

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please provide
- dependency tree (`mvn dependency:tree`)
  		<dependency>
			<groupId>com.microsoft.azure</groupId>
			<artifactId>azure</artifactId>
			<version>1.41.2</version>
		</dependency>
**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by joshfree** [comment]
Hi @zlishaojiez can you provide the name and version number of the SDK that you are using?

**Comment by zlishaojiez** [comment]
Hi, @joshfree 

I try such versions of the SDK
1.		<dependency>
			<groupId>com.microsoft.azure</groupId>
			<artifactId>azure</artifactId>
			<version>1.36.2</version>
		</dependency>

2.		<dependency>
			<groupId>com.microsoft.azure</groupId>
			<artifactId>azure</artifactId>
			<version>1.41.2</version>
		</dependency>

These versions of the SDK all have the issue.

And then I try the new Azure management client library Individually
<dependency>
  <groupId>com.azure.resourcemanager</groupId>
  <artifactId>azure-resourcemanager</artifactId>
  <version>2.7.0</version>
</dependency>

It also has the same issue

**Comment by joshfree** [comment]
closing old issue from Sep 15, 2021
