### ISSUE TITLE
azure-cosmos-spark_3-1_2-12-4.3.1.jar - java.lang.IllegalStateException: Timeout on blocking read for 120000000000 NANOSECONDS

### ISSUE THREAD

**Issue by arijit-das-us** [Azure/azure-sdk-for-java#24204]
I am running spark streaming job to update records to cosmos, using azure-cosmos-spark_3-1_2-12-4.3.1.jar library, I am getting Exception as below and stopping the streaming every 2 hours - 
my code - 
val configMapAggByDay = Map(
  "spark.cosmos.accountEndpoint" -> cdbEndpoint,
  "spark.cosmos.accountKey" -> cdbMasterkey,
  "spark.cosmos.database" -> cdbDatabaseAgg,
  "spark.cosmos.container" -> cdbCollectionAggByDay,
  "spark.cosmos.preferredRegionsList" -> cdbRegions,
  "spark.cosmos.write.maxRetryCount" -> "500",
  "spark.cosmos.write.strategy" -> "ItemOverwrite")
 
import org.apache.spark.sql._
 spark.sparkContext.setLocalProperty("spark.scheduler.pool", "AggDayStreamPool1")
 
aggregatesDFDay
.writeStream
.queryName("AggDayStreamQuery1")
.foreachBatch { (batchDF: DataFrame, batchId: Long) =>
  batchDF
  .write
   .format("cosmos.oltp")
   .options(configMapAggByDay)
   .mode("APPEND")
   .save()
}
.outputMode("update")
  .start()

java.lang.IllegalStateException: Timeout on blocking read for 120000000000 NANOSECONDS
	at azure_cosmos_spark.reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:123)
	at azure_cosmos_spark.reactor.core.publisher.Mono.block(Mono.java:1728)
	at azure_cosmos_spark.com.azure.cosmos.implementation.GlobalEndpointManager.init(GlobalEndpointManager.java:77)
	at azure_cosmos_spark.com.azure.cosmos.implementation.RxDocumentClientImpl.init(RxDocumentClientImpl.java:418)
	at azure_cosmos_spark.com.azure.cosmos.implementation.AsyncDocumentClient$Builder.build(AsyncDocumentClient.java:237)
	at azure_cosmos_spark.com.azure.cosmos.CosmosAsyncClient.<init>(CosmosAsyncClient.java:123)
	at azure_cosmos_spark.com.azure.cosmos.CosmosClientBuilder.buildAsyncClient(CosmosClientBuilder.java:741)
	at com.azure.cosmos.spark.CosmosClientCache$.syncCreate(CosmosClientCache.scala:118)
	at com.azure.cosmos.spark.CosmosClientCache$.apply(CosmosClientCache.scala:44)
	at com.azure.cosmos.spark.ItemsReadOnlyTable.<init>(ItemsReadOnlyTable.scala:72)
	at com.azure.cosmos.spark.ItemsTable.<init>(ItemsTable.scala:39)
	at com.azure.cosmos.spark.CosmosItemsDataSource.getTable(CosmosItemsDataSource.scala:64)
	at org.apache.spark.sql.DataFrameWriter.getTable$1(DataFrameWriter.scala:362)
	at org.apache.spark.sql.DataFrameWriter.saveInternal(DataFrameWriter.scala:380)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:310)
	at $linea893301d96134719878deab30af91aa543.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.$anonfun$res5$1(command-2481228021522689:14)
	at $linea893301d96134719878deab30af91aa543.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.$anonfun$res5$1$adapted(command-2481228021522689:9)
	at org.apache.spark.sql.execution.streaming.sources.ForeachBatchSink.addBatch(ForeachBatchSink.scala:38)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.$anonfun$runBatch$16(MicroBatchExecution.scala:613)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withCustomExecutionEnv$5(SQLExecution.scala:119)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:251)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withCustomExecutionEnv$1(SQLExecution.scala:104)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:843)
	at org.apache.spark.sql.execution.SQLExecution$.withCustomExecutionEnv(SQLExecution.scala:77)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:201)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.$anonfun$runBatch$15(MicroBatchExecution.scala:611)
	at org.apache.spark.sql.execution.streaming.ProgressReporter.reportTimeTaken(ProgressReporter.scala:293)
	at org.apache.spark.sql.execution.streaming.ProgressReporter.reportTimeTaken$(ProgressReporter.scala:291)
	at org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:73)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.runBatch(MicroBatchExecution.scala:611)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.$anonfun$runActivatedStream$4(MicroBatchExecution.scala:250)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.withSchemaEvolution(MicroBatchExecution.scala:697)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.$anonfun$runActivatedStream$2(MicroBatchExecution.scala:247)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.apache.spark.sql.execution.streaming.ProgressReporter.reportTimeTaken(ProgressReporter.scala:293)
	at org.apache.spark.sql.execution.streaming.ProgressReporter.reportTimeTaken$(ProgressReporter.scala:291)
	at org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:73)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.$anonfun$runActivatedStream$1(MicroBatchExecution.scala:216)
	at org.apache.spark.sql.execution.streaming.ProcessingTimeExecutor.execute(TriggerExecutor.scala:57)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.runActivatedStream(MicroBatchExecution.scala:210)
	at org.apache.spark.sql.execution.streaming.StreamExecution.org$apache$spark$sql$execution$streaming$StreamExecution$$runStream(StreamExecution.scala:364)
	at org.apache.spark.sql.execution.streaming.StreamExecution$$anon$1.run(StreamExecution.scala:268)

**Comment by joshfree** [comment]
@kushagraThapar could you please help route @arijit-das-us's issue

**Comment by kushagraThapar** [comment]
@moderakh  - PTAL

**Comment by arijit-das-us** [comment]
[cosmos conn error.txt](https://github.com/Azure/azure-sdk-for-java/files/7198421/cosmos.conn.error.txt)
attached log4j error log from spark driver from databrick cluster

**Comment by xinlian12** [comment]
@arijit-das-us  please try the latest spark connector SDK. you can download from here: https://search.maven.org/search?q=g:com.azure.cosmos.spark

Please open a new one if you are still facing the same issue. Thanks
