### ISSUE TITLE
[BUG] Sporadic timeouts sending to service bus with azure-messaging-servicebus

### ISSUE THREAD

**Issue by JunhaoSLi** [Azure/azure-sdk-for-java#24500]
**Describe the bug**
I have an Azure Function with a queue trigger that creates a `ServiceBusSenderClient` and attempts to send a single message to a service bus topic via `ServiceBusSenderClient.sendMessage`. For around 10% of the function invocations, `sendMessage` times out with an IllegalStateException. 

The function is able to send other messages to the service bus during the time that these timeouts are occurring. Retries of `sendMessage` help to alleviate the issue but some messages still timeout after 15 minutes of retrying.

***Exception or Stack Trace***
From application insights
```
java.lang.IllegalStateException: Timeout on blocking read for 242400000000 NANOSECONDS
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:123)
	at reactor.core.publisher.Mono.block(Mono.java:1727)
	at com.mycom.ForwarderFunction.forwardEventFromQueue(ForwarderFunction.java:108)
	at sun.reflect.GeneratedMethodAccessor184.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.microsoft.azure.functions.worker.broker.JavaMethodInvokeInfo.invoke(JavaMethodInvokeInfo.java:22)
	at com.microsoft.azure.functions.worker.broker.JavaMethodExecutorImpl.execute(JavaMethodExecutorImpl.java:54)
	at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:57)
	at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:33)
	at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)
	at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:45)
	at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:92)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**To Reproduce**
I haven't been able to reproduce the issue sending to our service bus topic while running the function app locally, but the error occurs sporadically with the function apps deployed in our Azure resource groups. Send a message to a service bus topic with `ServiceBusSenderClient.sendMessage` at regular intervals; a portion of the calls block and timeout.

***Code Snippet***
```
public class ForwarderFunction {
    String SERVICE_BUS_CONN_STRING = "...";
    String SERVICE_BUS_TOPIC = "...";

    @FunctionName("Forward-message")
    public void ForwardEventFromQueue(
            @QueueTrigger(name = "qmsg", queueName = QUEUE_NAME, connection = QUEUE_CONNECTION) String qmsg,
            final ExecutionContext context
    ) {
        String result = doSomeProcessing();

        ServiceBusSenderClient senderClient = ServiceBusClientBuilder()
                .connectionString(SERVICE_BUS_CONN_STRING)
                .retryOptions(retryOptions)
                .sender()
                .topicName(SERVICE_BUS_TOPIC)
                .buildClient();
        
        ServiceBusMessage serviceBusMessage = new ServiceBusMessage(result);
        senderClient.sendMessage(serviceBusMessage);

        senderClient.close();
    }
}
```

**Expected behavior**
The `sendMessage` function calls do not time out with an exception and messages are consistently sent successfully to the service bus topic. 

I understand timeouts may be inevitable if there are issues on the service bus topic side but that doesn't seem to be the case as other messages are sent successfully in the same time frame as these timeouts.

**Setup (please complete the following information):**
 - Java version: 8
 - App Server/Environment: Azure Function
 - 'com.azure', name: 'azure-core', version: '1.17.0'
 - 'com.azure', name: 'azure-messaging-servicebus', version: '7.4.0'

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by joshfree** [comment]
@ki1729 could you follow up on @JunhaoSLi's github issue?

/cc @anuchandy
