### ISSUE TITLE
[BUG] azure-cosmos attempts making telemetry connection even though disabled

### ISSUE THREAD

**Issue by runeflobakk** [Azure/azure-sdk-for-java#24524]
**Describe the bug**
The azure-cosmos client (CosmosAsyncClient) attempts making a connection to telemetry endpoint 169.254.169.254 in its init-routine, even though [CosmosClientBuilder.clientTelemetryEnabled](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/CosmosClientBuilder.java#L110) is `false`. In our case, we have not allowed our application to make connections to the telemetry service. This results in the client [logging it is "not on azure vm"](https://github.com/Azure/azure-sdk-for-java/blob/edfedd946d8e79d39aeeb9f1ba992a6fbc437999/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/clienttelemetry/ClientTelemetry.java#L251-L253), and also Netty logging a generic warn in `reactor.netty.http.client.HttpClientConnect`: "The connection observed an error". In our case it seems to happen consistently from the `reactor-http-epoll-2` thread, but I don't know if it is tied to that. 

We would prefer not to have this warn when we start up our application, but we can't simply suppress it because we would like to log warns happening from other reasons with the Netty connections. Preferably we would like cosmos-azure to not attempt to make any telemetry connections unless we have asked it to do so.

***Exception or Stack Trace***
```
io.netty.handler.proxy.HttpProxyHandler$HttpProxyConnectException: http, none, /w.x.y.z:3128 => /169.254.169.254:80, status: 403 Forbidden
	at io.netty.handler.proxy.HttpProxyHandler.handleResponse(HttpProxyHandler.java:200)
	at io.netty.handler.proxy.ProxyHandler.channelRead(ProxyHandler.java:257)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.handler.proxy.HttpProxyHandler$HttpClientCodecWrapper.channelRead(HttpProxyHandler.java:272)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$1.run(AbstractEpollChannel.java:425)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:831)
```

**To Reproduce**
Block access to 169.254.169.254 and call `CosmosClientBuilder.buildAsyncClient()`

***Code Snippet***
https://github.com/Azure/azure-sdk-for-java/blob/edfedd946d8e79d39aeeb9f1ba992a6fbc437999/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/RxDocumentClientImpl.java#L451

**Expected behavior**
Do not expect azure-cosmos to make connection to telemetry, unless explicitly enabled. (default [documentet as false](https://docs.microsoft.com/en-us/java/api/com.azure.cosmos.cosmosclientbuilder.clienttelemetryenabled?view=azure-java-stable#com_azure_cosmos_CosmosClientBuilder_clientTelemetryEnabled_boolean_))

**Setup (please complete the following information):**
 - OS: linux
 - Library/Libraries: [e.g. com.azure:azure-cosmos:1.19.1 (groupId:artifactId:version)]
 - Java version: 16 
 - App Server/Environment: Azure Kubernetes Service
 - Frameworks: Spring Boot
  
**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by joshfree** [comment]
@lmolkova @kushagraThapar could you please follow up with @runeflobakk's github issue?

**Comment by kushagraThapar** [comment]
@simplynaveen20  - can you please take a look at this ?

**Comment by kushagraThapar** [comment]
This has been fixed in the recent PR by @xinlian12

**Comment by AshutoshNirkhe** [comment]
> This has been fixed in the recent PR by @xinlian12

@kushagraThapar I am facing same issue (while using latest maven azure-cosmos library v4.x) 
Can you please point out which PR fixed it and which version is this available from ?

**Comment by kushagraThapar** [comment]
@AshutoshNirkhe - I doubt if you are facing the same issue, because you are getting error on `i.o.e.internal.grpc.OkHttpGrpcExporter` which is not cosmos code, looks like some grpc code from your application. 
Also, if you notice, you are trying to connect to the localhost. Our telemetry did not go to the localhost. 

So I would recommend debugging your application to see why this is happening, nevertheless here is the PR that fixed it for the above original issue reported: https://github.com/Azure/azure-sdk-for-java/pull/34889
