### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by nesanmano** [Azure/azure-sdk-for-java#24557]
**Describe the bug**
I am trying to use Azure SDK in my Spring Boot application. I have done put everything correctly except for one thing the netty bom dependency. 

I keep getting this every time I run my test.

2021-10-05 16:34:09.556 ERROR   --- [onPool-worker-1] c.a.i.ClientCertificateCredential        : Azure Identity => ERROR in getToken() call for scopes [https://management.core.windows.net//.default]: Could not initialize class reactor.netty.http.client.HttpClientSecure
2021-10-05 16:34:09.582 ERROR   --- [onPool-worker-1] c.a.c.implementation.AccessTokenCache    : Failed to acquire a new access token.
2021-10-05 16:34:39.589 ERROR   --- [onPool-worker-3] c.a.i.ClientCertificateCredential        : Azure Identity => ERROR in getToken() call for scopes [https://management.core.windows.net//.default]: Could not initialize class reactor.netty.http.client.HttpClientSecure
2021-10-05 16:34:39.591 ERROR   --- [onPool-worker-3] c.a.c.implementation.AccessTokenCache    : Failed to acquire a new access token.
2021-10-05 16:35:09.601 ERROR   --- [onPool-worker-5] c.a.i.ClientCertificateCredential        : Azure Identity => ERROR in getToken() call for scopes [https://management.core.windows.net//.default]: Could not initialize class reactor.netty.http.client.HttpClientSecure
2021-10-05 16:35:09.602 ERROR   --- [onPool-worker-5] c.a.c.implementation.AccessTokenCache    : Failed to acquire a new access token.
2021-10-05 16:35:39.610 ERROR   --- [onPool-worker-7] c.a.i.ClientCertificateCredential        : Azure Identity => ERROR in getToken() call for scopes [https://management.core.windows.net//.default]: Could not initialize class reactor.netty.http.client.HttpClientSecure
2021-10-05 16:35:39.611 ERROR   --- [onPool-worker-7] c.a.c.implementation.AccessTokenCache    : Failed to acquire a new access token.
2021-10-05 16:35:39.611  INFO   --- [onPool-worker-7] com.azure.core.http.policy.RetryPolicy   : Retry attempts have been exhausted after 3 attempts.

java.lang.NoClassDefFoundError: Could not initialize class reactor.netty.http.client.HttpClientSecure

	at reactor.netty.http.client.HttpClientConnect$MonoHttpConnect.lambda$subscribe$0(HttpClientConnect.java:219)
	at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:57)
	at reactor.core.publisher.FluxRetryWhen.subscribe(FluxRetryWhen.java:77)
	at reactor.core.publisher.MonoRetryWhen.subscribeOrReturn(MonoRetryWhen.java:46)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
	at reactor.netty.http.client.HttpClientConnect$MonoHttpConnect.subscribe(HttpClientConnect.java:271)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
	at reactor.core.publisher.FluxRetryWhen.subscribe(FluxRetryWhen.java:77)
	at reactor.core.publisher.MonoRetryWhen.subscribeOrReturn(MonoRetryWhen.java:46)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4338)
	at reactor.core.publisher.Mono.block(Mono.java:1703)
	at com.azure.identity.implementation.HttpPipelineAdapter.send(HttpPipelineAdapter.java:58)
	at com.microsoft.aad.msal4j.HttpHelper.executeHttpRequestWithRetries(HttpHelper.java:96)
	at com.microsoft.aad.msal4j.HttpHelper.executeHttpRequest(HttpHelper.java:49)
	at com.microsoft.aad.msal4j.AadInstanceDiscoveryProvider.executeRequest(AadInstanceDiscoveryProvider.java:232)
	at com.microsoft.aad.msal4j.AadInstanceDiscoveryProvider.sendInstanceDiscoveryRequest(AadInstanceDiscoveryProvider.java:187)
	at com.microsoft.aad.msal4j.AadInstanceDiscoveryProvider.doInstanceDiscoveryAndCache(AadInstanceDiscoveryProvider.java:285)
	at com.microsoft.aad.msal4j.AadInstanceDiscoveryProvider.getMetadataEntry(AadInstanceDiscoveryProvider.java:57)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.getAuthorityWithPrefNetworkHost(AuthenticationResultSupplier.java:39)
	at com.microsoft.aad.msal4j.AcquireTokenSilentSupplier.execute(AcquireTokenSilentSupplier.java:23)
	at com.microsoft.aad.msal4j.AcquireTokenByClientCredentialSupplier.execute(AcquireTokenByClientCredentialSupplier.java:46)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:69)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:18)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run$$$capture(CompletableFuture.java:1604)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596)
	at java.util.concurrent.ForkJoinTask.doExec$$$capture(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

This is a part of my POM dependency file:

        <dependency>
            <groupId>com.clickntap</groupId>
            <artifactId>vimeo</artifactId>
            <version>1.13</version>
        </dependency>

        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-security-keyvault-administration</artifactId>
            <version>4.0.3</version>
        </dependency>
        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-security-keyvault-certificates</artifactId>
            <version>4.2.3</version>
        </dependency>
        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-security-keyvault-jca</artifactId>
            <version>2.0.0</version>
        </dependency>
        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-security-keyvault-keys</artifactId>
            <version>4.3.3</version>
        </dependency>
        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-security-keyvault-secrets</artifactId>
            <version>4.3.3</version>
        </dependency>

        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-core-management</artifactId>
            <version>1.4.1</version>
        </dependency>

        <dependency>
            <groupId>com.azure.resourcemanager</groupId>
            <artifactId>azure-resourcemanager-resources</artifactId>
            <version>2.8.0</version>
        </dependency>

        <dependency>
            <groupId>com.azure.resourcemanager</groupId>
            <artifactId>azure-resourcemanager-keyvault</artifactId>
            <version>2.8.0</version>
        </dependency>

        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-security-keyvault-keys</artifactId>
            <version>4.3.2</version>
        </dependency>

        <dependency>
            <groupId>com.microsoft.azure</groupId>
            <artifactId>msal4j</artifactId>
            <version>1.11.0</version>
        </dependency>

        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-security-keyvault-administration</artifactId>
            <version>4.0.3</version>
        </dependency>

        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-identity</artifactId>
            <version>1.3.6</version>
            <exclusions>
                <exclusion>
                    <groupId>io.projectreactor</groupId>
                    <artifactId>reactor-core</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>io.projectreactor.netty</groupId>
                    <artifactId>reactor-netty</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-tcnative-boringssl-static</artifactId>
        </dependency>

        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-core</artifactId>
            <version>1.20.0</version>
        </dependency>

        
        <dependency>
            <groupId>io.projectreactor</groupId>
            <artifactId>reactor-core</artifactId>
            <version>3.4.9</version>
        </dependency>
        <dependency>
            <groupId>io.projectreactor</groupId>
            <artifactId>reactor-test</artifactId>
            <version>3.4.9</version>
        </dependency>
        <dependency>
            <groupId>io.projectreactor</groupId>
            <artifactId>reactor-tools</artifactId>
            <version>3.4.9</version>
        </dependency>
        <dependency>
            <groupId>io.projectreactor.addons</groupId>
            <artifactId>reactor-extra</artifactId>
            <version>3.4.4</version>
        </dependency>
        <dependency>
            <groupId>io.projectreactor.addons</groupId>
            <artifactId>reactor-adapter</artifactId>
            <version>3.4.4</version>
        </dependency>
        <dependency>
            <groupId>io.projectreactor.netty</groupId>
            <artifactId>reactor-netty</artifactId>
            <version>1.0.10</version>
        </dependency>
        <dependency>
            <groupId>io.projectreactor.netty</groupId>
            <artifactId>reactor-netty-core</artifactId>
            <version>1.0.10</version>
        </dependency>
        <dependency>
            <groupId>io.projectreactor.netty</groupId>
            <artifactId>reactor-netty-http</artifactId>
            <version>1.0.10</version>
        </dependency>
        <dependency>
            <groupId>io.projectreactor.netty</groupId>
            <artifactId>reactor-netty-http-brave</artifactId>
            <version>1.0.10</version>
        </dependency>
        <dependency>
            <groupId>io.projectreactor.addons</groupId>
            <artifactId>reactor-pool</artifactId>
            <version>0.2.6</version>
        </dependency>
        <dependency>
            <groupId>io.projectreactor.kafka</groupId>
            <artifactId>reactor-kafka</artifactId>
            <version>1.3.5</version>
        </dependency>
        <dependency>
            <groupId>io.projectreactor.rabbitmq</groupId>
            <artifactId>reactor-rabbitmq</artifactId>
            <version>1.5.3</version>
        </dependency>
        <dependency>
            <groupId>io.projectreactor.kotlin</groupId>
            <artifactId>reactor-kotlin-extensions</artifactId>
            <version>1.1.4</version>
        </dependency>

        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-handler</artifactId>
            <version>4.1.67.Final</version>
        </dependency>

        <dependency>
            <groupId>com.nimbusds</groupId>
            <artifactId>nimbus-jose-jwt</artifactId>
            <version>8.20</version>
        </dependency>

    </dependencies>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.azure</groupId>
                <artifactId>azure-sdk-bom</artifactId>
                <version>1.0.4</version>
            </dependency>
            <dependency>
                <groupId>io.projectreactor</groupId>
                <artifactId>reactor-bom</artifactId>
                <version>2020.0.10</version>
            </dependency>
            <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-bom</artifactId>
                <version>4.1.67.Final</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

I suspect that there could be a version conflict between the dependencies. I am using Spring core 2.4.0

Please help me to solve this issue. I am geeting delayed.

**Comment by nesanmano** [comment]
I am including spring-core 2.4.0 as part of the parent pom. Regarding the dependency management section, I have taken the important things from the azure-sdk-bom. I am really not sure what is messing everything up.

**Comment by alzimmermsft** [comment]
Any chance you could send an `mvn dependency:tree` output of your project? I've attempted to reproduce it based on the dependencies listed above and I didn't run into the `Could not initialize class reactor.netty.http.client.HttpClientSecure` exception. Additionally, given what `HttpClientSecure` is is there a specific OS you're using? There may be hooks into OS level SSL handling that may be going awry.

**Comment by alzimmermsft** [comment]
@nesanmano, thank you for this! 

After digging through this it is an issue with the version of `netty-tcnative-boringssl-static` being resolved. This is stemming from the parent POM `spring-boot-starter-parent:2.4.0`, this has a dependency on `netty-tcnative-boringssl-static:2.0.34.Final` but you're including and depending on a version of `reactor-netty` which leverages functionality adding in `netty-tcnative-boringssl-static:2.0.40.Final`.

This is the class being depended on https://github.com/netty/netty-tcnative/blob/main/openssl-dynamic/src/main/java/io/netty/internal/tcnative/AsyncSSLPrivateKeyMethod.java.

Including a direct dependency of `netty-tcnative-boringssl-static:2.0.40.Final`, or later, or upgrading the version of `spring-boot-starter-parent:2.4.8` or later should resolve this issue.

**Comment by alzimmermsft** [comment]
Thanks for the update @nesanmano, is it still throwing the same `NoClassDefFoundError` when 

```xml
<dependency>
  <groupId>io.netty</groupId>
  <artifactId>netty-tcnative-boringssl-static</artifactId>
  <version>2.0.40.Final</version>
</dependency>
```

is being included as the dependency?

**Comment by nesanmano** [comment]
yes, that is correct. I am trying to upgrade my spring boot to 2.5.5. I will keep you updated.

**Comment by weidongxu-microsoft** [comment]
@nesanmano

Keyvault is a bit hard to understand.

When you create (or modify) it, you can see it has 2 approach to permission.
![image](https://user-images.githubusercontent.com/53292327/136879857-10a64bd3-d54a-479a-9efa-35d7986e2235.png)

One is the access policy defined within Keyvault, and if you use this, IAM does not apply, you need to add your appId here.

Another (newer approach) is the RBAC. If you use this, you can use IAM with e.g. KEY_VAULT_CRYPTO_USER, KEY_VAULT_SECRETS_USER

**Comment by weidongxu-microsoft** [comment]
Also let me know which call result in 403. I don't think `listByResourceGroup` will get this?

**Comment by nesanmano** [comment]
@weidongxu-microsoft Hi, I have set and configured everything, I am able to question the key vault using my Java app. I am looking for a best practice to retrieve those keys and store them in environment variables in my Linux container.

**Comment by nesanmano** [comment]
@vcolin7 Hi, You have totally understood my concern. I am actually using you way to retrieve the key in my unit test. My concern is that I don't want to use it very often. Frequent queries to the vault is not very cost effective from my understanding. Hence, I am looking to run a custom script every time the server boots up and the software would simply get them from the env.
