### ISSUE TITLE
Using the synchronous client produces exceptions

### ISSUE THREAD

**Issue by Glamdring** [Azure/azure-sdk-for-java#24612]
**Describe the bug**

Using the synchronous client produces exceptions

I'm trying to synchronously consume events from EventHub. EVents are not consumed, but after a couple of minutes I'm starting to get the exceptions below. "After a couple of minutes" means that the client has been open and closed multiple times - instead of streaming the events, we do batch consumption, just as documented here https://azuresdkdocs.blob.core.windows.net/$web/java/azure-messaging-eventhubs/5.10.1/index.html at "Consuming events with EventHubConsumerClient. 

***Exception or Stack Trace***
2021-10-07 10:38:51,043  WARN c.a.c.a.i.ReactorDispatcher:381 - connectionId[MF_6830a6_1633603060368] signalWorkQueue failed before reactor closed.
2021-10-07 10:38:51,043  WARN c.a.c.a.i.ReactorDispatcher:381 - connectionId[MF_6830a6_1633603060368] signalWorkQueue failed before reactor closed.
2021-10-07 10:38:51,044 ERROR r.c.p.Operators:314 - Operator called default onErrorDropped
java.lang.RuntimeException: connectionId[MF_6830a6_1633603060368] IO Sink was interrupted before reactor closed.
	at com.azure.core.amqp.implementation.ReactorDispatcher.signalWorkQueue(ReactorDispatcher.java:130)
	at com.azure.core.amqp.implementation.ReactorDispatcher.invoke(ReactorDispatcher.java:94)
	at com.azure.core.amqp.implementation.RequestResponseChannel.<init>(RequestResponseChannel.java:186)
	at com.azure.core.amqp.implementation.ReactorConnection.lambda$createRequestResponseChannel$16(ReactorConnection.java:389)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:113)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:127)
	at reactor.core.publisher.Operators$MonoSubscriber.request(Operators.java:1905)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:169)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:169)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.request(FluxPeekFuseable.java:144)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.request(Operators.java:2157)
	at com.azure.core.amqp.implementation.AmqpChannelProcessor.requestUpstream(AmqpChannelProcessor.java:308)
	at com.azure.core.amqp.implementation.AmqpChannelProcessor.lambda$onNext$3(AmqpChannelProcessor.java:119)
	at reactor.core.publisher.LambdaSubscriber.onComplete(LambdaSubscriber.java:132)
	at reactor.core.publisher.EmitterProcessor.checkTerminated(EmitterProcessor.java:554)
	at reactor.core.publisher.EmitterProcessor.drain(EmitterProcessor.java:415)
	at reactor.core.publisher.EmitterProcessor.tryEmitComplete(EmitterProcessor.java:234)
	at reactor.core.publisher.SinkManySerialized.tryEmitComplete(SinkManySerialized.java:61)
	at reactor.core.publisher.InternalManySink.emitComplete(InternalManySink.java:68)
	at com.azure.core.amqp.implementation.RequestResponseChannel.onTerminalState(RequestResponseChannel.java:401)
	at com.azure.core.amqp.implementation.RequestResponseChannel.lambda$new$3(RequestResponseChannel.java:161)
	at reactor.core.publisher.LambdaSubscriber.onComplete(LambdaSubscriber.java:132)
	at reactor.core.publisher.FluxDistinctUntilChanged$DistinctUntilChangedSubscriber.onComplete(FluxDistinctUntilChanged.java:172)
	at reactor.core.publisher.FluxReplay$SizeBoundReplayBuffer.replayNormal(FluxReplay.java:805)
	at reactor.core.publisher.FluxReplay$SizeBoundReplayBuffer.replay(FluxReplay.java:898)
	at reactor.core.publisher.ReplayProcessor.tryEmitComplete(ReplayProcessor.java:465)
	at reactor.core.publisher.SinkManySerialized.tryEmitComplete(SinkManySerialized.java:61)
	at reactor.core.publisher.InternalManySink.emitComplete(InternalManySink.java:68)
	at com.azure.core.amqp.implementation.handler.Handler.close(Handler.java:132)
	at com.azure.core.amqp.implementation.handler.ReceiveLinkHandler.onLinkLocalClose(ReceiveLinkHandler.java:185)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:173)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291)
	at com.azure.core.amqp.implementation.ReactorExecutor.run(ReactorExecutor.java:86)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.nio.channels.AsynchronousCloseException: null
	at java.base/java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:202)
	at java.base/sun.nio.ch.SocketChannelImpl.endWrite(SocketChannelImpl.java:447)
	at java.base/sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:469)
	at java.base/sun.nio.ch.SinkChannelImpl.write(SinkChannelImpl.java:114)
	at com.azure.core.amqp.implementation.ReactorDispatcher.signalWorkQueue(ReactorDispatcher.java:123)
	... 41 common frames omitted
2021-10-07 10:38:51,046 ERROR c.a.c.a.i.ReactorDispatcher:387 - ReactorDispatcher instance is closed.
2021-10-07 10:38:51,044  WARN c.a.c.a.i.ReactorDispatcher:381 - connectionId[MF_6830a6_1633603060368] signalWorkQueue failed before reactor closed.

**To Reproduce**

1. Create an event hub
2. Configure the event hub for Azure AD log collection
3. Launch a scheduled job every 10 seconds to fetch all accumulated events in the event hub.

***Code Snippet***

        EventHubClientBuilder clientBuilder = new EventHubClientBuilder()
                .connectionString(connectionString)
                .clientOptions(new ClientOptions().setApplicationId("custom-consumer"))
                .prefetchCount(FETCH_SIZE)
                .consumerGroup(EventHubClientBuilder.DEFAULT_CONSUMER_GROUP_NAME);

        try (EventHubConsumerClient client = clientBuilder.buildConsumerClient()) {
            logger.info("Created Azure client {} with partitions {}", client.getConsumerGroup(),
                    client.getPartitionIds().stream().collect(Collectors.joining(", ")));

            List<Entry> entries = new ArrayList<>();

            for (String partitionId : client.getPartitionIds()) {
                var events = client.receiveFromPartition(partitionId, FETCH_SIZE,
                        EventPosition.fromEnqueuedTime(details.getLastFetchedTime().toInstant(ZoneOffset.UTC)),
                        Duration.ofSeconds(RECEIVE_TIMEOUT_SECONDS), RECEIVE_OPTIONS);

                for (PartitionEvent event : events) {
                    entries.addAll(toEntry(event.getData(), event.getPartitionContext()));
                }
            }

**Expected behavior**

Events should be consumed and there should be no stacktraces

**Screenshots**

**Setup (please complete the following information):**
 - OS: Windows
 - IDE: IntelliJ
 - Library/Libraries: com.azure:azure-messaging-eventhubs:5.10.1
 - Java version: 11
 - App Server/Environment: Undertow
 - Frameworks: Spring Boot

**Comment by joshfree** [comment]
@conniey could you please follow up with @Glamdring on their github issue?

**Comment by conniey** [comment]
Apologies for dropping the ball on this. I'll take a look at it now. 
Every time `receiveFromPartition` is called, it creates a new receive link, receives x number of events, then closes that receive link. It may not be as performant as you want using the async client and then calling `receive` will give you potentially an infinite stream of events where you an apply Reactor operators to have back-pressure etc.

**Comment by Glamdring** [comment]
For reasons outside the scope of the issue, we can't work with an infinite stream and a reactor; it has to be a batch "fetch and close" repeatedly.

**Comment by ramya-rao-a** [comment]
> the client has been open and closed multiple times

@Glamdring Does this mean that you are creating a new client after receiving a batch of events from each partition?

**Comment by Glamdring** [comment]
> > the client has been open and closed multiple times
> 
> @Glamdring Does this mean that you are creating a new client after receiving a batch of events from each partition?

Yes, that's correct. It is a session-less batch process, so leaving a client open is hardly an option.

**Comment by ZejiaJiang** [comment]
Hi @Glamdring , I just go through this issue,

Sorry for that I didn't repro this issue, I need more details:
1. Could you provide more logs and turn on the DEBUG log level? From the error message, the reactor is closed, there could be some other error cause the reactor closed I assumed. So I guess here is not the whole error logs. We fixed a client-closed related issue in July's release. Not sure this issue is related with the one we fixed before . But we **highly recommand** upgrade to the latest version. So could you please upgrade the SDK to latest version which is `v5.13.0` now.
2. I want to know how you trigger the batch process task. Do you set up a timer to do this process every 10s? Each process task is on a new thread?

PS:
 >  It is a session-less batch process, so leaving a client open is hardly an option.

 I'm curious about why leaving a client open is hardly an option. Actually our customers have similar scenario, they also do some session-less batch process tasks. they keep the client opening in the server side and trigger the task by http request. The time between every request is random. It also works.

**Comment by Glamdring** [comment]
Hello @ZejiaJiang 
I'm not longer involved with the issue, but I'll let the team know they should upgrade and try again. Will get back with results.
The batch task is triggered by spring's @Scheduled mechanism, which means a thread pool is executing the tasks. The issue with leaving a session open is that the application is stateless and 1runs in a cluster of several machines, so it's not guaranteed that the next run will happen on the same machine (we have a distributed lock mechanism to make sure there are no race conditions). So each time the task runs, we have to assume it doesn't have rely on any application state (we store some state in the database).

**Comment by ZejiaJiang** [comment]
I did some tests to repro this issue, but all I got is two exception we fixed before, https://github.com/Azure/azure-sdk-for-java/pull/27400 and https://github.com/Azure/azure-sdk-for-java/pull/27512 . In the latest verion of SDK, all work well.

I created two eventhub instance, one has 1 partition and the another one has 32 partitions, I wrote some code just like given code snippet. failed to repro this issue. So if the issue still remains in latest version of SDK, could you please provide some more information:
1. Turn on the `DEBUG` log level? here is the configure step [Enable and configure logging](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/eventhubs/azure-messaging-eventhubs/TROUBLESHOOTING.md#enable-and-configure-logging)
2. More detail of parameters, how many partitions in you eventhubs instance? how many events (FETCH_SIZE) to fetch in each batch task? How long each task take?
