### ISSUE TITLE
[BUG] MismatchedInputException when trying to create a VM with a public address while a Policy forbids it

### ISSUE THREAD

**Issue by slandelle** [Azure/azure-sdk-for-java#24663]
**Describe the bug**

When a policy forbids creating a VM with a public address, we should have a proper Exception, not a Jackson MismatchedInputException.

***Exception or Stack Trace***

```
root rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: retrofit2.Response.class
root 	at rx.exceptions.OnErrorThrowable.addValueAsLastCause(OnErrorThrowable.java:118)
root 	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:73)
root 	... 50 common frames omitted
root Wrapped by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `java.util.ArrayList` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('Microsoft.Network/networkInterfaces')
root  at [Source: (String)"{"policyDefinitionDisplayName":"Network interfaces should not have public IPs","evaluationDetails":{"evaluatedExpressions":[{"result":"True","expressionKind":"Field","expression":"type","path":"type","expressionValue":"Microsoft.Network/networkInterfaces","targetValue":"Microsoft.Network/networkInterfaces","operator":"Equals"},{"result":"False","expressionKind":"Field","expression":"Microsoft.Network/networkInterfaces/ipconfigurations[*].publicIpAddress.id","path":"properties.ipConfigurations[*]"[truncated 816 chars]; line: 1, column: 271] (through reference chain: com.microsoft.azure.CloudError["additionalInfo"]->java.util.ArrayList[0]->com.microsoft.azure.PolicyViolationErrorInfo["evaluationDetails"]->com.microsoft.azure.EvaluationDetails["evaluatedExpressions"]->java.util.ArrayList[0]->com.microsoft.azure.ExpressionEvaluationDetails["targetValue"])
root 	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
root 	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1728)
root 	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1353)
root 	at com.fasterxml.jackson.databind.deser.std.StdDeserializer._deserializeFromString(StdDeserializer.java:311)
root 	at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.handleNonArray(StringCollectionDeserializer.java:284)
root 	at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:192)
root 	at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:182)
root 	at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:25)
root 	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138)
root 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:313)
root 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:176)
root 	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:355)
root 	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
root 	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
root 	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138)
root 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:313)
root 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:176)
root 	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138)
root 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:313)
root 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:176)
root 	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
root 	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4675)
root 	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3630)
root 	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3598)
root 	at com.microsoft.azure.PolicyViolation.<init>(PolicyViolation.java:41)
root 	at com.microsoft.azure.serializer.TypedErrorInfoDeserializer.deserialize(TypedErrorInfoDeserializer.java:61)
root 	at com.microsoft.azure.serializer.TypedErrorInfoDeserializer.deserialize(TypedErrorInfoDeserializer.java:24)
root 	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:355)
root 	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
root 	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
root 	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138)
root 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:313)
root 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:176)
root 	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
root 	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4651)
root 	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2831)
root 	at com.fasterxml.jackson.core.JsonParser.readValueAs(JsonParser.java:2277)
root 	at com.microsoft.azure.serializer.CloudErrorDeserializer.deserialize(CloudErrorDeserializer.java:65)
root 	at com.microsoft.azure.serializer.CloudErrorDeserializer.deserialize(CloudErrorDeserializer.java:24)
root 	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
root 	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4675)
root 	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3630)
root 	at com.microsoft.rest.serializer.JacksonAdapter.deserialize(JacksonAdapter.java:137)
root 	at com.microsoft.azure.AzureClient.createExceptionFromResponse(AzureClient.java:820)
root 	... 54 common frames omitted
root Wrapped by: java.lang.RuntimeException: Unknown error with status code 403
root 	at com.microsoft.azure.AzureClient.createExceptionFromResponse(AzureClient.java:829)
root 	at com.microsoft.azure.AzureClient.access$100(AzureClient.java:34)
root 	at com.microsoft.azure.AzureClient$4.call(AzureClient.java:172)
root 	at com.microsoft.azure.AzureClient$4.call(AzureClient.java:169)
root 	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
root 	at retrofit2.adapter.rxjava.CallArbiter.deliverResponse(CallArbiter.java:120)
root 	at retrofit2.adapter.rxjava.CallArbiter.emitResponse(CallArbiter.java:102)
root 	at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:46)
root 	at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:24)
root 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
root 	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
root 	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
root 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
root 	at rx.internal.operators.OnSubscribeSingle.call(OnSubscribeSingle.java:81)
root 	at rx.internal.operators.OnSubscribeSingle.call(OnSubscribeSingle.java:27)
root 	at rx.internal.operators.SingleToObservable.call(SingleToObservable.java:39)
root 	at rx.internal.operators.SingleToObservable.call(SingleToObservable.java:27)
root 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
root 	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
root 	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
root 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
root 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
root 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
root 	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
root 	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
root 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
root 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
root 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
root 	at rx.internal.operators.DeferredScalarSubscriber.subscribeTo(DeferredScalarSubscriber.java:153)
root 	at rx.internal.operators.OnSubscribeTakeLastOne.call(OnSubscribeTakeLastOne.java:32)
root 	at rx.internal.operators.OnSubscribeTakeLastOne.call(OnSubscribeTakeLastOne.java:22)
root 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
root 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
root 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
root 	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
root 	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
root 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
root 	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
root 	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
root 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
root 	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
root 	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
root 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
root 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
root 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
root 	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
root 	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
root 	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
root 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
root 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
root 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
root 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
root 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
root 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
root 	at java.lang.Thread.run(Thread.java:748)
```

**To Reproduce**

1. apply a policy that forbids VMs to have a public address.
2. try to create VM  with **Azure Java SDK 1.41.2** (latest as of now)

***Code Snippet***

```
var definitions = client.virtualMachines()
          .define(name)
          .withRegion(region)
          .withExistingResourceGroup(resourceGroup)
          .withExistingPrimaryNetwork(network)
          .withSubnet(subnet)
          .withPrimaryPrivateIPAddressDynamic()
          .withNewPrimaryPublicIPAddress(name)
          .withLatestLinuxImage(image.publisherName, image.offer, image.sku)
          .withRootUsername(username)
          .withSsh(publicSshKey)
          .withSize(size)
          .withPlan(image.plan);

client.virtualMachines.create(definition);
```

**Expected behavior**

We should get a `CloudException` that should contain a `com.microsoft.azure.PolicyViolation`.

**Screenshots**
N/A

**Setup (please complete the following information):**
 - OS: any, irrelevant, happens on both Linux and MacOS
 - IDE: irrelevant, happens both in dev and in production with compiled app
 - Library/Libraries: com.microsoft.azure:azure:1.41.2
 - Java version: 8
 - App Server/Environment: irrelevant
 - Frameworks: irrelevant
  
**Additional context**
N/A

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by weidongxu-microsoft** [comment]
@slandelle 

If you are new to the SDK, you can start with the new SDK here https://aka.ms/azsdk/java/mgmt

If it is convenient for you, would you include logging of service response? This seems some mismatch of swagger specs and service response.

**Comment by slandelle** [comment]
@weidongxu-microsoft Thanks a lot for the information.
Glad 1.xx is still maintained. We'll upgrade in the next months anyway. In particular, I'm crossing fingers that with the move from RxJava to Reactor fixes the Exception causes. As you can see in the above stacktrace, causality is broken in 1.xx, eg the Jackson Exception is caused by an RxJava one, which doesn't make sense. It makes things complicated in our case as we tend to display the root cause.

**Comment by weidongxu-microsoft** [comment]
I cannot simply change the array to string, as some policy error will be like this (so it could be either string or array):
```
        {
            "result" : "True",
            "expressionKind" : "Field",
            "expression" : "Microsoft.Compute/imagePublisher",
            "path" : "properties.storageProfile.imageReference.publisher",
            "expressionValue" : "Canonical",
            "targetValue" : "Canonical",
            "operator" : "Equals"
          }, {
            "result" : "True",
            "expressionKind" : "Field",
            "expression" : "Microsoft.Compute/imageOffer",
            "path" : "properties.storageProfile.imageReference.offer",
            "expressionValue" : "UbuntuServer",
            "targetValue" : [ "UbuntuServer", "Ubuntu_Core" ],
            "operator" : "In"
          }
```

Still thinking about how to do about this... Maybe I need some customized `JsonSerialize` for this field.
