### ISSUE TITLE
[BUG] No type field available

### ISSUE THREAD

**Issue by khauser** [Azure/azure-sdk-for-java#24742]
Hi,

we have problem upgrading our current message receiver using the methods which worked before.

Message sender uses:
`compile 'com.azure:azure-messaging-servicebus:7.1.0'`

Message receiver uses:
`implementation group: 'com.azure.spring', name: 'azure-spring-boot-starter-servicebus-jms', version: "3.9.0"`

We upgraded from `compile group: 'com.microsoft.azure', name: 'azure-servicebus-jms-spring-boot-starter', version: "2.3.5"`

The receiver now complains about a missing {{type}} field.
```
org.springframework.jms.support.converter.MessageConversionException: Could not find type id property [_type] on message [ID:AMQP_NO_PREFIX:44442f21de2a4d5dbe3f92bd7afa96af] from destination [TP_request_queue]
	at org.springframework.jms.support.converter.MappingJackson2MessageConverter.getJavaTypeForMessage(MappingJackson2MessageConverter.java:456)
	at org.springframework.jms.support.converter.MappingJackson2MessageConverter.fromMessage(MappingJackson2MessageConverter.java:232)
	at org.springframework.jms.core.JmsTemplate.doConvertFromMessage(JmsTemplate.java:859)
	at org.springframework.jms.core.JmsTemplate.receiveAndConvert(JmsTemplate.java:829)
	at com.intershop.iste.message.service.azure.AzureBusService.receive(AzureBusService.java:34)
	at com.intershop.iste.message.service.azure.AzureBusMessageReceiver.receiveMessage(AzureBusMessageReceiver.java:25)
	at com.intershop.iste.message.service.MessageService.getMessage(MessageService.java:35)
	at com.intershop.iste.message.controller.AsyncMessageController.getNextMessage(AsyncMessageController.java:69)
	at com.intershop.iste.message.controller.AsyncMessageController.lambda$getMessage$1(AsyncMessageController.java:51)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at datadog.trace.bootstrap.instrumentation.java.concurrent.Wrapper.run(Wrapper.java:25)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

Do we miss something?

Best
Karsten

**Comment by joshfree** [comment]
@stliu could you please help route @khauser's issue migrating from Track1 to the new Track 2  `azure-servicebus-jms-spring-boot-starter`

**Comment by yiliuTo** [comment]
Hi @khauser thanks for reporting this, could you provide a tiny sample project reproducing this bug, which includes how you send messages to Azure Service Bus and the way you use azure-servicebus-jms-spring-boot-starter to receive and convert messags from SB?
