### ISSUE TITLE
Error where trying to copy blob -  Status code 409 - CannotVerifyCopySource - Could not verify copy source.

### ISSUE THREAD

**Issue by ihudedi** [Azure/azure-sdk-for-java#24881]
Hi,
I am trying to copy blob in azure and getting this issue.
I am using AD with secret key.
api version 12.14.0
The environment is private cloud.
I am trying to copy in same account,same container,same location only changing the file name like
from dir1/file1 to dir1/file2
and I am getting this exception.

2021-10-15 10:38:08,329 ERROR [Thread-20] (AzureWrapper:937) -  Error in AzureWrapper::renameDirFile, oldPath = '/snowflake_extractor/controlM/DMaaS/opcion00/file_platform.json', newPath = '/snowflake_extractor/controlM/DMaaS/opcion00/file_platform.json_procesado', isReplaceExisting = 'true' : Status code 409, "﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>CannotVerifyCopySource</Code><Message>Could not verify copy source.
RequestId:7c2d5e89-901e-004c-3a9f-c17a9e000000
Time:2021-10-15T08:38:08.3168607Z</Message></Error>"
com.azure.storage.blob.models.BlobStorageException: Status code 409, "﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>CannotVerifyCopySource</Code><Message>Could not verify copy source.
RequestId:7c2d5e89-901e-004c-3a9f-c17a9e000000
Time:2021-10-15T08:38:08.3168607Z</Message></Error>"
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at com.azure.core.http.rest.RestProxy.instantiateUnexpectedException(RestProxy.java:343) ~[azure-core-1.17.0.jar!/:?]
	at com.azure.core.http.rest.RestProxy.lambda$ensureExpectedStatus$5(RestProxy.java:382) ~[azure-core-1.17.0.jar!/:?]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:125) ~[reactor-core-3.4.6.jar!/:3.4.6]
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1815) ~[reactor-core-3.4.6.jar!/:3.4.6]
	at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.signalCached(MonoCacheTime.java:337) ~[reactor-core-3.4.6.jar!/:3.4.6]
	at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.onNext(MonoCacheTime.java:354) ~[reactor-core-3.4.6.jar!/:3.4.6]
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2397) ~[reactor-core-3.4.6.jar!/:3.4.6]
	at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.onSubscribe(MonoCacheTime.java:293) ~[reactor-core-3.4.6.jar!/:3.4.6]
	at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:192) ~[reactor-core-3.4.6.jar!/:3.4.6]
	at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53) ~[reactor-core-3.4.6.jar!/:3.4.6]
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57) ~[reactor-core-3.4.6.jar!/:3.4.6]
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) ~[reactor-core-3.4.6.jar!/:3.4.6]
	at reactor.core.publisher.MonoCacheTime.subscribeOrReturn(MonoCacheTime.java:143) ~[reactor-core-3.4.6.jar!/:3.4.6]
	at reactor.core.publisher.Mono.subscribe(Mono.java:4135) ~[reactor-core-3.4.6.jar!/:3.4.6]
	at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:203) ~[reactor-core-3.4.6.jar!/:3.4.6]
	at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53) ~[reactor-core-3.4.6.jar!/:3.4.6]
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57) ~[reactor-core-3.4.6.jar!/:3.4.6]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157) ~[reactor-core-3.4.6.jar!/:3.4.6]
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:120) ~[reactor-core-3.4.6.jar!/:3.4.6]
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79) ~[reactor-core-3.4.6.jar!/:3.4.6]
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1815) ~[reactor-core-3.4.6.jar!/:3.4.6]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151) ~[reactor-core-3.4.6.jar!/:3.4.6]
	at reactor.core.publisher.FluxDelaySubscription$DelaySubscriptionMainSubscriber.onNext(FluxDelaySubscription.java:188) ~[reactor-core-3.4.6.jar!/:3.4.6]
	at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:99) ~[reactor-core-3.4.6.jar!/:3.4.6]
	at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:99) ~[reactor-core-3.4.6.jar!/:3.4.6]
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.onNext(FluxTimeout.java:179) ~[reactor-core-3.4.6.jar!/:3.4.6]
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1815) ~[reactor-core-3.4.6.jar!/:3.4.6]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151) ~[reactor-core-3.4.6.jar!/:3.4.6]
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.complete(MonoIgnoreThen.java:284) ~[reactor-core-3.4.6.jar!/:3.4.6]
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onNext(MonoIgnoreThen.java:187) ~[reactor-core-3.4.6.jar!/:3.4.6]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:127) ~[reactor-core-3.4.6.jar!/:3.4.6]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:127) ~[reactor-core-3.4.6.jar!/:3.4.6]
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1815) ~[reactor-core-3.4.6.jar!/:3.4.6]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151) ~[reactor-core-3.4.6.jar!/:3.4.6]
	at reactor.core.publisher.MonoCreate$DefaultMonoSink.success(MonoCreate.java:160) ~[reactor-core-3.4.6.jar!/:3.4.6]
	at com.azure.core.http.okhttp.OkHttpAsyncHttpClient$OkHttpCallback.onResponse(OkHttpAsyncHttpClient.java:191) ~[azure-core-http-okhttp-1.7.1.jar!/:?]
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519) ~[okhttp-4.8.1.jar!/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) ~[?:?]
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99) ~[reactor-core-3.4.6.jar!/:3.4.6]
		at reactor.core.publisher.Mono.block(Mono.java:1703) ~[reactor-core-3.4.6.jar!/:3.4.6]
		at com.azure.core.util.polling.PollerFlux.lambda$new$1(PollerFlux.java:95) ~[azure-core-1.17.0.jar!/:?]
		at com.azure.core.util.polling.DefaultSyncPoller.<init>(DefaultSyncPoller.java:71) ~[azure-core-1.17.0.jar!/:?]
		at com.azure.core.util.polling.PollerFlux.getSyncPoller(PollerFlux.java:230) ~[azure-core-1.17.0.jar!/:?]
		at com.azure.storage.blob.specialized.BlobClientBase.beginCopy(BlobClientBase.java:443) ~[azure-storage-blob-12.12.0.jar!/:?]
		at com.azure.storage.blob.specialized.BlobClientBase.beginCopy(BlobClientBase.java:417) ~[azure-storage-blob-12.12.0.jar!/:?]
		at com.azure.storage.blob.specialized.BlobClientBase.beginCopy(BlobClientBase.java:376) ~[azure-storage-blob-12.12.0.jar!/:?]
		at com.bmc.cm.aft.client.wrapper.AzureWrapper.copyBlob(AzureWrapper.java:947) ~[classes!/:?]
		at com.bmc.cm.aft.client.wrapper.AzureWrapper.renameDirFile(AzureWrapper.java:927) [classes!/:?]
		at com.bmc.cm.aft.client.PostActions.runFileActionPostTransfer(PostActions.java:367) [classes!/:?]
		at com.bmc.cm.aft.client.PostActions.sourceFileActionPostTransfer(PostActions.java:283) [classes!/:?]
		at com.bmc.cm.aft.client.PostActions.postActionsTransferSucceed(PostActions.java:106) [classes!/:?]
		at com.bmc.cm.aft.client.PostActions.run(PostActions.java:63) [classes!/:?]
		at com.bmc.cm.aft.client.FileCopy.run(FileCopy.java:1430) [classes!/:?]
		at com.bmc.cm.aft.client.MultiFileCopy.copySingleFile(MultiFileCopy.java:679) [classes!/:?]
		at com.bmc.cm.aft.client.MultiFileCopy.copy(MultiFileCopy.java:149) [classes!/:?]
		at com.bmc.cm.aft.client.FTCTransfer.copyMultipleFiles(FTCTransfer.java:1040) [classes!/:?]
		at com.bmc.cm.aft.client.FTCTransfer.copy(FTCTransfer.java:772) [classes!/:?]
		at com.bmc.cm.aft.client.FTCTransfer.runCopy(FTCTransfer.java:372) [classes!/:?]
		at com.bmc.cm.aft.client.FTCTransfer.run(FTCTransfer.java:301) [classes!/:?]
		at com.bmc.cm.aft.client.SubtaskRunner.run(SubtaskRunner.java:599) [classes!/:?]
		at com.bmc.cm.aft.client.FTCHandler.runSubTasks(FTCHandler.java:400) [classes!/:?]
		at com.bmc.cm.aft.client.FTCHandler.runJob(FTCHandler.java:197) [classes!/:?]
		at com.bmc.cm.aft.jobmanagement.JobObjectImpl$JobRunnerThread.run(JobObjectImpl.java:366) [classes!/:?]

Do you know what is the error means and how to solve this issue ?
Thanks,
Itay

**Comment by rickle-msft** [comment]
Hi, @ihudedi. This generally means that there's not enough information to validate you are authorized to read the blob source. With Sas and AD, the authentication method used for the request ensures you are able to write at the destination, but it does not guarantee permissions on the source, even if it is in the same container. (SharedKey can apply to both in the same location). Typically the url to the source should have a sas token attached to it. Could you please try that and let me know?

**Comment by ihudedi** [comment]
Hi @rickle-msft 
Here is the code
    String sourceUrl = blobClientOld.getBlobUrl();
  
                logger.info("AzureWrapper::copyBlob - generateUserDelegationSas using "+azureCredentialMethod);
                OffsetDateTime startTime = OffsetDateTime.now();
                OffsetDateTime expiryTime = startTime.plusDays(1);
                BlobSasPermission permission = new BlobSasPermission().setReadPermission(true);
                UserDelegationKey userDelegationKey = blobServiceClient.getUserDelegationKey(startTime, expiryTime);
                String sas = blobClientOld.generateUserDelegationSas(new BlobServiceSasSignatureValues(expiryTime, permission).setStartTime(startTime), userDelegationKey);
                sourceUrl = blobClientOld.getBlobUrl() + "?" + sas;
            }
        }
        logger.debug(String.format("Attempting to copy object with path '%s' to path '%s'", blobClientOld.getBlobName(), blobClientNew.getBlobName()));
        SyncPoller<BlobCopyInfo, Void> syncPoller = blobClientNew.beginCopy(sourceUrl, null);
        PollResponse<BlobCopyInfo> pollResponse = syncPoller.waitForCompletion(Duration.ofSeconds(azureCopyBlobOperationTimeoutInSeconds));
        if (pollResponse != null && pollResponse.getStatus() != LongRunningOperationStatus.SUCCESSFULLY_COMPLETED) {
            throw new AzureException(String.format("Failed to copy object with path '%s' to path '%s' with error '%s'", blobClientOld.getBlobName(),
                    blobClientNew.getBlobName(), (pollResponse.getValue() != null ? pollResponse.getValue().getError() : "")));
        }
        logger.debug(String.format("End AzureWrapper::copyBlob - Copying object with old path '%s' to new path '%s' succeeded", blobClientOld.getBlobName(), blobClientNew.getBlobName()));
    }
And we use secret kay and failed in :
tatus code 409, "?<?xml version="1.0" encoding="utf-8"?><Erro\

r><Code>CannotVerifyCopySource</Code><Message>Could not verify copy source.

RequestId:e47d3605-c01e-0023-6015-da706d000000

Time:2021-11-15T11:36:45.6825717Z</Message></Error>"

**Comment by rickle-msft** [comment]
Hi, @ihudedi. I was able to successfully run your code without hitting any auth errors. The only thing that really may be different is how you're constructing your old blob client. There may also be a question of what permissions your application has and what client you're using to generate the delegation key.

```
def oauthClient = getOAuthServiceClient() // Constructs credentials using client secret, client id, and tenant id
        oauthClient.getProperties() // authentication check
        def oauthBlobClient = oauthClient.getBlobContainerClient(cc.getBlobContainerName()).getBlobClient(bc.getBlobName())
        def blobClientNew = oauthClient.getBlobContainerClient(cc.getBlobContainerName()).getBlobClient(generateBlobName())
        OffsetDateTime startTime = OffsetDateTime.now()
        OffsetDateTime expiryTime = startTime.plusDays(1)
        BlobSasPermission permission = new BlobSasPermission().setReadPermission(true)
        UserDelegationKey userDelegationKey = oauthClient.getUserDelegationKey(startTime, expiryTime)
        String sas = oauthBlobClient
            .generateUserDelegationSas(new BlobServiceSasSignatureValues(expiryTime, permission).setStartTime(startTime), userDelegationKey);
        def sourceUrl = oauthBlobClient.getBlobUrl() + "?" + sas;

        SyncPoller<BlobCopyInfo, Void> syncPoller = blobClientNew.beginCopy(sourceUrl, null);
        PollResponse<BlobCopyInfo> pollResponse = syncPoller.waitForCompletion(Duration.ofSeconds(10));
        if (pollResponse != null && pollResponse.getStatus() != LongRunningOperationStatus.SUCCESSFULLY_COMPLETED) {
            throw new AzureException("fail");
        }
```

**Comment by ihudedi** [comment]
Hi @rickle-msft 
The blobClient is done via blobContainerClient.getBlobClient(path);
blobContainerClient = blobServiceClient.getBlobContainerClient(containerName);
I am building the serviceclient according to the client id secret key and tenant id
What permission should I add to the application?
I already have
Azure Active Directroy -> App Registration -> App -> Api permission - Add Microsoft Graph ( User.Read) and Azure Storage (user_impersonation) and press on grand admin consent for Default directory for all of those permissions.
Storage Account -> 	account -> Access Control (IAM) -> Add role Assignment -> (to user logged in  and application and for system/user managed identity) - Storage Blob Data Contributor role.

**Comment by rickle-msft** [comment]
My app registration has the Storage Blob Data Reader role, the Storage Blob Data Owner role, and Storage Blob Delegator role as well.

**Comment by ihudedi** [comment]
Hi @rickle-msft 
What do we do for copy blob when using credentials as Shared Access Signature?
generateSas method is valid for Shared Key
and generateUserDelegationSas valid for TokenCredential
Thanks,
Itay

**Comment by rickle-msft** [comment]
Hi, @ihudedi 
I'm not sure I understand how your most recent question is different from what we have already been discussing here? "What do we do for copy blob when using credentials as Shared Access Signature?" Ensure the key used to generate the sas token has the right permissions (my previous comment). Ensure the sas token itself has the right permissions. Ensure the sastoken is attached to the sourceUrl parameter. 

I am not sure what you are getting at by saying this?

> generateSas method is valid for Shared Key
generateUserDelegationSas valid for token credential only

**Comment by ihudedi** [comment]
Hi @rickle-msft
When connecting to azure with sas token.Is this the sas token we provide to the source url when copying blob.? For other credentials we genenerate the sas token but now I have it so I take this  token to the source url when coping blob?
Thanks,
Itay

**Comment by rickle-msft** [comment]
If you want to authenticate entirely with sas tokens when doing a copy, there has to be a sas token in two places. 1) On the destination url 2) on the source url. They can be the same sas token if one sas token has authorization for both resources or they can be different sas tokens if they are each scoped to one resource. 

Does that answer your question?

**Comment by ihudedi** [comment]
Hi @rickle-msft
I connect the blob using sas token.
When I copy blob should I add the token to source url and destination url? 
What about if I connect via shared key.should I add sas token to source url and destination url also?
You told me in the previous messages only attach the sas to source url.
Thanks,
Itay.

**Comment by rickle-msft** [comment]
There are two ways of authenticating these requests.
- Shared key can authorize the destination (the target of the request). If the source is in the same account, shared key can also authorize the source (method parameter) with no extra steps. If the source is in a different account, the source must be authorized via an attached sas token
- Sas can be used to authorize the destination by attaching it to the destination (target) url. Sas can also be used to authorize the source as mentioned. They need not be distinct sas tokens if its permissions are sufficient, but it must be present in both urls in this case.

The same information said another way that each url must be authorized for the request to succeed:
- The destination url can be authorized with the signature set on the authorization header (shared key set on the builder). Or it can be authorized with a sas token.
- The source url can can be authenticated with the authorization header on the request if it is in the same account as the destination. Otherwise, it must have a sas token attached.


I only mentioned adding the sas to the source url because I presumed you already had it attached to the destination as well. That seems to have been an incorrect assumption and I apologize.

**Comment by amishra-dev** [comment]
Please let us know if you are still having this issue.
