### ISSUE TITLE
[BUG] com.azure.resourcemanager.appservice.fluent.WebAppsClient / getBackupConfiguration(String,String) fails with Reader role

### ISSUE THREAD

**Issue by luisCavalcantiDev** [Azure/azure-sdk-for-java#24893]
**Describe the bug**
com.azure.resourcemanager.appservice.fluent.WebAppsClient / getBackupConfiguration(String, String) fails with Reader role (or Security Reader and Log Analytics Reader roles)

Response: AuthorizationFailed to perform action API 'Microsoft.Web/sites/config/list/action' using service principal with role Reader or roles Security Reader and Log Analytics Reader 

***Exception or Stack Trace***
com.azure.resourcemanager.appservice.models.DefaultErrorResponseErrorException: Status code 403, "{"error":{"code":"AuthorizationFailed","message":"The client 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx' with object id 'yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy' does not have authorization to perform action 'Microsoft.Web/sites/config/list/action' over scope '/subscriptions/ssssssss-ssss-ssss-ssss-ssssssssssss/resourceGroups/rg-appservices/providers/Microsoft.Web/sites/app-dev-001/config/backup' or the scope is invalid. If access was recently granted, please refresh your credentials."}}": The client 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx' with object id 'yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy' does not have authorization to perform action 'Microsoft.Web/sites/config/list/action' over scope '/subscriptions/ssssssss-ssss-ssss-ssss-ssssssssssss/resourceGroups/rg-appservices-mp-rules/providers/Microsoft.Web/sites/app-dev-001/config/backup' or the scope is invalid. If access was recently granted, please refresh your credentials.
	at com.azure.core.http.rest.RestProxy.instantiateUnexpectedException(RestProxy.java:365)
	at com.azure.core.http.rest.RestProxy.lambda$ensureExpectedStatus$5(RestProxy.java:405)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:125)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
	at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.signalCached(MonoCacheTime.java:337)
	at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.onNext(MonoCacheTime.java:354)
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2398)
	at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.onSubscribe(MonoCacheTime.java:293)
	at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:192)
	at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at reactor.core.publisher.MonoCacheTime.subscribeOrReturn(MonoCacheTime.java:143)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157)
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2398)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onSubscribe(MonoFlatMap.java:110)
	at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:55)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:120)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:120)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.complete(MonoIgnoreThen.java:284)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onNext(MonoIgnoreThen.java:187)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:249)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:127)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
	at reactor.core.publisher.MonoCollect$CollectSubscriber.onComplete(MonoCollect.java:159)
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2400)
	at reactor.core.publisher.MonoCollect$CollectSubscriber.onSubscribe(MonoCollect.java:103)
	at reactor.core.publisher.FluxJust.subscribe(FluxJust.java:68)
	at reactor.core.publisher.FluxDefer.subscribe(FluxDefer.java:54)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157)
	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:180)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:249)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.complete(MonoIgnoreThen.java:284)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onNext(MonoIgnoreThen.java:187)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:232)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:203)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onComplete(FluxDoFinally.java:145)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.checkTerminated(FluxFlatMap.java:846)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:608)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.drain(FluxFlatMap.java:588)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onComplete(FluxFlatMap.java:465)
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2400)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onSubscribe(FluxFlatMap.java:371)
	at reactor.core.publisher.FluxJust.subscribe(FluxJust.java:68)
	at reactor.core.publisher.FluxDefer.subscribe(FluxDefer.java:54)
	at reactor.core.publisher.Flux.subscribe(Flux.java:8411)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:255)
	at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.complete(MonoIgnoreThen.java:284)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onNext(MonoIgnoreThen.java:187)
	at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:99)
	at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.onNext(FluxRetryWhen.java:174)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
	at reactor.core.publisher.Operators$MonoInnerProducerBase.complete(Operators.java:2664)
	at reactor.core.publisher.MonoSingle$SingleSubscriber.onComplete(MonoSingle.java:180)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onComplete(MonoFlatMapMany.java:260)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onComplete(FluxMapFuseable.java:150)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onComplete(FluxMapFuseable.java:150)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1817)
	at reactor.core.publisher.MonoCollect$CollectSubscriber.onComplete(MonoCollect.java:159)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onComplete(FluxDoFinally.java:145)
	at reactor.core.publisher.FluxHandle$HandleSubscriber.onComplete(FluxHandle.java:213)
	at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onComplete(FluxMap.java:269)
	at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:400)
	at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:419)
	at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:473)
	at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:684)
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:93)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1373)
	at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1247)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1287)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
		at reactor.core.publisher.Mono.block(Mono.java:1704)
		at com.azure.resourcemanager.appservice.implementation.WebAppsClientImpl.getBackupConfiguration(WebAppsClientImpl.java:12530)

**Steps To Reproduce**
1 - Creata a service principal with role Reader or roles Security Reader and Log Analytics Reader;
2 - Create AppServiceManager service instance with service principal credentials;
3 - Call API getBackupConfiguration
    
Response:
Status code 403, "{"error":{"code":"AuthorizationFailed","message":"The client 'xxxxxxxx-xxxx-xxxx-xxxx' with object id 'yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy' does not have authorization to perform action 'Microsoft.Web/sites/config/list/action' over scope '/subscriptions/ssssssss-ssss-ssss-ssss-ssssssssssss/resourceGroups/rg-appservices-mp-rules/providers/Microsoft.Web/sites/app-dev-001/config/backup' or the scope is invalid. If access was recently granted, please refresh your credentials."}}": The client 'xxxxxxxx-xxxx-xxxx-xxxx' with object id 'yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy' does not have authorization to perform action 'Microsoft.Web/sites/config/list/action' over scope '/subscriptions/ssssssss-ssss-ssss-ssss-ssssssssssss/resourceGroups/rg-appservice/providers/Microsoft.Web/sites/app-dev-001/config/backup' or the scope is invalid. If access was recently granted, please refresh your credentials.

***Code Snippet***
appService.serviceClient()
    .getWebApps()
    .getBackupConfiguration("rg-appservice", "app-dev-001")

**Expected behavior**
Response with status code 200 (GET) for API call com.azure.resourcemanager.appservice.fluent.WebAppsClient / getBackupConfiguration(String, String) using service principal with Reader role or Security Reader and Log Analytics Reader roles 

**Screenshots**
Not applicable.

**Setup (please complete the following information):**
 - OS: Linux
 - IDE: Apache NetBeans 12.4
 - Library/Libraries: azure-resourcemanager-appservice: 2.8.0
 - Java version: 8
 - Frameworks: Play! Framework 1.5

**Additional context**
It seems related to #1874
Also trying to do this API call using Azure CLI v2.17.0, using same service principal credential with Reader and Security Reader / Log Analytics Reader roles:

az webapp config backup show --resource-group rg-appservices --webapp-name app-dev-001

Works without requesting any permissions

**Comment by luisCavalcantiDev** [comment]
@weidongxu-microsoft
Thank you for reply

I've tried with --debug in CLI (tried here with 2.17.0 and 2.29.0), with service principal credentials with Reader role

az webapp config backup show --resource-group rg-appservice --webapp-name app-dev-001 --debug

cli.knack.cli: Command arguments: ['webapp', 'config', 'backup', 'show', '--resource-group', 'rg-appservice', '--webapp-name', 'app-dev-001', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7f16eeabbbf8>, <function OutputProducer.on_global_arguments at 0x7f16ee9e8730>, <function CLIQuery.on_global_arguments at 0x7f16eea08840>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'webapp': ['azure.cli.command_modules.appservice']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: appservice                0.242        65       233
cli.azure.cli.core: Total (1)                 0.242        65       233
cli.azure.cli.core: Loaded 65 groups, 233 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : webapp config backup show
cli.azure.cli.core: Command table: webapp config backup show
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7f16ee48c158>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/home/luisdev/.azure/commands/2021-10-20.11-46-22.webapp_config_backup_show.6785.log'.
az_command_data_logger: command args: webapp config backup show --resource-group {} --webapp-name {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7f16ee4b10d0>, <function register_global_query_examples_argument.<locals>.register_query_examples at 0x7f16ee402378>]
cli.azure.cli.core.util: attempting to read file /opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/resources/WindowsFunctionsStacks.json as utf-8-sig
cli.azure.cli.core.util: attempting to read file /opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/resources/LinuxFunctionsStacks.json as utf-8-sig
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7f16ee402400>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7f16ee402510>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7f16ee9e87b8>, <function CLIQuery.handle_query_parameter at 0x7f16eea088c8>, <function register_global_query_examples_argument.<locals>.handle_example_parameter at 0x7f16ee4022f0>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7f16ee402488>]
cli.azure.cli.core.commands.client_factory: Getting management service client client_type=WebSiteManagementClient
cli.azure.cli.core.adal_authentication: AdalAuthentication.get_token invoked by Track 2 SDK with scopes=('https://management.core.windows.net//.default',)
cli.azure.cli.core._profile: Retrieving token from ADAL for resource 'https://management.core.windows.net/'
cli.azure.cli.core.util: attempting to read file /home/luisdev/.azure/accessTokens.json as utf-8-sig
adal-python: b1c3e7d5-e014-4c24-adf6-2a8551877983 - Authority:Performing instance discovery: ...
adal-python: b1c3e7d5-e014-4c24-adf6-2a8551877983 - Authority:Performing static instance discovery
adal-python: b1c3e7d5-e014-4c24-adf6-2a8551877983 - Authority:Authority validated via static instance discovery
adal-python: b1c3e7d5-e014-4c24-adf6-2a8551877983 - TokenRequest:Getting token from cache with refresh if necessary.
adal-python: b1c3e7d5-e014-4c24-adf6-2a8551877983 - CacheDriver:finding with query keys: {'_clientId': '...', 'userId': '...'}
adal-python: b1c3e7d5-e014-4c24-adf6-2a8551877983 - CacheDriver:Looking for potential cache entries: {'_clientId': '...', 'userId': '...'}
adal-python: b1c3e7d5-e014-4c24-adf6-2a8551877983 - CacheDriver:Found 2 potential entries.
adal-python: b1c3e7d5-e014-4c24-adf6-2a8551877983 - CacheDriver:Resource specific token found.
adal-python: b1c3e7d5-e014-4c24-adf6-2a8551877983 - CacheDriver:Returning token from cache lookup, AccessTokenId: b'4fJsdRn1gaW28jtDsntGuqg7Jp8y9j9sFQPZGvh8kN8=', RefreshTokenId: b'cgHzOZYBwP+jAAgbGEljFqPF/hXsxFmPP5TTaRokS5c='
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxx/resourceGroups/rg-appservice/providers/Microsoft.Web/sites/app-dev-001/config/backup/list?api-version=2020-09-01'
cli.azure.cli.core.sdk.policies: Request method: 'POST'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
cli.azure.cli.core.sdk.policies:     'CommandName': 'webapp config backup show'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--resource-group --webapp-name --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.29.0 (DEB) azsdk-python-azure-mgmt-web/4.0.0 Python/3.6.10 (Linux-4.19.128-microsoft-standard-x86_64-with-debian-bullseye-sid)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "POST /subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxx/resourceGroups/rg-appservice/providers/Microsoft.Web/sites/app-dev-001/config/backup/list?api-version=2020-09-01 HTTP/1.1" 200 None
cli.azure.cli.core.sdk.policies: Response status: 200
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Transfer-Encoding': 'chunked'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Content-Encoding': 'gzip'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'Vary': 'Accept-Encoding'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': 'ff6abb9d-8a13-4d6c-9ef3-49c422692362'
cli.azure.cli.core.sdk.policies:     'Server': 'Microsoft-IIS/10.0'
cli.azure.cli.core.sdk.policies:     'X-AspNet-Version': '4.0.30319'
cli.azure.cli.core.sdk.policies:     'X-Powered-By': 'ASP.NET'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-resource-requests': '11999'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '84a4f486-98fc-4c59-8871-5e3fc232101e'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'BRAZILSOUTH:20211020T144624Z:84a4f486-98fc-4c59-8871-5e3fc232101e'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Wed, 20 Oct 2021 14:46:24 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"id":"/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxx/resourceGroups/rg-appservice/providers/Microsoft.Web/sites/app-dev-001","name":"app-dev-001","type":"Microsoft.Web/sites","location":"East US","properties":{"name":"app-dev-001","backupName":"app-dev-001","enabled":true,"storageAccountUrl":"https://cs2100320010820c1d9.blob.core.windows.net/backup?sp=rwdl&st=2021-10-20T11:44:59Z&se=2295-08-04T11:44:59Z&sv=2020-08-04&sr=c&sig=0q%2Fxus2wrj9JalPysU6VL%2B0Zt6u34tO33Pjq1KxTnDY%3D","backupSchedule":{"frequencyInterval":1,"frequencyUnit":"Day","keepAtLeastOneBackup":true,"retentionPeriodInDays":30,"startTime":"2021-10-20T11:44:59.956","lastExecutionTime":"2021-10-20T11:45:12.6055501"},"databases":[],"type":"Default","mySqlDumpParams":null}}
cli.knack.cli: Event: CommandInvoker.OnTransformResult [<function _resource_group_transform at 0x7f16ee461d90>, <function _x509_from_base64_to_hex_transform at 0x7f16ee461e18>]
cli.knack.cli: Event: CommandInvoker.OnFilterResult []
{
  "backupName": "app-dev-001",
  "backupSchedule": {
    "frequencyInterval": 1,
    "frequencyUnit": "Day",
    "keepAtLeastOneBackup": true,
    "lastExecutionTime": "2021-10-20T11:45:12.605550",
    "retentionPeriodInDays": 30,
    "startTime": "2021-10-20T11:44:59.956000"
  },
  "databases": [],
  "enabled": true,
  "id": "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxx/resourceGroups/rg-appservice/providers/Microsoft.Web/sites/app-dev-001",
  "kind": null,
  "location": "East US",
  "name": "app-dev-001",
  "resourceGroup": "rg-appservice",
  "storageAccountUrl": "https://test.blob.core.windows.net/backup?sp=rwdl&st=2021-10-20T11:44:59Z&se=2295-08-04T11:44:59Z&sv=2020-08-04&sr=c&sig=0q%2Fxus2wrj9JalPysU6VL%2B0Zt6u34tO33Pjq1KxTnDY%3D",
  "systemData": null,
  "type": "Microsoft.Web/sites"
}
cli.knack.cli: Event: Cli.SuccessfulExecute []
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7f16ee48c378>]
az_command_data_logger: exit code: 0
cli.__main__: Command ran in 2.098 seconds (init: 0.275, invoke: 1.822)
telemetry.save: Save telemetry record of length 3037 in cache
telemetry.check: Negative: The /home/luisdev/.azure/telemetry.txt was modified at 2021-10-20 11:45:49.516753, which in less than 600.000000 s

As you can see, it works without fail permissions for me, different from using SDK.

**Comment by weidongxu-microsoft** [comment]
CLI logged `Returning token from cache lookup` so I am not really sure whether it uses new token, or existing one.

Anyway I will involve service for response.

**Comment by weidongxu-microsoft** [comment]
## To app service

API call to `Microsoft.Web/sites/config/list` returns 403 AuthorizationFailed when service principal has Reader role.

Same service principal works on API call to `Microsoft.Web/sites`.

**Comment by weidongxu-microsoft** [comment]
@AzureAppServiceCLI, @antcp
Any update?

**Comment by luisCavalcantiDev** [comment]
Hi,
Any update?

**Comment by weidongxu-microsoft** [comment]
@AzureAppServiceCLI, @antcp
Any update?

**Comment by luisCavalcantiDev** [comment]
Hi @weidongxu-microsoft 

I've checked new verision SDK (azure-resourcemanager-appservice: 2.11.0 ). Unfortunately, I'm still getiing same error reported on this issue.

**Comment by weidongxu-microsoft** [comment]
@luisCavalcantiDev the RBAC is service behavior, and SDK not able to do anything about it. Pinging service.

https://github.com/AzureAppServiceCLI, @antcp
Any update from service?

**Comment by luisCavalcantiDev** [comment]
Thanks for your help @weidongxu-microsoft

BTW, I've noticed that if an app has a lock, it's not possible to read it from getBackupConfiguration API neither.

API throws com.azure.resourcemanager.appservice.models.DefaultErrorResponseErrorException with HttpResponse body:

Status code 409, "{"error":{"code":"ScopeLocked","message":"The scope '/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/rg-appservices/providers/Microsoft.Web/sites/app-dev-001/config/backup' cannot perform write operation because following scope(s) are locked: '/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/rg-appservices'. Please remove the lock and try again."}}": The scope '/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/rg-appservices/providers/Microsoft.Web/sites/app-dev-001/config/backup' cannot perform write operation because following scope(s) are locked: '/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/rg-appservices'. Please remove the lock and try again.

**Comment by luisCavalcantiDev** [comment]
hey guys,

any update?

**Comment by weidongxu-microsoft** [comment]
I was pinging in internal thread, but not hear back yet.

Webapp service is a big team and sometimes it is hard to find who owns it...

**Comment by weidongxu-microsoft** [comment]
@luisCavalcantiDev 

Get feedback.
We missed that this method is a POST, which is protected in ARM. Reader role will get work.
I assume the reason is that its response may contain storage account URI, which could be a secret. Hence the POST.
You might need higher role for this, maybe Website Contributor?

**Comment by luisCavalcantiDev** [comment]
Thank you for the feedback @weidongxu-microsoft 

It seems not right a POST method related with GET method during getBackup() API call. Also using a Contributor role is not the user case, Reader role should be used for all read operations.

I've noticed that appService API authSettings() melthord call has same problem using Reader role. However, appService API exposes auhSettingsV2() call and it works just fine using same Reader role. I've tried to undestand how auhSettingsV2 API call works iand the differences between them, maybe we can think about have a getBackupConfigurationV2() that works with GET operations on Reader role. 

Do you think we could check it with Webapp service team?

**Comment by weidongxu-microsoft** [comment]
From what I heard, GET method on `authSettingsV2` was actually wrong in the first place. Service is trying to fix it without breaking existing user.
