### ISSUE TITLE
[BUG] Getting "Issuer validation failed. Issuer did not match." while connecting to Storage account using MSI

### ISSUE THREAD

**Issue by eggboy** [Azure/azure-sdk-for-java#24926]
**Describe the bug**
Hi, 

I was trying to listBlobs inside the pod on AKS that is configured with Pod Identity, and it throws an error "Issuer validation failed. Issuer did not match"  I can verify from the log that ManagedIdentityCredential can successfully connect to IMDS. 

2021-10-20 16:23:19.901  INFO 1 --- [     parallel-1] c.a.identity.ManagedIdentityCredential   : Azure Identity => Managed Identity environment: AZURE VM IMDS ENDPOINT
2021-10-20 16:23:19.901  INFO 1 --- [     parallel-1] c.a.identity.ManagedIdentityCredential   : Azure Identity => getToken() result for scopes [https://storage.azure.com/.default]: SUCCESS
 
'az login' and 'az storage container list' work just fine that it is not just roles-related issue. 

***Exception or Stack Trace***

`com.azure.storage.blob.models.BlobStorageException: Status code 401, "?<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidAuthenticationInfo</Code><Message>Server failed to authenticate the request. Please refer to the information in the www-authenticate header.
RequestId:bef2d353-601e-000a-06ce-c5ce49000000
Time:2021-10-20T16:23:21.4313342Z</Message><AuthenticationErrorDetail>Issuer validation failed. Issuer did not match.</AuthenticationErrorDetail></Error>"
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[na:na]
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source) ~[na:na]
	at com.azure.core.http.rest.RestProxy.instantiateUnexpectedException(RestProxy.java:365) ~[azure-core-1.20.0.jar:1.20.0]
	at com.azure.core.http.rest.RestProxy.lambda$ensureExpectedStatus$5(RestProxy.java:405) ~[azure-core-1.20.0.jar:1.20.0]`

....

**Comment by joshfree** [comment]
@g2vinay could you please take a quick look and follow up with @eggboy?

/cc @billwert

**Comment by g2vinay** [comment]
@eggboy 
The Azure Identity SDK is successfully able to retrieve a token as per the logs.
The 401 returned seems to be a service related issue. 
Can you ensure that you've assigned RBAC permissions to the user assigned Identity linked to your Pod Identity ?

If you still continue to get the 401, then this is a service bug.
Looping in @rickle-msft  to get the service attention for this.
