### ISSUE TITLE
[BUG] The lock supplied is invalid. Either the lock expired--LockRenewalOperation always failure

### ISSUE THREAD

**Issue by parkybyang** [Azure/azure-sdk-for-java#25121]
**Describe the bug**
Suppose all retryOptions and Topic properties as default and maxAutoLockRenewDuration(Duration.ofHours(2)), after 30s locking of message, and client start to renew msg lock, below error occurs ALWAYS.
***Exception or Stack Trace***
09:50:38.922 [reactor-executor-3] WARN class com.azure.messaging.servicebus.implementation.ManagementChannel<junit_business_process_topic/subscriptions/all_messages> - status[GONE] description[The lock supplied is invalid. Either the lock expired, or the message has already been removed from the queue. For more information please see https://aka.ms/ServiceBusExceptions . Reference:e4942427-bc27-48e1-ae30-59ad1740749d, TrackingId:d953ffd6-6def-4c7c-89e2-43dd0af8c8cc_B31, SystemTracker:boeing:Topic:junit_business_process_topic|all_messages, Timestamp:2021-11-01T01:50:37] condition[com.microsoft:message-lock-lost] Operation not successful.
09:50:38.923 [reactor-executor-3] ERROR com.azure.messaging.servicebus.LockRenewalOperation - token[{}]. Error occurred while renewing lock token.
The lock supplied is invalid. Either the lock expired, or the message has already been removed from the queue. For more information please see https://aka.ms/ServiceBusExceptions . Reference:e4942427-bc27-48e1-ae30-59ad1740749d, TrackingId:d953ffd6-6def-4c7c-89e2-43dd0af8c8cc_B31, SystemTracker:boeing:Topic:junit_business_process_topic|all_messages, Timestamp:2021-11-01T01:50:37, errorContext[NAMESPACE: boeing.servicebus.windows.net. ERROR CONTEXT: N/A, PATH: junit_business_process_topic/subscriptions/all_messages/$management, REFERENCE_ID: junit_business_process_topic/subscriptions/all_messages-mgmt:receiver, LINK_CREDIT: 2]
com.azure.messaging.servicebus.ServiceBusException: The lock supplied is invalid. Either the lock expired, or the message has already been removed from the queue. For more information please see https://aka.ms/ServiceBusExceptions . Reference:e4942427-bc27-48e1-ae30-59ad1740749d, TrackingId:d953ffd6-6def-4c7c-89e2-43dd0af8c8cc_B31, SystemTracker:boeing:Topic:junit_business_process_topic|all_messages, Timestamp:2021-11-01T01:50:37, errorContext[NAMESPACE: boeing.servicebus.windows.net. ERROR CONTEXT: N/A, PATH: junit_business_process_topic/subscriptions/all_messages/$management, REFERENCE_ID: junit_business_process_topic/subscriptions/all_messages-mgmt:receiver, LINK_CREDIT: 2]
        at com.azure.messaging.servicebus.implementation.ManagementChannel.mapError(ManagementChannel.java:241)
        at reactor.core.publisher.Mono.lambda$onErrorMap$31(Mono.java:3676)
        at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94)
        at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onError(Operators.java:2063)
        at reactor.core.publisher.FluxHandle$HandleSubscriber.onError(FluxHandle.java:203)
        at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:125)
        at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.complete(MonoIgnoreThen.java:284)
        at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onNext(MonoIgnoreThen.java:187)
        at reactor.core.publisher.MonoCreate$DefaultMonoSink.success(MonoCreate.java:160)
        at com.azure.core.amqp.implementation.RequestResponseChannel.settleMessage(RequestResponseChannel.java:365)
        at com.azure.core.amqp.implementation.RequestResponseChannel.lambda$new$0(RequestResponseChannel.java:151)
        at reactor.core.publisher.LambdaSubscriber.onNext(LambdaSubscriber.java:160)
        at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:120)
        at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:200)
        at reactor.core.publisher.EmitterProcessor.drain(EmitterProcessor.java:491)
        at reactor.core.publisher.EmitterProcessor.tryEmitNext(EmitterProcessor.java:299)
        at reactor.core.publisher.SinkManySerialized.tryEmitNext(SinkManySerialized.java:100)
        at reactor.core.publisher.InternalManySink.emitNext(InternalManySink.java:27)
        at com.azure.core.amqp.implementation.handler.ReceiveLinkHandler.onDelivery(ReceiveLinkHandler.java:146)
        at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:185)
        at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
        at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
        at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291)
        at com.azure.core.amqp.implementation.ReactorExecutor.run(ReactorExecutor.java:86)
        at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
        at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.azure.core.amqp.exception.AmqpException: The lock supplied is invalid. Either the lock expired, or the message has already been removed from the queue. For more information please see https://aka.ms/ServiceBusExceptions . Reference:e4942427-bc27-48e1-ae30-59ad1740749d, TrackingId:d953ffd6-6def-4c7c-89e2-43dd0af8c8cc_B31, SystemTracker:boeing:Topic:junit_business_process_topic|all_messages, Timestamp:2021-11-01T01:50:37, errorContext[NAMESPACE: boeing.servicebus.windows.net. ERROR CONTEXT: N/A, PATH: junit_business_process_topic/subscriptions/all_messages/$management, REFERENCE_ID: junit_business_process_topic/subscriptions/all_messages-mgmt:receiver, LINK_CREDIT: 2]
        at com.azure.core.amqp.implementation.ExceptionUtil.toException(ExceptionUtil.java:85)
        at com.azure.messaging.servicebus.implementation.ManagementChannel.lambda$sendWithVerify$17(ManagementChannel.java:498)
        at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:103)
        ... 25 common frames omitted
09:50:38.925 [reactor-executor-3] DEBUG com.azure.core.amqp.implementation.handler.ReceiveLinkHandler - onDelivery connectionId[MF_9e92bd_1635731349762], linkName[junit_business_process_topic/subscriptions/all_messages-mgmt:receiver], updatedLinkCredit[2],remoteCredit[0], remoteCondition[N/A], delivery.isPartial[false], delivery.isSettled[false]
09:50:38.926 [reactor-executor-3] DEBUG com.azure.core.amqp.implementation.RequestResponseChannel - connectionId[MF_9e92bd_1635731349762], linkName[junit_business_process_topic/subscriptions/all_messages-mgmt]: Settling message: 251
09:50:38.926 [reactor-executor-3] WARN class com.azure.messaging.servicebus.implementation.ManagementChannel<junit_business_process_topic/subscriptions/all_messages> - status[GONE] description[The lock supplied is invalid. Either the lock expired, or the message has already been removed from the queue. For more information please see https://aka.ms/ServiceBusExceptions . Reference:a1f66ffc-804e-4095-a909-8d44e2df0520, TrackingId:efbc8a86-a3db-46d1-9e9f-a34cce81fd28_B31, SystemTracker:boeing:Topic:junit_business_process_topic|all_messages, Timestamp:2021-11-01T01:50:37] condition[com.microsoft:message-lock-lost] Operation not successful.
09:50:38.927 [reactor-executor-3] ERROR com.azure.messaging.servicebus.LockRenewalOperation - token[{}]. Error occurred while renewing lock token.
The lock supplied is invalid. Either the lock expired, or the message has already been removed from the queue. For more information please see https://aka.ms/ServiceBusExceptions . Reference:a1f66ffc-804e-4095-a909-8d44e2df0520, TrackingId:efbc8a86-a3db-46d1-9e9f-a34cce81fd28_B31, SystemTracker:boeing:Topic:junit_business_process_topic|all_messages, Timestamp:2021-11-01T01:50:37, errorContext[NAMESPACE: boeing.servicebus.windows.net. ERROR CONTEXT: N/A, PATH: junit_business_process_topic/subscriptions/all_messages/$management, REFERENCE_ID: junit_business_process_topic/subscriptions/all_messages-mgmt:receiver, LINK_CREDIT: 1]
com.azure.messaging.servicebus.ServiceBusException: The lock supplied is invalid. Either the lock expired, or the message has already been removed from the queue. For more information please see https://aka.ms/ServiceBusExceptions . Reference:a1f66ffc-804e-4095-a909-8d44e2df0520, TrackingId:efbc8a86-a3db-46d1-9e9f-a34cce81fd28_B31, SystemTracker:boeing:Topic:junit_business_process_topic|all_messages, Timestamp:2021-11-01T01:50:37, errorContext[NAMESPACE: boeing.servicebus.windows.net. ERROR CONTEXT: N/A, PATH: junit_business_process_topic/subscriptions/all_messages/$management, REFERENCE_ID: junit_business_process_topic/subscriptions/all_messages-mgmt:receiver, LINK_CREDIT: 1]
        at com.azure.messaging.servicebus.implementation.ManagementChannel.mapError(ManagementChannel.java:241)
        at reactor.core.publisher.Mono.lambda$onErrorMap$31(Mono.java:3676)
        at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94)
        at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onError(Operators.java:2063)
        at reactor.core.publisher.FluxHandle$HandleSubscriber.onError(FluxHandle.java:203)
        at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:125)
        at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.complete(MonoIgnoreThen.java:284)
        at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onNext(MonoIgnoreThen.java:187)
        at reactor.core.publisher.MonoCreate$DefaultMonoSink.success(MonoCreate.java:160)
        at com.azure.core.amqp.implementation.RequestResponseChannel.settleMessage(RequestResponseChannel.java:365)
        at com.azure.core.amqp.implementation.RequestResponseChannel.lambda$new$0(RequestResponseChannel.java:151)
        at reactor.core.publisher.LambdaSubscriber.onNext(LambdaSubscriber.java:160)
        at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:120)
        at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:200)
        at reactor.core.publisher.EmitterProcessor.drain(EmitterProcessor.java:491)
        at reactor.core.publisher.EmitterProcessor.tryEmitNext(EmitterProcessor.java:299)
        at reactor.core.publisher.SinkManySerialized.tryEmitNext(SinkManySerialized.java:100)
        at reactor.core.publisher.InternalManySink.emitNext(InternalManySink.java:27)
        at com.azure.core.amqp.implementation.handler.ReceiveLinkHandler.onDelivery(ReceiveLinkHandler.java:146)
        at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:185)
        at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
        at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
        at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291)
        at com.azure.core.amqp.implementation.ReactorExecutor.run(ReactorExecutor.java:86)
        at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
        at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.azure.core.amqp.exception.AmqpException: The lock supplied is invalid. Either the lock expired, or the message has already been removed from the queue. For more information please see https://aka.ms/ServiceBusExceptions . Reference:a1f66ffc-804e-4095-a909-8d44e2df0520, TrackingId:efbc8a86-a3db-46d1-9e9f-a34cce81fd28_B31, SystemTracker:boeing:Topic:junit_business_process_topic|all_messages, Timestamp:2021-11-01T01:50:37, errorContext[NAMESPACE: boeing.servicebus.windows.net. ERROR CONTEXT: N/A, PATH: junit_business_process_topic/subscriptions/all_messages/$management, REFERENCE_ID: junit_business_process_topic/subscriptions/all_messages-mgmt:receiver, LINK_CREDIT: 1]
        at com.azure.core.amqp.implementation.ExceptionUtil.toException(ExceptionUtil.java:85)
        at com.azure.messaging.servicebus.implementation.ManagementChannel.lambda$sendWithVerify$17(ManagementChannel.java:498)
        at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:103)
        ... 25 common frames omitted
09:50:38.929 [reactor-executor-3] DEBUG com.azure.core.amqp.implementation.handler.ReceiveLinkHandler - onDelivery connectionId[MF_9e92bd_1635731349762], linkName[junit_business_process_topic/subscriptions/all_messages-mgmt:receiver], updatedLinkCredit[1],remoteCredit[0], remoteCondition[N/A], delivery.isPartial[false], delivery.isSettled[false]
09:50:38.930 [reactor-executor-3] DEBUG com.azure.core.amqp.implementation.RequestResponseChannel - connectionId[MF_9e92bd_1635731349762], linkName[junit_business_process_topic/subscriptions/all_messages-mgmt]: Settling message: 246
09:50:38.930 [reactor-executor-3] WARN class com.azure.messaging.servicebus.implementation.ManagementChannel<junit_business_process_topic/subscriptions/all_messages> - status[GONE] description[The lock supplied is invalid. Either the lock expired, or the message has already been removed from the queue. For more information please see https://aka.ms/ServiceBusExceptions . Reference:bed92111-45d4-44c9-bd70-219be8cf4a8e, TrackingId:299e113e-3531-4c55-941f-50598fd6bccb_B31, SystemTracker:boeing:Topic:junit_business_process_topic|all_messages, Timestamp:2021-11-01T01:50:37] condition[com.microsoft:message-lock-lost] Operation not successful.
09:50:38.931 [reactor-executor-3] ERROR com.azure.messaging.servicebus.LockRenewalOperation - token[{}]. Error occurred while renewing lock token.
The lock supplied is invalid. Either the lock expired, or the message has already been removed from the queue. For more information please see https://aka.ms/ServiceBusExceptions . Reference:bed92111-45d4-44c9-bd70-219be8cf4a8e, TrackingId:299e113e-3531-4c55-941f-50598fd6bccb_B31, SystemTracker:boeing:Topic:junit_business_process_topic|all_messages, Timestamp:2021-11-01T01:50:37, errorContext[NAMESPACE: boeing.servicebus.windows.net. ERROR CONTEXT: N/A, PATH: junit_business_process_topic/subscriptions/all_messages/$management, REFERENCE_ID: junit_business_process_topic/subscriptions/all_messages-mgmt:receiver, LINK_CREDIT: 0]
com.azure.messaging.servicebus.ServiceBusException: The lock supplied is invalid. Either the lock expired, or the message has already been removed from the queue. For more information please see https://aka.ms/ServiceBusExceptions . Reference:bed92111-45d4-44c9-bd70-219be8cf4a8e, TrackingId:299e113e-3531-4c55-941f-50598fd6bccb_B31, SystemTracker:boeing:Topic:junit_business_process_topic|all_messages, Timestamp:2021-11-01T01:50:37, errorContext[NAMESPACE: boeing.servicebus.windows.net. ERROR CONTEXT: N/A, PATH: junit_business_process_topic/subscriptions/all_messages/$management, REFERENCE_ID: junit_business_process_topic/subscriptions/all_messages-mgmt:receiver, LINK_CREDIT: 0]
        at com.azure.messaging.servicebus.implementation.ManagementChannel.mapError(ManagementChannel.java:241)
        at reactor.core.publisher.Mono.lambda$onErrorMap$31(Mono.java:3676)
        at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94)
        at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onError(Operators.java:2063)
        at reactor.core.publisher.FluxHandle$HandleSubscriber.onError(FluxHandle.java:203)
        at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:125)
        at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.complete(MonoIgnoreThen.java:284)
        at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onNext(MonoIgnoreThen.java:187)
        at reactor.core.publisher.MonoCreate$DefaultMonoSink.success(MonoCreate.java:160)
        at com.azure.core.amqp.implementation.RequestResponseChannel.settleMessage(RequestResponseChannel.java:365)
        at com.azure.core.amqp.implementation.RequestResponseChannel.lambda$new$0(RequestResponseChannel.java:151)
        at reactor.core.publisher.LambdaSubscriber.onNext(LambdaSubscriber.java:160)
        at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:120)
        at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:200)
        at reactor.core.publisher.EmitterProcessor.drain(EmitterProcessor.java:491)
        at reactor.core.publisher.EmitterProcessor.tryEmitNext(EmitterProcessor.java:299)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.azure.core.amqp.exception.AmqpException: The lock supplied is invalid. Either the lock expired, or the message has already been removed from the queue. For more information please see https://aka.ms/ServiceBusExceptions . Reference:bed92111-45d4-44c9-bd70-219be8cf4a8e, TrackingId:299e113e-3531-4c55-941f-50598fd6bccb_B31, SystemTracker:boeing:Topic:junit_business_process_topic|all_messages, Timestamp:2021-11-01T01:50:37, errorContext[NAMESPACE: boeing.servicebus.windows.net. ERROR CONTEXT: N/A, PATH: junit_business_process_topic/subscriptions/all_messages/$management, REFERENCE_ID: junit_business_process_topic/subscriptions/all_messages-mgmt:receiver, LINK_CREDIT: 0]
        at com.azure.core.amqp.implementation.ExceptionUtil.toException(ExceptionUtil.java:85)
        at com.azure.messaging.servicebus.implementation.ManagementChannel.lambda$sendWithVerify$17(ManagementChannel.java:498)
        at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:103)
        ... 25 common frames omitted
09:50:38.934 [reactor-executor-3] DEBUG com.azure.core.amqp.implementation.handler.ReceiveLinkHandler - onDelivery connectionId[MF_9e92bd_1635731349762], linkName[junit_business_process_topic/subscriptions/all_messages-mgmt:receiver], updatedLinkCredit[0],remoteCredit[0], remoteCondition[N/A], delivery.isPartial[false], delivery.isSettled[false]
Terminate batch job (Y/N)? y
**To Reproduce**
`
Just run the below code snippet.
`
***Code Snippet***
package com.example.spring;

import com.azure.messaging.servicebus.*;
import com.azure.messaging.servicebus.models.ServiceBusReceiveMode;

import java.util.concurrent.atomic.AtomicInteger;
import java.util.stream.IntStream;
import java.time.Duration;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class MSGLockRenewBugRepro {
    public static void main(String[] args) {
        MSGLockRenewBugRepro locktest = new MSGLockRenewBugRepro();

        locktest.testReceiverLockFailure();
    }

    static String connectionString = "Endpoint=sb://xxxxxx.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=xxxxxxLQQDsFJP/JBvCGWn6R1+83Q7a1D9y0IsiY=";
    static String topicName = "junit_business_process_topic";
    static String subName = "all_messages";

    ServiceBusSenderClient senderClient = new ServiceBusClientBuilder().connectionString(connectionString).sender()
            .topicName(topicName).buildClient();

    // Creates an ServiceBusMessageBatch where the ServiceBus.
    ServiceBusMessageBatch messageBatch = senderClient.createMessageBatch();

    public void testReceiverLockFailure() {
        final Map<String, ServiceBusMessage> batchMap = new HashMap<>();
        IntStream.range(0, 1000).forEach(i -> {
            final String eventId = String.valueOf(i);
            batchMap.put(eventId, new ServiceBusMessage("this is the No. of  " + eventId + "evnet!"));
        });
        final List<ServiceBusMessage> batch = new ArrayList<>(batchMap.values());
        // messageBatch.send(batch);
        for (ServiceBusMessage message : batch) {
            if (messageBatch.tryAddMessage(message)) {
                continue;
            }

            // The batch is full, so we create a new batch and send the batch.
            senderClient.sendMessages(messageBatch);
            System.out.println("Sent a batch of messages to the topic: " + topicName);

            // create a new batch
            messageBatch = senderClient.createMessageBatch();

            // Add that message that we couldn't before.
            if (!messageBatch.tryAddMessage(message)) {
                System.err.printf("Message is too large for an empty batch. Skipping. Max size: %s.",
                        messageBatch.getMaxSizeInBytes());
            }
        }

        if (messageBatch.getCount() > 0) {
            senderClient.sendMessages(messageBatch);
            System.out.println("Sent a batch of messages to the topic: " + topicName);
        }

        // close the client
        senderClient.close();

        final ServiceBusReceiverAsyncClient testAsyncReceiver = new ServiceBusClientBuilder()
                // .retryOptions(getRetryOptions())
                .connectionString(connectionString).receiver().topicName("junit_business_process_topic")
                .subscriptionName("all_messages").maxAutoLockRenewDuration(Duration.ofHours(48))
                .receiveMode(ServiceBusReceiveMode.PEEK_LOCK).disableAutoComplete().prefetchCount(1000)
                .buildAsyncClient();

        final AtomicInteger completeCounter = new AtomicInteger();
        testAsyncReceiver.receiveMessages().toStream().forEachOrdered(msg -> {
            testAsyncReceiver.complete(msg).block();
            System.out.println("Completed counter: " + completeCounter.incrementAndGet());
        });
    }
}

**Expected behavior**
The process will broke when renew msg lock.
**Screenshots**

**Setup (please complete the following information):**
 - IDE: [e.g. IntelliJ]
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)]
 - Java version: [e.g. 8] 
 - App Server/Environment: [e.g. Tomcat, WildFly, Azure Function, Apache Spark, Databricks, IDE plugin or anything special]
 - Frameworks: [e.g. Spring Boot, Micronaut, Quarkus, etc] 

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please provide
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
  
**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by joshfree** [comment]
Thanks for supplying the repro code, @parkybyang.  @anuchandy @conniey could you please take a look?

**Comment by anuchandy** [comment]
Hi @parkybyang, we're in the process of deprecating/removing the "auto-lock-renew" and "auto-complete" in the Receiver Client. I.e., after the deprecation, the experience should be the same as invoking "disableAutoComplete" & "disableAutoRenew" in the Receiver client today (these two APIs will be deprecated as well)

This aligns Java SDK with SB SDK in other languages. 

So to future proof the code, recommendation here is - use "disableAutoComplete" & "disableAutoRenew" then use the following guideline on  "prefetch-size"

The maximum prefetch-size configured on the queue/topic/subscription needs to be balanced with the configured the lock-timeout (via portal/CLI/other tools), such that lock-timeout is at aleast exceeds the cumulative expected message processing time for the maximum size of the prefetch buffer, plus one message.

Reference:

https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-prefetch?tabs=dotnet#why-is-prefetch-not-the-default-option

\\cc @ramya-rao-a

**Comment by parkybyang** [comment]
Hi @anuchandy
Thank you for your explanation and information. Actually I tried  maxAutoLockRenewDuration(Duration.ZERO) to disable the autolockrenew, and it works and normally completed process the 1000 msgs in the repo code.
However, this doesn't according to the app's business logic design, in the design, client app may keep the msg for hours long, so there do require an autolockrenew. Can you let me know, if this kind of situation won't be suported in the future?

**Comment by anuchandy** [comment]
Thanks for the response; yes, the Receiver client in the library won't support auto-renew any longer; Java is aligning with the rest of the language SDKs on this. Note that "auto-renew" is a client-side concept, where SDK spin-up a background thread that keeps calling renew API. 

The Receiver client has a method for lock-renewal, which the application can call to renew the lock.

 Also, just to clarify on the "to-be-deprecated" "maxAutoLockRenewDuration()" API, this API was supposed to renew only the current message delivered to the app, not the prefetched messages in local memory waiting to be consumed by the app.

**Comment by parkybyang** [comment]
Thanks for Andy's confirmation.

**Comment by sohanlal311** [comment]
Hi @anuchandy

I raised this concern through Azure Support portal to @parkybyang. I want some more clarification.

I agree that built-in auto lock renewal support in the receiver client is going to be deprecated and we should manually call the **renewMessageLock** method available on sync/async receiver client but calling this method will also spin up a thread in background to renew the lock. I have manually tested it.

Please consider the below mentioned case.

**Scenario:**
1. I read 1000 messages with the help of a synchronous client (Please check the code below).
2. Then I start renewal in background by manually calling the renewMessageLock method on sync receiver.
3. Then I wait for some time till the processing is complete. This time is more than the message lock time on server.
4. And then I try to mark all of them complete.

Question: This scenario is also the same as built-in lock renewal mechanism because it will also spin up 1000 threads in background to renew the lock of those 1000 messages. eventually will fail with the same error "The lock is expired". I have manually tried it in my local and it fails 8 out of 20 times.
```
	final ServiceBusReceiverClient testReceiver = new ServiceBusClientBuilder()
			// .retryOptions(getRetryOptions())
			.connectionString(connectionString)
			.receiver()
			.topicName("junit_business_process_topic")
			.subscriptionName("all_messages")
			.buildClient();

	// receive messages
	final IterableStream<ServiceBusReceivedMessage> itrStream = testReceiver.receiveMessages(1000, 120Seconds);

	// start lock renewal thread in backround
	itrStream.stream().forEachOrdered(msg -> testReceiver.renewMessageLock(msg, 24Hours, null));

	// wait for 1 hour until the processing is complete
	TimeUnit.MINUTES.sleep(60);

	// and then I try to mark all of them complete
	final AtomicInteger completeCounter = new AtomicInteger();
	itrStream.stream().forEachOrdered(msg -> {
        	testReceiver.complete(msg);
        	System.out.println("Completed counter: " + completeCounter.incrementAndGet());
    	});
```

Regards
Sohan

**Comment by parkybyang** [comment]
hello @anuchandy 
Could you please see @sohanlal311 's comment, even he tried to manuelly renewMessageLock the message, he got the same exception.

**Comment by anuchandy** [comment]
thanks for getting back @sohanlal311, @parkybyang, let me use the above-shared code and create a repro to understand more.

**Comment by sohanlal311** [comment]
I have analyzed the internal code from azure library and found the code snippet which is causing the issue.

**package:** com.azure.messaging.servicebus;
**class:** LockRenewalOperation implements AutoCloseable {
**method:**    private Flux<OffsetDateTime> getRenewLockOperation(OffsetDateTime initialLockedUntil, Duration maxLockRenewalDuration) {
**Note:** Please look at the lines marked with **----->** in below code.
```
        return Flux.switchOnNext(emitterProcessor.map(interval -> Mono.delay(interval)
            .thenReturn(Flux.create(s -> s.next(interval)))))
            .takeUntilOther(cancellationSignals)
            .flatMap(delay -> {
                logger.info("token[{}]. now[{}]. Starting lock renewal.", lockToken, OffsetDateTime.now());
                return renewalOperation.apply(lockToken);
            })
            .map(offsetDateTime -> {
----->      final Duration next = Duration.between(OffsetDateTime.now(), offsetDateTime);
                logger.info("token[{}]. nextExpiration[{}]. next: [{}]. isSession[{}]", lockToken, offsetDateTime, next,
                    isSession);

----->      sink.next(MessageUtils.adjustServerTimeout(next));
                return offsetDateTime;
            });
```

Here is the code for **MessageUtils.adjustServerTimeout** method which is the second occurrence in above code which is marked with **----->**:
```
    // Pass little less than client timeout to the server so client doesn't time out before server times out
    public static Duration adjustServerTimeout(Duration clientTimeout) {
        return clientTimeout.minusMillis(1000);
    }
```

**My analysis:**
1. The reference **next** is the difference between the current time and the next expiration time. It will be a few milliseconds. Suppose it is 300 milliseconds.
2. Then you are adjusting the time in **MessageUtils.adjustServerTimeout** method by subtracting 1000 milliseconds from the **next** time.

**Conclusion:**
Hence according to the above logic, the next renewal from the client side will roughly happen just 1.3 seconds before the next expiration. Please note it may fail as well due to network latency or some other IO related issues.

**Fix:**
Could you please allow the client to pass a time which will be used in **MessageUtils.adjustServerTimeout** method rather than just 1 second so that client has control to renew the lock. It will really be beneficial in cases where we are fetching a batch of messages and processing them.

**Comment by anuchandy** [comment]
@parkybyang, the same discussion is duplicated in this [ticket](https://github.com/Azure/azure-sdk-for-java/issues/25259) as well. Please subscribe to that for the latest updates.
