### ISSUE TITLE
[BUG]JsonFlattern style annotation not working in azure-core version 1.21.0

### ISSUE THREAD

**Issue by XiaofeiCao** [Azure/azure-sdk-for-java#25164]
**Describe the bug**
JsonFlattern style annotation not working in azure core.
(This bug seems to be introduced in `recent` version of azure core, no exception thrown when using older version `1.10.0`.)
```
@JsonProperty(value = "properties.registrationTtl")
private String registrationTtl;
```

``` pom.xml - dependancy
<dependency>
      <groupId>com.azure</groupId>
      <artifactId>azure-core</artifactId>
      <version>1.21.0</version>
</dependency>
```

***Exception or Stack Trace***
```
Exception in thread "main" com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.lang.String` from Object value (token `JsonToken.START_OBJECT`)
 at [Source: (String)"{"id":"/subscriptions/.../resourceGroups/nhbangbang/providers/Microsoft.NotificationHubs/namespaces/.../notificationHubs/...","name":"...-01","type":"Microsoft.NotificationHubs/namespaces/notificationHubs","location":"East Asia","tags":{},"properties":{"registrationTtl":"10675199.02:48:05.4775807","authorizationRules":[]}}"; line: 1, column: 324] (through reference chain: com.azure.core.test.SampleResource["properties.name"])
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1601)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1375)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1280)
	at com.fasterxml.jackson.databind.DeserializationContext.extractScalarFromObject(DeserializationContext.java:872)
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:62)
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:11)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:324)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187)
	at com.azure.core.implementation.jackson.FlatteningDeserializer.deserialize(FlatteningDeserializer.java:155)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4593)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3548)
	at com.azure.core.implementation.jackson.ObjectMapperShim.readValue(ObjectMapperShim.java:198)
	at com.azure.core.util.serializer.JacksonAdapter.deserialize(JacksonAdapter.java:193)
	at com.azure.core.test.JsonTest.main(JsonTest.java:16)

```

**To Reproduce**
<strong>test repo can be found in src/test/java/com/xiaofei/azure/testcase</strong>
https://github.com/XiaofeiCao/azure-testcase

SampleClass that uses JsonFlattern annotation
```
@JsonFlatten
@Fluent
public class SampleResource {

    @JsonProperty(value = "properties.name")
    private String namePropertiesName;

    @JsonProperty(value = "properties.registrationTtl")
    private String registrationTtl;

    public SampleResource withNamePropertiesName(String namePropertiesName){
        this.namePropertiesName = namePropertiesName;
        return this;
    }

    public SampleResource withRegistrationTtl(String registrationTtl){
        this.registrationTtl = registrationTtl;
        return this;
    }

    public String getNamePropertiesName() {
        return namePropertiesName;
    }

    public String getRegistrationTtl() {
        return registrationTtl;
    }
}

```

test case:
```
SampleResource sampleResource = JacksonAdapter.createDefaultSerializerAdapter().deserialize(
            "{\"id\":\"/subscriptions/.../resourceGroups/nhbangbang/providers/Microsoft.NotificationHubs/namespaces/.../notificationHubs/...\",\"name\":\"...-01\",\"type\":\"Microsoft.NotificationHubs/namespaces/notificationHubs\",\"location\":\"East Asia\",\"tags\":{},\"properties\":{\"registrationTtl\":\"10675199.02:48:05.4775807\",\"authorizationRules\":[]}}"
            , SampleResource.class
            , SerializerEncoding.JSON
        ); //exception thrown
System.out.println(sampleResource.getRegistrationTtl()); // can't reach here
```

**Setup (please complete the following information):**
 - OS: windows11
 - IDE: IntelliJ
 - Library/Libraries: com.azure:azure-core:1.21.0
 - Java version: 11
 - App Server/Environment: local debug
 - Frameworks: no

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Root cause of issue
https://github.com/Azure/azure-sdk-for-java/issues/25122

**Comment by weidongxu-microsoft** [comment]
@XiaofeiCao 
If you can, just put your test code to a repo in github.

**Comment by XiaofeiCao** [comment]
test code repo can be found in 
https://github.com/XiaofeiCao/azure-testcase

**Comment by XiaofeiCao** [comment]
FYI:
The bug seems to be introduced in version 1.18.0. Version 1.17.0 has no issue.
It still exists in 1.22.0-beta.1.

**Comment by samvaity** [comment]
Hey @XiaofeiCao, Thank you for providing the test case. 
Although, would the correct representation of the `SampleResource` object be with `name` and `registrationTtl` inside of the property bag?

`"{\"properties\":{\"name\":\"...-01\",\"registrationTtl\":\"10675199.02:48:05.4775807\"}}";`

**Comment by XiaofeiCao** [comment]
@samvaity Hi, I followed your suggestion and I find out that, either putting the `name` property inside the `properties` bag or simply removing it actually work without any exceptions.
Which makes me wonder, why the placement of the `name` outside the `properties` bag results in `MismatchedInputException`.
Is this actually a `JsonFlatten` feature of some sort of check enforcement, since most json deserializers I know will simply ignore the misplaced `name` property?

**Comment by weidongxu-microsoft** [comment]
@samvaity 

`id`, `name`, `type` out of `properties` is a must for any ARM resource.

`name` and `properties.name` is not usual. But it is common to have `type` and `properties.type` at same object.

**Comment by samvaity** [comment]
@weidongxu-microsoft yes, I think we understand the issue. This [PR ](https://github.com/Azure/azure-sdk-for-java/pull/25621) should help fix the issue.

**Comment by XiaofeiCao** [comment]
Confirm fixed in latest azure-core, thanks!
