### ISSUE TITLE
[BUG] azure-security-keyvault-jca | throws UnsupportedSchemeException while using managed identity

### ISSUE THREAD

**Issue by Descatles** [Azure/azure-sdk-for-java#25255]
**Describe the bug**
 azure-security-keyvault-jca throws exception while using system managed identity on azure spring cloud to get certificate from keyvault.

***Exception or Stack Trace***
Build in Environment Variables
BUILD_IN_EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=https://secure.svc.asc-test.net/eureka/eureka
BUILD_IN_SPRING_CLOUD_CONFIG_URI=https://secure.svc.asc-test.net/config
BUILD_IN_SPRING_CLOUD_CONFIG_FAILFAST=true
[Azure Spring Cloud] The following environment variables are loaded: KEY_VAULT_URI SERVER_SSL_CERTIFICATE_NAME
Picked up JAVA_TOOL_OPTIONS:  -Xms2048m -Xmx2048m -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:+UseG1GC -Djava.awt.headless=true -Djava.awt.headless=true -Dreactor.netty.http.server.accessLogEnabled=true
2021-11-09 08:29:23.537Z INFO  c.m.applicationinsights.agent - ApplicationInsights Java Agent 3.1.1 started successfully

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.3.0.RELEASE)

2021-11-09 08:29:29.938  INFO 1 --- [           main] c.a.s.k.j.implementation.KeyVaultClient  : Using Azure Key Vault: https://certs-2021.vault.azure.net/
2021-11-09 08:29:30.775  INFO 1 --- [           main] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at : https://secure.svc.asc-test.net/config
2021-11-09 08:29:31.450  INFO 1 --- [           main] c.c.c.ConfigServicePropertySourceLocator : Located environment: name=gateway, profiles=[default], label=null, version=c5a4e071d4ab5fbc560b19d17225e519c81957c1, state=null
2021-11-09 08:29:31.453  INFO 1 --- [           main] b.c.PropertySourceBootstrapConfiguration : Located property source: [BootstrapPropertySource {name='bootstrapProperties-configClient'}, BootstrapPropertySource {name='bootstrapProperties-https://github.com/Descatles/spring-boot-secure-communications-using-end-to-end-tls-ssl-config.git/gateway.yml'}, BootstrapPropertySource {name='bootstrapProperties-https://github.com/Descatles/spring-boot-secure-communications-using-end-to-end-tls-ssl-config.git/application.yml'}]
2021-11-09 08:29:31.536  INFO 1 --- [           main] com.secure.gateway.GatewayApplication    : No active profile set, falling back to default profiles: default
2021-11-09 08:29:34.376  WARN 1 --- [           main] o.s.boot.actuate.endpoint.EndpointId     : Endpoint ID 'service-registry' contains invalid characters, please migrate to a valid format.
2021-11-09 08:29:34.830  INFO 1 --- [           main] o.s.cloud.context.scope.GenericScope     : BeanFactory id=9dfcfa26-f06f-3ae8-ac64-ec49e2e47f62
2021-11-09 08:29:35.349  INFO 1 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.cloud.client.loadbalancer.reactive.LoadBalancerBeanPostProcessorAutoConfiguration' of type [org.springframework.cloud.client.loadbalancer.reactive.LoadBalancerBeanPostProcessorAutoConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2021-11-09 08:29:35.350  INFO 1 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.cloud.client.loadbalancer.reactive.LoadBalancerBeanPostProcessorAutoConfiguration$ReactiveLoadBalancerConfig' of type [org.springframework.cloud.client.loadbalancer.reactive.LoadBalancerBeanPostProcessorAutoConfiguration$ReactiveLoadBalancerConfig] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2021-11-09 08:29:35.370  INFO 1 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'deferringLoadBalancerExchangeFilterFunction' of type [org.springframework.cloud.client.loadbalancer.reactive.DeferringLoadBalancerExchangeFilterFunction] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2021-11-09 08:29:36.056  INFO 1 --- [           main] c.a.s.k.j.implementation.KeyVaultClient  : Using Azure Key Vault: https://certs-2021.vault.azure.net/
2021-11-09 08:29:36.062  INFO 1 --- [           main] c.a.s.k.j.i.utils.AccessTokenUtil        : Getting access token using managed identity
2021-11-09 08:29:36.882  INFO 1 --- [           main] c.a.s.k.j.i.s.o.a.h.i.e.RetryExec        : I/O exception (com.azure.security.keyvault.jca.implementation.shaded.org.apache.http.conn.UnsupportedSchemeException) caught when processing request to {}->http://169.254.169.254:80: http protocol is not supported
2021-11-09 08:29:36.883  INFO 1 --- [           main] c.a.s.k.j.i.s.o.a.h.i.e.RetryExec        : Retrying request to {}->http://169.254.169.254:80
2021-11-09 08:29:36.883  INFO 1 --- [           main] c.a.s.k.j.i.s.o.a.h.i.e.RetryExec        : I/O exception (com.azure.security.keyvault.jca.implementation.shaded.org.apache.http.conn.UnsupportedSchemeException) caught when processing request to {}->http://169.254.169.254:80: http protocol is not supported
2021-11-09 08:29:36.884  INFO 1 --- [           main] c.a.s.k.j.i.s.o.a.h.i.e.RetryExec        : Retrying request to {}->http://169.254.169.254:80
2021-11-09 08:29:36.884  INFO 1 --- [           main] c.a.s.k.j.i.s.o.a.h.i.e.RetryExec        : I/O exception (com.azure.security.keyvault.jca.implementation.shaded.org.apache.http.conn.UnsupportedSchemeException) caught when processing request to {}->http://169.254.169.254:80: http protocol is not supported
2021-11-09 08:29:36.884  INFO 1 --- [           main] c.a.s.k.j.i.s.o.a.h.i.e.RetryExec        : Retrying request to {}->http://169.254.169.254:80
2021-11-09 08:29:36.892  WARN 1 --- [           main] c.a.s.k.j.implementation.utils.HttpUtil  : Unable to finish the http get request.

com.azure.security.keyvault.jca.implementation.shaded.org.apache.http.conn.UnsupportedSchemeException: http protocol is not supported
        at com.azure.security.keyvault.jca.implementation.shaded.org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:109) ~[azure-security-keyvault-jca-2.2.0.jar!/:2.2.0]
        at com.azure.security.keyvault.jca.implementation.shaded.org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376) ~[azure-security-keyvault-jca-2.2.0.jar!/:2.2.0]
        at com.azure.security.keyvault.jca.implementation.shaded.org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393) ~[azure-security-keyvault-jca-2.2.0.jar!/:2.2.0]
        at com.azure.security.keyvault.jca.implementation.shaded.org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[azure-security-keyvault-jca-2.2.0.jar!/:2.2.0]
        at com.azure.security.keyvault.jca.implementation.shaded.org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) ~[azure-security-keyvault-jca-2.2.0.jar!/:2.2.0]
        at com.azure.security.keyvault.jca.implementation.shaded.org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[azure-security-keyvault-jca-2.2.0.jar!/:2.2.0]
        at com.azure.security.keyvault.jca.implementation.shaded.org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[azure-security-keyvault-jca-2.2.0.jar!/:2.2.0]
        at com.azure.security.keyvault.jca.implementation.shaded.org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[azure-security-keyvault-jca-2.2.0.jar!/:2.2.0]
        at com.azure.security.keyvault.jca.implementation.shaded.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72) ~[azure-security-keyvault-jca-2.2.0.jar!/:2.2.0]
        at com.azure.security.keyvault.jca.implementation.shaded.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:221) ~[azure-security-keyvault-jca-2.2.0.jar!/:2.2.0]
        at com.azure.security.keyvault.jca.implementation.shaded.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:165) ~[azure-security-keyvault-jca-2.2.0.jar!/:2.2.0]
        at com.azure.security.keyvault.jca.implementation.shaded.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:140) ~[azure-security-keyvault-jca-2.2.0.jar!/:2.2.0]
        at com.azure.security.keyvault.jca.implementation.utils.HttpUtil.get(HttpUtil.java:61) ~[azure-security-keyvault-jca-2.2.0.jar!/:2.2.0]
        at com.azure.security.keyvault.jca.implementation.utils.AccessTokenUtil.getAccessTokenOnOthers(AccessTokenUtil.java:171) [azure-security-keyvault-jca-2.2.0.jar!/:2.2.0]
        at com.azure.security.keyvault.jca.implementation.utils.AccessTokenUtil.getAccessToken(AccessTokenUtil.java:72) [azure-security-keyvault-jca-2.2.0.jar!/:2.2.0]
        at com.azure.security.keyvault.jca.implementation.KeyVaultClient.getAccessTokenByHttpRequest(KeyVaultClient.java:216) [azure-security-keyvault-jca-2.2.0.jar!/:2.2.0]
        at com.azure.security.keyvault.jca.implementation.KeyVaultClient.getAccessToken(KeyVaultClient.java:194) [azure-security-keyvault-jca-2.2.0.jar!/:2.2.0]
        at com.azure.security.keyvault.jca.implementation.KeyVaultClient.getAliases(KeyVaultClient.java:233) [azure-security-keyvault-jca-2.2.0.jar!/:2.2.0]
        at com.azure.security.keyvault.jca.implementation.certificates.KeyVaultCertificates.refreshCertificates(KeyVaultCertificates.java:142) [azure-security-keyvault-jca-2.2.0.jar!/:2.2.0]
        at com.azure.security.keyvault.jca.implementation.certificates.KeyVaultCertificates.refreshCertificatesIfNeeded(KeyVaultCertificates.java:130) [azure-security-keyvault-jca-2.2.0.jar!/:2.2.0]
        at com.azure.security.keyvault.jca.implementation.certificates.KeyVaultCertificates.getAliases(KeyVaultCertificates.java:100) [azure-security-keyvault-jca-2.2.0.jar!/:2.2.0]
        at com.azure.security.keyvault.jca.KeyVaultKeyStore.getAllAliases(KeyVaultKeyStore.java:291) [azure-security-keyvault-jca-2.2.0.jar!/:2.2.0]
        at com.azure.security.keyvault.jca.KeyVaultKeyStore.engineIsCertificateEntry(KeyVaultKeyStore.java:263) [azure-security-keyvault-jca-2.2.0.jar!/:2.2.0]
        at com.azure.security.keyvault.jca.KeyVaultKeyStore.engineContainsAlias(KeyVaultKeyStore.java:181) [azure-security-keyvault-jca-2.2.0.jar!/:2.2.0]
        at java.security.KeyStore.containsAlias(KeyStore.java:1254) [na:1.8.0_302]
        at org.springframework.boot.web.server.SslConfigurationValidator.validateKeyAlias(SslConfigurationValidator.java:39) [spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
        at org.springframework.boot.web.embedded.netty.SslServerCustomizer.getKeyManagerFactory(SslServerCustomizer.java:110) [spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
        at org.springframework.boot.web.embedded.netty.SslServerCustomizer.getContextBuilder(SslServerCustomizer.java:90) [spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
        at org.springframework.boot.web.embedded.netty.SslServerCustomizer.lambda$apply$0(SslServerCustomizer.java:78) [spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
        at reactor.netty.http.server.HttpServerSecure.<init>(HttpServerSecure.java:37) ~[reactor-netty-0.9.7.RELEASE.jar!/:0.9.7.RELEASE]
        at reactor.netty.http.server.HttpServer.secure(HttpServer.java:552) ~[reactor-netty-0.9.7.RELEASE.jar!/:0.9.7.RELEASE]
        at org.springframework.boot.web.embedded.netty.SslServerCustomizer.apply(SslServerCustomizer.java:77) [spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
        at org.springframework.boot.web.embedded.netty.NettyReactiveWebServerFactory.createHttpServer(NettyReactiveWebServerFactory.java:166) ~[spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
        at org.springframework.boot.web.embedded.netty.NettyReactiveWebServerFactory.getWebServer(NettyReactiveWebServerFactory.java:70) ~[spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
        at org.springframework.boot.web.reactive.context.WebServerManager.<init>(WebServerManager.java:49) ~[spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
        at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.createWebServer(ReactiveWebServerApplicationContext.java:90) ~[spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
        at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.onRefresh(ReactiveWebServerApplicationContext.java:77) ~[spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:544) ~[spring-context-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
        at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:62) ~[spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758) ~[spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750) ~[spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237) ~[spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) ~[spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
        at com.secure.gateway.GatewayApplication.main(GatewayApplication.java:10) ~[classes!/:1.0.0]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_302]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_302]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_302]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_302]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[5d7981b9-9fa2-472f-a281-8ec7cf5438a9:1.0.0]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:109) ~[5d7981b9-9fa2-472f-a281-8ec7cf5438a9:1.0.0]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[5d7981b9-9fa2-472f-a281-8ec7cf5438a9:1.0.0]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[5d7981b9-9fa2-472f-a281-8ec7cf5438a9:1.0.0]

2021-11-09 08:29:36.897  WARN 1 --- [           main] onfigReactiveWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Unable to start reactive web server; nested exception is java.lang.IllegalStateException: java.lang.IllegalStateException: java.lang.NullPointerException
2021-11-09 08:29:37.258  INFO 1 --- [           main] ConditionEvaluationReportLoggingListener :

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2021-11-09 08:29:37.261 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.context.ApplicationContextException: Unable to start reactive web server; nested exception is java.lang.IllegalStateException: java.lang.IllegalStateException: java.lang.NullPointerException
        at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.onRefresh(ReactiveWebServerApplicationContext.java:80) ~[spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:544) ~[spring-context-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
        at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:62) ~[spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758) [spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750) [spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237) [spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
        at com.secure.gateway.GatewayApplication.main(GatewayApplication.java:10) [classes!/:1.0.0]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_302]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_302]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_302]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_302]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) [5d7981b9-9fa2-472f-a281-8ec7cf5438a9:1.0.0]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:109) [5d7981b9-9fa2-472f-a281-8ec7cf5438a9:1.0.0]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) [5d7981b9-9fa2-472f-a281-8ec7cf5438a9:1.0.0]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) [5d7981b9-9fa2-472f-a281-8ec7cf5438a9:1.0.0]
Caused by: java.lang.IllegalStateException: java.lang.IllegalStateException: java.lang.NullPointerException
        at org.springframework.boot.web.embedded.netty.SslServerCustomizer.apply(SslServerCustomizer.java:85) ~[spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
        at org.springframework.boot.web.embedded.netty.NettyReactiveWebServerFactory.createHttpServer(NettyReactiveWebServerFactory.java:166) ~[spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
        at org.springframework.boot.web.embedded.netty.NettyReactiveWebServerFactory.getWebServer(NettyReactiveWebServerFactory.java:70) ~[spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
        at org.springframework.boot.web.reactive.context.WebServerManager.<init>(WebServerManager.java:49) ~[spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
        at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.createWebServer(ReactiveWebServerApplicationContext.java:90) ~[spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
        at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.onRefresh(ReactiveWebServerApplicationContext.java:77) ~[spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
        ... 17 common frames omitted
Caused by: java.lang.IllegalStateException: java.lang.NullPointerException
        at org.springframework.boot.web.embedded.netty.SslServerCustomizer.getKeyManagerFactory(SslServerCustomizer.java:123) ~[spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
        at org.springframework.boot.web.embedded.netty.SslServerCustomizer.getContextBuilder(SslServerCustomizer.java:90) ~[spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
        at org.springframework.boot.web.embedded.netty.SslServerCustomizer.lambda$apply$0(SslServerCustomizer.java:78) ~[spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
        at reactor.netty.http.server.HttpServerSecure.<init>(HttpServerSecure.java:37) ~[reactor-netty-0.9.7.RELEASE.jar!/:0.9.7.RELEASE]
        at reactor.netty.http.server.HttpServer.secure(HttpServer.java:552) ~[reactor-netty-0.9.7.RELEASE.jar!/:0.9.7.RELEASE]
        at org.springframework.boot.web.embedded.netty.SslServerCustomizer.apply(SslServerCustomizer.java:77) ~[spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
        ... 22 common frames omitted
Caused by: java.lang.NullPointerException: null
        at com.azure.security.keyvault.jca.implementation.KeyVaultClient.getAccessToken(KeyVaultClient.java:195) ~[azure-security-keyvault-jca-2.2.0.jar!/:2.2.0]
        at com.azure.security.keyvault.jca.implementation.KeyVaultClient.getAliases(KeyVaultClient.java:233) ~[azure-security-keyvault-jca-2.2.0.jar!/:2.2.0]
        at com.azure.security.keyvault.jca.implementation.certificates.KeyVaultCertificates.refreshCertificates(KeyVaultCertificates.java:142) ~[azure-security-keyvault-jca-2.2.0.jar!/:2.2.0]
        at com.azure.security.keyvault.jca.implementation.certificates.KeyVaultCertificates.refreshCertificatesIfNeeded(KeyVaultCertificates.java:130) ~[azure-security-keyvault-jca-2.2.0.jar!/:2.2.0]
        at com.azure.security.keyvault.jca.implementation.certificates.KeyVaultCertificates.getAliases(KeyVaultCertificates.java:100) ~[azure-security-keyvault-jca-2.2.0.jar!/:2.2.0]
        at com.azure.security.keyvault.jca.KeyVaultKeyStore.getAllAliases(KeyVaultKeyStore.java:291) ~[azure-security-keyvault-jca-2.2.0.jar!/:2.2.0]
        at com.azure.security.keyvault.jca.KeyVaultKeyStore.engineIsCertificateEntry(KeyVaultKeyStore.java:263) ~[azure-security-keyvault-jca-2.2.0.jar!/:2.2.0]
        at com.azure.security.keyvault.jca.KeyVaultKeyStore.engineContainsAlias(KeyVaultKeyStore.java:181) ~[azure-security-keyvault-jca-2.2.0.jar!/:2.2.0]
        at java.security.KeyStore.containsAlias(KeyStore.java:1254) ~[na:1.8.0_302]
        at org.springframework.boot.web.server.SslConfigurationValidator.validateKeyAlias(SslConfigurationValidator.java:39) ~[spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
        at org.springframework.boot.web.embedded.netty.SslServerCustomizer.getKeyManagerFactory(SslServerCustomizer.java:110) ~[spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
        ... 27 common frames omitted

**To Reproduce**
Just follow this [sample](https://github.com/Azure-Samples/spring-boot-secure-communications-using-end-to-end-tls-ssl) to create an app and using managed identity to fetch certificate from azure keyvault.
And you should use the lastest version of azure-spring-boot-starter-keyvault-certificates 3.10.0
And update spring boot to 2.5.4 , spring cloud 2020.0.3

***Code Snippet***
`azure:
  keyvault:
    uri: ${KEY_VAULT_URI}

server:
  ssl:
    key-alias: ${SERVER_SSL_CERTIFICATE_NAME}
    key-store-type: AzureKeyVault`

**Expected behavior**
Successfully load certificates form key vault

**Screenshots**

**Setup (please complete the following information):**
just following the sample guide

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please provide
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
  
**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by joshfree** [comment]
Thanks for filing this github issue, @Descatles.  @chenrujun could you please take a look?

**Comment by chenrujun** [comment]
@Descatles , thanks for reaching out. I'll investigate this issue. I set the milestone to `2021 January`.
