### ISSUE TITLE
Service bus - Spring Cloud Stream to use proxy for connection

### ISSUE THREAD

**Issue by preethamjebarajjohn** [Azure/azure-sdk-for-java#25485]
I am looking for an option to set proxy for connecting to Service bus using "Spring cloud Streams". Below is my configuration and error logs. I can able to connect to same service bus topic using ServiceBusReceiverAsyncClient by setting proxy. I am looking to achieve this by using Cloud Stream.
```yml
spring:
  cloud:
    azure:
      servicebus:
        connection-string: Endpoint=sb://namespace.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=XXXXXXX
    stream:
      bindings:
        consume-in-0:
          destination: XXXXX
          group: XXXXXX
      servicebus:
        topic:
          bindings:
            consume-in-0:
              consumer:
                checkpoint-mode: MANUAL
      function:
        definition: consume;
      poller:
        fixed-delay: 1000
        initial-delay: 0
```
Error Logs:
```
21-11-16 Tue 11:48:48.352 DEBUG 44993b2bb111c24e ReactorExecutor                          : Had more tasks to process on reactor but it is shutting down.
21-11-16 Tue 11:48:48.352 INFO  44993b2bb111c24e ReactorDispatcher                        : connectionId[MF_853c41_1637081310280] Reactor selectable is being disposed.
21-11-16 Tue 11:48:48.353 INFO  44993b2bb111c24e ReactorConnection                        : Shutdown signal received from reactor provider.
21-11-16 Tue 11:48:48.353 INFO  44993b2bb111c24e ReactorConnection                        : onConnectionShutdown connectionId[MF_853c41_1637081310280], hostName[ici-namespace.servicebus.windows.net], message[Shutting down], shutdown signal[false]
21-11-16 Tue 11:48:48.353 DEBUG 44993b2bb111c24e ReactorExecutor                          : Completing close and disposing scheduler. Finished processing pending tasks.
21-11-16 Tue 11:48:48.356 ERROR 44993b2bb111c24e Operators                                : Operator called default onErrorDropped
reactor.core.Exceptions$ErrorCallbackNotImplemented: com.azure.core.amqp.exception.AmqpException: errorContext[NAMESPACE: namespace.servicebus.windows.net. ERROR CONTEXT: N/A]
Caused by: com.azure.core.amqp.exception.AmqpException: errorContext[NAMESPACE: namespace.servicebus.windows.net. ERROR CONTEXT: N/A]
	at com.azure.core.amqp.implementation.ExceptionUtil.toException(ExceptionUtil.java:85) ~[azure-core-amqp-2.3.2.jar:2.3.2]
	at com.azure.core.amqp.implementation.handler.ConnectionHandler.notifyErrorContext(ConnectionHandler.java:325) ~[azure-core-amqp-2.3.2.jar:2.3.2]
	at com.azure.core.amqp.implementation.handler.ConnectionHandler.onTransportError(ConnectionHandler.java:228) ~[azure-core-amqp-2.3.2.jar:2.3.2]
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:191) ~[proton-j-0.33.8.jar:na]
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108) ~[proton-j-0.33.8.jar:na]
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324) ~[proton-j-0.33.8.jar:na]
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291) ~[proton-j-0.33.8.jar:na]
	at com.azure.core.amqp.implementation.ReactorExecutor.run(ReactorExecutor.java:86) ~[azure-core-amqp-2.3.2.jar:2.3.2]
	at org.springframework.cloud.sleuth.instrument.reactor.ReactorSleuth.lambda$null$6(ReactorSleuth.java:312) ~[spring-cloud-sleuth-instrumentation-3.0.4.jar:3.0.4]
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68) ~[reactor-core-3.4.11.jar:3.4.11]
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28) ~[reactor-core-3.4.11.jar:3.4.11]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) ~[na:1.8.0_302]
	at java.util.concurrent.FutureTask.run(FutureTask.java) ~[na:1.8.0_302]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_302]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_302]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_302]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_302]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_302]
```

**Comment by pallavit** [comment]
/cc: @conniey could you please take a look.

**Comment by chenrujun** [comment]
Hi, @yiliuTo , could you please handle this issue?

**Comment by yiliuTo** [comment]
Hi @preethamjebarajjohn , the proxy configuration for service bus spring cloud stream binder is only supported from the latest release of [spring-cloud-azure-stream-binder-servicebus 4.0.0-beta.2](https://repo1.maven.org/maven2/com/azure/spring/spring-cloud-azure-stream-binder-servicebus/). 
In 4.0.0-beta.2 and future versions, we support three levels of configurations:
1. You could set the overall proxy by the configuration options of `spring.cloud.azure.servicebus.proxy.*`, which will be applied with all producer and consumer clients. Detailed proxy configuration options include: https://microsoft.github.io/spring-cloud-azure/docs/current/reference/html/index.html#azure-common-configuration-options-5
2. Also you could choose set different proxy for consumer/produer with `spring.cloud.azure.servicebus.processor.proxy.*` and `spring.cloud.azure.servicebus.producer.proxy.*`. If configured, this will override the above one.
3. You could choose to set different proxy for each consumer/procuder client when you have multiple consumers/producers, with the properties of `spring.cloud.stream.servicebus.bindings.<binding-name>.consumer.proxy.*` and `spring.cloud.stream.servicebus.bindings.<binding-name>.producer.proxy.*`. Also this will override the above ones.

**Comment by preethamjebarajjohn** [comment]
Thanks @yiliuTo . I will start consuming it after December 20, 2021. Can you confirm if below configuration works ? 

spring.cloud.azure.servicebus.proxy = http://hostname:portnumber

**Comment by yiliuTo** [comment]
Hi @preethamjebarajjohn , due to some interval plans, we didn't release the GA version of 4.0.0 in December, you could subscribe to this issue to track the GA release plan. https://github.com/Azure/azure-sdk-for-java/issues/24327
