### ISSUE TITLE
[BUG] Cosmos spark - Spark job does not finish after "transient" errors connecting to CosmosDB

### ISSUE THREAD

**Issue by klesouza** [Azure/azure-sdk-for-java#25600]
**Describe the bug**
Spark job does not finish when writing to CosmosDB.  
I have a spark job that reads from a Delta table and writes to CosmosDB, this job usually runs for a few hours, but I see sometimes it keeps running for days (if I don't cancel). In the logs I just see some issues connecting to the cosmos DB instance. But I would expect the job to fail at some point.

***Exception or Stack Trace***

```
21/11/15 14:55:42 WARN HttpClientConnect: [id:8e36b835-46, L:/10.13.2.4:33624 - R:[COSMOS URL]] The connection observed an error
azure_cosmos_spark.io.netty.handler.timeout.ReadTimeoutException
21/11/15 14:55:42 ERROR RxGatewayStoreModel: Network failure
azure_cosmos_spark.io.netty.handler.timeout.ReadTimeoutException
21/11/15 14:55:42 WARN ClientRetryPolicy: shouldRetryQueryPlanAndAddress() Retrying on endpoint [COSMOS URL HERE]/, operationType = QueryPlan, count = 1, isAddressRefresh = false
21/11/15 14:58:01 WARN HttpClientConnect: [id:ed0d43b5-1, L:/[IP] - R:[COSMOS URL HERE]] The connection observed an error
azure_cosmos_spark.io.netty.handler.timeout.ReadTimeoutException
21/11/15 14:58:01 ERROR RxGatewayStoreModel: Network failure
azure_cosmos_spark.io.netty.handler.timeout.ReadTimeoutException
21/11/15 14:58:01 WARN RxDocumentClientImpl: Failed to retrieve database account information. azure_cosmos_spark.io.netty.handler.timeout.ReadTimeoutException
21/11/15 14:58:01 ERROR GlobalEndpointManager: Fail to reach global gateway [COSMOS URL HERE], [{"innerErrorMessage":null,"cosmosDiagnostics":{"userAgent":"azsdk-java-cosmos/4.16.0-beta.2 Linux/5.4.0-1062-azure JRE/1.8.0_302","requestLatencyInMs":60092,"requestStartTimeUTC":"2021-11-15T14:57:01.573Z","requestEndTimeUTC":"2021-11-15T14:58:01.665Z","responseStatisticsList":[],"supplementalResponseStatisticsList":[],"addressResolutionStatistics":{},"regionsContacted":[],"retryContext":{"statusAndSubStatusCodes":null,"retryLatency":0,"retryCount":0},"metadataDiagnosticsContext":{"metadataDiagnosticList":null},"serializationDiagnosticsContext":{"serializationDiagnosticsList":null},"gatewayStatistics":{"sessionToken":null,"operationType":"Read","resourceType":"DatabaseAccount","statusCode":0,"subStatusCode":10002,"requestCharge":null,"requestTimeline":null},"systemInformation":{"usedMemory":"1549591 KB","availableMemory":"4762345 KB","systemCpuLoad":"(2021-11-15T14:57:34Z 4.0%), (2021-11-15T14:57:39Z 3.5%), (2021-11-15T14:57:44Z 4.8%), (2021-11-15T14:57:49Z 3.8%), (2021-11-15T14:57:54Z 8.2%), (2021-11-15T14:57:59Z 4.8%)","availableProcessors":4},"clientCfgs":{"id":0,"connectionMode":"DIRECT","numberOfClients":1,"connCfg":{"rntbd":"(cto:PT5S, rto:PT5S, icto:PT0S, ieto:PT1H, mcpe:130, mrpc:30, cer:false)","gw":"(cps:1000, rto:PT5S, icto:null, p:false)","other":"(ed: true, cs: false)"},"consistencyCfg":"(consistency: Eventual, mm: true, prgns: [])"}}}]
21/11/15 14:58:01 ERROR GlobalEndpointManager: startRefreshLocationTimerAsync() - Unable to refresh database account from any location. Exception: {"ClassName":"CosmosException","userAgent":"azsdk-java-cosmos/4.16.0-beta.2 Linux/5.4.0-1062-azure JRE/1.8.0_302","statusCode":0,"resourceAddress":"[COSMOS URL HERE]","innerErrorMessage":null,"causeInfo":"[class: class azure_cosmos_spark.io.netty.handler.timeout.ReadTimeoutException, message: null]","responseHeaders":"{x-ms-substatus=10002}","requestHeaders":"[Accept=application/json, x-ms-date=Mon, 15 Nov 2021 14:57:01 GMT]","cosmosDiagnostics":{"userAgent":"azsdk-java-cosmos/4.16.0-beta.2 Linux/5.4.0-1062-azure JRE/1.8.0_302","requestLatencyInMs":60092,"requestStartTimeUTC":"2021-11-15T14:57:01.573Z","requestEndTimeUTC":"2021-11-15T14:58:01.665Z","responseStatisticsList":[],"supplementalResponseStatisticsList":[],"addressResolutionStatistics":{},"regionsContacted":[],"retryContext":{"statusAndSubStatusCodes":null,"retryLatency":0,"retryCount":0},"metadataDiagnosticsContext":{"metadataDiagnosticList":null},"serializationDiagnosticsContext":{"serializationDiagnosticsList":null},"gatewayStatistics":{"sessionToken":null,"operationType":"Read","resourceType":"DatabaseAccount","statusCode":0,"subStatusCode":10002,"requestCharge":null,"requestTimeline":null},"systemInformation":{"usedMemory":"1550355 KB","availableMemory":"4761581 KB","systemCpuLoad":"(2021-11-15T14:57:34Z 4.0%), (2021-11-15T14:57:39Z 3.5%), (2021-11-15T14:57:44Z 4.8%), (2021-11-15T14:57:49Z 3.8%), (2021-11-15T14:57:54Z 8.2%), (2021-11-15T14:57:59Z 4.8%)","availableProcessors":4},"clientCfgs":{"id":0,"connectionMode":"DIRECT","numberOfClients":1,"connCfg":{"rntbd":"(cto:PT5S, rto:PT5S, icto:PT0S, ieto:PT1H, mcpe:130, mrpc:30, cer:false)","gw":"(cps:1000, rto:PT5S, icto:null, p:false)","other":"(ed: true, cs: false)"},"consistencyCfg":"(consistency: Eventual, mm: true, prgns: [])"}}}
{"ClassName":"CosmosException","userAgent":"azsdk-java-cosmos/4.16.0-beta.2 Linux/5.4.0-1062-azure JRE/1.8.0_302","statusCode":0,"resourceAddress":"[COSMOS URL HERE]","innerErrorMessage":null,"causeInfo":"[class: class azure_cosmos_spark.io.netty.handler.timeout.ReadTimeoutException, message: null]","responseHeaders":"{x-ms-substatus=10002}","requestHeaders":"[Accept=application/json, x-ms-date=Mon, 15 Nov 2021 14:57:01 GMT]","cosmosDiagnostics":{"userAgent":"azsdk-java-cosmos/4.16.0-beta.2 Linux/5.4.0-1062-azure JRE/1.8.0_302","requestLatencyInMs":60092,"requestStartTimeUTC":"2021-11-15T14:57:01.573Z","requestEndTimeUTC":"2021-11-15T14:58:01.665Z","responseStatisticsList":[],"supplementalResponseStatisticsList":[],"addressResolutionStatistics":{},"regionsContacted":[],"retryContext":{"statusAndSubStatusCodes":null,"retryLatency":0,"retryCount":0},"metadataDiagnosticsContext":{"metadataDiagnosticList":null},"serializationDiagnosticsContext":{"serializationDiagnosticsList":null},"gatewayStatistics":{"sessionToken":null,"operationType":"Read","resourceType":"DatabaseAccount","statusCode":0,"subStatusCode":10002,"requestCharge":null,"requestTimeline":null},"systemInformation":{"usedMemory":"1550389 KB","availableMemory":"4761547 KB","systemCpuLoad":"(2021-11-15T14:57:34Z 4.0%), (2021-11-15T14:57:39Z 3.5%), (2021-11-15T14:57:44Z 4.8%), (2021-11-15T14:57:49Z 3.8%), (2021-11-15T14:57:54Z 8.2%), (2021-11-15T14:57:59Z 4.8%)","availableProcessors":4},"clientCfgs":{"id":0,"connectionMode":"DIRECT","numberOfClients":1,"connCfg":{"rntbd":"(cto:PT5S, rto:PT5S, icto:PT0S, ieto:PT1H, mcpe:130, mrpc:30, cer:false)","gw":"(cps:1000, rto:PT5S, icto:null, p:false)","other":"(ed: true, cs: false)"},"consistencyCfg":"(consistency: Eventual, mm: true, prgns: [])"}}}
	at azure_cosmos_spark.com.azure.cosmos.BridgeInternal.createCosmosException(BridgeInternal.java:454)
	at azure_cosmos_spark.com.azure.cosmos.implementation.RxGatewayStoreModel.lambda$toDocumentServiceResponse$3(RxGatewayStoreModel.java:323)
	at azure_cosmos_spark.reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94)
	at azure_cosmos_spark.reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onError(FluxMapFuseable.java:140)
	at azure_cosmos_spark.reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:172)
	at azure_cosmos_spark.reactor.core.publisher.MonoSingle$SingleSubscriber.onError(MonoSingle.java:150)
	at azure_cosmos_spark.reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:106)
	at azure_cosmos_spark.reactor.core.publisher.Operators.error(Operators.java:197)
	at azure_cosmos_spark.reactor.core.publisher.MonoError.subscribe(MonoError.java:52)
	at azure_cosmos_spark.reactor.core.publisher.Mono.subscribe(Mono.java:4150)
	at azure_cosmos_spark.reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103)
	at azure_cosmos_spark.reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onError(FluxPeekFuseable.java:234)
	at azure_cosmos_spark.reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onError(FluxContextWrite.java:121)
	at azure_cosmos_spark.reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onError(MonoFlatMapMany.java:204)
	at azure_cosmos_spark.reactor.core.publisher.SerializedSubscriber.onError(SerializedSubscriber.java:124)
	at azure_cosmos_spark.reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.whenError(FluxRetryWhen.java:224)
	at azure_cosmos_spark.reactor.core.publisher.FluxRetryWhen$RetryWhenOtherSubscriber.onError(FluxRetryWhen.java:273)
	at azure_cosmos_spark.reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:413)
	at azure_cosmos_spark.reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onNext(FluxConcatMap.java:250)
	at azure_cosmos_spark.reactor.core.publisher.EmitterProcessor.drain(EmitterProcessor.java:491)
	at azure_cosmos_spark.reactor.core.publisher.EmitterProcessor.tryEmitNext(EmitterProcessor.java:299)
	at azure_cosmos_spark.reactor.core.publisher.SinkManySerialized.tryEmitNext(SinkManySerialized.java:97)
	at azure_cosmos_spark.reactor.core.publisher.InternalManySink.emitNext(InternalManySink.java:27)
	at azure_cosmos_spark.reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.onError(FluxRetryWhen.java:189)
	at azure_cosmos_spark.reactor.core.publisher.MonoCreate$DefaultMonoSink.error(MonoCreate.java:189)
	at azure_cosmos_spark.reactor.netty.http.client.HttpClientConnect$HttpObserver.onUncaughtException(HttpClientConnect.java:358)
	at azure_cosmos_spark.reactor.netty.ReactorNetty$CompositeConnectionObserver.onUncaughtException(ReactorNetty.java:647)
	at azure_cosmos_spark.reactor.netty.resources.DefaultPooledConnectionProvider$DisposableAcquire.onUncaughtException(DefaultPooledConnectionProvider.java:214)
	at azure_cosmos_spark.reactor.netty.resources.DefaultPooledConnectionProvider$PooledConnection.onUncaughtException(DefaultPooledConnectionProvider.java:462)
	at azure_cosmos_spark.reactor.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:233)
	at azure_cosmos_spark.reactor.netty.channel.FluxReceive.onInboundError(FluxReceive.java:454)
	at azure_cosmos_spark.reactor.netty.channel.ChannelOperations.onInboundError(ChannelOperations.java:485)
	at azure_cosmos_spark.reactor.netty.channel.ChannelOperationsHandler.exceptionCaught(ChannelOperationsHandler.java:127)
	at azure_cosmos_spark.io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302)
	at azure_cosmos_spark.io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:281)
	at azure_cosmos_spark.io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:273)
	at azure_cosmos_spark.io.netty.handler.timeout.ReadTimeoutHandler.readTimedOut(ReadTimeoutHandler.java:98)
	at azure_cosmos_spark.io.netty.handler.timeout.ReadTimeoutHandler.channelIdle(ReadTimeoutHandler.java:90)
	at azure_cosmos_spark.io.netty.handler.timeout.IdleStateHandler$ReaderIdleTimeoutTask.run(IdleStateHandler.java:504)
	at azure_cosmos_spark.io.netty.handler.timeout.IdleStateHandler$AbstractIdleTask.run(IdleStateHandler.java:476)
	at azure_cosmos_spark.io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at azure_cosmos_spark.io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
	at azure_cosmos_spark.io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at azure_cosmos_spark.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at azure_cosmos_spark.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at azure_cosmos_spark.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at azure_cosmos_spark.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at azure_cosmos_spark.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: azure_cosmos_spark.io.netty.handler.timeout.ReadTimeoutException

```

**To Reproduce**
Write to CosmosDB.  
It's not consistent error. It seems due to intermittent connectivity issues with CosmosDB instance

***Code Snippet***
`data.write.format("cosmos.oltp").options(**spark_cosmos_write_conf).mode("APPEND").save()`

**Expected behavior**
If there's a consistent problem to connect to the CosmosDB instance, I would expect my job to finish with a failed state.

**Setup (please complete the following information):**
 - Library/Libraries: com.azure.cosmos.spark:azure-cosmos-spark_3-1_2-12:4.1.0
 - Java version: [e.g. 8] 
 - App Server/Environment:Apache Spark, Databricks, PySpark 

  
**Additional context**
This does not happen consistently, It works most of the time.  
I'm using the container Throughput control to write.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ x ] Bug Description Added
- [ x ] Repro Steps Added
- [ x ] Setup information Added

**Comment by pallavit** [comment]
@kushagraThapar can you please help route the issue.

**Comment by kushagraThapar** [comment]
@moderakh  - please help me route this issue, or take a look, thanks!

**Comment by kushagraThapar** [comment]
@klesouza - please upgrade to the latest version of the connector, I believe this has been fixed.

**Comment by TealDep** [comment]
@kushagraThapar having a similar issue with azure-cosmos-spark_3-1_2-12 after session stop as well driver not shutting down keeps connections open
22/02/15 09:11:24 INFO com.walmart.canada.ims.app.CosmosSparkJob: Saved to DB
22/02/15 09:11:24 INFO org.sparkproject.jetty.server.AbstractConnector: Stopped Spark@2307f1a8{HTTP/1.1, (http/1.1)}{0.0.0.0:0}
22/02/15 09:15:57 INFO azure_cosmos_spark.com.azure.cosmos.implementation.RxDocumentClientImpl: Getting database account endpoint from https://{}.documents.azure.com:443
22/02/15 09:20:57 INFO azure_cosmos_spark.com.azure.cosmos.implementation.RxDocumentClientImpl: Getting database account endpoint from https://{}.documents.azure.com:443
22/02/15 09:25:58 INFO azure_cosmos_spark.com.azure.cosmos.implementation.RxDocumentClientImpl: Getting database account endpoint from https://{}documents.azure.com:443

**Comment by kushagraThapar** [comment]
@FabianMeiswinkel   - can you please look at this?

**Comment by FabianMeiswinkel** [comment]
Yes @TealDep created #27120 for this - and I have assigned it to myself already and added it to the Spark project backlog

**Comment by FabianMeiswinkel** [comment]
I think we can keep this one closed - because this one was about a hand during bulk ingestion in 4.1.0 (which is fixed). @TealDep is facing an issue where the app/console isn't shutting down because the CosmosClient is still open and netty-io threads are not daemon threads. So different issue.

**Comment by shea3100** [comment]
@FabianMeiswinkel  any update on this issue? I'm facing same issue @TealDep is facing using  azure-cosmos-spark_3-2_2-12 verison4.17.0 with spark 3.2
