### ISSUE TITLE
ScopeLocked error on read operation

### ISSUE THREAD

**Issue by brokenjpl** [Azure/azure-sdk-for-java#2560]
I have my ResourceGroup, RG, which I've added a read only lock. In the SDK, I perform the following operations:

`List<StorageAccount> sas = azure.storageAccounts().listByResourceGroup("RG");`

Then, for each storage account in the the resource group I perform the following:

`storageAccount.getKeys();`

This results in the following error:

`Status code 409, {"error":{"code":"ScopeLocked","message":"The scope '/subscriptions/removed/resourceGroups/RG/providers/Microsoft.Storage/storageAccounts/diagnosticStorageAccountName' cannot perform write operation because following scope(s) are locked: '/subscriptions/removed/resourceGroups/RG'. Please remove the lock and try again."}}`

The stack trace is as follows:

```
com.microsoft.azure.CloudException: Status code 409, {"error":{"code":"ScopeLocked","message":"The scope '/subscriptions/removed/resourceGroups/RG/providers/Microsoft.Storage/storageAccounts/diagnosticStorageAccountName' cannot perform write operation because following scope(s) are locked: '/subscriptions/removed/resourceGroups/RG'. Please remove the lock and try again."}}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_161]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_161]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_161]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_161]
	at com.microsoft.rest.ServiceResponseBuilder.build(ServiceResponseBuilder.java:122) ~[client-runtime-1.6.3.jar:?]
	at com.microsoft.azure.AzureResponseBuilder.build(AzureResponseBuilder.java:56) ~[azure-client-runtime-1.6.3.jar:?]
	at com.microsoft.azure.management.storage.implementation.StorageAccountsInner.listKeysDelegate(StorageAccountsInner.java:873) ~[azure-mgmt-storage-1.1.2.jar:1.1.2]
	at com.microsoft.azure.management.storage.implementation.StorageAccountsInner.access$700(StorageAccountsInner.java:46) ~[azure-mgmt-storage-1.1.2.jar:1.1.2]
	at com.microsoft.azure.management.storage.implementation.StorageAccountsInner$29.call(StorageAccountsInner.java:860) ~[azure-mgmt-storage-1.1.2.jar:1.1.2]
	at com.microsoft.azure.management.storage.implementation.StorageAccountsInner$29.call(StorageAccountsInner.java:856) ~[azure-mgmt-storage-1.1.2.jar:1.1.2]
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69) ~[rxjava-1.2.4.jar:1.2.4]
	at retrofit2.adapter.rxjava.CallArbiter.deliverResponse(CallArbiter.java:120) ~[adapter-rxjava-2.4.0.jar:?]
	at retrofit2.adapter.rxjava.CallArbiter.emitResponse(CallArbiter.java:102) ~[adapter-rxjava-2.4.0.jar:?]
	at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:46) ~[adapter-rxjava-2.4.0.jar:?]
	at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:24) ~[adapter-rxjava-2.4.0.jar:?]
	at rx.Observable.unsafeSubscribe(Observable.java:10142) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.Observable.unsafeSubscribe(Observable.java:10142) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.Observable.unsafeSubscribe(Observable.java:10142) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.Observable.unsafeSubscribe(Observable.java:10142) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.internal.operators.DeferredScalarSubscriber.subscribeTo(DeferredScalarSubscriber.java:153) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.internal.operators.OnSubscribeTakeLastOne.call(OnSubscribeTakeLastOne.java:32) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.internal.operators.OnSubscribeTakeLastOne.call(OnSubscribeTakeLastOne.java:22) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.Observable.subscribe(Observable.java:10238) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.Observable.subscribe(Observable.java:10205) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:444) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.observables.BlockingObservable.last(BlockingObservable.java:227) ~[rxjava-1.2.4.jar:1.2.4]
	at com.microsoft.azure.management.storage.implementation.StorageAccountImpl.getKeys(StorageAccountImpl.java:113) ~[azure-mgmt-storage-1.1.2.jar:1.1.2]
```

Please advise if this is intended, or an issue with the SDK.

Thanks,
JP

**Comment by vhvb1989** [comment]
Hello @brokenjpl

I am sorry about you didn't get a sooner answer on this
Do you still need help? Let me know and I would be happy to assist.

Note: As part of repository cleaning effort, this issue will be closed by Sep 20 if no response is received from submitter and/or not further action is required.
