### ISSUE TITLE
[BUG] Cosmos query throws exception with 'rid must not be null'

### ISSUE THREAD

**Issue by zhoujia1974** [Azure/azure-sdk-for-java#25778]
**Describe the bug**
We are using CosmosTemplate.runPaginationQuery to retrieve a page of the documents. The query itself does a join with child collection and returns the distinct parent documents. The filter is simply based on the partition key. The page size is 100. The code throws an exception as below.

`java.lang.IllegalArgumentException: rid must not be null.
		at com.azure.cosmos.implementation.query.OrderByContinuationToken.<init>(OrderByContinuationToken.java:44) ~[azure-cosmos-4.16.0.jar!/:na]
		at com.azure.cosmos.implementation.query.OrderByDocumentQueryExecutionContext.getContinuationToken(OrderByDocumentQueryExecutionContext.java:560) ~[azure-cosmos-4.16.0.jar!/:na]
		at com.azure.cosmos.implementation.query.OrderByDocumentQueryExecutionContext$ItemToPageTransformer.lambda$apply$4(OrderByDocumentQueryExecutionContext.java:459) ~[azure-cosmos-4.16.0.jar!/:na]
		at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:106) ~[reactor-core-3.4.11.jar!/:3.4.11]
		at reactor.core.publisher.FluxSkip$SkipSubscriber.onNext(FluxSkip.java:87) ~[reactor-core-3.4.11.jar!/:3.4.11]
		at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:120) ~[reactor-core-3.4.11.jar!/:3.4.11]
		at reactor.core.publisher.FluxConcatArray$ConcatArraySubscriber.onNext(FluxConcatArray.java:201) ~[reactor-core-3.4.11.jar!/:3.4.11]
		at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:120) ~[reactor-core-3.4.11.jar!/:3.4.11]
		at reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:712) ~[reactor-core-3.4.11.jar!/:3.4.11]
		at reactor.core.publisher.FluxFlatMap$FlatMapMain.drain(FluxFlatMap.java:588) ~[reactor-core-3.4.11.jar!/:3.4.11]
		at reactor.core.publisher.FluxFlatMap$FlatMapInner.onNext(FluxFlatMap.java:971) ~[reactor-core-3.4.11.jar!/:3.4.11]
...
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99) ~[reactor-core-3.4.11.jar!/:3.4.11]
		at reactor.core.publisher.Mono.block(Mono.java:1706) ~[reactor-core-3.4.11.jar!/:3.4.11]
		at com.azure.spring.data.cosmos.core.CosmosTemplate.sliceQuery(CosmosTemplate.java:714) ~[azure-spring-data-cosmos-3.8.0.jar!/:na]
		at com.azure.spring.data.cosmos.core.CosmosTemplate.paginationQuery(CosmosTemplate.java:676) ~[azure-spring-data-cosmos-3.8.0.jar!/:na]
		at com.azure.spring.data.cosmos.core.CosmosTemplate.runPaginationQuery(CosmosTemplate.java:657) ~[azure-spring-data-cosmos-3.8.0.jar!/:na]
...`

There are exactly 100 documents match the filter. I initially suspect there is a bug on cosmos sdk side that incorrectly handle the continuation token for paged query when page size equals the total document count. And we tested it again by reducing the document count to less than 100. But the error still shows up until we reduce the count to less than 50.

The document is like below.
`{ "id": "111", "partitionKey": "AA", "child": [ { "name": "John" }, { "name": "Jason" } ] }`

The query is like below.
`SELECT DISTINCT c.id, c.partitionKey, c.child FROM c JOIN i IN c.child WHERE c.partitionKey = 'AA' ORDER BY c.id`

***Exception or Stack Trace***
Please see the stack trace in description

**To Reproduce**

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - OS: [windows, *nix]
 - IDE: [Eclipse]
 - Library/Libraries: [com.azure.spring:azure-spring-boot-starter-cosmos:3.6.0]
 - Java version: [11] 
 - App Server/Environment: [Tomcat]
 - Frameworks: [Spring Boot] 

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please provide
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
  
**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by joshfree** [comment]
@backwind1233 could you please take a look?

**Comment by backwind1233** [comment]
Thanks for reaching us, @zhoujia1974
I will look into this issue.

**Comment by zhoujia1974** [comment]
Follow up on this ticket, I debugged the call stack and was able to figure out the root cause. For custom sql using pagination, the sql select part must include Cosmos built in column _rid in the document. Cosmos internally uses this _rid to build the continuationToken. This needs to be documented somewhere.

**Comment by xinlian12** [comment]
@zhoujia1974  _rid is an internal property used in cosmos, you should not put it in the select query part.

And I have not been able to repro locally with a similar query, can u provide a repro sample?
Can u also try if you change to use exists  instead of join in the query, would the issue still exists?
 https://docs.microsoft.com/en-us/azure/cosmos-db/sql/sql-query-subquery#exists-expression

Thanks

**Comment by zhoujia1974** [comment]
@xinlian12 I don't have a simplified project for you to check. If you want, we can set up a team meeting and I can debug the code with you.

But meanwhile, here is the basic steps how we get this error.

      Pageable pageable =
          CosmosPageRequest.of(0, 0, 50, null, Sort.unsorted());

      String queryString = "SELECT DISTINCT c.id, c.partitionKey, c.child FROM c JOIN i IN c.child WHERE c.partitionKey = @partitionKey ORDER BY c.id";
      SqlQuerySpec sqlQuerySpec = new SqlQuerySpec(queryString, List.of(new SqlParameter("@partitionKey", "aa")));
      
     cosmosTemplate.runPaginationQuery(
              sqlQuerySpec, pageable, SomeEntity.class, SomeEntity.class);

**Comment by xinlian12** [comment]
@zhoujia1974  yea, we can do that. Can u reach out to Kushagra.Thapar@microsoft.com? And then we can schedule our debugging session from there. Thanks

**Comment by Diego10Rocha** [comment]
@Diego10Rocha, @luanpereira and @G3Quixabeira , managed to solve this problem as follows:
`**SELECT * FROM (**SELECT DISTINCT c.id, c.partitionKey, c.child, **c._rid** FROM c JOIN i IN c.child WHERE c.partitionKey = 'AA' ORDER BY c.id**)**`
It doesn't make sense, but it solved the problem.
