### ISSUE TITLE
[BUG] connection timeout is being ignored

### ISSUE THREAD

**Issue by eyal33** [Azure/azure-sdk-for-java#25777]
**Describe the bug**
I am trying to create via azure java sdk a blob container while the azurite local docker is down.
I was expected that after the configured timeout is elapsed, I'll get an exception.
However, the exception was thrown after around 60 seconds.

***Exception or Stack Trace***
Before creating container Thu Dec 02 08:32:29 IST 2021
Error in creating container Thu Dec 02 08:33:30 IST 2021
reactor.core.Exceptions$ReactiveException: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/0:0:0:0:0:0:0:1:10000
	at reactor.core.Exceptions.propagate(Exceptions.java:392)
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:97)
	at reactor.core.publisher.Mono.block(Mono.java:1706)
	at com.azure.storage.common.implementation.StorageImplUtils.blockWithOptionalTimeout(StorageImplUtils.java:128)
	at com.azure.storage.blob.BlobContainerClient.createWithResponse(BlobContainerClient.java:266)
	at com.azure.storage.blob.BlobServiceClient.createBlobContainerWithResponse(BlobServiceClient.java:132)
	at com.azure.storage.blob.BlobServiceClient.createBlobContainer(BlobServiceClient.java:107)
	at com.blobs.quickstart.AppForBug.main(AppForBug.java:46)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
		... 6 more
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/0:0:0:0:0:0:0:1:10000
Caused by: java.net.ConnectException: Connection refused: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:779)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:707)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)

**To Reproduce**
create a new container when the local container is down. No need to start any container for that. 

***Code Snippet***

public static void main( String[] args ) throws IOException {
        try {
            String connectionStr = "DefaultEndpointsProtocol=https;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://localhost:10000/devstoreaccount1";

            HttpClient httpClient = new NettyAsyncHttpClientBuilder()
                    .connectTimeout(Duration.ofMillis(5111))
                    .responseTimeout(Duration.ofMillis(2222))
                    .build();

            BlobServiceClient blobServiceClient = new BlobServiceClientBuilder()
                                        .httpClient(httpClient)
                                        .connectionString(connectionStr).buildClient();

            //Create a unique name for the container
            String containerName = "quickstartblobs" + java.util.UUID.randomUUID();

            System.out.println("Before creating container " + new Date());

            //BlobContainerClient containerClient = blobServiceClient.getBlobContainerClient("quickstartblobs5c14670c-0eae-4605-939f-5dd99b7880ed");
            BlobContainerClient containerClient = blobServiceClient.createBlobContainer(containerName);

            System.out.println("After creating container " + new Date());

        } catch (Exception e) {
            System.out.println("Error in creating container " + new Date());
            e.printStackTrace();
        }

    }

**Expected behavior**
I was expected that after at most 6 seconds, exception will be thrown.
(       .connectTimeout(Duration.ofMillis(5111)) )

**Screenshots**

**Setup (please complete the following information):**
 - OS: Windows
 - IDE:  IntelliJ
 - Library/Libraries: com.azure:azure-storage-blob:12.14.2 , com.microsoft.azure:azure-storage:8.6.6
 - Java version: 8 
 - App Server/Environment: Intellij
 - Frameworks: Java Main, Spring Boot 

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please provide
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
  
**Additional context**
- The same problem occurs when running on com.azure:azure-storage-blob:12.13.0 .
- The same problem occurs when running on Spring boot.
- The same problem occurs when trying to create a blob.
- The same problem occurs when using OkHttpAsyncHttpClientBuilder instead of NettyAsyncHttpClientBuilder.
- The same problem occurs when using async clients.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Adde
[pom.xml.txt](https://github.com/Azure/azure-sdk-for-java/files/7639694/pom.xml.txt)
[AppForBug.java.txt](https://github.com/Azure/azure-sdk-for-java/files/7639703/AppForBug.java.txt)
d

**Comment by eyal33** [comment]
Any update?

**Comment by joshfree** [comment]
@alzimmermsft could you please follow up?

**Comment by alzimmermsft** [comment]
Hi @eyal33, thanks for filing this issue.

What is happening here is that, by default, `BlobContainerClient` uses a retry policy for failed requests, in this case anything that is an IOException or a 500/503 HTTP response, and the connection timeout is a retryable error. So, the connection timeout is likely happening in 5 seconds it is being retried a few times with a backoff on each retry getting a total request time to the 60 seconds you're seeing.

Could you add this update and verify whether the request fails in roughly 5 seconds as expected:

```java
BlobServiceClient blobServiceClient = new BlobServiceClientBuilder()
    .httpClient(httpClient)
    .connectionString(connectionStr)
    .retryOptions(new RequestRetryOptions(null, 1, null, null, null, null))
    .buildClient();
```

This configures the client to only try a request once, so if the timeout is working properly it should fail in roughly 6 seconds.

**Comment by alzimmermsft** [comment]
@eyal33 was what I provided above able to help resolve the issue?

**Comment by eyal33** [comment]
Yes. Thanks a lot.

בתאריך יום ג׳, 26 באפר׳ 2022, 17:27, מאת Alan Zimmer ‏<
***@***.***>:

**Comment by alzimmermsft** [comment]
Closing as resolved based on the last comment
