### ISSUE TITLE
[BUG] createContainerIfNotExists: Resource with specified id, name, or unique index already exists.

### ISSUE THREAD

**Issue by Horcrux7** [Azure/azure-sdk-for-java#25918]
**Describe the bug**

The method CosmosDatabase.createContainerIfNotExists(CosmosContainerProperties) throws sporadic an exception with the StatusCodes.CONFLICT (409)

***Exception or Stack Trace***

{"ClassName":"CosmosException","userAgent":"azsdk-java-cosmos/4.17.0 Linux/5.4.0-84-generic JRE/11.0.12","statusCode":409,"resourceAddress":"https://10.10.1.150:8081/dbs/test/colls","error":"{\"code\":\"Conflict\",\"message\":\"Message: {\\\"Errors\\\":[\\\"Resource with specified id, name, or unique index already exists.\\\"]}\\r\\nActivityId: f428f58a-4891-4026-a35b-7a388fd20864, Request URI: /apps/DocDbApp/services/DocDbMaster0/partitions/780e44f4-38c8-11e6-8106-8cdcd42c33be/replicas/1p/, RequestStats: \\r\\nRequestStartTime: 2021-12-09T02:52:46.6486560Z, RequestEndTime: 2021-12-09T02:52:46.6576110Z,  Number of regions attempted:1\\r\\n{\\\"systemHistory\\\":[{\\\"dateUtc\\\":\\\"2021-12-09T02:51:55.2356642Z\\\",\\\"cpu\\\":36,328,\\\"memory\\\":8016379904,000,\\\"threadInfo\\\":{\\\"isThreadStarving\\\":\\\"False\\\",\\\"threadWaitIntervalInMs\\\":0,0385,\\\"availableThreads\\\":32764,\\\"minThreads\\\":4,\\\"maxThreads\\\":32767}},{\\\"dateUtc\\\":\\\"2021-12-09T02:52:05.2487324Z\\\",\\\"cpu\\\":38,495,\\\"memory\\\":7897845760,000,\\\"threadInfo\\\":{\\\"isThreadStarving\\\":\\\"False\\\",\\\"threadWaitIntervalInMs\\\":0,1653,\\\"availableThreads\\\":32766,\\\"minThreads\\\":4,\\\"maxThreads\\\":32767}},{\\\"dateUtc\\\":\\\"2021-12-09T02:52:15.2506532Z\\\",\\\"cpu\\\":38,594,\\\"memory\\\":7938097152,000,\\\"threadInfo\\\":{\\\"isThreadStarving\\\":\\\"False\\\",\\\"threadWaitIntervalInMs\\\":1,2199,\\\"availableThreads\\\":32765,\\\"minThreads\\\":4,\\\"maxThreads\\\":32767}},{\\\"dateUtc\\\":\\\"2021-12-09T02:52:25.2516405Z\\\",\\\"cpu\\\":34,570,\\\"memory\\\":8056696832,000,\\\"threadInfo\\\":{\\\"isThreadStarving\\\":\\\"False\\\",\\\"threadWaitIntervalInMs\\\":0,1391,\\\"availableThreads\\\":32765,\\\"minThreads\\\":4,\\\"maxThreads\\\":32767}},{\\\"dateUtc\\\":\\\"2021-12-09T02:52:35.2646634Z\\\",\\\"cpu\\\":33,346,\\\"memory\\\":8145162240,000,\\\"threadInfo\\\":{\\\"isThreadStarving\\\":\\\"False\\\",\\\"threadWaitIntervalInMs\\\":0,1365,\\\"availableThreads\\\":32766,\\\"minThreads\\\":4,\\\"maxThreads\\\":32767}},{\\\"dateUtc\\\":\\\"2021-12-09T02:52:45.2656145Z\\\",\\\"cpu\\\":33,867,\\\"memory\\\":8257957888,000,\\\"threadInfo\\\":{\\\"isThreadStarving\\\":\\\"False\\\",\\\"threadWaitIntervalInMs\\\":0,15,\\\"availableThreads\\\":32765,\\\"minThreads\\\":4,\\\"maxThreads\\\":32767}}]}\\r\\nRequestStart: 2021-12-09T02:52:46.6486560Z; ResponseTime: 2021-12-09T02:52:46.6576110Z; StoreResult: StorePhysicalAddress: rntbd://10.10.1.150:10251/apps/DocDbApp/services/DocDbMaster0/partitions/780e44f4-38c8-11e6-8106-8cdcd42c33be/replicas/1p/, LSN: 36888, GlobalCommittedLsn: -1, PartitionKeyRangeId: , IsValid: True, StatusCode: 409, SubStatusCode: 0, RequestCharge: 0, ItemLSN: -1, SessionToken: -1#36888, UsingLocalLSN: False, TransportException: null, BELatencyMs: 6.474, ActivityId: f428f58a-4891-4026-a35b-7a388fd20864, TransportRequestTimeline: {\\\"requestTimeline\\\":[{\\\"event\\\": \\\"Created\\\", \\\"startTimeUtc\\\": \\\"2021-12-09T02:52:46.6486560Z\\\", \\\"durationInMs\\\": 0.0277},{\\\"event\\\": \\\"ChannelAcquisitionStarted\\\", \\\"startTimeUtc\\\": \\\"2021-12-09T02:52:46.6486837Z\\\", \\\"durationInMs\\\": 0.0165},{\\\"event\\\": \\\"Pipelined\\\", \\\"startTimeUtc\\\": \\\"2021-12-09T02:52:46.6487002Z\\\", \\\"durationInMs\\\": 0.56},{\\\"event\\\": \\\"Transit Time\\\", \\\"startTimeUtc\\\": \\\"2021-12-09T02:52:46.6492602Z\\\", \\\"durationInMs\\\": 7.2411},{\\\"event\\\": \\\"Received\\\", \\\"startTimeUtc\\\": \\\"2021-12-09T02:52:46.6565013Z\\\", \\\"durationInMs\\\": 0.1351},{\\\"event\\\": \\\"Completed\\\", \\\"startTimeUtc\\\": \\\"2021-12-09T02:52:46.6566364Z\\\", \\\"durationInMs\\\": 0}],\\\"requestSizeInBytes\\\":2010,\\\"requestBodySizeInBytes\\\":1622,\\\"responseMetadataSizeInBytes\\\":163,\\\"responseBodySizeInBytes\\\":80};\\r\\n ResourceType: Collection, OperationType: BatchApply\\r\\n, SDK: Microsoft.Azure.Documents.Common/2.14.0, StatusCode: Conflict\",\"additionalErrorInfo\":null}","innerErrorMessage":"Message: {\"Errors\":[\"Resource with specified id, name, or unique index already exists.\"]}\r\nActivityId: f428f58a-4891-4026-a35b-7a388fd20864, Request URI: /apps/DocDbApp/services/DocDbMaster0/partitions/780e44f4-38c8-11e6-8106-8cdcd42c33be/replicas/1p/, RequestStats: \r\nRequestStartTime: 2021-12-09T02:52:46.6486560Z, RequestEndTime: 2021-12-09T02:52:46.6576110Z,  Number of regions attempted:1\r\n{\"systemHistory\":[{\"dateUtc\":\"2021-12-09T02:51:55.2356642Z\",\"cpu\":36,328,\"memory\":8016379904,000,\"threadInfo\":{\"isThreadStarving\":\"False\",\"threadWaitIntervalInMs\":0,0385,\"availableThreads\":32764,\"minThreads\":4,\"maxThreads\":32767}},{\"dateUtc\":\"2021-12-09T02:52:05.2487324Z\",\"cpu\":38,495,\"memory\":7897845760,000,\"threadInfo\":{\"isThreadStarving\":\"False\",\"threadWaitIntervalInMs\":0,1653,\"availableThreads\":32766,\"minThreads\":4,\"maxThreads\":32767}},{\"dateUtc\":\"2021-12-09T02:52:15.2506532Z\",\"cpu\":38,594,\"memory\":7938097152,000,\"threadInfo\":{\"isThreadStarving\":\"False\",\"threadWaitIntervalInMs\":1,2199,\"availableThreads\":32765,\"minThreads\":4,\"maxThreads\":32767}},{\"dateUtc\":\"2021-12-09T02:52:25.2516405Z\",\"cpu\":34,570,\"memory\":8056696832,000,\"threadInfo\":{\"isThreadStarving\":\"False\",\"threadWaitIntervalInMs\":0,1391,\"availableThreads\":32765,\"minThreads\":4,\"maxThreads\":32767}},{\"dateUtc\":\"2021-12-09T02:52:35.2646634Z\",\"cpu\":33,346,\"memory\":8145162240,000,\"threadInfo\":{\"isThreadStarving\":\"False\",\"threadWaitIntervalInMs\":0,1365,\"availableThreads\":32766,\"minThreads\":4,\"maxThreads\":32767}},{\"dateUtc\":\"2021-12-09T02:52:45.2656145Z\",\"cpu\":33,867,\"memory\":8257957888,000,\"threadInfo\":{\"isThreadStarving\":\"False\",\"threadWaitIntervalInMs\":0,15,\"availableThreads\":32765,\"minThreads\":4,\"maxThreads\":32767}}]}\r\nRequestStart: 2021-12-09T02:52:46.6486560Z; ResponseTime: 2021-12-09T02:52:46.6576110Z; StoreResult: StorePhysicalAddress: rntbd://10.10.1.150:10251/apps/DocDbApp/services/DocDbMaster0/partitions/780e44f4-38c8-11e6-8106-8cdcd42c33be/replicas/1p/, LSN: 36888, GlobalCommittedLsn: -1, PartitionKeyRangeId: , IsValid: True, StatusCode: 409, SubStatusCode: 0, RequestCharge: 0, ItemLSN: -1, SessionToken: -1#36888, UsingLocalLSN: False, TransportException: null, BELatencyMs: 6.474, ActivityId: f428f58a-4891-4026-a35b-7a388fd20864, TransportRequestTimeline: {\"requestTimeline\":[{\"event\": \"Created\", \"startTimeUtc\": \"2021-12-09T02:52:46.6486560Z\", \"durationInMs\": 0.0277},{\"event\": \"ChannelAcquisitionStarted\", \"startTimeUtc\": \"2021-12-09T02:52:46.6486837Z\", \"durationInMs\": 0.0165},{\"event\": \"Pipelined\", \"startTimeUtc\": \"2021-12-09T02:52:46.6487002Z\", \"durationInMs\": 0.56},{\"event\": \"Transit Time\", \"startTimeUtc\": \"2021-12-09T02:52:46.6492602Z\", \"durationInMs\": 7.2411},{\"event\": \"Received\", \"startTimeUtc\": \"2021-12-09T02:52:46.6565013Z\", \"durationInMs\": 0.1351},{\"event\": \"Completed\", \"startTimeUtc\": \"2021-12-09T02:52:46.6566364Z\", \"durationInMs\": 0}],\"requestSizeInBytes\":2010,\"requestBodySizeInBytes\":1622,\"responseMetadataSizeInBytes\":163,\"responseBodySizeInBytes\":80};\r\n ResourceType: Collection, OperationType: BatchApply\r\n, SDK: Microsoft.Azure.Documents.Common/2.14.0, StatusCode: Conflict","causeInfo":null,"responseHeaders":"{Transfer-Encoding=chunked, x-ms-last-state-change-utc=Thu, 09 Dec 2021 00:00:57.362 GMT, x-ms-current-replica-set-size=1, Server=Microsoft-HTTPAPI/2.0, x-ms-request-duration-ms=6.474, x-ms-session-token=0:-1#36888, Access-Control-Allow-Origin=, lsn=36888, x-ms-schemaversion=1.12, x-ms-transport-request-id=31703, x-ms-number-of-read-regions=0, x-ms-current-write-quorum=1, x-ms-cosmos-quorum-acked-llsn=36888, x-ms-quorum-acked-lsn=36888, Date=Thu, 09 Dec 2021 02:52:46 GMT, x-ms-activity-id=f428f58a-4891-4026-a35b-7a388fd20864, x-ms-xp-role=0, x-ms-global-Committed-lsn=-1, Access-Control-Allow-Credentials=true, x-ms-cosmos-llsn=36888, x-ms-gatewayversion=version=2.14.0, x-ms-serviceversion=version=2.14.0.0, Content-Type=application/json}","requestHeaders":"[Accept=application/json, x-ms-date=Thu, 09 Dec 2021 02:52:46 GMT, Content-Type=application/json]","cosmosDiagnostics":{"userAgent":"azsdk-java-cosmos/4.17.0 Linux/5.4.0-84-generic JRE/11.0.12","requestLatencyInMs":749,"requestStartTimeUTC":"2021-12-09T02:52:46.302510Z","requestEndTimeUTC":"2021-12-09T02:52:47.051649Z","responseStatisticsList":[],"supplementalResponseStatisticsList":[],"addressResolutionStatistics":{},"regionsContacted":["https://10.10.1.150:8081/"],"retryContext":{"statusAndSubStatusCodes":null,"retryLatency":0,"retryCount":0},"metadataDiagnosticsContext":{"metadataDiagnosticList":null},"serializationDiagnosticsContext":{"serializationDiagnosticsList":[{"serializationType":"CONTAINER_SERIALIZATION","startTimeUTC":"2021-12-09T02:52:46.302626Z","endTimeUTC":"2021-12-09T02:52:46.302659Z","durationInMicroSec":33}]},"gatewayStatistics":{"sessionToken":null,"operationType":"Create","resourceType":"DocumentCollection","statusCode":409,"subStatusCode":0,"requestCharge":null,"requestTimeline":[{"eventName":"connectionCreated","startTimeUTC":"2021-12-09T02:52:46.302734Z","durationInMicroSec":120},{"eventName":"connectionConfigured","startTimeUTC":"2021-12-09T02:52:46.302854Z","durationInMicroSec":11},{"eventName":"requestSent","startTimeUTC":"2021-12-09T02:52:46.302865Z","durationInMicroSec":129},{"eventName":"transitTime","startTimeUTC":"2021-12-09T02:52:46.302994Z","durationInMicroSec":747634},{"eventName":"received","startTimeUTC":"2021-12-09T02:52:47.050628Z","durationInMicroSec":842}]},"systemInformation":{"usedMemory":"270820 KB","availableMemory":"253468 KB","systemCpuLoad":"(2021-12-09T02:52:38.627606Z 2.1%), (2021-12-09T02:52:43.627595Z 1.7%), (2021-12-09T02:52:48.627570Z 2.2%), (2021-12-09T02:52:53.627570Z 0.5%), (2021-12-09T02:52:58.627568Z 0.7%), (2021-12-09T02:53:03.627583Z 0.7%)","availableProcessors":8},"clientCfgs":{"id":0,"connectionMode":"DIRECT","numberOfClients":1,"connCfg":{"rntbd":"(cto:PT5S, rto:PT5S, icto:PT0S, ieto:PT1H, mcpe:130, mrpc:30, cer:false)","gw":"(cps:1000, rto:PT5S, icto:null, p:false)","other":"(ed: true, cs: false)"},"consistencyCfg":"(consistency: null, mm: true, prgns: [])"}}}
	at com.azure.cosmos.BridgeInternal.createCosmosException(BridgeInternal.java:463)
	at com.azure.cosmos.implementation.RxGatewayStoreModel.validateOrThrow(RxGatewayStoreModel.java:365)
	at com.azure.cosmos.implementation.RxGatewayStoreModel.lambda$toDocumentServiceResponse$0(RxGatewayStoreModel.java:294)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:106)
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:73)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:199)
	at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:118)
	at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:220)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:130)
	at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:184)
	at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1815)
	at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:128)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:259)
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:142)
	at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:401)
	at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:416)
	at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:470)
	at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:685)
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:94)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1368)
	at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1245)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1282)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 more
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
		at reactor.core.publisher.Mono.block(Mono.java:1703)
		at com.azure.cosmos.CosmosDatabase.blockContainerResponse(CosmosDatabase.java:291)
		at com.azure.cosmos.CosmosDatabase.createContainerIfNotExists(CosmosDatabase.java:198)
		at com.inet.persistence.azure.cosmos.AzureCosmosPersistence.getOrCreateContainer(AzureCosmosPersistence.java:196)

**To Reproduce**

Try to create the same container from different threads. If you do this in a loop after some thousand containers the error should occur.

***Code Snippet***

        CosmosContainerProperties props = new CosmosContainerProperties( collectionName, "/tag/val" );

        IndexingPolicy indexing = new IndexingPolicy();
        indexing.setExcludedPaths( Arrays.asList( new ExcludedPath( "/*" ) ) );
        CompositePath path1 = new CompositePath();
        path1.setPath( "/tag" );
        CompositePath path2 = new CompositePath();
        path2.setPath( "/val" );
        indexing.setCompositeIndexes( Arrays.asList( Arrays.asList( path1, path2 ) ) );
        props.setIndexingPolicy( indexing );

        CosmosDatabase database = ...;
        return database.createContainerIfNotExists( props  );

**Expected behavior**

The method should never throw an conflict exception. If the container already exists then is should return the existing container. If this required to refresh the container list then this is needed. Because this can be triggered from different client a synchroniced in our code is not helpful.

An alternative solution is to documented this problem in the API documentation with a client code to handle this.

**Setup (please complete the following information):**
 - OS: Linux, Windows and Mac
 - IDE: -
 - Library/Libraries: com.azure:azure-cosmos:4.17.0
 - Java version: 11.0.12
 - App Server/Environment: JUnit test in a docker container with Cosmos DB Emulator
 - Frameworks:

**Comment by kushagraThapar** [comment]
Apologies @Horcrux7 for missing this issue, pls re-open if this is still a valid issue, thanks!
