### ISSUE TITLE
[BUG] Error Execution of class com.microsoft.aad.msal4j.AcquireTokenByClientCredentialSupplier failed

### ISSUE THREAD

**Issue by vmaheshw** [Azure/azure-sdk-for-java#26067]
**Describe the bug**
Error Execution of class com.microsoft.aad.msal4j.AcquireTokenByClientCredentialSupplier failed. We use credential based token to access and write to blob storage. We are seeing the exception without any clear pattern.

***Exception or Stack Trace***
2021/12/16 01:09:55.319 ERROR [ConfidentialClientApplication] [ForkJoinPool.commonPool-worker-9] [brooklin-service] [] [Correlation ID: 538e4bf3-9c44-47fc-afde-8290f7f2d462] Execution of class com.microsoft.aad.msal4j.AcquireTokenByClientCredentialSupplier failed.
com.microsoft.aad.msal4j.MsalClientException: java.net.SocketTimeoutException: Read timed out
        at com.microsoft.aad.msal4j.HttpHelper.executeHttpRequest(HttpHelper.java:53) ~[msal4j-1.11.0.jar:1.11.0]
        at com.microsoft.aad.msal4j.OAuthHttpRequest.send(OAuthHttpRequest.java:33) ~[msal4j-1.11.0.jar:1.11.0]
        at com.microsoft.aad.msal4j.TokenRequestExecutor.executeTokenRequest(TokenRequestExecutor.java:36) ~[msal4j-1.11.0.jar:1.11.0]
        at com.microsoft.aad.msal4j.AbstractClientApplicationBase.acquireTokenCommon(AbstractClientApplicationBase.java:128) ~[msal4j-1.11.0.jar:1.11.0]
        at com.microsoft.aad.msal4j.AcquireTokenByAuthorizationGrantSupplier.execute(AcquireTokenByAuthorizationGrantSupplier.java:63) ~[msal4j-1.11.0.jar:1.11.0]
        at com.microsoft.aad.msal4j.AcquireTokenByClientCredentialSupplier.acquireTokenByClientCredential(AcquireTokenByClientCredentialSupplier.java:63) ~[msal4j-1.11.0.jar:1.11.0]
        at com.microsoft.aad.msal4j.AcquireTokenByClientCredentialSupplier.execute(AcquireTokenByClientCredentialSupplier.java:49) ~[msal4j-1.11.0.jar:1.11.0]
        at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:69) [msal4j-1.11.0.jar:1.11.0]
        at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:18) [msal4j-1.11.0.jar:1.11.0]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700) [?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692) [?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) [?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) [?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) [?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) [?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) [?:?]
Caused by: java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method) ~[?:?]
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:115) ~[?:?]
        at java.net.SocketInputStream.read(SocketInputStream.java:168) ~[?:?]
        at java.net.SocketInputStream.read(SocketInputStream.java:140) ~[?:?]
        at sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:467) ~[?:?]
        at sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:461) ~[?:?]
        at sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:70) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1349) ~[?:?]
        at sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:958) ~[?:?]
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:252) ~[?:?]
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:292) ~[?:?]
        at java.io.BufferedInputStream.read(BufferedInputStream.java:351) ~[?:?]
        at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:754) ~[?:?]
        at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:689) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1615) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520) ~[?:?]
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527) ~[?:?]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:334) ~[?:?]
        at com.microsoft.aad.msal4j.DefaultHttpClient.readResponseFromConnection(DefaultHttpClient.java:107) ~[msal4j-1.11.0.jar:1.11.0]
        at com.microsoft.aad.msal4j.DefaultHttpClient.executeHttpPost(DefaultHttpClient.java:63) ~[msal4j-1.11.0.jar:1.11.0]
        at com.microsoft.aad.msal4j.DefaultHttpClient.send(DefaultHttpClient.java:37) ~[msal4j-1.11.0.jar:1.11.0]
        at com.microsoft.aad.msal4j.HttpHelper.executeHttpRequestWithRetries(HttpHelper.java:96) ~[msal4j-1.11.0.jar:1.11.0]
        at com.microsoft.aad.msal4j.HttpHelper.executeHttpRequest(HttpHelper.java:49) ~[msal4j-1.11.0.jar:1.11.0]
        ... 15 more
2021/12/16 01:09:55.323 ERROR [ClientSecretCredential] [ForkJoinPool.commonPool-worker-9] [brooklin-service] [] Azure Identity => ERROR in getToken() call for scopes [https://storage.azure.com/.default]: java.net.SocketTimeoutException: Read timed out
2021/12/16 01:09:55.324 ERROR [AccessTokenCache] [ForkJoinPool.commonPool-worker-9] [brooklin-service] [] Failed to acquire a new access token at 289 seconds before expiry. Retry may be attempted after 30 seconds. The token currently cached will be used.

**To Reproduce**
Not sure

***Code Snippet***
Not sure

**Expected behavior**
no error/exception.

**Screenshots**

**Setup (please complete the following information):**
 - IDE: [e.g. IntelliJ]
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)]
 - Java version: [e.g. 8] 
 - App Server/Environment: [e.g. Tomcat, WildFly, Azure Function, Apache Spark, Databricks, IDE plugin or anything special]
 - Frameworks: [e.g. Spring Boot, Micronaut, Quarkus, etc] 

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by lmolkova** [comment]
This issue seems to belong to  https://github.com/AzureAD/microsoft-authentication-library-for-java based on the stack trace.

It also looks like a network issue `com.microsoft.aad.msal4j.MsalClientException: java.net.SocketTimeoutException: Read timed out`. It might be a benign transient issue. 

@vmaheshw can you please help understand the severity of it: is something broken because of it or it's only a suspicious log record?

@Avery-Dunn can you please take a look? I can't transfer the issue between orgs, is it possible to do track it here, or is better to re-create one in MSAL4J repo?

**Comment by Avery-Dunn** [comment]
Hello @vmaheshw : Sorry for the delayed response. Is the issue still happening? 

You said the exception is happening 'without any clear pattern', but does it only happen when acquiring a token with a client credential (like in your stack trace here), or are you seeing the timeout error with other token flows or network calls? 

As @lmolkova said, the `java.net.SocketTimeoutException: Read timed out` usually means a network issue, rather than an issue with MSAL Java itself, especially if it's intermittent like you said.

**Comment by vmaheshw** [comment]
The issue is still happening and it is intermittent. We are keeping an eye if it results in any issue on our side. I will keep you posted.

**Comment by lmolkova** [comment]
@vmaheshw thanks for the update!

@Avery-Dunn would it be possible to write transient issues with warning/info severity and only write error if the final attempt fails?

**Comment by LoneWolfKJ** [comment]
Hi @lmolkova @Avery-Dunn ,
Any update regarding this? Am facing the same thing, it does not affect our application, but appears as error in the logs. 

am using service principal to connect to connect to the db. 
What is the cause for this, let me know if any additional info required.

The versions i am using are 
9.2.1.jre11 for mssql-jdbc
And 
1.11.0 for msal4j
