### ISSUE TITLE
Error while creating aks cluster: java.lang.NoSuchMethodError: rx.Observable.mergeDelayError(Ljava/lang/Iterable;)Lrx/Observable;

### ISSUE THREAD

**Issue by ArundathiGV** [Azure/azure-sdk-for-java#2611]
Hi,
I am trying to create aks cluster. I'm using the following libraries:

`compile group: 'com.microsoft.azure', name: 'azure', version:'1.12.0'`
`compile group: 'com.microsoft.azure', name: 'azure-mgmt-containerservice', version:'1.13.0' `

But I received the following error when attempting to create

**exception:**

java.lang.NoSuchMethodError: rx.Observable.mergeDelayError(Ljava/lang/Iterable;)Lrx/Observable;
	at com.microsoft.azure.management.resources.fluentcore.dag.TaskGroup.invokeReadyTasksAsync(TaskGroup.java:364)
	at com.microsoft.azure.management.resources.fluentcore.dag.TaskGroup.invokeInternAsync(TaskGroup.java:287)
	at com.microsoft.azure.management.resources.fluentcore.dag.TaskGroup.access$100(TaskGroup.java:44)
	at com.microsoft.azure.management.resources.fluentcore.dag.TaskGroup$1.call(TaskGroup.java:255)
	at com.microsoft.azure.management.resources.fluentcore.dag.TaskGroup$1.call(TaskGroup.java:240)
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:44)
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:33)
	at rx.Observable$2.call(Observable.java:169)
	at rx.Observable$2.call(Observable.java:162)
	at rx.Observable$2.call(Observable.java:169)
	at rx.Observable$2.call(Observable.java:162)
	at rx.Observable$2.call(Observable.java:169)
	at rx.Observable$2.call(Observable.java:162)
	at rx.Observable$2.call(Observable.java:169)
	at rx.Observable$2.call(Observable.java:162)
	at rx.Observable$2.call(Observable.java:169)
	at rx.Observable$2.call(Observable.java:162)
	at rx.Observable.subscribe(Observable.java:8068)
	at rx.internal.operators.BlockingOperatorToIterator.toIterator(BlockingOperatorToIterator.java:50)
	at rx.observables.BlockingObservable.getIterator(BlockingObservable.java:151)
	at rx.observables.BlockingObservable$2.iterator(BlockingObservable.java:435)
	at rx.observables.BlockingObservable.single(BlockingObservable.java:348)
	at com.microsoft.azure.management.resources.fluentcore.model.implementation.CreatableUpdatableImpl.create(CreatableUpdatableImpl.java:251)
	at com.microsoft.azure.management.resources.fluentcore.model.implementation.CreatableUpdatableImpl.create(CreatableUpdatableImpl.java:33)

**Comment by vhvb1989** [comment]
Hello @ArundathiGV 

I am sorry about you didn't get a sooner answer on this
Do you still need help on this? Let me know and I would be happy to help.

Note: As part of repository cleaning effort, this issue will be closed by **Nov 11** if no response is received from submitter and/or not further action is required.

**Comment by mhjort** [comment]
I get this same error with version `1.28.0`
