### ISSUE TITLE
[BUG] azure-identity uses vulnerable version of oauth2-oidc-sdk

### ISSUE THREAD

**Issue by willemneethling** [Azure/azure-sdk-for-java#26383]
**Describe the bug**
We use azure-identity from a Java-based Spring Boot microservice running in Azure Kubernetes Service to access Azure Storage. NexusIQ is detecting a vulnerability in oauth2-oidc-sdk 7.1.1, which is a transitive dependency of azure-identity (sonatype-2021-0429, https://cwe.mitre.org/data/definitions/611.html).  

Upgrading to the recommended non-vulnerable version of oauth2-oidc-sdk (8.36.2) does not help, as this leads to a class not found exception regarding com/nimbusds/oauth2/sdk/http/CommonContentTypes. This type was deprecated in version 7.1.1 and removed.

The latest version of azure-identity (1.4.2) uses the same version of oauth2-oidc-sdk (7.1.1) - this does not resolve it.

***Exception or Stack Trace***
```
Caused by: java.lang.NoClassDefFoundError: com/nimbusds/oauth2/sdk/http/CommonContentTypes
	at com.microsoft.aad.msal4j.TokenRequest.toOauthHttpRequest(TokenRequest.java:164)
	at com.microsoft.aad.msal4j.TokenRequest.executeOauthRequestAndProcessResponse(TokenRequest.java:55)
	at com.microsoft.aad.msal4j.ClientApplicationBase.acquireTokenCommon(ClientApplicationBase.java:163)
	at com.microsoft.aad.msal4j.AcquireTokenByAuthorizationGrantSupplier.execute(AcquireTokenByAuthorizationGrantSupplier.java:52)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:57)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:17)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
```

**To Reproduce**
Upgrade the version of com.nimbusds:oauth2-oidc-sdk to the non-vulnerable version 8.36.2
```
<dependencyManagement>
<dependencies>
	<dependency>
		<groupId>com.nimbusds</groupId>
		<artifactId>oauth2-oidc-sdk</artifactId>
		<version>8.36.2</version>
	</dependency>
</dependencies>
</dependencyManagement>
```

**Expected behavior**
It is expected that azure-identity does not use the vulnerable version of com.nimbusds:oauth2-oidc-sdk

**Setup (please complete the following information):**
 - Library/Libraries: com.azure:azure-identity:jar:1.0.7
 - Java version: 11
 - Frameworks: Spring Boot 2.3.5.RELEASE

snippet of dependency tree:
```
[INFO] +- com.azure:azure-identity:jar:1.4.2:compile
[INFO] |  +- com.azure:azure-core-http-netty:jar:1.11.2:compile
[INFO] |  |  +- io.netty:netty-handler-proxy:jar:4.1.53.Final:compile
[INFO] |  |  |  \- io.netty:netty-codec-socks:jar:4.1.53.Final:compile
[INFO] |  |  +- io.netty:netty-codec-http:jar:4.1.53.Final:compile
[INFO] |  |  +- io.netty:netty-codec-http2:jar:4.1.53.Final:compile
[INFO] |  |  +- io.netty:netty-transport-native-unix-common:jar:4.1.53.Final:compile
[INFO] |  |  +- io.netty:netty-transport-native-epoll:jar:linux-x86_64:4.1.53.Final:compile
[INFO] |  |  +- io.netty:netty-transport-native-kqueue:jar:osx-x86_64:4.1.53.Final:compile
[INFO] |  |  \- io.projectreactor.netty:reactor-netty-http:jar:1.0.11:compile
[INFO] |  |     +- io.netty:netty-resolver-dns:jar:4.1.53.Final:compile
[INFO] |  |     |  \- io.netty:netty-codec-dns:jar:4.1.53.Final:compile
[INFO] |  |     +- io.netty:netty-resolver-dns-native-macos:jar:osx-x86_64:4.1.53.Final:compile
[INFO] |  |     \- io.projectreactor.netty:reactor-netty-core:jar:1.0.11:compile
[INFO] |  +- com.microsoft.azure:msal4j:jar:1.11.0:compile
[INFO] |  |  \- com.nimbusds:oauth2-oidc-sdk:jar:7.1.1:compile
[INFO] |  |     +- com.nimbusds:content-type:jar:2.0:compile
[INFO] |  |     +- com.nimbusds:lang-tag:jar:1.4.4:compile
[INFO] |  |     +- com.nimbusds:nimbus-jose-jwt:jar:8.19:compile
[INFO] |  |     \- com.sun.mail:javax.mail:jar:1.6.1:compile
[INFO] |  |        \- javax.activation:activation:jar:1.1:compile
[INFO] |  +- com.microsoft.azure:msal4j-persistence-extension:jar:1.1.0:compile
[INFO] |  |  \- net.java.dev.jna:jna:jar:5.5.0:compile
[INFO] |  +- net.java.dev.jna:jna-platform:jar:5.6.0:compile
[INFO] |  \- net.minidev:json-smart:jar:2.4.2:compile
[INFO] |     \- net.minidev:accessors-smart:jar:2.4.2:compile
```

**Comment by joshfree** [comment]
@g2vinay please take a look for the February release.

**Comment by anumalasri** [comment]
Do we have any update on these transitive dependencies?  We are finding some of 'nimbus' versions showing vulnerabilities

```
com.nimbusds:nimbus-jose-jwt:9.9.3
\--- com.nimbusds:oauth2-oidc-sdk:9.7
     \--- com.microsoft.azure:msal4j:1.11.0 
          +--- com.azure:azure-identity:1.4.6
          |    \--- com.azure.spring:spring-cloud-azure-core:4.0.0
          |         \--- com.azure.spring:spring-cloud-azure-service:4.0.0
          |              \--- com.azure.spring:spring-cloud-azure-autoconfigure:4.0.0
          |                   \--- com.azure.spring:spring-cloud-azure-starter:4.0.0
          |                        \--- com.azure.spring:spring-cloud-azure-starter-keyvault-secrets:4.0.0
```

**Comment by g2vinay** [comment]
@willemneethling, azure-identity latest version 1.5.0 uses oauth2-oidc-sdk:v9.22.1 
you can upgrade to that.

**Comment by anumalasri** [comment]
Also please take care of  -` com.fasterxml.jackson.core:jackson-databind:12.2.1`  vulnerability.

https://mvnrepository.com/artifact/com.azure/azure-identity/1.5.0
https://mvnrepository.com/artifact/com.microsoft.azure/msal4j/1.11.3

@g2vinay @willemneethling

**Comment by anumalasri** [comment]
@g2vinay  ..Hope you are following MSAL4J and v1.12.0 should be used in Azure SDK to solve the issue completely.

https://github.com/AzureAD/microsoft-authentication-library-for-java/issues/501

Do you agree ?
