### ISSUE TITLE
[BUG] Blob clients with Netty do not work behind proxy server without accessible DNS server

### ISSUE THREAD

**Issue by maben-mw** [Azure/azure-sdk-for-java#26559]
**Describe the bug**
This is pretty much the exact same as in #17930 again, only at the moment it appears things are broken for any proxy (authenticated or not). It looks like the code related to this was refactored entirely and that somehow broke the fix for the previously reported issue.

On machines which cannot perform DNS lookups of external internet hosts and which require a proxy for access to the internet, the Blob clients just fail to work, even with proxy properly configured using `NettyAsyncHttpClientBuilder`. As before, it appears the SDK first tries to perform a DNS lookup of the host before even handing off the request to the proxy. Which will fail. Typically if you need a proxy to access the internet, you also will not be able to perform DNS lookups of internet hosts.

***Exception or Stack Trace***
```
Exception in thread "main" reactor.core.Exceptions$ReactiveException: java.net.UnknownHostException: <redacted>.blob.core.windows.net
        at reactor.core.Exceptions.propagate(Exceptions.java:392)
        at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:97)
        at reactor.core.publisher.Flux.blockLast(Flux.java:2644)
        at com.azure.core.util.paging.ContinuablePagedByIteratorBase.requestPage(ContinuablePagedByIteratorBase.java:94)
        at com.azure.core.util.paging.ContinuablePagedByItemIterable$ContinuablePagedByItemIterator.<init>(ContinuablePagedByItemIterable.java:50)
        at com.azure.core.util.paging.ContinuablePagedByItemIterable.iterator(ContinuablePagedByItemIterable.java:37)
        at com.azure.core.util.paging.ContinuablePagedIterable.iterator(ContinuablePagedIterable.java:106)
        at java.lang.Iterable.forEach(Iterable.java:74)
        at com.example.App.main(App.java:35)
        Suppressed: java.lang.Exception: #block terminated with an error
                at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
                ... 7 more
Caused by: java.net.UnknownHostException: <redacted>.blob.core.windows.net
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
        at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929)
        at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324)
        at java.net.InetAddress.getAllByName0(InetAddress.java:1277)
        at java.net.InetAddress.getAllByName(InetAddress.java:1193)
        at java.net.InetAddress.getAllByName(InetAddress.java:1127)
        at io.netty.util.internal.SocketUtils$9.run(SocketUtils.java:169)
        at io.netty.util.internal.SocketUtils$9.run(SocketUtils.java:166)
        at java.security.AccessController.doPrivileged(Native Method)
        at io.netty.util.internal.SocketUtils.allAddressesByName(SocketUtils.java:166)
        at io.netty.resolver.DefaultNameResolver.doResolveAll(DefaultNameResolver.java:50)
        at io.netty.resolver.SimpleNameResolver.resolveAll(SimpleNameResolver.java:79)
        at io.netty.resolver.SimpleNameResolver.resolveAll(SimpleNameResolver.java:71)
        at io.netty.resolver.InetSocketAddressResolver.doResolveAll(InetSocketAddressResolver.java:73)
        at io.netty.resolver.InetSocketAddressResolver.doResolveAll(InetSocketAddressResolver.java:31)
        at io.netty.resolver.AbstractAddressResolver.resolveAll(AbstractAddressResolver.java:158)
        at reactor.netty.transport.TransportConnector.doResolveAndConnect(TransportConnector.java:283)
        at reactor.netty.transport.TransportConnector.lambda$connect$6(TransportConnector.java:110)
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:125)
        at reactor.netty.transport.TransportConnector$MonoChannelPromise._subscribe(TransportConnector.java:579)
        at reactor.netty.transport.TransportConnector$MonoChannelPromise.lambda$subscribe$0(TransportConnector.java:499)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
```

**To Reproduce**

* Have a machine with no direct internet access (e.g. a Hyper-V virtual machine with only an "Internal Network" and then a proxy on the host.)
* Run the Java Code below

***Code Snippet***
```java
    public static void main(String[] args) {

        String TEST_URL = "BlobEndpoint=https://...";

        // proxy server accepts both unauthenticated and authenticated requests
        String PROXY_HOST = "<proxyhost>";
        final String PROXY_PORT = "8080";
        final String PROXY_USER = "testuser";
        final String PROXY_PASS = "pass";
        final int PROXY_PORT_INT = Integer.parseInt(PROXY_PORT);

        // non-authenticated proxy only works with internet connection for DNS querys
        try {
            ProxyOptions nonAuthProxyOptions = new ProxyOptions(ProxyOptions.Type.HTTP,
                    new InetSocketAddress(PROXY_HOST, PROXY_PORT_INT));
            HttpClient nonAuthClient = new NettyAsyncHttpClientBuilder().proxy(nonAuthProxyOptions).build();
            BlobServiceClient nonAuthBlobClient = new BlobServiceClientBuilder().connectionString(TEST_URL)
                    .httpClient(nonAuthClient)
                    .buildClient();
            nonAuthBlobClient.listBlobContainers().forEach(blob -> System.out.println(blob.getName()));
            System.out.println("non auth succeeded");
        } catch (Exception e) {
            System.out.println("non auth failed");
        }

        // authenticated proxy only works with internet connection for DNS querys
        try {
            ProxyOptions authProxyOptions = new ProxyOptions(ProxyOptions.Type.HTTP,
                    new InetSocketAddress(PROXY_HOST, PROXY_PORT_INT));
            authProxyOptions.setCredentials(PROXY_USER, PROXY_PASS);
            HttpClient authClient = new NettyAsyncHttpClientBuilder().proxy(authProxyOptions).build();
            BlobServiceClient authBlobClient = new BlobServiceClientBuilder().connectionString(TEST_URL)
                    .httpClient(authClient).buildClient();
            authBlobClient.listBlobContainers().forEach(blob -> System.out.println(blob.getName()));
            System.out.println("with auth succeeded");
        } catch (Exception e) {
            System.out.println("with auth failed");
        }
    }
```

**Expected behavior**
This should just work, the SDK should not even consider trying the DNS lookup and just immediately let the proxy handle the whole request.

**Setup (please complete the following information):**
 - OS: Windows
 - IDE: VS Code
 - Library/Libraries: azure-storage-blob through azure-sdk-bom:1.0.6
 - Java version: 8

**Additional context**
Things appear to work fine with okHTTP and this appears to be Netty specific.

Looks like you can work around this by first explicitly creating a Netty HTTP Client with NoopAddressResolverGroup but this is not mentioned as being required in any documentation and it does not feel like this should be necessary.
```java
        reactor.netty.http.client.HttpClient baseClient = reactor.netty.http.client.HttpClient.create()
                .resolver(io.netty.resolver.NoopAddressResolverGroup.INSTANCE);
        HttpClient nonAuthClient = new NettyAsyncHttpClientBuilder(baseClient).proxy(nonAuthProxyOptions).build();
```

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by joshfree** [comment]
Thanks for filling this GitHub issue, @maben-mw.  @alzimmermsft could you please take a look?

**Comment by alzimmermsft** [comment]
Thank you for filing this, I'll have an update soon

**Comment by alzimmermsft** [comment]
@maben-mw a fix has been merged that will be included in the next release of azure-core-http-netty. In the meantime, if possible, could you use the source version to verify it has resolved the issue you were seeing?

@jbkervyn I believe this issue may be the same problem you referenced in #22661, can you confirm.

**Comment by jbkervyn** [comment]
@alzimmermsft yes, I confirm ! Thanks Alan !

**Comment by maben-mw** [comment]
I wasn't really able to actually build the SDK from source (with Java 8) but I did run a quick test where I explicitly pulled-in:
```
    <dependency>
        <groupId>com.azure</groupId>
        <artifactId>azure-core-http-netty</artifactId>
        <version>1.12.0-alpha.20220125.1</version>
    </dependency> 
```
with this, the issue does indeed appear to be resolved.

Great work, thanks!

**Comment by alzimmermsft** [comment]
Thanks for the verification @jbkervyn and @maben-mw, I'll update you once the fixed version of `azure-core-http-netty` is released and you can override the dependency version as a work around until a newer version of the Storage libraries are released with the fixed version as the dependency version.
