### ISSUE TITLE
Question the same condition with issues13235

### ISSUE THREAD

**Issue by YeJiaL** [Azure/azure-sdk-for-java#26583]
the same condition with  https://github.com/Azure/azure-sdk-for-java/issues/13235,how to fix it?
because start application in two nodes?but i can't get all the subscribers  by my application

log
`New receiver 'nil' with higher epoch of '0' is created hence current receiver 'nil' with epoch '0' is getting disconnected. If you are recreating the receiver, make sure a higher epoch is used. TrackingId:a977ac870000344200042d9561e7b963_G2S2_B4S3, SystemTracker:iothub-ns-uplusiothu-xxxxx-xxxxx:eventhub:uplusiothub2~16383|$default, Timestamp:2022-01-19T07:10:38`

pom.xml
```
       
       <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-messaging-eventhubs-checkpointstore-blob</artifactId>
            <version>1.10.1</version> <!-- {x-version-update;com.azure:azure-messaging-eventhubs-checkpointstore-blob;dependency} -->
        </dependency>
 <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-messaging-eventhubs-checkpointstore-blob</artifactId>
            <version>1.10.1</version> <!-- {x-version-update;com.azure:azure-messaging-eventhubs-checkpointstore-blob;dependency} -->
        </dependency>
```

**Comment by conniey** [comment]
Do you have a code snippet of what your code is doing? It's normal to see that during load balancing for the Event Processor Client.

**Comment by YeJiaL** [comment]
> Do you have a code snippet of what your code is doing? It's normal to see that during load balancing for the Event Processor Client.
@conniey  this is the code.
main code 

` public void logReceive() {
        logger.log(LogCst.IOT_DEV_INFO, "Starting  receiveEdgeMessage the processor,iotConfigUtil={}", iotConfigUtil.toString());


        BlobContainerAsyncClient blobContainerAsyncClient = new BlobContainerClientBuilder()
                .connectionString(iotConfigUtil.getStoreConfigConnectStr())
                .containerName(iotConfigUtil.getStoreContainerName())
                .sasToken(iotConfigUtil.getStoreSasToken())
                .httpLogOptions(new HttpLogOptions().setLogLevel(HttpLogDetailLevel.BODY_AND_HEADERS))
                .buildAsyncClient();

        EventProcessorClientBuilder eventProcessorClientBuilder = new EventProcessorClientBuilder()
                //                .connectionString(iotConfigUtil.getEventHubConnectStr()).retry(amqpRetryOptions)
                .connectionString(iotConfigUtil.getEventHubConnectStr()).consumerGroup(
                        EventHubClientBuilder.DEFAULT_CONSUMER_GROUP_NAME).processEvent(PARTITION_PROCESSOR).processError(
                        ERROR_HANDLER)
                //                .loadBalancingUpdateInterval(Duration.ofSeconds(5))
                //                .partitionOwnershipExpirationInterval(Duration.ofSeconds(60)).loadBalancingStrategy(
                //                        LoadBalancingStrategy.BALANCED)
                .checkpointStore(new BlobCheckpointStore(blobContainerAsyncClient));

        EventProcessorClient eventProcessorClient = eventProcessorClientBuilder.buildEventProcessorClient();
        eventProcessorClient.start();
        logger.log(LogCst.IOT_DEV_INFO, "logReceive after receiveFromAllPartitions");

    }


    public  Consumer<EventContext> PARTITION_PROCESSOR = eventContext -> {
        EventData data =  eventContext.getEventData();
        String partitionId = eventContext.getPartitionContext().getPartitionId();
        System.out.printf("Processing event from partition %s with sequence number %d %n",
                          partitionId, data.getSequenceNumber());

        Long offset = data.getOffset();
        Long sequenceNumber = data.getSequenceNumber();


        String bodyAsString = data.getBodyAsString();

        logger.log(LogCst.IOT_DEV_INFO,
                   "logReceive partitionId={},bodyAsString={},offset={},sequenceNumber={}",
                   partitionId, bodyAsString, offset,
                   sequenceNumber);
        handleLogService.handleIotLogStr(bodyAsString);
        if (sequenceNumber % 10 == 0) {
            eventContext.updateCheckpoint();
        }
    };

    public static final Consumer<ErrorContext> ERROR_HANDLER = errorContext -> {
        logger.log(LogCst.IOT_DEV_ERROR, "=============partitionId={},getConsumerGroup={},getFullyQualifiedNamespace={}",
                   errorContext.getPartitionContext().getPartitionId(), errorContext.getPartitionContext().getConsumerGroup(),
                   errorContext.getPartitionContext().getFullyQualifiedNamespace());
        logger.log(LogCst.IOT_DEV_ERROR, "logReceive Error receiving events,e={}", errorContext.getThrowable());
    };
`
ERROR_HANDLER  logg

> 2022-01-20 11:24:09.491  INFO [reactor-executor-43] c.a.c.a.i.handler.ReceiveLinkHandler : connectionId[MF_cd5b22_1642649046924] linkName[3_b9fa91_1642649046925] state[ACTIVE] Local link state is not closed.
2022-01-20 11:24:09.491  WARN [reactor-executor-43] c.a.c.a.implementation.ReactorReceiver : connectionId[MF_cd5b22_1642649046924] entityPath[uplusiothub-prod/ConsumerGroups/$default/Partitions/3] linkName[3_b9fa91_1642649046925] Freeing resources due to error.
Receiver 'nil' with a higher epoch '1' already exists. Receiver 'nil' with epoch 0 cannot be created. Make sure you are creating receiver with increasing epoch value to ensure connectivity, or ensure all old epoch receivers are closed or disconnected. TrackingId:97687fcb-cef5-456f-a1bb-aa65bb2c402c_B5S2, SystemTracker:iothub-ns-uplusiothu-16952866-4acfaff5bd:eventhub:uplusiothub-prod~32766, Timestamp:2022-01-20T03:24:08 Reference:199c513c-b80e-46d3-97e7-f9833ca8c638, TrackingId:5d5e38dc-4c16-430e-b2e6-c367b246813b_B5S2, SystemTracker:iothub-ns-uplusiothu-16952866-4acfaff5bd:eventhub:uplusiothub-prod~32766|$default, Timestamp:2022-01-20T03:24:09 TrackingId:54526b02806f4464a0ae2d8e925d5729_G1S1, SystemTracker:gateway5, Timestamp:2022-01-20T03:24:09, errorContext[NAMESPACE: iothub-ns-uplusiothu-16952866-4acfaff5bd.servicebus.windows.net. ERROR CONTEXT: N/A, PATH: uplusiothub-prod/ConsumerGroups/$default/Partitions/3, REFERENCE_ID: 3_b9fa91_1642649046925, LINK_CREDIT: 0]
2022-01-20 11:24:09.491  INFO [reactor-executor-43] c.a.m.e.i.AmqpReceiveLinkProcessor : linkName[3_b9fa91_1642649046925] was already closed. Could not add credits.
2022-01-20 11:24:09.491  INFO [reactor-executor-43] c.a.m.e.i.AmqpReceiveLinkProcessor : linkName[3_b9fa91_1642649046925] Error on receive link.
2022-01-20 11:24:09.492  INFO [reactor-executor-43] c.a.m.e.EventHubConsumerAsyncClient : linkName[3_b9fa91_1642649046925], partitionId[3], signal[onError]: Receiving completed.
2022-01-20 11:24:09.492  INFO [reactor-executor-43] c.a.m.e.EventHubPartitionAsyncConsumer : Closed consumer for partition 3
2022-01-20 11:24:09.492  INFO [reactor-executor-43] c.a.c.a.i.handler.ReceiveLinkHandler : connectionId[MF_cd5b22_1642649046924] linkName[3_b9fa91_1642649046925] entityPath[uplusiothub-prod/ConsumerGroups/$default/Partitions/3] Receiver link was never active. Closing endpoint states.
2022-01-20 11:24:09.492  INFO [reactor-executor-43] c.a.c.a.i.handler.ReceiveLinkHandler : onLinkFinal connectionId[MF_cd5b22_1642649046924], linkName[3_b9fa91_1642649046925]
2022-01-20 11:24:09.493  WARN [partition-pump-3-87] c.a.m.eventhubs.PartitionPumpManager : Error receiving events from partition 3
Receiver 'nil' with a higher epoch '1' already exists. Receiver 'nil' with epoch 0 cannot be created. Make sure you are creating receiver with increasing epoch value to ensure connectivity, or ensure all old epoch receivers are closed or disconnected. TrackingId:97687fcb-cef5-456f-a1bb-aa65bb2c402c_B5S2, SystemTracker:iothub-ns-uplusiothu-16952866-4acfaff5bd:eventhub:uplusiothub-prod~32766, Timestamp:2022-01-20T03:24:08 Reference:199c513c-b80e-46d3-97e7-f9833ca8c638, TrackingId:5d5e38dc-4c16-430e-b2e6-c367b246813b_B5S2, SystemTracker:iothub-ns-uplusiothu-16952866-4acfaff5bd:eventhub:uplusiothub-prod~32766|$default, Timestamp:2022-01-20T03:24:09 TrackingId:54526b02806f4464a0ae2d8e925d5729_G1S1, SystemTracker:gateway5, Timestamp:2022-01-20T03:24:09, errorContext[NAMESPACE: iothub-ns-uplusiothu-16952866-4acfaff5bd.servicebus.windows.net. ERROR CONTEXT: N/A, PATH: uplusiothub-prod/ConsumerGroups/$default/Partitions/3, REFERENCE_ID: 3_b9fa91_1642649046925, LINK_CREDIT: 0]
2022-01-20 11:24:09.493 ERROR [partition-pump-3-87] c.u.u.s.l.i.c.IotReceiveMessageService2 : =============partitionId=3,getConsumerGroup=$default,getFullyQualifiedNamespace=iothub-ns-uplusiothu-16952866-4acfaff5bd.servicebus.windows.net
2022-01-20 11:24:32.042  INFO [pool-11-thread-1] c.a.m.e.PartitionBasedLoadBalancer : Starting load balancer for 9baaa19b-cfee-4c17-b4b5-3e1a015b3e4a
2022-01-20 11:24:32.043  INFO [parallel-2] c.a.c.a.i.RequestResponseChannel : connectionId[MF_18e766_1642648943467] linkName[cbs] Timed out waiting for RequestResponseChannel to complete closing. Manually closing.
2022-01-20 11:24:32.043 ERROR [partition-pump-3-87] c.u.u.s.l.i.c.IotReceiveMessageService2 : logReceive Error receiving events,e={}

com.azure.core.amqp.exception.AmqpException: Receiver 'nil' with a higher epoch '1' already exists. Receiver 'nil' with epoch 0 cannot be created. Make sure you are creating receiver with increasing epoch value to ensure connectivity, or ensure all old epoch receivers are closed or disconnected. TrackingId:97687fcb-cef5-456f-a1bb-aa65bb2c402c_B5S2, SystemTracker:iothub-ns-uplusiothu-16952866-4acfaff5bd:eventhub:uplusiothub-prod~32766, Timestamp:2022-01-20T03:24:08 Reference:199c513c-b80e-46d3-97e7-f9833ca8c638, TrackingId:5d5e38dc-4c16-430e-b2e6-c367b246813b_B5S2, SystemTracker:iothub-ns-uplusiothu-16952866-4acfaff5bd:eventhub:uplusiothub-prod~32766|$default, Timestamp:2022-01-20T03:24:09 TrackingId:54526b02806f4464a0ae2d8e925d5729_G1S1, SystemTracker:gateway5, Timestamp:2022-01-20T03:24:09, errorContext[NAMESPACE: iothub-ns-uplusiothu-16952866-4acfaff5bd.servicebus.windows.net. ERROR CONTEXT: N/A, PATH: uplusiothub-prod/ConsumerGroups/$default/Partitions/3, REFERENCE_ID: 3_b9fa91_1642649046925, LINK_CREDIT: 0]
	at com.azure.core.amqp.implementation.ExceptionUtil.toException(ExceptionUtil.java:85)
	at com.azure.core.amqp.implementation.handler.LinkHandler.handleRemoteLinkClosed(LinkHandler.java:110)
	at com.azure.core.amqp.implementation.handler.LinkHandler.onLinkRemoteClose(LinkHandler.java:61)
	at com.azure.core.amqp.implementation.handler.ReceiveLinkHandler.onLinkRemoteClose(ReceiveLinkHandler.java:193)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:176)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291)
	at com.azure.core.amqp.implementation.ReactorExecutor.run(ReactorExecutor.java:92)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

2022-01-20 11:24:32.043  INFO [partition-pump-3-87] c.a.m.e.i.PartitionProcessor : Closing partition processor for partition 3 with close reason LOST_PARTITION_OWNERSHIP
2022-01-20 11:24:32.044  INFO [partition-pump-3-87] c.a.m.eventhubs.PartitionPumpManager : Closing consumer for partition id 3
2022-01-20 11:24:32.044  INFO [partition-pump-3-87] c.a.m.e.i.EventHubConnectionProcessor : Upstream connection publisher was completed. Terminating processor.
2022-01-20 11:24:32.044  INFO [partition-pump-3-87] c.a.m.e.i.EventHubConnectionProcessor : namespace[iothub-ns-uplusiothu-16952866-4acfaff5bd.servicebus.windows.net] entityPath[uplusiothub-prod]: AMQP channel processor completed. Notifying 0 subscribers.
2022-01-20 11:24:32.044  INFO [partition-pump-3-87] c.a.c.a.i.ReactorConnection : connectionId[MF_cd5b22_1642649046924] signal[Disposed by client., isTransient[false], initiatedByClient[true]]: Disposing of ReactorConnection.
2022-01-20 11:24:32.044  INFO [partition-pump-3-87] c.a.m.e.i.EventHubConnectionProcessor : namespace[iothub-ns-uplusiothu-16952866-4acfaff5bd.servicebus.windows.net] entityPath[uplusiothub-prod]: Channel is disposed.
2022-01-20 11:24:32.045  INFO [parallel-1] c.a.s.b.i.C.listBlobFlatSegment : --> GET https://uplusiotsa.blob.core.windows.net/solar-prod-container?prefix=REDACTED&include=REDACTED&restype=REDACTED&comp=REDACTED&sp=REDACTED&st=REDACTED&se=REDACTED&sv=REDACTED&sr=REDACTED&sig=REDACTED(empty body)--> END GET
2022-01-20 11:24:32.045  INFO [partition-pump-3-87] c.a.m.eventhubs.PartitionPumpManager : Removing partition id 3 from list of processing partitions
2022-01-20 11:24:32.278  INFO [reactor-executor-43] c.a.c.a.i.handler.SendLinkHandler : onLinkRemoteClose connectionId[MF_cd5b22_1642649046924] linkName[cbs:sender], errorCondition[null] errorDescription[null]
2022-01-20 11:24:32.278  INFO [reactor-executor-43] c.a.c.a.i.handler.ReceiveLinkHandler : onLinkRemoteClose connectionId[MF_cd5b22_1642649046924] linkName[cbs:receiver], errorCondition[null] errorDescription[null]
2022-01-20 11:24:32.278  INFO [reactor-executor-43] c.a.c.a.i.RequestResponseChannel:$cbs : namespace[MF_cd5b22_1642649046924] entityPath[$cbs]: Channel is closed. Requesting upstream. 
2022-01-20 11:24:32.278  INFO [reactor-executor-43] c.a.c.a.i.RequestResponseChannel:$cbs : namespace[MF_cd5b22_1642649046924] entityPath[$cbs]: Connection not requested, yet. Requesting one.
2022-01-20 11:24:32.278  INFO [reactor-executor-43] c.a.c.a.i.ReactorConnection : connectionId[MF_cd5b22_1642649046924] entityPath[$cbs] linkName[cbs] Emitting new response channel.
2022-01-20 11:24:32.278  INFO [reactor-executor-43] c.a.c.a.i.RequestResponseChannel:$cbs : namespace[MF_cd5b22_1642649046924] entityPath[$cbs]: Setting next AMQP channel.
2022-01-20 11:24:32.279  INFO [reactor-executor-43] c.a.c.a.i.RequestResponseChannel:$cbs : namespace[MF_cd5b22_1642649046924] entityPath[$cbs]: Next AMQP channel received, updating 1 current subscribers

**Comment by YeJiaL** [comment]
i run the method logReceive in a job, this is the error reason?

>     @Override
>     public void run(String... args) throws Exception {
>         LogReceiveJob logReceiveJob = new LogReceiveJob();
>         int nThreads = 1;
>         ExecutorService executor = new ThreadPoolExecutor(nThreads, nThreads, 0L, TimeUnit.MILLISECONDS,
>                                                           new LinkedBlockingQueue<Runnable>());
>         executor.execute(logReceiveJob);
>         //        logReceive();
>     }
> 
> 
>     private class LogReceiveJob implements Runnable {
>         @Override
>         public void run() {
>             logReceive();
>         }
>     }

**Comment by conniey** [comment]
Apologies for the delay... The error you are seeing is common during load balancing, see: https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/eventhubs/azure-messaging-eventhubs/TROUBLESHOOTING.md#current-receiver-receiver_name-with-epoch-0-is-getting-disconnected

Can you clarify what you mean by: "i can't get all the subscribers by my application"? Are you not receiving messages from _any_ partitions?
