### ISSUE TITLE
[BUG] Cannot send a message when request response channel is disposed

### ISSUE THREAD

**Issue by sohanlal311** [Azure/azure-sdk-for-java#26761]
**Describe the bug**

Cannot send a message when request response channel is disposed.

**Exception or Stack Trace**
```
2022-01-19 10:58:27,755 ERROR [pool-9-thread-1(25480)] {serviceName=PRODUCT_GENERATION, traceId=bcde9802-2cf5-44ca-b4b1-dc865a101f93} com.msci.esb.services.ESBEventHandler - Failed applying onRunning handler. Marking dead-letter. com.azure.messaging.servicebus.ServiceBusException: Cannot send a message when request response channel is disposed.
at com.azure.messaging.servicebus.ServiceBusSenderAsyncClient.mapError(ServiceBusSenderAsyncClient.java:818)
at reactor.core.publisher.Mono.lambda$onErrorMap$31(Mono.java:3437)
at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94)
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.lambda$onError$2(TracingSubscriber.java:63)
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.withActiveSpan(TracingSubscriber.java:79)
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.onError(TracingSubscriber.java:63)
at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:172)
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.lambda$onError$2(TracingSubscriber.java:63)
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.withActiveSpan(TracingSubscriber.java:79)
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.onError(TracingSubscriber.java:63)
at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onError(FluxHide.java:141)
at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onError(MonoPeekTerminal.java:258)
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.lambda$onError$2(TracingSubscriber.java:63)
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.withActiveSpan(TracingSubscriber.java:79)
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.onError(TracingSubscriber.java:63)
at reactor.core.publisher.SerializedSubscriber.onError(SerializedSubscriber.java:124)
at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.whenError(FluxRetryWhen.java:224)
at reactor.core.publisher.FluxRetryWhen$RetryWhenOtherSubscriber.onError(FluxRetryWhen.java:273)
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.lambda$onError$2(TracingSubscriber.java:63)
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.withActiveSpan(TracingSubscriber.java:79)
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.onError(TracingSubscriber.java:63)
at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.innerError(FluxConcatMap.java:308)
at reactor.core.publisher.FluxConcatMap$ConcatMapInner.onError(FluxConcatMap.java:872)
at reactor.core.publisher.Operators.error(Operators.java:197)
at reactor.core.publisher.MonoError.subscribe(MonoError.java:52)
at reactor.core.publisher.Mono.subscribe(Mono.java:4099)
at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:448)
at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onNext(FluxConcatMap.java:250)
at reactor.core.publisher.EmitterProcessor.drain(EmitterProcessor.java:491)
at reactor.core.publisher.EmitterProcessor.tryEmitNext(EmitterProcessor.java:299)
at reactor.core.publisher.SinkManySerialized.tryEmitNext(SinkManySerialized.java:97)
at reactor.core.publisher.InternalManySink.emitNext(InternalManySink.java:27)
at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.onError(FluxRetryWhen.java:189)
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.lambda$onError$2(TracingSubscriber.java:63)
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.withActiveSpan(TracingSubscriber.java:79)
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.onError(TracingSubscriber.java:63)
at reactor.core.publisher.SerializedSubscriber.onError(SerializedSubscriber.java:124)
at reactor.core.publisher.SerializedSubscriber.onError(SerializedSubscriber.java:124)
at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.onError(FluxTimeout.java:218)
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.lambda$onError$2(TracingSubscriber.java:63)
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.withActiveSpan(TracingSubscriber.java:79)
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.onError(TracingSubscriber.java:63)
at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onError(FluxPeekFuseable.java:234)
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.lambda$onError$2(TracingSubscriber.java:63)
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.withActiveSpan(TracingSubscriber.java:79)
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.onError(TracingSubscriber.java:63)
at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onError(FluxHide.java:141)
at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondError(MonoFlatMap.java:192)
at reactor.core.publisher.MonoFlatMap$FlatMapInner.onError(MonoFlatMap.java:259)
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.lambda$onError$2(TracingSubscriber.java:63)
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.withActiveSpan(TracingSubscriber.java:79)
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.onError(TracingSubscriber.java:63)
at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondError(MonoFlatMap.java:192)
at reactor.core.publisher.MonoFlatMap$FlatMapInner.onError(MonoFlatMap.java:259)
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.lambda$onError$2(TracingSubscriber.java:63)
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.withActiveSpan(TracingSubscriber.java:79)
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.onError(TracingSubscriber.java:63)
at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onError(FluxMapFuseable.java:140)
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.lambda$onError$2(TracingSubscriber.java:63)
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.withActiveSpan(TracingSubscriber.java:79)
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.onError(TracingSubscriber.java:63)
at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onError(FluxHide.java:141)
at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onError(FluxMapFuseable.java:140)
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.lambda$onError$2(TracingSubscriber.java:63)
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.withActiveSpan(TracingSubscriber.java:79)
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.onError(TracingSubscriber.java:63)
at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onError(FluxHide.java:141)
at reactor.core.publisher.Operators$MonoSubscriber.onError(Operators.java:1862)
at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreInner.onError(MonoIgnoreThen.java:243)
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.lambda$onError$2(TracingSubscriber.java:63)
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.withActiveSpan(TracingSubscriber.java:79)
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.onError(TracingSubscriber.java:63)
at reactor.core.publisher.MonoWhen$WhenCoordinator.signalError(MonoWhen.java:172)
at reactor.core.publisher.MonoWhen$WhenInner.onError(MonoWhen.java:288)
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.lambda$onError$2(TracingSubscriber.java:63)
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.withActiveSpan(TracingSubscriber.java:79)
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.onError(TracingSubscriber.java:63)
at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onError(FluxMapFuseable.java:140)
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.lambda$onError$2(TracingSubscriber.java:63)
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.withActiveSpan(TracingSubscriber.java:79)
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.onError(TracingSubscriber.java:63)
at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onError(FluxHide.java:141)
at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondError(MonoFlatMap.java:192)
at reactor.core.publisher.MonoFlatMap$FlatMapInner.onError(MonoFlatMap.java:259)
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.lambda$onError$2(TracingSubscriber.java:63)
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.withActiveSpan(TracingSubscriber.java:79)
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.onError(TracingSubscriber.java:63)
at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondError(MonoFlatMap.java:192)
at reactor.core.publisher.MonoFlatMap$FlatMapInner.onError(MonoFlatMap.java:259)
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.lambda$onError$2(TracingSubscriber.java:63)
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.withActiveSpan(TracingSubscriber.java:79)
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.onError(TracingSubscriber.java:63)
at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondError(MonoFlatMap.java:192)
at reactor.core.publisher.MonoFlatMap$FlatMapInner.onError(MonoFlatMap.java:259)
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.lambda$onError$2(TracingSubscriber.java:63)
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.withActiveSpan(TracingSubscriber.java:79)
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.onError(TracingSubscriber.java:63)
at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onError(Operators.java:2062)
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.lambda$onError$2(TracingSubscriber.java:63)
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.withActiveSpan(TracingSubscriber.java:79)
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.onError(TracingSubscriber.java:63)
at reactor.core.publisher.FluxHandle$HandleSubscriber.onError(FluxHandle.java:202)
at reactor.core.publisher.Operators.error(Operators.java:197)
at reactor.core.publisher.MonoError.subscribe(MonoError.java:52)
at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157)
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.lambda$onNext$1(TracingSubscriber.java:58)
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.withActiveSpan(TracingSubscriber.java:79)
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.onNext(TracingSubscriber.java:58)
at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onNext(FluxHide.java:136)
at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:180)
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.lambda$onNext$1(TracingSubscriber.java:58)
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.withActiveSpan(TracingSubscriber.java:79)
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.onNext(TracingSubscriber.java:58)
at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:199)
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.lambda$onNext$1(TracingSubscriber.java:58)
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.withActiveSpan(TracingSubscriber.java:79)
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.onNext(TracingSubscriber.java:58)
at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:73)
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.lambda$onNext$1(TracingSubscriber.java:58)
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.withActiveSpan(TracingSubscriber.java:79)
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.onNext(TracingSubscriber.java:58)
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.lambda$onNext$1(TracingSubscriber.java:58)
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.withActiveSpan(TracingSubscriber.java:79)
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.onNext(TracingSubscriber.java:58)
at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:127)
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.lambda$onNext$1(TracingSubscriber.java:58)
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.withActiveSpan(TracingSubscriber.java:79)
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.onNext(TracingSubscriber.java:58)
at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onNext(FluxHide.java:136)
at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1815)
at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:249)
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.lambda$onNext$1(TracingSubscriber.java:58)
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.withActiveSpan(TracingSubscriber.java:79)
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.onNext(TracingSubscriber.java:58)
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.lambda$onNext$1(TracingSubscriber.java:58)
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.withActiveSpan(TracingSubscriber.java:79)
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.onNext(TracingSubscriber.java:58)
at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1815)
at reactor.core.publisher.MonoCompletionStage.lambda$subscribe$0(MonoCompletionStage.java:82)
at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1595)
at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582)
at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Suppressed: java.lang.Exception: #block terminated with an error
at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:139)
at reactor.core.publisher.Mono.block(Mono.java:1727)
at com.azure.messaging.servicebus.ServiceBusSenderClient.sendMessage(ServiceBusSenderClient.java:178)
at com.msci.esb.client.asb.ASBSenderClient.sendInternal(ASBSenderClient.java:126)
at com.msci.esb.client.asb.ASBSenderClient.send(ASBSenderClient.java:70)
at com.msci.esb.utils.ResponseUtils.lambda$sendViaSenders$0(ResponseUtils.java:36)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1082)
at com.msci.esb.utils.ResponseUtils.sendViaSenders(ResponseUtils.java:36)
at com.msci.esb.services.ESBEventHandler.onRunning(ESBEventHandler.java:712)
at com.msci.esb.services.ESBEventHandler.applyOnRunningHandler(ESBEventHandler.java:613)
at com.msci.esb.services.ESBEventHandler.wrap(ESBEventHandler.java:447)
at com.msci.esb.services.ESBEventHandler.lambda$onConsume$9(ESBEventHandler.java:431)
at java.util.function.Function.lambda$andThen$1(Function.java:88)
at java.util.function.Function.lambda$andThen$1(Function.java:88)
at com.msci.esb.services.ESBEventHandler.onConsume(ESBEventHandler.java:433)
at com.msci.esb.services.ESBEventHandler.lambda$start$1(ESBEventHandler.java:170)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Cannot send a message when request response channel is disposed.
at com.azure.core.amqp.implementation.RequestResponseChannel.sendWithAck(RequestResponseChannel.java:297)
at com.azure.core.amqp.implementation.RequestResponseChannel.sendWithAck(RequestResponseChannel.java:284)
at com.azure.core.amqp.implementation.ClaimsBasedSecurityChannel.lambda$authorize$2(ClaimsBasedSecurityChannel.java:67)
at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:125)
... 43 more
```
**To Reproduce**
1. Receive a message from a topic using ServiceBusReceiverClient.
2. Then process the received message. Suppose, it takes a very long time, e.g. 2-3 hours.
3. During the processing time, keep renewing the message lock. Please note that the server message lock time for the topic is maximum 5 minutes. And we are renewing the lock every one minute making sure that it never loses the lock.
4. Once the processing is over, send a new message to the same topic using ServiceBusSenderClient.
5. Exception comes: Cannot send a message when request response channel is disposed

**Expected behavior**

Message should have been sent to topic by using ServiceBusSenderClient without any exception. Even if there is some diconnect between sender and server, SDK should revive the connection automatically. Please note that this error is an intermittent error.

**Setup (please complete the following information):**
 - OS: UNIX
 - IDE: IntelliJ
 - Library/Libraries: com.azure:azure-messaging-servicebus:7.5.1
 - Java version: 8
 - App Server/Environment: Tomcat
 - Frameworks: Spring

**Additional context**
1. Error comes while sending a message after a long processing time.
2. Please note that this error is an intermittent error.
3. Earlier this error was very frequent in our UAT environment. Then as per the suggestion from Microsoft support, we upgraded to the latest SDK azure-messaging-servicebus v7.5.1 and it was fixed for us in UAT environment.
4. But after going into production we encountered this error again but only once in the last 20 days.

**Comment by joshfree** [comment]
@anuchandy could you please take a look at this issue filed by @sohanlal311?

**Comment by lmolkova** [comment]
to fellow Azure SDK devs: I took a look into the call stack from a tracing standpoint. I don't think the issue is related to tracing:

- TracingSubscriber in the call-stack is OpenTelemetry reactor instrumentation that propagates context. From what I can tell it's bubbling up onError callback through the reactor chain and looks healthy (but verbose).

- Based on the issue description, it shouldn't be tracing-related, but tracing might exaggerate memory and perf issues, e.g. it can cause OOM faster or some new race conditions to happen. 

Happy to investigate further if needed.

**Comment by paul2u** [comment]
@joshfree @lmolkova Thank you for checking this issue. 
Would you direct to correct engineer if it is misrouted.

**Comment by sohanlal311** [comment]
Please note that we stopped receiving messages after the above error. Despite the fact that there were messages lying on subscription, ServiceBusReceiverClient instance was not able to fetch any messages. Seems like ServiceBusReceiverClient was unnecessary pulling the message even when the connection was closed.

Moreover, there is no API on ServiceBusReceiverClient class to know if the connection is lost. Could you please provide the same so that we can destroy the old receiver and create a new one in non-transient error scenarios.

This is highly important for us.

**Comment by paul2u** [comment]
Hi @joshfree  @lmolkova could you locate correct resource to investigate this issue for Sohan?
Thanks.

**Comment by anuchandy** [comment]
@yvgopal  and I had a sync up on the long auto-renewal topic/holding on to the message for a long time - If the underlying amqp-receiver-link or amqp-connection to the service get closed (e.g., transient), then the application's attempt to complete the message(s) at later point will fail even though SDK recovered to use new link/connection underneath. Considering this, an application taking more than a couple of minutes should be designed to handle any duplicate messages.

**Comment by sohanlal311** [comment]
@anuchandy Thanks for you reply. Much appreciated.

1. Regarding the logs of intermittent error - We are currently unable to provide you the DEBUG logs (+/- 20 minutes) for the incident because we do not have DEBUG enabled in production. After reading your message, we have enabled DEBUG logs for two of our micro-services in production which are the most eligible candidates for long running jobs. I will update here on this thread once we encounter this issue again.
2. Regarding ServiceBusReceiverClient - I think it wasn't able to recover the connection (because the above error is a non-transient one), otherwise it would have fetched some messages from ASB and processed them. Most surprising part is that it was constantly trying to pull messages from ASB for around 3 hours and wasn't able to pull even a single message, despite the fact that there were messages on ASB server. Finally, we had to restart the service. These kinds of non-transient errors can occur anytime in production and hence the only solution which I think right now is to re-create the receiver and sender rather than using the old ones. Am I right here? But the problem is that we don't know when to create the new ones as there is no way for us to know that the underlying connection is closed.
3. Regarding the health-check - Yes, we have made a note of it and started following the link provided by you.

**Comment by sohanlal311** [comment]
@anuchandy May I know if there is any update on this one?

**Comment by paul2u** [comment]
@anuchandy Hi Anu, thank you so much for checking this issue. Would you advise further on this?

**Comment by anuchandy** [comment]
Hi @sohanlal311, can you explain a bit more on "_Most surprising part is that it was constantly trying to pull messages from ASB for around 3 hours and wasn't able to pull even a single message, despite the fact that there were messages on the ASB server_"

How did we conclude that the library was trying to "pull messages for 3 hours"? Do you mean you saw the "credit placement events" and "onDelivery events" in the log, but it never handled it over to your application callback?

**Comment by sohanlal311** [comment]
@anuchandy We have put logs in our application. We were calling the receive API again and again with an interval of 10 seconds. We were expecting that this API call would throw us some error since the connection is broken but surprising it didn't. There were messages on ASB server but receive call had no effect since the connection was broken. This is kind of false impression on client side that the API is trying to fetch messages without giving any errors. We were thinking that messages are not present on ASB server. I hope it clarifies.

**Comment by sohanlal311** [comment]
@anuchandy Could you please let me know if there is an update on this one?

**Comment by sohanlal311** [comment]
@anuchandy Sure, we will give it a try and update this thread shortly.

**Comment by sohanlal311** [comment]
@anuchandy We upgraded to the version you specified and I confirm that it has been fixed. Thanks for your support. Please close this ticket

**Comment by anuchandy** [comment]
thanks for confirming @sohanlal311
