### ISSUE TITLE
"The receiver is overrun by more signals than expected" with latest libraries

### ISSUE THREAD

**Issue by sbaunthiyal** [Azure/azure-sdk-for-java#26764]
**Describe the bug**
Recently consumer was upgraded to the latest libraries, post that thousand of "The receiver is overrun by more signals than expected" are being hit in production.

***Exception or Stack Trace***
```
reactor.core.Exceptions$OverflowException: The receiver is overrun by more signals than expected (bounded queue...)
	at reactor.core.Exceptions.failWithOverflow(Exceptions.java:220)
	at reactor.core.publisher.FluxWindowTimeout$WindowTimeoutSubscriber.onNext(FluxWindowTimeout.java:241)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:200)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:130)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:200)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:120)
	at com.azure.messaging.eventhubs.implementation.AmqpReceiveLinkProcessor.drainQueue(AmqpReceiveLinkProcessor.java:486)
	at com.azure.messaging.eventhubs.implementation.AmqpReceiveLinkProcessor.drain(AmqpReceiveLinkProcessor.java:447)
	at com.azure.messaging.eventhubs.implementation.AmqpReceiveLinkProcessor.lambda$onNext$8(AmqpReceiveLinkProcessor.java:261)
	at reactor.core.publisher.LambdaSubscriber.onNext(LambdaSubscriber.java:160)
	at reactor.core.publisher.FluxOnBackpressureBufferStrategy$BackpressureBufferDropOldestSubscriber.innerDrain(FluxOnBackpressureBufferStrategy.java:274)
	at reactor.core.publisher.FluxOnBackpressureBufferStrategy$BackpressureBufferDropOldestSubscriber.drain(FluxOnBackpressureBufferStrategy.java:238)
	at reactor.core.publisher.FluxOnBackpressureBufferStrategy$BackpressureBufferDropOldestSubscriber.onNext(FluxOnBackpressureBufferStrategy.java:203)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.tryEmit(FluxFlatMap.java:543)
	at reactor.core.publisher.FluxFlatMap$FlatMapInner.onNext(FluxFlatMap.java:984)
	at reactor.core.publisher.MonoCreate$DefaultMonoSink.success(MonoCreate.java:165)
	at com.azure.core.amqp.implementation.ReactorReceiver.lambda$new$0(ReactorReceiver.java:78)
	at com.azure.core.amqp.implementation.handler.DispatchHandler.onTimerTask(DispatchHandler.java:34)
	at com.azure.core.amqp.implementation.ReactorDispatcher$WorkScheduler.run(ReactorDispatcher.java:184)
	at org.apache.qpid.proton.reactor.impl.SelectableImpl.readable(SelectableImpl.java:118)
	at org.apache.qpid.proton.reactor.impl.IOHandler.handleQuiesced(IOHandler.java:61)
	at org.apache.qpid.proton.reactor.impl.IOHandler.onUnhandled(IOHandler.java:390)
	at com.azure.core.amqp.implementation.handler.CustomIOHandler.onUnhandled(CustomIOHandler.java:41)
	at org.apache.qpid.proton.engine.BaseHandler.onReactorQuiesced(BaseHandler.java:87)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:206)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.engine.impl.EventImpl.delegate(EventImpl.java:129)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:114)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291)
	at com.azure.core.amqp.implementation.ReactorExecutor.run(ReactorExecutor.java:86)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**To Reproduce**
Build a consumer using the below listed library versions.

***Code Snippet***
```java
EventProcessorClient eventProcessorClient = new EventProcessorClientBuilder()
			.processEvent(this::processEvent, Duration.ofMillis(config.getHealthInterval()))
			.processError(this::processError).processPartitionInitialization(this::initializePartition)
			.processPartitionClose(this::closePartition)
			.credential(config.getFullyQualifiedNamespace(), config.getEventHubName(), credential)
			.consumerGroup(config.getConsumerGroup()).checkpointStore(config.getBlobCheckpoint(credential))
			.initialPartitionEventPosition(map).proxyOptions(getproxyOptions())
			.transportType(AmqpTransportType.AMQP_WEB_SOCKETS).buildEventProcessorClient();
```
**Expected behavior**
Continuous consumption of events without any exceptions.

**Screenshots**

**Setup (please complete the following information):**
 - OS: linux
 - IDE: STS
 - Library/Libraries:  
azure-client-sdk-parent:1.7.0
azure-messaging-eventhubs:5.10.1
azure-storage-blob:12.14.0
azure-identity:1.4.0
azure-messaging-eventhubs-checkpointstore-blob:1.10.0
azure-core-http-netty:1.11.1
reactor-core:3.4.11

 - Java version: 8
 - App Server/Environment: Docker
 - Frameworks: Spring Boot

** Other available logs **

**SDK logs :**
WARN  c.a.m.e.PartitionPumpManager - Error receiving events from partition 0
The receiver is overrun by more signals than expected (bounded queue...)
INFO  c.a.m.e.PartitionPumpManager - Closing consumer for partition id 0
INFO  c.a.m.e.i.EventHubConnectionProcessor - namespace[eus-evh-sub-ps-alight.servicebus.windows.net] entityPath[alight-balance]: AMQP channel processor completed. Notifying 0 subscribers.
INFO  c.a.m.e.i.EventHubConnectionProcessor - Upstream connection publisher was completed. Terminating processor.
INFO  c.a.m.e.i.EventHubConnectionProcessor - namespace[eus-evh-sub-ps-alight.servicebus.windows.net] entityPath[alight-balance]: Channel is disposed.
INFO  c.a.m.e.PartitionPumpManager - Removing partition id 0 from list of processing partitions
INFO  c.a.c.a.i.ReactorConnection - connectionId[MF_e01f22_1643272147743] signal[Disposed by client., isTransient[false], initiatedByClient[true]]: Disposing of ReactorConnection.

**Consumer logs sequence** 
processError is initiated. 
An exception occurred while consuming events with stack trace provided above.
Closed  the partition: 0  Reason : LOST_PARTITION_OWNERSHIP

**Additional context**
This exception has started after upgrading to latest version.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by joshfree** [comment]
@conniey could you please follow up with @sbaunthiyal?

**Comment by conniey** [comment]
Could you provide a bit more information about your set-up?
1. Event Hub configuration
  - How many partitions?
  - What is your throughput units?
  - What is the traffic like in your Event Hub instance?
2. How many instances of EventProcessorClient do you have running simultaneously?
  - What resources do you allocate for this client? (ie. RAM and CPU)
3. What version did you upgrade from?
  - Your bug says you upgraded to 5.10.1 but what was your previous version?
4. What settings do you use when building your EventProcessorClient? (ie. What are your new EventProcessorClientBuilder settings?)

**Comment by sbaunthiyal** [comment]
Hi @conniey, Answers in **Bold**
Event Hub configuration
How many partitions? **15**
What is your throughput units? **Getting that information, will revert soon**
What is the traffic like in your Event Hub instance? **Getting that information, will revert soon**
How many instances of EventProcessorClient do you have running simultaneously? **2**
What resources do you allocate for this client? (ie. RAM and CPU) **Container is running with JVM param of -Xms256m -Xmx256m**
What version did you upgrade from? **Listed below**
Your bug says you upgraded to 5.10.1 but what was your previous version?
**Previous version
azure-client-sdk-parent:1.7.0
azure-messaging-eventhubs:5.1.1
azure-storage-blob:12.6.1
azure-identity:1.1.0-beta.7
azure-messaging-eventhubs-checkpointstore-blob:1.1.1
azure-core-http-netty', version: '1.5.4**

**Comment by conniey** [comment]
Hey, thanks for the information. Unfortunately, any EventProcessorClientBuilder overloads that take into consideration `Duration` use the reactor `windowTimeout` operator, which encounters this issue: #23950 . We are waiting for an external party to fix it. In the meantime, the overloads that don't take `Duration` wouldn't face this issue.

**Comment by sbaunthiyal** [comment]
Thanks, @conniey , removing Duration worked for us.

**Comment by ramya-rao-a** [comment]
Hey @sbaunthiyal 

Closing this issue as the workaround resolves the issue for you. Please subscribe to https://github.com/Azure/azure-sdk-for-java/issues/23950 for updates on the original issue.

Thanks for reporting!
