### ISSUE TITLE
Investigate non-reactive Netty.

### ISSUE THREAD

**Issue by kasobol-msft** [Azure/azure-sdk-for-java#26788]
Investigate how non-reactor Netty would perform for sync clients.

**Comment by kasobol-msft** [comment]
https://github.com/Azure/azure-sdk-for-java/pull/27881

**Comment by lmolkova** [comment]
The conclusion for now is that sync pipeline over async reactor-netty client is good enough:
- stack trace is readable (below) - users would see their code, SDK code and pipeline in the stack, the only missing part  is reactor-netty client stack
- Based on @kasobol-msft (👋 ) perf investigation, SimpleNettyClient is ~20% slower than sync-over-async reactor-netty


```log
	at reactor.core.Exceptions.propagate(Exceptions.java:392)
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:97)
	at reactor.core.publisher.Mono.block(Mono.java:1707)
	at com.azure.core.http.policy.HttpPipelinePolicy.processSync(HttpPipelinePolicy.java:39)
	at com.azure.core.http.HttpPipelineNextSyncPolicy.processSync(HttpPipelineNextSyncPolicy.java:41)
	at com.azure.core.http.policy.HttpPipelineSyncPolicy.processSync(HttpPipelineSyncPolicy.java:37)
	at com.azure.core.http.HttpPipelineNextSyncPolicy.processSync(HttpPipelineNextSyncPolicy.java:41)
	at com.azure.data.appconfiguration.implementation.ConfigurationCredentialsPolicy.processSync(ConfigurationCredentialsPolicy.java:84)
	at com.azure.core.http.HttpPipelineNextSyncPolicy.processSync(HttpPipelineNextSyncPolicy.java:41)
	at com.azure.core.http.policy.HttpPipelineSyncPolicy.processSync(HttpPipelineSyncPolicy.java:37)
	at com.azure.core.http.policy.AddDatePolicy.processSync(AddDatePolicy.java:46)
	at com.azure.core.http.HttpPipelineNextSyncPolicy.processSync(HttpPipelineNextSyncPolicy.java:41)
	at com.azure.core.http.policy.RetryPolicy.attemptSync(RetryPolicy.java:177)
	at com.azure.core.http.policy.RetryPolicy.attemptSync(RetryPolicy.java:190)
	at com.azure.core.http.policy.RetryPolicy.attemptSync(RetryPolicy.java:190)
	at com.azure.core.http.policy.RetryPolicy.attemptSync(RetryPolicy.java:190)
	at com.azure.core.http.policy.RetryPolicy.processSync(RetryPolicy.java:127)
	at com.azure.core.http.HttpPipelineNextSyncPolicy.processSync(HttpPipelineNextSyncPolicy.java:41)
	at com.azure.core.http.policy.HttpPipelineSyncPolicy.processSync(HttpPipelineSyncPolicy.java:37)
	at com.azure.core.http.policy.AddHeadersPolicy.processSync(AddHeadersPolicy.java:45)
	at com.azure.core.http.HttpPipelineNextSyncPolicy.processSync(HttpPipelineNextSyncPolicy.java:41)
	at com.azure.core.http.policy.HttpPipelineSyncPolicy.processSync(HttpPipelineSyncPolicy.java:37)
	at com.azure.core.http.policy.AddHeadersFromContextPolicy.processSync(AddHeadersFromContextPolicy.java:70)
	at com.azure.core.http.HttpPipelineNextSyncPolicy.processSync(HttpPipelineNextSyncPolicy.java:41)
	at com.azure.core.http.policy.HttpPipelineSyncPolicy.processSync(HttpPipelineSyncPolicy.java:37)
	at com.azure.core.http.policy.RequestIdPolicy.processSync(RequestIdPolicy.java:66)
	at com.azure.core.http.HttpPipelineNextSyncPolicy.processSync(HttpPipelineNextSyncPolicy.java:41)
	at com.azure.core.http.policy.HttpPipelineSyncPolicy.processSync(HttpPipelineSyncPolicy.java:37)
	at com.azure.core.http.policy.UserAgentPolicy.processSync(UserAgentPolicy.java:154)
	at com.azure.core.http.HttpPipelineNextSyncPolicy.processSync(HttpPipelineNextSyncPolicy.java:41)
	at com.azure.core.http.HttpPipeline.sendSync(HttpPipeline.java:121)
	at com.azure.core.implementation.http.rest.SyncRestProxy.send(SyncRestProxy.java:49)
	at com.azure.core.implementation.http.rest.SyncRestProxy.invoke(SyncRestProxy.java:74)
	at com.azure.core.implementation.http.rest.RestProxyBase.invoke(RestProxyBase.java:110)
	at com.azure.core.http.rest.RestProxy.invoke(RestProxy.java:95)
	at jdk.proxy2/jdk.proxy2.$Proxy3.getKeyValue(Unknown Source)
	at com.azure.data.appconfiguration.implementation.ConfigurationClientImpl.getConfigurationSettingWithResponse(ConfigurationClientImpl.java:497)
	at com.azure.data.appconfiguration.ConfigurationClient.getConfigurationSetting(ConfigurationClient.java:358)
	at org.example.foo.Program.main(Program.java:122)
```

**Comment by dennis-benzinger-hybris** [comment]
> The conclusion for now is that sync pipeline over async reactor-netty client is good enough:
> 
>     * stack trace is readable (below) - users would see their code, SDK code and pipeline in the stack, the only missing part  is reactor-netty client stack

@lmolkova, how can I set up such a sync pipeline for the [azure-storage-blob SDK](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/storage/azure-storage-blob) ?

With the default async Netty client I have difficulties to find out where exceptions come from.

**Comment by samvaity** [comment]
@dennis-benzinger-hybris We are in the process of setting up a sync pipeline for azure-storage-blob. 
Will update once it is available.
