### ISSUE TITLE
ReactiveException while executing updateCheckpoint

### ISSUE THREAD

**Issue by sbaunthiyal** [Azure/azure-sdk-for-java#26972]
**Describe the bug**
When updateCheckpoint() is executed in the same time frame of eventProcessorClient.stop(). Threads which are polling messages from partition and doing updateCheckpoint hits "ReactiveException: java.lang.InterruptedException"

***Exception or Stack Trace***
reactor.core.Exceptions$ReactiveException: java.lang.InterruptedException
	at reactor.core.Exceptions.propagate(Exceptions.java:392)
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:91)
	at reactor.core.publisher.Mono.block(Mono.java:1706)
	at com.azure.messaging.eventhubs.models.EventContext.updateCheckpoint(EventContext.java:101)
	at com.alight.upoint.azure.consumer.service.AzureConsumerService.processEvent(AzureConsumerService.java:427)
	at com.azure.messaging.eventhubs.EventProcessorClientBuilder$1.processEvent(EventProcessorClientBuilder.java:595)
	at com.azure.messaging.eventhubs.PartitionPumpManager.processEvent(PartitionPumpManager.java:274)
	at com.azure.messaging.eventhubs.PartitionPumpManager.processEvents(PartitionPumpManager.java:318)
	at com.azure.messaging.eventhubs.PartitionPumpManager.lambda$startPartitionPump$2(PartitionPumpManager.java:235)
	at reactor.core.publisher.LambdaSubscriber.onNext(LambdaSubscriber.java:160)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runAsync(FluxPublishOn.java:440)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:527)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:998)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:87)
	... 18 more

**To Reproduce**
Steps to reproduce the behavior: Put consumer under heavy load when eventProcessorClient.stop() is about to be executed.

***Code Snippet***
Let us know if that's needed, will share the abridged code removing business logic.

**Expected behavior**
updateCheckpoint() should execute successfully without interruption.

**Screenshots**
None

Setup (please complete the following information):

OS: linux

IDE: STS

Library/Libraries:
azure-client-sdk-parent:1.7.0
azure-messaging-eventhubs:5.10.1
azure-storage-blob:12.14.0
azure-identity:1.4.0
azure-messaging-eventhubs-checkpointstore-blob:1.10.0
azure-core-http-netty:1.11.1
reactor-core:3.4.11

Java version: 8

App Server/Environment: Docker

Frameworks: Spring Boot

** Other available logs **

Information Checklist
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report

 Bug Description Added
 Repro Steps Added
 Setup information Added

**Comment by joshfree** [comment]
@srnagar could you please follow up with @sbaunthiyal

**Comment by ZejiaJiang** [comment]
@joshfree Hi Josh, Mahitha send this issue to me this morning. I think I can handle this. Let me follow up with this issue.

**Comment by sbaunthiyal** [comment]
@ZejiaJiang Any suggestion or findings on this?

**Comment by ZejiaJiang** [comment]
> @ZejiaJiang Any suggestion or findings on this?

Hi, @sbaunthiyal , I've tried to repro this issue, but failed. Could please provide more informations:

1. If applicable, how many partation in your eventhubs and how many events that your client process per second?
2. I think it's very helpful to share the abridged code for us to understand your scenario that how and when your client call the stop() method. So could you please share the code?

**Comment by sbaunthiyal** [comment]
@ZejiaJiang 
1. With the load of Hundered thousand events minutes before eventProcessorClient.stop() is to be executed, client was processing on average 2000 messages per second.
2. Attached the code
[Consumer.zip](https://github.com/Azure/azure-sdk-for-java/files/8072839/Consumer.zip)

**Comment by ZejiaJiang** [comment]
@sbaunthiyal Thanks.

I will reply ASAP.

**Comment by ZejiaJiang** [comment]
Hi @sbaunthiyal ,

I'd like to ask do you call the `stop()` method directly in your progrom or stop the docker and send a signal to your progrom to call the `stop()` method? If you call the `stop()` method at intervals, how often do you call the `start()` and `stop()` method?

**Comment by sbaunthiyal** [comment]
Hi @ZejiaJiang, stop() is already called directly. You can refer to the code I attached yesterday.

stop() is called after 55 minutes of start() then after 5 minutes, start() is executed again and the cycle goes on.

**Comment by ZejiaJiang** [comment]
Hi @sbaunthiyal ,

Got it. I've already read your code and want to double check this logic. Thanks.

**Comment by sbaunthiyal** [comment]
@ZejiaJiang Yesterday I saw questions on the checkpoint store. Answered them in **bold** text below in case you need it. 
1.	Are there several clients use the same checkpoint store? **There is only one client.**
2.	What kind of checkpoint that the client is using? **Blob Storage**. If the checkpoint store is customized, could you please provide the code? **It's not customized.**

**Comment by ZejiaJiang** [comment]
Update:
client `stop()` method interruped the thead of Reactor, then `updateCheckpoint()` method which is waiting for the response found the thread is interrupted and throw a interruptedException.

**Comment by sbaunthiyal** [comment]
@ZejiaJiang Is there a targeted version for this fix?

**Comment by ZejiaJiang** [comment]
Hi @sbaunthiyal , for this issue, we rely on the third party package ( reactor-core ), I've already create an issue to them to use `shutdown()` instead of `shutdownNow()`, currently there is no respose.

**Comment by ZejiaJiang** [comment]
https://github.com/reactor/reactor-core/issues/3068
