### ISSUE TITLE
[BUG] ServiceBus and EventHub producer examples require processor and attempt  to receive events

### ISSUE THREAD

**Issue by lmolkova** [Azure/azure-sdk-for-java#27052]
When I want to **send** messages using `ServiceBusTemplate` or `EventHubsTemplate`, following [this sample](https://github.com/Azure-Samples/azure-spring-boot-samples/blob/spring-cloud-azure_4.0.0-beta.4/eventhubs/spring-cloud-azure-starter-integration-eventhubs/eventhubs-integration/src/main/java/com/azure/spring/sample/eventhubs/SendController.java) I still have to configure `EventHubsProcessor` like shown [here](https://github.com/Azure-Samples/azure-spring-boot-samples/blob/spring-cloud-azure_4.0.0-beta.4/eventhubs/spring-cloud-azure-starter-integration-eventhubs/eventhubs-integration/src/main/java/com/azure/spring/sample/eventhubs/EventHubIntegrationConfiguration.java#L33).

```java
 @Bean
  public EventHubsInboundChannelAdapter messageChannelAdapter(
          @Qualifier(INPUT_CHANNEL) MessageChannel inputChannel,
          EventHubsProcessorContainer processorContainer) {
      CheckpointConfig config = new CheckpointConfig(CheckpointMode.MANUAL);

      EventHubsInboundChannelAdapter adapter =
              new EventHubsInboundChannelAdapter(processorContainer, EVENTHUB_NAME,
                      CONSUMER_GROUP, config);
      adapter.setOutputChannel(inputChannel);
      return adapter;
  }
```

## Sample should show how to properly send messages without necessarily receiving them

**It seems that the `EventHubsInboundChannelAdapter`  is not required at all to send events and it can be achieved without it at all - so the sample perhaps can be improved to make it clear?**

Here's the [controller code](https://github.com/Azure-Samples/azure-spring-boot-samples/blob/spring-cloud-azure_4.0.0-beta.4/eventhubs/spring-cloud-azure-starter-integration-eventhubs/eventhubs-integration/src/main/java/com/azure/spring/sample/eventhubs/SendController.java) which should demonstrate sending messages only.

## Sample should show configure checkpoint store
Sample [doesn't configure it](https://github.com/Azure-Samples/azure-spring-boot-samples/blob/spring-cloud-azure_4.0.0-beta.4/eventhubs/spring-cloud-azure-starter-integration-eventhubs/eventhubs-integration/src/main/resources/application.yaml) and it causes the following error:

```2022-02-11 10:54:58.674  WARN 4060 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'messageChannelAdapter' defined in class path resource [com/azure/spring/sample/eventhubs/multibinders/EventProducerConfiguration.class]: Unsatisfied dependency expressed through method 'messageChannelAdapter' parameter 1; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.azure.spring.eventhubs.core.EventHubsProcessorContainer' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}```

since `ProcessorContainerConfiguration` is only registered when [checkpoint-store is configured](https://github.com/Azure/azure-sdk-for-java/blob/feature/azure-spring-cloud-4.0/sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/eventhubs/AzureEventHubsMessagingAutoConfiguration.java#L65)

## Receiving messages fails

If I run a sample with a processor configured, it still fails to receive messages
    - it starts receiving: [IntegrationRecordEventProcessingListener.onEvent](https://github.com/Azure/azure-sdk-for-java/blob/feature/azure-spring-cloud-4.0/sdk/spring/spring-integration-azure-eventhubs/src/main/java/com/azure/spring/integration/eventhubs/inbound/EventHubsInboundChannelAdapter.java#L253)
    - but it attempts to send the message to the channel
    - it fails with `dispatcher has no subscribers for channel 'application.input'.` (below) and doesn't checkpoint

Here's SDK verbose log
```2022-02-11 11:34:24.701 ERROR 21168 --- [ition-pump-0-14] c.a.m.eventhubs.PartitionPumpManager     : Error in event processing callback

com.azure.messaging.eventhubs.implementation.PartitionProcessorException: Error in event processing callback
	at com.azure.messaging.eventhubs.PartitionPumpManager.processEvents(PartitionPumpManager.java:322) ~[azure-messaging-eventhubs-5.10.3.jar:5.10.3]
	at com.azure.messaging.eventhubs.PartitionPumpManager.lambda$startPartitionPump$2(PartitionPumpManager.java:235) ~[azure-messaging-eventhubs-5.10.3.jar:5.10.3]
	at reactor.core.publisher.LambdaSubscriber.onNext(LambdaSubscriber.java:160) ~[reactor-core-3.4.9.jar:3.4.9]
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runAsync(FluxPublishOn.java:440) ~[reactor-core-3.4.9.jar:3.4.9]
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:527) ~[reactor-core-3.4.9.jar:3.4.9]
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84) ~[reactor-core-3.4.9.jar:3.4.9]
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37) ~[reactor-core-3.4.9.jar:3.4.9]
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
Caused by: com.azure.messaging.eventhubs.implementation.PartitionProcessorException: Error in event processing callback
	at com.azure.messaging.eventhubs.PartitionPumpManager.processEvent(PartitionPumpManager.java:284) ~[azure-messaging-eventhubs-5.10.3.jar:5.10.3]
	at com.azure.messaging.eventhubs.PartitionPumpManager.processEvents(PartitionPumpManager.java:318) ~[azure-messaging-eventhubs-5.10.3.jar:5.10.3]
	... 12 common frames omitted
Caused by: org.springframework.messaging.MessageDeliveryException: Dispatcher has no subscribers for channel 'application.input'.; nested exception is org.springframework.integration.MessageDispatchingException: Dispatcher has no subscribers, failedMessage=GenericMessage [payload=byte[3], headers={replyChannel=nullChannel, x-opt-sequence-number=48230, azure_checkpointer=com.azure.spring.messaging.checkpoint.AzureCheckpointer@6b472e09, azure_raw_partition_id=0, azure_eventhub_sequence_number=48230, azure_eventhub_enqueued_time=2022-02-11T07:26:35.524Z, x-opt-offset=98784417952, id=df9dc5bb-537a-7619-acfb-c2347a9c2feb, azure_eventhub_offset=98784417952, x-opt-enqueued-time=2022-02-11T07:26:35.524Z, timestamp=1644608040285}]
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:76) ~[spring-integration-core-5.5.3.jar:5.5.3]
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:317) ~[spring-integration-core-5.5.3.jar:5.5.3]
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:272) ~[spring-integration-core-5.5.3.jar:5.5.3]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187) ~[spring-messaging-5.3.9.jar:5.3.9]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166) ~[spring-messaging-5.3.9.jar:5.3.9]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47) ~[spring-messaging-5.3.9.jar:5.3.9]
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109) ~[spring-messaging-5.3.9.jar:5.3.9]
	at org.springframework.integration.endpoint.MessageProducerSupport.sendMessage(MessageProducerSupport.java:208) ~[spring-integration-core-5.5.3.jar:5.5.3]
	at com.azure.spring.integration.eventhubs.inbound.EventHubsInboundChannelAdapter.access$300(EventHubsInboundChannelAdapter.java:77) ~[spring-integration-azure-eventhubs-4.0.0-beta.3.jar:4.0.0-beta.3]
	at com.azure.spring.integration.eventhubs.inbound.EventHubsInboundChannelAdapter$IntegrationRecordEventProcessingListener.onEvent(EventHubsInboundChannelAdapter.java:269) ~[spring-integration-azure-eventhubs-4.0.0-beta.3.jar:4.0.0-beta.3]
	at com.azure.messaging.eventhubs.EventProcessorClientBuilder$1.processEvent(EventProcessorClientBuilder.java:645) ~[azure-messaging-eventhubs-5.10.3.jar:5.10.3]
	at com.azure.messaging.eventhubs.PartitionPumpManager.processEvent(PartitionPumpManager.java:274) ~[azure-messaging-eventhubs-5.10.3.jar:5.10.3]
	... 13 common frames omitted
Caused by: org.springframework.integration.MessageDispatchingException: Dispatcher has no subscribers
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:139) ~[spring-integration-core-5.5.3.jar:5.5.3]
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:106) ~[spring-integration-core-5.5.3.jar:5.5.3]
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:72) ~[spring-integration-core-5.5.3.jar:5.5.3]
	... 24 common frames omitted

2022-02-11 11:34:24.705 ERROR 21168 --- [ition-pump-0-14] reactor.core.scheduler.Schedulers        : Scheduler worker in group main failed with an uncaught exception

com.azure.messaging.eventhubs.implementation.PartitionProcessorException: Error in event processing callback
	at com.azure.messaging.eventhubs.PartitionPumpManager.processEvents(PartitionPumpManager.java:322) ~[azure-messaging-eventhubs-5.10.3.jar:5.10.3]
	at com.azure.messaging.eventhubs.PartitionPumpManager.lambda$startPartitionPump$2(PartitionPumpManager.java:235) ~[azure-messaging-eventhubs-5.10.3.jar:5.10.3]
	at reactor.core.publisher.LambdaSubscriber.onNext(LambdaSubscriber.java:160) ~[reactor-core-3.4.9.jar:3.4.9]
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runAsync(FluxPublishOn.java:440) ~[reactor-core-3.4.9.jar:3.4.9]
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:527) ~[reactor-core-3.4.9.jar:3.4.9]
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84) ~[reactor-core-3.4.9.jar:3.4.9]
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37) ~[reactor-core-3.4.9.jar:3.4.9]
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
Caused by: com.azure.messaging.eventhubs.implementation.PartitionProcessorException: Error in event processing callback
	at com.azure.messaging.eventhubs.PartitionPumpManager.processEvent(PartitionPumpManager.java:284) ~[azure-messaging-eventhubs-5.10.3.jar:5.10.3]
	at com.azure.messaging.eventhubs.PartitionPumpManager.processEvents(PartitionPumpManager.java:318) ~[azure-messaging-eventhubs-5.10.3.jar:5.10.3]
	... 12 common frames omitted
Caused by: org.springframework.messaging.MessageDeliveryException: Dispatcher has no subscribers for channel 'application.input'.; nested exception is org.springframework.integration.MessageDispatchingException: Dispatcher has no subscribers, failedMessage=GenericMessage [payload=byte[3], headers={replyChannel=nullChannel, x-opt-sequence-number=48230, azure_checkpointer=com.azure.spring.messaging.checkpoint.AzureCheckpointer@6b472e09, azure_raw_partition_id=0, azure_eventhub_sequence_number=48230, azure_eventhub_enqueued_time=2022-02-11T07:26:35.524Z, x-opt-offset=98784417952, id=df9dc5bb-537a-7619-acfb-c2347a9c2feb, azure_eventhub_offset=98784417952, x-opt-enqueued-time=2022-02-11T07:26:35.524Z, timestamp=1644608040285}]
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:76) ~[spring-integration-core-5.5.3.jar:5.5.3]
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:317) ~[spring-integration-core-5.5.3.jar:5.5.3]
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:272) ~[spring-integration-core-5.5.3.jar:5.5.3]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187) ~[spring-messaging-5.3.9.jar:5.3.9]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166) ~[spring-messaging-5.3.9.jar:5.3.9]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47) ~[spring-messaging-5.3.9.jar:5.3.9]
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109) ~[spring-messaging-5.3.9.jar:5.3.9]
	at org.springframework.integration.endpoint.MessageProducerSupport.sendMessage(MessageProducerSupport.java:208) ~[spring-integration-core-5.5.3.jar:5.5.3]
	at com.azure.spring.integration.eventhubs.inbound.EventHubsInboundChannelAdapter.access$300(EventHubsInboundChannelAdapter.java:77) ~[spring-integration-azure-eventhubs-4.0.0-beta.3.jar:4.0.0-beta.3]
	at com.azure.spring.integration.eventhubs.inbound.EventHubsInboundChannelAdapter$IntegrationRecordEventProcessingListener.onEvent(EventHubsInboundChannelAdapter.java:269) ~[spring-integration-azure-eventhubs-4.0.0-beta.3.jar:4.0.0-beta.3]
	at com.azure.messaging.eventhubs.EventProcessorClientBuilder$1.processEvent(EventProcessorClientBuilder.java:645) ~[azure-messaging-eventhubs-5.10.3.jar:5.10.3]
	at com.azure.messaging.eventhubs.PartitionPumpManager.processEvent(PartitionPumpManager.java:274) ~[azure-messaging-eventhubs-5.10.3.jar:5.10.3]
	... 13 common frames omitted
Caused by: org.springframework.integration.MessageDispatchingException: Dispatcher has no subscribers
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:139) ~[spring-integration-core-5.5.3.jar:5.5.3]
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:106) ~[spring-integration-core-5.5.3.jar:5.5.3]
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:72) ~[spring-integration-core-5.5.3.jar:5.5.3]
	... 24 common frames omitted
```

So:
- Samples should demonstrate how to send messages (without requiring to receive them)
- regarding `dispatcher has no subscribers for channel 'application.input': either there is a configuration problem, sample issue or a bug, it needs some investigation
- the error message is not descriptive and it's hard to understand what and where went wrong - is there a way to improve it?

**Comment by saragluna** [comment]
@yiliuTo please take a look at this issue.

**Comment by yiliuTo** [comment]
FYI @jialigit

**Comment by yiliuTo** [comment]
Hi @lmolkova thanks for reporting this.
1. For question 1: Sample should show how to properly send messages without necessarily receiving them.
   For the [sample](https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_4.0.0-beta.4/eventhubs/spring-cloud-azure-starter-integration-eventhubs/eventhubs-integration), we want to show how to use Spring Integration framework to both send and receive messages to Event Hubs. Thus we write both send / receive code in this project. 

   Currently the sending logic and configuration are all placed in the [SendController](https://github.com/Azure-Samples/azure-spring-boot-samples/blob/spring-cloud-azure_4.0.0-beta.4/eventhubs/spring-cloud-azure-starter-integration-eventhubs/eventhubs-integration/src/main/java/com/azure/spring/sample/eventhubs/SendController.java). While for receiving part, we first define the necessary bean of `EventHubsInboundChannelAdapter` in [EventHubIntegrationConfiguration](https://github.com/Azure-Samples/azure-spring-boot-samples/blob/spring-cloud-azure_4.0.0-beta.4/eventhubs/spring-cloud-azure-starter-integration-eventhubs/eventhubs-integration/src/main/java/com/azure/spring/sample/eventhubs/EventHubIntegrationConfiguration.java) and the message-consuming logic is in [ReceiveService](https://github.com/Azure-Samples/azure-spring-boot-samples/blob/spring-cloud-azure_4.0.0-beta.4/eventhubs/spring-cloud-azure-starter-integration-eventhubs/eventhubs-integration/src/main/java/com/azure/spring/sample/eventhubs/ReceiveService.java). I am considering to adjust the sample by moving all configuration to one class which means part of the `SendController` should be put into `EventHubIntegrationConfiguration`, and refactor EventHubIntegrationConfiguration as the way [AzureEventHubsMessagingAutoConfiguration](https://github.com/Azure/azure-sdk-for-java/blob/3a1c944c376169588412248fb8667307390faa1e/sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/eventhubs/AzureEventHubsMessagingAutoConfiguration.java#L49) does, in this way can the sending and receiving configration get separated and make it much clearer. cc @backwind1233 

   Thus if you want to try the function of sending only, files of `EventHubIntegrationConfiguration.java` and `ReceiveService.java` should be ignored together with the checkpoint configuration.

2. For question 2, Sample should show configure checkpoint store.
The reason of such error has been introduced above. And do you mean we could have two separated samples of sending / receiving functions instead of putting them together?

3. For question 3, Receiving messages fails.
According to the error `dispatcher has no subscribers for channel 'application.input'`, that may happen when there is no [message handler](https://github.com/Azure-Samples/azure-spring-boot-samples/blob/3e2211d05902f383a0758594c8e88dfc9aa8718c/eventhubs/spring-cloud-azure-starter-integration-eventhubs/eventhubs-integration/src/main/java/com/azure/spring/sample/eventhubs/ReceiveService.java#L29) for the [input channel](https://github.com/Azure-Samples/azure-spring-boot-samples/blob/3e2211d05902f383a0758594c8e88dfc9aa8718c/eventhubs/spring-cloud-azure-starter-integration-eventhubs/eventhubs-integration/src/main/java/com/azure/spring/sample/eventhubs/EventHubIntegrationConfiguration.java#L34) we define for the `EventHubsInboundChannelAdapter`. So can you check if there are any changes in the related part? 

   Besides, such error is thrown by the Spring framework and we cannot wrap or improve it.

**Comment by lmolkova** [comment]
@yiliuTo thanks for the explanation! So my understanding is that `EventHubsInboundChannelAdapter` main use case is to receive and process messages, correct?

I see what you're saying about samples, it makes sense now! I think what was missing is some explanation in the docs where and how specific things are used (I see there are examples in the docs, but not necessarily descriptive javadocs):
- templates 
- `*InboundChannelAdapter` - what's is itand how it's used, what else needed for it to work. 

> For question 2, Sample should show configure checkpoint store.

sorry, it was my bad.

> dispatcher has no subscribers for channel 'application.input',
I removed ReceiveService, but there is no indication in the docs that it has to be there - just samples, so I thought I can remove it. Some docs would be useful.

My concerns, besides a bit more clarity in docs and samples, is  `EventHubsInboundChannelAdapter` design and potential usage. It can be used to both send and receive messages. It probably shouldn't do it all because each user service would likely either send or receive from a single EH/SB, but never both.

There are 4(!) ways to send messages:
```java
 @Autowired
  private EventHubsTemplate template;

  @Autowired
  EventHubOutboundGateway messagingGateway;

  @Autowired
  EventHubProducerClient producer;

  @Autowired
  EventHubsInboundChannelAdapter adapter;

  @GetMapping("/messages")
  public String send() {
      Message<EventData> message =  new GenericMessage<EventData>(new EventData("123"));
      template.send("demohub", message);
      
      EventDataBatch batch = producer.createBatch();
      batch.tryAdd(new EventData("123"));
      this.producer.send(batch);
      this.messagingGateway.send("123");
      this.adapter.getOutputChannel().send(message);
      return "123";
  }
```

**Summary:** it would be great to
1. Review them and see if `EventHubsInboundChannelAdapter ` truly should send messages
1. Document how it should be used and what's required for it to work

**Comment by yiliuTo** [comment]
Hi @lmolkova thanks for such important suggestions! We will refactor the structure of this sample project to make it clearer to understand and easier to modify. Also as you mentioned, introduction about the function of each part, how they work and if other components are needed are also necessary, we will update in the sample's javadoc.

And for the other concern of `EventHubsInboundChannelAdapter`, it is designed only for receving messages but not sending. And its sending related APIs are inheirted from the `MessageProducerSupport` abstraction of Spring Integration, which are used to send messages to other channels aiming to link it with the message handler. And users could also choose to use the output channel (message handler) to send messages to EH/SB, but I think this should be a normal use case. Can this answer your concern of `EventHubsInboundChannelAdapter`?

**Comment by lmolkova** [comment]
@yiliuTo, thanks for the explanation!

now I understand that `EventHubsInboundChannelAdapter` is only used to receive messages and `this.adapter.getOutputChannel().send(message)` does something else in-process.

BTW, why do we want users to write the code below? It seems the bean can be registered in event hub integration and users would only provide `ReceiveService` and `MessageChannel`. Configuration can be done through the application.yml, so why do we want users to write this code at all?

```java
    @Bean
    public EventHubsInboundChannelAdapter messageChannelAdapter(
            @Qualifier(INPUT_CHANNEL) MessageChannel inputChannel,
            EventHubsProcessorContainer processorContainer) {
        CheckpointConfig config = new CheckpointConfig(CheckpointMode.MANUAL);

        EventHubsInboundChannelAdapter adapter =
                new EventHubsInboundChannelAdapter(processorContainer, EVENTHUB_NAME,
                        CONSUMER_GROUP, config);
        adapter.setOutputChannel(inputChannel);
        return adapter;
    }
```

**Comment by yiliuTo** [comment]
Hi @lmolkova thanks for the suggestion. And to declare components such as channel adapters, message handlers is exactly the way of using Spring Integration framework. You can refer to a Spring Integration Kafka [sample](https://github.com/spring-projects/spring-integration-samples/blob/main/basic/kafka/src/main/java/org/springframework/integration/samples/kafka/Application.java#L141) for its usage. And the way you proposed is very similar with Spring Cloud Stream framework, where developers only need to focus on the message-processing logic, and the underlying spring cloud stream binder library takes the responsibily of constructing messaging flows. For example, for our EH/SB spring cloud stream binder libraries, the related inbound channel adapter / message handler is [constructed internally in our library](https://github.com/Azure/azure-sdk-for-java/blob/b5e9555fab13b2a2b5e2a94e55270194dc4baaa5/sdk/spring/spring-cloud-azure-stream-binder-eventhubs/src/main/java/com/azure/spring/cloud/stream/binder/eventhubs/EventHubsMessageChannelBinder.java#L124) instead of the users' code.

**Comment by lmolkova** [comment]
So, the design choice here is to just do exactly what kafka does, and for those who want less code is to go with binders, correct? Are there any reasons for this choice, or some customer development results?

**Comment by yiliuTo** [comment]
Hi @lmolkova , no it's not to follow Kafka only, but the Spring Integration's specification to define configuration of its messaging components like message handler, channel adapter, message channel and so on, here is a [common usage introduction](https://www.baeldung.com/spring-integration), and Kafka is just one of the examples. You can also refer to other [official Spring integration sample projects](https://github.com/spring-projects/spring-integration-samples/tree/main/basic), which usually declare those components in xml, i.e., https://github.com/spring-projects/spring-integration-samples/blob/main/basic/jdbc/src/main/resources/META-INF/spring/integration/spring-integration-context.xml

**Comment by lmolkova** [comment]
Looking into those articles, it seems there are still other ways that don't involve registering this bean or involve different APIs 

https://docs.spring.io/spring-integration/reference/html/kafka.html#kafka-inbound-pollable

```java
@InboundChannelAdapter(channel = "fromKafka", poller = @Poller(fixedDelay = "5000"))
@Bean
public KafkaMessageSource<String, String> source(ConsumerFactory<String, String> cf)  {
    KafkaMessageSource<String, String> source = new KafkaMessageSource<>(cf, "myTopic");
    source.setGroupId("myGroupId");
    source.setClientId("myClientId");
    return source;
}
```

or

```java
@Bean
public IntegrationFlow flow(ConsumerFactory<String, String> cf)  {
    return IntegrationFlows.from(Kafka.inboundChannelAdapter(cf, "myTopic")
                .groupId("myDslGroupId"), e -> e.poller(Pollers.fixedDelay(5000)))
            .handle(System.out::println)
            .get();
}
```

or here https://www.baeldung.com/spring-integration 

My question is how we evaluated all these different configurations and why we picked only an option to explicitly register `EventHubsInboundChannelAdapter` and not some other patten(s)?

**Comment by yiliuTo** [comment]
Hi @lmolkova , thanks for your investigation and comparision. 

Here I would like to introduce one of the main differences between `KafkaMessageSource` and `EventHubsInboundChannelAdapter` first. Spring Integration (SI) has two kinds of abstraction for the inbound message flow which are designed for polling and listening mode. `KafkaMessageSource` belongs to a pollable message source, we can refer to its [javadoc](https://javadoc.io/doc/org.springframework.integration/spring-integration-kafka/5.5.5/org/springframework/integration/kafka/inbound/KafkaMessageSource.html), while `EventHubsInboundChannelAdapter` implements `MessageProducerSupport` which is designed for the listening mode. This difference causes that `EventHubsInboundChannelAdapter` cannot use `@InboundChannelAdapter` for configuration, because it only supports the pollable message source. By the way, to support the polling mode with SDK's consumer client is also in our [plan](https://github.com/Azure/azure-sdk-for-java/issues/26461).

Spring Integration Kafka also has a listening-mode implementation, which is [KafkaMessageDrivenChannelAdapter](https://docs.spring.io/spring-integration/reference/html/kafka.html#kafka-inbound), you can see this implementation also inherit `MessageProducerSupport`. So we could compare the configuration ways between `KafkaMessageDrivenChannelAdapter` and `EventHubsInboundChannelAdapter`.

Refering to Kafka's offcial doc, there are 3 ways documented:
1. [Java Configuration](https://docs.spring.io/spring-integration/reference/html/kafka.html#java-configuration-2)
2. [Java DSL Configuration](https://docs.spring.io/spring-integration/reference/html/kafka.html#java-configuration-2)
3. [XML Configuration](https://docs.spring.io/spring-integration/reference/html/kafka.html#xml-configuration-2)

In fact, the three above ways are provided by Spring Integration framework natively, so they are all applied with EventHubsInboundChannelAdapter and ServiceBusInboundChannelAdapter. We can also introduce other two alternative ways in our sample / docs for wider use cases. Thanks!

**Comment by lmolkova** [comment]
sure, the only thing I would ask for is that before new ways are introduced (and for existing ways), we'd have a user study and get feedback from people with different backgrounds (experienced Spring users and people newer to Spring) on what's useful and what can be better.

**Comment by jialigit** [comment]
> @yiliuTo thanks for the explanation! So my understanding is that `EventHubsInboundChannelAdapter` main use case is to receive and process messages, correct?
> 
> I see what you're saying about samples, it makes sense now! I think what was missing is some explanation in the docs where and how specific things are used (I see there are examples in the docs, but not necessarily descriptive javadocs):
> 
> * templates
> * `*InboundChannelAdapter` - what's is itand how it's used, what else needed for it to work.
> 
> > For question 2, Sample should show configure checkpoint store.
> 
> sorry, it was my bad.
> 
> > dispatcher has no subscribers for channel 'application.input',
> > I removed ReceiveService, but there is no indication in the docs that it has to be there - just samples, so I thought I can remove it. Some docs would be useful.
> 
> My concerns, besides a bit more clarity in docs and samples, is `EventHubsInboundChannelAdapter` design and potential usage. It can be used to both send and receive messages. It probably shouldn't do it all because each user service would likely either send or receive from a single EH/SB, but never both.
> 
> There are 4(!) ways to send messages:
> 
> ```java
>  @Autowired
>   private EventHubsTemplate template;
> 
>   @Autowired
>   EventHubOutboundGateway messagingGateway;
> 
>   @Autowired
>   EventHubProducerClient producer;
> 
>   @Autowired
>   EventHubsInboundChannelAdapter adapter;
> 
>   @GetMapping("/messages")
>   public String send() {
>       Message<EventData> message =  new GenericMessage<EventData>(new EventData("123"));
>       template.send("demohub", message);
>       
>       EventDataBatch batch = producer.createBatch();
>       batch.tryAdd(new EventData("123"));
>       this.producer.send(batch);
>       this.messagingGateway.send("123");
>       this.adapter.getOutputChannel().send(message);
>       return "123";
>   }
> ```
> 
> **Summary:** it would be great to
> 
> 1. Review them and see if `EventHubsInboundChannelAdapter ` truly should send messages (I propose it shouldn't)
> 2. Document how it should be used and what's required for it to work

InboundChannelAdapter is designed to receive messages from remote endpoint. And in this way we could decouple the sending and receiving operation, right? If we send message using the InboundChannelAdapter, that means the message always in the local environment, so what we do this for then? It doesn't make sense in real business logic even though it can work, just make no sense for real job. Isn't it? When using Spring Integration framework, we should always be clear that the basic model for this pattern is about one pipeline and two endpoints. where does message come from and where it goes? Even we can access the channel directly in the code, but it is not designed for users to operate on it on intention. It is by the framework. And of course split the project into producer and consumer separately will make this more clear.
