### ISSUE TITLE
[BUG] Error creating bean with name 'azureResourceManager': NullPointerException

### ISSUE THREAD

**Issue by vprudnikov** [Azure/azure-sdk-for-java#27093]
**Describe the bug**
azure-spring-cloud-starter-eventhubs-kafka doesn't work 

***Exception or Stack Trace***
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'azureResourceManager' defined in class path resource [com/azure/spring/cloud/autoconfigure/context/AzureContextAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.azure.resourcemanager.AzureResourceManager]: Factory method 'azureResourceManager' threw exception; nested exception is java.lang.NullPointerException
at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:658)
at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:638)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
at org.springframework.beans.factory.support.AbstractBeanFactory$$Lambda$407/0x00000000ac10a4a0.getObject(Unknown Source)
at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944)
at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145)
at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:730)
at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:412)
at org.springframework.boot.SpringApplication.run(SpringApplication.java:302)
at org.springframework.boot.SpringApplication.run(SpringApplication.java:1301)
at org.springframework.boot.SpringApplication.run(SpringApplication.java:1290)
at no.my.Application.main(MyApplication.java:10)
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.azure.resourcemanager.AzureResourceManager]: Factory method 'azureResourceManager' threw exception; nested exception is java.lang.NullPointerException
at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
... 20 common frames omitted
Caused by: java.lang.NullPointerException: null
at java.base/java.util.Objects.requireNonNull(Objects.java:208)
at com.azure.core.http.policy.BearerTokenAuthenticationPolicy.<init>(BearerTokenAuthenticationPolicy.java:36)
at com.azure.core.management.http.policy.ArmChallengeAuthenticationPolicy.<init>(ArmChallengeAuthenticationPolicy.java:47)
at com.azure.resourcemanager.resources.fluentcore.policy.AuthenticationPolicy.<init>(AuthenticationPolicy.java:28)
at com.azure.resourcemanager.resources.fluentcore.utils.HttpPipelineProvider.buildHttpPipeline(HttpPipelineProvider.java:87)
at com.azure.resourcemanager.resources.fluentcore.arm.implementation.AzureConfigurableImpl.buildHttpPipeline(AzureConfigurableImpl.java:165)
at com.azure.resourcemanager.AzureResourceManager$ConfigurableImpl.authenticate(AzureResourceManager.java:198)
at com.azure.spring.cloud.autoconfigure.context.AzureContextAutoConfiguration.azureResourceManager(AzureContextAutoConfiguration.java:45)
at com.azure.spring.cloud.autoconfigure.context.AzureContextAutoConfiguration$$EnhancerBySpringCGLIB$$cc6f25c8.CGLIB$azureResourceManager$0(<generated>)
at com.azure.spring.cloud.autoconfigure.context.AzureContextAutoConfiguration$$EnhancerBySpringCGLIB$$cc6f25c8$$FastClassBySpringCGLIB$$659e125e.invoke(<generated>)
at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
at com.azure.spring.cloud.autoconfigure.context.AzureContextAutoConfiguration$$EnhancerBySpringCGLIB$$cc6f25c8.azureResourceManager(<generated>)
```

**To Reproduce**
I got this error after upgrading the libraries. It worked fine with Spring Boot 2.4.4, Azure Cloud 2.3.0, Spring Cloud Dependencies 2020.0.2. I'm running a docker image in a k8s environment containing a Java app that is trying to connect to Azure Event Hubs.

***Code Snippet***
pom.xml
```
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.6.1</version>
    </parent>

    <properties>
        <!-- default environment properties -->
        <java.version>15</java.version>

        <!-- dependency management versions -->
        <lombok.version>1.18.22</lombok.version>
        <jjwt.version>0.9.1</jjwt.version>
        <postgresql.version>42.3.2</postgresql.version>
        <flyway.version>8.4.4</flyway.version>
        <hibernate-types.version>2.14.0</hibernate-types.version>
        <guava.version>31.0.1-jre</guava.version>
        <commons-collections4.version>4.4</commons-collections4.version>
        <commons-compress.version>1.21</commons-compress.version>
        <commons-codec.version>1.15</commons-codec.version>
        <commons-io.version>2.11.0</commons-io.version>
        <springdoc-openapi-ui.version>1.6.6</springdoc-openapi-ui.version>
        <spring-cloud-dependencies.version>2021.0.0</spring-cloud-dependencies.version>
        <azure-spring-cloud.version>2.12.0</azure-spring-cloud.version>
    </properties>

        <dependency>
            <groupId>com.azure.spring</groupId>
            <artifactId>azure-spring-cloud-starter-eventhubs-kafka</artifactId>
            <version>${azure-spring-cloud.version}</version>
        </dependency>

```
configuration:
```
    spring:
      cloud:
        azure:
          client-id: ${AZURE_EVENT_HUBS_SERVICE_PRINCIPAL_CLIENT_ID}
          client-secret: ${AZURE_EVENT_HUBS_SERVICE_PRINCIPAL_CLIENT_SECRET}
          tenant-id: {AZURE_SUBSCRIPTION_TENANT_ID}
          resource-group: {K8S_CLUSTER_NAME}-event-hubs-rg
          eventhub:
            namespace: {K8S_CLUSTER_NAME}-event-hub
```

**Expected behavior**
The application context should not fail. It should just start.

**Setup (please complete the following information):**
 - OS: Linux
 - IDE: N/A
 - Library/Libraries: azure-spring-cloud-starter-eventhubs-kafka:[2.12.0, 2.13.0], spring-boot-starter-parent:[2.6.1, 2.6.2, 2.6.3], spring-cloud-dependencies:2021.0.0
 - Java version: 15
 - App Server/Environment: AKS engine in Azure
 - Frameworks: Spring Boot

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by vprudnikov** [comment]
The issue can be closed.
The reason for the issue was using the outdated version of the azure-core library (as a hotfix for https://github.com/Azure/azure-sdk-for-java/issues/18929)

Fix: please ensure you have the correct version of the `azure-core` in your dependency list.
