### ISSUE TITLE
[BUG] EventHubs - LastEnqueuedEventProperties methods throw Null Pointer Exceptions / processEventBatch Consumer on the EventProcessorClientBuilder gets invoked with empty data

### ISSUE THREAD

**Issue by dennyac** [Azure/azure-sdk-for-java#27121]
**Describe the bug**
This is related to EventHubs SDK
- processEventBatch Consumer<EventBatchContext> on the EventProcessorClientBuilder gets invoked with empty list of EventData. 
- When enabling trackLastEnqueuedEventProperties on EventProcessorClientBuilder, the LastEnqueuedEventProperties methods throw Null Pointer Exceptions when processEventBatch Consumer<EventBatchContext> is invoked with empty list of EventData. 

***Exception or Stack Trace***
```
//Method invoked at InstrumentedEventProcessor.java:44 is eventBatchContext.getLastEnqueuedEventProperties().getEnqueuedTime()

ERROR [2022-02-15 16:23:45,573] com.stealth.service.processor.InstrumentedEventProcessor: Failed to report metrics
! java.lang.NullPointerException: null
! at com.stealth.service.processor.InstrumentedEventProcessor.accept(InstrumentedEventProcessor.java:44)
! at com.stealth.service.processor.InstrumentedEventProcessor.accept(InstrumentedEventProcessor.java:16)
! at com.azure.messaging.eventhubs.EventProcessorClientBuilder$1.processEventBatch(EventProcessorClientBuilder.java:652)
! at com.azure.messaging.eventhubs.PartitionPumpManager.processEvents(PartitionPumpManager.java:306)
! at com.azure.messaging.eventhubs.PartitionPumpManager.lambda$startPartitionPump$2(PartitionPumpManager.java:235)
! at reactor.core.publisher.LambdaSubscriber.onNext(LambdaSubscriber.java:160)
! at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runAsync(FluxPublishOn.java:440)
! at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:527)
! at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
! at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
! at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
! at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
! at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
! at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
! at java.base/java.lang.Thread.run(Thread.java:829)
```
**To Reproduce**
```
EventProcessorClientBuilder().consumerGroup(consumerGroup)
                .trackLastEnqueuedEventProperties(true)
                .processPartitionInitialization(x -> logger
                        .info("Starting to process partition {} on event hub {}", x.getPartitionContext()
                                .getPartitionId(), x.getPartitionContext().getEventHubName()))
                .connectionString(eventHubConfiguration.getConnectionString(), eventHubConfiguration.getEventHubName())
                .checkpointStore(checkpointStore)
                .processEventBatch(ebc -> ebc.getLastEnqueuedEventProperties().getEnqueuedTime(), 50, 20)
                .processError(eventHubErrorProcessor)
                .buildEventProcessorClient().start();
```

***Code Snippet***
Add the code snippet that causes the issue.
```
eventBatchContext.getLastEnqueuedEventProperties().getEnqueuedTime()

```

**Expected behavior**
The provided Consumer<EventBatchContext> shouldn't be invoked when there are no events. Alternatively eventBatchContext.getLastEnqueuedEventProperties() should return an Optional<LastEnqueuedEventProperties>. 

**Screenshots**
NA
**Setup (please complete the following information):**
 - OS: Alpine Linux
 - IDE: IntelliJ
 - Library/Libraries: com.azure:azure-messaging-eventhubs:1.0.6. (azure-sdk-bom.version)
 - Java version: 11
 - App Server/Environment: Jetty
 - Frameworks: Dropwizard

**Additional context**
NA

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by joshfree** [comment]
@conniey could you please take a look?

/cc @Azure/azsdk-sb-java

**Comment by conniey** [comment]
Thanks for the succinct repro. I'll take a look at this
