### ISSUE TITLE
NullPointerException at okhttp3.internal.http1.Http1ExchangeCodec$FixedLengthSource.read()

### ISSUE THREAD

**Issue by adelcheva** [Azure/azure-sdk-for-java#27220]
We are using azure-sdk-for-java version 1.41.2 and we had the following issue. It looks like it is an issue with okhttp3 package. When collecting subscriptions we get a NullPointerException, which stacktrace looks like this: 

```text
java.lang.NullPointerException
		at okhttp3.internal.http1.Http1ExchangeCodec$FixedLengthSource.read(Http1ExchangeCodec.java:429)
		at okhttp3.internal.Util.skipAll(Util.java:204)
		at okhttp3.internal.http1.Http1ExchangeCodec.skipConnectBody(Http1ExchangeCodec.java:308)
		at okhttp3.internal.connection.RealConnection.createTunnel(RealConnection.java:403)
		at okhttp3.internal.connection.RealConnection.connectTunnel(RealConnection.java:236)
		at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:177)
		at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224)
		at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108)
		at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88)
		at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169)
		at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
		at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
		at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
		at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
		at com.microsoft.rest.retry.RetryHandler.intercept(RetryHandler.java:75)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
		at com.microsoft.rest.interceptors.CustomHeadersInterceptor.intercept(CustomHeadersInterceptor.java:140)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
		at com.microsoft.rest.interceptors.UserAgentInterceptor.intercept(UserAgentInterceptor.java:83)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
		at com.microsoft.azure.credentials.AzureTokenCredentialsInterceptor.intercept(AzureTokenCredentialsInterceptor.java:40)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
		...
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
		at com.microsoft.azure.management.resources.fluentcore.utils.ResourceManagerThrottlingInterceptor.intercept(ResourceManagerThrottlingInterceptor.java:56)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
		at com.microsoft.rest.interceptors.BaseUrlHandler.intercept(BaseUrlHandler.java:43)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
		at com.microsoft.rest.interceptors.RequestIdHeaderInterceptor.intercept(RequestIdHeaderInterceptor.java:29)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
		at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
		at okhttp3.RealCall.execute(RealCall.java:81)
		at retrofit2.OkHttpCall.execute(OkHttpCall.java:188)
		at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:40)
		at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:24)
		at rx.Observable.unsafeSubscribe(Observable.java:10327)
		at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
		at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
		at rx.internal.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:107)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
		at java.base/java.lang.Thread.run(Thread.java:829)
```
Can you help us with this?

**Comment by joshfree** [comment]
@srnagar could you please follow up while @alzimmermsft is out?

**Comment by srnagar** [comment]
@adelcheva Could you please confirm that you meant `azure-mgmt-resources` version 1.41.2? Also, it would be great if you could share a sample code snippet to reproduce this issue. Can you also please share more details about the issue?
- Does it happen on each request or are there any specific requests that result in NPE?
- What version of okhttp3 is used? (see how to get the dependency version from [dependency-tree](https://docs.microsoft.com/en-us/azure/developer/java/sdk/troubleshooting-dependency-version-conflict#view-a-dependency-tree))

cc: @weidongxu-microsoft This looks like a Track 1 management library issue.

**Comment by weidongxu-microsoft** [comment]
Yes, 1.41.2 is old lib.

@adelcheva Please consider migrate to https://aka.ms/azsdk/java/mgmt

**Comment by adelcheva** [comment]
Hi, Weidong Xu,

We are using the dependency which comes directly from “com.microsoft.azure:azure:jar:1.41.2” which looks like to be the latest available. I believe we can have a separate dependency, overriding the one that comes from the sdk itself, but it gets harder to keep them both up-to date. Is that what you are proposing?

Thanks,
Anna

From: Weidong Xu ***@***.***>
Date: Wednesday, 23 February 2022, 5:05
To: Azure/azure-sdk-for-java ***@***.***>
Cc: Anna Delcheva ***@***.***>, Mention ***@***.***>
Subject: Re: [Azure/azure-sdk-for-java] NullPointerException at okhttp3.internal.http1.Http1ExchangeCodec$FixedLengthSource.read() (Issue #27220)

Yes, 1.41.2 is old lib.

@adelcheva<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fadelcheva&data=04%7C01%7Cadelcheva%40vmware.com%7C12cba5532c1f452ea33e08d9f679461c%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637811823015855261%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=9cBZuKjSqdzSkYsvupUAuOdU%2FabeWOixUMcXWwHH7lI%3D&reserved=0> Please consider migrate to https://aka.ms/azsdk/java/mgmt<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Fazsdk%2Fjava%2Fmgmt&data=04%7C01%7Cadelcheva%40vmware.com%7C12cba5532c1f452ea33e08d9f679461c%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637811823015855261%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Bj%2Ft96p4DTnjF4kmKKzQgIYzSzVfmIId888C6tbdMeo%3D&reserved=0>

—
Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-sdk-for-java%2Fissues%2F27220%23issuecomment-1048409100&data=04%7C01%7Cadelcheva%40vmware.com%7C12cba5532c1f452ea33e08d9f679461c%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637811823015855261%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ChqDdh2VwK2RmwVYZwZwuXf%2BqQABYmSd4ig%2B5RrpPqs%3D&reserved=0>, or unsubscribe<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAKLGNCI65EK4U2EYKV465MTU4RFFTANCNFSM5O66AONA&data=04%7C01%7Cadelcheva%40vmware.com%7C12cba5532c1f452ea33e08d9f679461c%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637811823015855261%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=19GZJ51S%2BBpA5E9Hdklne6OvjpjV1EkuQ3DLWPHfsC4%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cadelcheva%40vmware.com%7C12cba5532c1f452ea33e08d9f679461c%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637811823015855261%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=LXyX40yDvvUFdIbZPF3Op%2BE2pu1xD4%2B%2FFp5loTtojfs%3D&reserved=0> or Android<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cadelcheva%40vmware.com%7C12cba5532c1f452ea33e08d9f679461c%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637811823015855261%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=vVETbgFAe6lTrv%2Fniacpt%2F6A2br%2F3hIKqgM2wIcKOdE%3D&reserved=0>.

**Comment by weidongxu-microsoft** [comment]
@adelcheva 

You can use this
```
<dependency>
  <groupId>com.azure.resourcemanager</groupId>
  <artifactId>azure-resourcemanager</artifactId>
  <version>2.12.0</version>
</dependency>
```

This is intended to replace "com.microsoft.azure:azure:jar:1.41.2", which is to be deprecated soon.
