### ISSUE TITLE
Getting ERROR c.a.identity.ClientSecretCredential - Azure Identity => ERROR in getToken() call for scopes

### ISSUE THREAD

**Issue by AnjanaCloud** [Azure/azure-sdk-for-java#27267]
I am trying to implement Subscription using Java

Code Snippet that causes the issue : 
```
   final ClientSecretCredential clientSecretCredential = new ClientSecretCredentialBuilder()
                        .clientId(CLIENT_ID)
                        .clientSecret(CLIENT_SECRET)
                        .tenantId(TENANT)
                        .build();

                final TokenCredentialAuthProvider tokenCredAuthProvider =
                        new TokenCredentialAuthProvider(SCOPES, clientSecretCredential);

                final GraphServiceClient graphClient = GraphServiceClient
                        .builder()
                        .authenticationProvider(tokenCredAuthProvider)
                        .buildClient();

                Subscription subscription = new Subscription();
                subscription.changeType = "created,updated";
                subscription.notificationUrl = "https://9b5e-103-142-222-1.ap.ngrok.io/api/mynotification";
                subscription.resource = "/users";
                subscription.expirationDateTime = OffsetDateTimeSerializer.deserialize("2022-02-24T11:00:00.0000000Z");
                subscription.clientState = "secretClientValue";
                subscription.latestSupportedTlsVersion = "v1_2";

                graphClient.subscriptions()
                        .buildRequest()
                        .post(subscription);
```

Expected behavior : After the post call , we expect the subscription to be created in Azure account

```
18:42:48.026 [ForkJoinPool.commonPool-worker-1] ERROR c.a.identity.ClientSecretCredential - Azure Identity => ERROR in getToken() call for scopes [https://graph.microsoft.com/.default]
: Could not initialize class reactor.netty.http.client.HttpClientSecure
com.microsoft.graph.core.ClientException: Error executing the request
        at com.microsoft.graph.http.CoreHttpProvider.sendRequestInternal(CoreHttpProvider.java:411)
        at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:226)
        at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:203)
        at com.microsoft.graph.http.BaseRequest.send(BaseRequest.java:335)
        at com.microsoft.graph.requests.SubscriptionRequest.post(SubscriptionRequest.java:122)
        at com.microsoft.graph.requests.SubscriptionCollectionRequest.post(SubscriptionCollectionRequest.java:64)
        at com.imcs.rest.User.lambda$start$1(User.java:292)
        at io.vertx.core.eventbus.impl.HandlerRegistration.deliver(HandlerRegistration.java:223)
        at io.vertx.core.eventbus.impl.HandlerRegistration.handle(HandlerRegistration.java:200)
        at io.vertx.core.eventbus.impl.EventBusImpl.lambda$deliverToHandler$3(EventBusImpl.java:533)
        at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
        at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Unknown Source)

``
![Screenshot (303)](https://user-images.githubusercontent.com/99974138/155332353-a6e855ce-0d0b-41bf-a557-7d598c7a2d82.png)
![Screenshot (302)](https://user-images.githubusercontent.com/99974138/155332372-de01ed1f-cd2c-4b30-acf0-29d11e4fdb81.png)
`

**Comment by joshfree** [comment]
@g2vinay could you please follow up with @AnjanaCloud on this issue?

/cc @billwert as fyi

**Comment by p-hakim** [comment]
Hi, i have the same probleme, did you fin a solution ?

**Comment by kyleabu** [comment]
Any solution to this?

**Comment by g2vinay** [comment]
@AnjanaCloud 

This appears to be a dependency conflict issue in your environment.

Can you share the dependency tree of your applcation via this command: mvn dependency:tree -Dverbose -f <path-to-pom.xml>

**Comment by g2vinay** [comment]
Closing this issue.
Let us know if the issue still persists or if you have any other questions.
