### ISSUE TITLE
[BUG] Simple ADL2 test project using Azure BOM 1.1.1 fails with "java.lang.NoClassDefFoundError: Could not initialize class reactor.netty.http.client.HttpClientSecure"

### ISSUE THREAD

**Issue by wheezil** [Azure/azure-sdk-for-java#27472]
**Describe the bug**

The attached maven project is a complete example. I was originally writing it to demonstrate a timeout issue, but I can't get that far.  Instead I am stuck on this apparent dependency problem.  You'll need to fill in the account, access key, and container name.

When the sample project is run, it produces a set of similar errors (one per thread, presumably), like:

3:29:07.690 [parallel-8] ERROR reactor.core.scheduler.Schedulers - Scheduler worker in group main failed with an uncaught exception
java.lang.NoClassDefFoundError: Could not initialize class reactor.netty.http.client.HttpClientSecure

***Exception or Stack Trace***
```
13:29:07.690 [parallel-8] ERROR reactor.core.scheduler.Schedulers - Scheduler worker in group main failed with an uncaught exception
java.lang.NoClassDefFoundError: Could not initialize class reactor.netty.http.client.HttpClientSecure
	at reactor.netty.http.client.HttpClientConnect$MonoHttpConnect.lambda$subscribe$0(HttpClientConnect.java:219) ~[reactor-netty-http-1.0.14.jar:1.0.14]
	at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:57) ~[reactor-core-3.4.9.jar:3.4.9]
	at reactor.core.publisher.FluxRetryWhen.subscribe(FluxRetryWhen.java:77) ~[reactor-core-3.4.9.jar:3.4.9]
	at reactor.core.publisher.MonoRetryWhen.subscribeOrReturn(MonoRetryWhen.java:46) ~[reactor-core-3.4.9.jar:3.4.9]
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57) ~[reactor-core-3.4.9.jar:3.4.9]
	at reactor.netty.http.client.HttpClientConnect$MonoHttpConnect.subscribe(HttpClientConnect.java:271) ~[reactor-netty-http-1.0.14.jar:1.0.14]
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[reactor-core-3.4.9.jar:3.4.9]
	at reactor.core.publisher.FluxRetryWhen.subscribe(FluxRetryWhen.java:77) ~[reactor-core-3.4.9.jar:3.4.9]
	at reactor.core.publisher.MonoRetryWhen.subscribeOrReturn(MonoRetryWhen.java:46) ~[reactor-core-3.4.9.jar:3.4.9]
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57) ~[reactor-core-3.4.9.jar:3.4.9]
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) ~[reactor-core-3.4.9.jar:3.4.9]
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[reactor-core-3.4.9.jar:3.4.9]
	at reactor.core.publisher.MonoDelaySubscription.accept(MonoDelaySubscription.java:53) ~[reactor-core-3.4.9.jar:3.4.9]
	at reactor.core.publisher.MonoDelaySubscription.accept(MonoDelaySubscription.java:34) ~[reactor-core-3.4.9.jar:3.4.9]
	at reactor.core.publisher.FluxDelaySubscription$DelaySubscriptionOtherSubscriber.onNext(FluxDelaySubscription.java:131) ~[reactor-core-3.4.9.jar:3.4.9]
	at reactor.core.publisher.MonoDelay$MonoDelayRunnable.propagateDelay(MonoDelay.java:271) ~[reactor-core-3.4.9.jar:3.4.9]
	at reactor.core.publisher.MonoDelay$MonoDelayRunnable.run(MonoDelay.java:286) ~[reactor-core-3.4.9.jar:3.4.9]
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68) [reactor-core-3.4.9.jar:3.4.9]
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28) [reactor-core-3.4.9.jar:3.4.9]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_211]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_211]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_211]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_211]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_211]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
13:29:07.691 [parallel-6] ERROR reactor.core.scheduler.Schedulers - Scheduler worker in group main failed with an uncaught exception
```

**To Reproduce**
Use attached project.  After filling in the account, access key, and container, build and run the attached project

***Code Snippet***
See attached project

**Expected behavior**
Does not produce this error

**Setup (please complete the following information):**
 - Maven 3.6.1
 - OS: Windows 10
 - IDE: IntelliJ
 - Library/Libraries: See pom.xml
 - Java version:  OpenJDK jdk1.8.0_211
 - App Server/Environment: n/a
 - Frameworks: n/a

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree 

Note that all dependencies come through azure BOM 1.1.1 so I would expect it to be compatible with itself.

```
13:36:25.473 [INFO] redpoint:scratch:jar:10.0.1-SNAPSHOT
13:36:25.473 [INFO] +- com.azure:azure-core:jar:1.20.0:compile
13:36:25.473 [INFO] |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.13.0:compile
13:36:25.474 [INFO] |  +- com.fasterxml.jackson.core:jackson-core:jar:2.13.0:compile
13:36:25.474 [INFO] |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.13.0:compile
13:36:25.474 [INFO] |  +- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.13.0:compile
13:36:25.474 [INFO] |  +- com.fasterxml.jackson.dataformat:jackson-dataformat-xml:jar:2.12.4:compile
13:36:25.474 [INFO] |  |  +- com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:2.12.4:compile
13:36:25.475 [INFO] |  |  |  +- jakarta.xml.bind:jakarta.xml.bind-api:jar:2.3.2:compile
13:36:25.475 [INFO] |  |  |  \- jakarta.activation:jakarta.activation-api:jar:1.2.1:compile
13:36:25.475 [INFO] |  |  +- org.codehaus.woodstox:stax2-api:jar:4.2.1:compile
13:36:25.475 [INFO] |  |  \- com.fasterxml.woodstox:woodstox-core:jar:6.2.4:compile
13:36:25.475 [INFO] |  +- io.projectreactor:reactor-core:jar:3.4.9:compile
13:36:25.476 [INFO] |  |  \- org.reactivestreams:reactive-streams:jar:1.0.3:compile
13:36:25.476 [INFO] |  \- io.netty:netty-tcnative-boringssl-static:jar:2.0.40.Final:compile
13:36:25.476 [INFO] +- com.azure:azure-identity:jar:1.3.6:compile
13:36:25.476 [INFO] |  +- com.azure:azure-core-http-netty:jar:1.11.7:compile
13:36:25.476 [INFO] |  |  +- io.netty:netty-handler:jar:4.1.72.Final:compile
13:36:25.476 [INFO] |  |  |  +- io.netty:netty-common:jar:4.1.72.Final:compile
13:36:25.477 [INFO] |  |  |  +- io.netty:netty-resolver:jar:4.1.72.Final:compile
13:36:25.477 [INFO] |  |  |  +- io.netty:netty-transport:jar:4.1.72.Final:compile
13:36:25.477 [INFO] |  |  |  +- io.netty:netty-codec:jar:4.1.72.Final:compile
13:36:25.477 [INFO] |  |  |  \- io.netty:netty-tcnative-classes:jar:2.0.46.Final:compile
13:36:25.477 [INFO] |  |  +- io.netty:netty-handler-proxy:jar:4.1.72.Final:compile
13:36:25.478 [INFO] |  |  |  \- io.netty:netty-codec-socks:jar:4.1.72.Final:compile
13:36:25.478 [INFO] |  |  +- io.netty:netty-buffer:jar:4.1.72.Final:compile
13:36:25.478 [INFO] |  |  +- io.netty:netty-codec-http:jar:4.1.72.Final:compile
13:36:25.478 [INFO] |  |  +- io.netty:netty-codec-http2:jar:4.1.72.Final:compile
13:36:25.478 [INFO] |  |  +- io.netty:netty-transport-native-unix-common:jar:4.1.72.Final:compile
13:36:25.478 [INFO] |  |  +- io.netty:netty-transport-native-epoll:jar:linux-x86_64:4.1.72.Final:compile
13:36:25.479 [INFO] |  |  |  \- io.netty:netty-transport-classes-epoll:jar:4.1.72.Final:compile
13:36:25.479 [INFO] |  |  +- io.netty:netty-transport-native-kqueue:jar:osx-x86_64:4.1.72.Final:compile
13:36:25.479 [INFO] |  |  |  \- io.netty:netty-transport-classes-kqueue:jar:4.1.72.Final:compile
13:36:25.479 [INFO] |  |  \- io.projectreactor.netty:reactor-netty-http:jar:1.0.14:compile
13:36:25.480 [INFO] |  |     +- io.netty:netty-resolver-dns:jar:4.1.72.Final:compile
13:36:25.480 [INFO] |  |     |  \- io.netty:netty-codec-dns:jar:4.1.72.Final:compile
13:36:25.480 [INFO] |  |     +- io.netty:netty-resolver-dns-native-macos:jar:osx-x86_64:4.1.72.Final:compile
13:36:25.480 [INFO] |  |     |  \- io.netty:netty-resolver-dns-classes-macos:jar:4.1.72.Final:compile
13:36:25.480 [INFO] |  |     \- io.projectreactor.netty:reactor-netty-core:jar:1.0.14:compile
13:36:25.481 [INFO] |  +- com.microsoft.azure:msal4j:jar:1.11.0:compile
13:36:25.481 [INFO] |  |  \- com.nimbusds:oauth2-oidc-sdk:jar:9.7:compile
13:36:25.481 [INFO] |  |     +- com.github.stephenc.jcip:jcip-annotations:jar:1.0-1:compile
13:36:25.481 [INFO] |  |     +- com.nimbusds:content-type:jar:2.1:compile
13:36:25.481 [INFO] |  |     +- com.nimbusds:lang-tag:jar:1.5:compile
13:36:25.482 [INFO] |  |     \- com.nimbusds:nimbus-jose-jwt:jar:9.9.3:compile
13:36:25.482 [INFO] |  +- com.microsoft.azure:msal4j-persistence-extension:jar:1.1.0:compile
13:36:25.482 [INFO] |  |  \- net.java.dev.jna:jna:jar:5.5.0:compile
13:36:25.482 [INFO] |  +- net.java.dev.jna:jna-platform:jar:5.6.0:compile
13:36:25.482 [INFO] |  \- net.minidev:json-smart:jar:2.4.7:compile
13:36:25.483 [INFO] |     \- net.minidev:accessors-smart:jar:2.4.7:compile
13:36:25.483 [INFO] |        \- org.ow2.asm:asm:jar:9.1:compile
13:36:25.483 [INFO] +- com.azure:azure-storage-file-datalake:jar:12.7.4:compile
13:36:25.483 [INFO] |  \- com.azure:azure-storage-blob:jar:12.14.4:compile
13:36:25.483 [INFO] |     +- com.azure:azure-storage-common:jar:12.14.3:compile
13:36:25.484 [INFO] |     \- com.azure:azure-storage-internal-avro:jar:12.1.4:compile
13:36:25.484 [INFO] +- org.junit.jupiter:junit-jupiter:jar:5.6.2:test
13:36:25.484 [INFO] +- org.junit.jupiter:junit-jupiter-engine:jar:5.6.2:test
13:36:25.484 [INFO] |  +- org.apiguardian:apiguardian-api:jar:1.1.0:test
13:36:25.484 [INFO] |  \- org.junit.platform:junit-platform-engine:jar:1.6.2:test
13:36:25.484 [INFO] +- org.junit.jupiter:junit-jupiter-api:jar:5.6.2:test
13:36:25.485 [INFO] |  +- org.opentest4j:opentest4j:jar:1.2.0:test
13:36:25.485 [INFO] |  \- org.junit.platform:junit-platform-commons:jar:1.6.2:test
13:36:25.485 [INFO] +- org.junit.jupiter:junit-jupiter-params:jar:5.6.2:test
13:36:25.485 [INFO] +- org.apache.logging.log4j:log4j-core:jar:2.17.0:compile
13:36:25.485 [INFO] +- org.apache.logging.log4j:log4j-api:jar:2.17.0:compile
13:36:25.486 [INFO] +- org.apache.logging.log4j:log4j-slf4j-impl:jar:2.17.0:compile
13:36:25.486 [INFO] +- org.apache.logging.log4j:log4j-1.2-api:jar:2.17.0:compile
13:36:25.486 [INFO] +- org.slf4j:jul-to-slf4j:jar:1.7.32:compile
13:36:25.486 [INFO] +- org.slf4j:slf4j-api:jar:1.7.32:compile
13:36:25.486 [INFO] +- commons-logging:commons-logging:jar:1.2:compile
13:36:25.486 [INFO] +- commons-io:commons-io:jar:2.11.0:compile
13:36:25.487 [INFO] \- commons-codec:commons-codec:jar:1.9:compile
```

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X ] Bug Description Added
- [ X] Repro Steps Added
- [ X] Setup information Added

**Comment by wheezil** [comment]
[scratch.zip](https://github.com/Azure/azure-sdk-for-java/files/8193462/scratch.zip)

**Comment by wheezil** [comment]
This seems to be in the same problem space as https://github.com/Azure/azure-sdk-for-java/issues/19041
but I cannot figure out how to use that to resolve my problem, especially using the BOM

**Comment by rickle-msft** [comment]
@pallavit Could you please take a look at how the bom is being used and ensure that everything is good there?

**Comment by pallavit** [comment]
Thank you for reporting the issue. I will take a look at it and get back to you. 

One quick thing that I noticed was that you are taking dependency on BOM 1.1.1 which has azure-core version 1.25.0 in it while your dependency tree is showing azure-core resolved as 1.20.0. Any idea where it is coming from? Any chance your classpath already has an older version of azure-core on it?

**Comment by wheezil** [comment]
I don't know why the dependency tree is like that.  However this is a
standalone maven project and azure is the only dependency, so nothing else
in the environment should be able to influence anything.

**Comment by pallavit** [comment]
Hey I tried using the sample you shared and it compiles and runs w/o dependency version mismatch. Here is the dependency tree that I get on my side.

```
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ scratch ---
[INFO] redpoint:scratch:jar:10.0.1-SNAPSHOT
[INFO] +- com.azure:azure-core:jar:1.25.0:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.13.1:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-core:jar:2.13.1:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.13.1:compile
[INFO] |  +- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.13.1:compile
[INFO] |  +- com.fasterxml.jackson.dataformat:jackson-dataformat-xml:jar:2.13.1:compile
[INFO] |  |  +- org.codehaus.woodstox:stax2-api:jar:4.2.1:compile
[INFO] |  |  \- com.fasterxml.woodstox:woodstox-core:jar:6.2.7:compile
[INFO] |  +- org.slf4j:slf4j-api:jar:1.7.32:compile
[INFO] |  +- io.projectreactor:reactor-core:jar:3.4.13:compile
[INFO] |  |  \- org.reactivestreams:reactive-streams:jar:1.0.3:compile
[INFO] |  \- io.netty:netty-tcnative-boringssl-static:jar:2.0.46.Final:compile
[INFO] |     \- io.netty:netty-tcnative-classes:jar:2.0.46.Final:compile
[INFO] +- com.azure:azure-identity:jar:1.4.4:compile
[INFO] |  +- com.azure:azure-core-http-netty:jar:1.11.7:compile
[INFO] |  |  +- io.netty:netty-handler:jar:4.1.72.Final:compile
[INFO] |  |  |  +- io.netty:netty-common:jar:4.1.72.Final:compile
[INFO] |  |  |  +- io.netty:netty-resolver:jar:4.1.72.Final:compile
[INFO] |  |  |  +- io.netty:netty-transport:jar:4.1.72.Final:compile
[INFO] |  |  |  \- io.netty:netty-codec:jar:4.1.72.Final:compile
[INFO] |  |  +- io.netty:netty-handler-proxy:jar:4.1.72.Final:compile
[INFO] |  |  |  \- io.netty:netty-codec-socks:jar:4.1.72.Final:compile
[INFO] |  |  +- io.netty:netty-buffer:jar:4.1.72.Final:compile
[INFO] |  |  +- io.netty:netty-codec-http:jar:4.1.72.Final:compile
[INFO] |  |  +- io.netty:netty-codec-http2:jar:4.1.72.Final:compile
[INFO] |  |  +- io.netty:netty-transport-native-unix-common:jar:4.1.72.Final:compile
[INFO] |  |  +- io.netty:netty-transport-native-epoll:jar:linux-x86_64:4.1.72.Final:compile
[INFO] |  |  |  \- io.netty:netty-transport-classes-epoll:jar:4.1.72.Final:compile
[INFO] |  |  +- io.netty:netty-transport-native-kqueue:jar:osx-x86_64:4.1.72.Final:compile
[INFO] |  |  |  \- io.netty:netty-transport-classes-kqueue:jar:4.1.72.Final:compile
[INFO] |  |  \- io.projectreactor.netty:reactor-netty-http:jar:1.0.14:compile
[INFO] |  |     +- io.netty:netty-resolver-dns:jar:4.1.72.Final:compile
[INFO] |  |     |  \- io.netty:netty-codec-dns:jar:4.1.72.Final:compile
[INFO] |  |     +- io.netty:netty-resolver-dns-native-macos:jar:osx-x86_64:4.1.72.Final:compile
[INFO] |  |     |  \- io.netty:netty-resolver-dns-classes-macos:jar:4.1.72.Final:compile
[INFO] |  |     \- io.projectreactor.netty:reactor-netty-core:jar:1.0.14:compile
[INFO] |  +- com.microsoft.azure:msal4j:jar:1.11.0:compile
[INFO] |  |  \- com.nimbusds:oauth2-oidc-sdk:jar:9.7:compile
[INFO] |  |     +- com.github.stephenc.jcip:jcip-annotations:jar:1.0-1:compile
[INFO] |  |     +- com.nimbusds:content-type:jar:2.1:compile
[INFO] |  |     +- com.nimbusds:lang-tag:jar:1.5:compile
[INFO] |  |     \- com.nimbusds:nimbus-jose-jwt:jar:9.9.3:compile
[INFO] |  +- com.microsoft.azure:msal4j-persistence-extension:jar:1.1.0:compile
[INFO] |  |  \- net.java.dev.jna:jna:jar:5.5.0:compile
[INFO] |  +- net.java.dev.jna:jna-platform:jar:5.6.0:compile
[INFO] |  \- net.minidev:json-smart:jar:2.4.7:compile
[INFO] |     \- net.minidev:accessors-smart:jar:2.4.7:compile
[INFO] |        \- org.ow2.asm:asm:jar:9.1:compile
[INFO] \- com.azure:azure-storage-file-datalake:jar:12.7.4:compile
[INFO]    \- com.azure:azure-storage-blob:jar:12.14.4:compile
[INFO]       +- com.azure:azure-storage-common:jar:12.14.3:compile
[INFO]       \- com.azure:azure-storage-internal-avro:jar:12.1.4:compile
[INFO] ------------------------------------------------------------------------
```

Core version 1.25.0 is the expected version. Can you please check if you have azure-core 1.20 on your classpath or in the target directory.

**Comment by pallavit** [comment]
You also seem to be resolving an older version of identity(1.3.6) than what is in the BOM(1.4.4).

**Comment by wheezil** [comment]
Yep, you are right, something was corked in my environment.  After moving the project to a new folder and rebuilding, everything is fine.

**Comment by pallavit** [comment]
Glad it worked out. Thank you for letting us know :)
