### ISSUE TITLE
[BUG] Inconsistent routing of traffic via HTTPS_PROXY

### ISSUE THREAD

**Issue by DhavalShewale** [Azure/azure-sdk-for-java#27546]
We are setting HTTPS_PROXY environment variable for routing traffic via proxy, however, we have observed that behavior of this library is not consistent for proxy and hence we are observing intermittent failures as the traffic does not get routed via proxy always.

We are setting HTTPS_PROXY as follows:
``` sh
export HTTPS_PROXY=http://myproxy.mydomain.com:1234
```

We are using `ClientCertificateCredentialBuilder` for authentication
``` java
return new ClientCertificateCredentialBuilder()
    .tenantId(tenantId)
    .clientId(clientId)
    .pfxCertificate(certificatePath, certificatePassword)
    .build();
```

We are observing timeout failures and on investigating we observed that request are directly sent from the host system and not the proxy host and hence are getting blocked
```
2022-03-09 08:59:18,778 | ERROR | [ForkJoinPool.commonPool-worker-19] | com.microsoft.aad.msal4j.ConfidentialClientApplication:logException(155) | [Correlation ID: xxx-xxx-xxx-xxx-xxx] Execution of class com.microsoft.aad.msal4j.AcquireTokenSilentSupplier failed. 
com.microsoft.aad.msal4j.MsalClientException: reactor.core.Exceptions$ReactiveException: io.netty.channel.ConnectTimeoutException: connection timed out: login.microsoftonline.com/20.190.160.9:443
	at com.microsoft.aad.msal4j.HttpHelper.executeHttpRequest(HttpHelper.java:53) ~[msal4j-1.11.0.jar:1.11.0]
	at com.microsoft.aad.msal4j.AadInstanceDiscoveryProvider.executeRequest(AadInstanceDiscoveryProvider.java:232) ~[msal4j-1.11.0.jar:1.11.0]
	at com.microsoft.aad.msal4j.AadInstanceDiscoveryProvider.sendInstanceDiscoveryRequest(AadInstanceDiscoveryProvider.java:187) ~[msal4j-1.11.0.jar:1.11.0]
	at com.microsoft.aad.msal4j.AadInstanceDiscoveryProvider.doInstanceDiscoveryAndCache(AadInstanceDiscoveryProvider.java:285) ~[msal4j-1.11.0.jar:1.11.0]
	at com.microsoft.aad.msal4j.AadInstanceDiscoveryProvider.getMetadataEntry(AadInstanceDiscoveryProvider.java:57) ~[msal4j-1.11.0.jar:1.11.0]
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.getAuthorityWithPrefNetworkHost(AuthenticationResultSupplier.java:39) [msal4j-1.11.0.jar:1.11.0]
	at com.microsoft.aad.msal4j.AcquireTokenSilentSupplier.execute(AcquireTokenSilentSupplier.java:23) ~[msal4j-1.11.0.jar:1.11.0]
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:69) [msal4j-1.11.0.jar:1.11.0]
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:18) [msal4j-1.11.0.jar:1.11.0]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) [?:?]
Caused by: reactor.core.Exceptions$ReactiveException: io.netty.channel.ConnectTimeoutException: connection timed out: login.microsoftonline.com/20.190.160.9:443
	at reactor.core.Exceptions.propagate(Exceptions.java:392) ~[reactor-core-3.4.13.jar:3.4.13]
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:97) ~[reactor-core-3.4.13.jar:3.4.13]
	at reactor.core.publisher.Mono.block(Mono.java:1707) ~[reactor-core-3.4.13.jar:3.4.13]
	at com.azure.identity.implementation.HttpPipelineAdapter.send(HttpPipelineAdapter.java:58) ~[azure-identity-1.4.4.jar:1.4.4]
	at com.microsoft.aad.msal4j.HttpHelper.executeHttpRequestWithRetries(HttpHelper.java:96) ~[msal4j-1.11.0.jar:1.11.0]
	at com.microsoft.aad.msal4j.HttpHelper.executeHttpRequest(HttpHelper.java:49) ~[msal4j-1.11.0.jar:1.11.0]
	... 15 more
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99) ~[reactor-core-3.4.13.jar:3.4.13]
		at reactor.core.publisher.Mono.block(Mono.java:1707) ~[reactor-core-3.4.13.jar:3.4.13]
		at com.azure.identity.implementation.HttpPipelineAdapter.send(HttpPipelineAdapter.java:58) ~[azure-identity-1.4.4.jar:1.4.4]
		at com.microsoft.aad.msal4j.HttpHelper.executeHttpRequestWithRetries(HttpHelper.java:96) ~[msal4j-1.11.0.jar:1.11.0]
		at com.microsoft.aad.msal4j.HttpHelper.executeHttpRequest(HttpHelper.java:49) ~[msal4j-1.11.0.jar:1.11.0]
		at com.microsoft.aad.msal4j.AadInstanceDiscoveryProvider.executeRequest(AadInstanceDiscoveryProvider.java:232) ~[msal4j-1.11.0.jar:1.11.0]
		at com.microsoft.aad.msal4j.AadInstanceDiscoveryProvider.sendInstanceDiscoveryRequest(AadInstanceDiscoveryProvider.java:187) ~[msal4j-1.11.0.jar:1.11.0]
		at com.microsoft.aad.msal4j.AadInstanceDiscoveryProvider.doInstanceDiscoveryAndCache(AadInstanceDiscoveryProvider.java:285) ~[msal4j-1.11.0.jar:1.11.0]
		at com.microsoft.aad.msal4j.AadInstanceDiscoveryProvider.getMetadataEntry(AadInstanceDiscoveryProvider.java:57) ~[msal4j-1.11.0.jar:1.11.0]
		at com.microsoft.aad.msal4j.AuthenticationResultSupplier.getAuthorityWithPrefNetworkHost(AuthenticationResultSupplier.java:39) [msal4j-1.11.0.jar:1.11.0]
		at com.microsoft.aad.msal4j.AcquireTokenSilentSupplier.execute(AcquireTokenSilentSupplier.java:23) ~[msal4j-1.11.0.jar:1.11.0]
		at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:69) [msal4j-1.11.0.jar:1.11.0]
		at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:18) [msal4j-1.11.0.jar:1.11.0]
		at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700) [?:?]
		at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692) [?:?]
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) [?:?]
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) [?:?]
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) [?:?]
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) [?:?]
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) [?:?]
Caused by: io.netty.channel.ConnectTimeoutException: connection timed out: login.microsoftonline.com/20.190.160.9:443
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:261) ~[netty-transport-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[netty-common-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170) ~[netty-common-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[netty-common-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) ~[netty-common-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503) ~[netty-transport-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[netty-common-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.72.Final.jar:4.1.72.Final]
	at java.lang.Thread.run(Thread.java:834) ~[?:?]
```

Pls note that these failures are intermittent and as the library has retry configured, the overall process succeeds after multiple attempts. There are also instances where traffic is routed correctly on first attempt and there are no failures in the log.

**Comment by billwert** [comment]
Taking a look, sorry for the delay @DhavalShewale.

**Comment by DhavalShewale** [comment]
@billwert any update on this?

**Comment by DhavalShewale** [comment]
I made below changes at my end to inject a `httpClient` with `proxyOptions` and now the behavior is quite consistent (i.e. traffic is always routed via proxy)

``` java
    @Bean
    public HttpClient httpClient(@Value("${HTTPS_PROXY:#{null}}") String httpsProxy) throws MalformedURLException {
        ProxyOptions proxyOptions = null;

        if (Objects.nonNull(httpsProxy)) {
            log.info(LoggingMarkers.APP_INFO, "Creating Http Client with Proxy Options - {}...", httpsProxy);
            URL proxyUrl = new URL(httpsProxy);
            proxyOptions = new ProxyOptions(ProxyOptions.Type.HTTP, new InetSocketAddress(proxyUrl.getHost(), proxyUrl.getPort()));
        }

        return Objects.nonNull(proxyOptions) ? new NettyAsyncHttpClientBuilder().proxy(proxyOptions).build() : new NettyAsyncHttpClientBuilder().build();
    }
```

``` java
    @Bean(name = "tokenCredential")
    public TokenCredential certificateTokenCredential(@Value("${TENANT_ID}") String tenantId,
                                                      @Value("${CLIENT_ID}") String clientId,
                                                      @Value("${CERTIFICATE_PATH}") String certificatePath,
                                                      HttpClient httpClient) {
        log.info(LoggingMarkers.APP_INFO, "Using Client Certificate Credentials...");
        return new ClientCertificateCredentialBuilder()
                .tenantId(tenantId)
                .clientId(clientId)
                .pfxCertificate(certificatePath, "")
                .httpClient(httpClient)
                .build();
    }
```

This helps to assert that the auto configuration is somehow not consistent and does not always route the traffic via the proxy.

**Comment by seanb4t** [comment]
This is definitely an issue and is not resolveable in client side code when using the spring starters for keyvault and a keyvault property source due to that keyvault property source being implemented as an environment post processor.

**Comment by billwert** [comment]
@DhavalShewale Hello! Can you validate that you are setting `java.net.useSystemProxies` to true before trying to use `HTTPS_PROXY`? Azure SDK only looks at configuration variables when this property is true.
