### ISSUE TITLE
[BUG] MsalClientException: Token not found in the cache

### ISSUE THREAD

**Issue by DhavalShewale** [Azure/azure-sdk-for-java#27585]
We are observing below failures while authentication. Pls advice

```
2022-03-10 13:45:40,310 |  INFO | [ForkJoinPool.commonPool-worker-19] | io.netty.util.internal.NativeLibraryLoader:load(204) | /tmp/libnetty_tcnative_linux_x86_6412303005071008879412.so exists but cannot be executed even when execute permissions set; check volume for "noexec" flag; use -Dio.netty.native.workdir=[path] to set native working directory separately.
2022-03-10 13:45:40,770 |  INFO | [ForkJoinPool.commonPool-worker-19] | io.netty.util.internal.NativeLibraryLoader:load(204) | /tmp/libnetty_transport_native_epoll_x86_6411635747388686835446.so exists but cannot be executed even when execute permissions set; check volume for "noexec" flag; use -Dio.netty.native.workdir=[path] to set native working directory separately.
2022-03-10 13:45:42,150 | DEBUG | [ForkJoinPool.commonPool-worker-19] | com.microsoft.aad.msal4j.ConfidentialClientApplication:logException(150) | [Correlation ID: xxx-xxx-xxx-xxx-xxx] Execution of class com.microsoft.aad.msal4j.AcquireTokenSilentSupplier failed.
com.microsoft.aad.msal4j.MsalClientException: Token not found in the cache
        at com.microsoft.aad.msal4j.AcquireTokenSilentSupplier.execute(AcquireTokenSilentSupplier.java:98) ~[msal4j-1.11.0.jar:1.11.0]
        at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:69) [msal4j-1.11.0.jar:1.11.0]
        at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:18) [msal4j-1.11.0.jar:1.11.0]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700) [?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692) [?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) [?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) [?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) [?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) [?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) [?:?]
2022-03-10 13:45:42,200 | DEBUG | [ForkJoinPool.commonPool-worker-19] | com.microsoft.aad.msal4j.AcquireTokenByClientCredentialSupplier:execute(24) | SkipCache set to false. Attempting cache lookup
2022-03-10 13:45:42,201 | DEBUG | [ForkJoinPool.commonPool-worker-19] | com.microsoft.aad.msal4j.AcquireTokenByClientCredentialSupplier:execute(48) | Cache lookup failed: Token not found in the cache
2022-03-10 13:45:42,584 | DEBUG | [ForkJoinPool.commonPool-worker-19] | com.microsoft.aad.msal4j.ConfidentialClientApplication:logResult(133) | [Correlation ID: xxx-xxx-xxx-xxx-xxx] Access Token was returned
2022-03-10 13:45:42,602 |  INFO | [ForkJoinPool.commonPool-worker-19] | com.azure.identity.ClientCertificateCredential:performLogging(494) | Azure Identity => getToken() result for scopes [https://xxx-xxx-xxx-xxx.azconfig.io/.default]: SUCCESS
2022-03-10 13:45:42,603 |  INFO | [ForkJoinPool.commonPool-worker-19] | com.azure.core.implementation.AccessTokenCache:info(222) | Acquired a new access token.
2022-03-10 13:45:43,855 | DEBUG | [ForkJoinPool.commonPool-worker-19] | com.microsoft.aad.msal4j.ConfidentialClientApplication:logException(150) | [Correlation ID: xxx-xxx-xxx-xxx-xxx] Execution of class com.microsoft.aad.msal4j.AcquireTokenSilentSupplier failed.
com.microsoft.aad.msal4j.MsalClientException: Token not found in the cache
        at com.microsoft.aad.msal4j.AcquireTokenSilentSupplier.execute(AcquireTokenSilentSupplier.java:98) ~[msal4j-1.11.0.jar:1.11.0]
        at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:69) [msal4j-1.11.0.jar:1.11.0]
        at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:18) [msal4j-1.11.0.jar:1.11.0]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700) [?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692) [?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) [?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) [?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) [?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) [?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) [?:?]
2022-03-10 13:45:43,858 | DEBUG | [ForkJoinPool.commonPool-worker-19] | com.microsoft.aad.msal4j.AcquireTokenByClientCredentialSupplier:execute(24) | SkipCache set to false. Attempting cache lookup
2022-03-10 13:45:43,858 | DEBUG | [ForkJoinPool.commonPool-worker-19] | com.microsoft.aad.msal4j.AcquireTokenByClientCredentialSupplier:execute(48) | Cache lookup failed: Token not found in the cache
```

Pls note that the overall process does not fail as acquiring token is retried multiple times and it eventually succeeds.

**Comment by joshfree** [comment]
@billwert could you please follow up with @DhavalShewale

**Comment by ahmadn3na3** [comment]
we have the same issue in our production enviroment

**Comment by billwert** [comment]
Hello! If the token is successfully retrieved this diagnostic logging can be ignored. The logging correctly indicates that there is not a token in the cache. Following this failure, msal4j will acquire the token (and then cache it for future use.)

Thanks.
