### ISSUE TITLE
Root causing protonj "no current delivery"

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-sdk-for-java#27716]
## Background

Two customer tickets reported that the ProtonJ error "no current delivery" appeared in the logs, but when it happened in the lower layer, it activated a code path in the upper layer that triggered a reliability issue;[ this-pr](https://github.com/Azure/azure-sdk-for-java/pull/24141) addressed it.

This ticket is created so that we can focus on ProtonJ error "no current delivery" .

## Root causing

As part of [this](https://github.com/Azure/azure-sdk-for-java/issues/27482) investigation, we learned that it is possible that the ProtonJ object state can be mutated (e.g disposed) after the "scheduling" of work to the message-pump but before the actual "execution" of the work. 

Sketching the control flow, it looks like the reason for "no current delivery"  is such a mutation; the flow appears to be below -

1. ProtonJ Receiver received a delivery. It updated its __current_ pointer to refer to this delivery then handed it over to ReceiveLinkHandler.
2. ReceiveLinkHandler [enqueues](https://github.com/Azure/azure-sdk-for-java/blob/0ddca1176c70abd30ab69d71c219f487aef4d0d3/sdk/core/azure-core-amqp/src/main/java/com/azure/core/amqp/implementation/handler/ReceiveLinkHandler.java#L164) the delivery to deliveries-Flux. 
3. The async-chain attached to deliveries-Flux [emits](https://github.com/Azure/azure-sdk-for-java/blob/0ddca1176c70abd30ab69d71c219f487aef4d0d3/sdk/core/azure-core-amqp/src/main/java/com/azure/core/amqp/implementation/ReactorReceiver.java#L82) the delivery to ReactorReceiver. 
4. The ReactorReceiver "[schedule](https://github.com/Azure/azure-sdk-for-java/blob/0ddca1176c70abd30ab69d71c219f487aef4d0d3/sdk/core/azure-core-amqp/src/main/java/com/azure/core/amqp/implementation/ReactorReceiver.java#L85)" a work to message-pump thread to decode this delivery.
5. The async-chain is waiting asynchronously for the Sink to complete. The completion happens only when scheduled work in 4 "executes" in the future.
6. The service traffic closed the amqp-receive-link, inturn [frees](https://github.com/Azure/azure-sdk-for-java/blob/0ddca1176c70abd30ab69d71c219f487aef4d0d3/sdk/core/azure-core-amqp/src/main/java/com/azure/core/amqp/implementation/ReactorReceiver.java#L347) the ProtonJ Receiver using message-pump thread. Note: the user-work in 4 and proton-j work in 6 does not execute strictly in FIFO order (two different pipes drive it), but the serial execution is guaranteed.
7. As part of freeing the ProtonJ Receiver, the ProtonJ library frees the delivery (that 4 refers to), settling the delivery and advancing the __current_ pointer. The __current_ become null.
8. ReceiveLinkHandler [enqueues](https://github.com/Azure/azure-sdk-for-java/blob/0ddca1176c70abd30ab69d71c219f487aef4d0d3/sdk/core/azure-core-amqp/src/main/java/com/azure/core/amqp/implementation/handler/ReceiveLinkHandler.java#L237) completion-event to deliveries-Flux. The completion-event emission to the async-chain is deferred because the Sink for the last event (5) is yet to be complete.
9. Work scheduled in 4 executes, but since __current_ is null and not the one the work is referring to, ProtonJ throws "no current delivery"

The exception in 9 goes to global error handling as an unhandled exception. Three 3 issues -

a. The Sink in 5 never errored
b. The completion-event in 8 never emits (because enqueued after a)
c. The unhandled exception forces the parent amqp-connection to close  

The good thing is, there is no one [downstream](https://github.com/Azure/azure-sdk-for-java/blob/0ddca1176c70abd30ab69d71c219f487aef4d0d3/sdk/eventhubs/azure-messaging-eventhubs/src/main/java/com/azure/messaging/eventhubs/implementation/AmqpReceiveLinkProcessor.java#L286) waiting to react to the "terminal event" from a (or b) to happen. But c is concerning because the closure of one amqp-receiver-link combined with the race resulted in amqp-connection to close, which means it causes all other healthy amqp-receiver-links in the same amqp-connection to disconnect from service. 

## Fix

Again fix is simple as [this](https://github.com/Azure/azure-sdk-for-java/issues/27482) ticket, i.e. do a deferred check for disposal of the Receiver so that the side effect is limited to that specific Receiver and not bypassed to the parent connection.

## References

The customer tickets - https://github.com/Azure/azure-sdk-for-java/issues/24575 and https://github.com/Azure/azure-sdk-for-java/issues/26975

**Comment by anuchandy** [comment]
Adding log entries corresponds to the above description -

#### Service closing receive link that dispose the ReactorReceiver

```
INFO  6 --- [tor-executor-15] c.a.c.a.i.handler.ReceiveLinkHandler     : onLinkRemoteClose connectionId[MF_30ffff_1633678666625] linkName[0_85414c_1633678666626], errorCondition[null] errorDescription[null]
INFO  6 --- [tor-executor-15] c.a.c.a.i.handler.ReceiveLinkHandler     : connectionId[MF_30ffff_1633678666625] linkName[0_85414c_1633678666626] state[ACTIVE] Local link state is not closed.
DEBUG 6 --- [tor-executor-15] c.a.c.a.implementation.ReactorReceiver   : connectionId[MF_30ffff_1633678666625] entityPath[projectname-ingest/ConsumerGroups/ingest/Partitions/0] linkName[0_85414c_1633678666626] State CLOSED
DEBUG 6 --- [tor-executor-15] c.a.c.a.implementation.ReactorReceiver   : connectionId[MF_30ffff_1633678666625] entityPath[projectname-ingest/ConsumerGroups/ingest/Partitions/0] linkName[0_85414c_1633678666626] Freeing resources.
DEBUG 6 --- [tor-executor-15] c.a.c.a.i.handler.ReceiveLinkHandler     : connectionId[MF_30ffff_1633678666625], entityPath[projectname-ingest/ConsumerGroups/ingest/Partitions/0], linkName[0_85414c_1633678666626] Could not emit deliveries.close when closing handler.
INFO  6 --- [tor-executor-15] c.a.c.a.implementation.ReactorSession    : linkName[0_85414c_1633678666626] entityPath[projectname-ingest/ConsumerGroups/ingest/Partitions/0]: Complete. Removing receive link.
INFO  6 --- [tor-executor-15] c.a.m.e.i.AmqpReceiveLinkProcessor       : linkName[0_85414c_1633678666626] entityPath[projectname-ingest/ConsumerGroups/ingest/Partitions/0] Receive link endpoint states are closed. Requesting another.
INFO  6 --- [tor-executor-15] c.a.m.e.i.AmqpReceiveLinkProcessor       : Requesting a new AmqpReceiveLink from upstream.
INFO  6 --- [tor-executor-15] c.a.m.e.i.AmqpReceiveLinkProcessor       : linkName[0_85414c_1633678666626] entityPath[projectname-ingest/ConsumerGroups/ingest/Partitions/0]. Setting next AMQP receive link.
INFO  6 --- [undedElastic-24] c.a.m.e.i.AmqpReceiveLinkProcessor       : linkName[0_85414c_1633678666626] entityPath[projectname-ingest/ConsumerGroups/ingest/Partitions/0] Receive link endpoint states are closed. Requesting another.
...
DEBUG 6 --- [tor-executor-15] c.a.c.a.i.handler.ReceiveLinkHandler     : onLinkLocalClose connectionId[MF_30ffff_1633678666625], linkName[0_85414c_1633678666626], errorCondition[null], errorDescription[null]
INFO  6 --- [tor-executor-15] c.a.c.a.i.handler.ReceiveLinkHandler     : onLinkFinal connectionId[MF_30ffff_1633678666625], linkName[0_85414c_1633678666626]
```

#### Work on ReactorReceiver trying to use the Delivery resulting ProtonJ ISE(no current delivery)

```
WARN  6 --- [tor-executor-15] c.a.c.a.implementation.ReactorExecutor   : connectionId[MF_30ffff_1633678666625], message[Unhandled exception while processing events in reactor, report this error.]
java.lang.IllegalStateException: no current delivery

org.apache.qpid.proton.engine.HandlerException: java.lang.IllegalStateException: no current delivery
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:112)
	at org.apache.qpid.proton.engine.impl.EventImpl.delegate(EventImpl.java:129)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:114)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291)
	at com.azure.core.amqp.implementation.ReactorExecutor.run(ReactorExecutor.java:86)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68) ~[reactor-core-3.4.8.jar!/:3.4.8]
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28) ~[reactor-core-3.4.8.jar!/:3.4.8]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
Caused by: java.lang.IllegalStateException: no current delivery
	at org.apache.qpid.proton.engine.impl.ReceiverImpl.recv(ReceiverImpl.java:87)
	at com.azure.core.amqp.implementation.ReactorReceiver.decodeDelivery(ReactorReceiver.java:242)
	at com.azure.core.amqp.implementation.ReactorReceiver.lambda$new$0(ReactorReceiver.java:74)
	at com.azure.core.amqp.implementation.handler.DispatchHandler.onTimerTask(DispatchHandler.java:34)
	at com.azure.core.amqp.implementation.ReactorDispatcher$WorkScheduler.run(ReactorDispatcher.java:184)
	at org.apache.qpid.proton.reactor.impl.SelectableImpl.readable(SelectableImpl.java:118)
	at org.apache.qpid.proton.reactor.impl.IOHandler.handleQuiesced(IOHandler.java:61)
	at org.apache.qpid.proton.reactor.impl.IOHandler.onUnhandled(IOHandler.java:390)
	at com.azure.core.amqp.implementation.handler.CustomIOHandler.onUnhandled(CustomIOHandler.java:41)
	at org.apache.qpid.proton.engine.BaseHandler.onReactorQuiesced(BaseHandler.java:87)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:206)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	... 12 common frames omitted

```
#### ISE localized to one ReactorReceiver causing global effect on the connection

```
INFO  6 --- [tor-executor-15] c.a.c.a.i.ReactorConnection              : onConnectionError connectionId[MF_30ffff_1633678666625], hostName[projectname-eval.servicebus.windows.net], message[Starting new reactor], error[no current delivery, TrackingId: 990db1f5-ff19-41ac-ad4b-27d7485828c5, at: 2021-10-10T10:10:14.855479Z[Etc/UTC], errorContext[NAMESPACE: projectname-eval.servicebus.windows.net. ERROR CONTEXT: N/A]]
DEBUG 6 --- [tor-executor-15] c.a.c.a.i.ReactorConnection              : onReactorError connectionId[MF_30ffff_1633678666625], hostName[projectname-eval.servicebus.windows.net]: Disposing.
INFO  6 --- [tor-executor-15] c.a.c.a.i.ReactorConnection              : connectionId[MF_30ffff_1633678666625] signal[onReactorError: com.azure.core.amqp.exception.AmqpException: no current delivery, TrackingId: 990db1f5-ff19-41ac-ad4b-27d7485828c5, at: 2021-10-10T10:10:14.855479Z[Etc/UTC], errorContext[NAMESPACE: projectname-eval.servicebus.windows.net. ERROR CONTEXT: N/A], isTransient[false], initiatedByClient[false]]: Disposing of ReactorConnection.
INFO  6 --- [tor-executor-15] c.a.m.e.i.EventHubConnectionProcessor    : namespace[projectname-eval.servicebus.windows.net] entityPath[projectname-ingest]: Channel is closed. Requesting upstream. 
DEBUG 6 --- [tor-executor-15] c.a.c.a.i.ReactorConnection              : connectionId[MF_30ffff_1633678666625] Was already closed. Not disposing again.
INFO  6 --- [tor-executor-15] c.a.m.e.i.EventHubConnectionProcessor    : namespace[projectname-eval.servicebus.windows.net] entityPath[projectname-ingest]: Connection not requested, yet. Requesting one.
```
