### ISSUE TITLE
[BUG] Multi-part upload API takes as much memory as the size of parts being uploaded

### ISSUE THREAD

**Issue by wheezil** [Azure/azure-sdk-for-java#27762]
**Describe the bug**

The attached test project is quite simple and can be built using maven.  It shows that more memory is needed in the JVM than the size of file parts being uploaded, despite using a "markable" input file stream to try to make the library not buffer everything.  It does anyway, apparently.

My observation is that the SDK will use memory equal to the total size of all parts being uploaded in parallel, excepting it seems to max out at 1GB per part. 

***Exception or Stack Trace***

The OOM stack looks something like
```
Exception in thread "main" java.util.concurrent.ExecutionException: java.lang.IllegalStateException: io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 1895825415, max: 1908932608)
        at java.util.concurrent.FutureTask.report(Unknown Source)
        at java.util.concurrent.FutureTask.get(Unknown Source)
        at net.redpoint.test.Test2.main(Test2.java:100)
Caused by: java.lang.IllegalStateException: io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 1895825415, max: 1908932608)
        at io.netty.channel.AbstractCoalescingBufferQueue.releaseAndCompleteAll(AbstractCoalescingBufferQueue.java:361)
        at io.netty.channel.AbstractCoalescingBufferQueue.releaseAndFailAll(AbstractCoalescingBufferQueue.java:208)
        at io.netty.handler.ssl.SslHandler.releaseAndFailAll(SslHandler.java:1907)
        at io.netty.handler.ssl.SslHandler.setHandshakeFailure(SslHandler.java:1886)
        at io.netty.handler.ssl.SslHandler.setHandshakeFailure(SslHandler.java:1851)
        at io.netty.handler.ssl.SslHandler.flush(SslHandler.java:780)
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:750)
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:742)
        at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:728)
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.flush(CombinedChannelDuplexHandler.java:531)
        at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:125)
        at io.netty.channel.CombinedChannelDuplexHandler.flush(CombinedChannelDuplexHandler.java:356)
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:750)
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:742)
        at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:728)
        at reactor.netty.channel.MonoSendMany$SendManyInner.run(MonoSendMany.java:324)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Unknown Source)
        Suppressed: java.lang.Exception: #block terminated with an error
                at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:139)
                at reactor.core.publisher.Mono.block(Mono.java:1731)
                at com.azure.storage.common.implementation.StorageImplUtils.blockWithOptionalTimeout(StorageImplUtils.java:130)
                at com.azure.storage.file.datalake.DataLakeFileClient.appendWithResponse(DataLakeFileClient.java:480)
                at net.redpoint.test.Test2.lambda$main$0(Test2.java:93)
                at java.util.concurrent.FutureTask.run(Unknown Source)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
                ... 1 more
Caused by: io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 1895825415, max: 1908932608)
        at io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:802)
        at io.netty.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:731)
        at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:648)
        at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:623)
        at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:202)
        at io.netty.buffer.PoolArena.tcacheAllocateSmall(PoolArena.java:172)
        at io.netty.buffer.PoolArena.allocate(PoolArena.java:134)
        at io.netty.buffer.PoolArena.allocate(PoolArena.java:126)
        at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:395)
        at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:188)
        at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:179)
        at io.netty.handler.ssl.SslHandler$SslEngineType$1.allocateWrapBuffer(SslHandler.java:231)
        at io.netty.handler.ssl.SslHandler.allocateOutNetBuf(SslHandler.java:2256)
        at io.netty.handler.ssl.SslHandler.wrap(SslHandler.java:823)
        at io.netty.handler.ssl.SslHandler.wrapAndFlush(SslHandler.java:797)
        at io.netty.handler.ssl.SslHandler.flush(SslHandler.java:778)
        ... 17 more
```

**To Reproduce**

Build the attached project:
`mvn install`
Run it and tell it to use 2GB of memory, uploading 3 x 1GB parts in parallel
`java -Xmx2g -jar target/*shad*jar 3 1000`
It will also fail with 12 x 100MB parts and 1GB of memory
`java -Xmx1g -jar target/*shad*jar 12 100`

***Code Snippet***

See attached sample

**Expected behavior**

Since the part upload data is on local disk, I expect the upload process to use a lot less memory, like maybe 8MB per part, since it can easily rewind and find the data on disk.

**Screenshots**
n/a

**Setup (please complete the following information):**
 - OS: Windows 10
 - IDE: n/a
 - Library/Libraries: See dependencies in attached project
 - Java version: 8
 - App Server/Environment: n/a
 - Frameworks: none

**Additional context**

Given that we are also facing https://github.com/Azure/azure-sdk-for-java/issues/27473, we are really in a bind with ADL2.  We seem to have to choose between an unstable upload and one that uses great gobs of memory.

**Comment by wheezil** [comment]
[multi_part_upload.zip](https://github.com/Azure/azure-sdk-for-java/files/8311549/multi_part_upload.zip)
See attachment

**Comment by rickle-msft** [comment]
@wheezil Thank you for opening this issue. The append method you're using in this sample does indeed do a lot of buffering, and that is by design. It is intended to be able to support non markable streams, and it doesn't have any awareness of the fact that the data is on the disk. It has to do a fair amount of buffering both to support retries in the general case and also to have a full payload to send. 

I think focusing on one issue at a time will give us the best progress, and I think the better method for your scenario is uploadFromFile, so let's focus there for now.

**Comment by wheezil** [comment]
@rickle-msft I would certainly love to have the uploadFromFile() bug fixed, as it seems like a better solution.
However, I have to disagree with your statement that "doesn't have any awareness of the fact that the data is on the disk".  The SDK code is keenly aware that stream is markable, and complains when it is not.  Yet, despite insisting that you give it a markable stream, it takes no advantage of that capability and buffers all of the data in memory anyway.  Frankly I can kind of see why... the "markable" stream concept is weak and barely useful, kind of retrograde from 1980.  It would be much better to find the underlying SeekableByteChannel and use it for random access.

Anyway, call this an ER, call it a bug, PO-TAY-TOH, PO-TAH-TOH.  Using this much memory is a surprising behavior that IMHO should be addressed at some point, or at least document this isn't suitable for large parts unless you have a lot of memory.

Cheers,
john

**Comment by wheezil** [comment]
Oh, and speaking of documentation... I'm pretty sure at some point I read a suggestion (either a support response, or online doc) that you wrap your FileInputStream in a BufferedInputStream to make it markable, but this makes it use *double* the memory as the size of the data!  We discovered this surprise in production a while ago.

**Comment by rickle-msft** [comment]
We don't use a BufferedInputStream anywhere in the Storage sdks, so we aren't doing any wrapping. We also do all our buffering using async logic, so we wouldn't use streams anyway, but yes, we do have to do some buffering. We do suggest in the docs that the customer use a BufferedInputStream to make their stream markable if the stream is not already markable and they don't have another means of making it markable, but they are also free to implement a more memory efficient wrapper to support marking. We do check that the stream is markable (hence the docs suggestion), but it doesn't have any awareness of the means of supporting marking; there is no knowledge that the data is on disk or simply in memory or another third option. 

We do make use of marking and resetting to support retries as we reset to the mark before reading from the data. However, there isn't a way to get the memory straight from the input stream and put it on the network stream. It has to be read from the stream into a buffer first, hence why we are still instantiating our own buffers. Additionally, not all streams are backed by a SeekableByteChannel, so we can't rely on that. 

The purpose of marking and resetting in this case is to enable the ability to retry uploads, not to necessarily to save on memory. Granted, we shouldn't use more memory than we need, but the insistence on a markable stream is not primarily a memory optimization issue. 

There are multiple upload options, each written with a different scenario in mind:
- uploadFromFile. The data is assumed to be coming from a file. We can take advantage of greater parallelization by reading from different parts of the disk pretty much simultaneously. We can also afford to do less buffering as we can read from disk and have more information about the data from the file's metadata that helps us make a number of decisions about our strategy.
- parallel uploadFromStream, often called buffered upload: This can take any arbitrary stream as its source and will upload in parallel. Because it is so generic, we have very little room to assume anything about the data. Hence, we buffer the stream both to ensure retryability, but also to be able to break the stream up into chunks to support parallelized uploads. These will tend to be called upload and take a ParallelTransferOptions
- Standard upload: These are the methods that are meant to match the REST API 1 to 1. The append method you call in the sample is of this nature. We don't do anything around parallelism or anything, just put the bytes on the wire. That said, there are a couple constraints. 1. The stream must be markable. Primarily for retry support as mentioned. It is a policy of the sdks to always ensure retries are possible given how frequently they are necessary in the wild. 2. All http clients are ultimately async http clients in this sdk. That means we have to convert the stream into an async object, which requires some buffering. While we don't eagerly read the whole stream into memory at once, depending on a number of configurations on the machine, that may be what ends up happening in effect. I believe azure-core is working on a fully sync stack to decouple the sync apis from a dependence on the async apis, which should hopefully remove some of the cost of this conversion.

**Comment by wheezil** [comment]
@rickle-msft  thanks for the explanation!  I do find the SDK to be rather expansive and I'm sure there is more there than I am aware of.

Do you think that, in the fullness of time, we might be better off working with the core/sync API you mentioned?  I have often found that the closer we are to the metal, the more control we have over behavior, but it comes at the expense of needing to deal with more details (like HTTP response codes, exception classes, etc) that are often rather detailed and finicky.  Clearly at some level we could just use basic HTTP calls and read/write directly to the stream, but I doubt we have the fortitude to program at the assembly-language-of-REST.  But we might find benefit from working at a level of the API where there is less magic, if that seems like a viable thing.  We are OK getting our hands dirty!
Thanks
john

**Comment by rickle-msft** [comment]
After an offline conversation, we've agreed that the current best option is to wait for a preview of the sync http stack and see what perf improvements that yields.

**Comment by rickle-msft** [comment]
Another alternative that we discussed but is not immediately necessary is the idea of an appendFromFile method which takes in a range for reading from a file on disk and appending to an azure file. This way we can get some optimizations from being able to read from the disk but it's not an all or nothing file transfer.

**Comment by wheezil** [comment]
Agreed, we have a go-to-production approach which is non-optimal in that there are some time/space tradeoffs we would rather not make, but it is workable.  The background story is that we are implementing an OutputStream that writes to ADL2 using multi-part uploads, so we don't know how big the data is until we are done.  Basically we are starting with a small part size and high parallelism to get performance.  But as the file grows larger we increase part sizes to avoid the 50k part limit, and at that point we may need to reduce parallelism to conserve memory, depending on the JVM settings.  Please do keep me apprised about developments in the sync API and we'll try it out.

**Comment by wheezil** [comment]
@rickle-msft , is the sync http stack available yet?  I would like to try it.

**Comment by wheezil** [comment]
Anyone, has there been any progress on a sync API SDK?
