### ISSUE TITLE
Not able to call azure api of Virtual machine scale set through java sdk

### ISSUE THREAD

**Issue by ningle12** [Azure/azure-sdk-for-java#27819]
Hello , My application on Azure VM is trying to call api of (Virtual machine scale set)VMSS through JAVA SDK but we are getting error message 'javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target' . We are using jdk1.8.0_321 , I see required ssl certificates e.g 'Baltimore CyberTrust Root', 'DigiCert Global Root G2', 'DigiCert Global Root CA' ("https://docs.microsoft.com/en-us/azure/security/fundamentals/tls-certificate-changes") are present under '/jdk1.8.0_321/jre/lib/security/cacerts'. Can you suggest if any other specific certificates are required ?

**Comment by ningle12** [comment]
I am using Eclipse

**Comment by joshfree** [comment]
Hi @ningle12 someone from the `Mgmt` team will follow up with you shortly.

In the mean time, could you please add missing details to the issue above specifically on the SDK version that you're using? 

 The GitHub issue template for the repo can be seen here: https://github.com/Azure/azure-sdk-for-java/blob/main/.github/ISSUE_TEMPLATE/bug_report.md
```
Setup (please complete the following information):

OS: [e.g. iOS]
IDE: [e.g. IntelliJ]
Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)]
Java version: [e.g. 8]
App Server/Environment: [e.g. Tomcat, WildFly, Azure Function, Apache Spark, Databricks, IDE plugin or anything special]
Frameworks: [e.g. Spring Boot, Micronaut, Quarkus, etc]
```




Thank you so much

**Comment by weidongxu-microsoft** [comment]
@ningle12 
ARM connects to https://management.azure.com/

Its CA path has this (root is same "DigiCert Global Root G2")
```
CN = Microsoft Azure TLS Issuing CA 01
O = Microsoft Corporation
C = US
```

**Comment by ningle12** [comment]
OS: Linux
IDE: Eclipse
Library/Libraries:  groupId= com.microsoft.azure , artifactId= azure, version= 1.27.2
Java version: jdk1.8.0_321
App Server/Environment: Tomcat 
Frameworks: Eclipse Modeling Framework (EMF)

Code Snippet: Whenever trying to make call to (Virtual Machine Scale Set)VMSS api.
<img width="534" alt="code" src="https://user-images.githubusercontent.com/102206104/160054112-c32e5df6-a5cd-425c-9e6e-224666b107b9.PNG">

Error: thread:javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by ningle12** [comment]
IDE: Eclipse
Library/Libraries: groupId= com.microsoft.azure , artifactId= azure, version= 1.27.2
Java version: jdk1.8.0_321
App Server/Environment: Tomcat
Frameworks: Eclipse Modeling Framework (EMF)

Code Snippet: Whenever trying to make call to (Virtual Machine Scale Set)VMSS api

<img width="534" alt="code" src="https://user-images.githubusercontent.com/102206104/160054963-09dd089d-d114-45d8-ac45-4293ffa0d9a4.PNG">


Error: thread:javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by weidongxu-microsoft** [comment]
com.microsoft.azure:azure is deprecated
https://github.com/Azure/azure-libraries-for-java

**Comment by weidongxu-microsoft** [comment]
@ningle12

Please migrate to https://aka.ms/azsdk/java/mgmt

PS: would you let me know why using this particular version 1.27.2? Even for that deprecated lib, latest is 1.41.2

**Comment by ningle12** [comment]
Hii @weidongxu-microsoft 
I have update azure libs from 1.27.2 to latest i.e   groupId: com.azure.resourcemanager , artifactId: azure-resourcemanager, version: 2.13.0 still i am getting same error
Getting error at same line i.e:
<img width="641" alt="erroratcode" src="https://user-images.githubusercontent.com/102206104/160594497-479ceaba-14d4-4d18-8427-4bc2205a1950.PNG">

Azure configure code:
 
<img width="746" alt="configuration" src="https://user-images.githubusercontent.com/102206104/160594547-e8e2e2ef-16a2-4c93-a824-51f06b5b5a39.PNG">

sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434)

3/29/22 10:18:52.402 t:[id:115]INFO: [ClientSecretCredential] Azure Identity => getToken() result for scopes [https://management.core.windows.net//.default]: SUCCESS
03/29/22 10:18:52.402 t:[id:115]INFO: [AccessTokenCache] Acquired a new access token.
03/29/22 10:18:52.580 t:[id:112]WARNING: [HttpClientConnect] [845ef473, L:/172.31.81.47:55850 - R:management.azure.com/13.73.240.225:443] The connection observed an error javax.net.ssl.SSLHandshakeException: General OpenSslEngine problem
at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.handshakeException(ReferenceCountedOpenSslEngine.java:1898)
at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.wrap(ReferenceCountedOpenSslEngine.java:822)
at javax.net.ssl.SSLEngine.wrap(SSLEngine.java:511)
at io.netty.handler.ssl.SslHandler.wrap(SslHandler.java:1039)
at io.netty.handler.ssl.SslHandler.wrapNonAppData(SslHandler.java:925)
at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1407)
at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1245)
at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1285)
at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$1.run(AbstractEpollChannel.java:425)
at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.lang.Thread.run(Thread.java:750)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439)
at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306)
at sun.security.validator.Validator.validate(Validator.java:271)
at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:312)
at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:275)
at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:140)
at io.netty.handler.ssl.ReferenceCountedOpenSslClientContext$ExtendedTrustManagerVerifyCallback.verify(ReferenceCountedOpenSslClientContext.java:234)
at io.netty.handler.ssl.ReferenceCountedOpenSslContext$AbstractCertificateVerifier.verify(ReferenceCountedOpenSslContext.java:748)
at io.netty.internal.tcnative.CertificateVerifierTask.runTask(CertificateVerifierTask.java:36)
at io.netty.internal.tcnative.SSLTask.run(SSLTask.java:48)
at io.netty.internal.tcnative.SSLTask.run(SSLTask.java:42)
at io.netty.handler.ssl.ReferenceCountedOpenSslEngine$TaskDecorator.run(ReferenceCountedOpenSslEngine.java:1465)
at io.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:1547)
at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1393)
... 
   
```

**Comment by weidongxu-microsoft** [comment]
@ningle12

1. Please migrate to https://aka.ms/azsdk/java/mgmt
2. Please try add certificate "Microsoft Azure TLS Issuing CA 01"

**Comment by ningle12** [comment]
Hi @weidongxu-microsoft 
I have updated my application to latest azure libs i.e com.azure.resourcemanager  with latest version i.e 2.13.0
I added "Microsoft Azure TLS Issuing CA 01" in java keystore i.e cacerts  still facing same SSLHandshakeException

**Comment by ningle12** [comment]
<img width="426" alt="baltimore" src="https://user-images.githubusercontent.com/102206104/161034294-a8c77a92-8613-46b6-ac97-df74747b7fd1.PNG">
<img width="420" alt="digicertG2" src="https://user-images.githubusercontent.com/102206104/161034317-dc12ad27-d4c8-4606-bf4a-53278c23c9da.PNG">
<img width="418" alt="azuretls" src="https://user-images.githubusercontent.com/102206104/161034340-d7b8d4db-cc75-4c86-aad8-fb583b4291ba.PNG">

Certificates present in java keystore

**Comment by weidongxu-microsoft** [comment]
@XiaofeiCao Would you take a look?

**Comment by ningle12** [comment]
Please reply

**Comment by XiaofeiCao** [comment]
@ningle12 Sorry for the delay, will investigate.

**Comment by ningle12** [comment]
Hii @XiaofeiCao 
Any update ?

**Comment by XiaofeiCao** [comment]
@ningle12 
Hi, currently I'm not able to reproduce the bug using `jdk_1.8.0_321` and eclipse. My truststore has `DigiCert Global Root G2` without `Microsoft Azure TLS Issuing CA 01` and it works fine... 
Does your cacerts contain this certificate(`DigiCert Global Root G2`, not `DigiCert Assured ID Root G2` in your screenshot)? 
![image](https://user-images.githubusercontent.com/92354331/162410314-5d668924-dc5a-480d-9127-367df507be76.png).

**Comment by ningle12** [comment]
<img width="433" alt="digi" src="https://user-images.githubusercontent.com/102206104/162422692-8c22773b-c65e-46c7-ac5e-1f491ea15fca.PNG">

Hii  @XiaofeiCao my keystore i.e cacerts have the following certificate.
And When i call Api's from my eclipse(Wrote a demo program) it also works for me but when i bundled my application with maven install and create tar and install my application on Azure VM at that time i am facing  issue.

**Comment by XiaofeiCao** [comment]
That's weird.. Please try adding the site's certificate: 
1. Visit https://management.azure.com (the site that has issue handshaking) 
2. Get the site's certificate
![image](https://user-images.githubusercontent.com/92354331/162433284-877b28ce-1680-4579-a9bd-fa4a9ebc4b35.png)
![image](https://user-images.githubusercontent.com/92354331/162433349-d74d7857-0d1c-41d3-803e-a122aaa82990.png)
![image](https://user-images.githubusercontent.com/92354331/162433432-8295be04-972a-44f1-a838-7a161307daba.png)
3. Import the certificate to your keystore i.e cacerts

Please also make sure that the JDK that Eclipse uses is actually where you import your certificates...

**Comment by ningle12** [comment]
Hi @XiaofeiCao 
https://management.azure.com  ??

I have added certificates from azure portal that I am using 

<img width="322" alt="azureportal" src="https://user-images.githubusercontent.com/102206104/162675452-48eb3470-b0d7-4ff0-94be-4555d8793f31.PNG">

But still facing same issue.

**Comment by XiaofeiCao** [comment]
@ningle12 mgmt SDK actually called API through gateway https://management.azure.com, not azure portal, as is reported handshake exception in your log here:
> 03/29/22 10:18:52.580 t:[id:112]WARNING: [HttpClientConnect] [845ef473, L:/172.31.81.47:55850 - R:management.azure.com/13.73.240.225:443] The connection observed an error javax.net.ssl.SSLHandshakeException: General OpenSslEngine problem

Normally this isn't necessary, since it's issued by `Microsoft Azure TLS Issuing CA 01`. In this issue's case, you can try adding management's certificate...

**Comment by ningle12** [comment]
I have added Microsoft Azure TLS Issuing CA 01 but same result

thread:javax.net.ssl.SSLHandshakeException: General OpenSslEngine problem
04/11/22 06:58:57.533 t:[id:111]WARNING: [HttpClientConnect] [16f02768, L:/10.100.1.27:45182 - R:management.azure.com/13.86.219.80:443] The connection observed an error javax.net.ssl.SSLHandshakeException: General OpenSslEngine problem
at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.handshakeException(ReferenceCountedOpenSslEngine.java:1898)

**Comment by XiaofeiCao** [comment]
@ningle12 Have you tried adding https://management.azure.com, or it still reports the same result?

**Comment by ningle12** [comment]
I am not able to open this https://management.azure.com

{"error":{"code":"MissingApiVersionParameter","message":"The api-version query parameter (?api-version=) is required for all requests."}}

**Comment by ningle12** [comment]
Not able to open this https://management.azure.com

{"error":{"code":"MissingApiVersionParameter","message":"The api-version query parameter (?api-version=) is required for all requests."}}

**Comment by XiaofeiCao** [comment]
It's expected as it's reported from server-side. The SSL validation is complete. You can export the certificate in this page.

**Comment by XiaofeiCao** [comment]
> Not able to open this https://management.azure.com
> 
> {"error":{"code":"MissingApiVersionParameter","message":"The api-version query parameter (?api-version=) is required for all requests."}}
> 
> Can u pls provide certificate names on https://management.azure.com ?

![image](https://user-images.githubusercontent.com/92354331/162683758-25a3e876-d93a-457c-bf59-c1f8b72eb9e8.png)

**Comment by ningle12** [comment]
<img width="311" alt="sd" src="https://user-images.githubusercontent.com/102206104/162686551-fb1de109-f202-40d3-b271-28753f6e20bd.PNG">
Added certificates still same error

**Comment by XiaofeiCao** [comment]
@ningle12 I can't reproduce the bug for now. If this is urgent issue, consider raising an IcM(https://portal.microsofticm.com/imp/v3/incidents/create) and full-time support will be involved.
