### ISSUE TITLE
Can't create write to Cosmos DB using Java API if partition key is in Upper Case

### ISSUE THREAD

**Issue by salavala** [Azure/azure-sdk-for-java#28002]
**Describe the bug**
Cosmos DB container with an uppercase partition key such as /USER_ID, /ACCOUNT_ID. Java API is failing to write data into Cosmos DB.

INFO: Generated TimeStamp is 2013-01-09 10:11:12.482
{"ClassName":"BadRequestException","userAgent":"azsdk-java-cosmos/4.28.0 Windows10/10.0 JRE/1.8.0_322","statusCode":400,"resourceAddress":"rntbd://cdb-ms-prod-eastus2-fd93.documents.azure.com:14063/apps/02b64f83-cdde-4a01-8492-fd4a7300e8d4/services/8edab210-f145-4308-a7ae-bf104cc7ae06/partitions/5a00a17c-0acf-4a14-be2b-7060010ee34e/replicas/132933042103290174p/","error":"{\"Errors\":[\"PartitionKey extracted from document doesn't match the one specified in the header. Learn more: https://aka.ms/CosmosDB/sql/errors/wrong-pk-value\"]}","innerErrorMessage":"[\"PartitionKey extracted from document doesn't match the one specified in the header. Learn more: https://aka.ms/CosmosDB/sql/errors/wrong-pk-value\"]","causeInfo":null,"responseHeaders":"{x-ms-current-replica-set-size=4, x-ms-last-state-change-utc=Fri, 01 Apr 2022 16:30:12.350 GMT, x-ms-request-duration-ms=0.409, x-ms-session-token=0:-1#1, lsn=1, x-ms-request-charge=1.24, x-ms-schemaversion=1.13, x-ms-transport-request-id=1, x-ms-number-of-read-regions=0, x-ms-current-write-quorum=3, x-ms-cosmos-quorum-acked-llsn=1, x-ms-quorum-acked-lsn=1, x-ms-activity-id=ad570c2b-b1db-11ec-9cd4-f16aefcf8c9c, x-ms-xp-role=1, x-ms-global-Committed-lsn=1, x-ms-cosmos-llsn=1, x-ms-serviceversion= version=2.14.0.0, x-ms-substatus=1001}","cosmosDiagnostics":{"userAgent":"azsdk-java-cosmos/4.28.0 Windows10/10.0 JRE/1.8.0_322","activityId":"ad570c2b-b1db-11ec-9cd4-f16aefcf8c9c","requestLatencyInMs":983,"requestStartTimeUTC":"2022-04-01T16:49:20.482Z","requestEndTimeUTC":"2022-04-01T16:49:21.465Z","responseStatisticsList":[{"storeResult":{"storePhysicalAddress":"rntbd://cdb-ms-prod-eastus2-fd93.documents.azure.com:14063/apps/02b64f83-cdde-4a01-8492-fd4a7300e8d4/services/8edab210-f145-4308-a7ae-bf104cc7ae06/partitions/5a00a17c-0acf-4a14-be2b-7060010ee34e/replicas/132933042103290174p/","lsn":1,"globalCommittedLsn":1,"partitionKeyRangeId":"0","isValid":true,"statusCode":400,"subStatusCode":1001,"isGone":false,"isNotFound":false,"isInvalidPartition":false,"isThroughputControlRequestRateTooLarge":false,"requestCharge":1.24,"itemLSN":-1,"sessionToken":"-1#1","backendLatencyInMs":0.409,"exception":"[\"PartitionKey extracted from document doesn't match the one specified in the header. Learn more: https://aka.ms/CosmosDB/sql/errors/wrong-pk-value\"]","transportRequestTimeline":[{"eventName":"created","startTimeUTC":"2022-04-01T16:49:20.797Z","durationInMicroSec":71000},{"eventName":"queued","startTimeUTC":"2022-04-01T16:49:20.868Z","durationInMicroSec":0},{"eventName":"channelAcquisitionStarted","startTimeUTC":"2022-04-01T16:49:20.868Z","durationInMicroSec":385000},{"eventName":"pipelined","startTimeUTC":"2022-04-01T16:49:21.253Z","durationInMicroSec":144000},{"eventName":"transitTime","startTimeUTC":"2022-04-01T16:49:21.397Z","durationInMicroSec":37000},{"eventName":"decodeTime","startTimeUTC":"2022-04-01T16:49:21.434Z","durationInMicroSec":0},{"eventName":"received","startTimeUTC":"2022-04-01T16:49:21.434Z","durationInMicroSec":31000},{"eventName":"completed","startTimeUTC":"2022-04-01T16:49:21.465Z","durationInMicroSec":0}],"rntbdRequestLengthInBytes":987,"rntbdResponseLengthInBytes":377,"requestPayloadLengthInBytes":539,"responsePayloadLengthInBytes":null,"channelTaskQueueSize":0,"pendingRequestsCount":0,"serviceEndpointStatistics":{"availableChannels":0,"acquiredChannels":0,"executorTaskQueueSize":0,"inflightRequests":1,"lastSuccessfulRequestTime":"2022-04-01T16:49:20.826Z","lastRequestTime":"2022-04-01T16:49:20.826Z","createdTime":"2022-04-01T16:49:20.812Z","isClosed":false}},"requestResponseTimeUTC":"2022-04-01T16:49:21.465Z","requestResourceType":"Document","requestOperationType":"Create"}],"supplementalResponseStatisticsList":[],"addressResolutionStatistics":{"ad7171ff-b1db-11ec-9cd4-f16aefcf8c9c":{"startTimeUTC":"2022-04-01T16:49:20.749Z","endTimeUTC":"2022-04-01T16:49:20.797Z","targetEndpoint":"https://alpha-table-performance-test-eastus2.documents.azure.com:443/addresses/?$resolveFor=dbs%2FLXEaAA%3D%3D%2Fcolls%2FLXEaAKSmbc0%3D%2Fdocs&$filter=protocol%20eq%20rntbd&$partitionKeyRangeIds=0","errorMessage":null,"forceRefresh":false,"forceCollectionRoutingMapRefresh":false,"inflightRequest":false}},"regionsContacted":["east us 2"],"retryContext":{"statusAndSubStatusCodes":null,"retryCount":0,"retryLatency":0},"metadataDiagnosticsContext":{"metadataDiagnosticList":[{"metaDataName":"CONTAINER_LOOK_UP","startTimeUTC":"2022-04-01T16:49:20.576Z","endTimeUTC":"2022-04-01T16:49:20.640Z","durationinMS":64},{"metaDataName":"PARTITION_KEY_RANGE_LOOK_UP","startTimeUTC":"2022-04-01T16:49:20.671Z","endTimeUTC":"2022-04-01T16:49:20.749Z","durationinMS":78},{"metaDataName":"SERVER_ADDRESS_LOOKUP","startTimeUTC":"2022-04-01T16:49:20.749Z","endTimeUTC":"2022-04-01T16:49:20.797Z","durationinMS":48}]},"serializationDiagnosticsContext":{"serializationDiagnosticsList":[{"serializationType":"ITEM_SERIALIZATION","startTimeUTC":"2022-04-01T16:49:20.497Z","endTimeUTC":"2022-04-

***Exception or Stack Trace***
Add the exception log and stack trace if available

01T16:49:20.576Z","durationInMicroSec":79000}]},"gatewayStatistics":null,"systemInformation":{"usedMemory":"71295 KB","availableMemory":"182145 KB","systemCpuLoad":"(2022-04-01T16:49:20.875Z 9.9%)","availableProcessors":8},"clientCfgs":{"id":1,"machineId":"uuid:acd06bcf-8873-4d15-b29b-d0c7da4ae652","connectionMode":"DIRECT","numberOfClients":1,"connCfg":{"rntbd":"(cto:PT5S, nrto:PT5S, icto:PT0S, ieto:PT1H, mcpe:130, mrpc:30, cer:false)","gw":"(cps:1000, nrto:null, icto:null, p:false)","other":"(ed: true, cs: false)"},"consistencyCfg":"(consistency: Session, mm: true, prgns: [])"}}}
        at com.azure.cosmos.implementation.directconnectivity.rntbd.RntbdRequestManager.messageReceived(RntbdRequestManager.java:784)
        at com.azure.cosmos.implementation.directconnectivity.rntbd.RntbdRequestManager.channelRead(RntbdRequestManager.java:182)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1371)
        at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1234)
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1283)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:750)
        Suppressed: java.lang.Exception: #block terminated with an error
                at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
                at reactor.core.publisher.Mono.block(Mono.java:1707)
                at com.azure.cosmos.CosmosContainer.blockItemResponse(CosmosContainer.java:242)
                at com.azure.cosmos.CosmosContainer.createItem(CosmosContainer.java:179)
                at com.azure.cosmos.examples.documentcrud.sync.DocumentCRUDRCGUpperCase.createDocument(DocumentCRUDRCGUpperCase.java:180)
                at com.azure.cosmos.examples.documentcrud.sync.DocumentCRUDRCGUpperCase.documentCRUDDemo(DocumentCRUDRCGUpperCase.java:134)
                at com.azure.cosmos.examples.documentcrud.sync.DocumentCRUDRCGUpperCase.main(DocumentCRUDRCGUpperCase.java:78)
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:498)
                at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
                ... 1 more

**To Reproduce**
1) Create Cosmos DB Container with Upper Case like "/USER_ID"
2) Create Java API to write data into Cosmos DB.

***Code Snippet***
Java Pojo:

 private String CONSUMER_ID="";

 /**
     * @return String return the CONSUMER_ID
     */
    public String getCONSUMER_ID() {
        return CONSUMER_ID;
    }

    /**
     * @param CONSUMER_ID the CONSUMER_ID to set
     */
    public void setCONSUMER_ID(String CONSUMER_ID) {
        this.CONSUMER_ID = CONSUMER_ID;
    }

Calling Class:

   RCGUpperCaseItem rcgObj = new RCGUpperCaseItem();

        rcgObj.setCONSUMER_ID(consumer_id);

CosmosItemResponse<RCGUpperCaseItem> item = container.createItem(rcgObj,new PartitionKey(rcgObj.getCONSUMER_ID()),new CosmosItemRequestOptions());

**Expected behavior**
Java SDK should be able to write data into Cosmos DB if it has Upper Case Partition Key. 

**Screenshots**

**Setup (please complete the following information):**
 - OS: Windows 11
 - IDE: Visual Studio Code
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)]
 - Java version: 1.8.0_322
 - App Server/Environment:N/A
 - Frameworks: N/A
If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by FabianMeiswinkel** [comment]
This has nothing to do with Cosmos DB - but the default naming strategy of Jackson when serializing/deserializing PoJos

Jackson by default uses LOWER_CAMEL_CASE (e.g. lowerCamelCase) - so your Java POJO property below gets transformed form "CONSUMER_ID" into probably "consumerId" (possibly "consumer_id" - haven't tested it)

The article below explains how you can deal with custom property names.

```
/**
* [@return](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Freturn&data=04%7C01%7CFabian.Meiswinkel%40microsoft.com%7Ce1f69e233c1846341dae08da1400f3c2%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637844292196360477%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=jbUIpWFfffg4BzdR9SZ2MMciAEXvaA1L%2FNnHBq%2B0eY8%3D&reserved=0) String return the CONSUMER_ID
*/
public String getCONSUMER_ID() {
return CONSUMER_ID;
}
/**
 * @param CONSUMER_ID the CONSUMER_ID to set
 */
public void setCONSUMER_ID(String CONSUMER_ID) {
    this.CONSUMER_ID = CONSUMER_ID;
}
```


https://dzone.com/articles/jackson-property-custom-naming-strategy
