### ISSUE TITLE
[BUG] Azure Key Vault integration in Spring Cloud Azure 4.0 fails when using only 1 KV with error "Could not resolve placeholder"

### ISSUE THREAD

**Issue by ezYakaEagle442** [Azure/azure-sdk-for-java#28128]
**Describe the bug**

The config below is the one officially [documented](https://microsoft.github.io/spring-cloud-azure/docs/4.0.0-beta.2/reference/html/index.html#one-property-source) and did causes the Spring Boot App to fails to start as it failed to fetch the secrets from Azure KV..

```sh
spring:
  cloud:
    azure:
      profile:
        tenant-id: ${AZURE_TENANT_ID}
      credential:
        client-id: ${AZURE_CLIENT_ID}
        client-secret: ${AZURE_CLIENT_SECRET}
      keyvault:
        secret:
          property-source-enabled: true
          endpoint: ${AZURE_KEYVAULT_ENDPOINT}
```

The only syntax which works is the Multiple property source, even in my case where I use only 1 KV : 
```sh
spring:
  cloud:
    azure:
      keyvault:
        secret:
          property-sources:
            - credential:
                client-id: ${AZURE_CLIENT_ID}
                client-secret: ${AZURE_CLIENT_SECRET}
              endpoint: ${ENDPOINT}
              profile:
                tenant-id: ${AZURE_TENANT_ID}
```

***Exception or Stack Trace***
Add the exception log and stack trace if available

```console
2022-04-08 18:32:09.314  INFO 56288 --- [           main] c.e.a.s.k.s.sample.SampleApplication     : The following 1 profile is active: "az"
2022-04-08 18:32:10.367  INFO 56288 --- [           main] o.s.cloud.context.scope.GenericScope     : BeanFactory id=ca3d1145-04b2-3af8-86f3-3476a8a5dc22
2022-04-08 18:32:11.151  INFO 56288 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
2022-04-08 18:32:11.151  INFO 56288 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2022-04-08 18:32:11.151  INFO 56288 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.60]
2022-04-08 18:32:11.246  INFO 56288 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2022-04-08 18:32:11.246  INFO 56288 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 1906 ms
2022-04-08 18:32:11.482  WARN 56288 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sampleApplication': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'FOO' in value "${FOO}"
2022-04-08 18:32:11.497  INFO 56288 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2022-04-08 18:32:11.513  INFO 56288 --- [           main] ConditionEvaluationReportLoggingListener :

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2022-04-08 18:32:11.544 ERROR 56288 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sampleApplication': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'FOO' in value "${FOO}"
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:405) ~[spring-beans-5.3.18.jar!/:5.3.18]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1431) ~[spring-beans-5.3.18.jar!/:5.3.18]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619) ~[spring-beans-5.3.18.jar!/:5.3.18]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.18.jar!/:5.3.18]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.18.jar!/:5.3.18]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.18.jar!/:5.3.18]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.18.jar!/:5.3.18]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.18.jar!/:5.3.18]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953) ~[spring-beans-5.3.18.jar!/:5.3.18]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.18.jar!/:5.3.18]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.18.jar!/:5.3.18]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[spring-boot-2.6.6.jar!/:2.6.6]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:740) ~[spring-boot-2.6.6.jar!/:2.6.6]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:415) ~[spring-boot-2.6.6.jar!/:2.6.6]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) ~[spring-boot-2.6.6.jar!/:2.6.6]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1312) ~[spring-boot-2.6.6.jar!/:2.6.6]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1301) ~[spring-boot-2.6.6.jar!/:2.6.6]
        at com.example.azure.spring.keyvault.secrets.sample.SampleApplication.main(SampleApplication.java:27) ~[classes!/:1.0.0]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[spring-cloud-azure-starter-keyvault-secrets-sample-single-property-source-1.0.0.jar:1.0.0]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[spring-cloud-azure-starter-keyvault-secrets-sample-single-property-source-1.0.0.jar:1.0.0]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[spring-cloud-azure-starter-keyvault-secrets-sample-single-property-source-1.0.0.jar:1.0.0]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[spring-cloud-azure-starter-keyvault-secrets-sample-single-property-source-1.0.0.jar:1.0.0]
Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'FOO' in value "${FOO}"
        at org.springframework.util.PropertyPlaceholderHelper.parseStringValue(PropertyPlaceholderHelper.java:180) ~[spring-core-5.3.18.jar!/:5.3.18]
        at org.springframework.util.PropertyPlaceholderHelper.replacePlaceholders(PropertyPlaceholderHelper.java:126) ~[spring-core-5.3.18.jar!/:5.3.18]
        at org.springframework.core.env.AbstractPropertyResolver.doResolvePlaceholders(AbstractPropertyResolver.java:239) ~[spring-core-5.3.18.jar!/:5.3.18]
        at org.springframework.core.env.AbstractPropertyResolver.resolveRequiredPlaceholders(AbstractPropertyResolver.java:210) ~[spring-core-5.3.18.jar!/:5.3.18]
        at org.springframework.context.support.PropertySourcesPlaceholderConfigurer.lambda$processProperties$0(PropertySourcesPlaceholderConfigurer.java:191) ~[spring-context-5.3.18.jar!/:5.3.18]
        at org.springframework.beans.factory.support.AbstractBeanFactory.resolveEmbeddedValue(AbstractBeanFactory.java:936) ~[spring-beans-5.3.18.jar!/:5.3.18]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1330) ~[spring-beans-5.3.18.jar!/:5.3.18]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1309) ~[spring-beans-5.3.18.jar!/:5.3.18]
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:656) ~[spring-beans-5.3.18.jar!/:5.3.18]
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:639) ~[spring-beans-5.3.18.jar!/:5.3.18]
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119) ~[spring-beans-5.3.18.jar!/:5.3.18]
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399) ~[spring-beans-5.3.18.jar!/:5.3.18]
        ... 25 common frames omitted
```

**To Reproduce**

clone my repo [https://github.com/ezYakaEagle442/spring-cloud-az-kv](https://github.com/ezYakaEagle442/spring-cloud-az-kv)

mvn clean package -DskipTests
java -jar .\target\spring-cloud-azure-starter-keyvault-secrets-sample-single-property-source-1.0.0.jar --spring.profiles.active=azure

***Code Snippet***
The config below is the one officially [documented](https://microsoft.github.io/spring-cloud-azure/docs/4.0.0-beta.2/reference/html/index.html#one-property-source) and did causes the issue.

```sh
spring:
  cloud:
    azure:
      profile:
        tenant-id: ${AZURE_TENANT_ID}
      credential:
        client-id: ${AZURE_CLIENT_ID}
        client-secret: ${AZURE_CLIENT_SECRET}
      keyvault:
        secret:
          property-source-enabled: true
          endpoint: ${AZURE_KEYVAULT_ENDPOINT}
```

**Expected behavior**
The secrets should be fetched KV and should be successfully injected in the App.

**Screenshots**

**Setup (please complete the following information):**
 - OS:  Windows 11
 - IDE: [e.g. IntelliJ] VS
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)]
 - Java version:  11
 - App Server/Environment: SpringBoot/Tomcat
 - Frameworks: [e.g. Spring Boot] 

**Additional context**

**Information Checklist**

- [ X] Bug Description Added
- [ X] Repro Steps Added
- [ X] Setup information Added

**Comment by stliu** [comment]
There are couple issue in the sample, and I have created a PR https://github.com/ezYakaEagle442/spring-cloud-az-kv/pull/1 to fix it, with this change, the sample works fine

@ezYakaEagle442 would you please give it a try and confirm, thanks

**Comment by stliu** [comment]
though there is one thing I'd like to discuss @saragluna  @chenrujun 

it seems this properties work
```
spring:
  cloud:
    azure:
      keyvault:
        secret:
          property-sources:
              - endpoint: ${AZURE_KV_ENDPOINT}
```

but this one doesn't active the property source integration

```
spring:
  cloud:
    azure:
      keyvault:
        secret:
             endpoint: ${AZURE_KV_ENDPOINT}
```

is this expect? if so, is this the same behavior as 3.x?

**Comment by chenrujun** [comment]
@stliu 

> is this expect?

Yes, it is expected. And this is documented in the [4.0.0 reference doc](https://microsoft.github.io/spring-cloud-azure/4.0.0/reference/html/index.html#configuration-properties) and [CHNAGELOG](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/spring/CHANGELOG.md#spring-cloud-azure-autoconfigure). 

> if so, is this the same behavior as 3.x?

No. A lot of things changed from 3.x to 4.0. For examples:
1. Property prefix changed from `azure.keyvault` to `spring.cloud.azure.keyvault`.
2. Added a new feature about configure `SecretClient`. And use different property prefix to config `SecretClient` and property-source: Use `spring.cloud.azure.keyvault.secret.xxx` to config `SecretClient` and use `spring.cloud.azure.keyuvault.secret.property-sources.xxx` to config property-source.
3. Delete property of `azure.keyvault.order`. Use the order in the definition. It's documented in the [reference doc](https://microsoft.github.io/spring-cloud-azure/4.0.0/reference/html/index.html#propertysource-priority).

**Comment by stliu** [comment]
```
spring:
  cloud:
    azure:
      profile:
        tenant-id: ${AZURE_TENANT_ID}
      credential:
        client-id: ${AZURE_CLIENT_ID}
        client-secret: ${AZURE_CLIENT_SECRET}
      keyvault:
        secret:
          property-source-enabled: true
          endpoint: ${AZURE_KEYVAULT_ENDPOINT}
```

This should be valid and expected usage for 1 KV scenario.

@saragluna we should plan a fix for this bug

**Comment by chenrujun** [comment]
Hi, @ezYakaEagle442 

1. For endpoint property:
```java
    @Value("${spring.cloud.azure.keyvault.secret.property-sources[].endpoint}")
    private String kvEndpoint;
```
Change `property-sources[]` to `property-sources[0]` will fix the problem.

2. For other properties:
```java
    @Value("${spring.cloud.azure.keyvault.secret.property-sources[].credential.client-id}")
    private String kvClientId;

    @Value("${spring.cloud.azure.keyvault.secret.property-sources[].credential.client-secret}")
    private String kvClientSecret;

    @Value("${spring.cloud.azure.keyvault.secret.property-sources[].profile.tenant-id}")
    private String kvTenantId;
```

2.1. If you are using [the sample project](https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_v4.0.0/keyvault/spring-cloud-azure-starter-keyvault-secrets/property-source) and not configure these properties in your application.yml, then even if we change `property-sources[]` to `property-sources[0]`, the problem can not be fixed. Because these properties are not configured. The sample use Azure CLI to authenticate instead of `client-id` and `client-secret`. Refs: [defaultazurecredential](https://microsoft.github.io/spring-cloud-azure/4.0.0/reference/html/index.html#defaultazurecredential)

2.2. If you configured these properties in your application.yml, then change `property-sources[]` to `property-sources[0]` will fix the problem
