### ISSUE TITLE
TokenCredential is not supported to configure in ShareServiceClientBuilder (spring-cloud-azure 4.0.0)

### ISSUE THREAD

**Issue by ctalpandey** [Azure/azure-sdk-for-java#28445]
With Spring-cloud-azure 4.0.0, Storage Blob/Queue are getting authenticated with service-principal having roles Storage Blob/Queue Data Contributor. However, it's not successful/supported with Storage File-Share though service principal has Storage File Data SMB Share Contributor role. Refer below details

Application.yml is as below:
```
spring:
  cloud:
    azure:
      profile:
        tenant-id: ${AZURE_TENANT_ID}
      credential:
        client-id: ${AZURE_CLIENT_ID}
        client-secret: ${AZURE_CLIENT_SECRET}
      storage:
        queue:
          account-name: "${AZURE_STORAGE_QUEUE_ACCOUNT_NAME}"
        fileshare:
          account-name: "${AZURE_STORAGE_FILESHARE_ACCOUNT_NAME}"
        blob:
          account-name: "${AZURE_STORAGE_BLOB_ACCOUNT_NAME}"
```
Below is the error:

```
2022-04-21 22:38:38.283  WARN 43556 --- [           main] AbstractAzureStorageClientBuilderFactory : The retry in a storage client builder is of type com.azure.spring.cloud.core.properties.retry.RetryProperties
2022-04-21 22:38:38.643  INFO 43556 --- [           main] c.a.s.m.s.q.core.StorageQueueTemplate    : StorageQueueTemplate started with default properties {messagePayloadType=class [B}
2022-04-21 22:38:38.740  INFO 43556 --- [           main] AbstractAzureServiceClientBuilderFactory : Will configure the default credential of type DefaultAzureCredential for class com.azure.identity.ClientSecretCredentialBuilder.
2022-04-21 22:38:38.972  INFO 43556 --- [           main] AbstractAzureServiceClientBuilderFactory : Will configure the default credential of type ClientSecretCredential for class com.azure.storage.file.share.ShareServiceClientBuilder.
2022-04-21 22:38:38.973  WARN 43556 --- [           main] s.i.s.f.ShareServiceClientBuilderFactory : TokenCredential is not supported to configure in ShareServiceClientBuilder.
2022-04-21 22:38:38.979 ERROR 43556 --- [           main] c.a.s.f.share.ShareServiceClientBuilder  : Credentials are required for authorization
2022-04-21 22:38:38.982  WARN 43556 --- [           main] s.c.a.AnnotationConfigApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shareServiceClient' defined in class path resource [com/azure/spring/cloud/autoconfigure/storage/fileshare/AzureStorageFileShareAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.azure.storage.file.share.ShareServiceClient]: Factory method 'shareServiceClient' threw exception; nested exception is java.lang.IllegalArgumentException: Credentials are required for authorization
2022-04-21 22:38:39.003  INFO 43556 --- [           main] ConditionEvaluationReportLoggingListener :

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2022-04-21 22:38:39.061 ERROR 43556 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shareServiceClient' defined in class path resource [com/azure/spring/cloud/autoconfigure/storage/fileshare/AzureStorageFileShareAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.azure.storage.file.share.ShareServiceClient]: Factory method 'shareServiceClient' threw exception; nested exception is java.lang.IllegalArgumentException: Credentials are required for authorization
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:658) ~[spring-beans-5.3.16.jar:5.3.16]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:638) ~[spring-beans-5.3.16.jar:5.3.16]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352) ~[spring-beans-5.3.16.jar:5.3.16]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195) ~[spring-beans-5.3.16.jar:5.3.16]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582) ~[spring-beans-5.3.16.jar:5.3.16]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.16.jar:5.3.16]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.16.jar:5.3.16]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.16.jar:5.3.16]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.16.jar:5.3.16]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.16.jar:5.3.16]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953) ~[spring-beans-5.3.16.jar:5.3.16]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.16.jar:5.3.16]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.16.jar:5.3.16]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:740) [spring-boot-2.6.4.jar:2.6.4]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:415) [spring-boot-2.6.4.jar:2.6.4]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) [spring-boot-2.6.4.jar:2.6.4]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1312) [spring-boot-2.6.4.jar:2.6.4]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1301) [spring-boot-2.6.4.jar:2.6.4]
        at com.boeing.fda.cplparser.CplParserApplication.main(CplParserApplication.java:20) [classes/:na]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.azure.storage.file.share.ShareServiceClient]: Factory method 'shareServiceClient' threw exception; nested exception is java.lang.IllegalArgumentException: Credentials are required for authorization
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.3.16.jar:5.3.16]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653) ~[spring-beans-5.3.16.jar:5.3.16]
        ... 18 common frames omitted
Caused by: java.lang.IllegalArgumentException: Credentials are required for authorization
        at com.azure.storage.file.share.ShareServiceClientBuilder.lambda$buildAsyncClient$0(ShareServiceClientBuilder.java:195) ~[azure-storage-file-share-12.12.0.jar:12.12.0]
        at com.azure.storage.file.share.implementation.util.BuilderHelper.buildPipeline(BuilderHelper.java:93) ~[azure-storage-file-share-12.12.0.jar:12.12.0]
        at com.azure.storage.file.share.ShareServiceClientBuilder.buildAsyncClient(ShareServiceClientBuilder.java:187) ~[azure-storage-file-share-12.12.0.jar:12.12.0]
        at com.azure.storage.file.share.ShareServiceClientBuilder.buildClient(ShareServiceClientBuilder.java:229) ~[azure-storage-file-share-12.12.0.jar:12.12.0]
        at com.azure.spring.cloud.autoconfigure.storage.fileshare.AzureStorageFileShareAutoConfiguration.shareServiceClient(AzureStorageFileShareAutoConfiguration.java:61) ~[spring-cloud-azure-autoconfigure-4.0.0.jar:4.0.0]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_282]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_282]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_282]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_282]
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.3.16.jar:5.3.16]
        ... 19 common frames omitted
```
Is TokenCredential not temporarily supported for ShareServiceClientBuilder? Is there any plan to support in near future?

**Comment by backwind1233** [comment]
@ctalpandey
Thanks for reaching us, Storage File doesn't support tokenCredential, in [sdk](https://docs.microsoft.com/en-us/java/api/overview/azure/storage-file-share-readme?view=azure-java-stable#get-credentials) side it supports SAS Token and Shared Key Credential, you can configure like below

```
spring:
  cloud:
    azure:
      storage:
        fileshare:
          account-name: ${STORAGE_ACCOUNT_NAME}
          account-key: ${STORAGE_ACCOUNT_KEY}
          endpoint:  ${STORAGE_FILESHARE_ENDPOINT}
```

**Comment by ctalpandey** [comment]
Thanks for quick reply. Is there any plan to support tokenCredential anytime soon? Or, probably not in short future due to any technical reason.

**Comment by backwind1233** [comment]
> Thanks for quick reply. Is there any plan to support tokenCredential anytime soon? Or, probably not in short future due to any technical reason.

Hi @ctalpandey, since Azure Files supports authorization [with Azure AD over SMB for domain-joined VMs only](https://docs.microsoft.com/en-us/azure/storage/files/storage-files-active-directory-overview), I am not sure whether the service side will support AAD in the future. 
If the service side support AAD, we will support tokenCredential.

**Comment by ctalpandey** [comment]
Thanks for the reply.  I have no further queries; closing issue from my side.
