### ISSUE TITLE
[BUG] AzureTokenCredentialAutoConfiguration fails with multiple ThreadPoolTaskExecutors

### ISSUE THREAD

**Issue by nioertel** [Azure/azure-sdk-for-java#28525]
**Describe the bug**
If there are multiple `ThreadPoolTaskExecutor`s in the Spring application context, the `AzureTokenCredentialAutoConfiguration` fails because `threadPoolTaskExecutors.ifAvailable(tpe -> factory.setExecutorService(tpe.getThreadPoolExecutor()));` expects that there is not more than one or if there are, one of them is marked as `@Primary`.

***Exception or Stack Trace***

```bash
[2022-04-25T14:44:49.319Z] Caused by: org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type 'org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor' available: expected single matching bean but found 2: taskExecutor1,taskExecutor2
  at org.springframework.beans.factory.config.DependencyDescriptor.resolveNotUnique(DependencyDescriptor.java:220) ~[spring-beans-5.3.19.jar:5.3.19]
  at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1367) ~[spring-beans-5.3.19.jar:5.3.19]
  at org.springframework.beans.factory.support.DefaultListableBeanFactory$DependencyObjectProvider.getIfAvailable(DefaultListableBeanFactory.java:2030) ~[spring-beans-5.3.19.jar:5.3.19]
  at org.springframework.beans.factory.support.DefaultListableBeanFactory$DependencyObjectProvider.ifAvailable(DefaultListableBeanFactory.java:2041) ~[spring-beans-5.3.19.jar:5.3.19]
  at com.azure.spring.cloud.autoconfigure.context.AzureTokenCredentialAutoConfiguration.azureCredentialBuilderFactory(AzureTokenCredentialAutoConfiguration.java:74) ~[spring-cloud-azure-autoconfigure-4.0.0.jar:4.0.0]
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
  ...
```

**To Reproduce**
Create Spring Boot Application with two `ThreadPoolTaskExecutor` and Azure Spring Cloud (e.g. Key Vault Secrets enabled).

***Code Snippet***
```java
  @Bean
  public ThreadPoolTaskExecutor threadPoolTaskExecutor1() {
    ThreadPoolTaskExecutor executor = new ThreadPoolTaskExecutor();
    executor.setMaxPoolSize(10);
    executor.setCorePoolSize(10);
    executor.initialize();
    return executor;
  }

  @Bean
  public ThreadPoolTaskExecutor threadPoolTaskExecutor2() {
    ThreadPoolTaskExecutor executor = new ThreadPoolTaskExecutor();
    executor.setMaxPoolSize(10);
    executor.setCorePoolSize(10);
    executor.initialize();
    return executor;
  }
```

**Expected behavior**
If there are more than 1 `ThreadPoolTaskExecutor`s, the auto configuration should skip setting one in the `DefaultAzureCredentialBuilderFactory`. Simple solution would be to replace `threadPoolTaskExecutors.ifAvailable` by `threadPoolTaskExecutors.ifUnique`.

**Setup (please complete the following information):**
 - OS: any
 - IDE: any
 - Library/Libraries: Spring Boot 2.6.7, `com.azure.spring:spring-cloud-azure-autoconfigure:4.0.0`
 - Java version: 11
 - App Server/Environment: Simple Spring Boot App
 - Frameworks: Spring Boot

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by joshfree** [comment]
Hi @nioertel thank you for reaching out to us via this GitHub issue.  Someone from the Azure Spring team will follow up shortly.

/cc @saragluna

**Comment by saragluna** [comment]
The change will go out in 4.1.0 later this month.
