### ISSUE TITLE
[BUG] Failed to Fetch Secrets from Key Vault using Java SDK when run from Azure Pipelines

### ISSUE THREAD

**Issue by abhishekd0907** [Azure/azure-sdk-for-java#28527]
**Describe the bug**
An exception occurs in fetching secrets while using Azure Pipelines. Works fine on WSL and Windows Gitbah,

***Exception or Stack Trace***
```
	2022-04-20T15:57:43.2014411Z 2022-04-20 15:57:43,200 WARN  [Thread-7] secrets.SecretAsyncClient: Failed to get secret - SynapseServicePrincipalKey
2022-04-20T15:57:43.2015946Z Max retries 3 times exceeded. Error Details: Structure.getFieldOrder() on class com.azure.identity.implementation.LinuxKeyRingAccessor$GError returns names ([code, domain, message]) which do not match declared field names ([])
2022-04-20T15:57:43.2051491Z Autoscale Tests Runner failed. Printing stack trace
2022-04-20T15:57:43.2058100Z java.lang.RuntimeException: Max retries 3 times exceeded. Error Details: Structure.getFieldOrder() on class com.azure.identity.implementation.LinuxKeyRingAccessor$GError returns names ([code, domain, message]) which do not match declared field names ([])
2022-04-20T15:57:43.2069926Z 	at com.azure.core.http.policy.RetryPolicy.lambda$attemptAsync$1(RetryPolicy.java:127)
2022-04-20T15:57:43.2071318Z 	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:88)
2022-04-20T15:57:43.2072246Z 	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:165)
2022-04-20T15:57:43.2080897Z 	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:165)
2022-04-20T15:57:43.2081941Z 	at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondError(MonoFlatMap.java:185)
2022-04-20T15:57:43.2082826Z 	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onError(MonoFlatMap.java:251)
2022-04-20T15:57:43.2084085Z 	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onError(MonoPeekTerminal.java:251)
2022-04-20T15:57:43.2085161Z 	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onError(MonoPeekTerminal.java:251)
2022-04-20T15:57:43.2086120Z 	at reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onError(FluxPeekFuseable.java:894)
2022-04-20T15:57:43.2087077Z 	at reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onError(FluxPeekFuseable.java:894)
2022-04-20T15:57:43.2088206Z 	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onError(Operators.java:2021)
2022-04-20T15:57:43.2089463Z 	at reactor.core.publisher.MonoNext$NextSubscriber.onError(MonoNext.java:87)
2022-04-20T15:57:43.2090311Z 	at reactor.core.publisher.FluxFlatMap$FlatMapMain.checkTerminated(FluxFlatMap.java:834)
2022-04-20T15:57:43.2091128Z 	at reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:600)
2022-04-20T15:57:43.2092031Z 	at reactor.core.publisher.FluxFlatMap$FlatMapMain.innerComplete(FluxFlatMap.java:909)
2022-04-20T15:57:43.2092789Z 	at reactor.core.publisher.FluxFlatMap$FlatMapInner.onComplete(FluxFlatMap.java:1013)
2022-04-20T15:57:43.2093620Z 	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onComplete(Operators.java:2016)
2022-04-20T15:57:43.2094376Z 	at reactor.core.publisher.Operators.complete(Operators.java:135)
2022-04-20T15:57:43.2095074Z 	at reactor.core.publisher.MonoEmpty.subscribe(MonoEmpty.java:45)
2022-04-20T15:57:43.2095726Z 	at reactor.core.publisher.Mono.subscribe(Mono.java:4213)
2022-04-20T15:57:43.2097501Z 	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:97)
2022-04-20T15:57:43.2098510Z 	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onError(FluxPeekFuseable.java:227)
2022-04-20T15:57:43.2099651Z 	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onError(MonoPeekTerminal.java:251)
2022-04-20T15:57:43.2100415Z 	at reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onError(FluxPeekFuseable.java:894)
2022-04-20T15:57:43.2101135Z 	at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onError(FluxMap.java:252)
2022-04-20T15:57:43.2102098Z 	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onError(Operators.java:2021)
2022-04-20T15:57:43.2102812Z 	at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondError(MonoFlatMap.java:185)
2022-04-20T15:57:43.2103451Z 	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onError(MonoFlatMap.java:251)
2022-04-20T15:57:43.2104103Z 	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:135)
2022-04-20T15:57:43.2104762Z 	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:73)
2022-04-20T15:57:43.2105446Z 	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1782)
2022-04-20T15:57:43.2106265Z 	at reactor.core.publisher.MonoCompletionStage.lambda$subscribe$0(MonoCompletionStage.java:86)
2022-04-20T15:57:43.2106973Z 	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
2022-04-20T15:57:43.2107672Z 	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
2022-04-20T15:57:43.2108395Z 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
2022-04-20T15:57:43.2109891Z 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1705)
2022-04-20T15:57:43.2110565Z 	at java.base/java.lang.Thread.run(Thread.java:829)
2022-04-20T15:57:43.2111152Z 	Suppressed: java.lang.Exception: #block terminated with an error
2022-04-20T15:57:43.2111791Z 		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
2022-04-20T15:57:43.2112404Z 		at reactor.core.publisher.Mono.block(Mono.java:1680)
2022-04-20T15:57:43.2113034Z 		at com.azure.security.keyvault.secrets.SecretClient.getSecretWithResponse(SecretClient.java:171)
2022-04-20T15:57:43.2113713Z 		at com.azure.security.keyvault.secrets.SecretClient.getSecret(SecretClient.java:150)
2022-04-20T15:57:43.2114415Z 		at com.microsoft.spark.perf.util.keyvault.KeyVaultAccessor.accessSecret(KeyVaultAccessor.scala:19)
2022-04-20T15:57:43.2115136Z 		at ms.autoscale.AutoscaleTestsRunner.fetchSecretsFromKeyVault(AutoscaleTestsRunner.scala:76)
2022-04-20T15:57:43.2115811Z 		at ms.autoscale.AutoscaleTestsRunner.run(AutoscaleTestsRunner.scala:33)
2022-04-20T15:57:43.2116419Z 		at ms.autoscale.AutoscaleTestsRunner$.main(AutoscaleTestsRunner.scala:202)
2022-04-20T15:57:43.2117012Z 		at ms.autoscale.AutoscaleTestsRunner.main(AutoscaleTestsRunner.scala)
2022-04-20T15:57:43.2117566Z 		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-04-20T15:57:43.2118218Z 		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2022-04-20T15:57:43.2118943Z 		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-04-20T15:57:43.2119596Z 		at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2022-04-20T15:57:43.2120220Z 		at scala.reflect.internal.util.ScalaClassLoader$$anonfun$run$1.apply(ScalaClassLoader.scala:70)
2022-04-20T15:57:43.2120958Z 		at scala.reflect.internal.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
2022-04-20T15:57:43.2121824Z 		at scala.reflect.internal.util.ScalaClassLoader$URLClassLoader.asContext(ScalaClassLoader.scala:101)
2022-04-20T15:57:43.2122593Z 		at scala.reflect.internal.util.ScalaClassLoader$class.run(ScalaClassLoader.scala:70)
2022-04-20T15:57:43.2123320Z 		at scala.reflect.internal.util.ScalaClassLoader$URLClassLoader.run(ScalaClassLoader.scala:101)
2022-04-20T15:57:43.2124017Z 		at scala.tools.nsc.CommonRunner$class.run(ObjectRunner.scala:22)
2022-04-20T15:57:43.2136685Z 		at scala.tools.nsc.ObjectRunner$.run(ObjectRunner.scala:39)
2022-04-20T15:57:43.2137212Z 		at scala.tools.nsc.CommonRunner$class.runAndCatch(ObjectRunner.scala:29)
2022-04-20T15:57:43.2137683Z 		at scala.tools.nsc.ObjectRunner$.runAndCatch(ObjectRunner.scala:39)
2022-04-20T15:57:43.2138176Z 		at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:65)
2022-04-20T15:57:43.2138870Z 		at scala.tools.nsc.MainGenericRunner.run$1(MainGenericRunner.scala:87)
2022-04-20T15:57:43.2139352Z 		at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:98)
2022-04-20T15:57:43.2139849Z 		at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:103)
2022-04-20T15:57:43.2140282Z 		at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
2022-04-20T15:57:43.2153765Z Caused by: java.lang.Error: Structure.getFieldOrder() on class com.azure.identity.implementation.LinuxKeyRingAccessor$GError returns names ([code, domain, message]) which do not match declared field names ([])
2022-04-20T15:57:43.2154431Z 	at com.sun.jna.Structure.getFields(Structure.java:1089)
2022-04-20T15:57:43.2154869Z 	at com.sun.jna.Structure.deriveLayout(Structure.java:1232)
2022-04-20T15:57:43.2155484Z 	at com.sun.jna.Structure.calculateSize(Structure.java:1159)
2022-04-20T15:57:43.2155926Z 	at com.sun.jna.Structure.calculateSize(Structure.java:1111)
2022-04-20T15:57:43.2156347Z 	at com.sun.jna.Structure.useMemory(Structure.java:350)
2022-04-20T15:57:43.2156967Z 	at com.sun.jna.Structure.<init>(Structure.java:202)
2022-04-20T15:57:43.2159125Z 	at com.sun.jna.Structure.<init>(Structure.java:193)
2022-04-20T15:57:43.2159585Z 	at com.sun.jna.Structure.<init>(Structure.java:189)
2022-04-20T15:57:43.2160094Z 	at com.azure.identity.implementation.LinuxKeyRingAccessor$GError.<init>(LinuxKeyRingAccessor.java:92)
2022-04-20T15:57:43.2160676Z 	at com.azure.identity.implementation.LinuxKeyRingAccessor.read(LinuxKeyRingAccessor.java:54)
2022-04-20T15:57:43.2161254Z 	at com.azure.identity.implementation.LinuxKeyRingAccessor.read(LinuxKeyRingAccessor.java:70)
2022-04-20T15:57:43.2161857Z 	at com.azure.identity.implementation.VisualStudioCacheAccessor.getCredentials(VisualStudioCacheAccessor.java:132)
2022-04-20T15:57:43.2162501Z 	at com.azure.identity.implementation.IdentityClient.authenticateWithVsCodeCredential(IdentityClient.java:628)
2022-04-20T15:57:43.2163136Z 	at com.azure.identity.VisualStudioCodeCredential.lambda$getToken$2(VisualStudioCodeCredential.java:79)
2022-04-20T15:57:43.2163678Z 	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44)
2022-04-20T15:57:43.2164117Z 	at reactor.core.publisher.Mono.subscribe(Mono.java:4213)
2022-04-20T15:57:43.2164631Z 	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FluxSwitchIfEmpty.java:75)
2022-04-20T15:57:43.2165175Z 	at reactor.core.publisher.Operators.complete(Operators.java:135)
2022-04-20T15:57:43.2165614Z 	at reactor.core.publisher.MonoEmpty.subscribe(MonoEmpty.java:45)
2022-04-20T15:57:43.2166067Z 	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
2022-04-20T15:57:43.2166488Z 	at reactor.core.publisher.Mono.subscribe(Mono.java:4213)
2022-04-20T15:57:43.2166942Z 	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:418)
2022-04-20T15:57:43.2167487Z 	at reactor.core.publisher.FluxIterable$IterableSubscription.slowPath(FluxIterable.java:267)
2022-04-20T15:57:43.2168045Z 	at reactor.core.publisher.FluxIterable$IterableSubscription.request(FluxIterable.java:225)
2022-04-20T15:57:43.2168909Z 	at reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:782)
2022-04-20T15:57:43.2169275Z 	... 23 more
```

**To Reproduce**
Code Snippet run from a java process is provided below. Java process runs fine in WSL / Windows gitbash but fails when run from
azure pipelines.

***Code Snippet***
Following Code is used to reproduce the issue
```
import com.azure.identity.DefaultAzureCredentialBuilder
import com.azure.security.keyvault.secrets.SecretClientBuilder

class KeyVaultAccessor(keyVaultUrl: String,
                       managedIdentityClient: String) {

  val credential = new DefaultAzureCredentialBuilder()
    .managedIdentityClientId(managedIdentityClient)
    .build()

  val client = new SecretClientBuilder()
    .vaultUrl(keyVaultUrl)
    .credential(credential)
    .buildClient()

  def accessSecret(secretName: String): String = {
    client.getSecret(secretName).getValue
  }

}
```
**Expected behavior**
Secrets should be fetched as they are fetched when running locally on WSL / Gitbash..

**Screenshots**
Not Applicable

**Setup (please complete the following information):**
Package the code I added above in a JAR file and run jar file from azure pipelines. I use the below azure pipelines config to run the jar using scala command.
```
trigger: 
- none

pool:
  vmImage: ubuntu-latest

steps:

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      sudo apt --assume-yes install scala 
      curl  -LO https://tpcdsperfsetup.blob.core.windows.net/perfsetup/autoscale-tests-1.0-SNAPSHOT.jar
      curl  -o config.json $(CONF_FILE_PATH)
      scala -classpath autoscale-tests-1.0-SNAPSHOT.jar ms.autoscale.AutoscaleTestsRunner config.json
  displayName: 'Run Autoscale Tests'
```

**Additional context**
Not applicable

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by joshfree** [comment]
Hi @abhishekd0907 thank you for reaching out to us via this GitHub issue.  @vcolin7 can you please follow up with @abhishekd0907?

**Comment by vcolin7** [comment]
Sure thing @joshfree, I will look into this tomorrow :)

**Comment by billwert** [comment]
@abhishekd0907 Can you also share what version of the SDK libraries you're using?

It's also worth noting that the `VSCodeCredential` comes after all of the managed identity credentials in the chain, so your managed identity wasn't properly configured. There should be error text higher up (but it isn't what stopped you) that indicated that. You'll need to resolve that before `ManagedIdentityCredential` will work for you.

**Comment by billwert** [comment]
Ah. I also just noticed this was Pipelines, not functions. In Pipelines, I do not think managed identity is configured by default. If you are using a [self-hosted VM instead of a pool VM](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/connect-to-azure?view=azure-devops#create-an-azure-resource-manager-service-connection-to-a-vm-with-a-managed-service-identity), you could use managed identity then.

In general, the way to get secrets into apps is by [injecting secrets directly from KeyVault](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/azure-key-vault?view=azure-devops). You authorize the pipeline to the KeyVault, then use those variables where you need them (perhaps as arguments.)

**Comment by abhishekd0907** [comment]
Thanks for your help @billwert  @joshfree and @vcolin7. Closing the issue
