### ISSUE TITLE
[BUG] azure-cosmos-spark_3-2_2-12: java.lang.IllegalStateException: No overlapping start token found for range 'NormalizedRange(,05C1C183E7E10808706D717472636367796C336C7777356565366C6472604570645466754264756A706F746035653562366563392E343667362E353A62312E623862312E36383131333936666738343200)'

### ISSUE THREAD

**Issue by michaelbpalmer** [Azure/azure-sdk-for-java#28628]
**Describe the bug**
Specifying spark.cosmos.partitioning.feedRangeFilter to readStream.format("cosmos.oltp.changeFeed") produces an exception: 

java.lang.IllegalStateException: No overlapping start token found for range 'NormalizedRange(,05C1C183E7E10808706D717472636367796C336C7777356565366C6472604570645466754264756A706F746035653562366563392E343667362E353A62312E623862312E36383131333936666738343200)'

This occurs on version 4.9.0 of azure-cosmos-spark_3-2_2-12 and is related to the fix for https://github.com/Azure/azure-sdk-for-java/issues/27758. The exception occurs after all of the existing data in the partition has been read from the change feed (I can see the  change feed output in my Spark table).

***Exception or Stack Trace***

22/05/03 17:29:54 ERROR MicroBatchExecution: Query CosmosDbDocSetChangeFeedSource [id = 7d7f99b8-a654-42ad-8ab6-01fcb7ffac77, runId = de222e16-455c-4c42-931a-3a1917c04e0a] terminated with error
java.lang.IllegalStateException: No overlapping start token found for range 'NormalizedRange(,05C1C183E7E10808706D717472636367796C336C7777356565366C6472604570645466754264756A706F746035653562366563392E343667362E353A62312E623862312E36383131333936666738343200)'.
        at com.azure.cosmos.spark.CosmosPartitionPlanner$.$anonfun$mergeStartAndLatestTokens$4(CosmosPartitionPlanner.scala:395)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
        at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
        at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
        at scala.collection.TraversableLike.map(TraversableLike.scala:286)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
        at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:198)
        at com.azure.cosmos.spark.CosmosPartitionPlanner$.mergeStartAndLatestTokens(CosmosPartitionPlanner.scala:391)
        at com.azure.cosmos.spark.CosmosPartitionPlanner$.getOrderedPartitionMetadataWithStartLsn(CosmosPartitionPlanner.scala:350)
        at com.azure.cosmos.spark.CosmosPartitionPlanner$.getLatestOffsetImpl(CosmosPartitionPlanner.scala:308)
        at com.azure.cosmos.spark.CosmosPartitionPlanner$.$anonfun$getLatestOffset$1(CosmosPartitionPlanner.scala:272)
        at com.azure.cosmos.spark.TransientErrorsRetryPolicy$.$anonfun$executeWithRetry$1(TransientErrorsRetryPolicy.scala:32)
        at scala.util.control.Breaks.breakable(Breaks.scala:42)
        at com.azure.cosmos.spark.TransientErrorsRetryPolicy$.executeWithRetry(TransientErrorsRetryPolicy.scala:26)
        at com.azure.cosmos.spark.CosmosPartitionPlanner$.getLatestOffset(CosmosPartitionPlanner.scala:261)
        at com.azure.cosmos.spark.ChangeFeedMicroBatchStream.latestOffset(ChangeFeedMicroBatchStream.scala:143)
        at org.apache.spark.sql.execution.streaming.MicroBatchExecution.$anonfun$constructNextBatch$3(MicroBatchExecution.scala:396)
        at org.apache.spark.sql.execution.streaming.ProgressReporter.reportTimeTaken(ProgressReporter.scala:375)
        at org.apache.spark.sql.execution.streaming.ProgressReporter.reportTimeTaken$(ProgressReporter.scala:373)
        at org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:69)
        at org.apache.spark.sql.execution.streaming.MicroBatchExecution.$anonfun$constructNextBatch$2(MicroBatchExecution.scala:387)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
        at scala.collection.Iterator.foreach(Iterator.scala:943)
        at scala.collection.Iterator.foreach$(Iterator.scala:943)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
        at scala.collection.IterableLike.foreach(IterableLike.scala:74)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
        at scala.collection.TraversableLike.map(TraversableLike.scala:286)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
        at scala.collection.AbstractTraversable.map(Traversable.scala:108)
        at org.apache.spark.sql.execution.streaming.MicroBatchExecution.$anonfun$constructNextBatch$1(MicroBatchExecution.scala:384)
        at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.java:23)
        at org.apache.spark.sql.execution.streaming.MicroBatchExecution.withProgressLocked(MicroBatchExecution.scala:627)
        at org.apache.spark.sql.execution.streaming.MicroBatchExecution.constructNextBatch(MicroBatchExecution.scala:380)
        at org.apache.spark.sql.execution.streaming.MicroBatchExecution.$anonfun$runActivatedStream$2(MicroBatchExecution.scala:210)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at org.apache.spark.sql.execution.streaming.ProgressReporter.reportTimeTaken(ProgressReporter.scala:375)
        at org.apache.spark.sql.execution.streaming.ProgressReporter.reportTimeTaken$(ProgressReporter.scala:373)
        at org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:69)
        at org.apache.spark.sql.execution.streaming.MicroBatchExecution.$anonfun$runActivatedStream$1(MicroBatchExecution.scala:193)
        at org.apache.spark.sql.execution.streaming.ProcessingTimeExecutor.execute(TriggerExecutor.scala:57)
        at org.apache.spark.sql.execution.streaming.MicroBatchExecution.runActivatedStream(MicroBatchExecution.scala:187)
        at org.apache.spark.sql.execution.streaming.StreamExecution.$anonfun$runStream$1(StreamExecution.scala:303)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
        at org.apache.spark.sql.execution.streaming.StreamExecution.org$apache$spark$sql$execution$streaming$StreamExecution$$runStream(StreamExecution.scala:286)
        at org.apache.spark.sql.execution.streaming.StreamExecution$$anon$1.run(StreamExecution.scala:209)

**To Reproduce**

Perform a streaming read from cosmos.oltp.changeFeed providing a feedRangeFilter to a streaming write (see code for details).

***Code Snippet***

    spark.udf.registerJavaFunction(
        "get_feedrange_for_partition_key_value",
        "com.azure.cosmos.spark.udf.GetFeedRangeForPartitionKeyValue",
        StringType(),
    )
    feed_range_filter_df = spark.sql(
        f"SELECT get_feedrange_for_partition_key_value('{PK_DEFINITION}', '{pk_value}')"
    )
    feed_range_filter = str(feed_range_filter_df.collect()[0][0])

    df = (
        spark.readStream.format("cosmos.oltp.changeFeed")
        .option("spark.cosmos.accountEndpoint", db_uri)
        .option("spark.cosmos.accountKey", db_key)
        .option("spark.cosmos.database", "DbName")
        .option("spark.cosmos.container", "Container")
        .option("spark.cosmos.partitioning.feedRangeFilter", feed_range_filter)
        .option("spark.cosmos.read.partitioning.strategy", "Restrictive")
        .option("spark.cosmos.read.inferSchema.enabled", False)
        .load()
    )

    writer = (
        df.writeStream.queryName(query_name)
        .format("delta")
        .option("checkpointLocation", checkpoint_location)
    )

    writer.start(table_path)

**Expected behavior**
No exceptions. The streaming query to continue running waiting for new data.

**Setup (please complete the following information):**
 - OS: [e.g. iOS] Debian Slim
 - IDE: [e.g. IntelliJ] VS Code
 - Library/Libraries: azure-cosmos-spark_3-2_2-12: 4.9.0
 - Java version: openjdk 11
 - App Server/Environment: Apache Spark 3.2.1

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by michaelbpalmer** [comment]
@FabianMeiswinkel, if there is any workaround that I can do to avoid this (while still using feedRange), please let me know. We are anxious to be able to use this in our production environment and this is our last blocker.

**Comment by FabianMeiswinkel** [comment]
@michaelbpalmer - I have been able to reproduce and have a PR out with a fix (and adding test coverage for your scenario to prevent any regressions in the future) - https://github.com/Azure/azure-sdk-for-java/pull/29338 - next release with version higher than 4.11.0 will have the fix - let me know if you need a private to test

**Comment by FabianMeiswinkel** [comment]
Version 4.11.1 containing the hotfix has been published to Maven
