### ISSUE TITLE
[BUG] BlobNotFound when deleting blobs from multithreading 

### ISSUE THREAD

**Issue by ierandra** [Azure/azure-sdk-for-java#28639]
**Describe the bug**
When trying to list and delete blobs from multiple threads the second thread always fails to delete the blob with Message `BlobNotFound` 

Notes:
- blobs is present.
- we don't have different process thats "modifying"/working with the blob that we try to delete.

***Exception or Stack Trace***
```
12:39:03.289 [ForkJoinPool-1-worker-27] INFO com.adobe.granite.client.azure.CodeSnippet - Trying to delete blob: 03-blob
12:39:03.546 [ForkJoinPool-1-worker-27] INFO com.adobe.granite.client.azure.CodeSnippet - Trying to delete blob: 03-blob with version: 2022-05-06T09:38:10.8284819Z
12:39:03.819 [ForkJoinPool-1-worker-5] INFO com.adobe.granite.client.azure.CodeSnippet - Trying to delete blob: 01-blob
12:39:04.046 [ForkJoinPool-1-worker-5] ERROR com.adobe.granite.client.azure.CodeSnippet - Error deleting blob 01-blob version 2022-05-06T09:38:10.8604626Z
com.azure.storage.blob.models.BlobStorageException: Status code 404, "﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>BlobNotFound</Code><Message>The specified blob does not exist.
RequestId:c82f69b9-701e-00fb-6b2d-61d908000000
Time:2022-05-06T09:39:04.1176061Z</Message></Error>"
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.azure.core.http.rest.RestProxy.instantiateUnexpectedException(RestProxy.java:337)
	at com.azure.core.http.rest.RestProxy.lambda$ensureExpectedStatus$5(RestProxy.java:376)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:125)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1815)
	at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.signalCached(MonoCacheTime.java:328)
	at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.onNext(MonoCacheTime.java:345)
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2397)
	at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.onSubscribe(MonoCacheTime.java:284)
	at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:191)
	at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at reactor.core.publisher.MonoCacheTime.subscribeOrReturn(MonoCacheTime.java:134)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:130)
	at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:118)
	at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:220)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:130)
	at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:184)
	at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1815)
	at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:128)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:259)
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:142)
	at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:389)
	at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:396)
	at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:452)
	at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:684)
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:94)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1533)
	at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1294)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1331)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:508)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:447)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.kqueue.AbstractKQueueStreamChannel$KQueueStreamUnsafe.readReady(AbstractKQueueStreamChannel.java:544)
	at io.netty.channel.kqueue.AbstractKQueueChannel$AbstractKQueueUnsafe.readReady(AbstractKQueueChannel.java:382)
	at io.netty.channel.kqueue.KQueueEventLoop.processReady(KQueueEventLoop.java:211)
	at io.netty.channel.kqueue.KQueueEventLoop.run(KQueueEventLoop.java:289)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
		at reactor.core.publisher.Mono.block(Mono.java:1703)
		at com.azure.storage.common.implementation.StorageImplUtils.blockWithOptionalTimeout(StorageImplUtils.java:131)
		at com.azure.storage.blob.specialized.BlobClientBase.deleteWithResponse(BlobClientBase.java:949)
		at com.azure.storage.blob.specialized.BlobClientBase.delete(BlobClientBase.java:920)
		at com.adobe.granite.client.azure.CodeSnippet.deleteBlobsAndVersion(CodeSnippet.java:48)
		at com.adobe.granite.client.azure.CodeSnippet.lambda$listAndDelete$0(CodeSnippet.java:72)
		at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
		at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
		at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
		at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
		at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
		at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
		at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
		at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
		at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
		at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**To Reproduce**
1. Create a storage account 
2. Enable versioning for the storage account
3. Add a container
4. In the container upload blobs with following names:
```
00-blob
01-blob
02-blob
03-blob
04-blob
```
5. In the code added in the ***Code Snippet*** section configure `storageAccountName`, `storageAccountKey`, `containerName`.
6. Run the code from ***Code Snippet*** section.

***Code Snippet***
```
import com.azure.core.http.rest.PagedIterable;
import com.azure.storage.blob.BlobClient;
import com.azure.storage.blob.BlobClientBuilder;
import com.azure.storage.blob.BlobContainerClient;
import com.azure.storage.blob.BlobContainerClientBuilder;
import com.azure.storage.blob.models.BlobItem;
import com.azure.storage.blob.models.BlobListDetails;
import com.azure.storage.blob.models.BlobStorageException;
import com.azure.storage.blob.models.ListBlobsOptions;
import lombok.extern.slf4j.Slf4j;

import java.time.Duration;
import java.util.List;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.ForkJoinPool;

@Slf4j
public class CodeSnippet {

    private final BlobContainerClient blobContainerClient;
    private final BlobClientBuilder blobClientBuilder;

    public CodeSnippet() {
        String storageAccountName = "<ADD_STORAGE_ACCOUT>";
        String storageAccountKey = "<ADD_STORAGE_KEY>";
        String containerName = "<ADD_CONTAINER_NAME>";

        String connectionString = "DefaultEndpointsProtocol=https;AccountName=" + storageAccountName + ";AccountKey=" + storageAccountKey + ";EndpointSuffix=core.windows.net";

        blobContainerClient = new BlobContainerClientBuilder().connectionString(connectionString).containerName(containerName).buildClient();
        blobClientBuilder = new BlobClientBuilder().connectionString(connectionString).containerName(containerName);
    }

    private PagedIterable<BlobItem> listBlobsNotDeletedWithMetadata(String prefix) {
        ListBlobsOptions listBlobsOptionsBlobsNotDeletedWithMetadata = new ListBlobsOptions().setPrefix(prefix).setDetails(new BlobListDetails().setRetrieveDeletedBlobs(false).setRetrieveSnapshots(true).setRetrieveVersions(true).setRetrieveMetadata(true));
        return blobContainerClient.listBlobs(listBlobsOptionsBlobsNotDeletedWithMetadata, Duration.ofSeconds(600));
    }

    private void deleteBlobsAndVersion(BlobItem blob) {
        try {
            synchronized (this) {
                if (blob.getProperties().getLeaseStatus() != null) {
                    log.info("Trying to delete blob: {}", blob.getName());
                    BlobClient blobClient = blobClientBuilder.blobName(blob.getName()).buildClient();
                    blobClient.delete();
                }
                log.info("Trying to delete blob: {} with version: {}", blob.getName(), blob.getVersionId());
                BlobClient blobClient = blobClientBuilder.blobName(blob.getName()).versionId(blob.getVersionId()).buildClient();
                blobClient.delete();
            }
        } catch (BlobStorageException e) {
            log.error("Error deleting blob {} version {}", blob.getName(), blob.getVersionId(), e);
        }
    }

    private List<String> getPrefixes() {
        return List.of("00", "01", "02", "03", "04");
    }

    public void listAndDelete() throws ExecutionException, InterruptedException {
        ExecutorService executorService = new ForkJoinPool(16);

        List<String> hexrange = getPrefixes();

        executorService.submit(() ->
                hexrange.parallelStream().forEach(prefix -> {
                    PagedIterable<BlobItem> blobs = listBlobsNotDeletedWithMetadata(prefix);
                    for (BlobItem blob : blobs) {
                        deleteBlobsAndVersion(blob);
                    }
                })).get();
    }


    public static void main(String[] args) throws ExecutionException, InterruptedException {
        CodeSnippet codeSnippet = new CodeSnippet();
        codeSnippet.listAndDelete();
    }


}
```

**Expected behavior**
Blobs should be successfully deleted.

**Screenshots**

**Setup (please complete the following information):**
 - OS: Linux, Docker
 - Library/Libraries: com.azure:azure-storage-blob:12.12.0
 - Java version: 11
 - Frameworks: dropwizard: 2.0.20

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by joshfree** [comment]
Hi @ierandra thank you for reaching out to us via this GitHub issue.  @rickle-msft could you please follow up?

**Comment by rickle-msft** [comment]
Hi, @ierandra. Thanks for opening this issue. You said the code that's deleting blobs is running from multiple threads. That sounds to me like there's a possibility that one thread deletes the blob successfully and then other threads fail. I would recommend looping over the blobs once and then submitting each of those delete operations to the executor service rather than having each task loop over and delete all the blobs. If that makes sense?

An alternative, which I don't recommend in this case because it will still have all those extra delete calls, but should work, is to use deleteIfExists, which will not throw an exception if the blob is not found. It will just return false/the status code. This should be coming out in our upcoming release

**Comment by ierandra** [comment]
@rickle-msft 
> That sounds to me like there's a possibility that one thread deletes the blob successfully and then other threads fail. 

It's not the case, because the blob it's still present in the container after I run the code.

> I would recommend looping over the blobs once and then submitting each of those delete operations to the executor service rather than having each task loop over and delete all the blobs. 

This doesn't work for us because we have containers with millions of blobs and having them in a set/list would easily throw a OutOfMemory exception and also it's not time eficient since we would need to iterate 2 times.

**Comment by seanmcc-msft** [comment]
Would it be possible to post a code sample so and can attempt to reproduce?

**Comment by ierandra** [comment]
I added the code sample in the _**Code Snippet**_ section. I addition you just need to add a `BlobContainerClient blobContainerClient` and `BlobClientBuilder blobClientBuilder`

**Comment by rickle-msft** [comment]
@ierandra What authentication method are you using?

When you said

> the second thread always fails to delete the blob

Does "second thread" refer to the second time a delete is issued for that blob? Or does it mean the first thread is the one listing and the second thread is the first time a delete is called?

**Comment by rickle-msft** [comment]
Hi, @ierandra. Thank you for fleshing out the code snippet. I ran it and saw the exception you were seeing. Without modifying any of the logic, I also added the following print statement after calling blob.delete:
```
blobClient.delete();
System.out.printf("Successfully deleted blob: %s%n", blob.getName());
```
I also did a programmatic check of blobs remaining in the container after the main program had been executed:
```
System.out.println("Remaining blobs:");
        for (BlobItem blob : containerClient.listBlobs()) {
            System.out.println(blob.getName());
        }
```

With that, my logs show as follows:
```
Trying to delete blob: 03-blob
Successfully deleted blob: 03-blob
Trying to delete blob: 03-blob with version: null
Error deleting blob 03-blob version null. Message: Status code 404, "﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>BlobNotFound</Code><Message>The specified blob does not exist.
RequestId:4f052501-001e-0020-177a-6174fc000000
Time:2022-05-06T18:50:55.3018083Z</Message></Error>"
Trying to delete blob: 02-blob
Successfully deleted blob: 02-blob
Trying to delete blob: 02-blob with version: null
Error deleting blob 02-blob version null. Message: Status code 404, "﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>BlobNotFound</Code><Message>The specified blob does not exist.
RequestId:3ddf8e75-e01e-004c-5a7a-61df2f000000
Time:2022-05-06T18:50:55.4160475Z</Message></Error>"
Trying to delete blob: 04-blob
Successfully deleted blob: 04-blob
Trying to delete blob: 04-blob with version: null
Error deleting blob 04-blob version null. Message: Status code 404, "﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>BlobNotFound</Code><Message>The specified blob does not exist.
RequestId:f0c024f0-801e-005c-4b7a-61e9c9000000
Time:2022-05-06T18:50:55.4926127Z</Message></Error>"
Trying to delete blob: 00-blob
Successfully deleted blob: 00-blob
Trying to delete blob: 00-blob with version: null
Error deleting blob 00-blob version null. Message: Status code 404, "﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>BlobNotFound</Code><Message>The specified blob does not exist.
RequestId:d2e585ba-501e-0055-067a-61f347000000
Time:2022-05-06T18:50:55.5721296Z</Message></Error>"
Trying to delete blob: 01-blob
Successfully deleted blob: 01-blob
Trying to delete blob: 01-blob with version: null
Error deleting blob 01-blob version null. Message: Status code 404, "﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>BlobNotFound</Code><Message>The specified blob does not exist.
RequestId:edd65b94-701e-0060-037a-615d12000000
Time:2022-05-06T18:50:55.6404030Z</Message></Error>"
Remaining blobs:
```

What I notice is that there are two calls to delete every given blob. The second one is always going to fail because the blob has already been successfully deleted. Furthermore, there are no blobs remaining in the container as a listing operation demonstrates. I wonder if you are refreshing your view of the portal after the application has run? But I believe the api is working properly with the expected results. 

Looks to me like the duplicate delete call is coming from:
```
if (blob.getProperties().getLeaseStatus() != null) {
```

Lease status will never be null as it will always be one of five lease states. This means the delete call inside the if block is always called in addition to the delete call outside the if block, which corresponds to the logs showing one is trying to delete just the blob, and one is trying to delete the blob "with version null", which is the same resource. I'm not sure what the intention is here with lease states and version ids, but I don't think it is correct.

**Comment by ierandra** [comment]
@rickle-msft 
> What I notice is that there are two calls to delete every given blob.

Yes because we have versioning enabled and we need to delete the version blob created after the first delete. I updated again the **To Reproduce** section. Sorry for not mentioning this. 
Could you please try again?

**Comment by rickle-msft** [comment]
I see. Yes, I was able to see the behavior again when I enabled versioning. I have another hypothesis for you to consider:
You are holding a reference to a BlobClientBuilder and using that to generate the clients that you call these operations on but not properly clearing the state when switching blobs to operate on. In particular, the version id field is not cleared between iterations, and it is not cleared automatically when setting a new blob name. I believe the following steps take place. 
1. call builder.setName("00") // name = "00"
2. call builder.setName("00").setVersion("foo") // name = "00"; version = "foo"
3. call builder.setName("01") // name = "01"; version = "foo"
4. BlobNotFound because the version attached to the client does not correspond to this base blob

This is corroborated by two observations:
1. The version id of the blob not found error message was not matching the version id on the properties of the base blob (because the state of the builder was not as it should be).
2. The deletion seems to work completely for blob "00" as it does not show up in the final list of remaining blobs (because the state of the builder had not yet been messed up).

The solution to this would be to not use the builder and instead use containerClient.getBlobClient().getVersionClient() to get each client. Using this method, I am seeing expected results. Can you please try this?

**Comment by ierandra** [comment]
@rickle-msft yes, you are correct. I tried using `containerClient.getBlobClient()` and `containerClient.getBlobClient().getVersionClient()` works and I am not getting the errors any more.

**Comment by rickle-msft** [comment]
Glad to hear it!
