### ISSUE TITLE
[BUG] The link is force detached Error of Service Bus JMS

### ISSUE THREAD

**Issue by Toniotti** [Azure/azure-sdk-for-java#28754]
**Describe the bug**
I have an endpoint in my application that sends the received data into a ServiceBus queue.
After 10 minutes of inactivity this error starts appearing in every try to send the message to the queue.

I'am using JmsTemplate to send the messages.

***Exception or Stack Trace***
```console
org.springframework.jms.core.JmsTemplate.lambda$send$3(JmsTemplate.java:586)
	at org.springframework.jms.core.JmsTemplate.execute(JmsTemplate.java:504)
	... 58 common frames omitted
	Caused by: org.apache.qpid.jms.provider.ProviderException: The link 'G7:39132992:qpid-jms:sender:ID:055b0ae2-bb34-451f-bcec-e81f2988a257:1:99:1:itax.data.product_tax_retention' is force detached. Code: publisher(link4261411). Details: AmqpMessagePublisher.IdleTimerExpired: Idle timeout: 00:10:00. [condition = amqp:link:detach-forced]
	at org.apache.qpid.jms.provider.amqp.AmqpSupport.convertToNonFatalException(AmqpSupport.java:181)
	at org.apache.qpid.jms.provider.amqp.AmqpAbstractResource.processRemoteClose(AmqpAbstractResource.java:269)
	at org.apache.qpid.jms.provider.amqp.AmqpProvider.processUpdates(AmqpProvider.java:985)
	at org.apache.qpid.jms.provider.amqp.AmqpProvider.onData(AmqpProvider.java:871)
	at org.apache.qpid.jms.transports.netty.NettyTcpTransport$NettyTcpTransportHandler.channelRead0(NettyTcpTransport.java:563)
	at org.apache.qpid.jms.transports.netty.NettyTcpTransport$NettyTcpTransportHandler.channelRead0(NettyTcpTransport.java:556)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1372)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1235)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1284)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
```

**To Reproduce**
Send a message using JmsTemplate and after 10 minutes try sending another one to the same queue.

***Code Snippet***
```java
@RestController
public class Controller {

    @Autowired
    private JmsTemplate jmsTemplate;

    @PostMapping(path = "/sendData:update", consumes = "application/json")
    public void update(@RequestBody DataObject data) {
        jmsTemplate.convertAndSend("QUEUE_NAME", data);
    }
}
```

**Expected behavior**
I think this is some mechanism to not let unused resources open, but i would expect it to reopen the connection/link when necessary.
Or at least to have an option to disable this behavior (i didn't find an option for this if it exists).

**Setup (please complete the following information):**
 - OS: ubuntu
 - Library/Libraries: `spring-cloud-azure-starter-servicebus-jms:4.0.0` and `spring-boot:2.5.5`
 - Java version: 11
 - App Server/Environment: Tomcat
 - Frameworks: Spring Boot

**Comment by jialigit** [comment]
Hi, @Toniotti,

Thank you for your reporting!

We have addressed a same issue in: https://github.com/microsoft/azure-spring-boot/issues/817

In the **last** comment, there is a summary for this issue and for this version specifically, you can refer the workaround-1 for version 4.x.x.

> ##### Workaround-1: Upgrade to new 4.x.x starter(**This is the Recommended**)

Version 4.x.x provides pooled feature for ConnectionFactory. Enabling the pooled connection factory will mitigate this issue while we can take advantage of the caching resource feature which can be used for boosting the operation efficiency. This can work because that the PooledConnectionFactory will clear the underlying connection before this session is dead for inactivity.

  1. Dependency: include  spring-cloud-azure-starter-servicebus-jms:4.0.0. See [maven repo](https://search.maven.org/artifact/com.azure.spring/spring-cloud-azure-starter-servicebus-jms/4.1.0/jar)

  Use the following snippet:

  ```xml
  <dependency>
    <groupId>com.azure.spring</groupId>
    <artifactId>spring-cloud-azure-dependencies</artifactId>
    <version>${version.spring.cloud.azure}</version>
    <type>pom</type>
    <scope>import</scope>
  </dependency>

  <dependency>
    <groupId>com.azure.spring</groupId>
    <artifactId>spring-cloud-azure-starter-servicebus-jms</artifactId>
  </dependency>
  ```
  2. Configuration. Enable the **pool** option.
   
  > Only this pool enabled can avoid the issue encountered while sending messages. This is important.

  Use the following snippet:

  ```yml
  spring:
    jms:
      servicebus:
        connection-string: ${SERVICEBUS_NAMESPACE_CONNECTION_STRING}
        idle-timeout: 1800000
        pricing-tier: ${PRICING_TIER}
        pool:
          enabled: true
          max-connections: ${MAX_CONNECTIONS}
  ```

Hope this helps!
