### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by gioma68** [Azure/azure-sdk-for-java#28856]
**Describe the bug**
Send message to service bus using  ServiceBusSenderClient get timeout on databricks 10.4 LTS (spark 3.2.1). Works fine with DB 9.1 LTS (spark 3.1.2)

***Exception or Stack Trace***
IllegalStateException: Timeout on blocking read for 245600000000 NANOSECONDS
at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:123)
at reactor.core.publisher.Mono.block(Mono.java:1731)

**To Reproduce**
Steps to reproduce the behavior (HAPPY PATH):
1) build a sample java 8 client using official samples e.g. https://docs.microsoft.com/en-us/java/api/overview/azure/messaging-servicebus-readme?view=azure-java-stable#send-messages
2) deploy and run the jar on azure databricks cluster ver. 9.1 LTS
3) _messages are correctly send and received by the configured service bus instance_

Steps to reproduce the behavior (ERROR):
4) **change databricks cluster to ver 10.4 LTS**
5) **run the job and get the error**

***Code Snippet***
Add the code snippet that causes the issue.
    

    val senderClient = builder.sender().topicName(serviceBusChannelName).buildClient() 
    // prepare messages
    val jsonMessages = Seq(
      new ServiceBusMessage(BinaryData.fromString("{\"color\":\"red\"}")),
      new ServiceBusMessage(BinaryData.fromString("{\"color\":\"blue\"}")),
      new ServiceBusMessage(BinaryData.fromString("{\"color\":\"orange\"}")),
      new ServiceBusMessage(BinaryData.fromString("{\"color\":\"green\"}")))

    senderClient.sendMessages(jsonMessages.asJava) 

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - OS: azure-cloud
 - IDE: IntelliJ
 - Library/Libraries: com.azure:azure-messaging-servicebus:7.8.0
 - Java version:  8
 - App Server/Environment: Databricks 9.1/10.4 LTS (with spark+scala)
 - Frameworks: N.A.

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by gioma68** [comment]
**I have noted that the log report a previous error (non fatal) caused by the same library (reactor)**

> 22/05/13 13:04:23 ERROR Schedulers: Scheduler worker in group main failed with an uncaught exception
> java.lang.NoSuchMethodError: reactor.util.retry.Retry.generateCompanion(Lreactor/core/publisher/Flux;)Lorg/reactivestreams/Publisher;
> 	at reactor.core.publisher.FluxRetryWhen.subscribe(FluxRetryWhen.java:68)
> 	at reactor.core.publisher.FluxRetryWhen.subscribeOrReturn(FluxRetryWhen.java:83)
> 	at reactor.core.publisher.Mono.subscribe(Mono.java:4385)
> 	at reactor.core.publisher.MonoWhen$WhenCoordinator.subscribe(MonoWhen.java:160)
> 	at reactor.core.publisher.MonoWhen.subscribe(MonoWhen.java:99)

**Comment by anuchandy** [comment]
It looks like what is happening is that the version of Reactor that ServiceBus SDK is defined to use conflicts with the version of Reactor that DataBricks is pinned to use. Luckily you had the global-error handler registered to log any uncaught errors, here `NoSuchMethodError` (i.e. dependency-conflict-error) is an uncaught error. The [NoSuchMethodError](https://docs.oracle.com/javase/7/docs/api/java/lang/NoSuchMethodError.html) is a [fatal](https://github.com/reactor/reactor-core/blob/95d4340f6995c67bebf7f2f6106d400346f976e6/reactor-core/src/main/java/reactor/core/Exceptions.java#L442-L452) `LinkageError` hence the JVM (hence the code path) won't be able to make progress which is manifested as the timeout.

Please refer -  https://github.com/Azure/azure-sdk-for-java/wiki/Frequently-Asked-Questions#dependency-conflict

**Comment by gioma68** [comment]
Hi @anuchandy thanks for your prompt reply. I'll try your suggestion and send feedback if I resolve it. Kind regards

**Comment by gioma68** [comment]
Hi @anuchandy the solution was to implement shaded jar as in your reference. I don't know if the proble is specific for Databricks 10.4 LTS but I need to remove fasterxml from shading and to add a specific import version in POM.XML for `com.fasterxml.jackson.dataformat` now sending to ServiceBus with sdk work well. Thanks for your kindly support.
>         <dependency>            
>               <groupId>com.fasterxml.jackson.dataformat</groupId>
>              <artifactId>jackson-dataformat-xml</artifactId>
>              <version>2.10.1</version>
>          </dependency>

**Comment by anuchandy** [comment]
Good to hear! Shading is the only solution I'm aware of if the pinned dependencies (e.g., Reactor here) in a hosted environment (e.g., DataBricks here) cause conflicts. It worked for you because the shading had relocation defined for Reactor

```xml
<relocation>
  <pattern>reactor</pattern>
  <shadedPattern>ms.shaded.reactor</shadedPattern>
</relocation>
```

I'm not sure about `jackson-dataformat-xml` though; probably some other parts of your project needed it. 

Closing this as you're unblocked.
