### ISSUE TITLE
[BUG] web pubsub create client access token does not work using service principal

### ISSUE THREAD

**Issue by TimtationOne** [Azure/azure-sdk-for-java#28853]
**Describe the bug**
As soon as I use a service principal (`ClientSecretCredentialBuilder`) or my personal credentials (`DefaultAzureCredentialBuilder`) instead of the connection string for Azure authentication the `getClientAccessToken(option)` of the azure-messaging-webpubsub returns a "com.azure.core.exception.HttpResponseException: Status code 500, "Internal server error."" 

***Exception or Stack Trace***
<details>
  <summary>Stack Trace</summary>

```
com.azure.core.exception.HttpResponseException: Status code 500, "Internal server error."

	at com.azure.core.http.rest.RestProxy.instantiateUnexpectedException(RestProxy.java:387)
	at com.azure.core.http.rest.RestProxy.lambda$ensureExpectedStatus$4(RestProxy.java:455)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4400)
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FluxSwitchIfEmpty.java:82)
	at reactor.core.publisher.Operators$MonoSubscriber.onComplete(Operators.java:1858)
	at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.signalCached(MonoCacheTime.java:343)
	at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.onComplete(MonoCacheTime.java:368)
	at reactor.core.publisher.Operators.complete(Operators.java:137)
	at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:195)
	at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at reactor.core.publisher.MonoCacheTime.subscribeOrReturn(MonoCacheTime.java:143)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157)
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:130)
	at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:119)
	at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:220)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:130)
	at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:184)
	at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
	at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:128)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:260)
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:142)
	at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:400)
	at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:419)
	at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:473)
	at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:703)
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:93)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1372)
	at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1246)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1286)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:832)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
		at reactor.core.publisher.Mono.block(Mono.java:1707)
		at com.azure.messaging.webpubsub.WebPubSubServiceClient.getClientAccessToken(WebPubSubServiceClient.java:71)
		at com.daimler.encore.odxeimport.infrastructure.WebSocketTest.myTestServicePrincipal(WebSocketTest.java:38)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.reflect.Method.invoke(Method.java:564)
		at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
		at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
		at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
		at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
		at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
		at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
		at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
		at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
		at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
		at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
		at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
		at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
		at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
		at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:214)
		at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:210)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
		at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
		at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
		at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
```

</details>

**To Reproduce**
1. Add azure-messaging-webpubsub to pom
2. Add azure-identity to pom
3. Create Junit Test
4. Create Azure Web PubSub Service (Standard Tier)
5. Create Service Principal
6. Add "Web PubSub Service Owner (Preview)" role to service principal
7. Write tests for generate client access token using service principal

***Code Snippet***

<details>
<summary>Test Code</summary>

```java
void generateClientAccessToken() {
    var TENANT_ID="<TENANT_ID>";
    var CLIENT_ID="<CLIENT_ID>";
    var CLIENT_SECRET="<CLIENT_SECRET>";
    var ENDPOINT="https://<SERVICE_NAME>.webpubsub.azure.com";
    var HUB = "<MY_HUB>";

    var servicePrincipalToken = new ClientSecretCredentialBuilder()
        .tenantId(TENANT_ID)
        .clientId(CLIENT_ID)
        .clientSecret(CLIENT_SECRET)
        .build();

    WebPubSubServiceClient service = new WebPubSubServiceClientBuilder()
        .credential(servicePrincipalToken)
        .endpoint(ENDPOINT)
        .hub(HUB)
        .buildClient();

    var option = new GetClientAccessTokenOptions();

    WebPubSubClientAccessToken clientToken = service.getClientAccessToken(option);
  }
```

</details>

**Expected behavior**
`getClientAccessToken()` returns a newly generated access token

**Setup (please complete the following information):**
 - OS: Windows
 - IDE: IntelliJ
 - Library/Libraries: 
   - com.azure:azure-sdk-bom:1.2.1, com.azure:azure-messaging-webpubsub:1.1.1, com.azure:azure-identity:1.5.0
   - com.azure:azure-sdk-bom:1.2.1, com.azure:azure-messaging-webpubsub:1.1.2, com.azure:azure-identity:1.5.0
   - com.azure:azure-sdk-bom:1.2.1, com.azure:azure-messaging-webpubsub:1.0.0, com.azure:azure-identity:1.5.0
 - Java version: 14
 - App Server/Environment: Undertow
 - Frameworks: Spring Boot

**Additional context**
I've successfully tested generating the access token using the service principal via REST API and via JavaScript library.
In all cases I used the same credentials, hub and web pubsub service.
Other methods like sending messages work without problems in Java library with service principal
Using the connection-string instead of service principal the access token generation also works.
Only following combinations doesn't seem to work:
- Service Principal
- Java library
- getClientAccessToken

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by TimtationOne** [comment]
I found a workaround for as long as this is not fixed:

```java
void generateClientAccessTokenWorkAround() {
    var TENANT_ID="<TENANT_ID>";
    var CLIENT_ID="<CLIENT_ID>";
    var CLIENT_SECRET="<CLIENT_SECRET>";
    var ENDPOINT="https://<SERVICE_NAME>.webpubsub.azure.com";
    var HUB = "<MY_HUB>";

    var clientCredentials = new ClientSecretCredentialBuilder()
        .tenantId(TENANT_ID)
        .clientId(CLIENT_ID)
        .clientSecret(CLIENT_SECRET)
        .build();

    var context = new TokenRequestContext();
    context.addScopes("https://webpubsub.azure.com/.default");
    var tokenMono = clientCredentials.getToken(context);
    var tokenString = tokenMono.block().getToken();

    WebPubSubServiceClient service = new WebPubSubServiceClientBuilder()
        .credential(new AzureKeyCredential(tokenString))
        .endpoint(ENDPOINT)
        .hub(HUB)
        .buildClient();

    var option = new GetClientAccessTokenOptions();

    WebPubSubClientAccessToken clientToken = service.getClientAccessToken(option);
  }
```

**Comment by navba-MSFT** [comment]
Adding Service team to look into this ask.

**Comment by camelmann** [comment]
any news regarding this

**Comment by joshfree** [comment]
Closing out this old issue related to `Web PubSub Service Owner (Preview)`, please reactivate or reach out via https://github.com/Azure/azure-sdk-for-java/blob/main/SUPPORT.md#azure-support-tickets if this is actually an active/current issue.  thank you
