### ISSUE TITLE
[QUERY] Problems connecting through a proxy with the cosmos sdk for scala

### ISSUE THREAD

**Issue by davidmssantander** [Azure/azure-sdk-for-java#28956]
**Query/Question**
Is there an option to connect to cosmos through the scala sdk?

***Why is this not a Bug or a feature Request?***
I'm not sure if this option exists or I can't find it in the documentation

**Setup (please complete the following information if applicable):**
 - OS: Window
 - IDE: IntelliJ
 - Library/Libraries: azure-cosmos-spark_3-1_2-12 version 4.8.0
 
 **Information Checklist**
Hello,

We are having problems connecting to our cosmosDB through a proxy.
Our project is made in scala and we are using the library azure-cosmos-spark_3-1_2-12 version 4.8.0.

We are launching the code from Intellij and from the windows operating system.
We have tried to launch the application configuring the proxy variables both at the user environment variables level, and at the java virtual machine level, as well as setting them in the system at the code level, but it seems that the scala library ignores them.

The scala code is as follows:
```scala
val spark = SparkSession.builder().master("local").appName("test").getOrCreate()

    println("Connecting cosmos...")

    val readCfg = Map(
      "spark.cosmos.accountEndpoint" -> "https://xxxxxxxxxxxxx.documents.azure.com:443",
      "spark.cosmos.accountKey" -> "xxxxxxxxxxxxxxxxxxxxxxxxxxx",
      "spark.cosmos.database" -> "xxxxxxxxx",
      "spark.cosmos.container" -> "xxxxxxxx",
      "spark.cosmos.read.customQuery" -> "SELECT COUNT(0) AS Count FROM c",
    )
    val query_df: DataFrame = spark.read.format("cosmos.oltp").options(readCfg).load()
    query_df.show(35, false)
```
And the error result is as follows:
```console
{"ClassName":"CosmosException","userAgent":"azsdk-java-cosmos/4.28.1 Windows10/10.0 JRE/1.8.0_121","statusCode":503,"resourceAddress":"https://xxxxxxxxx.documents.azure.com:443/","innerErrorMessage":null,"causeInfo":"[class: class java.net.UnknownHostException, message: xxxxxxxxx.documents.azure.com]","responseHeaders":"{x-ms-substatus=10001}","requestHeaders":"[Accept=application/json, x-ms-date=Wed, 18 May 2022 10:36:27 GMT]","cosmosDiagnostics":{"userAgent":"azsdk-java-cosmos/4.28.1 Windows10/10.0 JRE/1.8.0_121","activityId":null,"requestLatencyInMs":1223,"requestStartTimeUTC":"2022-05-18T10:36:27.761Z","requestEndTimeUTC":"2022-05-18T10:36:28.984Z","responseStatisticsList":[],"supplementalResponseStatisticsList":[],"addressResolutionStatistics":{},"regionsContacted":[],"retryContext":{"statusAndSubStatusCodes":null,"retryCount":0,"retryLatency":0},"metadataDiagnosticsContext":{"metadataDiagnosticList":null},"serializationDiagnosticsContext":{"serializationDiagnosticsList":null},"gatewayStatistics":{"sessionToken":null,"operationType":"Read","resourceType":"DatabaseAccount","statusCode":503,"subStatusCode":10001,"requestCharge":"0.0","requestTimeline":[{"eventName":"connectionAcquired","startTimeUTC":"2022-05-18T10:36:27.770Z","durationInMicroSec":825000},{"eventName":"connectionConfigured","startTimeUTC":null,"durationInMicroSec":0},{"eventName":"requestSent","startTimeUTC":null,"durationInMicroSec":0},{"eventName":"transitTime","startTimeUTC":null,"durationInMicroSec":0},{"eventName":"received","startTimeUTC":null,"durationInMicroSec":0}],"partitionKeyRangeId":null},"systemInformation":{"usedMemory":"126403 KB","availableMemory":"340029 KB","systemCpuLoad":"empty","availableProcessors":4},"clientCfgs":{"id":1,"machineId":"uuid:7a9be2b3-975a-47a9-9387-a615073891c5","connectionMode":"DIRECT","numberOfClients":1,"connCfg":{"rntbd":null,"gw":"(cps:1000, nrto:null, icto:null, p:false)","other":"(ed: true, cs: false)"},"consistencyCfg":"(consistency: Eventual, mm: true, prgns: [])"}}}
at azure_cosmos_spark.com.azure.cosmos.BridgeInternal.createCosmosException(BridgeInternal.java:477)
at azure_cosmos_spark.com.azure.cosmos.implementation.RxGatewayStoreModel.lambda$toDocumentServiceResponse$3(RxGatewayStoreModel.java:393)
at azure_cosmos_spark.reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94)
at azure_cosmos_spark.reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onError(FluxMapFuseable.java:140)
at azure_cosmos_spark.reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:172)
at azure_cosmos_spark.reactor.core.publisher.MonoSingle$SingleSubscriber.onError(MonoSingle.java:150)
at azure_cosmos_spark.reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:106)
at azure_cosmos_spark.reactor.core.publisher.Operators.error(Operators.java:198)
at azure_cosmos_spark.reactor.core.publisher.MonoError.subscribe(MonoError.java:53)
at azure_cosmos_spark.reactor.core.publisher.Mono.subscribe(Mono.java:4400)
at azure_cosmos_spark.reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103)
at azure_cosmos_spark.reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onError(FluxPeekFuseable.java:234)
at azure_cosmos_spark.reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onError(FluxContextWrite.java:121)
at azure_cosmos_spark.reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onError(MonoFlatMapMany.java:204)
at azure_cosmos_spark.reactor.core.publisher.SerializedSubscriber.onError(SerializedSubscriber.java:124)
at azure_cosmos_spark.reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.whenError(FluxRetryWhen.java:225)
at azure_cosmos_spark.reactor.core.publisher.FluxRetryWhen$RetryWhenOtherSubscriber.onError(FluxRetryWhen.java:274)
at azure_cosmos_spark.reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:415)
at azure_cosmos_spark.reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onNext(FluxConcatMap.java:251)
at azure_cosmos_spark.reactor.core.publisher.EmitterProcessor.drain(EmitterProcessor.java:491)
at azure_cosmos_spark.reactor.core.publisher.EmitterProcessor.tryEmitNext(EmitterProcessor.java:299)
at azure_cosmos_spark.reactor.core.publisher.SinkManySerialized.tryEmitNext(SinkManySerialized.java:100)
at azure_cosmos_spark.reactor.core.publisher.InternalManySink.emitNext(InternalManySink.java:27)
at azure_cosmos_spark.reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.onError(FluxRetryWhen.java:190)
at azure_cosmos_spark.reactor.core.publisher.MonoCreate$DefaultMonoSink.error(MonoCreate.java:194)
at azure_cosmos_spark.reactor.netty.http.client.HttpClientConnect$MonoHttpConnect$ClientTransportSubscriber.onError(HttpClientConnect.java:304)
at azure_cosmos_spark.reactor.core.publisher.MonoCreate$DefaultMonoSink.error(MonoCreate.java:194)
at azure_cosmos_spark.reactor.netty.resources.DefaultPooledConnectionProvider$DisposableAcquire.onError(DefaultPooledConnectionProvider.java:154)
at azure_cosmos_spark.reactor.netty.internal.shaded.reactor.pool.AbstractPool$Borrower.fail(AbstractPool.java:477)
at azure_cosmos_spark.reactor.netty.internal.shaded.reactor.pool.SimpleDequePool.lambda$drainLoop$9(SimpleDequePool.java:401)
at azure_cosmos_spark.reactor.core.publisher.FluxDoOnEach$DoOnEachSubscriber.onError(FluxDoOnEach.java:186)
at azure_cosmos_spark.reactor.core.publisher.MonoCreate$DefaultMonoSink.error(MonoCreate.java:194)
at azure_cosmos_spark.reactor.netty.resources.DefaultPooledConnectionProvider$PooledConnectionAllocator$PooledConnectionInitializer.onError(DefaultPooledConnectionProvider.java:536)
at azure_cosmos_spark.reactor.core.publisher.MonoFlatMap$FlatMapMain.secondError(MonoFlatMap.java:192)
at azure_cosmos_spark.reactor.core.publisher.MonoFlatMap$FlatMapInner.onError(MonoFlatMap.java:259)
at azure_cosmos_spark.reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:106)
at azure_cosmos_spark.reactor.core.publisher.Operators.error(Operators.java:198)
at azure_cosmos_spark.reactor.core.publisher.MonoError.subscribe(MonoError.java:53)
at azure_cosmos_spark.reactor.core.publisher.Mono.subscribe(Mono.java:4400)
at azure_cosmos_spark.reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103)
at azure_cosmos_spark.reactor.core.publisher.Operators.error(Operators.java:198)
at azure_cosmos_spark.reactor.core.publisher.MonoError.subscribe(MonoError.java:53)
at azure_cosmos_spark.reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
at azure_cosmos_spark.reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157)
at azure_cosmos_spark.reactor.netty.transport.TransportConnector$MonoChannelPromise._subscribe(TransportConnector.java:579)
at azure_cosmos_spark.reactor.netty.transport.TransportConnector$MonoChannelPromise.lambda$subscribe$0(TransportConnector.java:499)
at azure_cosmos_spark.io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
at azure_cosmos_spark.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
at azure_cosmos_spark.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
at azure_cosmos_spark.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
at azure_cosmos_spark.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at azure_cosmos_spark.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.UnknownHostException: xxxxxxxxx.documents.azure.com
```
Is there a way to tell the cosmos sdk to go through the proxy?

Greetings and thank you very much

**Comment by kushagraThapar** [comment]
@xinlian12  - can you please take a look at this issue, thanks!

**Comment by TheovanKraay** [comment]
Not currently supported. We will be considering whether to include this support in upcoming Semester planning. Meanwhile, if you want to add the capability, please feel free to post a PR. We encourage contributions, and our team will help review your code.

**Comment by kushagraThapar** [comment]
@davidmssantander I am closing this issue in lieu of https://github.com/Azure/azure-sdk-for-java/issues/31693
We will plan this soon.
