### ISSUE TITLE
Getting an error "No such host is known"

### ISSUE THREAD

**Issue by Mahesh-MSFT** [Azure/azure-sdk-for-java#28965]
Getting this error when running this sample

```
2019-09-13 12:47:41.317  INFO 6696 --- [nio-8080-exec-1] io.lettuce.core.KqueueProvider           : Starting without optional kqueue library
2019-09-13 12:47:42.499 ERROR 6696 --- [nio-8080-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to maksh-redis.redis.cache.windows.net:6379] with root cause

java.net.UnknownHostException: No such host is known (XXX-YYYY.redis.cache.windows.net)
        at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method) ~[na:na]
        at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:929) ~[na:na]
        at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1515) ~[na:na]
        at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:848) ~[na:na]
        at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1505) ~[na:na]
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1364) ~[na:na]
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1298) ~[na:na]
        at java.base/java.net.InetAddress.getByName(InetAddress.java:1248) ~[na:na]
        at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:146) ~[netty-common-4.1.39.Final.jar!/:4.1.39.Final]
        at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:143) ~[netty-common-4.1.39.Final.jar!/:4.1.39.Final]
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:552) ~[na:na]
        at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:143) ~[netty-common-4.1.39.Final.jar!/:4.1.39.Final]
        at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:43) ~[netty-resolver-4.1.39.Final.jar!/:4.1.39.Final]
        at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:63) ~[netty-resolver-4.1.39.Final.jar!/:4.1.39.Final]
        at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:55) ~[netty-resolver-4.1.39.Final.jar!/:4.1.39.Final]
```

What changes are needed to get this sample running?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c250a5d-b97e-7db0-cf67-1d19b201b849
* Version Independent ID: 3ab5fb94-b16e-0a1c-4de1-4a20bc0fd89e
* Content: [Configure a Spring Boot Initializer app to use Azure Redis Cache](https://docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-boot-initializer-java-app-with-redis-cache?view=azure-java-stable)
* Content Source: [docs-ref-conceptual/spring-framework/configure-spring-boot-initializer-java-app-with-redis-cache.md](https://github.com/Azure/azure-docs-sdk-java/blob/master/docs-ref-conceptual/spring-framework/configure-spring-boot-initializer-java-app-with-redis-cache.md)
* Service: **cache**
* GitHub Login: @rmcmurray
* Microsoft Alias: **robmcm**

**Comment by alzimmermsft** [comment]
This could have been an issue with Java internals resolving the address, we've seen similar happen before and it has been resolved without changes (likely due to networking issues outside of our control).
