### ISSUE TITLE
[BUG] Consumer has invalid offset stored and is not able to consume new events

### ISSUE THREAD

**Issue by LBoraz** [Azure/azure-sdk-for-java#28990]
**Describe the bug**
The same as https://github.com/Azure/azure-sdk-for-net/issues/28244 but for the java client.
The consumer somehow ends up with an invalid offset and is not able to recover anymore. Only way seems to delete the offsets from the storage account.

***Exception or Stack Trace***
```console
host logstash-678cde56-c7bf-438f-8016-04ff90f8899c: 0: Failure creating client or receiver, retrying
java.util.concurrent.CompletionException: com.microsoft.azure.eventhubs.EventHubException: The supplied offset '562667152376' is invalid. The last offset in the system is '94492375776' TrackingId:178557ce-49df-40f3-b61c-9c589b4b1e78_B32, SystemTracker:evthubs-apim-uat:eventhub:elastic-logs-hub-uat~16383, Timestamp:2022-05-13T14:07:29 Reference:95171ab2-abcb-4414-8ff8-0daee874fe90, TrackingId:3a86f92f-2110-4e8d-bd15-b49cca0dd9af_B32, SystemTracker:evthubs-apim-uat:eventhub:elastic-logs-hub-uat~16383|$default, Timestamp:2022-05-13T14:07:29 TrackingId:478e01c44e9a487992ea198f973cf032_G20, SystemTracker:gateway5, Timestamp:2022-05-13T14:07:29, errorContext[NS: evthubs-apim-uat.servicebus.windows.net, PATH: elastic-logs-hub-uat/ConsumerGroups/$Default/Partitions/0, REFERENCE_ID: LN_f3e8c1_1652450849164_032_G20]
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:704) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088) ~[?:?]
	at com.microsoft.azure.eventhubs.impl.ExceptionUtil.completeExceptionally(ExceptionUtil.java:104) ~[azure-eventhubs-2.3.2.jar:?]
	at com.microsoft.azure.eventhubs.impl.MessageReceiver.cancelOpen(MessageReceiver.java:361) ~[azure-eventhubs-2.3.2.jar:?]
	at com.microsoft.azure.eventhubs.impl.MessageReceiver.onOpenComplete(MessageReceiver.java:351) ~[azure-eventhubs-2.3.2.jar:?]
	at com.microsoft.azure.eventhubs.impl.MessageReceiver.onError(MessageReceiver.java:418) ~[azure-eventhubs-2.3.2.jar:?]
	at com.microsoft.azure.eventhubs.impl.MessageReceiver.onClose(MessageReceiver.java:746) ~[azure-eventhubs-2.3.2.jar:?]
	at com.microsoft.azure.eventhubs.impl.BaseLinkHandler.processOnClose(BaseLinkHandler.java:70) ~[azure-eventhubs-2.3.2.jar:?]
	at com.microsoft.azure.eventhubs.impl.BaseLinkHandler.handleRemoteLinkClosed(BaseLinkHandler.java:106) ~[azure-eventhubs-2.3.2.jar:?]
	at com.microsoft.azure.eventhubs.impl.BaseLinkHandler.onLinkRemoteClose(BaseLinkHandler.java:48) ~[azure-eventhubs-2.3.2.jar:?]
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:176) ~[proton-j-0.33.9.jar:?]
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108) ~[proton-j-0.33.9.jar:?]
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324) ~[proton-j-0.33.9.jar:?]
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291) ~[proton-j-0.33.9.jar:?]
	at com.microsoft.azure.eventhubs.impl.MessagingFactory$RunReactor.run(MessagingFactory.java:512) ~[azure-eventhubs-2.3.2.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: com.microsoft.azure.eventhubs.EventHubException: The supplied offset '562667152376' is invalid. The last offset in the system is '94492375776' TrackingId:178557ce-49df-40f3-b61c-9c589b4b1e78_B32, SystemTracker:evthubs-apim-uat:eventhub:elastic-logs-hub-uat~16383, Timestamp:2022-05-13T14:07:29 Reference:95171ab2-abcb-4414-8ff8-0daee874fe90, TrackingId:3a86f92f-2110-4e8d-bd15-b49cca0dd9af_B32, SystemTracker:evthubs-apim-uat:eventhub:elastic-logs-hub-uat~16383|$default, Timestamp:2022-05-13T14:07:29 TrackingId:478e01c44e9a487992ea198f973cf032_G20, SystemTracker:gateway5, Timestamp:2022-05-13T14:07:29, errorContext[NS: evthubs-apim-uat.servicebus.windows.net, PATH: elastic-logs-hub-uat/ConsumerGroups/$Default/Partitions/0, REFERENCE_ID: LN_f3e8c1_1652450849164_032_G20]
	at com.microsoft.azure.eventhubs.impl.ExceptionUtil.toException(ExceptionUtil.java:43) ~[azure-eventhubs-2.3.2.jar:?]
	at com.microsoft.azure.eventhubs.impl.MessageReceiver.onClose(MessageReceiver.java:745) ~[azure-eventhubs-2.3.2.jar:?]
	... 14 more
Caused by: com.microsoft.azure.eventhubs.impl.AmqpException: The supplied offset '562667152376' is invalid. The last offset in the system is '94492375776' TrackingId:178557ce-49df-40f3-b61c-9c589b4b1e78_B32, SystemTracker:evthubs-apim-uat:eventhub:elastic-logs-hub-uat~16383, Timestamp:2022-05-13T14:07:29 Reference:95171ab2-abcb-4414-8ff8-0daee874fe90, TrackingId:3a86f92f-2110-4e8d-bd15-b49cca0dd9af_B32, SystemTracker:evthubs-apim-uat:eventhub:elastic-logs-hub-uat~16383|$default, Timestamp:2022-05-13T14:07:29 TrackingId:478e01c44e9a487992ea198f973cf032_G20, SystemTracker:gateway5, Timestamp:2022-05-13T14:07:29
	at com.microsoft.azure.eventhubs.impl.ExceptionUtil.toException(ExceptionUtil.java:43) ~[azure-eventhubs-2.3.2.jar:?]
	at com.microsoft.azure.eventhubs.impl.MessageReceiver.onClose(MessageReceiver.java:745) ~[azure-eventhubs-2.3.2.jar:?]
	... 14 more
```
**To Reproduce**
The Event Hubs was destroyed and recreated with the same parameters (same name, entity paths, and so on) at the same time the issue in the consumer started.

***Code Snippet***
The event hub is consumed from Logstash, i don't have a code snippet

**Expected behavior**
The consumer does not store an invalid offset
The consumer does not block forever

**Screenshots**
No screenshots available

**Setup (please complete the following information):**
 - OS: Linux
 - IDE: IntelliJ
 - Library/Libraries: not known the version of the lib used by logstash
 - Java version: 11
 - App Server/Environment: Logstash in Kubernetes (AKS)
 - Frameworks: -

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ x] Bug Description Added
- [ x] Repro Steps Added
- [ x] Setup information Added

**Comment by jsquire** [comment]
Hi @LBoraz.  Thank you for reaching out and we regret that you're experiencing difficulties.   As discussed in the .NET issue that was referenced, offsets are only invalidated in scenarios where a manual action was taken to delete an Event Hub to or initiate fail-over.  **The recommended mediation for this scenario is to extend that manual process to either configure a new Storage container for the processor or clear all blobs from the existing container.**

This is not a scenario where it is reasonably possible to automatically detect or prevent from within the client library.  The challenge with doing so is that the client cannot reliably determine the intent.  It's not possible to know whether someone made a mistake and specified the wrong container/Event Hub or if the Event Hub was manually changed.  In the first case, the better course of action is to fail and avoid processing the wrong events.   In the second case, it may or may not be desirable to reset state and start from the beginning of the stream.   

Because the cause of this behavior is an explicit action taken external to the SDK and the right corrective action cannot be determined automatically, this is not something we can address in the SDK.   I'm going to mark this as addressed, but please feel free to unresolve if you'd like to continue the discussion.
