### ISSUE TITLE
[BUG] java.lang.ExceptionInInitializerError in ReflectionUtilsApi  on Java 17 when running on IoT Edge, uploading to Blob Storage

### ISSUE THREAD

**Issue by derSchtefan** [Azure/azure-sdk-for-java#29046]
**Describe the bug**
When using the Azure SDK on Java 17 in an IoT edge environment, uploading a blob via the Azure Blob storage SDK, a class initializer exception is thrown. It is not clear what causes this, but it appears that ReflectionUtilsApi tries to instantiate [ReflectionUtils](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/core/azure-core/src/main/java/com/azure/core/implementation/ReflectionUtils.java), and fails in the static initializer with some Reflection related issues (potentially deprecated?)

This is maybe related to the application running on azul/zulu-openjdk-alpine:17-jre in a docker container, but it might be a java 17 issue. Java 11 works fine.

***Exception or Stack Trace***
```
2022-05-24 13:14:51.065 ERROR 1 --- [or-http-epoll-1] r.n.channel.ChannelOperationsHandler     : [c1b94163, L:/172.21.0.4:55466 - R:localblobstore/172.21.0.3:11002] Error was received while reading the incoming data. The connection will be closed.

java.lang.ExceptionInInitializerError: null
        at com.azure.core.implementation.ReflectionUtilsApi.<clinit>(ReflectionUtilsApi.java:12) ~[app.jar:1.0.0-SNAPSHOT]
        at com.azure.core.implementation.jackson.ObjectMapperShim.lambda$deserialize$2(ObjectMapperShim.java:305) ~[app.jar:1.0.0-SNAPSHOT]
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) ~[na:na]
        at com.azure.core.implementation.jackson.ObjectMapperShim.getFromCache(ObjectMapperShim.java:433) ~[app.jar:1.0.0-SNAPSHOT]
        at com.azure.core.implementation.jackson.ObjectMapperShim.deserialize(ObjectMapperShim.java:302) ~[app.jar:1.0.0-SNAPSHOT]
        at com.azure.core.util.serializer.JacksonAdapter.lambda$deserialize$10(JacksonAdapter.java:244) ~[app.jar:1.0.0-SNAPSHOT]
        at com.azure.core.util.serializer.JacksonAdapter.useAccessHelper(JacksonAdapter.java:271) ~[app.jar:1.0.0-SNAPSHOT]
        at com.azure.core.util.serializer.JacksonAdapter.deserialize(JacksonAdapter.java:244) ~[app.jar:1.0.0-SNAPSHOT]
        at com.azure.core.implementation.serializer.HttpResponseHeaderDecoder.decode(HttpResponseHeaderDecoder.java:39) ~[app.jar:1.0.0-SNAPSHOT]
        at com.azure.core.implementation.serializer.HttpResponseDecoder$HttpDecodedResponse.getDecodedHeaders(HttpResponseDecoder.java:96) ~[app.jar:1.0.0-SNAPSHOT]
        at com.azure.core.http.rest.RestProxy.createResponse(RestProxy.java:480) ~[app.jar:1.0.0-SNAPSHOT]
        at com.azure.core.http.rest.RestProxy.lambda$handleRestResponseReturnType$5(RestProxy.java:459) ~[app.jar:1.0.0-SNAPSHOT]
        at reactor.core.publisher.MonoCallable.call(MonoCallable.java:92) ~[app.jar:1.0.0-SNAPSHOT]
        at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:228) ~[app.jar:1.0.0-SNAPSHOT]
        at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:203) ~[app.jar:1.0.0-SNAPSHOT]
        at reactor.core.publisher.MonoIgnoreElements$IgnoreElementsSubscriber.onComplete(MonoIgnoreElements.java:89) ~[app.jar:1.0.0-SNAPSHOT]
        at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144) ~[app.jar:1.0.0-SNAPSHOT]
        at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onComplete(FluxDoFinally.java:145) ~[app.jar:1.0.0-SNAPSHOT]
        at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144) ~[app.jar:1.0.0-SNAPSHOT]
        at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:400) ~[app.jar:1.0.0-SNAPSHOT]
        at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:419) ~[app.jar:1.0.0-SNAPSHOT]
        at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:473) ~[app.jar:1.0.0-SNAPSHOT]
        at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:703) ~[app.jar:1.0.0-SNAPSHOT]
        at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:93) ~[app.jar:1.0.0-SNAPSHOT]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[app.jar:1.0.0-SNAPSHOT]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[app.jar:1.0.0-SNAPSHOT]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[app.jar:1.0.0-SNAPSHOT]
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) ~[app.jar:1.0.0-SNAPSHOT]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) ~[app.jar:1.0.0-SNAPSHOT]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) ~[app.jar:1.0.0-SNAPSHOT]
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) ~[app.jar:1.0.0-SNAPSHOT]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[app.jar:1.0.0-SNAPSHOT]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[app.jar:1.0.0-SNAPSHOT]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[app.jar:1.0.0-SNAPSHOT]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[app.jar:1.0.0-SNAPSHOT]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[app.jar:1.0.0-SNAPSHOT]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[app.jar:1.0.0-SNAPSHOT]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[app.jar:1.0.0-SNAPSHOT]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[app.jar:1.0.0-SNAPSHOT]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487) ~[app.jar:1.0.0-SNAPSHOT]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385) ~[app.jar:1.0.0-SNAPSHOT]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) ~[app.jar:1.0.0-SNAPSHOT]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[app.jar:1.0.0-SNAPSHOT]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[app.jar:1.0.0-SNAPSHOT]
        at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make java.lang.invoke.MethodHandles$Lookup(java.lang.Class) accessible: module java.base does not "opens java.lang.invoke" to unnamed module @20322d26
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354) ~[na:na]
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297) ~[na:na]
        at java.base/java.lang.reflect.Constructor.checkCanSetAccessible(Constructor.java:188) ~[na:na]
        at java.base/java.lang.reflect.Constructor.setAccessible(Constructor.java:181) ~[na:na]
        at com.azure.core.implementation.ReflectionUtils.<clinit>(ReflectionUtils.java:23) ~[app.jar:1.0.0-SNAPSHOT]
        ... 45 common frames omitted
```

**To Reproduce**
- Use Java 17 with azul/zulu-openjdk-alpine:17-jre
- Upload a blob with BlobClient.upload(stream,length)

***Code Snippet***
```java
BlobClient blobClient = blobContainerClient.getBlobClient(name);
var length = stream.available();
blobClient.upload(stream, length);
```

**Expected behavior**
It works fine under Java 11

**Setup (please complete the following information):**
 - OS: Docker container running azul/zulu-openjdk-alpine:17-jre
 - Library/Libraries: 
 - Spring: 2.7.0
 - azure.iot.device.client.version: 2.0.3
 - azure.iot.service.client.version: 2.0.2
 - azure-storage-blob: 12.16.1
 - reactor-core: 3.4.18
 - Java version: 17

**Additional context**
Maybe happens because of azul? Maybe because this runs as a module in an IoT edge environment?  Works fine with Java 11, fails only at the first attempt to upload a blob.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by alzimmermsft** [comment]
Thanks for filing this @derSchtefan, this issue looks pretty peculiar.

So, `ReflectionUtils` has two implementations, [one for Java 8](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/core/azure-core/src/main/java/com/azure/core/implementation/ReflectionUtils.java) and [one for Java 9+](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/core/azure-core/src/main/java9/com/azure/core/implementation/ReflectionUtils.java), and to me right away this looks like it is trying to use the Java 8 implementation which calls into JDK internal APIs (which is loosely allowed in Java 8).

Is the application being used an uber, or all-in-one, JAR where dependencies are pulled into it?

**Comment by derSchtefan** [comment]
@alzimmermsft It is an all-in-one, coming out of a maven build.

The application is an iot edge module, that runs fine under azul/zulu-openjdk-alpine:11-jre but the very same jar does fail under azul/zulu-openjdk-alpine:17-jre

The application is built with `RUN mvn install -Dmaven.test.skip=false` and copied into the run-container with `COPY --from=build-env /app/target/OpcRouter-1.0.0-SNAPSHOT-with-deps.jar ./app.jar` 

So yes, an all-in-one.

**Comment by alzimmermsft** [comment]
@derSchtefan did my last comment help?

**Comment by derSchtefan** [comment]
@alzimmermsft Public Holiday / Long weekend here in Europe. Will write you on Monday. :)

**Comment by alzimmermsft** [comment]
@derSchtefan hope you had a good holiday! Did you have a chance to check if what I wrote was able to fix your issue?

**Comment by derSchtefan** [comment]
@alzimmermsft Sorry, this has fallen through the cracks. I stopped working in that company end of May. My colleagues will have a look asap, I pinged them. Thank you for your fast response.

**Comment by ivan-p92** [comment]
Same here. The additional Manifest entry fixes the issue for us too. We use `eclipse-temurin:18-jre`.

**Comment by alzimmermsft** [comment]
The next release of `azure-core` should no longer require `Multi-Release: true` in `META-INF` when creating an all-in-one JAR.
