### ISSUE TITLE
[BUG] NullPointerException when inserting documents using ReactiveCosmosTemplate because HTTP result with code 201 and no content

### ISSUE THREAD

**Issue by geriamir** [Azure/azure-sdk-for-java#29411]
**Describe the bug**
When trying to insert documents to a Azure CosmosDB with SQL API, the result is a NullPointerException.
I've debugged the processes internally in ReactiveCosmosTemplate and seen that the response cosmosItemResponse is with code 201 and no content, so the deserialization back to domain object throws a NullPointerException.

***Exception or Stack Trace***
java.lang.NullPointerException
	at com.azure.spring.data.cosmos.core.convert.MappingCosmosConverter.readInternal(MappingCosmosConverter.java:75)
	at com.azure.spring.data.cosmos.core.convert.MappingCosmosConverter.read(MappingCosmosConverter.java:64)
	at com.azure.spring.data.cosmos.core.ReactiveCosmosTemplate.toDomainObject(ReactiveCosmosTemplate.java:792)
	at com.azure.spring.data.cosmos.core.ReactiveCosmosTemplate.lambda$insert$13(ReactiveCosmosTemplate.java:410)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:125)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
	at reactor.core.publisher.MonoPublishOn$PublishOnSubscriber.run(MonoPublishOn.java:181)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**To Reproduce**
Create a POJO with @Container annotation, and members: ID, ETAG (with Version annotation), and an additional field.
Create a ReactiveCosmosTemplate.
insert a POJO instance using the "insert" method.

***Code Snippet***
reactiveCosmosTemplate.insert(record)

**Expected behavior**
The method will return the record deserialized after getting it back from the DB.

**Setup (please complete the following information):**
 - OS: Linux and Windows
 - IDE: IntelliJ
 - Library/Libraries: com.azure:azure-spring-data-cosmos:3.13.0
 - Java version: 11
 - App Server/Environment: Dockerize Spring running on AKS.
 - Frameworks: SpringBoot

**Comment by geriamir** [comment]
@kushagraThapar if the method "insert" is not supported, than it should be in that API.

**Comment by kushagraThapar** [comment]
@geriamir - `ReactiveCosmosTemplate` is not supposed to be public API, however, coming back to the discussion, it could be possible that you are not setting `contentResponseOnWriteEnabled` flag on `CosmosClientBuilder` if you are creating `CosmosAsyncClient` -> 

```
    /**
     * Sets the boolean to only return the headers and status code in Cosmos DB response
     * in case of Create, Update and Delete operations on CosmosItem.
     *
     * If set to false (which is by default), service doesn't return payload in the response. It reduces networking
     * and CPU load by not sending the payload back over the network and serializing it on the client.
     *
     * This feature does not impact RU usage for read or write operations.
     *
     * By-default, this is false.
     *
     * @param contentResponseOnWriteEnabled a boolean indicating whether payload will be included in the response or not
     * @return current cosmosClientBuilder
     */
    public CosmosClientBuilder contentResponseOnWriteEnabled(boolean contentResponseOnWriteEnabled) {
        this.contentResponseOnWriteEnabled = contentResponseOnWriteEnabled;
        return this;
    }
```
