### ISSUE TITLE
[BUG] BlockBlobClient.upload causes "com.azure.core.exception.UnexpectedLengthException: Request body emitted N bytes, more than the expected N-1 bytes"

### ISSUE THREAD

**Issue by hawk-phi-tran** [Azure/azure-sdk-for-java#29504]
**Describe the bug**
We use Azure Blob Storage to store a json file (78KB).
In our Java service, we update the file and upload it to Azure using **BlockBlobClient.upload** method
The method call is like
```
class BlobStorage:
public void putObject(inputStream) {
  BlockBlobClient blobClient = initClient();
  blobClient.upload(inputStream, size-of-inputStream, true);
}
```

***Exception or Stack Trace***
`Caused by: c.a.c.e.UnexpectedLengthException: Request body emitted 44131 bytes, more than the expected 44130 bytes.
	at c.a.s.common.Utility.lambda$convertStreamToByteBuffer$1(Utility.java:266)
	at r.c.p.MonoCallable.call(MonoCallable.java:92)
	at r.c.p.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:410)
	at r.c.p.FluxConcatMap$ConcatMapImmediate.onNext(FluxConcatMap.java:251)
	at r.c.p.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:127)
	at r.c.p.Operators$ScalarSubscription.request(Operators.java:2398)
	at r.c.p.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:169)
	at r.c.p.FluxConcatMap$ConcatMapImmediate.onSubscribe(FluxConcatMap.java:236)
	at r.c.p.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:96)
	at r.c.p.FluxJust.subscribe(FluxJust.java:68)
	at r.c.p.InternalFluxOperator.subscribe(InternalFluxOperator.java:62)
	at r.c.p.FluxDefer.subscribe(FluxDefer.java:54)
	at r.c.p.FluxSubscribeOn$SubscribeOnSubscriber.run(FluxSubscribeOn.java:194)
	at r.c.s.WorkerTask.call(WorkerTask.java:84)
	at r.c.s.WorkerTask.call(WorkerTask.java:37)
	at j.u.c.FutureTask.run(Unknown Source)
	at j.u.c.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at j.u.c.ThreadPoolExecutor.runWorker(Unknown Source)
	at j.u.c.ThreadPoolExecutor$Worker.run(Unknown Source)
	... 1 common frames omitted
	Suppressed: java.lang.Exception: #block terminated with an error
		at r.c.p.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
		at r.c.publisher.Mono.block(Mono.java:1707)
		at c.a.s.c.i.StorageImplUtils.blockWithOptionalTimeout(StorageImplUtils.java:191)
		at c.a.s.b.s.BlockBlobClient.uploadWithResponse(BlockBlobClient.java:421)
		at c.a.s.b.s.BlockBlobClient.uploadWithResponse(BlockBlobClient.java:363)
		at c.a.s.b.s.BlockBlobClient.upload(BlockBlobClient.java:297)
		at t.h.u.c.s.BlobStorage.lambda$putObject$2(BlobStorage.java:45)
		at j.u.c.CompletableFuture.uniApplyNow(Unknown Source)
		at j.u.c.CompletableFuture.uniApplyStage(Unknown Source)
		at j.u.c.CompletableFuture.thenApply(Unknown Source)
		at t.h.u.c.s.BlobStorage.putObject(BlobStorage.java:41)`

**To Reproduce**
Calling **BlockBlobClient.upload** method to upload a "big" file, here my file is 78KB and caused the error.
Uploading a smaller file (10KB) didn't cause the error

***Code Snippet***
See the description above

**Expected behavior**
The upload should work

**Screenshots**
Not available

**Setup (please complete the following information):**
 - OS: Windows 10
 - IDE: IntelliJ 2021.1.1
 - Library/Libraries: group: 'com.azure', name: 'azure-storage-blob', version: 12.17.1
 - Java version: 11
 - App Server/Environment: I tested it from my local IntelliJ
 - Frameworks: Spring Boot

**Comment by joshfree** [comment]
Hi @hawk-phi-tran thanks for reaching out to us via this Github issue.  Someone from the storage sdk team will follow up with you shortly.

/cc @rickle-msft @kasobol-msft

**Comment by hawk-phi-tran** [comment]
@rickle-msft 
We convert an input array into byte array and take the size of that array.
The size is correct but somehow the SDK expects 1 byte bigger and throws **UnexpectedLengthException**
`
JSON = new ObjectMapper();
byte[] objectAsBytes = JSON.writeValueAsString(inputArray).getBytes(StandardCharsets.UTF_8); <--- length of this byte array
`
A dirty workaround is to add 1 to the calculated size so that it matches the expected size in the SDK but I'm looking for a better approach, something maintainable.

**Comment by rickle-msft** [comment]
What version of the sdk are you using?

**Comment by rickle-msft** [comment]
And I'm assuming you then do something like

```
inputStream = new ByteArrayInputStream(JsonString.getBytes())
```
Is that correct? In any case, having a bit more comprehensive code sample that I could use to repro would be very helpful

**Comment by hawk-phi-tran** [comment]
I use azure-storage-blob: 12.17.1
The code sample:
`
List<Object> dataToUpload = ... ;
byte[] objectAsBytes = new ObjectMapper().writeValueAsString(dataToUpload).getBytes(StandardCharsets.UTF_8);
var inputStream = new ByteArrayInputStream(objectAsBytes);

BlockBlobClient blobClient = initClient();
blobClient.putObject(inputStream, objectAsBytes.length, true);
`

**Comment by hawk-phi-tran** [comment]
We found a bug in our code, the method that calculates the data size returns wrong value when the data is bigger than a certain amount. We know how to fix it.
Sorry for the trouble. I will close this ticket. If I find something related to the Azure SDK later, I'll open another ticket.
