### ISSUE TITLE
Cosmos should fail fast on non-retrievable exceptions rather than wait for the 30 second timeout to fail

### ISSUE THREAD

**Issue by hshukla** [Azure/azure-sdk-for-java#29529]
**Describe the bug**
On Cosmos Async Client Builder, the code goes in infinite retry(with back- off I think) until the client times out which would be default to 30secs.  In this case WebExceptionRetryPolicy gets retriable web exception, which in my opinion in valid as the given accountName/key is invalid and there is no way a caller can get out of this loop before the client timeout.

***Exception or Stack Trace***

```
2022/06/16 23:14:03.859 ERROR [RxGatewayStoreModel] [reactor-http-epoll-12] [brooklin-service] [] Network failure
io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: test.documents.azure.com/13.71.170.3:443
Caused by: java.net.ConnectException: finishConnect(..) failed: Connection refused
        at io.netty.channel.unix.Errors.throwConnectException(Errors.java:124) ~[netty-all-4.1.52.Final.jar:4.1.52.Final]
        at io.netty.channel.unix.Socket.finishConnect(Socket.java:251) ~[netty-all-4.1.52.Final.jar:4.1.52.Final]
        at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.doFinishConnect(AbstractEpollChannel.java:672) [netty-all-4.1.52.Final.jar:4.1.52.Final]
        at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:649) [netty-all-4.1.52.Final.jar:4.1.52.Final]
        at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:529) [netty-all-4.1.52.Final.jar:4.1.52.Final]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:465) [netty-all-4.1.52.Final.jar:4.1.52.Final]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) [netty-all-4.1.52.Final.jar:4.1.52.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-all-4.1.52.Final.jar:4.1.52.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.52.Final.jar:4.1.52.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.52.Final.jar:4.1.52.Final]
        at java.lang.Thread.run(Thread.java:834) [?:?]

2022/06/16 23:14:03.860 WARN [WebExceptionRetryPolicy] [reactor-http-epoll-12] [brooklin-service] [] Received retriable web exception, will retry
com.azure.cosmos.CosmosException: {"innerErrorMessage":null,"cosmosDiagnostics":{"userAgent":"azsdk-java-cosmos/4.28.0 Linux/3.10.0-1160.59.1.el7.x86_64 JRE/11.0.8","activityId":null,"requestLatencyInMs":64,"requestStartTimeUTC":"2022-06-16T23:14:03.795877Z","requestEndTimeUTC":"2022-06-16T23:14:03.860286Z","responseStatisticsList":[],"supplementalResponseStatisticsList":[],"addressResolutionStatistics":{},"regionsContacted":[],"retryContext":{"statusAndSubStatusCodes":null,"retryCount":0,"retryLatency":0},"metadataDiagnosticsContext":{"metadataDiagnosticList":null},"serializationDiagnosticsContext":{"serializationDiagnosticsList":null},"gatewayStatistics":{"sessionToken":null,"operationType":"Read","resourceType":"DatabaseAccount","statusCode":503,"subStatusCode":10001,"requestCharge":"0.0","requestTimeline":[{"eventName":"connectionAcquired","startTimeUTC":"2022-06-16T23:14:03.795889Z","durationInMicroSec":64396},{"eventName":"connectionConfigured","startTimeUTC":null,"durationInMicroSec":0},{"eventName":"requestSent","startTimeUTC":null,"durationInMicroSec":0},{"eventName":"transitTime","startTimeUTC":null,"durationInMicroSec":0},{"eventName":"received","startTimeUTC":null,"durationInMicroSec":0}],"partitionKeyRangeId":null},"systemInformation":{"usedMemory":"8985230 KB","availableMemory":"23520626 KB","systemCpuLoad":"(2022-06-16T23:13:34.512357Z 0.8%), (2022-06-16T23:13:39.512322Z 0.5%), (2022-06-16T23:13:44.512307Z 1.1%), (2022-06-16T23:13:49.512308Z 0.6%), (2022-06-16T23:13:54.512307Z 0.6%), (2022-06-16T23:13:59.512303Z 1.4%)","availableProcessors":24},"clientCfgs":{"id":3634,"machineId":"uuid:86de8075-e398-46cb-b774-1376c0b9a1fa","connectionMode":"GATEWAY","numberOfClients":1040,"connCfg":{"rntbd":null,"gw":"(cps:1000, nrto:PT1M, icto:PT1M, p:false)","other":"(ed: true, cs: false)"},"consistencyCfg":"(consistency: Session, mm: true, prgns: [])"}}}
        at com.azure.cosmos.BridgeInternal.createCosmosException(BridgeInternal.java:477) ~[azure-cosmos-4.28.0.jar:4.28.0]
        at com.azure.cosmos.implementation.RxGatewayStoreModel.lambda$toDocumentServiceResponse$3(RxGatewayStoreModel.java:393) ~[azure-cosmos-4.28.0.jar:4.28.0]
        at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94) ~[reactor-core-3.4.14.jar:3.4.14]
        at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onError(FluxMapFuseable.java:140) ~[reactor-core-3.4.14.jar:3.4.14]
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:172) ~[reactor-core-3.4.14.jar:3.4.14]
        at reactor.core.publisher.MonoSingle$SingleSubscriber.onError(MonoSingle.java:150) ~[reactor-core-3.4.14.jar:3.4.14]
        at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:106) ~[reactor-core-3.4.14.jar:3.4.14]
        at reactor.core.publisher.Operators.error(Operators.java:198) ~[reactor-core-3.4.14.jar:3.4.14]
        at reactor.core.publisher.MonoError.subscribe(MonoError.java:53) ~[reactor-core-3.4.14.jar:3.4.14]
        at reactor.core.publisher.Mono.subscribe(Mono.java:4400) ~[reactor-core-3.4.14.jar:3.4.14]
        at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103) ~[reactor-core-3.4.14.jar:3.4.14]
```

**To Reproduce**
- Give invalid accountName and or key.

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**
- I guess it is ok to consider this as non-retrievable exception and fail fast, this way client can take necessary action and free up thread/resources sooner.

**Screenshots**

**Setup (please complete the following information):**
 - IDE: IntelliJ
 - Library/Libraries: azure-cosmos-4.28.0.jar
 - Java version: 11.0.8-msft
 - App Server/Environment: [e.g. Tomcat, WildFly, Azure Function, Apache Spark, Databricks, IDE plugin or anything special]
 - Frameworks: [e.g. Spring Boot, Micronaut, Quarkus, etc] 

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by moarychan** [comment]
Hi @hshukla , this issue title is missing, could you please update it？

**Comment by TheovanKraay** [comment]
@hshukla thanks for raising this. Although technically invalid account name/key is not retriable, UnknownHostException can also occur for many other reasons. Practically speaking invalid account name/key is an issue that would normally be picked up very early in test phases and so is very unlikely to cause a production problem. Furthermore, WebExceptionPolicy is applied to all gateway related requests, and there is currently no built-in way to differentiate whether this exception happens during the initialization stage or later, so this would require quite high risk some work for what appears to be a very low impact issue. Can you articulate the scenario in which this causes a production problem for you? Perhaps we are underestimating this.

**Comment by TheovanKraay** [comment]
@hshukla any thoughts on this?
