### ISSUE TITLE
[BUG] Error when receiving messages from Azure servicebus using the claim-check pattern 

### ISSUE THREAD

**Issue by shreyask92** [Azure/azure-sdk-for-java#29564]
**Describe the bug**
Error when receiving messages from Azure servicebus, generated using the [claim-check pattern](https://docs.microsoft.com/en-us/azure/architecture/patterns/claim-check). Exception caused due to empty payload of such messages.

***Exception or Stack Trace***
```console
2022-06-14 11:33:08.519 ERROR 11084 --- [a-dev-handler-0] o.s.integration.handler.LoggingHandler   : org.springframework.messaging.converter.MessageConversionException: Cannot convert from actual payload type 'byte[]' to expected payload type 'java.lang.String' when payload is empty, 
failedMessage=GenericMessage [payload=byte[0], headers={sourceEnv=dev, DeadLetterErrorDescription=The message expired and was dead lettered., raw_id=97b6093e3f084ace927fd2dff6cd5a0a, subscriberTags='lp,x,y', azure_checkpointer=com.microsoft.azure.spring.integration.core.AzureCheckpointer@53996ab3, runId=fcpCubistTest, id=3e39f9aa-3ca1-32c5-9cee-856d870e127f, 
Diagnostic-Id=00-a8c17461fd3909a246054f3af104edbc-cba5f97490fe8b41-00, contentType=application/json, DeadLetterReason=TTLExpiredException, $attachment.blob=50e04616-c7d9-46a1-bae0-d12314857d74, timestamp=1655199188503}]
	at org.springframework.cloud.stream.config.SmartMessageMethodArgumentResolver.resolveArgument(SmartMessageMethodArgumentResolver.java:83)
	at org.springframework.messaging.handler.invocation.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:118)
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:147)
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:115)
	at org.springframework.cloud.stream.binding.StreamListenerMessageHandler.handleRequestMessage(StreamListenerMessageHandler.java:55)
	at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:136)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:56)
	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:115)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:133)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:106)
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:72)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:317)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:272)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47)
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109)
	at org.springframework.integration.endpoint.MessageProducerSupport.sendMessage(MessageProducerSupport.java:216)
	at com.microsoft.azure.spring.integration.core.AbstractInboundChannelAdapter.receiveMessage(AbstractInboundChannelAdapter.java:45)
	at com.microsoft.azure.spring.integration.servicebus.ServiceBusMessageHandler.onMessageAsync(ServiceBusMessageHandler.java:55)
	at com.microsoft.azure.servicebus.MessageAndSessionPump.lambda$null$0(MessageAndSessionPump.java:177)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

2022-06-14 11:33:08.533  INFO 11084 --- [pool-3-thread-3] c.m.a.servicebus.MessageAndSessionPump   : onMessage with message containing sequence number '1262' threw exception

org.springframework.messaging.converter.MessageConversionException: Cannot convert from actual payload type 'byte[]' to expected payload type 'java.lang.String' when payload is empty
	at org.springframework.cloud.stream.config.SmartMessageMethodArgumentResolver.resolveArgument(SmartMessageMethodArgumentResolver.java:83) ~[spring-cloud-stream-3.0.13.RELEASE.jar:3.0.13.RELEASE]
	at org.springframework.messaging.handler.invocation.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:118) ~[spring-messaging-5.3.19.jar:5.3.19]
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:147) ~[spring-messaging-5.3.19.jar:5.3.19]
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:115) ~[spring-messaging-5.3.19.jar:5.3.19]
	at org.springframework.cloud.stream.binding.StreamListenerMessageHandler.handleRequestMessage(StreamListenerMessageHandler.java:55) ~[spring-cloud-stream-3.0.13.RELEASE.jar:3.0.13.RELEASE]
	at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:136) ~[spring-integration-core-5.5.11.jar:5.5.11]
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:56) ~[spring-integration-core-5.5.11.jar:5.5.11]
	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:115) ~[spring-integration-core-5.5.11.jar:5.5.11]
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:133) ~[spring-integration-core-5.5.11.jar:5.5.11]
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:106) ~[spring-integration-core-5.5.11.jar:5.5.11]
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:72) ~[spring-integration-core-5.5.11.jar:5.5.11]
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:317) ~[spring-integration-core-5.5.11.jar:5.5.11]
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:272) ~[spring-integration-core-5.5.11.jar:5.5.11]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187) ~[spring-messaging-5.3.19.jar:5.3.19]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166) ~[spring-messaging-5.3.19.jar:5.3.19]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47) ~[spring-messaging-5.3.19.jar:5.3.19]
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109) ~[spring-messaging-5.3.19.jar:5.3.19]
	at org.springframework.integration.endpoint.MessageProducerSupport.sendMessage(MessageProducerSupport.java:216) ~[spring-integration-core-5.5.11.jar:5.5.11]
	at com.microsoft.azure.spring.integration.core.AbstractInboundChannelAdapter.receiveMessage(AbstractInboundChannelAdapter.java:45) ~[spring-integration-azure-core-1.2.5.jar:1.2.5]
	at com.microsoft.azure.spring.integration.servicebus.ServiceBusMessageHandler.onMessageAsync(ServiceBusMessageHandler.java:55) ~[spring-integration-servicebus-1.2.5.jar:1.2.5]
	at com.microsoft.azure.servicebus.MessageAndSessionPump.lambda$null$0(MessageAndSessionPump.java:177) ~[azure-servicebus-3.1.1.jar:na]
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

2022-06-14 11:33:08.538 ERROR 11084 --- [a-dev-handler-0] c.m.a.s.i.s.ServiceBusMessageHandler     : Exception encountered in phase USERCALLBACK

org.springframework.messaging.converter.MessageConversionException: Cannot convert from actual payload type 'byte[]' to expected payload type 'java.lang.String' when payload is empty
	at org.springframework.cloud.stream.config.SmartMessageMethodArgumentResolver.resolveArgument(SmartMessageMethodArgumentResolver.java:83) ~[spring-cloud-stream-3.0.13.RELEASE.jar:3.0.13.RELEASE]
	at org.springframework.messaging.handler.invocation.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:118) ~[spring-messaging-5.3.19.jar:5.3.19]
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:147) ~[spring-messaging-5.3.19.jar:5.3.19]
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:115) ~[spring-messaging-5.3.19.jar:5.3.19]
	at org.springframework.cloud.stream.binding.StreamListenerMessageHandler.handleRequestMessage(StreamListenerMessageHandler.java:55) ~[spring-cloud-stream-3.0.13.RELEASE.jar:3.0.13.RELEASE]
	at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:136) ~[spring-integration-core-5.5.11.jar:5.5.11]
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:56) ~[spring-integration-core-5.5.11.jar:5.5.11]
	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:115) ~[spring-integration-core-5.5.11.jar:5.5.11]
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:133) ~[spring-integration-core-5.5.11.jar:5.5.11]
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:106) ~[spring-integration-core-5.5.11.jar:5.5.11]
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:72) ~[spring-integration-core-5.5.11.jar:5.5.11]
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:317) ~[spring-integration-core-5.5.11.jar:5.5.11]
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:272) ~[spring-integration-core-5.5.11.jar:5.5.11]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187) ~[spring-messaging-5.3.19.jar:5.3.19]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166) ~[spring-messaging-5.3.19.jar:5.3.19]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47) ~[spring-messaging-5.3.19.jar:5.3.19]
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109) ~[spring-messaging-5.3.19.jar:5.3.19]
	at org.springframework.integration.endpoint.MessageProducerSupport.sendMessage(MessageProducerSupport.java:216) ~[spring-integration-core-5.5.11.jar:5.5.11]
	at com.microsoft.azure.spring.integration.core.AbstractInboundChannelAdapter.receiveMessage(AbstractInboundChannelAdapter.java:45) ~[spring-integration-azure-core-1.2.5.jar:1.2.5]
	at com.microsoft.azure.spring.integration.servicebus.ServiceBusMessageHandler.onMessageAsync(ServiceBusMessageHandler.java:55) ~[spring-integration-servicebus-1.2.5.jar:1.2.5]
	at com.microsoft.azure.servicebus.MessageAndSessionPump.lambda$null$0(MessageAndSessionPump.java:177) ~[azure-servicebus-3.1.1.jar:na]
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]`
```

**To Reproduce**
1. Generate message using the technique described in https://docs.microsoft.com/en-us/azure/architecture/patterns/claim-check
2. Standard config for receiving messages from azure servicebus
3. Receive the message using StreamListener

***Code Snippet***

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - OS: ubuntu
 - IDE: IntelliJ
 - Library/Libraries: spring-cloud-stream: 3.0.13.RELEASE, spring-cloud-azure-servicebus-topic-stream-binder: 1.2.5
 - Java version: 11
 - App Server/Environment: Docker/K8
 - Frameworks: Spring Boot

**Additional context**
Raise an issue with spring SDK, [GitHub Issue](https://github.com/spring-cloud/spring-cloud-stream/issues/2432), feedback from the Spring SDK team is that most likely the issue resides in the Azure SDK

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by joshfree** [comment]
Hi @shreyask92 thank you for reaching out to us on Github.  @yiliuTo could you please follow up?

**Comment by yiliuTo** [comment]
Hi @shreyask92 I will look into it, besides could you provide a sample project/code snippet to show how you send messags to Service Bus via claim-check pattern, and the way you use StreamListener to receive messages, which can help us reproduce it soon?

**Comment by yiliuTo** [comment]
Hi team @Azure/azsdk-sb-java , for the claim-check pattern of service bus, could you help to share: when messages are sent to service bus in claim-check pattern, then when a service bus consumer receives those messages from Service Bus, do the amqp messages still contain payload(body) part? I suspect the payload will be put in Storage Blob, thus those service bus amqp messages won't contain it

**Comment by yiliuTo** [comment]
After checking with Service Bus service team, it's the expected behavior to have empty-payload messages in claim-check pattern. Thus this issue is due that Spring Cloud Stream doesn't allow it, see [here](https://github.com/spring-cloud/spring-cloud-stream/issues/2518) for more details. The issue has been created for Spring Cloud Stream to track.

**Comment by shreyask92** [comment]
@yiliuTo I had already raised an issue with spring cloud stream (https://github.com/spring-cloud/spring-cloud-stream/issues/2432)[link]

**Comment by yiliuTo** [comment]
@shreyask92 , since empty payload messages are currently not allowed in Spring Messaging, we will use #31422 to discuss the how to support such case. Besides, instead of using `@StreamListener`, using java functional programming model like `Consumer` can bypass the check of empty payload, which may be considered as a workaround currently.
