### ISSUE TITLE
Batch live test failing

### ISSUE THREAD

**Issue by weshaggard** [Azure/azure-sdk-for-java#2963]
```
[ERROR] Tests run: 11, Failures: 2, Errors: 2, Skipped: 1, Time elapsed: 1,948.527 s <<< FAILURE! - in com.microsoft.azure.batch.PoolTests
[ERROR] canCRUDLowPriPaaSPool(com.microsoft.azure.batch.PoolTests)  Time elapsed: 300.44 s  <<< FAILURE!
java.lang.AssertionError: The pool did not reach a steady state in the allotted time
	at com.microsoft.azure.batch.PoolTests.canCRUDLowPriPaaSPool(PoolTests.java:405)

[ERROR] canCRUDLowPriPaaSPool(com.microsoft.azure.batch.PoolTests)  Time elapsed: 180.209 s  <<< ERROR!
com.microsoft.azure.batch.protocol.models.BatchErrorException: 
Status code 404, {
  "odata.metadata":"https://***.centralus.batch.azure.com/$metadata#Microsoft.Azure.Batch.Protocol.Entities.Container.errors/@Element","code":"PoolNotFound","message":{
    "lang":"en-US","value":"The specified pool does not exist.\nRequestId:8e167f79-95de-47a4-a998-497b8951430c\nTime:2019-02-20T12:29:35.7898757Z"
  }
}
	at com.microsoft.azure.batch.PoolTests.canCRUDLowPriPaaSPool(PoolTests.java:393)

[ERROR] canCRUDLowPriPaaSPool(com.microsoft.azure.batch.PoolTests)  Time elapsed: 300.611 s  <<< FAILURE!
java.lang.AssertionError: The pool did not reach a steady state in the allotted time
	at com.microsoft.azure.batch.PoolTests.canCRUDLowPriPaaSPool(PoolTests.java:405)

[ERROR] canCRUDLowPriPaaSPool(com.microsoft.azure.batch.PoolTests)  Time elapsed: 270.284 s  <<< ERROR!
com.microsoft.azure.batch.protocol.models.BatchErrorException: 
Status code 404, {
  "odata.metadata":"https://***.centralus.batch.azure.com/$metadata#Microsoft.Azure.Batch.Protocol.Entities.Container.errors/@Element","code":"PoolNotFound","message":{
    "lang":"en-US","value":"The specified pool does not exist.\nRequestId:b2886e5b-ade7-4fa4-a74f-7a40c1fad5ce\nTime:2019-02-20T12:39:06.9568648Z"
  }
}
	at com.microsoft.azure.batch.PoolTests.canCRUDLowPriPaaSPool(PoolTests.java:393)

Expect exception java.lang.RuntimeException: java.net.UnknownHostException: noexistaccount.westus.batch.azure.com[ERROR] Errors: 
[ERROR] com.microsoft.azure.batch.PoolTests.canCRUDLowPriPaaSPool(com.microsoft.azure.batch.PoolTests)
[ERROR]   Run 1: PoolTests.canCRUDLowPriPaaSPool:405 The pool did not reach a steady state in the allotted time
[ERROR]   Run 2: PoolTests.canCRUDLowPriPaaSPool:393 � BatchError Status code 404, {
  "odata....
[ERROR]   Run 3: PoolTests.canCRUDLowPriPaaSPool:405 The pool did not reach a steady state in the allotted time
[ERROR]   Run 4: PoolTests.canCRUDLowPriPaaSPool:393 � BatchError Status code 404, {
  "odata....
[ERROR] Tests run: 23, Failures: 0, Errors: 1, Skipped: 1
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.1:test (default-test) on project azure-batch: There are test failures.
[ERROR] 
[ERROR] Please refer to D:\a\1\s\.\batch\data-plane\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

There have been a number of test runs that fail with this error. See below for a couple examples:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=5217
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=5308

**Comment by g2vinay** [comment]
PR with the fix was successfully merged.
Last three scheduled builds have succeeded.
