### ISSUE TITLE
[QUERY] What should I do with the "Cannot create receive link from a closed session" AmqpException

### ISSUE THREAD

**Issue by mzesri** [Azure/azure-sdk-for-java#29705]
**Query/Question**
We have a user running into this AmqpException recently while consuming from an EventHub topic.  This error shows up in the error handler.  

```
com.azure.core.amqp.exception.AmqpException: connectionId[MF_3a9715_1656513613229] sessionName[xxx/ConsumerGroups/yyy/Partitions/7] entityPath[xxx/ConsumerGroups/yyy/Partitions/7] linkName[7_896631_1656513613230] Cannot create receive link from a closed session., errorContext[NAMESPACE: aaa-bbb-ehub.servicebus.windows.net. ERROR CONTEXT: N/A, PATH: xxx/ConsumerGroups/yyy/Partitions/7]
	at com.azure.core.amqp.implementation.ReactorSession.createConsumer(ReactorSession.java:336)
	at com.azure.messaging.eventhubs.implementation.EventHubReactorSession.createConsumer(EventHubReactorSession.java:100)
	at com.azure.messaging.eventhubs.implementation.EventHubReactorAmqpConnection.lambda$createReceiveLink$1(EventHubReactorAmqpConnection.java:125)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:125)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:127)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:249)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.complete(MonoIgnoreThen.java:284)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onNext(MonoIgnoreThen.java:187)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:232)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:203)
	at reactor.core.publisher.SerializedSubscriber.onComplete(SerializedSubscriber.java:146)
	at reactor.core.publisher.SerializedSubscriber.onComplete(SerializedSubscriber.java:146)
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.onComplete(FluxTimeout.java:234)
	at reactor.core.publisher.MonoNext$NextSubscriber.onComplete(MonoNext.java:102)
	at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:83)
	at reactor.core.publisher.FluxFilterFuseable$FilterFuseableSubscriber.onNext(FluxFilterFuseable.java:118)
	at reactor.core.publisher.FluxReplay$SizeBoundReplayBuffer.replayNormal(FluxReplay.java:814)
	at reactor.core.publisher.FluxReplay$SizeBoundReplayBuffer.replay(FluxReplay.java:898)
	at reactor.core.publisher.FluxReplay$ReplayInner.request(FluxReplay.java:1465)
	at reactor.core.publisher.FluxFilterFuseable$FilterFuseableSubscriber.request(FluxFilterFuseable.java:191)
	at reactor.core.publisher.MonoNext$NextSubscriber.request(MonoNext.java:108)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.request(Operators.java:2158)
	at reactor.core.publisher.SerializedSubscriber.request(SerializedSubscriber.java:151)
	at reactor.core.publisher.SerializedSubscriber.request(SerializedSubscriber.java:151)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onSubscribe(MonoIgnoreThen.java:134)
	at reactor.core.publisher.SerializedSubscriber.onSubscribe(SerializedSubscriber.java:65)
	at reactor.core.publisher.SerializedSubscriber.onSubscribe(SerializedSubscriber.java:65)
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.onSubscribe(FluxTimeout.java:154)
	at reactor.core.publisher.MonoNext$NextSubscriber.onSubscribe(MonoNext.java:70)
	at reactor.core.publisher.FluxFilterFuseable$FilterFuseableSubscriber.onSubscribe(FluxFilterFuseable.java:87)
	at reactor.core.publisher.FluxReplay.subscribeOrReturn(FluxReplay.java:1114)
	at reactor.core.publisher.FluxReplay.subscribe(FluxReplay.java:1086)
	at reactor.core.publisher.FluxAutoConnectFuseable.subscribe(FluxAutoConnectFuseable.java:61)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4338)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:255)
	at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:127)
	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:180)
	at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onNext(FluxHide.java:137)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.complete(MonoIgnoreThen.java:284)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onNext(MonoIgnoreThen.java:187)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:232)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:203)
	at reactor.core.publisher.SerializedSubscriber.onComplete(SerializedSubscriber.java:146)
	at reactor.core.publisher.SerializedSubscriber.onComplete(SerializedSubscriber.java:146)
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.onComplete(FluxTimeout.java:234)
	at reactor.core.publisher.MonoNext$NextSubscriber.onComplete(MonoNext.java:102)
	at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:83)
	at reactor.core.publisher.FluxFilterFuseable$FilterFuseableSubscriber.onNext(FluxFilterFuseable.java:118)
	at reactor.core.publisher.FluxReplay$SizeBoundReplayBuffer.replayNormal(FluxReplay.java:814)
	at reactor.core.publisher.FluxReplay$SizeBoundReplayBuffer.replay(FluxReplay.java:898)
	at reactor.core.publisher.FluxReplay$ReplayInner.request(FluxReplay.java:1465)
	at reactor.core.publisher.FluxFilterFuseable$FilterFuseableSubscriber.request(FluxFilterFuseable.java:191)
	at reactor.core.publisher.MonoNext$NextSubscriber.request(MonoNext.java:108)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.request(Operators.java:2158)
	at reactor.core.publisher.SerializedSubscriber.request(SerializedSubscriber.java:151)
	at reactor.core.publisher.SerializedSubscriber.request(SerializedSubscriber.java:151)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onSubscribe(MonoIgnoreThen.java:134)
	at reactor.core.publisher.SerializedSubscriber.onSubscribe(SerializedSubscriber.java:65)
	at reactor.core.publisher.SerializedSubscriber.onSubscribe(SerializedSubscriber.java:65)
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.onSubscribe(FluxTimeout.java:154)
	at reactor.core.publisher.MonoNext$NextSubscriber.onSubscribe(MonoNext.java:70)
	at reactor.core.publisher.FluxFilterFuseable$FilterFuseableSubscriber.onSubscribe(FluxFilterFuseable.java:87)
	at reactor.core.publisher.FluxReplay.subscribeOrReturn(FluxReplay.java:1114)
	at reactor.core.publisher.FluxReplay.subscribe(FluxReplay.java:1086)
	at reactor.core.publisher.FluxAutoConnectFuseable.subscribe(FluxAutoConnectFuseable.java:61)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4338)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:255)
	at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4338)
	at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:203)
	at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
	at com.azure.core.amqp.implementation.AmqpChannelProcessor.subscribe(AmqpChannelProcessor.java:251)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
	at reactor.core.publisher.FluxRepeatPredicate$RepeatPredicateSubscriber.resubscribe(FluxRepeatPredicate.java:120)
	at reactor.core.publisher.FluxRepeatPredicate$RepeatPredicateSubscriber.onComplete(FluxRepeatPredicate.java:101)
	at reactor.core.publisher.Operators$MonoSubscriber.request(Operators.java:1907)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.request(Operators.java:2158)
	at com.azure.messaging.eventhubs.implementation.AmqpReceiveLinkProcessor.requestUpstream(AmqpReceiveLinkProcessor.java:421)
	at com.azure.messaging.eventhubs.implementation.AmqpReceiveLinkProcessor.lambda$onNext$7(AmqpReceiveLinkProcessor.java:254)
	at reactor.core.publisher.LambdaSubscriber.onComplete(LambdaSubscriber.java:132)
	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.onComplete(FluxSubscribeOn.java:166)
	at reactor.core.publisher.FluxDistinct$DistinctFuseableSubscriber.onComplete(FluxDistinct.java:501)
	at reactor.core.publisher.FluxReplay$SizeBoundReplayBuffer.replayNormal(FluxReplay.java:805)
	at reactor.core.publisher.FluxReplay$SizeBoundReplayBuffer.replay(FluxReplay.java:898)
	at reactor.core.publisher.FluxReplay$ReplaySubscriber.onComplete(FluxReplay.java:1273)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:260)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:260)
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:142)
	at reactor.core.publisher.FluxDistinctUntilChanged$DistinctUntilChangedSubscriber.onComplete(FluxDistinctUntilChanged.java:173)
	at reactor.core.publisher.FluxReplay$SizeBoundReplayBuffer.replayNormal(FluxReplay.java:805)
	at reactor.core.publisher.FluxReplay$SizeBoundReplayBuffer.replay(FluxReplay.java:898)
	at reactor.core.publisher.ReplayProcessor.tryEmitComplete(ReplayProcessor.java:465)
	at reactor.core.publisher.SinkManySerialized.tryEmitComplete(SinkManySerialized.java:64)
	at reactor.core.publisher.InternalManySink.emitComplete(InternalManySink.java:68)
	at com.azure.core.amqp.implementation.handler.Handler.close(Handler.java:132)
	at com.azure.core.amqp.implementation.handler.LinkHandler.onLinkFinal(LinkHandler.java:78)
	at com.azure.core.amqp.implementation.handler.ReceiveLinkHandler.onLinkFinal(ReceiveLinkHandler.java:202)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:182)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291)
	at com.azure.core.amqp.implementation.ReactorExecutor.run(ReactorExecutor.java:86)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

We were using the EventProcessorClient to read.  This is how we created the client:

```
eventProcessorClient = new EventProcessorClientBuilder()
      .connectionString(connectionStr)
      .consumerGroup(consumerGroup)
      .processEventBatch(processPartitionBatch, BATCH_SIZE, Duration.ofSeconds(MAX_WAIT_SECOND))
      .processError(handleError)
      .processPartitionClose(handlePartitionClose)
      .checkpointStore(checkpointStore)
      .trackLastEnqueuedEventProperties(true)
      .buildEventProcessorClient()
```

In our error handler, we restart the application if we run into errors that are not on the ignore list.  I did some research on this error message but couldn't find any info/solution specific to this error.  I am wondering if you could tell me what caused this error and what we should do when this happens.

**Setup (please complete the following information if applicable):**
 - OS: Linux
 - IDE: IntelliJ
 - Library/Libraries: 
    azure-messaging-eventhubs:5.10.1
    azure-core-amqp:2.3.2
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by joshfree** [comment]
Hi @mzesri thank you for posting this question on GitHub.  You can find the Event Hubs troubleshooting guide in the repo here: https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/eventhubs/azure-messaging-eventhubs/TROUBLESHOOTING.md which has more details on investigating and handling this exception.

Someone from the `Event Hubs SDK` team will follow up with you shortly.  /cc @Azure/azsdk-sb-java

**Comment by ki1729** [comment]
@mzesri Can you please share a code snippet of what happens in your error handler and the debug logs around the time window when you see this exception (starting from when the error handler is invoked)?

**Comment by mzesri** [comment]
@ki1729, you mean the Azure Event Hub logs around the time window when we see this exception?  I don't think we have that.  We provide a service for people to connect to their Event Hubs.  So, we would have to ask them for the logs when this happens.  We haven't seen this error in our logs since then.  Next time when it happens, I will ask the users to send me event hub logs.  

As for as the error handler code is concerned, you have seen how I used the error handler in the original post, the errorhandler is very simple:
```
  private val handleError: Consumer[ErrorContext] = errorContext => {
    val error = errorContext.getThrowable
    logger.userError(error, LogKey.FEEDS__AZURE_EVENT_HUB_ON_ERROR)
    updateCheckpoint(None, logCheckpoints = true)
    System.exit(1)
  }
```
logger.userError is our custom error handling code.  It is responsible for the error to be printed in the log file, like those in my original post.  After logging the error, we then update the check point and exists the application.

**Comment by conniey** [comment]
When there is an error that occurs in the library, it propagates that upstream irrespective of whether or not we retry. In this case, we would recreate the underlying consumer client and continue consuming events. You would take no action on this exception,
