### ISSUE TITLE
[BUG] Taking snapshot of data disk through SDK fails.

### ISSUE THREAD

**Issue by kmrgaurav11235** [Azure/azure-sdk-for-java#29811]
**Describe the bug**
Taking snapshot of data disk fails.
This is the method that causes the issue:
https://github.com/Azure/azure-sdk-for-java/blob/3f31d68eed6fbe11516ca3afe3955c8840a6e974/sdk/resourcemanager/azure-resourcemanager-compute/src/main/java/com/azure/resourcemanager/compute/models/Snapshot.java#L239

***Exception or Stack Trace***

```
2022-06-29T15:47:45.231Z [tsch:aims-4] INFO  c.v.h.s.a.o.s.SnapshotsOperationImpl.logErrorAsInfo - ERROR: SKU StandardSSD_LRS is not supported for resource type Snapshot in this region. Supported SKUs for this region are Premium_LRS,Standard_LRS,Standard_ZRS; ErrorDetail{code='InvalidParameter', message='SKU StandardSSD_LRS is not supported for resource type Snapshot in this region. Supported SKUs for this region are Premium_LRS,Standard_LRS,Standard_ZRS', detail='Azure failed with errorCode: InvalidParameter and message: SKU StandardSSD_LRS is not supported for resource type Snapshot in this region. Supported SKUs for this region are Premium_LRS,Standard_LRS,Standard_ZRS', domain='SG_AZURE', severity='Error', parameters={errorMessage=SKU StandardSSD_LRS is not supported for resource type Snapshot in this region. Supported SKUs for this region are Premium_LRS,Standard_LRS,Standard_ZRS, errorCode=InvalidParameter}, cause=null}
2022-06-29T15:47:45.232Z [tsch:aims-4] ERROR c.v.h.s.aims.service.ImagesService.takeSnapshotsOfManagedDisksAttachedToVm - Failed to take snapshots of managed disks attached to VM kg-04-1-0-0 in resource group vmw-hcs-62bac0d5a12ef8556e451d5b-base-vms
com.vmware.horizon.sg.azurerm.error.AzureException: SKU StandardSSD_LRS is not supported for resource type Snapshot in this region. Supported SKUs for this region are Premium_LRS,Standard_LRS,Standard_ZRS
	at com.vmware.horizon.sg.azurerm.operations.snapshots.SnapshotsOperationImpl.createFromDataDisk(SnapshotsOperationImpl.java:124)
	at com.vmware.horizon.servicegateway.aims.service.ImagesService.takeSnapshotsOfManagedDisksAttachedToVm(ImagesService.java:2699)
	at com.vmware.horizon.servicegateway.aims.tasks.publish.BackupVMTask.run(BackupVMTask.java:104)
	at com.vmware.horizon.sg.common.scheduler.impl.redis.TaskRunner.runImpl(TaskRunner.java:84)
	at com.vmware.horizon.sg.common.scheduler.impl.redis.TaskRunner.run(TaskRunner.java:66)
	at com.vmware.horizon.sg.common.scheduler.impl.redis.TaskWrapperImpl.runImpl(TaskWrapperImpl.java:280)
	at com.vmware.horizon.sg.common.scheduler.impl.redis.TaskWrapperImpl.runInTransaction(TaskWrapperImpl.java:176)
	at com.vmware.horizon.sg.common.scheduler.impl.redis.TaskWrapperImpl.run(TaskWrapperImpl.java:102)
	at com.vmware.horizon.sg.common.scheduler.impl.redis.TaskWrapperNormal.run(TaskWrapperNormal.java:47)
	at org.redisson.executor.TasksRunnerService.executeRunnable(TasksRunnerService.java:340)
	at org.redisson.executor.TasksRunnerService.executeRunnable(TasksRunnerService.java:352)
	at org.redisson.executor.TasksRunnerService.scheduleRunnable(TasksRunnerService.java:201)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.redisson.executor.RedissonExecutorRemoteService.invokeMethod(RedissonExecutorRemoteService.java:106)
	at org.redisson.RedissonRemoteService.lambda$executeMethod$11(RedissonRemoteService.java:460)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.azure.core.management.exception.ManagementException: Status code 400, "{
  "error": {
    "code": "InvalidParameter",
    "message": "SKU StandardSSD_LRS is not supported for resource type Snapshot in this region. Supported SKUs for this region are Premium_LRS,Standard_LRS,Standard_ZRS",
    "target": "sku"
  }
}"
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.azure.core.http.rest.RestProxy.instantiateUnexpectedException(RestProxy.java:389)
	at com.azure.core.http.rest.RestProxy.lambda$ensureExpectedStatus$7(RestProxy.java:444)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:125)
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74)
```

**To Reproduce**
Create a VM in Azure. Add data disks to it. I used "West US 2" region and default disk type -- Standard SSD LRS. Take a snapshot using Azure SDK (code snippet below). But got an exception.

***Code Snippet***

```
public @NonNull Snapshot createFromDataDisk(@NonNull String snapshotName,
                                                @NonNull String region,
                                                @NonNull String resourceGroupName,
                                                @NonNull Disk disk) throws AzureException {
        try {
            Snapshot snapshot = inner.snapshots()
                    .define(snapshotName)
                    .withRegion(region)
                    .withExistingResourceGroup(resourceGroupName)
                    .withDataFromDisk(disk)
                    .create();

            return SnapshotImpl.of(snapshot);
        } catch (Exception ex) {
            throw AzureException.fromAzureError(ex)
                    .logErrorAsInfo(log);
        }
    }
```

PS: Classes used are com.azure.resourcemanager.compute.models.Snapshot and com.azure.resourcemanager.compute.models.Disk

**Expected behavior**
Should be able to take snapshots successfully

**Screenshots**
Will add below

**Setup (please complete the following information):**
 - OS: [e.g. iOS] OS of created VM is Windows
 - IDE: [e.g. IntelliJ] IntelliJ
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)] azure-resourcemanager-compute-2.11.0.jar
 - Java version: [e.g. 8] 11
 - App Server/Environment: [e.g. Tomcat, WildFly, Azure Function, Apache Spark, Databricks, IDE plugin or anything special] Java Sprint boot
 - Frameworks: [e.g. Spring Boot, Micronaut, Quarkus, etc]  Spring Boot

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by kmrgaurav11235** [comment]
Screenshots
<img width="1567" alt="VM2" src="https://user-images.githubusercontent.com/27720046/177512695-454038cd-24cc-4d5e-b0ca-889e8ade2b1c.png">
<img width="1557" alt="VM1" src="https://user-images.githubusercontent.com/27720046/177512709-ecf3adef-7f9f-4264-aff1-f7771550195a.png">

**Comment by weidongxu-microsoft** [comment]
@kmrgaurav11235 

This error message is from service
```
Status code 400, "{
  "error": {
    "code": "InvalidParameter",
    "message": "SKU StandardSSD_LRS is not supported for resource type Snapshot in this region. Supported SKUs for this region are Premium_LRS,Standard_LRS,Standard_ZRS",
    "target": "sku"
  }
}"
```

Are you sure StandardSSD_LRS is allowed for Snapshot?

**Comment by kmrgaurav11235** [comment]
Hi,
When I created the data disk for the VM, I have used the default type that was available with Azure. So, I am using the default data disk type that Azure provides.
Also, I am not passing on the SKU type to the snapshot creation method in SDK. I just passed the parameter of "Disk" type to the method as you can see in the code snippet above. One would assume that once the Disk is passed, the SDK will be able to create a Snapshot of appropriate SKU type.
The Azure portal UI works similarly. When I click the "Create Snapshot" button is the Disk page, it creates a snapshot of appropriate type according to the SKU type of Disk.

**Comment by XiaofeiCao** [comment]
It's due to a mismatch between `SnapshotStorageAccountTypes`and `DiskStorageAccountTypes`:
https://github.com/Azure/azure-sdk-for-java/blob/3161ed5b6381b56c57f519978ed60c36d7f875f9/sdk/resourcemanager/azure-resourcemanager-compute/src/main/java/com/azure/resourcemanager/compute/implementation/SnapshotImpl.java#L265-L267

`withSku`:

https://github.com/Azure/azure-sdk-for-java/blob/3161ed5b6381b56c57f519978ed60c36d7f875f9/sdk/resourcemanager/azure-resourcemanager-compute/src/main/java/com/azure/resourcemanager/compute/implementation/SnapshotImpl.java#L287-L292

@weidongxu-microsoft I think we can remove the `withSku` assignment in `withDataFromDisk(Disk disk)` implementation, since snapshot sku has little to do with disk sku.

**Comment by XiaofeiCao** [comment]
I think snapshot sku is independent of disk sku. I can create snapshot with `STANDARD_LRS` for disk of sku `PREMIUM_LRS`. 

If no skus are provided during snapshot creation, `STANDARD_LRS` will be chosen by default. 

> should we provide an overload for user e.g. (Disk managedDisk, SnapshotSku sku)?

If the user wants to set sku for snapshot, he can do 
```java
.withDataFromDisk(Disk managedDisk)
.withSku(Snapshot SnapshotStorageAccountTypes)
```
Probably no need for the overload?

**Comment by weidongxu-microsoft** [comment]
Look good. Let us do this.

**Comment by XiaofeiCao** [comment]
Close as 2.18.0 has released and the issue should be resolved.
