### ISSUE TITLE
[BUG] SDK is not able to talk to Cosmos DB instance when using private link

### ISSUE THREAD

**Issue by k-anshul** [Azure/azure-sdk-for-java#30045]
**Describe the bug**
I upgraded the SDK from 4.7.0 to 4.31.0. Post the upgrade the SDK is not able to communicate to privatelink endpoint.
However when using the global endpoint it works.

***Exception or Stack Trace***
Caused by: java.lang.RuntimeException: Client initialization failed. Check if the endpoint is reachable and if your auth token is valid. More info: https://aka.ms/cosmosdb-tsg-service-unavailable-java
	at com.azure.cosmos.implementation.RxDocumentClientImpl.initializeGatewayConfigurationReader(RxDocumentClientImpl.java:445)
	at com.azure.cosmos.implementation.RxDocumentClientImpl.init(RxDocumentClientImpl.java:480)
	at com.azure.cosmos.implementation.AsyncDocumentClient$Builder.build(AsyncDocumentClient.java:259)
	at com.azure.cosmos.CosmosAsyncClient.<init>(CosmosAsyncClient.java:129)
	at com.azure.cosmos.CosmosClientBuilder.buildAsyncClient(CosmosClientBuilder.java:779)

**To Reproduce**
Use private link for cosmos db

**Expected behavior**
SDK should be able to communicate to private link

**Setup (please complete the following information):**
 - OS: Linux
 - Library/Libraries: com.azure:azure-cosmos:4.31.0 
 - Java version: JDK 11
 - Frameworks: SpringBoot

**Additional context**
Was working fine on version 4.7.0

**Comment by code1305** [comment]
Hi Team

Did you get a chance to look into this ?

Thanks

**Comment by TheovanKraay** [comment]
@k-anshul thank you for raising this. We will investigate. If your upgrade need is time-sensitive, I would suggest also raising a support case.

**Comment by k-anshul** [comment]
We had incorrectly configured our internal endpoint which was breaking TLS handshake(Somehow that was working with older version).

The resolution is outlined in the comments here :  https://github.com/MicrosoftDocs/azure-docs/issues/52778#issuecomment-624181061
