### ISSUE TITLE
[QUERY] How to Stop a Service Bus Client And Delete Subscription Without Error

### ISSUE THREAD

**Issue by azizabah** [Azure/azure-sdk-for-java#30105]
**Query/Question**
I currently have code that creates many ServiceBusProcessorClients using ServiceBusClientBuilder. We have a use case to stop consuming messages from a subscription and then delete the subscription (to avoid data accumulating) while the service is still running. To implement this, I grabbed my reference to the appropriate ServiceBusProcessorClient and called its .close() method and confirmed that messages were no longer being consumed. I then proceeded to delete the subscription and received a large number of error messages sent to my errorHandler defined when using the ServiceBusClientBuilder:
```
Caused by: java.lang.IllegalStateException: Cannot add credits to closed link: topic/sub
	at com.azure.core.amqp.implementation.ReactorReceiver.addCredits(ReactorReceiver.java:176)
	at com.azure.messaging.servicebus.implementation.ServiceBusReceiveLinkProcessor.checkAndAddCredits(ServiceBusReceiveLinkProcessor.java:535)
	at com.azure.messaging.servicebus.implementation.ServiceBusReceiveLinkProcessor.onNext(ServiceBusReceiveLinkProcessor.java:242)
	at com.azure.messaging.servicebus.implementation.ServiceBusReceiveLinkProcessor.onNext(ServiceBusReceiveLinkProcessor.java:43)
	at reactor.core.publisher.FluxRepeatPredicate$RepeatPredicateSubscriber.onNext(FluxRepeatPredicate.java:86)
	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:180)
	at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:99)
	at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.onNext(FluxRetryWhen.java:174)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:210)
	at reactor.core.publisher.Operators$MonoSubscriber.request(Operators.java:1906)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.request(FluxPeekFuseable.java:144)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.request(Operators.java:2158)
	at reactor.core.publisher.SerializedSubscriber.request(SerializedSubscriber.java:151)
	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.request(MonoPeekTerminal.java:139)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.request(Operators.java:2158)
	at com.azure.messaging.servicebus.implementation.ServiceBusReceiveLinkProcessor.requestUpstream(ServiceBusReceiveLinkProcessor.java:413)
	at com.azure.messaging.servicebus.implementation.ServiceBusReceiveLinkProcessor.lambda$onError$6(ServiceBusReceiveLinkProcessor.java:319)
	at reactor.core.publisher.LambdaMonoSubscriber.onNext(LambdaMonoSubscriber.java:171)
	at reactor.core.publisher.MonoDelay$MonoDelayRunnable.propagateDelay(MonoDelay.java:271)
	at reactor.core.publisher.MonoDelay$MonoDelayRunnable.run(MonoDelay.java:286)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2022-07-22 15:44:18,592 ERROR [boundedElastic-21] com.services.impl.ErrorHandler: The messaging entity 'topic/sub' could not be found. To know more visit https://aka.ms/sbResourceMgrExceptions.  TrackingId:f9efe7cf-501b-4d81-843d-2ebc21dff8ef_B24, SystemTracker:topic:Topic:topic/sub, Timestamp:2022-07-22T19:44:12 TrackingId:766faf7633cb453c97a92ee45a2535f7_G8, SystemTracker:gateway7, Timestamp:2022-07-22T19:44:12, errorContext[NAMESPACE: topic.servicebus.windows.net. ERROR CONTEXT: N/A, PATH: topic/sub, REFERENCE_ID: topic/sub, LINK_CREDIT: 0]
com.azure.messaging.servicebus.ServiceBusException: The messaging entity 'topic:Topic:topic/sub' could not be found. To know more visit https://aka.ms/sbResourceMgrExceptions.  TrackingId:f9efe7cf-501b-4d81-843d-2ebc21dff8ef_B24, SystemTracker:topic/sub, Timestamp:2022-07-22T19:44:12 TrackingId:766faf7633cb453c97a92ee45a2535f7_G8, SystemTracker:gateway7, Timestamp:2022-07-22T19:44:12, errorContext[NAMESPACE: topic.servicebus.windows.net. ERROR CONTEXT: N/A, PATH: topic/sub, REFERENCE_ID: topic/sub, LINK_CREDIT: 0]
	at com.azure.messaging.servicebus.ServiceBusReceiverAsyncClient.mapError(ServiceBusReceiverAsyncClient.java:1496)
	at com.azure.messaging.servicebus.ServiceBusReceiverAsyncClient.lambda$receiveMessagesWithContext$18(ServiceBusReceiverAsyncClient.java:799)
	at reactor.core.publisher.Flux.lambda$onErrorMap$28(Flux.java:6911)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.doError(FluxPublishOn.java:511)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.checkTerminated(FluxPublishOn.java:549)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runAsync(FluxPublishOn.java:432)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:527)
	at reactor.core.scheduler.ImmediateScheduler$ImmediateSchedulerWorker.schedule(ImmediateScheduler.java:84)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.trySchedule(FluxPublishOn.java:312)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.onError(FluxPublishOn.java:248)
	at com.azure.messaging.servicebus.FluxAutoComplete$AutoCompleteSubscriber.hookOnError(FluxAutoComplete.java:110)
	at reactor.core.publisher.BaseSubscriber.onError(BaseSubscriber.java:180)
	at com.azure.messaging.servicebus.FluxAutoLockRenew$LockRenewSubscriber.hookOnError(FluxAutoLockRenew.java:121)
	at reactor.core.publisher.BaseSubscriber.onError(BaseSubscriber.java:180)
	at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:132)
	at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:132)
	at com.azure.messaging.servicebus.implementation.ServiceBusReceiveLinkProcessor.onError(ServiceBusReceiveLinkProcessor.java:332)
	at com.azure.messaging.servicebus.implementation.ServiceBusReceiveLinkProcessor.lambda$onNext$4(ServiceBusReceiveLinkProcessor.java:221)
	at reactor.core.publisher.LambdaSubscriber.onError(LambdaSubscriber.java:149)
	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.onError(FluxSubscribeOn.java:157)
	at reactor.core.publisher.FluxDistinct$DistinctFuseableSubscriber.onError(FluxDistinct.java:490)
	at reactor.core.publisher.FluxReplay$SizeBoundReplayBuffer.replayNormal(FluxReplay.java:865)
	at reactor.core.publisher.FluxReplay$SizeBoundReplayBuffer.replay(FluxReplay.java:965)
	at reactor.core.publisher.FluxReplay$ReplayInner.request(FluxReplay.java:1711)
	at reactor.core.publisher.FluxDistinct$DistinctFuseableSubscriber.request(FluxDistinct.java:511)
	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.requestUpstream(FluxSubscribeOn.java:131)
	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.onSubscribe(FluxSubscribeOn.java:124)
	at reactor.core.publisher.FluxDistinct$DistinctFuseableSubscriber.onSubscribe(FluxDistinct.java:428)
	at reactor.core.publisher.FluxReplay.subscribeOrReturn(FluxReplay.java:1181)
	at reactor.core.publisher.FluxReplay.subscribe(FluxReplay.java:1153)
	at reactor.core.publisher.FluxAutoConnectFuseable.subscribe(FluxAutoConnectFuseable.java:61)
	at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62)
	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.run(FluxSubscribeOn.java:194)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.azure.core.amqp.exception.AmqpException: The messaging entity 'topic/sub' could not be found. To know more visit https://aka.ms/sbResourceMgrExceptions.  TrackingId:f9efe7cf-501b-4d81-843d-2ebc21dff8ef_B24, SystemTracker:topic/sub, Timestamp:2022-07-22T19:44:12 TrackingId:766faf7633cb453c97a92ee45a2535f7_G8, SystemTracker:gateway7, Timestamp:2022-07-22T19:44:12, errorContext[NAMESPACE: topic.servicebus.windows.net. ERROR CONTEXT: N/A, PATH: topic/sub, REFERENCE_ID: topic/sub, LINK_CREDIT: 0]
	at com.azure.core.amqp.implementation.ExceptionUtil.distinguishNotFound(ExceptionUtil.java:123)
	at com.azure.core.amqp.implementation.ExceptionUtil.toException(ExceptionUtil.java:78)
	at com.azure.core.amqp.implementation.handler.LinkHandler.handleRemoteLinkClosed(LinkHandler.java:110)
	at com.azure.core.amqp.implementation.handler.LinkHandler.onLinkRemoteClose(LinkHandler.java:61)
	at com.azure.core.amqp.implementation.handler.ReceiveLinkHandler.onLinkRemoteClose(ReceiveLinkHandler.java:193)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:176)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291)
	at com.azure.core.amqp.implementation.ReactorExecutor.run(ReactorExecutor.java:92)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	... 5 common frames omitted
```

I am using the ServiceBusAdministrationClient to both create and delete subscriptions on a topic.

***Why is this not a Bug or a feature Request?***
It's possible this is a bug but it's also possible I'm just not closing it the way it was intended. My expectation is that by calling .close() it would no longer check or care about the existence of the subscription.

**Setup (please complete the following information if applicable):**
Azure SDK 1.1.0 BOM
Java 11
com.azure:azure-messaging-servicebus library. 
Spring Boot 2.6.7
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Query Added
- [X] Setup information Added

**Comment by ZejiaJiang** [comment]
Hi @azizabah , 

When we call the method to close `ServiceBusProcessorClient` it will take some time, because there are several subscriptions in the client need to be closed. So I'm not sure how long did you wait after calling the `close()` method, maybe you could try to wait longer.

>  I then proceeded to delete the subscription and received a large number of error messages sent to my errorHandler defined when using the ServiceBusClientBuilder

I didn't really get when using the ServiceBusClientBuilder, do you mean that you are using the builder to build a new client after delete the subscription? If so, I'd like to know the new subscription name is different from before? Maybe you can give some more information, could you please provide some code snippet about your builder and client? The easiest way is that you can use a new builder to build new client.

**Comment by azizabah** [comment]
Thanks @ZejiaJiang . I was referencing code that looks like this:
```
val client = ServiceBusClientBuilder()
            .connectionString(configProperties.connectionString)
            .processor()
            .topicName(topicName)
            .subscriptionName(subscriptionName)
            .processMessage(consumer)
            .processError(ErrorHandler(subscriptionName))
            .buildProcessorClient()
```

So when client.stop() is called and then the subscription is deleted, many errors flow to my ErrorHandler() class referenced here which just logs them out. I am not building a client after deleting the subscription since I just deleted the subscription and don't need it anymore. 


> Hi @azizabah ,
> 
> When we call the method to close `ServiceBusProcessorClient` it will take some time, because there are several subscriptions in the client need to be closed. So I'm not sure how long did you wait after calling the `close()` method, **maybe you could try to wait longer**.

How long do you expect it to take? Five seconds? Five minutes? Is the delay around the reactive stream cleaning itself up? I'm just trying to understand what expectations I should have.

**Comment by ZejiaJiang** [comment]
Hi @azizabah , thanks for your replying.

The reason of many errors is that the processor client is not close completely. So when the subsription are deleted in service, client lost the subscription and throw a bench of errors. 

The close operation(close link) is asynchronous. call `stop()` or `close()` will stop processing message immediately. Hence calling `close()` and there are no message processing doesn't mean that the client is close completely. If you just want to avoid data accumulating, call `close()` is enough. Sorry for that I can't give you a certain time to wait to delete the subscription.

**Comment by azizabah** [comment]
Thanks for the information, @ZejiaJiang .
