### ISSUE TITLE
[BUG][`azure-data-factory`] Broken step for pipeline run

### ISSUE THREAD

**Issue by VolhaPrachkina** [Azure/azure-sdk-for-java#30171]
**Describe the bug**
The step to run ADF pipeline is broken, no pipeline can be run

***Exception or Stack Trace***
java.lang.NullPointerException: 'from' cannot be null.
	at java.base/java.util.Objects.requireNonNull(Objects.java:246)
	at com.azure.core.util.CoreUtils.mergeContexts(CoreUtils.java:367)
	at com.azure.resourcemanager.datafactory.implementation.DataFactoryManagementClientImpl.mergeContext(DataFactoryManagementClientImpl.java:445)
	at com.azure.resourcemanager.datafactory.implementation.PipelinesClientImpl.createRunWithResponseAsync(PipelinesClientImpl.java:1036)
	at com.azure.resourcemanager.datafactory.implementation.PipelinesClientImpl.createRunWithResponse(PipelinesClientImpl.java:1191)
	at com.azure.resourcemanager.datafactory.implementation.PipelinesImpl.createRunWithResponse(PipelinesImpl.java:100)
	at org.vividus.azure.datafactory.steps.DataFactorySteps.runPipeline(DataFactorySteps.java:111)
	at org.vividus.azure.datafactory.steps.DataFactorySteps.runPipeline(DataFactorySteps.java:88)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jbehave.core.steps.StepCreator$ParametrisedStep.perform(StepCreator.java:857)
	at org.jbehave.core.steps.StepCreator$ReportingAbstractStep.perform(StepCreator.java:678)
	at org.jbehave.core.embedder.PerformableTree$FineSoFar.run(PerformableTree.java:397)
	at org.jbehave.core.embedder.PerformableTree$PerformableSteps.perform(PerformableTree.java:1423)
	at org.jbehave.core.embedder.PerformableTree$AbstractPerformableScenario.perform(PerformableTree.java:1274)
	at org.jbehave.core.embedder.PerformableTree$AbstractPerformableScenario.performRestartableSteps(PerformableTree.java:1254)
	at org.jbehave.core.embedder.PerformableTree$AbstractPerformableScenario.performScenario(PerformableTree.java:1266)
	at org.jbehave.core.embedder.PerformableTree$ExamplePerformableScenario.perform(PerformableTree.java:1336)
	at org.jbehave.core.embedder.PerformableTree$PerformableScenario.perform(PerformableTree.java:1195)
	at org.jbehave.core.embedder.PerformableTree$PerformableStory.performScenarios(PerformableTree.java:1089)
	at org.jbehave.core.embedder.PerformableTree$PerformableStory.perform(PerformableTree.java:1064)
	at org.jbehave.core.embedder.PerformableTree.performCancellable(PerformableTree.java:514)
	at org.jbehave.core.embedder.PerformableTree.perform(PerformableTree.java:481)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:300)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:273)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

**To Reproduce**
1. Create a story with the step to run pipeline. e.g.
When I run pipeline `pipeline_name` in Data Factory `ADFName` from resource group `RGName` with wait timeout `PT60S` and expect run status to be equal to `Succeeded`

**Expected behavior**
Pipeline can be successfully run

**Screenshots**
<img width="405" alt="image" src="https://user-images.githubusercontent.com/80336192/181481676-2d66bddd-5644-41eb-b068-0c83e0fa8b48.png">

**Setup (please complete the following information):**
 - OS: win 10.0.18363
 - vividusVersion: '0.4.13'

**Comment by SaurabhSharma-MSFT** [comment]
@VolhaPrachkina I believe you have successfully submitted a PR to fix this issue which has been merged to master.  If that's the case, please let me know if we can close this issue.
