### ISSUE TITLE
[BUG] ShareFileClient.upload() fails to upload empty file

### ISSUE THREAD

**Issue by wheezil** [Azure/azure-sdk-for-java#30200]
**Describe the bug**

This method subtracts one from the length:
```
    Mono<Response<ShareFileUploadInfo>> uploadRangeWithResponse(ShareFileUploadRangeOptions options, Context context) {
        ShareRequestConditions requestConditions = options.getRequestConditions() == null ? new ShareRequestConditions() : options.getRequestConditions();
        long rangeOffset = options.getOffset() == null ? 0L : options.getOffset();
        ShareFileRange range = new ShareFileRange(rangeOffset, rangeOffset + options.getLength() - 1L);
```

Presumably this is done because ShareFileRange.end is inclusive (undocumented and uncommented, but it seems to work that way).

It inevitably leads to this error
```
    public ShareFileRange(long start, Long end) {
        if (start < 0L) {
            throw LOGGER.logExceptionAsError(new IllegalArgumentException("ShareFileRange offset must be greater than or equal to 0."));
        } else {
            this.start = start;
            if (end != null && end < 0L) {
>>>                throw LOGGER.logExceptionAsError(new IllegalArgumentException(new IllegalArgumentException("ShareFileRange end must be greater than or equal to 0 if specified.")));
            } else {
                this.end = end;
            }
        }
    }
```

Well, of course it is < 0.  Because the end is _inclusive_, and empty range is [0,-1], and a length-one range is [0,0]

This check should be changed to
```            if (end != null && end < -1L) {```

Or better yet, use an exclusive range, because that's the convention everyone expects and these bugs won't pop up.

***Exception or Stack Trace***

```
java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: ShareFileRange end must be greater than or equal to 0 if specified.

	at com.azure.storage.file.share.models.ShareFileRange.<init>(ShareFileRange.java:43)
	at com.azure.storage.file.share.ShareFileAsyncClient.uploadRangeWithResponse(ShareFileAsyncClient.java:2207)
	at com.azure.storage.file.share.ShareFileAsyncClient.lambda$uploadWithResponse$38(ShareFileAsyncClient.java:2053)
	at com.azure.storage.common.implementation.UploadUtils.lambda$uploadFullOrChunked$0(UploadUtils.java:72)
	at reactor.core.publisher.FluxSwitchOnFirst$AbstractSwitchOnFirstMain.onComplete(FluxSwitchOnFirst.java:563)
	at reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.onComplete(FluxConcatMapNoPrefetch.java:240)
	at reactor.core.publisher.FluxFilter$FilterSubscriber.onComplete(FluxFilter.java:166)
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:368)
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onComplete(FluxConcatMap.java:276)
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144)
	at reactor.core.publisher.Operators.complete(Operators.java:137)
	at reactor.core.publisher.FluxEmpty.subscribe(FluxEmpty.java:42)
	at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62)
	at reactor.core.publisher.FluxDefer.subscribe(FluxDefer.java:54)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4397)
	at reactor.core.publisher.Mono.block(Mono.java:1706)
	at com.azure.storage.common.implementation.StorageImplUtils.blockWithOptionalTimeout(StorageImplUtils.java:191)
	at com.azure.storage.file.share.ShareFileClient.uploadWithResponse(ShareFileClient.java:1602)
	at com.azure.storage.file.share.ShareFileClient.upload(ShareFileClient.java:1569)
	at com.redpointglobal.rg1.nio.afs.AfsConnectionStringTest.foo(AfsConnectionStringTest.java:207)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
```

**To Reproduce**

see code snippet

***Code Snippet***

```
public void foo() throws Exception {
  Path tmp = Files.createTempFile("tmp-azure-file-share-", ".dat");
  Files.write(tmp, new byte[0]);
  String name = UUID.randomUUID().toString().replace("-", "");
  ShareServiceClientBuilder serviceClientBuilder = new ShareServiceClientBuilder().endpoint("https://youraccount.file.core.windows.net/");
  serviceClientBuilder.connectionString("your connection string");
  ShareServiceClient client = serviceClientBuilder.buildClient();
  ShareClient shareClient = client.getShareClient("glarp");
  if (!shareClient.exists()) {
    shareClient.create();
  }
  ShareFileClient fileClient = shareClient.getFileClient(name);
  if (!fileClient.exists()) {
    fileClient.create(1);
  }
  //fileClient.uploadFromFile(tmp.toString());
  fileClient.upload(new MarkableFileInputStream(new FileInputStream(tmp.toFile())), 0);
}
```

Note that the commented-out uploadFromFile() works as expected

**Expected behavior**

Upload a zero-length file.

**Setup (please complete the following information):**
 - OS: Windows 10 pro
 - IDE: IntelliJ
 - Library/Libraries: 
```
<dependency>
  <groupId>com.azure</groupId>
  <artifactId>azure-sdk-bom</artifactId>
  <version>1.2.4</version>
  <type>pom</type>
  <scope>import</scope>
</dependency>
```
 - Java version: 8 
 - App Server/Environment: n/a
 - Frameworks: n/a

**Comment by rickle-msft** [comment]
@wheezil Thanks for opening this issue and taking the time to do some investigation. We'll work on putting out a fix for this.

**Comment by wheezil** [comment]
I forgot to include the utility class:
```
public class MarkableFileInputStream extends FilterInputStream {
	private FileChannel myFileChannel;
	private long mark = -1;
	public MarkableFileInputStream(FileInputStream fis) {
		super(fis);
		myFileChannel = fis.getChannel();
	}
	@Override
	public boolean markSupported() {
		return true;
	}
	@Override
	public synchronized void mark(int readlimit) {
		try {
			mark = myFileChannel.position();
		}
		catch (IOException ex) {
			mark = -1;
		}
	}
	@Override
	public synchronized void reset() throws IOException {
		if (mark == -1) {
			throw new IOException("not marked");
		}
		myFileChannel.position(mark);
	}
}
```

**Comment by wheezil** [comment]
Hi @rickle-msft  always a pleasure to work with you.  Thanks for taking a look.

**Comment by wheezil** [comment]
I should add that there is a simple workaround.  Use uploadFromFile() instead.
However the workaround is imperfect, because uploadFromFile() is a memory hog for large files, so I kind of need both.

**Comment by rickle-msft** [comment]
@wheezil Thinking about this a bit more as I'm starting to work on the fix... Why would you want to make an upload call with 0 length? It ends up being a waste of a network call because the file is empty when you create it. It seems like the more performant thing would be to check if the length and just skip the upload call if the length is 0.

**Comment by wheezil** [comment]
@rickle-msft 
Well, we are just a humble file I/O layer unifying all of the cloud storage we support.  We have an ETL framework that writes data files according to user design, and it is just a matter of time until some user writes a headerless CSV file with no records and hits this bug.  Granted this is a better workaround than uploading a zero-length file.  But it's just another workaround, meaning my application code has to check for zero-length and not do the upload.  Also it means that one cannot truncate an existing file to zero-length using this technique (not that we actually do that).  Mostly it is that the SDK API has a contract that it broke, and so unsuspecting programmers like me run into its limitations and have to build our own special cases.  If zero-length files aren't allowed, just say that in the contract and throw an exception like "zero-length file upload not supported, just call ShareFileClient.create()"
Cheers,
john

**Comment by rickle-msft** [comment]
@wheezil Thanks for the information. I did some experimentation and tried sending some empty data to the service, and the service rejected it with a 400 saying Content-Length can't be zero for an upload range call. Given that, we won't be able to support empty writes on the client, and I would consider adding a check for empty data to be a legitimate code path rather than a workaround. 

I can at least update the exception message that bubbles up when attempting this, though.

**Comment by wheezil** [comment]
OK, thanks for checking it out.
john
