### ISSUE TITLE
securityRules.sourceAddressPrefix is required and cannot be null

### ISSUE THREAD

**Issue by DawidCh** [Azure/azure-sdk-for-java#3030]
**Describe the bug**
Hello.
We can't update network security group (add new rule) using following code. We run the code on jenkins (in shared library).

***Exception or Stack Trace***
```
java.lang.IllegalArgumentException: securityRules.sourceAddressPrefix is required and cannot be null.
	at com.microsoft.rest.Validator.validateClass(Validator.java:120)
	at com.microsoft.rest.Validator.validate(Validator.java:64)
	at com.microsoft.azure.management.network.implementation.NetworkSecurityGroupsInner.createOrUpdateWithServiceResponseAsync(NetworkSecurityGroupsInner.java:491)
	at com.microsoft.azure.management.network.implementation.NetworkSecurityGroupsInner.createOrUpdateAsync(NetworkSecurityGroupsInner.java:461)
	at com.microsoft.azure.management.network.implementation.NetworkSecurityGroupImpl.createInner(NetworkSecurityGroupImpl.java:153)
	at com.microsoft.azure.management.resources.fluentcore.arm.models.implementation.GroupableParentResourceImpl.createResourceAsync(GroupableParentResourceImpl.java:53)
	at com.microsoft.azure.management.resources.fluentcore.model.implementation.CreatableUpdatableImpl.updateResourceAsync(CreatableUpdatableImpl.java:168)
	at com.microsoft.azure.management.resources.fluentcore.model.implementation.CreateUpdateTask.executeAsync(CreateUpdateTask.java:65)
	at com.microsoft.azure.management.resources.fluentcore.dag.TaskGroupEntry.executeTaskAsync(TaskGroupEntry.java:77)
	at com.microsoft.azure.management.resources.fluentcore.dag.TaskGroup.executeTaskAsync(TaskGroup.java:208)
	at com.microsoft.azure.management.resources.fluentcore.dag.TaskGroup.executeReadyTasksAsync(TaskGroup.java:168)
	at com.microsoft.azure.management.resources.fluentcore.dag.TaskGroup.executeAsync(TaskGroup.java:108)
	at com.microsoft.azure.management.resources.fluentcore.model.implementation.CreatableUpdatableImpl.executeTaskGroupAsync(CreatableUpdatableImpl.java:172)
	at com.microsoft.azure.management.resources.fluentcore.model.implementation.CreatableUpdatableImpl.applyAsync(CreatableUpdatableImpl.java:153)
	at com.microsoft.azure.management.resources.fluentcore.model.implementation.CreatableUpdatableImpl.apply(CreatableUpdatableImpl.java:163)
	at com.microsoft.azure.management.resources.fluentcore.model.implementation.CreatableUpdatableImpl.apply(CreatableUpdatableImpl.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:47)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.methodCall(DefaultInvoker.java:20)
	at com.tomtom.searchapi.infra.services.networksecurity.AzureNSGImpl.createSecurityRule(file:/var/jenkins_home/jobs/nsg-rule-test/builds/203/libs/mayday-pipeline/src/com/tomtom/searchapi/infra/services/networksecurity/AzureNSGImpl.groovy:24)
	at com.cloudbees.groovy.cps.CpsDefaultGroovyMethods.each(CpsDefaultGroovyMethods:2030)
	at com.cloudbees.groovy.cps.CpsDefaultGroovyMethods.each(CpsDefaultGroovyMethods:2015)
	at com.cloudbees.groovy.cps.CpsDefaultGroovyMethods.each(CpsDefaultGroovyMethods:2056)
	at com.tomtom.searchapi.infra.services.networksecurity.AzureNSGImpl.createSecurityRule(file:/var/jenkins_home/jobs/nsg-rule-test/builds/203/libs/mayday-pipeline/src/com/tomtom/searchapi/infra/services/networksecurity/AzureNSGImpl.groovy:22)
	at com.tomtom.searchapi.infra.services.networksecurity.NetworkSecurityServiceImpl.createSecurityRule(file:/var/jenkins_home/jobs/nsg-rule-test/builds/203/libs/mayday-pipeline/src/com/tomtom/searchapi/infra/services/networksecurity/NetworkSecurityServiceImpl.groovy:14)
	at com.tomtom.searchapi.infra.services.networksecurity.NetworkSecurityController.createSecurityRule(file:/var/jenkins_home/jobs/nsg-rule-test/builds/203/libs/mayday-pipeline/src/com/tomtom/searchapi/infra/services/networksecurity/NetworkSecurityController.groovy:64)
	at com.tomtom.searchapi.infra.pipeline.PostDeployPipeline.createNSG(file:/var/jenkins_home/jobs/nsg-rule-test/builds/203/libs/mayday-pipeline/src/com/tomtom/searchapi/infra/pipeline/PostDeployPipeline.groovy:68)
	at com.tomtom.searchapi.infra.pipeline.PipelinePhase.runStage(file:/var/jenkins_home/jobs/nsg-rule-test/builds/203/libs/mayday-pipeline/src/com/tomtom/searchapi/infra/pipeline/PipelinePhase.groovy:46)
	at ___cps.transform___(Native Method)
	at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:57)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:109)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixName(FunctionCallBlock.java:77)
	at sun.reflect.GeneratedMethodAccessor277.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
	at com.cloudbees.groovy.cps.Next.step(Next.java:83)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:122)
	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:261)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$101(SandboxContinuable.java:34)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.lambda$run0$0(SandboxContinuable.java:59)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.GroovySandbox.runInSandbox(GroovySandbox.java:108)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:58)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:182)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:332)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$200(CpsThreadGroup.java:83)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:244)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:232)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:131)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**To Reproduce**
Steps to reproduce the behavior: Create resource group. Create network security group inside it (operations from azure portal). Run the code.

***Code Snippet***
```
azure.networkSecurityGroups()
                .getByResourceGroup(createRuleEntity.getResourceGroupName(), createRuleEntity.getSecurityGroupName())
                .update()
                .defineRule('sample')
                .allowInbound()
                .fromAddress('192.168.2.0/24')
                .fromAnyPort()
                .toAnyAddress()
                .toPort('8080')
                .withProtocol(SecurityRuleProtocol.TCP)
                .withPriority(102)
                .attach()
                .apply()
```

**Expected behavior**
I expect that rule is created on NSG

**Screenshots**

**Setup (please complete the following information):**
 - OS: ubuntu 16lts, groovy 2.6, 
 - IDE : Intellij
 - Version of the Library used: com.microsoft.azure:azure-mgmt-network:1.3.0
```
<dependency>
            <groupId>org.jenkins-ci.plugins</groupId>
            <artifactId>credentials</artifactId>
            <version>2.1.18</version>
        </dependency>
        <dependency>
            <groupId>org.jenkins-ci.plugins</groupId>
            <artifactId>azure-credentials</artifactId>
            <version>1.6.0</version>
        </dependency>
        <dependency>
            <groupId>org.jenkins-ci.plugins</groupId>
            <artifactId>azure-commons-core</artifactId>
            <version>0.2.8</version>
        </dependency>
```

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ x] Bug Description Added
- [ x] Repro Steps Added
- [ x] Setup information Added

**Comment by DawidCh** [comment]
I have found the problem:
1. Create resource group in portal.
2. Create nsg in portal
3. Create nsg rule in portal but in source IP address write two, or more, addresses: x.x.x.x/32,y.y.y.y/32
4. Run:
```
nsg = azure.networkSecurityGroups()
                .getByResourceGroup(createRuleEntity.getResourceGroupName(), createRuleEntity.getSecurityGroupName())
com.microsoft.rest.Validator.validate(nsg)
```
Conclusion: the rules which have multiple addresses configured in portal have sourceAddressPrefix set to null while are being retrieved from Azure. So uploading the network security group back to azure (with or without modifications) fails on validation.

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.
