### ISSUE TITLE
[QUERY] NoSuchMethodError for Azure Management Java SDK

### ISSUE THREAD

**Issue by ihsanhaikalz** [Azure/azure-sdk-for-java#30327]
I am really new with Azure Java SDK and I would like to run Azure Management Java SDK following https://docs.microsoft.com/en-us/java/api/overview/azure/resourcemanager-apimanagement-readme?view=azure-java-preview and https://github.com/Azure/azure-sdk-for-java/blob/azure-resourcemanager-apimanagement_1.0.0-beta.3/sdk/resourcemanager/docs/AUTH.md with the code as follows:

```
    AzureProfile profile = new AzureProfile(tenantId, subscriptionId, AzureEnvironment.AZURE);
    final ClientSecretCredential clientSecretCredential = new ClientSecretCredentialBuilder()
            .clientId(clientId)
            .clientSecret(clientSecret)
            .tenantId(tenantId)
            .authorityHost(profile.getEnvironment().getActiveDirectoryEndpoint())

            .build();
    ApiManagementManager manager = ApiManagementManager.authenticate(clientSecretCredential, profile);
```

However, when I run the code it would return this error on the ApiManagementManager:

```
    java.lang.NoSuchMethodError: 'void com.azure.core.util.serializer.JacksonAdapter.<init>(java.util.function.BiConsumer)'
    	at com.azure.core.management.implementation.serializer.AzureJacksonAdapter.<init>(AzureJacksonAdapter.java:17)
    	at com.azure.core.management.serializer.SerializerFactory.createDefaultManagementSerializerAdapter(SerializerFactory.java:26)
    	at com.azure.resourcemanager.apimanagement.implementation.ApiManagementClientBuilder.buildClient(ApiManagementClientBuilder.java:142)
    	at com.azure.resourcemanager.apimanagement.ApiManagementManager.<init>(ApiManagementManager.java:350)
    	at com.azure.resourcemanager.apimanagement.ApiManagementManager.<init>(ApiManagementManager.java:186)
    	at com.azure.resourcemanager.apimanagement.ApiManagementManager$Configurable.authenticate(ApiManagementManager.java:525)
    	at com.azure.resourcemanager.apimanagement.ApiManagementManager.authenticate(ApiManagementManager.java:363)
```

Any idea why?

**Comment by joshfree** [comment]
Hi @ihsanhaikalz thank you for reaching out to us via this GitHub issue.  Someone from the `control plane` SDK team will follow up with you shortly.

You can also refer to https://docs.microsoft.com/en-us/azure/developer/java/sdk/troubleshooting-dependency-version-conflict and https://devblogs.microsoft.com/azure-sdk/dependency-management-for-java/ for guidance on how to resolve dependency conflicts in the local client side application.

**Comment by weidongxu-microsoft** [comment]
@ihsanhaikalz 

Please see https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/resourcemanager#dependency-management

Your project likely having conflict version of `azure-core`. Please make it the latest version.
