### ISSUE TITLE
[QUERY]

### ISSUE THREAD

**Issue by zhukexingkong** [Azure/azure-sdk-for-java#30322]
**Query/Question**
Can not connetct to Azure Key Vault with  AZURE_CLIENT_ID,AZURE_TENANT_ID,AZURE_CLIENT_SECRET in China.

***Why is this not a Bug or a feature Request?***
It is a problem of default authortyHost.

**Setup (please complete the following information if applicable):**
 - OS: window
 - IDE: IntelliJ
 - Library/Libraries: azure-identity:1.5.3

**Comment by zhukexingkong** [comment]
I have resolved the issue. The reason is the problem of authorityHost, the default is "https://login.microsoftonline.com/", in China it should be "https://login.chinacloudapi.cn/", the code is written as follows to connect the key vault successfully:
DefaultAzureCredential defaultAzureCredential = new DefaultAzureCredentialBuilder().authorityHost(AzureAuthorityHosts.AZURE_CHINA).build();
KeyClient keyClient = new KeyClientBuilder()
.vaultUrl("https://XXX.vault.azure.cn/")
.credential(defaultAzureCredential)
.buildClient();

KeyVaultKey key = keyClient.getKey("test-RSA");
System.out.printf("A key was returned with name \"%s\" and id %s%n", key.getName(), key.getId());

**Comment by zhukexingkong** [comment]
The Error is:
[ForkJoinPool.commonPool-worker-5] ERROR com.microsoft.aad.msal4j.ConfidentialClientApplication - [Correlation ID: XXX-XXXX] Execution of class com.microsoft.aad.msal4j.AcquireTokenByClientCredentialSupplier failed.
com.microsoft.aad.msal4j.MsalServiceException: AADSTS90002: Tenant 'XXX-XXX-XXX' not found. Check to make sure you have the correct tenant ID and are signing into the correct cloud. Check with your subscription administrator, this may happen if there are no active subscriptions for the tenant.
Trace ID: XXX-XXX
Correlation ID: XXX-XXX
Timestamp: 2022-08-01 03:47:33Z
	at com.microsoft.aad.msal4j.MsalServiceExceptionFactory.fromHttpResponse(MsalServiceExceptionFactory.java:45)
	at com.microsoft.aad.msal4j.TokenRequestExecutor.createAuthenticationResultFromOauthHttpResponse(TokenRequestExecutor.java:102)
	at com.microsoft.aad.msal4j.TokenRequestExecutor.executeTokenRequest(TokenRequestExecutor.java:33)
	at com.microsoft.aad.msal4j.AbstractClientApplicationBase.acquireTokenCommon(AbstractClientApplicationBase.java:128)
	at com.microsoft.aad.msal4j.AcquireTokenByAuthorizationGrantSupplier.execute(AcquireTokenByAuthorizationGrantSupplier.java:63)
	at com.microsoft.aad.msal4j.AcquireTokenByClientCredentialSupplier.acquireTokenByClientCredential(AcquireTokenByClientCredentialSupplier.java:63)
	at com.microsoft.aad.msal4j.AcquireTokenByClientCredentialSupplier.execute(AcquireTokenByClientCredentialSupplier.java:49)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:71)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:20)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run$$$capture(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
[ForkJoinPool.commonPool-worker-5] ERROR com.azure.core.implementation.AccessTokenCache - Failed to acquire a new access token.
