### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by MohakWadhwani** [Azure/azure-sdk-for-java#30554]
**Describe the bug**
Getting version conflicts in jackson data bind when using 
<dependency>
			<groupId>com.azure.spring</groupId>
			<artifactId>azure-spring-cloud-appconfiguration-config</artifactId>
			<version>2.3.0</version>
</dependency>

<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>

2022-08-19 20:13:23 [restartedMain] INFO  JacksonVersion:171 - Package versions: jackson-annotations=2.13.2, jackson-core=2.13.2, jackson-databind=2.13.2.2, jackson-dataformat-xml=2.13.2, jackson-datatype-jsr310=2.13.2, azure-core=1.23.1, Troubleshooting version conflicts: https://aka.ms/azsdk/java/dependency/troubleshoot

```
2022-08-19 20:13:23 [restartedMain] INFO  JacksonVersion:171 - Package versions: jackson-annotations=2.13.2, jackson-core=2.13.2, jackson-databind=2.13.2.2, jackson-dataformat-xml=2.13.2, jackson-datatype-jsr310=2.13.2, azure-core=1.23.1, Troubleshooting version conflicts: https://aka.ms/azsdk/java/dependency/troubleshoot
2022-08-19 20:13:23 [restartedMain] DEBUG MemberNameConverterImpl:426 - Failed to retrieve MethodHandles used to get naming strategy. Falling back to BeanUtils.
java.lang.ClassNotFoundException: com.fasterxml.jackson.databind.introspect.AccessorNamingStrategy.Provider
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:315) ~[?:?]
	at com.azure.core.implementation.jackson.MemberNameConverterImpl.<clinit>(MemberNameConverterImpl.java:55) ~[azure-core-1.23.1.jar:1.23.1]
	at com.azure.core.implementation.jackson.ObjectMapperShim.<init>(ObjectMapperShim.java:139) ~[azure-core-1.23.1.jar:1.23.1]
	at com.azure.core.implementation.jackson.ObjectMapperShim.createHeaderMapper(ObjectMapperShim.java:127) ~[azure-core-1.23.1.jar:1.23.1]
	at com.azure.core.util.serializer.JacksonAdapter.<init>(JacksonAdapter.java:80) ~[azure-core-1.23.1.jar:1.23.1]
	at com.azure.core.util.serializer.JacksonAdapter.<init>(JacksonAdapter.java:58) ~[azure-core-1.23.1.jar:1.23.1]
	at com.azure.core.util.serializer.JacksonAdapter$SerializerAdapterHolder.<clinit>(JacksonAdapter.java:113) ~[azure-core-1.23.1.jar:1.23.1]
	at com.azure.core.util.serializer.JacksonAdapter.createDefaultSerializerAdapter(JacksonAdapter.java:122) ~[azure-core-1.23.1.jar:1.23.1]
	at com.azure.identity.implementation.IdentityClient.<clinit>(IdentityClient.java:100) ~[azure-identity-1.4.4.jar:1.4.4]
	at com.azure.identity.implementation.IdentityClientBuilder.build(IdentityClientBuilder.java:139) ~[azure-identity-1.4.4.jar:1.4.4]
	at com.azure.identity.AzureCliCredential.<init>(AzureCliCredential.java:34) ~[azure-identity-1.4.4.jar:1.4.4]
	at com.azure.identity.AzureCliCredentialBuilder.build(AzureCliCredentialBuilder.java:34) ~[azure-identity-1.4.4.jar:1.4.4]
	at com.msci.dm.config.AzureAuthentication.cliTokenCredential(AzureAuthentication.java:27) ~[classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.3.18.jar:5.3.18]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653) ~[spring-beans-5.3.18.jar:5.3.18]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:486) ~[spring-beans-5.3.18.jar:5.3.18]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352) ~[spring-beans-5.3.18.jar:5.3.18]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195) ~[spring-beans-5.3.18.jar:5.3.18]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582) ~[spring-beans-5.3.18.jar:5.3.18]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.18.jar:5.3.18]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.18.jar:5.3.18]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.18.jar:5.3.18]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.18.jar:5.3.18]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.18.jar:5.3.18]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953) ~[spring-beans-5.3.18.jar:5.3.18]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.18.jar:5.3.18]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.18.jar:5.3.18]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:740) ~[spring-boot-2.6.6.jar:2.6.6]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:415) ~[spring-boot-2.6.6.jar:2.6.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) ~[spring-boot-2.6.6.jar:2.6.6]
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:164) ~[spring-boot-2.6.6.jar:2.6.6]
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.bootstrapServiceContext(BootstrapApplicationListener.java:195) ~[spring-cloud-context-3.1.0.jar:3.1.0]
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:114) ~[spring-cloud-context-3.1.0.jar:3.1.0]
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:77) ~[spring-cloud-context-3.1.0.jar:3.1.0]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-5.3.18.jar:5.3.18]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-5.3.18.jar:5.3.18]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-5.3.18.jar:5.3.18]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:131) ~[spring-context-5.3.18.jar:5.3.18]
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:85) ~[spring-boot-2.6.6.jar:2.6.6]
	at org.springframework.boot.SpringApplicationRunListeners.lambda$environmentPrepared$2(SpringApplicationRunListeners.java:66) ~[spring-boot-2.6.6.jar:2.6.6]
	at java.util.ArrayList.forEach(ArrayList.java:1541) ~[?:?]
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:120) ~[spring-boot-2.6.6.jar:2.6.6]
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:114) ~[spring-boot-2.6.6.jar:2.6.6]
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:65) ~[spring-boot-2.6.6.jar:2.6.6]
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:339) ~[spring-boot-2.6.6.jar:2.6.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:297) ~[spring-boot-2.6.6.jar:2.6.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1312) ~[spring-boot-2.6.6.jar:2.6.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1301) ~[spring-boot-2.6.6.jar:2.6.6]
	at com.msci.dm.Application.main(Application.java:35) ~[classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) ~[spring-boot-devtools-2.6.6.jar:2.6.6]
2022-08-19 20:13:23 [restartedMain] DEBUG Loggers:245 - Using Slf4j logging framework



**To Reproduce**
Steps to reproduce the behavior:

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Setup (please complete the following information):**
 - OS: [e.g. iOS]
 - IDE: [e.g. IntelliJ]
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)]
 - Java version: [e.g. 8] 
 - App Server/Environment: [e.g. Tomcat, WildFly, Azure Function, Apache Spark, Databricks, IDE plugin or anything special]
 - Frameworks: [e.g. Spring Boot, Micronaut, Quarkus, etc] 

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**
When checked the dependency hierarchy found both the libraries were bringing 2.13.2.2 of jackson data bind

**Comment by joshfree** [comment]
Hi @MohakWadhwani could you please include the verbose dependency tree output from: `mvn dependency:tree -Dverbose`

**Comment by alzimmermsft** [comment]
Thanks for reporting this @MohakWadhwani.

This is interesting as `1.23.1` included [this change](https://github.com/Azure/azure-sdk-for-java/pull/25840) to fix `.` being used for a inner class instead of the proper `$`. Could you ensure that `azure-core` `1.23.1` is explicitly included using a direct dependency. If the error continues happening after that would you mind trying `azure-core` `1.24.1` as it included changes to reflective access to reduce errors.

**Comment by MohakWadhwani** [comment]
Thanks @alzimmermsft  
adding azure-core 1.24.1 dependency explicitly resolved this issue.

**Comment by MohakWadhwani** [comment]
Hey @alzimmermsft  @joshfree 
can we please re open the issue

We upgraded the version of azure core to 1.30.0 but seems other similar issues 

we are executing the application with javaagent:applicationinsights so may be dependencies from app insights are causing this issue.

Executing java -Xms512m -Xmx6G -XX:+UseG1GC -javaagent:applicationinsights-agent.jar  -DAUTOMENU_date=2022-08-23 -DDD=23 -DMM=08 -DYYYY=2022 -DUSER=dmqa -cp /3.0.1/app-3.0.1.jar com..main.MainClass  




2022-08-25 14:17:11,526 |  INFO | [main] | com.azure.core.implementation.jackson.JacksonVersion:info(222) | Package versions: jackson-annotations=2.13.3, jackson-core=2.13.3, jackson-databind=2.13.3, jackson-dataformat-xml=2.13.3, jackson-datatype-jsr310=2.13.3, azure-core=1.30.0, Troubleshooting version conflicts: https://aka.ms/azsdk/java/dependency/troubleshoot 
2022-08-25 14:17:11,541 | DEBUG | [main] | com.azure.core.implementation.jackson.ObjectMapperFactory:performLogging(491) | Failed to retrieve MethodHandles used to set coercion configurations. Setting coercion configurations will be skipped. 
java.lang.IllegalAccessException: no such method: com.fasterxml.jackson.databind.ObjectMapper.coercionConfigDefaults()MutableCoercionConfig/invokeVirtual
	at java.lang.invoke.MemberName.makeAccessException(MemberName.java:959) ~[?:?]
	at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1101) ~[?:?]
	at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:2030) ~[?:?]
	at java.lang.invoke.MethodHandles$Lookup.findVirtual(MethodHandles.java:1194) ~[?:?]
	at com.azure.core.implementation.jackson.ObjectMapperFactory.<init>(ObjectMapperFactory.java:52) ~[azure-core-1.30.0.jar:1.30.0]
	at com.azure.core.implementation.jackson.ObjectMapperFactory.<clinit>(ObjectMapperFactory.java:42) ~[azure-core-1.30.0.jar:1.30.0]
	at com.azure.core.implementation.jackson.ObjectMapperShim.createHeaderMapper(ObjectMapperShim.java:135) ~[azure-core-1.30.0.jar:1.30.0]
	at com.azure.core.util.serializer.JacksonAdapter.<init>(JacksonAdapter.java:81) ~[azure-core-1.30.0.jar:1.30.0]
	at com.azure.core.util.serializer.JacksonAdapter.<init>(JacksonAdapter.java:59) ~[azure-core-1.30.0.jar:1.30.0]
	at com.azure.core.util.serializer.JacksonAdapter$SerializerAdapterHolder.<clinit>(JacksonAdapter.java:114) ~[azure-core-1.30.0.jar:1.30.0]
	at com.azure.core.util.serializer.JacksonAdapter.createDefaultSerializerAdapter(JacksonAdapter.java:123) ~[azure-core-1.30.0.jar:1.30.0]
	at com.azure.identity.implementation.IdentityClient.<clinit>(IdentityClient.java:104) ~[azure-identity-1.5.3.jar:1.5.3]
	at com.azure.identity.implementation.IdentityClientBuilder.build(IdentityClientBuilder.java:158) ~[azure-identity-1.5.3.jar:1.5.3]
	at com.azure.identity.ManagedIdentityCredential.<init>(ManagedIdentityCredential.java:88) ~[azure-identity-1.5.3.jar:1.5.3]
	at com.azure.identity.ManagedIdentityCredentialBuilder.build(ManagedIdentityCredentialBuilder.java:57) ~[azure-identity-1.5.3.jar:1.5.3]
	at com.xx.azure.appconfig.TokenCredentialFactory.remoteCredential(TokenCredentialFactory.java:64) ~[azure-app-config-1.0.12.jar:1.0.12]
	at com.xx.azure.appconfig.TokenCredentialFactory.get(TokenCredentialFactory.java:53) ~[azure-app-config-1.0.12.jar:1.0.12]
	at com.xx.azure.appconfig.spring.AzurePropertySourcesPlaceHolderConfigurer.<init>(AzurePropertySourcesPlaceHolderConfigurer.java:42) ~[azure-app-config-1.0.12.jar:1.0.12]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:211) ~[spring-beans-5.3.20.jar:5.3.20]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:117) ~[spring-beans-5.3.20.jar:5.3.20]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:311) ~[spring-beans-5.3.20.jar:5.3.20]
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:296) ~[spring-beans-5.3.20.jar:5.3.20]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372) ~[spring-beans-5.3.20.jar:5.3.20]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222) ~[spring-beans-5.3.20.jar:5.3.20]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582) ~[spring-beans-5.3.20.jar:5.3.20]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.20.jar:5.3.20]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.20.jar:5.3.20]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) [spring-beans-5.3.20.jar:5.3.20]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) [spring-beans-5.3.20.jar:5.3.20]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:213) [spring-beans-5.3.20.jar:5.3.20]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:171) [spring-context-5.3.20.jar:5.3.20]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:746) [spring-context-5.3.20.jar:5.3.20]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:564) [spring-context-5.3.20.jar:5.3.20]
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:144) [spring-context-5.3.20.jar:5.3.20]
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:85) [spring-context-5.3.20.jar:5.3.20]
	at com.xx.dm.facts.main.FactsInvoker.main(FactsInvoker.java:36) [FactsFramework-3.0.1.jar:3.0.1]
Caused by: java.lang.LinkageError: loader constraint violation: when resolving method "com.fasterxml.jackson.databind.ObjectMapper.coercionConfigDefaults()Lcom/fasterxml/jackson/databind/cfg/MutableCoercionConfig;" the class loader 'bootstrap' of the current class, java/lang/Object, and the class loader 'app' (instance of jdk.internal.loader.ClassLoaders$AppClassLoader) for the method's defining class, com/fasterxml/jackson/databind/ObjectMapper, have different Class objects for the type com/fasterxml/jackson/databind/cfg/MutableCoercionConfig used in the signature
	at java.lang.invoke.MethodHandleNatives.resolve(Native Method) ~[?:?]
	at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:1070) ~[?:?]
	at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1098) ~[?:?]
	... 38 more
2022-08-25 14:17:11,646 | DEBUG | [main] | com.azure.core.implementation.jackson.MemberNameConverterImpl:performLogging(491) | Failed to retrieve MethodHandles used to get naming strategy. Falling back to BeanUtils. 
java.lang.IllegalAccessException: no such method: com.fasterxml.jackson.databind.cfg.MapperConfig.getAccessorNaming()Provider/invokeVirtual
	at java.lang.invoke.MemberName.makeAccessException(MemberName.java:959) ~[?:?]
	at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1101) ~[?:?]
	at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:2030) ~[?:?]
	at java.lang.invoke.MethodHandles$Lookup.findVirtual(MethodHandles.java:1194) ~[?:?]
	at com.azure.core.implementation.jackson.MemberNameConverterImpl.<clinit>(MemberNameConverterImpl.java:57) ~[azure-core-1.30.0.jar:1.30.0]
	at com.azure.core.implementation.jackson.ObjectMapperShim.<init>(ObjectMapperShim.java:148) ~[azure-core-1.30.0.jar:1.30.0]
	at com.azure.core.implementation.jackson.ObjectMapperShim.createHeaderMapper(ObjectMapperShim.java:136) ~[azure-core-1.30.0.jar:1.30.0]
	at com.azure.core.util.serializer.JacksonAdapter.<init>(JacksonAdapter.java:81) ~[azure-core-1.30.0.jar:1.30.0]
	at com.azure.core.util.serializer.JacksonAdapter.<init>(JacksonAdapter.java:59) ~[azure-core-1.30.0.jar:1.30.0]
	at com.azure.core.util.serializer.JacksonAdapter$SerializerAdapterHolder.<clinit>(JacksonAdapter.java:114) ~[azure-core-1.30.0.jar:1.30.0]
	at com.azure.core.util.serializer.JacksonAdapter.createDefaultSerializerAdapter(JacksonAdapter.java:123) ~[azure-core-1.30.0.jar:1.30.0]
	at com.azure.identity.implementation.IdentityClient.<clinit>(IdentityClient.java:104) ~[azure-identity-1.5.3.jar:1.5.3]
	at com.azure.identity.implementation.IdentityClientBuilder.build(IdentityClientBuilder.java:158) ~[azure-identity-1.5.3.jar:1.5.3]
	at com.azure.identity.ManagedIdentityCredential.<init>(ManagedIdentityCredential.java:88) ~[azure-identity-1.5.3.jar:1.5.3]
	at com.azure.identity.ManagedIdentityCredentialBuilder.build(ManagedIdentityCredentialBuilder.java:57) ~[azure-identity-1.5.3.jar:1.5.3]
	at com.msci.azure.appconfig.TokenCredentialFactory.remoteCredential(TokenCredentialFactory.java:64) ~[azure-app-config-1.0.12.jar:1.0.12]
	at com.msci.azure.appconfig.TokenCredentialFactory.get(TokenCredentialFactory.java:53) ~[azure-app-config-1.0.12.jar:1.0.12]
	at com.msci.azure.appconfig.spring.AzurePropertySourcesPlaceHolderConfigurer.<init>(AzurePropertySourcesPlaceHolderConfigurer.java:42) ~[azure-app-config-1.0.12.jar:1.0.12]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:211) ~[spring-beans-5.3.20.jar:5.3.20]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:117) ~[spring-beans-5.3.20.jar:5.3.20]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:311) ~[spring-beans-5.3.20.jar:5.3.20]
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:296) ~[spring-beans-5.3.20.jar:5.3.20]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372) ~[spring-beans-5.3.20.jar:5.3.20]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222) ~[spring-beans-5.3.20.jar:5.3.20]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582) ~[spring-beans-5.3.20.jar:5.3.20]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.20.jar:5.3.20]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.20.jar:5.3.20]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) [spring-beans-5.3.20.jar:5.3.20]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) [spring-beans-5.3.20.jar:5.3.20]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:213) [spring-beans-5.3.20.jar:5.3.20]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:171) [spring-context-5.3.20.jar:5.3.20]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:746) [spring-context-5.3.20.jar:5.3.20]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:564) [spring-context-5.3.20.jar:5.3.20]
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:144) [spring-context-5.3.20.jar:5.3.20]
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:85) [spring-context-5.3.20.jar:5.3.20]
	at com.xxx.dm.facts.main.FactsInvoker.main(FactsInvoker.java:36) [FactsFramework-3.0.1.jar:3.0.1]
Caused by: java.lang.LinkageError: loader constraint violation: when resolving method "com.fasterxml.jackson.databind.cfg.MapperConfig.getAccessorNaming()Lcom/fasterxml/jackson/databind/introspect/AccessorNamingStrategy$Provider;" the class loader 'bootstrap' of the current class, java/lang/Object, and the class loader 'app' (instance of jdk.internal.loader.ClassLoaders$AppClassLoader) for the method's defining class, com/fasterxml/jackson/databind/cfg/MapperConfig, have different Class objects for the type com/fasterxml/jackson/databind/introspect/AccessorNamingStrategy$Provider used in the signature
	at java.lang.invoke.MethodHandleNatives.resolve(Native Method) ~[?:?]
	at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:1070) ~[?:?]
	at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1098) ~[?:?]
	... 38 more
2022-08-25 14:17:11,673 | DEBUG | [main] | com.azure.core.implementation.jackson.ObjectMapperFactory:verbose(174) | Didn't set coercion defaults as it wasn't found on the classpath. 
2022-08-25 14:17:11,895 | DEBUG | [main] | com.azure.identity.ManagedIdentityCredential:performLogging(491) | Azure Identity => Found the following environment variables:  
2022-08-25 14:17:12,161 | DEBUG | [main] | com.azure.core.implementation.jackson.ObjectMapperFactory:verbose(174) | Didn't set coercion defaults as it wasn't found on the classpath.

**Comment by Yanglane2021** [comment]
@alzimmermsft @joshfree
16:01:48.180 [main] INFO com.azure.core.implementation.jackson.JacksonVersion - Package versions: jackson-core=2.11.3, jackson-databind=2.11.3, jackson-dataformat-xml=2.11.3, jackson-datatype-jsr310=2.11.3, azure-core=1.33.0, Troubleshooting version conflicts: https://aka.ms/azsdk/java/dependency/troubleshoot
16:01:48.458 [main] DEBUG com.azure.core.implementation.jackson.MemberNameConverterImpl - Failed to retrieve MethodHandles used to get naming strategy. Falling back to BeanUtils. Please consider updating your Jackson dependencies to at least version 2.12

**Comment by Yanglane2021** [comment]
Happened in  azure-core version 1.33.0

**Comment by alzimmermsft** [comment]
> 

This is the correct handling and just an informational message. The `MethodHandle` being used for Jackson 2.12 doesn't exist in Jackson 2.11
