### ISSUE TITLE
Batch: Improve playback test reliability

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk-for-java#3063]
One of the Batch tests appears to be flaky:

```
canCRUDTest
java.lang.RuntimeException: java.io.IOException: ==> Unexpected request: GET /jobs/BatchUser-canCRUDTest/tasks?api-version=2018-12-01.8.0&$select=id, state
	at com.microsoft.azure.batch.TaskTests.canCRUDTest(TaskTests.java:129)
Caused by: java.io.IOException: ==> Unexpected request: GET /jobs/BatchUser-canCRUDTest/tasks?api-version=2018-12-01.8.0&$select=id, state
	at com.microsoft.azure.batch.TaskTests.canCRUDTest(TaskTests.java:129)
```

https://dev.azure.com/azure-sdk/public/_build/results?buildId=7081&view=ms.vss-test-web.build-test-results-tab

The tests should be run in a loop for several hours to measure reliability.

CC: @g2vinay

**Comment by mikeharder** [comment]
Closing due to lack of recent failures.  Test only failed once in past 14 days, and zero failures in past 7 days.
