### ISSUE TITLE
Jackson Data bind conflict  com.azure.core.implementation.jackson.ObjectMapperFactory:performLogging(491) | Failed to retrieve MethodHandles used to set coercion configurations. Setting coercion configurations will be skipped. java.lang.IllegalAccessException: no such method: com.fasterxml.jackson.databind.ObjectMapper.coercionConfigDefaults()MutableCoercionConfig/invokeVirtual

### ISSUE THREAD

**Issue by MohakWadhwani** [Azure/azure-sdk-for-java#30662]
In Similar lines with 30554 

Hey @alzimmermsft @joshfree

We upgraded the version of azure core to 1.30.0 but seems other similar issues

we are executing the application with javaagent:applicationinsights 3.3.1 so may be dependencies from app insights are causing this issue.

Executing java -Xms512m -Xmx6G -XX:+UseG1GC -javaagent:applicationinsights-agent.jar -DAUTOMENU_date=2022-08-23 -DDD=23 -DMM=08 -DYYYY=2022 -DUSER=dmqa -cp /3.0.1/app-3.0.1.jar com..main.MainClass

2022-08-25 14:17:11,526 | INFO | [main] | com.azure.core.implementation.jackson.JacksonVersion:info(222) | Package versions: jackson-annotations=2.13.3, jackson-core=2.13.3, jackson-databind=2.13.3, jackson-dataformat-xml=2.13.3, jackson-datatype-jsr310=2.13.3, azure-core=1.30.0, Troubleshooting version conflicts: https://aka.ms/azsdk/java/dependency/troubleshoot
2022-08-25 14:17:11,541 | DEBUG | [main] | com.azure.core.implementation.jackson.ObjectMapperFactory:performLogging(491) | Failed to retrieve MethodHandles used to set coercion configurations. Setting coercion configurations will be skipped.
java.lang.IllegalAccessException: no such method: com.fasterxml.jackson.databind.ObjectMapper.coercionConfigDefaults()MutableCoercionConfig/invokeVirtual
at java.lang.invoke.MemberName.makeAccessException(MemberName.java:959) ~[?:?]
at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1101) ~[?:?]
at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:2030) ~[?:?]
at java.lang.invoke.MethodHandles$Lookup.findVirtual(MethodHandles.java:1194) ~[?:?]
at com.azure.core.implementation.jackson.ObjectMapperFactory.(ObjectMapperFactory.java:52) ~[azure-core-1.30.0.jar:1.30.0]
at com.azure.core.implementation.jackson.ObjectMapperFactory.(ObjectMapperFactory.java:42) ~[azure-core-1.30.0.jar:1.30.0]
at com.azure.core.implementation.jackson.ObjectMapperShim.createHeaderMapper(ObjectMapperShim.java:135) ~[azure-core-1.30.0.jar:1.30.0]
at com.azure.core.util.serializer.JacksonAdapter.(JacksonAdapter.java:81) ~[azure-core-1.30.0.jar:1.30.0]
at com.azure.core.util.serializer.JacksonAdapter.(JacksonAdapter.java:59) ~[azure-core-1.30.0.jar:1.30.0]
at com.azure.core.util.serializer.JacksonAdapter$SerializerAdapterHolder.(JacksonAdapter.java:114) ~[azure-core-1.30.0.jar:1.30.0]
at com.azure.core.util.serializer.JacksonAdapter.createDefaultSerializerAdapter(JacksonAdapter.java:123) ~[azure-core-1.30.0.jar:1.30.0]
at com.azure.identity.implementation.IdentityClient.(IdentityClient.java:104) ~[azure-identity-1.5.3.jar:1.5.3]
at com.azure.identity.implementation.IdentityClientBuilder.build(IdentityClientBuilder.java:158) ~[azure-identity-1.5.3.jar:1.5.3]
at com.azure.identity.ManagedIdentityCredential.(ManagedIdentityCredential.java:88) ~[azure-identity-1.5.3.jar:1.5.3]
at com.azure.identity.ManagedIdentityCredentialBuilder.build(ManagedIdentityCredentialBuilder.java:57) ~[azure-identity-1.5.3.jar:1.5.3]
at com.xx.azure.appconfig.TokenCredentialFactory.remoteCredential(TokenCredentialFactory.java:64) ~[azure-app-config-1.0.12.jar:1.0.12]
at com.xx.azure.appconfig.TokenCredentialFactory.get(TokenCredentialFactory.java:53) ~[azure-app-config-1.0.12.jar:1.0.12]
at com.xx.azure.appconfig.spring.AzurePropertySourcesPlaceHolderConfigurer.(AzurePropertySourcesPlaceHolderConfigurer.java:42) ~[azure-app-config-1.0.12.jar:1.0.12]
at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:211) ~[spring-beans-5.3.20.jar:5.3.20]
at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:117) ~[spring-beans-5.3.20.jar:5.3.20]
at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:311) ~[spring-beans-5.3.20.jar:5.3.20]
at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:296) ~[spring-beans-5.3.20.jar:5.3.20]
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372) ~[spring-beans-5.3.20.jar:5.3.20]
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222) ~[spring-beans-5.3.20.jar:5.3.20]
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582) ~[spring-beans-5.3.20.jar:5.3.20]
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.20.jar:5.3.20]
at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.20.jar:5.3.20]
at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) [spring-beans-5.3.20.jar:5.3.20]
at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) [spring-beans-5.3.20.jar:5.3.20]
at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:213) [spring-beans-5.3.20.jar:5.3.20]
at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:171) [spring-context-5.3.20.jar:5.3.20]
at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:746) [spring-context-5.3.20.jar:5.3.20]
at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:564) [spring-context-5.3.20.jar:5.3.20]
at org.springframework.context.support.ClassPathXmlApplicationContext.(ClassPathXmlApplicationContext.java:144) [spring-context-5.3.20.jar:5.3.20]
at org.springframework.context.support.ClassPathXmlApplicationContext.(ClassPathXmlApplicationContext.java:85) [spring-context-5.3.20.jar:5.3.20]
at com.xx.dm.facts.main.FactsInvoker.main(FactsInvoker.java:36) [FactsFramework-3.0.1.jar:3.0.1]
Caused by: java.lang.LinkageError: loader constraint violation: when resolving method "com.fasterxml.jackson.databind.ObjectMapper.coercionConfigDefaults()Lcom/fasterxml/jackson/databind/cfg/MutableCoercionConfig;" the class loader 'bootstrap' of the current class, java/lang/Object, and the class loader 'app' (instance of jdk.internal.loader.ClassLoaders$AppClassLoader) for the method's defining class, com/fasterxml/jackson/databind/ObjectMapper, have different Class objects for the type com/fasterxml/jackson/databind/cfg/MutableCoercionConfig used in the signature
at java.lang.invoke.MethodHandleNatives.resolve(Native Method) ~[?:?]
at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:1070) ~[?:?]
at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1098) ~[?:?]
... 38 more
2022-08-25 14:17:11,646 | DEBUG | [main] | com.azure.core.implementation.jackson.MemberNameConverterImpl:performLogging(491) | Failed to retrieve MethodHandles used to get naming strategy. Falling back to BeanUtils.
java.lang.IllegalAccessException: no such method: com.fasterxml.jackson.databind.cfg.MapperConfig.getAccessorNaming()Provider/invokeVirtual
at java.lang.invoke.MemberName.makeAccessException(MemberName.java:959) ~[?:?]
at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1101) ~[?:?]
at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:2030) ~[?:?]
at java.lang.invoke.MethodHandles$Lookup.findVirtual(MethodHandles.java:1194) ~[?:?]
at com.azure.core.implementation.jackson.MemberNameConverterImpl.(MemberNameConverterImpl.java:57) ~[azure-core-1.30.0.jar:1.30.0]
at com.azure.core.implementation.jackson.ObjectMapperShim.(ObjectMapperShim.java:148) ~[azure-core-1.30.0.jar:1.30.0]
at com.azure.core.implementation.jackson.ObjectMapperShim.createHeaderMapper(ObjectMapperShim.java:136) ~[azure-core-1.30.0.jar:1.30.0]
at com.azure.core.util.serializer.JacksonAdapter.(JacksonAdapter.java:81) ~[azure-core-1.30.0.jar:1.30.0]
at com.azure.core.util.serializer.JacksonAdapter.(JacksonAdapter.java:59) ~[azure-core-1.30.0.jar:1.30.0]
at com.azure.core.util.serializer.JacksonAdapter$SerializerAdapterHolder.(JacksonAdapter.java:114) ~[azure-core-1.30.0.jar:1.30.0]
at com.azure.core.util.serializer.JacksonAdapter.createDefaultSerializerAdapter(JacksonAdapter.java:123) ~[azure-core-1.30.0.jar:1.30.0]
at com.azure.identity.implementation.IdentityClient.(IdentityClient.java:104) ~[azure-identity-1.5.3.jar:1.5.3]
at com.azure.identity.implementation.IdentityClientBuilder.build(IdentityClientBuilder.java:158) ~[azure-identity-1.5.3.jar:1.5.3]
at com.azure.identity.ManagedIdentityCredential.(ManagedIdentityCredential.java:88) ~[azure-identity-1.5.3.jar:1.5.3]
at com.azure.identity.ManagedIdentityCredentialBuilder.build(ManagedIdentityCredentialBuilder.java:57) ~[azure-identity-1.5.3.jar:1.5.3]
at com.msci.azure.appconfig.TokenCredentialFactory.remoteCredential(TokenCredentialFactory.java:64) ~[azure-app-config-1.0.12.jar:1.0.12]
at com.msci.azure.appconfig.TokenCredentialFactory.get(TokenCredentialFactory.java:53) ~[azure-app-config-1.0.12.jar:1.0.12]
at com.msci.azure.appconfig.spring.AzurePropertySourcesPlaceHolderConfigurer.(AzurePropertySourcesPlaceHolderConfigurer.java:42) ~[azure-app-config-1.0.12.jar:1.0.12]
at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:211) ~[spring-beans-5.3.20.jar:5.3.20]
at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:117) ~[spring-beans-5.3.20.jar:5.3.20]
at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:311) ~[spring-beans-5.3.20.jar:5.3.20]
at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:296) ~[spring-beans-5.3.20.jar:5.3.20]
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372) ~[spring-beans-5.3.20.jar:5.3.20]
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222) ~[spring-beans-5.3.20.jar:5.3.20]
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582) ~[spring-beans-5.3.20.jar:5.3.20]
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.20.jar:5.3.20]
at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.20.jar:5.3.20]
at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) [spring-beans-5.3.20.jar:5.3.20]
at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) [spring-beans-5.3.20.jar:5.3.20]
at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:213) [spring-beans-5.3.20.jar:5.3.20]
at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:171) [spring-context-5.3.20.jar:5.3.20]
at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:746) [spring-context-5.3.20.jar:5.3.20]
at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:564) [spring-context-5.3.20.jar:5.3.20]
at org.springframework.context.support.ClassPathXmlApplicationContext.(ClassPathXmlApplicationContext.java:144) [spring-context-5.3.20.jar:5.3.20]
at org.springframework.context.support.ClassPathXmlApplicationContext.(ClassPathXmlApplicationContext.java:85) [spring-context-5.3.20.jar:5.3.20]
at com.xxx.dm.facts.main.FactsInvoker.main(FactsInvoker.java:36) [FactsFramework-3.0.1.jar:3.0.1]
Caused by: java.lang.LinkageError: loader constraint violation: when resolving method "com.fasterxml.jackson.databind.cfg.MapperConfig.getAccessorNaming()Lcom/fasterxml/jackson/databind/introspect/AccessorNamingStrategy$Provider;" the class loader 'bootstrap' of the current class, java/lang/Object, and the class loader 'app' (instance of jdk.internal.loader.ClassLoaders$AppClassLoader) for the method's defining class, com/fasterxml/jackson/databind/cfg/MapperConfig, have different Class objects for the type com/fasterxml/jackson/databind/introspect/AccessorNamingStrategy$Provider used in the signature
at java.lang.invoke.MethodHandleNatives.resolve(Native Method) ~[?:?]
at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:1070) ~[?:?]
at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1098) ~[?:?]
... 38 more
2022-08-25 14:17:11,673 | DEBUG | [main] | com.azure.core.implementation.jackson.ObjectMapperFactory:verbose(174) | Didn't set coercion defaults as it wasn't found on the classpath.
2022-08-25 14:17:11,895 | DEBUG | [main] | com.azure.identity.ManagedIdentityCredential:performLogging(491) | Azure Identity => Found the following environment variables:
2022-08-25 14:17:12,161 | DEBUG | [main] | com.azure.core.implementation.jackson.ObjectMapperFactory:verbose(174) | Didn't set coercion defaults as it wasn't found on the classpath.

**Comment by alzimmermsft** [comment]
Thanks for filing this @MohakWadhwani, could you include the output of `mvn dependency:tree -f <your POM>` to help determine if this is a version conflict happening.

If the version of Jackson Databind being resolved is 2.11 or below this isn't an issue as these classes don't exist in that version and what is trying to be reflective configured doesn't need to happen. If it is 2.12 or above then this will need further investigation.

**Comment by MohakWadhwani** [comment]
Hey @alzimmermsft  PFB the dep tree

[INFO] --- maven-dependency-plugin:3.1.2:tree (default-cli) @ FactsFramework ---
[INFO] com.msci.dm:FactsFramework:jar:3.0.0-SNAPSHOT
[INFO] +- commons-collections:commons-collections:jar:3.2.2:compile
[INFO] +- commons-logging:commons-logging:jar:1.2:compile
[INFO] +- org.springframework:spring-jdbc:jar:5.3.20:compile
[INFO] |  +- org.springframework:spring-beans:jar:5.3.20:compile
[INFO] |  \- org.springframework:spring-tx:jar:5.3.20:compile
[INFO] +- org.springframework:spring-core:jar:5.3.20:compile
[INFO] |  \- org.springframework:spring-jcl:jar:5.3.20:compile
[INFO] +- org.springframework:spring-context:jar:5.3.20:compile
[INFO] |  \- org.springframework:spring-expression:jar:5.3.20:compile
[INFO] +- org.springframework:spring-aop:jar:5.3.20:compile
[INFO] +- org.aspectj:aspectjweaver:jar:1.7.4:compile
[INFO] +- org.aspectj:aspectjrt:jar:1.7.4:compile
[INFO] +- commons-cli:commons-cli:jar:1.2:compile
[INFO] +- org.springframework:spring-test:jar:5.3.20:compile
[INFO] +- junit:junit:jar:4.13.1:test
[INFO] |  \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] +- cglib:cglib-nodep:jar:3.1:test
[INFO] +- com.msci.common:util:jar:8.35.2:compile
[INFO] |  +- org.slf4j:slf4j-api:jar:1.7.35:compile
[INFO] |  +- commons-dbcp:commons-dbcp:jar:1.4:compile
[INFO] |  |  \- commons-pool:commons-pool:jar:1.5.4:compile
[INFO] |  +- commons-configuration:commons-configuration:jar:1.7:compile
[INFO] |  |  +- commons-lang:commons-lang:jar:2.6:compile
[INFO] |  |  \- commons-digester:commons-digester:jar:1.8.1:compile
[INFO] |  +- jtemporal:jtemporal:jar:0.80:compile
[INFO] |  +- com.github.stefanbirkner:system-rules:jar:1.19.0:compile
[INFO] |  +- com.google.guava:guava:jar:31.0.1-jre:compile
[INFO] |  |  +- com.google.guava:failureaccess:jar:1.0.1:compile
[INFO] |  |  +- com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava:compile
[INFO] |  |  +- com.google.code.findbugs:jsr305:jar:3.0.2:compile
[INFO] |  |  +- org.checkerframework:checker-qual:jar:3.12.0:compile
[INFO] |  |  +- com.google.errorprone:error_prone_annotations:jar:2.7.1:compile
[INFO] |  |  \- com.google.j2objc:j2objc-annotations:jar:1.3:compile
[INFO] |  +- com.sun.xsom:xsom:jar:20110809:compile
[INFO] |  |  \- relaxngDatatype:relaxngDatatype:jar:20020414:compile
[INFO] |  +- com.sun.mail:javax.mail:jar:1.6.0-rc2:compile
[INFO] |  |  \- javax.activation:activation:jar:1.1:compile
[INFO] |  +- org.apache.commons:commons-lang3:jar:3.12.0:compile
[INFO] |  \- commons-beanutils:commons-beanutils:jar:1.9.4:compile
[INFO] +- org.easymock:easymock:jar:3.4:compile
[INFO] |  \- org.objenesis:objenesis:jar:2.2:compile
[INFO] +- com.oracle.database.jdbc:ojdbc11:jar:21.5.0.0:compile
[INFO] +- org.jmock:jmock:jar:2.6.0:test
[INFO] |  \- org.hamcrest:hamcrest-library:jar:1.1:test
[INFO] +- org.jmock:jmock-legacy:jar:2.6.0:test
[INFO] +- org.hamcrest:hamcrest-all:jar:1.3:test
[INFO] +- org.apache.logging.log4j:log4j-api:jar:2.17.1:compile
[INFO] +- org.apache.logging.log4j:log4j-core:jar:2.17.1:compile
[INFO] +- org.apache.logging.log4j:log4j-jcl:jar:2.17.1:compile
[INFO] +- org.apache.logging.log4j:log4j-jul:jar:2.17.1:compile
[INFO] +- org.apache.logging.log4j:log4j-slf4j-impl:jar:2.17.1:compile
[INFO] +- org.projectlombok:lombok:jar:1.18.0:compile
[INFO] +- com.zaxxer:HikariCP:jar:5.0.0:compile
[INFO] +- com.msci.azure:azure-app-config:jar:1.0.12:compile
[INFO] |  +- com.azure:azure-data-appconfiguration:jar:1.3.5:compile
[INFO] |  |  \- com.azure:azure-core-http-netty:jar:1.12.3:compile
[INFO] |  |     +- io.netty:netty-handler:jar:4.1.78.Final:compile
[INFO] |  |     |  +- io.netty:netty-common:jar:4.1.78.Final:compile
[INFO] |  |     |  +- io.netty:netty-resolver:jar:4.1.78.Final:compile
[INFO] |  |     |  +- io.netty:netty-transport:jar:4.1.78.Final:compile
[INFO] |  |     |  \- io.netty:netty-codec:jar:4.1.78.Final:compile
[INFO] |  |     +- io.netty:netty-handler-proxy:jar:4.1.78.Final:compile
[INFO] |  |     |  \- io.netty:netty-codec-socks:jar:4.1.78.Final:compile
[INFO] |  |     +- io.netty:netty-buffer:jar:4.1.78.Final:compile
[INFO] |  |     +- io.netty:netty-codec-http:jar:4.1.78.Final:compile
[INFO] |  |     +- io.netty:netty-codec-http2:jar:4.1.78.Final:compile
[INFO] |  |     +- io.netty:netty-transport-native-unix-common:jar:4.1.78.Final:compile
[INFO] |  |     +- io.netty:netty-transport-native-epoll:jar:linux-x86_64:4.1.78.Final:compile
[INFO] |  |     |  \- io.netty:netty-transport-classes-epoll:jar:4.1.78.Final:compile
[INFO] |  |     +- io.netty:netty-transport-native-kqueue:jar:osx-x86_64:4.1.78.Final:compile
[INFO] |  |     |  \- io.netty:netty-transport-classes-kqueue:jar:4.1.78.Final:compile
[INFO] |  |     +- io.netty:netty-tcnative-boringssl-static:jar:2.0.53.Final:compile
[INFO] |  |     |  +- io.netty:netty-tcnative-classes:jar:2.0.53.Final:compile
[INFO] |  |     |  +- io.netty:netty-tcnative-boringssl-static:jar:linux-x86_64:2.0.53.Final:compile
[INFO] |  |     |  +- io.netty:netty-tcnative-boringssl-static:jar:linux-aarch_64:2.0.53.Final:compile
[INFO] |  |     |  +- io.netty:netty-tcnative-boringssl-static:jar:osx-x86_64:2.0.53.Final:compile
[INFO] |  |     |  +- io.netty:netty-tcnative-boringssl-static:jar:osx-aarch_64:2.0.53.Final:compile
[INFO] |  |     |  \- io.netty:netty-tcnative-boringssl-static:jar:windows-x86_64:2.0.53.Final:compile
[INFO] |  |     \- io.projectreactor.netty:reactor-netty-http:jar:1.0.20:compile
[INFO] |  |        +- io.netty:netty-resolver-dns:jar:4.1.77.Final:compile
[INFO] |  |        |  \- io.netty:netty-codec-dns:jar:4.1.77.Final:compile
[INFO] |  |        +- io.netty:netty-resolver-dns-native-macos:jar:osx-x86_64:4.1.77.Final:compile
[INFO] |  |        |  \- io.netty:netty-resolver-dns-classes-macos:jar:4.1.77.Final:compile
[INFO] |  |        \- io.projectreactor.netty:reactor-netty-core:jar:1.0.20:compile
[INFO] |  +- com.azure:azure-core-http-okhttp:jar:1.11.0:compile
[INFO] |  |  \- com.squareup.okhttp3:okhttp:jar:4.10.0:compile
[INFO] |  |     +- com.squareup.okio:okio-jvm:jar:3.0.0:compile
[INFO] |  |     |  +- org.jetbrains.kotlin:kotlin-stdlib-jdk8:jar:1.5.31:compile
[INFO] |  |     |  |  \- org.jetbrains.kotlin:kotlin-stdlib-jdk7:jar:1.5.31:compile
[INFO] |  |     |  \- org.jetbrains.kotlin:kotlin-stdlib-common:jar:1.5.31:compile
[INFO] |  |     \- org.jetbrains.kotlin:kotlin-stdlib:jar:1.6.20:compile
[INFO] |  |        \- org.jetbrains:annotations:jar:13.0:compile
[INFO] |  +- com.azure:azure-identity:jar:1.5.3:compile
[INFO] |  |  +- com.microsoft.azure:msal4j:jar:1.12.0:compile
[INFO] |  |  |  +- com.nimbusds:oauth2-oidc-sdk:jar:9.32:compile
[INFO] |  |  |  |  +- com.github.stephenc.jcip:jcip-annotations:jar:1.0-1:compile
[INFO] |  |  |  |  +- com.nimbusds:content-type:jar:2.2:compile
[INFO] |  |  |  |  +- com.nimbusds:lang-tag:jar:1.6:compile
[INFO] |  |  |  |  \- com.nimbusds:nimbus-jose-jwt:jar:9.21:compile
[INFO] |  |  |  \- net.minidev:json-smart:jar:2.4.8:compile
[INFO] |  |  |     \- net.minidev:accessors-smart:jar:2.4.8:compile
[INFO] |  |  |        \- org.ow2.asm:asm:jar:9.1:compile
[INFO] |  |  +- com.microsoft.azure:msal4j-persistence-extension:jar:1.1.0:compile
[INFO] |  |  |  \- net.java.dev.jna:jna:jar:5.5.0:compile
[INFO] |  |  \- net.java.dev.jna:jna-platform:jar:5.6.0:compile
[INFO] |  +- com.azure:azure-security-keyvault-secrets:jar:4.4.4:compile
[INFO] |  \- com.azure:azure-core:jar:1.30.0:compile
[INFO] |     +- com.fasterxml.jackson.core:jackson-annotations:jar:2.13.3:compile
[INFO] |     +- com.fasterxml.jackson.core:jackson-core:jar:2.13.3:compile
[INFO] |     +- com.fasterxml.jackson.core:jackson-databind:jar:2.13.3:compile
[INFO] |     +- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.13.3:compile
[INFO] |     +- com.fasterxml.jackson.dataformat:jackson-dataformat-xml:jar:2.13.3:compile
[INFO] |     |  +- org.codehaus.woodstox:stax2-api:jar:4.2.1:compile
[INFO] |     |  \- com.fasterxml.woodstox:woodstox-core:jar:6.2.7:compile
[INFO] |     \- io.projectreactor:reactor-core:jar:3.4.19:compile
[INFO] |        \- org.reactivestreams:reactive-streams:jar:1.0.4:compile
[INFO] +- xerces:xercesImpl:jar:2.12.2:compile
[INFO] |  \- xml-apis:xml-apis:jar:1.4.01:compile
[INFO] +- javax.annotation:javax.annotation-api:jar:1.3.2:compile
[INFO] +- com.microsoft.azure:applicationinsights-agent:jar:3.3.1:compile
[INFO] \- io.opentelemetry:opentelemetry-api:jar:1.6.0:compile
[INFO]    \- io.opentelemetry:opentelemetry-context:jar:1.6.0:compile
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS

**Comment by MohakWadhwani** [comment]
@alzimmermsft Yes its all in one jar.

This the below command what we execute 
Executing java -Xms512m -Xmx6G -XX:+UseG1GC -javaagent:applicationinsights-agent.jar -DAUTOMENU_date=2022-08-23 -DDD=23 -DMM=08 -DYYYY=2022 -DUSER=dmqa -cp /3.0.1/app-3.0.1.jar com..main.MainClass

the dependency tree mentioned above is for app-3.0.1.jar

i suspect the issue comes when we run it with -javaagent:applicationinsights-agent.jar
because in local when we run app-3.0.1.jar com..main.MainClass this issue never comes.

**Comment by alzimmermsft** [comment]
Thanks @MohakWadhwani, this actually leads to one more question.

You mentioned locally this doesn't happen, when this is failing is this in a hosted environment such as Databricks, Synapse, Azure Functions, etc? The root cause could also be that the hosted environment is polluting the classpath causing older versions of Jackson to be used.
