### ISSUE TITLE
[BUG] Null Pointer Exception during alertRules().activityLogAlerts()

### ISSUE THREAD

**Issue by danilomilano** [Azure/azure-sdk-for-java#30684]
**Describe the bug**

A null pointer exception is being presented during _alertRules().activityLogAlerts().list()_ request.

***Exception or Stack Trace***

```
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NullPointerException: null
	at java.base/java.util.TreeMap.put(TreeMap.java:561)
	at com.azure.resourcemanager.monitor.implementation.ActivityLogAlertImpl.<init>(ActivityLogAlertImpl.java:39)
	at com.azure.resourcemanager.monitor.implementation.ActivityLogAlertsImpl.wrapModel(ActivityLogAlertsImpl.java:33)
	at com.azure.resourcemanager.monitor.implementation.ActivityLogAlertsImpl.wrapModel(ActivityLogAlertsImpl.java:14)
	at com.azure.resourcemanager.resources.fluentcore.arm.collection.implementation.ReadableWrappersImpl.lambda$wrapPageAsync$1(ReadableWrappersImpl.java:32)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com.azure.resourcemanager.resources.fluentcore.utils.PagedConverter.lambda$mapPagedResponse$6(PagedConverter.java:111)
```

**To Reproduce**

- no _alertRules_ configured on Azure portal
- create an _AzureResourceManager_ client with a _ClientSecretCredential_ for authentication
- call _azureResourceManager.alertRules().activityLogAlerts().list().stream().collect(Collectors.toList());_

***Code Snippet***
`azureResourceManager.alertRules().activityLogAlerts().list()`

**Expected behavior**
The null alert rules and null log alerts should be treated to not present a null pointer exception.

** Screenshots **

![image](https://user-images.githubusercontent.com/3742440/187210753-dc1fef8f-f023-4ba1-a3c5-32d57439e22f.png)

**Setup (please complete the following information):**
 - OS: linux
 - IDE: IntelliJ
 - Library/Libraries: com.azure:azure-resourcemanager-monitor:2.17.0
 - Java version: 11
 - Frameworks: Spring Boot

**Comment by joshfree** [comment]
Thanks for reporting this issue, @danilomilano.  @weidongxu-microsoft could you please follow up?

**Comment by weidongxu-microsoft** [comment]
@XiaofeiCao 

Would you take a look? Though not sure why these fields are null.

**Comment by XiaofeiCao** [comment]
Hi @danilomilano 

I tried my subscription with no alert rules or alert logs, but experienced no NPE.

Could you share the log please? It should look like this:
> [reactor-http-nio-2] INFO com.azure.resourcemanager.monitor.implementation.ActivityLogAlertsClientImpl$ActivityLogAlertsService.list - <-- 200 https://management.azure.com/subscriptions/xxx/providers/microsoft.insights/activityLogAlerts?api-version=2017-04-01 (434 ms, 19-byte body)
xxx
Response body:
{
  "value" : [ ]
}

You may need to set the log level to `BODY_AND_HEADERS`:
```java
AzureResourceManager
  .configure()
  .withLogLevel(HttpLogDetailLevel.BODY_AND_HEADERS)
  .authenticate()
```

Thanks!

**Comment by danilomilano** [comment]
Hi @XiaofeiCao, 

I reproduced the scenario in one customer account with activity log alerts (id was changed only to no expose the data).

![image](https://user-images.githubusercontent.com/3742440/193594112-a05f2109-1c23-42c3-ac72-90565ff0efc9.png)


Note that condition.allOf contains 4 null values for field and equals.

![image](https://user-images.githubusercontent.com/3742440/193593397-ef86f458-7ecc-458e-b091-3a3ff1d49b34.png)


![image](https://user-images.githubusercontent.com/3742440/193595598-f9dc4c42-818b-49f1-891c-8979dcd6de34.png)

Thanks

**Comment by XiaofeiCao** [comment]
@danilomilano Thanks for the log, helps a lot. I'm curious why 4 of the conditions are null. 

If there's way we can know how the customer created the alert rule(through Azure Portal, Azure CLI or Java SDK), we'd love to have, it would help diagnose the issue further. 

If not, it's fine, we'll probably just add an NPE protection to prevent it from throwing in such situations.
