### ISSUE TITLE
[BUG] Error retriving billing in a CSP Azure offer using costmanagement io.netty.ChannelInitializer Exception caught

### ISSUE THREAD

**Issue by ablazleon** [Azure/azure-sdk-for-java#30682]
**Describe the bug**
We could not retrieve billing using the following code (in code snippet section). The instructions for authentication relating this code (https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/costmanagement/azure-resourcemanager-costmanagement/src/samples/java/com/azure/resourcemanager/costmanagement/QueryUsageSamples.java) were followed: it was registered an application so to get some keys,

***Exception or Stack Trace***

```
Aug 29, 2022 6:53:31 AM io.netty.channel.ChannelInitializer exceptionCaught
WARNING: Failed to initialize a channel. Closing: [id: 0x38baf396]
java.util.NoSuchElementException: reactor.left.sslHandler
        at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1073)
        at io.netty.channel.DefaultChannelPipeline.addAfter(DefaultChannelPipeline.java:302)
        at io.netty.channel.DefaultChannelPipeline.addAfter(DefaultChannelPipeline.java:290)
        at reactor.netty.tcp.SslProvider.addSslReadHandler(SslProvider.java:600)
        at reactor.netty.tcp.SslProvider.addSslHandler(SslProvider.java:562)
        at reactor.netty.http.client.HttpClientConfig$HttpClientChannelInitializer.onChannelInit(HttpClientConfig.java:824)
        at reactor.netty.transport.TransportConfig$TransportChannelInitializer.initChannel(TransportConfig.java:399)
        at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129)
        at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112)
        at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:938)
        at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609)
        at io.netty.channel.DefaultChannelPipeline.addFirst(DefaultChannelPipeline.java:181)
        at io.netty.channel.DefaultChannelPipeline.addFirst(DefaultChannelPipeline.java:358)
        at io.netty.channel.DefaultChannelPipeline.addFirst(DefaultChannelPipeline.java:339)
        at reactor.netty.resources.DefaultPooledConnectionProvider$PooledConnectionAllocator$PooledConnectionInitializer.initChannel(DefaultPooledConnectionProvider.java:524)
        at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129)
        at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112)
        at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:938)
        at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609)
        at io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46)
        at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1463)
        at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1115)
        at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:650)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:514)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register(AbstractChannel.java:480)
        at reactor.netty.transport.TransportConnector.doInitAndRegister(TransportConnector.java:240)
        at reactor.netty.transport.TransportConnector.lambda$connect$3(TransportConnector.java:115)
        at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44)
        at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.resubscribe(FluxRetryWhen.java:216)
        at reactor.core.publisher.FluxRetryWhen$RetryWhenOtherSubscriber.onNext(FluxRetryWhen.java:269)
        at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.innerNext(FluxConcatMap.java:282)
        at reactor.core.publisher.FluxConcatMap$ConcatMapInner.onNext(FluxConcatMap.java:863)
        at reactor.core.publisher.Operators$MonoSubscriber.request(Operators.java:1906)
        at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.request(Operators.java:2158)
        at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.request(FluxConcatMap.java:331)
        at reactor.core.publisher.Operators$DeferredSubscription.request(Operators.java:1680)
        at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.onError(FluxRetryWhen.java:192)
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondError(MonoFlatMap.java:192)
        at reactor.core.publisher.MonoFlatMap$FlatMapInner.onError(MonoFlatMap.java:259)
        at reactor.netty.transport.TransportConnector$MonoChannelPromise.tryFailure(TransportConnector.java:517)
        at reactor.netty.transport.TransportConnector$MonoChannelPromise.setFailure(TransportConnector.java:471)
        at reactor.netty.transport.TransportConnector.lambda$doConnect$7(TransportConnector.java:203)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
        at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:184)
        at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:95)
        at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:30)
        at reactor.netty.transport.TransportConnector.lambda$doConnect$8(TransportConnector.java:188)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

**To Reproduce**

- 1. An application was registered in azure. 
- 2. This authentication variables are exported in the shell.
- 3. The code is executed.

***Code Snippet***
```
import com.azure.core.credential.TokenCredential;
import com.azure.core.management.AzureEnvironment;
import com.azure.core.management.profile.AzureProfile;
import com.azure.identity.DefaultAzureCredentialBuilder;
import com.azure.core.util.Context;
import com.azure.resourcemanager.costmanagement.CostManagementManager;
import com.azure.resourcemanager.costmanagement.models.ExportType;
import com.azure.resourcemanager.costmanagement.models.FunctionType;
import com.azure.resourcemanager.costmanagement.models.GranularityType;
import com.azure.resourcemanager.costmanagement.models.QueryAggregation;
import com.azure.resourcemanager.costmanagement.models.QueryColumnType;
import com.azure.resourcemanager.costmanagement.models.QueryDataset;
import com.azure.resourcemanager.costmanagement.models.QueryDefinition;
import com.azure.resourcemanager.costmanagement.models.QueryGrouping;
import com.azure.resourcemanager.costmanagement.models.TimeframeType;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;

// Sample to query in a table
public class Query {

  public static void main(String[] args) {

    // Azure
    AzureProfile profile = new AzureProfile(AzureEnvironment.AZURE);
    TokenCredential credential = new DefaultAzureCredentialBuilder()
            .authorityHost(profile.getEnvironment().getActiveDirectoryEndpoint())
            .build();
    // System.out.println(profile.getTenantId());
    CostManagementManager manager = CostManagementManager
            .authenticate(credential, profile);
    System.out.println(System.getenv("AZURE_TENANT_ID"));
    System.out.println(System.getenv("AZURE_CLIENT_ID"));
    System.out.println(System.getenv("AZURE_CLIENT_SECRET"));

    
    try{
        subscriptionQueryLegacy(manager);
    }
     catch (final Exception e) {
        System.out.println(e);
    }

  }

    @SuppressWarnings("unchecked")
    private static <T> Map<String, T> mapOf(Object... inputs) {
        Map<String, T> map = new HashMap<>();
        for (int i = 0; i < inputs.length; i += 2) {
            String key = (String) inputs[i];
            T value = (T) inputs[i + 1];
            map.put(key, value);
        }
        return map;
    }

    /**
     * Este código funciona en la función de prueba de azure
     * 
     * Sample code: SubscriptionQuery-Legacy.
     *
     * @param costManagementManager Entry point to CostManagementManager.
     */
    public static void subscriptionQueryLegacy(
        com.azure.resourcemanager.costmanagement.CostManagementManager costManagementManager) {
        costManagementManager
            .queries()
            .usageWithResponse(
                "subscriptions/xxxxxxxxxxxxxxxxxxxxxxx",
                new QueryDefinition()
                    .withType(ExportType.USAGE)
                    .withTimeframe(TimeframeType.MONTH_TO_DATE)
                    .withDataset(
                        new QueryDataset()
                            .withGranularity(GranularityType.DAILY)
                           ),
                Context.NONE);
    }


}

```

**Expected behavior**
When this code was run in the try it section of the costmanager api documentation the billing was retrieve.

**Screenshots**

Error screenshot:

![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/28836810/187140198-52c4d864-9e21-426f-aafb-cef74931d75e.png)

**Setup (please complete the following information):**
 - OS: in GCP cloud shell
 - Library/Libraries: costmanager sdk

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by ablazleon** [comment]
It's solved! I looked for similar errors in google and it was said this issue was relating to a netty packeage not include. In the readme it was described to use netty for authentication but no package was written. Finally, I found one in the resource manager part of the sdk and included it in the pom.xml:

```
    <dependency>
        <groupId>com.azure</groupId>
        <artifactId>azure-core-http-netty</artifactId>
        <version>1.12.4</version>
    </dependency>
```
