### ISSUE TITLE
[FEATURE REQ] KeyVault JCA does not  work under JDK 17

### ISSUE THREAD

**Issue by moarychan** [Azure/azure-sdk-for-java#30717]
**Is your feature request related to a problem? Please describe.**
The `azure-security-keyvault-jca` can not work fine under JDK 17 and Spring Boot 3. When using the `azure-security-keyvault-jca-2.7.0`, the below exception occurs:

```console
org.springframework.context.ApplicationContextException: Unable to start web server
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:164) ~[spring-boot-3.0.0-M4.jar!/:3.0.0-M4]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:586) ~[spring-context-6.0.0-M5.jar!/:6.0.0-M5]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[spring-boot-3.0.0-M4.jar!/:3.0.0-M4]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:731) ~[spring-boot-3.0.0-M4.jar!/:3.0.0-M4]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:430) ~[spring-boot-3.0.0-M4.jar!/:3.0.0-M4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312) ~[spring-boot-3.0.0-M4.jar!/:3.0.0-M4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303) ~[spring-boot-3.0.0-M4.jar!/:3.0.0-M4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292) ~[spring-boot-3.0.0-M4.jar!/:3.0.0-M4]
	at com.azure.spring.boot.sample.webapp.SpringBootWebappApplication.main(SpringBootWebappApplication.java:15) ~[classes!/:1.0.0]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[run-with-command-line-server-side-1.0.0-17.jar:1.0.0]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:95) ~[run-with-command-line-server-side-1.0.0-17.jar:1.0.0]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[run-with-command-line-server-side-1.0.0-17.jar:1.0.0]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65) ~[run-with-command-line-server-side-1.0.0-17.jar:1.0.0]
Caused by: java.lang.InternalError: internal error: SHA-1 not available.
	at java.base/sun.security.provider.SecureRandom.init(SecureRandom.java:114) ~[na:na]
	at java.base/sun.security.provider.SecureRandom.<init>(SecureRandom.java:85) ~[na:na]
	at java.base/java.security.SecureRandom.getDefaultPRNG(SecureRandom.java:291) ~[na:na]
	at java.base/java.security.SecureRandom.<init>(SecureRandom.java:225) ~[na:na]
	at java.base/java.nio.file.TempFileHelper.<clinit>(TempFileHelper.java:53) ~[na:na]
	at java.base/java.nio.file.Files.createTempDirectory(Files.java:1017) ~[na:na]
	at org.springframework.boot.web.server.AbstractConfigurableWebServerFactory.createTempDir(AbstractConfigurableWebServerFactory.java:202) ~[spring-boot-3.0.0-M4.jar!/:3.0.0-M4]
	at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getWebServer(TomcatServletWebServerFactory.java:194) ~[spring-boot-3.0.0-M4.jar!/:3.0.0-M4]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:183) ~[spring-boot-3.0.0-M4.jar!/:3.0.0-M4]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:161) ~[spring-boot-3.0.0-M4.jar!/:3.0.0-M4]
	... 16 common frames omitted
Caused by: java.security.NoSuchAlgorithmException: SHA MessageDigest not available
	at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:159) ~[na:na]
	at java.base/java.security.MessageDigest.getInstance(MessageDigest.java:185) ~[na:na]
	at java.base/sun.security.provider.SecureRandom.init(SecureRandom.java:112) ~[na:na]
	... 25 common frames omitted
```

**Describe the solution you'd like**
N/A

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [ ] Expected solution specified

**Comment by moarychan** [comment]
The Azure KeyVault JCA can work with Java 17. I am sorry that the previous conclusion is due to my personal mistakes, the same exception will occur if the path to the custom `java.security` file we pass is invalid.
Below is my new testing result,  I am going to closing this issue first, and will add back the jca samples for Spring CLoud Azure 6.0 branch.
![image](https://user-images.githubusercontent.com/19926623/196149890-af77b84a-bbdc-439c-bae3-a1250d0086cd.png)
