### ISSUE TITLE
[BUG] [SB] SynchronousReceiverClient stops abruptly by logging the error 'bound must be greater than origin' and couldn't recover.

### ISSUE THREAD

**Issue by vpeddada** [Azure/azure-sdk-for-java#30765]
**Describe the bug**
One of our customer's environment had encountered issue with Service Bus Receiver using Topic-Subscription. We developed the receiver using Synchronous Receiver Client using Azure Service Bus Java SDK 7.10.1 with OAuth as follows:
However after certain period of time, the client encounters errors and couldn't recover using the retry config

***Exception or Stack Trace***
2022-08-31T11:58:33,509 ERROR [reactor-executor-1] c.a.c.amqp.implementation.RetryUtil - Failed to create receive link horizon.buy.out.po.common.sd.t/subscriptions/liquor_food.wms.po_73f434_1661907172730
bound must be greater than origin
java.lang.IllegalArgumentException: bound must be greater than origin
	at java.base/java.util.concurrent.ThreadLocalRandom.nextLong(ThreadLocalRandom.java:388)
	at reactor.util.retry.RetryBackoffSpec.lambda$generateCompanion$4(RetryBackoffSpec.java:599)
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:374)
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onNext(FluxConcatMap.java:250)
	at reactor.core.publisher.EmitterProcessor.drain(EmitterProcessor.java:491)
	at reactor.core.publisher.EmitterProcessor.tryEmitNext(EmitterProcessor.java:299)
	at reactor.core.publisher.SinkManySerialized.tryEmitNext(SinkManySerialized.java:97)
	at reactor.core.publisher.InternalManySink.emitNext(InternalManySink.java:27)
	at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.onError(FluxRetryWhen.java:189)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:106)
	at reactor.core.publisher.Operators.error(Operators.java:197)
	at reactor.core.publisher.MonoError.subscribe(MonoError.java:52)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4150)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onError(FluxPeekFuseable.java:234)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondError(MonoFlatMap.java:192)
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onError(MonoFlatMap.java:259)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondError(MonoFlatMap.java:192)
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onError(MonoFlatMap.java:259)
	at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:132)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:106)
	at reactor.core.publisher.Operators.error(Operators.java:197)
	at reactor.core.publisher.MonoErrorSupplied.subscribe(MonoErrorSupplied.java:71)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4150)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onError(MonoIgnoreThen.java:270)
	at reactor.core.publisher.MonoWhen$WhenCoordinator.signalError(MonoWhen.java:172)
	at reactor.core.publisher.MonoWhen$WhenInner.onError(MonoWhen.java:288)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onError(FluxMapFuseable.java:140)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondError(MonoFlatMap.java:192)
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onError(MonoFlatMap.java:259)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondError(MonoFlatMap.java:192)
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onError(MonoFlatMap.java:259)
	at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onError(FluxHide.java:141)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onError(Operators.java:2062)
	at reactor.core.publisher.FluxHandle$HandleSubscriber.onError(FluxHandle.java:202)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onError(MonoIgnoreThen.java:270)
	at reactor.core.publisher.MonoCreate$DefaultMonoSink.error(MonoCreate.java:189)
	at com.azure.core.amqp.implementation.RequestResponseChannel.terminateUnconfirmedSends(RequestResponseChannel.java:479)
	at com.azure.core.amqp.implementation.RequestResponseChannel.onTerminalState(RequestResponseChannel.java:435)
	at com.azure.core.amqp.implementation.RequestResponseChannel.lambda$new$3(RequestResponseChannel.java:190)
	at reactor.core.publisher.LambdaSubscriber.onComplete(LambdaSubscriber.java:132)
	at reactor.core.publisher.FluxDistinctUntilChanged$DistinctUntilChangedSubscriber.onComplete(FluxDistinctUntilChanged.java:172)
	at reactor.core.publisher.FluxReplay$SizeBoundReplayBuffer.replayNormal(FluxReplay.java:805)
	at reactor.core.publisher.FluxReplay$SizeBoundReplayBuffer.replay(FluxReplay.java:898)
	at reactor.core.publisher.ReplayProcessor.tryEmitComplete(ReplayProcessor.java:465)
	at reactor.core.publisher.SinkManySerialized.tryEmitComplete(SinkManySerialized.java:61)
	at reactor.core.publisher.InternalManySink.emitComplete(InternalManySink.java:68)
	at com.azure.core.amqp.implementation.handler.Handler.close(Handler.java:155)
	at com.azure.core.amqp.implementation.handler.LinkHandler.handleRemoteLinkClosed(LinkHandler.java:121)
	at com.azure.core.amqp.implementation.handler.LinkHandler.onLinkRemoteClose(LinkHandler.java:61)
	at com.azure.core.amqp.implementation.handler.ReceiveLinkHandler.onLinkRemoteClose(ReceiveLinkHandler.java:219)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:176)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291)
	at com.azure.core.amqp.implementation.ReactorExecutor.run(ReactorExecutor.java:91)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**To Reproduce**
Create a Topic Subscription receiver application with Synchronous receiver client. and keep sending messages to Topics using another application at regular intervals of time. 

***Code Snippet***
```
AmqpRetryOptions retry = new AmqpRetryOptions();
Duration delay = Duration.ofMillis(1000);
Duration timeout = Duration.ofMillis(60000);
retry.setMaxRetries(10);
retry.setDelay(delay);
retry.setMode(AmqpRetryMode.FIXED);
retry.setTryTimeout(timeout);
creds = new ClientSecretCredentialBuilder()
.tenantId(TenantID)
.clientId(ClientID).clientSecret(ClientSecret)
.build();
ServiceBusReceiverClient receiverClient= new ServiceBusClientBuilder().credential(host,creds)
                                        .connectionString(connectionString)
                                        .retryOptions(retry)
                                        .receiver().disableAutoComplete()
.topicName(queueName)
.subscriptionName(subscriberName)
.buildClient();

while(flag){
receiverClient.receiveMessages(maxMessages);
}
```

**Expected behavior**
The receiver should always be up and running and if any intermittent errors occur, it should have ensured fault tolerance and recover from the error using the retry configuration

**Screenshots**

**Setup (please complete the following information):**
 - OS: Windows
 - IDE: eclipse
 - Library/Libraries: [azure-messaging-servicebus]» 7.10.1 and its dependencies
 - Java version: 8
 - App Server/Environment: Redhat Openshift
 - Frameworks: Spring boot

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**
We have had similar issue last year and worked with @conniey @anuchandy @liukun-msft . However this issue is observed in one of our customer's environment. 
Besides, we haven't not configured any throttling mechanism in this scenario. 

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [*] Bug Description Added
- [*] Repro Steps Added
- [*] Setup information Added
[xdockpurchaseorderservice-1-m2rsb-xdockpurchaseorderservice.log](https://github.com/Azure/azure-sdk-for-java/files/9474981/xdockpurchaseorderservice-1-m2rsb-xdockpurchaseorderservice.log)

**Comment by joshfree** [comment]
@anuchandy could you please help take a look at @vpeddada's github issue?  Thank you

**Comment by vpeddada** [comment]
Hi @joshfree 

Any update on this issue? Our customers are continuously chasing us for this. Please let me know any progress that has been made so that I can update our customers. 

Just to give you a background and business impact, 
The business impact is higher and at first we had approached the MS support team through the Azure Support partnership channel. However they redirected us to the Github as they mentioned that SDKs issues are directly handled here. 

Let me know if any additional info is required apart from the debug log that I had attached.

Thanks
Varenya

**Comment by anuchandy** [comment]
Hi Varneya,

The only scenario I could en-force Reactor to throw the error you see in the stack trace is -

If the "max-delay" duration provided in `AmqpRetryOptions::setMaxDelay(max-delay)` is not at least 5 seconds bigger than"min-dealy" in `AmqpRetryOptions::setDelay(min-delay)`.

It looks like the messaging use case [adds ](https://github.com/Azure/azure-sdk-for-java/blob/70bcaa2a06ad799b44eca6f093e99ed9189eda30/sdk/core/azure-core-amqp/src/main/java/com/azure/core/amqp/implementation/RetryUtil.java#L104) 4 seconds to the min-delay to account server timeout.

Once I ensure "max-delay > min-delay + 4 seconds," then I don't see this happening.

```java
AmqpRetryOptions retry = new AmqpRetryOptions();

retry.setMode(AmqpRetryMode.FIXED);
retry.setDelay(minDelay);
retry.setMaxDelay(minDelay.plusSeconds(6));
retry.setTryTimeout(timeout);
retry.setMaxRetries(10);
...
```

Could you check if the customer setup somehow ended up in such a retry configuration causing this?

**Comment by anuchandy** [comment]
Also, note that the default max-delay is 1 minute, which means if the user explicitly sets min-delay to a value >= 57 seconds, the same error will occur.

**Comment by vpeddada** [comment]
Hi @anuchandy 

Thank you for this finding. The customer has configured the min delay as 60000ms and we in our code have left the _maxDelay_ to set to the default. We will make necessary code changes to keep the necessary difference just like you mentioned.

We will carry out a test with _mindelay_ lesser than MaxDelay by at least 5 seconds(for e.g 50000ms in our current design) and let you know if it resolves the issue.

Also please point me to any standard guidelines reference for Retry configuration so that we will handle any other corner cases.

Thanks

**Comment by anuchandy** [comment]
I see, right, min-delay of 1 min with default max-delay will trigger the validation error. 

I didn't locate any other such corner cases; yes, please update the configuration. I'm updating the ticket title, so it's discoverable in the future.

**Comment by vpeddada** [comment]
Hi @anuchandy !

Need a clarification. Just wanted to know if this retry mechanism  is part of **azure-messaging-servicebus-7.8.0** as well or is it something implemented later in the latest version i.e **7.10.1**

**Comment by vpeddada** [comment]
[tibcoerpoutboundposervice-1-xjxx8-tibcoerpoutboundposervice.log](https://github.com/Azure/azure-sdk-for-java/files/9730821/tibcoerpoutboundposervice-1-xjxx8-tibcoerpoutboundposervice.log)

Hi @anuchandy @joshfree !

After successfully running for over a month, our customer has encountered error for the ServiceBus Receiver after configuring the retry config as per your recommendations. I have attached the debug logs and refer to **2022-10-04T17:04:01,724** timestamp for the incidence of error. Please let us know your analysis. 

SDK version for this test is azure-messaging-servicebus-7.8.0
AmqpRetryOptions::setDelay(min-delay) is 30000=30sec

Thanks
Varenya

**Comment by anuchandy** [comment]
Hi Varenya, is there a way to confirm the "final" retry-options values being passed to the SDK? For this mutual customer, Is it possible to log the retry options just before giving it to the SDK?
