### ISSUE TITLE
Partial document update error

### ISSUE THREAD

**Issue by 544cl** [Azure/azure-sdk-for-java#30767]
**Describe the bug**
Partial document update gives error if number of columns is greater then 12

***Exception or Stack Trace***

Job aborted due to stage failure: Task 7 in stage 39.0 failed 4 times, most recent failure: Lost task 7.3 in stage 39.0 (TID 502) (vm-1d372245 executor 1): {"ClassName":"BulkOperationFailedException","userAgent":"azsdk-java-cosmos/4.34.0 Linux/4.15.0-1149-azure JRE/1.8.0_342","statusCode":400,"resourceAddress":null,"innerErrorMessage":"All retries exhausted for 'PATCH' bulk operation - statusCode=[400:0] itemId=[1234], partitionKeyValue=[[\"test\"]]","causeInfo":null,"responseHeaders":"{x-ms-substatus=0}"}
	at com.azure.cosmos.spark.BulkWriter.handleNonSuccessfulStatusCode(BulkWriter.scala:396)
	at com.azure.cosmos.spark.BulkWriter.$anonfun$subscriptionDisposable$2(BulkWriter.scala:168)
	at com.azure.cosmos.spark.BulkWriter.$anonfun$subscriptionDisposable$2$adapted(BulkWriter.scala:144)
	at azure_cosmos_spark.reactor.core.scala.publisher.package$.$anonfun$scalaConsumer2JConsumer$2(package.scala:45)
	at azure_cosmos_spark.reactor.core.scala.publisher.package$.$anonfun$scalaConsumer2JConsumer$2$adapted(package.scala:45)
	at scala.Option.foreach(Option.scala:407)
	at azure_cosmos_spark.reactor.core.scala.publisher.package$.$anonfun$scalaConsumer2JConsumer$1(package.scala:45)
	at azure_cosmos_spark.reactor.core.publisher.LambdaSubscriber.onNext(LambdaSubscriber.java:160)
	at azure_cosmos_spark.reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runAsync(FluxPublishOn.java:440)
	at azure_cosmos_spark.reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:527)
	at azure_cosmos_spark.reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
	at azure_cosmos_spark.reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

Driver stacktrace:

**To Reproduce**

columns = ['id', 'systemName', 'col1', 'col2', 'col3', 'col4', 'col5', 'col6', 'col7', 'col8', 'col9', 'col10', 'col11', 'col12']
(14 columns)
partition key = systemName

This will work

testDf.select(*testDf.columns[0:12]).write
    .format('cosmos.oltp')
    .option("spark.synapse.linkedService", "LS_KGP_CosmosDB")
    .option("spark.cosmos.container", 'BranchSystemSerial')
    .option('spark.cosmos.write.strategy', 'ItemPatch')
    .option("spark.cosmos.write.patch.columnConfigs","col(col1).op(Increment)")
    .mode('append')
    .save()

If we include one more column, it gives the above error

testDf.select(*testDf.columns[0:13]).write
    .format('cosmos.oltp')
    .option("spark.synapse.linkedService", "LS_KGP_CosmosDB")
    .option("spark.cosmos.container", 'BranchSystemSerial')
    .option('spark.cosmos.write.strategy', 'ItemPatch')
    .option("spark.cosmos.write.patch.columnConfigs","col(col1).op(Increment)")
    .mode('append')
    .save()

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**
There Should not be an error with more then 12 columns

**Screenshots**
Working for 12 columns
![image](https://user-images.githubusercontent.com/45840260/188068836-16932155-3480-4d74-a93e-4f9d9a129677.png)

Gives error for more then 12 columns
![image](https://user-images.githubusercontent.com/45840260/188069025-aeea2ba6-a9c8-409e-9099-cb38cd2ecbfd.png)

**Setup (please complete the following information):**
 - Library/Libraries: azure-cosmos-spark_3-2_2-12-4.12.2.jar
 - Java version: 1.8.0_282
 - Python version: 3.8
 - Spark version: 3.2
 - Cosmos DB SQL API
 - App Environment: Azure Synapse

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by TheovanKraay** [comment]
Hello @544cl - this is actually a limitation of patch - we only allow 10 patches/fields to be updated per patch operation. So you would have to do something like the below in your case:

patch1=[{'id': '1234', 'systemName': 'hello', 'col1':1, 'col2':'2', 'col3':'patched', 'col4':'4', 'col5':'5', 'col6':'patched', 'col7':'7', 'col8':'patched', 'col9':'9', 'col10':'patched'}]
patch2=[{'id': '1234', 'systemName': 'hello', 'col1':1, 'col11':'patched','col12':'patched'}]

testDf1=spark.createDataFrame(patch1)
testDf2=spark.createDataFrame(patch2)

testDf1.select(*testDf1.columns[0:12]).write
.format('cosmos.oltp')
.option("spark.synapse.linkedService", "LS_KGP_CosmosDB")
.option("spark.cosmos.container", 'BranchSystemSerial')
.option('spark.cosmos.write.strategy', 'ItemPatch')
.option("spark.cosmos.write.patch.columnConfigs","col(col1).op(Increment)")
.mode('append')
.save()

testDf2.select(*testDf2.columns[0:5]).write
.format('cosmos.oltp')
.option("spark.synapse.linkedService", "LS_KGP_CosmosDB")
.option("spark.cosmos.container", 'BranchSystemSerial')
.option('spark.cosmos.write.strategy', 'ItemPatch')
.option("spark.cosmos.write.patch.columnConfigs","col(col1).op(Increment)")
.mode('append')
.save()

This is still technically a bug because we should report the limitation as an error (and we do in scala, but not in Python, so we need to fix that). But otherwise it should work as above.

**Comment by 544cl** [comment]
@TheovanKraay Thanks for the explaination.
