### ISSUE TITLE
[QUESTION] Event Hubs Checkpointstore with custom blob storage policies

### ISSUE THREAD

**Issue by lovababu** [Azure/azure-sdk-for-java#30937]
**Query/Question**
com.azure.storage.blob.BlobContainerClientBuilder with below properties,
  -.addPolicy(new AddHeadersPolicy(new HttpHeaders().add("If-Match", "*")))
  -.endpoint(fullyqualified_storage_endpoint)

We are experiencing issues with above settings, 
 - adding policy to client builder causing Authentication failure exception.
 - adding endpoint causing storage container doesn't exist.

Just wanted to know whats wrong with these properties, shouldn't we allowed to set these properties by developer.?

***Why is this not a Bug or a feature Request?***
Since the library still works without those properties set.

**Setup (please complete the following information if applicable):**
 - OS: Windows
 - IDE: IntelliJ
 - Library/Libraries: azure-messaging-eventhubs: v5.12.1, azure-messaging-checkpointstore-blob: v1.13.0
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by joshfree** [comment]
@conniey could you follow up with @lovababu on their question?

**Comment by conniey** [comment]
Do you have an exception callstack we can look at? We expect the Storage container to exist when passing it to our checkpoint store.  Also, some of the calls we make modify the If-Match header (in the case when trying to claim partitions), what's the user scenario for overriding it with *?

**Comment by lovababu** [comment]
Hi @conniey

1. adding endpoint causing storage container doesn't exist. 
    >> I Couldn't reproduce this issue not sure what went wrong that day.
2. adding policy to client builder causing Authentication failure exception.
    >> Why I am trying to overriding the header?
          - We are seeing too many 412-ConditionNotMet errors in logs, I wanted to suppress these errors hence tried to override this header so that API doesn't evaluate pre-condition check while updating blob.  Correct me if am doing really wrong here. 
    >> Here is the exception logs with If-Match: *

16:15:59 [SpringApplicationShutdownHook] D o.s.c.a.AnnotationConfigApplicationContext - Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@200a26bc, started on Tue Sep 27 16:13:55 IST 2022
16:15:59 [reactor-http-nio-2] D r.n.r.PooledConnectionProvider - [0f34b548, L:/192.168.29.50:59513 - R:devpitmgtterrasa.blob.core.windows.net/20.38.105.196:443] Channel acquired, now: 1 active connections, 0 inactive connections and 0 pending acquire requests.
16:15:59 [reactor-http-nio-2] D r.n.h.c.HttpClientConnect - [0f34b548-5, L:/192.168.29.50:59513 - R:devpitmgtterrasa.blob.core.windows.net/20.38.105.196:443] Handler is being applied: {uri=https://devpitmgtterrasa.blob.core.windows.net/test-avol?restype=container&comp=list&prefix=dev-cmn-terra-ussc-cat-ehns-10.servicebus.windows.net/dev-eventlog-terra-ussc-cat-eh-01/%24default/ownership/&include=metadata, method=GET}
16:15:59 [reactor-http-nio-2] D r.n.r.DefaultPooledConnectionProvider - [0f34b548-5, L:/192.168.29.50:59513 - R:devpitmgtterrasa.blob.core.windows.net/20.38.105.196:443] onStateChange(GET{uri=/test-avol?restype=container&comp=list&prefix=dev-cmn-terra-ussc-cat-ehns-10.servicebus.windows.net/dev-eventlog-terra-ussc-cat-eh-01/%24default/ownership/&include=metadata, connection=PooledConnection{channel=[id: 0x0f34b548, L:/192.168.29.50:59513 - R:devpitmgtterrasa.blob.core.windows.net/20.38.105.196:443]}}, [request_prepared])
16:15:59 [reactor-http-nio-2] D r.netty.ReactorNetty - [0f34b548-5, L:/192.168.29.50:59513 - R:devpitmgtterrasa.blob.core.windows.net/20.38.105.196:443] Added decoder [azureWriteTimeoutHandler] at the end of the user pipeline, full pipeline: [reactor.left.sslHandler, reactor.left.httpCodec, azureWriteTimeoutHandler, reactor.right.reactiveBridge, DefaultChannelPipeline$TailContext#0]
16:15:59 [reactor-http-nio-2] D r.netty.ReactorNetty - [0f34b548-5, L:/192.168.29.50:59513 - R:devpitmgtterrasa.blob.core.windows.net/20.38.105.196:443] Non Removed handler: azureRequestProgressHandler, context: null, pipeline: DefaultChannelPipeline{(reactor.left.sslHandler = io.netty.handler.ssl.SslHandler), (reactor.left.httpCodec = io.netty.handler.codec.http.HttpClientCodec), (azureWriteTimeoutHandler = com.azure.core.http.netty.implementation.WriteTimeoutHandler), (reactor.right.reactiveBridge = reactor.netty.channel.ChannelOperationsHandler)}
16:15:59 [reactor-http-nio-2] D r.n.r.DefaultPooledConnectionProvider - [0f34b548-5, L:/192.168.29.50:59513 - R:devpitmgtterrasa.blob.core.windows.net/20.38.105.196:443] onStateChange(GET{uri=/test-avol?restype=container&comp=list&prefix=dev-cmn-terra-ussc-cat-ehns-10.servicebus.windows.net/dev-eventlog-terra-ussc-cat-eh-01/%24default/ownership/&include=metadata, connection=PooledConnection{channel=[id: 0x0f34b548, L:/192.168.29.50:59513 - R:devpitmgtterrasa.blob.core.windows.net/20.38.105.196:443]}}, [request_sent])
16:15:59 [reactor-http-nio-2] D r.netty.ReactorNetty - [0f34b548-5, L:/192.168.29.50:59513 - R:devpitmgtterrasa.blob.core.windows.net/20.38.105.196:443] Non Removed handler: azureRequestProgressHandler, context: null, pipeline: DefaultChannelPipeline{(reactor.left.sslHandler = io.netty.handler.ssl.SslHandler), (reactor.left.httpCodec = io.netty.handler.codec.http.HttpClientCodec), (azureWriteTimeoutHandler = com.azure.core.http.netty.implementation.WriteTimeoutHandler), (reactor.right.reactiveBridge = reactor.netty.channel.ChannelOperationsHandler)}
16:15:59 [reactor-http-nio-2] D r.netty.ReactorNetty - [0f34b548-5, L:/192.168.29.50:59513 - R:devpitmgtterrasa.blob.core.windows.net/20.38.105.196:443] Removed handler: azureWriteTimeoutHandler, pipeline: DefaultChannelPipeline{(reactor.left.sslHandler = io.netty.handler.ssl.SslHandler), (reactor.left.httpCodec = io.netty.handler.codec.http.HttpClientCodec), (reactor.right.reactiveBridge = reactor.netty.channel.ChannelOperationsHandler)}
16:15:59 [reactor-http-nio-2] D r.netty.ReactorNetty - [0f34b548-5, L:/192.168.29.50:59513 - R:devpitmgtterrasa.blob.core.windows.net/20.38.105.196:443] Added decoder [azureResponseTimeoutHandler] at the end of the user pipeline, full pipeline: [reactor.left.sslHandler, reactor.left.httpCodec, azureResponseTimeoutHandler, reactor.right.reactiveBridge, DefaultChannelPipeline$TailContext#0]
16:15:59 [reactor-http-nio-2] D r.n.h.c.HttpClientOperations - [0f34b548-5, L:/192.168.29.50:59513 - R:devpitmgtterrasa.blob.core.windows.net/20.38.105.196:443] Received response (auto-read:false) : [Content-Type=application/xml, Server=Microsoft-HTTPAPI/2.0, x-ms-request-id=e8deaa28-501e-00c3-105e-d2d325000000, x-ms-error-code=AuthenticationFailed, Date=Tue, 27 Sep 2022 10:45:58 GMT, content-length=866]
16:15:59 [reactor-http-nio-2] D r.n.r.DefaultPooledConnectionProvider - [0f34b548-5, L:/192.168.29.50:59513 - R:devpitmgtterrasa.blob.core.windows.net/20.38.105.196:443] onStateChange(GET{uri=/test-avol?restype=container&comp=list&prefix=dev-cmn-terra-ussc-cat-ehns-10.servicebus.windows.net/dev-eventlog-terra-ussc-cat-eh-01/%24default/ownership/&include=metadata, connection=PooledConnection{channel=[id: 0x0f34b548, L:/192.168.29.50:59513 - R:devpitmgtterrasa.blob.core.windows.net/20.38.105.196:443]}}, [response_received])
16:15:59 [reactor-http-nio-2] D r.netty.ReactorNetty - [0f34b548-5, L:/192.168.29.50:59513 - R:devpitmgtterrasa.blob.core.windows.net/20.38.105.196:443] Removed handler: azureResponseTimeoutHandler, pipeline: DefaultChannelPipeline{(reactor.left.sslHandler = io.netty.handler.ssl.SslHandler), (reactor.left.httpCodec = io.netty.handler.codec.http.HttpClientCodec), (reactor.right.reactiveBridge = reactor.netty.channel.ChannelOperationsHandler)}
16:15:59 [reactor-http-nio-2] D r.netty.ReactorNetty - [0f34b548-5, L:/192.168.29.50:59513 - R:devpitmgtterrasa.blob.core.windows.net/20.38.105.196:443] Added decoder [azureReadTimeoutHandler] at the end of the user pipeline, full pipeline: [reactor.left.sslHandler, reactor.left.httpCodec, azureReadTimeoutHandler, reactor.right.reactiveBridge, DefaultChannelPipeline$TailContext#0]
16:15:59 [reactor-http-nio-2] D r.n.c.FluxReceive - [0f34b548-5, L:/192.168.29.50:59513 - R:devpitmgtterrasa.blob.core.windows.net/20.38.105.196:443] FluxReceive{pending=0, cancelled=false, inboundDone=false, inboundError=null}: subscribing inbound receiver
16:15:59 [reactor-http-nio-2] D r.n.h.c.HttpClientOperations - [0f34b548-5, L:/192.168.29.50:59513 - R:devpitmgtterrasa.blob.core.windows.net/20.38.105.196:443] Received last HTTP packet
16:15:59 [reactor-http-nio-2] D r.n.r.DefaultPooledConnectionProvider - [0f34b548, L:/192.168.29.50:59513 - R:devpitmgtterrasa.blob.core.windows.net/20.38.105.196:443] onStateChange(GET{uri=/test-avol?restype=container&comp=list&prefix=dev-cmn-terra-ussc-cat-ehns-10.servicebus.windows.net/dev-eventlog-terra-ussc-cat-eh-01/%24default/ownership/&include=metadata, connection=PooledConnection{channel=[id: 0x0f34b548, L:/192.168.29.50:59513 - R:devpitmgtterrasa.blob.core.windows.net/20.38.105.196:443]}}, [response_completed])
16:15:59 [reactor-http-nio-2] D r.netty.ReactorNetty - [0f34b548, L:/192.168.29.50:59513 - R:devpitmgtterrasa.blob.core.windows.net/20.38.105.196:443] Removed handler: azureReadTimeoutHandler, pipeline: DefaultChannelPipeline{(reactor.left.sslHandler = io.netty.handler.ssl.SslHandler), (reactor.left.httpCodec = io.netty.handler.codec.http.HttpClientCodec), (reactor.right.reactiveBridge = reactor.netty.channel.ChannelOperationsHandler)}
16:15:59 [reactor-http-nio-2] D r.netty.ReactorNetty - [0f34b548, L:/192.168.29.50:59513 - R:devpitmgtterrasa.blob.core.windows.net/20.38.105.196:443] Non Removed handler: azureWriteTimeoutHandler, context: null, pipeline: DefaultChannelPipeline{(reactor.left.sslHandler = io.netty.handler.ssl.SslHandler), (reactor.left.httpCodec = io.netty.handler.codec.http.HttpClientCodec), (reactor.right.reactiveBridge = reactor.netty.channel.ChannelOperationsHandler)}
16:15:59 [reactor-http-nio-2] D r.netty.ReactorNetty - [0f34b548, L:/192.168.29.50:59513 - R:devpitmgtterrasa.blob.core.windows.net/20.38.105.196:443] Non Removed handler: azureResponseTimeoutHandler, context: null, pipeline: DefaultChannelPipeline{(reactor.left.sslHandler = io.netty.handler.ssl.SslHandler), (reactor.left.httpCodec = io.netty.handler.codec.http.HttpClientCodec), (reactor.right.reactiveBridge = reactor.netty.channel.ChannelOperationsHandler)}
16:15:59 [reactor-http-nio-2] D r.netty.ReactorNetty - [0f34b548, L:/192.168.29.50:59513 - R:devpitmgtterrasa.blob.core.windows.net/20.38.105.196:443] Non Removed handler: azureReadTimeoutHandler, context: null, pipeline: DefaultChannelPipeline{(reactor.left.sslHandler = io.netty.handler.ssl.SslHandler), (reactor.left.httpCodec = io.netty.handler.codec.http.HttpClientCodec), (reactor.right.reactiveBridge = reactor.netty.channel.ChannelOperationsHandler)}
16:15:59 [reactor-http-nio-2] D r.n.r.DefaultPooledConnectionProvider - [0f34b548, L:/192.168.29.50:59513 - R:devpitmgtterrasa.blob.core.windows.net/20.38.105.196:443] onStateChange(GET{uri=/test-avol?restype=container&comp=list&prefix=dev-cmn-terra-ussc-cat-ehns-10.servicebus.windows.net/dev-eventlog-terra-ussc-cat-eh-01/%24default/ownership/&include=metadata, connection=PooledConnection{channel=[id: 0x0f34b548, L:/192.168.29.50:59513 - R:devpitmgtterrasa.blob.core.windows.net/20.38.105.196:443]}}, [disconnecting])
16:15:59 [reactor-http-nio-2] D r.n.r.DefaultPooledConnectionProvider - [0f34b548, L:/192.168.29.50:59513 - R:devpitmgtterrasa.blob.core.windows.net/20.38.105.196:443] Releasing channel
16:15:59 [reactor-http-nio-2] D r.n.r.PooledConnectionProvider - [0f34b548, L:/192.168.29.50:59513 - R:devpitmgtterrasa.blob.core.windows.net/20.38.105.196:443] Channel cleaned, now: 0 active connections, 1 inactive connections and 0 pending acquire requests.
16:15:59 [SpringApplicationShutdownHook] I c.a.m.e.EventProcessorClient - {"az.sdk.message":"Event processor has already stopped","eventProcessorId":"df1b27bb-256f-412b-8a7d-b9179fc47f77"}
Exception in thread "Thread-1" com.azure.storage.blob.models.BlobStorageException: If you are using a StorageSharedKeyCredential, and the server returned an error message that says 'Signature did not match', you can compare the string to sign with the one generated by the SDK. To log the string to sign, pass in the context key value pair 'Azure-Storage-Log-String-To-Sign': true to the appropriate method call.
If you are using a SAS token, and the server returned an error message that says 'Signature did not match', you can compare the string to sign with the one generated by the SDK. To log the string to sign, pass in the context key value pair 'Azure-Storage-Log-String-To-Sign': true to the appropriate generateSas method call.
Please remember to disable 'Azure-Storage-Log-String-To-Sign' before going to production as this string can potentially contain PII.
Status code 403, "﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:e8deaa28-501e-00c3-105e-d2d325000000
Time:2022-09-27T10:45:59.5372949Z</Message><AuthenticationErrorDetail>The MAC signature found in the HTTP request 'WfIhjvyq3HXB9fV5egVA/gSfElDZsvpaOxsZc5upXEs=' is not the same as any computed signature. Server used following string to sign: 'GET





Tue, 27 Sep 2022 10:45:59 GMT

*



x-ms-client-request-id:2ecb07ed-cd00-493d-873a-aecd8ba23835
x-ms-version:2021-08-06
/devpitmgtterrasa/test-avol
comp:list
include:metadata
prefix:dev-cmn-terra-ussc-cat-ehns-10.servicebus.windows.net/dev-eventlog-terra-ussc-cat-eh-01/$default/ownership/
restype:container'.</AuthenticationErrorDetail></Error>"
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:710)
	at com.azure.core.implementation.http.rest.ResponseExceptionConstructorCache.invoke(ResponseExceptionConstructorCache.java:56)
	at com.azure.core.implementation.http.rest.RestProxyBase.instantiateUnexpectedException(RestProxyBase.java:377)
	at com.azure.core.implementation.http.rest.AsyncRestProxy.lambda$ensureExpectedStatus$1(AsyncRestProxy.java:117)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:113)
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2398)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:171)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:2194)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:2068)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:96)
	at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:55)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129)
	at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onNext(FluxHide.java:137)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129)
	at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onNext(FluxHide.java:137)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151)
	at reactor.core.publisher.FluxDelaySubscription$DelaySubscriptionMainSubscriber.onNext(FluxDelaySubscription.java:189)
	at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:99)
	at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:99)
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.onNext(FluxTimeout.java:180)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151)
	at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:99)
	at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.onNext(FluxRetryWhen.java:174)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
	at reactor.core.publisher.Operators$MonoInnerProducerBase.complete(Operators.java:2664)
	at reactor.core.publisher.MonoSingle$SingleSubscriber.onComplete(MonoSingle.java:180)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onComplete(MonoFlatMapMany.java:260)
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onComplete(FluxDoFinally.java:128)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onComplete(FluxMapFuseable.java:152)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1817)
	at reactor.core.publisher.MonoCollect$CollectSubscriber.onComplete(MonoCollect.java:160)
	at reactor.core.publisher.FluxHandle$HandleSubscriber.onComplete(FluxHandle.java:220)
	at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onComplete(FluxMap.java:275)
	at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:400)
	at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:419)
	at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:473)
	at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:703)
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:93)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1373)
	at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1247)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1287)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:139)
		at reactor.core.publisher.Flux.blockLast(Flux.java:2669)
		at com.azure.messaging.eventhubs.EventProcessorClient.stopProcessing(EventProcessorClient.java:202)
		at com.azure.messaging.eventhubs.EventProcessorClient.stop(EventProcessorClient.java:180)
		at java.base/java.util.Optional.ifPresent(Optional.java:183)
		at com.cat.terra.az.springboot.eventhub.consumer.EventConsumer.lambda$new$0(EventConsumer.java:25)
		... 1 more

**Comment by conniey** [comment]
@lovababu Hey.  The 412 errors are a core part of our `claimOwnership` logic.  We want to only claim ownership if no one else has already... And that is determined by matching eTags. Please see: https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/eventhubs/azure-messaging-eventhubs/TROUBLESHOOTING.md#412-precondition-failures-when-using-an-event-processor
