### ISSUE TITLE
[BUG] Update NSG Rule - Unable to add ASG

### ISSUE THREAD

**Issue by NatanelY** [Azure/azure-sdk-for-java#31070]
**Describe the bug**
We are using Azure SDK for Java, version: 1.41.4.
We are trying Update rule that contain Service Tag as a source, getting exception code 400 with the following error message: 

***Exception or Stack Trace***
“Required security rule parameters are missing for security rule with Id: /subscriptions/”subscription_id”/resourceGroups/TEST/providers/Microsoft.Network/networkSecurityGroups/nsg/securityRules/ruletest. Security rule must specify SourceAddressPrefixes, SourceAddressPrefix, or SourceApplicationSecurityGroups.

***Code Snippet***
networkSecurityGroup
.update()
.updateRule(ruletest)
.withSourceApplicationSecurityGroup("/subscriptions/”subscription_id”/resourceGroups/TEST/providers/Microsoft.Network/applicationSecurityGroups/ASG2")
.parent()
.apply();

**Expected behavior**
The service tag should be replace with Application Security Group(ASG)

**Setup (please complete the following information):**

- OS: windows\linux
- IDE:  IntelliJ
- Library/Libraries: com.microsoft.azure:azure-mgmt-network:1.41.4,  com.microsoft.azure:azure:1.41.4, com.microsoft.azure:azure-client-authentication:1.7.14 , com.microsoft.azure:azure-mgmt-resources:1.41.4 (and more libraries, but these are the relevant)
- Java version:  8
- App Server/Environment: Apache Maven

**Comment by joshfree** [comment]
@weidongxu-microsoft could you please help route @NatanelY's issue?

**Comment by weidongxu-microsoft** [comment]
@NatanelY 

The 1.x SDK is deprecated, please migrate to https://aka.ms/azsdk/java/mgmt, latest is 2.19.0

+ @XiaofeiCao in case there is issue with NSG.

**Comment by NatanelY** [comment]
@weidongxu-microsoft 
can you please confirm that this issue related to adding ASG through the SDK is solved when upgrading to 2.19.0 version ?

**Comment by XiaofeiCao** [comment]
@NatanelY 
Confirmed using following code snippet(SDK 2.19.0):
```java

        NetworkSecurityGroup nsg = networkManager.networkSecurityGroups().define(nsgName)
            .withRegion(region)
            .withNewResourceGroup(rgName)
            .defineRule("rule1")
                .allowOutbound()
                .fromAddress("Storage") // Service Tag
                .fromAnyPort()
                .toAnyAddress()
                .toPort(80)
                .withProtocol(SecurityRuleProtocol.TCP)
                .attach()
            .create();

        ApplicationSecurityGroup asg = networkManager.applicationSecurityGroups().define(asgName)
            .withRegion(region)
            .withNewResourceGroup(rgName)
            .create();

        nsg.update()
            .updateRule("rule1")
            .withSourceApplicationSecurityGroup(asg.id())
            .parent()
            .apply();

        Assertions.assertTrue(nsg.securityRules().get("rule1").sourceApplicationSecurityGroupIds().contains(asg.id()));
    
```

Note:
Although change from Service Tag to ASG works fine, the other way around may fail. It is to be fixed in another [PR](https://github.com/Azure/azure-sdk-for-java/pull/30804)(it also supports convenient method for Service Tag, but may not merge for a while).

**Comment by NatanelY** [comment]
@XiaofeiCao 
Hi,
We are having some authentication issues in order to login:

AzureProfile profile = new AzureProfile(tenant, subscription, com.azure.core.management.AzureEnvironment.AZURE);
ClientSecretCredential cred = new ClientSecretCredentialBuilder()
                        .tenantId(tenant)
                        .clientId(clientId)
                        .clientSecret(secretKey)
                        .build();
AzureResourceManager azureResourceManager = AzureResourceManager
                        .configure()
                        .withLogLevel(HttpLogDetailLevel.BODY_AND_HEADERS)
                        .authenticate(cred, profile)
                        .withSubscription(subscription);
NetworkSecurityGroup nsg = azureResourceManager.networkSecurityGroups().getById("/subscriptions/" + subscription + "/resourceGroups/CM/providers/Microsoft.Network/networkSecurityGroups/CMvm-nsg");

We are getting the following error:
[Correlation ID: dcba2d26-2ada-49eb-bcd2-2821f77d87e7] Execution of class com.microsoft.aad.msal4j.AcquireTokenSilentSupplier failed.
com.microsoft.aad.msal4j.MsalClientException: Token not found in the cache
              at com.microsoft.aad.msal4j.AcquireTokenSilentSupplier.execute(AcquireTokenSilentSupplier.java:75) ~[msal4j-1.13.2.jar:1.13.2]
              at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:69) ~[msal4j-1.13.2.jar:1.13.2]
              at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:18) ~[msal4j-1.13.2.jar:1.13.2]
              at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) ~[?:1.8.0_162]
              at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582) ~[?:1.8.0_162]
              at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_162]
              at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_162]
              at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_162]
              at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_162]
SkipCache set to false. Attempting cache lookup
Cache lookup failed: Token not found in the cache
Sending token request to: https://login.microsoftonline.com/66ce1041-d7c0-48f9-b6db-8af0e284603e/
[Correlation ID: 136aa7fe-c397-424f-99f2-747f873a7865] Execution of class com.microsoft.aad.msal4j.AcquireTokenByClientCredentialSupplier failed.
java.lang.ClassCastException: java.util.Collections$SingletonList cannot be cast to java.lang.String
              at com.nimbusds.oauth2.sdk.util.URLUtils.serializeParameters(URLUtils.java:103) ~[oauth2-oidc-sdk-5.64.4.jar:5.64.4]
              at com.microsoft.aad.msal4j.TokenRequestExecutor.createOauthHttpRequest(TokenRequestExecutor.java:54) ~[msal4j-1.13.2.jar:1.13.2]
              at com.microsoft.aad.msal4j.TokenRequestExecutor.executeTokenRequest(TokenRequestExecutor.java:32) ~[msal4j-1.13.2.jar:1.13.2]
              at com.microsoft.aad.msal4j.AbstractClientApplicationBase.acquireTokenCommon(AbstractClientApplicationBase.java:128) ~[msal4j-1.13.2.jar:1.13.2]
              at com.microsoft.aad.msal4j.AcquireTokenByAuthorizationGrantSupplier.execute(AcquireTokenByAuthorizationGrantSupplier.java:63) ~[msal4j-1.13.2.jar:1.13.2]
              at com.microsoft.aad.msal4j.AcquireTokenByClientCredentialSupplier.acquireTokenByClientCredential(AcquireTokenByClientCredentialSupplier.java:86) ~[msal4j-1.13.2.jar:1.13.2]
              at com.microsoft.aad.msal4j.AcquireTokenByClientCredentialSupplier.execute(AcquireTokenByClientCredentialSupplier.java:49) ~[msal4j-1.13.2.jar:1.13.2]
              at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:69) ~[msal4j-1.13.2.jar:1.13.2]
              at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:18) ~[msal4j-1.13.2.jar:1.13.2]
              at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) ~[?:1.8.0_162]
              at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582) ~[?:1.8.0_162]
              at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_162]
              at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_162]
              at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_162]
              at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_162]
Azure Identity => ERROR in getToken() call for scopes [https://management.core.windows.net//.default]: java.util.Collections$SingletonList cannot be cast to java.lang.String
Failed to acquire a new access token.
{"az.sdk.message":"Error resume.","exception":"java.util.Collections$SingletonList cannot be cast to java.lang.String","tryCount":0}
java.lang.ClassCastException: java.util.Collections$SingletonList cannot be cast to java.lang.String
              at com.nimbusds.oauth2.sdk.util.URLUtils.serializeParameters(URLUtils.java:103) ~[oauth2-oidc-sdk-5.64.4.jar:5.64.4]
              at com.microsoft.aad.msal4j.TokenRequestExecutor.createOauthHttpRequest(TokenRequestExecutor.java:54) ~[msal4j-1.13.2.jar:1.13.2]
              at com.microsoft.aad.msal4j.TokenRequestExecutor.executeTokenRequest(TokenRequestExecutor.java:32) ~[msal4j-1.13.2.jar:1.13.2]
              at com.microsoft.aad.msal4j.AbstractClientApplicationBase.acquireTokenCommon(AbstractClientApplicationBase.java:128) ~[msal4j-1.13.2.jar:1.13.2]
              at com.microsoft.aad.msal4j.AcquireTokenByAuthorizationGrantSupplier.execute(AcquireTokenByAuthorizationGrantSupplier.java:63) ~[msal4j-1.13.2.jar:1.13.2]
              at com.microsoft.aad.msal4j.AcquireTokenByClientCredentialSupplier.acquireTokenByClientCredential(AcquireTokenByClientCredentialSupplier.java:86) ~[msal4j-1.13.2.jar:1.13.2]
              at com.microsoft.aad.msal4j.AcquireTokenByClientCredentialSupplier.execute(AcquireTokenByClientCredentialSupplier.java:49) ~[msal4j-1.13.2.jar:1.13.2]
              at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:69) ~[msal4j-1.13.2.jar:1.13.2]
              at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:18) ~[msal4j-1.13.2.jar:1.13.2]
              at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) ~[?:1.8.0_162]
              at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582) ~[?:1.8.0_162]
              at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_162]
              at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_162]
              at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_162]
              at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_162]

**Comment by XiaofeiCao** [comment]
Hi @NatanelY 

Thanks for the log. I noticed this part of the error in your log:
> Azure Identity => ERROR in getToken() call for scopes [https://management.core.windows.net//.default]: java.util.Collections$SingletonList cannot be cast to java.lang.String
Failed to acquire a new access token.
{"az.sdk.message":"Error resume.","exception":"java.util.Collections$SingletonList cannot be cast to java.lang.String","tryCount":0}
java.lang.ClassCastException: java.util.Collections$SingletonList cannot be cast to java.lang.String
at com.nimbusds.oauth2.sdk.util.URLUtils.serializeParameters(URLUtils.java:103) ~[oauth2-oidc-sdk-5.64.4.jar:5.64.4]

The problem is that the package  `oauth2-oidc-sdk-5.64.4.jar:5.64.4` is too old and the method signature of `com.nimbusds.oauth2.sdk.util.URLUtils.serializeParameters()` has changed in the newer version(params from `Map<String, String>` to `Map<String, List<String>>`), thus the cast exception.

You should use the latest [`azure-identity`](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/resourcemanager#include-the-package), the correct oauth2-oidc-sdk version should be included transitively:
```pom.xml
<dependency>
  <groupId>com.azure</groupId>
  <artifactId>azure-identity</artifactId>
  <version>1.6.1</version>
</dependency>
```

Or explicitly declare the oauth2-oidc-sdk version(if above declaration doesn't work): 
```pom.xml
<!-- https://mvnrepository.com/artifact/com.nimbusds/oauth2-oidc-sdk -->
<dependency>
    <groupId>com.nimbusds</groupId>
    <artifactId>oauth2-oidc-sdk</artifactId>
    <version>9.35</version>
</dependency>
```

Please make sure runtime use the newer version of `oauth2-oidc-sdk` and try again, thanks.
