### ISSUE TITLE
[Question] Azure AD authentication with spring security thymeleaf authentication

### ISSUE THREAD

**Issue by nisamux** [Azure/azure-sdk-for-java#31075]
**Describe the bug**
The issue is that when the authentication is successful on azure and we redirect the authenticated user to our application, the local spring security which is managing our local authentication refuses outside authentication to mean that you need to be authenticated again by our local implemented login.

***Exception or Stack Trace***
```
[DEBUG] 2022-09-21 12:25:36.475 [http-nio-8085-exec-9] ExceptionTranslationFilter - Access is denied (user is anonymous); redirecting to authentication entry point
org.springframework.security.access.AccessDeniedException: Access is denied
	at org.springframework.security.access.vote.AffirmativeBased.decide(AffirmativeBased.java:84) ~[spring-security-core-5.3.5.RELEASE.jar:5.3.5.RELEASE]
	at org.springframework.security.access.intercept.AbstractSecurityInterceptor.beforeInvocation(AbstractSecurityInterceptor.java:233) ~[spring-security-core-5.3.5.RELEASE.jar:5.3.5.RELEASE]
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:123) ~[spring-security-web-5.3.5.RELEASE.jar:5.3.5.RELEASE]
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:90) ~[spring-security-web-5.3.5.RELEASE.jar:5.3.5.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.3.5.RELEASE.jar:5.3.5.RELEASE]
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:118) [spring-security-web-5.3.5.RELEASE.jar:5.3.5.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.3.5.RELEASE.jar:5.3.5.RELEASE]
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137) [spring-security-web-5.3.5.RELEASE.jar:5.3.5.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.3.5.RELEASE.jar:5.3.5.RELEASE]
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111) [spring-security-web-5.3.5.RELEASE.jar:5.3.5.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.3.5.RELEASE.jar:5.3.5.RELEASE]
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:158) [spring-security-web-5.3.5.RELEASE.jar:5.3.5.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.3.5.RELEASE.jar:5.3.5.RELEASE]
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63) [spring-security-web-5.3.5.RELEASE.jar:5.3.5.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.3.5.RELEASE.jar:5.3.5.RELEASE]
	at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:155) [spring-security-web-5.3.5.RELEASE.jar:5.3.5.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.2.10.RELEASE.jar:5.2.10.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.3.5.RELEASE.jar:5.3.5.RELEASE]
	at org.springframework.security.web.session.ConcurrentSessionFilter.doFilter(ConcurrentSessionFilter.java:152) [spring-security-web-5.3.5.RELEASE.jar:5.3.5.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.3.5.RELEASE.jar:5.3.5.RELEASE]
```
**To Reproduce**
[We have tried using different dependencies, downgrading java version but it didn't work. We have made an attempt to use Azure authentication without any  local authentication and that has worked. So the big issue is how to use it[Azure authentication together with other local spring security authentication]

***Code Snippet***
```java
Controller:

    @GetMapping(value = "/oAuth2")
    @ResponseBody
    public String index(OAuth2AuthenticationToken token) {
        System.out.println("Azure Token"+token);
        if (token != null) {
            final OAuth2User userr = token.getPrincipal();
            System.out.println("Azure User"+userr);
        }
        return "Test Azure Login";
    }

Security Config:

  private final AADB2COidcLoginConfigurer configurer;

    public SecurityConfig(AADB2COidcLoginConfigurer configurer) {
        this.configurer = configurer;
    }

	  // Disable CSFR protection on the following urls:
            private AntPathRequestMatcher[] requestMatchers = {
                    new AntPathRequestMatcher("/login"),
                    new AntPathRequestMatcher("/oAuth2"),
                    new AntPathRequestMatcher("/api/**"),
            };

	 http.authorizeRequests()
                .antMatchers("/login", "/forgot-password/**", "/reset-password/**","/oAuth2").permitAll()
                .anyRequest().authenticated()
                .and()
                .apply(configurer)
        ;
```

**Expected behaviour**
Our application need to allow double authentication: i.e.: if a user has azure AD account, he can use it to login or login using the local implemented  spring security login

**Setup (please complete the following information):**
 - OS: [Windows 11]
 - IDE: [IntelliJ]
 - Library/Libraries: [azure-spring-boot-starter-active-directory-b2c]
 - Java version: [11] 
 - App Server/Environment: [Tomcat]
 - Frameworks: [Spring Boot] 

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [Yes] Bug Description Added
- [Yes] Repro Steps Added
- [Yes] Setup information Added

**Comment by chenrujun** [comment]
Hi, @nisamux

Thanks for reaching out. I will look into it ASAP and get back to you

**Comment by chenrujun** [comment]
Hi, @nisamux 
Here is the change that I made to support `Azure AD B2C OAuth2 login` and `form login` at the same time: https://github.com/chenrujun/azure-spring-boot-samples/commit/722ca36e9252ab58ee3abfd10f08366289b0045a

If [this commit](https://github.com/chenrujun/azure-spring-boot-samples/commit/722ca36e9252ab58ee3abfd10f08366289b0045a) cannot satisfy your requirement. Please create PR target to [this branch](https://github.com/chenrujun/azure-spring-boot-samples/tree/azure-sdk-for-java-issues-31075-AzureAD-with-spring-security-thymeleaf) to explain your requirement.

**Comment by chenrujun** [comment]
Closing this issue, because there is no response for more than 14 days.
