### ISSUE TITLE
[QUERY] - Cosmos Spark OLTP 3 Connecter With SpringBoot Issue

### ISSUE THREAD

**Issue by ImAbhishekTomar** [Azure/azure-sdk-for-java#31128]
Hi,

Tying spark connector with spring-boot but it's not working and giving me an error. can anyone please help or share any sample repo. Thanks in advance.

**ERROR**

> ```
> Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/spark/sql/SparkSession
> 	at com.sparkdemo.demo.DemoApplication.CosmosDbOltpSparConnect3(DemoApplication.java:39)
> 	at com.sparkdemo.demo.DemoApplication.main(DemoApplication.java:16)
> Caused by: java.lang.ClassNotFoundException: org.apache.spark.sql.SparkSession
> 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
> 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
> 	... 2 more
> ```

**My Program**

```
package com.sparkdemo.demo;
import org.apache.spark.SparkConf;
import org.apache.spark.SparkContext;
import org.apache.spark.sql.SparkSession;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
//https://learn.microsoft.com/en-us/azure/cosmos-db/sql/create-sql-api-spark?tabs=scala
@SpringBootApplication
public class DemoApplication {
	public static void main(String[] args) {
		SpringApplication.run(DemoApplication.class, args);
		CosmosDbOltpSparkConnect3();
	}
	public static void CosmosDbOltpSparkConnect3(){

		var cosmosEndpoint = "ENDPOINT";
		var cosmosMasterKey = "KEY";
		var cosmosDatabaseName = "DATABASE";
		var cosmosContainerName = "COLLECTION";

		SparkConf conf=new SparkConf()
				.setAppName("spark-cosmos-demo")
				.setMaster("local[*]")
				.set("spark.cosmos.accountEndpoint",cosmosEndpoint)
				.set("spark.cosmos.accountKey",cosmosMasterKey)
				.set("spark.cosmos.database",cosmosDatabaseName)
				.set("spark.cosmos.container",cosmosContainerName);
		SparkContext context=new SparkContext(conf);
		context.conf().set("spark.sql.catalog.cosmosCatalog","com.azure.cosmos.spark.CosmosCatalog");
		context.conf().set("spark.sql.catalog.cosmosCatalog.spark.cosmos.accountEndpoint",cosmosEndpoint);
		context.conf().set("spark.sql.catalog.cosmosCatalog.spark.cosmos.accountKey","cosmosMasterKey");
		try (SparkSession session = new SparkSession(context)) {
			var collectionRow = session.read().format("cosmos.oltp")
					.option("spark.cosmos.read.inferSchema.enabled", "true")
					.option("spark.cosmos.accountEndpoint",cosmosEndpoint)
					.option("spark.cosmos.accountKey",cosmosMasterKey)
					.option("spark.cosmos.database",cosmosDatabaseName)
					.option("spark.cosmos.container",cosmosContainerName)
					.load();
			collectionRow.printSchema();
			collectionRow.createOrReplaceGlobalTempView("FlattenTable");
			collectionRow.limit(5).show();
			session.cloneSession();
		}catch (Exception e){
			System.out.println("ERROR: " + e.getMessage());
		}finally {
			System.out.println("Closed!");
		}
	}
}
```

**POM**

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.7.4</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
	<groupId>com.sparkdemo</groupId>
	<artifactId>demo</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>demo</name>
	<description>Demo project for Spring Boot</description>
	<properties>
		<java.version>17</java.version>
		<maven.compiler.source>11</maven.compiler.source>
		<maven.compiler.target>11</maven.compiler.target>
	</properties>
	<dependencies>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
			<exclusions>
				<exclusion>
					<groupId>org.slf4j</groupId>
					<artifactId>slf4j-log4j12</artifactId>
				</exclusion>
				<exclusion>
					<groupId>log4j</groupId>
					<artifactId>log4j</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
			<exclusions>
				<exclusion>
					<groupId>org.slf4j</groupId>
					<artifactId>slf4j-log4j12</artifactId>
				</exclusion>
				<exclusion>
					<groupId>log4j</groupId>
					<artifactId>log4j</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

		<dependency>
			<groupId>com.azure.cosmos.spark</groupId>
			<artifactId>azure-cosmos-spark_3-2_2-12</artifactId>
			<version>4.13.1</version>
		</dependency>
		<dependency><groupId>org.apache.spark</groupId>
			<artifactId>spark-core_2.13</artifactId>
			<version>3.3.0</version>
		</dependency>
		<dependency>
			<groupId>org.apache.spark</groupId>
			<artifactId>spark-sql_2.13</artifactId>
			<version>3.3.0</version>
			<scope>provided</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

</project>

```

**Comment by FabianMeiswinkel** [comment]
Hi - what are you trying to do. Is this for a demo only? Usually hosting Spark within a Spring Boot app wouldn't allow using many of the benefits of Spark (spreading work across nodes and distributing it)?
If it is mostly for demo or local testing you could do this in a similar way like we do in unit tests (look at https://github.com/Azure/azure-sdk-for-java/blob/a094170a51aacfe35de8d0841f3f6eac8182197f/sdk/cosmos/azure-cosmos-spark_3-2_2-12/pom.xml#L96-L107)

Obvious incompatibility above is that you use Spark 3.3 with Scala 2.13 - while our connector only supports Spark 3.1 (azure-cosmos-spark_3-1_2-12) or Spark 3.2 (azure-cosmos-spark_3-2_2-12)
