### ISSUE TITLE
[BUG] Null pointer exception for Azure Resource Manager Monitor Diagnostic Settings 

### ISSUE THREAD

**Issue by ihsanhaikalz** [Azure/azure-sdk-for-java#31151]
I tried to run either the following code similar to https://learn.microsoft.com/en-us/cli/azure/monitor/diagnostic-settings/subscription?view=azure-cli-latest#az-monitor-diagnostic-settings-subscription-list:

```
monitorService.diagnosticSettings().get("subscriptions/"+subscriptionId, diagnosticSettingName);

        List<DiagnosticSetting> diagnosticSettings= monitorService.diagnosticSettings().listByResource("subscriptions/"+subscriptionId).;

```       
However, I got NPE with the error stack as follows:
```
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because the return value of "com.azure.resourcemanager.monitor.fluent.models.DiagnosticSettingsResourceInner.metrics()" is null
	at com.azure.resourcemanager.monitor.implementation.DiagnosticSettingImpl.setInner(DiagnosticSettingImpl.java:250)
	at com.azure.resourcemanager.monitor.implementation.DiagnosticSettingImpl.setInner(DiagnosticSettingImpl.java:24)
	at com.azure.resourcemanager.resources.fluentcore.model.implementation.IndexableRefreshableWrapperImpl.<init>(IndexableRefreshableWrapperImpl.java:29)
	at com.azure.resourcemanager.resources.fluentcore.model.implementation.CreatableUpdatableImpl.<init>(CreatableUpdatableImpl.java:66)
	at com.azure.resourcemanager.resources.fluentcore.model.implementation.CreatableUpdatableImpl.<init>(CreatableUpdatableImpl.java:55)
	at com.azure.resourcemanager.monitor.implementation.DiagnosticSettingImpl.<init>(DiagnosticSettingImpl.java:39)
	at com.azure.resourcemanager.monitor.implementation.DiagnosticSettingsImpl.wrapModel(DiagnosticSettingsImpl.java:60)
	at com.azure.resourcemanager.monitor.implementation.DiagnosticSettingsImpl.get(DiagnosticSettingsImpl.java:146)
```

I confirmed on my Azure powershell that there was no error doing it.

**Comment by joshfree** [comment]
Thanks for reporting this issue, @ihsanhaikalz.  @weidongxu-microsoft could you please follow up?

**Comment by weidongxu-microsoft** [comment]
@XiaofeiCao Could you help?

@ihsanhaikalz Would you let us know the version of the SDK?

**Comment by XiaofeiCao** [comment]
@ihsanhaikalz 
Thanks for your report. The bug exists in our latest sdk. The fix will be shipped along with our next release.
