### ISSUE TITLE
[BUG] DataLakeFileClient.flush() gets HTTP 412 error

### ISSUE THREAD

**Issue by turcsanyip** [Azure/azure-sdk-for-java#31248]
**Describe the bug**
We use `DataLakeFileClient.append()` + `DataLakeFileClient.flush()` to upload files to ADLS and it properly works using `azure-storage-file-datalake:12.7.4`.

From version `12.8.0` on, `DataLakeFileClient.flush()` receives HTTP 412 error with message _"The condition specified using HTTP conditional header(s) is not met."_.

***Exception or Stack Trace***
```
18:13:17.469 [main] DEBUG c.a.c.i.http.HttpClientProviders - Using com.azure.core.http.netty.NettyAsyncHttpClientProvider as the default HttpClientProvider. [logback] 
Exception in thread "main" com.azure.storage.file.datalake.models.DataLakeStorageException: Status code 412, "{"error":{"code":"ConditionNotMet","message":"The condition specified using HTTP conditional header(s) is not met.\nRequestId:d226fae0-201f-0044-2979-d684e9000000\nTime:2022-10-02T16:13:20.0639147Z"}}"
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at com.azure.core.implementation.http.rest.ResponseExceptionConstructorCache.invoke(ResponseExceptionConstructorCache.java:56)
	at com.azure.core.implementation.http.rest.RestProxyBase.instantiateUnexpectedException(RestProxyBase.java:378)
	at com.azure.core.implementation.http.rest.AsyncRestProxy.lambda$ensureExpectedStatus$1(AsyncRestProxy.java:116)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:106)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:113)
	at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:126)
	at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:224)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:113)
	at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:191)
	at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
	at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:129)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:260)
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144)
	at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:400)
	at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:419)
	at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:473)
	at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:703)
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:93)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1373)
	at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1247)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1287)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.kqueue.AbstractKQueueStreamChannel$KQueueStreamUnsafe.readReady(AbstractKQueueStreamChannel.java:544)
	at io.netty.channel.kqueue.AbstractKQueueChannel$AbstractKQueueUnsafe.readReady(AbstractKQueueChannel.java:383)
	at io.netty.channel.kqueue.KQueueEventLoop.processReady(KQueueEventLoop.java:211)
	at io.netty.channel.kqueue.KQueueEventLoop.run(KQueueEventLoop.java:289)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
		at reactor.core.publisher.Mono.block(Mono.java:1707)
		at com.azure.storage.common.implementation.StorageImplUtils.blockWithOptionalTimeout(StorageImplUtils.java:191)
		at com.azure.storage.file.datalake.DataLakeFileClient.flushWithResponse(DataLakeFileClient.java:590)
		at com.azure.storage.file.datalake.DataLakeFileClient.flush(DataLakeFileClient.java:542)
		at com.azure.storage.file.datalake.DataLakeFileClient.flush(DataLakeFileClient.java:510)
```

***Code Snippet***
```
        DataLakeFileSystemClient fileSystemClient = ...

        byte[] data = "hello".getBytes();
        InputStream is = new ByteArrayInputStream(data);

        DataLakeFileClient fileClient = fileSystemClient.createFile(UUID.randomUUID().toString());
        fileClient.append(is, 0, data.length);
        fileClient.flush(data.length);
```
For sake of simplicity I added a single `append()` here but we use `append()` in a loop for chunked uploading.

**Expected behavior**
`DataLakeFileClient.flush()` should upload/flush the file content after `append()` calls.

**Setup (please complete the following information):**
 - Library/Libraries: `azure-storage-file-datalake:12.8.0` +

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by turcsanyip** [comment]
I looked into the code and the logic was changed here: https://github.com/Azure/azure-sdk-for-java/commit/fad18c5c154dcfbc6200f86927358244898176b4
The `overwrite` flag had been used in the wrong way before that commit but now the issue seems to me that appending to a newly created 0 byte file is detected as "overwriting" and gets rejected in `overwrite=false` mode (which is the default for `flush()`).

**Comment by joshfree** [comment]
Thank you for reporting this issue @turcsanyip; @jaschrep-msft could you please follow up?

**Comment by ibrahimrabab** [comment]
Hi @turcsanyip 

Thank you for opening this issue. If you pass in true for overwrite like so: 
`fileClient.flush(data.length, true);`

The error will go away. If you don't specify the overwrite value, the default is false. It's best to pass the overwrite value even if the length of the file is 0.

Please let me know if this fixes your problem, or if you have any additional questions.

**Comment by archana-jambhulkar-kr** [comment]
I am using azure-storage-file-datalake:12.13.1, and passed default value as false. but still getting error which was mentioned above.
fileClient.flush(data.length, false);
Please let me know if this is been fixed.

**Comment by ibrahimrabab** [comment]
Hi @archana-jambhulkar-kr 
Can you try passing in true instead of false? Ex:
fileClient.flush(data.length, true);

Let me know if this fixes the problem.

**Comment by archana-jambhulkar-kr** [comment]
Just the background I have azure-storage-file-datalake:12.6.0 and upgrading to 12.13.1. And the below code breaks
fileClient.flush(data.length);
So I tried to pass true and it works, But in order to support above flush method isnt the overwrite needs to be set to false? as that's the default value for flush.

**Comment by ibrahimrabab** [comment]
@archana-jambhulkar-kr 
So when you use `fileClient.flush(data.length)`, the value for flush is defaulted to **false**. If you want to overwrite, you need to use the overload method and pass in **true**, 
`fileClient.flush(data.length, true)`
and this will ensure you won't run into the 412 error code. So, in your case you need to use the overload method and pass **true**. 

Hope this makes sense, let me know if you have any other clarifying questions!

**Comment by turcsanyip** [comment]
@ibrahimrabab Sorry for not replying earlier! So the suggested `overwrite=true` works for us and we are fine.

However, I would consider it as a client side workaround and agree with @archana-jambhulkar-kr that from API perspective `overwrite=false` should also work. As far as I understand, the default `flush()` method (using `overwrite=false`) does not work at all. At least I could not find a use case when it does not throw 412.

Is there a valid scenario that works with the default `flush()` / `overwrite=false` currently?

**Comment by archana-jambhulkar-kr** [comment]
@ibrahimrabab Do you plan to fix the bug where overwrite flag is inverted ? If yes when do we expect the release version of the same? Thanks.

**Comment by ibrahimrabab** [comment]
@turcsanyip @archana-jambhulkar-kr 
Thank you both for clarifying this issue better! We've decided to go ahead and deprecate the existing `DataLakeFileClient.flush(long position)` method since as you both mentioned, the logic is inverted. We've added notes in the CHANGELOG as well. 

To avoid breaking changes, we've kept `DataLakeFileClient.flush(long position, boolean overwrite)` the same in case there are users depending on passing `overwrite=false`. In your guys' case, you will need to continue to use `DataLakeFileClient.flush(data.length, true)` in order for it to work properly. 

Thanks again for bringing this issue to our attention, please let us know if you have any additional questions :)

**Comment by archana-jambhulkar-kr** [comment]
1. Can you please explain what is the purpose of overwrite flag in this method DataLakeFileClient.flush(long position, boolean overwrite) ?
2. Does DataLakeFileClient.flush(data.length, false) works ? or does it still throw 412 error ?
3. How does deprecating DataLakeFileClient.flush(long position) solves the problem ?

**Comment by archana-jambhulkar-kr** [comment]
Thanks for the clarification. Appreciate it.
