### ISSUE TITLE
[BUG] PasswordlessMySQLIT will fail in non-global environment

### ISSUE THREAD

**Issue by backwind1233** [Azure/azure-sdk-for-java#31476]
**Describe the bug**
Now we have PasswordlessMySQLIT to test our passwordless feature with MySQL, 
but it will fail in non-global environment('UsGov,China').

<img width="303" alt="image" src="https://user-images.githubusercontent.com/4465723/195749803-9c333781-6062-40a7-bf2a-b4cb8e78e062.png">

***Exception or Stack Trace***
[error link](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1912584&view=logs&j=f6cd9d1b-db6b-5aad-05d5-bfb021ebbd54&t=2e824c2a-ea24-5457-4b71-7c7060db6422&l=6849)
```
 "error": {
      "code": "DeploymentFailed",
      "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
      "details": [
        {
          "code": "ProvisioningDisabled",
          "message": "This subscription is restricted from provisioning MySQL servers in this region. Please choose a different region or open a support request with service and subscription limits (quotas) issue type."
        }
      ]

```

[error link](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1912584&view=logs&j=628b3ae7-b010-5d76-0167-08f9e6f337c2&t=5bb9b0cf-2b83-5130-973b-79b7a029cac2&l=460)
```
com.microsoft.aad.msal4j.MsalServiceException: AADSTS900382: Confidential Client is not supported in Cross Cloud request.
Trace ID: f4a206fb-1178-43a4-910e-05b4f6a43900
Correlation ID: aaa45bf3-0bc1-4ba9-8801-56453e8bce52
Timestamp: 2022-10-12 09:02:45Z
	at com.microsoft.aad.msal4j.MsalServiceExceptionFactory.fromHttpResponse(MsalServiceExceptionFactory.java:45) ~[msal4j-1.13.1.jar:1.13.1]
	at com.microsoft.aad.msal4j.TokenRequestExecutor.createAuthenticationResultFromOauthHttpResponse(TokenRequestExecutor.java:103) ~[msal4j-1.13.1.jar:1.13.1]
	at com.microsoft.aad.msal4j.TokenRequestExecutor.executeTokenRequest(TokenRequestExecutor.java:34) ~[msal4j-1.13.1.jar:1.13.1]
	at com.microsoft.aad.msal4j.AbstractClientApplicationBase.acquireTokenCommon(AbstractClientApplicationBase.java:128) ~[msal4j-1.13.1.jar:1.13.1]
	at com.microsoft.aad.msal4j.AcquireTokenByAuthorizationGrantSupplier.execute(AcquireTokenByAuthorizationGrantSupplier.java:63) ~[msal4j-1.13.1.jar:1.13.1]
	at com.microsoft.aad.msal4j.AcquireTokenByClientCredentialSupplier.acquireTokenByClientCredential(AcquireTokenByClientCredentialSupplier.java:86) ~[msal4j-1.13.1.jar:1.13.1]
	at com.microsoft.aad.msal4j.AcquireTokenByClientCredentialSupplier.execute(AcquireTokenByClientCredentialSupplier.java:49) ~[msal4j-1.13.1.jar:1.13.1]
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:71) [msal4j-1.13.1.jar:1.13.1]
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:20) [msal4j-1.13.1.jar:1.13.1]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604) [na:1.8.0_345]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_345]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_345]
	at java.lang.Thread.run(Thread.java:750) [na:1.8.0_345]

```

## CheckList
- [ ] The PasswordlessMySQLIT must be enabled before closing this issue.

**To Reproduce**

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - IDE: [e.g. IntelliJ]
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)]
 - Java version: [e.g. 8] 
 - App Server/Environment: [e.g. Tomcat, WildFly, Azure Function, Apache Spark, Databricks, IDE plugin or anything special]
 - Frameworks: [e.g. Spring Boot, Micronaut, Quarkus, etc] 

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by backwind1233** [comment]
The PasswordlessMySQLIT must be enabled before closing this issue.

**Comment by backwind1233** [comment]
![image](https://user-images.githubusercontent.com/4465723/196842796-e6bf496c-f149-4147-985d-925ad7e24625.png)

As the table shows, for china region, chinanorth3 is the only region all ITs can provision resources except for MySQL,
For now, we need to disable PasswordlessMySQLIT in China Cloud.

This is PR is used to enable PasswordlessMySQLIT in https://github.com/Azure/azure-sdk-for-java/pull/31595/ Public Cloud.
