### ISSUE TITLE
When consuming messages from servicebus , client got AMQP ERROR: Cannot add credits to closed link

### ISSUE THREAD

**Issue by wstest123** [Azure/azure-sdk-for-java#31513]
when consuming message from servicebus, the client got the following AMQP ERROR, and client can not consume any messages.

**Client Version**
azure-messaging-servicebus   7.7.0

***Exception or Stack Trace***
azure-messaging-servicebus   7.7.0
[2022-10-13 11:48:03.130] [parallel-16] [ERROR] [] [] [] [reactor.core.publisher.Operators.error@315] Operator called default onErrorDropped
reactor.core.Exceptions$ErrorCallbackNotImplemented: java.lang.IllegalStateException: Cannot add credits to closed link: t_youzan_order/subscriptions/t_cdp_ma_subscribe_dcp_youzan_order_e0eb61_1665632278474
Caused by: java.lang.IllegalStateException: Cannot add credits to closed link: t_youzan_order/subscriptions/t_cdp_ma_subscribe_dcp_youzan_order_e0eb61_1665632278474
at com.azure.core.amqp.implementation.ReactorReceiver.addCredits(ReactorReceiver.java:198)
at com.azure.messaging.servicebus.implementation.ServiceBusReceiveLinkProcessor.checkAndAddCredits(ServiceBusReceiveLinkProcessor.java:563)
at com.azure.messaging.servicebus.implementation.ServiceBusReceiveLinkProcessor.onNext(ServiceBusReceiveLinkProcessor.java:258)
at com.azure.messaging.servicebus.implementation.ServiceBusReceiveLinkProcessor.onNext(ServiceBusReceiveLinkProcessor.java:48)
at com.dynatrace.agent.introspection.reactor3.TracingReactorSubscriber.lambda$onNext$0(TracingReactorSubscriber.java:36)
at com.dynatrace.agent.introspection.reactor3.TracingReactorSubscriber.withActivePath(TracingReactorSubscriber.java:62)
at com.dynatrace.agent.introspection.reactor3.TracingReactorSubscriber.onNext(TracingReactorSubscriber.java:36)
at reactor.core.publisher.FluxRepeatPredicate$RepeatPredicateSubscriber.onNext(FluxRepeatPredicate.java:86)
at com.dynatrace.agent.introspection.reactor3.TracingReactorSubscriber.lambda$onNext$0(TracingReactorSubscriber.java:36)
at com.dynatrace.agent.introspection.reactor3.TracingReactorSubscriber.withActivePath(TracingReactorSubscriber.java:62)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:748)
[2022-10-13 11:48:03.131] [boundedElastic-402999] [WARN] [] [] [] [com.azure.messaging.servicebus.FluxAutoComplete.performLogging@500] Unable to 'complete' message.
java.lang.InterruptedException
[2022-10-13 11:48:03.131] [boundedElastic-402999] [ERROR] [] [] [] [com.azure.messaging.servicebus.FluxAutoComplete.performLogging@506] Error occurred. Passing downstream.
java.lang.InterruptedException
[2022-10-13 11:48:03.131] [boundedElastic-402560] [INFO] [] [] [] [c.a.messaging.servicebus.ServiceBusProcessorClient.performLogging@494] Error receiving messages.
[2022-10-13 11:48:03.131] [boundedElastic-402560] [INFO] [] [] [] [c.c.cep.service.event.ServiceBusServiceImpl.processError@105] Error when receiving messages from namespace: 'consumer-prd-cne2-cmsdcp-queue-sb-0.servicebus.chinacloudapi.cn'. Entity: 't_youzan_order/subscriptions/t_cdp_ma_subscribe_dcp_youzan_order
[2022-10-13 11:48:03.133] [reactor-executor-261841] [INFO] [] [] [] [c.a.c.amqp.implementation.ActiveClientTokenManager.performLogging@358] {"az.sdk.message":"Scheduling refresh token task.","scopes":"amqp://consumer-prd-cne2-cmsdcp-queue-sb-0.servicebus.chinacloudapi.cn/t_youzan_order/subscriptions/t_cdp_ma_subscribe_dcp_youzan_order"}
[2022-10-13 11:48:03.136] [reactor-executor-261841] [INFO] [] [] [] [com.azure.core.amqp.implementation.ReactorSession.performLogging@358] {"az.sdk.message":"Creating a new receiver 
link.","connectionId":"MF_a24483_1665632278473","sessionName":"t_youzan_order/subscriptions/t_cdp_ma_subscribe_dcp_youzan_order","linkName":"t_youzan_order/subscriptions/t_cdp_ma_subscribe_dcp_youzan_order_e0eb61_1665632278474"}
[2022-10-13 11:48:03.136] [boundedElastic-402560] [INFO] [] [] [] [c.c.cep.service.event.ServiceBusServiceImpl.processError@133] Error source RECEIVE, reason GENERAL_ERROR, message: {}
com.azure.messaging.servicebus.ServiceBusException: java.lang.InterruptedException
at com.azure.messaging.servicebus.ServiceBusReceiverAsyncClient.mapError(ServiceBusReceiverAsyncClient.java:1571)
at com.azure.messaging.servicebus.ServiceBusReceiverAsyncClient.lambda$receiveMessagesWithContext$18(ServiceBusReceiverAsyncClient.java:817)
at reactor.core.publisher.Flux.lambda$onErrorMap$28(Flux.java:6910)
at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94)
at com.dynatrace.agent.introspection.reactor3.TracingReactorSubscriber.lambda$onError$1(TracingReactorSubscriber.java:41)
at com.dynatrace.agent.introspection.reactor3.TracingReactorSubscriber.withActivePath(TracingReactorSubscriber.java:62)
at com.dynatrace.agent.introspection.reactor3.TracingReactorSubscriber.onError(TracingReactorSubscriber.java:41)
at com.dynatrace.agent.introspection.reactor3.TracingReactorSubscriber.lambda$onError$1(TracingReactorSubscriber.java:41)
at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:87)
... 33 common frames omitted
[2022-10-13 11:48:03.136] [boundedElastic-402560] [INFO] [] [] [] [c.a.m.servicebus.ServiceBusReceiverAsyncClient.info@222] Removing receiver links.
[2022-10-13 11:48:03.136] [boundedElastic-402560] [INFO] [] [] [] [c.a.messaging.servicebus.ServiceBusClientBuilder.performLogging@358] {"az.sdk.message":"Closing a dependent client.","numberOfOpenClients":0}
[2022-10-13 11:48:03.136] [boundedElastic-402560] [INFO] [] [] [] [c.a.messaging.servicebus.ServiceBusClientBuilder.info@222] No more open clients, closing shared connection.

**Comment by anuchandy** [comment]
Hello @wstest123, it looks like auto-complete is enabled, and there is a thread-race issue currently with auto-complete. Could you update the application to do explicit-complete as shown in this [sample](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/servicebus/azure-messaging-servicebus/src/samples/java/com/azure/messaging/servicebus/ServiceBusProcessorPeekLockReceiveSample.java)

**Comment by wstest123** [comment]
@anuchandy  Thanks so much for your advice! Is there any plan to fix the thread-race issue?

**Comment by anuchandy** [comment]
Hi Michelle, yes, it will be as part of this backlog [work-item](https://github.com/Azure/azure-sdk-for-java/issues/26084). For now, please use explicit APIs as shown in the sample.

**Comment by anuchandy** [comment]
Hi @vn53h3y, The Service Bus SDK version 7.9.1 is missing a reliability fix, [this ](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/core/azure-core-amqp/CHANGELOG.md#bugs-fixed-1) one. Could you 

1. Update to the latest SDK version
2. Then double-check three things - 
   -  code is opt-in for [disableAutoComplete](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/servicebus/azure-messaging-servicebus/src/samples/java/com/azure/messaging/servicebus/ServiceBusProcessorPeekLockReceiveSample.java#L58-L63).
    - code is doing explicit complete and abandon [call](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/servicebus/azure-messaging-servicebus/src/samples/java/com/azure/messaging/servicebus/ServiceBusProcessorPeekLockReceiveSample.java#L96-L110)
    - code is [handling ](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/servicebus/azure-messaging-servicebus/src/samples/java/com/azure/messaging/servicebus/ServiceBusProcessorPeekLockReceiveSample.java#L99-L102) exceptions from complete and abandon call, and is **NOT** rethrowing the exception

**Comment by anuchandy** [comment]
Guidance provided to mitigate the specific issue observed in the log (I.e. receiver not recovering after InterruptedException). Closing this issue as the underlying thread hoping problem is tracked in the mentioned work item.

**Comment by anuchandy** [comment]
Note: The deprecation work item will only address the problem with auto-complete so that app don’t have to do manual-complete. It has no relation to the log message: _"cannot add credit to closed link"_; this is a transient message when the link closes - treat it as errors like service busy, connection reset etc..
