### ISSUE TITLE
[BUG] [SB] Using  ServiceBusReceiverAsyncClient.prefetchCount > 0 causes backpressure overflow error

### ISSUE THREAD

**Issue by ialexandrov** [Azure/azure-sdk-for-java#31527]
**Describe the bug**
Using prefetchCount on  ServiceBusReceiverAsyncClient causues  backpressure overflow error due to incorrect counting of link credits.

***Exception or Stack Trace***
Caused by: reactor.core.Exceptions$OverflowException: Backpressure overflow during Sinks.Many#emitNext
	at reactor.core.Exceptions.failWithOverflow(Exceptions.java:233)
	at reactor.core.publisher.InternalManySink.emitNext(InternalManySink.java:46)
	at com.azure.core.amqp.implementation.handler.ReceiveLinkHandler.onDelivery(ReceiveLinkHandler.java:173)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:185)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291)
	at com.azure.core.amqp.implementation.ReactorExecutor.run(ReactorExecutor.java:91)
	at com.azure.core.amqp.implementation.ReactorExecutor$$Lambda$1075/0x0000000000000000.run(Unknown Source)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:866)

**To Reproduce**
1. Publish 10000 messages to session enabled queue
2. Start async session receiver with prefetchCount = 100 and RECEIVE_AND_DELETE mode.
3. call receiveMessages with subscriber doing some sleep on each message
4. Start the tests - after some time receiver will fail with error.

The failure is due to incorrect counting of credits on receive link when prefetch is enabled.
ServiceBusSessionReceiver calculates credits to add like this:

`receiveLink.addCredits(Math.max(0,prefetch - receiveLink.getCredits())).subscribe();`

While ReactorReceiver implements getCredits()  as receiver.getRemoteCredit()

`public int getRemoteCredit() {
        return this.getCredit() - this.getQueued();
    }`

So if receiver has received and queued deliveries, getRemoteCredit() might return 0 causing more credits to be added.  As number of link credits grows, deliveries overflow buffer in sink

**Expected behavior**
Expected is that receiver keeps number of credits on link not exceeding prefetchCount.

**Comment by ki1729** [comment]
@ialexandrov Thank you for resporting this! Yes we have observed the mismatch in link credits as well. We are actively working on a fix for this issue. Will provide more information about the release with the fix as soon as I have that information.

**Comment by ki1729** [comment]
@ialexandrov we are completely rewriting the credit calulation mechanism and the underlying framework, we are expecting the beta release for this to come out in the next 4-6 weeks. I will update here as soon as we have it released in beta

**Comment by pjrharley** [comment]
I believe I'm hitting this same bug, or something very similar to it. I created a repro case here:

https://github.com/pjrharley/ServiceBus.Batch.Repro

(there's some more details in the readme on that repo).

For me I can see thousands of messages being prefetched in the logs, and then what happens is that processing gets > 1 minute behind so I get loads of errors that lock tokens have expired.

Does it seem like this is the same issue, a mistake in my code, or should I raise this separately? It looks like that other issue linked above is making progress - is there a pre-release build I can try out to confirm whether this might be fixed?

**Comment by anuchandy** [comment]
The issue with credit calculation is fixed in version 7.15.x. Please follow the upgrade recommendation                                                                                                                                                              https://learn.microsoft.com/en-us/azure/developer/java/sdk/troubleshooting-messaging-service-bus-overview#upgrade-to-715x  


However, SDK cannot see the Reactor operators that application added to the Flux returned by low level `ServiceBusReceiverAsyncClient`. The SDK will only convert the backpressure request that Reactor operators calculated and informed as the credit to the broker. Because many Reactor operators have their own internal in-memory queues with different backpressure need, the total backpressure informed to the SDK could result in credit more than the application wanted. The SDK has no control over the operator chain that application uses and how Reactor chain compute backpressure internally. One example of this is happening with bufferTimeout+flatmap combination in the shared code. Therefore, it is advised to use `ServiceBusProcessorClient`, this is mentioned in README                                                                                                                                                                   [azure-sdk-for-java/sdk/servicebus/azure-messaging-servicebus/README.md at main · Azure/azure-sdk-for-java (github.com](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/servicebus/azure-messaging-servicebus/README.md#when-to-use-servicebusprocessorclient)
