### ISSUE TITLE
[BUG] Spark Cosmos connector contains an assumption that is liable to fail

### ISSUE THREAD

**Issue by achistef** [Azure/azure-sdk-for-java#31553]
Hi, 
I have noticed that the Spark Cosmos connector contains an assumption that may fail. The assumption is in the line `BulkWriter.scala:538` in version 4.13.1. We have 6 streaming applications that all use the Cosmos connector. There have been 5 incidents so far within the last 4 days, so this is not a once-in-a-lifetime scenario.
The stack trace is 
```
22/10/17 20:32:56 INFO DAGScheduler: ResultStage 50642 (start at command-2098666970312691:125) failed in 50.330 s due to Job aborted due to stage failure: Task 1 in stage 50642.0 failed 4 times, most recent failure: Lost task 1.3 in stage 50642.0 (TID 241160) (10.139.64.40 executor 0): java.lang.AssertionError: assumption failed
	at scala.Predef$.assume(Predef.scala:239)
	at com.azure.cosmos.spark.BulkWriter.flushAndClose(BulkWriter.scala:538)
	at com.azure.cosmos.spark.ItemsDataWriteFactory$CosmosWriter.commit(ItemsDataWriteFactory.scala:131)
	at org.apache.spark.sql.execution.datasources.v2.DataWritingSparkTask$.$anonfun$run$1(WriteToDataSourceV2Exec.scala:460)
	at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1691)
	at org.apache.spark.sql.execution.datasources.v2.DataWritingSparkTask$.run(WriteToDataSourceV2Exec.scala:487)
	at org.apache.spark.sql.execution.datasources.v2.V2TableWriteExec.$anonfun$writeWithV2$2(WriteToDataSourceV2Exec.scala:395)
	at org.apache.spark.scheduler.ResultTask.$anonfun$runTask$3(ResultTask.scala:75)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.ResultTask.$anonfun$runTask$1(ResultTask.scala:75)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:55)
	at org.apache.spark.scheduler.Task.doRunTask(Task.scala:150)
	at org.apache.spark.scheduler.Task.$anonfun$run$1(Task.scala:119)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.Task.run(Task.scala:91)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$13(Executor.scala:819)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1657)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:822)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:678)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
Unfortunately, I cannot provide you with some steps that reproduce the issue. It seems that the issue just "happens" at random. It may take hours to days until a streaming application fails due to that assumption. Also, the exception may rise from different streaming applications, so I wouldn't think that the problem is caused by the input.

The expected behaviour would be that long-lived streaming applications do not crash once in a while due to this assumption. Please correct me if I'm wrong.

The problem was observed in Azure Databricks 9.1. The library version that we use is 4.13.1

Additional context:
I hope that this bug report is not marked as incomplete because it lacks reproduction steps. There is a good reason for that. My mere observation is that the exception rises from a synchronization issue. Even if I knew exactly what the problem was, it would be very hard to reproduce a scenario in which the assumption fails.

 As far as I can see, the code assumes that the semaphore is in its full capacity `maxPendingOperations`. Since that assumption is false, the code releases less/more permits than it should. Even if I cannot spot why that happens, I will try to help by pointing out:
- line 532 `semaphore.release(activeTasks.get())`:  exiting the code block at line 514 ensures that `activeTasks.get()` returns 0, so this line would not release any permits
- line 176 `semaphore.release()` is in a finally block. I know little to none regarding the thread model of Spark, let alone the connector's. I wonder if the thread that executes the `finally` block is somehow interrupted/stopped before it finishes with the `finally` block.

I hope this information makes this bug worth looking into. Any questions are welcome. I will gladly provide more information if needed.

Enjoy the rest of your day!

**Comment by TheovanKraay** [comment]
Will consider whether this can be investigated and fixed with the information provided in next Semester.

**Comment by TheovanKraay** [comment]
@xinlian12 would you be able to take a look at this?

**Comment by xinlian12** [comment]
Hi @achistef, is that possible you can also try on the latest version 4.21.0 and see whether it is still re-producible? https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-cosmos-spark_3-1_2-12/CHANGELOG.md#4210-2023-08-09
https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-cosmos-spark_3-2_2-12/CHANGELOG.md#4210-2023-08-09
https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-cosmos-spark_3-3_2-12/CHANGELOG.md#4210-2023-08-09

**Comment by achistef** [comment]
We see the same issue in version 4.18.1 with Databricks 12.2 LTS, although it is less frequent.

**Comment by kushagraThapar** [comment]
Closing because of inactivity, @achistef can you please try the latest version and check if the issue still persists? If so, please feel free to re-open this issue and we will investigate, thanks!
