### ISSUE TITLE
[BUG] Not expected behaviors in storage account management operations

### ISSUE THREAD

**Issue by ghost** [Azure/azure-sdk-for-java#3164]
# Bug 1
**Describe the bug**
Get an not existing storage account, throw `NullPointerException` in earlier versions (v2016_01_01 and v2017-10-01), and return `null` in latest version.

***Exception or Stack Trace***
In v2016_01_01 and v2017-10-01:
```
java.lang.NullPointerException
	at com.microsoft.azure.management.storage.v2017_10_01.implementation.StorageAccountsImpl.wrapModel(StorageAccountsImpl.java:196)
	at com.microsoft.azure.management.storage.v2017_10_01.implementation.StorageAccountsImpl.wrapModel(StorageAccountsImpl.java:32)
	at com.microsoft.azure.arm.resources.collection.implementation.GroupableResourcesCoreImpl$1.call(GroupableResourcesCoreImpl.java:118)
	at com.microsoft.azure.arm.resources.collection.implementation.GroupableResourcesCoreImpl$1.call(GroupableResourcesCoreImpl.java:115)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.emitScalar(OperatorMerge.java:511)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.tryEmit(OperatorMerge.java:466)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:244)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:148)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
	at retrofit2.adapter.rxjava.CallArbiter.deliverResponse(CallArbiter.java:120)
	at retrofit2.adapter.rxjava.CallArbiter.emitResponse(CallArbiter.java:102)
	at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:46)
	at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:24)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.DeferredScalarSubscriber.subscribeTo(DeferredScalarSubscriber.java:153)
	at rx.internal.operators.OnSubscribeTakeLastOne.call(OnSubscribeTakeLastOne.java:32)
	at rx.internal.operators.OnSubscribeTakeLastOne.call(OnSubscribeTakeLastOne.java:22)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.subscribe(Observable.java:10423)
	at rx.Observable.subscribe(Observable.java:10390)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:443)
	at rx.observables.BlockingObservable.last(BlockingObservable.java:226)
	at com.microsoft.azure.arm.resources.collection.implementation.GroupableResourcesCoreImpl.getByResourceGroup(GroupableResourcesCoreImpl.java:110)
	at com.microsoft.azure.arm.resources.collection.implementation.GroupableResourcesCoreImpl.getByResourceGroup(GroupableResourcesCoreImpl.java:34)
Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: null
	at rx.exceptions.OnErrorThrowable.addValueAsLastCause(OnErrorThrowable.java:118)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:73)
```

**To Reproduce**
See code snippet below.

***Code Snippet***
```java
// Specified storage account name is not exist.
storageManager.storageAccounts().getByResourceGroup(resourceGroupName, randomAccountName);
```

**Expected behavior**
Throw `CloudException`, status code: `404`, error code: `ResourceNotFound`.

**Additional context**
The server does return expected error.
![Bug 1 server response](https://user-images.githubusercontent.com/48782724/54738120-d5559980-4bed-11e9-83f8-ee36a21308d1.png)

# Bug 2

**Describe the bug**
List storages accounts from not existing subscription, return empty list in earlier versions (v2016_01_01 and v2017-10-01), and throw `NullPointerException` in latest version.

***Exception or Stack Trace***
In latest version:
```
java.lang.NullPointerException
	at com.microsoft.azure.management.storage.implementation.StorageAccountsInner$22.call(StorageAccountsInner.java:698)
	at com.microsoft.azure.management.storage.implementation.StorageAccountsInner$22.call(StorageAccountsInner.java:693)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
	at retrofit2.adapter.rxjava.CallArbiter.deliverResponse(CallArbiter.java:120)
	at retrofit2.adapter.rxjava.CallArbiter.emitResponse(CallArbiter.java:102)
	at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:46)
	at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:24)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.subscribe(Observable.java:10423)
	at rx.Observable.subscribe(Observable.java:10390)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:443)
	at rx.observables.BlockingObservable.single(BlockingObservable.java:340)
	at com.microsoft.azure.management.storage.implementation.StorageAccountsInner.list(StorageAccountsInner.java:644)
	at com.microsoft.azure.management.resources.fluentcore.arm.collection.implementation.TopLevelModifiableResourcesImpl.list(TopLevelModifiableResourcesImpl.java:118)
```

**To Reproduce**
See code snippet below.

***Code Snippet***
```java
// Specified subscription id is not exist.
var storageManager = StorageManager.authenticate(credentials, randomSubscriptionId);
var result = storageManager.storageAccounts().list();
```

**Expected behavior**
Throw `CloudException`, status code: `404`, error code: `SubscriptionNotFound`.

**Screenshots**
The return value of v2016_01_01 and v2017-10-01:

![Bug 2 result](https://user-images.githubusercontent.com/48782724/54738168-10f06380-4bee-11e9-9652-5f7a319cea16.png)

**Additional context**
The server does return expected error.
![Bug 2 server response](https://user-images.githubusercontent.com/48782724/54738182-19489e80-4bee-11e9-860d-de05d5d832c3.png)

# Bug 3
**Describe the bug**
When update storage account, tags property cannot be serialized into payload body in earlier versions (v2016_01_01 and v2017-10-01).

**To Reproduce**
Execute code below on Azure Stack, all operations executed successfully, but the tags didn't updated at all.
Execute on Azure, throw `CloudException`, status code `400`,  error code: `MustSpecifyPropertyToUpdate`.

***Code Snippet***
```java
// 1. withTag
var result1 = storageAccount.update()
    .withTag("tag01key", "tag01value")
    .apply();

// 2. withTags
var tags = new HashMap<String, String>() {
    {
        put("tag01key", "tag01value");
        put("tag02key", "tag02value");
        put("tag03key", "tag03value");
    }
};
var result2 = storageAccount.update()
    .withTags(tags)
    .apply();

// 3. with other property
var result3 = storageAccount.update()
    .withEnableHttpsTrafficOnly(true)
    .withTag("tag01key", "tag01value")
    .apply();
```

**Expected behavior**
For valid operations, executed successfully. 
For invalid operations, throw `CloudException`, status code: `400`, error code: depend on test case.

**Additional context**
Tags property cannot be serialized into payload body as expected.
*Code Snippet 1 and 2*
![Bug 3 request 1](https://user-images.githubusercontent.com/48782724/54738400-1ef2b400-4bef-11e9-9d51-4d1c8e5b4559.png)
*Code Snippet 3*
![Bug 3 request 2](https://user-images.githubusercontent.com/48782724/54738408-231ed180-4bef-11e9-96bc-baaa38ff3cf4.png)

**Setup**
 - OS: Windows Server 2016
 - IDE : IntelliJ IDEA
 - Version of the Library used: 
   - com.microsoft.azure.storage.v2016_01_01:azure-mgmt-storage:1.0.0-beta-1
   - com.microsoft.azure.storage-2017-10-01:azure-mgmt-storage:1.0.0-beta-1
   - com.microsoft.azure:azure-mgmt-storage:1.20.1

**Comment by knithinc** [comment]
FYI, This is an Azure Stack issue.

**Comment by brandonhums** [comment]
@knithinc We have run the tests on Azure Cloud, it has the same issue. So I don't think this is only related to Azure Stack.

**Comment by yungezz** [comment]
hi @xccc-msft could you pls help to check are those issues still valid in latest storage lite packages? Are those issues service issue or SDK issue? thanks.

**Comment by xccc-msft** [comment]
For issue 1 and 2, it's invalid as it's by design we will return null when catching the cloud exception. We will plan to throw cloud exception within our next-generation SDK in the future.

For issue 3, it looks it's a generator issue. According the [lines](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/storage/mgmt-v2016_01_01/src/main/java/com/microsoft/azure/management/storage/v2016_01_01/implementation/StorageAccountImpl.java#L39-L40) in `createResourceAsync`, it's missing similar lines in `updateResourceAsync` for `updateParameter`.
cc: @jianghaolu, @weidongxu-microsoft
