### ISSUE TITLE
java.lang.ExceptionInInitializerError: null 

### ISSUE THREAD

**Issue by vishwanathdc** [Azure/azure-sdk-for-java#31669]
I have a java spring boot application which makes http get calls. The application is running on Kubernetes pod.
When I run a Java application, I am getting this error:

java.lang.ExceptionInInitializerError: null
	at reactor.netty.http.client.HttpClient.lambda$request$12(HttpClient.java:1042) ~[reactor-netty-0.9.20.RELEASE.jar!/:0.9.20.RELEASE]
	at reactor.netty.tcp.TcpClientBootstrap.configure(TcpClientBootstrap.java:39) ~[reactor-netty-0.9.20.RELEASE.jar!/:0.9.20.RELEASE]
	at reactor.netty.tcp.TcpClientBootstrap.configure(TcpClientBootstrap.java:39) ~[reactor-netty-0.9.20.RELEASE.jar!/:0.9.20.RELEASE]
	at reactor.netty.tcp.TcpClientBootstrap.configure(TcpClientBootstrap.java:39) ~[reactor-netty-0.9.20.RELEASE.jar!/:0.9.20.RELEASE]
	at reactor.netty.tcp.TcpClient.connect(TcpClient.java:212) ~[reactor-netty-0.9.20.RELEASE.jar!/:0.9.20.RELEASE]
	at reactor.netty.http.client.HttpClientFinalizer.connect(HttpClientFinalizer.java:80) ~[reactor-netty-0.9.20.RELEASE.jar!/:0.9.20.RELEASE]
	at reactor.netty.http.client.HttpClientFinalizer.responseConnection(HttpClientFinalizer.java:97) ~[reactor-netty-0.9.20.RELEASE.jar!/:0.9.20.RELEASE]
	at org.springframework.http.client.reactive.ReactorClientHttpConnector.connect(ReactorClientHttpConnector.java:112) ~[spring-web-5.2.15.RELEASE.jar!/:5.2.15.RELEASE]
	at org.springframework.web.reactive.function.client.ExchangeFunctions$DefaultExchangeFunction.exchange(ExchangeFunctions.java:104) ~[spring-webflux-5.2.15.RELEASE.jar!/:5.2.15.RELEASE]
	at org.springframework.web.reactive.function.client.DefaultWebClient$DefaultRequestBodyUriSpec.lambda$exchange$0(DefaultWebClient.java:338) ~[spring-webflux-5.2.15.RELEASE.jar!/:5.2.15.RELEASE]
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44) ~[reactor-core-3.3.17.RELEASE.jar!/:3.3.17.RELEASE]
	at reactor.core.publisher.Mono.subscribe(Mono.java:4252) ~[reactor-core-3.3.17.RELEASE.jar!/:3.3.17.RELEASE]
	at reactor.core.publisher.Mono.subscribeWith(Mono.java:4363) ~[reactor-core-3.3.17.RELEASE.jar!/:3.3.17.RELEASE]
	at reactor.core.publisher.Mono.toFuture(Mono.java:4697) ~[reactor-core-3.3.17.RELEASE.jar!/:3.3.17.RELEASE]
	at 
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:792) [spring-boot-2.3.12.RELEASE.jar!/:2.3.12.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:776) [spring-boot-2.3.12.RELEASE.jar!/:2.3.12.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:319) [spring-boot-2.3.12.RELEASE.jar!/:2.3.12.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1247) [spring-boot-2.3.12.RELEASE.jar!/:2.3.12.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1236) [spring-boot-2.3.12.RELEASE.jar!/:2.3.12.RELEASE]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_331]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_331]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_331]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_331]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) [app.jar:0.0.57]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) [app.jar:0.0.57]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) [app.jar:0.0.57]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) [app.jar:0.0.57]
Caused by: java.lang.IllegalArgumentException: 'httpClientConf' is already in use
	at io.netty.util.ConstantPool.createOrThrow(ConstantPool.java:108) ~[netty-common-4.1.65.Final.jar!/:4.1.65.Final]
	at io.netty.util.ConstantPool.newInstance(ConstantPool.java:90) ~[netty-common-4.1.65.Final.jar!/:4.1.65.Final]
	at io.netty.util.AttributeKey.newInstance(AttributeKey.java:55) ~[netty-common-4.1.65.Final.jar!/:4.1.65.Final]
	at reactor.netty.http.client.HttpClientConfiguration.<clinit>(HttpClientConfiguration.java:51) ~[reactor-netty-0.9.20.RELEASE.jar!/:0.9.20.RELEASE]
	... 30 common frames omitted

**Comment by fangjian0423** [comment]
hi @vishwanathdc 

Could you pls provide more details about this issue or provide a sample to reproduce it?

Thanks.
