### ISSUE TITLE
[BUG] OutOfMemoryError when calling ShareFileAsyncClient.getProperties() after `azure-storage-file-share` lib upgrade

### ISSUE THREAD

**Issue by croudet** [Azure/azure-sdk-for-java#31849]
**Describe the bug**
When using `azure-storage-file-share` version `12.15.1` and `12.16.0` I got an `OutOfMemoryError` when downloading large file (325M) with `ShareFileAsyncClient.downloadWithResponse()`
No such error with version `12.14.0`

***Exception or Stack Trace***
```
java.lang.OutOfMemoryError: Java heap space
	at com.azure.core.implementation.ByteBufferCollector.<init>(ByteBufferCollector.java:52) ~[azure-core-1.33.0.jar:1.33.0]
	at com.azure.core.util.FluxUtil.lambda$collectBytesInByteBufferStream$2(FluxUtil.java:139) ~[azure-core-1.33.0.jar:1.33.0]
	at com.azure.core.util.FluxUtil$$Lambda$1447/0x00000008014b4fc0.get(Unknown Source) ~[?:?]
	at reactor.core.publisher.MonoCollect.subscribeOrReturn(MonoCollect.java:58) ~[reactor-core-3.4.24.jar:3.4.24]
	at reactor.core.publisher.Flux.subscribe(Flux.java:8512) ~[reactor-core-3.4.24.jar:3.4.24]
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onNext(MonoFlatMapMany.java:195) ~[reactor-core-3.4.24.jar:3.4.24]
	at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:99) ~[reactor-core-3.4.24.jar:3.4.24]
	at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.onNext(FluxRetryWhen.java:174) ~[reactor-core-3.4.24.jar:3.4.24]
	at reactor.core.publisher.MonoCreate$DefaultMonoSink.success(MonoCreate.java:172) ~[reactor-core-3.4.24.jar:3.4.24]
	at reactor.netty.http.client.HttpClientConnect$HttpIOHandlerObserver.onStateChange(HttpClientConnect.java:431) ~[reactor-netty-http-1.0.24.jar:1.0.24]
	at reactor.netty.ReactorNetty$CompositeConnectionObserver.onStateChange(ReactorNetty.java:677) ~[reactor-netty-core-1.0.24.jar:1.0.24]
	at reactor.netty.resources.DefaultPooledConnectionProvider$DisposableAcquire.onStateChange(DefaultPooledConnectionProvider.java:187) ~[reactor-netty-core-1.0.24.jar:1.0.24]
	at reactor.netty.resources.DefaultPooledConnectionProvider$PooledConnection.onStateChange(DefaultPooledConnectionProvider.java:444) ~[reactor-netty-core-1.0.24.jar:1.0.24]
	at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:637) ~[reactor-netty-http-1.0.24.jar:1.0.24]
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:113) ~[reactor-netty-core-1.0.24.jar:1.0.24]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) ~[netty-transport-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336) ~[netty-codec-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308) ~[netty-codec-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) ~[netty-transport-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[netty-transport-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1373) ~[netty-handler-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1236) ~[netty-handler-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1285) ~[netty-handler-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:519) ~[netty-codec-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:458) ~[netty-codec-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:280) ~[netty-codec-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.84.Final.jar:4.1.84.Final]
```
**To Reproduce**
Limit your heap size, and download a large file with code below.
Jvm options used: `-Xms64M -Xmx256M -Xss256k -XX:+UseStringDeduplication -XX:MaxHeapFreeRatio=30 -XX:MinHeapFreeRatio=10`

***Code Snippet***
```java
        final ShareFileAsyncClient shareFileClient = ...
        final StreamingResponseBody streamingResponseBody = outputStream ->
                shareFileClient.downloadWithResponse(fileRange, null)
                        .flatMap(response -> FluxUtil.writeToOutputStream(response.getValue(), outputStream)).block();
        return responseEntity
                .cacheControl(CacheControl.maxAge(Duration.ofDays(10L)))
                .contentType(VIDEO_MP4)
                .contentLength(contentLength)
                .eTag(etag)
                .lastModified(lastModifiedInstant)
                .body(streamingResponseBody);
```

**Expected behavior**
No `OutOfMemoryError`.

**Setup (please complete the following information):**
 - OS: Windows 10
 - IDE: IntelliJ
 - Library/Libraries: `com.azure:azure-storage-file-share:12.16.0`
 - Java version: `OpenJDK Runtime Environment Temurin-17.0.5+8 (build 17.0.5+8)`
 - App Server/Environment: Tomcat
 - Frameworks: Spring-boot v2.7.5

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by alzimmermsft** [comment]
Thank you for filing this issue @croudet. Would it be possible for you to include a full reproduction of this issue, there are many factors that can change the runtime behavior when consuming responses. Also, would it be possible to include a call stack for when `ByteBufferCollector` is reach (where the `OutOfMemeoryError` is being thrown from). It's unexpected for this code path to be used for a download request.

**Comment by croudet** [comment]
Hi Alan,

You are right, in fact this `AzureAsyncFileClient.getProperties()` that crashes:
```java
public ResponseEntity<StreamingResponseBody> generateStreamingResponse(String filePath, HttpRange range, HttpHeaders headers) {
        final ShareFileAsyncClient shareFileClient = recordingsDirectoryAsyncClient.getFileClient(filePath);
        final ShareFileProperties shareFileProperties = shareFileClient.getProperties().block(); // IT CRASHES HERE
        // check etag and lastModified
        final String etag = '"' + shareFileProperties.getETag() + '"';
        final String fileName = filePath.substring(filePath.lastIndexOf('/'));

        // If-None-Match header should contain "*" or ETag. If so, then return 304.
        final List<String> ifNoneMatch = headers.getIfNoneMatch();
        if (!ifNoneMatch.isEmpty() && matches(ifNoneMatch, fileName)) {
            return ResponseEntity.status(HttpStatus.NOT_MODIFIED).header(HttpHeaders.ETAG, etag).build();
        }

        // If-Modified-Since header should be greater than LastModified. If so, then return 304.
        // This header is ignored if any If-None-Match header is specified.
        final long ifModifiedSince = headers.getIfModifiedSince();
        final Instant lastModifiedInstant = shareFileProperties.getLastModified().toInstant();
        final long lastModified = lastModifiedInstant.toEpochMilli();
        if (ifNoneMatch.isEmpty() && ifModifiedSince != -1L && ifModifiedSince + 1000L > lastModified) {
            return ResponseEntity.status(HttpStatus.NOT_MODIFIED).header(HttpHeaders.ETAG, etag).build();
        }

        //final ShareFileAsyncClient shareFileClient = shareFilePair.shareFileClient;
        final List<String> ifMatch = headers.getIfMatch();
        if (!ifMatch.isEmpty() && !matches(ifMatch, shareFileClient.getFilePath())) {
            return ResponseEntity.status(HttpStatus.PRECONDITION_FAILED).build();
        }

        // If-Unmodified-Since header should be greater than LastModified. If not, then return 412.
        final long ifUnmodifiedSince = headers.getIfUnmodifiedSince();
        if (ifUnmodifiedSince != -1L && ifUnmodifiedSince + 1000L <= lastModified) {
            return ResponseEntity.status(HttpStatus.PRECONDITION_FAILED).build();
        }

        range = checkIfRange(range, headers, etag);

        final ShareFileRange fileRange;
        final long resourceLength = shareFileProperties.getContentLength();
        final long contentLength;
        final ResponseEntity.BodyBuilder responseEntity;
        if (range == null) {
            fileRange = new ShareFileRange(0);
            contentLength = resourceLength;
            responseEntity = ResponseEntity.ok();
        } else {
            final long rangeStart = range.getRangeStart(resourceLength);
            final long rangeEnd = range.getRangeEnd(resourceLength);
            contentLength = rangeEnd - rangeStart + 1;
            // Note I have opened a bug for ShareFileRange https://github.com/Azure/azure-sdk-for-java/issues/31524
            // `end` is not handle properly when used with `openInputStream`
            fileRange = new ShareFileRange(rangeStart, rangeEnd);
            responseEntity = ResponseEntity.status(HttpStatus.PARTIAL_CONTENT)
                    .header(HttpHeaders.ACCEPT_RANGES, "bytes")
                    .header(HttpHeaders.CONTENT_RANGE, "bytes "
                            + rangeStart + '-'
                            + rangeEnd + '/'
                            + resourceLength);
        }
        final StreamingResponseBody streamingResponseBody = outputStream ->
                shareFileClient.downloadWithResponse(fileRange, null)
                        .flatMap(response -> FluxUtil.writeToOutputStream(response.getValue(), outputStream)).block();
        return responseEntity
                .cacheControl(CacheControl.maxAge(Duration.ofDays(10L)))
                .contentType(VIDEO_MP4)
                .contentLength(contentLength)
                .eTag(etag)
                .lastModified(lastModifiedInstant)
                .body(streamingResponseBody);
    }
```

**Comment by alzimmermsft** [comment]
@ibrahimrabab this looks similar to #31555

**Comment by alzimmermsft** [comment]
One more question @croudet, what form of authentication are you using? Connection string, SAS token, TokenCredential?

**Comment by croudet** [comment]
We are using connection string.

While debugging I saw a call to `public ByteBufferCollector(int initialSize)` with initialSize of 148297217.
