### ISSUE TITLE
[BUG] Unable to connect to postgresql with azure ad

### ISSUE THREAD

**Issue by vtapadia** [Azure/azure-sdk-for-java#31850]
Unable to connect to the Azure PostgreSQL Single server database with Managed Identity in a Spring Boot simple setup.

**Exception**
```console
2022-10-31 22:28:07.939  INFO [,,] 25480 --- [  restartedMain] org.hibernate.dialect.Dialect            : HHH000400: Using dialect: org.hibernate.dialect.PostgreSQLDialect
2022-10-31 22:28:08.541  INFO [,,] 25480 --- [  restartedMain] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
Disconnected from the target VM, address: '127.0.0.1:53157', transport: 'socket'
2022-10-31 22:28:09.832 ERROR [,,] 25480 --- [  restartedMain] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Exception during pool initialization.

org.postgresql.util.PSQLException: The server requested password-based authentication, but no password was provided by plugin null
	at org.postgresql.core.v3.AuthenticationPluginManager.lambda$withEncodedPassword$0(AuthenticationPluginManager.java:110) ~[postgresql-42.3.6.jar:42.3.6]
	at org.postgresql.core.v3.AuthenticationPluginManager.withPassword(AuthenticationPluginManager.java:81) ~[postgresql-42.3.6.jar:42.3.6]
	at org.postgresql.core.v3.AuthenticationPluginManager.withEncodedPassword(AuthenticationPluginManager.java:107) ~[postgresql-42.3.6.jar:42.3.6]
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:691) ~[postgresql-42.3.6.jar:42.3.6]
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:180) ~[postgresql-42.3.6.jar:42.3.6]
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:235) ~[postgresql-42.3.6.jar:42.3.6]
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49) ~[postgresql-42.3.6.jar:42.3.6]
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:223) ~[postgresql-42.3.6.jar:42.3.6]
	at org.postgresql.Driver.makeConnection(Driver.java:402) ~[postgresql-42.3.6.jar:42.3.6]
	at org.postgresql.Driver.connect(Driver.java:261) ~[postgresql-42.3.6.jar:42.3.6]
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[HikariCP-4.0.3.jar:na]
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364) ~[HikariCP-4.0.3.jar:na]
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206) ~[HikariCP-4.0.3.jar:na]
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476) ~[HikariCP-4.0.3.jar:na]
```
**To Reproduce**
Simple Spring Boot app with using the library
```
        <dependency>
            <groupId>com.azure.spring</groupId>
            <artifactId>spring-cloud-azure-starter-jdbc-postgresql</artifactId>
            <version>4.5.0-beta.1</version>
        </dependency>
```
Followed the guide as defined here
https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-data-jpa-with-azure-postgresql?toc=%2Fazure%2Fpostgresql%2Ftoc.json&bc=%2Fazure%2Fbread%2Ftoc.json&tabs=passwordless

also set the following properties
```
  datasource:
    url: jdbc:postgresql://<myDB>.postgres.database.azure.com:5432/postgres?sslmode=require
    username: <myRole>@<myDB>
    azure:
      passwordless-enabled: true

```
***Code Snippet***
After the properties, the application fails at the start while trying to create connection pool.

**Expected behavior**
The connection pool should have been setup without any errors.

**Setup (please complete the following information):**
 - OS: Windows
 - IDE: IntelliJ
 - Library/Libraries: 4.5.0-beta.1
 - Java version: 17
 - App Server/Environment: Tomcat
 - Frameworks: Spring Boot

**Additional context**
The example in the link considers System Managed Identity, but User Managed Identity is not explained on how to use or setup. I have defined the default identity using the following properties but not sure if this is the right way.
```
spring:
  cloud:
    azure:
      credential:
        managed-identity-enabled: true
        client-id: *clientID
        client-secret: *clientSecret
      profile:
        tenant-id: *tenantID
        cloud-type: azure
```

**Comment by backwind1233** [comment]
Hi @vtapadia, thanks for reaching out, I will look into this issue.

**Comment by backwind1233** [comment]
Hi @vtapadia 

Could you try configurations like below and also check this [documentation](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/migrate-postgresql-to-passwordless-connection?tabs=sign-in-azure-cli%2Cspring%2Capp-service%2Capp-service-identity%2Cassign-role-azure-cli).
:
```

spring:
  datasource:
    url: jdbc:postgresql://<myDB>.postgres.database.azure.com:5432/db
    username: <myRole>@<myDB>
    azure:
      passwordlessEnabled: true
      credential:
        managed-identity-enabled: true
```
I tried using managed  identity within Azure Spring Apps, and it worked.
![image](https://user-images.githubusercontent.com/4465723/199491062-c320f8fb-5ef1-4cff-b70f-f152f92dadb3.png)

**Comment by vtapadia** [comment]
HI @backwind1233 
Thanks for providing the feedback. I tried with your setup as well, but still gets the error.
One thing to mention is that we are **not** using Azure Spring Apps. Could it be that we are missing a library that is auto-available in the environment/buildpacks that you are deploying to.

I also noticed that the IntellijIdea could not detect the properties that you have mentioned being used by any class.
![image](https://user-images.githubusercontent.com/6841829/200142053-91c3d608-9d6c-47e1-8713-f7d68ac0fcab.png)

_I will have to see how I can share the code as corpotate policy won't allow me to share the current project that I am working on._

**Comment by vtapadia** [comment]
Hi @backwind1233 
Thanks for the quick reply.

1. I am still not able to see that the fields are identified, it is not able to detect even client-id when I give it actual value and not reference. So it seems I have to wait for the next drop to see that those values are detected in the Intellij. 
2. I am testing it locally only. I guess this is the issue maybe, because we do not use a service to deploy this. We host it ourselves (Cloud Foundry) and use the ClientSecretCredential to use the User Managed Identity to connect to other services. We use the same Client Secret to connect to Key Vault and other services and they work jsut fine.
3. Yes, and that is what I actually wanted to use, because we use User Managed Identity.

I thought that if it supports AD, then however we get the accesstoken, it should be able to use that to connect. But maybe I am expecting something that is still not supported. Can you confirm?

**Comment by stliu** [comment]
@backwind1233 with regard to this
> but the other two managed-identity-enabled and cloud-type should able be detected, it works in my local IDE.

could you check the generated metadata from released artifact?

**Comment by backwind1233** [comment]
Hi @stliu 
I checked the generated metadata and confirmed it contains the metadata.
1. I downloaded the jar file spring-cloud-azure-autoconfigure-4.5.0-beta.1.jar from maven central  [spring-cloud-azure-autoconfigure/4.5.0-beta.1](https://mvnrepository.com/artifact/com.azure.spring/spring-cloud-azure-autoconfigure/4.5.0-beta.1), unzip the jar and checked the metadata.
![image](https://user-images.githubusercontent.com/4465723/200570838-cd038d49-39e8-44b2-bfc7-159082d09b0a.png)

2. I also checked the [PR](https://github.com/Azure/azure-sdk-for-java/pull/31373)  and [file changes](https://github.com/backwind1233/azure-sdk-for-java/blob/db2b2911c67493bd836a77f7b8b3e360acaf65d1/sdk/spring/spring-cloud-azure-autoconfigure/src/main/resources/META-INF/additional-spring-configuration-metadata.json#L1512).

**Comment by vtapadia** [comment]
Hi,

Thanks and I will check this out and see if I can find the issue. In the meantime, we also deployed a azre spring cloud instance to see if this works there, but running into java version issue. For that I will have to raise another issue at the portal side..  :(

**Comment by stliu** [comment]
@vtapadia Hi any updates on this issue?
