### ISSUE TITLE
[BUG] Stream Mark exprires using blob nio implementation while reading a Seekable InputStream

### ISSUE THREAD

**Issue by sebastianhorn1** [Azure/azure-sdk-for-java#31924]
**Describe the bug**
When i set the Position of the Seekable Input Stream to an value which is bigger than maxint i will get an Exception (Stream Mark expires)
***Exception or Stack Trace***
Position: 2147753232 Bigger than MaxInttrue
2022-11-03 17:40:57 TRACE DefaultByteBufferPool:58 - Allocating new buffer of capacity: 2097152
2022-11-03 17:40:57 TRACE DefaultByteBufferPool:64 - Releasing buffer of capacity: 2097152
2022-11-03 17:40:57 TRACE DefaultByteBufferPool:58 - Allocating new buffer of capacity: 2097152
2022-11-03 17:40:58 TRACE DefaultByteBufferPool:83 - Read chunk of size 2097152 bytes in 717ms. (2.0 KB/ms).
2022-11-03 17:40:58 ERROR StorageInputStream:506 - Stream mark expired.
2022-11-03 17:40:58 ERROR NioBlobInputStream:324 - java.lang.RuntimeException: Stream mark expired.
Exception in thread "main" java.io.IOException: java.lang.RuntimeException: Stream mark expired.
	at com.azure.storage.blob.nio.NioBlobInputStream.reset(NioBlobInputStream.java:186)
	at com.azure.storage.blob.nio.AzureSeekableByteChannel.position(AzureSeekableByteChannel.java:175)
	at com.azure.storage.blob.nio.AzureSeekableByteChannel.position(AzureSeekableByteChannel.java:25)
Caused by: java.lang.RuntimeException: Stream mark expired.
	at com.azure.storage.common.StorageInputStream.reset(StorageInputStream.java:394)
	at com.azure.storage.blob.nio.NioBlobInputStream.reset(NioBlobInputStream.java:183)
	... 11 more

**To Reproduce**
SeekableByteChannel ch = Files.newByteChannel(fs.getPath(parts.getBlobName))
ch.position(2147753232L)

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**
Streaming should be possible even for larger Files

**Screenshots**

**Setup (please complete the following information):**
 - OS: Windows
 - IDE: Intellij
 - Library/Libraries:com.azure:azure-storage-blob-nio:12.0.0-beta.19
 - Java version: [e.g. 8] 
 - App Server/Environment: n.a.
 - Frameworks: -

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [ ] Setup information Added

**Comment by joshfree** [comment]
Thank you for filing this issue, @sebastianhorn1; someone from the storage team will follow up shortly.

**Comment by jaschrep-msft** [comment]
@sebastianhorn1 we've looked into this and the issue stems from a lack of SeekableByteChannel implementation in the standard blob package. Currently there is only InputStream support, which is limited by mark() only supporting int values instead of long.

Without some nasty hacks, the way out of this is for there to be a true SeekableByteChannel implementation in the first place, which is a larger feature ask. This would ideally be supported in the main blobs package and wrapped by our NIO package.
