### ISSUE TITLE
PoolAcquirePendingLimitException

### ISSUE THREAD

**Issue by ranjith106** [Azure/azure-sdk-for-java#31971]
- We are getting the below issue on frequently , when we are using to get the BlockBlobClient and Blob read operation by using the azure java sdk
- We have raised a azure ticket for the same with all the details - TrackingID#2210190030001911
-   azure.version : 1.0.6

**Exception:**
reactor.netty.internal.shaded.reactor.pool.PoolAcquirePendingLimitException: Pending acquire queue has reached its maximum size of 32
              at reactor.netty.internal.shaded.reactor.pool.SimpleDequePool.drainLoop(SimpleDequePool.java:365)
              at reactor.netty.internal.shaded.reactor.pool.SimpleDequePool.pendingOffer(SimpleDequePool.java:551)
              at reactor.netty.internal.shaded.reactor.pool.SimpleDequePool.doAcquire(SimpleDequePool.java:268)
              at reactor.netty.internal.shaded.reactor.pool.AbstractPool$Borrower.request(AbstractPool.java:432)
              at reactor.netty.resources.DefaultPooledConnectionProvider$DisposableAcquire.onSubscribe(DefaultPooledConnectionProvider.java:212)
              at reactor.netty.internal.shaded.reactor.pool.SimpleDequePool$QueueBorrowerMono.subscribe(SimpleDequePool.java:676)
              at reactor.netty.resources.PooledConnectionProvider.lambda$acquire$1(PooledConnectionProvider.java:135)
              at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:57)
              at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
              at reactor.netty.http.client.HttpClientConnect$MonoHttpConnect.lambda$subscribe$0(HttpClientConnect.java:268)
              at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:57)
              at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
              at reactor.core.publisher.FluxRetryWhen.subscribe(FluxRetryWhen.java:77)
              at reactor.core.publisher.MonoRetryWhen.subscribeOrReturn(MonoRetryWhen.java:46)
              at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
              at reactor.netty.http.client.HttpClientConnect$MonoHttpConnect.subscribe(HttpClientConnect.java:271)
              at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
              at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
              at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
              at reactor.core.publisher.FluxRetryWhen.subscribe(FluxRetryWhen.java:77)
              at reactor.core.publisher.MonoRetryWhen.subscribeOrReturn(MonoRetryWhen.java:46)
              at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
              at io.opentelemetry.javaagent.instrumentation.azurecore.v1_19.SuppressNestedClientMono.subscribe(SuppressNestedClientMono.java:30)
              at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
              at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
              at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
              at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:236)
              at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:203)
              at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.withActiveSpan(TracingSubscriber.java:79)
              at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.onComplete(TracingSubscriber.java:68)
              at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:148)
              at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.lambda$onNext$1(TracingSubscriber.java:58)
              at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.withActiveSpan(TracingSubscriber.java:79)
              at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.onNext(TracingSubscriber.java:58)
              at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.lambda$onNext$1(TracingSubscriber.java:58)
              at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.withActiveSpan(TracingSubscriber.java:79)
              at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.onNext(TracingSubscriber.java:58)
              at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:82)
              at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.lambda$onNext$1(TracingSubscriber.java:58)
              at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.withActiveSpan(TracingSubscriber.java:79)
              at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.onNext(TracingSubscriber.java:58)
              at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:99)
              at reactor.core.publisher.FluxRepeatWhen$RepeatWhenMainSubscriber.onNext(FluxRepeatWhen.java:142)
              at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.lambda$onNext$1(TracingSubscriber.java:58)
              at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.withActiveSpan(TracingSubscriber.java:79)
              at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.onNext(TracingSubscriber.java:58)
              at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.lambda$onNext$1(TracingSubscriber.java:58)
              at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.withActiveSpan(TracingSubscriber.java:79)
              at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.onNext(TracingSubscriber.java:58)
              at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:130)
              at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.lambda$onNext$1(TracingSubscriber.java:58)
              at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.withActiveSpan(TracingSubscriber.java:79)
              at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.onNext(TracingSubscriber.java:58)
              at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onNext(FluxHide.java:137)
              at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:180)
              at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.lambda$onNext$1(TracingSubscriber.java:58)
              at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.withActiveSpan(TracingSubscriber.java:79)
              at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.onNext(TracingSubscriber.java:58)
              at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onNext(FluxHide.java:137)
              at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
              at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:249)
              at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2398)
              at reactor.core.publisher.MonoFlatMap$FlatMapInner.onSubscribe(MonoFlatMap.java:238)
              at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:55)
              at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
              at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157)
              at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.lambda$onNext$1(TracingSubscriber.java:58)
              at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.withActiveSpan(TracingSubscriber.java:79)
              at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.onNext(TracingSubscriber.java:58)
              at reactor.core.publisher.MonoMaterialize$MaterializeSubscriber.drain(MonoMaterialize.java:133)
              at reactor.core.publisher.MonoMaterialize$MaterializeSubscriber.onComplete(MonoMaterialize.java:127)
              at reactor.core.publisher.Operators.complete(Operators.java:137)
              at reactor.core.publisher.MonoEmpty.subscribe(MonoEmpty.java:46)
              at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
              at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
              at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
              at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
              at reactor.core.publisher.Mono.subscribe(Mono.java:4400)
              at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:255)
              at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51)
              at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
              at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
              at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
              at reactor.core.publisher.MonoDelaySubscription.accept(MonoDelaySubscription.java:53)
              at reactor.core.publisher.MonoDelaySubscription.accept(MonoDelaySubscription.java:34)
              at reactor.core.publisher.FluxDelaySubscription$DelaySubscriptionOtherSubscriber.onNext(FluxDelaySubscription.java:131)
              at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.lambda$onNext$1(TracingSubscriber.java:58)
              at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.withActiveSpan(TracingSubscriber.java:79)
              at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.onNext(TracingSubscriber.java:58)
              at reactor.core.publisher.MonoDelay$MonoDelayRunnable.propagateDelay(MonoDelay.java:271)
              at reactor.core.publisher.MonoDelay$MonoDelayRunnable.run(MonoDelay.java:286)
              at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
              at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
              at java.util.concurrent.FutureTask.run(FutureTask.java:266)
              at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
              at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
              at java.lang.Thread.run(Thread.java:748)

reactor.netty.internal.shaded.reactor.pool.PoolAcquirePendingLimitException: Pending acquire queue has reached its maximum size of 32
              at reactor.netty.internal.shaded.reactor.pool.SimpleDequePool.drainLoop(SimpleDequePool.java:365)
              at reactor.netty.internal.shaded.reactor.pool.SimpleDequePool.pendingOffer(SimpleDequePool.java:551)
              at reactor.netty.internal.shaded.reactor.pool.SimpleDequePool.doAcquire(SimpleDequePool.java:268)
              at reactor.netty.internal.shaded.reactor.pool.AbstractPool$Borrower.request(AbstractPool.java:432)
              at reactor.netty.resources.DefaultPooledConnectionProvider$DisposableAcquire.onSubscribe(DefaultPooledConnectionProvider.java:212)
              at reactor.netty.internal.shaded.reactor.pool.SimpleDequePool$QueueBorrowerMono.subscribe(SimpleDequePool.java:676)
              at reactor.netty.resources.PooledConnectionProvider.lambda$acquire$1(PooledConnectionProvider.java:135)
              at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:57)
              at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)

**Comment by jaschrep-msft** [comment]
Hi @ranjith106, can you please give us

- azure-storage-blob version
- sample code of how you are using the offending library functionality
- known environmental trends when the issue triggers (e.g. blob size, high concurrency, network slowdown, etc., we can explore this more as things become clearer)
