### ISSUE TITLE
[Azure/azure-sdk-for-java]: import certificate to keyvault by CertificateClient failed

### ISSUE THREAD

**Issue by CQ-Developer** [Azure/azure-sdk-for-java#31997]
**Query/Question**
try to use keyvault to upload a customized certificate(cert.pem) failed.

**Setup (please complete the following information if applicable):**
 - OS: win10
 - IDE: IntelliJ
 - Library/Libraries: com.azure:azure-security-keyvault-certificates:4.4.1
 
 **Information Checklist**
error:
```txt
Exception in thread "main" com.azure.core.exception.HttpResponseException: Status code 400, "{"error":{"code":"BadParameter","message":"No certificate with private key found in the specified X.509 certificate content. Please specify X.509 certificate content with only one certificate containing private key."}}"
	at com.azure.core.implementation.http.rest.RestProxyBase.instantiateUnexpectedException(RestProxyBase.java:348)
	at com.azure.core.implementation.http.rest.SyncRestProxy.ensureExpectedStatus(SyncRestProxy.java:126)
	at com.azure.core.implementation.http.rest.SyncRestProxy.handleRestReturnType(SyncRestProxy.java:209)
	at com.azure.core.implementation.http.rest.SyncRestProxy.invoke(SyncRestProxy.java:79)
	at com.azure.core.implementation.http.rest.RestProxyBase.invoke(RestProxyBase.java:94)
	at com.azure.core.http.rest.RestProxy.invoke(RestProxy.java:95)
	at com.sun.proxy.$Proxy3.importCertificate(Unknown Source)
	at com.azure.security.keyvault.certificates.implementation.CertificateClientImpl.importCertificateWithResponse(CertificateClientImpl.java:1869)
	at com.azure.security.keyvault.certificates.CertificateClient.importCertificateWithResponse(CertificateClient.java:1569)
	at com.azure.security.keyvault.certificates.CertificateClient.importCertificate(CertificateClient.java:1539)
	at org.hhu.key.vault.demo.App.main(App.java:48)

```

pom.xml:
```xml
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-sdk-bom</artifactId>
            <version>1.2.7</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>
<dependencies>
    <dependency>
        <groupId>com.azure</groupId>
        <artifactId>azure-security-keyvault-certificates</artifactId>
    </dependency>
    <dependency>
        <groupId>com.azure</groupId>
        <artifactId>azure-identity</artifactId>
    </dependency>
</dependencies>
```

customized certificate:
```shell
openssl req -newkey rsa:2048 -x509 -keyout key.pem -out cert.pem -days 365
```

code:
```java
ClientSecretCredential clientSecretCredential = new ClientSecretCredentialBuilder()
        .authorityHost(authorityHost)
        .tenantId(tenantId)
        .clientId(clientId)
        .clientSecret(clientSecret)
        .build();

CertificateClient certificateClient = new CertificateClientBuilder()
        .credential(clientSecretCredential)
        .vaultUrl(url)
        .buildClient();

CertificateFactory certificateFactory = CertificateFactory.getInstance("X.509");
Certificate certificate = certificateFactory.generateCertificate(Files.newInputStream(Paths.get("C:/chen/tmp/cert.pem")));
byte[] bytes = certificate.getEncoded();

ImportCertificateOptions importCertificateOptions = new ImportCertificateOptions("cert-test", bytes);
importCertificateOptions.setEnabled(true);
importCertificateOptions.setPassword("1234");

// ERROR
KeyVaultCertificateWithPolicy keyVaultCertificateWithPolicy = certificateClient.importCertificate(importCertificateOptions);
```

**Comment by CQ-Developer** [comment]
@vcolin7 please check on this for me, thank you!

**Comment by vcolin7** [comment]
Hi @CQ-Developer, sorry for the late reply!

Your certificate's private key is missing from the X.509 certificate you're trying to import to your vault. This key is in the file `key.pem` (from the command you used to generate your certificate).

You can use the following commands to produce a combined file including both your certificate and unencrypted key:

```bash
openssl req -newkey rsa:2048 -x509 -keyout key.pem -out cert.pem -days 365
openssl pkcs8 -topk8 -inform PEM -outform PEM -in key.pem -out unencryprtedKey.pem -nocrypt
cat cert.pem unencryprtedKey.pem > certWithKey.pem
```

Then you can pass the file's bytes to the `importCertificate()` method like so:

```java
String pemPath = getClass().getClassLoader().getResource(<path-to-certWithKey.pem>).getPath();
StringBuilder pemCert = new StringBuilder();

try (BufferedReader br = new BufferedReader(new FileReader(pemPath))) {
    String line;

    while ((line = br.readLine()) != null) {
        pemCert.append(line).append("\n");
    }
}

byte[] certificateContents = pemCert.toString().getBytes();

ImportCertificateOptions importCertificateOptions =
    new ImportCertificateOptions("cert-test", certificateContents)
        .setEnabled(true)
        .setPassword("1234");

KeyVaultCertificateWithPolicy keyVaultCertificateWithPolicy = certificateClient.importCertificate(importCertificateOptions);
```

**Comment by CQ-Developer** [comment]
@vcolin7 

Thank you for your reply.

I tried and success.

But if I want to import a third-part certificate, how should I do?
In this case, I have their certificate but absolutely no private key.

**Comment by CQ-Developer** [comment]
@vcolin7 

Thanks again.

For this case, I turned to use `SecretClient`.

**Comment by vcolin7** [comment]
Hi @CQ-Developer, sorry for not getting back to you earlier, I was out for most of last week. Your use of a `SecretClient` sounds like an adequate approach, as the Key vault service itself stores the private key of a certificate it creates as a secret, which in turn cannot be retrieved with as `CertificateClient`.
