### ISSUE TITLE
[BUG] tokenCachePersistenceOptions.unencryptedStorageAllowed not functioning on Linux

### ISSUE THREAD

**Issue by zc07** [Azure/azure-sdk-for-java#32138]
Using InteractiveBrowser to get the accessToken for Blob and cache the token as unencrypted file in a local directory, which by default to be `~/.IdentityService/localTokenCache`. 

Based on the [documentation](https://learn.microsoft.com/en-us/java/api/com.azure.identity.tokencachepersistenceoptions?view=azure-java-stable), I should be able to do that by using `tokenCachePersistanceOption.setUnencryptedStorageAllowed(true)`, following is some sudo code:

``` java
tokenCachePersistanceOptions.setName("localTokenCache")
tokenCachePersistanceOptions.setUnencryptedStorageAllowed(true)
...
sharedTokenCredentialBuilder.tokenCachePersistenceOptions(tokenCachePersistanceOptions)
```

This created an empty file `~/.IdentityService/localTokenCache`, and no token is being cached here.

This is the exact same behavior as if `tokenCachePersistanceOption.setUnencryptedStorageAllowed(false)`, only an empty file is being created.

Reading through the code in [PersistentTokenCacheImpl.java](https://github.com/Azure/azure-sdk-for-java/blob/742b5dd7192fee169a26372a0d4505c2a8e53af8/sdk/identity/azure-identity/src/main/java/com/azure/identity/implementation/PersistentTokenCacheImpl.java#L79), it looks like this flag is never being used and unencrypted local file will only be created when there is an exception when setting the Linux Keyring. 

The document also mentioned about specifying the cache file location using `cacheFileLocation()`, which I wasn't able to find any reference in either the doc or the codebase.

**Expected behavior**
An unencrypted token cache file should be created under `~/.IdentityService` directory.

**Setup (please complete the following information):**
 - OS: Debian
 - IDE: N/A
 - Library/Libraries: com.azure:azure-identity:1.7.0
 - Java version: 8 
 - App Server/Environment: Local
 - Frameworks: N/A

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by joshfree** [comment]
@g2vinay could you please follow up with @zc07 on this issue? 

cc: @billwert

**Comment by zc07** [comment]
Any update on this issue? Instead of using the following:

``` java
        } else if (Platform.isLinux()) {
            try {
                persistenceSettingsBuilder
                    .setLinuxKeyring(DEFAULT_KEYRING_NAME, DEFAULT_KEYRING_SCHEMA,
                        name != null ? name : DEFAULT_KEYRING_ITEM_NAME, DEFAULT_KEYRING_ATTR_NAME,
                        DEFAULT_KEYRING_ATTR_VALUE, null, null);
                return persistenceSettingsBuilder.build();
            } catch (KeyRingAccessException e) {
                if (!allowUnencryptedStorage) {
                    throw LOGGER.logExceptionAsError(e);
                }
                persistenceSettingsBuilder.setLinuxUseUnprotectedFileAsCacheStorage(true);
                return persistenceSettingsBuilder.build();
            }
```

Change it to the following should help:
``` java
        } else if (Platform.isLinux()) {
            // Use Keyring when disallowed unencrypted storage
            if !allowUnencryptedStorage{
                persistenceSettingsBuilder
                    .setLinuxKeyring(DEFAULT_KEYRING_NAME, DEFAULT_KEYRING_SCHEMA,
                        name != null ? name : DEFAULT_KEYRING_ITEM_NAME, DEFAULT_KEYRING_ATTR_NAME,
                        DEFAULT_KEYRING_ATTR_VALUE, null, null);
                return persistenceSettingsBuilder.build();
            } else {
                // Use local directory with default ~/.IdentityService/msal.cache when allowed unencrypted storage
                persistenceSettingsBuilder.setLinuxUseUnprotectedFileAsCacheStorage(true);
                return persistenceSettingsBuilder.build();
            }
```

Which make it consistent with the documentation.

Additionally, `DEFAULT_CACHE_FILE_NAME` and `DEFAULT_CACHE_FILE_PATH` should be from some input arguments if `cacheFileLocation()` is set (It's documented, but I'm not seeing it to be implemented).

I did a quick verification using the following and it successfully uses/creates `~/.IdentityService/msal.cache`:

``` java
        } else if (Platform.isLinux()) {
            // Force to use unprotected file
            persistenceSettingsBuilder.setLinuxUseUnprotectedFileAsCacheStorage(true);
        }
```

**Comment by billwert** [comment]
@zc07 Hello, thanks for the great deep dive. We will take a look at this very soon and get it into a future release.

**Comment by g2vinay** [comment]
@zc07 
Thank you for bringing up this issue, I am looking into this and will provide an update before our upcoming release next month.

**Comment by g2vinay** [comment]
The `setUnencryptedStorageAllowed` API enables caching to an unprotected file only when Linux Key Ring isn't working. 
There's probably some miscommunication from the documentation, I will get it updated.
The behavior which you're getting is what's intended.

Resolving this issue.
Let us know if you still need any assistance.

**Comment by zc07** [comment]
> The `setUnencryptedStorageAllowed` API enables caching to an unprotected file only when Linux Key Ring isn't working. There's probably some miscommunication from the documentation, I will get it updated. The behavior which you're getting is what's intended.
> 
> Resolving this issue. Let us know if you still need any assistance.

Hi @g2vinay, does that mean there is no code update? According to your comment, an unprotected file should be created when:

1. ***setUnencryptedStorageAllowed(true)***
2. ***No linux keyring in the OS***

This is exactly what I did in the [reproduction code above](https://github.com/Azure/azure-sdk-for-java/issues/32138#issuecomment-1540752875). Instead of generating the cache, it throws exceptions.

Could you point me to where `KeyRingAccessException` is being thrown in this workflow? Neither [`persistenceSettingsBuilder.setLinuxKeyring`](https://github.com/AzureAD/microsoft-authentication-extensions-for-java/blob/c8bb9d7bad5785983c5de21b2f2dea8d4f09171e/src/main/java/com/microsoft/aad/msal4jextensions/PersistenceSettings.java#L247) nor [`persistenceSettingsBuilder.build()`](https://github.com/AzureAD/microsoft-authentication-extensions-for-java/blob/c8bb9d7bad5785983c5de21b2f2dea8d4f09171e/src/main/java/com/microsoft/aad/msal4jextensions/PersistenceSettings.java#L314) does it.

I'm not seeing how this is an expected behavior and either [`PersistenceSettings.java`](https://github.com/AzureAD/microsoft-authentication-extensions-for-java/blob/c8bb9d7bad5785983c5de21b2f2dea8d4f09171e/src/main/java/com/microsoft/aad/msal4jextensions/PersistenceSettings.java#L314) or [`private PersistenceSettings getPersistenceSettings()`](https://github.com/Azure/azure-sdk-for-java/blob/742b5dd7192fee169a26372a0d4505c2a8e53af8/sdk/identity/azure-identity/src/main/java/com/azure/identity/implementation/PersistentTokenCacheImpl.java#L80) needs to throw this exact exception.

**Comment by uvoigt** [comment]
I experience the same error using latest com.azure:azure-identity:1.13.0
The exception occurs after PersistentTokenCacheImpl.getPersistenceSettings within PersistenceTokenCacheAccessAspect constructor (see below)

I assume that this has been successfully tested, but fails within a container image lacking some features just as the keyring.
To test this I installed `apt -y install libsecret-1-0 keychain` but that did not help yet

Are there hints or suggestions on what has to be installed or configured to make that work correctly?


`Caused by: java.lang.Error: Exception reading field 'domain' in class com.microsoft.aad.msal4jextensions.persistence.linux.GError	at com.sun.jna.Structure.getFieldValue(Structure.java:653)	at com.sun.jna.Structure.deriveLayout(Structure.java:1318)	at com.sun.jna.Structure.calculateSize(Structure.java:1192)	at com.sun.jna.Structure.calculateSize(Structure.java:1144)	at com.sun.jna.Structure.useMemory(Structure.java:358)	at com.sun.jna.Structure.<init>(Structure.java:213)	at com.sun.jna.Structure.<init>(Structure.java:204)	at com.sun.jna.Structure.<init>(Structure.java:200)	at com.microsoft.aad.msal4jextensions.persistence.linux.GError.<init>(GError.java:25)	at com.microsoft.aad.msal4jextensions.persistence.linux.KeyRingAccessor.write(KeyRingAccessor.java:111)	at com.microsoft.aad.msal4jextensions.persistence.linux.KeyRingAccessor.verify(KeyRingAccessor.java:56)	at com.microsoft.aad.msal4jextensions.PersistenceTokenCacheAccessAspect.<init>(PersistenceTokenCacheAccessAspect.java:86)	at com.azure.identity.implementation.PersistentTokenCacheImpl.registerCache(PersistentTokenCacheImpl.java:61)	... 29 common frames omittedCaused by: java.lang.IllegalAccessException: class com.sun.jna.Structure cannot access a member of class com.microsoft.aad.msal4jextensions.persistence.linux.GError with modifiers "public"	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Unknown Source)	at java.base/java.lang.reflect.AccessibleObject.checkAccess(Unknown Source)	at java.base/java.lang.reflect.Field.checkAccess(Unknown Source)	at java.base/java.lang.reflect.Field.get(Unknown Source)	at com.sun.jna.Structure.getFieldValue(Structure.java:650)	... 41 common frames omitted
`

**Comment by zc07** [comment]
> `KeyRingAccessException`

I've been waiting for a solution since 2022 and yet to hear any feedback.

My hypothesis is they are making the assumption and design that `KeyRingAccessException` is expected to be thrown by a specific third-party keyring in their test environment when something goes wrong, given that none of the Microsoft code does that.

In the actual use cases, the keyring they are looking for may not even exist in the OS (Container is a perfect example), so nobody is going to throw the expected exception (Which is a totally valid use case based on their doc), and thereby the whatever happens will crash the SDK and not be catched.

Either update the exceptions to catch, or actually throw an exception would be a solution. The implementation should only be a couple lines. I'm not sure why it takes so long.

**Comment by zc07** [comment]
> I experience the same error using latest com.azure:azure-identity:1.13.0 The exception occurs after PersistentTokenCacheImpl.getPersistenceSettings within PersistenceTokenCacheAccessAspect constructor (see below)
> 
> I assume that this has been successfully tested, but fails within a container image lacking some features just as the keyring. To test this I installed `apt -y install libsecret-1-0 keychain` but that did not help yet
> 
> Are there hints or suggestions on what has to be installed or configured to make that work correctly?
> 
> ```
> Caused by: java.lang.Error: Exception reading field 'domain' in class com.microsoft.aad.msal4jextensions.persistence.linux.GError
> 	at com.sun.jna.Structure.getFieldValue(Structure.java:653)
> 	at com.sun.jna.Structure.deriveLayout(Structure.java:1318)
> 	at com.sun.jna.Structure.calculateSize(Structure.java:1192)
> 	at com.sun.jna.Structure.calculateSize(Structure.java:1144)
> 	at com.sun.jna.Structure.useMemory(Structure.java:358)
> 	at com.sun.jna.Structure.<init>(Structure.java:213)
> 	at com.sun.jna.Structure.<init>(Structure.java:204)
> 	at com.sun.jna.Structure.<init>(Structure.java:200)
> 	at com.microsoft.aad.msal4jextensions.persistence.linux.GError.<init>(GError.java:25)
> 	at com.microsoft.aad.msal4jextensions.persistence.linux.KeyRingAccessor.write(KeyRingAccessor.java:111)
> 	at com.microsoft.aad.msal4jextensions.persistence.linux.KeyRingAccessor.verify(KeyRingAccessor.java:56)
> 	at com.microsoft.aad.msal4jextensions.PersistenceTokenCacheAccessAspect.<init>(PersistenceTokenCacheAccessAspect.java:86)
> 	at com.azure.identity.implementation.PersistentTokenCacheImpl.registerCache(PersistentTokenCacheImpl.java:61)	... 29 common frames omitted
> Caused by: java.lang.IllegalAccessException: class com.sun.jna.Structure cannot access a member of class com.microsoft.aad.msal4jextensions.persistence.linux.GError with modifiers "public"
> 	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Unknown Source)
> 	at java.base/java.lang.reflect.AccessibleObject.checkAccess(Unknown Source)
> 	at java.base/java.lang.reflect.Field.checkAccess(Unknown Source)
> 	at java.base/java.lang.reflect.Field.get(Unknown Source)
> 	at com.sun.jna.Structure.getFieldValue(Structure.java:650)
> 	... 41 common frames omitted
> ```

I've been waiting for a solution since 2022 and yet to hear any feedback.

My hypothesis is they are making the assumption and design that `KeyRingAccessException` is expected to be thrown by a specific third-party keyring in their test environment when something goes wrong, given that none of the Microsoft code does that.

In the actual use cases, the keyring they are looking for may not even exist in the OS (Container is a perfect example), so nobody is going to throw the expected exception (Which is a totally valid use case based on their doc), and thereby the whatever happens will crash the SDK and not be catched.

Either update the exceptions to catch, or actually throw an exception would be a solution. The implementation should only be a couple lines. I'm not sure why it takes so long.

**Comment by g2vinay** [comment]
Duplicate of https://github.com/Azure/azure-sdk-for-java/issues/42962
