### ISSUE TITLE
AILED com.microsoft.azure.storage.StorageException: Server encountered an internal error. Please try again after some time.

### ISSUE THREAD

**Issue by Akshata17** [Azure/azure-sdk-for-java#32207]
**Query/Question**
Facing this issue from Azure-

Caused by: com.microsoft.azure.storage.StorageException: Server encountered an internal error. Please try again after some time.

		at com.microsoft.azure.storage.StorageException.translateException(StorageException.java:87)

		at com.microsoft.azure.storage.core.ExecutionEngine.executeWithRetry(ExecutionEngine.java:220)

		at com.microsoft.azure.storage.blob.CloudBlobClient.listContainersWithPrefixSegmented(CloudBlobClient.java:348)

		at com.microsoft.azure.storage.blob.CloudBlobClient.listContainersSegmented(CloudBlobClient.java:261)

		at com.vmware.photon.controller.model.adapters.azure.enumeration.AzureStorageEnumerationAdapterServiceV2.lambda$getStorageContainersAndDisks$35(AzureStorageEnumerationAdapterServiceV2.java:1218)

		... 7 more

	Caused by: java.lang.NullPointerException

		at com.microsoft.azure.storage.core.ExecutionEngine.executeWithRetry(ExecutionEngine.java:202)

		... 10 more

***Why is this not a Bug or a feature Request?***
This could be a bug from Azure.

**Setup (please complete the following information if applicable):**
 - IDE: IntelliJ
 - Library/Libraries: CloudBlobClient --> listContainersWithPrefixSegmented()  (azure-storage-8.6.6.jar)
 
 **Information Checklist**
 We are using CloudBlobClient-->listContainersSegmented()-->listContainersWithPrefixSegmented() and then failure happens in ExecutionEngine.executeWithRetry() which caused server error. Could you please help us know what is the cause for this server error from Azure ?

Stacktrace -
Caused by: com.microsoft.azure.storage.StorageException: Server encountered an internal error. Please try again after some time.

		at com.microsoft.azure.storage.StorageException.translateException(StorageException.java:87)

		at com.microsoft.azure.storage.core.ExecutionEngine.executeWithRetry(ExecutionEngine.java:220)

		at com.microsoft.azure.storage.blob.CloudBlobClient.listContainersWithPrefixSegmented(CloudBlobClient.java:348)

		at com.microsoft.azure.storage.blob.CloudBlobClient.listContainersSegmented(CloudBlobClient.java:261)

		at com.vmware.photon.controller.model.adapters.azure.enumeration.AzureStorageEnumerationAdapterServiceV2.lambda$getStorageContainersAndDisks$35(AzureStorageEnumerationAdapterServiceV2.java:1218)

		... 7 more

	Caused by: java.lang.NullPointerException

		at com.microsoft.azure.storage.core.ExecutionEngine.executeWithRetry(ExecutionEngine.java:202)

		... 10 more

**Comment by Akshata17** [comment]
<img width="1728" alt="ExecutionEngine" src="https://user-images.githubusercontent.com/18043958/202693980-0a786557-84b5-4f55-b983-4f9f51599021.png">
<img width="704" alt="NullErrorCode" src="https://user-images.githubusercontent.com/18043958/202694033-6ce7d4cc-ab62-4ca2-8d6d-8cc3d4d6c5f9.png">
<img width="1336" alt="CodeBlockThatHasFault" src="https://user-images.githubusercontent.com/18043958/202694037-9a8cf161-e6c8-41c5-926f-0143f87e6a43.png">


The above screenshots will showcase wherein the NullPointerException is caused -

 if (task.getResult().getStatusCode() == HttpURLConnection.HTTP_NOT_IMPLEMENTED
                            || task.getResult().getStatusCode() == HttpURLConnection.HTTP_VERSION
                            || translatedException.getErrorCode().equals(StorageErrorCodeStrings.INVALID_BLOB_TYPE)) {
                        throw translatedException;
                    }

**Comment by Akshata17** [comment]
Any updates on this issue ?

**Comment by joshfree** [comment]
@jaschrep-msft could you please take a look?

/cc @alzimmermsft
