### ISSUE TITLE
[BUG] com.azure.core.exception.ResourceNotFoundException is thrown during ServiceBusAdministrationClient#getQueueExists execution

### ISSUE THREAD

**Issue by avrilfanomar** [Azure/azure-sdk-for-java#32219]
**Describe the bug**
The com.azure.messaging.servicebus.administration.ServiceBusAdministrationClient#getQueueExists method is throwing ResourceNotFoundException when the queue doesn't exist instead of returning false.
***Exception or Stack Trace***
at com.azure.messaging.servicebus.administration.ServiceBusAdministrationClient.getQueueWithResponse(ServiceBusAdministrationClient.java:682) ~[azure-messaging-servicebus-7.12.1.jar!/:7.12.1]\n
at com.azure.messaging.servicebus.administration.ServiceBusAdministrationClient.getQueueExistsWithResponse(ServiceBusAdministrationClient.java:721) ~[azure-messaging-servicebus-7.12.1.jar!/:7.12.1]\n
at com.azure.messaging.servicebus.administration.ServiceBusAdministrationClient.getQueueExists(ServiceBusAdministrationClient.java:703) ~[azure-messaging-servicebus-7.12.1.jar!/:7.12.1]\n

**To Reproduce**
Invoke ServiceBusAdministrationClient#getQueueExists with the non-existing queue

**Expected behavior**
False is returned

**Setup (please complete the following information):**
Affects 7.12.1 version

**Comment by avrilfanomar** [comment]
same as https://github.com/Azure/azure-sdk-for-java/issues/32220

**Comment by alzimmermsft** [comment]
@ki1729 could you take a look at this

**Comment by ki1729** [comment]
@avrilfanomar Thank you for reporting this! This has been fixed in the latest release v7.13.0. Here is th PR that fixed this problem : https://github.com/Azure/azure-sdk-for-java/pull/31804
