### ISSUE TITLE
[BUG] KeyVaultSecret .getValue() throws com.fasterxml.jackson.databind.exc.MismatchedInputException

### ISSUE THREAD

**Issue by apoguy** [Azure/azure-sdk-for-java#32460]
**Describe the bug**
Trying to get a KeyVault Secret the .getValue() throws com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.lang.String` from Array value (token `JsonToken.START_ARRAY`)

***Exception or Stack Trace***
```
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.lang.String` from Array value (token `JsonToken.START_ARRAY`)
 at [Source: (byte[])"{"value":[{"id":"https://****vault.azure.net/secrets/secret-name","attributes":{"enabled":true,"created":1670301111,"updated":1670301111,"recoveryLevel":"Recoverable+Purgeable","recoverableDays":90},"tags":{}}],"nextLink":null}"; line: 1, column: 10] (through reference chain: com.azure.security.keyvault.secrets.models.KeyVaultSecret["value"])
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1746)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1520)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer._deserializeFromArray(StdDeserializer.java:222)
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:46)
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:11)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4697)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3746)
	at com.azure.core.implementation.jackson.ObjectMapperShim.readValue(ObjectMapperShim.java:224)
	at com.azure.core.util.serializer.JacksonAdapter.lambda$deserialize$8(JacksonAdapter.java:277)
	at com.azure.core.util.serializer.JacksonAdapter.useAccessHelper(JacksonAdapter.java:327)
	at com.azure.core.util.serializer.JacksonAdapter.deserialize(JacksonAdapter.java:275)
	at com.azure.core.implementation.serializer.HttpResponseBodyDecoder.deserialize(HttpResponseBodyDecoder.java:159)
	at com.azure.core.implementation.serializer.HttpResponseBodyDecoder.deserializeBody(HttpResponseBodyDecoder.java:132)
	at com.azure.core.implementation.serializer.HttpResponseBodyDecoder.decodeByteArray(HttpResponseBodyDecoder.java:75)
	... 17 more
```
***Code Snippet***
```
SecretClient secretClient = new SecretClientBuilder()
                .vaultUrl(keyVaultUrl)
                .credential(new DefaultAzureCredentialBuilder().build())
                .buildClient();

secretClient.getSecret(secretName).getValue();
```

**Expected behavior**
Get the secret value as String

**Setup (please complete the following information):**
 - OS: MacOS
 - IDE: IntelliJ
 - Library/Libraries:
     - com.azure:azure-identity:1.7.1
     - com.azure:azure-security-keyvault-secrets:4.5.2
 - Java version: 11

**Comment by chenrujun** [comment]
Hi, @alzimmermsft , could you please help to handle this issue?

**Comment by alzimmermsft** [comment]
@vcolin7 based on the snippet of JSON included in the error message there is a `nextLink` property, is this a new change in the KeyVault client?

**Comment by alzimmermsft** [comment]
@vcolin7 any updates on this? Based on the JSON this looks more like the [Get Secrets](https://learn.microsoft.com/en-us/rest/api/keyvault/secrets/get-secrets/get-secrets?tabs=HTTP#getsecrets) response rather than the [Get Secret](https://learn.microsoft.com/en-us/rest/api/keyvault/secrets/get-secret/get-secret?tabs=HTTP#getsecret) response.

@apoguy, what was the value of `secretName` when the API call was made?

**Comment by apoguy** [comment]
@alzimmermsft I really can't remember, sorry. But I think you could reproduce it using an invalid secret name.

**Comment by vcolin7** [comment]
Yeah, it looks like when we get an empty or null name it's like we were calling `listSettings()`, so the response has an array of secrets we are not expecting and cannot deserialize. I'll bring this up to the team.
