### ISSUE TITLE
secretClient.getSecret throws IllegalAccessException for Key Vault due to Jackson dependency

### ISSUE THREAD

**Issue by mkemmerz** [Azure/azure-sdk-for-java#32546]
**Describe the bug**
jackson-databind causes a linkage error, even if all jackson versions are identical. I checked other github issues to this topic and obviously this seems like a dependency issue. Unfortunately I am not able to get to the core of the issue. In my opinion the dependencies are fine and jackson shouldn't have any conflicting versions :(

GH issues I checked: 
- https://github.com/Azure/azure-sdk-for-java/issues/32460
- https://github.com/Azure/azure-sdk-for-java/issues/30554
- https://github.com/FasterXML/jackson-dataformat-xml/issues/471

***Exception or Stack Trace***
```
Caused by: java.lang.LinkageError: 
loader constraint violation: when resolving method 
'com.fasterxml.jackson.databind.introspect.AccessorNamingStrategy$Provider com.fasterxml.jackson.databind.cfg.MapperConfig.getAccessorNaming()' 
the class loader 'bootstrap' of the current class, java/lang/Object, and the 
class loader org.springframework.boot.loader.LaunchedURLClassLoader @ee8e7ff for the 
method's defining class, com/fasterxml/jackson/databind/cfg/MapperConfig, have different 
Class objects for the type com/fasterxml/jackson/databind/introspect/AccessorNamingStrategy$Provider used in the 
signature (java.lang.Object is in module java.base of loader 'bootstrap'; com.fasterxml.jackson.databind.cfg.MapperConfig is 
in unnamed module of loader org.springframework.boot.loader.LaunchedURLClassLoader @ee8e7ff, parent loader 'app')

com.azure.core.implementation.jackson.JacksonVersion - Package versions: jackson-core=2.13.4, jackson-databind=2.13.4, jackson-dataformat-xml=2.13.4, jackson-datatype-jsr310=2.13.4, azure-core=1.34.0, Troubleshooting version conflicts: https://aka.ms/azsdk/java/dependency/troubleshoot

DEBUG com.azure.core.implementation.jackson.MemberNameConverterImpl - Failed to retrieve MethodHandles used to get naming strategy. Falling back to BeanUtils. Please consider updating your Jackson dependencies to at least version 2.12
java.lang.IllegalAccessException: no such method: com.fasterxml.jackson.databind.cfg.MapperConfig.getAccessorNaming()Provider/invokeVirtual
	at java.base/java.lang.invoke.MemberName.makeAccessException(Unknown Source)
	at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(Unknown Source)
	at java.base/java.lang.invoke.MethodHandles$Lookup.resolveOrFail(Unknown Source)
	at java.base/java.lang.invoke.MethodHandles$Lookup.findVirtual(Unknown Source)
	at com.azure.core.implementation.jackson.MemberNameConverterImpl.<clinit>(MemberNameConverterImpl.java:57)
	at com.azure.core.implementation.jackson.ObjectMapperShim.<init>(ObjectMapperShim.java:148)
	at com.azure.core.implementation.jackson.ObjectMapperShim.createPrettyPrintMapper(ObjectMapperShim.java:122)
	at com.azure.core.http.policy.HttpLoggingPolicy.<clinit>(HttpLoggingPolicy.java:47)
	at com.azure.security.keyvault.secrets.SecretClientBuilder.buildInnerClient(SecretClientBuilder.java:225)
	at com.azure.security.keyvault.secrets.SecretClientBuilder.buildClient(SecretClientBuilder.java:145)
	at com.schaeffler.hello.helloworld.HelloWorldApplication.main(HelloWorldApplication.java:33)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
Caused by: java.lang.LinkageError: loader constraint violation: when resolving method 'com.fasterxml.jackson.databind.introspect.AccessorNamingStrategy$Provider com.fasterxml.jackson.databind.cfg.MapperConfig.getAccessorNaming()' the class loader 'bootstrap' of the current class, java/lang/Object, and the class loader org.springframework.boot.loader.LaunchedURLClassLoader @536b71b4 for the method's defining class, com/fasterxml/jackson/databind/cfg/MapperConfig, have different Class objects for the type com/fasterxml/jackson/databind/introspect/AccessorNamingStrategy$Provider used in the signature (java.lang.Object is in module java.base of loader 'bootstrap'; com.fasterxml.jackson.databind.cfg.MapperConfig is in unnamed module of loader org.springframework.boot.loader.LaunchedURLClassLoader @536b71b4, parent loader 'app')
	at java.base/java.lang.invoke.MethodHandleNatives.resolve(Native Method)
	at java.base/java.lang.invoke.MemberName$Factory.resolve(Unknown Source)
	... 18 common frames omitted
```

mvn dependency:tree:
```
[INFO] --- maven-dependency-plugin:3.3.0:tree (default-cli) @ hello-world ---
[INFO] com.test.hello:hello-world:jar:0.0.1-SNAPSHOT
[INFO] +- org.springframework.boot:spring-boot-starter-web:jar:2.7.6:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter:jar:2.7.6:compile
[INFO] |  |  +- org.springframework.boot:spring-boot:jar:2.7.6:compile
[INFO] |  |  +- org.springframework.boot:spring-boot-autoconfigure:jar:2.7.6:compile
[INFO] |  |  +- org.springframework.boot:spring-boot-starter-logging:jar:2.7.6:compile
[INFO] |  |  |  +- ch.qos.logback:logback-classic:jar:1.2.11:compile
[INFO] |  |  |  |  \- ch.qos.logback:logback-core:jar:1.2.11:compile
[INFO] |  |  |  +- org.apache.logging.log4j:log4j-to-slf4j:jar:2.17.2:compile
[INFO] |  |  |  |  \- org.apache.logging.log4j:log4j-api:jar:2.17.2:compile
[INFO] |  |  |  \- org.slf4j:jul-to-slf4j:jar:1.7.36:compile
[INFO] |  |  +- jakarta.annotation:jakarta.annotation-api:jar:1.3.5:compile
[INFO] |  |  \- org.yaml:snakeyaml:jar:1.30:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-json:jar:2.7.6:compile
[INFO] |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jdk8:jar:2.13.4:compile
[INFO] |  |  \- com.fasterxml.jackson.module:jackson-module-parameter-names:jar:2.13.4:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-tomcat:jar:2.7.6:compile
[INFO] |  |  +- org.apache.tomcat.embed:tomcat-embed-core:jar:9.0.69:compile
[INFO] |  |  +- org.apache.tomcat.embed:tomcat-embed-el:jar:9.0.69:compile
[INFO] |  |  \- org.apache.tomcat.embed:tomcat-embed-websocket:jar:9.0.69:compile
[INFO] |  +- org.springframework:spring-web:jar:5.3.24:compile
[INFO] |  |  \- org.springframework:spring-beans:jar:5.3.24:compile
[INFO] |  \- org.springframework:spring-webmvc:jar:5.3.24:compile
[INFO] |     +- org.springframework:spring-context:jar:5.3.24:compile
[INFO] |     \- org.springframework:spring-expression:jar:5.3.24:compile
[INFO] +- org.springframework.boot:spring-boot-starter-data-jpa:jar:2.7.6:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-jdbc:jar:2.7.6:compile
[INFO] |  |  +- com.zaxxer:HikariCP:jar:4.0.3:compile
[INFO] |  |  \- org.springframework:spring-jdbc:jar:5.3.24:compile
[INFO] |  +- jakarta.transaction:jakarta.transaction-api:jar:1.3.3:compile
[INFO] |  +- jakarta.persistence:jakarta.persistence-api:jar:2.2.3:compile
[INFO] |  +- org.hibernate:hibernate-core:jar:5.6.14.Final:compile
[INFO] |  |  +- org.jboss.logging:jboss-logging:jar:3.4.3.Final:compile
[INFO] |  |  +- net.bytebuddy:byte-buddy:jar:1.12.19:compile
[INFO] |  |  +- antlr:antlr:jar:2.7.7:compile
[INFO] |  |  +- org.jboss:jandex:jar:2.4.2.Final:compile
[INFO] |  |  +- com.fasterxml:classmate:jar:1.5.1:compile
[INFO] |  |  +- org.hibernate.common:hibernate-commons-annotations:jar:5.1.2.Final:compile
[INFO] |  |  \- org.glassfish.jaxb:jaxb-runtime:jar:2.3.7:compile
[INFO] |  |     +- org.glassfish.jaxb:txw2:jar:2.3.7:compile
[INFO] |  |     +- com.sun.istack:istack-commons-runtime:jar:3.0.12:compile
[INFO] |  |     \- com.sun.activation:jakarta.activation:jar:1.2.2:runtime
[INFO] |  +- org.springframework.data:spring-data-jpa:jar:2.7.6:compile
[INFO] |  |  +- org.springframework.data:spring-data-commons:jar:2.7.6:compile
[INFO] |  |  +- org.springframework:spring-orm:jar:5.3.24:compile
[INFO] |  |  \- org.springframework:spring-tx:jar:5.3.24:compile
[INFO] |  \- org.springframework:spring-aspects:jar:5.3.24:compile
[INFO] +- org.springframework.boot:spring-boot-starter-test:jar:2.7.6:test
[INFO] |  +- org.springframework.boot:spring-boot-test:jar:2.7.6:test
[INFO] |  +- org.springframework.boot:spring-boot-test-autoconfigure:jar:2.7.6:test
[INFO] |  +- com.jayway.jsonpath:json-path:jar:2.7.0:test
[INFO] |  +- jakarta.xml.bind:jakarta.xml.bind-api:jar:2.3.3:compile
[INFO] |  |  \- jakarta.activation:jakarta.activation-api:jar:1.2.2:compile
[INFO] |  +- org.assertj:assertj-core:jar:3.22.0:test
[INFO] |  +- org.hamcrest:hamcrest:jar:2.2:test
[INFO] |  +- org.junit.jupiter:junit-jupiter:jar:5.8.2:test
[INFO] |  |  +- org.junit.jupiter:junit-jupiter-api:jar:5.8.2:test
[INFO] |  |  |  +- org.opentest4j:opentest4j:jar:1.2.0:test
[INFO] |  |  |  +- org.junit.platform:junit-platform-commons:jar:1.8.2:test
[INFO] |  |  |  \- org.apiguardian:apiguardian-api:jar:1.1.2:test
[INFO] |  |  +- org.junit.jupiter:junit-jupiter-params:jar:5.8.2:test
[INFO] |  |  \- org.junit.jupiter:junit-jupiter-engine:jar:5.8.2:test
[INFO] |  |     \- org.junit.platform:junit-platform-engine:jar:1.8.2:test
[INFO] |  +- org.mockito:mockito-core:jar:4.5.1:test
[INFO] |  |  +- net.bytebuddy:byte-buddy-agent:jar:1.12.19:test
[INFO] |  |  \- org.objenesis:objenesis:jar:3.2:test
[INFO] |  +- org.mockito:mockito-junit-jupiter:jar:4.5.1:test
[INFO] |  +- org.skyscreamer:jsonassert:jar:1.5.1:test
[INFO] |  |  \- com.vaadin.external.google:android-json:jar:0.0.20131108.vaadin1:test
[INFO] |  +- org.springframework:spring-core:jar:5.3.24:compile
[INFO] |  |  \- org.springframework:spring-jcl:jar:5.3.24:compile
[INFO] |  +- org.springframework:spring-test:jar:5.3.24:test
[INFO] |  \- org.xmlunit:xmlunit-core:jar:2.9.0:test
[INFO] +- org.springframework.security:spring-security-test:jar:5.7.5:test
[INFO] |  +- org.springframework.security:spring-security-core:jar:5.7.5:compile
[INFO] |  |  \- org.springframework.security:spring-security-crypto:jar:5.7.5:compile
[INFO] |  \- org.springframework.security:spring-security-web:jar:5.7.5:compile
[INFO] +- org.springframework.boot:spring-boot-starter-security:jar:2.7.6:compile
[INFO] |  +- org.springframework:spring-aop:jar:5.3.24:compile
[INFO] |  \- org.springframework.security:spring-security-config:jar:5.7.5:compile
[INFO] +- org.springframework.boot:spring-boot-starter-oauth2-resource-server:jar:2.7.6:compile
[INFO] |  +- org.springframework.security:spring-security-oauth2-resource-server:jar:5.7.5:compile
[INFO] |  |  \- org.springframework.security:spring-security-oauth2-core:jar:5.7.5:compile
[INFO] |  \- org.springframework.security:spring-security-oauth2-jose:jar:5.7.5:compile
[INFO] |     \- com.nimbusds:nimbus-jose-jwt:jar:9.22:compile
[INFO] +- org.springframework.boot:spring-boot-starter-oauth2-client:jar:2.7.6:compile
[INFO] |  \- org.springframework.security:spring-security-oauth2-client:jar:5.7.5:compile
[INFO] +- org.springframework.boot:spring-boot-starter-aop:jar:2.7.6:compile
[INFO] |  \- org.aspectj:aspectjweaver:jar:1.9.7:compile
[INFO] +- io.opentelemetry:opentelemetry-api:jar:1.20.1:compile
[INFO] |  \- io.opentelemetry:opentelemetry-context:jar:1.20.1:compile
[INFO] +- org.springframework.boot:spring-boot-starter-actuator:jar:2.7.6:compile
[INFO] |  +- org.springframework.boot:spring-boot-actuator-autoconfigure:jar:2.7.6:compile
[INFO] |  |  \- org.springframework.boot:spring-boot-actuator:jar:2.7.6:compile
[INFO] |  \- io.micrometer:micrometer-core:jar:1.9.6:compile
[INFO] |     +- org.hdrhistogram:HdrHistogram:jar:2.1.12:compile
[INFO] |     \- org.latencyutils:LatencyUtils:jar:2.0.3:runtime
[INFO] +- com.h2database:h2:jar:2.1.214:compile
[INFO] +- org.projectlombok:lombok:jar:1.18.24:provided
[INFO] +- io.netty:netty-resolver-dns-native-macos:jar:osx-aarch_64:4.1.85.Final:runtime
[INFO] |  \- io.netty:netty-resolver-dns-classes-macos:jar:4.1.85.Final:compile
[INFO] |     +- io.netty:netty-common:jar:4.1.85.Final:compile
[INFO] |     +- io.netty:netty-resolver-dns:jar:4.1.85.Final:compile
[INFO] |     |  +- io.netty:netty-resolver:jar:4.1.85.Final:compile
[INFO] |     |  +- io.netty:netty-transport:jar:4.1.85.Final:compile
[INFO] |     |  +- io.netty:netty-codec:jar:4.1.85.Final:compile
[INFO] |     |  \- io.netty:netty-codec-dns:jar:4.1.85.Final:compile
[INFO] |     \- io.netty:netty-transport-native-unix-common:jar:4.1.85.Final:compile
[INFO] +- com.azure:azure-security-keyvault-secrets:jar:4.5.2:compile
[INFO] |  \- com.azure:azure-core-http-netty:jar:1.12.7:compile
[INFO] |     +- io.netty:netty-handler:jar:4.1.85.Final:compile
[INFO] |     +- io.netty:netty-handler-proxy:jar:4.1.85.Final:compile
[INFO] |     |  \- io.netty:netty-codec-socks:jar:4.1.85.Final:compile
[INFO] |     +- io.netty:netty-buffer:jar:4.1.85.Final:compile
[INFO] |     +- io.netty:netty-codec-http:jar:4.1.85.Final:compile
[INFO] |     +- io.netty:netty-codec-http2:jar:4.1.85.Final:compile
[INFO] |     +- io.netty:netty-transport-native-epoll:jar:linux-x86_64:4.1.85.Final:compile
[INFO] |     |  \- io.netty:netty-transport-classes-epoll:jar:4.1.85.Final:compile
[INFO] |     +- io.netty:netty-transport-native-kqueue:jar:osx-x86_64:4.1.85.Final:compile
[INFO] |     |  \- io.netty:netty-transport-classes-kqueue:jar:4.1.85.Final:compile
[INFO] |     +- io.netty:netty-tcnative-boringssl-static:jar:2.0.54.Final:compile
[INFO] |     |  +- io.netty:netty-tcnative-classes:jar:2.0.54.Final:compile
[INFO] |     |  +- io.netty:netty-tcnative-boringssl-static:jar:linux-x86_64:2.0.54.Final:compile
[INFO] |     |  +- io.netty:netty-tcnative-boringssl-static:jar:linux-aarch_64:2.0.54.Final:compile
[INFO] |     |  +- io.netty:netty-tcnative-boringssl-static:jar:osx-x86_64:2.0.54.Final:compile
[INFO] |     |  +- io.netty:netty-tcnative-boringssl-static:jar:osx-aarch_64:2.0.54.Final:compile
[INFO] |     |  \- io.netty:netty-tcnative-boringssl-static:jar:windows-x86_64:2.0.54.Final:compile
[INFO] |     \- io.projectreactor.netty:reactor-netty-http:jar:1.0.25:compile
[INFO] |        +- io.netty:netty-resolver-dns-native-macos:jar:osx-x86_64:4.1.85.Final:compile
[INFO] |        \- io.projectreactor.netty:reactor-netty-core:jar:1.0.25:compile
[INFO] +- com.fasterxml.jackson.core:jackson-databind:jar:2.13.4:compile
[INFO] |  \- com.fasterxml.jackson.core:jackson-annotations:jar:2.13.4:compile
[INFO] +- com.fasterxml.jackson.core:jackson-core:jar:2.13.4:compile
[INFO] +- com.azure:azure-core:jar:1.34.0:compile
[INFO] |  +- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.13.4:compile
[INFO] |  +- com.fasterxml.jackson.dataformat:jackson-dataformat-xml:jar:2.13.4:compile
[INFO] |  |  \- org.codehaus.woodstox:stax2-api:jar:4.2.1:compile
[INFO] |  +- com.fasterxml.woodstox:woodstox-core:jar:6.4.0:compile
[INFO] |  +- org.slf4j:slf4j-api:jar:1.7.36:compile
[INFO] |  \- io.projectreactor:reactor-core:jar:3.4.25:compile
[INFO] |     \- org.reactivestreams:reactive-streams:jar:1.0.4:compile
[INFO] +- com.azure:azure-identity:jar:1.7.1:compile
[INFO] |  +- com.microsoft.azure:msal4j-persistence-extension:jar:1.1.0:compile
[INFO] |  |  \- net.java.dev.jna:jna:jar:5.5.0:compile
[INFO] |  \- net.java.dev.jna:jna-platform:jar:5.6.0:compile
[INFO] \- com.microsoft.azure:msal4j:jar:1.13.3:compile
[INFO]    +- com.nimbusds:oauth2-oidc-sdk:jar:9.35:compile
[INFO]    |  +- com.github.stephenc.jcip:jcip-annotations:jar:1.0-1:compile
[INFO]    |  +- com.nimbusds:content-type:jar:2.2:compile
[INFO]    |  \- com.nimbusds:lang-tag:jar:1.6:compile
[INFO]    \- net.minidev:json-smart:jar:2.4.8:compile
[INFO]       \- net.minidev:accessors-smart:jar:2.4.8:compile
[INFO]          \- org.ow2.asm:asm:jar:9.1:compile

```

**To Reproduce**

***Code Snippet**
I am using the workload identity for Azure Kubernetes Service to access the Key Vault. `WorkloadIdentityTokenProvider` is the same as the example in the workload-identity Github repository: https://github.com/Azure/azure-workload-identity/tree/main/examples/msal-java

```
    String keyvaultURL = "https://xxx.vault.azure.net/";
    String secretName = "test";

    SecretClient secretClient = new SecretClientBuilder()
      .vaultUrl(keyvaultURL)
      .credential(new WorkloadIdentityTokenProvider())
      .buildClient();

    KeyVaultSecret secret = secretClient.getSecret(secretName);
    System.out.printf("successfully got secret, secret=%s", secret.getValue());
```

**Comment by chenrujun** [comment]
Hi, @alzimmermsft , could you please help to handle this issue?

**Comment by alzimmermsft** [comment]
Thanks for filing this @mkemmerz, your Jackson dependencies look correct, so it's a bit odd that there is a `LinkageError` being thrown. You did mention the usage of Azure Kubernetes Service, which I don't have much experience with, is this a managed runtime which may include its own dependencies on the classpath?

**Comment by alzimmermsft** [comment]
@mkemmerz I've merged a change which should prevent this code path from being executed in a strong majority of cases which should resolve what you're seeing based on the call stack provided. I'm going to continue doing some more investigation in this area to further harden the functionality and have a question about your usage. In your application are you shading/relocating dependencies when creating the JAR being used in AKS?

**Comment by mkemmerz** [comment]
Hey @alzimmermsft! Thanks for the effort you are putting into this issue! Unfortunately I am no longer working on the project where I encountered this issue. Therefore I won't be able to test it the next months.

In regards to your question. The only thing I noticed is that an Azure Application Insights Agent JAR is moved into the target folder.
