### ISSUE TITLE
[BUG]  Indefinite lease on a blob without performing the lease operation.

### ISSUE THREAD

**Issue by hawk-pawel-polak** [Azure/azure-sdk-for-java#32629]
**Describe the bug**
We have faced an indefinite lease on a blob without performing the lease operation. We are uploading a blob and then overriding that and nowhere Lease mechanism is being programmatically used. 

***Exception or Stack Trace***
```
j.u.c.CompletionException: tech.hawkai.utils.cloudstorage.exception.CloudStorageBlobException: java.util.concurrent.CompletionException: com.azure.storage.blob.models.BlobStorageException: Status code 412, "<?xml version="1.0" encoding="utf-8"?><Error><Code>LeaseIdMissing</Code><Message>There is currently a lease on the blob and no lease ID was specified in the request.
RequestId:02c59ab4-701e-0075-7db2-0fec32000000
Time:2022-12-14T11:52:36.5923103Z</Message></Error>"
	at j.u.c.CompletableFuture.encodeThrowable(Unknown Source)
	at j.u.c.CompletableFuture.completeThrowable(Unknown Source)
	at j.u.c.CompletableFuture.uniExceptionally(Unknown Source)
	at j.u.c.CompletableFuture.uniExceptionallyStage(Unknown Source)
	at j.u.c.CompletableFuture.exceptionally(Unknown Source)
	at t.h.u.c.s.BlobStorage.putObject(BlobStorage.java:50)
	at t.h.c.s.ConfigurationBucketRetryableService.putAndRetry(ConfigurationBucketRetryableService.java:172)
	at t.h.c.s.ConfigurationBucketRetryableService$$FastClassBySpringCGLIB$$955de141.invoke(<generated>)
	... 4 frames excluded
	at o.s.r.i.RetryOperationsInterceptor$1.doWithRetry(RetryOperationsInterceptor.java:97)
	at o.s.r.s.RetryTemplate.doExecute(RetryTemplate.java:329)
	... 44 frames truncated
Caused by: t.h.u.c.e.CloudStorageBlobException: java.util.concurrent.CompletionException: com.azure.storage.blob.models.BlobStorageException: Status code 412, "<?xml version="1.0" encoding="utf-8"?><Error><Code>LeaseIdMissing</Code><Message>There is currently a lease on the blob and no lease ID was specified in the request.
RequestId:02c59ab4-701e-0075-7db2-0fec32000000
Time:2022-12-14T11:52:36.5923103Z</Message></Error>"
	at t.h.u.c.s.BlobStorage.createCloudStorageBlobException(BlobStorage.java:129)
	at t.h.u.c.s.BlobStorage.lambda$putObject$3(BlobStorage.java:51)
	... 52 common frames omitted
Caused by: j.u.c.CompletionException: com.azure.storage.blob.models.BlobStorageException: Status code 412, "<?xml version="1.0" encoding="utf-8"?><Error><Code>LeaseIdMissing</Code><Message>There is currently a lease on the blob and no lease ID was specified in the request.
RequestId:02c59ab4-701e-0075-7db2-0fec32000000
Time:2022-12-14T11:52:36.5923103Z</Message></Error>"
	at j.u.c.CompletableFuture.encodeThrowable(Unknown Source)
	at j.u.c.CompletableFuture.uniApplyNow(Unknown Source)
	at j.u.c.CompletableFuture.uniApplyStage(Unknown Source)
	at j.u.c.CompletableFuture.thenApply(Unknown Source)
	at t.h.u.c.s.BlobStorage.putObject(BlobStorage.java:41)
	... 48 common frames omitted
Caused by: c.a.s.b.m.BlobStorageException: Status code 412, "<?xml version="1.0" encoding="utf-8"?><Error><Code>LeaseIdMissing</Code><Message>There is currently a lease on the blob and no lease ID was specified in the request.
RequestId:02c59ab4-701e-0075-7db2-0fec32000000
Time:2022-12-14T11:52:36.5923103Z</Message></Error>"
	at j.l.i.MethodHandle.invokeWithArguments(Unknown Source)
	at c.a.c.i.h.r.ResponseExceptionConstructorCache.invoke(ResponseExceptionConstructorCache.java:56)
	at c.a.c.i.h.r.RestProxyBase.instantiateUnexpectedException(RestProxyBase.java:378)
	at c.a.c.i.h.r.AsyncRestProxy.lambda$ensureExpectedStatus$1(AsyncRestProxy.java:116)
	at r.c.p.FluxMap$MapSubscriber.onNext(FluxMap.java:106)
	at r.c.p.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:130)
	at r.c.p.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:126)
	at r.c.p.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:220)
	at r.c.p.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:130)
	at r.c.p.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:191)
	... 40 frames truncated
	Suppressed: java.lang.Exception: #block terminated with an error
		at r.c.p.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
		at r.c.publisher.Mono.block(Mono.java:1707)
		at c.a.s.c.i.StorageImplUtils.blockWithOptionalTimeout(StorageImplUtils.java:191)
		at c.a.s.b.s.BlockBlobClient.uploadWithResponse(BlockBlobClient.java:421)
		at c.a.s.b.s.BlockBlobClient.uploadWithResponse(BlockBlobClient.java:363)
		at c.a.s.b.s.BlockBlobClient.upload(BlockBlobClient.java:297)
		at t.h.u.c.s.BlobStorage.lambda$putObject$2(BlobStorage.java:45)
		at j.u.c.CompletableFuture.uniApplyNow(Unknown Source)
		at j.u.c.CompletableFuture.uniApplyStage(Unknown Source)
		at j.u.c.CompletableFuture.thenApply(Unknown Source)
		... 49 frames truncated
```

**To Reproduce**
We do not know how to reproduce that.

***Code Snippet***
```java
try (InputStream dataStream = new ByteArrayInputStream(request.getObjectContent().getBytes())) {
    BlockBlobItem blockBlobItem = blockBlobClient.upload(dataStream, request.getObjectContent().getContentLength(), true);
    return blockBlobItem.getETag();
} catch (IOException e) {
    throw createCloudStorageBlobException(e);
}
```

**Expected behavior**
Lease should not be automatically acquired for indefinite time. Or there should be an option to acquire lease for specific time (as default). Library should not do that behind the scenes. 

**Screenshots**
Here you can see that there was a moment when many leases has been acquired but none of them released. Then app started to work as normal. 
<img width="408" alt="MicrosoftTeams-image (2)" src="https://user-images.githubusercontent.com/108471293/208118657-d04a20e3-6c38-4573-87c2-cc92206ba6a5.png">
<img width="395" alt="MicrosoftTeams-image (1)" src="https://user-images.githubusercontent.com/108471293/208118660-3d66ab5d-7a52-418c-bc1e-39b52905e157.png">

**Setup (please complete the following information):**
 - OS: Java / Linux
 - IDE: IntelliJ
 - Library/Libraries: com.azure:azure-storage-blob:12.18.0
 - Java version: 17
 - App Server/Environment: Tomcat
 - Frameworks: Spring Boot

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**
It is highly unlikely that somebody clicked 10 leases in similar period of time. Plus we do not use lease operations. 

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by alzimmermsft** [comment]
Thanks for filing this issue @hawk-pawel-polak.

Are there any other applications or services that have access to the blobs being affected with this mysterious lease? Walking through the call chain based on your code snippet there is never a called made to lease the blob as part of upload.

**Comment by hawk-pawel-polak** [comment]
Unfortunately no - we triple checked that. The only way to reproduce it is to go to UI and acquire lease manually - which we estimated that is very unlikely because: 

1) only few people has access to Azure Portal
2) most of them are developers and non developers probably are scared to touch anything
3) our folder structure is a bit random because we create a directory with generated UUID for every client and file that we had issues is inside that folder, so it is very unlikely that someone intentionally will go to that folder and lock that particular file.

**Comment by ibrahimrabab** [comment]
Hi @hawk-pawel-polak 
Following up on this thread. Is this still an issue you're facing?

**Comment by hawk-pawel-polak** [comment]
We do not because we have implemented automatic lease break if it has been sitting longer than certain period of time.

**Comment by ibrahimrabab** [comment]
@hawk-pawel-polak Great to hear! We'll go ahead and close this issue. If you have any questions, please feel free to reach out again.
