### ISSUE TITLE
Unable to send a simple event to Azure Event Hub

### ISSUE THREAD

**Issue by sorinache** [Azure/azure-sdk-for-java#32658]
Hello,

I'm trying to send a simple string to one Azure Event Hub instance using azure-sdk. 

Code snippet: 

```java
    public void produceMessage(final BaseMessage message) {
        final EventData eventData = new EventData(message.toJsonString());

        EventHubProducerClient producer = this.eventHubClientBuilder.getEventHubProducer();
        EventDataBatch eventDataBatch = producer.createBatch();

        if (!eventDataBatch.tryAdd(eventData)){
            producer.send(eventDataBatch);
            producer.close();
        }
    }


    public EventHubProducerClient getEventHubProducer(){
        return super.credential(configurationService.getConfiguration().getString(.eventhub.client.namespace"),
                configurationService.getConfiguration().getString("eventhub.client.topic"),
                eventHubClientCredential.build()).buildProducerClient();
    }
```

This are my configures dependencies :

```xml
<dependencies>
		<!-- https://mvnrepository.com/artifact/com.microsoft.azure/msal4j -->
		<dependency>
			<groupId>com.microsoft.azure</groupId>
			<artifactId>msal4j</artifactId>
			<version>1.13.3</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/com.nimbusds/oauth2-oidc-sdk -->
		<dependency>
			<groupId>com.nimbusds</groupId>
			<artifactId>oauth2-oidc-sdk</artifactId>
			<version>10.1</version>
			<scope>runtime</scope>
		</dependency>
		<!-- https://mvnrepository.com/artifact/com.nimbusds/content-type -->
		<dependency>
			<groupId>com.nimbusds</groupId>
			<artifactId>content-type</artifactId>
			<version>2.2</version>
		</dependency>

		<!-- https://mvnrepository.com/artifact/org.apache.qpid/proton-j -->
		<dependency>
			<groupId>org.apache.qpid</groupId>
			<artifactId>proton-j</artifactId>
			<version>0.34.0</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/com.fasterxml.jackson.datatype/jackson-datatype-jsr310 -->
		<dependency>
			<groupId>com.fasterxml.jackson.datatype</groupId>
			<artifactId>jackson-datatype-jsr310</artifactId>
			<version>2.14.1</version>
		</dependency>

		 <!--https://mvnrepository.com/artifact/com.azure/azure-messaging-eventhubs -->
		<dependency>
			<groupId>com.azure</groupId>
			<artifactId>azure-messaging-eventhubs</artifactId>
			<version>5.15.0</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/com.azure/azure-identity -->
		<dependency>
			<groupId>com.azure</groupId>
			<artifactId>azure-identity</artifactId>
			<version>1.7.2</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/com.azure/azure-core -->
		<dependency>
			<groupId>com.azure</groupId>
			<artifactId>azure-core</artifactId>
			<version>1.34.0</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/com.azure/azure-core-amqp -->
       <dependency>
           <groupId>com.azure</groupId>
           <artifactId>azure-core-amqp</artifactId>
           <version>2.8.0</version>
       </dependency>
   </dependencies>
```

when I'm running the code to send the event I always get below error on the producer.createBatch() line:

```
ERROR [reactor-executor-1] [Operators] Operator called default onErrorDropped
reactor.core.Exceptions$ErrorCallbackNotImplemented: com.azure.core.amqp.exception.AmqpException: errorContext[NAMESPACE: ".......servicebus.windows.net". ERROR CONTEXT: N/A]
Caused by: com.azure.core.amqp.exception.AmqpException: errorContext[NAMESPACE: "........servicebus.windows.net". ERROR CONTEXT: N/A]
	at com.azure.core.amqp.implementation.ExceptionUtil.toException(ExceptionUtil.java:85) ~[azure-core-amqp-2.8.0.jar:2.8.0]
	at com.azure.core.amqp.implementation.handler.ConnectionHandler.notifyErrorContext(ConnectionHandler.java:351) ~[azure-core-amqp-2.8.0.jar:2.8.0]
	at com.azure.core.amqp.implementation.handler.ConnectionHandler.onTransportError(ConnectionHandler.java:253) ~[azure-core-amqp-2.8.0.jar:2.8.0]
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:191) ~[proton-j-0.34.0.jar:?]
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108) ~[proton-j-0.34.0.jar:?]
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324) ~[proton-j-0.34.0.jar:?]
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291) ~[proton-j-0.34.0.jar:?]
	at com.azure.core.amqp.implementation.ReactorExecutor.run(ReactorExecutor.java:91) ~[azure-core-amqp-2.8.0.jar:2.8.0]
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68) [reactor-core-3.4.6.jar:3.4.6]
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28) [reactor-core-3.4.6.jar:3.4.6]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

Ignore the dots from namespace, I removed it on purpose. 

What I'm doing wrong here ? I just tried to follow the example from official documentation: https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/eventhubs/azure-messaging-eventhubs/README.md 

Thanks,
Sorin

**Comment by sorinache** [comment]
Hello,

I managed to fix this issue, it was a problem related to some dependencies from the platform where I was running the app.  it was using an older version of reactore-core and this was causing the issue.  I upgrade it to 3.5.0 and everything works now. Thank you
