### ISSUE TITLE
[FEATURE REQ] Improve exception thrown on bad credentials

### ISSUE THREAD

**Issue by DaveCTurner** [Azure/azure-sdk-for-java#32689]
**Is your feature request related to a problem? Please describe.**

An Elasticsearch user (version 8.2.2) supplied the Azure snapshot repository plugin with invalid credentials. The exception returned by the Azure SDK (version 12.9.0) was `java.lang.IllegalArgumentException: Illegal base64 character 2d` which did not lead them towards an actionable remedy, or even really to indicate that the problem was related to the credentials they had supplied. It would be great if the thrown exception included more context to guide users more directly towards a solution.

**Describe the solution you'd like**

We'd like exceptions related to bad credentials like this one to be wrapped up with some more useful context, indicating that the SDK encountered a problem related to credentials.

**Describe alternatives you've considered**

Elasticsearch could conceivably catch and wrap this exception in the calling code instead, but it would be difficult to get this right. Elasticsearch doesn't really have a way to know that this particular exception was related to auth, at least not in a manner which would be robust to future SDK changes.

**Additional context**

<details>
<summary>Click to expand exceptions and stack trace</summary>

```
[2022-12-21T01:30:00,020][WARN ][o.e.s.SnapshotShardsService] [confront-prd-elk-3] [[confront-client-logs-8f07449f-ede2-4fba-b070-1bfa7dc00555-2022.10.24][1]][confront_prd_azure_snapshot_repo:daily-2022.12.21-jsyjr-1ur_2d1ctgelp9dg/D-MlRQh7RF6VBLQ1YoeQbQ] failed to snapshot shard
org.elasticsearch.index.snapshots.IndexShardSnapshotFailedException: failed to list blobs
        at org.elasticsearch.repositories.blobstore.BlobStoreRepository.snapshotShard(BlobStoreRepository.java:2647) [elasticsearch-8.2.2.jar:8.2.2]
        at org.elasticsearch.snapshots.SnapshotShardsService.snapshot(SnapshotShardsService.java:360) [elasticsearch-8.2.2.jar:8.2.2]
        at org.elasticsearch.snapshots.SnapshotShardsService.lambda$startNewShards$1(SnapshotShardsService.java:265) [elasticsearch-8.2.2.jar:8.2.2]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:714) [elasticsearch-8.2.2.jar:8.2.2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.io.IOException: Unable to list blobs by prefix [index-] for path elasticsearch/snapshots/confront_prd/indices/ImdxduPFTiKHQZ2bCn1wpQ/1/
        at org.elasticsearch.repositories.azure.AzureBlobStore.listBlobsByPrefix(AzureBlobStore.java:339) ~[?:?]
        at org.elasticsearch.repositories.azure.AzureBlobContainer.listBlobsByPrefix(AzureBlobContainer.java:135) ~[?:?]
        at org.elasticsearch.repositories.blobstore.BlobStoreRepository.snapshotShard(BlobStoreRepository.java:2645) ~[elasticsearch-8.2.2.jar:8.2.2]
        ... 6 more
Caused by: java.lang.IllegalArgumentException: Illegal base64 character 2d
        at java.util.Base64$Decoder.decode0(Base64.java:848) ~[?:?]
        at java.util.Base64$Decoder.decode(Base64.java:566) ~[?:?]
        at java.util.Base64$Decoder.decode(Base64.java:589) ~[?:?]
        at com.azure.storage.common.implementation.StorageImplUtils.computeHMac256(StorageImplUtils.java:174) ~[?:?]
        at com.azure.storage.common.StorageSharedKeyCredential.generateAuthorizationHeader(StorageSharedKeyCredential.java:96) ~[?:?]
        at com.azure.storage.common.policy.StorageSharedKeyCredentialPolicy.process(StorageSharedKeyCredentialPolicy.java:37) ~[?:?]
        at com.azure.core.http.HttpPipelineNextPolicy.process(HttpPipelineNextPolicy.java:46) ~[?:?]
        at com.azure.core.http.policy.AddDatePolicy.lambda$process$0(AddDatePolicy.java:29) ~[?:?]
        at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44) ~[?:?]
        at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[?:?]
        at reactor.core.publisher.MonoDelaySubscription.accept(MonoDelaySubscription.java:52) ~[?:?]
        at reactor.core.publisher.MonoDelaySubscription.accept(MonoDelaySubscription.java:33) ~[?:?]
        at reactor.core.publisher.FluxDelaySubscription$DelaySubscriptionOtherSubscriber.onNext(FluxDelaySubscription.java:123) ~[?:?]
        at reactor.core.publisher.MonoDelay$MonoDelayRunnable.run(MonoDelay.java:117) ~[?:?]
        at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68) ~[?:?]
        at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at org.elasticsearch.repositories.azure.SocketAccess.lambda$doPrivilegedVoidException$0(SocketAccess.java:46) ~[?:?]
        at java.security.AccessController.doPrivileged(AccessController.java:569) ~[?:?]
        at org.elasticsearch.repositories.azure.SocketAccess.doPrivilegedVoidException(SocketAccess.java:45) ~[?:?]
        at org.elasticsearch.repositories.azure.AzureClientProvider$1.lambda$decorateRunnable$0(AzureClientProvider.java:210) ~[?:?]
        ... 4 more
        Suppressed: java.lang.Exception: #block terminated with an error
                at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99) ~[?:?]
                at reactor.core.publisher.Flux.blockLast(Flux.java:2497) ~[?:?]
                at com.azure.core.util.paging.ContinuablePagedByIteratorBase.requestPage(ContinuablePagedByIteratorBase.java:94) ~[?:?]
                at com.azure.core.util.paging.ContinuablePagedByItemIterable$ContinuablePagedByItemIterator.<init>(ContinuablePagedByItemIterable.java:50) ~[?:?]
                at com.azure.core.util.paging.ContinuablePagedByItemIterable.iterator(ContinuablePagedByItemIterable.java:37) ~[?:?]
                at com.azure.core.util.paging.ContinuablePagedIterable.iterator(ContinuablePagedIterable.java:106) ~[?:?]
                at org.elasticsearch.repositories.azure.AzureBlobStore.lambda$listBlobsByPrefix$15(AzureBlobStore.java:327) ~[?:?]
                at org.elasticsearch.repositories.azure.SocketAccess.lambda$doPrivilegedVoidException$0(SocketAccess.java:46) ~[?:?]
                at java.security.AccessController.doPrivileged(AccessController.java:569) ~[?:?]
                at org.elasticsearch.repositories.azure.SocketAccess.doPrivilegedVoidException(SocketAccess.java:45) ~[?:?]
                at org.elasticsearch.repositories.azure.AzureBlobStore.listBlobsByPrefix(AzureBlobStore.java:321) ~[?:?]
                at org.elasticsearch.repositories.azure.AzureBlobContainer.listBlobsByPrefix(AzureBlobContainer.java:135) ~[?:?]
                at org.elasticsearch.repositories.blobstore.BlobStoreRepository.snapshotShard(BlobStoreRepository.java:2645) [elasticsearch-8.2.2.jar:8.2.2]
                at org.elasticsearch.snapshots.SnapshotShardsService.snapshot(SnapshotShardsService.java:360) [elasticsearch-8.2.2.jar:8.2.2]
                at org.elasticsearch.snapshots.SnapshotShardsService.lambda$startNewShards$1(SnapshotShardsService.java:265) [elasticsearch-8.2.2.jar:8.2.2]
                at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:714) [elasticsearch-8.2.2.jar:8.2.2]
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
                at java.lang.Thread.run(Thread.java:833) [?:?]
```

</details>

**Information Checklist**

Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by alzimmermsft** [comment]
Thanks for filing this @DaveCTurner.

Based on the stack trace could you make sure the Storage account key is correctly formatted as this stack trace points to the decoding of the account key.

But this is a good feature request to include more information here, the following could be a change proposal:


**Before**

```java
public static String computeHMac256(final String base64Key, final String stringToSign) {
        try {
            byte[] key = Base64.getDecoder().decode(base64Key);
            Mac hmacSHA256 = Mac.getInstance("HmacSHA256");
            hmacSHA256.init(new SecretKeySpec(key, "HmacSHA256"));
            byte[] utf8Bytes = stringToSign.getBytes(StandardCharsets.UTF_8);
            return Base64.getEncoder().encodeToString(hmacSHA256.doFinal(utf8Bytes));
        } catch (NoSuchAlgorithmException | InvalidKeyException ex) {
            throw new RuntimeException(ex);
        }
    }
```

**After**

```java
public static String computeHMac256(final String base64Key, final String stringToSign) {
        byte[] key;
        try {
            key = Base64.getDecoder().decode(base64Key);
        } catch (IllegalArgumentException ex) {
            throw new RuntimeException("'base64Key' was not a valid Base64 scheme. Ensure the Storage account key or SAS key is properly formatted.", ex)
        }

        try {
            Mac hmacSHA256 = Mac.getInstance("HmacSHA256");
            hmacSHA256.init(new SecretKeySpec(key, "HmacSHA256"));
            byte[] utf8Bytes = stringToSign.getBytes(StandardCharsets.UTF_8);
            return Base64.getEncoder().encodeToString(hmacSHA256.doFinal(utf8Bytes));
        } catch (NoSuchAlgorithmException | InvalidKeyException ex) {
            throw new RuntimeException(ex);
        }
    }
```

**Comment by DaveCTurner** [comment]
Thanks @alzimmermsft, yes sorry I didn't get the full details from the user but it could well have been their account key that was incorrect. I think your proposal would have helped them find the problem indeed.
