### ISSUE TITLE
[BUG] No registered resource provider found for location 'chinanorth2' and API version '2021-11-01' for type 'namespaces'

### ISSUE THREAD

**Issue by domainname** [Azure/azure-sdk-for-java#32739]
**Describe the bug**

We upgraded `azure-resourcemanager` from 2.17.0 to a newer version. Then our application failed to start, with the following error. The problem occurs in any version between [2.18.0, 2.22.0]. It occurs in Mooncake, and does NOT occur in public cloud.

After reverting its version to 2.17.0, our application started to work again.

```
2022-12-30 14:05:27.041 ERROR 53642 --- [           main] o.s.boot.SpringApplication               : Application run failed

...
Caused by: com.azure.core.management.exception.ManagementException: Status code 400, "{"error":{"code":"NoRegisteredProviderFound","message":"No registered resource provider found for location 'chinanorth2' and API version '2021-11-01' for type 'namespaces'. The supported api-versions are '2014-09-01, 2015-08-01, 2017-04-01, 2018-01-01-preview, 2021-01-01-preview, 2021-06-01-preview, 2022-01-01-preview'. The supported locations are 'chinanorth, chinaeast, chinanorth2, chinaeast2, chinanorth3'."}}"
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:710)
	at com.azure.core.implementation.http.rest.ResponseExceptionConstructorCache.invoke(ResponseExceptionConstructorCache.java:56)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    ...
	at java.base/java.lang.Thread.run(Thread.java:829)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
		at reactor.core.publisher.Mono.block(Mono.java:1742)
		at com.azure.resourcemanager.resources.fluentcore.arm.collection.implementation.GroupableResourcesImpl.getById(GroupableResourcesImpl.java:62)
		at com.azure.resourcemanager.resources.fluentcore.arm.collection.implementation.GroupableResourcesImpl.getById(GroupableResourcesImpl.java:28)
        ...
```

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**

***Code Snippet***
```
        ServiceBusNamespace ns = azureProvider.getAzure(subscriptionId)
            .serviceBusNamespaces()
            .getById(resourceId);
```

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - IDE: [e.g. IntelliJ]
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)]
 - Java version: 11
 - App Server/Environment: [e.g. Tomcat, WildFly, Azure Function, Apache Spark, Databricks, IDE plugin or anything special]
 - Frameworks: Spring Boot

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by joshfree** [comment]
Hi @domainname thank you for reporting this issue.  @weidongxu-microsoft could you please follow up?

**Comment by XiaofeiCao** [comment]
`servicebus` is using a newer api-version `2021-11-01` since 2.18.0. Seems like service backend didn't roll out this api version to Mooncake. This needs service attention.

As a workaround before service fix, you can try explicitly specifying to depend on 2.17.0 of `azure-resourcemanager`.

**Comment by domainname** [comment]
Hi @Saglodha , @EldertGrootenboer , any updates on this?

**Comment by weidongxu-microsoft** [comment]
I've also mentioned this in other threads as well. But currently the available api-version depends on backend.

@XiaofeiCao One thing we can think/improve on SDK side is whether we can allow customer select an older api-version (there probably some risk and difficulty with this approach, due to breaking changes or potential change from single version to multiple version combined, so we'd likely needs more discussion).

**Comment by Saglodha** [comment]
Thanks for bringing this to our attention @domainname 

I would check with the team on the roll out status for the China cloud and would circle back with an update soon,

**Comment by domainname** [comment]
Hi @Saglodha , do you have any updates on this issue?

**Comment by Saglodha** [comment]
@domainname, I checked with the team and could know that this has been rolled out. Could you please retry and confirm if you have been facing any issues now?
