### ISSUE TITLE
[BUG] beginDeleteSecret().waitForCompletion() recently meets timeout more frequently

### ISSUE THREAD

**Issue by waboqin** [Azure/azure-sdk-for-java#32879]
**Describe the bug**
Hi, 
i code like this:
 this.secretClient.beginDeleteSecret(secretName).waitForCompletion(Duration.ofSeconds(30L))

it works fine before. but recently , it always meet timeout error, wired thing is, i also check the log in key vault, **there's no failed or slow response, every request response is within 10s from key vault side**.

***Exception or Stack Trace***
java.lang.RuntimeException: java.util.concurrent.TimeoutException
	at com.azure.core.util.polling.PollingUtil.pollingLoop(PollingUtil.java:62)
	at com.azure.core.util.polling.SimpleSyncPoller.waitForCompletionHelper(SimpleSyncPoller.java:142)
	at com.azure.core.util.polling.SimpleSyncPoller.waitForCompletion(SimpleSyncPoller.java:96)

Caused by: java.util.concurrent.TimeoutException: null
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
	at com.azure.core.util.polling.PollingUtil.pollingLoop(PollingUtil.java:56)
	... 152 common frames omitted

**To Reproduce**
set up akv in West Europe, try to 
1.create a secret 
2. get that secret
3. delete that secret

***Code Snippet***
Add the code snippet that causes the issue.
 this.secretClient.beginDeleteSecret(secretName).waitForCompletion(Duration.ofSeconds(30L))

**Expected behavior**
since key vault doesn't fail or slow response. it should behave the same. 

**Screenshots**

**Setup (please complete the following information):**
 - IDE: [e.g. IntelliJ]
 - Library/Libraries: 
 - azure.resource.management.sdk.version:2.22.0
 - azure-security-keyvault-secrets：4.5.2
 - Java version:11 
 

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by alzimmermsft** [comment]
@waboqin this is somewhat related to #30648 where the wait for completion timeout would be reset for every intermediate poll operation. In #30587 we redesigned the synchronous poller to correctly timeout the operation if a terminal polling status wasn't reached during the wait for completion timeout instead of resetting on each poll operation. A workaround for this would be increasing the timeout to allow for the entirety of polling to complete.

We'll be working on offering better timeout handling in polling and will have updates for this issue as we progress.

**Comment by g2vinay** [comment]
Thank you @alzimmermsft for the response.
@waboqin 
If you'd prefer the old behaviour of Polling timeout, let us know too, as that data will be helpful to offer better timeout options to our users.
