### ISSUE TITLE
[BUG] Event Hub Client crashes on null data body

### ISSUE THREAD

**Issue by thomasstoermer** [Azure/azure-sdk-for-java#32939]
**Describe the bug**
Event Consumer of Java Event Hub SDK fails when processing an event containing body with data(null). Such an event can be created with https://github.com/Azure/azure-sdk-for-js, if the body of the event is undefined/null.
An `EventProcessorClient` will get blocked by continuously failing on such an event.

***Exception or Stack Trace***
```
java.lang.NullPointerException
	at com.azure.messaging.eventhubs.implementation.MessageUtils.toAmqpAnnotatedMessage(MessageUtils.java:205)
	at com.azure.messaging.eventhubs.EventHubMessageSerializer.deserializeEventData(EventHubMessageSerializer.java:198)
	at com.azure.messaging.eventhubs.EventHubMessageSerializer.deserialize(EventHubMessageSerializer.java:134)
	at com.azure.messaging.eventhubs.EventHubPartitionAsyncConsumer.onMessageReceived(EventHubPartitionAsyncConsumer.java:125)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:106)
	at com.azure.messaging.eventhubs.implementation.AmqpReceiveLinkProcessor.drainQueue(AmqpReceiveLinkProcessor.java:581)
	at com.azure.messaging.eventhubs.implementation.AmqpReceiveLinkProcessor.drain(AmqpReceiveLinkProcessor.java:539)
	at com.azure.messaging.eventhubs.implementation.AmqpReceiveLinkProcessor.lambda$onNext$8(AmqpReceiveLinkProcessor.java:329)
	at reactor.core.publisher.LambdaSubscriber.onNext(LambdaSubscriber.java:160)
	at reactor.core.publisher.FluxOnBackpressureBufferStrategy$BackpressureBufferDropOldestSubscriber.innerDrain(FluxOnBackpressureBufferStrategy.java:274)
	at reactor.core.publisher.FluxOnBackpressureBufferStrategy$BackpressureBufferDropOldestSubscriber.drain(FluxOnBackpressureBufferStrategy.java:238)
	at reactor.core.publisher.FluxOnBackpressureBufferStrategy$BackpressureBufferDropOldestSubscriber.onNext(FluxOnBackpressureBufferStrategy.java:203)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.tryEmit(FluxFlatMap.java:543)
	at reactor.core.publisher.FluxFlatMap$FlatMapInner.onNext(FluxFlatMap.java:984)
	at reactor.core.publisher.MonoCreate$DefaultMonoSink.success(MonoCreate.java:172)
	at com.azure.core.amqp.implementation.ReactorReceiver.lambda$new$0(ReactorReceiver.java:125)
	at com.azure.core.amqp.implementation.handler.DispatchHandler.onTimerTask(DispatchHandler.java:32)
	at com.azure.core.amqp.implementation.ReactorDispatcher$WorkScheduler.run(ReactorDispatcher.java:207)
	at org.apache.qpid.proton.reactor.impl.SelectableImpl.readable(SelectableImpl.java:118)
	at org.apache.qpid.proton.reactor.impl.IOHandler.handleQuiesced(IOHandler.java:61)
	at org.apache.qpid.proton.reactor.impl.IOHandler.onUnhandled(IOHandler.java:390)
	at org.apache.qpid.proton.engine.BaseHandler.onReactorQuiesced(BaseHandler.java:87)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:206)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:292)
	at com.azure.core.amqp.implementation.ReactorExecutor.run(ReactorExecutor.java:91)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
**To Reproduce**
- Send event with null body (azure-sdk-for-js)
- Start consumer with java sdk

***Code Snippet***
Send event with null body (azure-sdk-for-js) 
```
const producer = new EventHubProducerClient(connection);
await producer.createBatch({ partitionId: "1" })
    .then(b => {
        b.tryAdd({
            properties: {
                some: "header"
            },
            body: null
        })
        return producer.sendBatch(b)
    })
```
**Expected behavior**
Client must not crash.

**Setup (please complete the following information):**
- Java 11
- com.azure:azure-messaging-eventhubs:jar:5.15.0

**Additional context**
-

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by joshfree** [comment]
@conniey could you follow up with @thomasstoermer on this issue?

**Comment by conniey** [comment]
Weird. Thank you for reporting this.

**Comment by thomasstoermer** [comment]
Thank you for the fix @joshfree and @conniey 👍
