### ISSUE TITLE
[BUG] Attempt to start recording fails with too many retries

### ISSUE THREAD

**Issue by dleewo** [Azure/azure-sdk-for-java#32963]
**Describe the bug**
Using the sample app, I set the `ConnectionString` in `config.properties `and tried to start a recording.  It always fails with the error "Retry attempts have been exhausted"

I know the connection string is fine and the passed in `serverCallId` is valid because if I try to start a recording after the meeting is ended, I get a different error.

I also built 1.0.0-beta.2 from the GitHub as of today and that fails too.

***Exception or Stack Trace***
```
2023-01-13 11:40:08.275  INFO 14195 --- [r-http-kqueue-1] com.azure.core.http.policy.RetryPolicy   : {"az.sdk.message":"Retry attempts have been exhausted.","tryCount":3}
com.azure.communication.callautomation.models.CallingServerErrorException: Status code 500, "{"error":{"code":"9999","message":"Unknown internal server error."}}"
	at com.azure.communication.callautomation.models.CallingServerErrorException$1.create(CallingServerErrorException.java:65)
	at com.azure.communication.callautomation.implementation.accesshelpers.ErrorConstructorProxy.create(ErrorConstructorProxy.java:57)
	at com.azure.communication.callautomation.implementation.accesshelpers.ErrorConstructorProxy.create(ErrorConstructorProxy.java:60)
```

**To Reproduce**
Invoke `http://localhost:8080/startRecording?serverCallId=aHR0c...[SNIP]...OTQ2MTU5MDEyOTQ3` against the sample app

***Code Snippet***
```
serverCallLocator = new ServerCallLocator(serverCallId);

StartRecordingOptions recordingOptions = new StartRecordingOptions(serverCallLocator);
recordingOptions.setRecordingContent(RecordingContent.AUDIO_VIDEO);
recordingOptions.setRecordingChannel(RecordingChannel.MIXED);
recordingOptions.setRecordingFormat(RecordingFormat.MP4);

logger.log(Level.INFO, "Getting call recording") ;
CallRecording callRecording = this.callAutomationClient.getCallRecording() ;
logger.log(Level.INFO, "Starting recording") ;
Response<RecordingStateResult> response = callRecording.startRecordingWithResponse(recordingOptions, null);
```

The last line that invokes `startRecordingWithResponse()` is what generates the error.  I also tried the `startRecording()` method and that fails similarly

**Expected behavior**
The recording should start without an error

**Screenshots**
N/A

**Setup**
 - OS: Max OS X 12.6.2
 - IDE: Visual Studio Code
 - Library/Libraries: azure-communication-callautomation:1.0.0-beta.1
 - Java version: OpenJDK 14.0.2
 - App Server/Environment: Sample app MS provides using Spring Boot
 - Frameworks: Spring Boot

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ x] Bug Description Added
- [ x] Repro Steps Added
- [ x] Setup information Added

**Comment by dleewo** [comment]
I've been testing with just the host in the meeting.  Could this error be due to not having a second person in the meeting?  If so, should the error returned better explain what went wrong?

**Comment by joshfree** [comment]
@juntuchen-msft could you please follow up with @dleewo
