### ISSUE TITLE
[Bug] ClassNotFoundException io.opentelemetry...AgentContextStorage with AppInsights agent 3.4.7

### ISSUE THREAD

**Issue by alain-marcel** [Azure/azure-sdk-for-java#32980]
**Describe the bug**
GIVEN
  Azure Function with Java 17
  SpringBoot : 2.7.6
  SpringCloud: 2021.0.5
  SpringCloudAzure: 4.5.0
  Java Opentelemetry Instrumentation BOM: 1.22.1
  Java ApplicationInsights agent: 3.4.7
  com.microsoft.azure:applicationinsights-runtime-attach:3.4.7

WHEN 
  Azure Function starts, and after calling  com.microsoft.applicationinsights.attach.ApplicationInsights.attach()

THEN
  ClassNotFoundException io.opentelemetry.javaagent.instrumentation.opentelemetryapi.context.AgentContextStorage is thrown.

***Exception or Stack Trace***
2023-01-14T18:29:00.781Z [p19940] [t1    ] [r.c.p.Hooks] DEBUG Hooking onEachOperator: io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber
2023-01-14T18:29:00.782Z [p19940] [t1    ] [r.c.p.Hooks] DEBUG Hooking onEachOperator: io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber
2023-01-14T18:29:00.973Z [p19940] [t1    ] [i.o.j.i.a.v.s.c.a.c.t.o.i.OpenTelemetrySpanSuppressionHelper] DEBUG Failed to discover OpenTelemetry agent classes, HTTP spans may be duplicated
java.lang.ClassNotFoundException: io.opentelemetry.javaagent.instrumentation.opentelemetryapi.context.AgentContextStorage
at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[?:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
at java.lang.Class.forName0(Native Method) ~[?:?]
at java.lang.Class.forName(Class.java:375) ~[?:?]
at io.opentelemetry.javaagent.instrumentation.azurecore.v1_19.shaded.com.azure.core.tracing.opentelemetry.implementation.OpenTelemetrySpanSuppressionHelper.<clinit>(OpenTelemetrySpanSuppressionHelper.java:31) ~[?:?]
at io.opentelemetry.javaagent.instrumentation.azurecore.v1_19.shaded.com.azure.core.tracing.opentelemetry.OpenTelemetryHttpPolicy$ScalarPropagatingMono.subscribe(OpenTelemetryHttpPolicy.java:241) ~[?:?]
at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[reactor-core-3.4.25.jar:3.4.25]
at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157) ~[reactor-core-3.4.25.jar:3.4.25]
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.lambda$onNext$1(TracingSubscriber.java:62) ~[?:?]
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.withActiveSpan(TracingSubscriber.java:86) ~[?:?]
at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.onNext(TracingSubscriber.java:62) ~[?:?]

**To Reproduce**
In the azure function context, user code does not have access to main method,
so we set System.setProperty("otel.javaagent.testing.runtime-attach.main-method-check", "false")
befoe calling  com.microsoft.applicationinsights.attach.ApplicationInsights.attach().

**Comment by joshfree** [comment]
@lmolkova @trask could you please follow up with @alain-marcel on this github issue?

**Comment by trask** [comment]
hi @alain-marcel!

`System.setProperty("otel.javaagent.testing.runtime-attach.main-method-check", "false")`

is not supported (it's only exposed for `testing` and undocumented)

we do have a supported Application Insights integration with Azure Functions in preview, can you try that and see if that works for you? https://learn.microsoft.com/en-us/azure/azure-monitor/app/monitor-functions#distributed-tracing-for-java-applications-public-preview

**Comment by alain-marcel** [comment]
Hi @trask, thanks for your response.
We cannot avoid exception with our context
About our context :
  - We integrate the jar using gradle with the com.microsoft.azure.azurefunctions plugin.
  - We load applicationinsights.json configuration file.

With your proposal, we cannot load applicationinsights.json configuration file.

**Comment by trask** [comment]
hey @alain-marcel, are you using Azure Functions consumption or dedicated?

which settings in applicationinsights.json are you configuring?

**Comment by alain-marcel** [comment]
We use premium plan

**Comment by trask** [comment]
as long as you aren't using consumption plan, you can specify a location for your applicationinsights.json file when using the Azure Functions Application Insights integration using [`APPLICATIONINSIGHTS_CONFIGURATION_FILE`](https://learn.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-config#configuration-file-path)

**Comment by alain-marcel** [comment]
ok thanks
