### ISSUE TITLE
[QUERY] : BlobRange count must be greater than or equal to 0 if specified.

### ISSUE THREAD

**Issue by syedyasiraswath** [Azure/azure-sdk-for-java#33048]
**Query/Question**
1. How do i set a BlobRange for downloading a blob using Azure SDK.
2. How do i know the range beforehand if i am passing the range for downloadwithresponse.
3. In my case i am writing a proxy service which will download the content and the Azure SDK is verifying the range before creating the outputstream

**Logs**
java.lang.IllegalArgumentException: BlobRange count must be greater than or equal to 0 if specified.
	at com.azure.storage.blob.models.BlobRange.<init>(BlobRange.java:49) ~[azure-storage-blob-12.14.4.jar:12.14.4]
	at com.azure.storage.blob.specialized.BlobAsyncClientBase.lambda$downloadStreamWithResponse$23(BlobAsyncClientBase.java:1305) ~[azure-storage-blob-12.14.4.jar:12.14.4]
	at com.azure.core.implementation.RetriableDownloadFlux.lambda$subscribe$1(RetriableDownloadFlux.java:64) ~[azure-core-1.31.0.jar:1.31.0]
	at com.azure.core.implementation.RetriableDownloadFlux.subscribe(RetriableDownloadFlux.java:52) ~[azure-core-1.31.0.jar:1.31.0]
	at reactor.core.publisher.Flux.subscribe(Flux.java:8469) ~[reactor-core-3.4.18.jar:3.4.18]
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103) ~[reactor-core-3.4.18.jar:3.4.18]
	at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:134) ~[reactor-core-3.4.18.jar:3.4.18]
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onError(MonoFlatMapMany.java:255) ~[reactor-core-3.4.18.jar:3.4.18]
	at reactor.core.publisher.SerializedSubscriber.onError(SerializedSubscriber.java:124) ~[reactor-core-3.4.18.jar:3.4.18]
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.onError(FluxTimeout.java:219) ~[reactor-core-3.4.18.jar:3.4.18]
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onError(FluxDoFinally.java:136) ~[reactor-core-3.4.18.jar:3.4.18]
	at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:134) ~[reactor-core-3.4.18.jar:3.4.18]
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onError(FluxDoFinally.java:136) ~[reactor-core-3.4.18.jar:3.4.18]
	at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:134) ~[reactor-core-3.4.18.jar:3.4.18]
	at reactor.netty.channel.FluxReceive.onInboundError(FluxReceive.java:450) ~[reactor-netty-core-1.0.19.jar:1.0.19]
	at reactor.netty.channel.ChannelOperations.onInboundError(ChannelOperations.java:488) ~[reactor-netty-core-1.0.19.jar:1.0.19]
	at reactor.netty.http.client.HttpClientOperations.onInboundClose(HttpClientOperations.java:298) ~[reactor-netty-http-1.0.19.jar:1.0.19]
	at reactor.netty.channel.ChannelOperationsHandler.channelInactive(ChannelOperationsHandler.java:73) ~[reactor-netty-core-1.0.19.jar:1.0.19]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelInactive(CombinedChannelDuplexHandler.java:418) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:392) ~[netty-codec-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:357) ~[netty-codec-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.handler.codec.http.HttpClientCodec$Decoder.channelInactive(HttpClientCodec.java:326) ~[netty-codec-http-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.CombinedChannelDuplexHandler.channelInactive(CombinedChannelDuplexHandler.java:221) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:813) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.kqueue.KQueueEventLoop.run(KQueueEventLoop.java:293) ~[netty-transport-classes-kqueue-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
	at java.base/java.lang.Thread.run(Thread.java:832) ~[na:na]

**Setup (please complete the following information if applicable):**
 - OS: IOS
 - IDE: IntelliJ
 - Library/Libraries: 
implementation platform('com.azure:azure-sdk-bom:1.1.1')

	implementation 'com.azure:azure-storage-blob'
	implementation 'com.azure:azure-core'
	implementation 'com.azure:azure-core-http-netty'
	//implementation 'com.azure:azure-core-http-ok'
	implementation 'com.azure:azure-identity'
	implementation 'com.azure:azure-security-keyvault-secrets'
	implementation group: 'org.apache.commons', name: 'commons-lang3', version: '3.12.0'

	implementation ('com.azure.resourcemanager:azure-resourcemanager:2.18.0') {
		exclude group: 'com.azure', module: 'azure-core'
	}

	configurations.all{
		resolutionStrategy{
			force 'com.azure:azure-storage-common:12.18.0', 'com.azure:azure-storage-common:12.14.3'
		}
	}
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Query Added
- [X] Setup information Added

**Comment by syedyasiraswath** [comment]
@alzimmermsft 
Can you take a look

**Comment by alzimmermsft** [comment]
> How do i set a BlobRange for downloading a blob using Azure SDK.

The current SDK design follows a pattern where there is an `X` API which takes all required parameters for an API call and `XWithResponse` which takes all parameters available for an API call, ex `download` and `downloadWithResponse`. Since `BlobRange` is an optional parameter to the Storage service for downloading you'll find `BlobRange` settable in `WithResponse` APIs, sometimes this is a parameter directly in the API and other times it's indirectly available through what we call option bags or in other terms a simple POJO that has fields for all parameters that can grow without adding extra APIs. Here are some examples:

https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/specialized/BlobClientBase.java#L881

https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/specialized/BlobClientBase.java#L1131

> How do i know the range beforehand if i am passing the range for downloadwithresponse.

You can get the size of the blob using `getProperties`, or if you don't want to make an additional service call you can call `downloadWithResponse` using an arbitrary initial range. The range doesn't need to be exact as the service will return a 206 (Partial Content) if a portion of the range was satisfiable (more details at https://learn.microsoft.com/en-us/rest/api/storageservices/specifying-the-range-header-for-blob-service-operations). In addition to that there will be a `Content-Range` header returned which will indicate the range download followed by the size of the blob, ex `bytes 0-1023/2048` where `0-1024` indicates the download range and `2048` indicates the blob size (the range is inclusive so `0-1023/1024` is a complete read). We use this logic ourselves and https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/implementation/util/ChunkedDownloadUtils.java has a good overview on how `BlobRange` can be used in practice.


> In my case i am writing a proxy service which will download the content and the Azure SDK is verifying the range before creating the outputstream

For this issue is there any logs indicating an error status code when downloading?

**Comment by syedyasiraswath** [comment]
ava.lang.IllegalArgumentException: BlobRange count must be greater than or equal to 0 if specified.
	at com.azure.storage.blob.models.BlobRange.<init>(BlobRange.java:49) ~[azure-storage-blob-12.14.4.jar:12.14.4]
	at com.azure.storage.blob.specialized.BlobAsyncClientBase.lambda$downloadStreamWithResponse$23(BlobAsyncClientBase.java:1305) ~[azure-storage-blob-12.14.4.jar:12.14.4]
	at com.azure.core.implementation.RetriableDownloadFlux.lambda$subscribe$1(RetriableDownloadFlux.java:64) ~[azure-core-1.31.0.jar:1.31.0]
	at com.azure.core.implementation.RetriableDownloadFlux.subscribe(RetriableDownloadFlux.java:52) ~[azure-core-1.31.0.jar:1.31.0]
	at reactor.core.publisher.Flux.subscribe(Flux.java:8469) ~[reactor-core-3.4.18.jar:3.4.18]
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103) ~[reactor-core-3.4.18.jar:3.4.18]
	at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:134) ~[reactor-core-3.4.18.jar:3.4.18]
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onError(MonoFlatMapMany.java:255) ~[reactor-core-3.4.18.jar:3.4.18]
	at reactor.core.publisher.SerializedSubscriber.onError(SerializedSubscriber.java:124) ~[reactor-core-3.4.18.jar:3.4.18]
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.onError(FluxTimeout.java:219) ~[reactor-core-3.4.18.jar:3.4.18]
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onError(FluxDoFinally.java:136) ~[reactor-core-3.4.18.jar:3.4.18]
	at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:134) ~[reactor-core-3.4.18.jar:3.4.18]
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onError(FluxDoFinally.java:136) ~[reactor-core-3.4.18.jar:3.4.18]
	at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:134) ~[reactor-core-3.4.18.jar:3.4.18]

**Comment by syedyasiraswath** [comment]
for(String aValue : header.getValue()) {
                    if (header.getKey().equalsIgnoreCase("eTag") || header.getKey().equalsIgnoreCase("x-ms-client-request-id")
                        || header.getKey().equalsIgnoreCase("Content-Length")
                        || header.getKey().equalsIgnoreCase("Accept-Ranges")
                    ) {
                        response.addHeader(header.getKey(), aValue);
                    }
                }

**Comment by syedyasiraswath** [comment]
i am passing the above headers from the endpointoverride

**Comment by alzimmermsft** [comment]
> for(String aValue : header.getValue()) { if (header.getKey().equalsIgnoreCase("eTag") || header.getKey().equalsIgnoreCase("x-ms-client-request-id") || header.getKey().equalsIgnoreCase("Content-Length") || header.getKey().equalsIgnoreCase("Accept-Ranges") ) { response.addHeader(header.getKey(), aValue); } }

Is this filtering out the headers being returned in the response? If so, you'll also want to include the `Content-Range` header as well. This is what is being inspected which leads to the exception being thrown, with chunked download (the default for larger blobs) `Content-Range` is used to determine:

- Has the whole blob been downloaded? Based on the total length portion of the `Content-Range` header.
- What size should the next chunk be? Based on the total length portion and the range portion of the `Content-Range` header.

Also, just a recommendation if you're application needs high throughput. If you're using a version of Storage, and transitively Azure Core, where `HttpHeaderName` is available I would recommend changing that codesnippet to:


```java
// Assumption, there is an azure-core HttpHeaders type not mentioned with the variable name 'httpHeaders'.

String[] values = null;
if ((values = httpHeaders.getValues(HttpHeaderName.ETAG) != null) {
  // Consume values
}

// Repeat same for each header being looked for, for headers that don't have an HttpHeaderName constant create a 
// custom constant using HttpHeaderName.fromString(String).
```

Or more generally put, when there is an available `HttpHeaderName` API use that instead of the `String` API. `HttpHeaderName` has a lot of string optimizations which removes having to use `String.toLowerCase` or `String.equalsIgnoreCase` one each call to on construction time of the `HttpHeaderName`.

**Comment by syedyasiraswath** [comment]
The Content-Range did not come from  SDK response.
Only the Content-Length came from it.

CASE1:
If i add the Content-Length to the HttpServletResponse then outputstream is loading forever and getting timed out

CASE2:
If i remove the Content-Length then the Outstream is flushed properly via postman
But when i invoke the proxy service from Client simulation code then its looking for Content-Range or Content-Length hence throwing null pointer

**Comment by alzimmermsft** [comment]
Just to clarify, which line in the code you pasted causes the `NullPointerException`? Is it this line:

> BlobDownloadResponse BlobDownloadResponse = blobClient.downloadWithResponse(outputStream, null, null, null, false, null, null);

And does this error happen all the time or periodically?

**Comment by ibrahimrabab** [comment]
Hi @syedyasiraswath 
Is this an issue that you're still facing? If so, can you provide more details on where you are seeing the NPE specifically?
