### ISSUE TITLE
[QUERY] Unable to create Private Link Service using the SDK. 

### ISSUE THREAD

**Issue by kevinpat1987** [Azure/azure-sdk-for-java#33163]
**Query/Question**
The creation of a Private Link Service against the private internal load balancer of the Kubernetes cluster is not working using the SDK for Java. 

***Why is this not a Bug or a feature Request?***
Not sure if this is a bug yet. Trying to verify is the steps that I have followed are correct.

**Setup (please complete the following information if applicable):**
 - OS: MacOS
 - JDK: amazon-corretto-8 
 - IDE: IntelliJ
 - Library/Libraries:     
    implementation group: 'com.azure', name: 'azure-core', version: '1.35.0'
    implementation group: 'com.azure', name: 'azure-identity', version: '1.7.3'
    implementation group: 'com.azure.resourcemanager', name: 'azure-resourcemanager', version: '2.22.0'

 
Getting the following exception when attempting to create a private link service. 

Exception in thread "main" com.azure.resourcemanager.network.models.ErrorException: Status code 400, "{
  "error": {
    "code": "InvalidRequestFormat",
    "message": "Cannot parse the request.",
    "details": []
  }
}": Cannot parse the request.
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at com.azure.core.implementation.http.rest.ResponseExceptionConstructorCache.invoke(ResponseExceptionConstructorCache.java:56)
	at com.azure.core.implementation.http.rest.RestProxyBase.instantiateUnexpectedException(RestProxyBase.java:377)
	at com.azure.core.implementation.http.rest.AsyncRestProxy.lambda$ensureExpectedStatus$1(AsyncRestProxy.java:116)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:113)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1839)
	at reactor.core.publisher.MonoCollect$CollectSubscriber.onComplete(MonoCollect.java:160)
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onComplete(MonoFlatMapMany.java:260)
	at reactor.core.publisher.FluxIterable$IterableSubscription.fastPath(FluxIterable.java:424)
	at reactor.core.publisher.FluxIterable$IterableSubscription.request(FluxIterable.java:291)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onSubscribeInner(MonoFlatMapMany.java:150)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onSubscribe(MonoFlatMapMany.java:245)
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:201)
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:83)
	at reactor.core.publisher.Flux.subscribe(Flux.java:8642)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onNext(MonoFlatMapMany.java:195)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1839)
	at reactor.core.publisher.MonoCacheTime.subscribeOrReturn(MonoCacheTime.java:151)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129)
	at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onNext(FluxHide.java:137)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129)
	at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onNext(FluxHide.java:137)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:122)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1839)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1839)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.complete(MonoIgnoreThen.java:292)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onNext(MonoIgnoreThen.java:187)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1839)
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:249)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1839)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1839)
	at reactor.core.publisher.MonoCollect$CollectSubscriber.onComplete(MonoCollect.java:160)
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onComplete(MonoFlatMapMany.java:260)
	at reactor.core.publisher.FluxIterable$IterableSubscription.fastPath(FluxIterable.java:424)
	at reactor.core.publisher.FluxIterable$IterableSubscription.request(FluxIterable.java:291)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onSubscribeInner(MonoFlatMapMany.java:150)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onSubscribe(MonoFlatMapMany.java:245)
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:201)
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:83)
	at reactor.core.publisher.Flux.subscribe(Flux.java:8642)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onNext(MonoFlatMapMany.java:195)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1839)
	at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.signalCached(MonoCacheTime.java:337)
	at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.onNext(MonoCacheTime.java:354)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1839)
	at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:129)
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onComplete(FluxDoFinally.java:128)
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144)
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144)
	at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:413)
	at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:419)
	at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:473)
	at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:702)
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:113)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1373)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1236)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1285)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.kqueue.AbstractKQueueStreamChannel$KQueueStreamUnsafe.readReady(AbstractKQueueStreamChannel.java:544)
	at io.netty.channel.kqueue.AbstractKQueueChannel$AbstractKQueueUnsafe.readReady(AbstractKQueueChannel.java:387)
	at io.netty.channel.kqueue.KQueueEventLoop.processReady(KQueueEventLoop.java:213)
	at io.netty.channel.kqueue.KQueueEventLoop.run(KQueueEventLoop.java:291)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:750)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
		at reactor.core.publisher.Mono.block(Mono.java:1742)
		at com.azure.resourcemanager.network.implementation.PrivateLinkServicesClientImpl.createOrUpdate(PrivateLinkServicesClientImpl.java:964)

`

public static void createPrivateLinkService(String resourceGroup, String region, String envId, String requestRouterIp, String subnetName, List<String> preApprovedIds,
                                                Map<String, String> tags) {

        AzureResourceManager azureResourceManager = getResourceManager(AzureEnvironment.AZURE);

        // Find the Kubernetes Service Internal Load Balancer
        LoadBalancer internalLoadBalancer = findKubernetesInternalLoadBalancer(azureResourceManager,
                getKubernetesInternalLBResourceGroup(envId, region));

        PrivateLinkServicesClient privateLinkServicesClient = azureResourceManager
                .networks()
                .manager()
                .serviceClient()
                .getPrivateLinkServices();
        
        // Simple name for the private link service based on certain format. e.g plk-1234566547
        String serviceName = getPrivateLinkServiceName(envId);

        PrivateLinkServicePropertiesAutoApproval autoApproval = new PrivateLinkServicePropertiesAutoApproval();
        autoApproval.withSubscriptions(preApprovedIds);

        PrivateLinkServicePropertiesVisibility propertiesVisibility = new PrivateLinkServicePropertiesVisibility();
        propertiesVisibility.withSubscriptions(Collections.singletonList("*"));

        FrontendIpConfigurationInner frontendIpConfigurationInner = new FrontendIpConfigurationInner();
        if (internalLoadBalancer != null) {
            for (Map.Entry<String, LoadBalancerPrivateFrontend> kv: internalLoadBalancer.privateFrontends().entrySet()) {
                if (kv.getValue().privateIpAddress().equalsIgnoreCase(requestRouterIp)) {
                    frontendIpConfigurationInner.withId(kv.getValue().innerModel().id());
                }
            }
        }

        PrivateLinkServiceIpConfigurationInner propertiesInner01 = new PrivateLinkServiceIpConfigurationInner();
        propertiesInner01.withPrivateIpAllocationMethod(IpAllocationMethod.DYNAMIC);
        propertiesInner01.withPrivateIpAddressVersion(IpVersion.IPV4);
        propertiesInner01.withPrimary(true);
        propertiesInner01.withSubnet(new SubnetInner().withId(subnetName));
        propertiesInner01.withName("test-01");

        PrivateLinkServiceIpConfigurationInner propertiesInner02 = new PrivateLinkServiceIpConfigurationInner();
        propertiesInner02.withPrivateIpAllocationMethod(IpAllocationMethod.DYNAMIC);
        propertiesInner02.withPrivateIpAddressVersion(IpVersion.IPV4);
        propertiesInner02.withPrimary(false);
        propertiesInner02.withSubnet(new SubnetInner().withId(subnetName));
        propertiesInner01.withName("test-02");

        PrivateLinkServiceInner privateLinkServiceInner = new PrivateLinkServiceInner();
        privateLinkServiceInner
                .withLocation(region)
                .withTags(tags)
                .withAutoApproval(autoApproval)
                .withVisibility(propertiesVisibility)
                .withLoadBalancerFrontendIpConfigurations(Collections.singletonList(frontendIpConfigurationInner))
                .withIpConfigurations(Arrays.asList(propertiesInner01, propertiesInner02))
                .withEnableProxyProtocol(false)
                .withFqdns(Collections.emptyList());

        PrivateLinkServiceInner result = privateLinkServicesClient.createOrUpdate(resourceGroup, serviceName, privateLinkServiceInner);

        System.out.println(result);
    }

`

I was able to create the private link service successfully from the Azure Portal against the same Internal load balancer of the Kubernetes Cluster. I tried to compare the parameters set in that case with the ones I am setting above, couldn't find any significant difference. 

Any help is appreciated. 

 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ X ] Query Added
- [ X ] Setup information Added

**Comment by joshfree** [comment]
@weidongxu-microsoft could you please follow up with @kevinpat1987 on this issue?

**Comment by weidongxu-microsoft** [comment]
@kevinpat1987

Would you please give us the JSON from Portal? So that it might be easier for us to cross-check (redact anything you don't want to disclose).
