### ISSUE TITLE
[BUG] DefaultAzureCredential throws exception when azd is not installed

### ISSUE THREAD

**Issue by saragluna** [Azure/azure-sdk-for-java#33290]
**Describe the bug**
I was testing using the latest code on the main branch, but ran into the `ClientAuthenticationException` because `azd` command is not found on my local machine. 

***Exception or Stack Trace***
```console
Exception in thread "main" com.azure.core.exception.ClientAuthenticationException: DefaultAzureCredential authentication failed. ---> AzureDeveloperCliCredential authentication failed. Error Details: /bin/sh: azd: command not found
	at com.azure.identity.ChainedTokenCredential.getTokenSync(ChainedTokenCredential.java:113)
	at org.example.Main.main(Main.java:16)
Caused by: com.azure.core.exception.ClientAuthenticationException: /bin/sh: azd: command not found
	at com.azure.identity.implementation.IdentityClientBase.getTokenFromAzureDeveloperCLIAuthentication(IdentityClientBase.java:571)
	at com.azure.identity.implementation.IdentitySyncClient.authenticateWithAzureDeveloperCli(IdentitySyncClient.java:370)
	at com.azure.identity.AzureDeveloperCliCredential.getTokenSync(AzureDeveloperCliCredential.java:54)
	at com.azure.identity.ChainedTokenCredential.getTokenSync(ChainedTokenCredential.java:108)
```

**To Reproduce**
https://github.com/saragluna/test-azure-identity/tree/master

***Code Snippet***
```java
final TokenCredential credential = new DefaultAzureCredentialBuilder().build();
        final TokenRequestContext tokenRequestContext = new TokenRequestContext();
        tokenRequestContext.addScopes("https://servicebus.azure.net/.default");
        final AccessToken tokenSync = credential.getTokenSync(tokenRequestContext);
        System.out.println(tokenSync.getToken());
```

**Expected behavior**
No exception thrown.

**Screenshots**
N/a

**Setup (please complete the following information):**
 - OS: [MacOS]
 - IDE: [IntelliJ]
 - Library/Libraries: [azure-identity:1.8.0-beta.2]
 - Java version: [17]
 - App Server/Environment: [N/A]
 - Frameworks: [N/A] 

**Additional context**
N/A

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by billwert** [comment]
Thanks @saragluna! I've got a fix and we'll get it into the beta. Great catch!
