### ISSUE TITLE
[BUG] Native build exception when using Azure Core with other SLF4J implementation

### ISSUE THREAD

**Issue by saragluna** [Azure/azure-sdk-for-java#33328]
**Describe the bug**
PR https://github.com/Azure/azure-sdk-for-java/pull/33144 moved the native config files into each individual library. There will be a native build exception when trying to build a Spring Boot application with the new `azure-core`. And then I found that the issue exists when there's another SLF4J implementation on the classpath. 

***Exception or Stack Trace***
```console
Error: Classes that should be initialized at run time got initialized during image building:
 ch.qos.logback.classic.Logger was unintentionally initialized at build time. com.azure.core.util.Configuration caused initialization of this class with the following trace: 
        at ch.qos.logback.classic.Logger.<clinit>(Logger.java:47)
        at ch.qos.logback.classic.LoggerContext.<init>(LoggerContext.java:81)
        at ch.qos.logback.classic.spi.LogbackServiceProvider.initialize(LogbackServiceProvider.java:39)
        at org.slf4j.LoggerFactory.bind(LoggerFactory.java:167)
        at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:154)
        at org.slf4j.LoggerFactory.getProvider(LoggerFactory.java:437)
        at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:423)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:372)
        at com.azure.core.util.logging.ClientLogger.<init>(ClientLogger.java:101)
        at com.azure.core.util.logging.ClientLogger.<init>(ClientLogger.java:67)
        at com.azure.core.util.logging.ClientLogger.<init>(ClientLogger.java:57)
        at com.azure.core.util.Configuration.<clinit>(Configuration.java:227)
```

**To Reproduce**
Follow this https://github.com/saragluna/demo-azsdk-clientlogger sample project to reproduce the issue.

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**
There's no build error. 

**Setup (please complete the following information):**
 - OS: [MacOS]
 - IDE: [IntelliJ]
 - Library/Libraries: [com.azure:azure-core:1.36.0 ]
 - Java version: [17] 
 - Frameworks: [Spring Boot] 

**Additional context**
N/A

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by saragluna** [comment]
@srnagar could you take a look at this?

**Comment by srnagar** [comment]
Discussed this with @JonathanGiles and since logback and log4j are popular logging libraries, we'll include the configuration for these libraries in azure-core. Also, we'll consider making a contribution to the extensions repo to include these 3rd party configurations.

**Comment by saragluna** [comment]
Thanks @srnagar. What do you think is the root cause? Is it in the native build?
