### ISSUE TITLE
[BUG] SELECT DISTINCT on multiple columns of Cosmos DB throws DistinctContinuationToken exception for Springboot application

### ISSUE THREAD

**Issue by kalamannilvarughesev-nlg** [Azure/azure-sdk-for-java#33419]
**Issue**
We have a Spring Boot application which is using annotated query to fetch data from Cosmos DB and anytime we use a **SELECT DISTINCT on multiple columns**, we get the below error.

**Exception Stacktrace**
```
_com.azure.cosmos.implementation.BadRequestException: {"innerErrorMessage":"One of the input values is invalid.: DistinctContinuationToken is malformed. DistinctContinuationToken can not have a 'lastHash', when the query type is not ordered (ex SELECT DISTINCT VALUE c.blah FROM c ORDER BY c.blah)."}
       at com.azure.cosmos.implementation.query.DistinctDocumentQueryExecutionContext.createAsync(DistinctDocumentQueryExecutionContext.java:62)
       at com.azure.cosmos.implementation.query.PipelinedDocumentQueryExecutionContext.lambda$createDistinctPipelineComponentFunction$3(PipelinedDocumentQueryExecutionContext.java:103)
       at com.azure.cosmos.implementation.query.PipelinedDocumentQueryExecutionContext.createAsyncCore(PipelinedDocumentQueryExecutionContext.java:172)
       at com.azure.cosmos.implementation.query.PipelinedQueryExecutionContextBase.createAsync(PipelinedQueryExecutionContextBase.java:62)
       at com.azure.cosmos.implementation.query.DocumentQueryExecutionContextFactory.createSpecializedDocumentQueryExecutionContextAsync(DocumentQueryExecutionContextFactory.java:383)
       at com.azure.cosmos.implementation.query.DocumentQueryExecutionContextFactory.lambda$createDocumentQueryExecutionContextAsync$5(DocumentQueryExecutionContextFactory.java:293)
       at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:125)
       at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1839)
       at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:249)
       at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:122)
       at reactor.core.publisher.Operators$MonoInnerProducerBase.complete(Operators.java:2666)
       at reactor.core.publisher.MonoSingle$SingleSubscriber.onComplete(MonoSingle.java:180)
       at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1840)
       at reactor.core.publisher.MonoTakeLastOne$TakeLastOneSubscriber.onComplete(MonoTakeLastOne.java:120)
       at reactor.core.publisher.FluxTakeUntil$TakeUntilPredicateSubscriber.onComplete(FluxTakeUntil.java:121)
       at reactor.core.publisher.FluxTakeUntil$TakeUntilPredicateSubscriber.onNext(FluxTakeUntil.java:99)
       at reactor.core.publisher.FluxRepeat$RepeatSubscriber.onNext(FluxRepeat.java:90)
       at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1839)
       at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151)
       at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129)
       at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129)
       at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129)
       at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1839)
       at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151)
       at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
       at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:122)
       at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
       at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1839)
       at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151)
       at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1839)
       at reactor.core.publisher.MonoCacheTime.subscribeOrReturn(MonoCacheTime.java:151)
       at reactor.core.publisher.FluxFromMonoOperator.subscribe(FluxFromMonoOperator.java:76)
       at reactor.core.publisher.FluxDefer.subscribe(FluxDefer.java:54)
       at reactor.core.publisher.FluxRepeat$RepeatSubscriber.resubscribe(FluxRepeat.java:120)
       at reactor.core.publisher.FluxRepeat$RepeatSubscriber.onComplete(FluxRepeat.java:104)
       at reactor.core.publisher.FluxRepeat.subscribeOrReturn(FluxRepeat.java:55)
       at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
       at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157)
       at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:99)
       at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.onNext(FluxRetryWhen.java:174)
       at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1839)
       at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151)
       at reactor.core.publisher.Operators$MonoInnerProducerBase.complete(Operators.java:2666)
       at reactor.core.publisher.MonoSingle$SingleSubscriber.onComplete(MonoSingle.java:180)
       at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onComplete(FluxMapFuseable.java:152)
       at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1840)
       at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:249)
       at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.complete(MonoIgnoreThen.java:292)
       at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onNext(MonoIgnoreThen.java:187)
       at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:236)
       at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51)
       at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157)
       at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
       at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.complete(MonoIgnoreThen.java:292)
       at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onNext(MonoIgnoreThen.java:187)
       at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:99)
       at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.onNext(FluxRetryWhen.java:174)
       at reactor.core.publisher.Operators$MonoInnerProducerBase.complete(Operators.java:2666)
       at reactor.core.publisher.MonoSingle$SingleSubscriber.onComplete(MonoSingle.java:180)
       at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onComplete(Operators.java:2060)
       at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onComplete(FluxMapFuseable.java:152)
       at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1840)
       at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:249)
       at reactor.core.publisher.Operators$MonoInnerProducerBase.complete(Operators.java:2666)
       at reactor.core.publisher.MonoSingle$SingleSubscriber.onComplete(MonoSingle.java:180)
       at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144)
       at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FluxSwitchIfEmpty.java:85)
       at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:260)
       at reactor.core.publisher.FluxHandle$HandleSubscriber.onComplete(FluxHandle.java:220)
       at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onComplete(FluxMap.java:275)
       at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onComplete(FluxDoFinally.java:128)
       at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onComplete(FluxHandleFuseable.java:236)
       at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onComplete(FluxContextWrite.java:126)
       at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1840)
       at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:129)
       at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:260)
       at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144)
       at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:415)
       at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:424)
       at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:478)
       at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:712)
       at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:113)
       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
       at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
       at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
       at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
       at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
       at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1373)
       at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1247)
       at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1287)
       at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
       at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
       at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
       at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
       at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
       at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
       at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
       at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
       at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
       at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
       at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
       at java.base/java.lang.Thread.run(Thread.java:833)_
```

**Code Snippet**
```
Annotated Query - @Query(value = "SELECT DISTINCT ui.firstName, ui.lastName FROM UserInfo ui")
Pagination - new CosmosPageRequest(pageNumber, pageSize, null, sort);
```

As you can see above, we are passing null for the requestContinuation value, since we dont intend use it.

**Setup**
 - OS: Windows
 - IDE: Spring Tool Suite
 - Library/Libraries: com.azure.spring:spring-cloud-azure-starter-data-cosmos:4.5.0
 - Java version: 11
 - App Server/Environment: Tomcat
 - Frameworks: Spring Boot(2.7.8)

**Comment by kalamannilvarughesev-nlg** [comment]
@kushagraThapar  @TheovanKraay :
Looks like its happening every time we use the keyword DISTINCT irrespective of the number of columns we are applying DISTINCT on. I just tried on one column and that also is failing with the same error. Showing below is a more accurate pseudo representation of our repository layer:

```
@Query(value = "SELECT DISTINCT ui.firstname, ui.lastname FROM UserInfo ui"
            + " WHERE ui.streetNumber=@streetNumber AND CONTAINS(ui.streetName,@streetName)")
Page<Person> getPersonByStreetNumberAndStreetName(
            @Param("streetNumber") String streetNumber, @Param("streetName") String streetName, Pageable pageable);
```

Even if I try the below code, Im getting the same error - I'm applying distinct on one column name.
```
@Query(value = "SELECT DISTINCT ui.firstname FROM UserInfo ui"
            + " WHERE ui.streetNumber=@streetNumber AND CONTAINS(ui.streetName,@streetName)")
Page<PersonName> getPersonByStreetNumberAndStreetName(
            @Param("streetNumber") String streetNumber, @Param("streetName") String streetName, Pageable pageable);
```

**Comment by TheovanKraay** [comment]
@trande4884 can you take a look at this?

**Comment by trande4884** [comment]
Even if you are passing null for the current continuation token, pagination can only happen with the use of continuation tokens in the background which must be used if you try to retrieve the next page. So in order to use distinct with pagination you must add an Order By clause.

**Comment by trande4884** [comment]
Closing due to lack of activity.
