### ISSUE TITLE
[BUG] Getting "ReactorDispatcher instance is closed..." on a `ServiceBusProcessorClient` mainly during idle periods.

### ISSUE THREAD

**Issue by rangarnow** [Azure/azure-sdk-for-java#33499]
**Describe the bug**

**Background:**
Hi, we are using `ServiceBusProcessorClient` to receive messages from two queues. For that, we are creating two separate `ServiceBusProcessorClient`, each for one queue.
Each processor is working in peek lock mode, have disabled auto complete and we do complete/abandon/dead letter messages manually. Also, it's using `maxConcurrentCalls` feature to receive few messages at once (we do use `maxAutoLockRenewDuration` as well). Code is similar to provided https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/servicebus/azure-messaging-servicebus/src/samples/java/com/azure/messaging/servicebus/ServiceBusProcessorPeekLockReceiveSample.java.

What's worth to notice is that we never close processor, as we would like to keep infinite stream of messages.

I was searching over this repo for a reason and did a check list:
- https://github.com/Azure/azure-sdk-for-java/issues/31793#issuecomment-1295280718 comment,
- this message may be false positive, as processor is recovered and level should be changed to "warning" - https://github.com/Azure/azure-service-bus-java/issues/418#issuecomment-944827183

but none is answering for to problem completely.

-------------
**Issue:**
We are receiving messages about closed link like this mostly due to inactive period. It happens as well from time to time for processing message, but it seems that it's always due to inactive period. Is this really something we should ignore or there is a room for an improvement (automatic pooling the connection every x minutes to keep active link etc.)?
![image](https://user-images.githubusercontent.com/92714803/218670282-81f951e3-d451-4706-92e1-97c86d72fd48.png)

***Exception or Stack Trace***
```
java.util.concurrent.RejectedExecutionException: ReactorDispatcher instance is closed. Should not continue dispatching work to this reactor.
	at com.azure.core.amqp.implementation.ReactorDispatcher.throwIfSchedulerError(ReactorDispatcher.java:139)
	at com.azure.core.amqp.implementation.ReactorDispatcher.invoke(ReactorDispatcher.java:103)
	at com.azure.core.amqp.implementation.ReactorConnection.lambda$closeAsync$26(ReactorConnection.java:472)
	at reactor.core.publisher.MonoRunnable.subscribe(MonoRunnable.java:49)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:240)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:203)
	at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.withActiveSpan(TracingSubscriber.java:86)
	at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.onComplete(TracingSubscriber.java:72)
	at reactor.core.publisher.MonoWhen$WhenCoordinator.signal(MonoWhen.java:213)
	at reactor.core.publisher.MonoWhen$WhenInner.onComplete(MonoWhen.java:293)
	at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.withActiveSpan(TracingSubscriber.java:86)
	at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.onComplete(TracingSubscriber.java:72)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onComplete(FluxDoFinally.java:128)
	at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.withActiveSpan(TracingSubscriber.java:86)
	at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.onComplete(TracingSubscriber.java:72)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondComplete(MonoFlatMap.java:196)
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onComplete(MonoFlatMap.java:268)
	at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.withActiveSpan(TracingSubscriber.java:86)
	at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.onComplete(TracingSubscriber.java:72)
	at reactor.core.publisher.MonoSubscribeOn$SubscribeOnSubscriber.onComplete(MonoSubscribeOn.java:162)
	at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.withActiveSpan(TracingSubscriber.java:86)
	at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.onComplete(TracingSubscriber.java:72)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onComplete(Operators.java:2060)
	at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.withActiveSpan(TracingSubscriber.java:86)
	at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.onComplete(TracingSubscriber.java:72)
	at reactor.core.publisher.SerializedSubscriber.onComplete(SerializedSubscriber.java:146)
	at reactor.core.publisher.SerializedSubscriber.onComplete(SerializedSubscriber.java:146)
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.onComplete(FluxTimeout.java:234)
	at reactor.core.publisher.Operators$MonoInnerProducerBase.complete(Operators.java:2671)
	at reactor.core.publisher.SinkEmptyMulticast.tryEmitEmpty(SinkEmptyMulticast.java:86)
	at reactor.core.publisher.SinkEmptySerialized.tryEmitEmpty(SinkEmptySerialized.java:46)
	at reactor.core.publisher.InternalEmptySink.emitEmpty(InternalEmptySink.java:26)
	at com.azure.core.amqp.implementation.RequestResponseChannel.onTerminalState(RequestResponseChannel.java:455)
	at com.azure.core.amqp.implementation.RequestResponseChannel.lambda$closeAsync$9(RequestResponseChannel.java:254)
	at reactor.core.publisher.MonoRunnable.subscribe(MonoRunnable.java:49)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4490)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103)
	at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.lambda$onError$2(TracingSubscriber.java:67)
	at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.withActiveSpan(TracingSubscriber.java:86)
	at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.onError(TracingSubscriber.java:67)
	at reactor.core.publisher.SerializedSubscriber.onError(SerializedSubscriber.java:124)
	at reactor.core.publisher.SerializedSubscriber.onError(SerializedSubscriber.java:124)
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.handleTimeout(FluxTimeout.java:295)
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.doTimeout(FluxTimeout.java:280)
	at reactor.core.publisher.FluxTimeout$TimeoutTimeoutSubscriber.onNext(FluxTimeout.java:419)
	at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.lambda$onNext$1(TracingSubscriber.java:62)
	at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.withActiveSpan(TracingSubscriber.java:86)
	at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.onNext(TracingSubscriber.java:62)
	at reactor.core.publisher.FluxOnErrorReturn$ReturnSubscriber.onNext(FluxOnErrorReturn.java:162)
	at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.lambda$onNext$1(TracingSubscriber.java:62)
	at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.withActiveSpan(TracingSubscriber.java:86)
	at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.onNext(TracingSubscriber.java:62)
	at reactor.core.publisher.MonoDelay$MonoDelayRunnable.propagateDelay(MonoDelay.java:271)
	at reactor.core.publisher.MonoDelay$MonoDelayRunnable.run(MonoDelay.java:286)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**To Reproduce**
I don't know actually what could be helpful to investigate that other than attached. Please let me know if any additional clarification is needed.

***Code Snippet***
Pseudo code:

```java
private void startProcessor(ServiceBusClientBuilder serviceBusClientBuilder,
                                             String queueName, Integer maxConcurrentRequests) {
        ServiceBusProcessorClient processor = serviceBusClientBuilder
                .processor()
                .queueName(queueName)
                .processMessage(pc -> processMessage(pc))
                .processError(this::processError)
                .receiveMode(ServiceBusReceiveMode.PEEK_LOCK)
                .maxConcurrentCalls(maxConcurrentRequests)
                .disableAutoComplete()
                .maxAutoLockRenewDuration(Duration.ofMinutes(180))
                .buildProcessorClient();

        processor.start();
    }

private void processMessage(ServiceBusReceivedMessageContext context) {
        Data data = doSomeAsyncReactorProcessing(context.getMessage()).block();

        if (data.isOk()) {
           context.complete();
        } else {
           if (shouldMoveToDeadLetter()) {
              context.deadLetter();
           } else {
              context.abandon();
           }
        }
    }
```

Also we annotate some methods in code with open telemetry `@WithSpan`.

**Expected behavior**
No exception is being thrown.

**Screenshots**

**Setup (please complete the following information):**
- Java 17,
- Service bus sdk - 7.13.1
- opentelemetry-instrumentation-annotations - 1.22.1

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by anuchandy** [comment]
Hi @rangarnow, You can ignore these logs; these are associated with connection recovery.

To give you some context, internally, a simplified view of the resources looks like

1. One _Connection_ resource backing Processor instances.
2. One _Event-Loop_ thread resource responsible for -
    * Processing the _Connection_ events coming on the wire.
    * Processing special library actions scheduled through a resource called _Dispatcher_.
3. Some work (e.g., lock renew) on other threads have to be dispatched to _Event-Loop_ thread using _Dispatcher_.
4. The lifetime of the _Event-Loop_ and _Dispatcher_ resources are scoped to the _Connection_. So when the current _Connection_ goes down, the library disposes these resources and obtain NEW _Connection_, _Event-Loop_ and _Dispatcher_.
5. While these dispositions (point_4) are in progress, the other threads running concurrently attempt to dispatch some work to the _Dispatcher_. Such actions from other threads are rejected, and the rejections can manifest as "RejctedExecutionException" / "ChannelInterruptedException"
6. Eventually, a new Connection is created to resume the message processing.

One reason the Connection goes down is when the Service Bus server identifies that the Connection is idle, this is normal and the library reconnects when it happens.

We're working on some designs that replace eager reconnect with reactive reconnect, which should help to removing some occurrence of these log instances.

Hope this explanation helps.

**Comment by rangarnow** [comment]
hi @anuchandy , indeed I did not saw any real effect on user experience because of that, but technically I was curious and didn't want to ignore potential dangerous exceptions.

Thanks for that, I am looking forward for the next updates!
