### ISSUE TITLE
[BUG] Azure Blob Storage SDK 12.20.2 breaks parsing of connection strings for Azurite emulator [REGRESSION]

### ISSUE THREAD

**Issue by jfurmankiewiczpros** [Azure/azure-sdk-for-java#33671]
**Describe the bug**

As of 12.20.2, the following connection string to locally running Azurite blob emulator

DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;EndpointSuffix=0.0.0.0:10000;

fails with "Host is not specified error".

This has worked fine with all previous versions of the SDK, all the way up to 12.20.1. 
It broke in 12.20.2

"com.azure:azure-storage-blob:12.20.2"

Impact is major, as it fails ALL integration tests across entire company.
No one can upgrade any more to newest SDK, as we all use Azurite for locally running integration tests.

***Exception or Stack Trace***

```java
Host is not specified
java.lang.IllegalArgumentException: Host is not specified
	at reactor.netty.http.client.UriEndpointFactory.createUriEndpoint(UriEndpointFactory.java:78)
	at reactor.netty.http.client.HttpClientConnect$HttpClientHandler.<init>(HttpClientConnect.java:508)
	at reactor.netty.http.client.HttpClientConnect$MonoHttpConnect.subscribe(HttpClientConnect.java:208)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
	at reactor.core.publisher.FluxRetryWhen.subscribe(FluxRetryWhen.java:77)
	at reactor.core.publisher.MonoRetryWhen.subscribeOrReturn(MonoRetryWhen.java:46)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4475)
	at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:200)
	at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4475)
	at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:203)
	at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4475)
	at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:200)
	at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4490)
	at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:203)
	at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53)
	at reactor.core.publisher.Flux.subscribe(Flux.java:8628)
	at reactor.core.publisher.Flux.blockLast(Flux.java:2760)
	at com.azure.core.util.paging.ContinuablePagedByIteratorBase.requestPage(ContinuablePagedByIteratorBase.java:102)
	at com.azure.core.util.paging.ContinuablePagedByItemIterable$ContinuablePagedByItemIterator.<init>(ContinuablePagedByItemIterable.java:75)
	at com.azure.core.util.paging.ContinuablePagedByItemIterable.iterator(ContinuablePagedByItemIterable.java:55)
	at com.azure.core.util.paging.ContinuablePagedIterable.iterator(ContinuablePagedIterable.java:141)
```

**To Reproduce**

***Code Snippet***

```
var builder = new BlobServiceClientBuilder().connectionString("DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;EndpointSuffix=0.0.0.0:10000;
;");

 var client =  builder.buildClient();

// invoke any type of client operation, e.g.
client. listBlobContainers().forEach(bc -> bc.setDeleted(true))
```

**Expected behavior**

It should connect fine to Azurite using this connection string as it has done in all previous versions of SDK,
all the way up to 12.20.1

**Screenshots**

**Setup (please complete the following information):**
 - OS: Ubuntu
 - IDE: IntellIJ
 - Library/Libraries: "com.azure:azure-storage-blob:12.20.2"
 - Java version: 17
 - App Server/Environment: Standalone library
 - Frameworks: all

**Additional context**

URGENT: stops all teams from upgrading to newer versions of SDK until this is fxied

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X ] Bug Description Added
- [ X] Repro Steps Added
- [ X] Setup information Added

**Comment by jfurmankiewiczpros** [comment]
Just as some extra context. we usually run Azurite in Docker Compose with its 10000 port mapped to 0.0.0.0:10000 on the developer's PC,hence the connection string points to 0.0.0.0:100000

**Comment by alzimmermsft** [comment]
Thanks for filing this issue @jfurmankiewiczpros. It would appear that a change from using Reactor Netty's `HttpClient.uri(String)` to `HttpClient.uri(URI)` is the cause of this regression, I'll get that changed. In the meanwhile to unblock you, is it possible to change the connection string being used from

`DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;EndpointSuffix=0.0.0.0:10000;`

to 

`"DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://0.0.0.0:10000/devstorageaccount1;`

I've tested this locally and this doesn't run into the same issue. Something with how the URL is created with the first connection string results in the URI created with `URI.create` to not have a host part.

**Comment by jfurmankiewiczpros** [comment]
thank you for the workaround, let me test on our end and verify that it works

**Comment by jfurmankiewiczpros** [comment]
hi @alzimmermsft  this change did not work for me.

Using 12.20.2, when I change the connection string to

DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://0.0.0.0:10000/devstorageaccount1

I get this error on any operation against the container, I've seen this in 2 separate apps I tried:

```
2023-02-22 22:53:52,479 ERROR c.p.c.j.e.AbstractExceptionMapper - Status code 400, "<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Error>
  <Code>InvalidOperation</Code>
  <Message>Invalid storage account.
RequestId:5a28bfcf-36ca-42e2-9a37-7e21c22c35e7
Time:2023-02-22T22:53:52.363Z</Message>
</Error>" localizedMessage="Internal server error. Please contact PROS Support." tid=? eid=? rid=PRC-bc6fcff1903ebfb6 errorID=INTERNAL_SERVER_ERROR statusCode=500 errorMessage="Status code 400, \"<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>
<Error>
  <Code>InvalidOperation</Code>
  <Message>Invalid storage account.
RequestId:5a28bfcf-36ca-42e2-9a37-7e21c22c35e7
Time:2023-02-22T22:53:52.363Z</Message>
</Error>\""
! com.azure.storage.blob.models.BlobStorageException: Status code 400, "<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
! <Error>
!   <Code>InvalidOperation</Code>
!   <Message>Invalid storage account.
! RequestId:5a28bfcf-36ca-42e2-9a37-7e21c22c35e7
! Time:2023-02-22T22:53:52.363Z</Message>
! </Error>"
! at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
! at com.azure.core.implementation.http.rest.ResponseExceptionConstructorCache.invoke(ResponseExceptionConstructorCache.java:56)
! at com.azure.core.implementation.http.rest.RestProxyBase.instantiateUnexpectedException(RestProxyBase.java:377)
! at com.azure.core.implementation.http.rest.AsyncRestProxy.lambda$ensureExpectedStatus$1(AsyncRestProxy.java:116)
! at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:113)
! at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2400)
! at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:171)
! at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:2196)
! at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:2070)
! at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:96)
! at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:55)
! at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
! at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157)
! at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129)
! at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onNext(FluxHide.java:137)
! at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129)
! at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129)
! at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onNext(FluxHide.java:137)
! at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
! at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1839)
! at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151)
! at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129)
! at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129)
! at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129)
! at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1839)
! at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151)
! at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:99)
! at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.onNext(FluxRetryWhen.java:174)
! at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
! at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1839)
! at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151)
! at reactor.core.publisher.Operators$MonoInnerProducerBase.complete(Operators.java:2666)
! at reactor.core.publisher.MonoSingle$SingleSubscriber.onComplete(MonoSingle.java:180)
! at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onComplete(MonoFlatMapMany.java:260)
! at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onComplete(FluxContextWrite.java:126)
! at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onComplete(FluxMap.java:275)
! at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FluxSwitchIfEmpty.java:85)
! at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onComplete(FluxDoFinally.java:128)
! at reactor.core.publisher.FluxHandle$HandleSubscriber.onComplete(FluxHandle.java:220)
! at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onComplete(FluxMap.java:275)
! at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onComplete(FluxDoFinally.java:128)
! at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onComplete(FluxHandleFuseable.java:236)
! at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onComplete(FluxContextWrite.java:126)
! at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1840)
! at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:129)
! at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:260)
! at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144)
! at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:413)
! at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:419)
! at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:473)
! at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:702)
! at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:113)
! at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
! at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
! at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
! at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
! at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
! at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
! at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
! at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
! at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
! at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
! at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
! at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
! at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
! at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
! at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
! at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
! at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
! at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
! at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
! at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
! at java.base/java.lang.Thread.run(Thread.java:833)
! Suppressed: java.lang.Exception: #block terminated with an error
! 	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
! 	at reactor.core.publisher.Mono.block(Mono.java:1742)
! 	at com.azure.storage.common.implementation.StorageImplUtils.blockWithOptionalTimeout(StorageImplUtils.java:129)
! 	at com.azure.storage.blob.BlobContainerClient.createIfNotExistsWithResponse(BlobContainerClient.java:374)
! 	at com.azure.storage.blob.BlobServiceClient.createBlobContainerIfNotExistsWithResponse(BlobServiceClient.java:210)
! 	at com.azure.storage.blob.BlobServiceClient.createBlobContainerIfNotExists(BlobServiceClient.java:172)
! 	at com.pros.commons.azure.blob.BlobStoreService.lambda$getContainerClient$12(BlobStoreService.java:407)
```

**Comment by jfurmankiewiczpros** [comment]
tested with 12.20.3 as well, same error as well

**Comment by alzimmermsft** [comment]
@jfurmankiewiczpros, this is my bad looks like I copied and pasted bad, should have been

`DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://0.0.0.0:10000/devstoreaccount1;`

Where I changed `devstoreaccount1` to `devstorageaccount1`

**Comment by jfurmankiewiczpros** [comment]
ah yes, good catch, thanks for noticing this.

Tested with 2 apps, this works fine. We can handle this workaround, thank you for identifying this.
