### ISSUE TITLE
[BUG] NullPointerException when calling ServiceBusReceiverAsyncClient.isConnectionClosed

### ISSUE THREAD

**Issue by KarimizandiA** [Azure/azure-sdk-for-java#33851]
**Describe the bug**
Sometimes when I try to use ServiceBusReceiverAsyncClient I get NullPointerException

**Exception or Stack Trace**
java.lang.NullPointerException: Cannot invoke \"com.azure.messaging.servicebus.ServiceBusReceiverAsyncClient.isConnectionClosed()\" because the return value of \"java.util.concurrent.atomic.AtomicReference.get()\" is null
at com.azure.messaging.servicebus.ServiceBusProcessorClient.lambda$start$0(ServiceBusProcessorClient.java:260)
at reactor.core.scheduler.PeriodicSchedulerTask.call(PeriodicSchedulerTask.java:49)
at reactor.core.scheduler.PeriodicSchedulerTask.run(PeriodicSchedulerTask.java:63)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)\n

**To Reproduce**
This issue is coming randomly.

**Expected behavior**
ServiceBusReceiverClient should consume the messages available in subscription.

**Comment by anuchandy** [comment]
Thanks @KarimizandiA; I see a route where this can happen when a thread moving works to a new receiver race with the thread making the connection check. Will open a pr with null check

**Comment by anuchandy** [comment]
The on-going work related to AMQP V2 stack redesigns the ProcessorClient such that the logic leading to this race condition no longer exists. Linking the V2 Stack PR https://github.com/Azure/azure-sdk-for-java/pull/34854 for tracking.

**Comment by anuchandy** [comment]
Resolving this. Refer https://learn.microsoft.com/en-us/azure/developer/java/sdk/troubleshooting-messaging-service-bus-overview#upgrade-to-715x
