### ISSUE TITLE
[BUG] ServiceBusSessionManager.close() calls Mono.block()

### ISSUE THREAD

**Issue by lgw-spyrosoft** [Azure/azure-sdk-for-java#33867]
Sometime to time, the application stops to receive messages from the queue and never get recover. I guess its because the issue below

`ServiceBusProcessorClient.onError(Throwable t)` here, app tries to renew connection and eventually reach `ServiceBusSessionManager.close()`. And then,

```
final List<Mono<Void>> closeables = sessionReceivers.values().stream()
    .map(receiver -> receiver.closeAsync())
    .collect(Collectors.toList());

Mono.when(closeables).block(operationTimeout);
sessionReceiveSink.complete();
```

block() throws an exception (stacktrace below). As its ran in boundedElastic schedulerer, the exception in inevitable even though the closable list is empty.

***Exception or Stack Trace***

```
2023-03-05 14:32:35.380 ERROR 290808 --- [ctor-executor-1] .s.i.s.i.ServiceBusInboundChannelAdapter : Error in the operation RECEIVE occurred on entity xxx. Error: {}

java.lang.IllegalStateException: block()/blockFirst()/blockLast() are blocking, which is not supported in thread reactor-executor-1
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:117)
	at reactor.core.publisher.Mono.block(Mono.java:1731)
	at com.azure.messaging.servicebus.ServiceBusSessionManager.close(ServiceBusSessionManager.java:241)
	at com.azure.messaging.servicebus.ServiceBusReceiverAsyncClient.close(ServiceBusReceiverAsyncClient.java:1309)
	at com.azure.messaging.servicebus.ServiceBusProcessorClient.restartMessageReceiver(ServiceBusProcessorClient.java:488)
	at com.azure.messaging.servicebus.ServiceBusProcessorClient.access$900(ServiceBusProcessorClient.java:123)
	at com.azure.messaging.servicebus.ServiceBusProcessorClient$1.onError(ServiceBusProcessorClient.java:381)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:106)
	at reactor.core.publisher.Operators.error(Operators.java:198)
	at reactor.core.publisher.MonoError.subscribe(MonoError.java:53)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4400)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.doError(FluxPublishOn.java:511)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.checkTerminated(FluxPublishOn.java:549)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runAsync(FluxPublishOn.java:432)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:527)
	at reactor.core.scheduler.ImmediateScheduler$ImmediateSchedulerWorker.schedule(ImmediateScheduler.java:84)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.trySchedule(FluxPublishOn.java:312)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.onError(FluxPublishOn.java:248)
	at com.azure.messaging.servicebus.FluxAutoComplete$AutoCompleteSubscriber.hookOnError(FluxAutoComplete.java:118)
	at reactor.core.publisher.BaseSubscriber.onError(BaseSubscriber.java:180)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.checkTerminated(FluxFlatMap.java:842)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:608)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.drain(FluxFlatMap.java:588)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.innerError(FluxFlatMap.java:863)
	at reactor.core.publisher.FluxFlatMap$FlatMapInner.onError(FluxFlatMap.java:990)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onError(MonoFlatMapMany.java:204)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:172)
	at reactor.core.publisher.SerializedSubscriber.onError(SerializedSubscriber.java:124)
	at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.whenError(FluxRetryWhen.java:225)
	at reactor.core.publisher.FluxRetryWhen$RetryWhenOtherSubscriber.onError(FluxRetryWhen.java:274)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.checkTerminated(FluxFlatMap.java:842)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:608)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.drain(FluxFlatMap.java:588)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onError(FluxFlatMap.java:451)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:416)
	at reactor.core.publisher.EmitterProcessor.drain(EmitterProcessor.java:491)
	at reactor.core.publisher.EmitterProcessor.tryEmitNext(EmitterProcessor.java:299)
	at reactor.core.publisher.SinkManySerialized.tryEmitNext(SinkManySerialized.java:100)
	at reactor.core.publisher.InternalManySink.emitNext(InternalManySink.java:27)
	at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.onError(FluxRetryWhen.java:190)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondError(MonoFlatMap.java:192)
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onError(MonoFlatMap.java:259)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onError(MonoIgnoreThen.java:278)
	at reactor.core.publisher.SerializedSubscriber.onError(SerializedSubscriber.java:124)
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.onError(FluxTimeout.java:219)
	at reactor.core.publisher.FluxTakeUntil$TakeUntilPredicateSubscriber.onError(FluxTakeUntil.java:111)
	at reactor.core.publisher.SerializedSubscriber.onError(SerializedSubscriber.java:124)
	at reactor.core.publisher.FluxTakeUntilOther$TakeUntilMainSubscriber.onError(FluxTakeUntilOther.java:231)
	at reactor.core.publisher.FluxDistinctUntilChanged$DistinctUntilChangedSubscriber.onError(FluxDistinctUntilChanged.java:162)
	at reactor.core.publisher.FluxReplay$SizeBoundReplayBuffer.replayNormal(FluxReplay.java:844)
	at reactor.core.publisher.FluxReplay$SizeBoundReplayBuffer.replay(FluxReplay.java:944)
	at reactor.core.publisher.FluxReplay$ReplaySubscriber.onError(FluxReplay.java:1339)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:222)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:222)
	at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:132)
	at reactor.core.publisher.FluxDistinctUntilChanged$DistinctUntilChangedSubscriber.onError(FluxDistinctUntilChanged.java:162)
	at reactor.core.publisher.FluxReplay$SizeBoundReplayBuffer.replayNormal(FluxReplay.java:844)
	at reactor.core.publisher.FluxReplay$SizeBoundReplayBuffer.replay(FluxReplay.java:944)
	at reactor.core.publisher.ReplayProcessor.tryEmitError(ReplayProcessor.java:488)
	at reactor.core.publisher.SinkManySerialized.tryEmitError(SinkManySerialized.java:82)
	at reactor.core.publisher.InternalManySink.emitError(InternalManySink.java:98)
	at com.azure.core.amqp.implementation.handler.Handler.onError(Handler.java:114)
	at com.azure.core.amqp.implementation.handler.LinkHandler.handleRemoteLinkClosed(LinkHandler.java:123)
	at com.azure.core.amqp.implementation.handler.LinkHandler.onLinkRemoteClose(LinkHandler.java:64)
	at com.azure.core.amqp.implementation.handler.ReceiveLinkHandler.onLinkRemoteClose(ReceiveLinkHandler.java:228)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:176)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291)
	at com.azure.core.amqp.implementation.ReactorExecutor.run(ReactorExecutor.java:91)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**To Reproduce**
Create ServiceBus Session Queue, run application, change session queue status to ReceiveDisable, exception is thrown, set back "Active" status - the consumption is not recovered.

***Code Snippet***
`Mono.when(closeables).block(operationTimeout);` 

**Expected behavior**
No exception expected

**Setup (please complete the following information):**
Create ServiceBus session queue, run application (key dependecy: `implementation 'com.azure.spring:spring-cloud-azure-stream-binder-servicebus:4.4.1'`)

**Mitigation**
maybe you can enclose `Mono.when(closeables).block(operationTimeout);` to `if(!closables.isEmpty)`

**Comment by anuchandy** [comment]
Hello @lgw-spyrosoft, thank for looking at the code. I also had a look at the stack trace, and this problem of blocking the non-blocking thread is fixed in the [pr](https://github.com/Azure/azure-sdk-for-java/pull/33386). Can you update to "com.azure:azure-messaging-servicebus:7.13.2" [version-7.13.2](https://central.sonatype.com/artifact/com.azure/azure-messaging-servicebus/7.13.2)? 

Closing this ticket as this is addressed, let us know if you encounter the same error "_java.lang.IllegalStateException: block()/blockFirst()/blockLast() are blocking..._" in 7.13.2

**Comment by JRiggenbach** [comment]
@anuchandy Having run 7.13.4 in our production env for a few weeks; we have seen this error on occasion and the only recourse we have at the moment is to restart the application instance to get it to start receiving messages again.  Any suggestions on how this should be handled?

**Comment by anuchandy** [comment]
Hi Josh, David reached out to me on this.

Could you share the following -
1. complete stack trace of the error.
2. logs (preferably debug level) -10 min from this error

These info should help us to understand the events that led to this problem, and threads get injected into the problematic path.

**Comment by JRiggenbach** [comment]
@anuchandy Thanks for the response.  We're working on a way to isolate just the one particular session based processor client that is running into this issue so we can turn on the verbose logging and not be overwhelmed.  We'll keep you posted...thanks again.

**Comment by JRiggenbach** [comment]
@anuchandy Here is the latest stack trace when running with the 7.13.4 SDK...

`{"timestamp":"2023-06-12 15:24:34.338","message":"Error when receiving messages from Entity: 'eligibility/subscriptions/Standard'. Exception: {}","logger":"com.mckesson.core.messaging.MessageHandler","thread":"parallel-2","level":"ERROR","exception":"java.lang.IllegalStateException: block()/blockFirst()/blockLast() are blocking, which is not supported in thread parallel-2\n\tat reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:117)\n\tat reactor.core.publisher.Mono.block(Mono.java:1731)\n\tat com.azure.messaging.servicebus.ServiceBusSessionManager.close(ServiceBusSessionManager.java:238)\n\tat com.azure.messaging.servicebus.ServiceBusReceiverAsyncClient.close(ServiceBusReceiverAsyncClient.java:1355)\n\tat com.azure.messaging.servicebus.ServiceBusProcessorClient.restartMessageReceiver(ServiceBusProcessorClient.java:477)\n\tat com.azure.messaging.servicebus.ServiceBusProcessorClient.access$800(ServiceBusProcessorClient.java:148)\n\tat com.azure.messaging.servicebus.ServiceBusProcessorClient$1.onError(ServiceBusProcessorClient.java:418)\n\tat reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:106)\n\tat reactor.core.publisher.Operators.error(Operators.java:198)\n\tat reactor.core.publisher.MonoError.subscribe(MonoError.java:53)\n\tat reactor.core.publisher.Mono.subscribe(Mono.java:4455)\n\tat reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103)\n\tat reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.doError(FluxPublishOn.java:511)\n\tat reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.checkTerminated(FluxPublishOn.java:549)\n\tat reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runAsync(FluxPublishOn.java:432)\n\tat reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:527)\n\tat reactor.core.scheduler.ImmediateScheduler$ImmediateSchedulerWorker.schedule(ImmediateScheduler.java:84)\n\tat reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.trySchedule(FluxPublishOn.java:312)\n\tat reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.onError(FluxPublishOn.java:248)\n\tat com.azure.messaging.servicebus.FluxAutoComplete$AutoCompleteSubscriber.hookOnError(FluxAutoComplete.java:118)\n\tat reactor.core.publisher.BaseSubscriber.onError(BaseSubscriber.java:180)\n\tat com.azure.messaging.servicebus.FluxAutoComplete$AutoCompleteSubscriber.applyWithCatch(FluxAutoComplete.java:156)\n\tat com.azure.messaging.servicebus.FluxAutoComplete$AutoCompleteSubscriber.hookOnNext(FluxAutoComplete.java:95)\n\tat com.azure.messaging.servicebus.FluxAutoComplete$AutoCompleteSubscriber.hookOnNext(FluxAutoComplete.java:55)\n\tat reactor.core.publisher.BaseSubscriber.onNext(BaseSubscriber.java:160)\n\tat com.azure.messaging.servicebus.FluxTrace$TracingSubscriber.hookOnNext(FluxTrace.java:65)\n\tat com.azure.messaging.servicebus.FluxTrace$TracingSubscriber.hookOnNext(FluxTrace.java:36)\n\tat reactor.core.publisher.BaseSubscriber.onNext(BaseSubscriber.java:160)\n\tat reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:712)\n\tat reactor.core.publisher.FluxFlatMap$FlatMapMain.innerComplete(FluxFlatMap.java:894)\n\t... 27 frames truncated\n","dt.entity.host":"HOST-56F4E6F24ABD2089","dt.entity.host_group":"HOST_GROUP-22F34B3925ED1469","dt.entity.process_group_instance":"PROCESS_GROUP_INSTANCE-5F7BFA6A4694F7BD"}`

**Comment by anuchandy** [comment]
Hi Josh, thanks for the stack trace. We can see that this stack trace and the original stack trace (in the issue description) has different path, so the error source is different but thrown error is the same. I synced with David today, and he mentioned he is working with you to collect the logs.

**Comment by JRiggenbach** [comment]
@anuchandy Thanks for the response.  This stack trace is really the only thing we have at the moment.  Our application specific logs are not going to be useful and we did not have any debug level AMQP logs.  From a setup perspective, we are using the ServiceBusClientBuilder to build a session aware ServiceBusProcessorClient.  The client is configured to run with 15 concurrent sessions with a message wait time of 5 seconds before it should move onto the next session.  The exception does not happen frequently, but unfortunately when it does the only way to recover from it is to restart the application as the processor client stops receiving messages.  I'll need help in understanding what exactly you would need from our side other than the stack trace.  If it is the AMQP debug logs, then we'll have to deploy something even more targeted as those logs are very verbose and would be difficult to sift through due to the amount of service bus traffic we're dealing with.  Thanks.

**Comment by anuchandy** [comment]
Hi Josh, Per our last [discussion](https://github.com/Azure/azure-sdk-for-java/issues/33867#issuecomment-1561533055), I thought you managed to isolate a Processor with logging enabled to debug this.

Without logs, we can't pinpoint the state (i.e., the wire traffic events, the amqp engine state, threads triggering events) that leads to this problem which blocks the RCA.

But I've some suggestions. Looking at the trace, it seems you've AutoComplete enabled, and the "Thread" that triggered the error ran through this AutoComplete facility. 

The AutoComplete currently has some issues with the context switch, and we decided to deprecate / remove the feature in the [future](https://github.com/Azure/azure-sdk-for-java/issues/33710). So we've been asking users to disable auto-complete.

Can you try to disable it and do the complete in the processor handler?

1. You want to call complete() API in a try-catch, so code don't rethrow. If the complete() API fails for some reason, don't call abandon(); such a call has no effect or is very likely to fail.
2. Also, surround abandon() API with try-catch if the application wants to abandon the message.
3. Please update to the latest SDK to get any reliability, feature and security fixes.

Pseudocode:

```java
handler(message) {
   boolean e = false;
   try {
     businessProcessing(message);
   } catch (RuntimeException re) { e = true; /** log(re) **/  }

   if (e) {
      try { abandon(e); } catch(RuntimeException t) {  /** log(t) **/  }
   } else {
      try {  complete(e); } catch(RuntimeException t) { /** log(t) **/  }
   }
}
```

**Comment by JRiggenbach** [comment]
@anuchandy Thanks for the guidance around AutoComplete.  We'll make the adjustment and see if this addresses the issue.  Thanks again.
