### ISSUE TITLE
[BUG] azure-cosmos-spark_3-3_2-12-4.15.0 patch getting "Resource Not Found" error using scala 

### ISSUE THREAD

**Issue by shea3100** [Azure/azure-sdk-for-java#34094]
**Describe the bug**
When I did patch operation with database with a big number of existing records, I received "Resource Not Found" error. However, when I used a new database for testing the patch operation worked with exactly the same code.

***Exception or Stack Trace***
org.apache.spark.SparkException: Writing job aborted.
  at org.apache.spark.sql.execution.datasources.v2.V2TableWriteExec.writeWithV2(WriteToDataSourceV2Exec.scala:388)

  at org.apache.spark.sql.execution.datasources.v2.V2TableWriteExec.writeWithV2$(WriteToDataSourceV2Exec.scala:336)

  at org.apache.spark.sql.execution.datasources.v2.AppendDataExec.writeWithV2(WriteToDataSourceV2Exec.scala:218)

  at org.apache.spark.sql.execution.datasources.v2.AppendDataExec.run(WriteToDataSourceV2Exec.scala:225)

  at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result$lzycompute(V2CommandExec.scala:40)

  at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result(V2CommandExec.scala:40)

  at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.doExecute(V2CommandExec.scala:55)

  at org.apache.spark.sql.execution.SparkPlan.$anonfun$execute$1(SparkPlan.scala:218)

  at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:256)

  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)

  at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:253)

  at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:214)

  at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:148)

  at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:147)

  at org.apache.spark.sql.DataFrameWriter.$anonfun$runCommand$1(DataFrameWriter.scala:1013)

  at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:107)

  at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:181)

  at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:94)

  at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)

  at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:68)

  at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:1013)

  at org.apache.spark.sql.DataFrameWriter.saveInternal(DataFrameWriter.scala:389)

  at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:303)

  ... 59 elided

Caused by: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 84.0 failed 4 times, most recent failure: Lost task 0.3 in stage 84.0 (TID 3062) (vm-0df79140 executor 1): {"ClassName":"NotFoundException","userAgent":"azsdk-java-cosmos/4.40.0 Linux/4.15.0-1162-azure JRE/1.8.0_362","statusCode":404,"resourceAddress":"rntbd://cdb-ms-prod-centralus1euap-be2.documents.azure.com:14393/apps/f71e46ae-dbec-4fc6-8889-678d8885e8c6/services/2c9945c6-a40c-4662-aaa3-37b26ca00097/partitions/f581daf6-12cb-437e-917a-1baa7f8f3691/replicas/133183677042090690p/","error":"{\"Errors\":[\"Resource Not Found. Learn more: [https://aka.ms/cosmosdb-tsg-not-found\"]}","innerErrorMessage":"[\"Resource](https://aka.ms/cosmosdb-tsg-not-found/%22]%7D%22,%22innerErrorMessage%22:%22[/%22Resource) Not Found. Learn more: [https://aka.ms/cosmosdb-tsg-not-found\"]","causeInfo":null,"responseHeaders":"{x-ms-current-replica-set-size=4,](https://aka.ms/cosmosdb-tsg-not-found/%22]%22,%22causeInfo%22:null,%22responseHeaders%22:%22%7Bx-ms-current-replica-set-size=4,) x-ms-last-state-change-utc=Thu, 16 Mar 2023 17:18:09.406 GMT, x-ms-request-duration-ms=0.343, x-ms-session-token=3:0#30800#52=-1, lsn=30800, x-ms-request-charge=1.00, x-ms-schemaversion=1.15, x-ms-transport-request-id=1660, x-ms-number-of-read-regions=1, x-ms-current-write-quorum=3, x-ms-cosmos-quorum-acked-llsn=30800, x-ms-quorum-acked-lsn=30800, x-ms-activity-id=1a2c55a8-c4f8-11ed-906a-310f859060e1, x-ms-xp-role=1, x-ms-global-Committed-lsn=30800, x-ms-cosmos-llsn=30800, x-ms-serviceversion= version=2.14.0.0}","cosmosDiagnostics":{"userAgent":"azsdk-java-cosmos/4.40.0 Linux/4.15.0-1162-azure JRE/1.8.0_362","activityId":"1a2c55a8-c4f8-11ed-906a-310f859060e1","requestLatencyInMs":40,"requestStartTimeUTC":"2023-03-17T19:15:38.840Z","requestEndTimeUTC":"2023-03-17T19:15:38.880Z","responseStatisticsList":[{"storeResult":{"storePhysicalAddress":"rntbd://cdb-ms-prod-centralus1euap-be2.documents.azure.com:14393/apps/f71e46ae-dbec-4fc6-8889-678d8885e8c6/services/2c9945c6-a40c-4662-aaa3-37b26ca00097/partitions/f581daf6-12cb-437e-917a-1baa7f8f3691/replicas/133183677042090690p/","lsn":30800,"globalCommittedLsn":30800,"partitionKeyRangeId":"3","isValid":true,"statusCode":404,"subStatusCode":0,"isGone":false,"isNotFound":true,"isInvalidPartition":false,"isThroughputControlRequestRateTooLarge":false,"requestCharge":1.0,"itemLSN":-1,"sessionToken":"3:0#30800#52=-1","backendLatencyInMs":0.343,"retryAfterInMs":null,"exceptionMessage":"[\"Resource Not Found. Learn more: [https://aka.ms/cosmosdb-tsg-not-found\"]","exceptionResponseHeaders":"{x-ms-current-replica-set-size=4,](https://aka.ms/cosmosdb-tsg-not-found/%22]%22,%22exceptionResponseHeaders%22:%22%7Bx-ms-current-replica-set-size=4,) x-ms-last-state-change-utc=Thu, 16 Mar 2023 17:18:09.406 GMT, x-ms-request-duration-ms=0.343, x-ms-session-token=3:0#30800#52=-1, lsn=30800, x-ms-request-charge=1.00, x-ms-schemaversion=1.15, x-ms-transport-request-id=1660, x-ms-number-of-read-regions=1, x-ms-current-write-quorum=3, x-ms-cosmos-quorum-acked-llsn=30800, x-ms-quorum-acked-lsn=30800, x-ms-activity-id=1a2c55a8-c4f8-11ed-906a-310f859060e1, x-ms-xp-role=1, x-ms-global-Committed-lsn=30800, x-ms-cosmos-llsn=30800, x-ms-documentdb-partitionkeyrangeid=3, x-ms-serviceversion= version=2.14.0.0}","replicaStatusList":["14393:Connected"],"transportRequestTimeline":[{"eventName":"created","startTimeUTC":"2023-03-17T19:15:38.841Z","durationInMilliSecs":0.0},{"eventName":"queued","startTimeUTC":"2023-03-17T19:15:38.841Z","durationInMilliSecs":0.0},{"eventName":"channelAcquisitionStarted","startTimeUTC":"2023-03-17T19:15:38.841Z","durationInMilliSecs":0.0},{"eventName":"pipelined","startTimeUTC":"2023-03-17T19:15:38.841Z","durationInMilliSecs":0.0},{"eventName":"transitTime","startTimeUTC":"2023-03-17T19:15:38.841Z","durationInMilliSecs":38.0},{"eventName":"decodeTime","startTimeUTC":"2023-03-17T19:15:38.879Z","durationInMilliSecs":0.0},{"eventName":"received","startTimeUTC":"2023-03-17T19:15:38.879Z","durationInMilliSecs":1.0},{"eventName":"completed","startTimeUTC":"2023-03-17T19:15:38.880Z","durationInMilliSecs":0.0}],"rntbdRequestLengthInBytes":576,"rntbdResponseLengthInBytes":300,"requestPayloadLengthInBytes":62,"responsePayloadLengthInBytes":300,"channelStatistics":{"channelId":"9cd27633","channelTaskQueueSize":1,"pendingRequestsCount":0,"lastReadTime":"2023-03-17T19:15:38.776Z","waitForConnectionInit":false},"serviceEndpointStatistics":{"availableChannels":1,"acquiredChannels":0,"executorTaskQueueSize":0,"inflightRequests":1,"lastSuccessfulRequestTime":"2023-03-17T19:15:38.776Z","lastRequestTime":"2023-03-17T19:15:38.737Z","createdTime":"2023-03-17T19:05:30.594Z","isClosed":false,"cerMetrics":{}}},"requestResponseTimeUTC":"2023-03-17T19:15:38.880Z","requestStartTimeUTC":"2023-03-17T19:15:38.840Z","requestResourceType":"Document","requestOperationType":"Patch","requestSessionToken":null}],"supplementalResponseStatisticsList":[],"addressResolutionStatistics":{},"regionsContacted":["central us euap"],"retryContext":{"statusAndSubStatusCodes":null,"retryLatency":0,"retryCount":0},"metadataDiagnosticsContext":{"metadataDiagnosticList":null},"serializationDiagnosticsContext":{"serializationDiagnosticsList":[{"serializationType":"ITEM_SERIALIZATION","startTimeUTC":"2023-03-17T19:15:38.840Z","endTimeUTC":"2023-03-17T19:15:38.840Z","durationInMilliSecs":0.0}]},"gatewayStatistics":null,"systemInformation":{"usedMemory":"1437869 KB","availableMemory":"116002643 KB","systemCpuLoad":"(2023-03-17T19:15:12.867Z 2.1%), (2023-03-17T19:15:17.867Z 2.0%), (2023-03-17T19:15:22.867Z 2.2%), (2023-03-17T19:15:27.867Z 2.4%), (2023-03-17T19:15:32.867Z 2.3%), (2023-03-17T19:15:37.867Z 2.0%)","availableProcessors":16},"clientCfgs":{"id":1,"machineId":"uuid:ca219e9d-8838-4279-995d-e5268f82d091","connectionMode":"DIRECT","numberOfClients":1,"clientEndpoints":{"https://iga-insights-useuap.documents.azure.com:443/":1},"connCfg":{"rntbd":"(cto:PT10S, nrto:PT10S, icto:PT0S, ieto:PT1H, mcpe:130, mrpc:30, cer:true)","gw":"(cps:1000, nrto:PT1M, icto:PT1M, p:false)","other":"(ed: true, cs: false, rv: true)"},"consistencyCfg":"(consistency: Eventual, mm: true, prgns: [])","proactiveInit":null}}}

	at azure_cosmos_spark.com.azure.cosmos.implementation.directconnectivity.rntbd.RntbdRequestManager.messageReceived(RntbdRequestManager.java:929)

	at azure_cosmos_spark.com.azure.cosmos.implementation.directconnectivity.rntbd.RntbdRequestManager.channelRead(RntbdRequestManager.java:195)

	at azure_cosmos_spark.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)

	at azure_cosmos_spark.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)

	at azure_cosmos_spark.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)

	at azure_cosmos_spark.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)

	at azure_cosmos_spark.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)

	at azure_cosmos_spark.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)

	at azure_cosmos_spark.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)

	at azure_cosmos_spark.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)

	at azure_cosmos_spark.io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)

	at azure_cosmos_spark.io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)

	at azure_cosmos_spark.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)

	at azure_cosmos_spark.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)

	at azure_cosmos_spark.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)

	at azure_cosmos_spark.io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)

	at azure_cosmos_spark.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)

	at azure_cosmos_spark.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)

	at azure_cosmos_spark.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)

	at azure_cosmos_spark.io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1373)

	at azure_cosmos_spark.io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1236)

	at azure_cosmos_spark.io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1285)

	at azure_cosmos_spark.io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)

	at azure_cosmos_spark.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)

	at azure_cosmos_spark.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)

	at azure_cosmos_spark.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)

	at azure_cosmos_spark.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)

	at azure_cosmos_spark.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)

	at azure_cosmos_spark.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)

	at azure_cosmos_spark.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)

	at azure_cosmos_spark.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)

	at azure_cosmos_spark.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)

	at azure_cosmos_spark.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)

	at azure_cosmos_spark.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)

	at azure_cosmos_spark.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)

	at azure_cosmos_spark.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)

	at azure_cosmos_spark.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)

	at azure_cosmos_spark.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)

	at azure_cosmos_spark.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)

	at azure_cosmos_spark.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

	at java.lang.Thread.run(Thread.java:750)

	Suppressed: java.lang.Exception: #block terminated with an error

		at azure_cosmos_spark.reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)

		at azure_cosmos_spark.reactor.core.publisher.Mono.block(Mono.java:1742)

		at com.azure.cosmos.spark.PointWriter.patchItem(PointWriter.scala:353)

		at com.azure.cosmos.spark.PointWriter.$anonfun$patchWithRetry$1(PointWriter.scala:317)

		at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:158)

		at com.azure.cosmos.spark.PointWriter.patchWithRetry(PointWriter.scala:315)

		at com.azure.cosmos.spark.PointWriter.$anonfun$patchWithRetryAsync$1(PointWriter.scala:206)

		at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)

		at com.azure.cosmos.spark.PointWriter$$anon$1.call(PointWriter.scala:453)

		at com.azure.cosmos.spark.PointWriter$$anon$1.call(PointWriter.scala:450)

		at java.util.concurrent.FutureTask.run(FutureTask.java:266)

		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

		... 1 more

Driver stacktrace:

  at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2313)

  at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2262)

  at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2261)

  at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)

  at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)

  at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)

  at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2261)

  at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1132)

  at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1132)

  at scala.Option.foreach(Option.scala:407)

  at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1132)

  at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2500)

  at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2442)

  at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2431)

  at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)

  at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:908)

  at org.apache.spark.SparkContext.runJob(SparkContext.scala:2306)

  at org.apache.spark.sql.execution.datasources.v2.V2TableWriteExec.writeWithV2(WriteToDataSourceV2Exec.scala:357)

**To Reproduce**

***Code Snippet***
Add the code snippet that causes the issue.
`val cosmosEndpoint ="..."
val cosmosMasterKey = "..."
val cosmosDatabaseName = "..."
val cosmosContainerName = "..."

//val predicate = "from c"

val cfgPatch = Map("spark.cosmos.accountEndpoint" -> cosmosEndpoint,
        "spark.cosmos.accountKey" -> cosmosMasterKey,
        "spark.cosmos.database" -> cosmosDatabaseName,
        "spark.cosmos.container" -> cosmosContainerName,
        "spark.cosmos.write.strategy" -> "ItemPatch",
        "spark.cosmos.write.bulk.enabled" -> "false",
        "spark.cosmos.write.patch.columnConfigs" -> "[col(usertype).op(add)]"
      )

//val s= "[col(accountEnabled).op(add),col(lastSignInDateTime).path(/lastSignIn/lastSignInDateTime).op(replace)]"
val patchDf = Seq(
("9120276d-6bfd-47fe-a09f-cdcf486f545f_c753d008-ccd4-4665-988d-7008a2fbd186",false)
      ).toDF("id", "usertype")

patchDf.write.format("cosmos.oltp").mode("Append").options(cfgPatch).save()`
**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - IDE: Synapse workspace 
 - Library/Libraries: azure-cosmos-spark_3_2-12
 - scala version: 2.12
 - spark.version:3.2.2

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by FabianMeiswinkel** [comment]
Looks like the 404 happens because the document with the PK/id of the to-be-patched input dataframe does not exist - this is expected - patch can only be applied to already existing documents.
