### ISSUE TITLE
[BUG] Service Bus session processor stops receiving messages after one minute

### ISSUE THREAD

**Issue by KnyGoo** [Azure/azure-sdk-for-java#34283]
**Describe the bug**
Session processor stops receiving messages after one minute.

**To Reproduce**
***Code Snippet***
`        

       AzureIdentityConfig azureIdentityConfig = new AzureIdentityConfig();
               azureIdentityConfig.setTenantId("a");
               azureIdentityConfig.setClientId("b");
               azureIdentityConfig.setClientSecret("c");

        ServiceBusProcessorClient serviceBusProcessorClient = new ServiceBusClientBuilder()
                .credential("xxx.servicebus.windows.net", azureIdentityConfig.buildCredential())
                .transportType(AmqpTransportType.AMQP_WEB_SOCKETS)
                .retryOptions(new AmqpRetryOptions().setTryTimeout(Duration.ofSeconds(60)))
                .sessionProcessor()
                .queueName("queueName")
                .receiveMode(ServiceBusReceiveMode.PEEK_LOCK)
                .disableAutoComplete()
                .processMessage(serviceBusReceivedMessageContext -> {
                    LOGGER.info("RECEIVED MESSAGE {}", serviceBusReceivedMessageContext.getMessage().getMessageId());
                    serviceBusReceivedMessageContext.complete();
                })
                .processError(context -> {})
                .maxConcurrentSessions(16)
                .maxConcurrentCalls(1)
                .maxAutoLockRenewDuration(Duration.ofSeconds(30))
                .buildProcessorClient();

        serviceBusProcessorClient.start();
`

**Expected behavior**
Processor should receive messages

**Setup (please complete the following information):**
 - OS: Windows
 - IDE: IntelliJ
 - Library/Libraries: com.azure:azure-messaging-servicebus:7.13.3
 - Java version: 11
 - App Server/Environment: Tomcat
 - Frameworks: Spring Boot

**Comment by KnyGoo** [comment]
Our session processor again stuck, nog after a connection error:
`   - 2023-04-01 06:35:57.541 [reactor-executor-13] ERROR - [trace=,span=] - Operator called default onErrorDropped [r.u.Loggers$Slf4JLogger:error:324] 
reactor.core.Exceptions$ErrorCallbackNotImplemented: com.azure.core.amqp.exception.AmqpException: An existing connection was forcibly closed by the remote host, errorContext[NAMESPACE: xxx.servicebus.windows.net. ERROR CONTEXT: N/A]
Caused by: com.azure.core.amqp.exception.AmqpException: An existing connection was forcibly closed by the remote host, errorContext[NAMESPACE: xxx.servicebus.windows.net. ERROR CONTEXT: N/A]
	at com.azure.core.amqp.implementation.ExceptionUtil.toException(ExceptionUtil.java:85)
	at com.azure.core.amqp.implementation.handler.ConnectionHandler.notifyErrorContext(ConnectionHandler.java:351)
	at com.azure.core.amqp.implementation.handler.ConnectionHandler.onTransportError(ConnectionHandler.java:253)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:191)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291)
	at com.azure.core.amqp.implementation.ReactorExecutor.run(ReactorExecutor.java:91)
	at org.springframework.cloud.sleuth.instrument.reactor.ReactorSleuth.lambda$null$6(ReactorSleuth.java:324)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)`

**Comment by KnyGoo** [comment]
After upgrade to 7.13.3 it even get worse. Consumer stops after one minute not receiving any messages.

`
2023-04-03 14:33:10.890  INFO 18344 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
2023-04-03 14:33:10.891  INFO 18344 --- [ctor-executor-1] c.a.c.a.i.h.WebSocketsConnectionHandler  : {"az.sdk.message":"onConnectionRemoteOpen","connectionId":"MF_f418a5_1680525190201","hostName":"xxx.servicebus.windows.net","remoteContainer":"7ad0274d731d4630bce738b1b113f524_G50"}
2023-04-03 14:33:10.892  INFO 18344 --- [ctor-executor-1] c.a.m.s.i.ServiceBusConnectionProcessor  : {"az.sdk.message":"Channel is now active.","entityPath":"N/A"}
2023-04-03 14:33:10.900  INFO 18344 --- [           main] b.s.c.a.AzureServicebusDemoApplication   : Started AzureServicebusDemoApplication in 2.403 seconds (JVM running for 2.737)
2023-04-03 14:33:10.933  INFO 18344 --- [ctor-executor-1] c.a.c.a.i.handler.SessionHandler         : {"az.sdk.message":"onSessionRemoteOpen","connectionId":"MF_f418a5_1680525190201","sessionName":"queueName","sessionIncCapacity":0,"sessionOutgoingWindow":2147483647}
2023-04-03 14:33:10.953  INFO 18344 --- [ctor-executor-1] c.a.c.a.i.ReactorConnection              : {"az.sdk.message":"Setting CBS channel.","connectionId":"MF_f418a5_1680525190201"}
2023-04-03 14:33:10.983  INFO 18344 --- [ctor-executor-1] c.a.c.a.i.handler.SessionHandler         : {"az.sdk.message":"onSessionRemoteOpen","connectionId":"MF_f418a5_1680525190201","sessionName":"cbs-session","sessionIncCapacity":0,"sessionOutgoingWindow":2147483647}
2023-04-03 14:33:10.991  INFO 18344 --- [ctor-executor-1] c.a.c.a.i.ReactorConnection              : {"az.sdk.message":"Emitting new response channel.","connectionId":"MF_f418a5_1680525190201","entityPath":"$cbs","linkName":"cbs"}
2023-04-03 14:33:10.992  INFO 18344 --- [ctor-executor-1] c.a.c.a.i.AmqpChannelProcessor           : {"az.sdk.message":"Setting next AMQP channel.","connectionId":"MF_f418a5_1680525190201","entityPath":"$cbs"}
2023-04-03 14:33:11.107  INFO 18344 --- [ctor-executor-1] c.a.c.a.i.AmqpChannelProcessor           : {"az.sdk.message":"Next AMQP channel received.","connectionId":"MF_f418a5_1680525190201","entityPath":"$cbs","subscriberId":"un_85808c_1680525190958"}
2023-04-03 14:33:11.107  INFO 18344 --- [ctor-executor-1] c.a.c.a.i.AmqpChannelProcessor           : {"az.sdk.message":"Next AMQP channel received.","connectionId":"MF_f418a5_1680525190201","entityPath":"$cbs","subscriberId":"un_74ae44_1680525190958"}
2023-04-03 14:33:11.153  INFO 18344 --- [ctor-executor-1] c.a.c.a.i.handler.SendLinkHandler        : {"az.sdk.message":"onLinkRemoteOpen","connectionId":"MF_f418a5_1680525190201","linkName":"cbs:sender","entityPath":"$cbs","remoteTarget":"Target{address='$cbs', durable=NONE, expiryPolicy=SESSION_END, timeout=0, dynamic=false, dynamicNodeProperties=null, capabilities=null}"}
2023-04-03 14:33:11.154  INFO 18344 --- [ctor-executor-1] c.a.c.a.i.AmqpChannelProcessor           : {"az.sdk.message":"Channel is now active.","connectionId":"MF_f418a5_1680525190201","entityPath":"$cbs"}
2023-04-03 14:33:11.155  INFO 18344 --- [ctor-executor-1] c.a.c.a.i.handler.ReceiveLinkHandler     : {"az.sdk.message":"onLinkRemoteOpen","connectionId":"MF_f418a5_1680525190201","entityPath":"$cbs","linkName":"cbs:receiver","remoteSource":"Source{address='$cbs', durable=NONE, expiryPolicy=SESSION_END, timeout=0, dynamic=false, dynamicNodeProperties=null, distributionMode=null, filter=null, defaultOutcome=null, outcomes=null, capabilities=null}"}
2023-04-03 14:33:12.096  INFO 18344 --- [pool-1-thread-3] c.azure.identity.ClientSecretCredential  : Azure Identity => getToken() result for scopes [https://servicebus.azure.net/.default]: SUCCESS
2023-04-03 14:33:12.119  INFO 18344 --- [pool-1-thread-4] c.azure.identity.ClientSecretCredential  : Azure Identity => getToken() result for scopes [https://servicebus.azure.net/.default]: SUCCESS
2023-04-03 14:33:12.477  INFO 18344 --- [ctor-executor-1] c.a.c.a.i.ActiveClientTokenManager       : {"az.sdk.message":"Scheduling refresh token task.","scopes":"https://servicebus.azure.net/.default"}
2023-04-03 14:33:12.486  INFO 18344 --- [ctor-executor-1] c.a.c.a.implementation.ReactorSession    : {"az.sdk.message":"Creating a new receiver link.","connectionId":"MF_f418a5_1680525190201","sessionName":"queueName","linkName":"session-_220bc2_1680525190324"}
2023-04-03 14:33:13.174  INFO 18344 --- [ctor-executor-1] c.a.c.a.i.ActiveClientTokenManager       : {"az.sdk.message":"Scheduling refresh token task.","scopes":"https://servicebus.azure.net/.default"}
2023-04-03 14:33:13.174  INFO 18344 --- [ctor-executor-1] c.a.c.a.implementation.ReactorSession    : {"az.sdk.message":"Creating a new receiver link.","connectionId":"MF_f418a5_1680525190201","sessionName":"queueName","linkName":"session-_70552d_1680525190374"}
2023-04-03 14:33:41.432  INFO 18344 --- [ctor-executor-1] c.a.c.a.i.handler.ReceiveLinkHandler     : {"az.sdk.message":"onLinkRemoteOpen","connectionId":"MF_f418a5_1680525190201","entityPath":"queueName","linkName":"session-_220bc2_1680525190324","action":"waitingForError"}
2023-04-03 14:33:41.432  INFO 18344 --- [ctor-executor-1] c.a.c.a.i.handler.ReceiveLinkHandler     : {"az.sdk.message":"onLinkRemoteClose","connectionId":"MF_f418a5_1680525190201","errorCondition":"com.microsoft:timeout","errorDescription":"A timeout has occurred during the operation. For more information please see https://aka.ms/ServiceBusExceptions . TrackingId:7ad0274d731d4630bce738b1b113f524_G50, SystemTracker:gateway7, Timestamp:2023-04-03T12:33:41","linkName":"session-_220bc2_1680525190324","entityPath":"queueName"}
2023-04-03 14:33:41.433  INFO 18344 --- [ctor-executor-1] c.a.c.a.i.handler.ReceiveLinkHandler     : {"az.sdk.message":"Local link state is not closed.","connectionId":"MF_f418a5_1680525190201","linkName":"session-_220bc2_1680525190324","entityPath":"queueName","state":"ACTIVE"}
2023-04-03 14:33:41.441  INFO 18344 --- [ctor-executor-1] c.a.c.a.implementation.ReactorReceiver   : {"az.sdk.message":"Freeing resources due to error.","connectionId":"MF_f418a5_1680525190201","entityPath":"queueName","linkName":"session-_220bc2_1680525190324"}
2023-04-03 14:33:41.448  INFO 18344 --- [ctor-executor-1] c.a.m.s.ServiceBusSessionManager         : {"az.sdk.message":"Error occurred while getting unnamed session.","exception":"A timeout has occurred during the operation. For more information please see https://aka.ms/ServiceBusExceptions . TrackingId:7ad0274d731d4630bce738b1b113f524_G50, SystemTracker:gateway7, Timestamp:2023-04-03T12:33:41, errorContext[NAMESPACE: xxx.servicebus.windows.net. ERROR CONTEXT: N/A, PATH: queueName, REFERENCE_ID: session-_220bc2_1680525190324, LINK_CREDIT: 0]","entityPath":"queueName","attempt":0}
2023-04-03 14:33:41.448  INFO 18344 --- [ctor-executor-1] c.a.c.a.i.handler.ReceiveLinkHandler     : {"az.sdk.message":"Receiver link was never active. Closing endpoint states","connectionId":"MF_f418a5_1680525190201","entityPath":"queueName","linkName":"session-_220bc2_1680525190324"}
2023-04-03 14:33:41.451  INFO 18344 --- [ctor-executor-1] c.a.c.a.i.handler.ReceiveLinkHandler     : {"az.sdk.message":"onLinkFinal","connectionId":"MF_f418a5_1680525190201","linkName":"session-_220bc2_1680525190324","entityPath":"queueName"}
2023-04-03 14:33:42.216  INFO 18344 --- [ctor-executor-1] c.a.c.a.i.handler.ReceiveLinkHandler     : {"az.sdk.message":"onLinkRemoteOpen","connectionId":"MF_f418a5_1680525190201","entityPath":"queueName","linkName":"session-_70552d_1680525190374","action":"waitingForError"}
2023-04-03 14:33:42.216  INFO 18344 --- [ctor-executor-1] c.a.c.a.i.handler.ReceiveLinkHandler     : {"az.sdk.message":"onLinkRemoteClose","connectionId":"MF_f418a5_1680525190201","errorCondition":"com.microsoft:timeout","errorDescription":"A timeout has occurred during the operation. For more information please see https://aka.ms/ServiceBusExceptions . TrackingId:7ad0274d731d4630bce738b1b113f524_G50, SystemTracker:gateway7, Timestamp:2023-04-03T12:33:42","linkName":"session-_70552d_1680525190374","entityPath":"queueName"}
2023-04-03 14:33:42.216  INFO 18344 --- [ctor-executor-1] c.a.c.a.i.handler.ReceiveLinkHandler     : {"az.sdk.message":"Local link state is not closed.","connectionId":"MF_f418a5_1680525190201","linkName":"session-_70552d_1680525190374","entityPath":"queueName","state":"ACTIVE"}
2023-04-03 14:33:42.216  INFO 18344 --- [ctor-executor-1] c.a.c.a.implementation.ReactorReceiver   : {"az.sdk.message":"Freeing resources due to error.","connectionId":"MF_f418a5_1680525190201","entityPath":"queueName","linkName":"session-_70552d_1680525190374"}
2023-04-03 14:33:42.217  INFO 18344 --- [ctor-executor-1] c.a.m.s.ServiceBusSessionManager         : {"az.sdk.message":"Error occurred while getting unnamed session.","exception":"A timeout has occurred during the operation. For more information please see https://aka.ms/ServiceBusExceptions . TrackingId:7ad0274d731d4630bce738b1b113f524_G50, SystemTracker:gateway7, Timestamp:2023-04-03T12:33:42, errorContext[NAMESPACE: xxx.servicebus.windows.net. ERROR CONTEXT: N/A, PATH: queueName, REFERENCE_ID: session-_70552d_1680525190374, LINK_CREDIT: 0]","entityPath":"queueName","attempt":0}
2023-04-03 14:33:42.217  INFO 18344 --- [ctor-executor-1] c.a.c.a.i.handler.ReceiveLinkHandler     : {"az.sdk.message":"Receiver link was never active. Closing endpoint states","connectionId":"MF_f418a5_1680525190201","entityPath":"queueName","linkName":"session-_70552d_1680525190374"}
2023-04-03 14:33:42.217  INFO 18344 --- [ctor-executor-1] c.a.c.a.i.handler.ReceiveLinkHandler     : {"az.sdk.message":"onLinkFinal","connectionId":"MF_f418a5_1680525190201","linkName":"session-_70552d_1680525190374","entityPath":"queueName"}

`

**Comment by joshfree** [comment]
Hi @KnyGoo thank you for reaching out to us via this GitHub issue.

If this is an urgent issue, we recommend an Azure Support ticket ([/SUPPORT.md](https://github.com/Azure/azure-sdk-for-java/blob/main/SUPPORT.md)).  There is additional information available in the troubleshooting guide, which may be useful, here: [/sdk/servicebus/azure-messaging-servicebus/TROUBLESHOOTING.md](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/servicebus/azure-messaging-servicebus/TROUBLESHOOTING.md)

Otherwise, someone from the `Service Bus` sdk team will follow up with you shortly.

/cc @Azure/azsdk-sb-java

**Comment by KnyGoo** [comment]
Hi @joshfree,

This seems like a bug in the Java SDK. I don't see this problem in 7.12.1, but after upgrade to 7.13.3 this issue arises. I wanted to upgrade, because the sessions receiver stops consuming messages at random times approx. once a day in 7.12.1. But seems like the issue is even bigger in 7.13.3 because it now stops after one minute...

We already use the non-session processor a long time in production environment without any problems. After upgrade from old to new SDK for session processor, we have a major production incident.

With kind regards,

Kenny

**Comment by domainname** [comment]
It seems that 7.13.0 works well. FYI. @KnyGoo @joshfree

**Comment by anuchandy** [comment]
This will be addressed in the April version, scheduled to be released by April-20th
