### ISSUE TITLE
[Apache Camel] Apache Camel wrapper for Service Bus stops receiving message.

### ISSUE THREAD

**Issue by ArtemTraierLotus** [Azure/azure-sdk-for-java#34386]
**Describe the bug**
We notice that service bus client connection hanged and stopped receiving msges , we are using apache camel service bus with underlying azure messaging servicebus 7.11

***Exception or Stack Trace***
`2023-04-08 02:06:32.334 [reactor-executor-1] [c.a.c.a.i.h.ReceiveLinkHandler] INFO  {"az.sdk.message":"onLinkRemoteClose","connectionId":"MF_20c602_1680618393793","errorCondition":null,"errorDescription":null,"linkName":"objectnotification_ab2efd_1680618395096","entityPath":"objectnotification"}
2023-04-08 02:06:32.335 [reactor-executor-1] [c.a.c.a.i.h.ReceiveLinkHandler] INFO  {"az.sdk.message":"Local link state is not closed.","connectionId":"MF_20c602_1680618393793","linkName":"objectnotification_ab2efd_1680618395096","entityPath":"objectnotification","state":"ACTIVE"}
2023-04-08 02:06:32.339 [reactor-executor-1] [c.a.c.a.i.ReactorSession] INFO  {"az.sdk.message":"Complete. Removing receive link.","connectionId":"MF_20c602_1680618393793","linkName":"objectnotification_ab2efd_1680618395096","entityPath":"objectnotification"}
2023-04-08 02:06:32.397 [reactor-executor-1] [c.a.m.s.i.ServiceBusReceiveLinkProcessor] INFO  Receive link endpoint states are closed. Requesting another.
2023-04-08 02:06:32.397 [reactor-executor-1] [c.a.m.s.i.ServiceBusReceiveLinkProcessor] INFO  Requesting a new AmqpReceiveLink from upstream.
2023-04-08 02:06:32.397 [reactor-executor-1] [c.a.m.s.i.ServiceBusReceiveLinkProcessor] INFO  {"az.sdk.message":"Setting next AMQP receive link.","linkName":"objectnotification_ab2efd_1680618395096","entityPath":"objectnotification"}
2023-04-08 02:06:32.398 [reactor-executor-1] [c.a.m.s.i.ServiceBusReceiveLinkProcessor] INFO  {"az.sdk.message":"Adding credits.","prefetch":0,"requested":1,"linkCredits":1,"expectedTotalCredit":1,"queuedMessages":0,"creditsToAdd":0,"messageQueueSize":0}
2023-04-08 02:06:32.399 [boundedElastic-4] [c.a.m.s.i.ServiceBusReceiveLinkProcessor] INFO  Receive link endpoint states are closed. Requesting another.
2023-04-08 02:06:32.399 [boundedElastic-4] [c.a.m.s.i.ServiceBusReceiveLinkProcessor] INFO  Requesting a new AmqpReceiveLink from upstream.
2023-04-08 02:06:32.499 [reactor-executor-1] [c.a.c.a.i.h.ReceiveLinkHandler] INFO  {"az.sdk.message":"onLinkFinal","connectionId":"MF_20c602_1680618393793","linkName":"objectnotification_ab2efd_1680618395096","entityPath":"objectnotification"}
2023-04-08 02:06:32.594 [reactor-executor-1] [c.a.c.a.i.ActiveClientTokenManager] INFO  {"az.sdk.message":"Scheduling refresh token task.","scopes":"amqp://lfdnodc33.servicebus.windows.net/objectnotification"}
2023-04-08 02:06:32.595 [reactor-executor-1] [c.a.c.a.i.ReactorSession] INFO  {"az.sdk.message":"Creating a new receiver link.","connectionId":"MF_20c602_1680618393793","sessionName":"objectnotification","linkName":"objectnotification_ab2efd_1680618395096"}
2023-04-08 02:06:32.596 [reactor-executor-1] [c.a.m.s.i.ServiceBusReceiveLinkProcessor] INFO  {"az.sdk.message":"Setting next AMQP receive link.","linkName":"objectnotification_ab2efd_1680618395096","entityPath":"objectnotification"}
2023-04-08 02:06:32.598 [reactor-executor-1] [c.a.m.s.i.ServiceBusReceiveLinkProcessor] INFO  {"az.sdk.message":"Adding credits.","prefetch":0,"requested":1,"linkCredits":0,"expectedTotalCredit":1,"queuedMessages":0,"creditsToAdd":1,"messageQueueSize":0}
2023-04-08 02:06:32.598 [reactor-executor-1] [c.a.c.a.i.ReactorSession] INFO  {"az.sdk.message":"Returning existing receive link.","connectionId":"MF_20c602_1680618393793","linkName":"objectnotification_ab2efd_1680618395096","entityPath":"objectnotification"}
2023-04-08 02:06:35.904 [object-storage-events-connector-2281] [c.l.c.ServiceResources] INFO  Route's heartbeat is successful
2023-04-08 02:06:52.725 [reactor-executor-1] [c.a.c.a.i.h.ReceiveLinkHandler] INFO  {"az.sdk.message":"onLinkRemoteOpen","connectionId":"MF_20c602_1680618393793","entityPath":"objectnotification","linkName":"objectnotification_ab2efd_1680618395096","action":"waitingForError"}
2023-04-08 02:06:52.725 [reactor-executor-1] [c.a.c.a.i.h.ReceiveLinkHandler] INFO  {"az.sdk.message":"onLinkRemoteClose","connectionId":"MF_20c602_1680618393793","errorCondition":"amqp:internal-error","errorDescription":"The service was unable to process the request; please retry the operation. For more information on exception types and proper exception handling, please refer to http://go.microsoft.com/fwlink/?LinkId=761101 TrackingId:500e00f709224bac9cc109220586bc14_G9, SystemTracker:gateway7, Timestamp:2023-04-08T02:06:52","linkName":"objectnotification_ab2efd_1680618395096","entityPath":"objectnotification"}
2023-04-08 02:06:52.725 [reactor-executor-1] [c.a.c.a.i.h.ReceiveLinkHandler] INFO  {"az.sdk.message":"Local link state is not closed.","connectionId":"MF_20c602_1680618393793","linkName":"objectnotification_ab2efd_1680618395096","entityPath":"objectnotification","state":"ACTIVE"}
2023-04-08 02:06:52.729 [reactor-executor-1] [c.a.c.a.i.ReactorReceiver] INFO  {"az.sdk.message":"Freeing resources due to error.","connectionId":"MF_20c602_1680618393793","entityPath":"objectnotification","linkName":"objectnotification_ab2efd_1680618395096"}
2023-04-08 02:06:52.730 [reactor-executor-1] [c.a.m.s.i.ServiceBusReceiveLinkProcessor] WARN  {"az.sdk.message":"Transient error occurred.","exception":"The service was unable to process the request; please retry the operation. For more information on exception types and proper exception handling, please refer to http://go.microsoft.com/fwlink/?LinkId=761101 TrackingId:500e00f709224bac9cc109220586bc14_G9, SystemTracker:gateway7, Timestamp:2023-04-08T02:06:52, errorContext[NAMESPACE: lfdnodc33.servicebus.windows.net. ERROR CONTEXT: N/A, PATH: objectnotification, REFERENCE_ID: objectnotification_ab2efd_1680618395096, LINK_CREDIT: 1]","linkName":"n/a","entityPath":"n/a","attempt":1,"retryAfter":4511}
2023-04-08 02:06:52.731 [reactor-executor-1] [c.a.c.a.i.h.ReceiveLinkHandler] INFO  {"az.sdk.message":"Receiver link was never active. Closing endpoint states","connectionId":"MF_20c602_1680618393793","entityPath":"objectnotification","linkName":"objectnotification_ab2efd_1680618395096"}
2023-04-08 02:06:52.793 [reactor-executor-1] [c.a.c.a.i.h.ReceiveLinkHandler] INFO  {"az.sdk.message":"onLinkFinal","connectionId":"MF_20c602_1680618393793","linkName":"objectnotification_ab2efd_1680618395096","entityPath":"objectnotification"}
2023-04-08 02:06:57.243 [parallel-1] [c.a.m.s.i.ServiceBusReceiveLinkProcessor] INFO  Requesting a new AmqpReceiveLink from upstream.
2023-04-08 02:06:57.243 [parallel-1] [c.a.m.s.i.ServiceBusReceiveLinkProcessor] INFO  {"az.sdk.message":"Setting next AMQP receive link.","linkName":"objectnotification_ab2efd_1680618395096","entityPath":"objectnotification"}
2023-04-08 02:06:57.243 [parallel-1] [c.a.m.s.i.ServiceBusReceiveLinkProcessor] INFO  {"az.sdk.message":"Adding credits.","prefetch":0,"requested":1,"linkCredits":1,"expectedTotalCredit":1,"queuedMessages":0,"creditsToAdd":0,"messageQueueSize":0}
2023-04-08 02:06:57.244 [boundedElastic-1] [c.a.m.s.i.ServiceBusReceiveLinkProcessor] WARN  {"az.sdk.message":"Transient error occurred.","exception":"The service was unable to process the request; please retry the operation. For more information on exception types and proper exception handling, please refer to http://go.microsoft.com/fwlink/?LinkId=761101 TrackingId:500e00f709224bac9cc109220586bc14_G9, SystemTracker:gateway7, Timestamp:2023-04-08T02:06:52, errorContext[NAMESPACE: lfdnodc33.servicebus.windows.net. ERROR CONTEXT: N/A, PATH: objectnotification, REFERENCE_ID: objectnotification_ab2efd_1680618395096, LINK_CREDIT: 1]","linkName":"n/a","entityPath":"n/a","attempt":2,"retryAfter":14575}
2023-04-08 02:06:57.249 [reactor-executor-1] [c.a.c.a.i.ActiveClientTokenManager] INFO  {"az.sdk.message":"Scheduling refresh token task.","scopes":"amqp://lfdnodc33.servicebus.windows.net/objectnotification"}
2023-04-08 02:06:57.249 [reactor-executor-1] [c.a.c.a.i.ReactorSession] INFO  {"az.sdk.message":"Creating a new receiver link.","connectionId":"MF_20c602_1680618393793","sessionName":"objectnotification","linkName":"objectnotification_ab2efd_1680618395096"}
2023-04-08 02:07:11.819 [parallel-1] [c.a.m.s.i.ServiceBusReceiveLinkProcessor] INFO  Requesting a new AmqpReceiveLink from upstream.
2023-04-08 02:07:11.819 [parallel-1] [c.a.m.s.i.ServiceBusReceiveLinkProcessor] INFO  {"az.sdk.message":"Setting next AMQP receive link.","linkName":"objectnotification_ab2efd_1680618395096","entityPath":"objectnotification"}
2023-04-08 02:07:11.820 [parallel-1] [c.a.m.s.i.ServiceBusReceiveLinkProcessor] INFO  {"az.sdk.message":"Adding credits.","prefetch":0,"requested":1,"linkCredits":0,"expectedTotalCredit":1,"queuedMessages":0,"creditsToAdd":1,"messageQueueSize":0}
2023-04-08 02:07:11.820 [parallel-1] [c.a.c.a.i.ReactorSession] INFO  {"az.sdk.message":"Returning existing receive link.","connectionId":"MF_20c602_1680618393793","linkName":"objectnotification_ab2efd_1680618395096","entityPath":"objectnotification"}
2023-04-08 02:07:17.407 [reactor-executor-1] [c.a.c.a.i.h.ReceiveLinkHandler] INFO  {"az.sdk.message":"onLinkRemoteOpen","connectionId":"MF_20c602_1680618393793","entityPath":"objectnotification","linkName":"objectnotification_ab2efd_1680618395096","action":"waitingForError"}
2023-04-08 02:07:17.408 [reactor-executor-1] [c.a.c.a.i.h.ReceiveLinkHandler] INFO  {"az.sdk.message":"onLinkRemoteClose","connectionId":"MF_20c602_1680618393793","errorCondition":"amqp:internal-error","errorDescription":"The service was unable to process the request; please retry the operation. For more information on exception types and proper exception handling, please refer to http://go.microsoft.com/fwlink/?LinkId=761101 TrackingId:500e00f709224bac9cc109220586bc14_G9, SystemTracker:gateway7, Timestamp:2023-04-08T02:07:17","linkName":"objectnotification_ab2efd_1680618395096","entityPath":"objectnotification"}
2023-04-08 02:07:17.408 [reactor-executor-1] [c.a.c.a.i.h.ReceiveLinkHandler] INFO  {"az.sdk.message":"Local link state is not closed.","connectionId":"MF_20c602_1680618393793","linkName":"objectnotification_ab2efd_1680618395096","entityPath":"objectnotification","state":"ACTIVE"}
2023-04-08 02:07:17.408 [reactor-executor-1] [c.a.c.a.i.ReactorReceiver] INFO  {"az.sdk.message":"Freeing resources due to error.","connectionId":"MF_20c602_1680618393793","entityPath":"objectnotification","linkName":"objectnotification_ab2efd_1680618395096"}
2023-04-08 02:07:17.408 [reactor-executor-1] [c.a.m.s.i.ServiceBusReceiveLinkProcessor] WARN  {"az.sdk.message":"Transient error occurred.","exception":"The service was unable to process the request; please retry the operation. For more information on exception types and proper exception handling, please refer to http://go.microsoft.com/fwlink/?LinkId=761101 TrackingId:500e00f709224bac9cc109220586bc14_G9, SystemTracker:gateway7, Timestamp:2023-04-08T02:07:17, errorContext[NAMESPACE: lfdnodc33.servicebus.windows.net. ERROR CONTEXT: N/A, PATH: objectnotification, REFERENCE_ID: objectnotification_ab2efd_1680618395096, LINK_CREDIT: 1]","linkName":"n/a","entityPath":"n/a","attempt":3,"retryAfter":51928}
2023-04-08 02:07:17.409 [reactor-executor-1] [c.a.c.a.i.h.ReceiveLinkHandler] INFO  {"az.sdk.message":"Receiver link was never active. Closing endpoint states","connectionId":"MF_20c602_1680618393793","entityPath":"objectnotification","linkName":"objectnotification_ab2efd_1680618395096"}
2023-04-08 02:07:17.409 [reactor-executor-1] [c.a.c.a.i.h.ReceiveLinkHandler] INFO  {"az.sdk.message":"onLinkFinal","connectionId":"MF_20c602_1680618393793","linkName":"objectnotification_ab2efd_1680618395096","entityPath":"objectnotification"}
2023-04-08 02:07:35.904 [object-storage-events-connector-42] [c.l.c.ServiceResources] INFO  Route's heartbeat is successful
2023-04-08 02:08:09.337 [parallel-1] [c.a.m.s.i.ServiceBusReceiveLinkProcessor] INFO  Requesting a new AmqpReceiveLink from upstream.
2023-04-08 02:08:09.337 [parallel-1] [c.a.m.s.i.ServiceBusReceiveLinkProcessor] INFO  {"az.sdk.message":"Setting next AMQP receive link.","linkName":"objectnotification_ab2efd_1680618395096","entityPath":"objectnotification"}
2023-04-08 02:08:09.337 [parallel-1] [c.a.m.s.i.ServiceBusReceiveLinkProcessor] INFO  {"az.sdk.message":"Adding credits.","prefetch":0,"requested":1,"linkCredits":1,"expectedTotalCredit":1,"queuedMessages":0,"creditsToAdd":0,"messageQueueSize":0}
2023-04-08 02:08:09.338 [boundedElastic-4] [c.a.m.s.i.ServiceBusReceiveLinkProcessor] WARN  {"az.sdk.message":"Non-retryable error occurred in AMQP receive link.","exception":"The service was unable to process the request; please retry the operation. For more information on exception types and proper exception handling, please refer to http://go.microsoft.com/fwlink/?LinkId=761101 TrackingId:500e00f709224bac9cc109220586bc14_G9, SystemTracker:gateway7, Timestamp:2023-04-08T02:07:17, errorContext[NAMESPACE: lfdnodc33.servicebus.windows.net. ERROR CONTEXT: N/A, PATH: objectnotification, REFERENCE_ID: objectnotification_ab2efd_1680618395096, LINK_CREDIT: 1]","linkName":"n/a","entityPath":"n/a"}
2023-04-08 02:08:09.338 [boundedElastic-4] [c.a.m.s.FluxAutoLockRenew$LockRenewSubscriber] ERROR Errors occurred upstream.
The service was unable to process the request; please retry the operation. For more information on exception types and proper exception handling, please refer to http://go.microsoft.com/fwlink/?LinkId=761101 TrackingId:500e00f709224bac9cc109220586bc14_G9, SystemTracker:gateway7, Timestamp:2023-04-08T02:07:17, errorContext[NAMESPACE: lfdnodc33.servicebus.windows.net. ERROR CONTEXT: N/A, PATH: objectnotification, REFERENCE_ID: objectnotification_ab2efd_1680618395096, LINK_CREDIT: 1]
2023-04-08 02:08:09.338 [boundedElastic-4] [c.a.m.s.FluxAutoComplete] ERROR Error occurred. Passing downstream.
The service was unable to process the request; please retry the operation. For more information on exception types and proper exception handling, please refer to http://go.microsoft.com/fwlink/?LinkId=761101 TrackingId:500e00f709224bac9cc109220586bc14_G9, SystemTracker:gateway7, Timestamp:2023-04-08T02:07:17, errorContext[NAMESPACE: lfdnodc33.servicebus.windows.net. ERROR CONTEXT: N/A, PATH: objectnotification, REFERENCE_ID: objectnotification_ab2efd_1680618395096, LINK_CREDIT: 1]
2023-04-08 02:08:09.342 [reactor-executor-1] [c.a.c.a.i.ActiveClientTokenManager] INFO  {"az.sdk.message":"Scheduling refresh token task.","scopes":"amqp://lfdnodc33.servicebus.windows.net/objectnotification"}
2023-04-08 02:08:09.342 [reactor-executor-1] [c.a.c.a.i.ReactorSession] INFO  {"az.sdk.message":"Creating a new receiver link.","connectionId":"MF_20c602_1680618393793","sessionName":"objectnotification","linkName":"objectnotification_ab2efd_1680618395096"}
2023-04-08 02:08:09.396 [boundedElastic-4] [o.a.c.c.a.s.ServiceBusConsumer] WARN  Error processing exchange. Exchange[]. Caused by: [com.azure.messaging.servicebus.ServiceBusException - The service was unable to process the request; please retry the operation. For more information on exception types and proper exception handling, please refer to http://go.microsoft.com/fwlink/?LinkId=761101 TrackingId:500e00f709224bac9cc109220586bc14_G9, SystemTracker:gateway7, Timestamp:2023-04-08T02:07:17, errorContext[NAMESPACE: lfdnodc33.servicebus.windows.net. ERROR CONTEXT: N/A, PATH: objectnotification, REFERENCE_ID: objectnotification_ab2efd_1680618395096, LINK_CREDIT: 1]]
com.azure.messaging.servicebus.ServiceBusException: The service was unable to process the request; please retry the operation. For more information on exception types and proper exception handling, please refer to http://go.microsoft.com/fwlink/?LinkId=761101 TrackingId:500e00f709224bac9cc109220586bc14_G9, SystemTracker:gateway7, Timestamp:2023-04-08T02:07:17, errorContext[NAMESPACE: lfdnodc33.servicebus.windows.net. ERROR CONTEXT: N/A, PATH: objectnotification, REFERENCE_ID: objectnotification_ab2efd_1680618395096, LINK_CREDIT: 1]
	at com.azure.messaging.servicebus.ServiceBusReceiverAsyncClient.mapError(ServiceBusReceiverAsyncClient.java:1628)
	at com.azure.messaging.servicebus.ServiceBusReceiverAsyncClient.lambda$receiveMessagesWithContext$22(ServiceBusReceiverAsyncClient.java:866)
	at reactor.core.publisher.Flux.lambda$onErrorMap$28(Flux.java:6908)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94)
	at com.azure.messaging.servicebus.FluxAutoComplete$AutoCompleteSubscriber.hookOnError(FluxAutoComplete.java:118)
	at reactor.core.publisher.BaseSubscriber.onError(BaseSubscriber.java:180)
	at com.azure.messaging.servicebus.FluxAutoLockRenew$LockRenewSubscriber.hookOnError(FluxAutoLockRenew.java:124)
	at reactor.core.publisher.BaseSubscriber.onError(BaseSubscriber.java:180)
	at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:134)
	at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:134)
	at com.azure.messaging.servicebus.implementation.ServiceBusReceiveLinkProcessor.onError(ServiceBusReceiveLinkProcessor.java:368)
	at com.azure.messaging.servicebus.implementation.ServiceBusReceiveLinkProcessor.lambda$onNext$5(ServiceBusReceiveLinkProcessor.java:247)
	at reactor.core.publisher.LambdaSubscriber.onError(LambdaSubscriber.java:149)
	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.onError(FluxSubscribeOn.java:157)
	at reactor.core.publisher.SerializedSubscriber.onError(SerializedSubscriber.java:124)
	at reactor.core.publisher.FluxTakeUntilOther$TakeUntilMainSubscriber.onError(FluxTakeUntilOther.java:231)
	at reactor.core.publisher.FluxDistinctUntilChanged$DistinctUntilChangedSubscriber.onError(FluxDistinctUntilChanged.java:162)
	at reactor.core.publisher.FluxReplay$SizeBoundReplayBuffer.replayNormal(FluxReplay.java:865)
	at reactor.core.publisher.FluxReplay$SizeBoundReplayBuffer.replay(FluxReplay.java:965)
	at reactor.core.publisher.FluxReplay$ReplayInner.request(FluxReplay.java:1711)
	at reactor.core.publisher.FluxDistinctUntilChanged$DistinctUntilChangedSubscriber.request(FluxDistinctUntilChanged.java:193)
	at reactor.core.publisher.FluxTakeUntilOther$TakeUntilMainSubscriber.request(FluxTakeUntilOther.java:174)
	at reactor.core.publisher.SerializedSubscriber.request(SerializedSubscriber.java:151)
	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.requestUpstream(FluxSubscribeOn.java:131)
	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.onSubscribe(FluxSubscribeOn.java:124)
	at reactor.core.publisher.SerializedSubscriber.onSubscribe(SerializedSubscriber.java:65)
	at reactor.core.publisher.FluxTakeUntilOther$TakeUntilMainSubscriber.onSubscribe(FluxTakeUntilOther.java:211)
	at reactor.core.publisher.FluxDistinctUntilChanged$DistinctUntilChangedSubscriber.onSubscribe(FluxDistinctUntilChanged.java:96)
	at reactor.core.publisher.FluxReplay.subscribeOrReturn(FluxReplay.java:1181)
	at reactor.core.publisher.FluxReplay.subscribe(FluxReplay.java:1153)
	at reactor.core.publisher.FluxAutoConnectFuseable.subscribe(FluxAutoConnectFuseable.java:61)
	at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62)
	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.run(FluxSubscribeOn.java:194)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.azure.core.amqp.exception.AmqpException: The service was unable to process the request; please retry the operation. For more information on exception types and proper exception handling, please refer to http://go.microsoft.com/fwlink/?LinkId=761101 TrackingId:500e00f709224bac9cc109220586bc14_G9, SystemTracker:gateway7, Timestamp:2023-04-08T02:07:17, errorContext[NAMESPACE: lfdnodc33.servicebus.windows.net. ERROR CONTEXT: N/A, PATH: objectnotification, REFERENCE_ID: objectnotification_ab2efd_1680618395096, LINK_CREDIT: 1]
	at com.azure.core.amqp.implementation.ExceptionUtil.toException(ExceptionUtil.java:85)
	at com.azure.core.amqp.implementation.handler.LinkHandler.handleRemoteLinkClosed(LinkHandler.java:120)
	at com.azure.core.amqp.implementation.handler.LinkHandler.onLinkRemoteClose(LinkHandler.java:64)
	at com.azure.core.amqp.implementation.handler.ReceiveLinkHandler.onLinkRemoteClose(ReceiveLinkHandler.java:228)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:176)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291)
	at com.azure.core.amqp.implementation.ReactorExecutor.run(ReactorExecutor.java:91)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	... 5 common frames omitted
2023-04-08 02:08:09.701 [reactor-executor-1] [c.a.c.a.i.h.ReceiveLinkHandler] INFO  {"az.sdk.message":"onLinkRemoteOpen","connectionId":"MF_20c602_1680618393793","entityPath":"objectnotification","linkName":"objectnotification_ab2efd_1680618395096","remoteSource":"Source{address='objectnotification', durable=NONE, expiryPolicy=SESSION_END, timeout=0, dynamic=false, dynamicNodeProperties=null, distributionMode=null, filter=null, defaultOutcome=null, outcomes=null, capabilities=null}"}`

**To Reproduce**
This was a one time issue we got recently once for the past month, but wanted to confirm what may caused it

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - IDE: [e.g. IntelliJ]
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)]
 - Java version: [e.g. 8] 
 - App Server/Environment: [e.g. Tomcat, WildFly, Azure Function, Apache Spark, Databricks, IDE plugin or anything special]
 - Frameworks: [e.g. Spring Boot, Micronaut, Quarkus, etc] 

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**
`Caused by: [com.azure.messaging.servicebus.ServiceBusException - The service was unable to process the request; please retry the operation. For more information on exception types and proper exception handling, please refer to http://go.microsoft.com/fwlink/?LinkId=761101 TrackingId:500e00f709224bac9cc109220586bc14_G9, SystemTracker:gateway7, Timestamp:2023-04-08T02:07:17, errorContext[NAMESPACE: lfdnodc33.servicebus.windows.net. ERROR CONTEXT: N/A, PATH: objectnotification, REFERENCE_ID: objectnotification_ab2efd_1680618395096, LINK_CREDIT: 1]]`

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by anuchandy** [comment]
Hi [@ArtemTraierLotus](https://github.com/ArtemTraierLotus), thanks for reaching out. There are known issues with how Apache Camel uses the Service Bus library. For details, please refer this thread https://github.com/Azure/azure-sdk-for-java/issues/26465#issuecomment-1445643543 and history. The suggestion is to open a ticket in the Apache Camel plugin repo, as mentioned in the above thread.

**Comment by ArtemTraierLotus** [comment]
@anuchandy @joshfree  thank you for response, I get it, will check out with camel plugin
