### ISSUE TITLE
[BUG] - Spring Boot application threads are blocked indefinitely querying in Cosmos using Spring Data

### ISSUE THREAD

**Issue by apescione** [Azure/azure-sdk-for-java#34406]
**Describe the bug**
Spring boot application based on Tomcat - Spring Data Cosmos -  at some point, all HTTP threads are in WAITING state for Spring Data Cosmos parallel-*  threads. When it happens, the application is frozen (CPU 0% and high memory usage), and only restart can fix it.

***Exception or Stack Trace***
No exceptions were explicitly found. The Application thread dump looks like:

**HTTP Pool**
```
"http-nio-8080-exec-378" #818 daemon prio=5 os_prio=0 tid=0x00000000247a5000 nid=0x84cc waiting on condition [0x0000000047c7c000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000007315cb968> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
        at reactor.core.publisher.BlockingIterable$SubscriberIterator.hasNext(BlockingIterable.java:179)
        at java.util.Iterator.forEachRemaining(Iterator.java:115)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at com.cosmos.example.web.rest.PetDelegateImpl.searchPet(PetDelegateImpl.java:66)
        at com.cosmos.example.server.Pets.api.PetsApi.searchPet(PetsApi.java:79)
        at sun.reflect.GeneratedMethodAccessor109.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

```
**cosmos-parallel-x**

```
"cosmos-parallel-2" #39 daemon prio=5 os_prio=0 tid=0x000000002798d000 nid=0x54c4 waiting on condition [0x000000002e4bf000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000006c3138198> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
        at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1081)
        at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
        - None

```

**parallel-x**

```
"parallel-3" #61 daemon prio=5 os_prio=0 tid=0x000000001ff2a000 nid=0x8f20 waiting on condition [0x0000000032e3f000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000006c3649c28> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
        at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1081)
        at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
        - None

```

**To Reproduce**
This issue can be replicated with a simple application stress test using the Apache Jmeter tool. The Cosmos collection had about 600.000 documents. No 429 error code has been found during the tests.

***Code Snippet***

Analyzing Azure Spring Data Cosmos repository, I potentially found the root cause in the usage of Reactor API in the class ```com.azure.spring.data.cosmos.core.CosmosTemplate```:

```
   public <T> T findById(String containerName, Object id, Class<T> domainType) {
        Assert.hasText(containerName, "containerName should not be null, empty or only whitespaces");
        Assert.notNull(domainType, "domainType should not be null");

        final String query = "select * from root where root.id = @ROOT_ID";
        final SqlParameter param = new SqlParameter("@ROOT_ID", CosmosUtils.getStringIDValue(id));
        final SqlQuerySpec sqlQuerySpec = new SqlQuerySpec(query, param);
        final CosmosQueryRequestOptions options = new CosmosQueryRequestOptions();
        options.setQueryMetricsEnabled(this.queryMetricsEnabled);
        return cosmosAsyncClient
            .getDatabase(this.databaseName)
            .getContainer(containerName)
            .queryItems(sqlQuerySpec, options, JsonNode.class)
            .byPage()
            .publishOn(Schedulers.parallel())
            .flatMap(cosmosItemFeedResponse -> {
                CosmosUtils.fillAndProcessResponseDiagnostics(this.responseDiagnosticsProcessor,
                    cosmosItemFeedResponse.getCosmosDiagnostics(), cosmosItemFeedResponse);
                return Mono.justOrEmpty(cosmosItemFeedResponse
                    .getResults()
                    .stream()
                    .map(cosmosItem -> emitOnLoadEventAndConvertToDomainObject(domainType, containerName, cosmosItem))
                    .findFirst());
            })
            .onErrorResume(throwable ->
                CosmosExceptionUtils.findAPIExceptionHandler("Failed to find item", throwable,
                    this.responseDiagnosticsProcessor))
            .blockFirst();
    }
```
- The ```blockFirst``` Api, without a timeout, forces the Thread to wait indefinitely (Reactor provides also the API that includes the timeout)
- ```Schedulers.parallel()``` should be used for fast execution as for its [documentation ](https://projectreactor.io/docs/core/3.4.12/api/reactor/core/scheduler/Schedulers.html)"Optimized for fast Runnable non-blocking executions". This code could be configurable.

**Expected behavior**
Any thread should not wait indefinitely, but at least it should raise an exception.

**Setup (please complete the following information):**
 - OS: Windows 10
 - IDE: IntelliJ
 - Library/Libraries: azure-spring-data-cosmos-3.16.0.jar
 - Java version: 8
 - App Server/Environment: Tomcat Embedded
 - Frameworks: Spring Boot 2.3.6.RELEASE

**Comment by joshfree** [comment]
@kushagraThapar could you help route @apescione's github issue?

**Comment by kushagraThapar** [comment]
@apescione - this looks like an issue that we solved sometime back. I would recommend upgrading to the latest version - https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-spring-data-cosmos/CHANGELOG.md#3330-2023-03-17 
you can find more information on the changelog of azure-cosmos (which had a dead-lock fixed in some earlier version) - https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-cosmos/CHANGELOG.md

**Comment by apescione** [comment]
Unfortunately, the latest versions of both azure-spring-data-cosmos and azure-cosmos don't fix this issue. All Threads are again stuck in waiting. These are the used versions:

```
        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-spring-data-cosmos</artifactId>
            <version>3.33.0</version>
        </dependency>
        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-cosmos</artifactId>
            <version>4.43.0</version>
        </dependency>
```

Here one piece of ThreadDump

```
"http-nio-8080-exec-21" #94 daemon prio=5 os_prio=0 tid=0x0000000024ccb800 nid=0x6068 waiting on condition [0x00000000374ed000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000006c458d3d0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at reactor.core.publisher.BlockingIterable$SubscriberIterator.hasNext(BlockingIterable.java:179)
	at java.util.Iterator.forEachRemaining(Iterator.java:115)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.cosmos.example.web.rest.PetDelegateImpl.searchPet(PetDelegateImpl.java:106)
	at com.cosmos.example.server.Pets.api.PetsApi.searchPet(PetsApi.java:111)
	at sun.reflect.GeneratedMethodAccessor52.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

```

**Comment by kushagraThapar** [comment]
@apescione thanks for the information, however with my local testing, I am able to get those documents back on query. Also, this blocking pattern is consistently used throughout all azure SDKs, including spring-data-cosmos, azure-cosmos and many more. I doubt if it is the issue with the blocking pattern. 

You mentioned the collection has 600.000 documents. Did you mean 600K documents? And you are trying to query all of them through one single query? Can you provide a sample application that can repro this?

**Comment by pasmimmo** [comment]
@apescione, @kushagraThapar seems this issue is related with a similar in the following link https://github.com/Azure/azure-sdk-for-java/issues/30261

**Comment by kushagraThapar** [comment]
@pasmimmo I recall this CFP issue has been fixed sometime back. so shouldn't happen on the new version. 
@apescione  - can you please provide more details on the above asked question?

**Comment by apescione** [comment]
I've prepared a repo and a Jmeter file to show you how to replicate the issue. I hope to publish it in a few days.

**Comment by kushagraThapar** [comment]
@apescione  - ack, looking forward to the investigation, thanks for the update!

**Comment by apescione** [comment]
@kushagraThapar  here https://github.com/apescione/spring-data-cosmos-tests you can find the application example. This is just an example to reproduce locally the Threads Stuck. Let me know if you need more information or others.
Thank you

**Comment by kushagraThapar** [comment]
@apescione - awesome, will give it a shot today, will keep you posted on how it goes, thanks!

**Comment by kushagraThapar** [comment]
@apescione - I looked at the code and it as you mentioned, it is not the best practice or even recommended practice to execute queries. It will of course cause the threads to look like they are getting stuck for a very long time because the operation takes a very long time to complete. 

spring-data-cosmos doesn't have bulk functionality yet, so inserting or retrieving 500,000 documents at once, using a single API call is not going to be fast and effective. 

It may seem that the threads are stuck, specially looking at the thread dump, however, in reality they all are making progress which you can see from the account metrics. (I ran on a production account and could see the progress on the metrics tab in azure portal). 

Also, for query, I see error because maximum response size is reached for getting these many results back in a single query :)

You can see how the create operation for total 500k requests took around 1.5 hours. Also, some of the thread dumps I took show this create operation getting stuck, however, it is making progress, just slow because it is a synchronous operation. 

"http-nio-8080-exec-9" #84 [57859] daemon prio=5 os_prio=31 cpu=209883.91ms elapsed=5328.68s tid=0x00007feea8191000 nid=57859 waiting on condition  [0x000070000c53a000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@19.0.1/Native Method)
	- parking to wait for  <0x00000007108b4ab0> (a java.util.concurrent.CountDownLatch$Sync)
	at java.util.concurrent.locks.LockSupport.park(java.base@19.0.1/LockSupport.java:221)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(java.base@19.0.1/AbstractQueuedSynchronizer.java:715)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(java.base@19.0.1/AbstractQueuedSynchronizer.java:1047)
	at java.util.concurrent.CountDownLatch.await(java.base@19.0.1/CountDownLatch.java:230)
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:87)
	at reactor.core.publisher.Mono.block(Mono.java:1742)
	at com.azure.spring.data.cosmos.core.CosmosTemplate.insert(CosmosTemplate.java:236)
	at com.azure.spring.data.cosmos.core.CosmosTemplate.insert(CosmosTemplate.java:195)
	at com.azure.spring.data.cosmos.repository.support.SimpleCosmosRepository.save(SimpleCosmosRepository.java:101)
	...
	at com.example.petmanagement.web.PetController.lambda$createPets$0(PetController.java:49)
	at com.example.petmanagement.web.PetController$$Lambda$1533/0x0000000801668c00.accept(Unknown Source)
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(java.base@19.0.1/Streams.java:104)
	at java.util.stream.IntPipeline$Head.forEach(java.base@19.0.1/IntPipeline.java:617)
	at com.example.petmanagement.web.PetController.createPets(PetController.java:40)
	...

![image](https://user-images.githubusercontent.com/14034156/236334211-a6ac943d-0b5e-4c2f-b86c-cf96b48bfe66.png)

**Comment by apescione** [comment]
Hi @kushagraThapar, thank you for your support, but the main problem is with the search api. As you can see, if I have the possibility to set a timeout, I can unstuck the threads and avoid the application freeze.  Anyway, my application example is just to highlight the missing timeout. In production, we have the application freeze for several days and it became unusable only a restart can resolve the issue. Unfortunately, I cannot publish production code, but in this application, all best practices are applied. This kind of issue occurs also for FindById API. If you need more information, please let me know. thanks again.

**Comment by kushagraThapar** [comment]
@apescione - we have end to end timeout coming out soon in our APIs for Cosmos Java SDK and then possibly soon in spring-data-cosmos, however, I doubt if that will solve your issue, because then your search API will just timeout since you are trying to search for everything all at once. 

The correct solution to this would be to implement pagination on client side, and only look up for the documents that you need for the current page. 
I am curious to know how `findById` is causing issues, because that just returns 1 document back and should not hang at all. 

I have re-opened this issue, so feel free to provide more information here regarding `findById` API. You don't have to provide your production code, just sample code would work. 
Also, if you would like, feel free to open a support ticket at Azure Cosmos DB and we can investigate through that route as well.

**Comment by kushagraThapar** [comment]
@apescione  - you can open a support ticket here if you would like - https://azure.microsoft.com/support/create-ticket 
Otherwise we can continue the discussion here, either works for me, thanks!

**Comment by apescione** [comment]
@kushagraThapar, I was giving a look at this page:

https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/best-practice-java

and I saw that some best practices seem are not followed by Spring Data, in particular:
```
Use Appropriate Scheduler (Avoid stealing Event loop IO Netty threads)
```
and 

```
End-to-End Timeouts
```
Please give me feedback about it.
I really appreciate any help you can provide.

**Comment by kushagraThapar** [comment]
@apescione - spring-data-cosmos follows the usage of appropriate scheduler (by changing the threads to reactor parallel threads in every call). It doesn't use end to end timeout policy yet, but as I said, it won't help in you case, as the API will just timeout since you are trying to query everything at once.  

Based on the last conversation we had above - `I am curious to know how findById is causing issues, because that just returns 1 document back and should not hang at all`.
Do you have any update on this?
