### ISSUE TITLE
[BUG] testproxy, LRO throw error when running tests in RECORD mode

### ISSUE THREAD

**Issue by haolingdong-msft** [Azure/azure-sdk-for-java#34453]
**Describe the bug**

Encounter below error when running [`ConfidentialLedgerManagementTest`](https://github.com/haolingdong-msft/azure-sdk-for-java/blob/migrate-test-recording/sdk/confidentialledger/azure-resourcemanager-confidentialledger/src/test/java/com/azure/resourcemanager/confidentialledger/ConfidentialLedgerManagementTest.java) in RECORD mode using test proxy.
The reason is because we store([code](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/core/azure-core-management/src/main/java/com/azure/core/management/polling/PollerFactory.java#L93)) the request url when initiate LRO, the url is "http://localhost:5000", it is `http` instead of `https`. We store this url after polling status succeeded and fire the final request to get the resource. When getting final result using this url, it throws exception during this [validation](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/core/azure-core/src/main/java/com/azure/core/http/policy/BearerTokenAuthenticationPolicy.java#L93) because it is `http` instead of `https`.

**Note:** Data plane LRO may also have this issue, it will also store the url [here](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/core/azure-core/src/main/java/com/azure/core/util/polling/OperationResourcePollingStrategy.java#L147)
```
[ForkJoinPool-1-worker-1] INFO com.azure.core.test.TestBase - Test Mode: RECORD, Name: ledgerCreateTest
[ForkJoinPool.commonPool-worker-1] INFO com.microsoft.aad.msal4j.AcquireTokenSilentSupplier - Returning token from cache
[ForkJoinPool.commonPool-worker-1] INFO com.azure.identity.ClientSecretCredential - Azure Identity => getToken() result for scopes [https://management.core.windows.net//.default]: SUCCESS
[ForkJoinPool.commonPool-worker-1] INFO com.azure.identity.ChainedTokenCredential - Azure Identity => Attempted credential EnvironmentCredential returns a token
[ForkJoinPool.commonPool-worker-1] INFO com.azure.core.implementation.AccessTokenCache - Acquired a new access token.
[reactor-http-nio-3] INFO com.azure.resourcemanager.confidentialledger.implementation.LedgersClientImpl$LedgersService.create - {"az.sdk.message":"HTTP request","method":"PUT","url":"http://localhost:5000/subscriptions/ec0aa5f7-9e78-40c9-85cd-535c6305b380/resourceGroups/acl-sdk-test-rg1681438036/providers/Microsoft.ConfidentialLedger/ledgers/acl-java-sdk-create-test?api-version=2022-05-13","tryCount":"1","Date":"Fri, 14 Apr 2023 02:07:23 GMT","Authorization":"REDACTED","Content-Length":"990","x-recording-mode":"REDACTED","x-recording-upstream-base-uri":"REDACTED","Content-Type":"application/json","x-recording-id":"REDACTED","x-ms-client-request-id":"4f139d7b-4df4-49a2-89dd-a76c360761fb","Accept":"application/json","User-Agent":"azsdk-java-com.azure.resourcemanager.confidentialledger/1.0.0-beta.1 (17.0.4.1; Windows 11; 10.0; auto-generated)","contentLength":990,"body":"{\"properties\":{\"ledgerType\":\"Public\",\"aadBasedSecurityPrincipals\":[{\"principalId\":\"074307f6-5baa-46bd-afd0-304b1f46345f\",\"tenantId\":\"72f988bf-86f1-41af-91ab-2d7cd011db47\",\"ledgerRoleName\":\"Administrator\"}],\"certBasedSecurityPrincipals\":[{\"cert\":\"-----BEGIN CERTIFICATE-----MIIBxTCCAUygAwIBAgIUFXobF1KhnQzlaPcPRe2tI8fdjjwwCgYIKoZIzj0EAwMwGjEYMBYGA1UEAwwPQUNMIENsaWVudCBDZXJ0MB4XDTIyMDgxNjE2Mjk1NFoXDTIzMDgxNjE2Mjk1NFowGjEYMBYGA1UEAwwPQUNMIENsaWVudCBDZXJ0MHYwEAYHKoZIzj0CAQYFK4EEACIDYgAE1GafPSAqwzZyTJDnzD5DSyue0hANYCwr1XIMjbRDJHOPEPsPK/fMThMHPXjV4LXOVVL0bwj+V5LD3U07ZaMJztvZOrRf+c6bP59U0GZlZM/DvPYfml9es/O2e62m1il9o1MwUTAdBgNVHQ4EFgQUg9kRNgnyP1nILNXBKfGvFjgaYP0wHwYDVR0jBBgwFoAUg9kRNgnyP1nILNXBKfGvFjgaYP0wDwYDVR0TAQH/BAUwAwEB/zAKBggqhkjOPQQDAwNnADBkAjAK/K4xWMTVq9uZwiOlo80MaYjA5V8xbWQBCsyrQzfyaxr1ol61lGlGyUqM1rGVUm4CMA9D8Z2Vblz3SaJwKBTe5PlBebZfS5a6gRs/fmL1RdmIQVjSFsx8OB1/nyIdARwhaQ==-----END CERTIFICATE-----\",\"ledgerRoleName\":\"Contributor\"}]},\"location\":\"eastus\",\"tags\":{\"tag1\":\"value\"}}"}
[reactor-http-nio-3] INFO com.azure.resourcemanager.confidentialledger.implementation.LedgersClientImpl$LedgersService.create - {"az.sdk.message":"HTTP response","contentLength":"1816","statusCode":201,"url":"http://localhost:5000/subscriptions/ec0aa5f7-9e78-40c9-85cd-535c6305b380/resourceGroups/acl-sdk-test-rg1681438036/providers/Microsoft.ConfidentialLedger/ledgers/acl-java-sdk-create-test?api-version=2022-05-13","durationMs":9532,"x-ms-providerhub-traffic":"REDACTED","Date":"Fri, 14 Apr 2023 02:07:32 GMT","x-ms-machineName":"REDACTED","Server":"Kestrel","Content-Length":"1816","Expires":"-1","x-ms-async-operation-timeout":"REDACTED","x-ms-ratelimit-remaining-subscription-writes":"REDACTED","x-ms-image-tag":"REDACTED","Strict-Transport-Security":"REDACTED","x-ms-correlation-request-id":"REDACTED","Pragma":"no-cache","X-Content-Type-Options":"REDACTED","x-ms-routing-request-id":"REDACTED","x-ms-image-digest":"REDACTED","ETag":"\"010038c4-0000-0100-0000-6438b5610000\"","Content-Type":"application/json; charset=utf-8","Cache-Control":"no-cache","x-ms-request-id":"8afef067-af99-420b-8149-bbdb0f01bea0","Azure-AsyncOperation":"REDACTED","x-ms-client-request-id":"4f139d7b-4df4-49a2-89dd-a76c360761fb","body":"{\"id\":\"/subscriptions/ec0aa5f7-9e78-40c9-85cd-535c6305b380/resourceGroups/acl-sdk-test-rg1681438036/providers/Microsoft.ConfidentialLedger/ledgers/acl-java-sdk-create-test\",\"name\":\"acl-java-sdk-create-test\",\"type\":\"microsoft.confidentialledger/ledgers\",\"location\":\"eastus\",\"tags\":{\"tag1\":\"value\"},\"systemData\":{\"createdBy\":\"cbd21561-2da6-499b-b745-786faaff18b2\",\"createdByType\":\"Application\",\"createdAt\":\"2023-04-14T02:07:28.0374549Z\",\"lastModifiedBy\":\"cbd21561-2da6-499b-b745-786faaff18b2\",\"lastModifiedByType\":\"Application\",\"lastModifiedAt\":\"2023-04-14T02:07:28.0374549Z\"},\"properties\":{\"ledgerName\":\"acl-java-sdk-create-test\",\"ledgerType\":\"Public\",\"aadBasedSecurityPrincipals\":[{\"principalId\":\"074307f6-5baa-46bd-afd0-304b1f46345f\",\"tenantId\":\"72f988bf-86f1-41af-91ab-2d7cd011db47\",\"ledgerRoleName\":\"Administrator\"},{\"principalId\":\"174bb102-95f3-4d79-8cce-f3a839e08a37\",\"tenantId\":\"72f988bf-86f1-41af-91ab-2d7cd011db47\",\"ledgerRoleName\":\"Administrator\"}],\"certBasedSecurityPrincipals\":[{\"cert\":\"-----BEGIN CERTIFICATE-----MIIBxTCCAUygAwIBAgIUFXobF1KhnQzlaPcPRe2tI8fdjjwwCgYIKoZIzj0EAwMwGjEYMBYGA1UEAwwPQUNMIENsaWVudCBDZXJ0MB4XDTIyMDgxNjE2Mjk1NFoXDTIzMDgxNjE2Mjk1NFowGjEYMBYGA1UEAwwPQUNMIENsaWVudCBDZXJ0MHYwEAYHKoZIzj0CAQYFK4EEACIDYgAE1GafPSAqwzZyTJDnzD5DSyue0hANYCwr1XIMjbRDJHOPEPsPK/fMThMHPXjV4LXOVVL0bwj+V5LD3U07ZaMJztvZOrRf+c6bP59U0GZlZM/DvPYfml9es/O2e62m1il9o1MwUTAdBgNVHQ4EFgQUg9kRNgnyP1nILNXBKfGvFjgaYP0wHwYDVR0jBBgwFoAUg9kRNgnyP1nILNXBKfGvFjgaYP0wDwYDVR0TAQH/BAUwAwEB/zAKBggqhkjOPQQDAwNnADBkAjAK/K4xWMTVq9uZwiOlo80MaYjA5V8xbWQBCsyrQzfyaxr1ol61lGlGyUqM1rGVUm4CMA9D8Z2Vblz3SaJwKBTe5PlBebZfS5a6gRs/fmL1RdmIQVjSFsx8OB1/nyIdARwhaQ==-----END CERTIFICATE-----\",\"ledgerRoleName\":\"Contributor\"}],\"ledgerInternalNamespace\":\"8b3ca12b-9aee-4e68-b20e-7fdbf1f117a0\",\"ledgerSku\":\"Unknown\",\"provisioningState\":\"Accepted\"}}"}
[parallel-2] INFO  - {"az.sdk.message":"HTTP request","method":"GET","url":"http://localhost:5000/providers/Microsoft.ConfidentialLedger/locations/EASTUS/operationStatuses/8afef067-af99-420b-8149-bbdb0f01bea0*0A4299ECC6C7BD4E0BE582CF01FAD6D6EFA85278C6DBFEA74E4FFF8758D580B2?api-version=2022-05-13","tryCount":"1","Date":"Fri, 14 Apr 2023 02:08:02 GMT","Authorization":"REDACTED","x-recording-mode":"REDACTED","x-recording-upstream-base-uri":"REDACTED","x-recording-id":"REDACTED","x-ms-client-request-id":"aa1f3d89-47ed-4b4b-b709-907f6d871be0","Accept":"application/json","User-Agent":"azsdk-java-com.azure.resourcemanager.confidentialledger/1.0.0-beta.1 (17.0.4.1; Windows 11; 10.0; auto-generated)","contentLength":0}
[reactor-http-nio-3] INFO  - {"az.sdk.message":"HTTP response","contentLength":"539","statusCode":200,"url":"http://localhost:5000/providers/Microsoft.ConfidentialLedger/locations/EASTUS/operationStatuses/8afef067-af99-420b-8149-bbdb0f01bea0*0A4299ECC6C7BD4E0BE582CF01FAD6D6EFA85278C6DBFEA74E4FFF8758D580B2?api-version=2022-05-13","durationMs":998,"Content-Length":"539","Content-Type":"application/json; charset=utf-8","Date":"Fri, 14 Apr 2023 02:08:02 GMT","Server":"Kestrel","Cache-Control":"no-cache","ETag":"\"00009c59-0000-0100-0000-6438b5610000\"","Expires":"-1","Pragma":"no-cache","x-ms-ratelimit-remaining-tenant-reads":"REDACTED","x-ms-request-id":"344eaeea-d40f-45db-967d-9937ca06a5b2","x-ms-correlation-request-id":"REDACTED","x-ms-routing-request-id":"REDACTED","Strict-Transport-Security":"REDACTED","X-Content-Type-Options":"REDACTED","body":"{\"id\":\"/providers/Microsoft.ConfidentialLedger/locations/EASTUS/operationStatuses/8afef067-af99-420b-8149-bbdb0f01bea0*0A4299ECC6C7BD4E0BE582CF01FAD6D6EFA85278C6DBFEA74E4FFF8758D580B2\",\"name\":\"8afef067-af99-420b-8149-bbdb0f01bea0*0A4299ECC6C7BD4E0BE582CF01FAD6D6EFA85278C6DBFEA74E4FFF8758D580B2\",\"resourceId\":\"/subscriptions/ec0aa5f7-9e78-40c9-85cd-535c6305b380/resourceGroups/acl-sdk-test-rg1681438036/providers/Microsoft.ConfidentialLedger/ledgers/acl-java-sdk-create-test\",\"status\":\"Accepted\",\"startTime\":\"2023-04-14T02:07:29.2720163Z\"}"}
[parallel-3] INFO  - {"az.sdk.message":"HTTP request","method":"GET","url":"http://localhost:5000/providers/Microsoft.ConfidentialLedger/locations/EASTUS/operationStatuses/8afef067-af99-420b-8149-bbdb0f01bea0*0A4299ECC6C7BD4E0BE582CF01FAD6D6EFA85278C6DBFEA74E4FFF8758D580B2?api-version=2022-05-13","tryCount":"1","Date":"Fri, 14 Apr 2023 02:08:33 GMT","Authorization":"REDACTED","x-recording-mode":"REDACTED","x-recording-upstream-base-uri":"REDACTED","x-recording-id":"REDACTED","x-ms-client-request-id":"28433f90-e935-44ac-99ae-d07b2afa6e21","Accept":"application/json","User-Agent":"azsdk-java-com.azure.resourcemanager.confidentialledger/1.0.0-beta.1 (17.0.4.1; Windows 11; 10.0; auto-generated)","contentLength":0}
[reactor-http-nio-3] INFO  - {"az.sdk.message":"HTTP response","contentLength":"539","statusCode":200,"url":"http://localhost:5000/providers/Microsoft.ConfidentialLedger/locations/EASTUS/operationStatuses/8afef067-af99-420b-8149-bbdb0f01bea0*0A4299ECC6C7BD4E0BE582CF01FAD6D6EFA85278C6DBFEA74E4FFF8758D580B2?api-version=2022-05-13","durationMs":309,"Content-Length":"539","Content-Type":"application/json; charset=utf-8","Date":"Fri, 14 Apr 2023 02:08:33 GMT","Server":"Kestrel","Cache-Control":"no-cache","ETag":"\"00009c59-0000-0100-0000-6438b5610000\"","Expires":"-1","Pragma":"no-cache","x-ms-ratelimit-remaining-tenant-reads":"REDACTED","x-ms-request-id":"ac0ca24b-6088-4c80-bc8f-2d7783e3b179","x-ms-correlation-request-id":"REDACTED","x-ms-routing-request-id":"REDACTED","Strict-Transport-Security":"REDACTED","X-Content-Type-Options":"REDACTED","body":"{\"id\":\"/providers/Microsoft.ConfidentialLedger/locations/EASTUS/operationStatuses/8afef067-af99-420b-8149-bbdb0f01bea0*0A4299ECC6C7BD4E0BE582CF01FAD6D6EFA85278C6DBFEA74E4FFF8758D580B2\",\"name\":\"8afef067-af99-420b-8149-bbdb0f01bea0*0A4299ECC6C7BD4E0BE582CF01FAD6D6EFA85278C6DBFEA74E4FFF8758D580B2\",\"resourceId\":\"/subscriptions/ec0aa5f7-9e78-40c9-85cd-535c6305b380/resourceGroups/acl-sdk-test-rg1681438036/providers/Microsoft.ConfidentialLedger/ledgers/acl-java-sdk-create-test\",\"status\":\"Accepted\",\"startTime\":\"2023-04-14T02:07:29.2720163Z\"}"}
[parallel-4] INFO  - {"az.sdk.message":"HTTP request","method":"GET","url":"http://localhost:5000/providers/Microsoft.ConfidentialLedger/locations/EASTUS/operationStatuses/8afef067-af99-420b-8149-bbdb0f01bea0*0A4299ECC6C7BD4E0BE582CF01FAD6D6EFA85278C6DBFEA74E4FFF8758D580B2?api-version=2022-05-13","tryCount":"1","Date":"Fri, 14 Apr 2023 02:09:04 GMT","Authorization":"REDACTED","x-recording-mode":"REDACTED","x-recording-upstream-base-uri":"REDACTED","x-recording-id":"REDACTED","x-ms-client-request-id":"154f4ffe-9dc1-4883-aeeb-9f8c6dd4a98c","Accept":"application/json","User-Agent":"azsdk-java-com.azure.resourcemanager.confidentialledger/1.0.0-beta.1 (17.0.4.1; Windows 11; 10.0; auto-generated)","contentLength":0}
[reactor-http-nio-3] INFO  - {"az.sdk.message":"HTTP response","contentLength":"539","statusCode":200,"url":"http://localhost:5000/providers/Microsoft.ConfidentialLedger/locations/EASTUS/operationStatuses/8afef067-af99-420b-8149-bbdb0f01bea0*0A4299ECC6C7BD4E0BE582CF01FAD6D6EFA85278C6DBFEA74E4FFF8758D580B2?api-version=2022-05-13","durationMs":311,"Content-Length":"539","Content-Type":"application/json; charset=utf-8","Date":"Fri, 14 Apr 2023 02:09:03 GMT","Server":"Kestrel","Cache-Control":"no-cache","ETag":"\"00009c59-0000-0100-0000-6438b5610000\"","Expires":"-1","Pragma":"no-cache","x-ms-ratelimit-remaining-tenant-reads":"REDACTED","x-ms-request-id":"add295f4-0259-437c-b0d3-285fac82ec2f","x-ms-correlation-request-id":"REDACTED","x-ms-routing-request-id":"REDACTED","Strict-Transport-Security":"REDACTED","X-Content-Type-Options":"REDACTED","body":"{\"id\":\"/providers/Microsoft.ConfidentialLedger/locations/EASTUS/operationStatuses/8afef067-af99-420b-8149-bbdb0f01bea0*0A4299ECC6C7BD4E0BE582CF01FAD6D6EFA85278C6DBFEA74E4FFF8758D580B2\",\"name\":\"8afef067-af99-420b-8149-bbdb0f01bea0*0A4299ECC6C7BD4E0BE582CF01FAD6D6EFA85278C6DBFEA74E4FFF8758D580B2\",\"resourceId\":\"/subscriptions/ec0aa5f7-9e78-40c9-85cd-535c6305b380/resourceGroups/acl-sdk-test-rg1681438036/providers/Microsoft.ConfidentialLedger/ledgers/acl-java-sdk-create-test\",\"status\":\"Accepted\",\"startTime\":\"2023-04-14T02:07:29.2720163Z\"}"}
[parallel-5] INFO  - {"az.sdk.message":"HTTP request","method":"GET","url":"http://localhost:5000/providers/Microsoft.ConfidentialLedger/locations/EASTUS/operationStatuses/8afef067-af99-420b-8149-bbdb0f01bea0*0A4299ECC6C7BD4E0BE582CF01FAD6D6EFA85278C6DBFEA74E4FFF8758D580B2?api-version=2022-05-13","tryCount":"1","Date":"Fri, 14 Apr 2023 02:09:34 GMT","Authorization":"REDACTED","x-recording-mode":"REDACTED","x-recording-upstream-base-uri":"REDACTED","x-recording-id":"REDACTED","x-ms-client-request-id":"1bd2bfda-3650-47d6-b2fd-2daa78195797","Accept":"application/json","User-Agent":"azsdk-java-com.azure.resourcemanager.confidentialledger/1.0.0-beta.1 (17.0.4.1; Windows 11; 10.0; auto-generated)","contentLength":0}
[reactor-http-nio-3] INFO  - {"az.sdk.message":"HTTP response","contentLength":"539","statusCode":200,"url":"http://localhost:5000/providers/Microsoft.ConfidentialLedger/locations/EASTUS/operationStatuses/8afef067-af99-420b-8149-bbdb0f01bea0*0A4299ECC6C7BD4E0BE582CF01FAD6D6EFA85278C6DBFEA74E4FFF8758D580B2?api-version=2022-05-13","durationMs":307,"Content-Length":"539","Content-Type":"application/json; charset=utf-8","Date":"Fri, 14 Apr 2023 02:09:34 GMT","Server":"Kestrel","Cache-Control":"no-cache","ETag":"\"00009c59-0000-0100-0000-6438b5610000\"","Expires":"-1","Pragma":"no-cache","x-ms-ratelimit-remaining-tenant-reads":"REDACTED","x-ms-request-id":"14ca02da-d767-4825-94d1-3d67766bbb32","x-ms-correlation-request-id":"REDACTED","x-ms-routing-request-id":"REDACTED","Strict-Transport-Security":"REDACTED","X-Content-Type-Options":"REDACTED","body":"{\"id\":\"/providers/Microsoft.ConfidentialLedger/locations/EASTUS/operationStatuses/8afef067-af99-420b-8149-bbdb0f01bea0*0A4299ECC6C7BD4E0BE582CF01FAD6D6EFA85278C6DBFEA74E4FFF8758D580B2\",\"name\":\"8afef067-af99-420b-8149-bbdb0f01bea0*0A4299ECC6C7BD4E0BE582CF01FAD6D6EFA85278C6DBFEA74E4FFF8758D580B2\",\"resourceId\":\"/subscriptions/ec0aa5f7-9e78-40c9-85cd-535c6305b380/resourceGroups/acl-sdk-test-rg1681438036/providers/Microsoft.ConfidentialLedger/ledgers/acl-java-sdk-create-test\",\"status\":\"Accepted\",\"startTime\":\"2023-04-14T02:07:29.2720163Z\"}"}
[parallel-6] INFO  - {"az.sdk.message":"HTTP request","method":"GET","url":"http://localhost:5000/providers/Microsoft.ConfidentialLedger/locations/EASTUS/operationStatuses/8afef067-af99-420b-8149-bbdb0f01bea0*0A4299ECC6C7BD4E0BE582CF01FAD6D6EFA85278C6DBFEA74E4FFF8758D580B2?api-version=2022-05-13","tryCount":"1","Date":"Fri, 14 Apr 2023 02:10:04 GMT","Authorization":"REDACTED","x-recording-mode":"REDACTED","x-recording-upstream-base-uri":"REDACTED","x-recording-id":"REDACTED","x-ms-client-request-id":"76a1eef4-e1ea-4af3-9d04-dd2aae61c52c","Accept":"application/json","User-Agent":"azsdk-java-com.azure.resourcemanager.confidentialledger/1.0.0-beta.1 (17.0.4.1; Windows 11; 10.0; auto-generated)","contentLength":0}
[reactor-http-nio-3] INFO  - {"az.sdk.message":"HTTP response","contentLength":"539","statusCode":200,"url":"http://localhost:5000/providers/Microsoft.ConfidentialLedger/locations/EASTUS/operationStatuses/8afef067-af99-420b-8149-bbdb0f01bea0*0A4299ECC6C7BD4E0BE582CF01FAD6D6EFA85278C6DBFEA74E4FFF8758D580B2?api-version=2022-05-13","durationMs":307,"Content-Length":"539","Content-Type":"application/json; charset=utf-8","Date":"Fri, 14 Apr 2023 02:10:04 GMT","Server":"Kestrel","Cache-Control":"no-cache","ETag":"\"00009c59-0000-0100-0000-6438b5610000\"","Expires":"-1","Pragma":"no-cache","x-ms-ratelimit-remaining-tenant-reads":"REDACTED","x-ms-request-id":"9251bdec-a045-49cb-8a13-741bb7e57dd9","x-ms-correlation-request-id":"REDACTED","x-ms-routing-request-id":"REDACTED","Strict-Transport-Security":"REDACTED","X-Content-Type-Options":"REDACTED","body":"{\"id\":\"/providers/Microsoft.ConfidentialLedger/locations/EASTUS/operationStatuses/8afef067-af99-420b-8149-bbdb0f01bea0*0A4299ECC6C7BD4E0BE582CF01FAD6D6EFA85278C6DBFEA74E4FFF8758D580B2\",\"name\":\"8afef067-af99-420b-8149-bbdb0f01bea0*0A4299ECC6C7BD4E0BE582CF01FAD6D6EFA85278C6DBFEA74E4FFF8758D580B2\",\"resourceId\":\"/subscriptions/ec0aa5f7-9e78-40c9-85cd-535c6305b380/resourceGroups/acl-sdk-test-rg1681438036/providers/Microsoft.ConfidentialLedger/ledgers/acl-java-sdk-create-test\",\"status\":\"Accepted\",\"startTime\":\"2023-04-14T02:07:29.2720163Z\"}"}
[parallel-7] INFO  - {"az.sdk.message":"HTTP request","method":"GET","url":"http://localhost:5000/providers/Microsoft.ConfidentialLedger/locations/EASTUS/operationStatuses/8afef067-af99-420b-8149-bbdb0f01bea0*0A4299ECC6C7BD4E0BE582CF01FAD6D6EFA85278C6DBFEA74E4FFF8758D580B2?api-version=2022-05-13","tryCount":"1","Date":"Fri, 14 Apr 2023 02:10:35 GMT","Authorization":"REDACTED","x-recording-mode":"REDACTED","x-recording-upstream-base-uri":"REDACTED","x-recording-id":"REDACTED","x-ms-client-request-id":"a7d1b2df-7eb0-4bd2-bf5e-9bb4e7035bd5","Accept":"application/json","User-Agent":"azsdk-java-com.azure.resourcemanager.confidentialledger/1.0.0-beta.1 (17.0.4.1; Windows 11; 10.0; auto-generated)","contentLength":0}
[reactor-http-nio-3] INFO  - {"az.sdk.message":"HTTP response","contentLength":"2011","statusCode":200,"url":"http://localhost:5000/providers/Microsoft.ConfidentialLedger/locations/EASTUS/operationStatuses/8afef067-af99-420b-8149-bbdb0f01bea0*0A4299ECC6C7BD4E0BE582CF01FAD6D6EFA85278C6DBFEA74E4FFF8758D580B2?api-version=2022-05-13","durationMs":308,"Content-Length":"2011","Content-Type":"application/json; charset=utf-8","Date":"Fri, 14 Apr 2023 02:10:35 GMT","Server":"Kestrel","Cache-Control":"no-cache","ETag":"\"0000cd59-0000-0100-0000-6438b5ff0000\"","Expires":"-1","Pragma":"no-cache","x-ms-ratelimit-remaining-tenant-reads":"REDACTED","x-ms-request-id":"33464634-563b-49b1-b7d7-ae78ca90f3b3","x-ms-correlation-request-id":"REDACTED","x-ms-routing-request-id":"REDACTED","Strict-Transport-Security":"REDACTED","X-Content-Type-Options":"REDACTED","body":"{\"id\":\"/providers/Microsoft.ConfidentialLedger/locations/EASTUS/operationStatuses/8afef067-af99-420b-8149-bbdb0f01bea0*0A4299ECC6C7BD4E0BE582CF01FAD6D6EFA85278C6DBFEA74E4FFF8758D580B2\",\"name\":\"8afef067-af99-420b-8149-bbdb0f01bea0*0A4299ECC6C7BD4E0BE582CF01FAD6D6EFA85278C6DBFEA74E4FFF8758D580B2\",\"resourceId\":\"/subscriptions/ec0aa5f7-9e78-40c9-85cd-535c6305b380/resourceGroups/acl-sdk-test-rg1681438036/providers/Microsoft.ConfidentialLedger/ledgers/acl-java-sdk-create-test\",\"status\":\"Succeeded\",\"startTime\":\"2023-04-14T02:07:29.2720163Z\",\"endTime\":\"2023-04-14T02:10:07.0266845Z\",\"properties\":{\"LedgerName\":\"acl-java-sdk-create-test\",\"LedgerUri\":\"https://acl-java-sdk-create-test.confidential-ledger.azure.com\",\"IdentityServiceUri\":\"https://identity.confidential-ledger.core.azure.com/ledgerIdentity/acl-java-sdk-create-test\",\"LedgerStorageAccount\":null,\"LedgerType\":\"Public\",\"AadBasedSecurityPrincipals\":[{\"principalId\":\"074307f6-5baa-46bd-afd0-304b1f46345f\",\"tenantId\":\"72f988bf-86f1-41af-91ab-2d7cd011db47\",\"ledgerRoleName\":\"Administrator\"},{\"principalId\":\"174bb102-95f3-4d79-8cce-f3a839e08a37\",\"tenantId\":\"72f988bf-86f1-41af-91ab-2d7cd011db47\",\"ledgerRoleName\":\"Administrator\"}],\"CertBasedSecurityPrincipals\":[{\"Cert\":\"-----BEGIN CERTIFICATE-----MIIBxTCCAUygAwIBAgIUFXobF1KhnQzlaPcPRe2tI8fdjjwwCgYIKoZIzj0EAwMwGjEYMBYGA1UEAwwPQUNMIENsaWVudCBDZXJ0MB4XDTIyMDgxNjE2Mjk1NFoXDTIzMDgxNjE2Mjk1NFowGjEYMBYGA1UEAwwPQUNMIENsaWVudCBDZXJ0MHYwEAYHKoZIzj0CAQYFK4EEACIDYgAE1GafPSAqwzZyTJDnzD5DSyue0hANYCwr1XIMjbRDJHOPEPsPK/fMThMHPXjV4LXOVVL0bwj+V5LD3U07ZaMJztvZOrRf+c6bP59U0GZlZM/DvPYfml9es/O2e62m1il9o1MwUTAdBgNVHQ4EFgQUg9kRNgnyP1nILNXBKfGvFjgaYP0wHwYDVR0jBBgwFoAUg9kRNgnyP1nILNXBKfGvFjgaYP0wDwYDVR0TAQH/BAUwAwEB/zAKBggqhkjOPQQDAwNnADBkAjAK/K4xWMTVq9uZwiOlo80MaYjA5V8xbWQBCsyrQzfyaxr1ol61lGlGyUqM1rGVUm4CMA9D8Z2Vblz3SaJwKBTe5PlBebZfS5a6gRs/fmL1RdmIQVjSFsx8OB1/nyIdARwhaQ==-----END CERTIFICATE-----\",\"LedgerRoleName\":\"Contributor\"}],\"LedgerInternalNamespace\":\"8b3ca12b-9aee-4e68-b20e-7fdbf1f117a0\",\"LedgerSku\":\"Unknown\"}}"}
[parallel-10] ERROR com.azure.core.http.policy.RetryPolicy - {"az.sdk.message":"Retry attempts have been exhausted.","exception":"token credentials require a URL using the HTTPS protocol scheme","tryCount":3}

java.lang.RuntimeException: token credentials require a URL using the HTTPS protocol scheme

	at com.azure.core@1.37.0/com.azure.core.http.policy.BearerTokenAuthenticationPolicy.process(BearerTokenAuthenticationPolicy.java:96)
	at com.azure.core@1.37.0/com.azure.core.http.HttpPipelineNextPolicy.process(HttpPipelineNextPolicy.java:67)
	at com.azure.core@1.37.0/com.azure.core.http.policy.HttpPipelineSyncPolicy.lambda$process$1(HttpPipelineSyncPolicy.java:32)
	at reactor.core@3.4.27/reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:152)
	at reactor.core@3.4.27/reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53)
	at reactor.core@3.4.27/reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
	at reactor.core@3.4.27/reactor.core.publisher.MonoDelaySubscription.accept(MonoDelaySubscription.java:53)
	at reactor.core@3.4.27/reactor.core.publisher.MonoDelaySubscription.accept(MonoDelaySubscription.java:34)
	at reactor.core@3.4.27/reactor.core.publisher.FluxDelaySubscription$DelaySubscriptionOtherSubscriber.onNext(FluxDelaySubscription.java:131)
	at reactor.core@3.4.27/reactor.core.publisher.MonoDelay$MonoDelayRunnable.propagateDelay(MonoDelay.java:271)
	at reactor.core@3.4.27/reactor.core.publisher.MonoDelay$MonoDelayRunnable.run(MonoDelay.java:286)
	at reactor.core@3.4.27/reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core@3.4.27/reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
```

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**
running [`ConfidentialLedgerManagementTest`](https://github.com/haolingdong-msft/azure-sdk-for-java/blob/migrate-test-recording/sdk/confidentialledger/azure-resourcemanager-confidentialledger/src/test/java/com/azure/resourcemanager/confidentialledger/ConfidentialLedgerManagementTest.java) in RECORD mode using test proxy
***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - IDE: [e.g. IntelliJ]
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)]
 - Java version: [e.g. 8] 
 - App Server/Environment: [e.g. Tomcat, WildFly, Azure Function, Apache Spark, Databricks, IDE plugin or anything special]
 - Frameworks: [e.g. Spring Boot, Micronaut, Quarkus, etc] 

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by haolingdong-msft** [comment]
It is resolved by upgrade azure-test version to 1.16.0
