### ISSUE TITLE
Azure Identity => ERROR in getToken() 

### ISSUE THREAD

**Issue by akreienbring** [Azure/azure-sdk-for-java#34639]
I also posted this in:
https://github.com/AzureAD/microsoft-authentication-library-for-java/issues/638

I see this error:
`Azure Identity => ERROR in getToken() call for scopes [https://graph.microsoft.com/.default]: Could not initialize class com.microsoft.aad.msal4j.HttpHeaders`

Cause:
`java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: Could not initialize class com.microsoft.aad.msal4j.HttpHeaders`

The flow of code is:
```
		final ClientSecretCredential clientSecretCredential = new ClientSecretCredentialBuilder()
				.clientId(m365_clientId)
				.clientSecret(m365_clientSecret)
				.tenantId(m365_tenantId).build();

		final List<String> scopes = new ArrayList<String>();
		scopes.add("https://graph.microsoft.com/.default");

		final TokenCredentialAuthProvider tokenCredentialAuthProvider = new TokenCredentialAuthProvider(scopes,
				clientSecretCredential);

		graphClient = GraphServiceClient.builder()
				.authenticationProvider(tokenCredentialAuthProvider)
				.buildClient();
		
		List<Option> requestOptions = new LinkedList<Option>();
        requestOptions.add(new QueryOption("search", m365_sharepoint_sitename));
        **SiteCollectionPage sites = graphClient.sites().buildRequest(requestOptions).get();**
```
And the last line produces the error.

The funny thing is: Exactly the same code work in a Spring Boot application.
While the error occurs in a more complex Tomcat Webapplication (with Maven and Spring beans).
I even use the exact same version of the artifacts...

```
		<dependency>
		  <groupId>com.microsoft.graph</groupId>
		  <artifactId>microsoft-graph</artifactId>
		  <version>5.52.0</version>
		</dependency>
		<dependency>
		  <!-- This dependency is only needed if you are using the TokenCrendentialAuthProvider -->
		  <groupId>com.azure</groupId>
		  <artifactId>azure-identity</artifactId>
		  <version>	1.8.2</version>
		</dependency>

```

### Actual behavior
Somehow the HttpHeaders class can not be initialized. Can someone point me in the right direction why this is only happening in the Tomcat Framework?

Tomcat: 9.0.62
JAVA:  java-17-openjdk-17.0.4.1.1-2.el8_6.x86_64
Azur Identity: 1.8.2
Microsoft-graph SDK:  5.52.0

Stacktrace:
```
docker-alfresco-secure-pdf-acs-1       |  2023-04-25 07:54:20,907  ERROR [azure.identity.ClientSecretCredential] [ForkJoinPool.commonPool-worker-1] Azure Identity => ERROR in getToken() call for scopes [https://graph.microsoft.com/.default]: Could not initialize class com.microsoft.aad.msal4j.HttpHeaders
docker-alfresco-secure-pdf-acs-1       |  2023-04-25 07:54:20,910  ERROR [extensions.webscripts.AbstractRuntime] [http-nio-8080-exec-5] Exception from executeScript: 03250007 Wrapped Exception (with status template): Error executing the request
docker-alfresco-secure-pdf-acs-1       |  org.springframework.extensions.webscripts.WebScriptException: 03250007 Wrapped Exception (with status template): Error executing the request
docker-alfresco-secure-pdf-acs-1       |        at org.springframework.extensions.webscripts.AbstractWebScript.createStatusException(AbstractWebScript.java:1139)
docker-alfresco-secure-pdf-acs-1       |        at org.springframework.extensions.webscripts.DeclarativeWebScript.execute(DeclarativeWebScript.java:171)
docker-alfresco-secure-pdf-acs-1       |        at org.alfresco.repo.web.scripts.RepositoryContainer.lambda$transactionedExecute$2(RepositoryContainer.java:561)
docker-alfresco-secure-pdf-acs-1       |        at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:452)
docker-alfresco-secure-pdf-acs-1       |        at org.alfresco.repo.web.scripts.RepositoryContainer.transactionedExecute(RepositoryContainer.java:544)
docker-alfresco-secure-pdf-acs-1       |        at org.alfresco.repo.web.scripts.RepositoryContainer.transactionedExecuteAs(RepositoryContainer.java:685)
docker-alfresco-secure-pdf-acs-1       |        at org.alfresco.repo.web.scripts.RepositoryContainer.transactionedExecuteAs(RepositoryContainer.java:721)
docker-alfresco-secure-pdf-acs-1       |        at org.alfresco.repo.web.scripts.RepositoryContainer.executeScriptInternal(RepositoryContainer.java:413)
docker-alfresco-secure-pdf-acs-1       |        at org.alfresco.repo.web.scripts.RepositoryContainer.executeScript(RepositoryContainer.java:309)
docker-alfresco-secure-pdf-acs-1       |        at org.springframework.extensions.webscripts.AbstractRuntime.executeScript(AbstractRuntime.java:423)
docker-alfresco-secure-pdf-acs-1       |        at org.springframework.extensions.webscripts.AbstractRuntime.executeScript(AbstractRuntime.java:210)
docker-alfresco-secure-pdf-acs-1       |        at org.springframework.extensions.webscripts.servlet.WebScriptServlet.service(WebScriptServlet.java:131)
docker-alfresco-secure-pdf-acs-1       |        at org.alfresco.repo.web.scripts.AlfrescoWebScriptServlet.service(AlfrescoWebScriptServlet.java:43)
docker-alfresco-secure-pdf-acs-1       |        at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
docker-alfresco-secure-pdf-acs-1       |        at jdk.internal.reflect.GeneratedMethodAccessor499.invoke(Unknown Source)
docker-alfresco-secure-pdf-acs-1       |        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
docker-alfresco-secure-pdf-acs-1       |        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
docker-alfresco-secure-pdf-acs-1       |        at org.apache.catalina.security.SecurityUtil.lambda$execute$0(SecurityUtil.java:280)
docker-alfresco-secure-pdf-acs-1       |        at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
docker-alfresco-secure-pdf-acs-1       |        at java.base/javax.security.auth.Subject.doAsPrivileged(Subject.java:584)
docker-alfresco-secure-pdf-acs-1       |        at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:311)
docker-alfresco-secure-pdf-acs-1       |        at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:170)
docker-alfresco-secure-pdf-acs-1       |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:221)
docker-alfresco-secure-pdf-acs-1       |        at org.apache.catalina.core.ApplicationFilterChain.lambda$doFilter$0(ApplicationFilterChain.java:145)
docker-alfresco-secure-pdf-acs-1       |        at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
docker-alfresco-secure-pdf-acs-1       |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:143)
docker-alfresco-secure-pdf-acs-1       |        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
docker-alfresco-secure-pdf-acs-1       |        at jdk.internal.reflect.GeneratedMethodAccessor481.invoke(Unknown Source)
docker-alfresco-secure-pdf-acs-1       |        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
docker-alfresco-secure-pdf-acs-1       |        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
docker-alfresco-secure-pdf-acs-1       |        at org.apache.catalina.security.SecurityUtil.lambda$execute$0(SecurityUtil.java:280)
docker-alfresco-secure-pdf-acs-1       |        at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
docker-alfresco-secure-pdf-acs-1       |        at java.base/javax.security.auth.Subject.doAsPrivileged(Subject.java:584)
docker-alfresco-secure-pdf-acs-1       |        at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:311)
docker-alfresco-secure-pdf-acs-1       |        at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:253)
docker-alfresco-secure-pdf-acs-1       |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:187)
docker-alfresco-secure-pdf-acs-1       |        at org.apache.catalina.core.ApplicationFilterChain.lambda$doFilter$0(ApplicationFilterChain.java:145)
docker-alfresco-secure-pdf-acs-1       |        at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
docker-alfresco-secure-pdf-acs-1       |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:143)
docker-alfresco-secure-pdf-acs-1       |        at org.alfresco.module.aosmodule.service.ContextRootFilter.doFilter(ContextRootFilter.java:93)
docker-alfresco-secure-pdf-acs-1       |        at jdk.internal.reflect.GeneratedMethodAccessor481.invoke(Unknown Source)
docker-alfresco-secure-pdf-acs-1       |        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
docker-alfresco-secure-pdf-acs-1       |        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
docker-alfresco-secure-pdf-acs-1       |        at org.apache.catalina.security.SecurityUtil.lambda$execute$0(SecurityUtil.java:280)
docker-alfresco-secure-pdf-acs-1       |        at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
docker-alfresco-secure-pdf-acs-1       |        at java.base/javax.security.auth.Subject.doAsPrivileged(Subject.java:584)
docker-alfresco-secure-pdf-acs-1       |        at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:311)
docker-alfresco-secure-pdf-acs-1       |        at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:253)
docker-alfresco-secure-pdf-acs-1       |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:187)
docker-alfresco-secure-pdf-acs-1       |        at org.apache.catalina.core.ApplicationFilterChain.lambda$doFilter$0(ApplicationFilterChain.java:145)
docker-alfresco-secure-pdf-acs-1       |        at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
docker-alfresco-secure-pdf-acs-1       |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:143)
docker-alfresco-secure-pdf-acs-1       |        at org.springframework.extensions.webscripts.servlet.SecurityHeadersFilter.doFilter(SecurityHeadersFilter.java:177)
docker-alfresco-secure-pdf-acs-1       |        at jdk.internal.reflect.GeneratedMethodAccessor481.invoke(Unknown Source)
docker-alfresco-secure-pdf-acs-1       |        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
docker-alfresco-secure-pdf-acs-1       |        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
docker-alfresco-secure-pdf-acs-1       |        at org.apache.catalina.security.SecurityUtil.lambda$execute$0(SecurityUtil.java:280)
docker-alfresco-secure-pdf-acs-1       |        at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
docker-alfresco-secure-pdf-acs-1       |        at java.base/javax.security.auth.Subject.doAsPrivileged(Subject.java:584)
docker-alfresco-secure-pdf-acs-1       |        at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:311)
docker-alfresco-secure-pdf-acs-1       |        at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:253)
docker-alfresco-secure-pdf-acs-1       |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:187)
docker-alfresco-secure-pdf-acs-1       |        at org.apache.catalina.core.ApplicationFilterChain.lambda$doFilter$0(ApplicationFilterChain.java:145)
docker-alfresco-secure-pdf-acs-1       |        at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
docker-alfresco-secure-pdf-acs-1       |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:143)
docker-alfresco-secure-pdf-acs-1       |        at org.alfresco.web.app.servlet.ServletMetricsFilter.doFilter(ServletMetricsFilter.java:161)
docker-alfresco-secure-pdf-acs-1       |        at org.alfresco.repo.web.filter.beans.BeanProxyFilter.doFilter(BeanProxyFilter.java:89)
docker-alfresco-secure-pdf-acs-1       |        at jdk.internal.reflect.GeneratedMethodAccessor481.invoke(Unknown Source)
docker-alfresco-secure-pdf-acs-1       |        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
docker-alfresco-secure-pdf-acs-1       |        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
docker-alfresco-secure-pdf-acs-1       |        at org.apache.catalina.security.SecurityUtil.lambda$execute$0(SecurityUtil.java:280)
docker-alfresco-secure-pdf-acs-1       |        at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
docker-alfresco-secure-pdf-acs-1       |        at java.base/javax.security.auth.Subject.doAsPrivileged(Subject.java:584)
docker-alfresco-secure-pdf-acs-1       |        at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:311)
docker-alfresco-secure-pdf-acs-1       |        at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:253)
docker-alfresco-secure-pdf-acs-1       |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:187)
docker-alfresco-secure-pdf-acs-1       |        at org.apache.catalina.core.ApplicationFilterChain.lambda$doFilter$0(ApplicationFilterChain.java:145)
docker-alfresco-secure-pdf-acs-1       |        at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
docker-alfresco-secure-pdf-acs-1       |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:143)
docker-alfresco-secure-pdf-acs-1       |        at org.alfresco.web.app.servlet.GlobalLocalizationFilter.doFilter(GlobalLocalizationFilter.java:68)
docker-alfresco-secure-pdf-acs-1       |        at jdk.internal.reflect.GeneratedMethodAccessor481.invoke(Unknown Source)
docker-alfresco-secure-pdf-acs-1       |        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
docker-alfresco-secure-pdf-acs-1       |        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
docker-alfresco-secure-pdf-acs-1       |        at org.apache.catalina.security.SecurityUtil.lambda$execute$0(SecurityUtil.java:280)
docker-alfresco-secure-pdf-acs-1       |        at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
docker-alfresco-secure-pdf-acs-1       |        at java.base/javax.security.auth.Subject.doAsPrivileged(Subject.java:584)
docker-alfresco-secure-pdf-acs-1       |        at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:311)
docker-alfresco-secure-pdf-acs-1       |        at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:253)
docker-alfresco-secure-pdf-acs-1       |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:187)
docker-alfresco-secure-pdf-acs-1       |        at org.apache.catalina.core.ApplicationFilterChain.lambda$doFilter$0(ApplicationFilterChain.java:145)
docker-alfresco-secure-pdf-acs-1       |        at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
docker-alfresco-secure-pdf-acs-1       |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:143)
docker-alfresco-secure-pdf-acs-1       |        at org.alfresco.web.app.servlet.ClearSecurityContextFilter.doFilter(ClearSecurityContextFilter.java:53)
docker-alfresco-secure-pdf-acs-1       |        at jdk.internal.reflect.GeneratedMethodAccessor481.invoke(Unknown Source)
docker-alfresco-secure-pdf-acs-1       |        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
docker-alfresco-secure-pdf-acs-1       |        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
docker-alfresco-secure-pdf-acs-1       |        at org.apache.catalina.security.SecurityUtil.lambda$execute$0(SecurityUtil.java:280)
docker-alfresco-secure-pdf-acs-1       |        at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
docker-alfresco-secure-pdf-acs-1       |        at java.base/javax.security.auth.Subject.doAsPrivileged(Subject.java:584)
docker-alfresco-secure-pdf-acs-1       |        at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:311)
docker-alfresco-secure-pdf-acs-1       |        at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:253)
docker-alfresco-secure-pdf-acs-1       |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:187)
docker-alfresco-secure-pdf-acs-1       |        at org.apache.catalina.core.ApplicationFilterChain.lambda$doFilter$0(ApplicationFilterChain.java:145)
docker-alfresco-secure-pdf-acs-1       |        at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
docker-alfresco-secure-pdf-acs-1       |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:143)
docker-alfresco-secure-pdf-acs-1       |        at org.apache.catalina.filters.CorsFilter.handleSimpleCORS(CorsFilter.java:264)
docker-alfresco-secure-pdf-acs-1       |        at org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:168)
docker-alfresco-secure-pdf-acs-1       |        at jdk.internal.reflect.GeneratedMethodAccessor481.invoke(Unknown Source)
docker-alfresco-secure-pdf-acs-1       |        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
docker-alfresco-secure-pdf-acs-1       |        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
docker-alfresco-secure-pdf-acs-1       |        at org.apache.catalina.security.SecurityUtil.lambda$execute$0(SecurityUtil.java:280)
docker-alfresco-secure-pdf-acs-1       |        at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
docker-alfresco-secure-pdf-acs-1       |        at java.base/javax.security.auth.Subject.doAsPrivileged(Subject.java:584)
docker-alfresco-secure-pdf-acs-1       |        at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:311)
docker-alfresco-secure-pdf-acs-1       |        at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:253)
docker-alfresco-secure-pdf-acs-1       |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:187)
docker-alfresco-secure-pdf-acs-1       |        at org.apache.catalina.core.ApplicationFilterChain.lambda$doFilter$0(ApplicationFilterChain.java:145)
docker-alfresco-secure-pdf-acs-1       |        at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
docker-alfresco-secure-pdf-acs-1       |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:143)
docker-alfresco-secure-pdf-acs-1       |        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
docker-alfresco-secure-pdf-acs-1       |        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
docker-alfresco-secure-pdf-acs-1       |        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
docker-alfresco-secure-pdf-acs-1       |        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
docker-alfresco-secure-pdf-acs-1       |        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
docker-alfresco-secure-pdf-acs-1       |        at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:769)
docker-alfresco-secure-pdf-acs-1       |        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
docker-alfresco-secure-pdf-acs-1       |        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
docker-alfresco-secure-pdf-acs-1       |        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
docker-alfresco-secure-pdf-acs-1       |        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
docker-alfresco-secure-pdf-acs-1       |        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
docker-alfresco-secure-pdf-acs-1       |        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890)
docker-alfresco-secure-pdf-acs-1       |        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1743)
docker-alfresco-secure-pdf-acs-1       |        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
docker-alfresco-secure-pdf-acs-1       |        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
docker-alfresco-secure-pdf-acs-1       |        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
docker-alfresco-secure-pdf-acs-1       |        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
docker-alfresco-secure-pdf-acs-1       |        at java.base/java.lang.Thread.run(Thread.java:833)
docker-alfresco-secure-pdf-acs-1       | Caused by: com.microsoft.graph.core.ClientException: Error executing the request
docker-alfresco-secure-pdf-acs-1       |        at com.microsoft.graph.http.CoreHttpProvider.sendRequestInternal(CoreHttpProvider.java:410)
docker-alfresco-secure-pdf-acs-1       |        at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:225)
docker-alfresco-secure-pdf-acs-1       |        at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:202)
docker-alfresco-secure-pdf-acs-1       |        at com.microsoft.graph.http.BaseCollectionRequest.send(BaseCollectionRequest.java:103)
docker-alfresco-secure-pdf-acs-1       |        at com.microsoft.graph.http.BaseEntityCollectionRequest.get(BaseEntityCollectionRequest.java:78)
docker-alfresco-secure-pdf-acs-1       |        at de.fme.securepdf.converter.MSGraphClient.init(MSGraphClient.java:72)
docker-alfresco-secure-pdf-acs-1       |        at de.fme.securepdf.action.executer.ConvertToPDFActionExecuter.executeImpl(ConvertToPDFActionExecuter.java:39)
docker-alfresco-secure-pdf-acs-1       |        at org.alfresco.repo.action.executer.ActionExecuterAbstractBase.execute(ActionExecuterAbstractBase.java:293)
docker-alfresco-secure-pdf-acs-1       |        at org.alfresco.repo.action.ActionServiceImpl.directActionExecution(ActionServiceImpl.java:910)
docker-alfresco-secure-pdf-acs-1       |        at org.alfresco.repo.action.ActionServiceImpl.executeActionImpl(ActionServiceImpl.java:811)
docker-alfresco-secure-pdf-acs-1       |        at org.alfresco.repo.action.ActionServiceImpl.executeAction(ActionServiceImpl.java:593)
docker-alfresco-secure-pdf-acs-1       |        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
docker-alfresco-secure-pdf-acs-1       |        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
docker-alfresco-secure-pdf-acs-1       |        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
docker-alfresco-secure-pdf-acs-1       |        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
docker-alfresco-secure-pdf-acs-1       |        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
docker-alfresco-secure-pdf-acs-1       |        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
docker-alfresco-secure-pdf-acs-1       |        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
docker-alfresco-secure-pdf-acs-1       |        at org.alfresco.repo.security.permissions.impl.AlwaysProceedMethodInterceptor.invoke(AlwaysProceedMethodInterceptor.java:41)
docker-alfresco-secure-pdf-acs-1       |        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
docker-alfresco-secure-pdf-acs-1       |        at org.alfresco.repo.security.permissions.impl.ExceptionTranslatorMethodInterceptor.invoke(ExceptionTranslatorMethodInterceptor.java:53)
docker-alfresco-secure-pdf-acs-1       |        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
docker-alfresco-secure-pdf-acs-1       |        at org.alfresco.repo.audit.AuditMethodInterceptor.invoke(AuditMethodInterceptor.java:166)
docker-alfresco-secure-pdf-acs-1       |        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
docker-alfresco-secure-pdf-acs-1       |        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
docker-alfresco-secure-pdf-acs-1       |        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
docker-alfresco-secure-pdf-acs-1       |        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
docker-alfresco-secure-pdf-acs-1       |        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
docker-alfresco-secure-pdf-acs-1       |        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
docker-alfresco-secure-pdf-acs-1       |        at jdk.proxy3/jdk.proxy3.$Proxy54.executeAction(Unknown Source)
docker-alfresco-secure-pdf-acs-1       |        at org.alfresco.repo.web.scripts.rule.ActionQueuePost.executeImpl(ActionQueuePost.java:94)
docker-alfresco-secure-pdf-acs-1       |        at org.springframework.extensions.webscripts.DeclarativeWebScript.execute(DeclarativeWebScript.java:64)
docker-alfresco-secure-pdf-acs-1       |        ... 135 more
docker-alfresco-secure-pdf-acs-1       | Caused by: java.io.IOException: java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: Could not initialize class com.microsoft.aad.msal4j.HttpHeaders
docker-alfresco-secure-pdf-acs-1       |        at com.microsoft.graph.httpcore.AuthenticationHandler.intercept(AuthenticationHandler.java:67)
docker-alfresco-secure-pdf-acs-1       |        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
docker-alfresco-secure-pdf-acs-1       |        at com.microsoft.graph.httpcore.TelemetryHandler.intercept(TelemetryHandler.java:68)
docker-alfresco-secure-pdf-acs-1       |        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
docker-alfresco-secure-pdf-acs-1       |        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
docker-alfresco-secure-pdf-acs-1       |        at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
docker-alfresco-secure-pdf-acs-1       |        at com.microsoft.graph.http.CoreHttpProvider.sendRequestInternal(CoreHttpProvider.java:407)
docker-alfresco-secure-pdf-acs-1       |        ... 166 more
docker-alfresco-secure-pdf-acs-1       | Caused by: java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: Could not initialize class com.microsoft.aad.msal4j.HttpHeaders
docker-alfresco-secure-pdf-acs-1       |        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
docker-alfresco-secure-pdf-acs-1       |        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
docker-alfresco-secure-pdf-acs-1       |        at com.microsoft.graph.httpcore.AuthenticationHandler.intercept(AuthenticationHandler.java:55)
docker-alfresco-secure-pdf-acs-1       |        ... 172 more
docker-alfresco-secure-pdf-acs-1       | Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.microsoft.aad.msal4j.HttpHeaders
docker-alfresco-secure-pdf-acs-1       |        at com.microsoft.aad.msal4j.MsalRequest.headers(MsalRequest.java:49)
docker-alfresco-secure-pdf-acs-1       |        at com.microsoft.aad.msal4j.AadInstanceDiscoveryProvider.sendInstanceDiscoveryRequest(AadInstanceDiscoveryProvider.java:237)
docker-alfresco-secure-pdf-acs-1       |        at com.microsoft.aad.msal4j.AadInstanceDiscoveryProvider.doInstanceDiscoveryAndCache(AadInstanceDiscoveryProvider.java:347)
docker-alfresco-secure-pdf-acs-1       |        at com.microsoft.aad.msal4j.AadInstanceDiscoveryProvider.getMetadataEntry(AadInstanceDiscoveryProvider.java:90)
docker-alfresco-secure-pdf-acs-1       |        at com.microsoft.aad.msal4j.AuthenticationResultSupplier.getAuthorityWithPrefNetworkHost(AuthenticationResultSupplier.java:39)
docker-alfresco-secure-pdf-acs-1       |        at com.microsoft.aad.msal4j.AcquireTokenSilentSupplier.execute(AcquireTokenSilentSupplier.java:23)
docker-alfresco-secure-pdf-acs-1       |        at com.microsoft.aad.msal4j.AcquireTokenByClientCredentialSupplier.execute(AcquireTokenByClientCredentialSupplier.java:46)
docker-alfresco-secure-pdf-acs-1       |        at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:69)
docker-alfresco-secure-pdf-acs-1       |        at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:18)
docker-alfresco-secure-pdf-acs-1       |        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
docker-alfresco-secure-pdf-acs-1       |        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
docker-alfresco-secure-pdf-acs-1       |        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
docker-alfresco-secure-pdf-acs-1       |        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
docker-alfresco-secure-pdf-acs-1       |        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
docker-alfresco-secure-pdf-acs-1       |        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
docker-alfresco-secure-pdf-acs-1       |        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by joshfree** [comment]
@g2vinay could you please take a look?

/cc @billwert

**Comment by g2vinay** [comment]
@akreienbring 

It appears to be a potential dependency conflict issue.

Can you try adding this dependency directly in your application pom file and run your app again in tomcat.

```
<dependency>
    <groupId>com.microsoft.azure</groupId>
    <artifactId>msal4j</artifactId>
    <version>1.13.8</version>
</dependency>
```

**Comment by akreienbring** [comment]
Thanks for your effort, but unfortunately I can't. Need to reinstall the whole thing first. Not so sure if I'm going to do that. But never say never...

**Comment by g2vinay** [comment]
Closing this issue as the solution is posted above.
