### ISSUE TITLE
[BUG]com.azure.core.amqp.exception.AmqpException: Connection reset, errorContext[NAMESPACE:<<SERVICE_BUS_NAME_HIDDEN>>. ERROR CONTEXT: N/A]

### ISSUE THREAD

**Issue by marcin-sikorski-circlek** [Azure/azure-sdk-for-java#34778]
**Describe the bug**
Our service stopped processing service bus queue messages, but remains alive and answers on rest controllers.
It did not try to restart connection to service bus. Restart of service restored functionality.

***Exception or Stack Trace***
Logger error stack trace:
`reactor.core.Exceptions$ErrorCallbackNotImplemented: com.azure.core.amqp.exception.AmqpException: Connection reset, errorContext[NAMESPACE: <<SERVICE_BUS_NAME_HIDDEN>>. ERROR CONTEXT: N/A]
Caused by: com.azure.core.amqp.exception.AmqpException: Connection reset, errorContext[NAMESPACE:<<SERVICE_BUS_NAME_HIDDEN>>. ERROR CONTEXT: N/A]
at com.azure.core.amqp.implementation.ExceptionUtil.toException(ExceptionUtil.java:85)
at com.azure.core.amqp.implementation.handler.ConnectionHandler.notifyErrorContext(ConnectionHandler.java:351)
at com.azure.core.amqp.implementation.handler.ConnectionHandler.onTransportError(ConnectionHandler.java:253)
at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:191)
at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291)
at com.azure.core.amqp.implementation.ReactorExecutor.run(ReactorExecutor.java:91)
at org.springframework.cloud.sleuth.instrument.reactor.ReactorSleuth.lambda$null$6(ReactorSleuth.java:324)
at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)`

**To Reproduce**
Cannot reproduce on demand, happened once after months of working correctly.

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**
Service bus connection should be restored after time.

**Setup (please complete the following information):**
 - OS: Docker eclipse-temurin:17.0.6_10-jdk
 - Library/Libraries: 'com.azure:azure-messaging-servicebus:7.12.1'
 
dependency management:
'com.microsoft.azure:azure-spring-boot-bom:2.3.5'
"org.springframework.cloud:spring-cloud-dependencies:2021.0.5"

 - Java version: [e.g. 8] 17
 - App Server/Environment: Docker
 - Frameworks: Spring Boot 2.7.10

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please

**Comment by anasabbal** [comment]
Can you please share with me config class 
beacause i have the same problem

**Comment by gbrehmer** [comment]
> i have the solution for this problem

Please share your solution

**Comment by marcin-sikorski-circlek** [comment]
@anasabbal Can you show me solution? I cannot share company's code.

**Comment by BDSebastian** [comment]
Same error

**Comment by eddieescoqc** [comment]
Did the solution get shared some where? We are running into the same issue

**Comment by brian-singer** [comment]
I also get the following every X hours. Sometimes 2-3 days.
Only in one environment of 4.
I am connected to 8+ queues.
Everything still works without restarting the service. Is this maybe networking problems? I am on AKS.

`reactor.core.Exceptions$ErrorCallbackNotImplemented: com.azure.core.amqp.exception.AmqpException: Connection reset, errorContext[NAMESPACE: januar.servicebus.windows.net. ERROR CONTEXT: N/A]
Caused by: com.azure.core.amqp.exception.AmqpException: Connection reset, errorContext[NAMESPACE: januar.servicebus.windows.net. ERROR CONTEXT: N/A]`

**Comment by anuchandy** [comment]
Hey @marcin-sikorski-circlek, Apologies for the delay. Are you using ServiceBusReceiverAsyncClient? This client (aka low level client) requires application to listen for the terminal error reported to the Subscriber.onError handler, and application needs to spin up a new ServiceBusReceiverAsyncClient to continue receiving. Does your application take this requirement into account?

If the application is using ServiceBusProcessorClient then it should be able to recover from such errors without any special handling from the application side. If you’re experiencing an issue with this Client, could you enable logging (preferably verbose) and share ? 

Also please update to the latest version of azure-messaging-servicebus to pick any reliability enhancements after 7.12.1
