### ISSUE TITLE
[BUG] Empty array causes NoSuchElementException in CosmosDB EncryptionProcessor

### ISSUE THREAD

**Issue by willivolt** [Azure/azure-sdk-for-java#34821]
**Describe the bug**
I have items similar to:
```
{
"id": "idValue",
"a": "aValue",
"b": {
	"c": [
		{
			"d": "dValue",
			"e": "eValue",
			"f": "fValue",
			"g": "gValue",
		}
	]
},
"h": "hValue"
}
```

Because elements a and d need to be encrypted, we have paths /a and /b setup to be encrypted in CosmosDB.  This work fine, as long as collection c is not empty.  However, when collection c is empty as follows:
```
{
"id": "idValue",
"a": "aValue",
"b": {
	"c": []
},
"h": "hValue"
}
```

EncryptionProcessor throws a java.util.NoSuchElementException when I upsert the item.

***Exception or Stack Trace***
```
java.util.NoSuchElementException
	at java.util.ArrayList$Itr.next(ArrayList.java:862)
	at com.azure.cosmos.encryption.implementation.EncryptionProcessor.encryptAndSerializeProperty(EncryptionProcessor.java:418)
	at com.azure.cosmos.encryption.implementation.EncryptionProcessor.encryptAndSerializeProperty(EncryptionProcessor.java:409)
	at com.azure.cosmos.encryption.implementation.EncryptionProcessor.lambda$encryptObjectNode$12(EncryptionProcessor.java:323)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:125)
```

**Expected behavior**
No exception. Item is upserted with /a encrypted and collection /b/c empty.

**Setup (please complete the following information):**
 - OS: Windows 10
 - IDE: IntelliJ
 - Library/Libraries: com.azure:azure-cosmos-encryption:2.0.0 (also happens in 1.12.0)
 - Java version: OpenJDK Runtime Environment Microsoft-7209853 (build 17.0.6+10-LTS)
 - App Server/Environment: Command Line app

**To Reproduce**

- Create container with the following client encryption policy:
```
{ "includedPaths": [ { "path": "/a", "clientEncryptionKeyId": "cmk", "encryptionAlgorithm": "AEAD_AES_256_CBC_HMAC_SHA256", "encryptionType": "Deterministic" }, { "path": "/b", "clientEncryptionKeyId": "cmk", "encryptionAlgorithm": "AEAD_AES_256_CBC_HMAC_SHA256", "encryptionType": "Deterministic" } ], "policyFormatVersion": 1 }
```
 
- Upset the record above.  ([Sample gist](https://gist.github.com/willivolt/8eab7e607bf5b10042dee324e0b1f770))

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by willivolt** [comment]
@mkrueger, @FabianMeiswinkel: Thank you for looking at this.  Any idea how long it typically takes a fix to make it into a release version?  This has turned out to be a real blocker item for us.
