### ISSUE TITLE
[BUG] ClassNotFoundException: io.opentelemetry.javaagent.instrumentation.opentelemetryapi.context.AgentContextStorage

### ISSUE THREAD

**Issue by bhupendergiri** [Azure/azure-sdk-for-java#34893]
**Describe the bug**
Similar to https://github.com/Azure/azure-sdk-for-java/issues/32980 I am facing this issue
java.lang.ClassNotFoundException: io.opentelemetry.javaagent.instrumentation.opentelemetryapi.context.AgentContextStorage
Infra details
Spring boot 2.7.7, Java 11
Azure core 1.38.0
azure-messaging-eventhubs-checkpointstore-blob 1.16.4, azure-messaging-eventhubs  5.15.3
***Exception or Stack Trace***
23:42:13.934 [pool-12-thread-1] DEBUG i.o.j.i.a.v.s.c.a.c.t.o.i.OpenTelemetrySpanSuppressionHelper - Failed to discover OpenTelemetry agent classes, HTTP spans may be duplicated 
java.lang.ClassNotFoundException: io.opentelemetry.javaagent.instrumentation.opentelemetryapi.context.AgentContextStorage
 at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
 at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
 at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151)
 at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
 at java.base/java.lang.Class.forName0(Native Method)
 at java.base/java.lang.Class.forName(Class.java:315)
 at io.opentelemetry.javaagent.instrumentation.azurecore.v1_19.shaded.com.azure.core.tracing.opentelemetry.implementation.OpenTelemetrySpanSuppressionHelper.<clinit>(OpenTelemetrySpanSuppressionHelper.java:31)
 at io.opentelemetry.javaagent.instrumentation.azurecore.v1_19.shaded.com.azure.core.tracing.opentelemetry.OpenTelemetryHttpPolicy$ScalarPropagatingMono.subscribe(OpenTelemetryHttpPolicy.java:241)
 at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
 at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157)
 at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.lambda$onNext$1(TracingSubscriber.java:58)
 at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.withActiveSpan(TracingSubscriber.java:79)
 at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.onNext(TracingSubscriber.java:58)
 at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onNext(FluxHide.java:137)
 at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1839)
 at reactor.core.publisher.MonoCallable.subscribe(MonoCallable.java:62)
 at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
 at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157)
 at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.lambda$onNext$1(TracingSubscriber.java:58)
 at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.withActiveSpan(TracingSubscriber.java:79)
 at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.onNext(TracingSubscriber.java:58)
 at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onNext(FluxHide.java:137)
 at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1839)
 at reactor.core.publisher.MonoCallable.subscribe(MonoCallable.java:62)
 at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
 at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157)
 at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.lambda$onNext$1(TracingSubscriber.java:58)
 at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.withActiveSpan(TracingSubscriber.java:79)
 at io.opentelemetry.javaagent.shaded.instrumentation.reactor.TracingSubscriber.onNext(TracingSubscriber.java:58)
 at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onNext(FluxHide.java:137)
 at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1839)
 at reactor.core.publisher.MonoCallable.subscribe(MonoCallable.java:62)
 at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
 at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
 at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
 at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157)
 at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2400)
 at reactor.core.publisher.MonoFlatMap$FlatMapMain.onSubscribe(MonoFlatMap.java:110)
 at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:55)
 at reactor.core.publisher.Flux.subscribe(Flux.java:8642)
 at reactor.core.publisher.FluxExpand$ExpandBreathSubscriber.drainQueue(FluxExpand.java:179)
 at reactor.core.publisher.FluxExpand.subscribeOrReturn(FluxExpand.java:71)
 at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:55)
 at reactor.core.publisher.FluxDefer.subscribe(FluxDefer.java:54)
 at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62)
 at com.azure.core.util.paging.ContinuablePagedFluxCore.subscribe(ContinuablePagedFluxCore.java:244)
 at com.azure.core.http.rest.PagedFluxBase.subscribe(PagedFluxBase.java:220)
 at reactor.core.publisher.Mono.subscribe(Mono.java:4490)
 at reactor.core.publisher.MonoZip.subscribe(MonoZip.java:129)
 at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
 at reactor.core.publisher.FluxRepeatPredicate$RepeatPredicateSubscriber.resubscribe(FluxRepeatPredicate.java:120)
 at reactor.core.publisher.MonoRepeatPredicate.subscribeOrReturn(MonoRepeatPredicate.java:48)
 at reactor.core.publisher.Flux.subscribe(Flux.java:8628)
 at reactor.core.publisher.Flux.subscribeWith(Flux.java:8815)
 at reactor.core.publisher.Flux.subscribe(Flux.java:8608)
 at reactor.core.publisher.Flux.subscribe(Flux.java:8532)
 at com.azure.messaging.eventhubs.PartitionBasedLoadBalancer.loadBalance(PartitionBasedLoadBalancer.java:151)
 at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
 at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
 at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
 at java.base/java.lang.Thread.run(Thread.java:829)

**To Reproduce**

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - IDE: [e.g. IntelliJ]
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)]
 - Java version: [e.g. 8] 
 - App Server/Environment: [e.g. Tomcat, WildFly, Azure Function, Apache Spark, Databricks, IDE plugin or anything special]
 - Frameworks: [e.g. Spring Boot, Micronaut, Quarkus, etc] 

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by jairmyree** [comment]
@bhupendergiri Thank you for identifying this issue. @anuchandy could you please follow up?

**Comment by lmolkova** [comment]
@bhupendergiri this log is recorded with `DEBUG` severity and does not indicate any particular issue. So it's ok to ignore it.

Also, it seems you're using an oldish version of OpenTelemetry agent, this log record should not appear with a few latest versions of the agent. 

Please try updating OpenTelemetry agent to the latest version and feel free to reopen the issue if you still observe this log record.
