### ISSUE TITLE
[BUG]Flaky tests

### ISSUE THREAD

**Issue by xinlian12** [Azure/azure-sdk-for-java#34919]
handleMerge:
```
leaseManager.release(
TestLease-df51e2eb-6bd7-4f9d-923e-097bd92a8144 Owner='null' Continuation=null Version=EPK_RANGE_BASED_LEASE FeedRange=eyJSYW5nZSI6eyJtaW4iOiJBQSIsIm1heCI6IkNDIn19 Timestamp(local)=2023-05-12T16:40:00.668758400Z[UTC] Timestamp(server)=1970-01-01T00:00Z[UTC]
);
-> at com.azure.cosmos.implementation.changefeed.epkversion.PartitionControllerImplTests.handleMerge(PartitionControllerImplTests.java:206)


However, there was exactly 1 interaction with this mock:
leaseManager.acquire(
TestLease-df51e2eb-6bd7-4f9d-923e-097bd92a8144 Owner='null' Continuation=null Version=EPK_RANGE_BASED_LEASE FeedRange=eyJSYW5nZSI6eyJtaW4iOiJBQSIsIm1heCI6IkNDIn19 Timestamp(local)=2023-05-12T16:40:00.668758400Z[UTC] Timestamp(server)=1970-01-01T00:00Z[UTC]
);
-> at com.azure.cosmos.implementation.changefeed.epkversion.PartitionControllerImpl.addOrUpdateLease(PartitionControllerImpl.java:70)
```

**Comment by xinlian12** [comment]
Has not seen the issue recently especally after the CI pipeline improvement, close for now
