### ISSUE TITLE
[BUG] azure-security-keyvault-secrets throw NPE when used in GraalVM native image

### ISSUE THREAD

**Issue by zhoufenqin** [Azure/azure-sdk-for-java#34938]
**Describe the bug**
I use `azure-security-keyvault-secrets` SDK to get secrets from keyvault. 
The demo project shows here: https://github.com/zhoufenqin/managed-identity-keyvault

I use `mvn -Pnative native:compile` to compile it into an executable file, then run it.

After that, run 
`curl --location 'http://localhost:8080/secrets/get/secret1' --header 'Content-Type: application/json'  --data '{"keyVaultUri": "https://fenzho-kv.vault.azure.net/"}'` to get the secret

***Exception or Stack Trace***
```shell
2023-05-15T19:53:34.783+08:00 ERROR 31500 --- [nio-8080-exec-3] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: java.lang.NullPointerException] with root cause

java.lang.NullPointerException: null
        at com.azure.security.keyvault.secrets.KeyVaultErrorCodeStrings.loadProperties(KeyVaultErrorCodeStrings.java:38) ~[na:na]
        at com.azure.security.keyvault.secrets.KeyVaultErrorCodeStrings.getErrorString(KeyVaultErrorCodeStrings.java:31) ~[na:na]
        at com.azure.security.keyvault.secrets.SecretAsyncClient.<init>(SecretAsyncClient.java:93) ~[na:na]
        at com.azure.security.keyvault.secrets.SecretClientBuilder.buildAsyncClient(SecretClientBuilder.java:240) ~[managed-identity-keyvault.exe:4.4.3]
        at com.azure.security.keyvault.secrets.SecretClientBuilder.buildClient(SecretClientBuilder.java:158) ~[managed-identity-keyvault.exe:4.4.3]
        at com.microsoft.azure.MainController.buildSecretClient(MainController.java:107) ~[managed-identity-keyvault.exe:na]
        at com.microsoft.azure.MainController.getSecret(MainController.java:31) ~[managed-identity-keyvault.exe:na]
        at java.base@17.0.6/java.lang.reflect.Method.invoke(Method.java:568) ~[managed-identity-keyvault.exe:na]
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:207) ~[managed-identity-keyvault.exe:6.0.7]
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:152) ~[managed-identity-keyvault.exe:6.0.7]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118) ~[managed-identity-keyvault.exe:6.0.7]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:884) ~[managed-identity-keyvault.exe:6.0.7]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797) ~[managed-identity-keyvault.exe:6.0.7]
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[managed-identity-keyvault.exe:6.0.7]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1081) ~[managed-identity-keyvault.exe:6.0.7]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:974) ~[managed-identity-keyvault.exe:6.0.7]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1011) ~[managed-identity-keyvault.exe:6.0.7]
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:914) ~[managed-identity-keyvault.exe:6.0.7]
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:563) ~[managed-identity-keyvault.exe:6.0]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885) ~[managed-identity-keyvault.exe:6.0.7]
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:631) ~[managed-identity-keyvault.exe:6.0]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205) ~[na:na]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[na:na]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[managed-identity-keyvault.exe:10.1.7]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[na:na]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[na:na]
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[managed-identity-keyvault.exe:6.0.7]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[managed-identity-keyvault.exe:6.0.7]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[na:na]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[na:na]
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[managed-identity-keyvault.exe:6.0.7]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[managed-identity-keyvault.exe:6.0.7]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[na:na]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[na:na]
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[managed-identity-keyvault.exe:6.0.7]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[managed-identity-keyvault.exe:6.0.7]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[na:na]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[na:na]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:166) ~[na:na]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90) ~[na:na]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493) ~[managed-identity-keyvault.exe:10.1.7]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115) ~[na:na]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) ~[managed-identity-keyvault.exe:10.1.7]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) ~[na:na]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:341) ~[na:na]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390) ~[na:na]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) ~[managed-identity-keyvault.exe:10.1.7]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:894) ~[na:na]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741) ~[na:na]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[managed-identity-keyvault.exe:10.1.7]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[na:na]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[na:na]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[na:na]
        at java.base@17.0.6/java.lang.Thread.run(Thread.java:833) ~[managed-identity-keyvault.exe:na]
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775) ~[managed-identity-keyvault.exe:na]
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.windows.WindowsPlatformThreads.osThreadStartRoutine(WindowsPlatformThreads.java:178) ~[na:na]
```

Should the SDK do some support for AOT GraalVM? I think it should not use `KeyVaultErrorCodeStrings.class.getClassLoader().getResource((ERROR_STRINGS_FILE_NAME)).openStream())` to load resources in AOT compile, see [here](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/keyvault/azure-security-keyvault-secrets/src/main/java/com/azure/security/keyvault/secrets/implementation/KeyVaultErrorCodeStrings.java#LL38C23-L38C23)

**To Reproduce**
- 1. create an keyvault and set an secret
- 2. `mvn -Pnative native:compile`
- 3. run the executable file.

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**
should not throw NPE, if it can't connect to keyvault, should report that "Failed to get secret xxxx"

**Screenshots**

**Setup (please complete the following information):**
 - OS: windows 11
 - IDE: IntelliJ
 - Library/Libraries: azure-security-keyvault-secrets:4.4.3
 - Java version: 17
 - App Server/Environment: [e.g. Tomcat, WildFly, Azure Function, Apache Spark, Databricks, IDE plugin or anything special]
 - Frameworks: Spring Boot

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by jairmyree** [comment]
@zhoufenqin Thank you for identifying this issue, @vcolin7 could you please take a look at this?

**Comment by vcolin7** [comment]
Thanks for reporting this @zhoufenqin, I will look into it but I think we can change things to avoid loading the error message from a separate file.
