### ISSUE TITLE
[BUG] Spring Stream Cloud Binder Azure Service Bus cannot be disabled with property

### ISSUE THREAD

**Issue by AvramPop** [Azure/azure-sdk-for-java#34937]
**Describe the bug**
I am using `spring-cloud-azure-stream-binder-servicebus` version `4.7.0` and try to disable the consumer in some of the environments. For that, I added the following property in our application.properties: `spring.cloud.azure.servicebus.enabled=false`. When I start the application, I get the stack trace described below:

***Exception or Stack Trace***
```
2023-05-15 12:49:18.652 ERROR 11052 --- [   scheduling-1] o.s.cloud.stream.binding.BindingService  : Failed to create consumer binding; retrying in 30 seconds

org.springframework.cloud.stream.binder.BinderException: Exception thrown while starting consumer: 
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindConsumer(AbstractMessageChannelBinder.java:486)
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindConsumer(AbstractMessageChannelBinder.java:98)
	at org.springframework.cloud.stream.binder.AbstractBinder.bindConsumer(AbstractBinder.java:143)
	at org.springframework.cloud.stream.binding.BindingService.lambda$rescheduleConsumerBinding$1(BindingService.java:209)
	at net.javacrumbs.shedlock.core.DefaultLockManager.executeWithLock(DefaultLockManager.java:49)
	at net.javacrumbs.shedlock.core.LockableRunnable.run(LockableRunnable.java:35)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NullPointerException: 'fullyQualifiedNamespace' cannot be null.
	at java.base/java.util.Objects.requireNonNull(Objects.java:233)
	at com.azure.messaging.servicebus.ServiceBusClientBuilder.fullyQualifiedNamespace(ServiceBusClientBuilder.java:269)
	at com.azure.spring.cloud.service.implementation.servicebus.factory.AbstractServiceBusSubClientBuilderFactory.configureService(AbstractServiceBusSubClientBuilderFactory.java:159)
	at com.azure.spring.cloud.service.implementation.servicebus.factory.ServiceBusProcessorClientBuilderFactory.configureService(ServiceBusProcessorClientBuilderFactory.java:67)
	at com.azure.spring.cloud.service.implementation.servicebus.factory.ServiceBusProcessorClientBuilderFactory.configureService(ServiceBusProcessorClientBuilderFactory.java:20)
	at com.azure.spring.cloud.core.implementation.factory.AbstractAzureServiceClientBuilderFactory.build(AbstractAzureServiceClientBuilderFactory.java:127)
	at com.azure.spring.messaging.servicebus.core.DefaultServiceBusNamespaceProcessorFactory.lambda$doCreateProcessor$3(DefaultServiceBusNamespaceProcessorFactory.java:196)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at com.azure.spring.messaging.servicebus.core.DefaultServiceBusNamespaceProcessorFactory.doCreateProcessor(DefaultServiceBusNamespaceProcessorFactory.java:163)
	at com.azure.spring.messaging.servicebus.core.DefaultServiceBusNamespaceProcessorFactory.createProcessor(DefaultServiceBusNamespaceProcessorFactory.java:135)
	at com.azure.spring.messaging.servicebus.core.listener.ServiceBusMessageListenerContainer.doStart(ServiceBusMessageListenerContainer.java:51)
	at com.azure.spring.messaging.listener.AbstractMessageListenerContainer.start(AbstractMessageListenerContainer.java:51)
	at com.azure.spring.integration.servicebus.inbound.ServiceBusInboundChannelAdapter.doStart(ServiceBusInboundChannelAdapter.java:119)
	at org.springframework.integration.endpoint.AbstractEndpoint.start(AbstractEndpoint.java:157)
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindConsumer(AbstractMessageChannelBinder.java:439)
	... 12 common frames omitted

```
**To Reproduce**
1. Create a Spring Boot 2.6 application
2. Add the following dependency: (together with the others needed such as Spring Cloud)
```
		<dependency>
			<groupId>com.azure.spring</groupId>
			<artifactId>spring-cloud-azure-stream-binder-servicebus</artifactId>
			<version>4.7.0</version>
		</dependency>
```
3. Add `spring.cloud.azure.servicebus.enabled=false` to application.properties.
4. Add a dummy consumer, such as:
```
    public Consumer<Message<byte[]>> consume() {
        return message -> System.out.println(message);
    }
```

**Comment by Netyyyy** [comment]
Hi @AvramPop sorry for the late reply.
If you want to disable the consumer, you could try to set `spring.cloud.azure.servicebus.consumer.enabled=false`.
Refer to [Azure Service Bus configuration properties](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configuration-properties-azure-service-bus)

**Comment by anuchandy** [comment]
Closing as the correct configuration property to use here is provided.
