### ISSUE TITLE
[BUG] Frequent occurrences of "Stream is already closed." when calling `close` on a StorageOutputStream

### ISSUE THREAD

**Issue by danking** [Azure/azure-sdk-for-java#35125]
**Describe the bug**
We run a distributed, highly parallel data processing system. Our CI/CD system issues millions of requests to Azure Blob Storage per day. Out of these millions of requests, we, perhaps several times a day, see failures when calling `close`. The failure states just "Stream is already closed.". These streams are wrapped by our streams which are idempotent. I am confident we are only calling `StorageOutputStream.close` once. This suggests to me that the underlying stream is getting closed by the remote peer and this is getting propagated back to our code.

It seems like the Azure ADK should notice this bad state and provide us a more informative error message, e.g. "too many requests". The error message as it stands seems to suggest the output stream was already successfully closed. I suspect that's not true though: I suspect nothing was committed into ABS.

Related to #24782

***Exception or Stack Trace***
```
E           java.lang.RuntimeException: Stream is already closed.
E           	at is.hail.shadedazure.com.azure.storage.common.StorageOutputStream.checkStreamState(StorageOutputStream.java:92)
E           	at is.hail.shadedazure.com.azure.storage.common.StorageOutputStream.flush(StorageOutputStream.java:102)
E           	at is.hail.io.fs.AzureStorageFS$$anon$3.close(AzureStorageFS.scala:309)
E           	at java.io.FilterOutputStream.close(FilterOutputStream.java:159)
E           	at java.util.zip.DeflaterOutputStream.close(DeflaterOutputStream.java:241)
E           	at is.hail.utils.package$.using(package.scala:640)
E           	at is.hail.io.index.IndexWriterUtils.writeMetadata(IndexWriter.scala:196)
E           	at __C48104collect_distributed_array_table_native_writer.apply(Unknown Source)
E           	at __C48104collect_distributed_array_table_native_writer.apply(Unknown Source)
E           	at is.hail.backend.BackendUtils.$anonfun$collectDArray$3(BackendUtils.scala:39)
E           	at is.hail.utils.package$.using(package.scala:635)
E           	at is.hail.backend.BackendUtils.$anonfun$collectDArray$2(BackendUtils.scala:38)
E           	at is.hail.utils.package$.using(package.scala:635)
E           	at is.hail.backend.BackendUtils.collectDArray(BackendUtils.scala:37)
E           	at __C48079Compiled.__m48081split_Let(Emit.scala)
E           	at __C48079Compiled.apply(Emit.scala)
E           	at is.hail.backend.service.ServiceBackend.$anonfun$execute$1(ServiceBackend.scala:322)
E           	at is.hail.backend.service.ServiceBackend.$anonfun$execute$1$adapted(ServiceBackend.scala:322)
E           	at is.hail.backend.ExecuteContext.$anonfun$scopedExecution$1(ExecuteContext.scala:140)
E           	at is.hail.utils.package$.using(package.scala:635)
E           	at is.hail.backend.ExecuteContext.scopedExecution(ExecuteContext.scala:140)
E           	at is.hail.backend.service.ServiceBackend.execute(ServiceBackend.scala:322)
E           	at is.hail.backend.service.ServiceBackend.execute(ServiceBackend.scala:349)
E           	at is.hail.backend.service.ServiceBackendSocketAPI2.$anonfun$executeOneCommand$12(ServiceBackend.scala:702)
E           	at is.hail.backend.service.ServiceBackendSocketAPI2.withIRFunctionsReadFromInput(ServiceBackend.scala:805)
E           	at is.hail.backend.service.ServiceBackendSocketAPI2.$anonfun$executeOneCommand$11(ServiceBackend.scala:700)
E           	at is.hail.backend.service.ServiceBackendSocketAPI2.$anonfun$executeOneCommand$2(ServiceBackend.scala:658)
E           	at is.hail.backend.ExecuteContext$.$anonfun$scoped$3(ExecuteContext.scala:75)
E           	at is.hail.utils.package$.using(package.scala:635)
E           	at is.hail.backend.ExecuteContext$.$anonfun$scoped$2(ExecuteContext.scala:75)
E           	at is.hail.utils.package$.using(package.scala:635)
E           	at is.hail.annotations.RegionPool$.scoped(RegionPool.scala:17)
E           	at is.hail.backend.ExecuteContext$.scoped(ExecuteContext.scala:63)
E           	at is.hail.backend.service.ServiceBackendSocketAPI2.$anonfun$executeOneCommand$1(ServiceBackend.scala:648)
E           	at is.hail.utils.ExecutionTimer$.time(ExecutionTimer.scala:52)
E           	at is.hail.utils.ExecutionTimer$.logTime(ExecutionTimer.scala:59)
E           	at is.hail.backend.service.ServiceBackendSocketAPI2.withExecuteContext$1(ServiceBackend.scala:634)
E           	at is.hail.backend.service.ServiceBackendSocketAPI2.executeOneCommand(ServiceBackend.scala:697)
E           	at is.hail.backend.service.ServiceBackendSocketAPI2$.$anonfun$main$6(ServiceBackend.scala:462)
E           	at is.hail.backend.service.ServiceBackendSocketAPI2$.$anonfun$main$6$adapted(ServiceBackend.scala:461)
E           	at is.hail.utils.package$.using(package.scala:635)
E           	at is.hail.backend.service.ServiceBackendSocketAPI2$.$anonfun$main$5(ServiceBackend.scala:461)
E           	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
E           	at is.hail.services.package$.retryTransientErrors(package.scala:137)
E           	at is.hail.backend.service.ServiceBackendSocketAPI2$.$anonfun$main$4(ServiceBackend.scala:460)
E           	at is.hail.backend.service.ServiceBackendSocketAPI2$.$anonfun$main$4$adapted(ServiceBackend.scala:459)
E           	at is.hail.utils.package$.using(package.scala:635)
E           	at is.hail.backend.service.ServiceBackendSocketAPI2$.$anonfun$main$3(ServiceBackend.scala:459)
E           	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
E           	at is.hail.services.package$.retryTransientErrors(package.scala:137)
E           	at is.hail.backend.service.ServiceBackendSocketAPI2$.main(ServiceBackend.scala:458)
E           	at is.hail.backend.service.Main$.main(Main.scala:15)
E           	at is.hail.backend.service.Main.main(Main.scala)
E           	at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
E           	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
E           	at java.lang.reflect.Method.invoke(Method.java:498)
E           	at is.hail.JVMEntryway$1.run(JVMEntryway.java:119)
E           	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
E           	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E           	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
E           	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E           	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
E           	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
E           	at java.lang.Thread.run(Thread.java:750)
```

**To Reproduce**
This is hard to reproduce. I suspect you'll need to use the Azure SDK to upload millions of objects per day to observe this with reasonable frequency.

***Code Snippet***
I can't provide a small code snippet that reliably reproduces this.

**Expected behavior**
I expect that if I'm getting rate limited, I get such a message. I expect that if the stream closed *without successfully storing the object* that I get an error indicating that the upload was unsuccessful.

**Screenshots**
N/A

**Setup (please complete the following information):**
 - OS: ubuntu:focal-20221019
 - IDE: N/A
 - Library/Libraries: 
```
    implementation group: 'com.azure', name: 'azure-storage-blob', version: '12.22.0'
    implementation group: 'com.azure', name: 'azure-core-http-netty', version: '1.13.3'
    implementation group: 'com.azure', name: 'azure-identity', version:'1.8.3'
```
 - Java version: 8
 - App Server/Environment: Inside a GNU/Linux container started by crun.
 - Frameworks: None.

**Additional context**
N/A

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by alzimmermsft** [comment]
Hi @danking thanks for reaching out to us via this GitHub issue. Someone from the storage team will follow up shortly.

// cc @ibrahimrabab

**Comment by ibrahimrabab** [comment]
Hi @danking 
Thanks for reaching out! Without a repro on our end, it's hard to determine what's causing the issue. I know you mentioned it's difficult to provide a code snippet with the issue reproducing, but can you provide a some code sample that shows the workflow you're going through with writing to the blobs and closing them? Also, are you running your application on multi threads? 
Thanks!

**Comment by danking** [comment]
Each input stream is created and consumed by one thread at a time.

The azure library lies under many layers of abstraction I don’t think any example I give you will be more insightful than what I’ve shared. For anyone who finds this issue in the future, we’ve treated this as a transient error. We catch it, check for the message, and then retry the upload with a new request. We hold the request body in memory so that we can do this retry. 

I’ll close since I don’t think y’all can make forward progress without more information.

**Comment by ibrahimrabab** [comment]
@danking sorry we could not help more, but I'm glad there is a workaround. If you have any additional questions, please feel free to reach out :)
