### ISSUE TITLE
[BUG] Native image build exception when using azure-core SDK 

### ISSUE THREAD

**Issue by zhoufenqin** [Azure/azure-sdk-for-java#35168]
I write a springboot project about accessing storage blob by managed identity, here is a [sample](https://github.com/zhoufenqin/java-native-image-samples/tree/main/managed-identity/managed-identity-storage-blob), Now I want to test if the feature can be realized in the native image.

When using `mvn -Pnative native:compile` I meet a problem caused by azure-core
```
.....
ch.qos.logback.core.util.Loader was unintentionally initialized at build time. com.azure.core.util.Configuration caused initialization of this class with the following trace:
        at ch.qos.logback.core.util.Loader.<clinit>(Loader.java:34)
        at ch.qos.logback.classic.util.DefaultJoranConfigurator.findURLOfDefaultConfigurationFile(DefaultJoranConfigurator.java:61)
        at ch.qos.logback.classic.util.DefaultJoranConfigurator.configure(DefaultJoranConfigurator.java:31)
        at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:98)
        at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:77)
        at ch.qos.logback.classic.spi.LogbackServiceProvider.initializeLoggerContext(LogbackServiceProvider.java:50)
        at ch.qos.logback.classic.spi.LogbackServiceProvider.initialize(LogbackServiceProvider.java:41)
        at org.slf4j.LoggerFactory.bind(LoggerFactory.java:183)
        at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:170)
        at org.slf4j.LoggerFactory.getProvider(LoggerFactory.java:455)
        at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:441)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:390)
        at com.azure.core.util.logging.ClientLogger.<init>(ClientLogger.java:100)
        at com.azure.core.util.logging.ClientLogger.<init>(ClientLogger.java:66)
        at com.azure.core.util.logging.ClientLogger.<init>(ClientLogger.java:56)
        at com.azure.core.util.Configuration.<clinit>(Configuration.java:227)

ch.qos.logback.core.status.InfoStatus was unintentionally initialized at build time. com.azure.core.util.Configuration caused initialization of this class with the following trace:
        at ch.qos.logback.core.status.InfoStatus.<clinit>(InfoStatus.java)
        at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:85)
        at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:77)
        at ch.qos.logback.classic.spi.LogbackServiceProvider.initializeLoggerContext(LogbackServiceProvider.java:50)
        at ch.qos.logback.classic.spi.LogbackServiceProvider.initialize(LogbackServiceProvider.java:41)
        at org.slf4j.LoggerFactory.bind(LoggerFactory.java:183)
        at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:170)
        at org.slf4j.LoggerFactory.getProvider(LoggerFactory.java:455)
        at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:441)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:390)
        at com.azure.core.util.logging.ClientLogger.<init>(ClientLogger.java:100)
        at com.azure.core.util.logging.ClientLogger.<init>(ClientLogger.java:66)
        at com.azure.core.util.logging.ClientLogger.<init>(ClientLogger.java:56)
        at com.azure.core.util.Configuration.<clinit>(Configuration.java:227)

ch.qos.logback.core.util.StatusPrinter was unintentionally initialized at build time. com.azure.core.util.Configuration caused initialization of this class with the following trace:
        at ch.qos.logback.core.util.StatusPrinter.<clinit>(StatusPrinter.java:29)
        at ch.qos.logback.classic.spi.LogbackServiceProvider.initializeLoggerContext(LogbackServiceProvider.java:56)
        at ch.qos.logback.classic.spi.LogbackServiceProvider.initialize(LogbackServiceProvider.java:41)
        at org.slf4j.LoggerFactory.bind(LoggerFactory.java:183)
        at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:170)
        at org.slf4j.LoggerFactory.getProvider(LoggerFactory.java:455)
        at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:441)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:390)
        at com.azure.core.util.logging.ClientLogger.<init>(ClientLogger.java:100)
        at com.azure.core.util.logging.ClientLogger.<init>(ClientLogger.java:66)
        at com.azure.core.util.logging.ClientLogger.<init>(ClientLogger.java:56)
        at com.azure.core.util.Configuration.<clinit>(Configuration.java:227)


        at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.UserError.abort(UserError.java:73)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.classinitialization.ProvenSafeClassInitializationSupport.checkDelayedInitialization(ProvenSafeClassInitializationSupport.java:273)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.duringAnalysis(ClassInitializationFeature.java:164)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$10(NativeImageGenerator.java:748)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:85)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$11(NativeImageGenerator.java:748)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.AbstractAnalysisEngine.runAnalysis(AbstractAnalysisEngine.java:162)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:745)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:578)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:535)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:403)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:580)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
```

There is a similar bug: https://github.com/Azure/azure-sdk-for-java/issues/33328

Does it a bug from azure-core to support native image?

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**
download the sample
run `mvn -Pnative native:compile`

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**
it can be build successfully.

**Screenshots**

**Setup (please complete the following information):**
 - OS: windows11
 - IDE:  IntelliJ
 - Library/Libraries:  com.azure:azure-core:1.39.0
 - Java version: JDK17
 - App Server/Environment: [e.g. Tomcat, WildFly, Azure Function, Apache Spark, Databricks, IDE plugin or anything special]
 - Frameworks: Spring Boot
 - 
If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by srnagar** [comment]
@barrotsteindev @zhoufenqin  This is an issue with the classes that are loaded from logback library which is a non-Azure dependency used in Spring applications. However, we do include the configuration to support the necessary classes that this popular logging library initializes at build time. Here are some of the classes we have included and note that other classes may be need depending on how you are using this library. 

https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/core/azure-core/src/main/resources/META-INF/native-image/com.azure/azure-core/native-image.properties#L6-L15


As shown in the example above, you can add your own `native-image.properties` in `src/main/resources/META-INF/native-image/<your-app-group-name>/<your-app-name>` directory of your application and add more classes that are not included in the Azure configuration files.
