### ISSUE TITLE
[BUG] Service Bus processing hangs on receiving message

### ISSUE THREAD

**Issue by lidkowiak** [Azure/azure-sdk-for-java#35197]
Service Bus processing hangs on receiving messages within session. The only solution is to restart the process.

***Thread dump***:

```
"EE-ManagedExecutorService-ServiceBusExecutor-Thread-2" #445 daemon prio=5 os_prio=0 tid=0x000001a498c76800 nid=0x22a0 waiting on condition [0x0000007f554fe000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0000000698fbde80> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2044)
	at reactor.core.publisher.BlockingIterable$SubscriberIterator.hasNext(BlockingIterable.java:179)
	at java.util.Iterator.forEachRemaining(Iterator.java:115)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at [COMPANY PACKAGE].servicebus.SessionsHandler.processSession(SessionsHandler.java:120)
	at [COMPANY PACKAGE].servicebus.SessionsHandler.processSessions(SessionsHandler.java:83)
	at [COMPANY PACKAGE].SessionsHandler$$Lambda$2084/1332643277.run(Unknown Source)
	at org.jboss.as.ee.concurrent.ControlPointUtils$ControlledRunnable.run(ControlPointUtils.java:125)
	at org.wildfly.security.auth.server.Scoped$$Lambda$2095/858682343.accept(Unknown Source)
	at org.wildfly.security.auth.server.Scoped$$Lambda$2098/1043870569.accept(Unknown Source)
	at org.wildfly.security.auth.server.SecurityIdentity.runAsConsumer(SecurityIdentity.java:376)
	at org.wildfly.security.auth.server.Scoped.runAsConsumer(Scoped.java:112)
	at org.wildfly.security.auth.server.Scoped.runAs(Scoped.java:60)
	at org.jboss.as.ee.concurrent.SecurityIdentityUtils.lambda$doIdentityWrap$1(SecurityIdentityUtils.java:63)
	at org.jboss.as.ee.concurrent.SecurityIdentityUtils$$Lambda$2086/1755134231.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.glassfish.enterprise.concurrent.internal.ManagedFutureTask.run(ManagedFutureTask.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
	at org.glassfish.enterprise.concurrent.ManagedThreadFactoryImpl$ManagedThread.run(ManagedThreadFactoryImpl.java:227)
```

Steps to reproduce the behavior: unknown, behaviour seems to be nondeterministic although we observed it for topics with lots of sessions  and maxWaitTimeOnReceivingMessage set to 1 sec

***Code***

```
 private void processSessions() {
        while (true) {
            try {
                if (stopSignalReceived) {
                    break;
                }
                processSession(serviceBusSessionReceiverClient.acceptNextSession());
            } catch (IllegalStateException e) {
                log.trace("Timeout happened on acceptNextSession(), ignoring.");
            } catch (AmqpException amqpException) { // https://github.com/Azure/azure-sdk-for-java/issues/28337
                log.warn("Received AMQP exception. Condition: {}, transient: {}, message: {}",
                        amqpException.getErrorCondition(), amqpException.isTransient(), amqpException.getMessage());
            } catch (Exception e) {
                log.error("Exception on receiving on topic {}", entityPath, e);
            }
        }
        log.info("Finished infinite acceptNextSession loop on {}", entityPath);
    }

    private void processSession(ServiceBusReceiverClient serviceBusReceiverClient) {
        // fix: https://github.com/Azure/azure-sdk-for-java/issues/28337
        if (serviceBusReceiverClient == null) {
            log.warn("serviceBusSessionReceiverClient.acceptNextSession() returned null");
            return;
        }
        final Instant sessionLockTimestamp = clock.instant().plus(maxAutoLockRenewal);
        final String sessionId = serviceBusReceiverClient.getSessionId();

        log.info("New session accepted {}", sessionId);

        String stoppingReason = "unknown";

        while (true) {
            try {
                if (stopSignalReceived) {
                    stoppingReason = "STOP_SIGNAL_RECEIVED";
                    break;
                }
                if (clock.instant().isAfter(sessionLockTimestamp)) {
                    stoppingReason = "SESSION_TIMEOUT_EXCEEDED";
                    break;
                }
                final List<ServiceBusReceivedMessage> receivedMessagesStream = serviceBusReceiverClient.receiveMessages(prefetchCount, maxWaitTimeOnReceivingMessage)
                        .stream().collect(Collectors.toList()); // hangs here

                if (receivedMessagesStream.isEmpty()) {
                    stoppingReason = "NO_MESSAGE_IN_SESSION";
                    break;
                }

                receivedMessagesStream.forEach(receivedMessage -> messageHandler.handle(receivedMessage, serviceBusReceiverClient));

            } catch (ServiceBusException e) {
                log.warn("Exception while receiving/processing messages sessionId {}", sessionId, e);
                stoppingReason = "EXCEPTION_OCCURRED";
                break;
            }
        }

        log.info("Closing session {} reason {}", sessionId, stoppingReason);
        serviceBusReceiverClient.close();
    }
```

**Setup**
 - OS: Windows Server 2019 Datacenter/Azure VM 
 - Library/Libraries: com.azure:azure-sdk-bom:1.2.12, com.azure:azure-messaging-servicebus:7.13.4
 - Java version: 8
 - App Server/Environment: WildFly 26.1.3.Final

**Comment by anuchandy** [comment]
Would you be able to share the -10/+10 logs from the point when library stops emitting messages from a session? 

Also, to understand a bit more about the use case – Is the application process one session at a time then move to next, as shown in the same code, or are there any concurrency involved?

**Comment by lidkowiak** [comment]
Sorry I'm not able to provide any logs for this issue. There is part of the tread dump we caught

**Comment by anuchandy** [comment]
Hello @lidkowiak, there is a bug exists in version 7.13.4, which can leads the Session receiveMessages() API to hang. From the code and comment you provided, the application seems to hung on receiveMessages. The detail of the hang is here https://github.com/Azure/azure-sdk-for-java/issues/34597. Could you upgrade  to the latest version (7.14.3 as of today 8/21/2023)?

**Comment by anuchandy** [comment]
Recommendation to upgrade the SDK version provided as the older version 7.13.4 known to have the problem.
