### ISSUE TITLE
Spring cloud stream service bus binder health recovery

### ISSUE THREAD

**Issue by dhananjay12** [Azure/azure-sdk-for-java#35266]
## Background
We are using service bus binder which pushes message to Azure service bus topics. The app is running in a K8s environment. 

spring-cloud-azure-stream-binder-servicebus - 4.4.1
Spring boot -2.7.7

There are unknown situation where the connectivity for the app and azure-service-bus is lost, resulting in readiness probe to be down. 
![image](https://github.com/Azure/azure-sdk-for-java/assets/950278/55445cca-7446-43bf-a377-315de70c5563)

In the logs I can see that the expected error
```
2023-06-02 03:20:39.976 ERROR 63250 --- [ctor-executor-9] reactor.core.publisher.Operators         : Operator called default onErrorDropped

reactor.core.Exceptions$ErrorCallbackNotImplemented: com.azure.messaging.servicebus.ServiceBusException: Retries exhausted: 3/3
Caused by: com.azure.messaging.servicebus.ServiceBusException: Retries exhausted: 3/3
	at com.azure.messaging.servicebus.ServiceBusSenderAsyncClient.mapError(ServiceBusSenderAsyncClient.java:848) ~[azure-messaging-servicebus-7.11.0.jar:7.11.0]
	at reactor.core.publisher.Mono.lambda$onErrorMap$31(Mono.java:3811) ~[reactor-core-3.4.26.jar:3.4.26]
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94) ~[reactor-core-3.4.26.jar:3.4.26]
	at reactor.core.publisher.FluxDoOnEach$DoOnEachSubscriber.onError(FluxDoOnEach.java:195) ~[reactor-core-3.4.26.jar:3.4.26]
	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onError(MonoPeekTerminal.java:258) ~[reactor-core-3.4.26.jar:3.4.26]
	at reactor.core.publisher.SerializedSubscriber.onError(SerializedSubscriber.java:124) ~[reactor-core-3.4.26.jar:3.4.26]
	at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.whenError(FluxRetryWhen.java:225) ~[reactor-core-3.4.26.jar:3.4.26]
	at reactor.core.publisher.FluxRetryWhen$RetryWhenOtherSubscriber.onError(FluxRetryWhen.java:274) ~[reactor-core-3.4.26.jar:3.4.26]
	at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onError(FluxContextWrite.java:121) ~[reactor-core-3.4.26.jar:3.4.26]
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:415) ~[reactor-core-3.4.26.jar:3.4.26]
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onNext(FluxConcatMap.java:251) ~[reactor-core-3.4.26.jar:3.4.26]
	at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107) ~[reactor-core-3.4.26.jar:3.4.26]
	at reactor.core.publisher.EmitterProcessor.drain(EmitterProcessor.java:537) ~[reactor-core-3.4.26.jar:3.4.26]
	at reactor.core.publisher.EmitterProcessor.tryEmitNext(EmitterProcessor.java:343) ~[reactor-core-3.4.26.jar:3.4.26]
	at reactor.core.publisher.SinkManySerialized.tryEmitNext(SinkManySerialized.java:100) ~[reactor-core-3.4.26.jar:3.4.26]
	at reactor.core.publisher.InternalManySink.emitNext(InternalManySink.java:27) ~[reactor-core-3.4.26.jar:3.4.26]
	at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.onError(FluxRetryWhen.java:190) ~[reactor-core-3.4.26.jar:3.4.26]
	at reactor.core.publisher.SerializedSubscriber.onError(SerializedSubscriber.java:124) ~[reactor-core-3.4.26.jar:3.4.26]
	at reactor.core.publisher.SerializedSubscriber.onError(SerializedSubscriber.java:124) ~[reactor-core-3.4.26.jar:3.4.26]
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.onError(FluxTimeout.java:219) ~[reactor-core-3.4.26.jar:3.4.26]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:172) ~[reactor-core-3.4.26.jar:3.4.26]
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onError(FluxPeekFuseable.java:234) ~[reactor-core-3.4.26.jar:3.4.26]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondError(MonoFlatMap.java:192) ~[reactor-core-3.4.26.jar:3.4.26]
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onError(MonoFlatMap.java:259) ~[reactor-core-3.4.26.jar:3.4.26]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:172) ~[reactor-core-3.4.26.jar:3.4.26]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onError(FluxMapFuseable.java:142) ~[reactor-core-3.4.26.jar:3.4.26]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:172) ~[reactor-core-3.4.26.jar:3.4.26]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onError(FluxMapFuseable.java:142) ~[reactor-core-3.4.26.jar:3.4.26]
	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onError(MonoPeekTerminal.java:258) ~[reactor-core-3.4.26.jar:3.4.26]
	at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onError(FluxHide.java:142) ~[reactor-core-3.4.26.jar:3.4.26]
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onError(MonoIgnoreThen.java:278) ~[reactor-core-3.4.26.jar:3.4.26]
	at reactor.core.publisher.SerializedSubscriber.onError(SerializedSubscriber.java:124) ~[reactor-core-3.4.26.jar:3.4.26]
	at reactor.core.publisher.SerializedSubscriber.onError(SerializedSubscriber.java:124) ~[reactor-core-3.4.26.jar:3.4.26]
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.onError(FluxTimeout.java:219) ~[reactor-core-3.4.26.jar:3.4.26]
	at reactor.core.publisher.MonoNext$NextSubscriber.onError(MonoNext.java:93) ~[reactor-core-3.4.26.jar:3.4.26]
	at reactor.core.publisher.FluxFilterFuseable$FilterFuseableSubscriber.onError(FluxFilterFuseable.java:162) ~[reactor-core-3.4.26.jar:3.4.26]
	at reactor.core.publisher.FluxReplay$SizeBoundReplayBuffer.replayNormal(FluxReplay.java:865) ~[reactor-core-3.4.26.jar:3.4.26]
	at reactor.core.publisher.FluxReplay$SizeBoundReplayBuffer.replay(FluxReplay.java:965) ~[reactor-core-3.4.26.jar:3.4.26]
	at reactor.core.publisher.FluxReplay$ReplaySubscriber.onError(FluxReplay.java:1360) ~[reactor-core-3.4.26.jar:3.4.26]
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:222) ~[reactor-core-3.4.26.jar:3.4.26]
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:106) ~[reactor-core-3.4.26.jar:3.4.26]
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onError(MonoIgnoreThen.java:278) ~[reactor-core-3.4.26.jar:3.4.26]
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:231) ~[reactor-core-3.4.26.jar:3.4.26]
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:203) ~[reactor-core-3.4.26.jar:3.4.26]
	at reactor.core.publisher.SinkEmptyMulticast$VoidInner.complete(SinkEmptyMulticast.java:272) ~[reactor-core-3.4.26.jar:3.4.26]
	at reactor.core.publisher.SinkEmptyMulticast.tryEmitEmpty(SinkEmptyMulticast.java:86) ~[reactor-core-3.4.26.jar:3.4.26]
	at reactor.core.publisher.SinkEmptySerialized.tryEmitEmpty(SinkEmptySerialized.java:46) ~[reactor-core-3.4.26.jar:3.4.26]
	at reactor.core.publisher.InternalEmptySink.emitEmpty(InternalEmptySink.java:26) ~[reactor-core-3.4.26.jar:3.4.26]
	at com.azure.core.amqp.implementation.ReactorConnection.lambda$closeConnectionWork$34(ReactorConnection.java:527) ~[azure-core-amqp-2.7.1.jar:2.7.1]
	at reactor.core.publisher.MonoRunnable.call(MonoRunnable.java:73) ~[reactor-core-3.4.26.jar:3.4.26]
	at reactor.core.publisher.MonoRunnable.call(MonoRunnable.java:32) ~[reactor-core-3.4.26.jar:3.4.26]
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:228) ~[reactor-core-3.4.26.jar:3.4.26]
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:203) ~[reactor-core-3.4.26.jar:3.4.26]
	at reactor.core.publisher.SinkEmptyMulticast$VoidInner.complete(SinkEmptyMulticast.java:272) ~[reactor-core-3.4.26.jar:3.4.26]
	at reactor.core.publisher.SinkEmptyMulticast.tryEmitEmpty(SinkEmptyMulticast.java:86) ~[reactor-core-3.4.26.jar:3.4.26]
	at reactor.core.publisher.SinkEmptySerialized.tryEmitEmpty(SinkEmptySerialized.java:46) ~[reactor-core-3.4.26.jar:3.4.26]
	at reactor.core.publisher.InternalEmptySink.emitEmpty(InternalEmptySink.java:26) ~[reactor-core-3.4.26.jar:3.4.26]
	at com.azure.core.amqp.implementation.ReactorExecutor.close(ReactorExecutor.java:188) ~[azure-core-amqp-2.7.1.jar:2.7.1]
	at com.azure.core.amqp.implementation.ReactorExecutor.lambda$scheduleCompletePendingTasks$1(ReactorExecutor.java:173) ~[azure-core-amqp-2.7.1.jar:2.7.1]
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68) ~[reactor-core-3.4.26.jar:3.4.26]
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28) ~[reactor-core-3.4.26.jar:3.4.26]
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
Caused by: reactor.core.Exceptions$RetryExhaustedException: Retries exhausted: 3/3
	at reactor.core.Exceptions.retryExhausted(Exceptions.java:294) ~[reactor-core-3.4.26.jar:3.4.26]
```

Spring actuator configurations for readiness/liveness:
```
management.endpoint.health.group.readiness.include=*
management.endpoint.health.group.readiness.show-details=always
management.endpoint.health.group.liveness.include=ping
management.endpoint.health.group.liveness.show-details=never
```
`readiness.show-details=always` is only to debug the application.

Because the readiness probe is DOWN, K8s stops sending traffic to the POD.

## Issue

When the connection gets restored, the readiness probe is still down and doesnt recover. K8s has stopped traffic to it, a successful request although possible never happens. 

On reproducing it locally, if I send a request to the service, it will connect and send the messsage to service-bus and the Health Endpoint is back to UP status. But this is not the case with K8s where the traffic is stopped to the container, and it just stays in that position.

I did find this class in the azure-binder class

![image](https://github.com/Azure/azure-sdk-for-java/assets/950278/0c2537f1-bc5c-4eb9-9b82-c9530aff4166)
The health instrumentation for the topic is always down until there is a successful delivery which is not possible in K8s. 

Is there any other configuration you would suggest to tackle this scenario? 

### Setup
The only way I could reproduce this situation locally is by running a simple app when the connection with the service bus is stable. I make a few successful requests and then intentionally disable the internet connection on my laptop. When attempting to make another request, it throws a retry exception, causing the readiness probe to fail (and the application to become unavailable if it was in K8s env). Even after restoring the internet connection, the app's readiness probe never recovers.

Simple app - https://github.com/dhananjay12/learn-azure/tree/main/scs-service-bus
NOTE - For connection we are using `service principal` way to connect to the service-bus topic. 
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Query Added
- [ ] Setup information Added

**Comment by dhananjay12** [comment]
The problem is with any kind of exception we get in the producer, after which it makes the readiness probe DOWN.  Another way to produce the issue is 
```
@GetMapping("/test")
    public void test() {
        JSONObject jsonObject = new JSONObject();

        for (int i = 0; i <= 3000; i++) {
            String key = "description" + i;
            String value = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque cursus, nisl sed vestibulum tempus, " +
                    "lectus leo venenatis massa, ut ullamcorper libero enim sit amet mi. Fusce aliquam aliquet augue, " +
                    "vitae pellentesque ex dignissim quis. Sed et neque ligula. Vivamus elementum varius lobortis. Sed " +
                    "efficitur, lorem vel efficitur faucibus, libero ex iaculis nisi, id consectetur massa orci ac tortor. " +
                    "Nullam malesuada lectus enim, vitae bibendum ex pulvinar nec. Nulla facilisi. Suspendisse potenti.";
            jsonObject.put(key, value);
        }

        streamBridge.send("hello-out-0", jsonObject);
    }
```
This is a huge object and obviously will throw an exception. 
<img width="1115" alt="image" src="https://github.com/Azure/azure-sdk-for-java/assets/950278/b49d6df6-8a3b-4582-907c-1ad896ecb703">
The readiness probe is down and will only be up after a successful request. We are in a similar situation where the in K8s, the traffic is stopped to the POD when readiness probes returns DOWN.

In the Code, I see the instrumentation is added to every [producer](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/spring/spring-cloud-azure-stream-binder-servicebus/src/main/java/com/azure/spring/cloud/stream/binder/servicebus/ServiceBusMessageChannelBinder.java#L276-L278)
Seeing the [Tests](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/spring/spring-cloud-azure-stream-binder-servicebus/src/test/java/com/azure/spring/cloud/stream/binder/servicebus/ServiceBusMessageChannelTestBinder.java#L48), while its marked as DOWN, I was wondering if a successful subsequent request is the only way to bring it UP?

Checking with other binders like Kafka, Rabbit, they typically check only connection, and recovers automatically, once the connection is back up.

**Comment by Netyyyy** [comment]
Hi @dhananjay12 ,
Thank you for reporting this issue. It seems like a new feature for K8s. We will take it into consideration. 
We appreciate your input and will review this matter as soon as possible. Please feel free to provide any additional information or context that you think may be helpful. We'll keep you updated on the progress of our review.
Thank you for your contribution to improving our project.

**Comment by dhananjay12** [comment]
Hey @Netyyyy 
While the issue (readiness endpoint not recovering automatically) can be seen without the need to deploy on K8s, you can build the image locally following the readme in the [repo](https://github.com/dhananjay12/learn-azure/tree/main/scs-service-bus).
You can apply the K8s folder on your local cluster. 
![image](https://github.com/Azure/azure-sdk-for-java/assets/950278/b9d157fe-f341-44c0-af35-daeb933d3090)
Check the k8 endpoints- `kubectl get endpoints | grep scs-service-bus`

<img width="631" alt="image" src="https://github.com/Azure/azure-sdk-for-java/assets/950278/4ad5d578-192e-40e5-b0a6-86530a3f63d8">

Hit - http://localhost:8080/test which is prgrammed to send a large object. In the logs you will see the exception which is fine, the important thing here that after 15/20 sec the readiness probe will be return DOWN which will will look something like this

![image](https://github.com/Azure/azure-sdk-for-java/assets/950278/e5ee31ce-3cd8-4e07-9af6-80ef5e2a724f)

If you grep endpoints again - `kubectl get endpoints | grep scs-service-bus`

<img width="659" alt="image" src="https://github.com/Azure/azure-sdk-for-java/assets/950278/806090e2-102a-49df-93d4-e3c1d3aed1c2">

Locally it will not affect much, but in an cluster the pod is not available for traffic.

**Comment by awsule-cvs** [comment]
@anuchandy and @saragluna we are also experiencing a similar issue where we are noticing missing data when this issue is raised in our logs. We only see a subset of the data in Service bus and the first few are missing. Somehow it seems the spring cloud stream binder is sending data even before fully confirming the service bus connection. Here's a screenshot of our error below:

Is there a way we could enable advanced/verbose tracing on the library and get some help from you to investigate further?


<img width="1356" alt="Screen Shot 2024-01-29 at 9 49 26 AM" src="https://github.com/Azure/azure-sdk-for-java/assets/141431420/0df2fbe9-61ca-4853-b5a4-6fb643fd498b">

**Comment by saragluna** [comment]
@awsule-cvs but seems like this is a different issue?

**Comment by ahrytsiuk** [comment]
Hello. Please find below few scenarios when health status is not updated and recovered automatically:

#### Scenario 1
1. Start Service
2. Connection established. 
    * Actuator reports status `UP`
3. Drop connection (for example disconnect service from internet access)

Expected: Actuator reports status `DOWN`
Actual: Actuator reports status `UP`

#### Scenario 2
1. Start Service
2. Connection established. 
    * Actuator reports status `UP`
3. Drop connection (for example disconnect service from internet access)
4. Produce message
    * Actuator reports status `UP`

Expected: Actuator reports status `DOWN`
Actual: Actuator reports status `UP`


#### Scenario 3
1. Start Service
2. Connection established. 
    * Actuator reports status `UP`
3. Produce message
    * Actuator reports status `UP`
4. Drop connection (for example disconnect service from internet access)
5. Produce another message
    * This time message will not be sent
    * Eventually in ~3-4 minutes Actuator status will change to `DOWN`
6. Re-establish connection
    * Service successfully reconnects
    * Actuator reports status `DOWN`
    * Status will not be changed until application will produce next message

Expected: Actuator reports status `UP`
Actual: Actuator reports status `DOWN`

**Comment by joshfree** [comment]
Hi @ahrytsiuk please note that if you're reporting a separate issue that it would be easier to open a new github issue to track it.

Also please note that response times to GitHub issues are not guaranteed and if there is an immediate need to please follow the Azure support instructions below:

# Support

## How to file issues and get help  

### Azure support tickets

Customers with an [Azure support plan](https://azure.microsoft.com/support/options/) can open an [Azure support ticket](https://azure.microsoft.com/support/create-ticket/).
**We recommend this option if your problem requires immediate attention.**

### GitHub issues

We use [GitHub Issues](https://github.com/Azure/azure-sdk-for-java/issues/new/choose) to track bugs, questions, and feature requests.
GitHub issues are free, but **response time is not guaranteed.** See [GitHub issues support process](https://devblogs.microsoft.com/azure-sdk/github-issue-support-process/) for more details.

**Comment by anuchandy** [comment]
Regarding the Azure Spring Binder / Actuator, let's wait for the Spring team to get back, and review the scenarios listed.

Meantime, I can provide some background details / history in the context of messaging libraries. The messaging libraries - Event Hubs, Service Bus - across languages do not expose the internal state of connections (i.e., to external applications or Spring Binder). It involves more than _just_ a single TCP connection to the broker; but consist of nested child connections (sessions, send-receive, authentication links – let's call it AMQP connections), each undergoing state changes both independently and concurrently.

The library implements a state machine that monitors these states at various levels, managing the teardown and recovery of whole or subsets of AMQP connections. There are higher-level abstractions, such as Processor, built on this state machine to simplify key use cases. Even if the library were to expose these internal connections states, it would be challenging for the library consumers to make decisions based on a snapshot of the states, given their dynamic nature and interdependence (e.g., parent-child relationships). There may be many such nested AMQP connections, each changing states throughout the client's lifecycle.

Additionally, health-check means different things to different people. For example, if the Processor is not delivering messages - it could be that there are no messages flowing to the queue/topic or could be that other Processors running in other replica are consuming messages or could be resource / network constrain on a specific host, making one or few other instances look like not processing messages or falling behind.

The cross-language feature team brain-stormed this in the past and a useful common library feature that fits all definitions of health check is not defined yet. But I want to share that, the libraries emit OTEL metrics, which could be useful, that for example can send over the Application insight. This enables combining monitoring info with knowledge of business use cases, and runtime information (via admin clients), letting people build what is right for their scenario / for their definition of health-check.

For a basic check of host and broker connectivity, it can be background recurring task runs every 5 minutes trying to either resolve the DNS name of the namespace  (e.g., using ` java.net.InetAddress.getByName`) or have a sender-client attempt to create a batch with a 30-second timeout (`ServiceBusSenderClient::createMessageBatch().timeout(Duration.ofSeconds(30))`) and observing the exception. I’m unsure how much this helps but just sharing it.

In the meantime, let's wait for the feedback from the Spring team regarding the questions around built-in health check. However, I wanted to provide some context around messaging libraries and library's metric emission.

\\cc @jsquire

**Comment by anuchandy** [comment]
Regarding the Azure Spring Binder / Actuator, let's wait for the Spring team to get back, and review the scenarios listed.

Meantime, I can provide some background details / history in the context of messaging libraries. The messaging libraries - Event Hubs, Service Bus - across languages do not expose the internal state of connections (i.e., to external applications or Spring Binder). It involves more than _just_ a single TCP connection to the broker; but consist of nested child connections (sessions, send-receive, authentication links – let's call it AMQP connections), each undergoing state changes both independently and concurrently.

The library implements a state machine that monitors these states at various levels, managing the teardown and recovery of whole or subsets of AMQP connections. There are higher-level abstractions, such as Processor, built on this state machine to simplify key use cases. Even if the library were to expose these internal connections states, it would be challenging for the library consumers to make decisions based on a snapshot of the states, given their dynamic nature and interdependence (e.g., parent-child relationships). There may be many such nested AMQP connections, each changing states throughout the client's lifecycle.

Additionally, health-check means different things to different people. For example, if the Processor is not delivering messages - it could be that there are no messages flowing to the queue/topic or could be that other Processors running in other replica are consuming messages or could be resource / network constrain on a specific host, making one or few other instances look like not processing messages or falling behind.

The cross-language feature team brain-stormed this in the past and a useful common library feature that fits all definitions of health check is not defined yet. But I want to share that, the libraries emit OTEL metrics, which could be useful, that for example can send over to Application insight. This enables combining library emitted metric with business metric and runtime information (via [Admin APIs](https://learn.microsoft.com/en-us/java/api/com.azure.messaging.servicebus.administration.servicebusadministrationclient?view=azure-java-stable), letting people build what is right for their scenario (e.g. watchers) / for their definition of health-check.

For a basic check of host and broker connectivity, it can be background recurring task runs every 5 minutes trying to either resolve the DNS name of the namespace  (e.g., using ` java.net.InetAddress.getByName`) or have a sender-client attempt to create a batch with a 30-second timeout (`ServiceBusSenderClient::createMessageBatch().timeout(Duration.ofSeconds(30))`) and observing the exception. I’m unsure how much this helps (because as you already noted library reconnects internally) but still want to share.

In the meantime, let's wait for the feedback from the Spring team regarding the questions around built-in health check.  It is likely that binder is using the service APIs in the library to make calls and trying to map outcome (call succeeded, failed) to Spring health signals. However, I wanted to provide some history and our learning around this topic and explain that there is no single definition for "health check" and differs based on use cases.

\\cc @jsquire

**Comment by saragluna** [comment]
Thanks @anuchandy for your detailed explanation. In my understanding, the `health-check` means that the connectivity to the server is not broken. So we could switch our checking logic to using the OTEL metrics instead.
