### ISSUE TITLE
[BUG] : The OpenAI library does not work in a WebFlux environment because it internally blocks processing

### ISSUE THREAD

**Issue by yoshioterada** [Azure/azure-sdk-for-java#35301]
**Describe the bug**

I am currently implementing a program using Server Sent Events on WebFlux. The program sends the text received from the web client to OpenAI in Stream mode and returns the received text to the web client as a Server Sent Event. 

The code sends the string received from the web client to OpenAI in Stream mode and then calls 
`EmitResult result = userSink.tryEmitNext(content);` to return the received string as an SSE. 
When I run this program, I encounter the error mentioned below stack trace section.

As mentioned in the error message, the issue is occurring due to the use of the block() operation.

```text
"block()/blockFirst()/blockLast() are blocking, which is not supported 
in thread reactor-http-kqueue-5","tryCount":3}
```

Upon actually examining the stack trace and source code, I found that the following part was at line 757.

https://github.com/Azure/azure-sdk-for-java/blob/f85f067fabbda7b5f165c45f64c3721fcfbb7350/sdk/openai/azure-ai-openai/src/main/java/com/azure/ai/openai/implementation/OpenAIClientImpl.java#L753-L765

And I noticed that the above method 'getChatCompletionsWithResponse' was sync blocking code. 
And it should be invoked following method `getChatCompletionsWithResponseAsync`.

https://github.com/Azure/azure-sdk-for-java/blob/f85f067fabbda7b5f165c45f64c3721fcfbb7350/sdk/openai/azure-ai-openai/src/main/java/com/azure/ai/openai/implementation/OpenAIClientImpl.java#L666-L680

Therefore, I checked the caller of this method. As a result, I found that it was called from the following method in `OpenAIClient.java`. 

https://github.com/Azure/azure-sdk-for-java/blob/f85f067fabbda7b5f165c45f64c3721fcfbb7350/sdk/openai/azure-ai-openai/src/main/java/com/azure/ai/openai/OpenAIClient.java#L403-L416

So if I modify the above method, it should be invoke the `getChatCompletionsWithResponseAsync` method instead of the following `getChatCompletionsWithResponse` method.

https://github.com/Azure/azure-sdk-for-java/blob/f85f067fabbda7b5f165c45f64c3721fcfbb7350/sdk/openai/azure-ai-openai/src/main/java/com/azure/ai/openai/OpenAIClient.java#L170-L176

However, there was no such `getChatCompletionsWithResponseAsync` method in the `OpenAIClient.java`.

***Exception or Stack Trace***

```text
2023-06-05T19:20:04.100+09:00 ERROR 9357 --- [r-http-kqueue-5] c.a.c.http.netty.NettyAsyncHttpClient    : block()/blockFirst()/blockLast() are blocking, which is not supported in thread reactor-http-kqueue-5
2023-06-05T19:20:04.907+09:00 ERROR 9357 --- [r-http-kqueue-5] c.a.c.http.netty.NettyAsyncHttpClient    : block()/blockFirst()/blockLast() are blocking, which is not supported in thread reactor-http-kqueue-5
2023-06-05T19:20:06.512+09:00 ERROR 9357 --- [r-http-kqueue-5] c.a.c.http.netty.NettyAsyncHttpClient    : block()/blockFirst()/blockLast() are blocking, which is not supported in thread reactor-http-kqueue-5
2023-06-05T19:20:09.603+09:00 ERROR 9357 --- [r-http-kqueue-5] c.a.c.http.netty.NettyAsyncHttpClient    : block()/blockFirst()/blockLast() are blocking, which is not supported in thread reactor-http-kqueue-5
2023-06-05T19:20:09.603+09:00 ERROR 9357 --- [r-http-kqueue-5] com.azure.core.http.policy.RetryPolicy   : {"az.sdk.message":"Retry attempts have been exhausted.","exception":"block()/blockFirst()/blockLast() are blocking, which is not supported in thread reactor-http-kqueue-5","tryCount":3}
2023-06-05T19:20:09.604+09:00 ERROR 9357 --- [r-http-kqueue-5] com.azure.core.http.policy.RetryPolicy   : block()/blockFirst()/blockLast() are blocking, which is not supported in thread reactor-http-kqueue-5
2023-06-05T19:20:09.604+09:00 ERROR 9357 --- [r-http-kqueue-5] c.a.c.i.http.rest.RestProxyBase          : block()/blockFirst()/blockLast() are blocking, which is not supported in thread reactor-http-kqueue-5
2023-06-05T19:20:09.608+09:00 ERROR 9357 --- [r-http-kqueue-5] a.w.r.e.AbstractErrorWebExceptionHandler : [5679cd03-5]  500 Server Error for HTTP POST "/openai-gpt4-sse-submit?userId=34e16dc1-afd0-4ed5-a101-04b1101d6e2a"

java.lang.IllegalStateException: block()/blockFirst()/blockLast() are blocking, which is not supported in thread reactor-http-kqueue-5
        at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:83) ~[reactor-core-3.5.6.jar:3.5.6]
        Suppressed: java.lang.IllegalStateException: block()/blockFirst()/blockLast() are blocking, which is not supported in thread reactor-http-kqueue-5
                at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:83) ~[reactor-core-3.5.6.jar:3.5.6]
                at reactor.core.publisher.Mono.block(Mono.java:1710) ~[reactor-core-3.5.6.jar:3.5.6]
                at com.azure.core.http.netty.NettyAsyncHttpClient.sendSync(NettyAsyncHttpClient.java:152) ~[azure-core-http-netty-1.13.3.jar:1.13.3]
                at com.azure.core.http.HttpPipelineNextSyncPolicy.processSync(HttpPipelineNextSyncPolicy.java:38) ~[azure-core-1.39.0.jar:1.39.0]
                at com.azure.core.http.policy.HttpLoggingPolicy.processSync(HttpLoggingPolicy.java:142) ~[azure-core-1.39.0.jar:1.39.0]
                at com.azure.core.http.HttpPipelineNextSyncPolicy.processSync(HttpPipelineNextSyncPolicy.java:41) ~[azure-core-1.39.0.jar:1.39.0]
                at com.azure.core.implementation.http.policy.InstrumentationPolicy.processSync(InstrumentationPolicy.java:75) ~[azure-core-1.39.0.jar:1.39.0]
                at com.azure.core.http.HttpPipelineNextSyncPolicy.processSync(HttpPipelineNextSyncPolicy.java:41) ~[azure-core-1.39.0.jar:1.39.0]
                at com.azure.core.http.policy.HttpPipelineSyncPolicy.processSync(HttpPipelineSyncPolicy.java:42) ~[azure-core-1.39.0.jar:1.39.0]
                at com.azure.core.http.policy.AzureKeyCredentialPolicy.processSync(AzureKeyCredentialPolicy.java:67) ~[azure-core-1.39.0.jar:1.39.0]
                at com.azure.core.http.HttpPipelineNextSyncPolicy.processSync(HttpPipelineNextSyncPolicy.java:41) ~[azure-core-1.39.0.jar:1.39.0]
                at com.azure.core.http.policy.CookiePolicy.processSync(CookiePolicy.java:50) ~[azure-core-1.39.0.jar:1.39.0]
                at com.azure.core.http.HttpPipelineNextSyncPolicy.processSync(HttpPipelineNextSyncPolicy.java:41) ~[azure-core-1.39.0.jar:1.39.0]
                at com.azure.core.http.policy.AddDatePolicy.processSync(AddDatePolicy.java:45) ~[azure-core-1.39.0.jar:1.39.0]
                at com.azure.core.http.HttpPipelineNextSyncPolicy.processSync(HttpPipelineNextSyncPolicy.java:41) ~[azure-core-1.39.0.jar:1.39.0]
                at com.azure.core.http.policy.RetryPolicy.attemptSync(RetryPolicy.java:177) ~[azure-core-1.39.0.jar:1.39.0]
                at com.azure.core.http.policy.RetryPolicy.processSync(RetryPolicy.java:127) ~[azure-core-1.39.0.jar:1.39.0]
                at com.azure.core.http.HttpPipelineNextSyncPolicy.processSync(HttpPipelineNextSyncPolicy.java:41) ~[azure-core-1.39.0.jar:1.39.0]
                at com.azure.core.http.policy.AddHeadersFromContextPolicy.processSync(AddHeadersFromContextPolicy.java:60) ~[azure-core-1.39.0.jar:1.39.0]
                at com.azure.core.http.HttpPipelineNextSyncPolicy.processSync(HttpPipelineNextSyncPolicy.java:41) ~[azure-core-1.39.0.jar:1.39.0]
                at com.azure.core.http.policy.HttpPipelineSyncPolicy.processSync(HttpPipelineSyncPolicy.java:42) ~[azure-core-1.39.0.jar:1.39.0]
                at com.azure.core.http.policy.RequestIdPolicy.processSync(RequestIdPolicy.java:69) ~[azure-core-1.39.0.jar:1.39.0]
                at com.azure.core.http.HttpPipelineNextSyncPolicy.processSync(HttpPipelineNextSyncPolicy.java:41) ~[azure-core-1.39.0.jar:1.39.0]
                at com.azure.core.http.policy.HttpPipelineSyncPolicy.processSync(HttpPipelineSyncPolicy.java:42) ~[azure-core-1.39.0.jar:1.39.0]
                at com.azure.core.http.policy.UserAgentPolicy.processSync(UserAgentPolicy.java:153) ~[azure-core-1.39.0.jar:1.39.0]
                at com.azure.core.http.HttpPipelineNextSyncPolicy.processSync(HttpPipelineNextSyncPolicy.java:41) ~[azure-core-1.39.0.jar:1.39.0]
                at com.azure.core.http.HttpPipeline.sendSync(HttpPipeline.java:131) ~[azure-core-1.39.0.jar:1.39.0]
                at com.azure.core.implementation.http.rest.SyncRestProxy.send(SyncRestProxy.java:54) ~[azure-core-1.39.0.jar:1.39.0]
                at com.azure.core.implementation.http.rest.SyncRestProxy.invoke(SyncRestProxy.java:75) ~[azure-core-1.39.0.jar:1.39.0]
                at com.azure.core.implementation.http.rest.RestProxyBase.invoke(RestProxyBase.java:109) ~[azure-core-1.39.0.jar:1.39.0]
                at com.azure.core.http.rest.RestProxy.invoke(RestProxy.java:91) ~[azure-core-1.39.0.jar:1.39.0]
                at jdk.proxy2/jdk.proxy2.$Proxy52.getChatCompletionsSync(Unknown Source) ~[na:na]
                at com.azure.ai.openai.implementation.OpenAIClientImpl.getChatCompletionsWithResponse(OpenAIClientImpl.java:757) ~[azure-ai-openai-1.0.0-beta.1.jar:1.0.0-beta.1]
                at com.azure.ai.openai.OpenAIClient.getChatCompletionsWithResponse(OpenAIClient.java:255) ~[azure-ai-openai-1.0.0-beta.1.jar:1.0.0-beta.1]
                at com.azure.ai.openai.OpenAIClient.getChatCompletionsStream(OpenAIClient.java:409) ~[azure-ai-openai-1.0.0-beta.1.jar:1.0.0-beta.1]
                at com.yoshio3.SSEOpenAIController.invokeStreamTest(SSEOpenAIController.java:106) ~[classes/:na]
                at com.yoshio3.SSEOpenAIController.openaiGpt4Sse(SSEOpenAIController.java:97) ~[classes/:na]
```

**To Reproduce**

Please use the attachment sample code.

***Code Snippet***

I write to add the code snippet as follows.
More detail, please see this [reproducible repository](https://github.com/yoshioterada/MS-OpenAI-Java-Lib-Sample).

```java
    @GetMapping(path = "/openai-gpt4-sse-stream", produces = MediaType.TEXT_EVENT_STREAM_VALUE)
    @ResponseBody
    public Flux<String> sseStream(@RequestParam UUID userId) {
        Sinks.Many<String> userSink = getUserSink(userId);
        if (userSink == null) {
            userSink = createUserSink(userId);
        }
        LOGGER.debug("USER ID IS ADDED: {}}", userId);
        return userSink.asFlux().delayElements(Duration.ofMillis(10));
    }

    @PostMapping("/openai-gpt4-sse-submit")
    @ResponseBody
    public void openaiGpt4Sse(@RequestBody String inputText, @RequestParam UUID userId) {
        LOGGER.debug(inputText);
        
        List<ChatMessage> chatMessages = createMessages(inputText);
        ChatCompletionsOptions options = new ChatCompletionsOptions(chatMessages);
        options.setStream(true);
        client.getChatCompletionsStream("gpt-4", options)
                .forEach(chatCompletions -> {
                    chatCompletions.getChoices().stream()
                            .map(ChatChoice::getDelta)
                            .map(ChatMessageDelta::getContent)
                            .filter(content -> content != null)
                            .forEach(content -> {   
                                System.out.println(content);
                                Sinks.Many<String> userSink = getUserSink(userId);
                                EmitResult result = userSink.tryEmitNext(content);   
                                showDetailErrorReasonForSSE(result, content, inputText);
                                try {
                                    TimeUnit.MILLISECONDS.sleep(20);
                                } catch (InterruptedException e) {
                                    e.printStackTrace();
                                }
                            });
                });
    }

```

**Expected behavior**

If we use the stream version, it will operate as the Non-Blocking.
As a result, it can run on WebFlux too.

**Screenshots**

![Terminal Console](https://live.staticflickr.com/65535/52953724235_51b3648b4e_b.jpg)

**Setup (please complete the following information):**

 - OS: [Mac OS Venus 13.4]
 - IDE: [VS Code for Java]
 - Library/Libraries: [com.azure.azure-ai-openai:1.0.0-beta.1]
 - Java version: [Microsoft-7209853 "17.0.6" 2023-01-17 LTS] 
 - App Server/Environment: [N/A]
 - Frameworks: [Spring Boot 3.1.0] 

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by mssfang** [comment]
Thank you @yoshioterada  for reporting this issue. 

We will investigate it and get back to you.

**Comment by srnagar** [comment]
@yoshioterada From the exception stacktrace, it seems like the code is using the synchronous client `OpenAIClient`. To use the async method, please try using the `OpenAIAsyncClient`.

```java
OpenAIAsyncClient client = new OpenAIClientBuilder()
            .endpoint(endpoint)
            .credential(new AzureKeyCredential(azureOpenaiKey))
            .buildAsyncClient(); // this creates the async client

client.getChatCompletionsStream(...); // this will call the async methods
```

### Stacktrace that shows the usage of sync client.
```
 at com.azure.ai.openai.implementation.OpenAIClientImpl.getChatCompletionsWithResponse(OpenAIClientImpl.java:757) ~[azure-ai-openai-1.0.0-beta.1.jar:1.0.0-beta.1]
at com.azure.ai.openai.OpenAIClient.getChatCompletionsWithResponse(OpenAIClient.java:255) ~[azure-ai-openai-1.0.0-beta.1.jar:1.0.0-beta.1]
at com.azure.ai.openai.OpenAIClient.getChatCompletionsStream(OpenAIClient.java:409) ~[azure-ai-openai-1.0.0-beta.1.jar:1.0.0-beta.1]
                
```
