### ISSUE TITLE
[BUG] Exception in thread "main" java.lang.NoSuchFieldError: MANAGED_HSM

### ISSUE THREAD

**Issue by maheshn99** [Azure/azure-sdk-for-java#35321]
**Describe the bug**
If I use the latest following artifact
<dependency>
<groupId>com.azure.resourcemanager</groupId>
<artifactId>azure-resourcemanager-resources</artifactId>
<version>2.27.0</version>
</dependency>, I get the following error: 

Exception in thread "main" java.lang.NoSuchFieldError: MANAGED_HSM
at com.azure.resourcemanager.resources.fluentcore.utils.PagedConverter$PagedIterableImpl.stream(PagedConverter.java:200)

The line of code that causes this is : 	List<String> subscriptionIds = azureResourceManager.subscriptions().list().stream()
				.map(sub -> sub.subscriptionId()).collect(Collectors.toList());

***Exception or Stack Trace***
 at com.azure.resourcemanager.resources.fluentcore.utils.ResourceManagerUtils.getDefaultScopeFromUrl(ResourceManagerUtils.java:185)
        at com.azure.resourcemanager.resources.fluentcore.utils.ResourceManagerUtils.getDefaultScopeFromRequest(ResourceManagerUtils.java:147)
        at com.azure.resourcemanager.resources.fluentcore.policy.AuthenticationPolicy.getScopes(AuthenticationPolicy.java:36)
        at com.azure.core.management.http.policy.ArmChallengeAuthenticationPolicy.lambda$authorizeRequest$0(ArmChallengeAuthenticationPolicy.java:55)
        at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44)
        at reactor.core.publisher.Mono.subscribe(Mono.java:4490)
        at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:263)
        at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51)
        at reactor.core.publisher.Mono.subscribe(Mono.java:4490)
        at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:200)
        at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53)
        at reactor.core.publisher.Mono.subscribe(Mono.java:4475)
        at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:203)
        at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53)
        at reactor.core.publisher.Mono.subscribe(Mono.java:4475)
        at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:200)
        at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53)
        at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
        at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
        at reactor.core.publisher.Mono.subscribe(Mono.java:4490)
        at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:203)
        at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53)
        at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
        at reactor.core.publisher.MonoDeferContextual.subscribe(MonoDeferContextual.java:55)
        at reactor.core.publisher.Flux.subscribe(Flux.java:8642)
        at reactor.core.publisher.Flux.blockLast(Flux.java:2760)
        at com.azure.core.util.paging.ContinuablePagedByIteratorBase.requestPage(ContinuablePagedByIteratorBase.java:102)
        at com.azure.core.util.paging.ContinuablePagedByItemIterable$ContinuablePagedByItemIterator.<init>(ContinuablePagedByItemIterable.java:75)
        at com.azure.core.util.paging.ContinuablePagedByItemIterable.iterator(ContinuablePagedByItemIterable.java:55)
        at java.base/java.lang.Iterable.spliterator(Iterable.java:101)
        at com.azure.core.util.paging.ContinuablePagedIterable.stream(ContinuablePagedIterable.java:85)
        at com.azure.resourcemanager.resources.fluentcore.utils.PagedConverter$PagedIterableImpl.stream(PagedConverter.java:200)

**To Reproduce**
Use the mentioned artifact

***Code Snippet***
List<String> subscriptionIds = azureResourceManager.subscriptions().list().stream()
				.map(sub -> sub.subscriptionId()).collect(Collectors.toList());

**Expected behavior**
List of subscription IDs should received without any exception being thrown

**Screenshots**
Not applicable

**Setup (please complete the following information):**
 - OS: Windows 10 Enterprise
 - IDE: IntelliJ
 - Library/Libraries: As mentioned
 - Java version: openjdk version "19.0.1" 2022-10-18
 - App Server/Environment:NA
 - Frameworks: NA

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X ] Bug Description Added
- [X] Repro Steps Added
- [ X] Setup information Added

**Comment by weidongxu-microsoft** [comment]
@maheshn99 

You can also refer to this for troubleshooting on dependencies
https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/resourcemanager#dependency-management

As mentioned by Alan, please make sure azure-core-management 1.11.0+ is used in dependency.

**Comment by maheshn99** [comment]
@weidongxu-microsoft  Thank you for the response. The error went away, after I used the azure-core-management 1.11.1 library.
