### ISSUE TITLE
when I try to use stream. I always got this error: com.fasterxml.jackson.databind.exc.MismatchedInputException: Missing required creator property 'usage' (index 3)

### ISSUE THREAD

**Issue by ZieglerHan** [Azure/azure-sdk-for-java#35322]
https://github.com/Azure/azure-sdk-for-java/blob/bb37892275404e8a3cac3d4e2c639cbc9b18b9f9/sdk/openai/azure-ai-openai/src/samples/java/com/azure/ai/openai/usage/GetChatCompletionsStreamSample.java#LL53C35-L53C35

```
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Missing required creator property 'usage' (index 3)
 at [Source: (String)"{"id":"chatcmpl-7ORI3zwlnUA9cgGa4bU1V1I5XoJO0","object":"chat.completion.chunk","created":1686059131,"model":"gpt-35-turbo","choices":[{"delta":{"role":"assistant"},"index":0,"finish_reason":null}]}"; line: 1, column: 198] (through reference chain: com.azure.ai.openai.models.ChatCompletions["usage"])
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1755)
	at com.fasterxml.jackson.databind.deser.impl.PropertyValueBuffer._findMissing(PropertyValueBuffer.java:192)
```

**Comment by mssfang** [comment]
@ZieglerHan 

This PR should already fixed the non-azure openai client. And it is already merged into the main branch. https://github.com/Azure/azure-sdk-for-java/pull/35336


You can try to build OpenAI SDK locally and use it.

**Comment by ZieglerHan** [comment]
> @ZieglerHan
> 
> This PR should fix the non-azure OpenAI client. And it is already merged into the main branch. #35336
> 
> You can try to build OpenAI SDK locally and use it.

Thank you！

**Comment by zizmax** [comment]
When will this fix be available via Maven?

**Comment by mssfang** [comment]
> When will this fix be available via Maven?

Hi @zizmax . We will release beta.2 which has the fix today, or not late than tomorrow.

Will update the release status here.

**Comment by mssfang** [comment]
https://repo1.maven.org/maven2/com/azure/azure-ai-openai/1.0.0-beta.2/

@zizmax Version 1.0.0-beta.2 released. Can you give a try and see if it solves your issue?

**Comment by zizmax** [comment]
Streaming works now, thank you!
