### ISSUE TITLE
java.lang.Exception: Cannot convert row into InternalRow and java.lang.ArithmeticException: long overflow

### ISSUE THREAD

**Issue by shwetaagrawal1** [Azure/azure-sdk-for-java#35465]
I upgraded my azure databricks spark cluster from 2.4 to 3.3.1 and post that I started using azure-cosmos-spark_3-3_2-12-4.18.2. I made the required code changes but I am getting below error after reading the data from cosmos db and when trying to perform query on the data:

Py4JJavaError                             Traceback (most recent call last)
File <command-4385743336184951>:1
----> 1 deltas = delta_processor.produce_delta_output(evaluated_rules_final_schema)

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/data_infra/common/io/deltas/delta_processor_base.py:82, in DeltaProcessorBase.produce_delta_output(self, latest_run, ignore_deleted_records)
     68 """
     69 This method will write deltas to a data feed.
     70 
   (...)
     78     The deltas that were written to the feed.
     79 """
     81 # Read existing data from the feed
---> 82 existing_data = self._read_existing_data()
     84 # Filter the existing data
     85 existing_data_filtered = self._filter_existing_data(existing_data)

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/data_infra/common/io/deltas/cosmos_db_delta_processor.py:126, in CosmosDbDeltaProcessor._read_existing_data(self)
    122 data = self.get_latest_version(data)
    124 # The execution plan, depending on how its executed, could result in reading the data multiple times. By persisting, we ensure subsequent reads will go
    125 # to disk instead of cosmos db which is much faster.
--> 126 return self.checkpoint_utility.checkpoint(data, self.spark)

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/eligibility/helpers/checkpointing/checkpoint_utility_base.py:39, in CheckpointUtilityBase.checkpoint(self, dataframe, spark)
     36 file_path = self.get_checkpoint_dir(uuid.uuid4())
     38 # Write the dataframe to this filepath.
---> 39 dataframe.write.parquet(path=file_path, mode="overwrite")
     41 # We want to keep track of the checkpoints written so we can clean them up after script execution ends.
     42 self.checkpoints.add(file_path)

File /databricks/spark/python/pyspark/instrumentation_utils.py:48, in _wrap_function.<locals>.wrapper(*args, **kwargs)
     46 start = time.perf_counter()
     47 try:
---> 48     res = func(*args, **kwargs)
     49     logger.log_success(
     50         module_name, class_name, function_name, time.perf_counter() - start, signature
     51     )
     52     return res

File /databricks/spark/python/pyspark/sql/readwriter.py:1656, in DataFrameWriter.parquet(self, path, mode, partitionBy, compression)
   1654     self.partitionBy(partitionBy)
   1655 self._set_opts(compression=compression)
-> 1656 self._jwrite.parquet(path)

File /databricks/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py:1322, in JavaMember.__call__(self, *args)
   1316 command = proto.CALL_COMMAND_NAME +\
   1317     self.command_header +\
   1318     args_command +\
   1319     proto.END_COMMAND_PART
   1321 answer = self.gateway_client.send_command(command)
-> 1322 return_value = get_return_value(
   1323     answer, self.gateway_client, self.target_id, self.name)
   1325 for temp_arg in temp_args:
   1326     if hasattr(temp_arg, "_detach"):

File /databricks/spark/python/pyspark/errors/exceptions/captured.py:162, in capture_sql_exception.<locals>.deco(*a, **kw)
    160 def deco(*a: Any, **kw: Any) -> Any:
    161     try:
--> 162         return f(*a, **kw)
    163     except Py4JJavaError as e:
    164         converted = convert_exception(e.java_exception)

File /databricks/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/protocol.py:326, in get_return_value(answer, gateway_client, target_id, name)
    324 value = OUTPUT_CONVERTER[type](answer[2:], gateway_client)
    325 if answer[1] == REFERENCE_TYPE:
--> 326     raise Py4JJavaError(
    327         "An error occurred while calling {0}{1}{2}.\n".
    328         format(target_id, ".", name), value)
    329 else:
    330     raise Py4JError(
    331         "An error occurred while calling {0}{1}{2}. Trace:\n{3}\n".
    332         format(target_id, ".", name, value))

Py4JJavaError: An error occurred while calling o2255.parquet.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 39 in stage 23466.0 failed 4 times, most recent failure: Lost task 39.11 in stage 23466.0 (TID 730911) (10.139.64.10 executor 82): java.lang.Exception: Cannot convert row into InternalRow
	at com.azure.cosmos.spark.CosmosRowConverter.fromRowToInternalRow(CosmosRowConverter.scala:86)
	at com.azure.cosmos.spark.ItemsPartitionReader.get(ItemsPartitionReader.scala:166)
	at com.azure.cosmos.spark.ItemsPartitionReader.get(ItemsPartitionReader.scala:24)
	at org.apache.spark.sql.execution.datasources.v2.PartitionIterator.next(DataSourceRDD.scala:135)
	at org.apache.spark.sql.execution.datasources.v2.MetricsRowIterator.next(DataSourceRDD.scala:172)
	at org.apache.spark.sql.execution.datasources.v2.MetricsRowIterator.next(DataSourceRDD.scala:169)
	at org.apache.spark.sql.execution.datasources.v2.DataSourceRDD$$anon$1.next(DataSourceRDD.scala:67)
	at org.apache.spark.InterruptibleIterator.next(InterruptibleIterator.scala:40)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:763)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:179)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
	at org.apache.spark.scheduler.ShuffleMapTask.$anonfun$runTask$3(ShuffleMapTask.scala:88)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.ShuffleMapTask.$anonfun$runTask$1(ShuffleMapTask.scala:88)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:60)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41)
	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:191)
	at org.apache.spark.scheduler.Task.doRunTask(Task.scala:181)
	at org.apache.spark.scheduler.Task.$anonfun$run$5(Task.scala:146)
	at com.databricks.unity.EmptyHandle$.runWithAndClose(UCSHandle.scala:125)
	at org.apache.spark.scheduler.Task.$anonfun$run$1(Task.scala:146)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$13(Executor.scala:908)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1717)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:911)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:761)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: org.apache.spark.SparkRuntimeException: Error while encoding: java.lang.ArithmeticException: long overflow
assertnotnull(staticinvoke(class org.apache.spark.unsafe.types.UTF8String, StringType, fromString, validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true]), 0, id), StringType, ObjectType(class java.lang.String)), true, false, true)) AS id#84789
assertnotnull(staticinvoke(class org.apache.spark.unsafe.types.UTF8String, StringType, fromString, validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true]), 1, ParticipantId), StringType, ObjectType(class java.lang.String)), true, false, true)) AS ParticipantId#84794
assertnotnull(staticinvoke(class org.apache.spark.unsafe.types.UTF8String, StringType, fromString, validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true]), 2, ParticipantIdType), StringType, ObjectType(class java.lang.String)), true, false, true)) AS ParticipantIdType#84796
assertnotnull(staticinvoke(class org.apache.spark.unsafe.types.UTF8String, StringType, fromString, validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true]), 3, EntityId), StringType, ObjectType(class java.lang.String)), true, false, true)) AS EntityId#84799
assertnotnull(staticinvoke(class org.apache.spark.unsafe.types.UTF8String, StringType, fromString, validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true]), 4, EntityIdType), StringType, ObjectType(class java.lang.String)), true, false, true)) AS EntityIdType#84800
if (assertnotnull(input[0, org.apache.spark.sql.Row, true]).isNullAt) null else staticinvoke(class org.apache.spark.unsafe.types.UTF8String, StringType, fromString, validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true]), 5, ProgramGuid), StringType, ObjectType(class java.lang.String)), true, false, true) AS ProgramGuid#84802
assertnotnull(mapobjects(lambdavariable(MapObject, ObjectType(class java.lang.Object), true, -1), if (isnull(validateexternaltype(lambdavariable(MapObject, ObjectType(class java.lang.Object), true, -1), StructField(StartDateTime,StringType,false), StructField(EndDateTime,StringType,false), StructField(IsEligible,BooleanType,false), StructField(ConfigSetId,StringType,false), StructField(EvaluationDetails,StringType,false), ObjectType(interface org.apache.spark.sql.Row)))) null else named_struct(StartDateTime, assertnotnull(staticinvoke(class org.apache.spark.unsafe.types.UTF8String, StringType, fromString, validateexternaltype(getexternalrowfield(validateexternaltype(lambdavariable(MapObject, ObjectType(class java.lang.Object), true, -1), StructField(StartDateTime,StringType,false), StructField(EndDateTime,StringType,false), StructField(IsEligible,BooleanType,false), StructField(ConfigSetId,StringType,false), StructField(EvaluationDetails,StringType,false), ObjectType(interface org.apache.spark.sql.Row)), 0, StartDateTime), StringType, ObjectType(class java.lang.String)), true, false, true)), EndDateTime, assertnotnull(staticinvoke(class org.apache.spark.unsafe.types.UTF8String, StringType, fromString, validateexternaltype(getexternalrowfield(validateexternaltype(lambdavariable(MapObject, ObjectType(class java.lang.Object), true, -1), StructField(StartDateTime,StringType,false), StructField(EndDateTime,StringType,false), StructField(IsEligible,BooleanType,false), StructField(ConfigSetId,StringType,false), StructField(EvaluationDetails,StringType,false), ObjectType(interface org.apache.spark.sql.Row)), 1, EndDateTime), StringType, ObjectType(class java.lang.String)), true, false, true)), IsEligible, assertnotnull(validateexternaltype(getexternalrowfield(validateexternaltype(lambdavariable(MapObject, ObjectType(class java.lang.Object), true, -1), StructField(StartDateTime,StringType,false), StructField(EndDateTime,StringType,false), StructField(IsEligible,BooleanType,false), StructField(ConfigSetId,StringType,false), StructField(EvaluationDetails,StringType,false), ObjectType(interface org.apache.spark.sql.Row)), 2, IsEligible), BooleanType, ObjectType(class java.lang.Boolean)).booleanValue), ConfigSetId, assertnotnull(staticinvoke(class org.apache.spark.unsafe.types.UTF8String, StringType, fromString, validateexternaltype(getexternalrowfield(validateexternaltype(lambdavariable(MapObject, ObjectType(class java.lang.Object), true, -1), StructField(StartDateTime,StringType,false), StructField(EndDateTime,StringType,false), StructField(IsEligible,BooleanType,false), StructField(ConfigSetId,StringType,false), StructField(EvaluationDetails,StringType,false), ObjectType(interface org.apache.spark.sql.Row)), 3, ConfigSetId), StringType, ObjectType(class java.lang.String)), true, false, true)), EvaluationDetails, assertnotnull(staticinvoke(class org.apache.spark.unsafe.types.UTF8String, StringType, fromString, validateexternaltype(getexternalrowfield(validateexternaltype(lambdavariable(MapObject, ObjectType(class java.lang.Object), true, -1), StructField(StartDateTime,StringType,false), StructField(EndDateTime,StringType,false), StructField(IsEligible,BooleanType,false), StructField(ConfigSetId,StringType,false), StructField(EvaluationDetails,StringType,false), ObjectType(interface org.apache.spark.sql.Row)), 4, EvaluationDetails), StringType, ObjectType(class java.lang.String)), true, false, true))), validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true]), 6, EvaluationPeriods), ArrayType(StructType(StructField(StartDateTime,StringType,false),StructField(EndDateTime,StringType,false),StructField(IsEligible,BooleanType,false),StructField(ConfigSetId,StringType,false),StructField(EvaluationDetails,StringType,false)),true), ObjectType(class java.lang.Object)), None)) AS EvaluationPeriods#84805
assertnotnull(CheckOverflow(staticinvoke(class org.apache.spark.sql.types.Decimal$, DecimalType(28,0), fromDecimal, validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true]), 7, Version), DecimalType(28,0), ObjectType(class java.lang.Object)), true, false, true), DecimalType(28,0))) AS Version#84807
if (assertnotnull(input[0, org.apache.spark.sql.Row, true]).isNullAt) null else staticinvoke(class org.apache.spark.unsafe.types.UTF8String, StringType, fromString, validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true]), 8, FlightConfigId), StringType, ObjectType(class java.lang.String)), true, false, true) AS FlightConfigId#84808
assertnotnull(staticinvoke(class org.apache.spark.sql.catalyst.util.DateTimeUtils$, TimestampType, fromJavaTimestamp, validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true]), 9, CreatedDateTime), TimestampType, ObjectType(class java.sql.Timestamp)), true, false, true)) AS CreatedDateTime#84809
assertnotnull(staticinvoke(class org.apache.spark.sql.catalyst.util.DateTimeUtils$, TimestampType, fromJavaTimestamp, validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true]), 10, ModifiedDateTime), TimestampType, ObjectType(class java.sql.Timestamp)), true, false, true)) AS ModifiedDateTime#84810
assertnotnull(validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true]), 11, IsDeleted), BooleanType, ObjectType(class java.lang.Boolean)).booleanValue) AS IsDeleted#84811.
	at org.apache.spark.sql.errors.QueryExecutionErrors$.expressionEncodingError(QueryExecutionErrors.scala:1735)
	at org.apache.spark.sql.catalyst.encoders.ExpressionEncoder$Serializer.apply(ExpressionEncoder.scala:232)
	at com.azure.cosmos.spark.CosmosRowConverter.fromRowToInternalRow(CosmosRowConverter.scala:80)
	... 36 more
Caused by: java.lang.ArithmeticException: long overflow
	at java.lang.Math.multiplyExact(Math.java:892)
	at org.apache.spark.sql.catalyst.util.DateTimeUtils$.millisToMicros(DateTimeUtils.scala:257)
	at org.apache.spark.sql.catalyst.util.DateTimeUtils$.fromJavaTimestampNoRebase(DateTimeUtils.scala:209)
	at org.apache.spark.sql.catalyst.util.DateTimeUtils$.fromJavaTimestamp(DateTimeUtils.scala:199)
	at org.apache.spark.sql.catalyst.util.DateTimeUtils.fromJavaTimestamp(DateTimeUtils.scala)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.writeFields_0_5$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.apply(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.apply(Unknown Source)
	at org.apache.spark.sql.catalyst.encoders.ExpressionEncoder$Serializer.apply(ExpressionEncoder.scala:229)
	... 37 more

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:3484)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:3416)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:3405)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:3405)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1453)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1453)
	at scala.Option.foreach(Option.scala:407)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1453)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:3704)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:3642)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:3630)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:51)
Caused by: java.lang.Exception: Cannot convert row into InternalRow
	at com.azure.cosmos.spark.CosmosRowConverter.fromRowToInternalRow(CosmosRowConverter.scala:86)
	at com.azure.cosmos.spark.ItemsPartitionReader.get(ItemsPartitionReader.scala:166)
	at com.azure.cosmos.spark.ItemsPartitionReader.get(ItemsPartitionReader.scala:24)
	at org.apache.spark.sql.execution.datasources.v2.PartitionIterator.next(DataSourceRDD.scala:135)
	at org.apache.spark.sql.execution.datasources.v2.MetricsRowIterator.next(DataSourceRDD.scala:172)
	at org.apache.spark.sql.execution.datasources.v2.MetricsRowIterator.next(DataSourceRDD.scala:169)
	at org.apache.spark.sql.execution.datasources.v2.DataSourceRDD$$anon$1.next(DataSourceRDD.scala:67)
	at org.apache.spark.InterruptibleIterator.next(InterruptibleIterator.scala:40)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:763)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:179)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
	at org.apache.spark.scheduler.ShuffleMapTask.$anonfun$runTask$3(ShuffleMapTask.scala:88)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.ShuffleMapTask.$anonfun$runTask$1(ShuffleMapTask.scala:88)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:60)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41)
	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:191)
	at org.apache.spark.scheduler.Task.doRunTask(Task.scala:181)
	at org.apache.spark.scheduler.Task.$anonfun$run$5(Task.scala:146)
	at com.databricks.unity.EmptyHandle$.runWithAndClose(UCSHandle.scala:125)
	at org.apache.spark.scheduler.Task.$anonfun$run$1(Task.scala:146)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$13(Executor.scala:908)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1717)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:911)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:761)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: org.apache.spark.SparkRuntimeException: Error while encoding: java.lang.ArithmeticException: long overflow
assertnotnull(staticinvoke(class org.apache.spark.unsafe.types.UTF8String, StringType, fromString, validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true]), 0, id), StringType, ObjectType(class java.lang.String)), true, false, true)) AS id#84789
assertnotnull(staticinvoke(class org.apache.spark.unsafe.types.UTF8String, StringType, fromString, validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true]), 1, ParticipantId), StringType, ObjectType(class java.lang.String)), true, false, true)) AS ParticipantId#84794
assertnotnull(staticinvoke(class org.apache.spark.unsafe.types.UTF8String, StringType, fromString, validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true]), 2, ParticipantIdType), StringType, ObjectType(class java.lang.String)), true, false, true)) AS ParticipantIdType#84796
assertnotnull(staticinvoke(class org.apache.spark.unsafe.types.UTF8String, StringType, fromString, validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true]), 3, EntityId), StringType, ObjectType(class java.lang.String)), true, false, true)) AS EntityId#84799
assertnotnull(staticinvoke(class org.apache.spark.unsafe.types.UTF8String, StringType, fromString, validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true]), 4, EntityIdType), StringType, ObjectType(class java.lang.String)), true, false, true)) AS EntityIdType#84800
if (assertnotnull(input[0, org.apache.spark.sql.Row, true]).isNullAt) null else staticinvoke(class org.apache.spark.unsafe.types.UTF8String, StringType, fromString, validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true]), 5, ProgramGuid), StringType, ObjectType(class java.lang.String)), true, false, true) AS ProgramGuid#84802
assertnotnull(mapobjects(lambdavariable(MapObject, ObjectType(class java.lang.Object), true, -1), if (isnull(validateexternaltype(lambdavariable(MapObject, ObjectType(class java.lang.Object), true, -1), StructField(StartDateTime,StringType,false), StructField(EndDateTime,StringType,false), StructField(IsEligible,BooleanType,false), StructField(ConfigSetId,StringType,false), StructField(EvaluationDetails,StringType,false), ObjectType(interface org.apache.spark.sql.Row)))) null else named_struct(StartDateTime, assertnotnull(staticinvoke(class org.apache.spark.unsafe.types.UTF8String, StringType, fromString, validateexternaltype(getexternalrowfield(validateexternaltype(lambdavariable(MapObject, ObjectType(class java.lang.Object), true, -1), StructField(StartDateTime,StringType,false), StructField(EndDateTime,StringType,false), StructField(IsEligible,BooleanType,false), StructField(ConfigSetId,StringType,false), StructField(EvaluationDetails,StringType,false), ObjectType(interface org.apache.spark.sql.Row)), 0, StartDateTime), StringType, ObjectType(class java.lang.String)), true, false, true)), EndDateTime, assertnotnull(staticinvoke(class org.apache.spark.unsafe.types.UTF8String, StringType, fromString, validateexternaltype(getexternalrowfield(validateexternaltype(lambdavariable(MapObject, ObjectType(class java.lang.Object), true, -1), StructField(StartDateTime,StringType,false), StructField(EndDateTime,StringType,false), StructField(IsEligible,BooleanType,false), StructField(ConfigSetId,StringType,false), StructField(EvaluationDetails,StringType,false), ObjectType(interface org.apache.spark.sql.Row)), 1, EndDateTime), StringType, ObjectType(class java.lang.String)), true, false, true)), IsEligible, assertnotnull(validateexternaltype(getexternalrowfield(validateexternaltype(lambdavariable(MapObject, ObjectType(class java.lang.Object), true, -1), StructField(StartDateTime,StringType,false), StructField(EndDateTime,StringType,false), StructField(IsEligible,BooleanType,false), StructField(ConfigSetId,StringType,false), StructField(EvaluationDetails,StringType,false), ObjectType(interface org.apache.spark.sql.Row)), 2, IsEligible), BooleanType, ObjectType(class java.lang.Boolean)).booleanValue), ConfigSetId, assertnotnull(staticinvoke(class org.apache.spark.unsafe.types.UTF8String, StringType, fromString, validateexternaltype(getexternalrowfield(validateexternaltype(lambdavariable(MapObject, ObjectType(class java.lang.Object), true, -1), StructField(StartDateTime,StringType,false), StructField(EndDateTime,StringType,false), StructField(IsEligible,BooleanType,false), StructField(ConfigSetId,StringType,false), StructField(EvaluationDetails,StringType,false), ObjectType(interface org.apache.spark.sql.Row)), 3, ConfigSetId), StringType, ObjectType(class java.lang.String)), true, false, true)), EvaluationDetails, assertnotnull(staticinvoke(class org.apache.spark.unsafe.types.UTF8String, StringType, fromString, validateexternaltype(getexternalrowfield(validateexternaltype(lambdavariable(MapObject, ObjectType(class java.lang.Object), true, -1), StructField(StartDateTime,StringType,false), StructField(EndDateTime,StringType,false), StructField(IsEligible,BooleanType,false), StructField(ConfigSetId,StringType,false), StructField(EvaluationDetails,StringType,false), ObjectType(interface org.apache.spark.sql.Row)), 4, EvaluationDetails), StringType, ObjectType(class java.lang.String)), true, false, true))), validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true]), 6, EvaluationPeriods), ArrayType(StructType(StructField(StartDateTime,StringType,false),StructField(EndDateTime,StringType,false),StructField(IsEligible,BooleanType,false),StructField(ConfigSetId,StringType,false),StructField(EvaluationDetails,StringType,false)),true), ObjectType(class java.lang.Object)), None)) AS EvaluationPeriods#84805
assertnotnull(CheckOverflow(staticinvoke(class org.apache.spark.sql.types.Decimal$, DecimalType(28,0), fromDecimal, validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true]), 7, Version), DecimalType(28,0), ObjectType(class java.lang.Object)), true, false, true), DecimalType(28,0))) AS Version#84807
if (assertnotnull(input[0, org.apache.spark.sql.Row, true]).isNullAt) null else staticinvoke(class org.apache.spark.unsafe.types.UTF8String, StringType, fromString, validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true]), 8, FlightConfigId), StringType, ObjectType(class java.lang.String)), true, false, true) AS FlightConfigId#84808
assertnotnull(staticinvoke(class org.apache.spark.sql.catalyst.util.DateTimeUtils$, TimestampType, fromJavaTimestamp, validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true]), 9, CreatedDateTime), TimestampType, ObjectType(class java.sql.Timestamp)), true, false, true)) AS CreatedDateTime#84809
assertnotnull(staticinvoke(class org.apache.spark.sql.catalyst.util.DateTimeUtils$, TimestampType, fromJavaTimestamp, validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true]), 10, ModifiedDateTime), TimestampType, ObjectType(class java.sql.Timestamp)), true, false, true)) AS ModifiedDateTime#84810
assertnotnull(validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true]), 11, IsDeleted), BooleanType, ObjectType(class java.lang.Boolean)).booleanValue) AS IsDeleted#84811.
	at org.apache.spark.sql.errors.QueryExecutionErrors$.expressionEncodingError(QueryExecutionErrors.scala:1735)
	at org.apache.spark.sql.catalyst.encoders.ExpressionEncoder$Serializer.apply(ExpressionEncoder.scala:232)
	at com.azure.cosmos.spark.CosmosRowConverter.fromRowToInternalRow(CosmosRowConverter.scala:80)
	... 36 more
Caused by: java.lang.ArithmeticException: long overflow
	at java.lang.Math.multiplyExact(Math.java:892)
	at org.apache.spark.sql.catalyst.util.DateTimeUtils$.millisToMicros(DateTimeUtils.scala:257)
	at org.apache.spark.sql.catalyst.util.DateTimeUtils$.fromJavaTimestampNoRebase(DateTimeUtils.scala:209)
	at org.apache.spark.sql.catalyst.util.DateTimeUtils$.fromJavaTimestamp(DateTimeUtils.scala:199)
	at org.apache.spark.sql.catalyst.util.DateTimeUtils.fromJavaTimestamp(DateTimeUtils.scala)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.writeFields_0_5$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.apply(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.apply(Unknown Source)
	at org.apache.spark.sql.catalyst.encoders.ExpressionEncoder$Serializer.apply(ExpressionEncoder.scala:229)

**Comment by TheovanKraay** [comment]
@shwetaagrawal1 we need **much** better information to investigate. The code sample you pasted includes line numbers and is not clear or readable, team cannot investigate based on the above. Closing this issue, please create a new issue and follow the instructions when creating the issue (i.e. steps to reproduce, code snippet, expected behaviour, screen shot, etc).
