### ISSUE TITLE
[BUG] NPE arising from use of FieldBuilder.build on immutable class

### ISSUE THREAD

**Issue by dsgrieve** [Azure/azure-sdk-for-java#35584]
**Describe the bug**
Using FieldBuilder on an immutable class results in a NullPointerException.   

***Exception or Stack Trace***
`
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "com.fasterxml.jackson.databind.introspect.TypeResolutionContext.resolveType(java.lang.reflect.Type)" because "this._typeContext" is null
	at com.fasterxml.jackson.databind.introspect.AnnotatedMethod.getType(AnnotatedMethod.java:76)
	at com.fasterxml.jackson.databind.introspect.DefaultAccessorNamingStrategy.findNameForIsGetter(DefaultAccessorNamingStrategy.java:80)
	at com.azure.core.serializer.json.jackson.implementation.JacksonDatabind212.removePrefix(JacksonDatabind212.java:37)
	at com.azure.core.serializer.json.jackson.implementation.MemberNameConverterImpl.removePrefix(MemberNameConverterImpl.java:130)
	at com.azure.core.serializer.json.jackson.implementation.MemberNameConverterImpl.convertMemberName(MemberNameConverterImpl.java:85)
	at com.azure.core.serializer.json.jackson.implementation.ObjectMapperShim.convertMemberName(ObjectMapperShim.java:392)
	at com.azure.core.serializer.json.jackson.JacksonJsonSerializer.convertMemberName(JacksonJsonSerializer.java:107)
	at com.azure.search.documents.implementation.util.FieldBuilder.buildSearchField(FieldBuilder.java:165)
	at com.azure.search.documents.implementation.util.FieldBuilder.lambda$build$0(FieldBuilder.java:132)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at com.azure.search.documents.implementation.util.FieldBuilder.build(FieldBuilder.java:134)
	at com.azure.search.documents.implementation.util.FieldBuilder.build(FieldBuilder.java:107)
	at Scratch.main(scratch.java:25)
`
**To Reproduce**
I ran this with azure-search-documents 11.6.0-beta.7 (built from source) and jackson-databind 2.15.1
`
class Reproducer {

    public static class Foo {
        @JsonProperty("Bar")
        private final String bar;

        @JsonCreator
        public Foo(@JsonProperty("Bar") String bar) {
            this.bar = bar;
        }

        @JsonGetter("Bar")
        public String getBar() {
            return bar;
        }
    }

    public static void main (String[] args)
    {
        FieldBuilder.build(Foo.class, null);
    }
`    
***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**
I expected FieldBuilder to find the annotated field

**Screenshots**

**Setup (please complete the following information):**
 - Java version: 11 and 17
 - Library/Libraries: com.azure:azure-search-documents:11.6.0-beta.7, com.fasterxml.jackson.core:jackson-databind:2.15.1

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by alzimmermsft** [comment]
Thanks for reporting this @dsgrieve. This is effectively the same issue as #35567 and is being fixed by https://github.com/Azure/azure-sdk-for-java/pull/35569
