### ISSUE TITLE
[BUG] TestUtils.getRecordFolder fails with GraalVM native

### ISSUE THREAD

**Issue by jeanbisutti** [Azure/azure-sdk-for-java#35616]
#35615 fix is used.

`TestUtils.getRecordFolder` always fails with a GraalVM native executable but with a different error:

```
Caused by: java.lang.IllegalArgumentException: URI scheme is not "file"
	at java.base@17.0.7/java.io.File.<init>(File.java:423) ~[native-tests.exe.exe:na]
	at com.azure.core.test.utils.TestUtils.getRecordFolder(TestUtils.java:107) ~[na:na]
```

I have created an issue on GraalVM side: https://github.com/oracle/graal/issues/6884

**Comment by trask** [comment]
@jeanbisutti is there any workaround that we could implement to avoid the graal bug in the meantime?

**Comment by jeanbisutti** [comment]
Close because the tests don't use TestUtils.getRecordFolder anymore.
