### ISSUE TITLE
[BUG] Key Vault access retries credential error that cannot ever succeed

### ISSUE THREAD

**Issue by wheezil** [Azure/azure-sdk-for-java#35668]
**Describe the bug**

This really isn't about AKV, rather it is about the credentials authentication that AKV calls implicitly.  If I attempt to use an invalid client ID, the error is logged immediately and it does not seem like the kind of thing that can ever succeed, no matter how long you retry, but then the client library retries for a while anyway.  

The problem for us is that this hangs during the AKV client call instead of throwing an error.  This leads to hung systems when we'd really like to just know about the misconfiguration and fix it.  Is is possible for the client to have better knowledge of which errors might succeed on retry and which never can?

Is it possible for us to install a filter into the retry chain to examine the exception ourselves and decide to retry or not?

***Exception or Stack Trace***

Eventually the exception is thrown.  But that's not the problem.  The problem is that it is not thrown immediately.

**To Reproduce**

Compile and run code snippet using Azure SDK BOM 1.2.13 maven dependency

***Code Snippet***

```
String azureUrl = "https://rpdmdev.vault.azure.net/";
String clientId = "12345678-1234-1234-1234-123456789012";// garbage
String clientSecret = "garbage";
String tenantId = "694677ec-2b39-48fa-8e56-0e9251535a38";
ClientSecretCredentialBuilder credBuilder = new ClientSecretCredentialBuilder();
TokenCredential credential = credBuilder.clientId(clientId).tenantId(tenantId).clientSecret(clientSecret).build();
var client = new SecretClientBuilder().vaultUrl(azureUrl).credential(credential).buildClient();
long start = System.currentTimeMillis();
try {
	client.setSecret("name", "value");
} catch (Exception ex) {
	ex.printStackTrace();
}
long end = System.currentTimeMillis();
System.out.println("ELAPSED=" + (end-start) + "ms");
```

**Expected behavior**

Since this cannot ever succeed, the client library should throw immediately.

Instead, this is logged very quickly, but the client enters a retry loop for 90 seconds, for what is obviously (to me anyway) something that cannot ever succeed.

```
2023-06-28T18:42:41.079 [ForkJoinPool.commonPool-worker-1] ConfidentialClientApplication.logException:155 ERROR - [Correlation ID: 88a44f83-54a2-4133-aee6-731648210c4d] Execution of class com.microsoft.aad.msal4j.AcquireTokenByClientCredentialSupplier failed. com.microsoft.aad.msal4j.MsalServiceException: AADSTS700016: Application with identifier '12345678-1234-1234-1234-123456789012' was not found in the directory 'rpdmdev-aad'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.
Trace ID: c326048f-5f74-4d3b-87d3-07e8541f5800
Correlation ID: 88a44f83-54a2-4133-aee6-731648210c4d
Timestamp: 2023-06-29 00:42:41Z
	at com.microsoft.aad.msal4j.MsalServiceExceptionFactory.fromHttpResponse(MsalServiceExceptionFactory.java:45)
	at com.microsoft.aad.msal4j.TokenRequestExecutor.createAuthenticationResultFromOauthHttpResponse(TokenRequestExecutor.java:111)
	at com.microsoft.aad.msal4j.TokenRequestExecutor.executeTokenRequest(TokenRequestExecutor.java:34)
	at com.microsoft.aad.msal4j.AbstractClientApplicationBase.acquireTokenCommon(AbstractClientApplicationBase.java:129)
	at com.microsoft.aad.msal4j.AcquireTokenByAuthorizationGrantSupplier.execute(AcquireTokenByAuthorizationGrantSupplier.java:63)
	at com.microsoft.aad.msal4j.AcquireTokenByClientCredentialSupplier.acquireTokenByClientCredential(AcquireTokenByClientCredentialSupplier.java:86)
	at com.microsoft.aad.msal4j.AcquireTokenByClientCredentialSupplier.execute(AcquireTokenByClientCredentialSupplier.java:49)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:69)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:18)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
2023-06-28T18:42:41.083 [ForkJoinPool.commonPool-worker-1] ClientSecretCredential.performDeferredLogging:553 ERROR - Azure Identity => ERROR in getToken() call for scopes [https://vault.azure.net/.default]: AADSTS700016: Application with identifier '12345678-1234-1234-1234-123456789012' was not found in the directory 'rpdmdev-aad'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.Trace ID: c326048f-5f74-4d3b-87d3-07e8541f5800Correlation ID: 88a44f83-54a2-4133-aee6-731648210c4dTimestamp: 2023-06-29 00:42:41Z
2023-06-28T18:42:41.084 [ForkJoinPool.commonPool-worker-1] AccessTokenCache.performLogging:365 ERROR - {"az.sdk.message":"Failed to acquire a new access token.","exception":"AADSTS700016: Application with identifier '12345678-1234-1234-1234-123456789012' was not found in the directory 'rpdmdev-aad'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.\r\nTrace ID: c326048f-5f74-4d3b-87d3-07e8541f5800\r\nCorrelation ID: 88a44f83-54a2-4133-aee6-731648210c4d\r\nTimestamp: 2023-06-29 00:42:41Z"}
```

**Screenshots**

**Setup (please complete the following information):**
 - OS: Windows 10 x64
 - IDE: IntelliJ
 - Library/Libraries: ADK BOM 1.2.13
 - Java version: OpenJDK17
 - App Server/Environment: 
 - Frameworks: 

**Additional context**

**Information Checklist**
- [ X] Bug Description Added
- [ X] Repro Steps Added
- [ X] Setup information Added

**Comment by grepory** [comment]
@g2vinay Any update here? This could be handled in a couple of ways, I think:

You could intercept 401s here:

https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/core/azure-core/src/main/java/com/azure/core/http/policy/RetryStrategy.java#L43-L50

Or, instead of retrying on _any_ exception here:

https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/core/azure-core/src/main/java/com/azure/core/http/policy/RetryStrategy.java#L59-L61

You could return false if it's an `MsalServiceException`.

Yeah?

**Comment by grepory** [comment]
I created my own RetryPolicy with a modified ExponentialBackoff that short-circuits on MsalServiceException. It has to be handled `shouldRetryException` with something like this:

```
    @Override
    public boolean shouldRetryException(Throwable throwable) {
        if (throwable instanceof MsalServiceException) {
            return false;
        }
        return throwable instanceof Exception;
    }
```

I've basically copied ExponentialBackoff.java and modified it and then I'm instantiating clients using that strategy, @wheezil. E.g.

```
AzureResourceManager.configure()
                .withRetryPolicy(new RetryPolicy(new ExponentialBackoff()))
                .authenticate(tokenCredential, profile)
                .withDefaultSubscription();
```

**Comment by wheezil** [comment]
@grepory is it possible to subclass ExponentialBackoff or do you have to write a new one?

**Comment by grepory** [comment]
I think this is still worth resolving in the SDK.

**Comment by g2vinay** [comment]
Looking into this, passing in the custom Exponential Backoff class is the better approach as mentioned above.

As, at SDK level the azure-core SDK isn't aware of exceptions thrown by dependencies/libraries downstream.
Handling custom exceptions from other libraries in azure-core will require it to take dependency on external libraries and it will be against its design.

Resolving this issue.
