### ISSUE TITLE
[BUG] Cannot use azure-ai-openai with Android

### ISSUE THREAD

**Issue by leejay001** [Azure/azure-sdk-for-java#35719]
**Describe the bug**
java.lang.ExceptionInInitializerError in Android studio
I wanna run azure openai sdk at Android, but when I created OpenAIClient, app broke down bacause of ReflectionUtils.

***Exception or Stack Trace***
java.lang.ExceptionInInitializerError
        at com.azure.core.implementation.ReflectionUtils.getLookupToUse(ReflectionUtils.java:119)
        at com.azure.core.util.ExpandableStringEnum.getDefaultConstructor(ExpandableStringEnum.java:88)
        at com.azure.core.util.ExpandableStringEnum.$r8$lambda$SMtq8BJfA6t_qJk1WfhslLPTCwc(ExpandableStringEnum.java:0)
        at com.azure.core.util.ExpandableStringEnum$$ExternalSyntheticLambda1.apply(R8$$SyntheticClass:0)
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1716)
        at com.azure.core.util.ExpandableStringEnum.fromString(ExpandableStringEnum.java:68)
        at com.azure.core.http.HttpHeaderName.fromString(HttpHeaderName.java:60)
        at com.azure.core.http.HttpHeaderName.<clinit>(HttpHeaderName.java:88)
        at com.azure.core.http.HttpHeaderName.fromString(HttpHeaderName.java:56)
        at com.azure.core.http.policy.RequestIdPolicy.<clinit>(RequestIdPolicy.java:33)
        at com.azure.ai.openai.OpenAIClientBuilder.createHttpPipeline(OpenAIClientBuilder.java:279)
        at com.azure.ai.openai.OpenAIClientBuilder.buildInnerClient(OpenAIClientBuilder.java:259)
        at com.azure.ai.openai.OpenAIClientBuilder.buildClient(OpenAIClientBuilder.java:382)
        at com.lee.openai.azure.AzureOpenAIClientKt$azureOpenAIClient$2.invoke(AzureOpenAIClient.kt:27)
        at com.lee.openai.azure.AzureOpenAIClientKt$azureOpenAIClient$2.invoke(AzureOpenAIClient.kt:23)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at com.lee.openai.azure.AzureOpenAIClientKt.getAzureOpenAIClient(AzureOpenAIClient.kt:23)
        at com.lee.openai.azure.AzureOpenAIClientKt.flowText(AzureOpenAIClient.kt:31)
        at com.lee.ailanguage.MainActivity$testAzureOpenAI$1.invokeSuspend(MainActivity.kt:25)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at androidx.lifecycle.DispatchQueue.drainQueue(DispatchQueue.kt:74)
        at androidx.lifecycle.DispatchQueue.enqueue(DispatchQueue.kt:111)
        at androidx.lifecycle.DispatchQueue.dispatchAndEnqueue$lambda$2$lambda$1(DispatchQueue.kt:99)
        at androidx.lifecycle.DispatchQueue.$r8$lambda$1ME-FmJywCV2uxhp8ajM5a9C_oI(DispatchQueue.kt:0)
        at androidx.lifecycle.DispatchQueue$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:0)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:236)
        at android.app.ActivityThread.main(ActivityThread.java:8073)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@ce6128c, Dispatchers.Main.immediate]
    Caused by: java.lang.RuntimeException: Unable to use package-private MethodHandles.Lookup constructor.
        at com.azure.core.implementation.ReflectionUtils.<clinit>(ReflectionUtils.java:84)
        	... 33 more
     Caused by: java.lang.NoSuchMethodException: java.lang.invoke.MethodHandles$Lookup.<init> [class java.lang.Class]
        at java.lang.Class.getConstructor0(Class.java:2332)
        at java.lang.Class.getDeclaredConstructor(Class.java:2170)
        at com.azure.core.implementation.ReflectionUtils.<clinit>(ReflectionUtils.java:76)

**To Reproduce**
env:
Android studio version: Android Studio Electric Eel | 2022.1.1 Patch 
jvm: Runtime version: 11.0.16+8-b2043.64 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
implemente azure openai : com.azure:azure-ai-openai:1.0.0-beta.2

create any OpenAIClient and test, then break. 

***Code Snippet***
 OpenAIClientBuilder()
        .credential(AzureKeyCredential(AZURE_OPEN_AI_KEY))
        .endpoint(AZURE_OPEN_AI_ENDPOINT)
        .buildClient()
The killer is AzureKeyCredential.

**Expected behavior**
No break at least.

**Screenshots**

**Setup (please complete the following information):**
 - OS: Android
 - IDE: Android studio Electric Eel | 2022.1.1 Patch 
 - Library/Libraries:  com.azure:azure-ai-openai:1.0.0-beta.2；com.azure:azure-core:1.40.0
 - Java version: Android studio need Java11 ,but at Gradle I set both sourceCompatibility and targetCompatibility to java8
 - App Server/Environment: Nothing
 - Frameworks: Android 

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**
I followed https://github.com/Azure/azure-sdk-for-java/wiki/Android-Support to config Android projects
Android studio need at least java11, but I can tell ReflectionUtils.java is for java8.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by alzimmermsft** [comment]
Hi @leejay001, this issue is similar to #35756 where I mention that the Azure SDKs for Java aren't guaranteed to work with Android, nor do we offer support for them working with Android.

**Comment by georgeps22** [comment]
I was hitting this until I updated the API version to >= 26.  In my `build.gradle` my minSDK is 26 with `targetSdk` of 33. I had already enabled Java 8 desugaring with the `JavaVersion.VERSION_1_8` for `sourceCompatibility` and `targetCompatability`.

**Comment by alzimmermsft** [comment]
Thanks for the update @georgeps22.

Updating to API version 26 and above makes sense as it appears Android added support for `MethodHandle`, and other `java.lang.invoke` APIs, in API version 26.

https://developer.android.com/reference/java/lang/invoke/MethodHandle

**Comment by leejay001** [comment]
Thanks for the help, @georgeps22 and @alzimmermsft. However, I had already set the min SDK to 26, as indicated by Android Studio before this bug occurred. Additionally, I have enabled Java 8 desugaring using JavaVersion.VERSION_1_8 for sourceCompatibility and targetCompatibility. I suspect that the issue may be related to the Gradle build tools I used, which are:

gradle-7.5-bin.zip
id 'com.android.application' version '7.4.2' apply false
id 'com.android.library' version '7.4.2' apply false
id 'org.jetbrains.kotlin.android' version '1.8.0' apply false
id 'org.jetbrains.kotlin.jvm' version '1.8.0' apply false
These require Java 11 or above, but ReflectionUtils is only compatible with Java 8. I found this issue on GitHub: [https://github.com/Azure/azure-sdk-for-java/issues/29046 ] ,where @alzimmermsft mentioned that there was a Java 9+ version of ReflectionUtils, but it cannot be found currently.

**Comment by joshfree** [comment]
@JonathanGiles could you please assist here since you're working on Android right now and Alan is away

**Comment by snijsure** [comment]
@JonathanGiles -- I am facing the same issue - I am using java version 11, is there no hope of this to work azure-ai-openai SDK to work with Java 11?

**Comment by JonathanGiles** [comment]
> @JonathanGiles -- I am facing the same issue - I am using java version 11, is there no hope of this to work azure-ai-openai SDK to work with Java 11?

This issue relates to usage on Android, whereas your comment appears unrelated to Android. Can you please file a new issue if you're specifically running into issues when running this library on Java 11 (without Android), as this library absolutely should work under Java 11. If you are asking about Android support, then your question should probably be asked in the context of Android API levels. Our target is to have some degree of baseline support from Android API level 26.

**Comment by Dawid-Witkowski** [comment]
Hey, just hit the same error and unfortunately the solution provided by @georgeps22 didn't help, can we expect any changes regarding this issue in the coming weeks? 🙏

**Comment by alzimmermsft** [comment]
Android is not the primary target of the libraries in this repository. Whilst effort has been made to test against Android 26+ occasionally, this is not something we prioritize and cannot guarantee will work at all times. Closing this issue as won't fix.
