### ISSUE TITLE
[BUG] Not able to get management policy through ManagementPoliciesClient when port 443 is closed on machine.

### ISSUE THREAD

**Issue by gaurav-gupta409** [Azure/azure-sdk-for-java#35721]
**Description**
We are facing issue in getting management policy associated with the specified storage account even on specifying working web proxy.
We are using ManagementPoliciesClient class(part of StorageManagementClient) of azure SDK  to get the management policy associated with the specified storage account. Even though we are setting web proxy in HttpClient connection used by ManagementPoliciesClient for fetching management policy, it seems like SDK internally does not respect the web proxy and tries to connect with microsoft's servers using new httpClient without web proxy. So when port 443 is closed , we cannot connect to servers for microsoft to get management policies. Thats why we keep getting connection time out continuously.
We identified that SDK is trying to access the URL : http://login.microsoftonline.com/40.126.62.131:443, http://login.microsoftonline.com/20.190.151.134:443, etc. It tries to connect to login.microsoft.com around 3-4 times and we get connection time out each time.
Tentative issue in sdk - Request is not going through web proxy. 

***Exception or Stack Trace***
```
Execution of class com.microsoft.aad.msal4j.AcquireTokenSilentSupplier failed.
    com.microsoft.aad.msal4j.MsalClientException: java.io.UncheckedIOException: io.netty.channel.ConnectTimeoutException: connection timed out: login.microsoftonline.com/20.190.151.131:443
    at com.microsoft.aad.msal4j.HttpHelper.executeHttpRequest(HttpHelper.java:56) 
    at com.microsoft.aad.msal4j.AadInstanceDiscoveryProvider.executeRequest(AadInstanceDiscoveryProvider.java:286) 
    at com.microsoft.aad.msal4j.AadInstanceDiscoveryProvider.sendInstanceDiscoveryRequest(AadInstanceDiscoveryProvider.java:237) 
    at com.microsoft.aad.msal4j.AadInstanceDiscoveryProvider.doInstanceDiscoveryAndCache(AadInstanceDiscoveryProvider.java:347) 
    at com.microsoft.aad.msal4j.AadInstanceDiscoveryProvider.getMetadataEntry(AadInstanceDiscoveryProvider.java:90) 
    at com.microsoft.aad.msal4j.AuthenticationResultSupplier.getAuthorityWithPrefNetworkHost(AuthenticationResultSupplier.java:39) 
    at com.microsoft.aad.msal4j.AcquireTokenSilentSupplier.execute(AcquireTokenSilentSupplier.java:23) 
    at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:69) 
    at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:18) 
    at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604) [na:1.8.0_345]
    at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596) [na:1.8.0_345]
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [na:1.8.0_345]
    at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [na:1.8.0_345]
    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [na:1.8.0_345]
    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) [na:1.8.0_345]
    Caused by: java.io.UncheckedIOException: io.netty.channel.ConnectTimeoutException: connection timed out: login.microsoftonline.com/20.190.151.131:443
    at com.azure.core.http.netty.NettyAsyncHttpClient.sendSync(NettyAsyncHttpClient.java:158) 
    at com.azure.core.http.HttpPipelineNextSyncPolicy.processSync(HttpPipelineNextSyncPolicy.java:38) 
    at com.azure.core.http.policy.HttpLoggingPolicy.processSync(HttpLoggingPolicy.java:142) 
    at com.azure.core.http.HttpPipelineNextSyncPolicy.processSync(HttpPipelineNextSyncPolicy.java:41) 
    at com.azure.core.implementation.http.policy.InstrumentationPolicy.processSync(InstrumentationPolicy.java:75) 
    at com.azure.core.http.HttpPipelineNextSyncPolicy.processSync(HttpPipelineNextSyncPolicy.java:41) 
    at com.azure.core.http.policy.RetryPolicy.attemptSync(RetryPolicy.java:177) 
    at com.azure.core.http.policy.RetryPolicy.attemptSync(RetryPolicy.java:189) 
    at com.azure.core.http.policy.RetryPolicy.attemptSync(RetryPolicy.java:189) 
    at com.azure.core.http.policy.RetryPolicy.attemptSync(RetryPolicy.java:189) 
    at com.azure.core.http.policy.RetryPolicy.processSync(RetryPolicy.java:127) 
    at com.azure.core.http.HttpPipelineNextSyncPolicy.processSync(HttpPipelineNextSyncPolicy.java:41) 
    at com.azure.core.http.policy.HttpPipelineSyncPolicy.processSync(HttpPipelineSyncPolicy.java:42) 
    at com.azure.core.http.policy.UserAgentPolicy.processSync(UserAgentPolicy.java:153) 
    at com.azure.core.http.HttpPipelineNextSyncPolicy.processSync(HttpPipelineNextSyncPolicy.java:41) 
    at com.azure.core.http.HttpPipeline.sendSync(HttpPipeline.java:131) 
    at com.azure.identity.implementation.HttpPipelineAdapter.send(HttpPipelineAdapter.java:67) 
    at com.microsoft.aad.msal4j.HttpHelper.executeHttpRequestWithRetries(HttpHelper.java:99) 
    at com.microsoft.aad.msal4j.HttpHelper.executeHttpRequest(HttpHelper.java:52) 
	... 14 common frames omitted
    Suppressed: java.io.UncheckedIOException: io.netty.channel.ConnectTimeoutException: connection timed out: login.microsoftonline.com/40.126.62.131:443
    at com.azure.core.http.netty.NettyAsyncHttpClient.sendSync(NettyAsyncHttpClient.java:158) 
    at com.azure.core.http.HttpPipelineNextSyncPolicy.processSync(HttpPipelineNextSyncPolicy.java:38) 
    at com.azure.core.http.policy.HttpLoggingPolicy.processSync(HttpLoggingPolicy.java:142) 
    at com.azure.core.http.HttpPipelineNextSyncPolicy.processSync(HttpPipelineNextSyncPolicy.java:41) 
    at com.azure.core.implementation.http.policy.InstrumentationPolicy.processSync(InstrumentationPolicy.java:75) 
    at com.azure.core.http.HttpPipelineNextSyncPolicy.processSync(HttpPipelineNextSyncPolicy.java:41) 
    at com.azure.core.http.policy.RetryPolicy.attemptSync(RetryPolicy.java:177) 
		... 23 common frames omitted
    Caused by: io.netty.channel.ConnectTimeoutException: connection timed out: login.microsoftonline.com/40.126.62.131:443
    at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$2.run(AbstractEpollChannel.java:613)
    at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
    at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153)
    at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:406)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
```
		
**To Reproduce**
1. Close port 443 on machine.
2. create object of HttpClient by passing working web proxy in it.
3. create object of ManagementPoliciesClient and pass HttpClient in it.
4. send request to get management policy for specified storage account using get() method.

***Pseudo Code Snippet***
```
        ProxyOptions proxyOptions = new ProxyOptions(Type.HTTP, new InetSocketAddress(webProxy.host, webProxy.port));
        NettyAsyncHttpClientBuilder httpClientBuilder = new NettyAsyncHttpClientBuilder();
        HttpClient httpClient = httpClientBuilder.proxy(proxyOptions).build();
        HttpPipeline httpPipeline = HttpPipelineProvider.buildHttpPipeline(credential, profile, /*scopes*/ null, /*httpLogOptions*/ null, /*configuration*/ null, /*retryPolicy*/ null, /*additionalPolicies*/ null, httpClient);
        StorageManagementClientImpl storageManagementClient = new StorageManagementClientBuilder().subscriptionId(targetConfiguration.getSubscriptionId()).pipeline(httpPipeline).buildClient();
        ManagementPoliciesClient policyClient = storageManagementClient.getManagementPolicies();
        ManagementPolicyInner managementPolicyInner = policyClient.get(resourceGroup, storageAccount, ManagementPolicyName.DEFAULT);
```
We are getting Exception in line -- policyClient.get(resourceGroup, storageAccount, ManagementPolicyName.DEFAULT);

**Expected behavior**
Even though our machine is in private network with port 443 closed, but we are specifying web proxy in httpClient object. So request should go through web proxy and we should be able to get management policies for a storage account.

**Setup :**
 - OS: CentOS Linux
 - IDE: IntelliJ
 - Library/Libraries: azure-core-1.39.0, azure-storage-blob-12.10.1, azure-resourcemanager-storage-2.26.0
 - Java version: 8
 - App Server/Environment: Tomcat
 - Frameworks: Spring Boot

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [&#x2713;] Bug Description Added
- [&#x2713;] Repro Steps Added
- [&#x2713;] Setup information Added

**Comment by joshfree** [comment]
@alzimmermsft could you assist @gaurav-gupta409 with this question on Proxy settings?

**Comment by alzimmermsft** [comment]
Hi @gaurav-gupta409, thanks for filing this issue.

Based on the exception stack trace it appears the issue is that the `TokenCredential` retrieval isn't using the proxy as expected. Depending on the `TokenCredential` type it also uses an `HttpClient` and that doesn't default to the `HttpClient` provided to the Storage client as you've done in your sample code. For example, using `EnvironmentCredential`'s build it would be:

```java
TokenCredential tokenCredential = new EnvironmentCredentialBuilder()
    .httpClient(httpClientWithProxy)
    ... // Actual credential configurations here
    .build();
```

The Azure SDKs for Java also support loading proxy configurations from the environment, which could simplify code.

https://learn.microsoft.com/azure/developer/java/sdk/proxying

**Comment by gaurav-gupta409** [comment]
Hi @alzimmermsft, passing web proxy explicitly in TokenCredential works for us. Now request for acquiring access token is going through web proxy. Thanks for the help!
