### ISSUE TITLE
[BUG] Default Subscription even though set correctly being ignored by ARM API

### ISSUE THREAD

**Issue by maheshn99** [Azure/azure-sdk-for-java#35743]
**Describe the bug**
The following API fails : AzureResourceManager azureResourceManager = AzureResourceManager.configure().withHttpClient(client)
                .withLogLevel(HttpLogDetailLevel.BASIC).authenticate(credential, profile).withDefaultSubscription(); even if default subscription is set. 

***Exception or Stack Trace***
2023-07-05 14:48:54 ERROR ResourceManagerUtils - More than one subscription found in your tenant. Please specify which one below is desired for resource management.LHG_XXXXXXXXXXXXXX : 7XXXXXXXXXXXXXXXXXXXX
		   LHA_XXXXXXXXX : bXXXXXXXXXXXXXXXXXXXXXX
Exception in thread "main" java.lang.IllegalStateException: More than one subscription found in your tenant. Please specify which one below is desired for resource management
		at com.azure.resourcemanager.resources.fluentcore.utils.ResourceManagerUtils.getDefaultSubscription(ResourceManagerUtils.java:135)
        at com.azure.resourcemanager.AzureResourceManager$AuthenticatedImpl.withDefaultSubscription(AzureResourceManager.java:346)
        at com.example.AzureExplorer.main(AzureExplorer.java:42)

**To Reproduce**
1. Compile attached source code
2. Execute in Azure Cloud Shell when you login into Azure Portal with an user who has access to more than one subscriptions

***Code Snippet***
package com.example;

import com.azure.core.credential.TokenCredential;
import com.azure.core.http.HttpClient;
import com.azure.core.http.policy.HttpLogDetailLevel;
import com.azure.core.management.AzureEnvironment;
import com.azure.core.management.profile.AzureProfile;
import com.azure.identity.AzureCliCredentialBuilder;
import com.azure.resourcemanager.AzureResourceManager;

import java.util.Date;
import java.util.List;
import java.util.stream.Collectors;

public class AzureExplorer {

    public static void main( String[] args )
    {

        final AzureProfile profile = new AzureProfile(AzureEnvironment.AZURE);

        HttpClient client = HttpClient.createDefault();

        System.out.println(" Start of Execution at " + new Date());

        System.out.println(" Got Azure Profile AD endpoint " + profile.getEnvironment().getActiveDirectoryEndpoint());

        // Acquire token from Azure Active Directory endpoint based on the Azure CLI
        // Credentials
        // Refer :
        // https://learn.microsoft.com/en-us/java/api/overview/azure/identity-readme?view=azure-java-stable
        // final TokenCredential credential = new DefaultAzureCredentialBuilder().authorityHost(profile.getEnvironment().getActiveDirectoryEndpoint()).build();

        final TokenCredential credential = new AzureCliCredentialBuilder().build();

        AzureResourceManager azureResourceManager = AzureResourceManager.configure().withHttpClient(client)
                .withLogLevel(HttpLogDetailLevel.BASIC).authenticate(credential, profile).withDefaultSubscription();

        // Get the list of all subscriptions that are accessible
        List<String> subscriptionIds = azureResourceManager.subscriptions().list().stream()
                .map(sub -> sub.subscriptionId()).collect(Collectors.toList());

        // Print the list of subscription IDs
        System.out.println("Subscription IDs: " + subscriptionIds);

          }
}

**POM.XML**

<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>AzureUtilities</groupId>
    <artifactId>AzureUtils</artifactId>
    <version>0.0.2-SNAPSHOT</version>
    <properties>
        <maven.compiler.source>12</maven.compiler.source>
        <maven.compiler.target>12</maven.compiler.target>
    </properties>
    <dependencies>
        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-core</artifactId>
            <version>1.35.0</version>
        </dependency>
        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-storage-file-share</artifactId>
            <version>12.16.2</version>
        </dependency>
        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-core-management</artifactId>
            <version>1.11.1</version>
        </dependency>

        <dependency>
            <groupId>com.azure.resourcemanager</groupId>
            <artifactId>azure-resourcemanager</artifactId>
            <version>2.22.0</version>
        </dependency>
        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-identity</artifactId>
            <version>1.1.0</version>
        </dependency>

        <dependency>
            <groupId>com.azure.resourcemanager</groupId>
            <artifactId>azure-resourcemanager-resourcegraph</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>com.azure.resourcemanager</groupId>
            <artifactId>azure-resourcemanager-resources</artifactId>
            <version>2.27.0</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-api</artifactId>
            <version>2.13.3</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core</artifactId>
            <version>2.13.3</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-slf4j-impl</artifactId>
            <version>2.13.3</version>
        </dependency>

        <dependency>
            
            <groupId>com.microsoft.graph</groupId>
            <artifactId>microsoft-graph</artifactId>
            <version>5.61.0</version>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.13.0</version>
        </dependency>

    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.4.1</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <transformers>
                                <transformer
                                        implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                    <mainClass>com.example.AzureExplorer</mainClass>
                                </transformer>
                            </transformers>
                            <filters>
                                <filter>
                                    <artifact>*:*</artifact>
                                    <excludes>
                                        <exclude>META-INF/*.SF</exclude>
                                        <exclude>META-INF/*.DSA</exclude>
                                        <exclude>META-INF/*.RSA</exclude>
                                    </excludes>
                                </filter>
                            </filters>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>11</source>
                    <target>11</target>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>

**Expected behavior**
Since "az account list" command already shows "isDefault": true to one of the subscriptions that the logged in user has access to, the API should use that one as the default subscription instead of throwing the mentioned exception.

**Screenshots**

**Setup (please complete the following information):**
 - OS: [e.g. iOS] Linux cc-f738ba56-7884549d55-xbbgk 5.4.0-1109-azure #115~18.04.1-Ubuntu SMP Mon May 22 20:06:37 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
 - IDE:  IntelliJ
 - Library/Libraries: see pom.xml attached
 - Java version: JDK12
 - App Server/Environment: Azure Cloud Shell
 - Frameworks:

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by maheshn99** [comment]
Apparently, this is not a bug:

        /**
         * Selects the default subscription as the subscription for the APIs to work with.
         *
         * <p>The default subscription can be specified inside the Azure profile using {@link
         * AzureProfile}. If no default subscription provided, we will try to set the only
         * subscription if applicable returned by {@link Authenticated#subscriptions()}</p>
         *
         * @throws IllegalStateException when no subscription or more than one subscription found in the tenant.
         * @return an authenticated Azure client configured to work with the default subscription
         */
        AzureResourceManager withDefaultSubscription();

**Comment by maheshn99** [comment]
Well, even when the Azure Profile is set, still the same exception is being thrown.

**Comment by maheshn99** [comment]
This is not a bug. By setting the Azure Profile properly, it worked.
