### ISSUE TITLE
[BUG] Exception while instantiating TextTranslationClientBuilder() on Android Java

### ISSUE THREAD

**Issue by Sh-Singh** [Azure/azure-sdk-for-java#35756]
**Describe the bug**
Getting an exception while instantiating TextTranslationClientBuilder on Android Java client which crashes the app. Verfied that gradle and API version are same as what is being supported by SDK.

***Exception or Stack Trace***
    Process: com.microsoft.mobile.relay.dev1, PID: 2669
    java.lang.ExceptionInInitializerError
        at com.azure.core.implementation.ReflectionUtils.getLookupToUse(ReflectionUtils.java:119)
        at com.azure.core.util.ExpandableStringEnum.getDefaultConstructor(ExpandableStringEnum.java:88)
        at com.azure.core.util.ExpandableStringEnum.$r8$lambda$SMtq8BJfA6t_qJk1WfhslLPTCwc(Unknown Source:0)
        at com.azure.core.util.ExpandableStringEnum$$ExternalSyntheticLambda0.apply(Unknown Source:2)
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1710)
        at com.azure.core.util.ExpandableStringEnum.fromString(ExpandableStringEnum.java:68)
        at com.azure.core.http.HttpHeaderName.fromString(HttpHeaderName.java:60)
        at com.azure.core.http.HttpHeaderName.<clinit>(HttpHeaderName.java:88)
        at com.azure.core.http.HttpHeaderName.fromString(HttpHeaderName.java:56)
        at com.azure.core.http.policy.RequestIdPolicy.<clinit>(RequestIdPolicy.java:33)
        at com.azure.ai.translation.text.TextTranslationClientBuilder.createHttpPipeline(TextTranslationClientBuilder.java:300)
        at com.azure.ai.translation.text.TextTranslationClientBuilder.buildInnerClient(TextTranslationClientBuilder.java:264)
        at com.azure.ai.translation.text.TextTranslationClientBuilder.buildClient(TextTranslationClientBuilder.java:358)
        at com.microsoft.mobile.polymer.ui.hometab.ExperimentSpaceActivity.initTextTranslation(ExperimentSpaceActivity.java:239)
        at com.microsoft.mobile.polymer.ui.hometab.ExperimentSpaceActivity.onCreate(ExperimentSpaceActivity.java:107)

**To Reproduce**
Below code is giving the mentioned exception:
TextTranslationClient client = new TextTranslationClientBuilder()
                .credential(credential)
                .region(region)
                .buildClient();

***Code Snippet***
TextTranslationClient client = new TextTranslationClientBuilder()
                .credential(credential)
                .region(region)
                .buildClient();

**Expected behavior**
create an instance of TextTranslationClientBuilder, which should be used to translate required text.

**Setup (please complete the following information):**
 - OS: Android OS
 - IDE: Android Studio
 - Library/Libraries: "com.azure:azure-ai-translation-text:1.0.0-beta.1"
 - Java version: 11
 - App Server/Environment: [e.g. Tomcat, WildFly, Azure Function, Apache Spark, Databricks, IDE plugin or anything special]
 - Frameworks: [e.g. Spring Boot, Micronaut, Quarkus, etc] 

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by joshfree** [comment]
For more context, this is from the [Quickstart: Azure Cognitive Services Translator SDKs (preview)](https://learn.microsoft.com/en-us/azure/cognitive-services/translator/quickstart-text-sdk?pivots=programming-language-java#set-up-your-java-environment) which is showing people how to use `com.azure:azure-ai-translation-text:1.0.0-beta.1` with Gradle.

**Comment by alzimmermsft** [comment]
Thanks for filing this @Sh-Singh and @joshfree for including the quickstart guide.

While the quickstart guide is using Gradle and Kotlin for the examples, and this is the common development choices for Android, the Java SDK for Text Translator doesn't provide support for Android, nor are there guarantees that the Java SDK will work for Android. To me, this appears to be confusion brought on by the quickstart guide as it gives an appearance for Android support while that is not the case.

**Comment by JonathanGiles** [comment]
I will contribute a PR to the docs for that sample to make it clear that the documentation refers to text translation on a server, rather than on Android.

As a follow-up to @Sh-Singh, we will potentially be spending some cycles towards the end of this year investigating making it more feasible for many of our libraries to more seamlessly work on Android - but unfortunately that is not available today. As discussed offline, you'll need to consider using your backup plan to achieve your goals.

**Comment by alzimmermsft** [comment]
@Sh-Singh, based on another issue similar to this Android API version 26, or above, may work with the Java SDKs.

https://github.com/Azure/azure-sdk-for-java/issues/35719#issuecomment-1629587961

That said, Android is still officially unsupported by the Azure SDK for Java repository.

**Comment by alzimmermsft** [comment]
Android is not the primary target of the libraries in this repository. Whilst effort has been made to test against Android 26+ occasionally, this is not something we prioritize and cannot guarantee will work at all times. Closing this issue as won't fix.
