### ISSUE TITLE
[FEATURE REQ] azure-spring-boot-starter-vault-certificates JCA support Spring Boot 3.x

### ISSUE THREAD

**Issue by StephaneVa** [Azure/azure-sdk-for-java#35782]
Hello,

**Describe the bug**
I'm using azure-spring-boot-starter-vault-certificates since a lot of time in order to retrieve our server certificate from Azure keyVault.
I've followed [this doc](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-key-vault-certificates#run-a-spring-boot-application-with-secure-inbound-connections) for the configuration. 

It works with spring-boot 2.7.x
It works with spring-boot 3.0.4

With spring-boot 3.1.1, server starts properly, but requesting it makes a SSL handshake issue. I think the certificate is retrieved, but not correctly set anymore 

***Exception or Stack Trace***
starting logs:
```log
Tomcat initialized with port(s) : 8443 (https)
Starting service [Tomcat]
Starting Servlet engine [Apache Tomcat/10.1.10]
Initializing Spring embedded WebApplicationContext
Root WebApplicationContext: initialization completed in 2768ms
Using Azure Key Vault: https://xxxxxxx.vault.azure.net/
Getting access token using managed identity
Getting key for alias: cert-alias
Getting certificate for alias: cert-alias
Tomcat started on port(s) : 8443 (https) with context path ''
Application started in 12.43 seconds (process running for 16.152)
Initializing Spring DispatcherServlet 'dispatcherServlet'
Initializing Servlet 'dispatcherServlet'
Completed initialization in 2 ms
```

With jvm flags "-Djavax.net.debug=ssl:handshake", we have this log when we request the server (ie: https://localhost:8443/health)

```log
ServerHello.java:589 | Produced ServerHello handshake message
X509Authentication.java:304 | No X.509 cert select for RSA
CertificateMessage.java:1084 | Unavailable authentication scheme: rsa_pss_rsae_sha256
... ... repeated those 2 lines aboves for lots of scheme ( rsa_pkcs1_sha256, .....)
TransportContext.java:361 | Fatal (HANDSHAKE_FAILURE): No available authentication scheme (
"throwable": {
  javax.net.ssl.SSLHandshakeException: No available authentication scheme
   at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
   at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
   at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:356)
   at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:312)
   at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:303)
   at java.base/sun.security.ssl.CertificateMessage$T13CertificateProducer.onProduceCertificate(CertificateMessage.java:972)
   at java.base/sun.security.ssl.CertificateMessage$T13CertificateProducer.produce(CertificateMessage.java:961)
   ...
}
)
```

**To Reproduce**
set up a spring boot web app with the certificate in an Azure Key Vault

**Expected behavior**
find & send the certificate when during the handshake

**Setup (please complete the following information):**
 - OS: alpine
 - Library/Libraries: 
    - azure-spring-boot-starter-keyvault-certificates:3.14.0
    - azure-spring-boot-starter-keyvault-secrets:3.14.0
    - spring-boot-starter-web:3.1.1
 - Java version: 17-ea+14 
 - App Server/Environment: the app is deployed on a Azure Kubernetes and retrieve secrets & certificates from Azure Key Vault
 - Frameworks: Spring Boot 3.1.1

**Additional context**
No issue with spring-boot 3.1.1 in local when the same certificate is configured locally (server.ssl.key-store-type=pfx, etc.)
No issue with spring-boot 3.0.4 in docker

we tried to use spring-boot 3.1.1 with the tomcat embedded by spring-boot 3.0.4, same issue

certificate signature algorithm: SHA256withRSA

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by Netyyyy** [comment]
Hi @StephaneVa , thanks for reaching out.
Could you with `spring-cloud-azure-starter-keyvault-certificates:5.3.0` and `spring-cloud-azure-starter-keyvault-secrets:5.3.0`, refer to https://github.com/Azure/azure-sdk-for-java/wiki/Spring-Versions-Mapping, version 3.14.0 not compatible with Spring Boot 3

**Comment by Netyyyy** [comment]
Hi @StephaneVa , thanks for reporting this issue. refer to this https://github.com/Azure/azure-sdk-for-java/wiki/Spring-Versions-Mapping, Spring Cloud Azure 3.14 doesn't compatible with Spring Boot 3, please try with the older version.
Please feel free to provide any additional information or context that you think may be helpful. We'll keep you updated on the progress of our review.
Thank you for your contribution to improving our project.

**Comment by StephaneVa** [comment]
Hello,

According to the [Spring-Versions-Mapping](https://github.com/Azure/azure-sdk-for-java/wiki/Spring-Versions-Mapping), indeed we should use Spring Cloud Azure version 5.3.0 

But from the [migration guide](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/migration-guide-for-4.0), azure-spring-boot-starter-keyvault-certificates is "Not included in this release, but will be supported in later version."

This was not an issue from spring-boot 2.4.x to 3.0.x since the starter still worked, but it's now problematic with spring-boot 3.1.x. 

Thank you for your understanding

**Comment by Netyyyy** [comment]
Hi @StephaneVa , sorry for the late reply.
`azure-spring-boot-starter-keyvault-certificates-3.14.0` is only supported with spring boot 2.4.x, we haven't had a plan to support the new spring boot version yet, sorry for the impact.

**Comment by Netyyyy** [comment]
Update description: https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/4715

**Comment by okapetan** [comment]
Hi, I'm following up on the compatibility issue between azure-spring-boot-starter-keyvault-certificates-3.14.0 and Spring Boot 3.x.

As per the last update from @Netyyyy, it appears that azure-spring-boot-starter-keyvault-certificates-3.14.0 is only compatible with Spring Boot 2.4.x, and there were no immediate plans to support newer versions of Spring Boot at that time.

Given this, I have a couple of questions:

- Are there any recent developments or updates regarding the support of azure-spring-boot-starter-keyvault-certificates with Spring Boot 3.x?
- @Netyyyy If the support for Spring Boot 3.x is not on the roadmap, could you recommend alternative approaches or solutions for integrating Azure Key Vault certificates in a Spring Boot 3.x application? 

Thanks in advance.

**Comment by Netyyyy** [comment]
Hi @okapetan , you can use `azure-security-keyvault-jca: 2.8.1` instead for now, here is the [README](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/keyvault/azure-security-keyvault-jca). The support of Keyvault Certificate is in our backlog and will be updated when it's finished.

**Comment by moarychan** [comment]
Closing it since the new starter PR merged.
