### ISSUE TITLE
[BUG] Spring Boot aot processing fails for AzureGlobalProperties

### ISSUE THREAD

**Issue by rvervaek** [Azure/azure-sdk-for-java#36001]
**Describe the bug**
When a project is build using the spring-boot-maven-plugin:process-aot goal, the build fails due to the unsupported bean definition of the `com.azure.spring.cloud.autoconfigure.implementation.context.properties.AzureGlobalProperties` class.

***Exception or Stack Trace***
```
Exception in thread "main" java.lang.IllegalArgumentException: Code generation is not supported for bean definitions declaring an instance supplier callback : Root bean: class [com.azure.spring.cloud.autoconfigure.implementation
.context.properties.AzureGlobalProperties]; scope=singleton; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodNames=
null; destroyMethodNames=null
        at org.springframework.beans.factory.aot.BeanDefinitionMethodGenerator.<init>(BeanDefinitionMethodGenerator.java:82)
        at org.springframework.beans.factory.aot.BeanDefinitionMethodGeneratorFactory.getBeanDefinitionMethodGenerator(BeanDefinitionMethodGeneratorFactory.java:100)
        at org.springframework.beans.factory.aot.BeanDefinitionMethodGeneratorFactory.getBeanDefinitionMethodGenerator(BeanDefinitionMethodGeneratorFactory.java:115)
        at org.springframework.beans.factory.aot.BeanRegistrationsAotProcessor.processAheadOfTime(BeanRegistrationsAotProcessor.java:49)
        at org.springframework.context.aot.AbstractAotProcessor.process(AbstractAotProcessor.java:82)
        at org.springframework.boot.SpringApplicationAotProcessor.main(SpringApplicationAotProcessor.java:80)
```

**To Reproduce**
Run `mvn -Pnative spring-boot:build-image` in the [spring-aot-springCloudAzureGlobalProperties.zip](https://github.com/Azure/azure-sdk-for-java/files/12107672/spring-aot-springCloudAzureGlobalProperties.zip) project.

**Expected behavior**
The Maven build during execution of the spring-boot-maven-plugin:process-aot goal succeeds.

**Setup (please complete the following information):**
 - OS: Windows
 - IDE: IntelliJ
 - Library/Libraries: 
 - - Spring Boot 3.0.9
 - - Spring Cloud Azure Starter 5.3.0
 - Java version: 17

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x ] Bug Description Added
- [x ] Repro Steps Added
- [x ] Setup information Added

**Comment by Netyyyy** [comment]
Hi @rvervaek , thank you for reaching out. We have received your submission and will take it into consideration. We appreciate your input and will review this matter ASAP.
Please feel free to provide any conditional information or context that you think may be helpful. We'll keep you updated on the progress of our review.
Thank you for your contribution to improving our project.

**Comment by saragluna** [comment]
See https://github.com/spring-projects/spring-boot/issues/34563 for more context.

**Comment by bitbaggi** [comment]
Not working with new Version 3.2.0-M1, any other news on this?

**Comment by Netyyyy** [comment]
Hi @bitbaggi , support 3.2.0-M1 is in our backlog. Please vote for this feature so we could prioritize it.

**Comment by saragluna** [comment]
Have you tried the latest version of Spring Cloud Azure 5.x? I believe we have fixed this issue.

**Comment by rvervaek** [comment]
@saragluna Yes, version 5.4.0 seems to have fixed the issue, thanks.

**Comment by bitbaggi** [comment]
Yeah with Version 5.4.0 its working.
But now there is another error.

```
Fatal error: java.lang.SecurityException: class "com.azure.spring.cloud.autoconfigure.implementation.messaging.AzureMessagingListenerAutoConfiguration$ServiceBusConfiguration$$SpringCGLIB$$0"'s signer information does not match signer information of other classes in the same package
    [creator]           at java.base/java.lang.ClassLoader.checkCerts(ClassLoader.java:1158)
    [creator]           at java.base/java.lang.ClassLoader.preDefineClass(ClassLoader.java:902)
    [creator]           at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1010)
    [creator]           at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
    [creator]           at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:524)
    [creator]           at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:427)
    [creator]           at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421)
    [creator]           at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
    [creator]           at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:420)
    [creator]           at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
    [creator]           at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
    [creator]           at java.base/java.lang.Class.forName0(Native Method)
    [creator]           at java.base/java.lang.Class.forName(Class.java:467)
    [creator]           at com.oracle.svm.hosted.ImageClassLoader.forName(ImageClassLoader.java:296)
    [creator]           at com.oracle.svm.hosted.ImageClassLoader.forName(ImageClassLoader.java:292)
    [creator]           at com.oracle.svm.hosted.ImageClassLoader.findClass(ImageClassLoader.java:285)
    [creator]           at com.oracle.svm.hosted.config.ReflectionRegistryAdapter.resolveType(ReflectionRegistryAdapter.java:70)
    [creator]           at com.oracle.svm.core.configure.ReflectionConfigurationParser.parseClass(ReflectionConfigurationParser.java:85)
    [creator]           at com.oracle.svm.core.configure.ReflectionConfigurationParser.parseClassArray(ReflectionConfigurationParser.java:69)
    [creator]           at com.oracle.svm.core.configure.ReflectionConfigurationParser.parseAndRegister(ReflectionConfigurationParser.java:64)
    [creator]           at com.oracle.svm.core.configure.ConfigurationParser.parseAndRegister(ConfigurationParser.java:71)
    [creator]           at com.oracle.svm.hosted.config.ConfigurationParserUtils.doParseAndRegister(ConfigurationParserUtils.java:125)
    [creator]           at com.oracle.svm.hosted.config.ConfigurationParserUtils.lambda$parseAndRegisterConfigurations$3(ConfigurationParserUtils.java:111)
    [creator]           at java.base/java.util.stream.ReferencePipeline$4$1.accept(ReferencePipeline.java:214)
    [creator]           at com.oracle.svm.hosted.config.ConfigurationParserUtils$1.tryAdvance(ConfigurationParserUtils.java:104)
    [creator]           at java.base/java.util.Spliterator.forEachRemaining(Spliterator.java:332)
    [creator]           at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
    [creator]           at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
    [creator]           at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
    [creator]           at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
    [creator]           at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
    [creator]           at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:310)
    [creator]           at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734)
    [creator]           at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
    [creator]           at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
    [creator]           at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
    [creator]           at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    [creator]           at java.base/java.util.stream.IntPipeline.reduce(IntPipeline.java:515)
    [creator]           at java.base/java.util.stream.IntPipeline.sum(IntPipeline.java:473)
    [creator]           at com.oracle.svm.hosted.config.ConfigurationParserUtils.parseAndRegisterConfigurations(ConfigurationParserUtils.java:113)
    [creator]           at com.oracle.svm.hosted.reflect.ReflectionFeature.duringSetup(ReflectionFeature.java:232)
    [creator]           at com.oracle.svm.hosted.NativeImageGenerator.lambda$setupNativeImage$16(NativeImageGenerator.java:918)
    [creator]           at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:85)
    [creator]           at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:918)
    [creator]           at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:575)
    [creator]           at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:535)
    [creator]           at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:403)
    [creator]           at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:580)
    [creator]           at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
    [creator]           at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:610)
```

**Comment by saragluna** [comment]
https://github.com/Azure/azure-sdk-for-java/issues/36320
