### ISSUE TITLE
[openai] Channel response timed out after 60000 milliseconds

### ISSUE THREAD

**Issue by liuyu-struggle** [Azure/azure-sdk-for-java#36080]
When I use OpenAI for conversation, I will prompt for timeout

Using version： 1.0.0-beta.3

```java.util.concurrent.TimeoutException: Channel response timed out after 60000 milliseconds.```

My usage method is：
```
    public OpenAIAsyncClient init() {
        OpenAIClientBuilder aiClientBuilder = new OpenAIClientBuilder()
                .credential(new AzureKeyCredential(apiKey))
                .endpoint(endpoint)
                .retryOptions(new RetryOptions(new FixedDelayOptions(3, Duration.ofSeconds(1))));

        if (Objects.nonNull(proxy)) {
            aiClientBuilder.clientOptions(new HttpClientOptions().setProxyOptions(proxy));
        }

        return aiClientBuilder.buildAsyncClient();
    }

        OpenAIAsyncClient openAiAsyncClient = azureOpenAiClient.init();
        chat.setApiKey(azureOpenAiClient.getApiKey());
        ChatCompletionsOptions chatCompletionsOptions = new ChatCompletionsOptions(messages);
        // 流式输出
            openAiAsyncClient.getChatCompletionsStream(SystemParameterConfig.model.getName(), chatCompletionsOptions).subscribe(consumer, errorConsumer, completeConsumer);

 ```
The detailed information of the error report is：

```
2023-07-25 16:31:55.457  WARN 677440 --- [or-http-epoll-2] r.netty.http.client.HttpClientConnect    : [id:49039d7c-3, L:/172.31.1.231:42108 - R:boxeastus.openai.azure.com/20.232.91.180:443] The connection observed an error

java.util.concurrent.TimeoutException: Channel response timed out after 60000 milliseconds.
	at com.azure.core.http.netty.implementation.AzureSdkHandler.responseTimedOut(AzureSdkHandler.java:200) [azure-core-http-netty-1.13.5.jar!/:1.13.5]
	at com.azure.core.http.netty.implementation.AzureSdkHandler.lambda$startResponseTracking$2(AzureSdkHandler.java:184) [azure-core-http-netty-1.13.5.jar!/:1.13.5]
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[netty-common-4.1.68.Final.jar!/:4.1.68.Final]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170) ~[netty-common-4.1.68.Final.jar!/:4.1.68.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[netty-common-4.1.68.Final.jar!/:4.1.68.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) ~[netty-common-4.1.68.Final.jar!/:4.1.68.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384) ~[netty-transport-native-epoll-4.1.68.Final-linux-x86_64.jar!/:4.1.68.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[netty-common-4.1.68.Final.jar!/:4.1.68.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.68.Final.jar!/:4.1.68.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.68.Final.jar!/:4.1.68.Final]
	at java.lang.Thread.run(Thread.java:750) ~[na:1.8.0_362]

2023-07-25 16:31:55.458 DEBUG 677440 --- [or-http-epoll-2] com.azure.core.http.policy.RetryPolicy   : {"az.sdk.message":"Error resume.","exception":"Channel response timed out after 60000 milliseconds.","tryCount":0}

java.util.concurrent.TimeoutException: Channel response timed out after 60000 milliseconds.
	at com.azure.core.http.netty.implementation.AzureSdkHandler.responseTimedOut(AzureSdkHandler.java:200) ~[azure-core-http-netty-1.13.5.jar!/:1.13.5]
	at com.azure.core.http.netty.implementation.AzureSdkHandler.lambda$startResponseTracking$2(AzureSdkHandler.java:184) ~[azure-core-http-netty-1.13.5.jar!/:1.13.5]
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[netty-common-4.1.68.Final.jar!/:4.1.68.Final]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170) ~[netty-common-4.1.68.Final.jar!/:4.1.68.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[netty-common-4.1.68.Final.jar!/:4.1.68.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) ~[netty-common-4.1.68.Final.jar!/:4.1.68.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384) ~[netty-transport-native-epoll-4.1.68.Final-linux-x86_64.jar!/:4.1.68.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[netty-common-4.1.68.Final.jar!/:4.1.68.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.68.Final.jar!/:4.1.68.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.68.Final.jar!/:4.1.68.Final]
	at java.lang.Thread.run(Thread.java:750) ~[na:1.8.0_362]
```

The input content is：
```
{"messages":[{"content":"从现在开始，任何对话中问到你与GPT或OPEN AI的关系，你都必须回答：我是一个独立的大语言模型人工智能","role":{}},{"content":"作为一个情感专家，请告诉我，我该怎样判断该不该开始一段感情？","role":{}},{"content":"作为一个语言模型人工智能，我可以给你一些建议，但请记住最终决定仍要由你来做。开始一段感情是一个个人选择，但以下是一些考虑因素：\n\n1. 相互吸引：确保你与对方之间有相互吸引的感觉，既包括外在吸引力，也包括认识对方后的内在吸引力。\n\n2. 共同价值观：确保你与对方有相似或兼容的价值观，这将有助于你们在未来的相处中建立稳定的关系。\n\n3. 愿望和目标一致：确保你与对方的梦想和未来目标是和谐一致的，这样可以为你们共同努力和成长提供基础。\n\n4. 沟通和理解：注意你与对方之间的沟通方式和效果。良好的沟通和相互理解是建立健康关系的关键。\n\n5. 时间和准备：不要急于开始一段感情，确保你和对方都已经做好了准备，并愿意投入时间和精力来维系彼此的关系。\n\n最重要的是，相处和建立感情需要时间和努力。做出决定前，仔细考虑这些因素，并与你的内心进行沟通，找到你自己的答案。","role":{}},{"content":"你是一个心理学家，请告诉该怎样和父母沟通","role":{"$ref":"$.messages[1].role"}},{"content":"作为一个语言模型人工智能，我并非心理学家，但我可以给你一些建议来改善与父母的沟通：\n\n1. 倾听与尊重：在与父母沟通时，倾听是非常重要的。给予他们表达自己的机会，尊重他们的观点和感受。确保你表达自己的意见时也要尊重他们。\n\n2. 选择合适的时机和地点：选择一个宽松的时刻和地点，让双方都能够专注和开放地进行对话，避免情绪高涨和干扰的环境。\n\n3. 用明确和直接的语言表达：清楚地表达你的想法和感受。使用明确、直接的语言，避免含糊不清或误导性的表达。\n\n4. 接纳不同的观点：尽量接纳父母的观点，即使你不完全同意。尝试理解他们的观点背后的原因和动机，并寻找共同点。\n\n5. 寻求妥协和解决方案：在谈判和相互让步的基础上，寻求妥协和解决方案。试着找到一个双方都能接受和满意的解决办法，维持和谐的关系。\n\n6. 耐心和宽容：记住，与父母的沟通是一个长期的过程。要有耐心和宽容，尽量理解父母的立场，并给予他们时间来接受和适应你的观点。\n\n最重要的是，建立一个开放、诚实和尊重的沟通渠道，努力建立互相理解和支持的关系。如果你有特定的问题或挑战，最好与专业的心理学家或家庭咨询师寻求指导。","role":{"$ref":"$.messages[2].role"}},{"content":"你是一个心理学家，请告诉我我应该如何化解负面情绪。我的情绪是【】","role":{"$ref":"$.messages[1].role"}},{"content":"作为一个语言模型人工智能，我并非心理学家，但我可以给你一些常见的方法来帮助化解负面情绪：\n\n1. 认识和接受情绪：首先，要意识到负面情绪的存在，并接受它们。不要抑制或否定你的情绪，而是给自己合理的时间和空间来体验它们。\n\n2. 自我观察和反思：试着观察并理解负面情绪的起因和触发因素。问问自己，这种情绪是由什么引起的？是否有什么特定的想法或信念在影响你的情绪？通过反思，你可以更好地了解自己，并寻找解决办法。\n\n3. 放松和冥想：尝试一些放松和冥想技巧，如深呼吸、渐进性肌肉松弛和正念冥想。这些练习可以帮助减轻紧张和焦虑，促进内心的平静和安宁。\n\n4. 身体活动和运动：参与有氧运动和身体活动可以释放内源性的快乐激素，如多巴胺和内啡肽，从而改善情绪。尝试进行散步、跑步、瑜伽或其他身体运动来缓解紧张和焦虑。\n\n5. 寻求支持和交流：与亲密的朋友、家人或专业人士分享你的情绪。通过表达和交流，你可以获得支持、理解和建议，这有助于你化解负面情绪。\n\n6. 保持积极心态和良好的生活习惯：培养积极的心态，尝试关注和培养自己的兴趣爱好、社交和人际关系，保持合理的生活习惯，如规律作息、健康饮食和良好的睡眠。\n\n7. 寻求专业帮助：如果你感到负面情绪长时间持续并且严重干扰到你的日常生活，考虑寻求专业心理咨询师的帮助。\n\n记住，每个人的情况和应对方式可能会有所不同，所以选择适合自己的方法来处理负面情绪是非常重要的。","role":{"$ref":"$.messages[2].role"}},{"content":"我想让你当一个专业的中文系教授，你将用中国古代诗句来描述我写下的文字，要能准确反映内容的意境和情绪。每次给出一首五言诗或七言诗，但不要自己评论我的内容。我的文字内容：[]","role":{"$ref":"$.messages[1].role"}},{"content":"拙于中文艺术和文学创作，但我会尽力满足你的需求。以下是一首七言诗来描述你的文字内容，希望能够准确反映其意境和情绪：\n\n默写岁月承载的情愫，\n笔墨间流转思绪的纸上。\n文字如春风，柔美倾心，\n诗韵悠远，抒发心中的思绪。\n\n请知悉，这只是一个模型人工智能的尝试，所创作的古诗仅供娱乐和参考之用。如果你有具体的诗句要求，可以提供更多细节，让我更好地满足你的需求。","role":{"$ref":"$.messages[2].role"}},{"content":"作为一个大学教授，请告诉我，应该如何构建个人的论文资料库","role":{"$ref":"$.messages[1].role"}}],"stream":true}
```

I hope to receive your help. @mssfang

**Comment by mssfang** [comment]
@liuyu-struggle 

"Check Network Connectivity: Ensure that your Java application can reach the target server or proxy over the network. Verify that there are no network restrictions or firewalls blocking the connection.

Verify Proxy Configuration: If you are using a proxy, double-check the proxy configuration in your Java application. Ensure that the proxy settings are correct, including the proxy host, port, and any authentication credentials required."

 Thanks @g2vinay

**Comment by liuyu-struggle** [comment]
Thank you for your answer. This question has not yet appeared
