### ISSUE TITLE
[BUG] Caused by: com.azure.core.amqp.exception.AmqpException: org.apache.qpid.proton.engine.TransportException

### ISSUE THREAD

**Issue by curiousmickey** [Azure/azure-sdk-for-java#36354]
**Describe the bug**
In our application logs (both non-prod & prod), we are consistently seeing this exception. No luck in reading a message.
Whereas when we connect to the same ASB topic from local/developer's computer, there is no issue.
Please help in unblocking us.

***Exception or Stack Trace***
2023/08/15 21:46:23.283 WARN [ConnectionHandler] [reactor-executor-188] [test-application-war] [] {"az.sdk.message":"onTransportError","connectionId":"MF_bac61f_1692135923282","errorCondition":"amqp:connection:framing-error","errorDescription":"org.apache.qpid.proton.engine.TransportException: connection aborted","hostName":"XXXXX.servicebus.windows.net"}
2023/08/15 21:46:23.284 INFO [ReactorConnection] [reactor-executor-188] [test-application-war] [] {"az.sdk.message":"Disposing of ReactorConnection.","connectionId":"MF_bac61f_1692135923282","isTransient":false,"isInitiatedByClient":false,"shutdownMessage":"org.apache.qpid.proton.engine.TransportException: connection aborted, errorContext[NAMESPACE: XXXXX.servicebus.windows.net. ERROR CONTEXT: N/A]"}
2023/08/15 21:46:23.284 INFO [ConnectionHandler] [reactor-executor-188] [test-application-war] [] {"az.sdk.message":"onConnectionUnbound","connectionId":"MF_bac61f_1692135923282","hostName":"XXXXX.servicebus.windows.net","state":"CLOSED","remoteState":"UNINITIALIZED"}
2023/08/15 21:46:23.285 INFO [ReactorConnection] [reactor-executor-188] [test-application-war] [] {"az.sdk.message":"Closing executor.","connectionId":"MF_bac61f_1692135923282"}
2023/08/15 21:46:27.292 INFO [ReactorExecutor] [reactor-executor-188] [test-application-war] [] {"az.sdk.message":"Processing all pending tasks and closing old reactor.","connectionId":"MF_bac61f_1692135923282"}
2023/08/15 21:46:27.293 INFO [ReactorDispatcher] [reactor-executor-188] [test-application-war] [] {"az.sdk.message":"Reactor selectable is being disposed.","connectionId":"MF_bac61f_1692135923282"}
2023/08/15 21:46:27.293 INFO [ReactorConnection] [reactor-executor-188] [test-application-war] [] {"az.sdk.message":"onConnectionShutdown. Shutting down.","connectionId":"MF_bac61f_1692135923282","isTransient":false,"isInitiatedByClient":false,"shutdownMessage":"connectionId[MF_bac61f_1692135923282] Reactor selectable is disposed.","namespace":"XXXXX.servicebus.windows.net"}
2023/08/15 21:46:27.293 ERROR [Operators] [reactor-executor-188] [test-application-war] [] Operator called default onErrorDropped
reactor.core.Exceptions$ErrorCallbackNotImplemented: com.azure.core.amqp.exception.AmqpException: org.apache.qpid.proton.engine.TransportException: connection aborted, errorContext[NAMESPACE: XXXXX.servicebus.windows.net. ERROR CONTEXT: N/A]
Caused by: com.azure.core.amqp.exception.AmqpException: org.apache.qpid.proton.engine.TransportException: connection aborted, errorContext[NAMESPACE: XXXXX.servicebus.windows.net. ERROR CONTEXT: N/A]
	at com.azure.core.amqp.implementation.ExceptionUtil.toException(ExceptionUtil.java:85) ~[com.azure.azure-core-amqp-2.8.7.jar:2.8.7]
	at com.azure.core.amqp.implementation.handler.ConnectionHandler.notifyErrorContext(ConnectionHandler.java:351) ~[com.azure.azure-core-amqp-2.8.7.jar:2.8.7]
	at com.azure.core.amqp.implementation.handler.ConnectionHandler.onTransportError(ConnectionHandler.java:253) ~[com.azure.azure-core-amqp-2.8.7.jar:2.8.7]
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:191) ~[org.apache.qpid.proton-j-0.33.8.jar:?]
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108) ~[org.apache.qpid.proton-j-0.33.8.jar:?]
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324) ~[org.apache.qpid.proton-j-0.33.8.jar:?]
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291) ~[org.apache.qpid.proton-j-0.33.8.jar:?]
	at com.azure.core.amqp.implementation.ReactorExecutor.run(ReactorExecutor.java:91) ~[com.azure.azure-core-amqp-2.8.7.jar:2.8.7]
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68) [io.projectreactor.reactor-core-3.4.30.jar:3.4.30]
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28) [io.projectreactor.reactor-core-3.4.30.jar:3.4.30]

**To Reproduce**
Happening in non-prod and production application server logs consistently

***Code Snippet***
N/A

**Expected behavior**
No issue in connecting and reading the message

**Screenshots**

**Setup (please complete the following information):**
 - IDE: [e.g. IntelliJ]
 - Library/Libraries: com.azure:azure-messaging-servicebus:7.14.2
 - Java version: 11.0.8-msft 
 - App Server/Environment: Jetty

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by joshfree** [comment]
@anuchandy PTAL

**Comment by curiousmickey** [comment]
Yes, we found out this indeed is network issue.
For the benefit of other users, who may come up with this issue here is the solution.
When network firewall rules are added, make sure to allow the traffic on AMQP port 5671 also along with HTTPS port 443.
