### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: com/azure/cosmos/implementation/faultinjection/IRntbdServerErrorInjector

### ISSUE THREAD

**Issue by kushagraThapar** [Azure/azure-sdk-for-java#36381]
There is an issue when using azure-cosmos-test version 1.0.0-beta.4 with latest azure-cosmos library 4.48.1 -> 

Because IRntbdServerErrorInjector class has been removed from azure-cosmos, the latest package of azure-cosmos will not have it and causes this exception to be thrown. 

Exception in thread "main" java.lang.NoClassDefFoundError: com/azure/cosmos/implementation/faultinjection/IRntbdServerErrorInjector 	at com.azure.cosmos.test.faultinjection.CosmosFaultInjectionHelper.lambda$configureFaultInjectionRules$0(CosmosFaultInjectionHelper.java:30) 	at com.azure.cosmos.CosmosAsyncContainer.getOrConfigureFaultInjectorProvider(CosmosAsyncContainer.java:2660) 	at com.azure.cosmos.CosmosAsyncContainer$1.getOrConfigureFaultInjectorProvider(CosmosAsyncContainer.java:2707) 	at com.azure.cosmos.test.faultinjection.CosmosFaultInjectionHelper.configureFaultInjectionRules(CosmosFaultInjectionHelper.java:30) 	at com.example.common.CosmosConsoleMeterRegistryExample.createReadSessionNotAvailableThroughFaultInjection(CosmosConsoleMeterRegistryExample.java:136) 	at com.example.common.CosmosConsoleMeterRegistryExample.main(CosmosConsoleMeterRegistryExample.java:56) Caused by: java.lang.ClassNotFoundException: com.azure.cosmos.implementation.faultinjection.IRntbdServerErrorInjector 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) 	... 6 more

Possible solution: 

Through changelog, we should recommend customers in every release of azure-cosmos to take azure-cosmos-test version which is compatible.

**Comment by kushagraThapar** [comment]
This has been fixed in the latest version of azure-cosmos-test library release - https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-cosmos-test/CHANGELOG.md#100-beta5-2023-08-21
