### ISSUE TITLE
[BUG] Error when creating ScaleSet with Proximity Group

### ISSUE THREAD

**Issue by roy-regatta** [Azure/azure-sdk-for-java#36417]
**Describe the bug**
When creating a `virtualMachineScaleSets` using the azure resource manager and setting the `withNewProximityPlacementGroup` option an exception is being thrown and the operation fails.
When running without the `withNewProximityPlacementGroup` option, everything works as expected.

***Exception or Stack Trace***
```
java.lang.IllegalStateException: block()/blockFirst()/blockLast() are blocking, which is not supported in thread parallel-5

	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:86)
	at reactor.core.publisher.Mono.block(Mono.java:1712)
	at com.azure.resourcemanager.compute.implementation.ProximityPlacementGroupsClientImpl.createOrUpdateWithResponse(ProximityPlacementGroupsClientImpl.java:334)
	at com.azure.resourcemanager.compute.implementation.ProximityPlacementGroupsClientImpl.createOrUpdate(ProximityPlacementGroupsClientImpl.java:351)
	at com.azure.resourcemanager.compute.implementation.VirtualMachineScaleSetImpl.createNewProximityPlacementGroup(VirtualMachineScaleSetImpl.java:2976)
	at com.azure.resourcemanager.compute.implementation.VirtualMachineScaleSetImpl.lambda$createInner$1(VirtualMachineScaleSetImpl.java:1662)
	at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:152)
	at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4480)
	at reactor.core.publisher.MonoSubscribeOn$SubscribeOnSubscriber.run(MonoSubscribeOn.java:126)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:103)
		at reactor.core.publisher.Mono.block(Mono.java:1712)
		at com.azure.resourcemanager.resources.fluentcore.model.implementation.CreatableUpdatableImpl.create(CreatableUpdatableImpl.java:255)
		at com.azure.resourcemanager.resources.fluentcore.model.implementation.CreatableUpdatableImpl.create(CreatableUpdatableImpl.java:29)
```

**To Reproduce**
Please see code snippet

***Code Snippet***
```
azureResourceManager.virtualMachineScaleSets()
                .define(name)
                .withRegion(region)
                .withExistingResourceGroup(group)
                .withFlexibleOrchestrationMode()
                .withSku(sku)
                .withNewProximityPlacementGroup("ppg", ProximityPlacementGroupType.STANDARD)
                .withExistingPrimaryNetworkSubnet(network, subnet)
                .withoutPrimaryInternetFacingLoadBalancer()
                .withoutPrimaryInternalLoadBalancer()
                .withGeneralizedLinuxCustomImage(imageId)
                .withRootUsername("username")
                .withRootPassword("password")
                .withCapacity(1)
                .withVirtualMachinePublicIp()
                .withAcceleratedNetworking()
                .create();
```

**Expected behavior**
For the scale set and vm(s) to be created 

**Setup (please complete the following information):**
 - OS: Windows 11
 - IDE: IntelliJ
 - Library/Libraries: `com.azure.resourcemanager:azure-resourcemanager:2.29.0`, `com.azure:azure-core:1.2.15`, `com.azure:azure-core-management:1.2.15`
 - Java version: temurin-17.0.8 
 - Frameworks: Spring Boot

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by joshfree** [comment]
@weidongxu-microsoft could you please help route @roy-regatta's github issue?
