### ISSUE TITLE
[BUG] BlobClient existsWithResponse times out with IllegalStateException every time

### ISSUE THREAD

**Issue by Burlinn** [Azure/azure-sdk-for-java#36487]
**Describe the bug**
Getting a timeout exception when trying to call `BlobClient.existsWithResponse`, which eventually never succeeds for any blob.

***Exception or Stack Trace***
```
java.lang.IllegalStateException: Timeout on blocking read for 5000000000 NANOSECONDS
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:123)
	at reactor.core.publisher.Mono.block(Mono.java:1766)
	at com.azure.storage.common.implementation.StorageImplUtils.blockWithOptionalTimeout(StorageImplUtils.java:135)
	at com.azure.storage.blob.specialized.BlobClientBase.existsWithResponse(BlobClientBase.java:501)
```

**Code Snippet/To Reproduce**

We recently updated from v8 to v12. Prior to the update everything worked as expected. Following the update, everything was mostly working alright except for this issue. We followed this migration guide:

https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-blob/migrationGuides/V8_V12.md

Without pasting our actual code, here's an approximation of our process:

```
TokenCredential tokenCredential = new DefaultAzureCredentialBuilder()
		.managedIdentityClientId(managedIdentityClientId)
		.build();
		
BlobServiceClient blobServiceClient = new BlobServiceClientBuilder()
	.endpoint("https://" + storageAccountName + ".blob.core.windows.net")
	.credential(tokenCredential.getCredential())
	.buildClient();
	
BlobContainerClient blobContainer = blobServiceClient.getBlobContainerClient(containerName);

BlobClient blobClient = blobContainer.getBlobClient(blobName, null);

boolean blobExists = blobClient.existsWithResponse(Duration.ofSeconds(5), Context.NONE).getValue();
```
Every once in a while we'll get the above errors when checking if a blob exists. If we attempt a retry, every retry on the same ` blobClient.existsWithResponse` call fails. We do see that future requests on the same blob eventually succeed though. At some point though the `existsWithResponse` requests just stops working entirely and continuously times out until the server is restarted or replaced, regardless of which blob or container it's trying to check.

**Expected behavior**

`existsWithResponse` should return a true or false response within a timely manner (preferably within 5 seconds).

**Screenshots**
Here's a graphical representation of our service making exists calls over time. The Blue Line indicates an exists check is about to occur. An Orange Line indicates an exists check has successfully returned either true or false. Dark Blue indicates the request has failed and timed out. At the end of the graph, the Blue and Dark Blue lines perfectly overlap.

![image](https://github.com/Azure/azure-sdk-for-java/assets/2353503/cff5f30b-2dee-4efd-b222-e576237e85aa)

**Setup (please complete the following information):**
 - OS: Linux
 - IDE: IntelliJ
 - Library/Libraries: 
    - com.azure:azure-storage-common:12.21.0
    - com.azure:azure-storage-blob:12.22.2
    - com.azure:azure-identity:1.9.1
 - Java version: 17
 - App Server/Environment: Azure VM

**Additional context**
We originally implemented just the `BlobClient.exists` call, but found that the call was eventually holding all the machine's available threads in a waiting state and never timing out. We implemeneted the `existsWithResponse` call to remedy that initial issue.

We're not sure if the exists call itself is the actual problem. And it could just be that the exists call is the first call we actually make against the BlobClient. We suspect that this could also fail if we called any BlobClient function that needed to actually make a blocking call to fetch data, but this issue only seems to pop up in Production and we're hesitant to test out there.

We have servers in a few different regions and all of them are experiencing the timeout issue, but only a few of them so far begin failing the call every time. If it helps so far the only servers that fail every time are in North Europe and Japan, with North Europe being the worst offender.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by Burlinn** [comment]
Update: The issue we were having is that in a prior token-authentication-based implementation of our code, we cached the BlobServiceClient with a lifespan of 30 seconds. The newest implementation that uses ManagedIdentity doesn't expire and was created with the expectation that you would create one BlobServiceClient for the lifetime of the service. So we were creating a bunch of BlobServiceClients that may have been slow to close and cleanup when the cache expired and eventually this brought down our instances. We fixed this by removing the cache ttl.

Huge thanks to the SDK team who helped us with the investigation into this one.
