### ISSUE TITLE
linkedstorageaccounts.get produces stack trace on success message concatenation

### ISSUE THREAD

**Issue by KinderBoeing12** [Azure/azure-sdk-for-java#36598]
**Describe the bug**
I’ve run into an error message when trying to pull information from the LinkedStorage accounts objects using the Azure Java SDK (with java 1.8).  This is with respect to trying to use Log Analytics API’s when trying to pull stats for our Azure Batch run.  This happens when I call the linkedStorageAccounts.get method (see print screen 2).  I have looked for a solution online and found none and I’ve looked through the code and it may be a bug (see print screen 1).

***Exception or Stack Trace***
19:19:40.162 [ForkJoinPool.commonPool-worker-1] DEBUG com.microsoft.aad.msal4j.ConfidentialClientApplication - [Correlation ID: 88f134fb-5bf4-414f-86e3-7e44a87dff79] Access Token was returned
19:19:40.166 [ForkJoinPool.commonPool-worker-1] ERROR reactor.core.publisher.Operators - Operator called default onErrorDropped
java.lang.NoSuchMethodError: com.azure.core.util.CoreUtils.stringJoin(Ljava/lang/String;Ljava/util/List;)Ljava/lang/String;
	at com.azure.identity.implementation.util.LoggingUtil.lambda$logTokenSuccess$0(LoggingUtil.java:30)
	at com.azure.core.util.logging.ClientLogger.performDeferredLogging(ClientLogger.java:530)
	at com.azure.core.util.logging.ClientLogger.log(ClientLogger.java:150)
	at com.azure.core.util.logging.ClientLogger.log(ClientLogger.java:125)
	at com.azure.identity.implementation.util.LoggingUtil.logTokenSuccess(LoggingUtil.java:28)
	at com.azure.identity.ClientSecretCredential.lambda$getToken$2(ClientSecretCredential.java:120)
	at reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onNext(FluxPeekFuseable.java:840)
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:249)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
	at reactor.core.publisher.MonoCompletionStage.lambda$subscribe$0(MonoCompletionStage.java:83)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1609)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1067)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1703)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:172)

**To Reproduce**
See code snippets

***Code Snippet***
LogAnalyticsManager manager = LogAnalyticsManager
		    .authenticate(credential, profile);
		
		LinkedStorageAccounts linkedStorageAccounts = manager.linkedStorageAccounts();
		LinkedStorageAccountsResource query = linkedStorageAccounts.get("jdif-storage-westus-rg", "jdif-dev-oms", DataSourceType.QUERY);
		LinkedStorageAccountsResource alerts = linkedStorageAccounts.get("jdif-storage-westus-rg", "jdif-dev-oms", DataSourceType.ALERTS);
		LinkedStorageAccountsResource watson = linkedStorageAccounts.get("jdif-storage-westus-rg", "jdif-dev-oms", DataSourceType.AZURE_WATSON);
		LinkedStorageAccountsResource logs = linkedStorageAccounts.get("jdif-storage-westus-rg", "jdif-dev-oms", DataSourceType.CUSTOM_LOGS);
		LinkedStorageAccountsResource ingestion = linkedStorageAccounts.get("jdif-storage-westus-rg", "jdif-dev-oms", DataSourceType.INGESTION);
		System.out.println();

**Expected behavior**
Correctly return success message and continue to next lines of code without printing a stack trace

**Screenshots**
Attached

**Setup (please complete the following information):**
 - OS: Windows 10 enterprise
 - IDE: Eclipse for Java developers
     - Version: 2022-09 (4.25.0)
       Build id: 20220908-1902
 - Library/Libraries: azure-resourcemanager-loganalytics: 1.0.0-beta.3
		
 - Java version:Oracle JDK 1.8_351
 - App Server/Environment:No app server
 - Frameworks: No framework

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added
![002_linkedStorageAccounts](https://github.com/Azure/azure-sdk-for-java/assets/143649539/d15e6d48-73bc-4fd3-b9ed-1289b88b2a77)
![003_oms_workspaceId](https://github.com/Azure/azure-sdk-for-java/assets/143649539/ef019dd6-26c8-43d9-b0c7-95994a7cc3e4)

**Comment by joshfree** [comment]
@weidongxu-microsoft could you please assist?

/cc @srnagar

**Comment by srnagar** [comment]
@KinderBoeing12 from the exception stacktrace, it looks like there's a dependency conflict.  Please take a look at the [troubleshooting guide](https://learn.microsoft.com/en-us/azure/developer/java/sdk/troubleshooting-dependency-version-conflict) for investigating `NoSuchMethodError`. If you are not able to resolve the version conflicts, could you please provide us with your application dependency tree and also a runnable reproducible sample?

**Comment by weidongxu-microsoft** [comment]
Thanks Srikanta.

@KinderBoeing12 
Here is some additional doc on dependency https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/resourcemanager#dependency-management
