### ISSUE TITLE
ClientClosedRequest for Async requests

### ISSUE THREAD

**Issue by hemasundars** [Azure/azure-sdk-for-java#36880]
Getting ClientClosedRequest error for root disk snapshot create Async requests. 

Invoking azure sdk createAsync request [1], getting timeout with in 16 seconds. Incoming put request [1] and getting error in 16 seconds [3]. We are not setting any timeouts, going with default API settings. 

[1] final Creatable<Snapshot> snapshotCreatable = createSnapshotCreatable(client, snapshotName, region,
                    resourceGroup, osDisk.id(), incrementalSnapshot, tags);

                final Mono<Snapshot> monoSnapshot = snapshotCreatable.createAsync();

[2] 2023-09-19T02:00:20,606 | INFO | reactor-http-nio-24 | createOrUpdate | 320 - full-azure-sdk - 2.21.0 | --> PUT https://management.azure.com/subscriptions/0772b926-6630-43f0-a114-0e1a18b774da/resourceGroups/msft-sites-stg-s1-backup/providers/Microsoft.Compute/snapshots/1695114011-msft-sites-stg-s1-dispatcher2eastus2?api-version=2022-07-02Try count: 1823-byte body:{"location":"eastus2","tags":{"DiskCount":"1","Adobe.ArchPath":"MC.AEM.Adobe Experience Manager MS","InstanceID":"msft-sites-stg-s1:dispatcher2eastus2","vtype":"root","BackupID":"1695114011:msft-sites-stg-s1:dispatcher2eastus2:","ExtentCount":"1","CryptKeyMD5":"$1$PHYIltGh$d513250950370a521b503aedad936c68","TimeStamp":"1695114011:KeepScheduleStage","Adobe.Owner":"Adobe Experience Manager Managed Services","Adobe.PCIData":"false","Adobe.CostCenter":"101554 5488811","ExtentID":"1","Adobe.Environment":"Production","UUID":"","Adobe.DataClassification":"Confidential","DiskID":"1"},"properties":{"creationData":{"createOption":"Copy","sourceResourceId":"/subscriptions/0772b926-6630-43f0-a114-0e1a18b774da/resourceGroups/MSFT-SITES-STG-S1/providers/Microsoft.Compute/disks/dispatcher2eastus2-disk-os"},"incremental":true}}--> END PUT

[3] 2023-09-19T02:00:36,956 | ERROR | reactor-http-nio-38 | AzureVMApi | 353 - com.adobe.lassen.service - 1.190.690 | Snapshot creation of root disk failed for instance msft-sites-stg-s1:dispatcher2eastus2 com.azure.core.management.exception.ManagementException: Long running operation is Failed or Cancelled. at com.azure.resourcemanager.resources.fluentcore.AzureServiceClient.getLroFinalResultOrError(AzureServiceClient.java:190) ~[?:?] at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:125) [!/:3.4.18] at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816) [!/:3.4.18]

Error: 
"statusCode": "499", "serviceRequestId": null, "statusMessage": "{\"error\":{\"code\":\"ClientClosedRequest\",\"message\":\"The connection has been closed by the client while the server is still processing its request for 'Microsoft.Compute'.\"}}", "responseBody": "{\"error\":{\"code\":\"ClientClosedRequest\",\"message\":\"The connection has been closed by the client while the server is still processing its request for 'Microsoft.Compute'.\"}}", "eventCategory": "Administrative", "entity": "/subscriptions/0772b926-6630-43f0-a114-0e1a18b774da/resourceGroups/msft-sites-prf-s-3-backup/providers/Microsoft.Compute/snapshots/1695214309-msft-sites-prf-s-3-dispatcher4westus2", "message": "Microsoft.Compute/snapshots/write", "hierarchy":

**Comment by joshfree** [comment]
@weidongxu-microsoft could you please assist @hemasundars

**Comment by weidongxu-microsoft** [comment]
@hemasundars 

What did you client do to the `Mono<Snapshot> monoSnapshot` in the response? Is it consumed somewhere? Could you provide a code snippet consume the `Mono`?

Alternatively, could you try just do `monoSnapshot.block()` as a test, and see if it would got 499 or not.

**Comment by hemasundars** [comment]
@weidongxu-microsoft  Here is the same code we are using. 
               final Creatable<Snapshot> snapshotCreatable = client.snapshots()
                .define(snapshotName)
                .withRegion(region)
                .withExistingResourceGroup(resourceGroup)
                .withDataFromDisk(diskFromId)
                .withIncremental(true)
                .withTags(tags);

                final Mono<Snapshot> monoSnapshot = snapshotCreatable.createAsync();

                // onError is the same for both sync and async tasks
                Consumer<Throwable> onError = throwable -> {
                    log.error("Snapshot creation of root disk failed for instance {}", backupInfo.getInstanceId(),
                        throwable);

               //onSucess 
                                   Consumer<Snapshot> onSuccess = snapshot -> {
                        log.info(String.format("Snapshot creation completed : %s", snapshot.name()));
                        updateStateForOndemandBackup(backupInfo, true);
                    };

**Comment by weidongxu-microsoft** [comment]
@hemasundars 

I mean which code consumes the `Mono<Snapshot> monoSnapshot`?

If no code consume it, and app ends with that state, the client could close during the request (as the thing is Async, and it running in a background thread). This likely causes 499.

Would you try adding
`Snapshot snapshot = monoSnapshot.block();`
as last line?

This may not what you want, but it would tell us whether 499 was caused by client close during network request (hence that request not finished).

**Comment by hemasundars** [comment]
@weidongxu-microsoft  We are already using block here is the next line of code. 
                    monoSnapshot.doOnSuccess(onSuccess)
                            .doOnError(onError)
                            .block();

**Comment by weidongxu-microsoft** [comment]
@hemasundars 

Thanks for the info.

The error log in your issue belongs to 2 snapshot.

One is `/resourceGroups/msft-sites-stg-s1-backup/providers/Microsoft.Compute/snapshots/1695114011-msft-sites-stg-s1-dispatcher2eastus2`. I think Ovi replied you that it is due to `IncrementalCopySourceInvalid` from service (potential race on creating snapshot?).

The other is "ClientClosedRequest" is `/resourceGroups/msft-sites-prf-s-3-backup/providers/Microsoft.Compute/snapshots/1695214309-msft-sites-prf-s-3-dispatcher4westus2`
Do you have the time of this issue? I searched ARM log around 9-18 to 9-20, I didn't find anything about "1695214309-msft-sites-prf-s-3-dispatcher4westus2"

**Comment by hemasundars** [comment]
@weidongxu-microsoft  created this request for foirst one  -> 695114011-msft-sites-stg-s1-dispatcher2eastus2. 

Second issue one OVi commented ->  1695214309-msft-sites-prf-s-3-dispatcher4westus2. Please ignore the second one for this issue

**Comment by weidongxu-microsoft** [comment]
@hemasundars 

Got it. So this issue is not related to "ClientClosedRequest".
May I update the title to e.g. "LRO failure after 16 seconds"? That should make it clearer.

If service response with Failed in LRO, SDK will throw ManagementException accordingly.

**Comment by hemasundars** [comment]
Yes @weidongxu-microsoft this is for LRO failure. I will check with OVI if need I will another request for IncrementalCopySourceInvalid.
