### ISSUE TITLE
[BUG] NullPointerException on the save method when id is specified with optimistic concurrency and JsonIgnore

### ISSUE THREAD

**Issue by MapFilterMagic** [Azure/azure-sdk-for-java#36887]
# Description
My team is attempting to set the `id` field on a document and are running into a `NullPointerException` from the `ReactiveCosmosTemplate` when saving the document off to the DB. We're utilizing optimistic concurrency with the use of `@Version` on an `_etag` field. Up until now, we had left the `id` field on the model unset, so Cosmos was just generating a random GUID for us. However, we now need to set this to a different unique value at the SDK level before saving it off into the database.

What we've found is that we cannot have all of the following at the same time without running into that `NullPointerException`
- Enforcement of optimistic concurrency at the SDK level via the use of `@Version` on an `_etag` field
- Use of `@JsonInclude(Include.NON_EMPTY)` on our persisted model
- Ability to set the `id` field from the SDK level (in our code) instead of leaving it unset and having Cosmos generate it for us

Eliminating any one of those three resolves the error. 

This appears to be the exact same issue we're running into except it involved `@JsonInclude(Include.NON_NULL)` (though the `NON_EMPTY` is very close to the same thing). However, it appears it was closed?:
- https://github.com/Azure/azure-sdk-for-java/issues/17724
- https://github.com/Azure/azure-sdk-for-java/issues/26967

Am I understanding that correctly?

# Steps to Reproduce
As stated above, doing all three of the following on or related to the same singular persistence model will result in the error upon invoking `save()`
- Enforcing optimistic concurrency at the SDK level via the use of `@Version` on an `_etag` field on the model
- Using `@JsonInclude(Include.NON_EMPTY)` on the model
- Setting the `id` field on the model at the SDK level (in our code) to any value before saving it to the database
- _All of the above assumes we're creating a new document in the database, not updating an existing one (as we can't get even past initial document creation because of this error)_

# Expected behavior
Does anyone see a path forward? Do we know what the resolution of the issue(s) was, or if it could be looked at again? **_Have we misunderstood how the SDK works, and will null and empty values be excluded in the document by Cosmos automatically?_**

**_We'd like to be able to omit null or empty values from the document, enforce optimistic concurrency, and set the document id field ourselves all at the same time without any error._**

# Stack Trace
```
java.lang.NullPointerException: null
	at com.azure.spring.data.cosmos.core.ReactiveCosmosTemplate.applyVersioning(ReactiveCosmosTemplate.java:817)
	at com.azure.spring.data.cosmos.core.ReactiveCosmosTemplate.upsert(ReactiveCosmosTemplate.java:470)
	at com.azure.spring.data.cosmos.repository.support.SimpleReactiveCosmosRepository.save(SimpleReactiveCosmosRepository.java:102)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker$RepositoryFragmentMethodInvoker.lambda$new$0(RepositoryMethodInvoker.java:289)
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.doInvoke(RepositoryMethodInvoker.java:137)
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.invoke(RepositoryMethodInvoker.java:121)
	at org.springframework.data.repository.core.support.RepositoryComposition$RepositoryFragments.invoke(RepositoryComposition.java:529)
	at org.springframework.data.repository.core.support.RepositoryComposition.invoke(RepositoryComposition.java:285)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$ImplementationMethodExecutionInterceptor.invoke(RepositoryFactorySupport.java:639)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:163)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:138)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
	at com.sun.proxy.$Proxy266.save(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
	at com.sun.proxy.$Proxy266.save(Unknown Source)
	at com.example.service.dao.ExampleDaoService.saveExampleEntity(ExampleDaoService.java:123)
	at com.example.service.example.ExampleService.doSomething(ExampleService.java:999)
	at com.exampo$$FastClassBySpringCGLIB$$2383bf94.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
	...
```

# Code Snippets

## Our Data Model
```
import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.Version;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.azure.spring.data.cosmos.core.mapping.Container;

@JsonInclude(Include.NON_EMPTY)
@Container(containerName = "my-container")
public class ExampleEntity implements PersistenceEntity {
    
    @Id
    private String id;
  
    @Version
    private String _etag;

    ...
    
    // also contains a variety of primitives and deeply nested POJOs
   
   ...

}
```

## Our Dao Layer

```
@Service
public class ExampleDaoService {
    @Autowired 
    private ExampleCosmosRepository exampleCosmosRepository;

    ...

    public void saveExampleEntity(ExampleEntity exampleEntity) {
        exampleCosmosReactiveRepository.save(exampleEntity).block();
    }
}
```

## Our Repository Layer

```
@Repository
public interface ExampleCosmosReactiveRepository extends ReactiveCosmosRepository<ExampleEntity, String> {
    // holds a few query methods
    ...
}
```

# Setup
- OS: MacOS
- IDE: N/A (Not running the app from an IDE)
- Java Version: 11
- Frameworks: Spring Boot
- Azure Cosmos DB (Core API)
- Libraries:
  * spring-boot-starter-parent: 2.6.6
  * spring-cloud.version: 2021.0.1
  * spring-cloud-azure-dependencies: 4.1.0
- Environment: Local machine

# Information Checklist
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by MapFilterMagic** [comment]
It appears that placing a  `@JsonInclude(Include.ALWAYS)` on the `_etag` field on the model resolves the error. Can anyone confirm that doing this won't mess with optimistic concurrency enforcement? Or if there's any way for me to tell if it is?

```java

import org.springframework.data.annotation.Version;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.azure.spring.data.cosmos.core.mapping.Container;

@JsonInclude(Include.NON_EMPTY)
@Container(containerName = "my-container")
public class ExampleEntity implements PersistenceEntity {

    @Id
    private String id;

    @JsonInclude(Include.ALWAYS)
    @Version
    private String _etag;

    ...

}
```

**Comment by Netyyyy** [comment]
Hi @kushagraThapar , please take a look

**Comment by kushagraThapar** [comment]
@MapFilterMagic - including _eTag field always should not cause any issues, that seems to be the right solution. 
The NPE happens because of the missing eTag field, so including it always makes sense!

**Comment by MapFilterMagic** [comment]
> @MapFilterMagic - including _eTag field always should not cause any issues, that seems to be the right solution. The NPE happens because of the missing eTag field, so including it always makes sense!

Sounds good. Will continue with the solution of always including the etag field. Thanks!

**Comment by kushagraThapar** [comment]
@MapFilterMagic - feel free to re-open if the issue still persists, thanks!
