### ISSUE TITLE
Private Endpoint question for Eventhub

### ISSUE THREAD

**Issue by liujiashunms** [Azure/azure-sdk-for-java#36973]
**Query/Question**
We encountered an issue with consuming messages from Eventhub after enabling and disabling the private endpoint (from networking on the portal). The error message displayed is as follows. We are using a connection string to connect to Eventhub, with version 5.15.0 for azure-messaging-eventhubs and 1.16.1 for azure-messaging-eventhubs-checkpointstore-blob.

reactor.core.Exceptions$ErrorCallbackNotImplemented: com.azure.core.amqp.exception.AmqpException: errorContext[NAMESPACE: ljstest.servicebus.windows.net. ERROR CONTEXT: N/A]
Caused by: com.azure.core.amqp.exception.AmqpException: errorContext[NAMESPACE: [namespace].servicebus.windows.net. ERROR CONTEXT: N/A]
	at com.azure.core.amqp.implementation.ExceptionUtil.toException(ExceptionUtil.java:85)
	at com.azure.core.amqp.implementation.handler.ConnectionHandler.notifyErrorContext(ConnectionHandler.java:351)
	at com.azure.core.amqp.implementation.handler.ConnectionHandler.onTransportError(ConnectionHandler.java:253)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:191)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291)
	at com.azure.core.amqp.implementation.ReactorExecutor.run(ReactorExecutor.java:91)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

**Comment by anuchandy** [comment]
@liujiashunms , could you provide more details, per log this is a transient error (arrived on transport) which will be logged and in the future load balancer cycles, the receiving should be resumed provided library can establish the connection.

**Comment by liujiashunms** [comment]
I dont think this is a transient issue, since I disabled PE for a week, but my Eventhub consumer is still not working. I am providing more logs,
[reactor-executor-1] ERROR reactor.core.publisher.Operators - Operator called default onErrorDropped
reactor.core.Exceptions$ErrorCallbackNotImplemented: com.azure.core.amqp.exception.AmqpException: errorContext[NAMESPACE: atlas-liujiashun.servicebus.windows.net. ERROR CONTEXT: N/A]
Caused by: com.azure.core.amqp.exception.AmqpException: errorContext[NAMESPACE: atlas-liujiashun.servicebus.windows.net. ERROR CONTEXT: N/A]
	at com.azure.core.amqp.implementation.ExceptionUtil.toException(ExceptionUtil.java:85)
	at com.azure.core.amqp.implementation.handler.ConnectionHandler.notifyErrorContext(ConnectionHandler.java:351)
	at com.azure.core.amqp.implementation.handler.ConnectionHandler.onTransportError(ConnectionHandler.java:253)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:191)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291)
	at com.azure.core.amqp.implementation.ReactorExecutor.run(ReactorExecutor.java:91)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
[reactor-executor-1] INFO com.azure.messaging.eventhubs.implementation.EventHubConnectionProcessor - {"az.sdk.message":"Transient error occurred. Retrying.","exception":"errorContext[NAMESPACE: atlas-liujiashun.servicebus.windows.net. ERROR CONTEXT: N/A]","entityPath":"test5","tryCount":0,"interval_ms":4511}
[reactor-executor-1] WARN com.azure.messaging.eventhubs.PartitionBasedLoadBalancer - Load balancing for event processor failed.
errorContext[NAMESPACE: atlas-liujiashun.servicebus.windows.net. ERROR CONTEXT: N/A]
Error occurred on partition: NONE. Error: com.azure.core.amqp.exception.AmqpException: errorContext[NAMESPACE: atlas-liujiashun.servicebus.windows.net. ERROR CONTEXT: N/A]
[reactor-executor-1] INFO com.azure.core.amqp.implementation.ReactorConnection - {"az.sdk.message":"onConnectionShutdown. Shutting down.","connectionId":"MF_1d768f_1696653236159","isTransient":false,"isInitiatedByClient":false,"shutdownMessage":"Finished processing pending tasks.","namespace":"atlas-liujiashun.servicebus.windows.net"}
[parallel-6] INFO com.azure.messaging.eventhubs.implementation.EventHubConnectionProcessor - {"az.sdk.message":"Requesting from upstream.","entityPath":"test5","tryCount":0}
[parallel-6] INFO com.azure.messaging.eventhubs.implementation.EventHubConnectionProcessor - {"az.sdk.message":"Connection not requested, yet. Requesting one.","entityPath":"test5"}
[parallel-6] INFO com.azure.messaging.eventhubs.EventHubClientBuilder - {"az.sdk.message":"Emitting a single connection.","connectionId":"MF_8b8d87_1696653245499"}
[parallel-6] INFO com.azure.messaging.eventhubs.implementation.EventHubConnectionProcessor - {"az.sdk.message":"Setting next AMQP channel.","entityPath":"test5"}
[pool-4-thread-1] INFO com.azure.messaging.eventhubs.PartitionBasedLoadBalancer - {"az.sdk.message":"Starting load balancer.","ownerId":"71bd5b10-c1dc-4cf4-86c9-d95b80354365"}
[pool-4-thread-1] INFO com.azure.messaging.eventhubs.PartitionBasedLoadBalancer - {"az.sdk.message":"Getting partitions from Event Hubs service.","entityPath":"test5"}
[pool-4-thread-1] INFO com.azure.core.amqp.implementation.ReactorConnection - {"az.sdk.message":"Creating and starting connection.","connectionId":"MF_8b8d87_1696653245499","hostName":"atlas-liujiashun.servicebus.windows.net","port":5671}
[pool-4-thread-1] INFO com.azure.core.amqp.implementation.ReactorExecutor - {"az.sdk.message":"Starting reactor.","connectionId":"MF_8b8d87_1696653245499"}
[reactor-executor-2] INFO com.azure.core.amqp.implementation.handler.ConnectionHandler - {"az.sdk.message":"onConnectionInit","connectionId":"MF_8b8d87_1696653245499","hostName":"atlas-liujiashun.servicebus.windows.net","namespace":"atlas-liujiashun.servicebus.windows.net"}
[reactor-executor-2] INFO com.azure.core.amqp.implementation.handler.ReactorHandler - {"az.sdk.message":"reactor.onReactorInit","connectionId":"MF_8b8d87_1696653245499"}
[reactor-executor-2] INFO com.azure.core.amqp.implementation.handler.ConnectionHandler - {"az.sdk.message":"onConnectionLocalOpen","connectionId":"MF_8b8d87_1696653245499","errorCondition":null,"errorDescription":null,"hostName":"atlas-liujiashun.servicebus.windows.net"}
[reactor-executor-2] INFO com.azure.core.amqp.implementation.handler.ConnectionHandler - {"az.sdk.message":"onConnectionBound","connectionId":"MF_8b8d87_1696653245499","hostName":"atlas-liujiashun.servicebus.windows.net","peerDetails":"atlas-liujiashun.servicebus.windows.net:5671"}
[reactor-executor-2] INFO com.azure.core.amqp.implementation.handler.StrictTlsContextSpi - SSLv2Hello was an enabled protocol. Filtering out.
[reactor-executor-2] WARN com.azure.core.amqp.implementation.handler.ConnectionHandler - {"az.sdk.message":"onTransportError","connectionId":"MF_8b8d87_1696653245499","errorCondition":"proton:io","errorDescription":null,"hostName":"atlas-liujiashun.servicebus.windows.net"}
[reactor-executor-2] INFO com.azure.core.amqp.implementation.ReactorConnection - {"az.sdk.message":"Disposing of ReactorConnection.","connectionId":"MF_8b8d87_1696653245499","isTransient":false,"isInitiatedByClient":false,"shutdownMessage":"errorContext[NAMESPACE: atlas-liujiashun.servicebus.windows.net. ERROR CONTEXT: N/A]"}
[reactor-executor-2] INFO com.azure.core.amqp.implementation.handler.ConnectionHandler - {"az.sdk.message":"onTransportClosed","connectionId":"MF_8b8d87_1696653245499","errorCondition":"proton:io","errorDescription":null,"hostName":"atlas-liujiashun.servicebus.windows.net"}
[reactor-executor-2] INFO com.azure.core.amqp.implementation.handler.TransportHandler - {"az.sdk.message":"onTransportClosed","connectionId":"MF_8b8d87_1696653245499","hostName":"atlas-liujiashun.servicebus.windows.net"}
[reactor-executor-2] INFO com.azure.core.amqp.implementation.handler.ConnectionHandler - {"az.sdk.message":"onConnectionUnbound","connectionId":"MF_8b8d87_1696653245499","hostName":"atlas-liujiashun.servicebus.windows.net","state":"ACTIVE","remoteState":"UNINITIALIZED"}
[reactor-executor-2] INFO com.azure.core.amqp.implementation.handler.ConnectionHandler - {"az.sdk.message":"onConnectionUnbound","connectionId":"MF_8b8d87_1696653245499","hostName":"atlas-liujiashun.servicebus.windows.net","state":"ACTIVE","remoteState":"UNINITIALIZED"}
[reactor-executor-2] INFO com.azure.core.amqp.implementation.handler.ConnectionHandler - {"az.sdk.message":"onConnectionFinal","connectionId":"MF_8b8d87_1696653245499","errorCondition":null,"errorDescription":null,"hostName":"atlas-liujiashun.servicebus.windows.net"}
[reactor-executor-2] INFO com.azure.core.amqp.implementation.ReactorConnection - {"az.sdk.message":"Closing executor.","connectionId":"MF_8b8d87_1696653245499"}
[reactor-executor-2] INFO com.azure.core.amqp.implementation.handler.ConnectionHandler - {"az.sdk.message":"onConnectionLocalClose","connectionId":"MF_8b8d87_1696653245499","errorCondition":null,"errorDescription":null,"hostName":"atlas-liujiashun.servicebus.windows.net"}
[reactor-executor-2] INFO com.azure.core.amqp.implementation.ReactorExecutor - {"az.sdk.message":"Processing all pending tasks and closing old reactor.","connectionId":"MF_8b8d87_1696653245499"}
[reactor-executor-2] INFO com.azure.core.amqp.implementation.ReactorDispatcher - {"az.sdk.message":"Reactor selectable is being disposed.","connectionId":"MF_8b8d87_1696653245499"}
[reactor-executor-2] INFO com.azure.core.amqp.implementation.ReactorConnection - {"az.sdk.message":"onConnectionShutdown. Shutting down.","connectionId":"MF_8b8d87_1696653245499","isTransient":false,"isInitiatedByClient":false,"shutdownMessage":"connectionId[MF_8b8d87_1696653245499] Reactor selectable is disposed.","namespace":"atlas-liujiashun.servicebus.windows.net"}
[reactor-executor-2] ERROR reactor.core.publisher.Operators - Operator called default onErrorDropped
reactor.core.Exceptions$ErrorCallbackNotImplemented: com.azure.core.amqp.exception.AmqpException: errorContext[NAMESPACE: atlas-liujiashun.servicebus.windows.net. ERROR CONTEXT: N/A]
Caused by: com.azure.core.amqp.exception.AmqpException: errorContext[NAMESPACE: atlas-liujiashun.servicebus.windows.net. ERROR CONTEXT: N/A]
	at com.azure.core.amqp.implementation.ExceptionUtil.toException(ExceptionUtil.java:85)
	at com.azure.core.amqp.implementation.handler.ConnectionHandler.notifyErrorContext(ConnectionHandler.java:351)
	at com.azure.core.amqp.implementation.handler.ConnectionHandler.onTransportError(ConnectionHandler.java:253)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:191)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291)
	at com.azure.core.amqp.implementation.ReactorExecutor.run(ReactorExecutor.java:91)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

**Comment by conniey** [comment]
The underlying protocol is stateful, can you provide 5-10 minutes of logs _before_ this error occurs? The error by itself isn't enough to tell us where it failed.  I am also surprised that there is no message or ErrorCondition in the AMQP exception.
