### ISSUE TITLE
[BUG] logprobs, best_of and echo parameters are not available on gpt-35-turbo model

### ISSUE THREAD

**Issue by nmaoez** [Azure/azure-sdk-for-java#37082]
The code example for a simple completion at [GetCompletionsSample.java](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/openai/azure-ai-openai/src/samples/java/com/azure/ai/openai/usage/GetCompletionsSample.java) is not working with the current GPT-35-Turbo version 0301, which we have deployed (we only got the first review done). Everytime I execute the sample I get the following exception:

```
Exception in thread "main" com.azure.core.exception.HttpResponseException: Status code 400, "{"error":{"code":"BadRequest","message":"logprobs, best_of and echo parameters are not available on gpt-35-turbo model. Please remove the parameter and try again. For more details, see https://go.microsoft.com/fwlink/?linkid=2227346."}}"
	at com.azure.core.implementation.http.rest.RestProxyBase.instantiateUnexpectedException(RestProxyBase.java:337)
	at com.azure.core.implementation.http.rest.SyncRestProxy.ensureExpectedStatus(SyncRestProxy.java:130)
	at com.azure.core.implementation.http.rest.SyncRestProxy.handleRestReturnType(SyncRestProxy.java:213)
	at com.azure.core.implementation.http.rest.SyncRestProxy.invoke(SyncRestProxy.java:81)
	at com.azure.core.implementation.http.rest.RestProxyBase.invoke(RestProxyBase.java:109)
	at com.azure.core.http.rest.RestProxy.invoke(RestProxy.java:91)
	at com.sun.proxy.$Proxy3.getCompletionsSync(Unknown Source)
	at com.azure.ai.openai.implementation.OpenAIClientImpl.getCompletionsWithResponse(OpenAIClientImpl.java:904)
	at com.azure.ai.openai.OpenAIClient.getCompletionsWithResponse(OpenAIClient.java:222)
	at com.azure.ai.openai.OpenAIClient.getCompletions(OpenAIClient.java:587)
```

The error message is not entirely unexpected since documentation states that the parametes `logprobs`, `best_of`, and `echo` are not available with the new GPT-35-Turbo and GPT-4 models: https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/chatgpt?pivots=programming-language-chat-completions#output

This is the following snippet I am running:

```java
public static void main(String[] args) {
    String azureOpenaiKey = "...";
    String endpoint = "...";
    String deploymentOrModelId = "...";

    OpenAIClient client = new OpenAIClientBuilder()
            .endpoint(endpoint)
            .credential(new AzureKeyCredential(azureOpenaiKey))
            .buildClient();

    List<String> prompt = new ArrayList<>();
    prompt.add("Say this is a test");

    Completions completions = client.getCompletions(deploymentOrModelId, new CompletionsOptions(prompt));

    System.out.printf("Model ID=%s is created at %s.%n", completions.getId(), completions.getCreatedAt());
    for (Choice choice : completions.getChoices()) {
      System.out.printf("Index: %d, Text: %s.%n", choice.getIndex(), choice.getText());
    }
  }
```

Since I do not explicitly set the stated parameters, the associated values should be `null`. I suspect, that within the request all parameters will be sent, even when they are set to `null`?

And/Or are the samples outdated? What should I have to change within the snippet to get a successful completion?

**Setup:**
 - OS: Windows 11 Pro 22H2
 - IDE: IntelliJ IDEA 2023.1.2 (Ultimate Edition)
 - Library/Libraries: [com.azure:azure-ai-openai:1.0.0-beta.5](https://mvnrepository.com/artifact/com.azure/azure-ai-openai/1.0.0-beta.5)
 - Java version: 11

**Comment by nmaoez** [comment]
The workaround at https://github.com/Azure/azure-sdk-for-java/issues/36054 help me fixing my problem, since I integrated both dependencies:
* `com.azure:azure-ai-openai:1.0.0-beta.5`
* `com.azure:azure-search-documents:11.5.11`
