### ISSUE TITLE
[BUG] Authenticating using a PFX certificate fails when using `pfxCertificate(String)` or `pfxCertificate(InputStream)`

### ISSUE THREAD

**Issue by vcolin7** [Azure/azure-sdk-for-java#37210]
**Describe the bug**
While using the new beta version of Azure Identity (`1.11.0-beta.1`), authenticating using a PFX certificate fails with the message:
```
"PEM certificate provided does not contain -----BEGIN CERTIFICATE-----END CERTIFICATE----- block"
```

***Exception or Stack Trace***
```
Exception in thread "main" java.lang.IllegalArgumentException: PEM certificate provided does not contain -----BEGIN CERTIFICATE-----END CERTIFICATE----- block
	at com.azure.identity.implementation.util.CertificateUtil.publicKeyFromPem(CertificateUtil.java:79)
	at com.azure.identity.implementation.IdentityClientBase.getConfidentialClient(IdentityClientBase.java:190)
	at com.azure.identity.implementation.IdentitySyncClient.lambda$new$2(IdentitySyncClient.java:91)
	at com.azure.identity.implementation.SynchronousAccessor.getValue(SynchronousAccessor.java:45)
	at com.azure.identity.implementation.IdentitySyncClient.authenticateWithConfidentialClient(IdentitySyncClient.java:130)
	at com.azure.identity.ClientCertificateCredential.getTokenSync(ClientCertificateCredential.java:137)
	at com.azure.core.implementation.AccessTokenCache.lambda$new$2(AccessTokenCache.java:62)
	at com.azure.core.implementation.AccessTokenCache.lambda$retrieveTokenSync$9(AccessTokenCache.java:224)
	at com.azure.core.implementation.AccessTokenCache.getTokenSync(AccessTokenCache.java:88)
	at com.azure.core.http.policy.BearerTokenAuthenticationPolicy.setAuthorizationHeaderHelperSync(BearerTokenAuthenticationPolicy.java:183)
	at com.azure.core.http.policy.BearerTokenAuthenticationPolicy.setAuthorizationHeaderSync(BearerTokenAuthenticationPolicy.java:169)
	at com.azure.security.keyvault.certificates.implementation.KeyVaultCredentialPolicy.authorizeRequestSync(KeyVaultCredentialPolicy.java:227)
	at com.azure.core.http.policy.BearerTokenAuthenticationPolicy.processSync(BearerTokenAuthenticationPolicy.java:131)
	at com.azure.core.http.HttpPipelineNextSyncPolicy.processSync(HttpPipelineNextSyncPolicy.java:41)
	at com.azure.core.http.policy.RetryPolicy.attemptSync(RetryPolicy.java:164)
	at com.azure.core.http.policy.RetryPolicy.attemptSync(RetryPolicy.java:176)
	at com.azure.core.http.policy.RetryPolicy.attemptSync(RetryPolicy.java:176)
	at com.azure.core.http.policy.RetryPolicy.attemptSync(RetryPolicy.java:176)
	at com.azure.core.http.policy.RetryPolicy.processSync(RetryPolicy.java:114)
	at com.azure.core.http.HttpPipelineNextSyncPolicy.processSync(HttpPipelineNextSyncPolicy.java:41)
	at com.azure.core.http.policy.AddHeadersPolicy.processSync(AddHeadersPolicy.java:39)
	at com.azure.core.http.HttpPipelineNextSyncPolicy.processSync(HttpPipelineNextSyncPolicy.java:41)
	at com.azure.core.http.policy.HttpPipelineSyncPolicy.processSync(HttpPipelineSyncPolicy.java:42)
	at com.azure.core.http.policy.UserAgentPolicy.processSync(UserAgentPolicy.java:153)
	at com.azure.core.http.HttpPipelineNextSyncPolicy.processSync(HttpPipelineNextSyncPolicy.java:41)
	at com.azure.core.http.HttpPipeline.sendSync(HttpPipeline.java:131)
	at com.azure.core.implementation.http.rest.SyncRestProxy.send(SyncRestProxy.java:54)
	at com.azure.core.implementation.http.rest.SyncRestProxy.invoke(SyncRestProxy.java:75)
	at com.azure.core.implementation.http.rest.RestProxyBase.invoke(RestProxyBase.java:109)
	at com.azure.core.http.rest.RestProxy.invoke(RestProxy.java:91)
	at jdk.proxy2/jdk.proxy2.$Proxy3.getCertificateWithPolicy(Unknown Source)
	at com.azure.security.keyvault.certificates.implementation.CertificateClientImpl.getCertificateWithResponse(CertificateClientImpl.java:1108)
	at com.azure.security.keyvault.certificates.CertificateClient.getCertificateWithResponse(CertificateClient.java:309)
	at com.azure.security.keyvault.certificates.CertificateClient.getCertificate(CertificateClient.java:282)
	at CertificateAuthentication.main(CertificateAuthentication.java:133)

```

**To Reproduce**
1. Create a service principal that authenticates with a certificate created in Key Vault (as shown [here](https://learn.microsoft.com/azure/developer/java/sdk/identity-service-principal-auth)) and give access to said SP to an Azure resource. In my case, I gave it access to one of my key vaults.
2. Download the certificate from the Azure Portal as a PEM/PFX:
![image](https://github.com/Azure/azure-sdk-for-java/assets/5799331/08f316aa-40a8-4bbd-9e59-3f2b30dce11c)
3. Create a client to connect to the service that authenticates with a `ClientCertificateCredential`.

***Code Snippet***
```java
ClientCertificateCredential clientCertificateCredential = new ClientCertificateCredentialBuilder()
    .clientId("<client-id>")
    .tenantId(System.getenv("<tenant-id>"))
    .pfxCertificate("<certificate-path>")
    .build();

CertificateClient certificateClient = certificateClientBuilder
    .vaultUrl("<key-vault-url>")
    .credential(clientCertificateCredential)
    .buildClient();

KeyVaultCertificate myCertificate = certificateClient .getCertificate("<certificate-name>");

System.out.println("Success! Retrieved certificate with name: " + myCertificate.getName());
```

You can find a more complete code sample [here](https://github.com/vcolin7/CertificateAuthenticationSample/tree/issue).

**Expected behavior**
The application should authenticate just like when you use `pfxCertificate(<"certificate-path">, "")` with an empty string. The reason this issue happens is because the `IdentityBaseClient` assumes a provided certificate is in PEM format if the provided password is `null`, which is the default for the new APIs that take a `String` or `InputStream` only. In fact, if you use the older `pfxCertificate(<"certificate-path">, null)` with `null` as there password, you'll see the same results.

**Setup (please complete the following information):**
 - OS: Windows 11
 - IDE: IntelliJ
 - Library/Libraries: com.azure:azure-identity:1.11.0-beta.1
 - Java version: 8+

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by billwert** [comment]
@g2vinay This is an interesting case and at least we should have a better error. I think maybe we need a fuller walkthrough of the scenarios though.

**Comment by joshfree** [comment]
@g2vinay @billwert chat with @vcolin7 offline - as this was coming up for some KV scenarios.

**Comment by joshfree** [comment]
@billwert could you please update the issue / milestone accordingly
