### ISSUE TITLE
[BUG] Failed connection to Azure due to NoSuchMethodError

### ISSUE THREAD

**Issue by snalli** [Azure/azure-sdk-for-java#37223]
**Describe the bug**

Connection to azure blob storage is failing due NoSuchMethod error

***Exception or Stack Trace***

The first error is causing the second one

https://github.com/reactor/reactor-core/blob/v3.4.23/reactor-core/src/main/java/reactor/core/publisher/MonoSink.java
We have reactor-core 3.4.23 and it has the method, so IDK why the code fails !!

```
reactor.core.Exceptions$ReactiveException: java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 60000ms in 'map' (and no fallback has been configured)
        at reactor.core.Exceptions.propagate(Exceptions.java:392) ~[com.linkedin.li-couchbase-client.li-couchbase-client-impl-1.0.0.jar:?]
        at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:97) ~[com.linkedin.li-couchbase-client.li-couchbase-client-impl-1.0.0.jar:?]
        at reactor.core.publisher.Flux.blockLast(Flux.java:2645) ~[com.linkedin.li-couchbase-client.li-couchbase-client-impl-1.0.0.jar:?]
        at com.azure.core.util.paging.ContinuablePagedByIteratorBase.requestPage(ContinuablePagedByIteratorBase.java:102) ~[com.azure.azure-core-1.34.0.jar:1.34.0]
        at com.azure.core.util.paging.ContinuablePagedByItemIterable$ContinuablePagedByItemIterator.<init>(ContinuablePagedByItemIterable.java:75) ~[com.azure.azure-core-1.34.0.jar:1.34.0]
        at com.azure.core.util.paging.ContinuablePagedByItemIterable.iterator(ContinuablePagedByItemIterable.java:55) ~[com.azure.azure-core-1.34.0.jar:1.34.0]
        at com.azure.core.util.paging.ContinuablePagedIterable.iterator(ContinuablePagedIterable.java:141) ~[com.azure.azure-core-1.34.0.jar:1.34.0]
```

```
java.lang.NoSuchMethodError: 'reactor.util.context.ContextView reactor.core.publisher.MonoSink.contextView()'
        at reactor.netty.http.client.HttpClientConnect$HttpObserver.<init>(HttpClientConnect.java:330) ~[io.projectreactor.netty.reactor-netty-http-1.0.23.jar:1.0.23]
        at reactor.netty.http.client.HttpClientConnect$MonoHttpConnect.lambda$subscribe$0(HttpClientConnect.java:260) ~[io.projectreactor.netty.reactor-netty-http-1.0.23.jar:1.0.23]
        at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:57) ~[com.linkedin.li-couchbase-client.li-couchbase-client-impl-1.0.0.jar:?]
        at reactor.core.publisher.FluxRetryWhen.subscribe(FluxRetryWhen.java:77) ~[com.linkedin.li-couchbase-client.li-couchbase-client-impl-1.0.0.jar:?]
        at reactor.core.publisher.MonoRetryWhen.subscribeOrReturn(MonoRetryWhen.java:46) ~[com.linkedin.li-couchbase-client.li-couchbase-client-impl-1.0.0.jar:?]
        at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57) ~[com.linkedin.li-couchbase-client.li-couchbase-client-impl-1.0.0.jar:?]
        at reactor.netty.http.client.HttpClientConnect$MonoHttpConnect.subscribe(HttpClientConnect.java:273) ~[io.projectreactor.netty.reactor-netty-http-1.0.23.jar:1.0.23]
        at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[com.linkedin.li-couchbase-client.li-couchbase-client-impl-1.0.0.jar:?]
        at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) ~[com.linkedin.li-couchbase-client.li-couchbase-client-impl-1.0.0.jar:?]
        at reactor.core.publisher.FluxRetryWhen.subscribe(FluxRetryWhen.java:77) ~[com.linkedin.li-couchbase-client.li-couchbase-client-impl-1.0.0.jar:?]
        at reactor.core.publisher.MonoRetryWhen.subscribeOrReturn(MonoRetryWhen.java:46) ~[com.linkedin.li-couchbase-client.li-couchbase-client-impl-1.0.0.jar:?]
        at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57) ~[com.linkedin.li-couchbase-client.li-couchbase-client-impl-1.0.0.jar:?]
        at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:236) ~[com.linkedin.li-couchbase-client.li-couchbase-client-impl-1.0.0.jar:?]
        at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51) ~[com.linkedin.li-couchbase-client.li-couchbase-client-impl-1.0.0.jar:?]
        at reactor.core.publisher.Mono.subscribe(Mono.java:4400) ~[com.linkedin.li-couchbase-client.li-couchbase-client-impl-1.0.0.jar:?]
        at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:200) ~[com.linkedin.li-couchbase-client.li-couchbase-client-impl-1.0.0.jar:?]
        at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53) ~[com.linkedin.li-couchbase-client.li-couchbase-client-impl-1.0.0.jar:?]
        at reactor.core.publisher.FluxFromMonoOperator.subscribe(FluxFromMonoOperator.java:76) ~[com.linkedin.li-couchbase-client.li-couchbase-client-impl-1.0.0.jar:?]
        at reactor.core.publisher.FluxDefer.subscribe(FluxDefer.java:54) ~[com.linkedin.li-couchbase-client.li-couchbase-client-impl-1.0.0.jar:?]
        at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[com.linkedin.li-couchbase-client.li-couchbase-client-impl-1.0.0.jar:?]
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157) ~[com.linkedin.li-couchbase-client.li-couchbase-client-impl-1.0.0.jar:?]
        at reactor.core.publisher.MonoDelay$MonoDelayRunnable.propagateDelay(MonoDelay.java:271) ~[com.linkedin.li-couchbase-client.li-couchbase-client-impl-1.0.0.jar:?]
        at reactor.core.publisher.MonoDelay$MonoDelayRunnable.run(MonoDelay.java:286) ~[com.linkedin.li-couchbase-client.li-couchbase-client-impl-1.0.0.jar:?]
        at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68) [com.linkedin.li-couchbase-client.li-couchbase-client-impl-1.0.0.jar:?]
        at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28) [com.linkedin.li-couchbase-client.li-couchbase-client-impl-1.0.0.jar:?]
```

**To Reproduce**

Run the code snippet below if you can

***Code Snippet***

```
  protected void testAzureStorageConnectivity() {
    logger.info("Testing Azure Storage connectivity");
    PagedIterable<BlobContainerItem> blobContainerItemPagedIterable = azureStorageClient.listBlobContainers();
    for (BlobContainerItem blobContainerItem : blobContainerItemPagedIterable) {
      logger.info("Azure blob storage container = {}", blobContainerItem.getName());
      break;
    }
    logger.info("Successful connection to Azure Storage");
  }

```

**Expected behavior**

`testAzureStorageConnectivity` must succeed

**Screenshots**

None

**Setup (please complete the following information):**
 - OS: [e.g. iOS] Linux
 - IDE: [e.g. IntelliJ] IntelliJ
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)] azure-core:1.34.0
 - Java version: [e.g. 8] JDK-11_0_8-msft
 - App Server/Environment: [e.g. Tomcat, WildFly, Azure Function, Apache Spark, Databricks, IDE plugin or anything special]
 - Frameworks: [e.g. Spring Boot, Micronaut, Quarkus, etc] 

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x ] Bug Description Added
- [x ] Repro Steps Added
- [x ] Setup information Added

**Comment by alzimmermsft** [comment]
Thanks for filing this issue @snalli.

Could you provide the output of `mvn dependency:tree -Dverbose` on your project, as this will list which version of Reactor is being resolved and why as well as any versions omitted.

**Comment by snalli** [comment]
```
mvn dependency:tree -Dverbose
zsh: command not found: mvn
```
 We don't use maven. We use gradle.

**Comment by alzimmermsft** [comment]
Oh, for Gradle it would be `gradle dependencies --scan`

**Comment by snalli** [comment]
![Screenshot 2023-10-18 at 1 25 41 PM](https://github.com/Azure/azure-sdk-for-java/assets/1379846/5da966f6-6be3-4475-a9ee-0f969bdc53c8)

**Comment by snalli** [comment]
![Screenshot 2023-10-18 at 1 32 19 PM](https://github.com/Azure/azure-sdk-for-java/assets/1379846/649d4553-985c-41a0-9484-b6d46f97a6e6)

**Comment by snalli** [comment]
reactor-core is at 3.4.26, lets chat on teams

**Comment by snalli** [comment]
```
2023/10/18 18:54:14.854 ERROR [Schedulers] [cosmos-parallel-1] [ambry-vcr] [] Scheduler worker in group main failed with an uncaught exception
java.lang.NoSuchMethodError: 'reactor.util.context.ContextView reactor.core.publisher.MonoSink.contextView()'
        at reactor.netty.http.client.HttpClientConnect$HttpObserver.<init>(HttpClientConnect.java:330) ~[io.projectreactor.netty.reactor-netty-http-1.0.23.jar:1.0.23]
        at reactor.netty.http.client.HttpClientConnect$MonoHttpConnect.lambda$subscribe$0(HttpClientConnect.java:260) ~[io.projectreactor.netty.reactor-netty-http-1.0.23.jar:1.0.23]
        at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:57) ~[com.linkedin.li-couchbase-client.li-couchbase-client-impl-1.0.0.jar:?]
        at reactor.core.publisher.FluxRetryWhen.subscribe(FluxRetryWhen.java:77) ~[com.linkedin.li-couchbase-client.li-couchbase-client-impl-1.0.0.jar:?]
        at reactor.core.publisher.MonoRetryWhen.subscribeOrReturn(MonoRetryWhen.java:46) ~[com.linkedin.li-couchbase-client.li-couchbase-client-impl-1.0.0.jar:?]
        at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57) ~[com.linkedin.li-couchbase-client.li-couchbase-client-impl-1.0.0.jar:?]
        at reactor.netty.http.client.HttpClientConnect$MonoHttpConnect.subscribe(HttpClientConnect.java:273) ~[io.projectreactor.netty.reactor-netty-http-1.0.23.jar:1.0.23]
        at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[com.linkedin.li-couchbase-client.li-couchbase-client-impl-1.0.0.jar:?]
        at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) ~[com.linkedin.li-couchbase-client.li-couchbase-client-impl-1.0.0.jar:?]
        at reactor.core.publisher.FluxRetryWhen.subscribe(FluxRetryWhen.java:77) ~[com.linkedin.li-couchbase-client.li-couchbase-client-impl-1.0.0.jar:?]
        at reactor.core.publisher.MonoRetryWhen.subscribeOrReturn(MonoRetryWhen.java:46) ~[com.linkedin.li-couchbase-client.li-couchbase-client-impl-1.0.0.jar:?]
        at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57) ~[com.linkedin.li-couchbase-client.li-couchbase-client-impl-1.0.0.jar:?]
        at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:236) ~[com.linkedin.li-couchbase-client.li-couchbase-client-impl-1.0.0.jar:?]
        at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51) ~[com.linkedin.li-couchbase-client.li-couchbase-client-impl-1.0.0.jar:?]
        at reactor.core.publisher.Mono.subscribe(Mono.java:4400) ~[com.linkedin.li-couchbase-client.li-couchbase-client-impl-1.0.0.jar:?]
        at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:200) ~[com.linkedin.li-couchbase-client.li-couchbase-client-impl-1.0.0.jar:?]
        at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53) ~[com.linkedin.li-couchbase-client.li-couchbase-client-impl-1.0.0.jar:?]
        at reactor.core.publisher.FluxFromMonoOperator.subscribe(FluxFromMonoOperator.java:76) ~[com.linkedin.li-couchbase-client.li-couchbase-client-impl-1.0.0.jar:?]
        at reactor.core.publisher.FluxDefer.subscribe(FluxDefer.java:54) ~[com.linkedin.li-couchbase-client.li-couchbase-client-impl-1.0.0.jar:?]
        at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[com.linkedin.li-couchbase-client.li-couchbase-client-impl-1.0.0.jar:?]
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157) ~[com.linkedin.li-couchbase-client.li-couchbase-client-impl-1.0.0.jar:?]
        at reactor.core.publisher.MonoDelay$MonoDelayRunnable.propagateDelay(MonoDelay.java:271) ~[com.linkedin.li-couchbase-client.li-couchbase-client-impl-1.0.0.jar:?]
        at reactor.core.publisher.MonoDelay$MonoDelayRunnable.run(MonoDelay.java:286) ~[com.linkedin.li-couchbase-client.li-couchbase-client-impl-1.0.0.jar:?]
        at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68) [com.linkedin.li-couchbase-client.li-couchbase-client-impl-1.0.0.jar:?]
        at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28) [com.linkedin.li-couchbase-client.li-couchbase-client-impl-1.0.0.jar:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by alzimmermsft** [comment]
Per the offline discussion, it was noted that multiple Azure SDK libraries were being used in the application from different points in time. Recommendation is to use `azure-sdk-bom` to manage all Azure SDK dependencies so that they are from the same release cycle, reducing potential dependency conflicts between Azure SDKs.
 
Further investigation found that another library was pulling in an older version of Reactor which resulted in Reactor being resolved to a version before `MonoSink.contextView()` was introduced. `MonoSink.contextView()` was introduced in reactor-core 3.4.17.
