### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by fredysierra** [Azure/azure-sdk-for-java#37337]
**Describe the bug**
I am using `spring-cloud-azure-stream-binder-servicebus` to connect to Azure servicebus.  The application has other binders like  `spring-cloud-stream-binder-kafka` and `spring-cloud-stream-binder-rabbit` as maven dependencies.

When configuring  `default-binder: servicebus` I am getting `Unknown binder configuration: servicebus` when the application is trying to start.  

Here is my configuration:

```yaml
spring:
  cloud:
    azure:
      credential:
        client-id: ${AZURE_CLIENT_ID}
        client-secret: ${AZURE_CLIENT_SECRET}
      profile:
        tenant-id: ${AZURE_TENANT_ID}
        subscription-id: ${SUBSCRIPTION_ID}
      servicebus:
        enabled: true
        entity-type: topic
        resource:
          resource-group: ${RESOURCE_GROUP}
        namespace: ${SERVICEBUS_NAMESPACE}
    stream:
      function.definition: consume
      bindings:
        consume-in-0.destination: topic0
        consume-in-0.group: sub0
        hello-out-0.destination: topic0
      servicebus:
        bindings:
          consume-in-0.consumer.auto-complete: false
          hello-out-0.producer.entity-type: topic
      default-binder: servicebus
```

***Exception or Stack Trace***
```
2023-10-24T10:56:07.010+02:00  INFO 13738 --- [           main] o.s.i.monitor.IntegrationMBeanExporter   : Registering MessageHandler _org.springframework.integration.errorLogger
2023-10-24T10:56:07.029+02:00  INFO 13738 --- [           main] o.s.i.endpoint.EventDrivenConsumer       : Adding {logging-channel-adapter:_org.springframework.integration.errorLogger} as a subscriber to the 'errorChannel' channel
2023-10-24T10:56:07.029+02:00  INFO 13738 --- [           main] o.s.i.channel.PublishSubscribeChannel    : Channel 'application.errorChannel' has 1 subscriber(s).
2023-10-24T10:56:07.030+02:00  INFO 13738 --- [           main] o.s.i.endpoint.EventDrivenConsumer       : started bean '_org.springframework.integration.errorLogger'
2023-10-24T10:56:07.042+02:00  INFO 13738 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
2023-10-24T10:56:07.044+02:00  INFO 13738 --- [           main] o.s.c.s.binder.DefaultBinderFactory      : Creating binder: servicebus
2023-10-24T10:56:07.044+02:00  INFO 13738 --- [           main] o.s.c.s.binder.DefaultBinderFactory      : Constructing binder child context for servicebus
2023-10-24T10:56:07.044+02:00  WARN 13738 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Failed to start bean 'inputBindingLifecycle'
2023-10-24T10:56:07.045+02:00  INFO 13738 --- [           main] o.s.i.endpoint.EventDrivenConsumer       : Removing {logging-channel-adapter:_org.springframework.integration.errorLogger} as a subscriber to the 'errorChannel' channel
2023-10-24T10:56:07.045+02:00  INFO 13738 --- [           main] o.s.i.channel.PublishSubscribeChannel    : Channel 'application.errorChannel' has 0 subscriber(s).
2023-10-24T10:56:07.045+02:00  INFO 13738 --- [           main] o.s.i.endpoint.EventDrivenConsumer       : stopped bean '_org.springframework.integration.errorLogger'
2023-10-24T10:56:07.067+02:00  INFO 13738 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2023-10-24T10:56:07.087+02:00  INFO 13738 --- [           main] .s.b.a.l.ConditionEvaluationReportLogger : 

Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2023-10-24T10:56:07.111+02:00 ERROR 13738 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.context.ApplicationContextException: Failed to start bean 'inputBindingLifecycle'
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:182) ~[spring-context-6.0.12.jar:6.0.12]
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:357) ~[spring-context-6.0.12.jar:6.0.12]
	at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[na:na]
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:156) ~[spring-context-6.0.12.jar:6.0.12]
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:124) ~[spring-context-6.0.12.jar:6.0.12]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:958) ~[spring-context-6.0.12.jar:6.0.12]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:611) ~[spring-context-6.0.12.jar:6.0.12]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[spring-boot-3.1.4.jar:3.1.4]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:737) ~[spring-boot-3.1.4.jar:3.1.4]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:439) ~[spring-boot-3.1.4.jar:3.1.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-3.1.4.jar:3.1.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1309) ~[spring-boot-3.1.4.jar:3.1.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1298) ~[spring-boot-3.1.4.jar:3.1.4]
	at com.example.azure.scsservicebus.ScsServiceBusApplication.main(ScsServiceBusApplication.java:10) ~[classes/:na]
Caused by: java.lang.IllegalStateException: Unknown binder configuration: servicebus
	at org.springframework.util.Assert.state(Assert.java:76) ~[spring-core-6.0.12.jar:6.0.12]
	at org.springframework.cloud.stream.binder.DefaultBinderFactory.getBinderInstance(DefaultBinderFactory.java:330) ~[spring-cloud-stream-4.0.4.jar:4.0.4]
	at org.springframework.cloud.stream.binder.DefaultBinderFactory.doGetBinderConventional(DefaultBinderFactory.java:276) ~[spring-cloud-stream-4.0.4.jar:4.0.4]
	at org.springframework.cloud.stream.binder.DefaultBinderFactory.doGetBinder(DefaultBinderFactory.java:179) ~[spring-cloud-stream-4.0.4.jar:4.0.4]
	at org.springframework.cloud.stream.binder.DefaultBinderFactory.getBinder(DefaultBinderFactory.java:166) ~[spring-cloud-stream-4.0.4.jar:4.0.4]
	at org.springframework.cloud.stream.binding.BindingService.getBinder(BindingService.java:411) ~[spring-cloud-stream-4.0.4.jar:4.0.4]
	at org.springframework.cloud.stream.binding.BindingService.bindConsumer(BindingService.java:108) ~[spring-cloud-stream-4.0.4.jar:4.0.4]
	at org.springframework.cloud.stream.binding.AbstractBindableProxyFactory.createAndBindInputs(AbstractBindableProxyFactory.java:98) ~[spring-cloud-stream-4.0.4.jar:4.0.4]
	at org.springframework.cloud.stream.binding.InputBindingLifecycle.doStartWithBindable(InputBindingLifecycle.java:58) ~[spring-cloud-stream-4.0.4.jar:4.0.4]
	at java.base/java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:647) ~[na:na]
	at org.springframework.cloud.stream.binding.AbstractBindingLifecycle.start(AbstractBindingLifecycle.java:57) ~[spring-cloud-stream-4.0.4.jar:4.0.4]
	at org.springframework.cloud.stream.binding.InputBindingLifecycle.start(InputBindingLifecycle.java:34) ~[spring-cloud-stream-4.0.4.jar:4.0.4]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:179) ~[spring-context-6.0.12.jar:6.0.12]
	... 13 common frames omitted
```

**To Reproduce**
Regular spring boot application with `spring-cloud-azure-stream-binder-servicebus` and adding `spring-cloud-stream-binder-Kafka` as an additional binder. Try to define `default-binder: servicebus`. 

**Expected behavior**
I should be able to select any binder using `spring.cloud.stream.default-binder`

**Setup:**
 - Java 17
 - Library/Libraries: com.azure.spring:spring-cloud-azure-stream-binder-servicebus:5.5.0
                                 org.springframework.cloud:spring-cloud-stream-binder-kafka:3.2.7
		
 - Frameworks: 
      * Spring Boot 3.1.4 
      * Spring Cloud 2022.0.4

**Additional context**
The issue only happens when `spring-cloud-stream-binder-kafka` and `spring-cloud-azure-stream-binder-servicebus` are added as dependencies. For now, I found that adding `"spring.cloud.azure.eventhubs.kafka.enabled": "false"` will fix the issue. But I should not need other properties than `spring.cloud.stream.default-binder` to switch between binders. 

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by Netyyyy** [comment]
HI @fredysierra , thanks for reporting.
Could you help provide a minimal project, thanks

**Comment by fredysierra** [comment]
sure @Netyyyy . This is my [sample project](https://github.com/fredysierra/scs-service-bus) .

**Comment by moarychan** [comment]
PR merged in the new version 5.16.0, it will be available in the last few days.
