### ISSUE TITLE
[BUG] Create or update index fails due to NoSuchMethodError

### ISSUE THREAD

**Issue by dharun1995** [Azure/azure-sdk-for-java#37355]
**Describe the bug**
Creation of index fails due to NoSuchMethodError

***Exception or Stack Trace***
```
Exception in thread "main" java.lang.NoSuchMethodError: 'com.azure.core.implementation.ReflectiveInvoker com.azure.core.implementation.ReflectionUtils.createNoOpInvoker()'
	at com.azure.core.serializer.json.jackson.implementation.ObjectMapperShim.<clinit>(ObjectMapperShim.java:49)
	at com.azure.core.serializer.json.jackson.JacksonJsonSerializerBuilder.<clinit>(JacksonJsonSerializerBuilder.java:21)
	at com.azure.core.serializer.json.jackson.JacksonJsonSerializerProvider.createInstance(JacksonJsonSerializerProvider.java:21)
	at com.azure.core.serializer.json.jackson.JacksonJsonSerializerProvider.createInstance(JacksonJsonSerializerProvider.java:12)
	at com.azure.core.util.serializer.JsonSerializerProviders.createInstance(JsonSerializerProviders.java:53)
	at com.azure.core.util.BinaryData.<clinit>(BinaryData.java:175)
	at com.azure.core.implementation.http.rest.SyncRestProxy.updateRequest(SyncRestProxy.java:233)
	at com.azure.core.implementation.http.rest.RestProxyBase.configRequest(RestProxyBase.java:324)
	at com.azure.core.implementation.http.rest.RestProxyBase.createHttpRequest(RestProxyBase.java:269)
	at com.azure.core.implementation.http.rest.RestProxyBase.invoke(RestProxyBase.java:86)
	at com.azure.core.http.rest.RestProxy.invoke(RestProxy.java:95)
	at jdk.proxy2/jdk.proxy2.$Proxy7.createOrUpdateSync(Unknown Source)
	at com.azure.search.documents.indexes.implementation.IndexesImpl.createOrUpdateWithResponse(IndexesImpl.java:781)
	at com.azure.search.documents.indexes.SearchIndexClient.lambda$createOrUpdateIndexWithResponse$6(SearchIndexClient.java:450)
	at com.azure.search.documents.implementation.util.Utility.executeRestCallWithExceptionHandling(Utility.java:192)
	at com.azure.search.documents.indexes.SearchIndexClient.createOrUpdateIndexWithResponse(SearchIndexClient.java:447)
	at com.azure.search.documents.indexes.SearchIndexClient.createOrUpdateIndex(SearchIndexClient.java:411)
	at main.main.java.azure.search.sample.Acstestsub.main(Acstestsub.java:66)
```
**To Reproduce**
Run the code snippet below 
***Code Snippet***
```
public static void main(String[] args)
    {
        SearchIndexClient index_client = new SearchIndexClientBuilder().endpoint(endpoint).credential(credential).buildClient();
        SearchIndexerClient indexer_client = new SearchIndexerClientBuilder().endpoint(endpoint).credential(credential).buildClient();
        final String datasourceindexerName = "mydatasourceindexname";



        SearchIndex datasourceIndex = new SearchIndex(datasourceindexerName)
                .setFields(
                        new SearchField("ParentKey", SearchFieldDataType.STRING)
                                .setFilterable(true),
                        new SearchField("page", SearchFieldDataType.STRING),
                        new SearchField("ChunkKey", SearchFieldDataType.STRING)
                                .setKey(true)
                                .setAnalyzerName(LexicalAnalyzerName.KEYWORD),
                        new SearchField("vector", SearchFieldDataType.collection(SearchFieldDataType.SINGLE))
                                .setVectorSearchDimensions(1536)
                                .setVectorSearchProfile("vectorsearchprofile")
                                .setSearchable(true))

                .setVectorSearch(new VectorSearch()
                        .setAlgorithms(Collections.singletonList(new HnswVectorSearchAlgorithmConfiguration("algoconfig")))
                        .setProfiles(Collections.singletonList(new VectorSearchProfile("vectorsearchprofile", "algoconfig").setVectorizer("myvectorizer")))
                        .setVectorizers(Collections.singletonList(new AzureOpenAIVectorizer("myvectorizer")
                                .setAzureOpenAIParameters(new AzureOpenAIParameters()
                                        .setResourceUri("https://azs-openai.openai.azure.com")
                                        .setDeploymentId("text-embedding-ada-002")
                                        .setApiKey(openaikey)))));


        index_client.createOrUpdateIndex(datasourceIndex);
    }
```
**Expected behavior**
Index must be created
**Screenshots**

**Setup (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - IDE: [e.g. IntelliJ] IntelliJ
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)]
 - Java version: [e.g. 8] 17
 - App Server/Environment: [e.g. Tomcat, WildFly, Azure Function, Apache Spark, Databricks, IDE plugin or anything special]
 - Frameworks: [e.g. Spring Boot, Micronaut, Quarkus, etc] 

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by alzimmermsft** [comment]
Thank you for filing this issue @dharun1995, could you include a dependency tree from the project you're using? This appears to me to be a dependency conflict as in the latest versions of `azure-core` this API does exist:

https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/core/azure-core/src/main/java/com/azure/core/implementation/ReflectionUtils.java#L149

Which leads me to believe there is a dependency conflict with `azure-core` causing it to resolve to an older version.

**Comment by dharun1995** [comment]
Thanks @alzimmermsft for your insights. That could be the reason.
