### ISSUE TITLE
[BUG] Azure SDK java-monitor Build/Release Pipeline not stable

### ISSUE THREAD

**Issue by heyams** [Azure/azure-sdk-for-java#37386]
I frequently have issues with test-proxy for CI build and release pipelines.  
Rerun usually fixed it automatically, but recently it's getting worse. 4 reruns are required for today's release.
It's very time consuming on PR and releases. 
I wonder if you can have someone look into it.

[full stack trace](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3199561&view=logs&j=2bfc2942-81d9-5008-056a-175c0d0e8b91&t=11fca26e-81bb-54c4-81ae-117d352955bf&s=b49e7e65-b64b-557c-018e-3fd79c15ded6)

java.io.UncheckedIOException: io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer
	at com.azure.core.http.netty.NettyAsyncHttpClient.sendSync(NettyAsyncHttpClient.java:180)
	at com.azure.core.test.http.TestProxyPlaybackClient.stopPlayback(TestProxyPlaybackClient.java:136)
	at com.azure.core.test.InterceptorManager.close(InterceptorManager.java:365)
	at com.azure.core.test.TestBase.teardownTest(TestBase.java:201)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	

cc @srnagar @mssfang @trask

**Comment by srnagar** [comment]
@samvaity could you please take a look at this issue?
