### ISSUE TITLE
[BUG] Difference in URI handling behavior of % for Blob Storage between V8 and V12

### ISSUE THREAD

**Issue by georgew5656** [Azure/azure-sdk-for-java#37564]
**Describe the bug**
When trying to upgrade between V8 and V12 I have discovered differing behavior when handling % in a file path in blob storage.

On v8 the code looks like this:
```
  CloudBlobContainer container = getOrCreateCloudBlobContainer(containerName); // create a CloudBlobContainer
  try (FileInputStream stream = new FileInputStream(file)) {
    container.getBlockBlobReference(blobPath).upload(stream, file.length());
  }
```

On v12 the code looks like this:
```
    BlobContainerClient blobContainerClient = getOrCreateBlobContainerClient(containerName);

    try (FileInputStream stream = new FileInputStream(file)) {
      // By default this creates a Block blob, no need to use a specific Block blob client.
      blobContainerClient.getBlobClient(blobPath).upload(stream, file.length());
    }
```

Where blobPath is "ab2a7d5f-b973-4222-83ba-d0581817a819 %Россия 한국 中国!?/file" (anything with a %<something after it> works to trigger this issue)

The public docs say that the client should automatically handle url encoding (% is not in the reserved characters list) (https://learn.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-containers--blobs--and-metadata).

But when I upload a file with a unencoded special character name directly via the azure UI it seems to work okay.
The V8 client seems to follow this logic, as it will accept a unencoded special character name.

But the V12 client will throw an exception.
***Exception or Stack Trace***
```
[2023-11-08T16:46:06.435Z] Caused by: java.lang.IllegalArgumentException: URLDecoder: Illegal hex characters in escape (%) pattern - Error at index 0 in: "Ро"
[2023-11-08T16:46:06.435Z] 	at java.base/java.net.URLDecoder.decode(URLDecoder.java:232)
[2023-11-08T16:46:06.435Z] 	at java.base/java.net.URLDecoder.decode(URLDecoder.java:142)
[2023-11-08T16:46:06.435Z] 	at com.azure.storage.common.Utility.decode(Utility.java:88)
[2023-11-08T16:46:06.435Z] 	at com.azure.storage.common.Utility.urlDecode(Utility.java:55)
[2023-11-08T16:46:06.435Z] 	at com.azure.storage.blob.specialized.BlobAsyncClientBase.<init>(BlobAsyncClientBase.java:242)
[2023-11-08T16:46:06.435Z] 	at com.azure.storage.blob.specialized.BlobAsyncClientBase.<init>(BlobAsyncClientBase.java:206)
[2023-11-08T16:46:06.435Z] 	at com.azure.storage.blob.BlobAsyncClient.<init>(BlobAsyncClient.java:154)
[2023-11-08T16:46:06.435Z] 	at com.azure.storage.blob.BlobContainerAsyncClient.getBlobAsyncClient(BlobContainerAsyncClient.java:194)
[2023-11-08T16:46:06.435Z] 	at com.azure.storage.blob.BlobContainerAsyncClient.getBlobAsyncClient(BlobContainerAsyncClient.java:172)
[2023-11-08T16:46:06.435Z] 	at com.azure.storage.blob.BlobContainerClient.getBlobClient(BlobContainerClient.java:98)
```

**To Reproduce**
Try using the Java V12 blob client to upload a file with blobPath: "asdf%asdf"

***Code Snippet***
Linked these in the description

**Expected behavior**
I would expect the new client's behavior to be similar to both the docs and the UI, but right now the docs and the UI have different behavior.

**Screenshots**
N/A

**Setup (please complete the following information):**
 - OS: Ubuntu
 - IDE: N/A
 - Library/Libraries: azure-storage-blob:12.24.0
 - Java version: 8,11,17
 - App Server/Environment: N/A
 - Frameworks: N/A

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by ibrahimrabab** [comment]
Hi @georgew5656 
Thank you for reaching out with this issue! This indeed is an issue on the Java side, we are currently working on a fix and hope to have it out soon. Will update on this thread when the fix is out!
