### ISSUE TITLE
[BUG] TimeoutException using azure-messaging-eventhubs

### ISSUE THREAD

**Issue by loreanazic** [Azure/azure-sdk-for-java#37661]
**Describe the bug**
I am creating a consumer that receives two messages per day from Event Hub. Currently, the Event Hub queue is empty, and the following two warnings are occurring:

**Event hub**
Error occurred in partition processor for partition NONE, {}
java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 60000ms in 'filter' (and no fallback has been configured)
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.handleTimeout(FluxTimeout.java:295)
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.doTimeout(FluxTimeout.java:280)
	at reactor.core.publisher.FluxTimeout$TimeoutTimeoutSubscriber.onNext(FluxTimeout.java:419)
	at reactor.core.publisher.FluxOnErrorReturn$ReturnSubscriber.onNext(FluxOnErrorReturn.java:162)
	at reactor.core.publisher.MonoDelay$MonoDelayRunnable.propagateDelay(MonoDelay.java:271)
	at reactor.core.publisher.MonoDelay$MonoDelayRunnable.run(MonoDelay.java:286)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

**Azure storage**
[6e294b8e-11, L:/10.80.192.135:43898 - R:srgnpfovdev.blob.core.windows.net/20.209.10.75:443] The connection observed an error
java.util.concurrent.TimeoutException: Channel response timed out after 60000 milliseconds.
	at com.azure.core.http.netty.implementation.ResponseTimeoutHandler.responseTimedOut(ResponseTimeoutHandler.java:58)
	at com.azure.core.http.netty.implementation.ResponseTimeoutHandler.lambda$handlerAdded$0(ResponseTimeoutHandler.java:45)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:406)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

The code used is from the documentation: 

        val credential : TokenCredential? = tokenCredential();

        val blobContainerAsyncClient: BlobContainerAsyncClient = BlobContainerClientBuilder()
            .credential(credential)
            .endpoint("https://$accountName.blob.core.windows.net")
            .containerName(container)
            .buildAsyncClient()

        val eventProcessorClient: EventProcessorClient = EventProcessorClientBuilder()
            .credential(namespace, eventHubName, credential)
            .consumerGroup(consumerGroup)
            .checkpointStore(BlobCheckpointStore(blobContainerAsyncClient))
            .processEvent { eventContext -> processEvent(eventContext, publisherChannel) }
            .processError { eventError -> processError(eventError) }
            .buildEventProcessorClient()

        return eventProcessorClient;
    

**To Reproduce**
Warnings begin to occur when deploying the service on Kubernetes and happen every few hours.

**Expected behavior**
Do the warnings affect message consumption, or is there an automatic reconnection? If there is no automatic reconnection, how can I handle the warnings?

**Screenshots**
![image](https://github.com/Azure/azure-sdk-for-java/assets/27374423/efbc9c08-39f2-40b2-b3ed-a9e768d8cb85)

**Setup (please complete the following information):**
 - IntelliJ
 - Library/Libraries: spring-cloud-azure-dependencies (4.7.0), spring-cloud-dependencies 2021.0.5
 - kotlin  1.6.21
 - Spring Boot
 - Kubernetes

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by Netyyyy** [comment]
Hi @loreanazic  , thanks for reaching out.
We have received your submission and will take it into consideration. We appreciate your input and will review this matter as soon as possible.
Please feel free to provide any additional information or context that you think may be helpful. We'll keep you updated on the progress of our review.
Thank you for your contribution to improving our project.

**Comment by Netyyyy** [comment]
Hi @loreanazic , seems you build `eventProcessorClient` from `azure-messaging-eventhubs`, 
@conniey  please help take a look

**Comment by joshfree** [comment]
Closing old issue from November 2023 with no activity since then.  Please feel free to reactivate or open a new issue if this is incorrect.

/cc @conniey
