### ISSUE TITLE
[BUG] Cognitive Search no longer works with index aliases

### ISSUE THREAD

**Issue by jnunderwood** [Azure/azure-sdk-for-java#37680]
**Describe the bug**
In `azure-search-documents v11.6.0`, we can no longer perform searches using index ***aliases***; we have to use the actual index ***names*** instead. This was working in `v11.6.0-beta.10`.

***Exception or Stack Trace***
```
com.azure.core.exception.HttpResponseException: Status code 404, "{"error":{"code":"","message":"The index 'MYALIAS' for service 'MYSERVICE' was not found."}}"
	at com.azure.core.implementation.http.rest.RestProxyBase.instantiateUnexpectedException(RestProxyBase.java:330)
	at com.azure.core.implementation.http.rest.SyncRestProxy.ensureExpectedStatus(SyncRestProxy.java:125)
	at com.azure.core.implementation.http.rest.SyncRestProxy.handleRestReturnType(SyncRestProxy.java:202)
	at com.azure.core.implementation.http.rest.SyncRestProxy.invoke(SyncRestProxy.java:82)
	at com.azure.core.implementation.http.rest.RestProxyBase.invoke(RestProxyBase.java:110)
	at com.azure.core.http.rest.RestProxy.invoke(RestProxy.java:91)
	at jdk.proxy2/jdk.proxy2.$Proxy74.searchPostSync(Unknown Source)
	at com.azure.search.documents.implementation.DocumentsImpl.searchPostWithResponse(DocumentsImpl.java:618)
	at com.azure.search.documents.SearchClient.lambda$search$4(SearchClient.java:808)
	at com.azure.search.documents.implementation.util.Utility.executeRestCallWithExceptionHandling(Utility.java:192)
	at com.azure.search.documents.SearchClient.search(SearchClient.java:807)
	at com.azure.search.documents.SearchClient.lambda$search$2(SearchClient.java:794)
	at com.azure.search.documents.SearchClient.lambda$search$3(SearchClient.java:795)
	at com.azure.search.documents.util.SearchPagedIterable.lambda$new$0(SearchPagedIterable.java:62)
	at com.azure.core.util.paging.ContinuablePagedByIteratorBase.requestPage(ContinuablePagedByIteratorBase.java:104)
	at com.azure.core.util.paging.ContinuablePagedByItemIterable$ContinuablePagedByItemIterator.<init>(ContinuablePagedByItemIterable.java:83)
	at com.azure.core.util.paging.ContinuablePagedByItemIterable.iterator(ContinuablePagedByItemIterable.java:58)
	at com.azure.core.util.paging.ContinuablePagedIterable.iterator(ContinuablePagedIterable.java:141)
```

**To Reproduce**
- In Azure Portal...
  - create a cognitive search index with a name, MYINDEX
  - create an alias to that index, MYALIAS
- In Java...
  - configure a search client to use the alias
  - perform a search using that client

***Code Snippet***
Add the code snippet that causes the issue.
```java
SearchClient client = new SearchClientBuilder()
                    .credential(credential)
                    .endpoint(endpoint)
                    .indexName(aliasName)
                    .httpLogOptions(httpLogOptions)
                    .buildClient();
SearchPagedIterable searchResults = client.search(searchText, searchOptions, Context.NONE);
```

**Expected behavior**
Configuring search to use an alias and calling `search()` should return results, not throw an exception.

**Screenshots**
N/A

**Setup (please complete the following information):**
 - OS: Windows Server 2022
 - IDE: JetBrains IntelliJ IDEA
 - Libraries: 
   - com.azure:azure-core:1.45.0
   - com.azure:azure-search-documents:11.6.0
 - Java version: 17.0.9
 - App Server/Environment: N/A
 - Frameworks: Micronaut v4.1.6

**Additional context**
I realize that there were several breaking changes between v11.6.0-beta.10 and v11.6.0. I may have missed something while updating my code to accommodate those changes, but I don't _think_ so.

**Information Checklist**
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by alzimmermsft** [comment]
Hi @jnunderwood, thanks for asking this question.

`azure-search-documents` `11.6.0` is based on the `2023-11-01` (https://learn.microsoft.com/rest/api/searchservice/operation-groups?view=rest-searchservice-2023-11-01) API version of the service which doesn't include alias support.

Aliases will continue to be supported in `11.6.0-beta.10` and will be supported in the next round of beta releases beginning with `11.7.0-beta.1` (when it releases).

**Comment by jnunderwood** [comment]
Thank you for the explanation.

**Comment by alzimmermsft** [comment]
Closing as answered
