### ISSUE TITLE
[QUERY] Storage info.eTag exception with Azurite on blob download

### ISSUE THREAD

**Issue by marcoMobilab** [Azure/azure-sdk-for-java#3769]
**Query/Question**
The azure-storage-blob 11.0.0 (azure-sdk-for-java) throws an exception during blob download using Azurite v3.0.0-preview and Azurite 2.6.5.
The exception is the following:
```
java.lang.IllegalArgumentException: The argument must not be null or an empty string. Argument name: info.eTag.
	at com.microsoft.azure.storage.blob.Utility.assertNotNull(Utility.java:77) ~[azure-storage-blob-11.0.0.jar!/:na]
	at com.microsoft.azure.storage.blob.DownloadResponse.<init>(DownloadResponse.java:56) ~[azure-storage-blob-11.0.0.jar!/:na]
	at com.microsoft.azure.storage.blob.BlobURL.lambda$0(BlobURL.java:369) ~[azure-storage-blob-11.0.0.jar!/:na]
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:57) ~[rxjava-2.2.0.jar!/:na]
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64) ~[rxjava-2.2.0.jar!/:na]
	at io.reactivex.internal.operators.single.SingleResumeNext$ResumeMainSingleObserver.onSuccess(SingleResumeNext.java:65) ~[rxjava-2.2.0.jar!/:na]
	at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback$FlatMapSingleObserver.onSuccess(SingleFlatMap.java:111) ~[rxjava-2.2.0.jar!/:na]
	at io.reactivex.internal.operators.maybe.MaybeToSingle$ToSingleMaybeSubscriber.onSuccess(MaybeToSingle.java:83) ~[rxjava-2.2.0.jar!/:na]
	at io.reactivex.internal.operators.maybe.MaybeMap$MapMaybeObserver.onSuccess(MaybeMap.java:89) ~[rxjava-2.2.0.jar!/:na]
	at io.reactivex.internal.operators.maybe.MaybeJust.subscribeActual(MaybeJust.java:36) ~[rxjava-2.2.0.jar!/:na]
	at io.reactivex.Maybe.subscribe(Maybe.java:4156) ~[rxjava-2.2.0.jar!/:na]
	at io.reactivex.internal.operators.maybe.MaybeMap.subscribeActual(MaybeMap.java:40) ~[rxjava-2.2.0.jar!/:na]
	at io.reactivex.Maybe.subscribe(Maybe.java:4156) ~[rxjava-2.2.0.jar!/:na]
	at io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46) ~[rxjava-2.2.0.jar!/:na]
	at io.reactivex.Single.subscribe(Single.java:3394) ~[rxjava-2.2.0.jar!/:na]
	at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSuccess(SingleFlatMap.java:84) ~[rxjava-2.2.0.jar!/:na]
	at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback$FlatMapSingleObserver.onSuccess(SingleFlatMap.java:111) ~[rxjava-2.2.0.jar!/:na]
	at io.reactivex.internal.operators.single.SingleJust.subscribeActual(SingleJust.java:30) ~[rxjava-2.2.0.jar!/:na]
	at io.reactivex.Single.subscribe(Single.java:3394) ~[rxjava-2.2.0.jar!/:na]
	at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSuccess(SingleFlatMap.java:84) ~[rxjava-2.2.0.jar!/:na]
	at io.reactivex.internal.operators.single.SingleResumeNext$ResumeMainSingleObserver.onSuccess(SingleResumeNext.java:65) ~[rxjava-2.2.0.jar!/:na]
	at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback$FlatMapSingleObserver.onSuccess(SingleFlatMap.java:111) ~[rxjava-2.2.0.jar!/:na]
	at io.reactivex.internal.operators.single.SingleJust.subscribeActual(SingleJust.java:30) ~[rxjava-2.2.0.jar!/:na]
	at io.reactivex.Single.subscribe(Single.java:3394) ~[rxjava-2.2.0.jar!/:na]
	at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSuccess(SingleFlatMap.java:84) ~[rxjava-2.2.0.jar!/:na]
	at io.reactivex.internal.observers.ResumeSingleObserver.onSuccess(ResumeSingleObserver.java:46) ~[rxjava-2.2.0.jar!/:na]
	at io.reactivex.internal.operators.single.SingleTimeout$TimeoutMainObserver.onSuccess(SingleTimeout.java:133) ~[rxjava-2.2.0.jar!/:na]
	at io.reactivex.internal.operators.single.SingleDoOnSuccess$DoOnSuccess.onSuccess(SingleDoOnSuccess.java:59) ~[rxjava-2.2.0.jar!/:na]
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64) ~[rxjava-2.2.0.jar!/:na]
	at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback$FlatMapSingleObserver.onSuccess(SingleFlatMap.java:111) ~[rxjava-2.2.0.jar!/:na]
	at io.reactivex.internal.operators.single.SingleJust.subscribeActual(SingleJust.java:30) ~[rxjava-2.2.0.jar!/:na]
	at io.reactivex.Single.subscribe(Single.java:3394) ~[rxjava-2.2.0.jar!/:na]
	at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSuccess(SingleFlatMap.java:84) ~[rxjava-2.2.0.jar!/:na]
	at io.reactivex.internal.operators.single.SingleDoOnSuccess$DoOnSuccess.onSuccess(SingleDoOnSuccess.java:59) ~[rxjava-2.2.0.jar!/:na]
	at io.reactivex.internal.operators.single.SingleDoOnError$DoOnError.onSuccess(SingleDoOnError.java:52) ~[rxjava-2.2.0.jar!/:na]
	at io.reactivex.internal.operators.single.SingleCreate$Emitter.onSuccess(SingleCreate.java:68) ~[rxjava-2.2.0.jar!/:na]
	at com.microsoft.rest.v2.http.NettyClient$HttpClientInboundHandler.channelRead(NettyClient.java:918) ~[client-runtime-2.1.0.jar!/:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[netty-transport-4.1.28.Final.jar!/:4.1.28.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[netty-transport-4.1.28.Final.jar!/:4.1.28.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[netty-transport-4.1.28.Final.jar!/:4.1.28.Final]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438) ~[netty-transport-4.1.28.Final.jar!/:4.1.28.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[netty-codec-4.1.28.Final.jar!/:4.1.28.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297) ~[netty-codec-4.1.28.Final.jar!/:4.1.28.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413) ~[netty-codec-4.1.28.Final.jar!/:4.1.28.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) ~[netty-codec-4.1.28.Final.jar!/:4.1.28.Final]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253) ~[netty-transport-4.1.28.Final.jar!/:4.1.28.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[netty-transport-4.1.28.Final.jar!/:4.1.28.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[netty-transport-4.1.28.Final.jar!/:4.1.28.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[netty-transport-4.1.28.Final.jar!/:4.1.28.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[netty-transport-4.1.28.Final.jar!/:4.1.28.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[netty-transport-4.1.28.Final.jar!/:4.1.28.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[netty-transport-4.1.28.Final.jar!/:4.1.28.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[netty-transport-4.1.28.Final.jar!/:4.1.28.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[netty-transport-4.1.28.Final.jar!/:4.1.28.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:646) ~[netty-transport-4.1.28.Final.jar!/:4.1.28.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:546) ~[netty-transport-4.1.28.Final.jar!/:4.1.28.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500) ~[netty-transport-4.1.28.Final.jar!/:4.1.28.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:460) ~[netty-transport-4.1.28.Final.jar!/:4.1.28.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) ~[netty-common-4.1.28.Final.jar!/:4.1.28.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.28.Final.jar!/:4.1.28.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
```

***Why is this not a Bug or a feature Request?***
Could not be a bug of azure-sdk-for-java because the above exception is not thrown using azure-storage-blob with Azure and the blob is correctly downloaded.
Seems to be an inconsistency with `etag` header between Azurite and azure-storage-blob.

**Setup (please complete the following information if applicable):**
 - azure-storage-blob version 11.0.0
- Azurite v3.0.0-preview
- Azurite 2.6.5
 
 **Steps to reproduce**
See: [https://github.com/Azure/Azurite/issues/217](https://github.com/Azure/Azurite/issues/217)

**Comment by praries880** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by rickle-msft** [comment]
Hi, @marcoMobilab. Sorry for the delay. I have followed up on the other thread to hopefully continue this conversation.

**Comment by rickle-msft** [comment]
I believe this issue has been satisfactorily responded to in the linked Azurite issue. Please refer to that thread for more information. I will close this issue now, but please reopen it if there are further concerns.
