### ISSUE TITLE
[BUG] NumberFomatException while calling DataLakeFileSystemClient.listPaths

### ISSUE THREAD

**Issue by Gianluca-HCL** [Azure/azure-sdk-for-java#37775]
**Describe the bug**
When we try to get the list of files from Azure Storage containers, we encounter NumberFormatException. 
This has occurred after updating Azure Data Lake Storage maven dependencies to latest versions. 
Though, if we enable HNS in the storage account, the functionality works as expected but with HNS enabled, 
we don't get option to use 'blob versioning' and it's a blocker. 

We then modified the dependency version of azure-storage-file-datalake from 12.11.0 to 12.4.0 and things now seem to work.

***Exception or Stack Trace***

java.lang.NumberFormatException: For input string: "Thu, 07 Sep 2023 07:47:20 GMT"
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.base/java.lang.Long.parseLong(Long.java:692)
        at java.base/java.lang.Long.parseLong(Long.java:817)
        at com.azure.storage.file.datalake.Transforms.toPathItem(Transforms.java:351)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:497)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:487)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:239)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at com.azure.storage.file.datalake.DataLakeFileSystemAsyncClient.lambda$listPathsWithOptionalTimeout$3(DataLakeFileSystemAsyncClient.java:708)
        at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:106)
        at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:99)
        at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.onNext(FluxTimeout.java:180)
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondComplete(MonoFlatMap.java:245)
        at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:305)
        at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74)
        at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129)
        at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:194)
        at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2545)
        at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.request(FluxHandleFuseable.java:260)
        at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:171)
        at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:2341)
        at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:2215)
        at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:96)
        at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onSubscribe(FluxHandleFuseable.java:164)
        at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:55)
        at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:165)
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:158)
        at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129)
        at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onNext(FluxHide.java:137)
        at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129)
        at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onNext(FluxHide.java:137)
        at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:158)
        at reactor.core.publisher.FluxDelaySubscription$DelaySubscriptionMainSubscriber.onNext(FluxDelaySubscription.java:189)
        at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:99)
        at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.onNext(FluxTimeout.java:180)
        at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129)
        at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129)
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:158)
        at reactor.core.publisher.MonoCreate$DefaultMonoSink.success(MonoCreate.java:172)
        at com.azure.core.http.okhttp.OkHttpAsyncHttpClient$OkHttpCallback.onResponse(OkHttpAsyncHttpClient.java:242)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:839)
        Suppressed: java.lang.Exception: #block terminated with an error
                at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:103)
                at reactor.core.publisher.Flux.blockLast(Flux.java:2753)
                at com.azure.core.util.paging.ContinuablePagedByIteratorBase.requestPage(ContinuablePagedByIteratorBase.java:102)
                at com.azure.core.util.paging.ContinuablePagedByItemIterable$ContinuablePagedByItemIterator.<init>(ContinuablePagedByItemIterable.java:75)
                at com.azure.core.util.paging.ContinuablePagedByItemIterable.iterator(ContinuablePagedByItemIterable.java:55)
                at java.base/java.lang.Iterable.spliterator(Iterable.java:101)
                at com.azure.core.util.paging.ContinuablePagedIterable.stream(ContinuablePagedIterable.java:85)
                at com.hcl.wa.plugin.azurestorage.jobexecutor.AzureStorageAction.getFileSystem(AzureStorageAction.java:795)
                at com.hcl.wa.plugin.azurestorage.jobexecutor.AzureStorageAction.runExecutorCommand(AzureStorageAction.java:310)
                at com.ibm.scheduling.agent.core.jobexecutor.LocalJobExecutorManager.runExecutorCommand(LocalJobExecutorManager.java:191)
                at com.ibm.scheduling.osgi.Framework.runExecutorCommand(Framework.java:137)
apps-fileview.texmex_20231109.01_p2
log.txt

**To Reproduce**
The following code snippet cause the issue, in particular the issue is caused by the dataLakeFileSystemClient.listPaths methods call

***Code Snippet***
List<String> filesList = new ArrayList<String>();
ListPathsOptions options = new ListPathsOptions();
options.setRecursive(true);
Duration timeout = Duration.ofSeconds(AzureStorageCustomConstants.TIMEOUT);  
DataLakeFileSystemClient dataLakeFileSystemClient = storageClient.getFileSystemClient(containerName);
     dataLakeFileSystemClient.listPaths(options, timeout).stream().filter(i->!i.isDirectory()).forEach(
            i->filesList.add(i.getName()));

**Expected behavior**
We expect to retrieve all files from the container

    OS: Windows
    IDE: IntelliJ
    Library/Libraries: azure-storage-file-datalake 12.11.0
    Java version: 8

**Additional context**
we found the following bug https://github.com/Azure/azure-sdk-for-java/issues/33129 which is quite indetical

**Comment by joshfree** [comment]
@ibrahimrabab @alzimmermsft could you please follow up?

**Comment by alzimmermsft** [comment]
@ibrahimrabab it appears the .NET SDK supports both long-based creation times and DateTimeRfc1123-based creation times.

https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Azure.Storage.Files.DataLake/src/DataLakeExtensions.cs#L615C29-L615C48

Let's copy that logic into the Java SDK to fix this issue fully.

**Comment by ivanGiacomoniDev98** [comment]
Hi @ibrahimrabab @alzimmermsft ! I'm following this issue together with @Gianluca-HCL.
So, from what I have understood, maybe there will be a new version of azure-storage-file-datalake, that will allow to correctly retrieve files from the container both in the case where HNS is enabled and in the case where HNS is disabled?

**Comment by Gianluca-HCL** [comment]
Hi whit which library level will this fix be available?

**Comment by ibrahimrabab** [comment]
@Gianluca-HCL this should be available in our next release which will be in January.
