### ISSUE TITLE
[BUG] Permission error on renaming file in Azure File Storage

### ISSUE THREAD

**Issue by prashantguleria** [Azure/azure-sdk-for-java#37777]
**Describe the bug**
The code was working fine from last 1-2 years and started getting exception today when trying to move file using rename() method.

***Exception or Stack Trace***
```
If you are using a StorageSharedKeyCredential, and the server returned an error message that says 'Signature did not match', you can compare the string to sign with the one generated by the SDK. To log the string to sign, pass in the context key value pair 'Azure-Storage-Log-String-To-Sign': true to the appropriate method call.
If you are using a SAS token, and the server returned an error message that says 'Signature did not match', you can compare the string to sign with the one generated by the SDK. To log the string to sign, pass in the context key value pair 'Azure-Storage-Log-String-To-Sign': true to the appropriate generateSas method call.
Please remember to disable 'Azure-Storage-Log-String-To-Sign' before going to production as this string can potentially contain PII.
Status code 403, "﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:cac6a78f-301a-0063-7e26-1d18ed000000
Time:2023-11-22T09:31:34.2594142Z</Message><AuthenticationErrorDetail>The MAC signature found in the HTTP request 'NQpY6dIwGMXpgOp+3wkBoLFxzDr/u0TNA/dvkbDJ2a4=' is not the same as any computed signature. Server used following string to sign: 'PUT
```
 
 
 
Wed, 22 Nov 2023 09:31:34 GMT

**To Reproduce**

Using following version :
`azure-storage-file-share/12.16.1/azure-storage-file-share-12.16.1-sources.jar!/com/azure/storage/file/share/ShareFileClient.java`

Just run this :
StorageSharedKeyCredential storageCredentials = new StorageSharedKeyCredential(accountName,accessKey);
        }
        this.cloudStorageAccount = new ShareServiceClientBuilder()
                .endpoint("https://" + accountName + ".file.core.windows.net")
                .credential(storageCredentials)
                .buildClient();
`
//// Get any cloud file and invoke rename
cloudFile.rename(destinationPath);`

other opertaions like, copy, delete etc. works fine

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**
Should move successfully wihtout any error.

**Screenshots**

**Setup (please complete the following information):**
 - IDE: [e.g. IntelliJ]
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)]
 - Java version: [e.g. 8] 
 - App Server/Environment: [e.g. Tomcat, WildFly, Azure Function, Apache Spark, Databricks, IDE plugin or anything special]
 - Frameworks: [e.g. Spring Boot, Micronaut, Quarkus, etc] 

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by joshfree** [comment]
@ibrahimrabab @alzimmermsft could you please follow up with @prashantguleria on this github issue?

**Comment by prashantguleria** [comment]
@ibrahimrabab It seems that their are special charatcer in the file name.
However, the probelm is encountered only in rename method. For now I have mitigated it by copying file to the destination directory and deleting the source file after copying.
 Please check the following stacktrace for your reference :



```
Wed, 22 Nov 2023 07:23:34 GMT





x-ms-client-request-id:356a5737-8e0e-477e-95d1-ae5a151fda66
x-ms-file-rename-source:https://xxxxx.file.core.windows.net/xxxxx/xxxx/xxxx/21-CLN-2100-TMP-056? v1.0.pdf
x-ms-version:2021-10-04
/xxxxx/metadata/templates%2FMPSP%2F21-CLN-2100-TMP-056%E2%80%8B%20v1.0_original.pdf
comp:rename'.&lt;/AuthenticationErrorDetail&gt;&lt;/Error&gt;"
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
	at com.azure.core.implementation.http.rest.ResponseExceptionConstructorCache.invoke(ResponseExceptionConstructorCache.java:56)
	at com.azure.core.implementation.http.rest.RestProxyBase.instantiateUnexpectedException(RestProxyBase.java:378)
	at com.azure.core.implementation.http.rest.AsyncRestProxy.lambda$ensureExpectedStatus$1(AsyncRestProxy.java:115)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:113)
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2400)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:171)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:2196)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:2070)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:96)
	at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:55)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129)
	at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onNext(FluxHide.java:137)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129)
	at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onNext(FluxHide.java:137)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1839)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1839)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151)
	at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:99)
	at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.onNext(FluxRetryWhen.java:174)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
	at reactor.core.publisher.Operators$MonoInnerProducerBase.complete(Operators.java:2666)
	at reactor.core.publisher.MonoSingle$SingleSubscriber.onComplete(MonoSingle.java:180)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onComplete(MonoFlatMapMany.java:260)
	at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onComplete(FluxContextWrite.java:126)
	at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onComplete(FluxMap.java:275)
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FluxSwitchIfEmpty.java:85)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onComplete(FluxDoFinally.java:128)
	at reactor.core.publisher.FluxHandle$HandleSubscriber.onComplete(FluxHandle.java:220)
	at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onComplete(FluxMap.java:275)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onComplete(FluxDoFinally.java:128)
	at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onComplete(FluxHandleFuseable.java:236)
	at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onComplete(FluxContextWrite.java:126)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1840)
	at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:129)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:260)
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144)
	at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:413)
	at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:419)
	at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:473)
	at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:702)
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:113)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1373)
	at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1247)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1287)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
		at reactor.core.publisher.Mono.block(Mono.java:1742)
		at com.azure.storage.common.implementation.StorageImplUtils.blockWithOptionalTimeout(StorageImplUtils.java:156)
		at com.azure.storage.file.share.ShareFileClient.renameWithResponse(ShareFileClient.java:2339)
		at com.azure.storage.file.share.ShareFileClient.rename(ShareFileClient.java:2296)
		at com.drogevate.AzureFileStorage.moveFile(AzureFileStorage.java:638)
		at com.drogevate.AzureFileStorage.moveFile(AzureFileStorage.java:653)
		at com.drogevate.NoesisHttpTemplatePreProcessor.run(NoesisHttpTemplatePreProcessor.java:72)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.reflect.Method.invoke(Method.java:568)
		at com.microsoft.azure.functions.worker.broker.JavaMethodInvokeInfo.invoke(JavaMethodInvokeInfo.java:22)
		at com.microsoft.azure.functions.worker.broker.EnhancedJavaMethodExecutorImpl.execute(EnhancedJavaMethodExecutorImpl.java:55)
		at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:61)
		at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:37)
		at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:12)
		at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:44)
		at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:93)
		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
		... 1 more
```

**Comment by prashantguleria** [comment]
> Hi @prashantguleria I tested out the rename() with azure-storage-file-share version 12.16.1 and did not experience any issues. Did you upgrade any other dependencies recently? Can you share all the dependencies in your pom file, and also try upgrading file-share to the latest version (12.21.0) and see if that succeeds?
> 
> Also, is it just the rename() method that throws the 403 exception for you, or does the exception get thrown by invoking any method in file-share?

I have not updated any dependency in the project from last 1.5 year. I can't change the dependency to the latest as it might break other functionalities.

During next release of ourproduct, we can update the dependency but not today.

**Comment by ibrahimrabab** [comment]
@prashantguleria can you provide a code snippet you are using to produce the error, as well as the source file name and destination file name? I'd like to reproduce this error locally and take a deeper look into what's going on.

**Comment by prashantguleria** [comment]
Hi @ibrahimrabab ,

Attaching the file that you can use with the code that you can use to reprodcue this issue.

[21-CLN-2100-TMP-056​ v1.0.pdf.txt](https://github.com/Azure/azure-sdk-for-java/files/13643571/21-CLN-2100-TMP-056.v1.0.pdf.txt)


Once you have it, I would like to delete this comment.

Let me know when you take the snippet from this comment.

```
 private ShareServiceClient cloudStorageAccount;
 private BlobServiceClient blobClient;

 public AzureFileStorage(String accountName, String accessKey) {
        initStorage(accountName, accessKey);
    }
    
    private void initStorage(String accountName,String accessKey) {

        StorageSharedKeyCredential storageCredentials = new StorageSharedKeyCredential(accountName,accessKey);
       
        this.cloudStorageAccount = new ShareServiceClientBuilder()
                .endpoint("https://" + accountName + ".file.core.windows.net")
                .credential(storageCredentials)
                .buildClient();
    }
    
    public boolean createFolder(String shareName,String folderPath) throws URISyntaxException
    {
        boolean isFolderCreated=false;
        try {
            ShareClient fileSharedDestination = this.cloudStorageAccount.getShareClient(shareName);
            ShareDirectoryClient rootDir = fileSharedDestination.getRootDirectoryClient();
            ShareDirectoryClient subDir = rootDir;
            if(folderPath.contains("/")){
                String[] destinationNameArray = folderPath.split("/");
                for(int i=0;i<destinationNameArray.length ; i++) {
                    if(StringUtils.isBlank(destinationNameArray[i])) continue;
                    subDir = subDir.getSubdirectoryClient(destinationNameArray[i]);
                    subDir.createIfNotExists();
                }
            }
            else
            {
                subDir = subDir.getSubdirectoryClient(folderPath);
                subDir.createIfNotExists();
            }
            isFolderCreated=true;
        }
        catch (Exception ex)
        {
            throw ex;
        }
        return isFolderCreated;
    }

public void moveFileTest(ShareFileClient cloudFile, String destinationPath, String fileName) throws Exception{
        if(cloudFile.exists()){
            boolean folderCreated = createFolder(cloudFile.getShareName(), destinationPath);
            if(folderCreated){
                if(fileName == null){
                    fileName  = FilenameUtils.getName(cloudFile.getFilePath());
                }
                destinationPath = destinationPath + "/" + fileName;
                cloudFile.rename(destinationPath);
            }
        }

    }
    
     public static void main(String[] args) {
        try {
            String filePath = "shareName/templates/MPSP/21-CLN-2100-TMP-056\u200B v1.0.pdf.txt";
            String fileName  = "21-CLN-2100-TMP-056\u200B v1.0.pdf_original.txt";
            String destinationPath = "templates/MPSP";
            String accountName = "";
            String secretKey = "";
            AzureFileStorage azureFileStorage = new AzureFileStorage(accountName,secretKey);
            ShareFileClient shareFileClient = azureFileStorage.getFileFromAzure(filePath);
            if(shareFileClient.exists()){
                azureFileStorage.moveFileTest(shareFileClient,destinationPath, fileName );
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
```

**Comment by ibrahimrabab** [comment]
@prashantguleria what is the method `azureFileStorage.getFileFromAzure(filePath)` doing in your main method? Is it getting a ShareFileClient based on the file name "21-CLN-2100-TMP-056\u200B v1.0.pdf.txt"? 

Also, I tested out your code and I did run into issues with trying to rename for the file name "21-CLN-2100-TMP-056\u200B v1.0.pdf.txt". After changing the original filename to "21-CLN-2100-TMP-056​ v1.0.pdf.txt" I was able to successfully call `rename()` without errors, but only when the original file name being uploaded did not contain the "​​​​\u200B" character. The original file must be in the following format:
String fileName = "21-CLN-2100-TMP-056 v1.0.pdf.txt";
in order for rename to be called on that file. Note that for the destination path it is okay to have the \u200B character. Another thing to note is that files do not get renamed within the same directory:
https://learn.microsoft.com/en-us/rest/api/storageservices/rename-file#remarks

Can you try performing the operation without the "\u200B" character in the original file path?

**Comment by prashantguleria** [comment]
HI @ibrahimrabab ,

Yes this method `azureFileStorage.getFileFromAzure(filePath)` fetches the ShareFileClient.

I already know that if the unicode character is not present in the filename it does work successfully,  but here the scenario is about the unicode character in file name.

If it did not work with copy, I would not have raised an issue here. But the strange thing is SDK is able to fetch, copy, delete the file with the same name with unicode characters.Also, I understand the rename doesn't work in the same directory but that's not the scenario in my case. 

I can't change the file name as It can impact the downstream systems which might have logic to work on the same file name as received by the system.

Let me know if it'll be handled in the next releases of SDK with a fix or it's out of scope.

In any case, even if it's out of scope, I would like the microsoft team to atleast add a proper exception message which says that file cannot be renamed. 

The Authentication exception that I am geting is misleading, Due to this exception I had to check all my systems as I thought something is wrong with the credentials actually.

Thanks

**Comment by prashantguleria** [comment]
@ibrahimrabab 

I have deleted the comment which had my code.

Thanks

**Comment by ibrahimrabab** [comment]
Hi @prashantguleria 
I've gone ahead and added a fix for the renaming file issue you brought up, and it should be available after our next release next month. Thank you for your patience!

**Comment by prashantguleria** [comment]
Thank you @ibrahimrabab
