### ISSUE TITLE
[BUG] IllegalArgumentException while trying to upload a 0B file

### ISSUE THREAD

**Issue by Gianluca-HCL** [Azure/azure-sdk-for-java#37837]
**Describe the bug**
When we try to upload a 0B file we got the below exception

***Exception or Stack Trace***
Nov 23, 2023 8:30:53 AM com.hcl.wa.plugin.azurestorage.jobexecutor.AzureStorageJobExecutor Failed to upload from file

SEVERE: Size of the file must be greater than 0.

java.lang.IllegalArgumentException: Size of the file must be greater than 0.

        at com.azure.storage.file.datalake.DataLakeFileAsyncClient.lambda$uploadFromFile$13(DataLakeFileAsyncClient.java:498)

        at reactor.core.publisher.MonoUsing.subscribe(MonoUsing.java:85)

        at reactor.core.publisher.Mono.subscribe(Mono.java:4397)

        at reactor.core.publisher.Mono.block(Mono.java:1706)

        at com.azure.storage.common.implementation.StorageImplUtils.blockWithOptionalTimeout(StorageImplUtils.java:131)

        at com.azure.storage.file.datalake.DataLakeFileClient.uploadFromFile(DataLakeFileClient.java:292)

        at com.azure.storage.file.datalake.DataLakeFileClient.uploadFromFile(DataLakeFileClient.java:264)

        at com.hcl.wa.plugin.azurestorage.jobexecutor.AzureStorageAction.uploadFile(AzureStorageAction.java:626)

        at com.hcl.wa.plugin.azurestorage.jobexecutor.AzureStorageAction.runAction(AzureStorageAction.java:192)

        at com.ibm.scheduling.spi.jobexecutor.JobExecutorSupport.runPattern(JobExecutorSupport.java:1070)

        at com.hcl.wa.plugin.azurestorage.jobexecutor.AzureStorageJobExecutor.execute(AzureStorageJobExecutor.java:92)

        at com.ibm.scheduling.jobexecutor.JobExecutorManagerSupport.execute(JobExecutorManagerSupport.java:409)

        at com.ibm.scheduling.jobexecutor.JobExecutorManagerSupport.connectAndExecute(JobExecutorManagerSupport.java:173)

        at com.ibm.scheduling.agent.core.jobexecutor.LocalJobExecutorManager.executeJob(LocalJobExecutorManager.java:134)

        at com.ibm.scheduling.osgi.Framework.executeJob(Framework.java:105)

        Suppressed: java.lang.Exception: #block terminated with an error

                at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)

                at reactor.core.publisher.Mono.block(Mono.java:1707)

                ... 11 more
 
Nov 23, 2023 8:30:53 AM com.hcl.wa.plugin.azurestorage.jobexecutor.AzureStorageJobExecutor runAction

SEVERE: AWKADL005E The job execution failed. The error message is "Upload_Fail"

com.ibm.scheduling.spi.jobexecutor.JobExecutorFailedExecutionException: AWKADL005E The job execution failed. The error message is "Upload_Fail"

        at com.hcl.wa.plugin.azurestorage.jobexecutor.AzureStorageAction.uploadFile(AzureStorageAction.java:663)

        at com.hcl.wa.plugin.azurestorage.jobexecutor.AzureStorageAction.runAction(AzureStorageAction.java:192)

        at com.ibm.scheduling.spi.jobexecutor.JobExecutorSupport.runPattern(JobExecutorSupport.java:1070)

        at com.hcl.wa.plugin.azurestorage.jobexecutor.AzureStorageJobExecutor.execute(AzureStorageJobExecutor.java:92)

        at com.ibm.scheduling.jobexecutor.JobExecutorManagerSupport.execute(JobExecutorManagerSupport.java:409)

        at com.ibm.scheduling.jobexecutor.JobExecutorManagerSupport.connectAndExecute(JobExecutorManagerSupport.java:173)

        at com.ibm.scheduling.agent.core.jobexecutor.LocalJobExecutorManager.executeJob(LocalJobExecutorManager.java:134)

        at com.ibm.scheduling.osgi.Framework.executeJob(Framework.java:105)

**To Reproduce**
The following code snippet cause the issue, in particular the issue is caused by the fileClient.uploadFromFile method call

***Code Snippet***
DataLakeFileSystemClient dataLakeFileSystemClient2 = storageClient.getFileSystemClient(containerName+"/"+azLocation);
DataLakeFileClient fileClient = dataLakeFileSystemClient2.getFileClient(name);
fileClient.uploadFromFile(filePath,true);

**Expected behavior**
We expect to be able to upload a 0B file

**Setup (please complete the following information):**
OS: Windows
IDE: IntelliJ
Library/Libraries: azure-storage-file-datalake 12.11.0
Java version: 8

**Comment by alzimmermsft** [comment]
Thanks for filing this issue @Gianluca-HCL 

@ibrandes, @ibrahimrabab this appears to still be the case in the latest version where an exception will be thrown if the file size is 0 bytes.

https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-file-datalake/src/main/java/com/azure/storage/file/datalake/DataLakeFileAsyncClient.java#L872

We should change this to just create the file if the size is 0 bytes and perform no uploading.

**Comment by Gianluca-HCL** [comment]
Hi with which library level will this fix be available?
