### ISSUE TITLE
[BUG] Stop pull message from eventhubs

### ISSUE THREAD

**Issue by CQ-Developer** [Azure/azure-sdk-for-java#37865]
**Describe the bug**

I have two scheduled tasks that pull messages from eventhubs at fixed times.

One of the tasks report warnings, causing it to no longer start at all.

The other one is completely normal.

**Exception or Stack Trace**

1. This is the stack trace from Java, there are no other error logs other than that.

```log
2023-11-25T20:46:59.637048855Z OUT com.azure.core.amqp.exception.AmqpException: The RequestResponseChannel didn't receive the acknowledgment for the send due receive link termination.
2023-11-25T20:46:59.637054255Z OUT 	at com.azure.core.amqp.implementation.RequestResponseChannel.onTerminalState(RequestResponseChannel.java:448) ~[azure-core-amqp-2.8.8.jar:2.8.8]
2023-11-25T20:46:59.637061155Z OUT 	at com.azure.core.amqp.implementation.RequestResponseChannel.lambda$closeAsync$9(RequestResponseChannel.java:254) ~[azure-core-amqp-2.8.8.jar:2.8.8]
2023-11-25T20:46:59.637065955Z OUT 	at reactor.core.publisher.MonoRunnable.subscribe(MonoRunnable.java:49) ~[reactor-core-3.5.9.jar:3.5.9]
2023-11-25T20:46:59.637088355Z OUT 	at reactor.core.publisher.Mono.subscribe(Mono.java:4495) ~[reactor-core-3.5.9.jar:3.5.9]
2023-11-25T20:46:59.637093455Z OUT 	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103) ~[reactor-core-3.5.9.jar:3.5.9]
2023-11-25T20:46:59.637096555Z OUT 	at com.dynatrace.agent.introspection.reactor3.TracingReactorSubscriber.lambda$onError$1(TracingReactorSubscriber.java:41) ~[na:na]
2023-11-25T20:46:59.637099755Z OUT 	at com.dynatrace.agent.introspection.reactor3.TracingReactorSubscriber.withActivePath(TracingReactorSubscriber.java:62) ~[na:na]
2023-11-25T20:46:59.637103555Z OUT 	at com.dynatrace.agent.introspection.reactor3.TracingReactorSubscriber.onError(TracingReactorSubscriber.java:41) ~[na:na]
2023-11-25T20:46:59.637107055Z OUT 	at reactor.core.publisher.SerializedSubscriber.onError(SerializedSubscriber.java:124) ~[reactor-core-3.5.9.jar:3.5.9]
2023-11-25T20:46:59.637109655Z OUT 	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.handleTimeout(FluxTimeout.java:295) ~[reactor-core-3.5.9.jar:3.5.9]
2023-11-25T20:46:59.637112455Z OUT 	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.doTimeout(FluxTimeout.java:280) ~[reactor-core-3.5.9.jar:3.5.9]
2023-11-25T20:46:59.637115155Z OUT 	at reactor.core.publisher.FluxTimeout$TimeoutTimeoutSubscriber.onNext(FluxTimeout.java:419) ~[reactor-core-3.5.9.jar:3.5.9]
2023-11-25T20:46:59.637118555Z OUT 	at com.dynatrace.agent.introspection.reactor3.TracingReactorSubscriber.lambda$onNext$0(TracingReactorSubscriber.java:36) ~[na:na]
2023-11-25T20:46:59.637122555Z OUT 	at com.dynatrace.agent.introspection.reactor3.TracingReactorSubscriber.withActivePath(TracingReactorSubscriber.java:62) ~[na:na]
2023-11-25T20:46:59.637125555Z OUT 	at com.dynatrace.agent.introspection.reactor3.TracingReactorSubscriber.onNext(TracingReactorSubscriber.java:36) ~[na:na]
2023-11-25T20:46:59.637128855Z OUT 	at reactor.core.publisher.FluxOnErrorReturn$ReturnSubscriber.onNext(FluxOnErrorReturn.java:162) ~[reactor-core-3.5.9.jar:3.5.9]
2023-11-25T20:46:59.637131555Z OUT 	at com.dynatrace.agent.introspection.reactor3.TracingReactorSubscriber.lambda$onNext$0(TracingReactorSubscriber.java:36) ~[na:na]
2023-11-25T20:46:59.637135755Z OUT 	at com.dynatrace.agent.introspection.reactor3.TracingReactorSubscriber.withActivePath(TracingReactorSubscriber.java:62) ~[na:na]
2023-11-25T20:46:59.637138655Z OUT 	at com.dynatrace.agent.introspection.reactor3.TracingReactorSubscriber.onNext(TracingReactorSubscriber.java:36) ~[na:na]
2023-11-25T20:46:59.637141255Z OUT 	at reactor.core.publisher.MonoDelay$MonoDelayRunnable.propagateDelay(MonoDelay.java:271) ~[reactor-core-3.5.9.jar:3.5.9]
2023-11-25T20:46:59.637144755Z OUT 	at reactor.core.publisher.MonoDelay$MonoDelayRunnable.run(MonoDelay.java:286) ~[reactor-core-3.5.9.jar:3.5.9]
2023-11-25T20:46:59.637149555Z OUT 	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68) ~[reactor-core-3.5.9.jar:3.5.9]
2023-11-25T20:46:59.637153555Z OUT 	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28) ~[reactor-core-3.5.9.jar:3.5.9]
2023-11-25T20:46:59.637160255Z OUT 	at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
2023-11-25T20:46:59.637163355Z OUT 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[na:na]
2023-11-25T20:46:59.637166655Z OUT 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
2023-11-25T20:46:59.637170055Z OUT 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
2023-11-25T20:46:59.637176455Z OUT 	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
```

2. This is the warning log reported in the SDK, and it appears almost every few days until the cron job no longer starts.

```log
2023-11-25T20:45:59.633Z  WARN 16 --- [tor-executor-29] c.a.c.a.implementation.ReactorExecutor   : {"az.sdk.message":"Unhandled exception while processing events in reactor, report this error.","exception":"java.lang.IllegalStateException","connectionId":"MF_38c638_1700819031571"}
2023-11-25T20:46:03.648Z  WARN 16 --- [tor-executor-29] c.a.c.a.implementation.ReactorExecutor   : {"az.sdk.message":"scheduleCompletePendingTasks - exception occurred while  processing events.\njava.lang.IllegalStateException\norg.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:112)\norg.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)\norg.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:292)\ncom.azure.core.amqp.implementation.ReactorExecutor.lambda$scheduleCompletePendingTasks$1(ReactorExecutor.java:158)\nreactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)\nreactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)\njava.base/java.util.concurrent.FutureTask.run(Unknown Source)\njava.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)\njava.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)\njava.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)\njava.base/java.lang.Thread.run(Unknown Source)Cause: null\norg.apache.qpid.proton.engine.impl.EndpointImpl.decref(EndpointImpl.java:54)\norg.apache.qpid.proton.engine.impl.TransportSession.unsetLocalChannel(TransportSession.java:142)\norg.apache.qpid.proton.engine.impl.TransportSession.freeLocalChannel(TransportSession.java:375)\norg.apache.qpid.proton.engine.impl.TransportImpl.freeLocalChannel(TransportImpl.java:1025)\norg.apache.qpid.proton.engine.impl.TransportImpl.processEnd(TransportImpl.java:1049)\norg.apache.qpid.proton.engine.impl.TransportImpl.writeInto(TransportImpl.java:373)\norg.apache.qpid.proton.engine.impl.TransportOutputAdaptor.pending(TransportOutputAdaptor.java:59)\norg.apache.qpid.proton.engine.impl.SaslImpl$SwitchingSaslTransportWrapper.pending(SaslImpl.java:842)\norg.apache.qpid.proton.engine.impl.HandshakeSniffingTransportWrapper.pending(HandshakeSniffingTransportWrapper.java:138)\norg.apache.qpid.proton.engine.impl.ssl.SimpleSslTransportWrapper.wrapOutput(SimpleSslTransportWrapper.java:217)\norg.apache.qpid.proton.engine.impl.ssl.SimpleSslTransportWrapper.pending(SimpleSslTransportWrapper.java:400)\norg.apache.qpid.proton.engine.impl.ssl.SslImpl$UnsecureClientAwareTransportWrapper.pending(SslImpl.java:173)\norg.apache.qpid.proton.engine.impl.TransportImpl.pending(TransportImpl.java:1591)\norg.apache.qpid.proton.reactor.impl.IOHandler.pending(IOHandler.java:193)\norg.apache.qpid.proton.reactor.impl.IOHandler.update(IOHandler.java:214)\norg.apache.qpid.proton.reactor.impl.IOHandler.handleTransport(IOHandler.java:347)\norg.apache.qpid.proton.reactor.impl.IOHandler.onUnhandled(IOHandler.java:384)\norg.apache.qpid.proton.engine.BaseHandler.onTransport(BaseHandler.java:80)\norg.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:188)\norg.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)\norg.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)\norg.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:292)\ncom.azure.core.amqp.implementation.ReactorExecutor.lambda$scheduleCompletePendingTasks$1(ReactorExecutor.java:158)\nreactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)\nreactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)\njava.base/java.util.concurrent.FutureTask.run(Unknown Source)\njava.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)\njava.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)\njava.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)\njava.base/java.lang.Thread.run(Unknown Source)","connectionId":"MF_38c638_1700819031571"}
2023-11-26T02:14:20.493Z  WARN 16 --- [tor-executor-28] c.a.c.a.implementation.ReactorExecutor   : {"az.sdk.message":"Unhandled exception while processing events in reactor, report this error.","exception":"java.lang.IllegalStateException","connectionId":"MF_2df4fc_1700819030794"}
2023-11-26T02:14:24.530Z  WARN 16 --- [tor-executor-28] c.a.c.a.implementation.ReactorExecutor   : {"az.sdk.message":"scheduleCompletePendingTasks - exception occurred while  processing events.\njava.lang.IllegalStateException\norg.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:112)\norg.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)\norg.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:292)\ncom.azure.core.amqp.implementation.ReactorExecutor.lambda$scheduleCompletePendingTasks$1(ReactorExecutor.java:158)\nreactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)\nreactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)\njava.base/java.util.concurrent.FutureTask.run(Unknown Source)\njava.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)\njava.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)\njava.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)\njava.base/java.lang.Thread.run(Unknown Source)Cause: null\norg.apache.qpid.proton.engine.impl.EndpointImpl.decref(EndpointImpl.java:54)\norg.apache.qpid.proton.engine.impl.TransportSession.unsetLocalChannel(TransportSession.java:142)\norg.apache.qpid.proton.engine.impl.TransportSession.freeLocalChannel(TransportSession.java:375)\norg.apache.qpid.proton.engine.impl.TransportImpl.freeLocalChannel(TransportImpl.java:1025)\norg.apache.qpid.proton.engine.impl.TransportImpl.processEnd(TransportImpl.java:1049)\norg.apache.qpid.proton.engine.impl.TransportImpl.writeInto(TransportImpl.java:373)\norg.apache.qpid.proton.engine.impl.TransportOutputAdaptor.pending(TransportOutputAdaptor.java:59)\norg.apache.qpid.proton.engine.impl.SaslImpl$SwitchingSaslTransportWrapper.pending(SaslImpl.java:842)\norg.apache.qpid.proton.engine.impl.HandshakeSniffingTransportWrapper.pending(HandshakeSniffingTransportWrapper.java:138)\norg.apache.qpid.proton.engine.impl.ssl.SimpleSslTransportWrapper.wrapOutput(SimpleSslTransportWrapper.java:217)\norg.apache.qpid.proton.engine.impl.ssl.SimpleSslTransportWrapper.pending(SimpleSslTransportWrapper.java:400)\norg.apache.qpid.proton.engine.impl.ssl.SslImpl$UnsecureClientAwareTransportWrapper.pending(SslImpl.java:173)\norg.apache.qpid.proton.engine.impl.TransportImpl.pending(TransportImpl.java:1591)\norg.apache.qpid.proton.reactor.impl.IOHandler.pending(IOHandler.java:193)\norg.apache.qpid.proton.reactor.impl.IOHandler.update(IOHandler.java:214)\norg.apache.qpid.proton.reactor.impl.IOHandler.handleTransport(IOHandler.java:347)\norg.apache.qpid.proton.reactor.impl.IOHandler.onUnhandled(IOHandler.java:384)\norg.apache.qpid.proton.engine.BaseHandler.onTransport(BaseHandler.java:80)\norg.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:188)\norg.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)\norg.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)\norg.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:292)\ncom.azure.core.amqp.implementation.ReactorExecutor.lambda$scheduleCompletePendingTasks$1(ReactorExecutor.java:158)\nreactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)\nreactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)\njava.base/java.util.concurrent.FutureTask.run(Unknown Source)\njava.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)\njava.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)\njava.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)\njava.base/java.lang.Thread.run(Unknown Source)","connectionId":"MF_2df4fc_1700819030794"}
2023-11-26T02:15:20.500Z  WARN 16 --- [     parallel-3] c.a.c.a.i.ReactorDispatcher              : {"az.sdk.message":"ReactorDispatcher instance is closed. Should not continue dispatching work to this reactor.","exception":"ReactorDispatcher instance is closed. Should not continue dispatching work to this reactor.","connectionId":"MF_2df4fc_1700819030794"}
2023-11-26T02:15:20.500Z  WARN 16 --- [     parallel-3] c.a.c.a.i.RequestResponseChannel         : {"az.sdk.message":"Unable to open send and receive link.","exception":"Unable to open send and receive link.","connectionId":"MF_2df4fc_1700819030794","linkName":"cbs"}
2023-11-26T02:15:20.500Z  WARN 16 --- [edElastic-18763] c.a.c.a.i.ReactorDispatcher              : {"az.sdk.message":"ReactorDispatcher instance is closed. Should not continue dispatching work to this reactor.","exception":"ReactorDispatcher instance is closed. Should not continue dispatching work to this reactor.","connectionId":"MF_2df4fc_1700819030794"}
2023-11-26T02:15:20.500Z  WARN 16 --- [     parallel-3] c.a.c.a.i.AmqpChannelProcessor           : {"az.sdk.message":"Retry attempts exhausted or exception was not retriable.","exception":"Unable to open send and receive link.","connectionId":"MF_2df4fc_1700819030794","entityPath":"$cbs","tryCount":0}
2023-11-26T02:15:20.501Z  WARN 16 --- [     parallel-3] c.a.c.a.i.ReactorDispatcher              : {"az.sdk.message":"ReactorDispatcher instance is closed. Should not continue dispatching work to this reactor.","exception":"ReactorDispatcher instance is closed. Should not continue dispatching work to this reactor.","connectionId":"MF_2df4fc_1700819030794"}
2023-11-26T02:15:22.647Z  WARN 16 --- [tor-executor-31] c.a.c.a.implementation.ReactorExecutor   : {"az.sdk.message":"Unhandled exception while processing events in reactor, report this error.","exception":"java.lang.NullPointerException: uncorrelated channel: 4","connectionId":"MF_6764cd_1700964860499"}
2023-11-26T02:16:22.649Z  WARN 16 --- [     parallel-1] c.a.c.a.i.ReactorDispatcher              : {"az.sdk.message":"ReactorDispatcher instance is closed. Should not continue dispatching work to this reactor.","exception":"ReactorDispatcher instance is closed. Should not continue dispatching work to this reactor.","connectionId":"MF_6764cd_1700964860499"}
2023-11-26T02:16:22.649Z  WARN 16 --- [     parallel-4] c.a.c.a.i.ReactorDispatcher              : {"az.sdk.message":"ReactorDispatcher instance is closed. Should not continue dispatching work to this reactor.","exception":"ReactorDispatcher instance is closed. Should not continue dispatching work to this reactor.","connectionId":"MF_6764cd_1700964860499"}
2023-11-26T02:16:22.649Z  WARN 16 --- [edElastic-18775] c.a.c.a.i.ReactorDispatcher              : {"az.sdk.message":"ReactorDispatcher instance is closed. Should not continue dispatching work to this reactor.","exception":"ReactorDispatcher instance is closed. Should not continue dispatching work to this reactor.","connectionId":"MF_6764cd_1700964860499"}
2023-11-26T02:16:22.650Z  WARN 16 --- [     parallel-4] c.a.c.a.i.RequestResponseChannel         : {"az.sdk.message":"Unable to open send and receive link.","exception":"Unable to open send and receive link.","connectionId":"MF_6764cd_1700964860499","linkName":"cbs"}
2023-11-26T02:16:22.650Z  WARN 16 --- [     parallel-4] c.a.c.a.i.AmqpChannelProcessor           : {"az.sdk.message":"Retry attempts exhausted or exception was not retriable.","exception":"Unable to open send and receive link.","connectionId":"MF_6764cd_1700964860499","entityPath":"$cbs","tryCount":0}
```

**To Reproduce**

It happens automatically from time to time.

I'm not sure it's due to some specific reason.

**Code Snippet**

```java
class SomeService {
    public void popFromEventHub() {
        // get partition id
        String[] partitionIds = consumerClient.getPartitionIds().stream().toArray(String[]::new);
        // concurrently pull messages from each partition
        CompletableFuture<?>[] futures = new CompletableFuture[partitionIds.length];
        for (int i = 0; i < partitionIds.length; i++) {
            String partitionId = partitionIds[i];
            // EventPosition is caching in redis
            Duration maxWaitTime = Duration.ofMillis(properties.getMaxWait());
            String redisKey = redisKeyWithPartitionId(partitionId);
            CompletableFuture<List<PartitionEvent>> future = CompletableFuture
                    .supplyAsync(() -> redis.opsForValue().get(redisKey), threadPool)
                    .thenApply(e -> {
                        if (e == null) {
                            return EventPosition.fromEnqueuedTime(Instant.now().minus(Duration.ofMinutes(30)));
                        }
                        OffsetEntity offsetEntity = CommonUtil.toBean(e, OffsetEntity.class);
                        return EventPosition.fromSequenceNumber(offsetEntity.getSequenceNumber());
                    })
                    .thenApply(e -> consumerClient.receiveFromPartition(partitionId, properties.getMaxMessage(), e, maxWaitTime))
                    .thenApply(e -> e.stream().collect(Collectors.toList()));
            futures[i] = future;
        }
        CompletableFuture.allOf(futures).join();
        // follow-up processing...
    }
}

class SomeJob {
    @Scheduled(fixedRate = 2500, initialDelay = 200)
    public void processEventHub() {
        var partitionEvents = someService.popFromEventHub();
        // follow-up processing...
    }
}
```

**Expected behavior**

Scheduled tasks never stop.

**Screenshorts**

![image](https://github.com/Azure/azure-sdk-for-java/assets/54073835/5e28366d-d612-41d1-ad2e-7a14743067da)

The picture above shows: From this point on, no messages are pulled from eventhubs.

**Setup**

- OS: Linux

- IDE: IntelliJ

- Lib: com.azure:azure-messaging-eventhubs:5.15.8

- Java version: 17

- App Server: Tomcat

- Frameworks: Spring Boot

**Additional context**

This error occurred almost every day for over a month while the service was running, but was preceded by a retry and then back to normal.
I don't know what caused it to stop starting at a certain time and stop pulling messages.

**Comment by joshfree** [comment]
@conniey could you please follow up?

**Comment by conniey** [comment]
Apologies for the delayed response. The EventHubConsumerAsyncClient applies the retry options when it encounters a transient error.  When retry options are exhausted, it stops trying to reconnect.  Consequently, you have to manage instances of EventHubConsumerAsyncClient (when it stops trying to reconnect).  

We have an async retry sample, albeit it is for Service Bus. The same technique applies: https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/servicebus/azure-messaging-servicebus/src/samples/java/com/azure/messaging/servicebus/ServiceBusReceiverAsyncClientRetrySample.java

I hope this helps.

**Comment by CQ-Developer** [comment]
@conniey 
thank you for helping. I will try this solution and close this issue.
