### ISSUE TITLE
Allow DefaultServiceBusNamespaceProcessorFactory  to use the shared serviceBusClientBuilder

### ISSUE THREAD

**Issue by mohyeid** [Azure/azure-sdk-for-java#37932]
**Describe the bug**
Today when spring boot/ spring cloud auto configuration, sub & producer factories are able to reuse the preconfigured serviceBuSClientBuilder and mark `shareServiceBusClientBuilder ` to `true` like here:

https://github.com/Azure/azure-sdk-for-java/blob/2b020724483dbb745531c113d78c4d900fcb52e4/sdk/spring/spring-cloud-azure-service/src/main/java/com/azure/spring/cloud/service/implementation/servicebus/factory/AbstractServiceBusSubClientBuilderFactory.java#L55

In the other hand the `DefaultServiceBusNamespaceProcessorFactory ` creates `` without passing any serviceBusClientBuilder instance, which result on creating a new instance that lacks any type of configurations that was done for the sub & producers. It will lack any configurations like proxy, custom-endpoint-address customization (reference issue: https://github.com/Azure/azure-sdk-for-java/issues/37930#issue-2026925790)

https://github.com/Azure/azure-sdk-for-java/blob/2b020724483dbb745531c113d78c4d900fcb52e4/sdk/spring/spring-messaging-azure-servicebus/src/main/java/com/azure/spring/messaging/servicebus/core/DefaultServiceBusNamespaceProcessorFactory.java#L189C40-L189C40

This line will call ServiceBusProcessorClientBuilderFactory without serviceBuSClientBuilder , which will result on calling another constructor passing null for serviceBuSClientBuilder  and result on a new instance lacking any type of configurations. 

***Exception or Stack Trace***
Lack of configurations will result on an exception when creating the processor connection despite the sub & producer connections being created successfully. 
```
[INFO ] 2023-12-05 11:17:40,371 ReactorConnection [reactor-executor-1] - {"az.sdk.message":"onConnectionShutdown. Shutting down.","connectionId":"MF_3cc3ca_1701803852833","isTransient":false,"isInitiatedByClient":false,"shutdownMessage":"connectionId[MF_3cc3ca_1701803852833] Reactor selectable is disposed.","namespace":"XXXXXXXXX.net"}

[ERROR] 2023-12-05 11:17:40,398 Operators [reactor-executor-1] - Operator called default onErrorDropped

reactor.core.Exceptions$ErrorCallbackNotImplemented: com.azure.core.amqp.exception.AmqpException: Connection refused: no further information, errorContext[NAMESPACE: XXXXXXXXX.net. ERROR CONTEXT: N/A]

Caused by: com.azure.core.amqp.exception.AmqpException: Connection refused: no further information, errorContext[NAMESPACE: XXXXXXXXX.net. ERROR CONTEXT: N/A]

            at com.azure.core.amqp.implementation.ExceptionUtil.toException(ExceptionUtil.java:85) ~[azure-core-amqp-2.8.4.jar:2.8.4]

            at com.azure.core.amqp.implementation.handler.ConnectionHandler.notifyErrorContext(ConnectionHandler.java:351) ~[azure-core-amqp-2.8.4.jar:2.8.4]

            at com.azure.core.amqp.implementation.handler.ConnectionHandler.onTransportError(ConnectionHandler.java:253) ~[azure-core-amqp-2.8.4.jar:2.8.4]

            at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:191) ~[proton-j-0.33.8.jar:?]

            at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108) ~[proton-j-0.33.8.jar:?]

            at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324) ~[proton-j-0.33.8.jar:?]

            at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291) ~[proton-j-0.33.8.jar:?]

            at com.azure.core.amqp.implementation.ReactorExecutor.run(ReactorExecutor.java:91) ~[azure-core-amqp-2.8.4.jar:2.8.4]

            at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68) ~[reactor-core-3.4.27.jar:3.4.27]

            at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28) ~[reactor-core-3.4.27.jar:3.4.27]

            at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]

            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]

            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]

            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]

            at java.lang.Thread.run(Thread.java:833) ~[?:?]

[INFO ] 2023-12-05 11:17:40,411 ServiceBusConnectionProcessor [reactor-executor-1] - {"az.sdk.message":"Transient error occurred. Retrying.","exception":"Connection refused: no further information, errorContext[NAMESPACE: XXXXXXXXX.net. ERROR CONTEXT: N/A]","entityPath":"N/A","tryCount":0,"interval_ms":4511}

[INFO ] 2023-12-05 11:17:40,413 ReactorConnection [reactor-executor-1] - {"az.sdk.message":"onConnectionShutdown. Shutting down.","connectionId":"MF_3cc3ca_1701803852833","isTransient":false,"isInitiatedByClient":false,"shutdownMessage":"Finished processing pending tasks.","namespace":"XXXXXXXXX.net"}

[INFO ] 2023-12-05 11:17:43,068 ServiceBusReceiverAsyncClient [boundedElastic-1] - Removing receiver links.
```

**To Reproduce**
Steps provided above. This is for spring cloud stream auto aonfigurations. 

***Code Snippet***
Added above

**Expected behavior**
Proccessor factory need to be able to use the preconfigured serviceBuSClientBuilder  similar to the sub & producer factories. 

**Setup (please complete the following information):**
 - OS: Windows 
 - IDE: IntelliJ
 - Library/Libraries: com.azure:azure-core:1.38.0 
 - Java version: 17
 - App Server/Environment: Azure Function,
 - Frameworks:  Spring Boot & Spring Cloud Stream

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ X] Bug Description Added
- [X ] Repro Steps Added
- [X ] Setup information Added

**Comment by mohyeid** [comment]
Here you go: https://github.com/mohyeid/azure-sdk-processor-issue 

Please, note tenantId, clientId, secret, proxy, etc.. are fake and for sample code only. You can debug the issue by putting these next breakpoints and noticing the differences:

AbstractServiceBusSubClientBuilderFactory:38 
     First run for sender & second run for reciever it uses the shared client
     Third run for processor, it creates a new instance. Breakpoints at:
                 - DefaultServiceBusNamespaceProcessorFactory:125 Note it will pass null to ServiceBusProcessorClientBuilderFactory constructor line 24 which will result on creating a new client. 
                 - AbstractServiceBusSubClientBuilderFactory:41  Note it's not using shared
     
Other helpful breakpoints:
       ReactorHandlerProvider:57 
           - First & second runs for sender and receiver have valid isCustomEndpointConfigured as true. Remember it's set on my customizer in the code example  ApplicationConfiguration:39 
           - Third run for the processor isCustomEndpointConfigured will be false since it did not use the shared client. 

Hope this helps, let me know if I can provide any extra details.

**Comment by moarychan** [comment]
Now the `DefaultServiceBusNamespaceProcessorFactory` can support to custom the ServiceBusClientBuilder and sub builders through methods `addXXXCustomizer`,
