### ISSUE TITLE
 [BUG]  io.netty.handler.ssl.SslHandshakeTimeoutException while connecting to azure cosmosdb from springboot 3 application

### ISSUE THREAD

**Issue by pyramesh** [Azure/azure-sdk-for-java#38038]
**Query/Question**

When I am trying to integrate **Spring boot 3** with a**zure cosmosDB**,  getting the below error 
 "**io.netty.handler.ssl.SslHandshakeTimeoutException: handshake timed out after 5000ms**"

**Error stack trace:**

```
  INFO 31896 --- [           main] com.azure.cosmos.CosmosClientBuilder     : Cosmos Client with (Correlation) ID [00001] started up in [1181] ms with the following configuration: serviceEndpoint [https://XXXXXXX:443/], preferredRegions [[]], excludedRegions [[]], connectionPolicy [ConnectionPolicy{httpNetworkRequestTimeout=PT1M, tcpNetworkRequestTimeout=PT5S, connectionMode=DIRECT, maxConnectionPoolSize=1000, idleHttpConnectionTimeout=PT1M, idleTcpConnectionTimeout=PT0S, userAgentSuffix='az-sd-cos/@project.version@', throttlingRetryOptions=RetryOptions{maxRetryAttemptsOnThrottledRequests=9, maxRetryWaitTime=PT30S}, endpointDiscoveryEnabled=true, preferredRegions=null, multipleWriteRegionsEnabled=true, proxyType=null, inetSocketProxyAddress=null, readRequestsFallbackEnabled=true, connectTimeout=PT5S, idleTcpEndpointTimeout=PT1H, maxConnectionsPerEndpoint=130, maxRequestsPerConnection=30, tcpConnectionEndpointRediscoveryEnabled=true, ioThreadPriority=5, ioThreadCountPerCoreFactor=2, tcpHealthCheckTimeoutDetectionEnabled=true, minConnectionPoolSizePerEndpoint=1, openConnectionsConcurrency=1, aggressiveWarmupConcurrency=20}], consistencyLevel [null], contentResponseOnWriteEnabled [true], sessionCapturingOverride [false], connectionSharingAcrossClients [false], clientTelemetryEnabled [false], proactiveContainerInit [null], diagnostics [{samplingRate=1.0, thresholds={pointOperationLatencyThreshold=PT1S, nonPointOperationLatencyThreshold=PT3S, requestChargeThreshold=1000.0, payloadSizeInBytesThreshold=2147483647, customFailureHandler=false}, clientCorrelationId=null, clientTelemetryEnabled=false, clientMetricsEnabled=true, transportLevelTracingEnabled=false, customTracerProvided=false, customDiagnosticHandlers=()}], tracing [true, false, com.azure.cosmos.implementation.DiagnosticsProvider.EnabledNoOpTracer, [com.azure.cosmos.implementation.clienttelemetry.ClientMetricsDiagnosticsHandler]]

  WARN 31896 --- [s-rntbd-nio-2-3] c.a.c.i.d.rntbd.RntbdClientChannelPool   : Channel([id: 0xae0eb09e, L:/192.168.2.12:61481 - R:c******.documents.azure.com/**.**.**:11302]) health check request failed due to:

io.netty.handler.ssl.SslHandshakeTimeoutException: handshake timed out after 5000ms
	at io.netty.handler.ssl.SslHandler$7.run(SslHandler.java:2217) ~[netty-handler-4.1.101.Final.jar:4.1.101.Final]
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[netty-common-4.1.101.Final.jar:4.1.101.Final]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153) ~[netty-common-4.1.101.Final.jar:4.1.101.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[netty-common-4.1.101.Final.jar:4.1.101.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166) ~[netty-common-4.1.101.Final.jar:4.1.101.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.101.Final.jar:4.1.101.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.101.Final.jar:4.1.101.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.101.Final.jar:4.1.101.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.101.Final.jar:4.1.101.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.101.Final.jar:4.1.101.Final]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

```

**Code Snippet**

Github link my project
[springboot3-cosmosdb](https://github.com/pyramesh/SpringBoot3-cosmosdb/tree/main/springboot3-cosmosdb)

**Entity**

```
@Container(containerName = "users")
@Getter
@Setter
public class User {

    @Id
    private String id;
    @PartitionKey
    private String firstName;
    private String lastName;
    private String email;
}
```

**pom.xml**

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.2.0</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
    <groupId>com.ramesh.cosmos</groupId>
    <artifactId>springboot3-cosmosdb</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>springboot3-cosmosdb</name>
    <description>springboot3-cosmosdb</description>
    <properties>
        <java.version>17</java.version>
        <spring-cloud-azure.version>5.7.0</spring-cloud-azure.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>com.azure.spring</groupId>
            <artifactId>spring-cloud-azure-starter-data-cosmos</artifactId>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.azure.spring</groupId>
                <artifactId>spring-cloud-azure-dependencies</artifactId>
                <version>${spring-cloud-azure.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <excludes>
                        <exclude>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </exclude>
                    </excludes>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
```

**Configuration** 
```
@Configuration
@EnableConfigurationProperties(AzureCosmosDBProperties.class)
@EnableCosmosRepositories(basePackages = "com.ramesh.cosmos.repository")
@PropertySource("classpath:application.properties")
@Slf4j
public class AzureCosmosDBConfiguration extends AbstractCosmosConfiguration {

  private final AzureCosmosDBProperties properties;

  AzureCosmosDBConfiguration(AzureCosmosDBProperties properties) {
    this.properties = properties;
  }

  /**
   *  Create a cosmos client builder to interact with cosmos DB
   *
   * @return cosmos client {@link CosmosClientBuilder}
   */
  @Bean
  public CosmosClientBuilder cosmosBuilderClient() {
    return new CosmosClientBuilder()
            .endpoint(properties.getUri())
            .key(properties.getKey())
            .directMode(DirectConnectionConfig.getDefaultConfig());
  }

  /**
   *  Create a cosmos configuration
   *
   * @return cosmos configuration {@link CosmosConfig}
   */
  @Override
  @Bean
  public CosmosConfig cosmosConfig() {
    return CosmosConfig.builder()
            .responseDiagnosticsProcessor(new ResponseDiagnosticsProcessorImplementation(properties))
            .enableQueryMetrics(properties.isQueryMetricsEnabled()).build();
  }

  private static class ResponseDiagnosticsProcessorImplementation implements ResponseDiagnosticsProcessor {

    private final AzureCosmosDBProperties properties;

    ResponseDiagnosticsProcessorImplementation(AzureCosmosDBProperties properties) {
      this.properties = properties;
    }

    @Override
    public void processResponseDiagnostics(@Nullable ResponseDiagnostics responseDiagnostics) {
      if (properties.isResponseDiagnosticsEnabled()) {
        log.info("Response Diagnostics {}", responseDiagnostics);
      }
    }
  }

  @Override
  protected String getDatabaseName() {
    return properties.getDatabase();
  }
}
```

**Repository**
```

public interface UserRepository extends CosmosRepository<User, String> {

}
```

***Why is this not a Bug or a feature Request?***
A clear explanation of why is this not a bug or a feature request?

**Setup (please complete the following information if applicable):**
 - OS: Windows
 - IDE: IntelliJ
 - Library/Libraries: 
 Spring Boot version : 3.1.6
  Spring-cloud-azure-starter-data-cosmos: 5.7.0
  java : 17

Could someone please help or suggest what am I doing wrong here ?

Let me know if you need any additional information

**Comment by Netyyyy** [comment]
@kushagraThapar please help take a look

**Comment by somedeveloper89** [comment]
I'm experiencing something similar with my spring project. To be sure that it's not my mistake I tried connecting to the Azure Cosmos Emulator via the sample project that is included in the [quickstart project ](https://localhost:8081/_explorer/quickstart/DocumentDB-Quickstart-Java.zip). The exception that I get is: 

`reactor.core.Exceptions$ReactiveException: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at reactor.core.Exceptions.propagate(Exceptions.java:336)
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:91)
	at reactor.core.publisher.Mono.block(Mono.java:1663)
	at com.azure.cosmos.internal.RxDocumentClientImpl.initializeGatewayConfigurationReader(RxDocumentClientImpl.java:262)
	at com.azure.cosmos.internal.RxDocumentClientImpl.init(RxDocumentClientImpl.java:281)
	at com.azure.cosmos.internal.AsyncDocumentClient$Builder.build(AsyncDocumentClient.java:185)
	at com.azure.cosmos.CosmosAsyncClient.<init>(CosmosAsyncClient.java:64)
	at com.azure.cosmos.CosmosClientBuilder.buildAsyncClient(CosmosClientBuilder.java:206)
	at com.azure.cosmos.CosmosClient.<init>(CosmosClient.java:21)
	at com.azure.cosmos.CosmosClientBuilder.buildClient(CosmosClientBuilder.java:226)
	at com.azure.cosmos.sample.sync.SyncMain.getStartedDemo(SyncMain.java:86)
	at com.azure.cosmos.sample.sync.SyncMain.main(SyncMain.java:56)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:93)
		... 10 more
Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:371)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:314)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:309)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:654)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:473)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:369)
	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:480)
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1277)
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1264)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask.run(SSLEngineImpl.java:1209)
	at io.netty.handler.ssl.SslHandler.runAllDelegatedTasks(SslHandler.java:1499)
	at io.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:1513)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1397)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1224)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1271)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:505)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:444)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:283)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439)
	at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306)
	at java.base/sun.security.validator.Validator.validate(Validator.java:264)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:285)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:144)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:632)
	... 32 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434)
	... 37 more
Cosmos getStarted failed with reactor.core.Exceptions$ReactiveException: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "com.azure.cosmos.CosmosClient.close()" because "this.client" is null
	at com.azure.cosmos.sample.sync.SyncMain.close(SyncMain.java:43)
	at com.azure.cosmos.sample.sync.SyncMain.main(SyncMain.java:63)`

**Comment by kushagraThapar** [comment]
@pyramesh - that is just a warning, and can happen intermittently if there is some network packet drop issue. Are you not able to connect to your cosmos account at all? Or is this issue happening every now and then?

@somedeveloper89 - the reason you are seeing certificate issue is because you have not exported the emulator ssl certificates to your java security cacerts keystore. 

Unfortunately there is some issue with our docs - where the content on how to export emulator certificates is deleted - but its being worked upon and should be back online by next week.

**Comment by kushagraThapar** [comment]
Closing this issue because of inactivity. Please re-open if the issue still persists.
