### ISSUE TITLE
[BUG] Most messages sent to Azure Service Bus queue from producer are unsuccessful, only a few are sent successfully

### ISSUE THREAD

**Issue by 3d3n** [Azure/azure-sdk-for-java#38053]
**Describe the bug**

We have an Azure service bus producer sending messages to a queue, the first few messages are successful, the rest fails and pod crashes eventually. An async method processes thousands of records and sends the results to the service bus queue. 

***Exception or Stack Trace***
**Producer**

```
lambda$handleSendResponseAsync$0(DefaultMessageHandler.java:101) - GenericMessage [payload={...}, headers={replyChannel=nullChannel, errorChannel=, id=c18eca79-8a97-b0db-d84f-d4c163a15e58, timestamp=1702503618434}] sent failed in async mode due to Retries exhausted: 3/3
```
```
2023-12-13 21:43:40,560 [ INFO ] [parallel-1] onFailure(ServiceBusConfig.java:41) - There was an error sending the message.
2023-12-13 21:43:40,560 [ERROR ] [parallel-1] error(Loggers.java:324) - Operator called default onErrorDropped
reactor.core.Exceptions$ErrorCallbackNotImplemented: com.azure.messaging.servicebus.ServiceBusException: Retries exhausted: 3/3
Caused by: com.azure.messaging.servicebus.ServiceBusException: Retries exhausted: 3/3
	at com.azure.messaging.servicebus.ServiceBusSenderAsyncClient.mapError(ServiceBusSenderAsyncClient.java:823)
	at reactor.core.publisher.Mono.lambda$onErrorMap$28(Mono.java:3783)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:180)
	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onError(MonoPeekTerminal.java:258)
	at reactor.core.publisher.SerializedSubscriber.onError(SerializedSubscriber.java:124)
	at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.whenError(FluxRetryWhen.java:225)
	at reactor.core.publisher.FluxRetryWhen$RetryWhenOtherSubscriber.onError(FluxRetryWhen.java:274)
	at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onError(FluxContextWrite.java:121)
	at reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.maybeOnError(FluxConcatMapNoPrefetch.java:326)
	at reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.onNext(FluxConcatMapNoPrefetch.java:211)
	at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107)
	at reactor.core.publisher.SinkManyEmitterProcessor.drain(SinkManyEmitterProcessor.java:471)
	at reactor.core.publisher.SinkManyEmitterProcessor.tryEmitNext(SinkManyEmitterProcessor.java:269)
	at reactor.core.publisher.SinkManySerialized.tryEmitNext(SinkManySerialized.java:100)
	at reactor.core.publisher.InternalManySink.emitNext(InternalManySink.java:27)
	at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.onError(FluxRetryWhen.java:190)
	at reactor.core.publisher.SerializedSubscriber.onError(SerializedSubscriber.java:124)
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.handleTimeout(FluxTimeout.java:295)
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.doTimeout(FluxTimeout.java:280)
	at reactor.core.publisher.FluxTimeout$TimeoutTimeoutSubscriber.onNext(FluxTimeout.java:419)
	at reactor.core.publisher.FluxOnErrorReturn$ReturnSubscriber.onNext(FluxOnErrorReturn.java:162)
	at reactor.core.publisher.MonoDelay$MonoDelayRunnable.propagateDelay(MonoDelay.java:271)
	at reactor.core.publisher.MonoDelay$MonoDelayRunnable.run(MonoDelay.java:286)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: reactor.core.Exceptions$RetryExhaustedException: Retries exhausted: 3/3
	at reactor.core.Exceptions.retryExhausted(Exceptions.java:306)
	at reactor.util.retry.RetryBackoffSpec.lambda$static$0(RetryBackoffSpec.java:68)
	at reactor.util.retry.RetryBackoffSpec.lambda$null$4(RetryBackoffSpec.java:560)
	at reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.onNext(FluxConcatMapNoPrefetch.java:183)
	... 20 common frames omitted
Caused by: java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 60000ms in 'peek' (and no fallback has been configured)
	... 13 common frames omitted
2023-12-13 21:43:40,567 [ INFO ] [parallel-1] performLogging(ClientLogger.java:493) - Azure Identity => Attempted credential EnvironmentCredential is unavailable.

```
**Consumer**
```
2023-12-13 13:59:17,685 [ WARN ] [reactor-executor-1] performLogging(LoggingEventBuilder.java:362) -- {"az.sdk.message":"onTransportError","connectionId":"MF_a81823_1702428642699","errorCondition":"amqp:connection:framing-error","errorCondition":"connection aborted","hostName":"NAMESPACE.servicebus.windows.net"}
2023-12-13 13:59:17,687 [ INFO ] [reactor-executor-1] performLogging(LoggingEventBuilder.java:359) - {"az.sdk.message":"Disposing of ReactorConnection.","connectionId":"MF_a81823_1702428642699","isTransient":false,"isInitiatedByClient":false,"shutdownMessage":"connection aborted, errorContext[NAMESPACE: NAMESPACE.servicebus.windows.net. ERROR CONTEXT: N/A]"}
2023-12-13 13:59:17,692 [ INFO ] [reactor-executor-1] performLogging(LoggingEventBuilder.java:359) - {"az.sdk.message":"onConnectionUnbound","connectionId":"MF_a81823_1702428642699","hostName":"NAMESPACE.servicebus.windows.net","state":"CLOSED","remoteState":"ACTIVE"}
2023-12-13 13:59:17,692 [ INFO ] [reactor-executor-1] performLogging(LoggingEventBuilder.java:359) - {"az.sdk.message":"onLinkFinal","connectionId":"MF_a81823_1702428642699","linkName":"ENTITY_NAME","entityPath":"ENTITY_NAME"}
2023-12-13 13:59:17,693 [ INFO ] [reactor-executor-1] info(ClientLogger.java:221) - Receive link endpoint states are closed. Requesting another.
2023-12-13 13:59:17,694 [ INFO ] [reactor-executor-1] info(ClientLogger.java:221) - Requesting a new AmqpReceiveLink from upstream.
2023-12-13 13:59:17,696 [ERROR ] [reactor-executor-1] performLogging(LoggingEventBuilder.java:365) - {"az.sdk.message":"","exception":"Cannot create receive link from a closed session., errorContext[NAMESPACE: NAMESPACE.servicebus.windows.net. ERROR CONTEXT: N/A, PATH: ENTITY_NAME]","connectionId":"MF_a81823_1702428642699","sessionName":"ENTITY_NAME","linkName":"ENTITY_NAME"}
2023-12-13 13:59:17,698 [ INFO ] [reactor-executor-1] performLogging(LoggingEventBuilder.java:359) - {"az.sdk.message":"onSessionFinal.","connectionId":"MF_a81823_1702428642699","sessionName":"ENTITY_NAME"}
2023-12-13 13:59:17,698 [ INFO ] [reactor-executor-1] performLogging(LoggingEventBuilder.java:359) - {"az.sdk.message":"onLinkFinal","connectionId":"MF_a81823_1702428642699","linkName":"cbs:sender","entityPath":"$cbs"}
2023-12-13 13:59:17,698 [ INFO ] [reactor-executor-1] performLogging(LoggingEventBuilder.java:359) - {"az.sdk.message":"onLinkFinal","connectionId":"MF_a81823_1702428642699","linkName":"cbs:receiver","entityPath":"$cbs"}
2023-12-13 13:59:17,698 [ INFO ] [reactor-executor-1] performLogging(LoggingEventBuilder.java:359) - {"az.sdk.message":"Channel is closed. Requesting upstream.","connectionId":"MF_a81823_1702428642699","entityPath":"$cbs"}
2023-12-13 13:59:17,699 [ INFO ] [reactor-executor-1] performLogging(LoggingEventBuilder.java:359) - {"az.sdk.message":"Connection not requested, yet. Requesting one.","connectionId":"MF_a81823_1702428642699","entityPath":"$cbs"}
2023-12-13 13:59:17,699 [ INFO ] [reactor-executor-1] performLogging(LoggingEventBuilder.java:359) - {"az.sdk.message":"Emitting new response channel.","connectionId":"MF_a81823_1702428642699","entityPath":"$cbs","linkName":"cbs"}
2023-12-13 13:59:17,699 [ INFO ] [reactor-executor-1] performLogging(LoggingEventBuilder.java:359) - {"az.sdk.message":"Setting next AMQP channel.","connectionId":"MF_a81823_1702428642699","entityPath":"$cbs"}
2023-12-13 13:59:17,699 [ INFO ] [reactor-executor-1] performLogging(LoggingEventBuilder.java:359) - {"az.sdk.message":"Upstream connection publisher was completed. Terminating processor.","connectionId":"MF_a81823_1702428642699","entityPath":"$cbs"}
2023-12-13 13:59:17,700 [ INFO ] [reactor-executor-1] performLogging(LoggingEventBuilder.java:359) - {"az.sdk.message":"onSessionFinal.","connectionId":"MF_a81823_1702428642699","sessionName":"cbs-session"}
2023-12-13 13:59:17,700 [ INFO ] [reactor-executor-1] performLogging(LoggingEventBuilder.java:359) - {"az.sdk.message":"onConnectionFinal","connectionId":"MF_a81823_1702428642699","errorCondition":"amqp:resource-limit-exceeded","errorCondition":"local-idle-timeout expired","hostName":"NAMESPACE.servicebus.windows.net"}
2023-12-13 13:59:17,702 [ INFO ] [reactor-executor-1] performLogging(LoggingEventBuilder.java:359) - {"az.sdk.message":"Closing executor.","connectionId":"MF_a81823_1702428642699"}
2023-12-13 13:59:17,702 [ INFO ] [reactor-executor-1] performLogging(LoggingEventBuilder.java:359) - {"az.sdk.message":"Sender link was never active. Closing endpoint states.","connectionId":"MF_a81823_1702428642699","linkName":"cbs","entityPath":"$cbs"}
2023-12-13 13:59:17,702 [ INFO ] [reactor-executor-1] performLogging(LoggingEventBuilder.java:359) - {"az.sdk.message":"Receiver link was never active. Closing endpoint states","connectionId":"MF_a81823_1702428642699","entityPath":"$cbs","linkName":"cbs"}
2023-12-13 13:59:17,702 [ INFO ] [reactor-executor-1] performLogging(LoggingEventBuilder.java:359) - {"az.sdk.message":"Channel is disposed.","connectionId":"MF_a81823_1702428642699","entityPath":"$cbs"}
2023-12-13 13:59:17,703 [ INFO ] [reactor-executor-1] performLogging(LoggingEventBuilder.java:359) - {"az.sdk.message":"onTransportClosed","connectionId":"MF_a81823_1702428642699","errorCondition":"amqp:connection:framing-error","errorCondition":"connection aborted","hostName":"NAMESPACE.servicebus.windows.net"}
2023-12-13 13:59:17,703 [ INFO ] [reactor-executor-1] performLogging(LoggingEventBuilder.java:359) - {"az.sdk.message":"onTransportClosed","connectionId":"MF_a81823_1702428642699","hostName":"NAMESPACE.servicebus.windows.net"}
2023-12-13 13:59:21,702 [ INFO ] [reactor-executor-1] performLogging(LoggingEventBuilder.java:359) - {"az.sdk.message":"Processing all pending tasks and closing old reactor.","connectionId":"MF_a81823_1702428642699"}
2023-12-13 13:59:21,703 [ INFO ] [reactor-executor-1] performLogging(LoggingEventBuilder.java:359) - {"az.sdk.message":"Reactor selectable is being disposed.","connectionId":"MF_a81823_1702428642699"}
2023-12-13 13:59:21,703 [ INFO ] [reactor-executor-1] performLogging(LoggingEventBuilder.java:359) - {"az.sdk.message":"onConnectionShutdown. Shutting down.","connectionId":"MF_a81823_1702428642699","isTransient":false,"isInitiatedByClient":false,"shutdownMessage":"connectionId[MF_a81823_1702428642699] Reactor selectable is disposed.","namespace":"NAMESPACE.servicebus.windows.net"}
2023-12-13 13:59:21,708 [ERROR ] [reactor-executor-1] error(Loggers.java:324) - Operator called default onErrorDropped
reactor.core.Exceptions$ErrorCallbackNotImplemented: com.azure.core.amqp.exception.AmqpException: connection aborted, errorContext[NAMESPACE: NAMESPACE.servicebus.windows.net. ERROR CONTEXT: N/A]
Caused by: com.azure.core.amqp.exception.AmqpException: connection aborted, errorContext[NAMESPACE: NAMESPACE.servicebus.windows.net. ERROR CONTEXT: N/A]
	at com.azure.core.amqp.implementation.ExceptionUtil.toException(ExceptionUtil.java:85)
	at com.azure.core.amqp.implementation.handler.ConnectionHandler.notifyErrorContext(ConnectionHandler.java:351)
	at com.azure.core.amqp.implementation.handler.ConnectionHandler.onTransportError(ConnectionHandler.java:253)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:191)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291)
	at com.azure.core.amqp.implementation.ReactorExecutor.run(ReactorExecutor.java:91)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
2023-12-13 13:59:21,712 [ INFO ] [reactor-executor-1] performLogging(LoggingEventBuilder.java:359) - {"az.sdk.message":"Transient error occurred. Retrying.","exception":"connection aborted, errorContext[NAMESPACE: NAMESPACE.servicebus.windows.net. ERROR CONTEXT: N/A]","entityPath":"N/A","tryCount":0,"interval_ms":4511}
2023-12-13 13:59:21,712 [ INFO ] [reactor-executor-1] performLogging(LoggingEventBuilder.java:359) - {"az.sdk.message":"onConnectionShutdown. Shutting down.","connectionId":"MF_a81823_1702428642699","isTransient":false,"isInitiatedByClient":false,"shutdownMessage":"Finished processing pending tasks.","namespace":"NAMESPACE.servicebus.windows.net"}
2023-12-13 13:59:22,893 [ INFO ] [boundedElastic-1] info(ClientLogger.java:221) - Removing receiver links.
2023-12-13 13:59:22,894 [ INFO ] [boundedElastic-1] performLogging(LoggingEventBuilder.java:359) - {"az.sdk.message":"Closing a dependent client.","numberOfOpenClients":0}
2023-12-13 13:59:22,894 [ INFO ] [boundedElastic-1] info(ClientLogger.java:221) - No more open clients, closing shared connection.
2023-12-13 13:59:22,894 [ INFO ] [boundedElastic-1] performLogging(LoggingEventBuilder.java:359) - {"az.sdk.message":"Upstream connection publisher was completed. Terminating processor.","entityPath":"N/A"}
2023-12-13 13:59:22,894 [ERROR ] [boundedElastic-1] performLogging(LoggingEventBuilder.java:365) - {"az.sdk.message":"Cannot subscribe. Processor is already terminated.","exception":"Cannot subscribe. Processor is already terminated.","entityPath":"N/A"}
2023-12-13 13:59:22,895 [ERROR ] [boundedElastic-1] performLogging(ClientLogger.java:505) - Failed to create receive linkENTITY_NAME
Cannot subscribe. Processor is already terminated.
2023-12-13 13:59:22,895 [ INFO ] [boundedElastic-1] info(ClientLogger.java:221) - AmqpReceiveLinkProcessor is terminated. Not reopening on error.
2023-12-13 13:59:22,895 [ INFO ] [boundedElastic-1] performLogging(LoggingEventBuilder.java:359) - {"az.sdk.message":"AMQP channel processor completed.","entityPath":"N/A","subscriberId":"un_843dda_1702475962551"}
2023-12-13 13:59:22,895 [ INFO ] [boundedElastic-1] performLogging(LoggingEventBuilder.java:359) - {"az.sdk.message":"Setting next AMQP channel.","entityPath":"N/A"}
2023-12-13 13:59:22,895 [ INFO ] [boundedElastic-1] performLogging(ClientLogger.java:493) - # of open clients with shared connection: 1
2023-12-13 13:59:22,896 [ INFO ] [boundedElastic-1] performLogging(LoggingEventBuilder.java:359) - {"az.sdk.message":"Creating consumer.","linkName":"ENTITY_NAME","entityPath":"ENTITY_NAME"}
2023-12-13 13:59:22,896 [ INFO ] [boundedElastic-1] info(ClientLogger.java:221) - Requesting a new AmqpReceiveLink from upstream.
2023-12-13 13:59:22,896 [ INFO ] [boundedElastic-1] performLogging(LoggingEventBuilder.java:359) - {"az.sdk.message":"Creating and starting connection.","connectionId":"MF_8c7204_1702475962895","hostName":"NAMESPACE.servicebus.windows.net","port":5671}
2023-12-13 13:59:22,896 [ INFO ] [boundedElastic-1] performLogging(LoggingEventBuilder.java:359) - {"az.sdk.message":"Starting reactor.","connectionId":"MF_8c7204_1702475962895"}
2023-12-13 13:59:22,897 [ INFO ] [reactor-executor-2] performLogging(LoggingEventBuilder.java:359) - {"az.sdk.message":"onConnectionInit","connectionId":"MF_8c7204_1702475962895","hostName":"NAMESPACE.servicebus.windows.net","namespace":"NAMESPACE.servicebus.windows.net"}
2023-12-13 13:59:22,897 [ INFO ] [reactor-executor-2] performLogging(LoggingEventBuilder.java:359) - {"az.sdk.message":"reactor.onReactorInit","connectionId":"MF_8c7204_1702475962895"}
2023-12-13 13:59:22,897 [ INFO ] [reactor-executor-2] performLogging(LoggingEventBuilder.java:359) - {"az.sdk.message":"onConnectionLocalOpen","connectionId":"MF_8c7204_1702475962895","hostName":"NAMESPACE.servicebus.windows.net"}
2023-12-13 13:59:22,898 [ INFO ] [reactor-executor-2] performLogging(LoggingEventBuilder.java:359) - {"az.sdk.message":"onConnectionBound","connectionId":"MF_8c7204_1702475962895","hostName":"NAMESPACE.servicebus.windows.net","peerDetails":"NAMESPACE.servicebus.windows.net:5671"}
2023-12-13 13:59:23,163 [ INFO ] [reactor-executor-2] performLogging(LoggingEventBuilder.java:359) - {"az.sdk.message":"onConnectionRemoteOpen","connectionId":"MF_8c7204_1702475962895","hostName":"NAMESPACE.servicebus.windows.net","remoteContainer":"f057b5b33de64dc1a1aa4872ebfbf753_G12"}
2023-12-13 13:59:23,163 [ INFO ] [reactor-executor-2] performLogging(LoggingEventBuilder.java:359) - {"az.sdk.message":"Channel is now active.","entityPath":"N/A"}
2023-12-13 13:59:23,178 [ INFO ] [reactor-executor-2] performLogging(LoggingEventBuilder.java:359) - {"az.sdk.message":"onSessionRemoteOpen","connectionId":"MF_8c7204_1702475962895","sessionName":"ENTITY_NAME","sessionIncCapacity":0,"sessionOutgoingWindow":2147483647}
2023-12-13 13:59:23,179 [ INFO ] [reactor-executor-2] performLogging(LoggingEventBuilder.java:359) - {"az.sdk.message":"Setting CBS channel.","connectionId":"MF_8c7204_1702475962895"}
2023-12-13 13:59:23,194 [ INFO ] [reactor-executor-2] performLogging(LoggingEventBuilder.java:359) - {"az.sdk.message":"onSessionRemoteOpen","connectionId":"MF_8c7204_1702475962895","sessionName":"cbs-session","sessionIncCapacity":0,"sessionOutgoingWindow":2147483647}
2023-12-13 13:59:23,194 [ INFO ] [reactor-executor-2] performLogging(LoggingEventBuilder.java:359) - {"az.sdk.message":"Emitting new response channel.","connectionId":"MF_8c7204_1702475962895","entityPath":"$cbs","linkName":"cbs"}
2023-12-13 13:59:23,195 [ INFO ] [reactor-executor-2] performLogging(LoggingEventBuilder.java:359) - {"az.sdk.message":"Setting next AMQP channel.","connectionId":"MF_8c7204_1702475962895","entityPath":"$cbs"}
2023-12-13 13:59:23,195 [ INFO ] [reactor-executor-2] performLogging(ClientLogger.java:493) - Azure Identity => Attempted credential EnvironmentCredential is unavailable.

```

**To Reproduce**
1. setup Azure Service Bus with a single namespace
2. Async method processes records and sends results from the producer
3. Consumer consumes results and save 

***Code Snippet***
producer
```
 @Bean("queueMessageSender")
    @ServiceActivator(inputChannel = OUTPUT_CHANNEL)
    public MessageHandler queueMessageSender(ServiceBusTemplate serviceBusTemplate) {
        serviceBusTemplate.setDefaultEntityType(ServiceBusEntityType.QUEUE);
        DefaultMessageHandler handler = new DefaultMessageHandler(queueName, serviceBusTemplate);
        handler.setLoggingEnabled(false);
        handler.setSendCallback(new ListenableFutureCallback<Void>() {
            @Override
            public void onSuccess(Void result) {
                LOGGER.info("Message was sent successfully.");
            }

            @Override
            public void onFailure(Throwable ex) {
                LOGGER.info("There was an error sending the message.");
            }
        });
        return handler;
    }

    @MessagingGateway(defaultRequestChannel = OUTPUT_CHANNEL)
    public interface QueueOutboundGateway {
        void send(Message<String> text);
    }
```

```
   try {
                    String payload = messages.get(index).toString();

                    Message<String> message = MessageBuilder.withPayload(payload).build();
                    messagingGateway.send(message);
                } catch (Exception ex) {
                    log.error("Error publishing to queue", ex);
                }
```
receiver
```
@Bean("queue-listener-container")
    public ServiceBusMessageListenerContainer messageListenerContainer(ServiceBusProcessorFactory processorFactory) {
        ServiceBusContainerProperties containerProperties = new ServiceBusContainerProperties();
        containerProperties.setEntityName(QUEUE_NAME);
        containerProperties.setMaxConcurrentCalls(10);
        containerProperties.setReceiveMode(ServiceBusReceiveMode.RECEIVE_AND_DELETE);
        return new ServiceBusMessageListenerContainer(processorFactory, containerProperties);
    }

    @Bean
    public ServiceBusInboundChannelAdapter queueMessageChannelAdapter(
            @Qualifier(INPUT_CHANNEL) MessageChannel inputChannel,
            @Qualifier("queue-listener-container") ServiceBusMessageListenerContainer listenerContainer) {
        ServiceBusInboundChannelAdapter adapter = new ServiceBusInboundChannelAdapter(listenerContainer);
        adapter.setOutputChannel(inputChannel);
        return adapter;
    }

    @Bean(name = INPUT_CHANNEL)
    public MessageChannel input() {
        return new DirectChannel();
    }

```

```
 @ServiceActivator(inputChannel = ServiceBusConfig.INPUT_CHANNEL)
    public void consumeMessage(byte[] payload) {
        String message = new String(payload);
        consumeMessage(message);
    }
```

**Expected behavior**
Producer should be able to send all messages and Consumer should be able to pick all messages from the Queue or atleast handle errors without crashing the pod.

**Screenshots**

**Setup (please complete the following information):**
- Platform: Azure Kubernetes
 - Library/Libraries: com.azure.spring:spring-cloud-azure-dependencies:5.3.0
 - Java version: Java 17
 - Frameworks: Spring Boot 3.1.2

**Additional context**
- Fairly new to using Azure Service Bus, kindly assist.
- Managed Identity used 
- References for implementation below: 
[Docs](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/using-service-bus-in-spring-applications#use-spring-integration-azure-service-bus)
[GitHub Pages](https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_5.3.0/servicebus/spring-cloud-azure-starter-integration-servicebus/single-namespace/src/main/java/com/azure/spring/sample/servicebus)

I don't know what we are doing wrong.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by Netyyyy** [comment]
Hi @3d3n , Could you try with spring-cloud-azure-dependencies 5.8.0?

**Comment by 3d3n** [comment]
Hi @Netyyyy thanks for the response,  we have upgraded to v5.8.0  and tests have been successful so far. 

I'll give an update once tests are concluded.

**Comment by 3d3n** [comment]
@Netyyyy with less than 1000 records, the process is successful. Tests with over 1000 records are producing the same errors initially reported.

**Comment by Netyyyy** [comment]
Hi @anuchandy , please help take a look, is there a limit to the number of messages?

**Comment by 3d3n** [comment]
Prior to the dependency upgrade sending messages were unsuccessful, after the upgrade we have been able to see messages been sent and received successfully albeit intermittently.
 
In the cases where it was unsuccessful, the errors were the same as before the dependency upgrade.

We think the main issue is this log message, **"Azure Identity => Attempted credential EnvironmentCredential is Unavailable",** because expired tokens are not refreshed in the cache. 

when we restarted the pod,  for less than a second the error is logged over a thousand times, then log message "Returning token from cache". After that, messages where sent successfully.

**Comment by Netyyyy** [comment]
> Prior to the dependency upgrade sending messages were unsuccessful, after the upgrade we have been able to see messages been sent and received successfully albeit intermittently.
> 
> In the cases where it was unsuccessful, the errors were the same as before the dependency upgrade.
> 
> We think the main issue is this log message, **"Azure Identity => Attempted credential EnvironmentCredential is Unavailable",** because expired tokens are not refreshed in the cache.
> 
> when we restarted the pod, for less than a second the error is logged over a thousand times, then log message "Returning token from cache". After that, messages where sent successfully.

what does "successfully albeit intermittently" mean? what does the error look like which logged over a thousand times?
Could you help provide a minimal project?
