### ISSUE TITLE
Exception: JsonParseException: Unexpected character ('<' (code 60))

### ISSUE THREAD

**Issue by MateuszSzybiak** [Azure/azure-sdk-for-java#38140]
**Describe the bug**
I'm using a Java Azure Function to send messages to Azure Storage Queue. During local development I initialize QueueClient with Managed Identity. When I use sendMessage function it puts the message on Queue, but instantly after that the process crash with exception presented below. It seams to Azure SDK returns XML data as a result, which were expecting JSON. 

I run the code using Powershell command `mvn clean package` and then `mvn azure-functions:run`

***Exception or Stack Trace***
`System.Private.CoreLib: Exception while executing function: Functions.ProcessorTechlogFile. System.Private.CoreLib: Result: Failure
Exception: JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (byte[])"?<?xml version="1.0" encoding="utf-8"?><QueueMessagesList><QueueMessage><MessageId>cb2f7e34-387f-40c8-a3aa-742d4eb403e8</MessageId><InsertionTime>Thu, 21 Dec 2023 13:53:19 GMT</InsertionTime><ExpirationTime>Thu, 28 Dec 2023 13:53:19 GMT</ExpirationTime><PopReceipt>AgAAAAMAAAAAAAAAl2kxDhU02gE=</PopReceipt><TimeNextVisible>Thu, 21 Dec 2023 13:53:19 GMT</TimeNextVisible></QueueMessage></QueueMessagesList>"; line: 1, column: 5]
Stack: java.lang.reflect.InvocationTargetException
[2023-12-21T13:53:19.852Z]      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2023-12-21T13:53:19.853Z]      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2023-12-21T13:53:19.853Z]      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2023-12-21T13:53:19.854Z]      at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2023-12-21T13:53:19.854Z]      at com.microsoft.azure.functions.worker.broker.JavaMethodInvokeInfo.invoke(JavaMethodInvokeInfo.java:22)
[2023-12-21T13:53:19.854Z]      at com.microsoft.azure.functions.worker.broker.EnhancedJavaMethodExecutorImpl.execute(EnhancedJavaMethodExecutorImpl.java:22)
[2023-12-21T13:53:19.855Z]      at com.microsoft.azure.functions.worker.chain.FunctionExecutionMiddleware.invoke(FunctionExecutionMiddleware.java:19)
[2023-12-21T13:53:19.855Z]      at com.microsoft.azure.functions.worker.chain.InvocationChain.doNext(InvocationChain.java:21)
[2023-12-21T13:53:19.856Z]      at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:125)
[2023-12-21T13:53:19.856Z]      at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:34)
[2023-12-21T13:53:19.856Z]      at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)
[2023-12-21T13:53:19.857Z]      at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:44)
[2023-12-21T13:53:19.857Z]      at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:94)
[2023-12-21T13:53:19.857Z]      at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[2023-12-21T13:53:19.858Z]      at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2023-12-21T13:53:19.858Z]      at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[2023-12-21T13:53:19.858Z]      at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[2023-12-21T13:53:19.859Z]      at java.base/java.lang.Thread.run(Thread.java:842)
[2023-12-21T13:53:19.859Z] Caused by: com.azure.core.exception.HttpResponseException: Deserialization Failed.`

As Azure Storage Queue API sends its response in XML format and my java program it trying to deserialize it as JSON, I don't know how to make it to treat the response as XML. Maybe there is a specific setting for It but I'm not sure.

***Code Snippet***

```
DefaultAzureCredentialBuilder credentialBuilder = new DefaultAzureCredentialBuilder();
        this.queueClient1 = new QueueClientBuilder()
                .endpoint("https://<QUEUE_NAME>.queue.core.windows.net")
                .queueName(this.STORAGE_ACCOUNT_OUTPUT_QUEUE_NAME + Integer.toString(0))
                .credential(credentialBuilder.build())
                .buildClient();
                
        SendMessageResult response = queueClient1.sendMessage("Testing");
```

**Expected behavior**
The sendMessage put the message on queue without crash.

**Setup (please complete the following information):**
 - OS: Windows 10
 - IDE: Visual Studio Code
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)]
 - Java version: 17
 - App Server/Environment: Azure Function
 - Dependencies:

```
<dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-core</artifactId>
            <version>1.45.0</version>
        </dependency>
<dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-identity</artifactId>
            <version>1.10.1</version>
        </dependency>

        <dependency>
            <groupId>com.microsoft.azure</groupId>
            <artifactId>azure-storage</artifactId>
            <version>8.6.6</version>
        </dependency>

        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-storage-blob</artifactId>
            <version>12.24.0</version>
        </dependency>

        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-storage-queue</artifactId>
            <version>12.20.1</version>
        </dependency>

        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-storage-common</artifactId>
            <version>12.24.0</version>
        </dependency>
```

**Comment by joshfree** [comment]
Hi @MateuszSzybiak, from the callstack I believe this is an issue that should be moved to the https://github.com/Azure/azure-functions-java-library repo for the Azure Functions folks to follow up.
