### ISSUE TITLE
[BUG] dataLakeFileSystemClient,listPaths() throws NumberFormatException

### ISSUE THREAD

**Issue by deewar** [Azure/azure-sdk-for-java#38197]
**Describe the bug**
The code below 
`    DataLakeServiceClient dataLakeServiceClient = new DataLakeServiceClientBuilder()
            .endpoint("https://something.dfs.core.windows.net")
            .credential(new StorageSharedKeyCredential(
                    "accountname",
                    "="))
            .buildClient();
    DataLakeFileSystemClient dataLakeFileSystemClient = dataLakeServiceClient.getFileSystemClient("containename");
    List<PathItem> pathItems = dataLakeFileSystemClient.getDirectoryClient("").listPaths().stream()
            .collect(Collectors.toList());
        Assertions.assertEquals(pathItems.size(), 5);`

throws 

`For input string: "Tue, 02 Jan 2024 14:29:41 GMT"
java.lang.NumberFormatException: For input string: "Tue, 02 Jan 2024 14:29:41 GMT"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Long.parseLong(Long.java:711)
	at java.base/java.lang.Long.parseLong(Long.java:836)
	at com.azure.storage.file.datalake.Transforms.toPathItem(Transforms.java:384)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at com.azure.storage.file.datalake.DataLakeDirectoryAsyncClient.lambda$listPathsWithOptionalTimeout$16(DataLakeDirectoryAsyncClient.java:1270)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:113)`

This is on 12.18.1 of the client skd and the code in question is here:
https://github.com/Azure/azure-sdk-for-java/blob/azure-storage-file-datalake_12.18.1/sdk/storage/azure-storage-file-datalake/src/main/java/com/azure/storage/file/datalake/Transforms.java#L384

looking at main, the code appears to be different  and catches this exception
https://github.com/Azure/azure-sdk-for-java/blob/2c940cfb82d1ff2c4691a464e0a6d1dd64b43b2e/sdk/storage/azure-storage-file-datalake/src/main/java/com/azure/storage/file/datalake/Transforms.java#L386

I cant figure out how the releases are managed so not sure when the bug was introduced vs fixed  - can we release another version with the fix that exists in main?

***Exception or Stack Trace***
` input string: "Tue, 02 Jan 2024 14:29:41 GMT"
java.lang.NumberFormatException: For input string: "Tue, 02 Jan 2024 14:29:41 GMT"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Long.parseLong(Long.java:711)
	at java.base/java.lang.Long.parseLong(Long.java:836)
	at com.azure.storage.file.datalake.Transforms.toPathItem(Transforms.java:384)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at com.azure.storage.file.datalake.DataLakeDirectoryAsyncClient.lambda$listPathsWithOptionalTimeout$16(DataLakeDirectoryAsyncClient.java:1270)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:113)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1839)
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:249)
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129)
	at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:191)
	at reactor.core.publisher.FluxSubscribeOnCallable$CallableSubscribeOnSubscription.run(FluxSubscribeOnCallable.java:251)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:100)
		at reactor.core.publisher.Flux.blockLast(Flux.java:2761)`
**To Reproduce**
See above
***Code Snippet***
see above
**Expected behavior**
List file returns a list of files
**Screenshots**

**Setup (please complete the following information):**
 - OS: [e.g. iOS] mac os
 - IDE: [e.g. IntelliJ] intellij 
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)]
 `
    implementation platform('com.azure:azure-sdk-bom:1.2.19')
    implementation 'com.azure:azure-storage-blob'
    implementation 'com.azure:azure-identity'
    implementation 'com.azure:azure-storage-file-datalake'

`
 - Java version: [e.g. 8] 
 - App Server/Environment: [e.g. Tomcat, WildFly, Azure Function, Apache Spark, Databricks, IDE plugin or anything special]
 - Frameworks: [e.g. Spring Boot, Micronaut, Quarkus, etc] 

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by ibrahimrabab** [comment]
Hi @deewar 
Thanks for reaching out! There was a fix introduced for the issue you are experiencing and we are scheduled to roll out our patch release fix in February. The latest azure-storage-blob version 12.26.0 that will be released next month will be the version containing the fix. 

If this is an urgent need, we can look into releasing patch fix sooner.

**Comment by deewar** [comment]
@ibrahimrabab  considering this only happens when trying to use the azure-storage-file-datalake sdk against a storage account with hierarchical namespace disabled i think it might be fine to wait for the next release. I  will continue to test with an accout with heirarchical namespace enabled for now.
