### ISSUE TITLE
[BUG] Unable to Authenticate Azure MySQL Single Server using Managed identity authentication

### ISSUE THREAD

**Issue by Afsalmc** [Azure/azure-sdk-for-java#38281]
**Describe the bug**
Unable to Authenticate Azure MySQL Single Server using Managed identity authentication.

***Exception or Stack Trace***
Caused by: java.sql.SQLException: Azure AD access token is not valid for user 'id-xx-xxxxx-eus-01' with OID 'xxxx-xxxx-xxxx-xxxx-xxxx'.
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:130)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:825)
        at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:446)
        at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:239)
        at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:188)
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359)
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470)
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100)
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
        at org.apache.shardingsphere.infra.datasource.pool.CatalogSwitchableDataSource.getConnection(CatalogSwitchableDataSource.java:46)
        at org.apache.shardingsphere.infra.state.datasource.DataSourceStateManager.checkState(DataSourceStateManager.java:86)

**To Reproduce**

In ShardingSphere Yaml config 
```
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc
    jdbcUrl: jdbc:mysql://servername.mysql.database.azure.com:3306/dbname?sslMode=REQUIRED&serverTimezone=UTC&defaultAuthenticationPlugin=com.azure.identity.extensions.jdbc.mysql.AzureMysqlAuthenticationPlugin&authenticationPlugins=com.azure.identity.extensions.jdbc.mysql.AzureMysqlAuthenticationPlugin&azure.managedIdentityEnabled=true
    username: id-xx-xxxxx-eus-01@servername
    azure:
      managedIdentityEnabled : true
```

**Setup (please complete the following information):**
 - OS: Ubuntu 22.04
 - Library/Libraries: azure-identity-extensions : 1.1.11
 - Java version: 11
 - App Server/Environment: Azure VM
 - Frameworks: ShardingSphere

**Comment by Afsalmc** [comment]
Sorry My bad! AZURE_CLIENT_ID was wrong.
