### ISSUE TITLE
[BUG] get "code 416: The range specified is invalid for the current size of the resource." error when update file storage #14961 reopened.

### ISSUE THREAD

**Issue by 269345** [Azure/azure-sdk-for-java#38410]
Hi @gapra-msft

Do you have any further questions regarding the behavior of the API?

_Originally posted by @gapra-msft in https://github.com/Azure/azure-sdk-for-java/issues/14961#issuecomment-825125421_

I am seeing this as well. The problem is if I create the file size with max size, yes I am able to upload the file onto Azure-Storage/File Shares.. however regardless of my source file/content size, the size after uploading the file on the AZ Storage/file shares is always this max size initialized. This is an issue, that we are using more space regardless of our need. Pls suggest

**Comment by 269345** [comment]
[[BUG] get "code 416: The range specified is invalid for the current size of the resource." error when update file storage](https://github.com/Azure/azure-sdk-for-java/issues/14961#top)  #14961 reopened.

**Comment by joshfree** [comment]
@269345 thank you for reaching out to us via this github issue.  Could you please `Edit` the issue `title` and include more relevant information in the issue so that the `storage` team can assist?

**Comment by ibrahimrabab** [comment]
Hi @269345 
I'm trying to understand your situation a bit better. Are you first creating a file with a fixed size, and then uploading data that is smaller than the size of the file?
Can you provide a code snippet and an exception stack trace of what you're seeing?

**Comment by 269345** [comment]
@ibrahimrabab  Thank you, for looking into this.
pls find below stack trace, and the relevant code snippet.

stack trace: com.azure.storage.file.share.models.ShareStorageException: Status code 416, "?<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidRange</Code><Message>The range specified is invalid for the current size of the resource.
RequestId:a101e81b-d01a-003d-104c-4d52d8000000
Time:2024-01-22T16:03:11.7522809Z</Message></Error>"
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732) ~[?:?]
	at com.azure.core.implementation.MethodHandleReflectiveInvoker.invokeWithArguments(MethodHandleReflectiveInvoker.java:35) ~[azure-core-1.45.1.jar:1.45.1]
	at com.azure.core.implementation.http.rest.ResponseExceptionConstructorCache.invoke(ResponseExceptionConstructorCache.java:51) ~[azure-core-1.45.1.jar:1.45.1]
	at com.azure.core.implementation.http.rest.RestProxyBase.instantiateUnexpectedException(RestProxyBase.java:356) ~[azure-core-1.45.1.jar:1.45.1]
	at com.azure.core.implementation.http.rest.AsyncRestProxy.lambda$ensureExpectedStatus$1(AsyncRestProxy.java:128) ~[azure-core-1.45.1.jar:1.45.1]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:113) ~[reactor-core-3.4.34.jar:3.4.34]
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2400) ~[reactor-core-3.4.34.jar:3.4.34]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:171) ~[reactor-core-3.4.34.jar:3.4.34]
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:2196) ~[reactor-core-3.4.34.jar:3.4.34]
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:2070) ~[reactor-core-3.4.34.jar:3.4.34]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:96) ~[reactor-core-3.4.34.jar:3.4.34]
	at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:55) ~[reactor-core-3.4.34.jar:3.4.34]
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[reactor-core-3.4.34.jar:3.4.34]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157) ~[reactor-core-3.4.34.jar:3.4.34]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129) ~[reactor-core-3.4.34.jar:3.4.34]
	at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onNext(FluxHide.java:137) ~[reactor-core-3.4.34.jar:3.4.34]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129) ~[reactor-core-3.4.34.jar:3.4.34]
	at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onNext(FluxHide.java:137) ~[reactor-core-3.4.34.jar:3.4.34]
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79) ~[reactor-core-3.4.34.jar:3.4.34]
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1839) ~[reactor-core-3.4.34.jar:3.4.34]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151) ~[reactor-core-3.4.34.jar:3.4.34]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129) ~[reactor-core-3.4.34.jar:3.4.34]
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1839) ~[reactor-core-3.4.34.jar:3.4.34]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151) ~[reactor-core-3.4.34.jar:3.4.34]
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79) ~[reactor-core-3.4.34.jar:3.4.34]
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1839) ~[reactor-core-3.4.34.jar:3.4.34]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151) ~[reactor-core-3.4.34.jar:3.4.34]
	at reactor.core.publisher.Operators$MonoInnerProducerBase.complete(Operators.java:2666) ~[reactor-core-3.4.34.jar:3.4.34]
	at reactor.core.publisher.MonoSingle$SingleSubscriber.onComplete(MonoSingle.java:180) ~[reactor-core-3.4.34.jar:3.4.34]
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onComplete(MonoFlatMapMany.java:260) ~[reactor-core-3.4.34.jar:3.4.34]
	at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onComplete(FluxContextWrite.java:126) ~[reactor-core-3.4.34.jar:3.4.34]
	at reactor.core.publisher.MonoUsing$MonoUsingSubscriber.onNext(MonoUsing.java:232) ~[reactor-core-3.4.34.jar:3.4.34]
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:122) ~[reactor-core-3.4.34.jar:3.4.34]
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74) ~[reactor-core-3.4.34.jar:3.4.34]
	at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:126) ~[reactor-core-3.4.34.jar:3.4.34]
	at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:224) ~[reactor-core-3.4.34.jar:3.4.34]
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:113) ~[reactor-core-3.4.34.jar:3.4.34]
	at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:191) ~[reactor-core-3.4.34.jar:3.4.34]
	at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107) ~[reactor-core-3.4.34.jar:3.4.34]
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1839) ~[reactor-core-3.4.34.jar:3.4.34]
	at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:129) ~[reactor-core-3.4.34.jar:3.4.34]
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:260) ~[reactor-core-3.4.34.jar:3.4.34]
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144) ~[reactor-core-3.4.34.jar:3.4.34]
	at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:415) ~[reactor-netty-core-1.0.39.jar:1.0.39]
	at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:439) ~[reactor-netty-core-1.0.39.jar:1.0.39]
	at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:493) ~[reactor-netty-core-1.0.39.jar:1.0.39]
	at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:768) ~[reactor-netty-http-1.0.39.jar:1.0.39]
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:114) ~[reactor-netty-core-1.0.39.jar:1.0.39]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.101.Final.jar:4.1.101.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.101.Final.jar:4.1.101.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.101.Final.jar:4.1.101.Final]
	at com.azure.core.http.netty.implementation.AzureSdkHandler.channelRead(AzureSdkHandler.java:222) ~[azure-core-http-netty-1.13.11.jar:1.13.11]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[netty-transport-4.1.101.Final.jar:4.1.101.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.101.Final.jar:4.1.101.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.101.Final.jar:4.1.101.Final]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) ~[netty-transport-4.1.101.Final.jar:4.1.101.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[netty-codec-4.1.101.Final.jar:4.1.101.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[netty-codec-4.1.101.Final.jar:4.1.101.Final]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) ~[netty-transport-4.1.101.Final.jar:4.1.101.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[netty-transport-4.1.101.Final.jar:4.1.101.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.101.Final.jar:4.1.101.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.101.Final.jar:4.1.101.Final]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1475) ~[netty-handler-4.1.101.Final.jar:4.1.101.Final]
	at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1349) ~[netty-handler-4.1.101.Final.jar:4.1.101.Final]
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1389) ~[netty-handler-4.1.101.Final.jar:4.1.101.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529) ~[netty-codec-4.1.101.Final.jar:4.1.101.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468) ~[netty-codec-4.1.101.Final.jar:4.1.101.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[netty-codec-4.1.101.Final.jar:4.1.101.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.101.Final.jar:4.1.101.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.101.Final.jar:4.1.101.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.101.Final.jar:4.1.101.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.101.Final.jar:4.1.101.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[netty-transport-4.1.101.Final.jar:4.1.101.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.101.Final.jar:4.1.101.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.101.Final.jar:4.1.101.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[netty-transport-4.1.101.Final.jar:4.1.101.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.101.Final.jar:4.1.101.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.101.Final.jar:4.1.101.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.101.Final.jar:4.1.101.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.101.Final.jar:4.1.101.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.101.Final.jar:4.1.101.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.101.Final.jar:4.1.101.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.101.Final.jar:4.1.101.Final]
	at java.base/java.lang.Thread.run(Thread.java:842) ~[?:?]
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:100) ~[reactor-core-3.4.34.jar:3.4.34]
		at reactor.core.publisher.Mono.block(Mono.java:1742) ~[reactor-core-3.4.34.jar:3.4.34]
		at com.azure.storage.file.share.ShareFileClient.uploadFromFile(ShareFileClient.java:2002) ~[azure-storage-file-share-12.21.1.jar:12.21.1]
		at com.azure.storage.file.share.ShareFileClient.uploadFromFile(ShareFileClient.java:1975) ~[azure-storage-file-share-12.21.1.jar:12.21.1]
		at com.aa.rpt.fltinvhub.skd.generate.AZFileCopyService.uploadFileToAzureFileShares(AZFileCopyService.java:82) ~[classes/:?]
		at com.aa.rpt.fltinvhub.skd.generate.FileGeneratorService.generateScheduleFile(FileGeneratorService.java:91) [classes/:?]
		at com.aa.rpt.fltinvhub.skd.ScheduleFileGeneratorApplication.generateScheduleFile(ScheduleFileGeneratorApplication.java:71) [classes/:?]
		at com.aa.rpt.fltinvhub.skd.ScheduleFileGeneratorApplication.main(ScheduleFileGeneratorApplication.java:22) [classes/:?]


************************

code snippet:
   public void uploadFileToAzureFileShares(String filePath) {

   
        String shareName = "xyz";

        String dirName = "pqr";
        String fileName = new File(filePath).getName();

        System.out.println("fileName  is " + fileName);
        long maxFileSizeInBytes = 1024 ; //* 1024 * 10; 
        {
            try {
                ShareDirectoryClient dirClient = new ShareFileClientBuilder()
                        .connectionString(connectionStringFileStorage).shareName(shareName)
                        .resourcePath(dirName)
                        .buildDirectoryClient();

                ShareFileClient fileClient = dirClient.getFileClient(fileName);
                
                fileClient.create(maxFileSizeInBytes);
                fileClient.uploadFromFile(filePath);
                logger.info("File from: {} uploaded successfully to Azure File Share: {}", filePath, shareName);
            } catch (UncheckedIOException | IllegalArgumentException | NullPointerException | IllegalStateException e) {
                logger.error("Error uploading FileToAzureFileShares", e);
                    throw new RuntimeException("Exception in uploadFileToFileShares ", e);
             
                
            }
        }

    }

**Comment by ibrahimrabab** [comment]
@269345 I tried to reproduce your code snippet but did not see any errors thrown if the file size to upload is less than the ShareFileClient. What is the size of the filePath that you are uploading? The error only gets thrown if you created a ShareFileClient of a specific size (such as 1024 KB) and if you are trying to upload a file that is larger than the specific size you created the ShareFileClient with (such as 1024 * 10 KB), it will throw a 416.

**Comment by 269345** [comment]
@ibrahimrabab  The issue is I am able to upload the file without any error, that is if I pre-specify as                                                       long maxFileSizeInBytes = 1024 * 1024 * 10; now in this case after I successfully upload my file (of < maxFileSizeInBytes ), in the target fileshares,  the size is maxFileSizeInBytes by default .  the system is accounting the max size regardless of our usage. That's an issue.

**Comment by ibrahimrabab** [comment]
@269345 
Unfortunately in File Shares there isn't a way to automatically truncate/resize a file after you create it. You will need to manually create a file of the same size as the file you are trying to upload.

Sorry we could not be of more help in this situation but let us know if you have more questions!

**Comment by 269345** [comment]
@ibrahimrabab  Thanks for your attention on this. However if the file to be uploaded may not be precisely the same size always, how can we be sure of a particular size. Is it a known limitation on the java jdk support for AZ Storage/file shares? Our use-case is as the file is generated from our app, we will need to upload it onto the AZ Storage/File Shares

**Comment by ibrahimrabab** [comment]
@269345 
This is a limitation on the service, not the Java SDK. For your case, I would recommend only creating the file of the exact size you want to upload once it gets generated and uploading that. 

Hopefully this helps!
