### ISSUE TITLE
[BUG] Using Kusto QueuedIngestClient throwing ConcurrentModificationException

### ISSUE THREAD

**Issue by the-mod** [Azure/azure-sdk-for-java#38778]
**Describe the bug**
I saw in my application logs a lot of `ConcurrentModificationException` flying.
They also seam to occur irregularly and I haven't been able to reproduce it safely yet.

***Exception or Stack Trace***
This is the (shortened) Stacktrace I get:

```
java.util.ConcurrentModificationException
	at java.base/java.util.ArrayDeque.nonNullElementAt(ArrayDeque.java:269)
	at java.base/java.util.ArrayDeque$DeqIterator.next(ArrayDeque.java:699)
	at com.microsoft.azure.kusto.ingest.resources.RankedStorageAccount.getRank(RankedStorageAccount.java:86)
	at com.microsoft.azure.kusto.ingest.resources.RankedStorageAccountSet.getRankedShuffledAccounts(RankedStorageAccountSet.java:79)
	at com.microsoft.azure.kusto.ingest.ResourceManager.getShuffledContainers(ResourceManager.java:137)
	at com.microsoft.azure.kusto.ingest.ResourceAlgorithms.uploadStreamToBlobWithRetries(ResourceAlgorithms.java:85)
	at com.microsoft.azure.kusto.ingest.QueuedIngestClientImpl.ingestFromStreamImpl(QueuedIngestClientImpl.java:217)
	at com.microsoft.azure.kusto.ingest.IngestClientBase.lambda$ingestFromStream$3(IngestClientBase.java:139)
	at com.microsoft.azure.kusto.data.instrumentation.MonitoredActivity.invoke(MonitoredActivity.java:33)
	at com.microsoft.azure.kusto.data.instrumentation.MonitoredActivity.invoke(MonitoredActivity.java:26)
	at com.microsoft.azure.kusto.ingest.IngestClientBase.ingestFromStream(IngestClientBase.java:138)
```

**To Reproduce**
See above, not sure yet under what circumstances it can occur.

**Setup (please complete the following information):**
 - OS: mcr.microsoft.com/openjdk/jdk:21-distroless
 - Library/Libraries: com.microsoft.azure.kusto:kusto-ingest:5.0.4 
 - Java version: 21
 - App Server/Environment: Apache Tomcat/10.1.18
 - Frameworks: Spring Boot 3.2.2

**Comment by anuchandy** [comment]
Hello the-mod, I've moved this to the GitHub repro hosting "com.microsoft.azure.kusto:kusto-ingest". Closing this.
