### ISSUE TITLE
[BUG] Java SDK - Private DNS - Delete virtual link doesn't work

### ISSUE THREAD

**Issue by AlexanderAshitkin** [Azure/azure-sdk-for-java#39088]
**Describe the bug**
Bug in implementation - parameters mismatch.
`com.azure.resourcemanager.privatedns.implementation.VirtualNetworkLinksImpl#deleteByResourceGroupNameAsync` calls underlying `com.azure.resourcemanager.privatedns.fluent.VirtualNetworkLinksClient#deleteAsync` with mismatched parameters:
* virtual Network Link Name passed instead of `privateZoneName`
* `etagValue` passed instead of `virtualNetworkLinkName` 
![image](https://github.com/Azure/azure-sdk-for-java/assets/642345/f3ed0217-f858-4097-9dc1-f6e9850335d1)

***Exception or Stack Trace***
etag value appears in the URL instead of the expected VNL name
![image](https://github.com/Azure/azure-sdk-for-java/assets/642345/33bb718f-b9ae-41f3-baeb-2e2f6cdefd0d)
```
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:100)
		at reactor.core.publisher.Mono.block(Mono.java:1742)
		at com.azure.resourcemanager.privatedns.implementation.VirtualNetworkLinksImpl.deleteById(VirtualNetworkLinksImpl.java:56)
```

**To Reproduce**
Use Azure Java SDK to delete an existing virtual network link in a privatedns zone

***Code Snippet***
```java
                    privateDnsZone
                            .virtualNetworkLinks()
                            .deleteById(virtualNetworkLink.id(), virtualNetworkLink.etag());
```

**Expected behavior**
API works properly. The link is deleted.

**Screenshots**
See above

**Setup (please complete the following information):**
 - Java version: 17
 - Azure SDK: 2.31.0, 2.36.0 

**Additional context**
NA

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by XiaofeiCao** [comment]
@AlexanderAshitkin 

Thanks for reporting. This should be a delete implementation bug. Would you try following code to see if this works for you?
```java
privateDnsZone.update()
    .withoutVirtualNetworkLink(virtualNetworkLink.id(), virtualNetworkLink.etag())
    .apply();
```

**Comment by samvaity** [comment]
@AlexanderAshitkin Does this solve the problem, feel free to close the issue if applicable.
