### ISSUE TITLE
[QUERY] Deployment template parameter parsing failure

### ISSUE THREAD

**Issue by leventegebhardt** [Azure/azure-sdk-for-java#39318]
**Query/Question**
I'm trying to deploy a function app via an ARM template through Azure Java SDK.
The template contains parameters of type "string":
```
...
"parameters": {
    "functionAppName": {
      "type": "string",
      "defaultValue": "fnapp-def",
      "metadata": {
        "description": "Description of the parameter"
      }
    },
...
```

Related Java code snippet:
```
Map<String, String> parameters = new HashMap<>();
parameters.put("functionAppName", "fnapp-test1");

...

resourceManager
    .deployments()
    .define(functionAppName)
    .withExistingResourceGroup(resourceGroup)
    .withTemplateLink(templateFile.getPath(), "1.0.0")
    .withParameters(parameters)
    .withMode(DeploymentMode.INCREMENTAL)
    .beginCreate();
```

Following exception is thrown at runtime:
```
java.io.UncheckedIOException: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `com.azure.resourcemanager.resources.models.DeploymentParameter` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('fnapp-test1')
 at [Source: (String)"{"functionAppName":"fnapp-test1"}"; line: 1, column: 20] (through reference chain: java.util.LinkedHashMap["functionAppName"])

	at com.azure.resourcemanager.resources.implementation.DeploymentImpl.getParametersFromObject(DeploymentImpl.java:613)
	at com.azure.resourcemanager.resources.implementation.DeploymentImpl.withParameters(DeploymentImpl.java:308)
	at com.azure.resourcemanager.resources.implementation.DeploymentImpl.withParameters(DeploymentImpl.java:59)
	at AzureFunctionAppHandler.createFunctionApp(AzureFunctionAppHandler.java:136)
```

***Why is this not a Bug or a feature Request?***
It seems that the SDK expects the parameter in a different form. If not, then this might be a bug indeed.

**Setup (please complete the following information if applicable):**
 - OS: iOS
 - IDE: IntelliJ
 - Library/Libraries: azure-resourcemanager-appservice:2.36.1, azure-resourcemanager:2.36.0, azure-core:1.47.0
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by XiaofeiCao** [comment]
@leventegebhardt 
There seems to be another "value" layer for parameter value.

Would you try:
```java
Map<String, String> functionAppNameValue = new HashMap<>();
functionAppNameValue.put("value", "fnapp-test1");
parameters.put("functionAppName", functionAppNameValue );
```
