### ISSUE TITLE
Couldn't acquire access token from IMDS, verify your objectId, clientId or msiResourceId[BUG]

### ISSUE THREAD

**Issue by rohitprashar21** [Azure/azure-sdk-for-java#39368]
**Describe the bug**
Couldn't acquire access token from IMDS, verify your objectId, clientId or msiResourceId.
Im trying to retrieve an Azure access token using Managed Identity Credential in a Java application

***Exception or Stack Trace***
Caused by: java.lang.RuntimeException: Couldn't acquire access token from IMDS, verify your objectId, clientId or msiResourceId
    at com.azure.identity.implementation.IdentityClient.lambda$authenticateToIMDSEndpoint$36(IdentityClient.java:852)
    at reactor.core.publisher.MonoCallable.call(MonoCallable.java:91)
    at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:173)
    at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53)
    at reactor.core.publisher.Mono.subscribe(Mono.java:4198)
    at reactor.core.publisher.Mono.block(Mono.java:1679)
    at uk.gov.moj.cpp.staging.pubhub.event.service.AzureIdentityService.getTokenFromLocalClientSecretCredentials(AzureIdentityService.java:37)
    at uk.gov.moj.cpp.staging.pubhub.event.service.PublishingService.sendData(PublishingService.java:51)
    at uk.gov.moj.cpp.staging.pubhub.event.processor.PublishEventProcessor.lambda$publishSjpPressReportRequested$0(PublishEventProcessor.java:121)
    at uk.gov.moj.cpp.staging.pubhub.helper.RetryHelper.postWithRetry(RetryHelper.java:42)
    at uk.gov.moj.cpp.staging.pubhub.event.processor.PublishEventProcessor.publishSjpPressReportRequested(PublishEventProcessor.java:129)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at uk.gov.justice.services.core.handler.HandlerMethod.execute(HandlerMethod.java:122)
    at uk.gov.justice.services.core.dispatcher.MethodInvoker.invoke(MethodInvoker.java:44)
    at uk.gov.justice.services.core.dispatcher.Dispatcher.dispatch(Dispatcher.java:46)
    at uk.gov.justice.services.core.interceptor.DefaultInterceptorChainProcessor.lambda$targetOf$0(DefaultInterceptorChainProcessor.java:30)
    at uk.gov.justice.services.core.interceptor.DefaultInterceptorChain.processNext(DefaultInterceptorChain.java:22)
    at uk.gov.justice.services.core.featurecontrol.FeatureControlInterceptor.process(FeatureControlInterceptor.java:68)
    at uk.gov.justice.services.core.interceptor.DefaultInterceptorChain.processNext(DefaultInterceptorChain.java:25)
    at uk.gov.justice.services.metrics.interceptor.AbstractMetricsInterceptor.process(AbstractMetricsInterceptor.java:21)
    at uk.gov.justice.services.core.interceptor.DefaultInterceptorChain.processNext(DefaultInterceptorChain.java:25)
    at uk.gov.justice.services.metrics.interceptor.AbstractMetricsInterceptor.process(AbstractMetricsInterceptor.java:21)
    at uk.gov.justice.services.core.interceptor.DefaultInterceptorChain.processNext(DefaultInterceptorChain.java:25)
    at uk.gov.justice.services.core.interceptor.DefaultInterceptorChainProcessor.process(DefaultInterceptorChainProcessor.java:25)
    at uk.gov.justice.services.event.sourcing.subscription.manager.BackwardsCompatibleSubscriptionManager.process(BackwardsCompatibleSubscriptionManager.java:22)
    at uk.gov.justice.services.adapter.messaging.DefaultSubscriptionJmsProcessor.process(DefaultSubscriptionJmsProcessor.java:55)
    at uk.gov.justice.api.StagingpubhubEventProcessorStagingpubhubEventJmsListener.onMessage(StagingpubhubEventProcessorStagingpubhubEventJmsListener.java:48)
    at sun.reflect.GeneratedMethodAccessor131.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.jboss.as.ee.component.ManagedReferenceMethodInterceptor.processInvocation(ManagedReferenceMethodInterceptor.java:52)
    at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
    at org.jboss.invocation.InterceptorContext$Invocation.proceed(InterceptorContext.java:437)
    at org.jboss.as.weld.ejb.Jsr299BindingsInterceptor.delegateInterception(Jsr299BindingsInterceptor.java:70)
    at org.jboss.as.weld.ejb.Jsr299BindingsInterceptor.doMethodInterception(Jsr299BindingsInterceptor.java:80)
    at org.jboss.as.weld.ejb.Jsr299BindingsInterceptor.processInvocation(Jsr299BindingsInterceptor.java:93)
    at org.jboss.as.ee.component.interceptors.UserInterceptorFactory$1.processInvocation(UserInterceptorFactory.java:63)
    at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
    at org.jboss.invocation.InterceptorContext$Invocation.proceed(InterceptorContext.java:437)
    at uk.gov.justice.services.adapter.messaging.JsonSchemaValidationInterceptor.validate(JsonSchemaValidationInterceptor.java:56)
    at sun.reflect.GeneratedMethodAccessor136.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.jboss.as.ee.component.ManagedReferenceLifecycleMethodInterceptor.processInvocation(ManagedReferenceLifecycleMethodInterceptor.java:89)
    at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
    at org.jboss.invocation.InterceptorContext$Invocation.proceed(InterceptorContext.java:437)
    at uk.gov.justice.services.adapter.messaging.JmsLoggerMetadataAdder.addRequestDataToMdc(JmsLoggerMetadataAdder.java:65)
    at uk.gov.justice.api.StagingpubhubEventProcessorStagingpubhubEventJmsLoggerMetadataInterceptor.addRequestDataToMdc(StagingpubhubEventProcessorStagingpubhubEventJmsLoggerMetadataInterceptor.java:16)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.jboss.as.ee.component.ManagedReferenceLifecycleMethodInterceptor.processInvocation(ManagedReferenceLifecycleMethodInterceptor.java:89)
    at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
    at org.jboss.as.ejb3.component.invocationmetrics.ExecutionTimeInterceptor.processInvocation(ExecutionTimeInterceptor.java:43)
    at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
    at org.jboss.invocation.InterceptorContext$Invocation.proceed(InterceptorContext.java:437)
    at org.jboss.weld.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:73)
    at org.jboss.as.weld.ejb.EjbRequestScopeActivationInterceptor.processInvocation(EjbRequestScopeActivationInterceptor.java:83)
    at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
    at org.jboss.as.ee.concurrent.ConcurrentContextInterceptor.processInvocation(ConcurrentContextInterceptor.java:45)
    at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
    at org.jboss.invocation.InitialInterceptor.processInvocation(InitialInterceptor.java:21)
    at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
    at org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:61)
    at org.jboss.as.ee.component.interceptors.ComponentDispatcherInterceptor.processInvocation(ComponentDispatcherInterceptor.java:52)
    at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
    at org.jboss.as.ejb3.component.pool.PooledInstanceInterceptor.processInvocation(PooledInstanceInterceptor.java:51)
    at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
    at org.jboss.as.ejb3.tx.CMTTxInterceptor.invokeInCallerTx(CMTTxInterceptor.java:254)
    ... 51 more
    Suppressed: java.lang.Exception: #block terminated with an error
        at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
        at reactor.core.publisher.Mono.block(Mono.java:1680)
        ... 118 more
Caused by: java.io.IOException: Server returned HTTP response code: 400 for URL: http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fmanagement.azure.com&client_id=4f7a35be-d88f-47c2-89d2-6c0b2a7e64c3
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1894)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
    at com.azure.identity.implementation.IdentityClient.lambda$authenticateToIMDSEndpoint$36(IdentityClient.java:814)
    ... 123 more

**To Reproduce**

***Code Snippet***
` public String getTokenFromLocalClientSecretCredentials() {
        String azureLocalMiClientId = applicationParameters.getAzureLocalMiClientId();
        ManagedIdentityCredential managedIdentityCredential = new ManagedIdentityCredentialBuilder()
                .clientId(azureLocalMiClientId)
                .build();

        TokenRequestContext tokenRequestContext = new TokenRequestContext()
                .addScopes("https://management.core.windows.net/.default");

        final AccessToken accessToken = managedIdentityCredential.getToken(tokenRequestContext).block();
        return accessToken.getToken();
    }`

**Expected behavior**
Im unable to access token 

**Screenshots**

**Setup (please complete the following information):**
 - IDE: [e.g. IntelliJ]
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)]
 - Java version: [e.g. 8] 
 - App Server/Environment: [e.g. Tomcat, WildFly, Azure Function, Apache Spark, Databricks, IDE plugin or anything special]
 - Frameworks: [e.g. Spring Boot, Micronaut, Quarkus, etc] 

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**
The env variables set in my aks env
`AZURE_FEDERATED_TOKEN_FILE=/var/run/secrets/azure/tokens/azure-identity-token
AZURE_CLIENT_ID=775af43e-b544-484b-ba37-291c664b996d
AZURE_TENANT_ID=e2995d11-9947-4e78-9de6-d44e0603518e
AZURE_AUTHORITY_HOST=https://login.microsoftonline.com`

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by joshfree** [comment]
@g2vinay could you please assist @rohitprashar21 with their question

**Comment by g2vinay** [comment]
@rohitprashar21 

Use the WorkloadIdentityCredential to target WorkloadIdentity directly.
```java
TokenCredential workloadIdentityCredential = new WorkloadIdentityCredentialBuilder().build();
```

**Comment by g2vinay** [comment]
Let us know, if any help is still needed.
