### ISSUE TITLE
java.lang.StackOverflowError when trace is enabled

### ISSUE THREAD

**Issue by JJ-WM** [Azure/azure-sdk-for-java#39373]
**Describe the bug**
When setting clientTelemetryConfig.tracingOptions(true).  Application is getting java.lang.StackOverflowError when calling
container.createItem

***Exception or Stack Trace***
Diagnostics["diagnosticsContext"]->com.azure.cosmos.CosmosDiagnosticsContext["diagnostics"]->java.util.concurrent.ConcurrentLinkedDeque[0]->com.azure.cosmos.CosmosDiagnostics["diagnosticsContext"]->com.azure.cosmos.CosmosDiagnosticsContext["diagnostics"]->java.util.concurrent.ConcurrentLinkedDeque[0]->com.azure.cosmos.CosmosDiagnostics["diagnosticsContext"]->com.azure.cosmos.CosmosDiagnosticsContext["diagnostics"]->java.util.concurrent.ConcurrentLinkedDeque[0]->com.azure.cosmos.CosmosDiagnostics["diagnosticsContext"]->com.azure.cosmos.CosmosDiagnosticsContext["diagnostics"]->java.util.concurrent.ConcurrentLinkedDeque[0]->com.azure.cosmos.CosmosDiagnostics["diagnosticsContext"]->com.azure.cosmos.CosmosDiagnosticsContext["diagnostics"]->java.util.concurrent.ConcurrentLinkedDeque[0]->com.azure.cosmos.CosmosDiagnostics["diagnosticsContext"]->com.azure.cosmos.CosmosDiagnosticsContext["diagnostics"]->java.util.concurrent.ConcurrentLinkedDeque[0]->com.azure.cosmos.CosmosDiagnostics["diagnosticsContext"]->com.azure.cosmos.CosmosDiagnosticsContext["diagnostics"]->java.util.concurrent.ConcurrentLinkedDeque[0]->com.azure.cosmos.CosmosDiagnostics["diagnosticsContext"]->com.azure.cosmos.CosmosDiagnosticsContext["diagnostics"]->java.util.concurrent.ConcurrentLinkedDeque[0]->com.azure.cosmos.CosmosDiagnostics["diagnosticsContext"]->com.azure.cosmos.CosmosDiagnosticsContext["diagnostics"]->java.util.concurrent.ConcurrentLinkedDeque[0]->com.azure.cosmos.CosmosDiagnostics["diagnosticsContext"]->com.azure.cosmos.CosmosDiagnosticsContext["diagnostics"]->java.util.concurrent.ConcurrentLinkedDeque[0]->com.azure.cosmos.CosmosDiagnostics["diagnosticsContext"]->com.azure.cosmos.CosmosDiagnosticsContext["diagnostics"]->java.util.concurrent.ConcurrentLinkedDeque[0]->com.azure.cosmos.CosmosDiagnostics["diagnosticsContext"]->com.azure.cosmos.CosmosDiagnosticsContext["diagnostics"]->java.util.concurrent.ConcurrentLinkedDeque[0]->com.azure.cosmos.CosmosDiagnostics["diagnosticsContext"]->com.azure.cosmos.CosmosDiagnosticsContext["diagnostics"]->java.util.concurrent.ConcurrentLinkedDeque[0]->com.azure.cosmos.CosmosDiagnostics["diagnosticsContext"]->com.azure.cosmos.CosmosDiagnosticsContext["diagnostics"]->java.util.concurrent.ConcurrentLinkedDeque[0]->com.azure.cosmos.CosmosDiagnostics["diagnosticsContext"]->com.azure.cosmos.CosmosDiagnosticsContext["diagnostics"]->java.util.concurrent.ConcurrentLinkedDeque[0]->com.azure.cosmos.CosmosDiagnostics["diagnosticsContext"]->com.azure.cosmos.CosmosDiagnosticsContext["diagnostics"]->java.util.concurrent.ConcurrentLinkedDeque[0]->com.azure.cosmos.CosmosDiagnostics["diagnosticsContext"]->com.azure.cosmos.CosmosDiagnosticsContext["diagnostics"]->java.util.concurrent.ConcurrentLinkedDeque[0]->com.azure.cosmos.CosmosDiagnostics["diagnosticsContext"]->com.azure.cosmos.CosmosDiagnosticsContext["diagnostics"]->java.util.concurrent.ConcurrentLinkedDeque[0]->com.azure.cosmos.CosmosDiagnostics["diagnosticsContext"]->com.azure.cosmos.CosmosDiagnosticsContext["diagnostics"]->java.util.concurrent.ConcurrentLinkedDeque[0]->com.azure.cosmos.CosmosDiagnostics["diagnosticsContext"]->com.azure.cosmos.CosmosDiagnosticsContext["diagnostics"]->java.util.concurrent.ConcurrentLinkedDeque[0]->com.azure.cosmos.CosmosDiagnostics["diagnosticsContext"]->com.azure.cosmos.CosmosDiagnosticsContext["diagnostics"]->java.util.concurrent.ConcurrentLinkedDeque[0]->com.azure.cosmos.CosmosDiagnostics["diagnosticsContext"]->com.azure.cosmos.CosmosDiagnosticsContext["diagnostics"]->java.util.concurrent.ConcurrentLinkedDeque[0]->com.azure.cosmos.CosmosDiagnostics["diagnosticsContext"]->com.azure.cosmos.CosmosDiagnosticsContext["diagnostics"])] with root cause
java.lang.StackOverflowError: null
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:524)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:427)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:420)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at com.fasterxml.jackson.databind.JsonMappingException.prependPath(JsonMappingException.java:455)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:790)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serializeContentsUsing(CollectionSerializer.java:171)
	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serializeContents(CollectionSerializer.java:116)
	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serialize(CollectionSerializer.java:107)
	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serialize(CollectionSerializer.java:25)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:732)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:772)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:732)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:772)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serializeContentsUsing(CollectionSerializer.java:171)
	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serializeContents(CollectionSerializer.java:116)
	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serialize(CollectionSerializer.java:107)
	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serialize(CollectionSerializer.java:25)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:732)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:772)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:732)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:772)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serializeContentsUsing(CollectionSerializer.java:171)
	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serializeContents(CollectionSerializer.java:116)
	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serialize(CollectionSerializer.java:107)
	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serialize(CollectionSerializer.java:25)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:732)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:772)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:732)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:772)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serializeContentsUsing(CollectionSerializer.java:171)
	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serializeContents(CollectionSerializer.java:116)
	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serialize(CollectionSerializer.java:107)
	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serialize(CollectionSerializer.java:25)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:732)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:772)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:732)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:772)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serializeContentsUsing(CollectionSerializer.java:171)
**To Reproduce**
Initialize client with trace enabled. 

***Code Snippet***
The code below is causing the recursion call.  Once I commented out this.diagnostics.add(cosmosDiagnostics), I don't see the exception.
```
+++ b/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/CosmosDiagnosticsContext.java
@@ -304,7 +304,7 @@ public final class CosmosDiagnosticsContext {
             this.addRequestSize(diagAccessor.getRequestPayloadSizeInBytes(cosmosDiagnostics));
             this.addResponseSize(diagAccessor.getTotalResponsePayloadSizeInBytes(cosmosDiagnostics));
-            this.diagnostics.add(cosmosDiagnostics);
+            //this.diagnostics.add(cosmosDiagnostics);
             this.cachedRequestDiagnostics = null;
             this.requestInfo = null;
             cosmosDiagnostics.setDiagnosticsContext(this);
    }
```
**Screenshots**
N/A

**Setup (please complete the following information):**
 - IDE: [e.g. IntelliJ]
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)]
 - Java version: [e.g. 8] 
 - App Server/Environment: [e.g. Tomcat, WildFly, Azure Function, Apache Spark, Databricks, IDE plugin or anything special]
 - Frameworks: [e.g. Spring Boot, Micronaut, Quarkus, etc] 

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by FabianMeiswinkel** [comment]
We debugged this offline - the trigger for the StackOverflowException wasn't tracing but the fact that the returned an entity that had a field of CosmosDiagnostics - and Json serialization tried to serialize it. Neither CosmosDiagnostics nor CosmosDiagnosticsContext are serializable - and they aren't intended to be serializable. But both have a way to get a json representation (CosmosDiagnostics.toString, CosmosDiagnosticsContext.toJson). The reason why neither is Serializable is that we can't guarantee that deserialization would work across SDK versions. The APIs above can be used to get a string/json representation - but there is intentionally no way to do the vice versa - create a CosmosDiagnostics(Context) from json. Test app was fixed to ignore the diagnostics - and that addresses the error above.
