### ISSUE TITLE
[BUG] java.lang.NullPointerException: proxySelector == null while getting azure virtual networks

### ISSUE THREAD

**Issue by giridharkn** [Azure/azure-sdk-for-java#3939]
**Describe the bug**
A clear and concCaused by: java.lang.NullPointerException: proxySelector == null
	at okhttp3.Address.<init>(Address.java:77)
	at okhttp3.internal.http.HttpEngine.createAddress(HttpEngine.java:1036)
	at okhttp3.internal.http.HttpEngine.<init>(HttpEngine.java:180)
	at okhttp3.RealCall.getResponse(RealCall.java:232)
	at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:201)
	at com.microsoft.rest.retry.RetryHandler.intercept(RetryHandler.java:75)
	at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:190)
	at com.microsoft.rest.interceptors.CustomHeadersInterceptor.intercept(CustomHeadersInterceptor.java:140)
	at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:190)
	at com.microsoft.rest.interceptors.UserAgentInterceptor.intercept(UserAgentInterceptor.java:83)
	at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:190)
	at com.microsoft.azure.credentials.AzureTokenCredentialsInterceptor.intercept(AzureTokenCredentialsInterceptor.java:40)
	at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:190)
	at com.microsoft.azure.management.resources.fluentcore.utils.ResourceManagerThrottlingInterceptor.intercept(ResourceManagerThrottlingInterceptor.java:43)
	at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:190)
	at com.microsoft.azure.management.resources.fluentcore.utils.ProviderRegistrationInterceptor.intercept(ProviderRegistrationInterceptor.java:43)
	at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:190)
	at com.microsoft.rest.interceptors.BaseUrlHandler.intercept(BaseUrlHandler.java:43)
	at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:190)
	at com.microsoft.rest.interceptors.RequestIdHeaderInterceptor.intercept(RequestIdHeaderInterceptor.java:29)
	at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:190)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:163)
	at okhttp3.RealCall.execute(RealCall.java:57)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$RequestArbiter.request(RxJavaCallAdapterFactory.java:171)
	at rx.Subscriber.setProducer(Subscriber.java:211)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102)
	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:152)
	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:138)
	at rx.Observable.unsafeSubscribe(Observable.java:10142)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.subscribe(Observable.java:10238)
	at rx.Observable.subscribe(Observable.java:10205)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:444)
	at rx.observables.BlockingObservable.single(BlockingObservable.java:341)
	at com.microsoft.azure.management.network.implementation.VirtualNetworksInner.list(VirtualNetworksInner.java:611)ise description of what the bug is.

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - IDE : [e.g. IntelliJ]
 - Version of the Library used

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by giridharkn** [comment]
Exception is thrown at,
VirtualNetworksInner.list() call.

NetworkManagementClientImpl is configured with Proxy

**Comment by praries880** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by giridharkn** [comment]
I have found similar issue here this https://github.com/square/okhttp/issues/4232 which was seems to be fixed in okhttp library.
Can i know, which azure SDK utilizes this latest okhttp library ??
Or using this library in current SDK will work ??

**Comment by giridharkn** [comment]
https://github.com/square/okhttp/issues/4232

**Comment by jianghaolu** [comment]
@giridharkn We are using 3.11 version of OkHttp (https://github.com/Azure/autorest-clientruntime-for-java/blob/master/pom.xml#L67). I'll update it to 3.12 and test it.

**Comment by jianghaolu** [comment]
Just to give a follow up response, I'm looking into this now and should be able to verify the 3.14 release resolves this issue (or not) early next week.

In the mean time you could work around this issue by forcing the okhttp version in your pom to 3.14. Let me know if you need anything else.

**Comment by joshfree** [comment]
Also to note that the upgrade to 3.14 will ship in the next release of the SDK package.

**Comment by jianghaolu** [comment]
@giridharkn We just released the 1.24.1 version of the SDK containing the 3.12.2 version of the OkHttp dependency. I verified it locally that the proxy selector issue is fixed. You can find the SDK at https://search.maven.org/artifact/com.microsoft.azure/azure/1.24.1/jar. 

Please let us know and feel free to reopen the issue if you have any questions! We are excited to help you get unblocked!
