### ISSUE TITLE
[BUG] Service bus sender client: connection errors in logs

### ISSUE THREAD

**Issue by ViacheslavPetriaievEBT** [Azure/azure-sdk-for-java#39575]
**Describe the bug**
The sender client works, and messages are sent successfully to a service bus. But from time to time, there are several types of errors appear in the logs:

- com.azure.core.amqp.exception.AmqpException: Connection reset, errorContext[NAMESPACE: *****.servicebus.windows.net. ERROR CONTEXT: N/A]
- com.azure.core.amqp.exception.AmqpException: Connection timed out: getsockopt, errorContext[NAMESPACE: *****.servicebus.windows.net. ERROR CONTEXT: N/A]
- com.azure.core.amqp.exception.AmqpException: connection aborted, errorContext[NAMESPACE: *****.servicebus.windows.net. ERROR CONTEXT: N/A]

These errors have no influence on the messages sending process, all messages are sent successfully.

***Exception or Stack Trace***
```
reactor.core.Exceptions$ErrorCallbackNotImplemented: com.azure.core.amqp.exception.AmqpException: connection aborted, errorContext[NAMESPACE: ***********.servicebus.windows.net. ERROR CONTEXT: N/A]
Caused by: com.azure.core.amqp.exception.AmqpException: connection aborted, errorContext[NAMESPACE *********.servicebus.windows.net. ERROR CONTEXT: N/A]
at com.azure.core.amqp.implementation.ExceptionUtil.toException(ExceptionUtil.java:85)
at com.azure.core.amqp.implementation.handler.ConnectionHandler.notifyErrorContext(ConnectionHandler.java:362)
at com.azure.core.amqp.implementation.handler.ConnectionHandler.onTransportError(ConnectionHandler.java:259)
at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:191)
at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291)
at com.azure.core.amqp.implementation.ReactorExecutor.run(ReactorExecutor.java:91)
at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
```

**To Reproduce**

***Code Snippet***
```
spring:
  cloud:
    azure:
      servicebus:
        namespace: ${service-bus-namespace}
        producer:
          entity-name: ${service-bus-queue-name}
          entity-type: QUEUE

ServiceBusSenderClient client; - injected client
client.sendMessage(message);
```

**Setup (please complete the following information):**
 - OS: Windows
 - Library: com.azure.spring:spring-cloud-azure-starter-servicebus:5.10.0
 - Java version: 21
 - App Server/Environment: Azure Function, standalone app running
 - Frameworks: Spring Boot

**Comment by lmolkova** [comment]
@ViacheslavPetriaievEBT  transient network issues are expected and based on your description are retried and don't result in visible impact.  
Is the ask here to reduce the severity to warning?

Would you expect error severity if ServiceBus SDK hits unrecoverable issue (either retries are exhausted or issue is not transient)?

**Comment by ViacheslavPetriaievEBT** [comment]
@lmolkova 
Yes, that's correct:
- warning - for recoverable issues
- error - for unrecoverable issues

**Comment by lmolkova** [comment]
@ViacheslavPetriaievEBT thank you for the confirmation!
Do you have an examples of the messages coming from ServiceBus SDK and logger/class name?

I'm trying to change levels in the #39904, but the stack trace and error messages describe the exception, but not the place where it's logged. Having a specific messages/logger names would really help to apply fixes in the places which affect your application.

Thanks!

**Comment by ViacheslavPetriaievEBT** [comment]
@lmolkova 
I've found only the following information:
- Logger Message: Operator called default onErrorDropped
- LoggerName: reactor.core.publisher.Operators
- SourceType: Logger
