### ISSUE TITLE
[QUERY] Caused by: com.azure.core.amqp.exception.AmqpException: errorContext[NAMESPACE: test-eh.servicebus.windows.net.servicebus.windows.net. ERROR CONTEXT: N/A]

### ISSUE THREAD

**Issue by satbad** [Azure/azure-sdk-for-java#39644]
**Query/Question**
A clear and concise ask/query.
 When we use latest Spring cloud azure sdk with spring boot 3.2.3 we are getting below error.
Caused by: com.azure.core.amqp.exception.AmqpException: errorContext[NAMESPACE: test-eh.servicebus.windows.net.servicebus.windows.net. ERROR CONTEXT: N/A]

references used : https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-cloud-stream-binder-java-app-azure-event-hub
https://learn.microsoft.com/en-us/azure/developer/java/sdk/troubleshooting-dependency-version-conflict 
https://github.com/Azure/azure-sdk-for-java/wiki/Spring-Versions-Mapping#which-version-of-spring-cloud-azure-should-i-use
***Why is this not a Bug or a feature Request?***
A clear explanation of why is this not a bug or a feature request?
tried to create a bug and it redirected me to SDK 
Detailed error log
```
2024-04-10T01:24:31.730-05:00  INFO 52119 --- [ctor-executor-1] c.a.m.e.i.EventHubConnectionProcessor    : {"az.sdk.message":"Transient error occurred. Retrying.","exception":"errorContext[NAMESPACE: test-eh.servicebus.windows.net.servicebus.windows.net. ERROR CONTEXT: N/A]","entityPath":"test-dev-eh-topic","tryCount":0,"intervalMs":1800}
2024-04-10T01:24:31.735-05:00  INFO 52119 --- [ctor-executor-1] c.a.c.a.i.ReactorConnection              : {"az.sdk.message":"onConnectionShutdown. Shutting down.","connectionId":"MF_55fbf1_1712730267348","isTransient":false,"isInitiatedByClient":false,"shutdownMessage":"Finished processing pending tasks.","namespace":"test-eh.servicebus.windows.net.servicebus.windows.net"}
2024-04-10T01:24:33.535-05:00  INFO 52119 --- [     parallel-9] c.a.m.e.i.EventHubConnectionProcessor    : {"az.sdk.message":"Requesting from upstream.","entityPath":"test-dev-eh-topic","tryCount":0}
2024-04-10T01:24:33.536-05:00  INFO 52119 --- [     parallel-9] c.a.m.e.i.EventHubConnectionProcessor    : {"az.sdk.message":"Connection not requested, yet. Requesting one.","entityPath":"test-dev-eh-topic"}
2024-04-10T01:24:33.536-05:00  INFO 52119 --- [     parallel-9] c.a.m.eventhubs.EventHubClientBuilder    : {"az.sdk.message":"Emitting a single connection.","connectionId":"MF_f9dfee_1712730273536"}
2024-04-10T01:24:33.536-05:00  INFO 52119 --- [     parallel-9] c.a.m.e.i.EventHubConnectionProcessor    : {"az.sdk.message":"Setting next AMQP channel.","entityPath":"test-dev-eh-topic"}
2024-04-10T01:24:33.880-05:00  INFO 52119 --- [ctor-executor-2] c.a.c.a.implementation.ReactorExecutor   : {"az.sdk.message":"Processing all pending tasks and closing old reactor.","connectionId":"MF_b8ebc2_1712730267302"}
2024-04-10T01:24:33.880-05:00  INFO 52119 --- [ctor-executor-2] c.a.c.a.i.ReactorDispatcher              : {"az.sdk.message":"Reactor selectable is being disposed.","connectionId":"MF_b8ebc2_1712730267302"}
2024-04-10T01:24:33.881-05:00  INFO 52119 --- [ctor-executor-2] c.a.c.a.i.ReactorConnection              : {"az.sdk.message":"onConnectionShutdown. Shutting down.","connectionId":"MF_b8ebc2_1712730267302","isTransient":false,"isInitiatedByClient":false,"shutdownMessage":"connectionId[MF_b8ebc2_1712730267302] Reactor selectable is disposed.","namespace":"test-eh.servicebus.windows.net.servicebus.windows.net"}
2024-04-10T01:24:33.882-05:00 ERROR 52119 --- [ctor-executor-2] reactor.core.publisher.Operators         : Operator called default onErrorDropped

reactor.core.Exceptions$ErrorCallbackNotImplemented: com.azure.core.amqp.exception.AmqpException: errorContext[NAMESPACE: test-eh.servicebus.windows.net.servicebus.windows.net. ERROR CONTEXT: N/A]
Caused by: com.azure.core.amqp.exception.AmqpException: errorContext[NAMESPACE: test-eh.servicebus.windows.net.servicebus.windows.net. ERROR CONTEXT: N/A]
	at com.azure.core.amqp.implementation.ExceptionUtil.toException(ExceptionUtil.java:85) ~[azure-core-amqp-2.9.1.jar:2.9.1]
	at com.azure.core.amqp.implementation.handler.ConnectionHandler.notifyErrorContext(ConnectionHandler.java:362) ~[azure-core-amqp-2.9.1.jar:2.9.1]
	at com.azure.core.amqp.implementation.handler.ConnectionHandler.onTransportError(ConnectionHandler.java:259) ~[azure-core-amqp-2.9.1.jar:2.9.1]
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:191) ~[proton-j-0.33.8.jar:na]
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108) ~[proton-j-0.33.8.jar:na]
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324) ~[proton-j-0.33.8.jar:na]
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291) ~[proton-j-0.33.8.jar:na]
	at com.azure.core.amqp.implementation.ReactorExecutor.run(ReactorExecutor.java:91) ~[azure-core-amqp-2.9.1.jar:2.9.1]
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68) ~[reactor-core-3.6.3.jar:3.6.3]
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28) ~[reactor-core-3.6.3.jar:3.6.3]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2024-04-10T01:24:33.883-05:00  INFO 52119 --- [ctor-executor-2] c.a.m.e.i.EventHubConnectionProcessor    : {"az.sdk.message":"Transient error occurred. Retrying.","exception":"errorContext[NAMESPACE: test-eh.servicebus.windows.net.servicebus.windows.net. ERROR CONTEXT: N/A]","entityPath":"consume-in-0","tryCount":0,"intervalMs":1800}
2024-04-10T01:24:33.884-05:00  INFO 52119 --- [ctor-executor-2] c.a.c.a.i.ReactorConnection              : {"az.sdk.message":"onConnectionShutdown. Shutting down.","connectionId":"MF_b8ebc2_1712730267302","isTransient":false,"isInitiatedByCl
```

**Setup (please complete the following information if applicable):**
 - OS: [e.g. iOS] Mac m1
 - IDE: [e.g. IntelliJ] Intellij java temurin :17- jdk
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)] 1.47.0
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ x] Query Added
- [x ] Setup information Added

**Comment by anuchandy** [comment]
Hello @satbad, could you push a minimal executable repro Spring project to GitHub and share the link here? Normally, the underlying Event Hubs SDK behind the Event Hubs Spring binder should recover transparently.

Tagging Spring team (\\cc @Netyyyy) to review the repro code when available.

**Comment by anuchandy** [comment]
Closing this provided there is no activity to continue the investigation. Please feel free to reply with requested info if assistance is needed at a later point.
