### ISSUE TITLE
[BUG] DeviceUpdateClient API listUpdates() does not catch 403 Http response

### ISSUE THREAD

**Issue by ranjith-t** [Azure/azure-sdk-for-java#39673]
**Describe the bug**
DeviceUpdateClient API listUpdates() does not catch 403 Http response when received.  The http response is returned as the API response instead of an exception. It is expected that the exception is thrown when a error response is received from the server(service).

***Exception or Stack Trace***
response received:
{"az.sdk.message":"HTTP response","contentLength":"327","statusCode":403,"url":"https://xxxxx.microsoft.com/deviceUpdate/yyyyy/updates?api-version=2022-10-01","durationMs":13,"body":"{\"error\":{\"code\":\"someerror\",\"message\":\"some error message related to network access permission. ....................... "}}"}

**To Reproduce**
call the API listUpdates() with server sending 403 error

**Expected behavior**
It is expected that an exception is thrown in case of an error response from the server.

**Setup (please complete the following information):**
 - Library/Libraries:com.azure: azure-iot-deviceupdate:1.0.4
 - Java version: [8] 
 - App Server/Environment: App Service
 - Frameworks: Ktor

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X ] Bug Description Added
- [X ] Repro Steps Added
- [X ] Setup information Added

**Comment by joshfree** [comment]
@mario-guerra could you please assist in routing this to the service team?

**Comment by mario-guerra** [comment]
@joshfree, @ronniegeraghty is the PM for IoT, reassigning accordingly.

**Comment by srnagar** [comment]
@ranjith-t Could you please provide a code sample to repro this issue? I tried this with the latest version of `azure-iot-deviceupdate` (1.0.18) and the request failed with an exception, as expected, when the status code was 403. Also, I noticed that the version used is 1.0.4. Can you please try upgrading to 1.0.18 and check if this issue still exists?


```java
 DeviceUpdateClient client = new DeviceUpdateClientBuilder()
      .endpoint(Configuration.getGlobalConfiguration().get("AZURE_ACCOUNT_ENDPOINT"))
      .instanceId(Configuration.getGlobalConfiguration().get("AZURE_INSTANCE_ID"))
      .credential(new DefaultAzureCredentialBuilder().build())
      .httpLogOptions(new HttpLogOptions().setLogLevel(HttpLogDetailLevel.BASIC))
      .buildClient();
  PagedIterable<BinaryData> binaryData = client.listUpdates(new RequestOptions());
  binaryData.stream().forEach(binaryData1 -> System.out.println(binaryData1.toString()));
```

Here's the response log:

```
[main] INFO com.azure.iot.deviceupdate.implementation.DeviceUpdatesImpl$DeviceUpdatesService.listUpdatesSync - {"az.sdk.message":"HTTP response","statusCode":403,"url":"https://<redacted>/deviceUpdate/<redacted>/updates?api-version=2022-10-01","durationMs":980,"content-length":0,"content-length":0}


Exception in thread "main" com.azure.core.exception.HttpResponseException: Status code 403, (empty body)
	at com.azure.core.implementation.http.rest.RestProxyBase.instantiateUnexpectedException(RestProxyBase.java:389)
	at com.azure.core.implementation.http.rest.SyncRestProxy.ensureExpectedStatus(SyncRestProxy.java:128)
	at com.azure.core.implementation.http.rest.SyncRestProxy.handleRestReturnType(SyncRestProxy.java:210)
	at com.azure.core.implementation.http.rest.SyncRestProxy.invoke(SyncRestProxy.java:86)
	at com.azure.core.implementation.http.rest.RestProxyBase.invoke(RestProxyBase.java:125)
	at com.azure.core.http.rest.RestProxy.invoke(RestProxy.java:97)
	at jdk.proxy2/jdk.proxy2.$Proxy3.listUpdatesSync(Unknown Source)
	at com.azure.iot.deviceupdate.implementation.DeviceUpdatesImpl.listUpdatesSinglePage(DeviceUpdatesImpl.java:1014)
	at com.azure.iot.deviceupdate.implementation.DeviceUpdatesImpl.lambda$listUpdates$4(DeviceUpdatesImpl.java:1104)
	at com.azure.core.http.rest.PagedIterable.lambda$new$1(PagedIterable.java:166)
	at com.azure.core.util.paging.ContinuablePagedByIteratorBase.requestPage(ContinuablePagedByIteratorBase.java:104)
	at com.azure.core.util.paging.ContinuablePagedByItemIterable$ContinuablePagedByItemIterator.<init>(ContinuablePagedByItemIterable.java:83)
	at com.azure.core.util.paging.ContinuablePagedByItemIterable.iterator(ContinuablePagedByItemIterable.java:58)
	at java.base/java.lang.Iterable.spliterator(Iterable.java:101)
	at com.azure.core.util.paging.ContinuablePagedIterable.stream(ContinuablePagedIterable.java:85)
	at com.azure.iot.deviceupdate.ListUpdatesSample.main(ListUpdatesSample.java:31)

```

Upgrade to this version:
```xml
<!-- https://mvnrepository.com/artifact/com.azure/azure-iot-deviceupdate -->
<dependency>
    <groupId>com.azure</groupId>
    <artifactId>azure-iot-deviceupdate</artifactId>
    <version>1.0.18</version>
</dependency>

```
