### ISSUE TITLE
[BUG] Fix GraalVM issue with Application Insights for Spring native

### ISSUE THREAD

**Issue by jeanbisutti** [Azure/azure-sdk-for-java#39699]
Reproducer: https://github.com/Azure-Samples/java-native-telemetry

Version:

```
<dependency>
    <groupId>com.azure.spring</groupId>
    <artifactId>spring-cloud-azure-starter-monitor</artifactId>
    <version>1.0.0-beta.5</version>
</dependency>

```
` --initialize-at-build-time=com.azure.core.util.logging.ClientLogger ` has to be added for GraalVM native compilation

**Comment by jeanbisutti** [comment]
The error with class initialization message:
```
com.oracle.svm.core.util.UserError$UserException: Classes that should be initialized at run time got initialized during image building:
 com.azure.core.util.logging.ClientLogger was unintentionally initialized at build time. com.azure.core.util.Configuration caused initialization of this class with the following trace:
        at com.azure.core.util.logging.ClientLogger.<clinit>(ClientLogger.java:61)
        at com.azure.core.util.Configuration.<clinit>(Configuration.java:258)
```
com.azure.core.util.Configuration is initialized at build time: https://github.com/Azure/azure-sdk-for-java/blob/33b5a31328e84f3177293a3906bc829f696ab059/sdk/core/azure-core/src/main/resources/META-INF/native-image/com.azure/azure-core/native-image.properties#L21

`ClientLogger` is then initialized by this static field: https://github.com/Azure/azure-sdk-for-java/blob/33b5a31328e84f3177293a3906bc829f696ab059/sdk/core/azure-core/src/main/java/com/azure/core/util/Configuration.java#L258
