### ISSUE TITLE
[BUG] List Responses Fail to Deserialize

### ISSUE THREAD

**Issue by original-brownbear** [Azure/azure-sdk-for-java#3999]
**Describe the bug**

Using the latest blob storage SDK v11.0.1 listing requests (flat and hierarchical) fail to deserialize because the response starts on a unicode BOM ('\uFEFF' 65279) which the JDK XML logic can't handle out of the box and interprets as illegal content before the XML.

***Exception or Stack Trace***

Failure stack trace is:

```
com.microsoft.rest.v2.RestException: HTTP response has a malformed body
	at com.microsoft.rest.v2.protocol.HttpResponseDecoder$2.apply(HttpResponseDecoder.java:124) ~[client-runtime-2.1.1.jar:?]
	at com.microsoft.rest.v2.protocol.HttpResponseDecoder$2.apply(HttpResponseDecoder.java:115) ~[client-runtime-2.1.1.jar:?]
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:57) ~[rxjava-2.2.8.jar:?]
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64) ~[rxjava-2.2.8.jar:?]
	at io.reactivex.internal.operators.single.SingleCache.onSuccess(SingleCache.java:134) ~[rxjava-2.2.8.jar:?]
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64) ~[rxjava-2.2.8.jar:?]
	at io.reactivex.internal.operators.flowable.FlowableCollectSingle$CollectSubscriber.onComplete(FlowableCollectSingle.java:119) ~[rxjava-2.2.8.jar:?]
	at com.microsoft.rest.v2.http.NettyClient$ResponseContentFlowable.emitContent(NettyClient.java:822) ~[client-runtime-2.1.1.jar:?]
	at com.microsoft.rest.v2.http.NettyClient$ResponseContentFlowable.drain(NettyClient.java:782) ~[client-runtime-2.1.1.jar:?]
	at com.microsoft.rest.v2.http.NettyClient$ResponseContentFlowable.onReceivedContent(NettyClient.java:705) ~[client-runtime-2.1.1.jar:?]
	at com.microsoft.rest.v2.http.NettyClient$HttpClientInboundHandler.channelRead(NettyClient.java:930) ~[client-runtime-2.1.1.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) ~[netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438) ~[netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) ~[netty-codec-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297) ~[netty-codec-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253) ~[netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) ~[netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1478) ~[netty-handler-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1227) ~[netty-handler-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1274) ~[netty-handler-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502) ~[netty-codec-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441) ~[netty-codec-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) ~[netty-codec-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) ~[netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408) ~[netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930) ~[netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:682) ~[netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:617) ~[netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:534) ~[netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) ~[netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906) ~[netty-common-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.36.Final.jar:4.1.36.Final]
	at java.lang.Thread.run(Thread.java:835) [?:?]
Caused by: com.fasterxml.jackson.core.JsonParseException: ParseError at [row,col]:[1,1]
Message: Content is not allowed in prolog.
	at com.fasterxml.jackson.dataformat.xml.util.StaxUtil.throwAsParseException(StaxUtil.java:37) ~[jackson-dataformat-xml-2.9.6.jar:2.9.6]
	at com.fasterxml.jackson.dataformat.xml.XmlFactory._initializeXmlReader(XmlFactory.java:657) ~[jackson-dataformat-xml-2.9.6.jar:2.9.6]
	at com.fasterxml.jackson.dataformat.xml.XmlFactory._createParser(XmlFactory.java:554) ~[jackson-dataformat-xml-2.9.6.jar:2.9.6]
	at com.fasterxml.jackson.dataformat.xml.XmlFactory.createParser(XmlFactory.java:433) ~[jackson-dataformat-xml-2.9.6.jar:2.9.6]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3042) ~[jackson-databind-2.9.6.jar:2.9.6]
	at com.microsoft.rest.v2.serializer.JacksonAdapter.deserialize(JacksonAdapter.java:131) ~[client-runtime-2.1.1.jar:?]
	at com.microsoft.rest.v2.protocol.HttpResponseDecoder.deserializeBody(HttpResponseDecoder.java:139) ~[client-runtime-2.1.1.jar:?]
	at com.microsoft.rest.v2.protocol.HttpResponseDecoder.access$100(HttpResponseDecoder.java:42) ~[client-runtime-2.1.1.jar:?]
	at com.microsoft.rest.v2.protocol.HttpResponseDecoder$2.apply(HttpResponseDecoder.java:119) ~[client-runtime-2.1.1.jar:?]
	... 42 more
Caused by: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,1]
Message: Content is not allowed in prolog.
	at com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.next(XMLStreamReaderImpl.java:652) ~[?:?]
	at com.fasterxml.jackson.dataformat.xml.XmlFactory._initializeXmlReader(XmlFactory.java:653) ~[jackson-dataformat-xml-2.9.6.jar:2.9.6]
	at com.fasterxml.jackson.dataformat.xml.XmlFactory._createParser(XmlFactory.java:554) ~[jackson-dataformat-xml-2.9.6.jar:2.9.6]
	at com.fasterxml.jackson.dataformat.xml.XmlFactory.createParser(XmlFactory.java:433) ~[jackson-dataformat-xml-2.9.6.jar:2.9.6]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3042) ~[jackson-databind-2.9.6.jar:2.9.6]
	at com.microsoft.rest.v2.serializer.JacksonAdapter.deserialize(JacksonAdapter.java:131) ~[client-runtime-2.1.1.jar:?]
	at com.microsoft.rest.v2.protocol.HttpResponseDecoder.deserializeBody(HttpResponseDecoder.java:139) ~[client-runtime-2.1.1.jar:?]
	at com.microsoft.rest.v2.protocol.HttpResponseDecoder.access$100(HttpResponseDecoder.java:42) ~[client-runtime-2.1.1.jar:?]
	at com.microsoft.rest.v2.protocol.HttpResponseDecoder$2.apply(HttpResponseDecoder.java:119) ~[client-runtime-2.1.1.jar:?]
	... 42 more
```

**To Reproduce**

This happens on any run of 

```java
client.createContainerURL(container)listBlobsHierarchySegment(
```

 no matter the arguments I use. The response returned otherwise is perfectly valid. I'm setting up the client just using default 

```
new PipelineOptions()
```

and am not adding any other customization to the client.
It looks to me like likely the person reporting this issue https://social.technet.microsoft.com/Forums/lync/en-US/70fb2362-dc4e-491e-a3de-3cb0c8690b5e/empty-body-200-response-when-listing-blobs?forum=windowsazuredata ran into the same thing.

Here's a screenshot of debugging this. Whatever hits `com.microsoft.rest.v2.serializer.JacksonAdapter#deserialize(java.lang.String, java.lang.reflect.Type, com.microsoft.rest.v2.protocol.SerializerEncoding)` already contains the unicode bom.

<img width="1236" alt="Screenshot 2019-06-19 at 13 42 31" src="https://user-images.githubusercontent.com/6490959/59762708-28e08d80-9298-11e9-9a78-28c53a1c1fcc.png">

**Setup (please complete the following information):**

* Tested on Ubuntu Linux Kernel 5 as well as OSX

**Comment by praries880** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by rickle-msft** [comment]
@original-brownbear Thank you for reporting this issue. Could I request a bit more information from you? Could you please try making a listContainers call and a getBlockList call on a block blob? These also return xml responses, and it will help us determine if there is something wrong with the xml parsing in general or if it's specific to this api. I also notice that you're testing on Linux and OSX, whereas we typically test on Windows. Do you happen to have a Windows environment where you can test? I would be quite confused if the platform affected java code, but just as a sanity check.

**Comment by original-brownbear** [comment]
@rickle-msft I tried the other two requests and ran into the same issue.

Unfortunately I don't have a Windows environment set up right now, but I think there is a good chance we have a platform effect here. The problem is that the UTF8 BOM isn't stripped by the JVM's UTF-8 encoding that the SDK v11 uses when converting the bytes received over the wire in `com.microsoft.rest.v2.http.BufferedHttpResponse#bodyAsString` to a `String` before passing it on to Jackson for XML decoding. Jackson then takes these bytes and passes them as is to the JDKs XML code that might act in a system specific way here since we create the XML parser without specifying an encoding.

I think the ideal fix would be to simply adjust the code in `com.microsoft.rest.v2.http.BufferedHttpResponse#bodyAsString` to account for https://bugs.java.com/bugdatabase/view_bug.do?bug_id=4508058 and strip the BOM.

I'm happy to open a PR for that :)

**Comment by rickle-msft** [comment]
@original-brownbear Thanks for looking into that! @jianghaolu actually owns the restv2 SDK, so I will let him comment on whether they will accept PRs or if he will prefer to fix it.

**Comment by jianghaolu** [comment]
@original-brownbear thanks for reporting this!

**Question:** Are you running into this issue only with this container, or all other containers? In other words, is this caused by some special structure or state of the container?

**Answer to your issue (and Rick's invite):** The equivalent of this piece of code is located at https://github.com/Azure/azure-sdk-for-java/blob/master/core/azure-core/src/main/java/com/azure/core/implementation/http/BufferedHttpResponse.java#L61 now for our next version of the client. We always welcome pull requests if it's convenient for you. Otherwise we will prioritize after this sprint and update here when we pick up this item.

For this version - it's in the https://github.com/Azure/autorest-clientruntime-for-java repo (we are unifying everything in this repo now, but sadly not for this version of runtime). When we fix this in the new version - we will back port the fix there too.

**Comment by zhusijia26** [comment]
Close this issue since answer provided. Please reopen is there is still question.

**Comment by russcam** [comment]
Its not clear to me why this issue has been closed, as there's some questions that don't appear to be answered which others might also have, coming across this issue, such as

1. Is this acknowledged to be a bug that can be reproduced?
2. If a bug, is there a target release/version in which this would be fixed
3. If a bug, is an issue that raises it typically closed _before_ a PR is submitted, reviewed and merged, that fixes it

Appreciate any clarity you can provide, as it will help set expectations.

**Comment by zhusijia26** [comment]
@russcam Sorry I closed the issue due to the idle time and comment from @jianghaolu. Reopne the issue, @jianghaolu Could you please address the question above?

**Comment by zhusijia26** [comment]
Remove Storage label since it is handled by different team now.

**Comment by rickle-msft** [comment]
@russcam Acknowledging the issue is still open, but I also want to give you a bit more context.

Storage is currently recommending customers move off of v11 and either stay on v8 (which is still supported and developed) or else start working with v12-preview (which is our priority moving forward). There are some stability issues in the core of v11 that are not present in v8 or v12. This issue will remain open to ensure it is not a problem in v12, but it is unlikely that this fix will be applied to v11 unless it becomes a security issue

**Comment by russcam** [comment]
No worries, @zhusijia26, just wanted to better understand the best path forward 😄  

Thank you for the context, @rickle-msft, it's really helpful. It sounds like we should consider targeting v12 over v11, once it comes out of preview, and in the meantime, stick with v8.

**Comment by rickle-msft** [comment]
Yes, that is the ideal strategy. We doing monthly preview releases of v12 until it's ready. We have one coming out today and then are targeting one or two more previews before GA (though of course are highest priority is ensuring it is strictly the best version yet before we GA)

**Comment by rickle-msft** [comment]
@original-brownbear or @russcam would one of you be willing to give this a try in v12?

**Comment by amishra-dev** [comment]
@original-brownbear please reactivate if you hit this on V12
