### ISSUE TITLE
Re-enable failing KeyVault (Secrets and Keys) tests

### ISSUE THREAD

**Issue by conniey** [Azure/azure-sdk-for-java#4013]
Tests using `KeyClientTestBase` and `SecretClientTestBase` are failing to run. It appears they make a real call to ADAL when getting an authentication result for playback mode. It may be an issue with the tests when in Playback Mode, it appears the audience is incorrectly set when creating the AuthenticationContext.

Part of the error stack looks like:
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
java.lang.IllegalArgumentException: 'authority' Uri should have at least one segment in the path (i.e. https://<host>/<path>/...)
	at com.microsoft.aad.adal4j.AuthenticationAuthority.detectAuthorityType(AuthenticationAuthority.java:204)
	at com.microsoft.aad.adal4j.AuthenticationAuthority.<init>(AuthenticationAuthority.java:81)
	at com.microsoft.aad.adal4j.AuthenticationContext.<init>(AuthenticationContext.java:125)
	at com.azure.keyvault.SecretClientTestBase.getAccessToken(SecretClientTestBase.java:107)
	at com.azure.keyvault.SecretClientTestBase.access$000(SecretClientTestBase.java:42)
	at com.azure.keyvault.SecretClientTestBase$1.getToken(SecretClientTestBase.java:86)
	at com.azure.core.http.policy.BearerTokenAuthenticationPolicy.lambda$new$0(BearerTokenAuthenticationPolicy.java:49)
```

**Comment by conniey** [comment]
This is also fixed in #4008
