### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by yvespp** [Azure/azure-sdk-for-java#40427]
**Describe the bug**
Since the update of azure-resourcemanager-resources to 2.39.0 and azure-resourcemanager-authorization to 2.39.0 in our project , we are getting the following exception:
```
2024-05-29T13:36:56.488122596+02:00 | WARN | throwIfFatal detected a jvm fatal exception, which is thrown and logged below: | : java.lang.NoSuchFieldError: Class com.azure.core.management.AzureEnvironment$Endpoint does not have member field 'com.azure.core.management.AzureEnvironment$Endpoint STORAGE'
       at com.azure.resourcemanager.resources.fluentcore.utils.ResourceManagerUtils.getDefaultScopeFromUrl(ResourceManagerUtils.java:191)
       at com.azure.resourcemanager.resources.fluentcore.utils.ResourceManagerUtils.getDefaultScopeFromRequest(ResourceManagerUtils.java:149)
       at com.azure.resourcemanager.resources.fluentcore.policy.AuthenticationPolicy.getScopes(AuthenticationPolicy.java:36)
       at com.azure.core.management.http.policy.ArmChallengeAuthenticationPolicy.lambda$authorizeRequest$0(ArmChallengeAuthenticationPolicy.java:54)
       at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:45)
       at reactor.core.publisher.Mono.subscribe(Mono.java:4490)
       at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:263)
       at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51)
       at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
       at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53)
       at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
       at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53)
       at reactor.core.publisher.Mono.subscribe(Mono.java:4490)
       at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:203)
       at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53)
       at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
       at reactor.core.publisher.MonoDeferContextual.subscribe(MonoDeferContextual.java:55)
       at reactor.core.publisher.Flux.subscribe(Flux.java:8642)
       at reactor.core.publisher.Flux.blockLast(Flux.java:2760)
       at com.azure.core.util.paging.ContinuablePagedByIteratorBase.requestPage(ContinuablePagedByIteratorBase.java:102)
       at com.azure.core.util.paging.ContinuablePagedByItemIterable$ContinuablePagedByItemIterator.<init>(ContinuablePagedByItemIterable.java:75)
       at com.azure.core.util.paging.ContinuablePagedByItemIterable.iterator(ContinuablePagedByItemIterable.java:55)
       at java.base/java.lang.Iterable.spliterator(Iterable.java:101)
       at com.azure.core.util.paging.ContinuablePagedIterable.stream(ContinuablePagedIterable.java:85)
       at com.azure.resourcemanager.resources.fluentcore.utils.PagedConverter$PagedIterableImpl.stream(PagedConverter.java:200)
       at my.app.directory.DirectoryReader.updateUsers(DirectoryReader.java:195)
       at my.app.directory.DirectoryReader_ClientProxy.updateUsers(Unknown Source)
       at my.app.directory.DirectoryReader_ScheduledInvoker_updateUsers_fa922a3d5993a039372a4e6b393ec8711b9c46e0.invokeBean(Unknown Source)
       at io.quarkus.scheduler.common.runtime.DefaultInvoker.invoke(DefaultInvoker.java:24)
       at io.quarkus.scheduler.common.runtime.StatusEmitterInvoker.invoke(StatusEmitterInvoker.java:35)
       at io.quarkus.scheduler.runtime.SimpleScheduler$ScheduledTask.doInvoke(SimpleScheduler.java:443)
       at io.quarkus.scheduler.runtime.SimpleScheduler$ScheduledTask$2.call(SimpleScheduler.java:425)
       at io.quarkus.scheduler.runtime.SimpleScheduler$ScheduledTask$2.call(SimpleScheduler.java:422)
       at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$0(ContextImpl.java:178)
       at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:279)
       at io.vertx.core.impl.ContextImpl.lambda$internalExecuteBlocking$2(ContextImpl.java:210)
       at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:604)
       at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
       at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
       at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
       at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
       at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
       at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
       at java.base/java.lang.Thread.run(Thread.java:1583)
```
The reason for this is that azure-core-management 1.12.0 is being used, which does not yet have the `Endpoint` field. 1.14.0 works and is also a direct dependency of of azure-resourcemanager-resources:
```
mvn dependency:tree -Dverbose
...
[INFO] +- com.azure.resourcemanager:azure-resourcemanager-resources:jar:2.39.0:compile
[INFO] |  +- com.azure:azure-core:jar:1.47.0:compile (version managed from 1.49.0)
[INFO] |  \- com.azure:azure-core-management:jar:1.12.0:compile (version managed from 1.14.0)
...
```

We use the the sdk-bom (v1.2.22): https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/boms/azure-sdk-bom
But sadly azure-resourcemanager-resources isn't included in it and so we have a conflict.

After I added azure-core-management 1.14.0 to our direct dependencies I got another error:

```
2024-05-30T08:30:08.052496539+02:00 | ERROR | java.lang.NoSuchMethodException: com.azure.resourcemanager.authorization.fluent.models.RoleAssignmentInner.fromJson(com.azure.json.JsonReader) |
2024-05-30T08:30:08.052988641+02:00 | ERROR | Error occurred while executing task for trigger IntervalTrigger [id=1_my.app.directory.DirectoryReader#updateUsers, interval=900000] | : java.util.concurrent.CompletionException: java.lang.IllegalStateException: java.lang.NoSuchMethodException: com.azure.resourcemanager.authorization.fluent.models.RoleAssignmentInner.fromJson(com.azure.json.JsonReader)
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:874)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:887)
        at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2357)
        at java.base/java.util.concurrent.CompletableFuture$MinimalStage.whenComplete(CompletableFuture.java:2948)
        at io.quarkus.scheduler.common.runtime.DefaultInvoker.invoke(DefaultInvoker.java:24)
        at io.quarkus.scheduler.common.runtime.StatusEmitterInvoker.invoke(StatusEmitterInvoker.java:35)
        at io.quarkus.scheduler.runtime.SimpleScheduler$ScheduledTask.doInvoke(SimpleScheduler.java:443)
        at io.quarkus.scheduler.runtime.SimpleScheduler$ScheduledTask$2.call(SimpleScheduler.java:425)
        at io.quarkus.scheduler.runtime.SimpleScheduler$ScheduledTask$2.call(SimpleScheduler.java:422)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$0(ContextImpl.java:178)
        at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:279)
        at io.vertx.core.impl.ContextImpl.lambda$internalExecuteBlocking$2(ContextImpl.java:210)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:604)
        at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.IllegalStateException: java.lang.NoSuchMethodException: com.azure.resourcemanager.authorization.fluent.models.RoleAssignmentInner.fromJson(com.azure.json.JsonReader)
        at com.azure.core.implementation.jackson.JsonSerializableDeserializer.<init>(JsonSerializableDeserializer.java:59)
        at com.azure.core.implementation.jackson.JsonSerializableDeserializer$1.modifyDeserializer(JsonSerializableDeserializer.java:31)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.buildBeanDeserializer(BeanDeserializerFactory.java:301)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:151)
        at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:440)
        at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:384)
        at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:285)
        at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:265)
        at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:163)
        at com.fasterxml.jackson.databind.DeserializationContext.findContextualValueDeserializer(DeserializationContext.java:636)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.createContextual(CollectionDeserializer.java:190)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.createContextual(CollectionDeserializer.java:30)
        at com.fasterxml.jackson.databind.DeserializationContext.handlePrimaryContextualization(DeserializationContext.java:851)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.resolve(BeanDeserializerBase.java:561)
        at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:316)
        at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:265)
        at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:163)
        at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:669)
        at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:5036)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4906)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3942)
        at com.azure.core.implementation.jackson.ObjectMapperShim.readValue(ObjectMapperShim.java:240)
        at com.azure.core.util.serializer.JacksonAdapter.lambda$deserialize$9(JacksonAdapter.java:351)
        at com.azure.core.util.serializer.JacksonAdapter.useAccessHelper(JacksonAdapter.java:483)
        at com.azure.core.util.serializer.JacksonAdapter.deserialize(JacksonAdapter.java:339)
        at com.azure.core.implementation.serializer.HttpResponseBodyDecoder.deserialize(HttpResponseBodyDecoder.java:176)
        at com.azure.core.implementation.serializer.HttpResponseBodyDecoder.deserializeBody(HttpResponseBodyDecoder.java:150)
        at com.azure.core.implementation.serializer.HttpResponseBodyDecoder.decodeByteArray(HttpResponseBodyDecoder.java:93)
        at com.azure.core.implementation.serializer.HttpResponseDecoder$HttpDecodedResponse.getDecodedBody(HttpResponseDecoder.java:93)
        at com.azure.core.implementation.http.rest.AsyncRestProxy.lambda$decodeBytes$8(AsyncRestProxy.java:164)
        at reactor.core.publisher.MonoCallable.call(MonoCallable.java:92)
        at reactor.core.publisher.FluxSubscribeOnCallable$CallableSubscribeOnSubscription.run(FluxSubscribeOnCallable.java:227)
        at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
        at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        ... 1 more
        Suppressed: java.lang.Exception: #block terminated with an error
                at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:100)
                at reactor.core.publisher.Flux.blockLast(Flux.java:2761)
                at com.azure.core.util.paging.ContinuablePagedByIteratorBase.requestPage(ContinuablePagedByIteratorBase.java:102)
                at com.azure.core.util.paging.ContinuablePagedByItemIterable$ContinuablePagedByItemIterator.<init>(ContinuablePagedByItemIterable.java:75)
                at com.azure.core.util.paging.ContinuablePagedByItemIterable.iterator(ContinuablePagedByItemIterable.java:55)
                at java.base/java.lang.Iterable.spliterator(Iterable.java:101)
                at com.azure.core.util.paging.ContinuablePagedIterable.stream(ContinuablePagedIterable.java:85)
                at com.azure.resourcemanager.resources.fluentcore.utils.PagedConverter$PagedIterableImpl.stream(PagedConverter.java:200)
                at my.app.directory.DirectoryReader.getUsersInContributorRoleForSubscription(DirectoryReader.java:270)
                at my.app.directory.DirectoryReader.lambda$updateUsers$5(DirectoryReader.java:200)
                at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
                at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
                at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
                at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
                at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939)
                at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
                at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
                at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
                at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
                at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
                at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
                at my.app.directory.DirectoryReader.updateUsers(DirectoryReader.java:195)
                at my.app.directory.DirectoryReader_ClientProxy.updateUsers(Unknown Source)
                at my.app.directory.DirectoryReader_ScheduledInvoker_updateUsers_fa922a3d5993a039372a4e6b393ec8711b9c46e0.invokeBean(Unknown Source)
                at io.quarkus.scheduler.common.runtime.DefaultInvoker.invoke(DefaultInvoker.java:24)
                at io.quarkus.scheduler.common.runtime.StatusEmitterInvoker.invoke(StatusEmitterInvoker.java:35)
                at io.quarkus.scheduler.runtime.SimpleScheduler$ScheduledTask.doInvoke(SimpleScheduler.java:443)
                at io.quarkus.scheduler.runtime.SimpleScheduler$ScheduledTask$2.call(SimpleScheduler.java:425)
                at io.quarkus.scheduler.runtime.SimpleScheduler$ScheduledTask$2.call(SimpleScheduler.java:422)
                at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$0(ContextImpl.java:178)
                at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:279)
                at io.vertx.core.impl.ContextImpl.lambda$internalExecuteBlocking$2(ContextImpl.java:210)
                at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:604)
                at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
                at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
                at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
                at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
                at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
                ... 1 more
Caused by: java.lang.NoSuchMethodException: com.azure.resourcemanager.authorization.fluent.models.RoleAssignmentInner.fromJson(com.azure.json.JsonReader)
        at java.base/java.lang.Class.getDeclaredMethod(Class.java:2848)
        at com.azure.core.implementation.jackson.JsonSerializableDeserializer.<init>(JsonSerializableDeserializer.java:57)
        ... 38 more
 
```

Here I'm not sure what the solution is. azure-resourcemanager-authorization-2.39.0.jar (class RoleAssignmentInner) probably isn't compatible with azure-core-1.47.0.jar (class JsonSerializableDeserializer) and needs 1.49.0. 1.47.0 also comes from the sdk-bom.

**Expected behavior**
Please consider including azure-resourcemanager-resources and azure-resourcemanager-authorization in the sdk bom so we don't have to manage the versions and we can be sure everything is compatible.

Or do you have an alternate recommendation to address this?

**Comment by joshfree** [comment]
@alzimmermsft @weidongxu-microsoft could you please take a look at this request?

**Comment by weidongxu-microsoft** [comment]
@yvespp 
If you does not use latest feature of azure-resourcemanager, and want it to match the BOM you currently use, you can use [version 2.37.0](https://github.com/Azure/azure-sdk-for-java/blob/azure-resourcemanager_2.37.0/sdk/resourcemanager/azure-resourcemanager-resources/pom.xml)

@alzimmermsft @srnagar for discussion on BOM (we had an earlier ask https://github.com/Azure/azure-sdk-for-java/issues/28281)

**Comment by yvespp** [comment]
I solved it by adding azure-core in the latest version (1.49.1) to our pom. According to the documentation it should always be backward compatible.

**Comment by weidongxu-microsoft** [comment]
@alzimmermsft 

We have another customer also asking about including storage mgmt lib into the BOM.

I think it be doable, but we may need to adjust the release date of mgmt lib, to e.g. about 2nd week of the month (of azure-core release).
This may be easier now, as we only have 4 azure-core releases per year.

**Comment by weidongxu-microsoft** [comment]
SDK dev has scheduled the task on next BOM release, which be expected at July.

In first batch, we plan to add [azure-resourcemanager](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/resourcemanager/azure-resourcemanager/pom.xml) and all its dependencies (which contains about 20 most frequently used ARM libs) into the BOM.

Let us know if you are also using other ARM lib, like azure-resourcemanager-resourcegraph, and we can schedule to put them in the first batch.

**Comment by sfc-gh-krank** [comment]
@weidongxu-microsoft this is awesome! Here is the list of ARM libraries we are using

```
azure-resourcemanager
azure-resourcemanager-appplatform
azure-resourcemanager-appservice
azure-resourcemanager-authorization
azure-resourcemanager-cdn
azure-resourcemanager-compute
azure-resourcemanager-containerinstance
azure-resourcemanager-containerregistry
azure-resourcemanager-containerservice
azure-resourcemanager-cosmos
azure-resourcemanager-dns
azure-resourcemanager-eventhub
azure-resourcemanager-keyvault
azure-resourcemanager-monitor
azure-resourcemanager-msi
azure-resourcemanager-network
azure-resourcemanager-privatedns
azure-resourcemanager-redis
azure-resourcemanager-resources
azure-resourcemanager-search
azure-resourcemanager-servicebus
azure-resourcemanager-sql
azure-resourcemanager-storage
azure-resourcemanager-trafficmanage
```

and Blob Storage
```
azure-blob-storage-cryptography
```

**Comment by weidongxu-microsoft** [comment]
Hi @sfc-gh-krank , I assume it be the `azure-storage-blob-cryptography` that already in current BOM?
https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/boms/azure-sdk-bom/pom.xml#L353-L357

**Comment by weidongxu-microsoft** [comment]
We've put mgmt libs under https://aka.ms/azsdk/java/mgmt into BOM, start with 1.2.36 https://repo1.maven.org/maven2/com/azure/azure-sdk-bom/1.2.36/
