### ISSUE TITLE
[BUG] When using Azurite and the connection string is incorrect, TableAsyncClient operation does not finish

### ISSUE THREAD

**Issue by taisuke-fujimoto** [Azure/azure-sdk-for-java#40442]
**Describe the bug**
TableAsyncClient operation does not finish under the following conditions:
* using Azurite table service
* `AccountKey` in the connection string is incorrect

This only happens in Azurite, so it's not a big issue, but it's a concern that the library is missing unexpected errors in asynchronous processing.

***Exception or Stack Trace***
**This is WARN log.**
```
java.lang.LinkageError: Package versions: jackson-core=2.13.5, jackson-databind=2.13.5, jackson-dataformat-xml=unknown, jackson-datatype-jsr310=2.13.5, azure-core=1.48.0, Troubleshooting version conflicts: https://aka.ms/azsdk/java/dependency/troubleshoot
	at com.azure.core.implementation.jackson.ObjectMapperShim.createXmlMapper(ObjectMapperShim.java:84)
	at com.azure.core.util.serializer.JacksonAdapter$GlobalXmlMapper.<clinit>(JacksonAdapter.java:66)
	at com.azure.core.util.serializer.JacksonAdapter.getXmlMapper(JacksonAdapter.java:467)
	at com.azure.core.util.serializer.JacksonAdapter.lambda$deserialize$10(JacksonAdapter.java:373)
	at com.azure.core.util.serializer.JacksonAdapter.useAccessHelper(JacksonAdapter.java:488)
	at com.azure.core.util.serializer.JacksonAdapter.deserialize(JacksonAdapter.java:368)
	at com.azure.data.tables.implementation.TablesJacksonSerializer.deserialize(TablesJacksonSerializer.java:107)
	at com.azure.data.tables.implementation.TablesJacksonSerializer.deserialize(TablesJacksonSerializer.java:116)
	at com.azure.core.implementation.serializer.HttpResponseBodyDecoder.deserialize(HttpResponseBodyDecoder.java:176)
	at com.azure.core.implementation.serializer.HttpResponseBodyDecoder.deserializeBody(HttpResponseBodyDecoder.java:150)
	at com.azure.core.implementation.serializer.HttpResponseBodyDecoder.decodeByteArray(HttpResponseBodyDecoder.java:67)
	at com.azure.core.implementation.serializer.HttpResponseDecoder$HttpDecodedResponse.getDecodedBody(HttpResponseDecoder.java:93)
	at com.azure.core.implementation.http.rest.AsyncRestProxy.lambda$ensureExpectedStatus$1(AsyncRestProxy.java:138)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:113)
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2400)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:171)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:2196)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:2070)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:96)
	at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:55)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129)
	at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onNext(FluxHide.java:137)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129)
	at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onNext(FluxHide.java:137)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1839)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1839)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1839)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151)
	at reactor.core.publisher.Operators$MonoInnerProducerBase.complete(Operators.java:2666)
	at reactor.core.publisher.MonoSingle$SingleSubscriber.onComplete(MonoSingle.java:180)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onComplete(MonoFlatMapMany.java:260)
	at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onComplete(FluxContextWrite.java:126)
	at reactor.core.publisher.MonoUsing$MonoUsingSubscriber.onNext(MonoUsing.java:232)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:122)
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74)
	at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:126)
	at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:224)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:113)
	at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:191)
	at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1839)
	at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:129)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:260)
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144)
	at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:415)
	at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:439)
	at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:493)
	at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:789)
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:114)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at com.azure.core.http.netty.implementation.AzureSdkHandler.channelRead(AzureSdkHandler.java:224)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.ExceptionInInitializerError
	at com.azure.core.implementation.jackson.ObjectMapperFactory.createXmlMapper(ObjectMapperFactory.java:66)
	at com.azure.core.implementation.jackson.ObjectMapperShim.createXmlMapper(ObjectMapperShim.java:81)
	... 81 more
Caused by: java.lang.IllegalStateException: Failed to retrieve invoker used to create XmlMapper. XML serialization won't be supported until 'com.fasterxml.jackson.dataformat:jackson-dataformat-xml' is added to the classpath or updated to a supported version. Package versions: jackson-core=2.13.5, jackson-databind=2.13.5, jackson-dataformat-xml=unknown, jackson-datatype-jsr310=2.13.5, azure-core=1.48.0, Troubleshooting version conflicts: https://aka.ms/azsdk/java/dependency/troubleshoot
	at com.azure.core.implementation.jackson.XmlMapperFactory.<init>(XmlMapperFactory.java:77)
	at com.azure.core.implementation.jackson.XmlMapperFactory.<clinit>(XmlMapperFactory.java:39)
	... 83 more
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.dataformat.xml.XmlMapper
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at com.azure.core.implementation.jackson.XmlMapperFactory.<init>(XmlMapperFactory.java:51)
	... 84 more
```

**To Reproduce**
https://github.com/taisuke-fujimoto/azure-tables-bug-by-incorrect-connection-string

***Code Snippet***
```kotlin
import com.azure.data.tables.TableClientBuilder

fun main() {
    val incorrectConnectionString = "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=incorrectAccountKey;TableEndpoint=http://127.0.0.1:10002/devstoreaccount1;"

    val tableClient = TableClientBuilder()
        .connectionString(incorrectConnectionString)
        .tableName("test")
        .buildAsyncClient()

    tableClient.createTable().block()
}
```

**Expected behavior**
TableAsyncClient operation should finish with an exception.

**Setup (please complete the following information):**
 - OS: Windows
 - Library/Libraries: com.azure:azure-data-tables:12.4.0
 - Java version: 17

**Comment by alzimmermsft** [comment]
Thanks for reporting this @taisuke-fujimoto.

Looking through the stack trace something seems a bit off here, nothing you did just something I noticed, where `createTable` is attempting to deserialize the response as XML but the documentation for the REST API says it should be JSON:

https://learn.microsoft.com/rest/api/storageservices/create-table#json-version-2013-08-15-and-later-1

If possible, could you get a capture of what Azurite is returning for a response when this API is called.

**Comment by taisuke-fujimoto** [comment]
@alzimmermsft 
Captured from Azurite debug log.
* request
  ```
  2024-06-04T03:12:51.029Z d72b49e6-8202-42cb-8b8a-2b0414591db9 info: TableStorageContextMiddleware: RequestMethod=POST RequestURL=http://127.0.0.1/devstoreaccount1/Tables RequestHeaders:{"host":"127.0.0.1:10002","date":"Tue, 04 Jun 2024 03:12:50 GMT","authorization":"SharedKeyLite devstoreaccount1:cq445rmWGNkGen9sV2RWNEmyLeiGi4kAsyMhyk24ELw=","x-ms-version":"2020-12-06","prefer":"return-no-content","content-type":"application/json;odata=nometadata","dataserviceversion":"3.0","x-ms-client-request-id":"f3601329-d7f5-4b22-9994-474088931aac","accept":"application/json;odata=minimalmetadata","user-agent":"azsdk-java-azure-data-tables/12.4.0 (17.0.6; Windows 11; 10.0)","content-length":"20"} ClientIP=172.17.0.1 Protocol=http HTTPVersion=1.1
  ```
* response
  ```
  2024-06-04T03:12:51.039Z d72b49e6-8202-42cb-8b8a-2b0414591db9 error: ErrorMiddleware: Set HTTP body: "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Error>\n  <Code>AuthorizationFailure</Code>\n  <Message>Server failed to authenticate the request. Make sure the value of the Authorization header is formed correctly including the signature.\nRequestId:d72b49e6-8202-42cb-8b8a-2b0414591db9\nTime:2024-06-04T03:12:51.035Z</Message>\n</Error>"
  2024-06-04T03:12:51.040Z d72b49e6-8202-42cb-8b8a-2b0414591db9 info: EndMiddleware: End response. TotalTimeInMS=12 StatusCode=403 StatusMessage=Forbidden Headers={"server":"Azurite-Table/3.30.0","x-ms-error-code":"AuthorizationFailure","x-ms-request-id":"d72b49e6-8202-42cb-8b8a-2b0414591db9","x-ms-version":"2024-05-04","content-type":"application/xml"}
  ```

Even with the latest version of Azurite (3.30.0), the response when an authentication error occurs is XML.

**Comment by alzimmermsft** [comment]
Thanks for sharing that @taisuke-fujimoto.

@jairmyree, @vcolin7 could you follow-up and do a comparison of the behavior when using the Tables service instead of Azurite. If the behaviors are different we can follow-up with Azurite to be consistent with the service, if the behaviors are the same we'll need to investigate further as this would mean that the service returns different error formats on authentication issues vs invalid request issues.

**Comment by samvaity** [comment]
@jairmyree Could you provide an update on this bug?

**Comment by jairmyree** [comment]
This bug has been backlogged since it does not negatively impact the use of Azure resources. Currently the Tables SDK only has bandwidth for critical bug fixes.
