### ISSUE TITLE
SPXERR_FILE_OPEN_FAILED

### ISSUE THREAD

**Issue by SalmanKhanB** [Azure/azure-sdk-for-java#40516]
### Type of issue

Typo

### Description

the error occured in androoid 10 and 13 i test in android 11 it work perfectly the permission is also allowed. directory name is correct.
update the sdk version to 1.37 still error 
                                                                                                    	
Error }
                                                                                                    	
Retry 0: unexpected error Exception with an error code: 0x8 (SPXERR_FILE_OPEN_FAILED) (Ask Gemini)
                                                                                                    java.lang.RuntimeException: Exception with an error code: 0x8 (SPXERR_FILE_OPEN_FAILED)
                                                                                                    	at com.microsoft.cognitiveservices.speech.util.Contracts.throwIfFail(Unknown Source:46)
                                                                                                    	at com.microsoft.cognitiveservices.speech.SpeechSynthesizer.<init>(Unknown Source:121)
                                                                                                    	at com.sound.voiceeffects.voicechanger.classes.Adapter.VoiceSDKAdapter$SynthesizeSpeechTask.doInBackground(VoiceSDKAdapter.java:517)
                                                                                                    	at com.sound.voiceeffects.voicechanger.classes.Adapter.VoiceSDKAdapter$SynthesizeSpeechTask.doInBackground(VoiceSDKAdapter.java:442)
                                                                                                    	at android.os.AsyncTask$3.call(AsyncTask.java:378)
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                                                                                                    	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                    	at java.lang.Thread.run(Thread.java:919)
                                                                                                    	
[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/java/api/com.microsoft.cognitiveservices.speech?view=azure-java-stable

### Content source URL

https://github.com/Azure/azure-docs-sdk-java/blob/master/docs-ref-autogen/com.microsoft.cognitiveservices.speech.yml

### Document Version Independent Id

b7956d8e-dc4a-51b1-09af-bb2b9f6023fe

### Article author

@rloutlaw

### Metadata

* ID: 50908397-cd07-68e4-fd88-adbfa3eb5a91 
* Service: **azure-ai-services**

**Comment by joshfree** [comment]
@vcolin7 could you please help route this?

**Comment by vcolin7** [comment]
Hi @SalmanKhanB, thanks for reaching out about the Cognitive Speech library for Java. We don't host the source code for it here, but I've reached out to some people that might be better suited to help.

@oscholz, @robch Would you mind taking a look when you get a chance?

**Comment by samvaity** [comment]
Answered here https://github.com/Azure/azure-sdk-for-java/issues/40478#issuecomment-2161613153
