### ISSUE TITLE
[BUG] Cannot use azure-ai-documentintelligence with azure-search-documents

### ISSUE THREAD

**Issue by xuanhai266** [Azure/azure-sdk-for-java#40563]
**Describe the bug**
I build a Java application using latest version of 2 libraries:
azure-search-documents and azure-ai-documentintelligence.
When I try to analyze document layout, it always returns 400 error (The parameter urlSource or base64Source is required.).
If I use azure-search-documents v11.0.0 or remove this library, the problem does not occur.

***Exception or Stack Trace***
Exception in thread "main" com.azure.core.exception.HttpResponseException: Status code 400, "{"error":{"code":"InvalidArgument","message":"Invalid argument.","innererror":{"code":"ParameterMissing","message":"The parameter urlSource or base64Source is required."}}}"
	at com.azure.core.implementation.http.rest.RestProxyBase.instantiateUnexpectedException(RestProxyBase.java:392)
	at com.azure.core.implementation.http.rest.SyncRestProxy.ensureExpectedStatus(SyncRestProxy.java:129)
	at com.azure.core.implementation.http.rest.SyncRestProxy.handleRestReturnType(SyncRestProxy.java:206)
	at com.azure.core.implementation.http.rest.SyncRestProxy.invoke(SyncRestProxy.java:82)
	at com.azure.core.implementation.http.rest.RestProxyBase.invoke(RestProxyBase.java:128)
	at com.azure.core.http.rest.RestProxy.invoke(RestProxy.java:97)
	at jdk.proxy2/jdk.proxy2.$Proxy3.analyzeDocumentSync(Unknown Source)
	at com.azure.ai.documentintelligence.implementation.DocumentIntelligenceClientImpl.analyzeDocumentWithResponse(DocumentIntelligenceClientImpl.java:373)
	at com.azure.ai.documentintelligence.implementation.DocumentIntelligenceClientImpl.lambda$beginAnalyzeDocumentWithModel$6(DocumentIntelligenceClientImpl.java:707)
	at com.azure.core.util.polling.SyncPoller.lambda$createPoller$0(SyncPoller.java:227)
	at com.azure.core.util.polling.SimpleSyncPoller.<init>(SimpleSyncPoller.java:92)
	at com.azure.core.util.polling.SyncPoller.createPoller(SyncPoller.java:196)
	at com.azure.core.util.polling.SyncPoller.createPoller(SyncPoller.java:240)
	at com.azure.ai.documentintelligence.implementation.DocumentIntelligenceClientImpl.beginAnalyzeDocumentWithModel(DocumentIntelligenceClientImpl.java:706)
	at com.azure.ai.documentintelligence.DocumentIntelligenceClient.beginAnalyzeDocument(DocumentIntelligenceClient.java:230)
	at document.intelligence.examp.DocIntelligence.main(DocIntelligence.java:39)

**To Reproduce**
- Create a Java application with Gradle
- Update build.gradle to import 2 libraries : azure-ai-documentintelligence v1.0.0-beta.2, azure-search-documents v11.7.0-beta.3
- Add code to analyze document layout
- Run Java app

***Code Snippet***
```java
DocumentIntelligenceClient client = new DocumentIntelligenceClientBuilder().credential(new AzureKeyCredential(key))
				.endpoint(endpoint).buildClient();

		// sample document
		String modelId = "prebuilt-layout";
		String documentUrl = "https://raw.githubusercontent.com/Azure-Samples/cognitive-services-REST-api-samples/master/curl/form-recognizer/sample-layout.pdf";

		SyncPoller<AnalyzeResultOperation, AnalyzeResultOperation> analyzeLayoutPoller = client.beginAnalyzeDocument(
				modelId, null, null, null, null, null, null, new AnalyzeDocumentRequest().setUrlSource(documentUrl));
				
		AnalyzeResult analyzeLayoutResult = analyzeLayoutPoller.getFinalResult().getAnalyzeResult();
```

**Expected behavior**
There is no error. It should returns analyze results

**Screenshots**
NA

**Setup (please complete the following information):**
 - OS: Windows
 - IDE: Spring Tool Suite
 - Library/Libraries: azure-ai-documentintelligence:1.0.0-beta.2, azure-search-documents:11.7.0-beta.3
 - Java version: 8, 17
 - App Server/Environment: NA
 - Frameworks: NA

**Additional context**
NA

**Comment by alzimmermsft** [comment]
Thanks for filing this issue @xuanhai266.

The issue appears to be that `azure-search-documents` includes a dependency on `azure-core-serializer-json-jackson`, which supplies a service provider implementation for `JsonSerializer`. So, when the request call is made instead of using the default implementation of `JsonSerializer` provided by `azure-core` it uses the one in `azure-core-serializer-json-jackson` which has one major difference in `null` values being included in serialization (the `azure-core` implementation is specifically meant for types managed by Azure SDKs and we don't send `null` values).

One solution to this problem is to Maven exclude the `azure-core-serializer-json-jackson` dependency from `azure-search-documents:

```xml
<dependency>
  <groupId>com.azure</groupId>
  <artifactId>azure-search-documents</artifactId>
  <version>11.7.0-beta.3</version>
  <exclusions>
    <exclusion>
      <groupId>com.azure</groupId>
      <artifactId>azure-core-serializer-json-jackson</artifactId>
    </exclusion>
  </exclusions>
</dependency>
```

Which I've verified locally makes the Document Intelligence API call work. But this could break features in `azure-search-documents`.

Another solution is preventing `azure-core-serializer-json-jackson`'s `JsonSerializer` implementation to be loaded from the service provider.

I also looked at the in-development version of `azure-ai-documentintelligence` and it is migrating to our new serialization framework using `azure-json` and it worked without any dependency removes or changes to build as it no longer uses Jackson annotations for serialization.

**Comment by xuanhai266** [comment]
@alzimmermsft 
Thank you for your response.

> One solution to this problem is to Maven exclude the azure-core-serializer-json-jackson dependency from `azure-search-documents:
Yes, this workaround is working well.
> But this could break features in azure-search-documents.
Do you know which features of azure-search-documents will be broken? 
>I also looked at the in-development version of azure-ai-documentintelligence and it is migrating to our new serialization framework using azure-json and it worked without any dependency removes or changes to build as it no longer uses Jackson annotations for serialization.
When does this version of azure-ai-documentintelligence release?

**Comment by alzimmermsft** [comment]
> Do you know which features of azure-search-documents will be broken if I exclude the azure-core-serializer-json-jackson dependency?

When `azure-core-serializer-json-jackson` is excluded `azure-search-documents` will fall back to the default serializer provided by `azure-core` to manage serializing documents sent to and received from the Search service, unless a custom `JsonSerializer` is passed while creating the `SearchClient` ([SearchClientBuilder.serializer](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/search/azure-search-documents/src/main/java/com/azure/search/documents/SearchClientBuilder.java#L491)). This will result in slightly different serialization handling provided by Jackson Databind, which may break some cases such as the default serializer in `azure-core` doesn't serialize null properties which is a valid case in a Search document.

> When does this version of azure-ai-documentintelligence release?

Let me follow-up with the owner of the SDK on this.

**Comment by alzimmermsft** [comment]
Hi @xuanhai266, a new version of `azure-ai-documentintelligence` has shipped:

https://central.sonatype.com/artifact/com.azure/azure-ai-documentintelligence

With this I think the issue can be considered addressed.
