### ISSUE TITLE
[BUG] Azure Queue Client Does Not Respect Encoding When Updating Message

### ISSUE THREAD

**Issue by tharsanrp** [Azure/azure-sdk-for-java#40585]
**Describe the bug**
When we configure the `QueueClient` with the message encoding of `QueueMessageEncoding.BASE64`, the `updateMessage` call does not encode the message to base64.

***Exception or Stack Trace***
Add the exception log and stack trace if available
```
Exception in thread "main" java.lang.IllegalArgumentException: Illegal base64 character 2c
	at java.base/java.util.Base64$Decoder.decode0(Base64.java:852)
	at java.base/java.util.Base64$Decoder.decode(Base64.java:570)
	at java.base/java.util.Base64$Decoder.decode(Base64.java:593)
	at com.azure.storage.queue.implementation.util.ModelHelper.decodeMessageBody(ModelHelper.java:31)
	at com.azure.storage.queue.implementation.util.ModelHelper.transformPeekedMessageItemInternal(ModelHelper.java:64)
	at com.azure.storage.queue.QueueClient.transformMessagesPeekResponse(QueueClient.java:1177)
	at com.azure.storage.queue.QueueClient.peekMessagesWithOptionalTimeout(QueueClient.java:1156)
	at com.azure.storage.queue.QueueClient.peekMessages(QueueClient.java:1144)
	at org.example.MessageSamples.main(MessageSamples.java:47)
```
**To Reproduce**
1. Setup a client with base64 message encoding
2. Push a message to the queue
3. Update the content of the message 

***Code Snippet***
``` java
package org.example;

import com.azure.core.util.CoreUtils;
import com.azure.storage.queue.QueueClient;
import com.azure.storage.queue.QueueMessageEncoding;
import com.azure.storage.queue.QueueServiceClient;
import com.azure.storage.queue.QueueServiceClientBuilder;
import java.time.Duration;

public class MessageSamples {


    private static final String CONNECTION_STRING = System.getenv("AZURE_STORAGE_CONNECTION_STRING");


    public static void main(String[] args) throws InterruptedException {
        QueueServiceClient queueServiceClient = new QueueServiceClientBuilder().connectionString(CONNECTION_STRING).messageEncoding(QueueMessageEncoding.BASE64).buildClient();

        // Create a queue client
        QueueClient queueClient = queueServiceClient.createQueue(generateRandomName("enqueue", 15));
        for (int i = 0; i < 3; i++) {
            queueClient.sendMessage("Hello World");
        }

        // Get the total count of msg in the queue
        int count = queueClient.getProperties().getApproximateMessagesCount();

        // Peek all messages in queue. It is supposed to print "Hello World" 3 times.
        queueClient.peekMessages(count, null, null).forEach(
            peekedMessage -> System.out.println("Here is the msg: " + peekedMessage.getBody().toString()));

        // Received all messages in queue and update the message "Hello World" to Hello, world!"
        queueClient.receiveMessages(count, Duration.ofSeconds(30), Duration.ofSeconds(50), null).forEach(
            queueMessage -> {
                String msgToReplace = "Hello, world!";
                queueClient.updateMessage(queueMessage.getMessageId(), queueMessage.getPopReceipt(),
                    msgToReplace, Duration.ZERO);
            }
        );

        queueClient.peekMessages(count, null, null).forEach(
            peekedMessage -> System.out.println("Here is the msg a second time: " + peekedMessage.getBody().toString()));

        Thread.sleep(500);
        queueClient.clearMessages();

        // Finally, we delete the queue.
        queueClient.delete();
    }

    static String generateRandomName(String prefix, int length) {
        int len = length > prefix.length() ? length - prefix.length() : 0;
        return prefix + CoreUtils.randomUuid().toString().substring(0, len);
    }
}
```
**Expected behavior**
The client should encode the message to the configured message encoding in the client.
**Screenshots**

**Setup (please complete the following information):**
 - OS: MacOS
 - IDE: IntelliJ
 - Library/Libraries: com.azure:azure-storage-queue

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by tharsanrp** [comment]
I have also made a draft PR to fix the bug, but I am not sure how to add the Test Proxy json. https://github.com/Azure/azure-sdk-for-java/pull/40573

**Comment by tharsanrp** [comment]
Missing labels due to missing information in issue. Closing to open a new issue with missing details

**Comment by alzimmermsft** [comment]
Thanks for filing the PR @tharsanrp. It looks good, it'll just need some test updates. @seanmcc-msft could someone from the Storage SDK team help add test recordings for the newly added tests?

**Comment by ibrahimrabab** [comment]
@tharsanrp thanks for your PR! We were able to get your suggested changes in, will update on the thread once this change gets shipped.
