### ISSUE TITLE
[QUERY] Unable to use Managed Identity to connect Cosmos DB using Spark Cosmos OLTP connector

### ISSUE THREAD

**Issue by kbharucha** [Azure/azure-sdk-for-java#40604]
**Query/Question**
We are using Spark Cosmos DB OLTP connector to connect Cosmos DB from HDInsights. We are trying to connect using Managed Identity. As per the documentation followed, we are using supported connector and have set necessary configs in the spark config. However, we are getting this error.

`Caused by: azure_cosmos_spark.com.microsoft.aad.msal4j.MsalAzureSDKException: java.util.concurrent.ExecutionException: azure_cosmos_spark.com.azure.identity.CredentialUnavailableException: ManagedIdentityCredential authentication unavailable. Connection to IMDS endpoint cannot be established.
	at azure_cosmos_spark.com.microsoft.aad.msal4j.AcquireTokenByAppProviderSupplier.fetchTokenUsingAppTokenProvider(AcquireTokenByAppProviderSupplier.java:79)
	at azure_cosmos_spark.com.microsoft.aad.msal4j.AcquireTokenByAppProviderSupplier.execute(AcquireTokenByAppProviderSupplier.java:56)
	at azure_cosmos_spark.com.microsoft.aad.msal4j.AcquireTokenByClientCredentialSupplier.acquireTokenByClientCredential(AcquireTokenByClientCredentialSupplier.java:78)
	at azure_cosmos_spark.com.microsoft.aad.msal4j.AcquireTokenByClientCredentialSupplier.execute(AcquireTokenByClientCredentialSupplier.java:49)
	at azure_cosmos_spark.com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:69)
	at azure_cosmos_spark.com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:18)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)`

We would like to understand if there are any missing configs.
 
***Why is this not a Bug or a feature Request?***
We followed required documentation.
https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-cosmos-spark_3_2-12/docs/configuration-reference.md#aad-auth-config

**Setup (please complete the following information if applicable):**
 - OS: Linux
 - IDE: IntelliJ
 - Library/Libraries: com.azure.cosmos.spark:azure-cosmos-spark_3-2_2-12:4.31.0
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by kushagraThapar** [comment]
@tvaron3 can you please check on this issue, thanks!

**Comment by afhussain332** [comment]
Hello,
I have a similar issue connecting to cosmos DB from databricks using Managed identity.
azure_cosmos_spark.com.azure.identity.CredentialUnavailableException: Managed Identity authentication is not available.
	at azure_cosmos_spark.com.azure.identity.implementation.IdentityClient.lambda$authenticateWithManagedIdentityConfidentialClient$23(IdentityClient.java:579)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)......
Caused by: azure_cosmos_spark.com.microsoft.aad.msal4j.MsalAzureSDKException: java.util.concurrent.ExecutionException: azure_cosmos_spark.com.azure.identity.CredentialUnavailableException: ManagedIdentityCredential authentication unavailable. Connection to IMDS endpoint cannot be established.
	at azure_cosmos_spark.com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:18)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
	... 5 more
.. 11 more
Please advise

**Comment by kushagraThapar** [comment]
@FabianMeiswinkel can you please take a look at this one?

**Comment by FabianMeiswinkel** [comment]
@afhussain332 - when you get that error in Databricks it means your Databricks workspace is most likely quite old. Databricks has started to populate ManagedIdentity only in the last couple of months - so, using a new Workspace should unblock.

**Comment by FabianMeiswinkel** [comment]
@kbharucha - For HDInsights you can't just set the auth type to `ManagedIdentity` - HDInsights doe snot provide direct access to the ManagedIdentity in the nodes on which the Spark driver/executors run. Instead HDInsights provides a libray `hdi-oauth-token-utils` that allows getting access tokens for external resources via the library. To make use of that in the Cosmos DB Spark Connector you have to set the `spark.cosmos.auth.type` config to `AccessToken` and provide a custom `AccountDataResolver` implementation on the classpath that uses the `HdiIdentityTokenServiceUtils.getAccessToken` API to provide tokens t the Cosmos DB Spark connector. A sample demonstrating on how to build such an `AccountDataResolver` implementation can be found [here](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-cosmos-spark-account-data-resolver-sample/src/main/scala/com/azure/cosmos/spark/samples/ManagedIdentityAccountDataResolver.scala) and HDInsights has provided guidance on how to use their library [here](https://learn.microsoft.com/en-us/azure/hdinsight/msi-support-to-access-azure-services). All of that said, it might just be easier to use Azure Databricks instead of HDInsights to simplify this.

**Comment by kbharucha** [comment]
@FabianMeiswinkel : thanks for sharing it.. @xinlian12 assisted us with this ask.
