### ISSUE TITLE
[BUG] The lock supplied is invalid. Either the lock expired, or the message has already been removed from the queue.

### ISSUE THREAD

**Issue by gataricd** [Azure/azure-sdk-for-java#40655]
**Describe the bug**
I am getting the following error in Kotlin Spring Boot application:
`The lock supplied is invalid. Either the lock expired, or the message has already been removed from the queue.` The Message lock duration of the queue is set to 1 minute, but it happens that the same message gets received 3 times in one minute.
I assume this happens while trying to complete a message. I found similar issue on [Stackoverflow](https://stackoverflow.com/questions/28127001/the-lock-supplied-is-invalid-either-the-lock-expired-or-the-message-has-alread) and the solution was to set prefetchCount=0, disableAutoComplete, maxAutoLockRenewDuration to 0 which I already use. We have never had this problem before and it started happening when we switched to the `com.azure:azure-messaging-servicebus:7.15.0`.

***Exception or Stack Trace***
```
com.azure.messaging.servicebus.ServiceBusException: The lock supplied is invalid. Either the lock expired, or the message has already been removed from the queue. For more information please see https://aka.ms/ServiceBusExceptions . Reference:53d2e560-59e6-4e3a-8336-b6bedd2e7f20, TrackingId:57a278b30000004d0000315a6666e4e0_G0_B15, SystemTracker:gi::G0:38162340:vil-command-queue_3064e8_1718019170742, bi::in-connection934(G0-2749081)::session935::link12634, Timestamp:2024-06-13T11:47:31, errorContext[NAMESPACE: westeurope-eu-e-servicebus.servicebus.windows.net. ERROR CONTEXT: N/A, PATH: vil-command-queue, REFERENCE_ID: vil-command-queue_3064e8_1718019170742, LINK_CREDIT: 9]
	at com.azure.messaging.servicebus.ServiceBusReceiverAsyncClient.lambda$updateDisposition$50(ServiceBusReceiverAsyncClient.java:1659)
	at reactor.core.publisher.Mono.lambda$onErrorMap$28(Mono.java:3783)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94)
	at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.onError(TracingSubscriber.java:85)
	at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.onError(TracingSubscriber.java:85)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:222)
	at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.onError(TracingSubscriber.java:85)
	at reactor.core.publisher.FluxDoOnEach$DoOnEachSubscriber.onError(FluxDoOnEach.java:195)
	at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.onError(TracingSubscriber.java:85)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:106)
	at reactor.core.publisher.Operators.error(Operators.java:198)
	at reactor.core.publisher.MonoError.subscribe(MonoError.java:53)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4495)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103)
	at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.onError(TracingSubscriber.java:85)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onError(MonoIgnoreThen.java:278)
	at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.onError(TracingSubscriber.java:85)
	at reactor.core.publisher.Operators$MonoSubscriber.onError(Operators.java:1886)
	at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.signalCached(MonoCacheTime.java:340)
	at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.onError(MonoCacheTime.java:363)
	at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.onError(TracingSubscriber.java:85)
	at reactor.core.publisher.MonoCreate$DefaultMonoSink.error(MonoCreate.java:201)
	at com.azure.core.amqp.implementation.handler.ReceiverUnsettledDeliveries$DispositionWork.onComplete(ReceiverUnsettledDeliveries.java:782)
	at com.azure.core.amqp.implementation.handler.ReceiverUnsettledDeliveries.completeDispositionWorkWithSettle(ReceiverUnsettledDeliveries.java:575)
	at com.azure.core.amqp.implementation.handler.ReceiverUnsettledDeliveries.handleRetriableRejectedRemoteOutcome(ReceiverUnsettledDeliveries.java:431)
	at com.azure.core.amqp.implementation.handler.ReceiverUnsettledDeliveries.onDispositionAck(ReceiverUnsettledDeliveries.java:255)
	at com.azure.core.amqp.implementation.handler.ReceiverDeliveryHandler.handleSettleViaDisposition(ReceiverDeliveryHandler.java:304)
	at com.azure.core.amqp.implementation.handler.ReceiverDeliveryHandler.onDelivery(ReceiverDeliveryHandler.java:113)
	at com.azure.core.amqp.implementation.handler.ReceiveLinkHandler2.onDelivery(ReceiveLinkHandler2.java:152)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:185)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291)
	at com.azure.core.amqp.implementation.ReactorExecutor.run(ReactorExecutor.java:91)
	at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.ContextPropagationOperator$RunnableWrapper.run(ContextPropagationOperator.java:358)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:103)
		at reactor.core.publisher.Mono.block(Mono.java:1712)
		at com.azure.messaging.servicebus.ServiceBusReceivedMessageContext.complete(ServiceBusReceivedMessageContext.java:104)
		at infrastructure.adapters.inbound.consumers.messagebroker.AzureServiceBusMessageProcessor$processMessageInTenantAndMdcContext$1.invoke(AzureServiceBusMessageProcessor.kt:58)
		at infrastructure.adapters.inbound.consumers.messagebroker.AzureServiceBusMessageProcessor$processMessageInTenantAndMdcContext$1.invoke(AzureServiceBusMessageProcessor.kt:55)
		at infrastructure.adapters.inbound.consumers.command.messagebroker.ServiceBusMessageInVehicleContextExecutor.processMessageInVehicleContext(ServiceBusMessageInVehicleContextExecutor.kt:38)
		at infrastructure.adapters.inbound.consumers.messagebroker.AzureServiceBusMessageProcessor.processMessageInTenantAndMdcContext(AzureServiceBusMessageProcessor.kt:55)
		at infrastructure.adapters.inbound.consumers.messagebroker.AzureServiceBusMessageListener.registerMessageListener$lambda$0(AzureServiceBusMessageListener.kt:42)
		at com.azure.messaging.servicebus.MessagePump.notifyMessage(MessagePump.java:157)
		at com.azure.messaging.servicebus.MessagePump.lambda$handleMessage$3(MessagePump.java:142)
		at com.azure.messaging.servicebus.implementation.instrumentation.ServiceBusReceiverInstrumentation.instrumentProcess(ServiceBusReceiverInstrumentation.java:94)
		at com.azure.messaging.servicebus.MessagePump.handleMessage(MessagePump.java:135)
		at com.azure.messaging.servicebus.MessagePump$RunOnWorker.lambda$apply$0(MessagePump.java:212)
		at reactor.core.publisher.MonoRunnable.subscribe(MonoRunnable.java:49)
		at reactor.core.publisher.Mono.subscribe(Mono.java:4495)
		at reactor.core.publisher.MonoSubscribeOn$SubscribeOnSubscriber.run(MonoSubscribeOn.java:126)
		at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.ContextPropagationOperator$RunnableWrapper.run(ContextPropagationOperator.java:358)
		at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
		at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
		... 5 more
Caused by: com.azure.core.amqp.exception.AmqpException: The lock supplied is invalid. Either the lock expired, or the message has already been removed from the queue. For more information please see https://aka.ms/ServiceBusExceptions . Reference:53d2e560-59e6-4e3a-8336-b6bedd2e7f20, TrackingId:57a278b30000004d0000315a6666e4e0_G0_B15, SystemTracker:gi::G0:38162340:vil-command-queue_3064e8_1718019170742, bi::in-connection934(G0-2749081)::session935::link12634, Timestamp:2024-06-13T11:47:31, errorContext[NAMESPACE: westeurope-eu-e-servicebus.servicebus.windows.net. ERROR CONTEXT: N/A, PATH: vil-command-queue, REFERENCE_ID: vil-command-queue_3064e8_1718019170742, LINK_CREDIT: 9]
	at com.azure.core.amqp.implementation.ExceptionUtil.toException(ExceptionUtil.java:90)
	at com.azure.core.amqp.implementation.handler.ReceiverUnsettledDeliveries.handleRetriableRejectedRemoteOutcome(ReceiverUnsettledDeliveries.java:408)
	... 17 more

```

**To Reproduce**
I was not able to reproduce this bug locally. It happens only during the application usage in an AKS.

***Code Snippet***
This is the code I am using to configure service bus client:
```
val processorClient: ServiceBusProcessorClient = serviceBusClientBuilder
            .credential(serviceBusFullyQualifiedName, DefaultAzureCredentialBuilder().build())
            .processor()
            .queueName(queueName)
            .processMessage(handler)
            .processError { context -> processError(context) }
            .maxConcurrentCalls(10)
            .disableAutoComplete()
            .maxAutoLockRenewDuration(Duration.ZERO)
            .prefetchCount(0)
            .buildProcessorClient()
processorClient.start()
```

**Expected behavior**
I am not expecting to receive such an error and the same message should not be received three times in one minute when the lock interval is 1 minute.

**Setup (please complete the following information):**
 - OS: Linux
 - Library/Libraries: com.azure:azure-messaging-servicebus:7.15.0
 - Java version: 21
 - App Server/Environment: AKS
 - Frameworks: Spring Boot

**Comment by deniszpua** [comment]
Observing the same on 7.15.1 for subscription workers

**Comment by lmolkova** [comment]
Thank you for reporting this!

As a first step, could you please try updating to the latest (stable) `azure-messaging-servicebus` version which is 7.17.0 at the moment. It has improvements around internal errors reporting and would help to investigate the issue.

Also, we just published an [update to the troubleshooting guide](https://learn.microsoft.com/en-us/azure/developer/java/sdk/troubleshooting-messaging-service-bus-overview#message-or-session-lock-is-lost) regarding lock being lost. Please take a look.

While some level of such errors caused by transient issues is inevitable, this

> Message lock duration of the queue is set to 1 minute, but it happens that the same message gets received 3 times in one minute.

does not look like a transient issue.

Do you happen to have some logs related to such messages? Are there any errors in the logs around that time?

Also, it seems you have OTel enabled (based on the stack trace) - do you happen to have some spans for these message processings recorded? They should have correlated calls for completions/abandonment/lock renewal operations. 

Please share logs and traces that you have.

Here's the details on how to enable [logs](https://learn.microsoft.com/en-us/azure/developer/java/sdk/troubleshooting-messaging-service-bus-overview#enable-and-configure-logging) and [distributed tracing](https://learn.microsoft.com/en-us/azure/developer/java/sdk/tracing#tracing-azure-sdk-calls-with-opentelemetry-agent).
