### ISSUE TITLE
[BUG] `XmlMapperFactory` does not work with `ReflectionUtilsClassic`

### ISSUE THREAD

**Issue by DaveCTurner** [Azure/azure-sdk-for-java#41243]
**Describe the bug**

`com.azure.core.implementation.jackson.XmlMapperFactory#createXmlMapper` attempts to reflectively invoke `com.fasterxml.jackson.dataformat.xml.XmlMapper$Builder#enable(ToXmlGenerator.Feature...)` with the argument `com.fasterxml.jackson.dataformat.xml.ser.ToXmlGenerator.Feature#WRITE_XML_DECLARATION`. If `com.azure.core.implementation.ReflectionUtils#INSTANCE` is of type `com.azure.core.implementation.ReflectionUtilsMethodHandle` then this works ok, but if the static initializer of `ReflectionUtils` cannot construct such an instance then it falls back to using a `com.azure.core.implementation.ReflectionUtilsClassic` instead. These two implementations behave differently when calling a method with a varargs parameter: `ReflectionUtilsMethodHandle` calls `java.lang.invoke.MethodHandle#invokeWithArguments(java.lang.Object...)` which automatically adds an array wrapper if needed, whereas `ReflectionUtilsClassic` will fail with `java.lang.IllegalArgumentException: argument type mismatch`.

I believe that we need to do something like replacing the following line in `XmlMapperFactory` ...

```java
    enableWriteXmlDeclaration.invokeWithArguments(xmlMapperBuilder, writeXmlDeclaration);
```

... with this one:

```java
    enableWriteXmlDeclaration.invokeWithArguments(xmlMapperBuilder, new Object[]{writeXmlDeclaration});
```

***Exception or Stack Trace***

```
[2024-07-22T13:49:43,249][WARN ][i.n.c.AbstractChannelHandlerContext] [david-turner] An exception 'java.lang.ExceptionInInitializerError' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.lang.ExceptionInInitializerError: null
        at com.azure.core.util.serializer.JacksonAdapter.getXmlMapper(JacksonAdapter.java:470) ~[?:?]
        at com.azure.core.util.serializer.JacksonAdapter.lambda$deserialize$9(JacksonAdapter.java:352) ~[?:?]
        at com.azure.core.util.serializer.JacksonAdapter.useAccessHelper(JacksonAdapter.java:491) ~[?:?]
        at com.azure.core.util.serializer.JacksonAdapter.deserialize(JacksonAdapter.java:347) ~[?:?]
        at com.azure.core.implementation.serializer.HttpResponseBodyDecoder.deserialize(HttpResponseBodyDecoder.java:176) ~[?:?]
        at com.azure.core.implementation.serializer.HttpResponseBodyDecoder.deserializeBody(HttpResponseBodyDecoder.java:150) ~[?:?]
        at com.azure.core.implementation.serializer.HttpResponseBodyDecoder.decodeByteArray(HttpResponseBodyDecoder.java:67) ~[?:?]
        at com.azure.core.implementation.serializer.HttpResponseDecoder$HttpDecodedResponse.getDecodedBody(HttpResponseDecoder.java:93) ~[?:?]
        at com.azure.core.implementation.http.rest.AsyncRestProxy.lambda$ensureExpectedStatus$1(AsyncRestProxy.java:136) ~[?:?]
        at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:113) ~[?:?]
        at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2400) ~[?:?]
        at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:171) ~[?:?]
        at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:2196) ~[?:?]
        at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:2070) ~[?:?]
        at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:96) ~[?:?]
        at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:55) ~[?:?]
        at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[?:?]
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157) ~[?:?]
        at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129) ~[?:?]
        at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onNext(FluxHide.java:137) ~[?:?]
        at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129) ~[?:?]
        at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onNext(FluxHide.java:137) ~[?:?]
        at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79) ~[?:?]
        at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1839) ~[?:?]
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151) ~[?:?]
        at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1839) ~[?:?]
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151) ~[?:?]
        at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.complete(MonoIgnoreThen.java:292) ~[?:?]
        at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onNext(MonoIgnoreThen.java:187) ~[?:?]
        at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:180) ~[?:?]
        at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.onNext(FluxMapFuseable.java:299) ~[?:?]
        at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.onNext(FluxMapFuseable.java:299) ~[?:?]
        at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1839) ~[?:?]
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151) ~[?:?]
        at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79) ~[?:?]
        at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1839) ~[?:?]
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151) ~[?:?]
        at reactor.core.publisher.Operators$MonoInnerProducerBase.complete(Operators.java:2666) ~[?:?]
        at reactor.core.publisher.MonoSingle$SingleSubscriber.onComplete(MonoSingle.java:180) ~[?:?]
        at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onComplete(MonoFlatMapMany.java:260) ~[?:?]
        at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onComplete(FluxContextWrite.java:126) ~[?:?]
        at reactor.core.publisher.MonoUsing$MonoUsingSubscriber.onNext(MonoUsing.java:232) ~[?:?]
        at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:122) ~[?:?]
        at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74) ~[?:?]
        at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:126) ~[?:?]
        at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:126) ~[?:?]
        at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:224) ~[?:?]
        at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:113) ~[?:?]
        at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:191) ~[?:?]
        at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107) ~[?:?]
        at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1839) ~[?:?]
        at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:129) ~[?:?]
        at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:260) ~[?:?]
        at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144) ~[?:?]
        at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:415) ~[?:?]
        at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:439) ~[?:?]
        at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:493) ~[?:?]
        at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:768) ~[?:?]
        at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:114) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[?:?]
        at com.azure.core.http.netty.implementation.AzureSdkHandler.channelRead(AzureSdkHandler.java:224) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[?:?]
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) ~[?:?]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[?:?]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[?:?]
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[?:?]
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1475) ~[?:?]
        at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1338) ~[?:?]
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1387) ~[?:?]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:530) ~[?:?]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:469) ~[?:?]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[?:?]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[?:?]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[?:?]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[?:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[?:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:689) ~[?:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:652) ~[?:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[?:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[?:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[?:?]
        at org.elasticsearch.repositories.azure.SocketAccess.lambda$doPrivilegedVoidException$0(SocketAccess.java:46) ~[?:?]
        at java.security.AccessController.doPrivileged(AccessController.java:571) ~[?:?]
        at org.elasticsearch.repositories.azure.SocketAccess.doPrivilegedVoidException(SocketAccess.java:45) ~[?:?]
        at org.elasticsearch.repositories.azure.executors.PrivilegedExecutor.lambda$execute$0(PrivilegedExecutor.java:27) ~[?:?]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:917) ~[elasticsearch-8.16.0-SNAPSHOT.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1570) ~[?:?]
Caused by: java.lang.IllegalArgumentException: argument type mismatch
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:107) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at com.azure.core.implementation.MethodReflectiveInvoker.invokeWithArguments(MethodReflectiveInvoker.java:24) ~[?:?]
        at com.azure.core.implementation.jackson.XmlMapperFactory.createXmlMapper(XmlMapperFactory.java:102) ~[?:?]
        at com.azure.core.implementation.jackson.ObjectMapperFactory.createXmlMapper(ObjectMapperFactory.java:63) ~[?:?]
        at com.azure.core.implementation.jackson.ObjectMapperShim.createXmlMapper(ObjectMapperShim.java:83) ~[?:?]
        at com.azure.core.util.serializer.JacksonAdapter$GlobalXmlMapper.<clinit>(JacksonAdapter.java:66) ~[?:?]
        ... 100 more
```

**To Reproduce**

Initialize the Azure plugin in a context where `ReflectionUtilsMethodHandle` cannot be instantiated, for instance with the security manager enabled and with a sufficiently restrictive security policy.

**Expected behavior**

`XmlMapperFactory` should work correctly with either implementation of `ReflectionUtilsApi`.

**Setup (please complete the following information):**
 - OS: `Linux/6.8.0-1010-azure/amd64`
 - IDE: N/A
 - Library/Libraries: `com.azure:azure-core:1.50.0`
 - Java version: `Oracle Corporation/OpenJDK 64-Bit Server VM/22.0.1/22.0.1+8-16]`
 - App Server/Environment: running within the `repository-azure` plugin in Elasticsearch
 - Frameworks: none

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by DaveCTurner** [comment]
Hi @alzimmermsft, I believe I was using `azure-core-1.50.0`. It doesn't look like `XmlMapperFactory` was touched in #40719 - its [changelog](https://github.com/Azure/azure-sdk-for-java/commits/main/sdk/core/azure-core/src/main/java/com/azure/core/implementation/jackson/XmlMapperFactory.java) indicates the last change was #38799.

Here's the whole list of dependencies in case it helps:

```
$ ls build/distribution/local/elasticsearch-8.16.0-SNAPSHOT/modules/repository-azure/ | sort
accessors-smart-2.5.1.jar
asm-9.3.jar
azure-core-1.50.0.jar
azure-core-http-netty-1.15.2.jar
azure-identity-1.13.1.jar
azure-json-1.1.0.jar
azure-storage-blob-12.26.1.jar
azure-storage-common-12.19.1.jar
azure-storage-internal-avro-12.5.3.jar
azure-xml-1.0.0.jar
content-type-2.3.jar
elasticsearch-ssl-config-8.16.0-SNAPSHOT.jar
jackson-annotations-2.13.5.jar
jackson-core-2.13.5.jar
jackson-databind-2.13.4.2.jar
jackson-dataformat-xml-2.13.5.jar
jackson-datatype-jsr310-2.13.5.jar
jackson-module-jaxb-annotations-2.13.5.jar
jakarta.activation-api-1.2.1.jar
jakarta.xml.bind-api-2.3.2.jar
jcip-annotations-1.0-1.jar
jna-5.14.0.jar
jna-platform-5.14.0.jar
json-smart-2.5.0.jar
lang-tag-1.7.jar
log4j-slf4j2-impl-2.19.0.jar
msal4j-1.16.1.jar
msal4j-persistence-extension-1.3.0.jar
netty-buffer-4.1.109.Final.jar
netty-codec-4.1.109.Final.jar
netty-codec-dns-4.1.109.Final.jar
netty-codec-http-4.1.109.Final.jar
netty-codec-http2-4.1.109.Final.jar
netty-codec-socks-4.1.109.Final.jar
netty-common-4.1.109.Final.jar
netty-handler-4.1.109.Final.jar
netty-handler-proxy-4.1.109.Final.jar
netty-resolver-4.1.109.Final.jar
netty-resolver-dns-4.1.109.Final.jar
netty-transport-4.1.109.Final.jar
netty-transport-native-unix-common-4.1.109.Final.jar
nimbus-jose-jwt-9.37.3.jar
oauth2-oidc-sdk-11.9.1.jar
plugin-descriptor.properties
plugin-security.policy
reactive-streams-1.0.4.jar
reactor-core-3.4.34.jar
reactor-netty-core-1.0.39.jar
reactor-netty-http-1.0.39.jar
repository-azure-8.16.0-SNAPSHOT.jar
slf4j-api-2.0.6.jar
stax2-api-4.2.1.jar
transport-netty4-8.16.0-SNAPSHOT.jar
woodstox-core-6.4.0.jar
```

**Comment by alzimmermsft** [comment]
Thanks @DaveCTurner, I understand now. I confused this with another issue where the `java.lang.reflect.*` implementation was passing the target arguments incorrectly on constructor and static method calls. I now see this issue is the API is being called incorrectly, with a wrong type.

I'll file a fix for this shortly.
