### ISSUE TITLE
[BUG] Path with a single slash causes an Index out of bounds error in DataLakePathAsyncClient 

### ISSUE THREAD

**Issue by nineinchnick** [Azure/azure-sdk-for-java#41393]
**Describe the bug**
Calling `DataLakeFilesystemClient.getDirectoryClient("/")` causes an exception. 

***Exception or Stack Trace***
```
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 0
	at com.azure.storage.file.datalake.DataLakePathAsyncClient.<init>(DataLakePathAsyncClient.java:165)
	at com.azure.storage.file.datalake.DataLakeDirectoryAsyncClient.<init>(DataLakeDirectoryAsyncClient.java:89)
	at com.azure.storage.file.datalake.DataLakeFileSystemAsyncClient.getDirectoryAsyncClient(DataLakeFileSystemAsyncClient.java:211)
	at com.azure.storage.file.datalake.DataLakeFileSystemClient.getDirectoryClient(DataLakeFileSystemClient.java:191)
```

**To Reproduce**
Call `DataLakeFilesystemClient.getDirectoryClient("/")`.

***Code Snippet***
```java
        // requires a String `account`, `containerName`, and AzureAuth `azureAuth` to be set. 
        DataLakeServiceClientBuilder serviceClientBuilder = new DataLakeServiceClientBuilder()
                .endpoint("https://%s.dfs.core.windows.net".formatted(account));
        azureAuth.setAuth(account, serviceClientBuilder);
        DataLakeServiceClient serviceClient = serviceClientBuilder.buildClient();
        DataLakeFileSystemClient fileSystemClient =  serviceClient.getFileSystemClient(containerName);
        // throws the exception
        fileSystemClient.getDirectoryClient("/");
```

**Expected behavior**
No exception thrown.

**Screenshots**

**Setup (please complete the following information):**
 - OS: macOS
 - IDE: IntelliJ
 - Library/Libraries: com.azure:azure-sdk-bom:1.2.26
 - Java version: 22
 - App Server/Environment: IDE
 - Frameworks: n/a

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**
This is caused by a change in https://github.com/Azure/azure-sdk-for-java/pull/40437/files#diff-2e339f4c2419fc6358f38081d34be6ab0bdc25856db2decf3876563d0dbd9b33R165

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by nineinchnick** [comment]
What's the version in which this was fixed? I don't think it made it to 1.2.27.
