### ISSUE TITLE
[BUG] Enabling logging triggers fatal error under security manager

### ISSUE THREAD

**Issue by DaveCTurner** [Azure/azure-sdk-for-java#41453]
**Describe the bug**

When running an application that uses the Azure SDK in an environment with the `${AZURE_LOG_LEVEL}` environment variable set to `INFO`, and the application uses a locked down security manager, then the static constructor of `NettyAsyncHttpClientBuilder` will fail without the `("java.lang.RuntimePermission" "getClassLoader")` permission.

AFAICT the only need for this permission is to log this specific log message, so we'd rather not grant it, and would prefer instead that the resulting exception be handled within the Azure SDK without throwing an `Error` that fails the whole application.

***Exception or Stack Trace***

```
[2024-08-07T07:46:49,961][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [node-0] fatal error in thread [elasticsearch[node-0][snapshot][T#1]], exiting
java.lang.ExceptionInInitializerError: null
	at org.elasticsearch.repositories.azure.AzureClientProvider.createClient(AzureClientProvider.java:176) ~[?:?]
	at org.elasticsearch.repositories.azure.AzureStorageService.client(AzureStorageService.java:91) ~[?:?]
	at org.elasticsearch.repositories.azure.AzureBlobStore.getAzureBlobServiceClientClient(AzureBlobStore.java:633) ~[?:?]
	at org.elasticsearch.repositories.azure.AzureBlobStore.asyncClient(AzureBlobStore.java:629) ~[?:?]
	at org.elasticsearch.repositories.azure.AzureBlobStore.lambda$executeSingleUpload$19(AzureBlobStore.java:463) ~[?:?]
	at org.elasticsearch.repositories.azure.SocketAccess.lambda$doPrivilegedVoidException$0(SocketAccess.java:46) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:571) ~[?:?]
	at org.elasticsearch.repositories.azure.SocketAccess.doPrivilegedVoidException(SocketAccess.java:45) ~[?:?]
	at org.elasticsearch.repositories.azure.AzureBlobStore.executeSingleUpload(AzureBlobStore.java:462) ~[?:?]
	at org.elasticsearch.repositories.azure.AzureBlobStore.writeBlob(AzureBlobStore.java:387) ~[?:?]
	at org.elasticsearch.repositories.azure.AzureBlobContainer.writeBlob(AzureBlobContainer.java:115) ~[?:?]
	at org.elasticsearch.repositories.azure.AzureBlobContainer.writeBlobAtomic(AzureBlobContainer.java:110) ~[?:?]
	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.startVerification(BlobStoreRepository.java:2156) ~[elasticsearch-8.16.0-SNAPSHOT.jar:?]
	at org.elasticsearch.repositories.RepositoriesService.lambda$validatePutRepositoryRequest$11(RepositoriesService.java:361) ~[elasticsearch-8.16.0-SNAPSHOT.jar:?]
	at org.elasticsearch.action.ActionRunnable$1.doRun(ActionRunnable.java:36) ~[elasticsearch-8.16.0-SNAPSHOT.jar:?]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:984) ~[elasticsearch-8.16.0-SNAPSHOT.jar:?]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) ~[elasticsearch-8.16.0-SNAPSHOT.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1570) ~[?:?]
Caused by: java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "getClassLoader")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:488) ~[?:?]
	at java.security.AccessController.checkPermission(AccessController.java:1085) ~[?:?]
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:411) ~[?:?]
	at java.lang.ClassLoader.checkClassLoaderPermission(ClassLoader.java:2068) ~[?:?]
	at java.lang.Thread.getContextClassLoader(Thread.java:2312) ~[?:?]
	at io.netty.util.internal.PlatformDependent0$11.run(PlatformDependent0.java:948) ~[?:?]
	at io.netty.util.internal.PlatformDependent0$11.run(PlatformDependent0.java:945) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:319) ~[?:?]
	at io.netty.util.internal.PlatformDependent0.getContextClassLoader(PlatformDependent0.java:945) ~[?:?]
	at io.netty.util.internal.PlatformDependent.getContextClassLoader(PlatformDependent.java:1088) ~[?:?]
	at io.netty.util.Version.identify(Version.java:66) ~[?:?]
	at io.netty.util.Version.identify(Version.java:56) ~[?:?]
	at com.azure.core.http.netty.implementation.NettyUtility.validateNettyVersions(NettyUtility.java:106) ~[?:?]
	at com.azure.core.http.netty.implementation.NettyUtility.validateNettyVersions(NettyUtility.java:97) ~[?:?]
	at com.azure.core.http.netty.NettyAsyncHttpClientBuilder.<clinit>(NettyAsyncHttpClientBuilder.java:118) ~[?:?]
	... 20 more
```

**To Reproduce**

Obtain a recent-ish Elasticsearch commit (for instance [`cda877308cdb4e784a06fe282dedcf9833f909e8`](https://github.com/elastic/elasticsearch/tree/cda877308cdb4e784a06fe282dedcf9833f909e8/)), configure it for an Azure repository, and run it with `AZURE_LOG_LEVEL=INFO`:

```
./gradlew :distribution:archives:darwin-aarch64-tar:assemble
tar xf distribution/archives/darwin-aarch64-tar/build/distributions/elasticsearch-8.16.0-SNAPSHOT-darwin-aarch64.tar.gz
cd elasticsearch-8.16.0-SNAPSHOT
bin/elasticsearch-keystore create
echo 'anything' | bin/elasticsearch-keystore add azure.client.default.account -x
export AZURE_LOG_LEVEL=INFO
bin/elasticsearch -Expack.security.enabled=false -d
```

Then try and create an azure repository:

```
curl -XPUT 'http://localhost:9200/_snapshot/test' -H 'Content-type: application/json' --data-binary '{"type":"azure"}'
```

This will crash Elasticsearch with the following exception in the logs:

```
$ tail -n40 logs/elasticsearch.log
[2024-08-07T08:09:02,060][INFO ][o.e.x.c.t.IndexTemplateRegistry] [Davids-MacBook-Pro.local] adding ingest pipeline metrics-apm@pipeline
[2024-08-07T08:09:05,552][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [Davids-MacBook-Pro.local] fatal error in thread [elasticsearch[Davids-MacBook-Pro.local][snapshot][T#1]], exiting
java.lang.ExceptionInInitializerError: null
	at org.elasticsearch.repositories.azure.AzureClientProvider.createClient(AzureClientProvider.java:176) ~[?:?]
	at org.elasticsearch.repositories.azure.AzureStorageService.client(AzureStorageService.java:91) ~[?:?]
	at org.elasticsearch.repositories.azure.AzureBlobStore.getAzureBlobServiceClientClient(AzureBlobStore.java:633) ~[?:?]
	at org.elasticsearch.repositories.azure.AzureBlobStore.asyncClient(AzureBlobStore.java:629) ~[?:?]
	at org.elasticsearch.repositories.azure.AzureBlobStore.lambda$executeSingleUpload$19(AzureBlobStore.java:463) ~[?:?]
	at org.elasticsearch.repositories.azure.SocketAccess.lambda$doPrivilegedVoidException$0(SocketAccess.java:46) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:571) ~[?:?]
	at org.elasticsearch.repositories.azure.SocketAccess.doPrivilegedVoidException(SocketAccess.java:45) ~[?:?]
	at org.elasticsearch.repositories.azure.AzureBlobStore.executeSingleUpload(AzureBlobStore.java:462) ~[?:?]
	at org.elasticsearch.repositories.azure.AzureBlobStore.writeBlob(AzureBlobStore.java:387) ~[?:?]
	at org.elasticsearch.repositories.azure.AzureBlobContainer.writeBlob(AzureBlobContainer.java:115) ~[?:?]
	at org.elasticsearch.repositories.azure.AzureBlobContainer.writeBlobAtomic(AzureBlobContainer.java:110) ~[?:?]
	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.startVerification(BlobStoreRepository.java:2156) ~[elasticsearch-8.16.0-SNAPSHOT.jar:?]
	at org.elasticsearch.repositories.RepositoriesService.lambda$validatePutRepositoryRequest$11(RepositoriesService.java:361) ~[elasticsearch-8.16.0-SNAPSHOT.jar:?]
	at org.elasticsearch.action.ActionRunnable$1.doRun(ActionRunnable.java:36) ~[elasticsearch-8.16.0-SNAPSHOT.jar:?]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:984) ~[elasticsearch-8.16.0-SNAPSHOT.jar:?]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) ~[elasticsearch-8.16.0-SNAPSHOT.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1570) ~[?:?]
Caused by: java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "getClassLoader")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:488) ~[?:?]
	at java.security.AccessController.checkPermission(AccessController.java:1085) ~[?:?]
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:411) ~[?:?]
	at java.lang.ClassLoader.checkClassLoaderPermission(ClassLoader.java:2068) ~[?:?]
	at java.lang.Thread.getContextClassLoader(Thread.java:2312) ~[?:?]
	at io.netty.util.internal.PlatformDependent0$11.run(PlatformDependent0.java:948) ~[?:?]
	at io.netty.util.internal.PlatformDependent0$11.run(PlatformDependent0.java:945) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:319) ~[?:?]
	at io.netty.util.internal.PlatformDependent0.getContextClassLoader(PlatformDependent0.java:945) ~[?:?]
	at io.netty.util.internal.PlatformDependent.getContextClassLoader(PlatformDependent.java:1088) ~[?:?]
	at io.netty.util.Version.identify(Version.java:66) ~[?:?]
	at io.netty.util.Version.identify(Version.java:56) ~[?:?]
	at com.azure.core.http.netty.implementation.NettyUtility.validateNettyVersions(NettyUtility.java:106) ~[?:?]
	at com.azure.core.http.netty.implementation.NettyUtility.validateNettyVersions(NettyUtility.java:97) ~[?:?]
	at com.azure.core.http.netty.NettyAsyncHttpClientBuilder.<clinit>(NettyAsyncHttpClientBuilder.java:118) ~[?:?]
	... 20 more
```

***Code Snippet***

Hopefully clear from the stack trace above.

**Expected behavior**

If this logging-related action, I'd expect the application to carry on running. Possibly with a warning in the logs about the problem, but definitely not a fatal error.

**Setup (please complete the following information):**

 - OS: Mac OS Sonoma Version 14.6 (23G80) (but should reproduce anywhere)
 - IDE: IntelliJ (but also reproduces on the command line)
 - Library/Libraries: See https://github.com/elastic/elasticsearch/blob/cda877308cdb4e784a06fe282dedcf9833f909e8/modules/repository-azure/build.gradle#L27-L36 (most notably `com.azure:azure-core:1.50.0`)
 - Java version: `Oracle Corporation/OpenJDK 64-Bit Server VM/22.0.1/22.0.1+8-16`
 - App Server/Environment: None
 - Frameworks: None

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by alzimmermsft** [comment]
Thank you for reporting this @DaveCTurner.

I'll look into this further today to see what options we can provide to resolve this.
