### ISSUE TITLE
[BUG] Connection reset by Azure

### ISSUE THREAD

**Issue by snalli** [Azure/azure-sdk-for-java#41647]
**Describe the bug**
We are consistently seeing connection-reset errors from Azure SDK impacting our uploads to Azure

***Exception or Stack Trace***
Add the exception log and stack trace if available

2024/08/26 23:06:23.586 WARN [HttpClientConnect] [reactor-http-epoll-6] [ambry-vcr] [] [6aa3dc58-5554, L:/10.183.58.25:44730 - R:ambryprodmainbackupwus2.blob.core.windows.net/10.4.49.4:443] The connection observed an error, the request cannot be retried as the headers/body were sent
io.netty.channel.unix.Errors$NativeIoException: recvAddress(..) failed: Connection reset by peer

**To Reproduce**
None, happens no matter what we try

***Code Snippet***
Add the code snippet that causes the issue.
None, this is Azure SDK internal, not our application

**Expected behavior**
Expected behaviour is to not have connection resets

**Screenshots**

**Setup (please complete the following information):**
 - OS: [e.g. iOS] Linux/Mariner
 - IDE: [e.g. IntelliJ]
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)]
 - Java version: [e.g. 8] JDK-11_0_8-msft
 - App Server/Environment: [e.g. Tomcat, WildFly, Azure Function, Apache Spark, Databricks, IDE plugin or anything special]
 - Frameworks: [e.g. Spring Boot, Micronaut, Quarkus, etc] 

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x ] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by snalli** [comment]
```
2024/08/26 23:06:23.586 WARN [HttpClientConnect] [reactor-http-epoll-6] [ambry-vcr] [] [6aa3dc58-5554, L:/10.183.58.25:44730 - R:ambryprodmainbackupwus2.blob.core.windows.net/10.4.49.4:443] The connection observed an error, the request cannot be retried as the headers/body were sent
io.netty.channel.unix.Errors$NativeIoException: recvAddress(..) failed: Connection reset by peer
2024/08/26 23:06:23.638 WARN [HttpClientConnect] [reactor-http-epoll-28] [ambry-vcr] [] [85ecb0bc-1814, L:/10.183.58.25:56026 - R:ambryprodmainbackupwus2.blob.core.windows.net/10.4.49.4:443] The connection observed an error, the request cannot be retried as the headers/body were sent
io.netty.channel.unix.Errors$NativeIoException: recvAddress(..) failed: Connection reset by peer
2024/08/26 23:06:23.690 WARN [HttpClientConnect] [reactor-http-epoll-16] [ambry-vcr] [] [5dc5e28c-6459, L:/10.183.58.25:51920 - R:ambryprodmainbackupwus2.blob.core.windows.net/10.4.49.4:443] The connection observed an error, the request cannot be retried as the headers/body were sent
io.netty.channel.unix.Errors$NativeIoException: recvAddress(..) failed: Connection reset by peer
2024/08/26 23:06:23.770 WARN [HttpClientConnect] [reactor-http-epoll-33] [ambry-vcr] [] [d779f744-1939, L:/10.183.58.25:35598 - R:ambryprodmainbackupwus2.blob.core.windows.net/10.4.49.4:443] The connection observed an error, the request cannot be retried as the headers/body were sent
io.netty.channel.unix.Errors$NativeIoException: recvAddress(..) failed: Connection reset by peer
2024/08/26 23:06:23.878 WARN [HttpClientConnect] [reactor-http-epoll-29] [ambry-vcr] [] [c7f1791e-1840, L:/10.183.58.25:35570 - R:ambryprodmainbackupwus2.blob.core.windows.net/10.4.49.4:443] The connection observed an error, the request cannot be retried as the headers/body were sent
io.netty.channel.unix.Errors$NativeIoException: recvAddress(..) failed: Connection reset by peer
```

**Comment by snalli** [comment]
@alzimmermsft is there a way to print out the full http request/response when a conn-reset is encountered ?

**Comment by snalli** [comment]
@alzimmermsft IDK if a retry is happening as I have configured the azure-java-client to handle retries and it does not inform or log any retries. It only prints a failure - possibly after exhausting all retry attempts. How do I find out if retries are happening when a connection reset occurs ? Furthermore, what causes connection resets - azure machines restart, connection remains idle etc. ? How do we debug without a ton of logging ?

**Comment by snalli** [comment]
I have two suspicions 
1. Some timeout is kicking in causing the conn to terminate - either from our side or azure ?
2. We are streaming some content to azure that we receive from another machine. Perhaps we could buffer the content in-memory before sending it out to Azure.

**Comment by snalli** [comment]
Option 2 has not worked. 
So for Option 1 - is there a timeout kicking that I can change ?

**Comment by alzimmermsft** [comment]
> It does lead to errors like this :
> 
> ```
> 2024/08/27 19:46:52.540 WARN [HttpClientConnect] [reactor-http-epoll-31] [ambry-vcr] [] [5ea72d6b-505, L:/10.183.58.25:46036 - R:ambryprodmainbackupwus2.table.core.windows.net/10.4.49.5:443] The connection observed an error, the request cannot be retried as the headers/body were sent
> io.netty.channel.unix.Errors$NativeIoException: recvAddress(..) failed: Connection reset by peer
> 2024/08/27 19:46:52.540 ERROR [NettyAsyncHttpClient] [VcrReplicaThread-Intra-401-prod-lor1] [ambry-vcr] [] io.netty.channel.unix.Errors$NativeIoException: recvAddress(..) failed: Connection reset by peer
> 2024/08/27 19:48:47.795 WARN [HttpClientConnect] [reactor-http-epoll-26] [ambry-vcr] [] [4d07a6f2-587, L:/10.183.58.25:45974 - R:ambryprodmainbackupwus2.table.core.windows.net/10.4.49.5:443] The connection observed an error
> java.util.concurrent.TimeoutException: Channel response timed out after 60000 milliseconds.
>         at com.azure.core.http.netty.implementation.AzureSdkHandler.responseTimedOut(AzureSdkHandler.java:200) ~[com.azure.azure-core-http-netty-1.13.7.jar:1.13.7]
>         at com.azure.core.http.netty.implementation.AzureSdkHandler.lambda$startResponseTracking$2(AzureSdkHandler.java:184) ~[com.azure.azure-core-http-netty-1.13.7.jar:1.13.7]
>         at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) [io.netty.netty-common-4.1.94.Final.jar:4.1.94.Final]
>         at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153) [io.netty.netty-common-4.1.94.Final.jar:4.1.94.Final]
>         at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) [io.netty.netty-common-4.1.94.Final.jar:4.1.94.Final]
>         at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) [io.netty.netty-common-4.1.94.Final.jar:4.1.94.Final]
>         at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) [io.netty.netty-common-4.1.94.Final.jar:4.1.94.Final]
>         at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:406) [io.netty.netty-transport-classes-epoll-4.1.94.Final.jar:4.1.94.Final]
>         at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [io.netty.netty-common-4.1.94.Final.jar:4.1.94.Final]
>         at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [io.netty.netty-common-4.1.94.Final.jar:4.1.94.Final]
>         at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty.netty-common-4.1.94.Final.jar:4.1.94.Final]
>         at java.lang.Thread.run(Thread.java:834) [?:?]
> ```

This is a client-side timeout happening. By default, we configure our HTTP clients to timeout after 60 seconds of inactivity on a request or response. This is a request timeout indicating that no bytes were written to the network request for 60 seconds, more information about these timeouts can be seen here:

https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/core/azure-core#http-timeouts

And that includes how you can configure these timeouts with both environment configuration changes and code changes.

This still doesn't answer the issue on the connection being reset being reset by the remote peer. If this is still something that can happen consistently it may be useful to get a Wireshark capture of the network traffic for these requests when the exception happens. Additionally, if an `x-ms-client-request-id` can be captured for the request that fails it may be possible to track that to what is happening.

**Comment by snalli** [comment]
Hmm ok, will try wireshark

**Comment by ibrahimrabab** [comment]
Hi @snalli 
Is this still an issue? If not, we can go ahead and close this.

**Comment by snalli** [comment]
Yes this is still an issue

**Comment by ibrahimrabab** [comment]
@snalli 
Can you please provide us a code snippet of how you're producing this connection reset? Also, have you tried adding additional logging as mentioned by @alzimmermsft ? 

Also, would you be able to provide x-ms-client-request-id from your logs, so that we may investigate on our end to see if it's related to a service issue? Thanks!

**Comment by snalli** [comment]
Too late a reply, I no longer work on this.
