### ISSUE TITLE
[QUERY] DefaultAzureCredential authentication failed. ---> IntelliJCredential authentication failed 

### ISSUE THREAD

**Issue by jdwilkin** [Azure/azure-sdk-for-java#41722]
**Query/Question**
How do I refresh an expired (due to inactivity) IntellijCredential token

***Why is this not a Bug or a feature Request?***
I think the DefaultAzureCredential class is doing the right thing by going through its chained token credentials and stopping when it finds one for Intellij (I logged out of the intellij azure plugin, so not sure why it is still finding that credential), but the cached credential refresh token apparently has expired and thus I am unable to authenticate to azure in my local environment.

here is the log output:

[2024-09-04T19:37:59.025Z] 2024-09-04 14:37:59.024  INFO 57712 --- [pool-2-thread-1] c.azure.identity.ChainedTokenCredential  : Azure Identity => Attempted credential EnvironmentCredential is unavailable.
[2024-09-04T19:37:59.025Z] 2024-09-04 14:37:59.024 ERROR 57712 --- [pool-2-thread-1] c.a.identity.WorkloadIdentityCredential  : WorkloadIdentityCredential authentication unavailable. The workload options are not fully configured. See the troubleshooting guide for more information. https://aka.ms/azsdk/java/identity/workloadidentitycredential/troubleshoot
[2024-09-04T19:37:59.026Z] 2024-09-04 14:37:59.024  INFO 57712 --- [pool-2-thread-1] c.azure.identity.ChainedTokenCredential  : Azure Identity => Attempted credential WorkloadIdentityCredential is unavailable.
[2024-09-04T19:38:00.221Z] 2024-09-04 14:38:00.220  INFO 57712 --- [onPool-worker-9] c.azure.identity.ChainedTokenCredential  : Azure Identity => Attempted credential ManagedIdentityCredential is unavailable.
[2024-09-04T19:38:00.236Z] 2024-09-04 14:38:00.235  INFO 57712 --- [onPool-worker-9] c.azure.identity.ChainedTokenCredential  : Azure Identity => Attempted credential SharedTokenCacheCredential is unavailable.
[2024-09-04T19:38:01.804Z] 2024-09-04 14:38:01.803 ERROR 57712 --- [onPool-worker-2] c.m.aad.msal4j.PublicClientApplication   : [Correlation ID: bd3e4f78-f210-4d98-9ffe-08aefc299c9f] Execution of class com.microsoft.aad.msal4j.AcquireTokenByAuthorizationGrantSupplier failed.
[2024-09-04T19:38:01.805Z] com.microsoft.aad.msal4j.MsalInteractionRequiredException: AADSTS700082: The refresh token has expired due to inactivity. The token was issued on 2023-12-13T15:14:36.4743228Z and was inactive for 90.00:00:00. Trace ID: 9218d31f-61ae-4ac8-a304-8bb88baed700 Correlation ID: bd3e4f78-f210-4d98-9ffe-08aefc299c9f Timestamp: 2024-09-04 19:38:02Z
[2024-09-04T19:38:01.805Z] 	at com.microsoft.aad.msal4j.MsalServiceExceptionFactory.fromHttpResponse(MsalServiceExceptionFactory.java:39) ~[msal4j-1.13.8.jar:1.13.8]
[2024-09-04T19:38:01.805Z] 	at com.microsoft.aad.msal4j.TokenRequestExecutor.createAuthenticationResultFromOauthHttpResponse(TokenRequestExecutor.java:111) ~[msal4j-1.13.8.jar:1.13.8]
[2024-09-04T19:38:01.805Z] 	at com.microsoft.aad.msal4j.TokenRequestExecutor.executeTokenRequest(TokenRequestExecutor.java:34) ~[msal4j-1.13.8.jar:1.13.8]
[2024-09-04T19:38:01.806Z] 	at com.microsoft.aad.msal4j.AbstractClientApplicationBase.acquireTokenCommon(AbstractClientApplicationBase.java:129) ~[msal4j-1.13.8.jar:1.13.8]
[2024-09-04T19:38:01.806Z] 	at com.microsoft.aad.msal4j.AcquireTokenByAuthorizationGrantSupplier.execute(AcquireTokenByAuthorizationGrantSupplier.java:63) ~[msal4j-1.13.8.jar:1.13.8]
[2024-09-04T19:38:01.806Z] 	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:69) [msal4j-1.13.8.jar:1.13.8]
[2024-09-04T19:38:01.806Z] 	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:18) [msal4j-1.13.8.jar:1.13.8]
[2024-09-04T19:38:01.807Z] 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604) [na:1.8.0_251]
[2024-09-04T19:38:01.807Z] 	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596) [na:1.8.0_251]
[2024-09-04T19:38:01.807Z] 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [na:1.8.0_251]
[2024-09-04T19:38:01.807Z] 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [na:1.8.0_251]
[2024-09-04T19:38:01.807Z] 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [na:1.8.0_251]
[2024-09-04T19:38:01.807Z] 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [na:1.8.0_251]
[2024-09-04T19:38:01.808Z] 2024-09-04 14:38:01.804 ERROR 57712 --- [onPool-worker-2] c.a.c.implementation.AccessTokenCache    : {"az.sdk.message":"Failed to acquire a new access token.","exception":"DefaultAzureCredential authentication failed. ---> IntelliJCredential authentication failed. Error Details: AADSTS700082: The refresh token has expired due to inactivity. The token was issued on 2023-12-13T15:14:36.4743228Z and was inactive for 90.00:00:00. Trace ID: 9218d31f-61ae-4ac8-a304-8bb88baed700 Correlation ID: bd3e4f78-f210-4d98-9ffe-08aefc299c9f Timestamp: 2024-09-04 19:38:02Z"}
[2024-09-04T19:38:01.808Z] DefaultAzureCredential authentication failed. ---> IntelliJCredential authentication failed. Error Details: AADSTS700082: The refresh token has expired due to inactivity.ÿThe token was issued on 2023-12-13T15:14:36.4743228Z and was inactive for 90.00:00:00. Trace ID: 9218d31f-61ae-4ac8-a304-8bb88baed700 Correlation ID: bd3e4f78-f210-4d98-9ffe-08aefc299c9f Timestamp: 2024-09-04 19:38:02Z

**Setup (please complete the following information if applicable):**
 - OS: Windows 10
 - IDE: Intellij
 - Library/Libraries: com.azure:azure-core:1.40.0
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Query Added
- [ ] Setup information Added

**Comment by billwert** [comment]
Hello! I will take a look at this. In the short term you can work around this issue by deleting the `azure-toolkit.cache` (or `azure-toolkit.cache.nocae`) file under `%localappdata%\.IdentityService`. That will invalidate the cache and authentication with `DefaultAzureCredential` should proceed.

**Comment by jdwilkin** [comment]
Thanks Bill for your quick response...  upon removing that file it seems it is no longer trying to use the intellij cached credential, however I now have a new error:
{"az.sdk.message":"Failed to acquire a new access token.","exception":"DefaultAzureCredential authentication failed. ---> AzureCliCredential authentication failed. Error Details: com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'Argument': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')\n at [Source: (String)\"Argument '--tenant' is in preview. It may be changed/removed in a future release.

It seems it is trying  to use AzureCLI (of which I am logged in).  Incidentally I also logged out/in to the IntelliJ plugin after removing that cache file and whether logged in or not I get the same error above, thanks for your help (This has worked without issue for years, but I don't debug it often so first time probably in 2024 that I have tried this)

**Comment by billwert** [comment]
Can you tell me a few things?

1) What version of azure-identity are you on?
2) what version of `az` are you on? `az version`
3) What is the output _before_ the block of json that `az account get-access-token` prints? Do **not** share the actual JSON output - I don't need it and it'll have an access token in it. :)

**Comment by jdwilkin** [comment]
after I posted my last update I went and updated azure-sdk-bom from 1.2.14 to 1.2.24 (the highest for my current version of spring boot) and Azure Identity was then able to successfully get a token from AzureCliCredential.  I am still confused why IntelliJCredential doesn't work even though the plugin is logged in, but for now I am in business with cli!

I will still answer you questions for your reference, but it seems the old version from the old bom was the problem:

1.  whatever was included in 1.2.14 of azure-sdk-bom
2. "azure-cli": "2.7.0",
3.  there isn't anything before the block of json that is printed however looking at the error it appears whatever the old version of azure-identity was calling was causing "Argument '--tenant' is in preview. It may be changed/removed in a future release." to be returned

**Comment by billwert** [comment]
Awesome! The `IntelliJCredential` has another issue I am actively working on fixing actually, so you might be hitting that. That fix will likely ship the first week of October.

I'm going to close this issue as I think we have resolved all the questions. Let me know if you need anything else!

**Comment by billwert** [comment]
Hey @jdwilkin! Can you please try this with `1.14.0-beta.2` of `azure-identity` as well as latest Azure Toolkit? We'll GA the fix next month, and I'd appreciate it if you can give it a quick try before we do so in case there is any other issue. Thanks!
