### ISSUE TITLE
[BUG] Initialize Cosmos client failed in Scala Spark environment via `CosmosClientBuilder` but succeeded with `CosmosAsyncClientCache`

### ISSUE THREAD

**Issue by mickjermsurawong-openai** [Azure/azure-sdk-for-java#41829]
**Describe the bug**

- In Spark environment (eg. databricks notebook), initializing Cosmos client
  - failed when using `CosmosClientBuilder` failed with `io.netty.channel.StacklessClosedChannelException`
  - succeeded when using `cosmos.spark.udf.CosmosAsyncClientCache`

***Exception or Stack Trace***

- The error message:
```
RuntimeException: Client initialization failed. Check if the endpoint is reachable and if your auth token is valid. ...
"statusCode":503,"subStatusCode":10001,
``` 
with stacktrace
```
	at com.azure.cosmos.BridgeInternal.createCosmosException(BridgeInternal.java:416)
	at com.azure.cosmos.implementation.RxGatewayStoreModel.lambda$toDocumentServiceResponse$4(RxGatewayStoreModel.java:449)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onError(FluxMapFuseable.java:142)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:172)
	at reactor.core.publisher.MonoSingle$SingleSubscriber.onError(MonoSingle.java:150)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:106)
	at reactor.core.publisher.Operators.error(Operators.java:198)
	at reactor.core.publisher.MonoError.subscribe(MonoError.java:53)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4491)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onError(FluxPeekFuseable.java:234)
	at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onError(FluxContextWrite.java:121)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onError(MonoFlatMapMany.java:204)
	at reactor.core.publisher.SerializedSubscriber.onError(SerializedSubscriber.java:124)
	at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.whenError(FluxRetryWhen.java:225)
	at reactor.core.publisher.FluxRetryWhen$RetryWhenOtherSubscriber.onError(FluxRetryWhen.java:274)
	at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onError(FluxContextWrite.java:121)
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:415)
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onNext(FluxConcatMap.java:251)
	at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107)
	at reactor.core.publisher.EmitterProcessor.drain(EmitterProcessor.java:537)
	at reactor.core.publisher.EmitterProcessor.tryEmitNext(EmitterProcessor.java:343)
	at reactor.core.publisher.SinkManySerialized.tryEmitNext(SinkManySerialized.java:100)
	at reactor.core.publisher.InternalManySink.emitNext(InternalManySink.java:27)
	at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.onError(FluxRetryWhen.java:190)
	at reactor.core.publisher.MonoCreate$DefaultMonoSink.error(MonoCreate.java:201)
	at reactor.netty.http.client.HttpClientConnect$MonoHttpConnect$ClientTransportSubscriber.onError(HttpClientConnect.java:311)
	at reactor.core.publisher.MonoCreate$DefaultMonoSink.error(MonoCreate.java:201)
	at reactor.netty.resources.DefaultPooledConnectionProvider$DisposableAcquire.onError(DefaultPooledConnectionProvider.java:160)
	at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onError(FluxContextWrite.java:121)
	at reactor.netty.internal.shaded.reactor.pool.AbstractPool$Borrower.fail(AbstractPool.java:475)
	at reactor.netty.internal.shaded.reactor.pool.SimpleDequePool.lambda$drainLoop$9(SimpleDequePool.java:431)
	at reactor.core.publisher.FluxDoOnEach$DoOnEachSubscriber.onError(FluxDoOnEach.java:186)
	at reactor.core.publisher.MonoCreate$DefaultMonoSink.error(MonoCreate.java:201)
	at reactor.netty.resources.DefaultPooledConnectionProvider$PooledConnectionAllocator$PooledConnectionInitializer.onError(DefaultPooledConnectionProvider.java:558)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondError(MonoFlatMap.java:192)
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onError(MonoFlatMap.java:259)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:106)
	at reactor.core.publisher.Operators.error(Operators.java:198)
	at reactor.core.publisher.MonoError.subscribe(MonoError.java:53)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4491)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103)
	at reactor.netty.transport.TransportConnector$MonoChannelPromise.tryFailure(TransportConnector.java:569)
	at reactor.netty.transport.TransportConnector$MonoChannelPromise.setFailure(TransportConnector.java:515)
	at reactor.netty.transport.TransportConnector.lambda$doConnect$7(TransportConnector.java:261)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:557)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492)
	at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:185)
	at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:95)
	at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:30)
	at reactor.netty.transport.TransportConnector.lambda$doConnect$8(TransportConnector.java:246)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: io.netty.channel.StacklessClosedChannelException
	at io.netty.channel.AbstractChannel$AbstractUnsafe.ensureOpen(ChannelPromise)(Unknown Source)
```

**To Reproduce**

```
import com.azure.cosmos.CosmosClientBuilder
val endpoint = "xxx:443"
val secretValue = "yyy"

// failed
val client = new CosmosClientBuilder().endpoint(endpoint).key(secretValue).buildAsyncClient()

// succeeded
import com.azure.cosmos.spark.udf.CosmosAsyncClientCache
import azure_cosmos_spark.com.azure.cosmos.CosmosAsyncClient

val cache = CosmosAsyncClientCache.getCosmosClientFromCache(Map(
  "spark.cosmos.accountEndpoint" -> endpoint,
  "spark.cosmos.accountKey" -> secretValue,
  "spark.cosmos.database" -> "xx",
  "spark.cosmos.container" -> "xx"))  
val client = cache.getClient.asInstanceOf[CosmosAsyncClient]
```

**Expected behavior**

- Standard initialization should succeed without the need to use Spark udf package

**Setup (please complete the following information):**

- Databricks runtime `14.3 LTS (includes Apache Spark 3.5.0, Scala 2.12)`
- `com.azure.cosmos.spark:azure-cosmos-spark_3-4_2-12:4.33.1`
- `com.azure:azure-cosmos:4.63.3`

**Additional context**
- There are a few spark-specific configurations to review.
  - I checked this, and repro in my env, but error still persisted
https://github.com/Azure/azure-sdk-for-java/blob/ac9ee6330b688f1b3eeea77548f1897be25782da/sdk/cosmos/azure-cosmos-spark_3_2-12/src/main/scala/com/azure/cosmos/spark/CosmosClientCache.scala#L38

  - Then there is this, which is highly suspicious for netty.io issue. I couldn't repro because setting thread is private package.
https://github.com/Azure/azure-sdk-for-java/blob/ac9ee6330b688f1b3eeea77548f1897be25782da/sdk/cosmos/azure-cosmos-spark_3_2-12/src/main/scala/com/azure/cosmos/spark/CosmosClientCache.scala#L326-L334

- Confirmed that connectivity isn't a problem as `telnet endpoint 443` succeeded in this Spark environment
- Confirmed that using python sdk in the same environment also succeeded
```
from azure.cosmos import CosmosClient
client = CosmosClient(endpoint, credential=secret)
```

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by kushagraThapar** [comment]
@mickjermsurawong-openai looks like this has been responded offline. Is there any follow up to this?

**Comment by FabianMeiswinkel** [comment]
The reason for the error above, are incompatibilities between the Netty/Jackson/Reactor versions provided/used by Spark and the ones used in azure-core. The usual way how to deal with those in Spark is to use shading - to allow two not necessarily binary compatible versions of netty/reactor etc. to be used concurrently. Our Spark connector azure-cosmos-spark is doing that - we shade these dependencies to make them work across all LTS Spark runtime versions (all minor Spark versions for which either Azure Databricks or Azure Synapse still have an LTS runtime). Using the CosmosClientCache API above allows using the shaded CosmosClient that works in Spark.
If you want to avoid using the azure-cosmos-spark package altogether and use the azure-cosmos package directly you will have to do similar shading like we do in our azure-cosmos-spark-* packages.
