### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by wesleyjpn** [Azure/azure-sdk-for-java#41888]
I am using databricks with the latest version of azure cosmos sdk but seems to have this issue when i am trying to push into adls one of my collection from cosmosdb. Using changefeed method.

Following the message issue

java.lang.NullPointerException
	at java.util.LinkedList$ListItr.next(LinkedList.java:893)
	at azure_cosmos_spark.com.azure.cosmos.implementation.feedranges.FeedRangeCompositeContinuationImpl.populatePropertyBag(FeedRangeCompositeContinuationImpl.java:113)
	at azure_cosmos_spark.com.azure.cosmos.implementation.changefeed.common.ChangeFeedStateV1.populatePropertyBag(ChangeFeedStateV1.java:162)
	at azure_cosmos_spark.com.azure.cosmos.implementation.JsonSerializable.toJson(JsonSerializable.java:814)
	at azure_cosmos_spark.com.azure.cosmos.implementation.JsonSerializable.toJson(JsonSerializable.java:804)
	at azure_cosmos_spark.com.azure.cosmos.implementation.changefeed.common.ChangeFeedState.toString(ChangeFeedState.java:81)
	at azure_cosmos_spark.com.azure.cosmos.implementation.changefeed.common.ChangeFeedStateV1.applyServerResponseContinuation(ChangeFeedStateV1.java:90)
	at azure_cosmos_spark.com.azure.cosmos.implementation.query.ChangeFeedFetcher.applyServerResponseContinuation(ChangeFeedFetcher.java:164)
	at azure_cosmos_spark.com.azure.cosmos.implementation.query.Fetcher.updateState(Fetcher.java:111)
	at azure_cosmos_spark.com.azure.cosmos.implementation.query.Fetcher.lambda$nextPage$3(Fetcher.java:169)
	at azure_cosmos_spark.reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.onNext(FluxMapFuseable.java:283)
	at azure_cosmos_spark.reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.onNext(FluxMapFuseable.java:299)
	at azure_cosmos_spark.reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1839)
	at azure_cosmos_spark.reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:249)
	at azure_cosmos_spark.reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1839)
	at azure_cosmos_spark.reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151)
	at azure_cosmos_spark.reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:180)
	at azure_cosmos_spark.reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
	at azure_cosmos_spark.reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1839)
	at azure_cosmos_spark.reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151)
	at azure_cosmos_spark.reactor.core.publisher.Operators$MonoInnerProducerBase.complete(Operators.java:2666)
	at azure_cosmos_spark.reactor.core.publisher.MonoSingle$SingleSubscriber.onComplete(MonoSingle.java:180)
	at azure_cosmos_spark.reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onComplete(FluxPeekFuseable.java:277)
	at azure_cosmos_spark.reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1840)
	at azure_cosmos_spark.reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151)
	at azure_cosmos_spark.reactor.core.publisher.Operators$MonoInnerProducerBase.complete(Operators.java:2666)
	at azure_cosmos_spark.reactor.core.publisher.MonoSingle$SingleSubscriber.onComplete(MonoSingle.java:180)
	at azure_cosmos_spark.reactor.core.publisher.FluxFlatMap$FlatMapMain.checkTerminated(FluxFlatMap.java:847)
	at azure_cosmos_spark.reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:609)
	at azure_cosmos_spark.reactor.core.publisher.FluxFlatMap$FlatMapMain.innerComplete(FluxFlatMap.java:895)
	at azure_cosmos_spark.reactor.core.publisher.FluxFlatMap$FlatMapInner.onComplete(FluxFlatMap.java:998)
	at azure_cosmos_spark.reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FluxSwitchIfEmpty.java:85)
	at azure_cosmos_spark.reactor.core.publisher.FluxConcatArray$ConcatArraySubscriber.onComplete(FluxConcatArray.java:208)
	at azure_cosmos_spark.reactor.core.publisher.MonoIgnoreElements$IgnoreElementsSubscriber.onComplete(MonoIgnoreElements.java:89)
	at azure_cosmos_spark.reactor.core.publisher.FluxTakeUntil$TakeUntilPredicateSubscriber.onComplete(FluxTakeUntil.java:121)
	at azure_cosmos_spark.reactor.core.publisher.FluxTakeUntil$TakeUntilPredicateSubscriber.onNext(FluxTakeUntil.java:99)
	at azure_cosmos_spark.reactor.core.publisher.FluxRepeatPredicate$RepeatPredicateSubscriber.onNext(FluxRepeatPredicate.java:86)
	at azure_cosmos_spark.reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:113)
	at azure_cosmos_spark.reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:122)
	at azure_cosmos_spark.reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
	at azure_cosmos_spark.reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1839)
	at azure_cosmos_spark.reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:129)
	at azure_cosmos_spark.reactor.core.publisher.FluxFlatMap$FlatMapMain.checkTerminated(FluxFlatMap.java:847)
	at azure_cosmos_spark.reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:609)
	at azure_cosmos_spark.reactor.core.publisher.FluxFlatMap$FlatMapMain.innerComplete(FluxFlatMap.java:895)
	at azure_cosmos_spark.reactor.core.publisher.FluxFlatMap$FlatMapInner.onComplete(FluxFlatMap.java:998)
	at azure_cosmos_spark.reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onComplete(Operators.java:2060)
	at azure_cosmos_spark.reactor.core.publisher.FluxFlatMap$FlatMapMain.checkTerminated(FluxFlatMap.java:847)
	at azure_cosmos_spark.reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:609)
	at azure_cosmos_spark.reactor.core.publisher.FluxFlatMap$FlatMapMain.drain(FluxFlatMap.java:589)
	at azure_cosmos_spark.reactor.core.publisher.FluxFlatMap$FlatMapMain.onComplete(FluxFlatMap.java:466)
	at azure_cosmos_spark.reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onComplete(Operators.java:2060)
	at azure_cosmos_spark.reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1840)
	at azure_cosmos_spark.reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:249)
	at azure_cosmos_spark.reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:180)
	at azure_cosmos_spark.reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1839)
	at azure_cosmos_spark.reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:249)
	at azure_cosmos_spark.reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1839)
	at azure_cosmos_spark.reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:249)
	at azure_cosmos_spark.reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:180)
	at azure_cosmos_spark.reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:180)
	at azure_cosmos_spark.reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:180)
	at azure_cosmos_spark.reactor.core.publisher.MonoPublishOn$PublishOnSubscriber.run(MonoPublishOn.java:181)
	at azure_cosmos_spark.reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at azure_cosmos_spark.reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

**Comment by kushagraThapar** [comment]
@wesleyjpn can you please provide the exact versions of azure-cosmos-spark and databricks being used?

**Comment by kushagraThapar** [comment]
@wesleyjpn I tried looking at the stack trace, and can't think of a reason causing this issue. I  am curious if you can provide any further details on this? Do you see the continuation token being logged? Can you share the driver / executor logs hoping they might contain some more information.

**Comment by wesleyjpn** [comment]
Yes,
This is part of the code i have in databricks: For the most collections i have its working fine, only for a few its not working.



import delta
from pyspark.sql.functions import lit, date_format, col, to_timestamp, from_json, coalesce, count
from pyspark.sql import SparkSession
from delta.tables import *
from pyspark.sql.window import Window

# Initialize SparkSession
spark = SparkSession.builder.appName("xxxx").getOrCreate()

logger = LoggingConsole(component='xxxxxxx')

# Configure Spark settings
spark.conf.set("spark.streaming.stopGracefullyOnShutdown", "true")
spark.conf.set("spark.sql.adaptive.skewJoin.enabled", "true")
spark.conf.set("spark.sql.shuffle.partitions", 400)

# Cosmos DB Change Feed configuration
cosmos_change_feed_config = {
    "spark.cosmos.accountEndpoint": xxxxxxx,
    "spark.cosmos.accountKey": xxxxxx,
    "spark.cosmos.database": xxxxxx,
    "spark.cosmos.container": xxxxxx,
    "spark.cosmos.read.partitioning.strategy": "Default",
    #"spark.cosmos.read.partitioning.strategy": "Restrictive",
    "spark.cosmos.read.inferSchema.enabled": "false",
    "spark.cosmos.changeFeed.startFrom": startFrom_param,
    "spark.cosmos.changeFeed.mode": "Incremental",
    "spark.cosmos.changeFeed.itemCountPerTriggerHint": itemCountPerTriggerHint_config_param,
    "spark.cosmos.read.maxItemCount": maxItemCount_config_param,
    "spark.cosmos.throughputControl.enabled": "true",
    "spark.cosmos.throughputControl.targetThroughputThreshold": targetThroughputThreshold_config_param,
    "spark.cosmos.throughputControl.name": "xxxxxx",
    "spark.cosmos.throughputControl.globalControl.database": database,
    "spark.cosmos.throughputControl.globalControl.container": "xxxxx",
    "spark.cosmos.preferredRegionsList": cosmos_db_region
}

print(cosmos_change_feed_config)

# Load Change Feed data
df_change_feed = spark.readStream.format("cosmos.oltp.changeFeed").options(**cosmos_change_feed_config).load()

def get_partition_key(df, column_key):
    df = df.withColumn("id", expr("get_json_object(_rawBody, '$.id')"))
    if column_key:
        df = df.withColumn(column_key, expr(f"get_json_object(_rawBody, '$.{column_key}')") )

    return df

def merge_delta(incremental, target, batch_id, condition_key="i.id = t.id and i.partition_key = t.partition_key", column_key=''):

    first_row = incremental.head(1)
    if first_row:
        incremental = incremental.withColumn("date_partition", date_format(to_timestamp(col("_ts")), "yyyyMMdd").cast("Integer"))
        if column_key:
            incremental = get_partition_key(incremental, column_key)

        incremental = incremental.withColumn("id", coalesce("id",lit('')))

        if column_key:
            incremental = incremental.withColumn(f"{column_key}", coalesce(col(f"{column_key}"),lit('')))

        row_sample = incremental.head(1)
        first_row_str = str(row_sample[0])
        logger.log_info(f"First row in incremental DataFrame Sample: {first_row_str}")

        incremental.createOrReplaceTempView("incremental")
        num_partitions = incremental.rdd.getNumPartitions()
        print(f"Number of partitions: {num_partitions}")

        try:
            incremental._jdf.sparkSession().sql(f"""
            MERGE INTO {target} t
            USING incremental i
            ON {condition_key}
            WHEN MATCHED THEN UPDATE SET *
            WHEN NOT MATCHED THEN INSERT *
            """)

        except Exception as e:
             logger.error(f"Error processing batch {batch_id}: {str(e)}")
             raise e




And this is the log i am getting inside driver:

java.lang.NullPointerException at java.util.LinkedList$ListItr.next(LinkedList.java:893) at azure_cosmos_spark.com.azure.cosmos.implementation.feedranges.FeedRangeCompositeContinuationImpl.populatePropertyBag(FeedRangeCompositeContinuationImpl.java:113) at azure_cosmos_spark.com.azure.cosmos.implementation.changefeed.common.ChangeFeedStateV1.populatePropertyBag(ChangeFeedStateV1.java:162) at azure_cosmos_spark.com.azure.cosmos.implementation.JsonSerializable.toJson(JsonSerializable.java:814) at azure_cosmos_spark.com.azure.cosmos.implementation.JsonSerializable.toJson(JsonSerializable.java:804) at azure_cosmos_spark.com.azure.cosmos.implementation.changefeed.common.ChangeFeedState.toString(ChangeFeedState.java:81) at azure_cosmos_spark.com.azure.cosmos.implementation.changefeed.common.ChangeFeedStateV1.applyServerResponseContinuation(ChangeFeedStateV1.java:90) at azure_cosmos_spark.com.azure.cosmos.implementation.query.ChangeFeedFetcher.applyServerResponseContinuation(ChangeFeedFetcher.java:164) at azure_cosmos_spark.com.azure.cosmos.implementation.query.Fetcher.updateState(Fetcher.java:111) at azure_cosmos_spark.com.azure.cosmos.implementation.query.Fetcher.lambda$nextPage$3(Fetcher.java:169) at azure_cosmos_spark.reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.onNext(FluxMapFuseable.java:283) at azure_cosmos_spark.reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.onNext(FluxMapFuseable.java:299) at azure_cosmos_spark.reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1839) at azure_cosmos_spark.reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:249) at azure_cosmos_spark.reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1839) at azure_cosmos_spark.reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151) at azure_cosmos_spark.reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:180) at azure_cosmos_spark.reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79) at azure_cosmos_spark.reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1839) at azure_cosmos_spark.reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151) at azure_cosmos_spark.reactor.core.publisher.Operators$MonoInnerProducerBase.complete(Operators.java:2666) at azure_cosmos_spark.reactor.core.publisher.MonoSingle$SingleSubscriber.onComplete(MonoSingle.java:180) at azure_cosmos_spark.reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onComplete(FluxPeekFuseable.java:277) at azure_cosmos_spark.reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1840) at azure_cosmos_spark.reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151) at azure_cosmos_spark.reactor.core.publisher.Operators$MonoInnerProducerBase.complete(Operators.java:2666) at azure_cosmos_spark.reactor.core.publisher.MonoSingle$SingleSubscriber.onComplete(MonoSingle.java:180) at azure_cosmos_spark.reactor.core.publisher.FluxFlatMap$FlatMapMain.checkTerminated(FluxFlatMap.java:847) at azure_cosmos_spark.reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:609) at azure_cosmos_spark.reactor.core.publisher.FluxFlatMap$FlatMapMain.innerComplete(FluxFlatMap.java:895) at azure_cosmos_spark.reactor.core.publisher.FluxFlatMap$FlatMapInner.onComplete(FluxFlatMap.java:998) at azure_cosmos_spark.reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FluxSwitchIfEmpty.java:85) at azure_cosmos_spark.reactor.core.publisher.FluxConcatArray$ConcatArraySubscriber.onComplete(FluxConcatArray.java:208) at azure_cosmos_spark.reactor.core.publisher.MonoIgnoreElements$IgnoreElementsSubscriber.onComplete(MonoIgnoreElements.java:89) at azure_cosmos_spark.reactor.core.publisher.FluxTakeUntil$TakeUntilPredicateSubscriber.onComplete(FluxTakeUntil.java:121) at azure_cosmos_spark.reactor.core.publisher.FluxTakeUntil$TakeUntilPredicateSubscriber.onNext(FluxTakeUntil.java:99) at azure_cosmos_spark.reactor.core.publisher.FluxRepeatPredicate$RepeatPredicateSubscriber.onNext(FluxRepeatPredicate.java:86) at azure_cosmos_spark.reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:113) at azure_cosmos_spark.reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:122) at azure_cosmos_spark.reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79) at azure_cosmos_spark.reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1839) at azure_cosmos_spark.reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:129) at azure_cosmos_spark.reactor.core.publisher.FluxFlatMap$FlatMapMain.checkTerminated(FluxFlatMap.java:847) at azure_cosmos_spark.reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:609) at azure_cosmos_spark.reactor.core.publisher.FluxFlatMap$FlatMapMain.innerComplete(FluxFlatMap.java:895) at azure_cosmos_spark.reactor.core.publisher.FluxFlatMap$FlatMapInner.onComplete(FluxFlatMap.java:998) at azure_cosmos_spark.reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onComplete(Operators.java:2060) at azure_cosmos_spark.reactor.core.publisher.FluxFlatMap$FlatMapMain.checkTerminated(FluxFlatMap.java:847) at azure_cosmos_spark.reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:609) at azure_cosmos_spark.reactor.core.publisher.FluxFlatMap$FlatMapMain.drain(FluxFlatMap.java:589) at azure_cosmos_spark.reactor.core.publisher.FluxFlatMap$FlatMapMain.onComplete(FluxFlatMap.java:466) at azure_cosmos_spark.reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onComplete(Operators.java:2060) at azure_cosmos_spark.reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1840) at azure_cosmos_spark.reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:249) at azure_cosmos_spark.reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:180) at azure_cosmos_spark.reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1839) at azure_cosmos_spark.reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:249) at azure_cosmos_spark.reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1839) at azure_cosmos_spark.reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:249) at azure_cosmos_spark.reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:180) at azure_cosmos_spark.reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:180) at azure_cosmos_spark.reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:180) at azure_cosmos_spark.reactor.core.publisher.MonoPublishOn$PublishOnSubscriber.run(MonoPublishOn.java:181) at azure_cosmos_spark.reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68) at azure_cosmos_spark.reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

________________________________
De: Kushagra Thapar ***@***.***>
Enviado: quarta-feira, 25 de setembro de 2024 15:53
Para: Azure/azure-sdk-for-java ***@***.***>
Cc: Wesley Shimabukuro ***@***.***>; Mention ***@***.***>
Assunto: Re: [Azure/azure-sdk-for-java] NullPointerException (Issue #41888)


@wesleyjpn<https://github.com/wesleyjpn> I tried looking at the stack trace, and can't think of a reason causing this issue. I am curious if you can provide any further details on this? Do you see the continuation token being logged? Can you share the driver / executor logs hoping they might contain some more information.

**Comment by kushagraThapar** [comment]
@tvaron3 can you please take a look at this?

**Comment by tvaron3** [comment]
@wesleyjpn for the containers where this happens, does the null pointer exception happen every time or just sometimes? Is it easily reproducible?
