### ISSUE TITLE
[BUG] io.netty.channel.ConnectTimeoutException after one minute of running

### ISSUE THREAD

**Issue by greatvovan** [Azure/azure-sdk-for-java#41929]
**Describe the bug**
An error message in the log output.

***Exception or Stack Trace***
_[AzureMetadataService-0] ERROR com.azure.core.http.netty.NettyAsyncHttpClient - io.netty.channel.ConnectTimeoutException: connection timed out after 10000 ms: /169.254.169.254:80_
No stack trace is printed.

**To Reproduce**
1. Create a Scala project
2. Copy the below code
3. Run sbt console
4. Issue `run` command
5. Keep sbt console running and wait for ~70 seconds

***Code Snippet***

build.sbt:
```scala
libraryDependencies += "org.slf4j" % "slf4j-simple" % "2.0.16"
libraryDependencies += "com.azure" % "azure-monitor-opentelemetry-exporter" % "1.0.0-beta.28"
```

Main.scala
```scala
object Main extends App {
  val aiConnStr = "..."

  import io.opentelemetry.sdk.autoconfigure.AutoConfiguredOpenTelemetrySdk
  import com.azure.monitor.opentelemetry.exporter.AzureMonitorExporterBuilder

  val sdkBuilder = AutoConfiguredOpenTelemetrySdk.builder()

  new AzureMonitorExporterBuilder()
      .connectionString(aiConnStr)
      .install(sdkBuilder)

  val openTelemetry = sdkBuilder.build().getOpenTelemetrySdk()
  println("Auto-configured")

  val meter = openTelemetry.getMeter("my-meter")
  val gauge = meter.gaugeBuilder("my-gauge").build()
  gauge.set(111)
  println("metric sent")

  openTelemetry.shutdown()
  println("Done")
}
```

**Expected behavior**
No error messaegs.

**Screenshots**
N/A

**Setup (please complete the following information):**
 - OS: 14.6.1 (23G93)
 - IDE: VSCode
 - Library/Libraries: azure-monitor-opentelemetry-exporter 1.0.0-beta.28
 - Java version: 8
 - Scala version: 3.5.0
 - sbt version: 1.10.2
 - App Server/Environment: N/A
 - Frameworks: N/A

**Additional context**
The message seems benign, and does not affect the subsequent operation. Still, not clear what is the endpoint it is complaining about.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by joshfree** [comment]
@lmolkova @trask please take a look

**Comment by heyams** [comment]
@greatvovan please check out my sample https://github.com/Azure-Samples/ApplicationInsights-Java-Samples/pull/534, 
it works for me though. 

I'm using opentelemetry-api-1.42.1 and azure-monitor-opentelemetry-exporter:1.0.0-beta.28:

```
<dependency>
    <groupId>io.opentelemetry.instrumentation</groupId>
    <artifactId>opentelemetry-instrumentation-bom</artifactId>
    <version>2.8.0</version>
    <type>pom</type>
    <scope>import</scope>
  </dependency>
  <dependency>
    <groupId>com.azure</groupId>
    <artifactId>azure-monitor-opentelemetry-exporter</artifactId>
    <version>1.0.0-beta.28</version>
  </dependency>
```

can you try it again and let me know if that resolves your issue?

**Comment by heyams** [comment]
@greatvovan I added ` Thread.sleep(70000);` after shutdown. I still don't get any error in the log. 

here is my maven dependency: 

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>exporter</artifactId>
        <groupId>com.example</groupId>
        <version>1.0-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>TrackMetric</artifactId>

    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>io.opentelemetry</groupId>
            <artifactId>opentelemetry-api</artifactId>
        </dependency>
        <dependency>
            <groupId>io.opentelemetry</groupId>
            <artifactId>opentelemetry-semconv</artifactId>
            <version>1.30.1-alpha</version>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>5.11.1</version>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>5.11.1</version>
        </dependency>
        <dependency>
            <groupId>io.opentelemetry</groupId>
            <artifactId>opentelemetry-api-incubator</artifactId>
        </dependency>
        <dependency>
            <groupId>io.opentelemetry</groupId>
            <artifactId>opentelemetry-sdk-metrics</artifactId>
        </dependency>
        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-monitor-opentelemetry-exporter</artifactId>
        </dependency>
        **<dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>2.0.16</version>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-core</artifactId>
            <version>1.5.8</version>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>1.5.8</version>
        </dependency>**
    </dependencies>

</project>
```

**Comment by greatvovan** [comment]
Hi @heyams. I am thinking, what if you try my version of the code instead of me trying yours? You will probably see the result faster.

The steps with Docker I posted in the last message should be enough to reproduce it on most computers in the world.

**Comment by heyams** [comment]
@greatvovan where is the step with Docker? 
Can you fork my PR and modify in a way that is reproducible?  I merged that PR, you can find it under closed tab.

**Comment by greatvovan** [comment]
> where is the step with Docker?

<img width="863" alt="Screenshot 2024-09-30 at 9 18 22 PM" src="https://github.com/user-attachments/assets/c8c2bbef-aca1-4f09-8082-89a7e2e5fa3b">
  
<img width="863" alt="Screenshot 2024-09-30 at 9 18 46 PM" src="https://github.com/user-attachments/assets/ab018d70-57aa-4c96-9b20-475778c5d1e2">


> Can you fork my PR and modify in a way that is reproducible? 

The only thing to modify in your sample is adding `Thread.sleep()` with a parameter longer than 60 s. **That's it.** If you can't reproduce it, it has something to do with the environment, logging level, or maybe the way of launching. That's why I suggest standardized environments such as containers. With your pom.xml, it printed a bit more, though:

```log
05:25:19.267 [reactor-http-epoll-4] DEBUG reactor.netty.transport.TransportConnector -- [54c0b1f2] Connect attempt to [/169.254.169.254:80] failed.
io.netty.channel.ConnectTimeoutException: connection timed out after 10000 ms: /169.254.169.254:80
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$2.run(AbstractEpollChannel.java:615)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:408)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
05:25:19.282 [AzureMetadataService-0] ERROR com.azure.core.http.netty.NettyAsyncHttpClient -- io.netty.channel.ConnectTimeoutException: connection timed out after 10000 ms: /169.254.169.254:80
java.io.UncheckedIOException: io.netty.channel.ConnectTimeoutException: connection timed out after 10000 ms: /169.254.169.254:80
	at com.azure.core.http.netty.NettyAsyncHttpClient.sendSync(NettyAsyncHttpClient.java:201)
	at com.azure.core.http.HttpPipelineNextSyncPolicy.processSync(HttpPipelineNextSyncPolicy.java:51)
	at com.azure.core.http.HttpPipeline.sendSync(HttpPipeline.java:138)
	at com.azure.monitor.opentelemetry.exporter.implementation.statsbeat.AzureMetadataService.run(AzureMetadataService.java:96)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: io.netty.channel.ConnectTimeoutException: connection timed out after 10000 ms: /169.254.169.254:80
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$2.run(AbstractEpollChannel.java:615)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:408)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 common frames omitted
05:25:19.282 [AzureMetadataService-0] DEBUG com.azure.monitor.opentelemetry.exporter.implementation.statsbeat.AzureMetadataService -- Shutting down AzureMetadataService scheduler: is not running on Azure VM or VMSS
```

This time it gave a hint in the last message. The 169.254.169.254 address might be Azure metadata endpoint? In this case, no wonder it can't connect to it. The exception must be caught though, to not pop up in stdout and not propagate to application's logging destination, causing confusion.
