### ISSUE TITLE
[BUG] Azure AI Inference API throwing JsonParseException: Illegal unquoted character ((CTRL-CHAR, code 10))

### ISSUE THREAD

**Issue by jdubois** [Azure/azure-sdk-for-java#42036]
**Describe the bug**
I'm using [azure-ai-inference_1.0.0-beta.1](https://github.com/Azure/azure-sdk-for-java/releases/tag/azure-ai-inference_1.0.0-beta.1).

When I send a string with a "\n", I get a stack trace saying "Illegal unquoted character ((CTRL-CHAR, code 10)): has to be escaped using backslash to be included in string value".

This is a Jackson configuration, which is explained at https://stackoverflow.com/questions/31537153/jsonparseexception-illegal-unquoted-character-ctrl-char-code-10

It's necessary for me to send such characters, that's typically what you do when doing the RAG pattern (in fact I use the Easy RAG pattern from LangChain4J and this is done by the framework).

***Exception or Stack Trace***
```
Caused by: com.fasterxml.jackson.core.JsonParseException: Illegal unquoted character ((CTRL-CHAR, code 10)): has to be escaped using backslash to be included in string value
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 62]
	at com.fasterxml.jackson.core.JsonParser._constructReadException(JsonParser.java:2648)
	at com.fasterxml.jackson.core.base.ParserBase._throwUnquotedSpace(ParserBase.java:1406)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._finishString2(UTF8StreamJsonParser.java:2591)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._finishAndReturnString(UTF8StreamJsonParser.java:2520)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.getText(UTF8StreamJsonParser.java:294)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializerNR.deserialize(UntypedObjectDeserializerNR.java:82)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:342)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4905)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3942)
	at com.azure.core.implementation.jackson.ObjectMapperShim.readValue(ObjectMapperShim.java:243)
	at com.azure.core.util.serializer.JacksonAdapter.lambda$deserialize$9(JacksonAdapter.java:359)
	at com.azure.core.util.serializer.JacksonAdapter.useAccessHelper(JacksonAdapter.java:491)
	at com.azure.core.util.serializer.JacksonAdapter.deserialize(JacksonAdapter.java:347)
	at com.azure.core.implementation.serializer.DefaultJsonSerializer.deserializeFromBytes(DefaultJsonSerializer.java:32)
```

**To Reproduce**
To reproduce this issue, execute the following code: https://github.com/jdubois/langchain4j-examples/blob/075a8d3893893977d965383f4bb2e673dfe8bb12/github-models-examples/src/main/java/GitHubModelsChatModelExamples.java#L17

As you can see, there's a "\n" at the end, and that will trigger the bug.

If you want to test the whole example, it's in this branch https://github.com/jdubois/langchain4j-examples/tree/azure-sdk-for-java-issue-1 that I created for this issue.

***Code Snippet***
The code is at https://github.com/jdubois/langchain4j-examples/blob/075a8d3893893977d965383f4bb2e673dfe8bb12/github-models-examples/src/main/java/GitHubModelsChatModelExamples.java#L17

**Expected behavior**
There should not be such error, with every other SDK (including the Azure OpenAI SDK), this character doesn't cause a stack trace.

**Setup (please complete the following information):**
 - OS: Mac OS
 - IDE: IntelliJ
 - Library/Libraries: azure-ai-inference_1.0.0-beta.1
 - Java version: 23
 - App Server/Environment: none
 - Frameworks: none

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by alzimmermsft** [comment]
Thanks for filing this issue @jdubois.

@mssfang, @jpalvarezl (and FYI @JonathanGiles, @srnagar), this appears to be an issue in the API call chain when `new ChatRequestUserMessage(String)` is being used to create the `ChatRequestUserMessage`, which then later crops up as this issue when `toJson` is being called on the class. The trailing `\n` doesn't get escaped properly to be valid JSON (should be `\\n`). Switching the constructor call from `BinaryData.fromString`, and removing the `String.format` call to quote the String value, to `BinaryData.fromObject` does alleviate this issue, but I can't guarantee this will cause more oddities and issues downstream.
