### ISSUE TITLE
[BUG] block()/blockFirst()/blockLast() are blocking, which is not supported in thread default-nioEventLoopGroup-1 for BlobClientBase.exists()

### ISSUE THREAD

**Issue by loicmathieu** [Azure/azure-sdk-for-java#42268]
**Describe the bug**

Exception when calling BlobClientBase.exists().

***Exception or Stack Trace***
```
java.lang.IllegalStateException: block()/blockFirst()/blockLast() are blocking, which is not supported in thread default-nioEventLoopGroup-1-5
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:87)
	at reactor.core.publisher.Mono.block(Mono.java:1779)
	at com.azure.storage.common.implementation.StorageImplUtils.blockWithOptionalTimeout(StorageImplUtils.java:146)
	at com.azure.storage.blob.specialized.BlobClientBase.existsWithResponse(BlobClientBase.java:501)
	at com.azure.storage.blob.specialized.BlobClientBase.exists(BlobClientBase.java:479)
```

**To Reproduce**
Using the following code in a Micronaut controller with file upload.
The error shows up only for files of a certain size (more than 1MB).

***Code Snippet***
```java
    private boolean exists(String path) {
        try {
            BlobClient blobClient = this.blobContainerClient.getBlobClient(path);
            return blobClient.exists();
        } catch (BlobStorageException e) {
            return false;
        }
    }
```

**Setup (please complete the following information):**
 - OS: Linux 6.8.0-45-generic #45-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug 30 12:02:04 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
 - Library/Libraries: com.azure:azure-storage-blob:12.27.1
 - Java version: 21
 - Frameworks: Micronaut 4.6.3

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by loicmathieu** [comment]
I found a workaround but it's not pretty:
- Use the asyncClient
- Dispatch all blocking call to an executor

Something like that:
```java
private final ExecutorService executorService = Executors.newSingleThreadExecutor();

    private <T> T block(Mono<T> mono) {
        try {
            return executorService.submit(() -> mono.blockOptional().orElse(null)).get();
        } catch (InterruptedException | ExecutionException e) {
            throw new RuntimeException(e);
        }
    }
```

**Comment by brian-mulier-p** [comment]
In fact I think we just reproduced the issue but only when working with another Azure service. For reference we get the following error when trying to pass an InputStream coming from `com.azure.storage.blob.BlobClient.openInputStream()` to `com.azure.storage.file.datalake.DataLakeFileClient.upload(BinaryData.fromStream(is))` because the input stream is fetching by doing multiple block() calls which is not supported by datalake client upload it seems...

[2025-05-19T101518.934913Z ERROR blo.txt](https://github.com/user-attachments/files/20302385/2025-05-19T101518.934913Z.ERROR.blo.txt)

**Comment by ibrandes** [comment]
The non-upload sync and async paths for the blob package were decoupled in version 12.29, so this issue will not occur in newer versions for `BlobClientBase.exists()`.
