### ISSUE TITLE
[BUG] Can't save to CosmosDB if partition key fields are inherited from parent class

### ISSUE THREAD

**Issue by pmottmwi** [Azure/azure-sdk-for-java#42362]
**Describe the bug**
Spring Cosmos library fails to retrieve partition key value from entity if that field is inherited from a different class.

***Exception or Stack Trace***
```
java.lang.RuntimeException: java.lang.NoSuchFieldException: id
	at com.azure.spring.data.cosmos.repository.support.CosmosEntityInformation.getPartitionKeyFieldValue(CosmosEntityInformation.java:325)
	at com.azure.spring.data.cosmos.core.CosmosTemplate.getPartitionKeyFromValue(CosmosTemplate.java:1326)
	at com.azure.spring.data.cosmos.core.CosmosTemplate.lambda$insertAll$2(CosmosTemplate.java:294)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.azure.spring.data.cosmos.core.CosmosTemplate.insertAll(CosmosTemplate.java:282)
	at com.azure.spring.data.cosmos.repository.support.SimpleCosmosRepository.saveAll(SimpleCosmosRepository.java:153)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:355)
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker$RepositoryFragmentMethodInvoker.lambda$new$0(RepositoryMethodInvoker.java:277)
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.doInvoke(RepositoryMethodInvoker.java:170)
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.invoke(RepositoryMethodInvoker.java:158)
	at org.springframework.data.repository.core.support.RepositoryComposition$RepositoryFragments.invoke(RepositoryComposition.java:516)
	at org.springframework.data.repository.core.support.RepositoryComposition.invoke(RepositoryComposition.java:285)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$ImplementationMethodExecutionInterceptor.invoke(RepositoryFactorySupport.java:628)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:173)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:148)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:223)
	at jdk.proxy3/jdk.proxy3.$Proxy162.saveAll(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:355)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:138)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:223)
	at jdk.proxy3/jdk.proxy3.$Proxy162.saveAll(Unknown Source)
```

**To Reproduce**
Call `CosmosRepository.saveAll` passing in entity from code snippet.

***Code Snippet***
```
public abstract class AbstractEntity {
	@Id
	private String id;

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}
}
	
@Container(partitionKeyPath = "/id")
public class EntityImpl extends AbstractEntity {
}
```

**Expected behavior**
Correct partition key value should be retrieved pulled from the entity.

**Setup (please complete the following information):**
 - Library/Libraries: azure-spring-data-cosmos-5.17.1
 - Java version: 17
 - Frameworks: Spring Boot

**Comment by kushagraThapar** [comment]
@trande4884 please take a look at this issue, thanks!

**Comment by pmottmwi** [comment]
I also get the same error when trying to delete a single entity. I don't get the error when trying to save a single entity.

**Comment by pmottmwi** [comment]
This also affects deleting entities, which is harder to work around (managed to get around the saveAll problem by saving the entities one at a time).

**Comment by kushagraThapar** [comment]
@pmottmwi this is already fixed in the latest version.
