### ISSUE TITLE
Cosmos DB Partial Update on Document using Spark Cosmos OLTP Connector

### ISSUE THREAD

**Issue by shweta5595** [Azure/azure-sdk-for-java#42834]
Hi Team, 

I wanted to do a partial update on cosmos db document . I see the spark write strategy as ItemPatch . However I am getting this error. Can someone please help.

***Exception or Stack Trace***
`Py4JJavaError: An error occurred while calling o2752.save.
: org.apache.spark.SparkException: Writing job aborted
	at org.apache.spark.sql.errors.QueryExecutionErrors$.writingJobAbortedError(QueryExecutionErrors.scala:717)
	at org.apache.spark.sql.execution.datasources.v2.V2TableWriteExec.writeWithV2(WriteToDataSourceV2Exec.scala:403)
	at org.apache.spark.sql.execution.datasources.v2.V2TableWriteExec.writeWithV2$(WriteToDataSourceV2Exec.scala:347)
	at org.apache.spark.sql.execution.datasources.v2.AppendDataExec.writeWithV2(WriteToDataSourceV2Exec.scala:249)
	at org.apache.spark.sql.execution.datasources.v2.V2ExistingTableWriteExec.run(WriteToDataSourceV2Exec.scala:326)
	at org.apache.spark.sql.execution.datasources.v2.V2ExistingTableWriteExec.run$(WriteToDataSourceV2Exec.scala:325)
	at org.apache.spark.sql.execution.datasources.v2.AppendDataExec.run(WriteToDataSourceV2Exec.scala:249)
	at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result$lzycompute(V2CommandExec.scala:43)
	at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result(V2CommandExec.scala:43)
	at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.executeCollect(V2CommandExec.scala:49)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$$nestedInanonfun$eagerlyExecuteCommands$1$1.$anonfun$applyOrElse$1(QueryExecution.scala:174)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withCustomExecutionEnv$8(SQLExecution.scala:245)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:393)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withCustomExecutionEnv$1(SQLExecution.scala:192)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:979)
	at org.apache.spark.sql.execution.SQLExecution$.withCustomExecutionEnv(SQLExecution.scala:147)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:343)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$$nestedInanonfun$eagerlyExecuteCommands$1$1.applyOrElse(QueryExecution.scala:174)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$$nestedInanonfun$eagerlyExecuteCommands$1$1.applyOrElse(QueryExecution.scala:170)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$1(TreeNode.scala:590)
	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:168)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:590)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDownWithPruning(LogicalPlan.scala:31)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning(AnalysisHelper.scala:268)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning$(AnalysisHelper.scala:264)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:31)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:31)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:566)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$eagerlyExecuteCommands$1(QueryExecution.scala:170)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.allowInvokingTransformsInAnalyzer(AnalysisHelper.scala:324)
	at org.apache.spark.sql.execution.QueryExecution.eagerlyExecuteCommands(QueryExecution.scala:170)
	at org.apache.spark.sql.execution.QueryExecution.commandExecuted$lzycompute(QueryExecution.scala:155)
	at org.apache.spark.sql.execution.QueryExecution.commandExecuted(QueryExecution.scala:146)
	at org.apache.spark.sql.execution.QueryExecution.assertCommandExecuted(QueryExecution.scala:200)
	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:959)
	at org.apache.spark.sql.DataFrameWriter.saveInternal(DataFrameWriter.scala:346)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:258)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)
	at py4j.Gateway.invoke(Gateway.java:295)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:251)
	at java.lang.Thread.run(Thread.java:750)
Caused by: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 53.0 failed 4 times, most recent failure: Lost task 0.3 in stage 53.0 (TID 33) (10.179.0.11 executor 1): {"ClassName":"BulkOperationFailedException","userAgent":"azsdk-java-cosmos/4.39.0 Linux/5.15.0-1073-azure JRE/1.8.0_382","statusCode":400,"resourceAddress":null,"innerErrorMessage":"All retries exhausted for 'PATCH' bulk operation - statusCode=[400:0] itemId=[SAVINGS.fff30475-aa2f-4bc9-98e1-784a818329af], partitionKeyValue=[[\"fff30475-aa2f-4bc9-98e1-784a818329af\"]]","causeInfo":null,"responseHeaders":"{x-ms-substatus=0}"}
	at com.azure.cosmos.spark.BulkWriter.handleNonSuccessfulStatusCode(BulkWriter.scala:396)
	at com.azure.cosmos.spark.BulkWriter.$anonfun$subscriptionDisposable$2(BulkWriter.scala:168)
	at com.azure.cosmos.spark.BulkWriter.$anonfun$subscriptionDisposable$2$adapted(BulkWriter.scala:144)
	at azure_cosmos_spark.reactor.core.scala.publisher.package$.$anonfun$scalaConsumer2JConsumer$2(package.scala:45)
	at azure_cosmos_spark.reactor.core.scala.publisher.package$.$anonfun$scalaConsumer2JConsumer$2$adapted(package.scala:45)
	at scala.Option.foreach(Option.scala:407)
	at azure_cosmos_spark.reactor.core.scala.publisher.package$.$anonfun$scalaConsumer2JConsumer$1(package.scala:45)
	at azure_cosmos_spark.reactor.core.publisher.LambdaSubscriber.onNext(LambdaSubscriber.java:160)
	at azure_cosmos_spark.reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runAsync(FluxPublishOn.java:440)
	at azure_cosmos_spark.reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:527)
	at azure_cosmos_spark.reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
	at azure_cosmos_spark.reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:3185)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:3120)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:3107)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:3107)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1448)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1448)
	at scala.Option.foreach(Option.scala:407)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1448)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:3393)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:3334)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:3322)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:1214)
	at org.apache.spark.SparkContext.runJobInternal(SparkContext.scala:2665)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2648)
	at org.apache.spark.sql.execution.datasources.v2.V2TableWriteExec.writeWithV2(WriteToDataSourceV2Exec.scala:371)
	... 46 more
Caused by: {"ClassName":"BulkOperationFailedException","userAgent":"azsdk-java-cosmos/4.39.0 Linux/5.15.0-1073-azure JRE/1.8.0_382","statusCode":400,"resourceAddress":null,"innerErrorMessage":"All retries exhausted for 'PATCH' bulk operation - statusCode=[400:0] itemId=[SAVINGS.fff30475-aa2f-4bc9-98e1-784a818329af], partitionKeyValue=[[\"fff30475-aa2f-4bc9-98e1-784a818329af\"]]","causeInfo":null,"responseHeaders":"{x-ms-substatus=0}"}
	at com.azure.cosmos.spark.BulkWriter.handleNonSuccessfulStatusCode(BulkWriter.scala:396)
	at com.azure.cosmos.spark.BulkWriter.$anonfun$subscriptionDisposable$2(BulkWriter.scala:168)
	at com.azure.cosmos.spark.BulkWriter.$anonfun$subscriptionDisposable$2$adapted(BulkWriter.scala:144)
	at azure_cosmos_spark.reactor.core.scala.publisher.package$.$anonfun$scalaConsumer2JConsumer$2(package.scala:45)
	at azure_cosmos_spark.reactor.core.scala.publisher.package$.$anonfun$scalaConsumer2JConsumer$2$adapted(package.scala:45)
	at scala.Option.foreach(Option.scala:407)
	at azure_cosmos_spark.reactor.core.scala.publisher.package$.$anonfun$scalaConsumer2JConsumer$1(package.scala:45)
	at azure_cosmos_spark.reactor.core.publisher.LambdaSubscriber.onNext(LambdaSubscriber.java:160)
	at azure_cosmos_spark.reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runAsync(FluxPublishOn.java:440)
	at azure_cosmos_spark.reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:527)
	at azure_cosmos_spark.reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
	at azure_cosmos_spark.reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more`

**To Reproduce**

***Code Snippet***
writeConfig = {
  "spark.cosmos.accountEndpoint": cosmosEndpoint,
  "spark.cosmos.accountKey": cosmosMasterKey,
  "spark.cosmos.database": cosmosDatabaseName,
  "spark.cosmos.container": cosmosContainerName,
  "spark.cosmos.write.bulk.maxPendingOperations" : 200,
  "spark.cosmos.write.strategy": "ItemPatch",
  "spark.cosmos.write.patch.defaultOperationType": "Add"
}

**Expected behavior**
Should be able to do a partial update on document

**Setup (please complete the following information):**
 - Library/Libraries: [com.azure.cosmos.spark:azure-cosmos-spark_3-2_2-12:4.15.0]
 - App Server/Environment: [Databricks]

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by TheovanKraay** [comment]
You need also a config `spark.cosmos.write.patch.columnConfigs`, e.g. below:

```Python
writeConfig = {
"spark.cosmos.accountEndpoint": cosmosEndpoint,
"spark.cosmos.accountKey": cosmosMasterKey,
"spark.cosmos.database": cosmosDatabaseName,
"spark.cosmos.container": cosmosContainerName,
"spark.cosmos.write.bulk.maxPendingOperations" : 200,
"spark.cosmos.write.strategy": "ItemPatch",
"spark.cosmos.write.patch.defaultOperationType": "Add",
"spark.cosmos.write.patch.columnConfigs": "[col(directReports).op(add)]"
}
```

See also docs [here](https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/tutorial-spark-connector?pivots=programming-language-python) and full sample [here](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-cosmos-spark_3_2-12/Samples/Python/patch-sample.py).

**Comment by shweta5595** [comment]
HI @TheovanKraay , even though I added above mentioned config 
I am getting following error : 

`Caused by: {"ClassName":"BulkOperationFailedException","userAgent":"azsdk-java-cosmos/4.39.0 Linux/5.15.0-1073-azure JRE/1.8.0_382","statusCode":400,"resourceAddress":null,"innerErrorMessage":"All retries exhausted for 'PATCH' bulk operation - statusCode=[400:0] itemId=[SAVINGS.fffe16f0-2ae2-4a19-8111-3f23da4563e7], partitionKeyValue=[[\"fffe16f0-2ae2-4a19-8111-3f23da4563e7\"]]","causeInfo":null,"responseHeaders":"{x-ms-substatus=0}"}
	at com.azure.cosmos.spark.BulkWriter.handleNonSuccessfulStatusCode(BulkWriter.scala:396)
	at com.azure.cosmos.spark.BulkWriter.$anonfun$subscriptionDisposable$2(BulkWriter.scala:168)
	at com.azure.cosmos.spark.BulkWriter.$anonfun$subscriptionDisposable$2$adapted(BulkWriter.scala:144)
	at azure_cosmos_spark.reactor.core.scala.publisher.package$.$anonfun$scalaConsumer2JConsumer$2(package.scala:45)
	at azure_cosmos_spark.reactor.core.scala.publisher.package$.$anonfun$scalaConsumer2JConsumer$2$adapted(package.scala:45)
	at scala.Option.foreach(Option.scala:407)
	at azure_cosmos_spark.reactor.core.scala.publisher.package$.$anonfun$scalaConsumer2JConsumer$1(package.scala:45)
	at azure_cosmos_spark.reactor.core.publisher.LambdaSubscriber.onNext(LambdaSubscriber.java:160)
	at azure_cosmos_spark.reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runAsync(FluxPublishOn.java:440)
	at azure_cosmos_spark.reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:527)
	at azure_cosmos_spark.reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
	at azure_cosmos_spark.reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
`

**Comment by TheovanKraay** [comment]
If partition key is different than "id", then in your dataframes, you will also need to include the partition key property. If you have already done that then please provide full sample (not just the config) so we can see what you are trying to do. You should also try using the config settings in samples as your starting point.

**Comment by shweta5595** [comment]
Hi @TheovanKraay , I am trying to use ItemBulkUpdate as my write strategy , since my no. of patch operations are more than 10 . 
But I get following error 
`Caused by: java.lang.IllegalArgumentException: ItemBulkUpdate valid value, valid values are ItemWriteStrategy.ValueSet(ItemOverwrite, ItemAppend, ItemDelete, ItemDeleteIfNotModified, ItemOverwriteIfNotModified, ItemPatch)
	at com.azure.cosmos.spark.CosmosConfigEntry$.$anonfun$parseEnumeration$2(CosmosConfig.scala:1409)
	at scala.Option.getOrElse(Option.scala:189)
	at com.azure.cosmos.spark.CosmosConfigEntry$.parseEnumeration(CosmosConfig.scala:1409)
	at com.azure.cosmos.spark.CosmosWriteConfig$.$anonfun$itemWriteStrategy$1(CosmosConfig.scala:652)
	at com.azure.cosmos.spark.CosmosConfigEntry.parse(CosmosConfig.scala:1396)
	... 24 more`

Docs Referred : [here](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-cosmos-spark_3-2_2-12/CHANGELOG.md) and [here](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-cosmos-spark_3-2_2-12/CHANGELOG.md)

**Comment by TheovanKraay** [comment]
@shweta5595 can you please share the full code, and version of Spark Connector you are using?

**Comment by shweta5595** [comment]
Spark Connector : com.azure.cosmos.spark:azure-cosmos-spark_3-2_2-12:4.23.0

`def processFile(file_name):
  print(str(datetime.now()),'#### starting Processing', file_name)
  savingsSchema = populateSchema()
  # blob_name = "/mnt/perksdata_prod/v2/SAVINGS/" + file_name 
  savingsDfRaw = spark.read.schema(savingsSchema).csv("/mnt/perksdata_stg/v2/LastYear/Savings/Savings_Test.csv").distinct().orderBy(col("triggerDate"))

   savingsdf= savingsDfRaw
  display(savingsdf)

  # data cleaning
  # replacing "null" to None 

  savingsdf = savingsdf.withColumn(
    "cardholderNbr", funNew(col("cardholderNbr"))).withColumn(
    "membershipNbr", funNew(col("membershipNbr"))).withColumn(
    "cntryRetailChannelMbrId", funNew(col("cntryRetailChannelMbrId"))).withColumn(
    "cntryRetailChannelCustId", funNew(col("cntryRetailChannelCustId"))).withColumn(
    "triggerDate", funNew(col("triggerDate"))).withColumn(
    "instantSavingsActualMemberYear", funNew(col("instantSavingsActualMemberYear"))).withColumn(
    # "instantSavingsLastTransactionDate", funNew(col("instantSavingsLastTransactionDate"))).withColumn(
    # "instantSavingsLastTransactionAmount", funNew(col("instantSavingsLastTransactionAmount"))).withColumn(
    # "instantSavingsActualLastMemberYear", funNew(col("instantSavingsActualLastMemberYear"))).withColumn(
    "freeShippingSavingsActual", funNew(col("freeShippingSavingsActual"))).withColumn(
    # "freeShippingLastTransactionDate", funNew(col("freeShippingLastTransactionDate"))).withColumn(
    # "freeShippingLastTransactionAmount", funNew(col("freeShippingLastTransactionAmount"))).withColumn(
    # "freeShippingSavingsActualLastMemberYear", funNew(col("freeShippingSavingsActualLastMemberYear"))).withColumn(
    # "freeShippingSavingPotential", funNew(col("freeShippingSavingPotential"))).withColumn(
    "travelSavingsActualMemberYear", funNew(col("travelSavingsActualMemberYear"))).withColumn(
    "entertainmentSavingsActualMemberYear", funNew(col("entertainmentSavingsActualMemberYear"))).withColumn(
    # "travelAndEntertainmentLastTransactionDate", funNew(col("travelAndEntertainmentLastTransactionDate"))).withColumn(
    # "travelAndEntertainmentLastTransactionAmount", funNew(col("travelAndEntertainmentLastTransactionAmount"))).withColumn(
    "competitiveSavingsActualMemberYear", funNew(col("competitiveSavingsActualMemberYear")))
    # .withColumn(
    # "competitiveSavingsLastTransactionDate", funNew(col("competitiveSavingsLastTransactionDate")))

  #Populating Savings

  savingsdf = savingsdf.withColumn("membershipAccount",f.concat(f.col("cardholderNbr"),f.col("membershipNbr")))
  savingsdf = savingsdf.withColumn("docType",f.lit("SAVINGS"))
  savingsdf = savingsdf.withColumn("docStatus",f.lit("ACTIVE"))
  savingsdf = savingsdf.withColumn("partitionKey",f.col("cntryRetailChannelCustID"))
  savingsdf = savingsdf.withColumn("id",f.concat(f.lit("SAVINGS."), f.col("cntryRetailChannelCustID")))
  savingsdf = savingsdf.withColumn("cntryRetailChannelMbrID",f.col("cntryRetailChannelMbrID"))
  savingsdf = savingsdf.withColumn("cntryRetailChannelCustID",f.col("cntryRetailChannelCustID"))
  savingsdf = savingsdf.withColumn("createdOn",f.lit(get_cur_date_time())) # This needs to be checked
  # savingsdf = savingsdf.withColumn("createdByApp",f.lit("OneTimeMigration"))
  savingsdf = savingsdf.withColumn("lastUpdatedOn",f.lit(get_cur_date_time())) # This needs to be checked
  # savingsdf = savingsdf.withColumn("lastUpdatedApp",f.lit("OneTimeMigration")) # This needs to be checked
  savingsdf = savingsdf.withColumn("lastUpdatedUser",f.lit("SAVINGS_LASTYEAR_EVENT_PROCESSOR")) # This needs to be checked
  savingsdf = savingsdf.withColumn("triggerDate",f.col("triggerDate"))

  ###########################################Instant Savings###########################################
  savingsdf = savingsdf.withColumn("amount", when(col("instantSavingsActualMemberYear").isNull() , lit(None))
     .otherwise(struct(
          col("instantSavingsActualMemberYear").alias("total"), lit("USD").alias("currency"))))

  savingsdf = savingsdf.withColumn("lastMemberYear", when(col("amount").isNull(), lit(None)) 
                             .otherwise(struct(
                               col("amount")))).drop("amount")

  savingsdf = savingsdf.withColumn("actualSaving", when(col("lastMemberYear").isNull(), lit(None)) .otherwise(
                                   struct(col("lastMemberYear")))).drop("lastMemberYear")

  savingsdf = savingsdf.withColumn("instantSavings", when(col("actualSaving").isNull() , lit(None)).otherwise(
                                   struct(col("actualSaving")))).drop("actualSaving")

  # ########################################### FreeShipping ###########################################

   ##### 1.2 lastMemberYear
  savingsdf = savingsdf.withColumn("amount", when(col("freeShippingSavingsActual").isNull() , lit(None))
     .otherwise(struct(
          col("freeShippingSavingsActual").alias("total"), lit("USD").alias("currency"))))

  savingsdf = savingsdf.withColumn("lastMemberYear", when(col("amount").isNull(), lit(None)) 
                             .otherwise(struct(
                               col("amount")))).drop("amount")

  savingsdf = savingsdf.withColumn("actualSaving", when(col("lastMemberYear").isNull(), lit(None)).otherwise(
                                   struct(col("lastMemberYear")))).drop("memberYear", "lastMemberYear", "freeShippingSavingsActual", "freeShippingSavingsActualLastMemberYear")

   # # freeShippings
  savingsdf = savingsdf.withColumn("freeShippings", when(col("actualSaving").isNull() , lit(None)).otherwise(
                                   struct(col("actualSaving")))).drop("actualSaving")


  # ########################################### Travel and Entertainment ###########################################

  # # 1.  travelActual
  
  savingsdf = savingsdf.withColumn("amount", when(col("travelSavingsActualMemberYear").isNull() , lit(None))
     .otherwise(struct(
          col("travelSavingsActualMemberYear").alias("total"), lit("USD").alias("currency"))))
  savingsdf = savingsdf.withColumn("lastMemberYear", when(col("amount").isNull() , lit(None)) .otherwise(struct(col("amount")))).drop("amount")

  savingsdf = savingsdf.withColumn("travelActual", when(col("lastMemberYear").isNull(), lit(None)).otherwise(
                                   struct(col("lastMemberYear")))).drop("lastMemberYear")

  # # 2.  entActual
  savingsdf = savingsdf.withColumn("amount", when(col("entertainmentSavingsActualMemberYear").isNull() , lit(None))
     .otherwise(struct(
          col("entertainmentSavingsActualMemberYear").alias("total"), lit("USD").alias("currency"))))
  savingsdf = savingsdf.withColumn("lastMemberYear", when(col("amount").isNull() , lit(None)) .otherwise(struct(col("amount")))).drop("amount")

  savingsdf = savingsdf.withColumn("entActual", when(col("lastMemberYear").isNull(), lit(None)).otherwise(
                                   struct(col("lastMemberYear")))).drop("lastMemberYear")

  # travelAndEntertainment
  savingsdf = savingsdf.withColumn("travelAndEntertainment", when(col("travelActual").isNull() & col("entActual").isNull(), lit(None)).otherwise(
                                   struct(col("travelActual"), col("entActual")))).drop("travelActual", "entActual")


  # ########################################### Competitive Savings ###########################################

  savingsdf = savingsdf.withColumn("amount", when(col("competitiveSavingsActualMemberYear").isNull() , lit(None))
     .otherwise(struct(
          col("competitiveSavingsActualMemberYear").alias("total"), lit("USD").alias("currency"))))
  savingsdf = savingsdf.withColumn("lastMemberYear", when(col("amount").isNull() , lit(None)) .otherwise(struct(col("amount")))).drop("amount")

  savingsdf = savingsdf.withColumn("actualSaving", when(col("lastMemberYear").isNull(), lit(None)).otherwise(
                                   struct(col("lastMemberYear")))).drop("lastMemberYear")


  savingsdf = savingsdf.withColumn("competitiveSavings", when(col("actualSaving").isNull(), lit(None)).otherwise(
                                   struct(col("actualSaving")))).drop("actualSaving","lastTransaction")

  savingsdf = savingsdf.withColumn("savings", struct(col("instantSavings"), col("freeShippings"), col("travelAndEntertainment") , col("competitiveSavings"))).drop("instantSavings","freeShippings", "travelAndEntertainment","competitiveSavings")
  
  savingsdf = savingsdf.distinct()
  print("Total Records Processed :  " + str(savingsdf.count()))
  savingsdf.write.format("cosmos.oltp").options(**configPatch).mode("APPEND").save()`

**Comment by TheovanKraay** [comment]
@shweta5595 can you show your current `configPatch` as well?

**Comment by TheovanKraay** [comment]
Also, please try two things:

1. set bulk to false: "spark.cosmos.write.bulk.enabled": "false" (better for debugging)
2. Double check Spark connector version (the version you have includes ItemBulkUpdate but the error indicates you are using a version that does not). Ideally, update to the latest version.

**Comment by shweta5595** [comment]
HI @TheovanKraay , 
Here is my current config : 
cosmosEndpoint = endPoint
cosmosMasterKey = key
cosmosDatabaseName = someDB
cosmosContainerName = someContainer

configPatch = dict(writeConfig)
configPatch["spark.cosmos.write.strategy"] = "ItemPatch"
configPatch["spark.cosmos.write.bulk.enabled"] = "false"
configPatch["spark.cosmos.write.patch.defaultOperationType"] = "Add"
configPatch["spark.cosmos.write.patch.columnConfigs"] = "[col(instantSavingsActualMemberYear).op(add)]"

**Comment by shweta5595** [comment]
Also , I have set spark.cosmos.write.bulk.enabled to false 
and using version 4.23.0 from the release documentation only

**Comment by TheovanKraay** [comment]
I see that you installed connector using `com.azure.cosmos.spark:azure-cosmos-spark_3-2_2-12:4.15.0`.
You need to install using `com.azure.cosmos.spark:azure-cosmos-spark_3-2_2-12:4.23.0` in order to get `ItemBulkUpdate`

**Comment by shweta5595** [comment]
Yes I am able to use this feature . Thanks for your help @TheovanKraay .
