### ISSUE TITLE
[BUG] Recursive update exception in HttpLogOptions initialization with security manager enabled

### ISSUE THREAD

**Issue by martin-frydl** [Azure/azure-sdk-for-java#42905]
**Describe the bug**
`java.lang.IllegalStateException: Recursive update` exception is thrown when `HttpLogOptions` class is initialized with security manager enabled.

***Exception or Stack Trace***
```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.azure.core.implementation.ReflectionUtilsMethodHandle.performSafePrivateLookupIn(ReflectionUtilsMethodHandle.java:197)
	at com.azure.core.implementation.ReflectionUtilsMethodHandle.getLookupToUse(ReflectionUtilsMethodHandle.java:153)
	at com.azure.core.implementation.ReflectionUtilsMethodHandle.getConstructorInvoker(ReflectionUtilsMethodHandle.java:111)
	at com.azure.core.implementation.ReflectionUtils.getConstructorInvoker(ReflectionUtils.java:130)
	at com.azure.core.implementation.ReflectionUtils.getConstructorInvoker(ReflectionUtils.java:96)
	at com.azure.core.util.ExpandableStringEnum.getDefaultConstructor(ExpandableStringEnum.java:91)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) <---------------------------
	at com.azure.core.util.ExpandableStringEnum.fromString(ExpandableStringEnum.java:70)
	at com.azure.core.http.HttpHeaderName.fromString(HttpHeaderName.java:73)
	at com.azure.core.http.HttpHeaderName.<clinit>(HttpHeaderName.java:101)
	at com.azure.core.http.policy.HttpLogOptions.<clinit>(HttpLogOptions.java:55)
	at AzureTest.main(AzureTest.java:3)
Caused by: java.lang.IllegalStateException: Recursive update
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1763) <----------------------
	at com.azure.core.util.ExpandableStringEnum.fromString(ExpandableStringEnum.java:70)
	at com.azure.core.http.HttpHeaderName.fromString(HttpHeaderName.java:73)
	at com.azure.core.implementation.ImplUtils.<clinit>(ImplUtils.java:55)
	... 12 more
```
**To Reproduce**
```java
public class AzureTest {
    public static void main(String args[]) {
        System.out.println(new com.azure.core.http.policy.HttpLogOptions());
   }
}
```
When running set `-Djava.security.manager -Djava.security.policy=policy.policy` where policy file contained following (just to make it run):
```
grant {
  permission java.lang.RuntimePermission "*";
  permission java.util.PropertyPermission "*", "read, write";
};
```

**Expected behavior**
Working initialization. It works fine in version 1.53.0 but fails in 1.54.0.

**Setup:**
 - OS: Ubuntu 22.04
 - Library/Libraries: com.azure:azure-core:1.54.0
 - Java version: 21

**Additional context**
The problem is in `ReflectionUtilsMethodHandle.performSafePrivateLookupIn()` where `ImplUtils.doPrivilegedException()` is called. `ImplUtils` gets initializated by calling exactly the same method - `HttpHeaderName.fromString()` - leading to setting the same key in the same map.

**Comment by alzimmermsft** [comment]
Thank you for reporting this @martin-frydl!

I'll file a PR to resolve this and include the information you've given to add tests that will prevent this in the future.
