### ISSUE TITLE
[BUG][LUIS] Apps.addCustomPrebuiltDomain throws because of missing tokenizerVersion

### ISSUE THREAD

**Issue by v-jaswel** [Azure/azure-sdk-for-java#4300]
**Describe the bug**
Calling Apps.addCustomPrebuiltDomain gets a 400 response from the server because no tokenizer version is specified.

***Exception or Stack Trace***
```
com.microsoft.azure.cognitiveservices.language.luis.authoring.models.ErrorResponseException: Status code 400, {
  "error": {
    "code": "BadArgument",
    "message": "The tokenizer version cannot be null or empty."
  }
}
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
        at com.microsoft.rest.ServiceResponseBuilder.build(ServiceResponseBuilder.java:122)
        at com.microsoft.azure.AzureResponseBuilder.build(AzureResponseBuilder.java:56)
        at com.microsoft.azure.cognitiveservices.language.luis.authoring.implementation.AppsImpl.addCustomPrebuiltDomainDelegate(AppsImpl.java:1836)
        at com.microsoft.azure.cognitiveservices.language.luis.authoring.implementation.AppsImpl.access$1800(AppsImpl.java:63)
        at com.microsoft.azure.cognitiveservices.language.luis.authoring.implementation.AppsImpl$56.call(AppsImpl.java:1823)
        at com.microsoft.azure.cognitiveservices.language.luis.authoring.implementation.AppsImpl$56.call(AppsImpl.java:1819)
        at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
        at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$RequestArbiter.request(RxJavaCallAdapterFactory.java:173)
        at rx.Subscriber.setProducer(Subscriber.java:211)
        at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102)
        at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:152)
        at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:138)
        at rx.Observable.unsafeSubscribe(Observable.java:10142)
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.Observable.subscribe(Observable.java:10238)
        at rx.Observable.subscribe(Observable.java:10205)
        at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:444)
        at rx.observables.BlockingObservable.single(BlockingObservable.java:341)
        at com.microsoft.azure.cognitiveservices.language.luis.authoring.implementation.AppsImpl.addCustomPrebuiltDomain(AppsImpl.java:1771)
        at Quickstart.create_application(Quickstart.java:24)
        at Quickstart.main(Quickstart.java:31)
```

**To Reproduce**
1. Get a LUIS subscription key.
1. Set the environment variable LUIS_SUBSCRIPTION_KEY to your subscription key.
1. Set the environment variable LUIS_REGION to the region for your subscription key (example: westus).
1. Copy the following XML into a file named pom.xml.
1. Copy the following Java code into a file named quickstart.java.
1. Install Maven (https://maven.apache.org/) and make sure the location of mvn.exe is in your PATH environment variable.
1. Open a command prompt and cd to where you put pom.xml and quickstart.java.
1. Run `mvn clean dependency:copy-dependencies`. This should download the required .jar files to a subfolder named `lib`.
1. Compile quickstart.java by running `javac Quickstart.java -cp .;lib\*`
1. Run `javac Quickstart.java -cp .;lib\*`

***Code Snippet***
pom.xml:
```
<?xml version="1.0" encoding="utf-8"?>
<!--
Source: https://gist.github.com/statico/547434f630d589651afcbe3f132b91d9
Run with: mvn clean dependency:copy-dependencies
-->
<project
    xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.foo</groupId>
  <artifactId>bar</artifactId>
  <version>0.0.1-SNAPSHOT</version>

  <dependencies>

    <!-- https://mvnrepository.com/artifact/com.microsoft.azure.cognitiveservices/azure-cognitiveservices-luis-authoring -->
    <dependency>
      <groupId>com.microsoft.azure.cognitiveservices</groupId>
      <artifactId>azure-cognitiveservices-luis-authoring</artifactId>
      <version>1.0.2-beta</version>
    </dependency>

    <!-- https://mvnrepository.com/artifact/com.microsoft.azure.cognitiveservices/azure-cognitiveservices-luis-runtime -->
    <dependency>
      <groupId>com.microsoft.azure.cognitiveservices</groupId>
      <artifactId>azure-cognitiveservices-luis-runtime</artifactId>
      <version>1.0.2-beta</version>
    </dependency>
    
    <!-- This fixes the following runtime warnings:
    SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
    SLF4J: Defaulting to no-operation (NOP) logger implementation
    SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
    -->
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-jdk14</artifactId>
      <version>1.7.25</version>
    </dependency>

  </dependencies>

  <build>
    <directory>lib</directory>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
        <configuration>
          <outputDirectory>
            ${project.build.directory}
          </outputDirectory>
        </configuration>
      </plugin>
    </plugins>
  </build>

</project>
```

quickstart.java
```
import com.microsoft.azure.cognitiveservices.language.luis.authoring.*;
import com.microsoft.azure.cognitiveservices.language.luis.authoring.models.*;
import com.microsoft.azure.cognitiveservices.language.luis.runtime.*;
import com.microsoft.azure.cognitiveservices.language.luis.runtime.models.*;

import java.io.*;
import java.lang.Object.*;
import java.time.format.DateTimeFormatter;  
import java.time.LocalDateTime; 
import java.util.*;
import java.net.*;

public class Quickstart {
	private static String subscription_key = System.getenv("LUIS_SUBSCRIPTION_KEY");
	// You must use the same region as you used to get your LUIS subscription keys. 
	private static String endpoint = System.getenv("LUIS_REGION") + ".api.cognitive.microsoft.com";
	private static com.microsoft.azure.cognitiveservices.language.luis.authoring.EndpointAPI authoring_region = com.microsoft.azure.cognitiveservices.language.luis.authoring.EndpointAPI.fromString(endpoint);
	private static com.microsoft.azure.cognitiveservices.language.luis.runtime.EndpointAPI runtime_region = com.microsoft.azure.cognitiveservices.language.luis.runtime.EndpointAPI.fromString(endpoint);

	public void create_application() {
		LUISAuthoringClient client = LUISAuthoringManager.authenticate(authoring_region, subscription_key);

		PrebuiltDomainCreateObject create_app_payload = new PrebuiltDomainCreateObject().withDomainName("HomeAutomation").withCulture("en-us");
		UUID app_id = client.apps().addCustomPrebuiltDomain(create_app_payload);
		System.out.println("Created LUIS app with ID " + app_id.toString());
	}

	public static void main(String[] args) {
		try {
			Quickstart quickstart = new Quickstart();
			quickstart.create_application();
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
}
```

**Expected behavior**
Apps.addCustomPrebuiltDomain does not throw.

**Setup (please complete the following information):**
 - OS: Windows 10 Enterprise 1803
 - IDE : None
 - Version of the Library used
    - azure-cognitiveservices-luis-runtime-1.0.2-beta.jar
    - azure-cognitiveservices-luis-authoring-1.0.2-beta.jar

**Additional context**
The necessity of the tokenizerVersion property can also be seen from the API testing console.

If you go to "Get LUIS prebuilt domains list" (https://westus.dev.cognitive.microsoft.com/docs/services/5890b47c39e2bb17b84a55ff/operations/59104cec5aca2f0b48c76be3) and use the console to send a request, you get back results such as:
```
{
  "name": "Calendar",
  "culture": "en-us",
  "tokenizerVersion": "1.0.0",
  "description": "The Calendar domain provides intent and entities for adding, deleting, or editing an appointment, checking participants availability, and finding information about a calendar event.",
  "examples": "-",
  "intents": [{
    "name": "AcceptEventEntry",
    "description": "-",
    "examples": "-"
  },
...
```

If you go to "Add prebuilt application" (https://westus.dev.cognitive.microsoft.com/docs/services/5890b47c39e2bb17b84a55ff/operations/59104e515aca2f0b48c76be5) and use the console to send the default request body:
```
{
	"domainName": "Web", 
	"culture": "en-us"
}
```
you get back the same response:
```
Response status

400 Bad Request
Response latency
111 ms
Response content

Pragma: no-cache
Apim-Request-Id: c0024d77-12bc-4063-8ec1-14ebae8a76a8
Request-Id: c0024d77-12bc-4063-8ec1-14ebae8a76a8
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
Request-Context: appId=cid-v1:26a3540d-a02a-4998-a060-715488fd769b
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
Cache-Control: no-store, proxy-revalidate, no-cache, max-age=0, private
Date: Mon, 08 Jul 2019 03:02:00 GMT
Content-Length: 116
Content-Type: application/json; charset=utf-8

{
  "error": {
    "code": "BadArgument",
    "message": "The tokenizer version cannot be null or empty."
  }
}
```

If you change the request body to:
```
{
	"domainName": "Web", 
	"culture": "en-us",
	"tokenizerVersion": "1.0.0"
}
```
and resend, you get back a successful response:
```
Response status

201 Created
Response latency
561 ms
Response content

Pragma: no-cache
Apim-Request-Id: 551b309f-5967-426b-bf98-cfff25895c59
Request-Id: 551b309f-5967-426b-bf98-cfff25895c59
Operation-Location: https://westus.api.cognitive.microsoft.com/luis/api/v2.0/apps/customprebuiltdomains/a9fb34c3-25be-4e92-9bc6-3370303803c2
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
Request-Context: appId=cid-v1:26a3540d-a02a-4998-a060-715488fd769b
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
Cache-Control: no-store, proxy-revalidate, no-cache, max-age=0, private
Date: Mon, 08 Jul 2019 03:14:09 GMT
Location: https://westus.api.cognitive.microsoft.com/luis/api/v2.0/apps/customprebuiltdomains/a9fb34c3-25be-4e92-9bc6-3370303803c2
Content-Length: 38
Content-Type: application/json; charset=utf-8

"a9fb34c3-25be-4e92-9bc6-3370303803c2"
```

It looks like a tokenizerVersion property needs to be added to PrebuiltDomain (https://github.com/Azure/azure-sdk-for-java/blob/master/cognitiveservices/data-plane/language/luis/authoring/src/main/java/com/microsoft/azure/cognitiveservices/language/luis/authoring/models/PrebuiltDomain.java).

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by maggiepint** [comment]
Thanks for the feedback. I have routed to the appropriate service team for follow-up.
