### ISSUE TITLE
[BUG][JAVA SDK]subnet's method "listNetworkInterfaceIPConfigurations" throws an exception in case of Bastion's subnet but it works for normal subnet.

### ISSUE THREAD

**Issue by abhishekpankaj54** [Azure/azure-sdk-for-java#43070]
**Describe the bug**
We use the method listNetworkInterfaceIPConfigurations to list the network interface IP configuration of the subnet but it throws an exception for bastion's subnet.  I observed below:

Bastion's Subnet: It does not have an interface and it throws an exception  like the below:
 Got exception
com.azure.core.management.exception.ManagementException: Status code 404, "{"error":{"code":"ResourceNotFound","message":"The Resource 'Microsoft.Network/networkInterfaces/TESTBASTION' under resource group 'TESTBASTION' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix"}}"
        at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
        at com.azure.core.implementation.MethodHandleReflectiveInvoker.invokeWithArguments(MethodHandleReflectiveInvoker.java:35)
        at com.azure.core.implementation.http.rest.ResponseExceptionConstructorCache.invoke(ResponseExceptionConstructorCache.java:51)
        at com.azure.core.implementation.http.rest.RestProxyBase.instantiateUnexpectedException(RestProxyBase.java:356)
        at com.azure.core.implementation.http.rest.AsyncRestProxy.lambda$ensureExpectedStatus$1(AsyncRestProxy.java:128)
        at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:113)
        at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2400)
        at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:171)
        at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:2196)
        at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:2070)
        at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:96)
        at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:55)
        at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157)
        at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129)
        at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onNext(FluxHide.java:137)
        at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:122)
        at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
        at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1839)
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151)
        at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1839)
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151)

Other subnet: Even if we do not have an interface too it does not throw any exception. it simple return an response as null/blank like below:

DEBUG_LOG after listNetworkInterfaceIPConfigurations[]

***Exception or Stack Trace***
Got exception
com.azure.core.management.exception.ManagementException: Status code 404, "{"error":{"code":"ResourceNotFound","message":"The Resource 'Microsoft.Network/networkInterfaces/TESTBASTION' under resource group 'TESTBASTION' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix"}}"
        at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
        at com.azure.core.implementation.MethodHandleReflectiveInvoker.invokeWithArguments(MethodHandleReflectiveInvoker.java:35)
        at com.azure.core.implementation.http.rest.ResponseExceptionConstructorCache.invoke(ResponseExceptionConstructorCache.java:51)
        at com.azure.core.implementation.http.rest.RestProxyBase.instantiateUnexpectedException(RestProxyBase.java:356)
        at com.azure.core.implementation.http.rest.AsyncRestProxy.lambda$ensureExpectedStatus$1(AsyncRestProxy.java:128)
        at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:113)
        at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2400)
        at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:171)
        at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:2196)
        at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:2070)
        at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:96)
        at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:55)
        at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157)
        at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129)
        at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onNext(FluxHide.java:137)
        at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:122)
        at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
        at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1839)
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151)
        at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1839)
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151)

**To Reproduce**
Just create the bastion and its Vnet and subnet newly write a sample program and use below method 

Collection<NicIpConfiguration> nicIPConfigurations = subnet.listNetworkInterfaceIPConfigurations();

***Code Snippet***
Collection<NicIpConfiguration> nicIPConfigurations = subnet.listNetworkInterfaceIPConfigurations();

**Expected behavior**
it should return null or value but not exception.
**Screenshots**

**Setup (please complete the following information):**
 - IDE: [e.g. IntelliJ]
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)] package com.azure.resourcemanager.network.models;
 - class name:
public interface Subnet extends HasInnerModel<SubnetInner>, ChildResource<Network> {

    /**
     * @return network interface IP configurations that are associated with this subnet
     *     <p>Note that this call may result in multiple calls to Azure to fetch all the referenced interfaces each time
     *     it is invoked.
     */
    Collection<NicIpConfiguration> listNetworkInterfaceIPConfigurations(); 

 - Java version: [e.g. 8] java 17
 - App Server/Environment: [e.g. Tomcat, WildFly, Azure Function, Apache Spark, Databricks, IDE plugin or anything special]
 - Frameworks: [e.g. Spring Boot, Micronaut, Quarkus, etc] 

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by abhishekpankaj54** [comment]
@weidongxu-microsoft , Could you Please look into this Urgently?

**Comment by weidongxu-microsoft** [comment]
@abhishekpankaj54 

Would you let me know about the detail of the bastion? (I'd need to be sure what to do to reproduce)
Is it created via e.g. below?
```java
        azure.networks().manager().serviceClient().getBastionHosts()
                .createOrUpdate(rgName, "bastion1weidxu",
                        new BastionHostInner()
                                .withLocation(region.toString())
                                .withIpConfigurations(Collections.singletonList(
                                        new BastionHostIpConfiguration()
                                                .withName("ipconfig1")
                                                .withSubnet(network.subnets().get("AzureBastionSubnet").innerModel())
                                                .withPrivateIpAllocationMethod(IpAllocationMethod.DYNAMIC)
                                                .withPublicIpAddress(new SubResource().withId(publicIpBastion.id())))));
```

Then we call `listNetworkInterfaceIPConfigurations` on the subnet (`AzureBastionSubnet` as above)?

**Comment by abhishekpankaj54** [comment]
@weidongxu-microsoft ,

Here are the details:

Bastion: Created via Portal, which has the default bastion subnet.

I have attached the screenshot of Bastion. ![Image](https://github.com/user-attachments/assets/7459df31-8132-4db7-81cb-04cfaffdacfd)


Program snippet:

We first get all Virtual networks of the specific region and fetch the subnet's details(like name,id , and all) of each Virtual network by looping. 

Collection<NicIpConfiguration> nicIPConfigurations = subnet.listNetworkInterfaceIPConfigurations();


Our program does not have any extra calls for Bastion. It simply gets the Vnet loops, each of the Vnet gets the details of the subnet, and stores them in the map.

**Comment by weidongxu-microsoft** [comment]
PR https://github.com/Azure/azure-sdk-for-java/pull/43082

**Comment by abhishekpankaj54** [comment]
@weidongxu-microsoft , When are you going to release this fix? ETA and Version, please.

**Comment by weidongxu-microsoft** [comment]
@abhishekpankaj54 

The next release would be 2.45.0 this week.

I am still thinking what happens to the case that the NIC could not be find. And what SDK should do in such case (throw, or log error).

**Comment by XiaofeiCao** [comment]
> This is not only happening for Bastion I just saw it failed for one of my normal Vnet, but when I checked the connected device of this Vnet it showed that NIC but when I clicked on that it showed resource not found

@abhishekpankaj54 Is this 404 NIC deleted? Maybe this is a bug for `Connected devices` that even if the NIC is deleted, it still shows this deleted NIC.

**Comment by abhishekpankaj54** [comment]
@XiaofeiCao , @weidongxu-microsoft ,

It looks like there are two bugs for me:

1)The UI shows the deleted NIC.
2)The method listNetworkInterfaceIPConfigurations also tries to list the deleted NIC.
   I got the same error with  "listNetworkInterfaceIPConfigurations"

"Exception in thread "main" com.azure.core.management.exception.ManagementException: Status code 404, "{"error":{"code":"ResourceNotFound","message":"The Resource 'Microsoft.Network/networkInterfaces/ENV1913AZ-NIC' under resource group 'ENV1913AZ-RESOURCEGROUP' was not found. For more details please go to [https://aka.ms/ARMResourceNotFoundFix"}}](https://aka.ms/ARMResourceNotFoundFix%22%7D%7D)": The Resource 'Microsoft.Network/networkInterfaces/ENV1913AZ-NIC' under resource group 'ENV1913AZ-RESOURCEGROUP' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix"


@XiaofeiCao , I have the necessary permissions, and if it is a permission issue, then why listNetworkInterfaceIPConfigurations is also throwing the same error 404.

**Comment by abhishekpankaj54** [comment]
@weidongxu-microsoft , Are we going to handle both(bastion and normal subnet(deleted NIC)) the case in the fix?

**Comment by weidongxu-microsoft** [comment]
Yes, I am also ignoring the 404 in the fix (log a warning instead).

**Comment by abhishekpankaj54** [comment]
@weidongxu-microsoft , Thanks for the Update, please update me once it is released.

**Comment by weidongxu-microsoft** [comment]
@abhishekpankaj54 
2.45.0 released

**Comment by abhishekpankaj54** [comment]
@weidongxu-microsoft ,



One of my partners is getting the below error for the "Virtual network gateway":
Subnet name:GatewaySubnet 
Doing the same Method calls subnet.listNetworkInterfaceIPConfigurations()


Got exception 
com.google.common.util.concurrent.UncheckedExecutionException: com.azure.core.management.exception.ManagementException: Status code 404, "{"error":{"code":"ResourceNotFound","message":"The Resource 'Microsoft.Network/networkInterfaces/AZ-BCDR-VPNGW-NE' under resource group 'RG-NETWORK-P-NE' was not found. For more details please go to [https://aka.ms/ARMResourceNotFoundFix"}}":](https://aka.ms/ARMResourceNotFoundFix%22%7D%7D%22:) The Resource 'Microsoft.Network/networkInterfaces/AZ-BCDR-VPNGW-NE' under resource group 'RG-NETWORK-P-NE' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix

**Comment by weidongxu-microsoft** [comment]
Is it on the 2.45.0?

The code should catch 404 from the NIC.
https://github.com/Azure/azure-sdk-for-java/blob/azure-resourcemanager-network_2.45.0/sdk/resourcemanager/azure-resourcemanager-network/src/main/java/com/azure/resourcemanager/network/implementation/SubnetImpl.java#L263-L270
(I even had a mistake of not rethrowing the exception, if not 404)

**Comment by abhishekpankaj54** [comment]
@weidongxu-microsoft , Yes, it is 2.45.0.

**Comment by abhishekpankaj54** [comment]
@weidongxu-microsoft , Can you please fix this and provide it Today?

**Comment by weidongxu-microsoft** [comment]
No. I cannot reproduce this.

I tested by getting to the API, delete the NIC, and finish the API. I didn't get the exception.

**Comment by abhishekpankaj54** [comment]
@weidongxu-microsoft ,

I do not have a full stack, but I have below 

Got exception 
com.google.common.util.concurrent.UncheckedExecutionException: com.azure.core.management.exception.ManagementException: Status code 404, "{"error":{"code":"ResourceNotFound","message":"The Resource 'Microsoft.Network/networkInterfaces/AZ-BCDR-VPNGW-NE' under resource group 'RG-NETWORK-P-NE' was not found. For more details please go to [https://aka.ms/ARMResourceNotFoundFix"}}":](https://aka.ms/ARMResourceNotFoundFix%22%7D%7D%22:) The Resource 'Microsoft.Network/networkInterfaces/AZ-BCDR-VPNGW-NE' under resource group 'RG-NETWORK-P-NE' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2086)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4012)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4035)

I have asked for the full stack. I'll be sure to reach out to you once I receive it.

**Comment by abhishekpankaj54** [comment]
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 common frames omitted
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:100)
		at reactor.core.publisher.Mono.block(Mono.java:1742)
		at com.azure.resourcemanager.resources.fluentcore.arm.collection.implementation.GroupableResourcesImpl.getById(GroupableResourcesImpl.java:62)
		at com.azure.resourcemanager.resources.fluentcore.arm.collection.implementation.GroupableResourcesImpl.getById(GroupableResourcesImpl.java:28)
		at com.azure.resourcemanager.network.implementation.SubnetImpl.listNetworkInterfaceIPConfigurations(SubnetImpl.java:242)
		at com.emc.cloud_dr.cdr.azure_adapter.service.impl.network.NetworkFacade.getOccupiedNetworkInterfaces(NetworkFacade.java:179)
		at com.emc.cloud_dr.cdr.azure_adapter.service.impl.vm.VmFacade.buildSubnetsList(VmFacade.java:352)
		at com.emc.cloud_dr.cdr.azure_adapter.service.impl.vm.VmFacade.lambda$getCloudTargetNetworksFromProvider$6(VmFacade.java:293)
		at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
		at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
		at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
		at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
		at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
		at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
		at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
		at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
		at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
		at com.emc.cloud_dr.cdr.azure_adapter.service.impl.vm.VmFacade.getCloudTargetNetworksFromProvider(VmFacade.java:294)

**Comment by abhishekpankaj54** [comment]
@weidongxu-microsoft ,

Screenshot of the RG
![Image](https://github.com/user-attachments/assets/774f055e-c736-4d38-bbfa-c38ff50fc9e5)

**Comment by weidongxu-microsoft** [comment]
@abhishekpankaj54 

Please help check the versions used by your partner?

Line 242 in 2.45.0 is here (which is not a code line at all)
https://github.com/Azure/azure-sdk-for-java/blob/azure-resourcemanager-network_2.45.0/sdk/resourcemanager/azure-resourcemanager-network/src/main/java/com/azure/resourcemanager/network/implementation/SubnetImpl.java#L242

In 2.43.0, line 242 is the code that now get fixed in 2.45.0
https://github.com/Azure/azure-sdk-for-java/blob/azure-resourcemanager-network_2.43.0/sdk/resourcemanager/azure-resourcemanager-network/src/main/java/com/azure/resourcemanager/network/implementation/SubnetImpl.java#L242

**Comment by abhishekpankaj54** [comment]
@weidongxu-microsoft , 

I only provided the Jar which compiled with 2.45.0 Azure SDK.

![Image](https://github.com/user-attachments/assets/980a4046-a7f2-47aa-900b-0c01ba7ab1ee)

**Comment by weidongxu-microsoft** [comment]
The exact version of lib used could be from your partner's pom.xml, and susceptible to transitive poms from other libs.

One can run e.g. `mvn dependency:tree` to check what's the version of lib used by their project.
Example (need some change in commandline) https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/resourcemanager#dependency-management

**Comment by abhishekpankaj54** [comment]
@weidongxu-microsoft, Last time, I reported the Bastion Subnet issue, which is not coming at all using the same Jar with 2.45.0, but now it's happening something wrong here for Virtual Network Gateway. 

I saw that line 242 is not a part of the 2.45.0, but I am not sure why it points to 2.43.0, I am using the latest SDK version

**Comment by abhishekpankaj54** [comment]
@weidongxu-microsoft , let me check the mvn dependency:tree

**Comment by abhishekpankaj54** [comment]
@weidongxu-microsoft ,

Using the same SDK version 2.45.0

![Image](https://github.com/user-attachments/assets/4bc0e8e6-5d96-452b-8f62-da865bf28865)

**Comment by abhishekpankaj54** [comment]
@weidongxu-microsoft ,

I am using the same Version 2.45.0

![Image](https://github.com/user-attachments/assets/903fed41-7311-46c1-9fb3-fdc95b2d6640)

**Comment by weidongxu-microsoft** [comment]
@abhishekpankaj54 

I mean, if you provide the JAR (with or without your pom) to another project, it is their pom (and the `mvn dependency:tree` ran on their project) decides the version of SDK.

**Comment by abhishekpankaj54** [comment]
@weidongxu-microsoft ,

Last time it was breaking for Azure Bastion subnet but this time you can see it passing it but breaking VNG.

**AzureBastionSubnet**

2024-11-28T12:46:40.351Z DEBUG [] [https-jsse-nio-127.0.0.1-8462-exec-3] [][][][][] [c.e.c.c.a.s.i.n.NetworkFacade.getOccupiedNetworkInterfaces(178)] -  DEBUG_LOG inside listNetworkInterfaceIPConfigurations subnet.name: AzureBastionSubnet 
2024-11-28T12:46:40.351Z DEBUG [] [https-jsse-nio-127.0.0.1-8462-exec-3] [][][][][] [c.e.c.c.a.s.i.n.NetworkFacade.getOccupiedNetworkInterfaces(180)] -  DEBUG_LOG after listNetworkInterfaceIPConfigurations:[] 
2024-11-28T12:46:40.352Z DEBUG [] [https-jsse-nio-127.0.0.1-8462-exec-3] [][][][][] [c.e.c.c.a.s.i.n.NetworkFacade.getOccupiedNetworkInterfaces(181)] -  DEBUG_LOG after getReservedIPs:[172.17.8.193, 172.17.8.194, 172.17.8.195, 172.17.8.196, 172.17.8.255] 
2024-11-28T12:46:40.353Z DEBUG [] [https-jsse-nio-127.0.0.1-8462-exec-3] [][][][][] [c.e.c.c.a.s.i.n.NetworkFacade.getOccupiedNetworkInterfaces(184)] -  DEBUG_LOG after occupiedIPs:[172.17.8.193, 172.17.8.194, 172.17.8.195, 172.17.8.196, 172.17.8.255] 
2024-11-28T12:46:40.353Z DEBUG [] [https-jsse-nio-127.0.0.1-8462-exec-3] [][][][][] [c.e.c.c.a.s.i.n.NetworkFacade.getOccupiedNetworkInterfaces(178)] -  DEBUG_LOG inside listNetworkInterfaceIPConfigurations subnet.name: GatewaySubnet 
2024-11-28T12:46:40.559Z ERROR [] [https-jsse-nio-127.0.0.1-8462-exec-3] [][][][][] [c.e.c.c.c.s.i.AbstractVmFacade.getCloudTargetNetworks(34)] -  Got exception 
com.google.common.util.concurrent.UncheckedExecutionException: com.azure.core.management.exception.ManagementException: Status code 404, "{"error":{"code":"ResourceNotFound","message":"The Resource 'Microsoft.Network/networkInterfaces/AZ-BCDR-VPNGW-NE' under resource group 'RG-NETWORK-P-NE' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix"}}": The Resource 'Microsoft.Network/networkInterfaces/AZ-BCDR-VPNGW-NE' under resource group 'RG-NETWORK-P-NE' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix

**Comment by abhishekpankaj54** [comment]
In my maven Project, I have only one version 2.45.0

![Image](https://github.com/user-attachments/assets/17a14c7d-7cac-401b-9979-8a4e57205ab5)

**Comment by weidongxu-microsoft** [comment]
That's strange.

Still checking what other possibilities could be...

@XiaofeiCao any thought?

**Comment by XiaofeiCao** [comment]
@abhishekpankaj54 is the partner experiencing this exception the same as the one who experienced Bastion error?

**Comment by abhishekpankaj54** [comment]
@XiaofeiCao , Yes, First my Partner got the Bastion Issue and later I reproduced it in my Lab, so both had a Bastion issue. Now with 2.45.0, it working fine. I did not observe any Issue related to Bastion.

**Comment by weidongxu-microsoft** [comment]
@abhishekpankaj54 

In my test, it does not be a problem in 2.45.0.

The actual resource type under "GatewaySubnet" would be "virtualNetworkGateways", which in 2.45.0 is excluded from the `nic = this.parent().manager().networkInterfaces().getById(nicID);` line.

test code
```java
        var vnet1 = networkManager.networks().getById("/subscriptions/<>/resourceGroups/rg-weidxu-test/providers/Microsoft.Network/virtualNetworks/vnet1");
        var subnet1 = vnet1.subnets().get("GatewaySubnet");
        var collection1 = subnet1.listNetworkInterfaceIPConfigurations();
```

code in SubnetImpl
![Image](https://github.com/user-attachments/assets/ae96dfb8-9283-49df-9792-d40f310b1d7a)

You can see line
```
if ("networkInterfaces".equalsIgnoreCase(resourceType)) {
```
just exclude it from further processing.

**Comment by weidongxu-microsoft** [comment]
Would there be another lib/JAR that using a different version of azure-resourcemanager-network be included in your partner's POM?

**Comment by abhishekpankaj54** [comment]
> [@abhishekpankaj54](https://github.com/abhishekpankaj54) Got it. This is super weird and seems your partner is running 2 versions of SDKs.
> 
> Did previous Bastion error fail for the same line?
> 
> > at com.emc.cloud_dr.cdr.azure_adapter.service.impl.network.NetworkFacade.getOccupiedNetworkInterfaces(NetworkFacade.java:179)

Yes, here the logs from my lab for BASTION one:
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        ... 1 common frames omitted
        Suppressed: java.lang.Exception: #block terminated with an error
                at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
                at reactor.core.publisher.Mono.block(Mono.java:1742)
                at com.azure.resourcemanager.resources.fluentcore.arm.collection.implementation.GroupableResourcesImpl.getById(GroupableResourcesImpl.java:62)
                at com.azure.resourcemanager.resources.fluentcore.arm.collection.implementation.GroupableResourcesImpl.getById(GroupableResourcesImpl.java:28)
                at com.azure.resourcemanager.network.implementation.SubnetImpl.listNetworkInterfaceIPConfigurations(SubnetImpl.java:261)
                at com.emc.cloud_dr.cdr.azure_adapter.service.impl.network.NetworkFacade.getOccupiedNetworkInterfaces(NetworkFacade.java:179)
                at com.emc.cloud_dr.cdr.azure_adapter.service.impl.vm.VmFacade.buildSubnetsList(VmFacade.java:352)
                at com.emc.cloud_dr.cdr.azure_adapter.service.impl.vm.VmFacade.lambda$getCloudTargetNetworksFromProvider$6(VmFacade.java:293)
                at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
                at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
                at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
                at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)

**Comment by weidongxu-microsoft** [comment]
Yes, the stack on your stack matches that from 2.44.0
https://github.com/Azure/azure-sdk-for-java/blob/azure-resourcemanager-network_2.44.0/sdk/resourcemanager/azure-resourcemanager-network/src/main/java/com/azure/resourcemanager/network/implementation/SubnetImpl.java#L261

Just the stack from your partner does not match either 2.44.0 nor 2.45.0
```
	at com.azure.resourcemanager.resources.fluentcore.arm.collection.implementation.GroupableResourcesImpl.getById(GroupableResourcesImpl.java:62)
	at com.azure.resourcemanager.resources.fluentcore.arm.collection.implementation.GroupableResourcesImpl.getById(GroupableResourcesImpl.java:28)
	at com.azure.resourcemanager.network.implementation.SubnetImpl.listNetworkInterfaceIPConfigurations(SubnetImpl.java:242)
```

**Comment by weidongxu-microsoft** [comment]
And same for the line in `GroupableResourcesImpl`.

2.43.0, line number (line 62) matches
https://github.com/Azure/azure-sdk-for-java/blob/azure-resourcemanager-network_2.43.0/sdk/resourcemanager/azure-resourcemanager-resources/src/main/java/com/azure/resourcemanager/resources/fluentcore/arm/collection/implementation/GroupableResourcesImpl.java#L62

2.45.0, line number does not match
https://github.com/Azure/azure-sdk-for-java/blob/azure-resourcemanager-network_2.45.0/sdk/resourcemanager/azure-resourcemanager-resources/src/main/java/com/azure/resourcemanager/resources/fluentcore/arm/collection/implementation/GroupableResourcesImpl.java#L62

**Comment by abhishekpankaj54** [comment]
@weidongxu-microsoft ,

One question, I do not see any getById present at line no 28 in both versions

	

at com.azure.resourcemanager.resources.fluentcore.arm.collection.implementation.GroupableResourcesImpl.getById(GroupableResourcesImpl.java:62)
	at com.azure.resourcemanager.resources.fluentcore.arm.collection.implementation.GroupableResourcesImpl.getById(GroupableResourcesImpl.java:28)
	at com.azure.resourcemanager.network.implementation.SubnetImpl.listNetworkInterfaceIPConfigurations(SubnetImpl.java:242)

**Comment by weidongxu-microsoft** [comment]
line 28 matches the class declaration (this is same for both versions)
![Image](https://github.com/user-attachments/assets/f03fc6f0-db8d-428e-8589-95e6ab8ac9b7)

(stack within a captured ManagementException)

**Comment by abhishekpankaj54** [comment]
@weidongxu-microsoft , 

How come line no 28, can point to the class name instead of the method call in the logs trace?

com.azure.resourcemanager.resources.fluentcore.arm.collection.implementation.GroupableResourcesImpl.getById(GroupableResourcesImpl.java:28)

**Comment by weidongxu-microsoft** [comment]
This would be the design of stack by Java/Oracle. I am not exactly sure when the line be logged. Maybe because the actual `getById` method is defined in `SupportsGettingById` interface, and `GroupableResourcesImpl implements SupportsGettingById<T>`.
