### ISSUE TITLE
[BUG] not compatible with spring-boot 3.4.0 GA

### ISSUE THREAD

**Issue by davidkarlsen** [Azure/azure-sdk-for-java#43085]
**Describe the bug**

The SDK is not compatible with latest spring-boot 3.4.0 GA release, as the deprecated class `TaskExecutorBuilder` has been removed from this release.

***Exception or Stack Trace***

```text

	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:336)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:288)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:334)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1568)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1514)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:913)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
	... 59 more
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor]: Factory method 'credentialTaskExecutor' threw exception with message: org/springframework/boot/task/TaskExecutorBuilder
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.lambda$instantiate$0(SimpleInstantiationStrategy.java:199)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiateWithFactoryMethod(SimpleInstantiationStrategy.java:88)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:168)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
	... 72 more
Caused by: java.lang.NoClassDefFoundError: org/springframework/boot/task/TaskExecutorBuilder
	at com.azure.spring.cloud.autoconfigure.implementation.context.AzureTokenCredentialAutoConfiguration.credentialTaskExecutor(AzureTokenCredentialAutoConfiguration.java:221)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.lambda$instantiate$0(SimpleInstantiationStrategy.java:171)
	... 75 more
Caused by: java.lang.ClassNotFoundException: org.springframework.boot.task.TaskExecutorBuilder
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 78 more

```

**To Reproduce**

Use this SDK on SB 3.4.0

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**
Should work with GA-releases (and proactive development and release happen to be ready at GA-release dates).

**Screenshots**

**Setup (please complete the following information):**
 - IDE: [e.g. IntelliJ]
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)]
 - Java version: [e.g. 8] 
 - App Server/Environment: [e.g. Tomcat, WildFly, Azure Function, Apache Spark, Databricks, IDE plugin or anything special]
 - Frameworks: [e.g. Spring Boot, Micronaut, Quarkus, etc] 

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by moarychan** [comment]
https://github.com/Azure/azure-sdk-for-java/issues/43142

**Comment by moarychan** [comment]
https://github.com/Azure/azure-sdk-for-java/pull/43098

**Comment by moarychan** [comment]
This removal class `TaskExecutorBuilder` has been fixed in https://github.com/Azure/azure-sdk-for-java/pull/42760

**Comment by gbrehmer** [comment]
Is an earlier release for the removed-class-fix planned? Because this could also be applied to the old code to remove usage of a deprecated class. then some of the functionality would be already compatible with Spring boot 3.4.0 with full backwards compatibility

**Comment by saragluna** [comment]
Spring Cloud Azure 5.19.0 has been released.
