### ISSUE TITLE
Azure OpenAI - Netty implementation error during streaming chat message

### ISSUE THREAD

**Issue by iAMSagar44** [Azure/azure-sdk-for-java#43191]
**Bug**
When I am invoking the streaming capability of the LLM I am regularly getting this warning message in the logs. This is usually happening for every 3 out of 5 messages exchanged between the user and the LLM.

***Stack Trace***

> **2024-12-04 12:45:29 WARN  i.n.u.c.AbstractEventExecutor - A task raised an exception. Task: com.azure.core.http.netty.implementation.NettyUtility$$Lambda/0x000000d001900240@117da9d2
> java.lang.IllegalStateException: channel not registered to an event loop**
> 	at io.netty.channel.AbstractChannel.eventLoop(AbstractChannel.java:163)
> 	at io.netty.channel.AbstractChannelHandlerContext.executor(AbstractChannelHandlerContext.java:132)
> 	at io.netty.channel.AbstractChannelHandlerContext.newPromise(AbstractChannelHandlerContext.java:1011)
> 	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:560)
> 	at io.netty.channel.DefaultChannelPipeline.close(DefaultChannelPipeline.java:906)
> 	at io.netty.channel.AbstractChannel.close(AbstractChannel.java:243)
> 	at reactor.netty.http.client.HttpClientOperations.onInboundCancel(HttpClientOperations.java:302)
> 	at reactor.netty.channel.FluxReceive.disposeAndUnsubscribeReceiver(FluxReceive.java:490)
> 	at reactor.netty.channel.FluxReceive.lambda$new$0(FluxReceive.java:86)
> 	at reactor.netty.channel.FluxReceive.cancelReceiver(FluxReceive.java:199)
> 	at reactor.netty.channel.FluxReceive.doCancel(FluxReceive.java:205)
> 	at reactor.netty.channel.FluxReceive.dispose(FluxReceive.java:118)
> 	at reactor.netty.channel.ChannelOperations.discard(ChannelOperations.java:384)
> 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
> 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
> 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
> 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
> 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
> 	at java.base/java.lang.Thread.run(Thread.java:1583)

**To Reproduce**
Invoke the streaming capability of the Azure OpenAI chat model GPT4o. Below is the dependency I am using -

```
<dependency>
      <groupId>com.azure</groupId>
      <artifactId>azure-ai-openai</artifactId>
      <version>1.0.0-beta.12</version>
      <scope>compile</scope>
</dependency>
```

**Setup:**
 - OS: MacOS
 - IDE: VsCode
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)]
 - Java version: 21
 - App Server/Environment: Tomcat
 - Frameworks: Spring Boot and Spring AI 1.0.0-beta.12
 - LLM - GPT4o
 - Azure SDK version -Azure AI OpenAI

**Comment by joshfree** [comment]
Thanks for reporting this @iAMSagar44; we may need some additional information in order to assist here.  @mssfang and @anuchandy could you please follow up with @iAMSagar44 here?

**Comment by mssfang** [comment]
@iAMSagar44 Do you have a sample that we can use to reproduce the warning messages in the logs.

**Comment by jpalvarezl** [comment]
The Azure OpenAI Inference SDK has been deprecated in its current form. This package will be repurposed to provide Azure types to be used with the official OpenAI Java SDK in the future, but there is not much detail I can provide at this point in time, as things are still in flux. We have provided a basic migration guide for this in [this folder](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/openai/azure-ai-openai-stainless).
