### ISSUE TITLE
[BUG] Spring Cloud Azure Service Bus JMS Cannot disable JmsPoolConnectionFactory

### ISSUE THREAD

**Issue by Saljack** [Azure/azure-sdk-for-java#43279]
**Describe the bug**
With enabling `JmsPoolConnectionFactory` as default you introduced `AzureServiceBusJmsPropertiesEnvironmentPostProcessor` that set `spring.jms.servicebus.pool.enabled`. I would like to disable `JmsPoolConnectionFactory` and use `SimpleConnectionFactory` because it throws this exception for "shared" subscriptions:
```
2024-12-05 14:01:48.010 [-][-][-][ WARN] [,] myservice-86f75bcbfc-64s7d --- [ontainer#3-1564] o.s.j.l.DefaultMessageListenerContainer  : Setup of JMS message listener invoker failed for destination 'mydestination' - trying to recover. Cause: A non-shared durable subscription is already active with name 'myservice'
2024-12-05 14:01:53.012 [-][-][-][ERROR] [,] myservice-86f75bcbfc-64s7d --- [ontainer#3-1565] class : Unable to process JMS message
jakarta.jms.JMSException: A non-shared durable subscription is already active with name 'myservice'
	at org.apache.qpid.jms.provider.ProviderException.toJMSException(ProviderException.java:34)
	at org.apache.qpid.jms.exceptions.JmsExceptionSupport.create(JmsExceptionSupport.java:80)
	at org.apache.qpid.jms.exceptions.JmsExceptionSupport.create(JmsExceptionSupport.java:112)
	at org.apache.qpid.jms.JmsConnection.createResource(JmsConnection.java:698)
	at org.apache.qpid.jms.JmsMessageConsumer.<init>(JmsMessageConsumer.java:125)
	at org.apache.qpid.jms.JmsTopicSubscriber.<init>(JmsTopicSubscriber.java:36)
	at org.apache.qpid.jms.JmsDurableTopicSubscriber.<init>(JmsDurableTopicSubscriber.java:29)
	at org.apache.qpid.jms.JmsSession.createDurableSubscriber(JmsSession.java:583)
	at com.azure.servicebus.jms.ServiceBusJmsSession.createDurableSubscriber(ServiceBusJmsSession.java:160)
	at org.messaginghub.pooled.jms.JmsPoolSession.createDurableSubscriber(JmsPoolSession.java:383)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.createConsumer(AbstractMessageListenerContainer.java:920)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.createListenerConsumer(AbstractPollingMessageListenerContainer.java:225)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.initResourcesIfNecessary(DefaultMessageListenerContainer.java:1454)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1419)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1410)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1287)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: org.apache.qpid.jms.provider.ProviderException: A non-shared durable subscription is already active with name 'myservice'
	at org.apache.qpid.jms.provider.exceptions.ProviderExceptionSupport.createNonFatalOrPassthrough(ProviderExceptionSupport.java:71)
	at org.apache.qpid.jms.provider.amqp.AmqpProvider.lambda$create$4(AmqpProvider.java:495)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:405)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	... 1 more
Caused by: jakarta.jms.JMSRuntimeException: A non-shared durable subscription is already active with name 'myservice'
	at org.apache.qpid.jms.provider.amqp.builders.AmqpConsumerBuilder.createEndpoint(AmqpConsumerBuilder.java:104)
	at org.apache.qpid.jms.provider.amqp.builders.AmqpConsumerBuilder.createEndpoint(AmqpConsumerBuilder.java:64)
	at org.apache.qpid.jms.provider.amqp.builders.AmqpResourceBuilder.buildResource(AmqpResourceBuilder.java:81)
	at org.apache.qpid.jms.provider.amqp.AmqpSession.createConsumer(AmqpSession.java:112)
	at org.apache.qpid.jms.provider.amqp.AmqpProvider$2.processConsumerInfo(AmqpProvider.java:442)
	at org.apache.qpid.jms.meta.JmsConsumerInfo.visit(JmsConsumerInfo.java:282)
	at org.apache.qpid.jms.provider.amqp.AmqpProvider.lambda$create$4(AmqpProvider.java:420)
	... 7 more
2024-12-05 14:01:53.013 [-][-][-][ WARN] [,] myservice-86f75bcbfc-64s7d --- [ontainer#3-1565] o.s.j.l.DefaultMessageListenerContainer  : Setup of JMS message listener invoker failed for destination 'mydestination' - trying to recover. Cause: A non-shared durable subscription is already active with name 'myservice'
2024-12-05 14:01:58.014 [-][-][-][ERROR] [,] myservice-86f75bcbfc-64s7d --- [ontainer#3-1566] f.s.j.DfAzureServiceBusAutoConfiguration : Unable to process JMS message
jakarta.jms.JMSException: A non-shared durable subscription is already active with name 'myservice'
	at org.apache.qpid.jms.provider.ProviderException.toJMSException(ProviderException.java:34)
	at org.apache.qpid.jms.exceptions.JmsExceptionSupport.create(JmsExceptionSupport.java:80)
	at org.apache.qpid.jms.exceptions.JmsExceptionSupport.create(JmsExceptionSupport.java:112)
	at org.apache.qpid.jms.JmsConnection.createResource(JmsConnection.java:698)
	at org.apache.qpid.jms.JmsMessageConsumer.<init>(JmsMessageConsumer.java:125)
	at org.apache.qpid.jms.JmsTopicSubscriber.<init>(JmsTopicSubscriber.java:36)
	at org.apache.qpid.jms.JmsDurableTopicSubscriber.<init>(JmsDurableTopicSubscriber.java:29)
	at org.apache.qpid.jms.JmsSession.createDurableSubscriber(JmsSession.java:583)
	at com.azure.servicebus.jms.ServiceBusJmsSession.createDurableSubscriber(ServiceBusJmsSession.java:160)
	at org.messaginghub.pooled.jms.JmsPoolSession.createDurableSubscriber(JmsPoolSession.java:383)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.createConsumer(AbstractMessageListenerContainer.java:920)
	at org.apache.qpid.jms.provider.amqp.AmqpProvider.lambda$create$4(AmqpProvider.java:495)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:405)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	... 1 more
Caused by: jakarta.jms.JMSRuntimeException: A non-shared durable subscription is already active with name 'myservice'
	at org.apache.qpid.jms.provider.amqp.builders.AmqpConsumerBuilder.createEndpoint(AmqpConsumerBuilder.java:104)
	at org.apache.qpid.jms.provider.amqp.builders.AmqpConsumerBuilder.createEndpoint(AmqpConsumerBuilder.java:64)
	at org.apache.qpid.jms.provider.amqp.builders.AmqpResourceBuilder.buildResource(AmqpResourceBuilder.java:81)
	at org.apache.qpid.jms.provider.amqp.AmqpSession.createConsumer(AmqpSession.java:112)
	at org.apache.qpid.jms.provider.amqp.AmqpProvider$2.processConsumerInfo(AmqpProvider.java:442)
	at org.apache.qpid.jms.meta.JmsConsumerInfo.visit(JmsConsumerInfo.java:282)
	at org.apache.qpid.jms.provider.amqp.AmqpProvider.lambda$create$4(AmqpProvider.java:420)
	... 7 more
```
When I enable durable shared subscriptions then I get another exception:
```
2024-12-05 20:27:21.127 [-][-][-][ WARN] [,] myservice-644799c885-4tp7p --- [ontainer#2-4490] o.s.j.l.DefaultMessageListenerContainer  : Setup of JMS message listener invoker failed for destination 'mydestination' - trying to recover. Cause: Subscription details dont match existing subscriber.
2024-12-05 20:27:26.139 [-][-][-][ERROR] [,] myservice-644799c885-4tp7p --- [ontainer#2-4491] class : Unable to process JMS message
jakarta.jms.JMSException: Subscription details dont match existing subscriber.
	at org.apache.qpid.jms.provider.ProviderException.toJMSException(ProviderException.java:34)
	at org.apache.qpid.jms.exceptions.JmsExceptionSupport.create(JmsExceptionSupport.java:80)
	at org.apache.qpid.jms.exceptions.JmsExceptionSupport.create(JmsExceptionSupport.java:112)
	at org.apache.qpid.jms.JmsConnection.createResource(JmsConnection.java:698)
	at org.apache.qpid.jms.JmsMessageConsumer.<init>(JmsMessageConsumer.java:125)
	at org.apache.qpid.jms.JmsSharedMessageConsumer.<init>(JmsSharedMessageConsumer.java:29)
	at org.apache.qpid.jms.JmsSharedDurableMessageConsumer.<init>(JmsSharedDurableMessageConsumer.java:29)
	at org.apache.qpid.jms.JmsSession.createSharedDurableConsumer(JmsSession.java:660)
	at com.azure.servicebus.jms.ServiceBusJmsSession.createSharedDurableConsumer(ServiceBusJmsSession.java:218)
	at org.messaginghub.pooled.jms.JmsPoolSession.createSharedDurableConsumer(JmsPoolSession.java:447)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.createConsumer(AbstractMessageListenerContainer.java:916)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.createListenerConsumer(AbstractPollingMessageListenerContainer.java:225)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.initResourcesIfNecessary(DefaultMessageListenerContainer.java:1454)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1419)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1410)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1287)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: org.apache.qpid.jms.provider.ProviderException: Subscription details dont match existing subscriber.
	at org.apache.qpid.jms.provider.exceptions.ProviderExceptionSupport.createNonFatalOrPassthrough(ProviderExceptionSupport.java:71)
	at org.apache.qpid.jms.provider.amqp.AmqpProvider.lambda$create$4(AmqpProvider.java:495)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:405)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	... 1 more
Caused by: jakarta.jms.JMSRuntimeException: Subscription details dont match existing subscriber.
	at org.apache.qpid.jms.provider.amqp.AmqpSubscriptionTracker.getSharedDurableSubLinkName(AmqpSubscriptionTracker.java:87)
	at org.apache.qpid.jms.provider.amqp.AmqpSubscriptionTracker.reserveNextSubscriptionLinkName(AmqpSubscriptionTracker.java:50)
	at org.apache.qpid.jms.provider.amqp.builders.AmqpConsumerBuilder.createEndpoint(AmqpConsumerBuilder.java:112)
	at org.apache.qpid.jms.provider.amqp.builders.AmqpConsumerBuilder.createEndpoint(AmqpConsumerBuilder.java:64)
	at org.apache.qpid.jms.provider.amqp.builders.AmqpResourceBuilder.buildResource(AmqpResourceBuilder.java:81)
	at org.apache.qpid.jms.provider.amqp.AmqpSession.createConsumer(AmqpSession.java:112)
	at org.apache.qpid.jms.provider.amqp.AmqpProvider$2.processConsumerInfo(AmqpProvider.java:442)
	at org.apache.qpid.jms.meta.JmsConsumerInfo.visit(JmsConsumerInfo.java:282)
	at org.apache.qpid.jms.provider.amqp.AmqpProvider.lambda$create$4(AmqpProvider.java:420)
	... 7 more
```
This is because we use the standard tier for testing environments (and the premium tier for production) which supports only JMS 1.1 and does not support shared durable subscriptions (even though all Azure Service Bus subscriptions are durable and shared by its design). It is driving me crazy because there is no solution without switching to the premium tier 😭

So it is impossible for me to use `JmsPoolConnectionFactory` factory and I have to use just the simple `ServiceBusJmsConnectionFactory`. It is not problem because we use this connection factory for long time without any performance problem (of course there well known issues with the whole Azure Service Bus and JMS). 

But I cannot simply set `spring.jms.servicebus.pool.enabled=false` in our shared library with `@PropertySource("classpath:library.properties")` that contains configuration for all our microservices. I can disable it directly in each microservice in its `application.yaml` but it means that I have to change more than 20 microservices. The whole problem is the `AzureServiceBusJmsPropertiesEnvironmentPostProcessor` it sets `spring.jms.servicebus.pool.enabled=true` before applying values from the `@PropertySource`. I think the whole problem is that this property is set as added as the first into `propertySources` and not as the last. 

It would be much better to enable this default value by a different way than using any `EnvironmentPostProcessor` because there is no way how to disable any `EnvironmentPostProcessor`.

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**
1. create a properties file e.g. `additional.properties` with content:
```
spring.jms.servicebus.pool.enabled=false
```
2. Add the properties file by `@PropertySource` e.g.:
```java
@Configuration
@PropertySource("classpath:additional.properties")
public class DefaultPropertiesConfiguration { }
```
3. `JmsPoolConnectionFactory jmsPoolConnectionFactory` is created but expected is `ServiceBusJmsConnectionFactory jmsConnectionFactory`
***Code Snippet***
See https://github.com/Azure/azure-sdk-for-java/blob/07eba9228857a5c29477d6913b09f7f43a024ba7/sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/implementation/jms/AzureServiceBusJmsPropertiesEnvironmentPostProcessor.java#L22
so change this line and use `addLast` instead `addFirst` :
```java
environment.getPropertySources().addLast(new MapPropertySource("azureServiceBusJms", azureServiceBusJms));
```

**Expected behavior**
Properties loaded by `@PropertySource` are applied instead of the default value from `AzureServiceBusJmsPropertiesEnvironmentPostProcessor`

**Screenshots**

**Setup (please complete the following information):**
 - OS: Windows/Linux
 - Library/Libraries: com.azure.spring:spring-cloud-azure-autoconfigure:5.18.0
 - Java version: 21
 - Frameworks: Spring Boot

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by Saljack** [comment]
I add my current workaround with adding a custom `EnvironmentPostProcessor`. This `EnvironmentPostProcessor` is applied before `AzureServiceBusJmsPropertiesEnvironmentPostProcessor`:
```java
class NullifyAzureServiceBusJmsPropertiesEnvironmentPostProcessor implements EnvironmentPostProcessor {

  @Override
  public void postProcessEnvironment(ConfigurableEnvironment environment, SpringApplication application) {
    if (!environment.containsProperty("spring.jms.servicebus.pool.enabled")) {
      environment.getPropertySources()
          .addFirst(new MapPropertySource("dfAzureServiceBusJms", Map.of("spring.jms.servicebus.pool.enabled", "false")));
    }
  }

}
```

**Comment by Saljack** [comment]
@Netyyyy and @moarychan Can you please reconsider the fixed code and try to find a better way how to autoconfigure ServiceBus JMS without `EnvironmentPostProcessor` and `ImportBeanDefinitionRegistrar` and using just simple `@ConditionalOnXXX`?  Or can you please explain why it is impossible and you have to use these nasty hacks?

**Comment by saragluna** [comment]
@Saljack sorry for any inconvenience, but we do want to improve this user experience. I left a comment here https://github.com/Azure/azure-sdk-for-java/pull/43373#issuecomment-2547802064.
