### ISSUE TITLE
Request body emitted 29863 bytes, more than the expected 29846 bytes.

### ISSUE THREAD

**Issue by pp4253biz** [Azure/azure-sdk-for-java#43286]
**Describe the bug**
Unable to write a json event stream to Azure Storage account as a blob.

***Exception or Stack Trace***
2024-12-06T17:39:05.1931057Z 2024-12-06T17:39:05.192Z ERROR 75 --- [p-nio-80-exec-4] com.azure.storage.common.Utility         : Request body emitted 29863 bytes, more than the expected 29846 bytes.
2024-12-06T17:39:05.1940864Z com.azure.core.exception.UnexpectedLengthException: Request body emitted 29863 bytes, more than the expected 29846 bytes.
2024-12-06T17:39:05.1948268Z            at com.azure.storage.common.Utility.lambda$convertStreamToByteBuffer$1(Utility.java:298)
2024-12-06T17:39:05.1948777Z            at reactor.core.publisher.FluxGenerate$GenerateSubscription.slowPath(FluxGenerate.java:271)
2024-12-06T17:39:05.1948859Z            at reactor.core.publisher.FluxGenerate$GenerateSubscription.request(FluxGenerate.java:213)
2024-12-06T17:39:05.1948950Z            at reactor.core.publisher.FluxFilter$FilterSubscriber.request(FluxFilter.java:186)
2024-12-06T17:39:05.1949017Z            at reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.request(FluxConcatMapNoPrefetch.java:336)
2024-12-06T17:39:05.1949117Z            at reactor.core.publisher.FluxSwitchOnFirst$AbstractSwitchOnFirstMain.onSubscribe(FluxSwitchOnFirst.java:499)
2024-12-06T17:39:05.1949184Z            at reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.onSubscribe(FluxConcatMapNoPrefetch.java:164)
2024-12-06T17:39:05.1949250Z            at reactor.core.publisher.FluxFilter$FilterSubscriber.onSubscribe(FluxFilter.java:85)
2024-12-06T17:39:05.1949331Z            at reactor.core.publisher.FluxGenerate.subscribe(FluxGenerate.java:85)
2024-12-06T17:39:05.1949396Z            at reactor.core.publisher.FluxDefer.subscribe(FluxDefer.java:54)
2024-12-06T17:39:05.1949461Z            at reactor.core.publisher.Mono.subscribe(Mono.java:4495)
2024-12-06T17:39:05.1949537Z            at reactor.core.publisher.Mono.block(Mono.java:1711)
2024-12-06T17:39:05.1949601Z            at com.azure.storage.common.implementation.StorageImplUtils.blockWithOptionalTimeout(StorageImplUtils.java:146)
2024-12-06T17:39:05.1949683Z            at com.azure.storage.blob.BlobClient.uploadWithResponse(BlobClient.java:337)
2024-12-06T17:39:05.1949747Z            at com.azure.storage.blob.BlobClient.uploadWithResponse(BlobClient.java:298)
2024-12-06T17:39:05.1949806Z            at com.azure.storage.blob.BlobClient.upload(BlobClient.java:243)
2024-12-06T17:39:05.1949884Z            at com.azure.storage.blob.BlobClient.upload(BlobClient.java:205)
2024-12-06T17:39:05.1949947Z            at com.att.dp.DDAPService.toDDAPStorage(DDAPService.java:86)
2024-12-06T17:39:05.1950006Z            at com.att.dp.WebHookController.webhookconsumer(WebHookController.java:43)
2024-12-06T17:39:05.1950088Z            at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
2024-12-06T17:39:05.1950157Z            at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2024-12-06T17:39:05.1950228Z            at java.base/java.lang.reflect.Method.invoke(Method.java:569)
2024-12-06T17:39:05.1950311Z            at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
2024-12-06T17:39:05.1950387Z            at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
2024-12-06T17:39:05.1950475Z            at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
2024-12-06T17:39:05.1950546Z            at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:756)
2024-12-06T17:39:05.1950627Z            at org.springframework.validation.beanvalidation.MethodValidationInterceptor.invoke(MethodValidationInterceptor.java:141)
2024-12-06T17:39:05.1950719Z            at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
2024-12-06T17:39:05.1950793Z            at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:756)
2024-12-06T17:39:05.1950874Z            at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
2024-12-06T17:39:05.1950942Z            at com.att.dp.WebHookController$$SpringCGLIB$$0.webhookconsumer(<generated>)
2024-12-06T17:39:05.1951013Z            at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
2024-12-06T17:39:05.1951090Z            at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2024-12-06T17:39:05.1951154Z            at java.base/java.lang.reflect.Method.invoke(Method.java:569)
2024-12-06T17:39:05.1951234Z            at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
2024-12-06T17:39:05.1951299Z            at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
2024-12-06T17:39:05.1951371Z            at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118)
2024-12-06T17:39:05.1951455Z            at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:884)
2024-12-06T17:39:05.1951525Z            at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
2024-12-06T17:39:05.1951612Z            at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
2024-12-06T17:39:05.1951680Z            at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1081)
2024-12-06T17:39:05.1951762Z            at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:974)
2024-12-06T17:39:05.1952006Z            at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1011)
2024-12-06T17:39:05.1952074Z            at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:914)
2024-12-06T17:39:05.1952154Z            at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:590)
2024-12-06T17:39:05.1952225Z            at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)
2024-12-06T17:39:05.1952300Z            at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)
2024-12-06T17:39:05.1952386Z            at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205)
2024-12-06T17:39:05.1955385Z            at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
2024-12-06T17:39:05.1955581Z            at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
2024-12-06T17:39:05.1955671Z            at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
2024-12-06T17:39:05.1955760Z            at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
2024-12-06T17:39:05.1955868Z            at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
2024-12-06T17:39:05.1956009Z            at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
2024-12-06T17:39:05.1956117Z            at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
2024-12-06T17:39:05.1956207Z            at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
2024-12-06T17:39:05.1956294Z            at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
2024-12-06T17:39:05.1956405Z            at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
2024-12-06T17:39:05.1956493Z            at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
2024-12-06T17:39:05.1956599Z            at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
2024-12-06T17:39:05.1956687Z            at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
2024-12-06T17:39:05.1956776Z            at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
2024-12-06T17:39:05.1956890Z            at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
2024-12-06T17:39:05.1956975Z            at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
2024-12-06T17:39:05.1957084Z            at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:166)
2024-12-06T17:39:05.1957169Z            at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
2024-12-06T17:39:05.1957257Z            at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
2024-12-06T17:39:05.1957359Z            at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
2024-12-06T17:39:05.1957426Z            at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
2024-12-06T17:39:05.1957490Z            at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
2024-12-06T17:39:05.1957579Z            at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:738)
2024-12-06T17:39:05.1957645Z            at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:341)
2024-12-06T17:39:05.1957726Z            at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:391)
2024-12-06T17:39:05.1957789Z            at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
2024-12-06T17:39:05.1957856Z            at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:894)
2024-12-06T17:39:05.1957948Z            at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1740)
2024-12-06T17:39:05.1958017Z            at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
2024-12-06T17:39:05.1958087Z            at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
2024-12-06T17:39:05.1958172Z            at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
2024-12-06T17:39:05.1958235Z            at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
2024-12-06T17:39:05.1958315Z            at java.base/java.lang.Thread.run(Thread.java:840)
2024-12-06T17:39:05.1958377Z            Suppressed: java.lang.Exception: #block terminated with an error
2024-12-06T17:39:05.1958439Z                           at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:103)
2024-12-06T17:39:05.1958517Z                           at reactor.core.publisher.Mono.block(Mono.java:1712)
2024-12-06T17:39:05.1958579Z                           ... 69 more

**To Reproduce**
The problem is intermittent in that it happens to seemingly random events and event types, but reproduceable, as in once an event fails, re-sending it will fail again.

***Code Snippet***
BlobClient blobClient = blobContainerClient.getBlobClient(blobFilename);
try (ByteArrayInputStream dataStream = new ByteArrayInputStream(payload.getBytes(StandardCharsets.UTF_8))) {
               blobClient.upload(dataStream, payload.length());

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - OS: Linux
 - Library/Libraries: <artifactId>azure-sdk-bom</artifactId><version>1.2.16</version>
 - Java version: 17 
 - App Server/Environment: [e.g. Embedded Tomcat / Azure App Service]
 - Frameworks: [Spring Boot] 

**Additional context**
We r uploading incoming event payload to Azure WebApp as json string to Azure Storage account as blobs. Most of the event payloads are uploaded fine but some specific ones are failing with the above error/stack trace. Those events that failed are consistently failing on retries.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by pp4253biz** [comment]
Yep that helped to resolve the issue. Thanks much!
