### ISSUE TITLE
Issue logging in with Spring Cloud Azure Active Directory when running in kubernetes

### ISSUE THREAD

**Issue by kevveh** [Azure/azure-sdk-for-java#43280]
Hello,

I've inherited a Spring project, and I'm currently in the process of moving the authentication flow to the BE, as described [here](https://www.baeldung.com/spring-cloud-gateway-bff-oauth2).

Since the application was using Azure AD, I'm using `spring-cloud-azure-starter-active-directory` (5.15.0). I've modified my code as described [here](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/spring-security-support?tabs=SpringCloudAzure5x#add-extra-security-configurations).

This application runs as a microservice in a Kubernetes cluster (v1.29.4). 

I've made all my modifications, and when I run the application on my local machine, everything works as expected: I enter my link in a browser, and I'm redirected to the Microsoft login page --> Once I log in, my data is returned. All this is working as expected. I can see the following in my application console:
```
06-12-2024 15:47:56.655 [http-nio-8080-exec-1] DEBUG o.s.security.web.FilterChainProxy.doFilterInternal - Securing GET /push-notification/count
06-12-2024 15:47:56.655 [http-nio-8080-exec-1] TRACE o.s.security.web.FilterChainProxy.doFilter - Invoking DisableEncodeUrlFilter (1/15)
06-12-2024 15:47:56.656 [http-nio-8080-exec-1] TRACE o.s.security.web.FilterChainProxy.doFilter - Invoking WebAsyncManagerIntegrationFilter (2/15)
06-12-2024 15:47:56.657 [http-nio-8080-exec-1] TRACE o.s.security.web.FilterChainProxy.doFilter - Invoking SecurityContextHolderFilter (3/15)
06-12-2024 15:47:56.657 [http-nio-8080-exec-1] TRACE o.s.security.web.FilterChainProxy.doFilter - Invoking HeaderWriterFilter (4/15)
06-12-2024 15:47:56.658 [http-nio-8080-exec-1] TRACE o.s.security.web.FilterChainProxy.doFilter - Invoking CorsFilter (5/15)
06-12-2024 15:47:56.660 [http-nio-8080-exec-1] TRACE o.s.security.web.FilterChainProxy.doFilter - Invoking LogoutFilter (6/15)
06-12-2024 15:47:56.660 [http-nio-8080-exec-1] TRACE o.s.s.w.a.logout.LogoutFilter.requiresLogout - Did not match request to Or [Ant [pattern='/logout', GET], Ant [pattern='/logout', POST], Ant [pattern='/logout', PUT], Ant [pattern='/logout', DELETE]]
06-12-2024 15:47:56.660 [http-nio-8080-exec-1] TRACE o.s.security.web.FilterChainProxy.doFilter - Invoking OAuth2AuthorizationRequestRedirectFilter (7/15)
06-12-2024 15:47:56.660 [http-nio-8080-exec-1] TRACE o.s.security.web.FilterChainProxy.doFilter - Invoking OAuth2LoginAuthenticationFilter (8/15)
06-12-2024 15:47:56.660 [http-nio-8080-exec-1] TRACE o.s.s.o.c.w.OAuth2LoginAuthenticationFilter.requiresAuthentication - Did not match request to Ant [pattern='/login/oauth2/code/*']
06-12-2024 15:47:56.660 [http-nio-8080-exec-1] TRACE o.s.security.web.FilterChainProxy.doFilter - Invoking DefaultLoginPageGeneratingFilter (9/15)
06-12-2024 15:47:56.660 [http-nio-8080-exec-1] TRACE o.s.security.web.FilterChainProxy.doFilter - Invoking DefaultLogoutPageGeneratingFilter (10/15)
06-12-2024 15:47:56.660 [http-nio-8080-exec-1] TRACE o.s.s.w.a.u.DefaultLogoutPageGeneratingFilter.doFilterInternal - Did not render default logout page since request did not match [Ant [pattern='/logout', GET]]
06-12-2024 15:47:56.660 [http-nio-8080-exec-1] TRACE o.s.security.web.FilterChainProxy.doFilter - Invoking RequestCacheAwareFilter (11/15)
06-12-2024 15:47:56.660 [http-nio-8080-exec-1] TRACE o.s.s.w.s.HttpSessionRequestCache.getMatchingRequest - matchingRequestParameterName is required for getMatchingRequest to lookup a value, but not provided
06-12-2024 15:47:56.660 [http-nio-8080-exec-1] TRACE o.s.security.web.FilterChainProxy.doFilter - Invoking SecurityContextHolderAwareRequestFilter (12/15)
06-12-2024 15:47:56.662 [http-nio-8080-exec-1] TRACE o.s.security.web.FilterChainProxy.doFilter - Invoking AnonymousAuthenticationFilter (13/15)
06-12-2024 15:47:56.662 [http-nio-8080-exec-1] TRACE o.s.security.web.FilterChainProxy.doFilter - Invoking ExceptionTranslationFilter (14/15)
06-12-2024 15:47:56.662 [http-nio-8080-exec-1] TRACE o.s.security.web.FilterChainProxy.doFilter - Invoking AuthorizationFilter (15/15)
06-12-2024 15:47:56.663 [http-nio-8080-exec-1] TRACE o.s.s.w.a.i.RequestMatcherDelegatingAuthorizationManager.check - Authorizing GET /push-notification/count
06-12-2024 15:47:56.664 [http-nio-8080-exec-1] TRACE o.s.s.w.a.i.RequestMatcherDelegatingAuthorizationManager.check - Checking authorization on GET /push-notification/count using org.springframework.security.authorization.AuthenticatedAuthorizationManager@4554088f
06-12-2024 15:47:56.664 [http-nio-8080-exec-1] TRACE o.s.s.w.c.HttpSessionSecurityContextRepository.readSecurityContextFromSession - No HttpSession currently exists
06-12-2024 15:47:56.664 [http-nio-8080-exec-1] TRACE o.s.s.w.c.SupplierDeferredSecurityContext.init - Created SecurityContextImpl [Null authentication]
06-12-2024 15:47:56.665 [http-nio-8080-exec-1] TRACE o.s.s.w.c.SupplierDeferredSecurityContext.init - Created SecurityContextImpl [Null authentication]
06-12-2024 15:47:56.665 [http-nio-8080-exec-1] TRACE o.s.s.w.a.AnonymousAuthenticationFilter.defaultWithAnonymous - Set SecurityContextHolder to AnonymousAuthenticationToken [Principal=anonymousUser, Credentials=[PROTECTED], Authenticated=true, Details=WebAuthenticationDetails [RemoteIpAddress=127.0.0.1, SessionId=null], Granted Authorities=[ROLE_ANONYMOUS]]
06-12-2024 15:47:56.665 [http-nio-8080-exec-1] TRACE o.s.s.w.a.ExceptionTranslationFilter.handleAccessDeniedException - Sending AnonymousAuthenticationToken [Principal=anonymousUser, Credentials=[PROTECTED], Authenticated=true, Details=WebAuthenticationDetails [RemoteIpAddress=127.0.0.1, SessionId=null], Granted Authorities=[ROLE_ANONYMOUS]] to authentication entry point since access is denied
org.springframework.security.access.AccessDeniedException: Access Denied
	at org.springframework.security.web.access.intercept.AuthorizationFilter.doFilter(AuthorizationFilter.java:98)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:126)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:120)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:100)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:179)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
	at org.springframework.security.web.authentication.ui.DefaultLogoutPageGeneratingFilter.doFilterInternal(DefaultLogoutPageGeneratingFilter.java:58)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
	at org.springframework.security.web.authentication.ui.DefaultLoginPageGeneratingFilter.doFilter(DefaultLoginPageGeneratingFilter.java:189)
	at org.springframework.security.web.authentication.ui.DefaultLoginPageGeneratingFilter.doFilter(DefaultLoginPageGeneratingFilter.java:175)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:227)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:221)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
	at org.springframework.security.oauth2.client.web.OAuth2AuthorizationRequestRedirectFilter.doFilterInternal(OAuth2AuthorizationRequestRedirectFilter.java:198)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:107)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:93)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:91)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
	at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90)
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
	at org.springframework.security.web.context.SecurityContextHolderFilter.doFilter(SecurityContextHolderFilter.java:82)
	at org.springframework.security.web.context.SecurityContextHolderFilter.doFilter(SecurityContextHolderFilter.java:69)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:62)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
	at org.springframework.security.web.session.DisableEncodeUrlFilter.doFilterInternal(DisableEncodeUrlFilter.java:42)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:233)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:191)
	at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:113)
	at org.springframework.web.servlet.handler.HandlerMappingIntrospector.lambda$createCacheFilter$3(HandlerMappingIntrospector.java:195)
	at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:113)
	at org.springframework.web.filter.CompositeFilter.doFilter(CompositeFilter.java:74)
	at org.springframework.security.config.annotation.web.configuration.WebMvcSecurityConfiguration$CompositeFilterChainProxy.doFilter(WebMvcSecurityConfiguration.java:230)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:352)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:268)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:731)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:389)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:896)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
	at java.base/java.lang.Thread.run(Thread.java:840)
06-12-2024 15:47:56.734 [http-nio-8080-exec-1] DEBUG o.s.s.w.s.HttpSessionRequestCache.saveRequest - Saved request http://localhost:8080/push-notification/count?continue to session
06-12-2024 15:47:56.735 [http-nio-8080-exec-1] DEBUG o.s.s.w.a.DelegatingAuthenticationEntryPoint.commence - Trying to match using And [Not [RequestHeaderRequestMatcher [expectedHeaderName=X-Requested-With, expectedHeaderValue=XMLHttpRequest]], Not [And [Or [Ant [pattern='/login'], Ant [pattern='/favicon.ico']], And [Not [RequestHeaderRequestMatcher [expectedHeaderName=X-Requested-With, expectedHeaderValue=XMLHttpRequest]], MediaTypeRequestMatcher [contentNegotiationStrategy=org.springframework.web.accept.ContentNegotiationManager@22fae187, matchingMediaTypes=[application/xhtml+xml, image/*, text/html, text/plain], useEquals=false, ignoredMediaTypes=[*/*]]]]], org.springframework.security.config.annotation.web.configurers.oauth2.client.OAuth2LoginConfigurer$$Lambda$997/0x00000187c3638228@4d9cba7]
06-12-2024 15:47:56.735 [http-nio-8080-exec-1] DEBUG o.s.s.w.a.DelegatingAuthenticationEntryPoint.commence - Match found! Executing org.springframework.security.web.authentication.LoginUrlAuthenticationEntryPoint@58978f1c
06-12-2024 15:47:56.736 [http-nio-8080-exec-1] DEBUG o.s.s.web.DefaultRedirectStrategy.sendRedirect - Redirecting to http://localhost:8080/oauth2/authorization/azure
06-12-2024 15:47:56.736 [http-nio-8080-exec-1] TRACE o.s.s.w.h.writers.HstsHeaderWriter.writeHeaders - Not injecting HSTS header since it did not match request to [Is Secure]
06-12-2024 15:47:56.748 [http-nio-8080-exec-7] TRACE o.s.security.web.FilterChainProxy.getFilters - Trying to match request against DefaultSecurityFilterChain [RequestMatcher=any request, Filters=[org.springframework.security.web.session.DisableEncodeUrlFilter@1dbff71c, org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter@93ce24d, org.springframework.security.web.context.SecurityContextHolderFilter@137a4b54, org.springframework.security.web.header.HeaderWriterFilter@20a9f5fb, org.springframework.web.filter.CorsFilter@d949bc4, org.springframework.security.web.authentication.logout.LogoutFilter@6fd7aba8, org.springframework.security.oauth2.client.web.OAuth2AuthorizationRequestRedirectFilter@1c7843c3, org.springframework.security.oauth2.client.web.OAuth2LoginAuthenticationFilter@7c8f047a, org.springframework.security.web.authentication.ui.DefaultLoginPageGeneratingFilter@6cee903a, org.springframework.security.web.authentication.ui.DefaultLogoutPageGeneratingFilter@7079f8f0, org.springframework.security.web.savedrequest.RequestCacheAwareFilter@1acc873b, org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter@dc8b2ff, org.springframework.security.web.authentication.AnonymousAuthenticationFilter@121cf6f4, org.springframework.security.web.access.ExceptionTranslationFilter@2a9e754e, org.springframework.security.web.access.intercept.AuthorizationFilter@4e7eba9f]] (1/1)
06-12-2024 15:47:56.748 [http-nio-8080-exec-7] DEBUG o.s.security.web.FilterChainProxy.doFilterInternal - Securing GET /oauth2/authorization/azure
06-12-2024 15:47:56.748 [http-nio-8080-exec-7] TRACE o.s.security.web.FilterChainProxy.doFilter - Invoking DisableEncodeUrlFilter (1/15)
06-12-2024 15:47:56.749 [http-nio-8080-exec-7] TRACE o.s.security.web.FilterChainProxy.doFilter - Invoking WebAsyncManagerIntegrationFilter (2/15)
06-12-2024 15:47:56.749 [http-nio-8080-exec-7] TRACE o.s.security.web.FilterChainProxy.doFilter - Invoking SecurityContextHolderFilter (3/15)
06-12-2024 15:47:56.749 [http-nio-8080-exec-7] TRACE o.s.security.web.FilterChainProxy.doFilter - Invoking HeaderWriterFilter (4/15)
06-12-2024 15:47:56.749 [http-nio-8080-exec-7] TRACE o.s.security.web.FilterChainProxy.doFilter - Invoking CorsFilter (5/15)
06-12-2024 15:47:56.749 [http-nio-8080-exec-7] TRACE o.s.security.web.FilterChainProxy.doFilter - Invoking LogoutFilter (6/15)
06-12-2024 15:47:56.749 [http-nio-8080-exec-7] TRACE o.s.s.w.a.logout.LogoutFilter.requiresLogout - Did not match request to Or [Ant [pattern='/logout', GET], Ant [pattern='/logout', POST], Ant [pattern='/logout', PUT], Ant [pattern='/logout', DELETE]]
06-12-2024 15:47:56.749 [http-nio-8080-exec-7] TRACE o.s.security.web.FilterChainProxy.doFilter - Invoking OAuth2AuthorizationRequestRedirectFilter (7/15)
06-12-2024 15:47:56.757 [http-nio-8080-exec-7] DEBUG o.s.s.web.DefaultRedirectStrategy.sendRedirect - Redirecting to https://login.microsoftonline.com/<TENANT_ID>/oauth2/v2.0/authorize?response_type=code&client_id=<CLIENT_ID>=openid%20profile%20offline_access&state=...%3D&redirect_uri=http://localhost:8080/login/oauth2/code/&nonce=...
06-12-2024 15:47:56.757 [http-nio-8080-exec-7] TRACE o.s.s.w.h.writers.HstsHeaderWriter.writeHeaders - Not injecting HSTS header since it did not match request to [Is Secure]
```
This all works: `http://localhost:8080/push-notification/count` --> Redirect to `http://localhost:8080/oauth2/authorization/azure` --> Redirect to `https://login.microsoftonline.com/<TENANT_ID>/oauth2/v2.0/authorize?...` --> Log in --> View data.

However, once I deploy to kubernetes, it no longer works. In my logging, I see the following:
```
06-12-2024 14:56:31.321 [http-nio-8080-exec-1] DEBUG o.apache.tomcat.util.http.Parameters.log - Set encoding to UTF-8
06-12-2024 14:56:31.335 [http-nio-8080-exec-1] DEBUG o.s.s.w.s.HttpSessionRequestCache.saveRequest - Saved request http://192.168.8.200/push-notification/count/?continue to session
06-12-2024 14:56:31.338 [http-nio-8080-exec-1] DEBUG o.s.s.w.a.DelegatingAuthenticationEntryPoint.commence - Trying to match using And [Not [RequestHeaderRequestMatcher [expectedHeaderName=X-Requested-With, expectedHeaderValue=XMLHttpRequest]], Not [And [Or [Ant [pattern='/login'], Ant [pattern='/favicon.ico']], And [Not [RequestHeaderRequestMatcher [expectedHeaderName=X-Requested-With, expectedHeaderValue=XMLHttpRequest]], MediaTypeRequestMatcher [contentNegotiationStrategy=org.springframework.web.accept.ContentNegotiationManager@366af379, matchingMediaTypes=[application/xhtml+xml, image/*, text/html, text/plain], useEquals=false, ignoredMediaTypes=[*/*]]]]], org.springframework.security.config.annotation.web.configurers.oauth2.client.OAuth2LoginConfigurer$$Lambda$1906/0x00000008018e2b18@531e7052]
06-12-2024 14:56:31.340 [http-nio-8080-exec-1] DEBUG o.s.s.w.a.DelegatingAuthenticationEntryPoint.commence - Match found! Executing org.springframework.security.web.authentication.LoginUrlAuthenticationEntryPoint@b21b18d
06-12-2024 14:56:31.414 [http-nio-8080-exec-1] DEBUG o.s.s.web.DefaultRedirectStrategy.sendRedirect - Redirecting to http://192.168.8.200/oauth2/authorization/azure
06-12-2024 14:56:31.420 [http-nio-8080-exec-1] TRACE o.s.s.w.h.writers.HstsHeaderWriter.writeHeaders - Not injecting HSTS header since it did not match request to [Is Secure]
06-12-2024 14:56:31.424 [http-nio-8080-exec-1] TRACE o.s.b.w.s.f.OrderedRequestContextFilter.doFilterInternal - Cleared thread-bound request context: org.apache.catalina.connector.RequestFacade@67ab2c12
06-12-2024 14:56:31.515 [http-nio-8080-exec-1] DEBUG o.a.coyote.http11.Http11InputBuffer.log - Before fill(): parsingHeader: [true], parsingRequestLine: [true], parsingRequestLinePhase: [0], parsingRequestLineStart: [0], byteBuffer.position(): [0], byteBuffer.limit(): [0], end: [760]
06-12-2024 14:56:31.517 [http-nio-8080-exec-1] DEBUG o.a.t.util.net.SocketWrapperBase.log - Socket: [org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper@24f2ec6:org.apache.tomcat.util.net.NioChannel@14e077d6:java.nio.channels.SocketChannel[connected local=/192.168.8.123:8080 remote=/192.168.8.95:55544]], Read from buffer: [0]
06-12-2024 14:56:31.525 [http-nio-8080-exec-1] DEBUG o.apache.tomcat.util.net.NioEndpoint.log - Socket: [org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper@24f2ec6:org.apache.tomcat.util.net.NioChannel@14e077d6:java.nio.channels.SocketChannel[connected local=/192.168.8.123:8080 remote=/192.168.8.95:55544]], Read direct from socket: [0]
06-12-2024 14:56:31.528 [http-nio-8080-exec-1] DEBUG o.a.coyote.http11.Http11InputBuffer.log - Received []
06-12-2024 14:56:31.529 [http-nio-8080-exec-1] DEBUG o.a.coyote.http11.Http11Processor.log - Socket: [org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper@24f2ec6:org.apache.tomcat.util.net.NioChannel@14e077d6:java.nio.channels.SocketChannel[connected local=/192.168.8.123:8080 remote=/192.168.8.95:55544]], Status in: [OPEN_READ], State out: [OPEN]
06-12-2024 14:56:31.529 [http-nio-8080-exec-1] DEBUG o.a.coyote.http11.Http11NioProtocol.log - Pushed Processor [org.apache.coyote.http11.Http11Processor@505386c8]
06-12-2024 14:56:31.530 [http-nio-8080-exec-1] DEBUG o.apache.tomcat.util.net.NioEndpoint.log - Registered read interest for [org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper@24f2ec6:org.apache.tomcat.util.net.NioChannel@14e077d6:java.nio.channels.SocketChannel[connected local=/192.168.8.123:8080 remote=/192.168.8.95:55544]]
```

`https://AZURE_APIM_URL/push-notification/count` --> APIM calls the microservice --> It gets stuck in a loop, and my browser tells me there is no response.

I can't figure out why it's currently not redirecting me to the Microsoft login page.

```
Kubernetes version: 1.29.4
Spring boot version: 3.3.0
Spring security version: 6.3.0
Package used: spring-cloud-azure-starter-active-directory - version 5.15.0
```
My SecurityConfig:
```
@Configuration
@EnableWebSecurity
@EnableMethodSecurity
public class SecurityConfig {

    @Bean
    public SecurityFilterChain filterChain(HttpSecurity http) throws Exception {
        return http
                .cors(Customizer.withDefaults())
                .csrf(AbstractHttpConfigurer::disable)
                .headers(headers -> headers.frameOptions(HeadersConfigurer.FrameOptionsConfig::disable))
                .with(AadWebApplicationHttpSecurityConfigurer.aadWebApplication(), Customizer.withDefaults())
                .authorizeHttpRequests((auth) ->
                        auth.anyRequest().authenticated())
                .exceptionHandling(Customizer.withDefaults())
                .build();
    }
}
```
My `application.yml` file:
```
spring:
  cloud:
    azure:
      active-directory:
        profile:
          tenant-id: ${azure-tenant-id}
        credential:
          client-id: ${azure-client-id}
          client-secret: ${azure-client-secret}
        enabled: true
        app-id-uri: api://${azure-client-id}
```

Redirect URI in my App registration = `http://localhost:8080/login/oauth2/code/`.

**Comment by Netyyyy** [comment]
We’ve added this into our backlog and will update this thread once we have more insights or a fix.

**Comment by Netyyyy** [comment]
We will close this issue as it has been open for a while. If you have any further questions or need assistance, please feel free to reopen it. Thank you!
