### ISSUE TITLE
[BUG] `java.util.NoSuchElementException: None.get` when loading Cosmos container with Spark

### ISSUE THREAD

**Issue by cthlo** [Azure/azure-sdk-for-java#43374]
**Describe the bug**
```python
config = {
    "spark.cosmos.accountEndpoint": "https://...documents.azure.com:443/",
    "spark.cosmos.auth.type": "ManagedIdentity",
    "spark.cosmos.account.tenantId": "...",
    "spark.cosmos.database": "default",
    "spark.cosmos.container": "volcano",
}

cosmos_df = spark.read.format("cosmos.oltp") \
    .options(**config) \
    .option("spark.cosmos.read.inferSchema.enabled", "true") \
    .load()
```

`default` is a new database.
`volcano` is an new, empty container.

(Confirmed that there is no access issue with Python `azure-cosmos` SDK)

***Exception or Stack Trace***
```
Py4JJavaError: An error occurred while calling o718.load.
: java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:529)
	at scala.None$.get(Option.scala:527)
	at com.azure.cosmos.spark.CosmosClientCache$.syncCreate(CosmosClientCache.scala:165)
	at com.azure.cosmos.spark.CosmosClientCache$.apply(CosmosClientCache.scala:89)
	at com.azure.cosmos.spark.ItemsReadOnlyTable.schema(ItemsReadOnlyTable.scala:116)
	at com.azure.cosmos.spark.CosmosItemsDataSource.inferSchema(CosmosItemsDataSource.scala:37)
	at org.apache.spark.sql.execution.datasources.v2.DataSourceV2Utils$.getTableFromProvider(DataSourceV2Utils.scala:99)
	at org.apache.spark.sql.execution.datasources.v2.DataSourceV2Utils$.loadV2Source(DataSourceV2Utils.scala:229)
	at org.apache.spark.sql.DataFrameReader.$anonfun$load$1(DataFrameReader.scala:349)
	at scala.Option.flatMap(Option.scala:271)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:347)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:236)
	at sun.reflect.GeneratedMethodAccessor483.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:397)
	at py4j.Gateway.invoke(Gateway.java:306)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:199)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:119)
	at java.lang.Thread.run(Thread.java:750)
File <command-1270680631647351>, line 4
      1 cosmos_df = spark.read.format("cosmos.oltp") \
      2     .options(**config) \
      3     .option("spark.cosmos.read.inferSchema.enabled", "true") \
----> 4     .load()
File /databricks/spark/python/pyspark/instrumentation_utils.py:47, in _wrap_function.<locals>.wrapper(*args, **kwargs)
     45 start = time.perf_counter()
     46 try:
---> 47     res = func(*args, **kwargs)
     48     logger.log_success(
     49         module_name, class_name, function_name, time.perf_counter() - start, signature
     50     )
     51     return res
File /databricks/spark/python/pyspark/sql/readwriter.py:319, in DataFrameReader.load(self, path, format, schema, **options)
    317     return self._df(self._jreader.load(self._spark._sc._jvm.PythonUtils.toSeq(path)))
    318 else:
--> 319     return self._df(self._jreader.load())
File /databricks/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py:1355, in JavaMember.__call__(self, *args)
   1349 command = proto.CALL_COMMAND_NAME +\
   1350     self.command_header +\
   1351     args_command +\
   1352     proto.END_COMMAND_PART
   1354 answer = self.gateway_client.send_command(command)
-> 1355 return_value = get_return_value(
   1356     answer, self.gateway_client, self.target_id, self.name)
   1358 for temp_arg in temp_args:
   1359     if hasattr(temp_arg, "_detach"):
File /databricks/spark/python/pyspark/errors/exceptions/captured.py:255, in capture_sql_exception.<locals>.deco(*a, **kw)
    252 from py4j.protocol import Py4JJavaError
    254 try:
--> 255     return f(*a, **kw)
    256 except Py4JJavaError as e:
    257     converted = convert_exception(e.java_exception)
File /databricks/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/protocol.py:326, in get_return_value(answer, gateway_client, target_id, name)
    324 value = OUTPUT_CONVERTER[type](answer[2:], gateway_client)
    325 if answer[1] == REFERENCE_TYPE:
--> 326     raise Py4JJavaError(
    327         "An error occurred while calling {0}{1}{2}.\n".
    328         format(target_id, ".", name), value)
    329 else:
    330     raise Py4JError(
    331         "An error occurred while calling {0}{1}{2}. Trace:\n{3}\n".
    332         format(target_id, ".", name, value))
```

**To Reproduce**

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - Library/Libraries: `com.azure.cosmos.spark:azure-cosmos-spark_3-5_2-12:4.35.0`
 - Scala version: `2.12`
 - App Server/Environment: Databricks 15.4 / Spark 3.5.0

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by cthlo** [comment]
After inspecting the [line of code](https://github.com/Azure/azure-sdk-for-java/blob/49f10a7bd8e9862c38ae4794c8bb4629b29ced12/sdk/cosmos/azure-cosmos-spark_3_2-12/src/main/scala/com/azure/cosmos/spark/CosmosClientCache.scala#L165), it appears that I'm missing `spark.cosmos.account.resourceGroupName`.

Upon adding the config, it's working fine.
It'd be nice if the exception also mentions that.

Thanks!
