### ISSUE TITLE
[BUG] PostgreSQL passwordless not work in Spring Cloud Azure 5.18.0

### ISSUE THREAD

**Issue by rujche** [Azure/azure-sdk-for-java#43407]
**Describe the bug**
PostgreSQL passwordless not work in Spring Cloud Azure 5.18.0 

***Exception or Stack Trace***

```shell
Caused by: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection
at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:84) ~[spring-jdbc-6.1.11.jar:6.1.11]
at org.springframework.jdbc.datasource.init.DatabasePopulatorUtils.execute(DatabasePopulatorUtils.java:52) ~[spring-jdbc-6.1.11.jar:6.1.11]
... 111 common frames omitted
Caused by: org.postgresql.util.PSQLException: FATAL: The access token does not have a valid audience claim. Please acquire a new token for the resource "https://ossrdbms-aad.database.windows.net".
at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:698) ~[postgresql-42.7.3.jar:42.7.3]
at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:207) ~[postgresql-42.7.3.jar:42.7.3]
at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:262) ~[postgresql-42.7.3.jar:42.7.3]
at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54) ~[postgresql-42.7.3.jar:42.7.3]
```

**To Reproduce**
Link to sample: https://github.com/azure-javaee/azure-spring-boot-samples/blob/7b200de74222628d47c216f2191950d97d70d664/postgresql/spring-cloud-azure-starter-jdbc-postgresql/spring-cloud-azure-postgresql-sample/pom.xml#L14

Use the SJAD version of azd, run `azd init` and `azd up`, this problem can be reproduced. Change Spring Cloud Azure's version from 5.18.0 to 5.16.0 can solve this problem.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added

**Comment by rujche** [comment]
Hi, @moarychan .

1. Could you please help to investigate this issue?
2. The problem of PostgreSQL + MI can be solved by changing spring-cloud-azure' version from 5.18.0 to 5.16.0 in [this commit](https://github.com/azure-javaee/azure-spring-boot-samples/commit/7b200de74222628d47c216f2191950d97d70d664). But the problem of MySQL + MI can not be solved by changing spring-cloud-azure' version from 5.18.0 to 5.16.0. Could you please help to investigate this issue at the same time? 

Related link: https://github.com/azure-javaee/azure-spring-boot-samples
Related screenshot:
> ![Image](https://github.com/user-attachments/assets/4d2dc40d-2ae6-4e66-bf66-2246a36af7f6)

**Comment by moarychan** [comment]
The root cause for PostgreSQL + MI usage is the scope bug from Azure Identity SDK, see more from https://github.com/Azure/azure-sdk-for-java/pull/42934, If you using Spring Cloud Azure 5.18.0, keep the azure-identity dependency version is `1.14.2+`.

**Comment by moarychan** [comment]
The root cause for MySQL + MI usage is that the ACA connector command takes a long connection name `springCloudAzureMysqlSampleMysql` in azd side, so the aad user can not be inserted into the mysql database for connection:

`az containerapp connection create mysql-flexible --connection springCloudAzureMysqlSampleMysql`

The fix will be soon! If you encounter this issue, please upgrade the azd version!
