### ISSUE TITLE
[BUG] If an exception occurs while sending an Azure storage request and it doesn't have a cause then the information in the exception gets dropped

### ISSUE THREAD

**Issue by charlesjmorgan** [Azure/azure-sdk-for-java#43463]
**Describe the bug**
The error handling for the `sendRequest` method in the `StorageImplUtils` assumes that the exception has a cause: https://github.com/Azure/azure-sdk-for-java/blob/f36f0f5c75e65691b175daa734f0733210357802/sdk/storage/azure-storage-common/src/main/java/com/azure/storage/common/implementation/StorageImplUtils.java#L499-L512 If the exception doesn't have a cause and it is the root cause itself then any information contained in the caught exception is dropped and a generic `RuntimeException` is thrown with a null cause

***Exception or Stack Trace***
Just an empty `RuntimeException` that gets thrown without a cause from `StorageImplUtils#sendRequest`

**To Reproduce**
Steps to reproduce the behavior: I don't believe these are needed

***Code Snippet***
```java
    public static <T> T sendRequest(Callable<T> operation, Duration timeout,
        Class<? extends RuntimeException> exceptionType) {
        try {
            if (timeout == null) {
                return operation.call();
            }
            Future<T> future = SharedExecutorService.getInstance().submit(operation);
            return getResultWithTimeout(future, timeout.toMillis(), exceptionType);
        } catch (Exception e) {
            Throwable cause = e.getCause();
            if (exceptionType.isInstance(e)) {
                // Safe to cast since we checked with isInstance
                throw exceptionType.cast(e);
            } else if (cause instanceof RuntimeException) {
                // Throw as is if it's already a RuntimeException
                throw (RuntimeException) cause;
            } else if (cause instanceof Error) {
                // Propagate if it's an Error
                throw (Error) cause;
            } else {
                // Wrap in RuntimeException if it's neither Error nor RuntimeException
                throw LOGGER.logExceptionAsError(new RuntimeException(cause));
            }
        }
    }
```

**Expected behavior**
I expect that if an exception is caught in the `sendRequest` method and it doesn't have a cause that the same exception should be rethrown if it is either a runtime exception or an error.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [/] Repro Steps Added
- [/] Setup information Added

**Comment by jairmyree** [comment]
@charlesjmorgan Thank you for reaching out. @ibrahimrabab could you please look into this?

**Comment by bryandx** [comment]
We ran into an issue that might be related to this.   We were using azure-storage-blob version 12.27.1 successfully with this code:
`getContainerClient().listBlobs(new ListBlobsOptions(), Duration.ofMinutes(1)).stream().collect(Collectors.toUnmodifiableList());`

When we upgraded azure-storage-blob to version 12.29.0, that same code resulted in this exception always being thrown:
```
java.lang.RuntimeException: null
	at com.azure.storage.common.implementation.StorageImplUtils.sendRequest(StorageImplUtils.java:511)
	at com.azure.storage.blob.BlobContainerClient.lambda$listBlobs$7(BlobContainerClient.java:1050)
	at com.azure.storage.blob.BlobContainerClient.lambda$listBlobs$8(BlobContainerClient.java:1065)
	at com.azure.core.http.rest.PagedIterable.lambda$new$5(PagedIterable.java:193)
	at com.azure.core.util.paging.ContinuablePagedByIteratorBase.requestPage(ContinuablePagedByIteratorBase.java:104)
	at com.azure.core.util.paging.ContinuablePagedByItemIterable$ContinuablePagedByItemIterator.<init>(ContinuablePagedByItemIterable.java:83)
	at com.azure.core.util.paging.ContinuablePagedByItemIterable.iterator(ContinuablePagedByItemIterable.java:58)
	at com.azure.core.util.paging.ContinuablePagedIterable.iterator(ContinuablePagedIterable.java:141)
	at java.base/java.lang.Iterable.forEach(Iterable.java:74)
	at com.simon.cluster.client.dao.DataStoreRepository.getAllBlobs(DataStoreRepository.java:298)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:359)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:138)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:727)
	at com.simon.cluster.client.dao.DataStoreRepository$$SpringCGLIB$$0.getAllBlobs(<generated>)
	at com.simon.cluster.client.manage.ClusterPruningService.performPruning(ClusterPruningService.java:86)
	at com.simon.cluster.client.manage.ClusterPruningScheduledService.scheduledPruning(ClusterPruningScheduledService.java:40)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.runInternal(ScheduledMethodRunnable.java:130)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.lambda$run$2(ScheduledMethodRunnable.java:124)
	at io.micrometer.observation.Observation.observe(Observation.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:124)
	at org.springframework.scheduling.config.Task$OutcomeTrackingRunnable.run(Task.java:85)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.lang.VirtualThread.run(VirtualThread.java:329)
```

I noticed that the exception was being thrown whenever the timeout (Duration.ofMinutes(1)) ) was met.  If I would increase the timeout to 4 minutes, the exception was thrown at 4 minutes.    However, a timeout shouldn't have been occurring.   When I change the code to remove the timeout:
`getContainerClient().listBlobs().stream().collect(Collectors.toUnmodifiableList());`
the method actually returned in **27 milliseconds**.      That quick response time isn't close to a 1 minute timeout so a timeout shouldn't have been occurring.

**Comment by kistlers** [comment]
@bryandx we are also still facing the exact same issue on any version after `azure-storage-blob:12.27.1`, which prevents us from upgrading the `azure-sdk-bom:1.2.27` to any newer version. Just removing the timeout seems unsafe, though.

**Comment by browndav-msft** [comment]
@charlesjmorgan sorry for not fixing this sooner. We've changed this so that the context for the error isn't lost.

https://github.com/Azure/azure-sdk-for-java/pull/46461

**Comment by browndav-msft** [comment]
@bryandx @kistlers the issue you are identifying is a slightly different issue. I'm working on it now. I will post an update here as soon as I find the issue.

**Comment by browndav-msft** [comment]
@bryandx @kistlers ,

I haven't been able to replicate the issue, but we made a changes under the hood between 12.27.1 and 12.29.0 and we need some more code to help find the issue. 

For both versions, I ran the following code and couldn't replicate the issue. Can you let me know if your code was different and perhaps provide context that could help me replicate the issues you are having.

```java
        BlockBlobClient blobClientBase =(new SpecializedBlobClientBuilder())
            .endpoint("https://" + BLOB_ACCOUNT_NAME + AZURE_STORAGE_BLOB_HOST_SUFFIX)
            .credential(new StorageSharedKeyCredential(BLOB_ACCOUNT_NAME, BLOB_ACCOUNT_KEY))
            .containerName(CONTAINER_NAME)
            .blobName(BLOB_NAME)
            .buildBlockBlobClient();

        var blobs = blobClientBase.getContainerClient()
            .listBlobs(new ListBlobsOptions(), Duration.ofMinutes(1))
            .stream()
            .collect(Collectors.toUnmodifiableList());
```

**Comment by bryandx** [comment]
@browndav-msft We've since upgraded to version 12.30.0 and 12.30.1, and couldn't reproduce the exception.

**Comment by kistlers** [comment]
@browndav-msft I think we only ever used timeouts configured in the httpClient:

```java
        this.timeout = Objects.requireNonNullElse(timeout, Duration.ofSeconds(60));
        final var httpClient =
                HttpClient.createDefault(
                        new HttpClientOptions()
                                .setConnectTimeout(this.timeout)
                                .setReadTimeout(this.timeout)
                                .setWriteTimeout(this.timeout));
        this.blobServiceClient =
                new BlobServiceClientBuilder()
                        .connectionString(connectionString)
                        .retryOptions(new RequestRetryOptions())
                        .httpClient(httpClient)
                        .buildClient();
```

Not as a parameter in the `listBlobs` call

**Comment by kistlers** [comment]
We configure the httpClient with some timeout, and we set the same timeout also in the listBlobs call. Could this be part of the issue?

```java
        this.timeout = Objects.requireNonNullElse(timeout, Duration.ofSeconds(60));
        final var httpClient =
                HttpClient.createDefault(
                        new HttpClientOptions()
                                .setConnectTimeout(this.timeout)
                                .setReadTimeout(this.timeout)
                                .setWriteTimeout(this.timeout));
        this.blobServiceClient =
                new BlobServiceClientBuilder()
                        .connectionString(connectionString)
                        .retryOptions(new RequestRetryOptions())
                        .httpClient(httpClient)
                        .buildClient();
        this.blobContainerClient = blobServiceClient.getBlobContainerClient(container);


        final var options = new ListBlobsOptions().setPrefix(path);
            blobItems = blobContainerClient.listBlobs(options, timeout);
```

I accidentally upgraded the azure-sdk-bom from 1.2.27 to 1.2.37 which raised azure-storage-common from 12.26 to 12.30 and still got the same error.

**Comment by bryandx** [comment]
@browndav-msft I haven't been able to reproduce the exception we were receiving either.

**Comment by browndav-msft** [comment]
@kistlers This could possibly run your application in debug mode and place a breakpoint here: 

https://github.com/Azure/azure-sdk-for-java/blob/4f606d7df70c1871a9d2635a39b308944de0dfd5/sdk/storage/azure-storage-common/src/main/java/com/azure/storage/common/policy/RequestRetryPolicy.java#L300

https://github.com/Azure/azure-sdk-for-java/blob/4f606d7df70c1871a9d2635a39b308944de0dfd5/sdk/storage/azure-storage-common/src/main/java/com/azure/storage/common/implementation/StorageImplUtils.java#L527

There is a possibility that an error could be thrown and caught in those locations. 

Once the error is caught, can you tell me what the cause is at each breakpoint? This will help me narrow down where the issue is occurring.

**Comment by browndav-msft** [comment]
> [@browndav-msft](https://github.com/browndav-msft) I haven't been able to reproduce the exception we were receiving either.

@kistlers I just wanted to verify, so you aren't having issues anymore?

**Comment by kistlers** [comment]
> > [@browndav-msft](https://github.com/browndav-msft) I haven't been able to reproduce the exception we were receiving either.
> 
> [@kistlers](https://github.com/kistlers) I just wanted to verify, so you aren't having issues anymore?

We are still having this issue, I managed to reproduce the issue with the stack trace looking very similiar to the one posted by @bryandx above:
```
java.lang.RuntimeException: null\ 
	at com.azure.storage.common.implementation.StorageImplUtils.sendRequest(StorageImplUtils.java:511)\ 
	at com.azure.storage.blob.BlobContainerClient.lambda$listBlobs$7(BlobContainerClient.java:1050)\ 
	at com.azure.storage.blob.BlobContainerClient.lambda$listBlobs$8(BlobContainerClient.java:1065)\ 
	at com.azure.core.http.rest.PagedIterable.lambda$new$5(PagedIterable.java:193)\ 
	at com.azure.core.util.paging.ContinuablePagedByIteratorBase.requestPage(ContinuablePagedByIteratorBase.java:104)\ 
	at com.azure.core.util.paging.ContinuablePagedByItemIterable$ContinuablePagedByItemIterator.<init>(ContinuablePagedByItemIterable.java:83)\ 
	at com.azure.core.util.paging.ContinuablePagedByItemIterable.iterator(ContinuablePagedByItemIterable.java:58)\ 
	at java.base/java.lang.Iterable.spliterator(Iterable.java:101)\ 
	at com.azure.core.util.paging.ContinuablePagedIterable.stream(ContinuablePagedIterable.java:85)\ 
	at ch.ubique.backend.storage.clients.AzureBlobStorageClient.list(AzureBlobStorageClient.java:231)\ 
	at ch.ubique.backend.storage.clients.AzureBlobStorageClient.deleteRecursive(AzureBlobStorageClient.java:211)\ 
	at ch.ubique.backend.storage.clients.AzureBlobStorageClient.delete(AzureBlobStorageClient.java:186)\ 
	at ch.ubique.backend.storage.invocation.DeleteMappingInvocationHandler.invoke(DeleteMappingInvocationHandler.java:43)\ 
	at ch.ubique.backend.storage.invocation.StorageInvocationHandler.invoke(StorageInvocationHandler.java:51)\ 
	at jdk.proxy2/jdk.proxy2.$Proxy328.deleteJobRunDirectory(Unknown Source)\ 
	at ch.ubique.backend.job.cleanup.CleanupJob.cleanInputFiles(CleanupJob.java:137)\ 
	at ch.ubique.backend.job.cleanup.CleanupJob.lambda$cleanJob$0(CleanupJob.java:112)\ 
	at ch.ubique.backend.core.executor.VirtualThreadUtils.lambda$callable$3(VirtualThreadUtils.java:153)\ 
	at ch.ubique.backend.core.utils.MdcUtils.runWithContext(MdcUtils.java:22)\ 
	at ch.ubique.backend.core.executor.VirtualThreadUtils.lambda$callable$4(VirtualThreadUtils.java:153)\ 
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)\ 
	at java.base/java.lang.VirtualThread.run(VirtualThread.java:329)\ 
```

I tried to debug locally and catch the exception but I failed to reproduce it locally on azure-storage-common:12.26.1.

Usually, we use the Azure Blob Storage for this operation only when the application is deployed. Hence, the reason I might not be able to reproduce it locally even though I run the code against Azure.

However, I was just checking our logs again to find more information for you to tackle the issue. In our latest cases, the exception did not occur after the 1 minute timeout runs out, but already 1-4 seconds after `listBlobs(...)` is called. Since we use the default `new RequestRetryOptions()` which uses exponetial backoff and 4 seconds initial retry delay, the exception has to occur on the first attempt, I would say.

**Comment by browndav-msft** [comment]
@bryandx Are you still having the issue?

**Comment by browndav-msft** [comment]
@kistlers two things:
1) What are you using for local development? Are you using Azurite?
2) If the app isn't hanging anymore (that is, it isn't going all the way to the timeout limit), then the issue should be resolved with the pull request above, which will give more context on the exception.

**Comment by bryandx** [comment]
> [@bryandx](https://github.com/bryandx) Are you still having the issue?

No.  I wasn't able to re-create the exception.

**Comment by kistlers** [comment]
@brownday-msft
1) No, we have some custom implementation, that makes the local file system act like a blob storage, without using azure libraries, but we have a test suite running against azurite.

2) Yes, I think that will be helpful and I am happy to wait on a released version of azure-storage-common (and preferably the azure-sdk-bom) to see if we can find a solution for our issue.

**Comment by browndav-msft** [comment]
@bryandx @kistlers @charlesjmorgan thanks for working with me on this. Sorry it took so long. I'm going to close the this thread, but I've got a pull request submitted that will be merged once it is reviewed.
