### ISSUE TITLE
[BUG] Managed Identity token acquisition thread will be blocked when the common pool ForkJoinPool exhausted

### ISSUE THREAD

**Issue by moarychan** [Azure/azure-sdk-for-java#43631]
**Describe the bug**
When using Managed Identity scenario, if you're using credential from `DefaultAzureCredentialBuilder` without a custom `ExecutorService` or directly using `ManagedIdentityCredentialBiulder`, you should be aware that the token acquisition thread may not execute in a timely manner.

Due to Managed Identity credential does not support the custom `ExecutorService`, and it will run the method `CompletableFuture.supplyAsync(supplier)`, see from [AbstractApplicationBase#executeRequest](https://github.com/AzureAD/microsoft-authentication-library-for-java/blob/bbdc93d59d54916cdbac4016f1b174822e9bb51c/msal4j-sdk/src/main/java/com/microsoft/aad/msal4j/AbstractApplicationBase.java#L92)

![Image](https://github.com/user-attachments/assets/276b6dbd-71fb-4773-98e3-c2f0c87ed1d5)

Then the token acquisition thread will use a static common pool `ForkJoinPool.commonPool()`, see from [CompletableFuture#supplyAsync](https://github.com/microsoft/openjdk-jdk17u/blob/bdc07d202a917384625f3a17c630e92dcd9f2fcf/src/java.base/share/classes/java/util/concurrent/CompletableFuture.java#L1988)

![Image](https://github.com/user-attachments/assets/728c912c-c22c-4852-9a7b-a393f6e3d9e7)

A more specific case is using Spring Boot + Spring Cloud Azure Starter JDBC MySQL + JPA. 
Lots of the user's business processing threads are executed in the common pool `java.util.concurrent.ForkJoinPool#common`, and they begin to need to connect to the MySQL database. At this time, because the [JDBC authentication plugin](https://github.com/Azure/azure-sdk-for-java/blob/azure-identity-extensions_1.1.22/sdk/identity/azure-identity-extensions/src/main/java/com/azure/identity/extensions/jdbc/mysql/AzureMysqlAuthenticationPlugin.java#L20) is available, then it's called to get access token as password, it will use the Managed Identity Credential, each token request thread will not be executed immediately, and the business thread will be stagnant.

***Exception or Stack Trace***
The token acquisition thread is not started, not found any stack trace within msal4j, stopped here:

```console
"xxx.mysql.database.azure.com/dev_data2 connection adder" #2873 daemon prio=5 os_prio=0 tid=0x00007f3b8801f000 nid=0x200202 waiting on condition [0x00007efa508ae000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000006c7c1e760> (a java.util.concurrent.CountDownLatch$Sync)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1037)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1328)
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:277)
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:125)
	at reactor.core.publisher.Mono.block(Mono.java:1738)
	at com.azure.identity.extensions.implementation.template.AzureAuthenticationTemplate.getTokenAsPassword(AzureAuthenticationTemplate.java:101)
	at com.azure.identity.extensions.jdbc.mysql.AzureMysqlAuthenticationPlugin.nextAuthenticationStep(AzureMysqlAuthenticationPlugin.java:88)
	at com.azure.identity.extensions.jdbc.mysql.AzureMysqlAuthenticationPlugin.nextAuthenticationStep(AzureMysqlAuthenticationPlugin.java:20)
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:446)
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:215)
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1428)
	at com.mysql.cj.NativeSession.connect(NativeSession.java:133)
	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:935)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:805)
	- locked <0x00000006c7b80690> (a com.mysql.cj.jdbc.ConnectionImpl)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:438)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:189)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
	at com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:726)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

   Locked ownable synchronizers:
	- <0x00000006c432f508> (a java.util.concurrent.ThreadPoolExecutor$Worker)
```

and there are lots of threads named started with `ForkJoinPool.commonPool-worker-`, they occupy common pool `java.util.concurrent.ForkJoinPool#common` resources.

**To Reproduce**
Run this [reproducer](https://github.com/moarychan/reproducers/tree/reproducers/2024/12-26-managed-identity-token-acquisition-thread-blocked) under Azure Managed Identity enabled environment.

***Code Snippet***
N/A

**Expected behavior**
Managed Identity credential supports custom `ExecutorService`, better to use a custom thread pool by default when no executor service provided.

**Screenshots**
N/A

**Setup (please complete the following information):**
 - OS: [e.g. iOS] Azure Virtual Machine Windows 11
 - IDE: [e.g. IntelliJ] Intellij Idea
 - Library/Libraries: Spring Boot 3.3.2 + Spring Cloud Azure 5.19.0
 - Java version: [e.g. 8] Java 17

**Additional context**
Related issues:
- https://github.com/Azure/azure-sdk-for-java/issues/8626
- https://github.com/Azure/azure-sdk-for-java/issues/22687.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by moarychan** [comment]
Just tested, please see the [the proven workaround](https://github.com/moarychan/reproducers/tree/reproducers/2024/12-26-managed-identity-token-acquisition-thread-blocked?tab=readme-ov-file#workaround).

**Comment by moarychan** [comment]
Hi @g2vinay , I have following questions, could you please help explain them to us?  CC @saragluna 

- Why does only default credential builder support custom executor service, while others like the managed identity biulder and the CLI credential biulder do not?
- Why does the managed identity credential not provide the sync acquisition token method instead the default async method with block calling? 
- Why does the managed identity credential not provide the caching ability like the [cachedToken of UsernamePasswordCredential](https://github.com/Azure/azure-sdk-for-java/blob/c92ac941881226258206b3b613527a029eafc6cd/sdk/identity/azure-identity/src/main/java/com/azure/identity/UsernamePasswordCredential.java#L65)?

**Comment by billwert** [comment]
@moarychan Hello! Thanks for investigation.



> * Why does only default credential builder support custom executor service, while others like the managed identity biulder and the CLI credential biulder do not?

The API difference is something we can think about. With that said it is my expectation that the MI client being used is using the `SharedExecutorService` from azure-core:

https://github.com/Azure/azure-sdk-for-java/blob/50af1d0914530a7be9072ef4244633288bce5125/sdk/identity/azure-identity/src/main/java/com/azure/identity/implementation/IdentityClientBase.java#L491-L495



> Why does the managed identity credential not provide the caching ability like the [cachedToken of UsernamePasswordCredential](https://github.com/Azure/azure-sdk-for-java/blob/c92ac941881226258206b3b613527a029eafc6cd/sdk/identity/azure-identity/src/main/java/com/azure/identity/UsernamePasswordCredential.java#L65)?

Caching of MI tokens is a recent feature and is handled entirely at the MSAL layer.


> * Why does the managed identity credential not provide the sync acquisition token method instead the default async method with block calling?

Good question. @g2vinay was there a reason we kept the async only API?

**Comment by billwert** [comment]
@g2vinay helped me remember that using the `SharedExecutorService` is still in beta - I will try the repro with the beta bits as well.

**Comment by moarychan** [comment]
If using this shared executor service, now the token acquisition thread ran in special thread pool, named with `azure-sdk-global-thread-x`
![Image](https://github.com/user-attachments/assets/8672d9de-133c-4829-9fe0-ca18081f7479)

**Comment by billwert** [comment]
Thanks for verifying @moarychan!

**Comment by billwert** [comment]
Fixed by releasing `azure-identity` 1.15.0.
