### ISSUE TITLE
[BUG] When producing message with Event Hubs async client - partitionId invalid, no available ones

### ISSUE THREAD

**Issue by Amir-Qlik** [Azure/azure-sdk-for-java#43649]
**Description**
In Event Hubs async client, producing a message to a partition with a valid partition Id "0" fails and the exception message lists an empty list of available partition Id's. 

***Exception***
"partitionId is not valid. Available ones:"

**To Reproduce**
- Create a buffered producer client builder.
- Use the builder to create an async client.
- Create event data.
- Use the client to enqueue the event, specifying a partition Id in the send options. 

***Code Snippet***

	EventHubBufferedProducerClientBuilder builder = new EventHubBufferedProducerClientBuilder()
			.onSendBatchSucceeded(this::onBatchSucceed)
			.onSendBatchFailed(this::onBatchFailed)
			.connectionString(connectionString, hubName);

	EventHubBufferedProducerAsyncClient producerClient = builder.buildAsyncClient();
	EventData eventData = new EventData(("data_0").getBytes()).setMessageId("id_0");
	producerClient.enqueueEvent(eventData, new SendOptions().setPartitionId("0")).subscribe(
			numberOfEvents -> {
				System.out.printf("There are %d events in the buffer.%n", numberOfEvents);
			}, error -> {
				System.err.println("Error occurred enqueueing events: " + error);
			},
			() -> {
				System.out.println("Event successfully enqueued.");
			});

**Setup**
 - OS: Windows Server 2016
 - IDE: IntelliJ IDEA 2024.1.4
 - SDK: 5.19.2
 - Library/Libraries: com.azure:azure-core:1.54.1
 - Java version: 17

**Comment by Amir-Qlik** [comment]
Added by mistake as wrong repository, moving to azure-event-hubs-java.

**Comment by Amir-Qlik** [comment]
Reproduces with 5.20.0

**Comment by Amir-Qlik** [comment]
Anyone?

**Comment by conniey** [comment]
I'll look into it.

**Comment by kumaran-sowrirajan** [comment]
The latest fix did not resolve the issue.

I think there are 2 issues but not sure whether the second one is depend upon the first one.

Problem 1:
Problem is [over here in flatMapMany](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/eventhubs/azure-messaging-eventhubs/src/main/java/com/azure/messaging/eventhubs/EventHubBufferedProducerAsyncClient.java#L186). For debugging, I am able to view the partitionIds by calling the following code

client.getEventHubProperties().block()

Whereas flatMapMany not emitting any results which results in partitionProducers empty.

Problem: 2:
When stopping the EventProcessorClient with the latest version (5.20.0), it blows up with the following exception and I am not sure whether is is related to the first one. I have 2 partitions in the event hub.

Caused by: reactor.core.Exceptions$ReactorRejectedExecutionException: Scheduler unavailable
	at reactor.core.Exceptions.failWithRejected(Exceptions.java:271) ~[reactor-core-3.4.41.jar:3.4.41]
	at reactor.core.publisher.Operators.onRejectedExecution(Operators.java:1024) ~[reactor-core-3.4.41.jar:3.4.41]
	... 30 more
Caused by: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@6e9afc06[Not completed, task = reactor.core.scheduler.WorkerTask@1a143d0e] rejected from BoundedScheduledExecutorService{IDLE, queued=0/10000, completed=3}
	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2065) ~[?:?]

**Comment by conniey** [comment]
With regards to problem 1, to make sure we're on the same page, you were able to reproduce the problem by:
1. pulling from `main`, 
2. rebuilt the library
3. Ran the snippet above in: https://github.com/Azure/azure-sdk-for-java/issues/43649#issue-2762276886

With regards to problem 2,
1. Do you have a code sample where this occurs?

**Comment by kumaran-sowrirajan** [comment]
Yes, I pulled the latest beta version (5.21.0-beta.1) and tested. Let me know if you need code samples for both the issues.

**Comment by kumaran-sowrirajan** [comment]
> > Yes, I pulled the latest beta version (5.21.0-beta.1) and tested. Let me know if you need code samples for both the issues.
> 
> I released 5.21.0-beta.1 from a feature branch several days ago. I merged the fix for this into branch `main` yesterday. We release on a monthly cadence, so the fix would not be published until March.
> 
> And yes, if you could provide a code sample for Problem 2, that would be appreciated.

Sure, I will provide a code sample for problem #2.

**Comment by Amir-Qlik** [comment]
Hi Connie,

Thank you for your response.

I have just tried the snippet with 5.21.0-beta.2, and the issue does not reproduce with a hub that has 19 partitions.

Best regards,
Amir

**Comment by kumaran-sowrirajan** [comment]
> > > Yes, I pulled the latest beta version (5.21.0-beta.1) and tested. Let me know if you need code samples for both the issues.
> > 
> > 
> > I released 5.21.0-beta.1 from a feature branch several days ago. I merged the fix for this into branch `main` yesterday. We release on a monthly cadence, so the fix would not be published until March.
> > And yes, if you could provide a code sample for Problem 2, that would be appreciated.
> 
> Sure, I will provide a code sample for problem [#2](https://github.com/Azure/azure-sdk-for-java/issues/2).

Below is the test method to see the below exception. Let me know if you need more details about it. Thanks.

**Caused by: reactor.core.Exceptions$ReactorRejectedExecutionException: Scheduler unavailable
at reactor.core.Exceptions.failWithRejected(Exceptions.java:271) ~[reactor-core-3.4.41.jar:3.4.41]
at reactor.core.publisher.Operators.onRejectedExecution(Operators.java:1024) ~[reactor-core-3.4.41.jar:3.4.41]
... 30 more
Caused by: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@6e9afc06[Not completed, task =**


```java
import com.azure.messaging.eventhubs.EventData;
import com.azure.messaging.eventhubs.EventHubBufferedProducerClient;
import com.azure.messaging.eventhubs.EventHubBufferedProducerClientBuilder;
import com.azure.messaging.eventhubs.EventHubClientBuilder;
import com.azure.messaging.eventhubs.EventProcessorClient;
import com.azure.messaging.eventhubs.EventProcessorClientBuilder;
import com.azure.messaging.eventhubs.checkpointstore.blob.BlobCheckpointStore;
import com.azure.messaging.eventhubs.models.EventPosition;
import com.azure.storage.blob.BlobContainerAsyncClient;
import com.azure.storage.blob.BlobServiceAsyncClient;
import com.azure.storage.blob.BlobServiceClientBuilder;
import com.azure.storage.common.StorageSharedKeyCredential;
import java.time.Duration;
import java.time.Instant;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.CountDownLatch;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

public class EventHubConsumerSDKTest {

    /**
     * This test is to demonstrate the exception upon stopping the EventProcessorClient
     */
    @Test
    public void testConsumeEventsInBatchByEventHubConsumerClient() {
        //Event Hub details
        String connectionString = "<<REPLACE_THIS_WITH_YOUR_EVENT_HUB_CONNECTION_STRING>>";
        String eventHubName = "<<REPLACE_THIS_WITH_YOUR_EVENT_HUB_NAME>>";

        //Blob Storage Account details (for checkpointing)
        String accountName = "<<REPLACE_THIS_WITH_YOUR_STORAGE_ACCOUNT_NAME>>";
        String accountKey = "<<REPLACE_THIS_WITH_YOUR_STORAGE_ACCOUNT_KEY>>";
        String containerName = "<<REPLACE_THIS_WITH_YOUR_STORAGE_ACCOUNT_CONTAINER_NAME>>";
        String endpointUrl = "<<REPLACE_THIS_WITH_YOUR_STORAGE_ACCOUNT_ENDPOINT>>";
 
        List<String> events = List.of("one", "two", "three");
        int numberOfEvents = events.size();
        BlobServiceClientBuilder blobServiceClientBuilder = new BlobServiceClientBuilder();
        BlobServiceAsyncClient blobServiceClient = blobServiceClientBuilder.credential(new StorageSharedKeyCredential(accountName, accountKey)).endpoint(endpointUrl).buildAsyncClient();
        BlobContainerAsyncClient blobContainerClient = blobServiceClient.getBlobContainerAsyncClient(containerName);
        CountDownLatch latch = new CountDownLatch(numberOfEvents);
        Map<String, String> eventsByPartition = new HashMap<>();
        EventPosition startingPosition = EventPosition.fromEnqueuedTime(Instant.now());
        EventProcessorClientBuilder eventProcessorClientBuilder = new EventProcessorClientBuilder();
        EventProcessorClient eventProcessorClient = eventProcessorClientBuilder.eventHubName(eventHubName)
                .connectionString(connectionString)
                .consumerGroup(EventHubClientBuilder.DEFAULT_CONSUMER_GROUP_NAME)
                .processEventBatch(eventBatchContext -> {
                    for (EventData eventData : eventBatchContext.getEvents()) {
                        String partitionId = eventBatchContext.getPartitionContext().getPartitionId();
                        eventsByPartition.putIfAbsent(partitionId + "-" + eventData.getOffset(), eventData.getBodyAsString());
                        latch.countDown();
                    }
                }, 10, Duration.ofSeconds(10))
                .processError(errorContext -> System.out.println(errorContext.getThrowable().getMessage()))//This will show the //exception message. Inspect the stacktrace to find more detail about the exception.
                .initialPartitionEventPosition(partitionId -> startingPosition)
                .checkpointStore(new BlobCheckpointStore(blobContainerClient))
                .buildEventProcessorClient();
        EventHubBufferedProducerClient producerClient = new EventHubBufferedProducerClientBuilder()
                .connectionString(connectionString)
                .eventHubName(eventHubName)
                .onSendBatchSucceeded(context -> System.out.println("partition-id => " + context.getPartitionId()))
                .onSendBatchFailed(context -> System.out.println("context.getThrowable().getMessage() => " + context.getThrowable().getMessage()))
                .buildClient();
        eventProcessorClient.start();
        try (producerClient) {
            List<EventData> eventData = events.stream().map(EventData::new).toList();
            producerClient.enqueueEvents(eventData);
            producerClient.flush();
            latch.await();
            Assertions.assertEquals(0, latch.getCount(), "Latch count should be 0");
        } catch (Exception e) {
            Assertions.fail("Unable to publish an event", e);
        } finally {
            if (eventProcessorClient.isRunning()) {
                eventProcessorClient.stop();
            }
        }
    }
}
`

**Comment by kumaran-sowrirajan** [comment]
> > > > Yes, I pulled the latest beta version (5.21.0-beta.1) and tested. Let me know if you need code samples for both the issues.
> > > 
> > > 
> > > I released 5.21.0-beta.1 from a feature branch several days ago. I merged the fix for this into branch `main` yesterday. We release on a monthly cadence, so the fix would not be published until March.
> > > And yes, if you could provide a code sample for Problem 2, that would be appreciated.
> > 
> > 
> > Sure, I will provide a code sample for problem [#2](https://github.com/Azure/azure-sdk-for-java/issues/2).
> 
> Below is the test method to see the below exception. Let me know if you need more details about it. Thanks.
> 
> **Caused by: reactor.core.Exceptions$ReactorRejectedExecutionException: Scheduler unavailable at reactor.core.Exceptions.failWithRejected(Exceptions.java:271) ~[reactor-core-3.4.41.jar:3.4.41] at reactor.core.publisher.Operators.onRejectedExecution(Operators.java:1024) ~[reactor-core-3.4.41.jar:3.4.41] ... 30 more Caused by: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@6e9afc06[Not completed, task =**
> 
> import com.azure.messaging.eventhubs.EventData;
> import com.azure.messaging.eventhubs.EventHubBufferedProducerClient;
> import com.azure.messaging.eventhubs.EventHubBufferedProducerClientBuilder;
> import com.azure.messaging.eventhubs.EventHubClientBuilder;
> import com.azure.messaging.eventhubs.EventProcessorClient;
> import com.azure.messaging.eventhubs.EventProcessorClientBuilder;
> import com.azure.messaging.eventhubs.checkpointstore.blob.BlobCheckpointStore;
> import com.azure.messaging.eventhubs.models.EventPosition;
> import com.azure.storage.blob.BlobContainerAsyncClient;
> import com.azure.storage.blob.BlobServiceAsyncClient;
> import com.azure.storage.blob.BlobServiceClientBuilder;
> import com.azure.storage.common.StorageSharedKeyCredential;
> import java.time.Duration;
> import java.time.Instant;
> import java.util.HashMap;
> import java.util.List;
> import java.util.Map;
> import java.util.concurrent.CountDownLatch;
> import org.junit.jupiter.api.Assertions;
> import org.junit.jupiter.api.Test;
> 
> public class EventHubConsumerSDKTest {
> 
>     /**
>      * This test is to demonstrate the exception upon stopping the EventProcessorClient
>      */
>     @Test
>     public void testConsumeEventsInBatchByEventHubConsumerClient() {
>         //Event Hub details
>         String connectionString = "<<REPLACE_THIS_WITH_YOUR_EVENT_HUB_CONNECTION_STRING>>";
>         String eventHubName = "<<REPLACE_THIS_WITH_YOUR_EVENT_HUB_NAME>>";
> 
>         //Blob Storage Account details (for checkpointing)
>         String accountName = "<<REPLACE_THIS_WITH_YOUR_STORAGE_ACCOUNT_NAME>>";
>         String accountKey = "<<REPLACE_THIS_WITH_YOUR_STORAGE_ACCOUNT_KEY>>";
>         String containerName = "<<REPLACE_THIS_WITH_YOUR_STORAGE_ACCOUNT_CONTAINER_NAME>>";
>         String endpointUrl = "<<REPLACE_THIS_WITH_YOUR_STORAGE_ACCOUNT_ENDPOINT>>";
>  
>         List<String> events = List.of("one", "two", "three");
>         int numberOfEvents = events.size();
>         BlobServiceClientBuilder blobServiceClientBuilder = new BlobServiceClientBuilder();
>         BlobServiceAsyncClient blobServiceClient = blobServiceClientBuilder.credential(new StorageSharedKeyCredential(accountName, accountKey)).endpoint(endpointUrl).buildAsyncClient();
>         BlobContainerAsyncClient blobContainerClient = blobServiceClient.getBlobContainerAsyncClient(containerName);
>         CountDownLatch latch = new CountDownLatch(numberOfEvents);
>         Map<String, String> eventsByPartition = new HashMap<>();
>         EventPosition startingPosition = EventPosition.fromEnqueuedTime(Instant.now());
>         EventProcessorClientBuilder eventProcessorClientBuilder = new EventProcessorClientBuilder();
>         EventProcessorClient eventProcessorClient = eventProcessorClientBuilder.eventHubName(eventHubName)
>                 .connectionString(connectionString)
>                 .consumerGroup(EventHubClientBuilder.DEFAULT_CONSUMER_GROUP_NAME)
>                 .processEventBatch(eventBatchContext -> {
>                     for (EventData eventData : eventBatchContext.getEvents()) {
>                         String partitionId = eventBatchContext.getPartitionContext().getPartitionId();
>                         eventsByPartition.putIfAbsent(partitionId + "-" + eventData.getOffset(), eventData.getBodyAsString());
>                         latch.countDown();
>                     }
>                 }, 10, Duration.ofSeconds(10))
>                 .processError(errorContext -> System.out.println(errorContext.getThrowable().getMessage()))//This will show the //exception message. Inspect the stacktrace to find more detail about the exception.
>                 .initialPartitionEventPosition(partitionId -> startingPosition)
>                 .checkpointStore(new BlobCheckpointStore(blobContainerClient))
>                 .buildEventProcessorClient();
>         EventHubBufferedProducerClient producerClient = new EventHubBufferedProducerClientBuilder()
>                 .connectionString(connectionString)
>                 .eventHubName(eventHubName)
>                 .onSendBatchSucceeded(context -> System.out.println("partition-id => " + context.getPartitionId()))
>                 .onSendBatchFailed(context -> System.out.println("context.getThrowable().getMessage() => " + context.getThrowable().getMessage()))
>                 .buildClient();
>         eventProcessorClient.start();
>         try (producerClient) {
>             List<EventData> eventData = events.stream().map(EventData::new).toList();
>             producerClient.enqueueEvents(eventData);
>             producerClient.flush();
>             latch.await();
>             Assertions.assertEquals(0, latch.getCount(), "Latch count should be 0");
>         } catch (Exception e) {
>             Assertions.fail("Unable to publish an event", e);
>         } finally {
>             if (eventProcessorClient.isRunning()) {
>                 eventProcessorClient.stop();
>             }
>         }
>     }
> }
> `

Do you want me to create a separate issue for it? Please advise. Thanks.
