### ISSUE TITLE
Can not create servicebusservice on linux.

### ISSUE THREAD

**Issue by andymaguo** [Azure/azure-sdk-for-java#481]
Hi, my java code can run ok on windows but raise error on ubuntu.
Error Info is as below:
Exception in thread "main" java.lang.RuntimeException: Service or property not registered:  com.microsoft.windowsazure.services.servicebus.ServiceBusContract interface com.microsoft.windowsazure.services.servicebus.ServiceBusContract
        at com.microsoft.windowsazure.core.DefaultBuilder.build(DefaultBuilder.java:197)
        at com.microsoft.windowsazure.Configuration.create(Configuration.java:113)
        at com.microsoft.windowsazure.services.servicebus.ServiceBusService.create(ServiceBusService.java:52)

**Comment by martinsawicki** [comment]
the service bus client library is not in this repo anymore, so if this is still an issue, it should go there:
https://github.com/azure/azure-service-bus-java
