### ISSUE TITLE
The Azure SDK throws a NPE when using ManagedIdentityCredential in version 4.0.0-preview.1

### ISSUE THREAD

**Issue by chadccollins** [Azure/azure-sdk-for-java#4846]
We are using the "new" Azure SDK for Key Vault Secrets (azure-keyvault-secrets 4.0.0-preview.1, azure-identity 1.0.0-preview.1) and encountering Exceptions in some scenarios described below:

Scenario 1: `NullPointerException` with `DefaultAzureCredential`
Using `DefaultAzureCredential` (as in the docs in Github) should use the SPN credentials (AZURE_CLIENT_ID, ...) first, and then the MSI credentials (MSI_ENDPOINT, ...)
However, even if only a SPN is configured (i.e., AZURE_CLIEND_ID etc. are set, but not MSI_ENDPOINT), it will still try to fetch MSI credentials, which results in a `NullPointerException`

Sample Logs:
```
2019-07-31 07:44:33.677  WARN 16628 --- [parallel-3] c.a.s.k.secrets.SecretAsyncClient        : Failed to get secret - **secret name**

java.lang.NullPointerException: null
	at com.azure.core.implementation.RestProxy.endTracingSpan(RestProxy.java:578) ~[azure-core-1.0.0-preview.1.jar!/:na]
	at reactor.core.publisher.FluxDoOnEach$DoOnEachSubscriber.onError(FluxDoOnEach.java:172) ~[reactor-core-3.2.9.RELEASE.jar!/:3.2.9.RELEASE]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:165) ~[reactor-core-3.2.9.RELEASE.jar!/:3.2.9.RELEASE]
...
Suppressed: com.azure.core.exception.ClientAuthenticationException: No credential can provide a token in the chain
		at com.azure.identity.credential.ChainedTokenCredential.getToken(ChainedTokenCredential.java:54) ~[azure-identity-1.0.0-preview.1.jar!/:na]
		at com.azure.core.http.policy.BearerTokenAuthenticationPolicy.lambda$new$0(BearerTokenAuthenticationPolicy.java:49) ~[azure-core-1.0.0-preview.1.jar!/:na]
		at com.azure.core.credentials.SimpleTokenCache.lambda$getToken$2(SimpleTokenCache.java:46) ~[azure-core-1.0.0-preview.1.jar!/:na]
```

In addition, in our first tests, using `DefaultAzureCredential` caused a delay of roughly 1:30 to 2:00 minutes during the first call to the key vault. 

Scenario 2: `SocketException` with `ManagedIdentityCredential`
Using `ManagedIdentityCredential` results in a `SocketException` with "permission denied: connect"
```
2019-07-31 08:15:31.925  WARN 11924 --- [parallel-3] c.a.s.k.secrets.SecretAsyncClient        : Failed to get secret - **secret name**

java.net.SocketException: Permission denied: connect
...
Caused by: java.net.SocketException: Permission denied: connect
	at java.net.TwoStacksPlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_181]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_181]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_181]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_181]
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172) ~[na:1.8.0_181]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_181]
	at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_181]
	at java.net.Socket.connect(Socket.java:538) ~[na:1.8.0_181]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180) ~[na:1.8.0_181]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463) ~[na:1.8.0_181]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558) ~[na:1.8.0_181]
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242) ~[na:1.8.0_181]
	at sun.net.www.http.HttpClient.New(HttpClient.java:339) ~[na:1.8.0_181]
	at sun.net.www.http.HttpClient.New(HttpClient.java:357) ~[na:1.8.0_181]
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220) ~[na:1.8.0_181]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156) ~[na:1.8.0_181]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050) ~[na:1.8.0_181]
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984) ~[na:1.8.0_181]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564) ~[na:1.8.0_181]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492) ~[na:1.8.0_181]
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480) ~[na:1.8.0_181]
	at com.azure.identity.IdentityClient.authenticateToIMDSEndpoint(IdentityClient.java:248) ~[azure-identity-1.0.0-preview.1.jar!/:na]
	at com.azure.identity.credential.VirtualMachineMSICredential.authenticate(VirtualMachineMSICredential.java:50) ~[azure-identity-1.0.0-preview.1.jar!/:na]
	at com.azure.identity.credential.ManagedIdentityCredential.getToken(ManagedIdentityCredential.java:84) ~[azure-identity-1.0.0-preview.1.jar!/:na]
	at com.azure.core.http.policy.BearerTokenAuthenticationPolicy.lambda$new$0(BearerTokenAuthenticationPolicy.java:49) ~[azure-core-1.0.0-preview.1.jar!/:na]
	at com.azure.core.credentials.SimpleTokenCache.lambda$getToken$2(SimpleTokenCache.java:46) ~[azure-core-1.0.0-preview.1.jar!/:na]

```
Analyzing this further, it seems that `ManagedIdentityCredential` tries to use a `VirtualMachineMSICredential` internally, instead of a `AppServiceMSICredential`.

It seems that the required configuration values are not available when we construct `ManagedIdentityCredential`.
Manually fetching them (via `ConfigurationManager.getConfiguration().get(BaseConfigurations.MSI_ENDPOINT))` forces them to load; and `ManagedIdentityCredential` then correctly uses `AppServiceMSICredential`

At that point, finally, we do get a Bearer token in the app to talk to the key vault, but it seems the SDK cannot correctly parse the response.
```
2019-07-31 08:51:44.988  WARN 21716 --- [parallel-3] c.a.s.k.secrets.SecretAsyncClient        : Failed to get secret - **secret name**

com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `com.azure.identity.implementation.MSIToken`, problem: Unable to parse date time 7/31/2019 4:51:44 PM +00:00 
 at [Source: (String)"{"access_token":"eyJ0eXAiOiJKV....."[truncated 1000 chars]; line: 1, column: 1442]
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67) ~[jackson-databind-2.9.8.jar!/:2.9.8]
	at com.fasterxml.jackson.databind.DeserializationContext.instantiationException(DeserializationContext.java:1608) ~[jackson-databind-2.9.8.jar!/:2.9.8]
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.wrapAsJsonMappingException(StdValueInstantiator.java:484) ~[jackson-databind-2.9.8.jar!/:2.9.8]
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.rewrapCtorProblem(StdValueInstantiator.java:503) ~[jackson-databind-2.9.8.jar!/:2.9.8]
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:285) ~[jackson-databind-2.9.8.jar!/:2.9.8]
	at com.fasterxml.jackson.databind.deser.ValueInstantiator.createFromObjectWith(ValueInstantiator.java:229) ~[jackson-databind-2.9.8.jar!/:2.9.8]
	at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:195) ~[jackson-databind-2.9.8.jar!/:2.9.8]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:422) ~[jackson-databind-2.9.8.jar!/:2.9.8]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1287) ~[jackson-databind-2.9.8.jar!/:2.9.8]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326) ~[jackson-databind-2.9.8.jar!/:2.9.8]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159) ~[jackson-databind-2.9.8.jar!/:2.9.8]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013) ~[jackson-databind-2.9.8.jar!/:2.9.8]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3042) ~[jackson-databind-2.9.8.jar!/:2.9.8]
	at com.azure.core.implementation.serializer.jackson.JacksonAdapter.deserialize(JacksonAdapter.java:147) ~[azure-core-1.0.0-preview.1.jar!/:na]
	at com.azure.identity.IdentityClient.authenticateToManagedIdentityEnpoint(IdentityClient.java:192) ~[azure-identity-1.0.0-preview.1.jar!/:na]
	at com.azure.identity.credential.AppServiceMSICredential.authenticate(AppServiceMSICredential.java:94) ~[azure-identity-1.0.0-preview.1.jar!/:na]
	at com.azure.identity.credential.ManagedIdentityCredential.getToken(ManagedIdentityCredential.java:83) ~[azure-identity-1.0.0-preview.1.jar!/:na]
	at com.azure.core.http.policy.BearerTokenAuthenticationPolicy.lambda$new$0(BearerTokenAuthenticationPolicy.java:49) ~[azure-core-1.0.0-preview.1.jar!/:na]
	at com.azure.core.credentials.SimpleTokenCache.lambda$getToken$2(SimpleTokenCache.java:46) ~[azure-core-1.0.0-preview.1.jar!/:na]
```

**Comment by g2vinay** [comment]
Thank you very much for raising this issue.
Scenario 1 has been fixed in preview 2 release of key vault.
Investigating and trying to reproduce Scenario 2 issue in Azure Identity's ManagedIdentityCredential.
