### ISSUE TITLE
[BUG][Spell Check] spellChecker method path is only '/spellcheck'; should be '/bing/v7.0/spellcheck'

### ISSUE THREAD

**Issue by v-jaswel** [Azure/azure-sdk-for-java#4864]
**Describe the bug**
The path for the spell check method is '/spellcheck'. It should be '/bing/v7.0/spellcheck'.

***Exception or Stack Trace***
```
Status code 404, {"error":{"code":"404","message": "Resource not found"}}
com.microsoft.azure.cognitiveservices.language.spellcheck.models.ErrorResponseException: Status code 404, {"error":{"code":"404","message": "Resource not found"}}
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
        at com.microsoft.rest.ServiceResponseBuilder.build(ServiceResponseBuilder.java:122)
        at com.microsoft.azure.AzureResponseBuilder.build(AzureResponseBuilder.java:56)
        at com.microsoft.azure.cognitiveservices.language.spellcheck.implementation.BingSpellCheckOperationsImpl.spellCheckerDelegate(BingSpellCheckOperationsImpl.java:191)
        at com.microsoft.azure.cognitiveservices.language.spellcheck.implementation.BingSpellCheckOperationsImpl.access$000(BingSpellCheckOperationsImpl.java:36)
        at com.microsoft.azure.cognitiveservices.language.spellcheck.implementation.BingSpellCheckOperationsImpl$2.call(BingSpellCheckOperationsImpl.java:178)
        at com.microsoft.azure.cognitiveservices.language.spellcheck.implementation.BingSpellCheckOperationsImpl$2.call(BingSpellCheckOperationsImpl.java:174)
        at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
        at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$RequestArbiter.request(RxJavaCallAdapterFactory.java:173)
        at rx.Subscriber.setProducer(Subscriber.java:211)
        at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102)
        at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:152)
        at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:138)
        at rx.Observable.unsafeSubscribe(Observable.java:10142)
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.Observable.subscribe(Observable.java:10238)
        at rx.Observable.subscribe(Observable.java:10205)
        at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:444)
        at rx.observables.BlockingObservable.single(BlockingObservable.java:341)
        at com.microsoft.azure.cognitiveservices.language.spellcheck.implementation.BingSpellCheckOperationsImpl.spellChecker(BingSpellCheckOperationsImpl.java:76)
        at Quickstart.get_suggestions(Quickstart.java:52)
        at Quickstart.main(Quickstart.java:66)
```

**To Reproduce**
1. Copy the contents of `pom.xml` below into a file named `pom.xml`.
1. Copy the contents of `quickstart.java` below into a file named `quickstart.java`.
1. Create an environment variable named SPELLCHECK_SUBSCRIPTION_KEY, whose value is a valid Bing Spell Check subscription key.
1. Create an environment variable named SPELLCHECK_ENDPOINT, whose value is the endpoint that corresponds to your subscription key (for example, "https://westus.api.cognitive.microsoft.com").
1. Install Maven (https://maven.apache.org/download.cgi) if you don't have it.
1. Open an Administrator command prompt and navigate to the folder that contains pom.xml and quickstart.java.
1. Run `mvn clean dependency:copy-dependencies`
1. Run `javac Quickstart.java -cp .;lib\*`
1. Run `java -cp .;lib\* Quickstart`

***Code Snippet***
pom.xml:
```
<?xml version="1.0" encoding="utf-8"?>
<!--
Source: https://gist.github.com/statico/547434f630d589651afcbe3f132b91d9
Run with: mvn clean dependency:copy-dependencies
-->
<project
    xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.foo</groupId>
  <artifactId>bar</artifactId>
  <version>0.0.1-SNAPSHOT</version>

  <dependencies>

    <!-- https://mvnrepository.com/artifact/com.microsoft.azure.cognitiveservices/azure-cognitiveservices-spellcheck -->
    <dependency>
      <groupId>com.microsoft.azure.cognitiveservices</groupId>
      <artifactId>azure-cognitiveservices-spellcheck</artifactId>
      <version>1.0.2</version>
    </dependency>

    <!-- This fixes the following runtime warnings:
    SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
    SLF4J: Defaulting to no-operation (NOP) logger implementation
    SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
    -->
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-jdk14</artifactId>
      <version>1.7.25</version>
    </dependency>

  </dependencies>

  <build>
    <directory>lib</directory>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
        <configuration>
          <outputDirectory>
            ${project.build.directory}
          </outputDirectory>
        </configuration>
      </plugin>
    </plugins>
  </build>

</project>
```

quickstart.java:
```
import com.microsoft.azure.cognitiveservices.language.spellcheck.*;
import com.microsoft.azure.cognitiveservices.language.spellcheck.models.*;

import java.io.*;
import java.lang.Object.*;
import java.util.*;
import java.net.*;

public class Quickstart {
	private static String subscription_key = System.getenv("SPELLCHECK_SUBSCRIPTION_KEY");
	private static String endpoint = System.getenv("SPELLCHECK_ENDPOINT");
	BingSpellCheckAPI client = BingSpellCheckManager.authenticate(endpoint, subscription_key);

	public void get_suggestions() {
		SpellCheck result = client.bingSpellCheckOperations().spellChecker("bill gtaes", null);
		System.out.println("Results:");
		for (SpellingFlaggedToken token: result.flaggedTokens()) {
			System.out.println("Offset: " + token.offset() + "\nToken: " + token.token() + "\nType: " + token.type());
			for (SpellingTokenSuggestion suggestion: token.suggestions()) {
				System.out.println("Suggestion: " + suggestion.suggestion());
				System.out.println("Score: " + suggestion.score());
			}
		}
	}

	public static void main(String[] args) {
		try {
			Quickstart quickstart = new Quickstart();
			quickstart.get_suggestions();
		} catch (Exception e) {
			System.out.println(e.getMessage());
			e.printStackTrace();
		}
	}
}
```

**Expected behavior**
Expected output:
```
Results:
Offset: 0
Token: bill
Type: UnknownToken
Suggestion: Bill
Score: 0.875
Offset: 5
Token: gtaes
Type: UnknownToken
Suggestion: Gates
Score: 0.881035720497807
```

**Setup (please complete the following information):**
 - OS: Windows 10 Enterprise 1803
 - IDE : None
 - Version of the Library used
azure-cognitiveservices-spellcheck-1.0.2-beta

**Additional context**
I am able to resolve the issue and get the expected output as follows.

1. In [My Github base folder]\azure-sdk-for-java\cognitiveservices\data-plane\language\bingspellcheck\src\main\java\com\microsoft\azure\cognitiveservices\language\spellcheck\implementation\BingSpellCheckOperationsImpl.java, change line 59 from:
```
POST("spellcheck")
```
to:
```
@POST("/bing/v7.0/SpellCheck")
```
1. Recompile azure-cognitiveservices-spellcheck-1.0.2.jar from my modified source and place it in the `lib` subfolder of my project folder (i.e. where `quickstart.java` is).

Similar issues:
https://github.com/Azure/azure-sdk-for-java/issues/4560
https://github.com/Azure/azure-sdk-for-python/issues/6472

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by loarabia** [comment]
Hi @v-jaswel  thanks for the thorough writeup. I'm labeling this so the Cognitive Services team can find it.
