### ISSUE TITLE
[BUG] Delete Doesn't Work

### ISSUE THREAD

**Issue by Intern426** [Azure/azure-sdk-for-java#4867]
**Describe the bug**
When I ran a modified version of the HelloWorld sample, the program crashed when it tried to  access the item and delete it.

Hello world example: https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/cosmos#example

***Exception or Stack Trace***
```
Exception in thread "main" reactor.core.Exceptions$ReactiveException: CosmosClientException{error={"code":"NotFound","message":"Entity with the specified id does not exist in the system., \r\nRequestStartTime: 2019-08-06T19:01:20.5144438Z, RequestEndTime: 2019-08-06T19:01:20.5244479Z, Number of regions attempted: 1\r\nResponseTime: 2019-08-06T19:01:20.5244479Z, StoreResult: StorePhysicalAddress: rntbd://cdb-ms-prod-westus1-fd25.documents.azure.com:14021/apps/0ef3b69a-b349-44f8-b0b2-d8c7a1df76aa/services/653efaed-8801-4c2a-aaa3-ff6ea0032a63/partitions/15dfd675-921c-4848-9918-b3b97564cfe2/replicas/132095372851250224s/, LSN: 3, GlobalCommittedLsn: 2, PartitionKeyRangeId: 0, IsValid: True, StatusCode: 404, SubStatusCode: 0, RequestCharge: 1, ItemLSN: -1, SessionToken: -1#3, UsingLocalLSN: True, TransportException: null, ResourceType: Document, OperationType: Read\r\n, Microsoft.Azure.Documents.Common/2.5.1, StatusCode: NotFound","additionalErrorInfo":null}, resourceAddress='null', statusCode=404, message=Entity with the specified id does not exist in the system., 
RequestStartTime: 2019-08-06T19:01:20.5144438Z, RequestEndTime: 2019-08-06T19:01:20.5244479Z, Number of regions attempted: 1
ResponseTime: 2019-08-06T19:01:20.5244479Z, StoreResult: StorePhysicalAddress: rntbd://cdb-ms-prod-westus1-fd25.documents.azure.com:14021/apps/0ef3b69a-b349-44f8-b0b2-d8c7a1df76aa/services/653efaed-8801-4c2a-aaa3-ff6ea0032a63/partitions/15dfd675-921c-4848-9918-b3b97564cfe2/replicas/132095372851250224s/, LSN: 3, GlobalCommittedLsn: 2, PartitionKeyRangeId: 0, IsValid: True, StatusCode: 404, SubStatusCode: 0, RequestCharge: 1, ItemLSN: -1, SessionToken: -1#3, UsingLocalLSN: True, TransportException: null, ResourceType: Document, OperationType: Read
, Microsoft.Azure.Documents.Common/2.5.1, StatusCode: NotFound, causeInfo=null, responseHeaders={Transfer-Encoding=chunked, x-ms-last-state-change-utc=Tue, 06 Aug 2019 03:55:00.213 GMT, Server=Microsoft-HTTPAPI/2.0, x-ms-session-token=0:-1#3, lsn=3, x-ms-request-charge=1, Content-Location=https://book221-westus.documents.azure.com/dbs/book-inventory/colls/book-infoz/docs/4f7624e1-30c7-4dc9-837f-fa5c7f079431, x-ms-schemaversion=1.8, x-ms-transport-request-id=1, x-ms-number-of-read-regions=0, Date=Tue, 06 Aug 2019 19:01:20 GMT, x-ms-activity-id=58045105-f2f8-47da-acbf-93648b351fe2, Strict-Transport-Security=max-age=31536000, x-ms-xp-role=1, x-ms-global-Committed-lsn=2, x-ms-cosmos-llsn=3, x-ms-gatewayversion=version=2.5.1, x-ms-serviceversion=version=2.4.0.0, Content-Type=application/json}, requestHeaders={authorization=type%3Dmaster%26ver%3D1.0%26sig%3DicaICRDnFJ5%2FgqdPToDFjmy5VAFweYfHkGqXi7z6oqM%3D, Accept=application/json, x-ms-date=Tue, 06 Aug 2019 19:01:20 GMT, x-ms-documentdb-partitionkey=[null]}}
	at reactor.core.Exceptions.propagate(Exceptions.java:326)
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:91)
	at reactor.core.publisher.Mono.block(Mono.java:1494)
	at com.azure.app.DeleteWork.main(DeleteWork.java:37)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:93)
		... 2 more
Caused by: CosmosClientException{error={"code":"NotFound","message":"Entity with the specified id does not exist in the system., \r\nRequestStartTime: 2019-08-06T19:01:20.5144438Z, RequestEndTime: 2019-08-06T19:01:20.5244479Z, Number of regions attempted: 1\r\nResponseTime: 2019-08-06T19:01:20.5244479Z, StoreResult: StorePhysicalAddress: rntbd://cdb-ms-prod-westus1-fd25.documents.azure.com:14021/apps/0ef3b69a-b349-44f8-b0b2-d8c7a1df76aa/services/653efaed-8801-4c2a-aaa3-ff6ea0032a63/partitions/15dfd675-921c-4848-9918-b3b97564cfe2/replicas/132095372851250224s/, LSN: 3, GlobalCommittedLsn: 2, PartitionKeyRangeId: 0, IsValid: True, StatusCode: 404, SubStatusCode: 0, RequestCharge: 1, ItemLSN: -1, SessionToken: -1#3, UsingLocalLSN: True, TransportException: null, ResourceType: Document, OperationType: Read\r\n, Microsoft.Azure.Documents.Common/2.5.1, StatusCode: NotFound","additionalErrorInfo":null}, resourceAddress='null', statusCode=404, message=Entity with the specified id does not exist in the system., 
RequestStartTime: 2019-08-06T19:01:20.5144438Z, RequestEndTime: 2019-08-06T19:01:20.5244479Z, Number of regions attempted: 1
ResponseTime: 2019-08-06T19:01:20.5244479Z, StoreResult: StorePhysicalAddress: rntbd://cdb-ms-prod-westus1-fd25.documents.azure.com:14021/apps/0ef3b69a-b349-44f8-b0b2-d8c7a1df76aa/services/653efaed-8801-4c2a-aaa3-ff6ea0032a63/partitions/15dfd675-921c-4848-9918-b3b97564cfe2/replicas/132095372851250224s/, LSN: 3, GlobalCommittedLsn: 2, PartitionKeyRangeId: 0, IsValid: True, StatusCode: 404, SubStatusCode: 0, RequestCharge: 1, ItemLSN: -1, SessionToken: -1#3, UsingLocalLSN: True, TransportException: null, ResourceType: Document, OperationType: Read
, Microsoft.Azure.Documents.Common/2.5.1, StatusCode: NotFound, causeInfo=null, responseHeaders={Transfer-Encoding=chunked, x-ms-last-state-change-utc=Tue, 06 Aug 2019 03:55:00.213 GMT, Server=Microsoft-HTTPAPI/2.0, x-ms-session-token=0:-1#3, lsn=3, x-ms-request-charge=1, Content-Location=https://book221-westus.documents.azure.com/dbs/book-inventory/colls/book-infoz/docs/4f7624e1-30c7-4dc9-837f-fa5c7f079431, x-ms-schemaversion=1.8, x-ms-transport-request-id=1, x-ms-number-of-read-regions=0, Date=Tue, 06 Aug 2019 19:01:20 GMT, x-ms-activity-id=58045105-f2f8-47da-acbf-93648b351fe2, Strict-Transport-Security=max-age=31536000, x-ms-xp-role=1, x-ms-global-Committed-lsn=2, x-ms-cosmos-llsn=3, x-ms-gatewayversion=version=2.5.1, x-ms-serviceversion=version=2.4.0.0, Content-Type=application/json}, requestHeaders={authorization=type%3Dmaster%26ver%3D1.0%26sig%3DicaICRDnFJ5%2FgqdPToDFjmy5VAFweYfHkGqXi7z6oqM%3D, Accept=application/json, x-ms-date=Tue, 06 Aug 2019 19:01:20 GMT, x-ms-documentdb-partitionkey=[null]}}
```

**To Reproduce**
Create an Azure Cosmos DB account. 
In the code, enter the endpoint and key in their respective Strings.

***Code Snippet***
https://github.com/Intern426/azure-sdk-for-java/blob/master/DeleteWork.java

**Comment by shurd** [comment]
Hi @Intern426, thank you for raising this issue. I looked into it, and you should specify the partition key when creating the item:

```java
PartitionKey pk = new PartitionKey(book.id);
CosmosItemRequestOptions options = new CosmosItemRequestOptions();
options.partitionKey(pk);

container.createItem(book, options) ...
```

**Comment by kirankumarkolli** [comment]
@Intern426 please validate and re-open if needed.
