### ISSUE TITLE
ARM API: handle retryable error?

### ISSUE THREAD

**Issue by xindzhan** [Azure/azure-sdk-for-java#501]
The following error happened a few times in the test and since it's a retryable error, does java SDK currently has any way to auto retry that? Or is this something we can target in swagger?

> java.util.concurrent.ExecutionException: com.microsoft.windowsazure.exception.ServiceException: RetryableError: A retryable error occured.
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.microsoft.azure.management.network.NetworkInterfaceOperationsImpl.createOrUpdate(NetworkInterfaceOperationsImpl.java:956)
	at com.microsoft.azure.utility.NetworkHelper.createNIC(NetworkHelper.java:109)
	at com.microsoft.azure.utility.ComputeHelper.createVM(ComputeHelper.java:260)
	at com.microsoft.azure.utility.compute.ComputeTestBase.createVM(ComputeTestBase.java:243)
	at com.microsoft.azure.utility.compute.ComputeTestBase.createVM(ComputeTestBase.java:225)
	at com.microsoft.azure.utility.compute.ComputeTestBase.createVM(ComputeTestBase.java:218)
	at com.microsoft.azure.utility.compute.VMDataDiskTests.testVMDataDiskScenario(VMDataDiskTests.java:61)
Caused by: com.microsoft.windowsazure.exception.ServiceException: RetryableError: A retryable error occured.
	at com.microsoft.windowsazure.exception.ServiceException.createFromJson(ServiceException.java:292)
	at com.microsoft.azure.management.network.NetworkInterfaceOperationsImpl.beginCreateOrUpdating(NetworkInterfaceOperationsImpl.java:396)
	at com.microsoft.azure.management.network.NetworkInterfaceOperationsImpl$1.call(NetworkInterfaceOperationsImpl.java:107)
	at com.microsoft.azure.management.network.NetworkInterfaceOperationsImpl$1.call(NetworkInterfaceOperationsImpl.java:104)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by xindzhan** [comment]
@devigned @ljhljh235

**Comment by matt-gibbs** [comment]
There are ServiceFilters for automatic retries. This directory has a few: https://github.com/Azure/azure-sdk-for-java/tree/master/core/azure-core/src/main/java/com/microsoft/windowsazure/core/pipeline/jersey The Swagger won't define the retry options. The client code can specify the which one to use or plug in a custom one.
