### ISSUE TITLE
Netty Exception: java.io.IOException: Connection reset by peer

### ISSUE THREAD

**Issue by kushagraThapar** [Azure/azure-sdk-for-java#5052]
**Describe the bug**
Netty experiences connection issues in both TCP and Https Connection mode, with Pooled Connection Provider, which causes Connection to break after some time. 

***Exception or Stack Trace***
```
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:247)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1140)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:697)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:632)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:549)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:511)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.lang.Thread.run(Thread.java:748)
```

**To Reproduce**
ReadMyWritesConsistencyTest

***Code Snippet***
N/A

**Expected behavior**
If connection is idle, it should get closed silently, and no error should be thrown.

**Comment by gsehgal** [comment]
Hi,
       I am facing the same issue, I am using : azure-storage-blob:12.0.0-preview.4, Can you please tell me what the fix to this is?

Regards,
Gaurav

**Comment by kushagraThapar** [comment]
> Hi,
> I am facing the same issue, I am using : azure-storage-blob:12.0.0-preview.4, Can you please tell me what the fix to this is?
> 
> Regards,
> Gaurav

We fixed this using latest version of reactor - netty, which maintains its own connection pool. 
https://github.com/reactor/reactor-netty/releases/tag/v0.9.0.RELEASE
