### ISSUE TITLE
Test failures in 0.8.0

### ISSUE THREAD

**Issue by paksv** [Azure/azure-sdk-for-java#524]
Guys, it is a general practice that releases contain not only sources, but binaries as well. I don't want to build by myself, especially when executing **mvn package** against 0.8.0 release gives the error below
(Luckily, **mvn -Dmaven.test.skip=true package** succeeded), but anyway not nice:
...
Running com.microsoft.azure.keyvault.test.KeyOperationsTest
Waiting to avoid throttling
Waiting to avoid throttling
Waiting to avoid throttling
Waiting to avoid throttling
Waiting to avoid throttling
Waiting to avoid throttling
Waiting to avoid throttling
Waiting to avoid throttling
Waiting to avoid throttling
Waiting to avoid throttling
Waiting to avoid throttling
Waiting to avoid throttling
Waiting to avoid throttling
Waiting to avoid throttling
Waiting to avoid throttling
Tests run: 9, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 3.73 sec <<< FAILURE! - in com.microsoft.azure.keyvault.test.KeyOperationsTest
listKeys(com.microsoft.azure.keyvault.test.KeyOperationsTest)  Time elapsed: 0.682 sec  <<< ERROR!
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(Unknown Source)
	at java.util.concurrent.FutureTask.get(Unknown Source)
	at com.microsoft.azure.keyvault.FutureAdapter.get(FutureAdapter.java:53)
	at com.microsoft.azure.keyvault.test.KeyOperationsTest.listKeys(KeyOperationsTest.java:382)
Caused by: java.lang.NullPointerException: null
	at com.microsoft.windowsazure.exception.ServiceException.create(ServiceException.java:158)
	at com.microsoft.azure.keyvault.KeyOperationsImpl.deleteKey(KeyOperationsImpl.java:516)
	at com.microsoft.azure.keyvault.KeyOperationsImpl$4.call(KeyOperationsImpl.java:443)
	at com.microsoft.azure.keyvault.KeyOperationsImpl$4.call(KeyOperationsImpl.java:440)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

Running com.microsoft.azure.keyvault.test.SecretOperationsTest
Tests run: 4, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.191 sec <<< FAILURE! - in com.microsoft.azure.keyvault.test.SecretOperationsTest
listSecrets(com.microsoft.azure.keyvault.test.SecretOperationsTest)  Time elapsed: 0.515 sec  <<< ERROR!
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(Unknown Source)
	at java.util.concurrent.FutureTask.get(Unknown Source)
	at com.microsoft.azure.keyvault.FutureAdapter.get(FutureAdapter.java:53)
	at com.microsoft.azure.keyvault.test.SecretOperationsTest.listSecrets(SecretOperationsTest.java:257)
Caused by: java.lang.NullPointerException: null
	at com.microsoft.windowsazure.exception.ServiceException.create(ServiceException.java:158)
	at com.microsoft.azure.keyvault.SecretOperationsImpl.delete(SecretOperationsImpl.java:153)
	at com.microsoft.azure.keyvault.SecretOperationsImpl$1.call(SecretOperationsImpl.java:88)
	at com.microsoft.azure.keyvault.SecretOperationsImpl$1.call(SecretOperationsImpl.java:85)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
...

**Comment by paksv** [comment]
I did some extra digging, accordning to documentation HttpEntity#getContentType() is nullable as well as HttpResponse#getEntity()  (https://hc.apache.org/httpcomponents-core-ga/httpcore/apidocs/org/apache/http/HttpEntity.html#getContentType() https://hc.apache.org/httpcomponents-core-ga/httpcore/apidocs/org/apache/http/HttpResponse.html#getEntity()). 
Need to add an extra check wherever applicable.

**Comment by jianghaolu** [comment]
The latest release is 0.8.3 and you should be able to get the binaries from maven central. 
Could you verify if the issue still exists?

**Comment by jianghaolu** [comment]
Closing as we haven't heard back from you. We assume this is no longer an issue for you. Please reopen if necessary.

Thanks for reporting issues to Azure SDK for Java.
Jianghao

**Comment by paksv** [comment]
I apologize for delay - didn't yet had time to look. Apparently, the issue still exists in 0.8.3. Attaching build log
[output.txt](https://github.com/Azure/azure-sdk-for-java/files/41776/output.txt)
