### ISSUE TITLE
PFX certificate are not working in web app without adding it to Windows Personal Keystore

### ISSUE THREAD

**Issue by ssuriya** [Azure/azure-sdk-for-java#527]
We are using Azure Management Libraries for Java to fetch NetworkSecurityGroup details. We are able to fetch it using JKS certificate file, but if we use PFX certificate, below exception is thrown. This code is part of Java based web application that is deployed inside tomcat. 

``` Java
java.io.IOException: Could not decrypt data. at com.rsa.cryptoj.o.lk.b(Unknown Source) at 
com.rsa.cryptoj.o.lk.a(Unknown Source) at com.rsa.cryptoj.o.lk.a(Unknown Source) at 
com.rsa.cryptoj.o.lk.a(Unknown Source) at com.rsa.cryptoj.o.lk.a(Unknown Source) at 
com.rsa.cryptoj.o.lk.engineLoad(Unknown Source) at 
java.security.KeyStore.load(KeyStore.java:1214) at 
com.microsoft.windowsazure.core.utils.SSLContextFactory.getKeyManagers(SSLContextFactory.java:185) at 
com.microsoft.windowsazure.core.utils.SSLContextFactory.create(SSLContextFactory.java:133) at 
com.microsoft.windowsazure.core.utils.SSLContextFactory.create(SSLContextFactory.java:60) at 
com.microsoft.windowsazure.credentials.CertificateCloudCredentials.applyConfig(CertificateCloudCredentials.java:128) at 
com.microsoft.windowsazure.core.pipeline.apache.Exports$2.create(Exports.java:53) at 
com.microsoft.windowsazure.core.pipeline.apache.Exports$2.create(Exports.java:43) at 
com.microsoft.windowsazure.core.DefaultBuilder.build(DefaultBuilder.java:200) at 
com.microsoft.windowsazure.core.pipeline.apache.Exports$3.create(Exports.java:67) at 
com.microsoft.windowsazure.core.pipeline.apache.Exports$3.create(Exports.java:60) at 
com.microsoft.windowsazure.core.DefaultBuilder.build(DefaultBuilder.java:200) at 
com.microsoft.windowsazure.core.DefaultBuilder$1.create(DefaultBuilder.java:138) at 
com.microsoft.windowsazure.core.DefaultBuilder.build(DefaultBuilder.java:200) at 
com.microsoft.windowsazure.Configuration.create(Configuration.java:113) at 
com.microsoft.windowsazure.management.network.NetworkManagementService.create(NetworkManagementService.java:51) at 
com.mcafee.mdcc.azure.connector.AzureCloudConnector.getAzureNetworkSecurityGroups(AzureCloudConnector.java:405) 

```

This link (azure.microsoft.com/en-us/blog/getting-started-with-the-azure-java-management-libraries/) advice to convert PFX file into JKS file, but clear details on PFX files support is not available there. 

I'm using the below code: 

``` Java
Configuration config = ManagementConfiguration.configure(new URI(baseURL), subscriptionId, keyStoreFile.getPath(), keyStorePassword, AzureConnectorConstants.EXTENSION_PFX.equals(extension)? KeyStoreType.pkcs12 : KeyStoreType.jks); 
NetworkManagementClient networkManagementClient = NetworkManagementService.create(config); 
NetworkSecurityGroupOperations NSGOps = networkManagementClient.getNetworkSecurityGroupsOperations(); 
NetworkSecurityGroupListResponse nsgResp = NSGOps.list(); 
nsgList = nsgResp.getNetworkSecurityGroups(); 
```

This code doesn't throw the exception in standalone Java Project, PFX certificate works, but in case of web project, it is throwing the exception. Am I missing something or PFX certificates are not supported in Java based web projects? 

Note 1: PFX certificate works in direct REST API calls, but Azure SDK for Java throws exception. 
Note 2: We do not want to import the PFX into keystore (certmgr.msc) on the web server machine.

**Comment by martinsawicki** [comment]
Obsolete - pls use the latest version of the Azure Management Libraries for Java
