### ISSUE TITLE
Authentication failed while trying to use NetworkResourceProviderClient

### ISSUE THREAD

**Issue by harish143us** [Azure/azure-sdk-for-java#536]
Hi

 I'm getting the Exception while trying the following code. I'm able to use

  NetworkResourceProviderClient  networkResourceProviderClient = NetworkResourceProviderService.create(config);
	       PublicIpAddressListResponse PublicIpAddressListResponse =networkResourceProviderClient.getPublicIpAddressesOperations().listAll();
	       ArrayList<PublicIpAddress> PublicIpAddressList =PublicIpAddressListResponse.getPublicIpAddresses();
	       System.out.println(PublicIpAddressList.size());

This is the Exception info.
Exception in thread "main" com.microsoft.windowsazure.exception.ServiceException: AuthenticationFailed: Authentication failed. The 'Authorization' header is not present or provided in an invalid format.
	at com.microsoft.windowsazure.exception.ServiceException.createFromJson(ServiceException.java:290)
	at com.microsoft.azure.management.network.PublicIpAddressOperationsImpl.listAll(PublicIpAddressOperationsImpl.java:1443)
	at com.microsoft.azure.auth.Program.main(Program.java:50)

could you please let me know what went wrong here?

**Comment by jianghaolu** [comment]
You need to authenticate through ADAL first before making actual requests. 

You can follow the way this test is authenticating in your application: https://github.com/Azure/azure-sdk-for-java/blob/master/resource-management/azure-mgmt-resources/src/test/java/com/microsoft/azure/ResourceManagementIntegrationTestBase.java

**Comment by jianghaolu** [comment]
Closing as we haven't heard back from you. We assume this is no longer an issue for you. Please reopen if necessary.

Thanks for reporting issues to Azure SDK for Java.
Jianghao
