### ISSUE TITLE
ARM Storage client throwing error for listByResouceGroup

### ISSUE THREAD

**Issue by xindzhan** [Azure/azure-sdk-for-java#538]
Stack trace:

java.lang.IllegalArgumentException: No enum constant com.microsoft.azure.management.storage.models.AccountStatus.available
	at java.lang.Enum.valueOf(Enum.java:238)
	at com.microsoft.azure.management.storage.StorageAccountOperationsImpl.listByResourceGroup(StorageAccountOperationsImpl.java:1767)
	at com.microsoft.azure.utility.StorageHelper.createStorageAccount(StorageHelper.java:79)
	at com.microsoft.azure.utility.StorageHelper.createStorageAccount(StorageHelper.java:53)
	at com.microsoft.azure.utility.ComputeHelper.createVM(ComputeHelper.java:265)
	at com.microsoft.azure.utility.compute.ComputeTestBase.createVM(ComputeTestBase.java:244)

**Comment by moshjeier** [comment]
I'm seeing the same thing, it looks like the case of the AccountStatus enum changed from all upper case (AVAILABLE) to only having the first letter upper cased (Available).

**Comment by devigned** [comment]
@jianghaolu would you give an update on status of this defect?

**Comment by mayurid** [comment]
@xindzhan : This is fixed in 0.9.0 and been published to Maven.
Please try and let us know if you still see this
