### ISSUE TITLE
Error when using sbt

### ISSUE THREAD

**Issue by LirazRom** [Azure/azure-sdk-for-java#539]
I am trying to use the sdk in scala
I have several problems which looks like bug

1. build.sbt 
libraryDependencies ++= Seq(
  "com.microsoft.azure"          % "azure-mgmt-resources"        % "0.8.3",
  "com.microsoft.azure"          % "azure-management" % "0.8.0",
  "com.microsoft.azure"          % "azure-storage"              % "4.0.0",
  "com.microsoft.azure"          % "azure-mgmt-utility"         % "0.8.3" ,
  "com.sun.jersey"               % "jersey-core"                % "1.19"
)
when the projects is refreshed there is an error

Error:Error while importing SBT project:
...
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] sbt.ResolveException: unresolved dependency: commons-codec#commons-codec;[1.10,): java.text.ParseException: inconsistent module descriptor file found in 'https://repo1.maven.org/maven2/commons-codec/commons-codec/20041127.091804/commons-codec-20041127.091804.pom': bad revision: expected='20041127.091804' found='1.3'; 
[error] Use 'last' for the full log.
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=384M; support was removed in 8.0

See complete log in C:\Users\liraz\.IntelliJIdea14\system\log\sbt.last.log

which seems that there is incorrect reference - regarding to version
 "com.microsoft.azure"          % "azure-mgmt-utility"         % "0.8.3" exclude ("commons-codec", "commons-codec") --> fixes it

and when i try to compile the project i get the microsoft isnt part of com object

**Comment by devigned** [comment]
We were bringing in commons-codec through adal4j, which is now fixed in the master branch. Thank you for pointing this out.

fyi, the azure-management artifact is moved to azure-svc-mgmt see: http://mvnrepository.com/artifact/com.microsoft.azure/azure-management. 

Also, you look like you are using Azure Resource Manager jars azure-mgmt-*, the azure-svc-* are Azure Service Management (legacy Azure). You should stick with the azure-mgmt-* if you would like the latest functionality.

**Comment by devigned** [comment]
@jianghaolu please close this after publication of the new jars.

**Comment by mayurid** [comment]
@LirazRom :0.9.0 is published in maven and this issue should be addressed. Please let us know and reopen this item if you still see this
