### ISSUE TITLE
[BUG]The client java return the messageId after 30 or more seconds.

### ISSUE THREAD

**Issue by mzegarras** [Azure/azure-sdk-for-java#5393]
**Describe the bug**
The client java return the messageId after 30 or more seconds.
The topic has about 40k messages.
When We do put in topic, it generated exception.

***Exception or Stack Trace***

com.microsoft.azure.servicebus.primitives.TimeoutException: Send operation timed out  at  2019-08-13T16:48:43.015825-05:00[America/Lima].
    at com.microsoft.azure.servicebus.primitives.CoreMessageSender.throwSenderTimeout(CoreMessageSender.java:912) ~[azure-servicebus-1.2.15.jar!/:na]
    at com.microsoft.azure.servicebus.primitives.CoreMessageSender.access$500(CoreMessageSender.java:59) ~[azure-servicebus-1.2.15.jar!/:na]
    at com.microsoft.azure.servicebus.primitives.CoreMessageSender$3.run(CoreMessageSender.java:261) ~[azure-servicebus-1.2.15.jar!/:na]
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[na:na]
    at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
    at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[na:na]
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
    at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]

**To Reproduce**

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - Maven
 - AKS
 - Dependecy:
      <dependency>
                <groupId>com.microsoft.azure</groupId>
                <artifactId>azure-servicebus</artifactId>
                <version>2.0.0</version>
            </dependency>

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by jfggdl** [comment]
@mzegarras, thank you for reporting this issue. We are working on this and we will try to reproduce this. Would you able to share the code snippet of your client? Please do not include any sensitive information. Thanks.

**Comment by mzegarras** [comment]
The delay occurred in "topicClient.sendAsync", after  about 30 seconds we recivied azureMessage.getMessageId().

`@Override
	public void publish(String message, String contentType, String label) {

		Message azureMessage = new Message(message, contentType);
		if (isNotEmpty(label)) {
			azureMessage.setLabel(label);
		}

		Span sendSpan = TracingMessageUtils.buildAndInjectSpan(topicClient.getTopicName(),azureMessage, GlobalTracer.get());

		LOGGER.debug("Azure try to publish: <{}>,<{}>", label, message);
		sendSpan.setTag(Tags.MESSAGE_BUS_DESTINATION,topicClient.getTopicName());


		try {
			topicClient.sendAsync(azureMessage).thenRunAsync(() -> {
				LOGGER.debug("Azure Published: <{}>,<{}>", label, message);
				sendSpan.setTag("message_bus.acknowledged",azureMessage.getMessageId());
				sendSpan.finish();
			});

		} catch (Exception ex){
			SpanEventBusDecorator.onError(ex, sendSpan);
			sendSpan.finish();
			throw ex;
		}
	}`

**Comment by jfggdl** [comment]
@mzegarras, would you please create a support request through the azure portal? This might be a service-side problem and for those kind of issues the Azure Support Engineers are an appropriate channel for support. Please share you case id here.
