### ISSUE TITLE
Failed to get StorageAccount properties

### ISSUE THREAD

**Issue by LirazRom** [Azure/azure-sdk-for-java#544]
I am trying to get the storageAccount properties and getting exception
azure-mgmt-storage 0.8.3

Exception in thread "main" java.lang.IllegalArgumentException: No enum constant com.microsoft.azure.management.storage.models.AccountStatus.available
	at java.lang.Enum.valueOf(Enum.java:238)
	at com.microsoft.azure.management.storage.StorageAccountOperationsImpl.getProperties(StorageAccountOperationsImpl.java:1148)

**Comment by jianghaolu** [comment]
Hi @LirazRom 

Thanks for reporting this issue. It should be fixed in 0.9.0, please reopen if you 0.9.0 does not solve your problem.

Thanks,
Jianghao
