### ISSUE TITLE
Calling StorageHelper.listStorageAccounts method generates error: "SubscriptionNotFound" even though subscription does exist

### ISSUE THREAD

**Issue by jonbullock** [Azure/azure-sdk-for-java#552]
I edited my local copy of ServicePrincipalExample with the relevant details and got it to run OK, however when I replaced the main code in ServicePrincipalExample with:

````
    	Configuration config = createConfiguration();
    	StorageManagementClient storageClient = StorageManagementService.create(config);
    	List<StorageAccount> storageAccounts = StorageHelper.listStorageAccounts(storageClient, null);
    	for (StorageAccount storAcc : storageAccounts) {
    		System.out.println(storAcc.getName());
    	}
````
I always get the following stacktrace:

````
Exception in thread "main" java.util.concurrent.ExecutionException: com.microsoft.windowsazure.exception.ServiceException: SubscriptionNotFound: Subscription e4002xxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx was not found.
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:188)
	at com.microsoft.azure.utility.StorageHelper.listStorageAccounts(StorageHelper.java:186)
	at com.company.azure.auth.ServicePrincipalExample.main(ServicePrincipalExample.java:82)
Caused by: com.microsoft.windowsazure.exception.ServiceException: SubscriptionNotFound: Subscription e4002xxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx was not found.
	at com.microsoft.windowsazure.exception.ServiceException.createFromJson(ServiceException.java:290)
	at com.microsoft.azure.management.storage.StorageAccountOperationsImpl.list(StorageAccountOperationsImpl.java:1355)
	at com.microsoft.azure.management.storage.StorageAccountOperationsImpl$6.call(StorageAccountOperationsImpl.java:1284)
	at com.microsoft.azure.management.storage.StorageAccountOperationsImpl$6.call(StorageAccountOperationsImpl.java:1281)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
````
The subscription does exist and my service principal has been granted the contributor role for the subscription. I've even added 'Classic Storage Account Contributor' as well as 'Storage Account Contributor' roles but they have had no effect.

**Comment by jonbullock** [comment]
I've granted the same Service Principal access to a more recently created Subscription (Contributor role), updated the subscription ID in the code and run it again. This time I don't receive an error but I don't get a list of storage accounts printed out either. The original block of code to print out the names of ResourceGroupExtended works though.

**Comment by devigned** [comment]
@jonbullock were the storage account created using Azure Resource Manager (the new portal) or were they created in Azure Service Management (the old portal)?

**Comment by jonbullock** [comment]
@devigned they were created using the Azure Service Management (the old portal).

**Comment by devigned** [comment]
@jonbullock the package we use in the example makes a request to Azure Resource Manager (com.microsoft.azure). The (com.microsoft.windowsazure) packages are Service Management based. This is terribly confusing, I know. We'll address this in an upcoming release.

Please make a storage account in the new portal and verify you can list it with the example.

**Comment by jonbullock** [comment]
@devigned Now I've created a storage account using the new portal my original code works.

I assumed that it didn't matter which portal I used to create the resources in, but I guess it does.

**Comment by devigned** [comment]
@jonbullock it's the disconnect between the V1 apis (Service management) and the V2 apis (Resource manager). It's pretty confusing. Stick to one, preferably V2, and you should be much happier.
