### ISSUE TITLE
Don't swallow exceptions in CertificateCloudCredentials

### ISSUE THREAD

**Issue by dadoonet** [Azure/azure-sdk-for-java#565]
Heya,

Sounds like that in `CertificateCloudCredentials`, you are swallowing exceptions. See https://github.com/Azure/azure-sdk-for-java/blob/master/core/azure-core/src/main/java/com/microsoft/windowsazure/credentials/CertificateCloudCredentials.java#L133-L139

Could you throw the exception instead or wrap it in an Azure exception?

Asking that because there is no way as a client to check that provided credentials are correct or not in Java code.

I'm typically trying to do that:

``` java
        try {
            Configuration configuration = ManagementConfiguration.configure(new URI(Azure.ENDPOINT),
                subscriptionId, keystorePath, keystorePassword, keystoreType);
            computeManagementClient = ComputeManagementService.create(configuration);
        } catch (IOException|URISyntaxException e) {
            logger.error("can not start azure client: {}", e.getMessage());
            throw new ElasticsearchException(e);
        }
```

If I provide bad settings, the error is logged but I can't stop my process.

In my test case, I'm providing a wrong `keystorePath` so I should have caught a `FileNotFoundException`.

```
déc. 03, 2015 11:27:55 AM com.microsoft.windowsazure.credentials.CertificateCloudCredentials applyConfig
GRAVE: null
java.io.FileNotFoundException: dummy (No such file or directory)
    at java.io.FileInputStream.open0(Native Method)
    at java.io.FileInputStream.open(FileInputStream.java:195)
    at java.io.FileInputStream.<init>(FileInputStream.java:138)
    at com.microsoft.windowsazure.core.utils.SSLContextFactory.create(SSLContextFactory.java:95)
    at com.microsoft.windowsazure.core.utils.SSLContextFactory.create(SSLContextFactory.java:60)
    at com.microsoft.windowsazure.credentials.CertificateCloudCredentials.applyConfig(CertificateCloudCredentials.java:128)
    at com.microsoft.windowsazure.core.pipeline.apache.Exports$2.create(Exports.java:51)
    at com.microsoft.windowsazure.core.pipeline.apache.Exports$2.create(Exports.java:41)
    at com.microsoft.windowsazure.core.DefaultBuilder.build(DefaultBuilder.java:200)
    at com.microsoft.windowsazure.core.pipeline.apache.Exports$3.create(Exports.java:65)
    at com.microsoft.windowsazure.core.pipeline.apache.Exports$3.create(Exports.java:58)
    at com.microsoft.windowsazure.core.DefaultBuilder.build(DefaultBuilder.java:200)
    at com.microsoft.windowsazure.core.DefaultBuilder$1.create(DefaultBuilder.java:138)
    at com.microsoft.windowsazure.core.DefaultBuilder.build(DefaultBuilder.java:200)
    at com.microsoft.windowsazure.Configuration.create(Configuration.java:113)
    at com.microsoft.windowsazure.management.compute.ComputeManagementService.create(ComputeManagementService.java:47)
    at org.elasticsearch.cloud.azure.management.AzureComputeServiceImpl.doStart(AzureComputeServiceImpl.java:97)
    at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:68)
    at org.elasticsearch.cloud.azure.AzureDiscoveryModule.configure(AzureDiscoveryModule.java:60)
    at org.elasticsearch.common.inject.AbstractModule.configure(AbstractModule.java:59)
    at org.elasticsearch.common.inject.spi.Elements$RecordingBinder.install(Elements.java:209)
    at org.elasticsearch.common.inject.spi.Elements.getElements(Elements.java:79)
    at org.elasticsearch.common.inject.InjectorShell$Builder.build(InjectorShell.java:148)
    at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:99)
    at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:96)
    at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:70)
    at org.elasticsearch.common.inject.ModulesBuilder.createInjector(ModulesBuilder.java:46)
    at org.elasticsearch.node.Node.<init>(Node.java:204)
    at org.elasticsearch.node.MockNode.<init>(MockNode.java:42)
    at org.elasticsearch.discovery.azure.AzureDiscoveryF.main(AzureDiscoveryF.java:47)
```

**Comment by jianghaolu** [comment]
Hi @dadoonet 

I agree it was bad design to swallow the exceptions. But it's hard to fix this without involving a breaking change. (I hope every script running today with this are feeding in correct credentials but I cannnot assume that.)

We will fix this in next major release. But certificate login only works for Service Management so I cannot guarantee when that's going to happen. For now you should be able to work around this by adding a handler to `Logger.getLogger(CertificateCloudCredentials.class.getName())` and check the handler when a request is sent.

**Comment by martinsawicki** [comment]
obsolete - pls use the latest version of the Azure Management Libraries for Java
