### ISSUE TITLE
[BUG] Download Example in README doesn't work

### ISSUE THREAD

**Issue by andreaturli** [Azure/azure-sdk-for-java#5652]
**Describe the bug**
[Download Example](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/storage/azure-storage-blob/README.md#downloading-a-blob-to-output-stream) in official doc doesn't work
using v12.0.0-preview.3

***Exception or Stack Trace***

```
Exception in thread "main" java.lang.UnsupportedOperationException
	at java.nio.ByteBuffer.array(ByteBuffer.java:994)
	at com.azure.storage.blob.BlobClient.lambda$1(BlobClient.java:380)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:177)
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:67)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:123)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114)
	at reactor.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:211)
	at reactor.netty.channel.FluxReceive.onInboundNext(FluxReceive.java:327)
16:26:07.556 [reactor-http-nio-4] DEBUG reactor.netty.resources.PooledConnectionProvider - [id: 0x0c7afd32, L:/192.168.64.100:51481 ! R:snapshotestimatortest.blob.core.windows.net/52.239.246.4:443] onStateChange(PooledConnection{channel=[id: 0x0c7afd32, L:/192.168.64.100:51481 ! R:snapshotestimatortest.blob.core.windows.net/52.239.246.4:443]}, [disconnecting])
	at reactor.netty.channel.ChannelOperations.onInboundNext(ChannelOperations.java:310)
	at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:504)
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:141)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1429)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1199)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1243)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:648)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:583)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: java.lang.Exception: #block terminated with an error
```
**To Reproduce**
Steps to reproduce the behavior: run the example

***Code Snippet***
Add the code snippet that causes the issue.
[Download Example](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/storage/azure-storage-blob/README.md#downloading-a-blob-to-output-stream)

**Expected behavior**

Exception in thread "main" java.lang.UnsupportedOperationException

**Screenshots**

**Setup (please complete the following information):**
 - IDE : [e.g. IntelliJ]
 - Version of the Library used

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by joshfree** [comment]
@srnagar PTAL

**Comment by joshfree** [comment]
Thank you for reporting this issue @andreaturli

**Comment by srnagar** [comment]
Thanks for reporting the issue @andreaturli 

I was able to reproduce this issue with preview 3 version. This issue is fixed in preview 4 which will be released soon. The README example will work as expected. Here's the complete code snippet that works with preview 4.

```java
   try {
      BlobServiceClient blobServiceClient = new BlobServiceClientBuilder()
          .endpoint(endpoint)
          .credential(new SharedKeyCredential(accountName, accountKey))
          .httpClient(HttpClient.createDefault())
          .buildClient();

      BlobContainerClient containerClient = blobServiceClient.getBlobContainerClient(containerName);
      BlobClient blobClient = containerClient.getBlobClient(blobId);

      try (ByteArrayOutputStream outputStream = new ByteArrayOutputStream()) {
        blobClient.download(outputStream);
        System.out.println("Downloaded bytes " + outputStream.size());
      }
      System.out.println("Download complete");
    } catch (Exception exc) {
      exc.printStackTrace();
    }
```

**Comment by srnagar** [comment]
Pending preview 4 release.

**Comment by JonathanGiles** [comment]
@srnagar @alzimmermsft I'm a big fan of getting documentation as close to the user as possible. With this code sample above, I would love to see it placed in the relevant places in JavaDoc (either class- or method-level). If this kind of sample doesn't already exist, could you make sure that after our next preview release we have a follow-up issue to move this (and other useful code samples) into our JavaDoc? Thanks!

**Comment by andreaturli** [comment]
Thanks! I'd have a couple of questions: 
- when is preview4 expected?
- Did you happen to test this even against Azurite?

**Comment by srnagar** [comment]
- We're hoping have preview 4 released this week. I will update this ticket as soon as the package is available.
- I haven't tested it against Azurite. Thank you for the suggestion. I will follow up on this and let you know.

**Comment by amishra-dev** [comment]
@rickle-msft fyi

**Comment by joshfree** [comment]
Updating this issue with a link to Preview4 (October 2019 Unified Azure SDK Preview)

https://azure.microsoft.com/en-us/blog/october-2019-unified-azure-sdk-preview/

https://search.maven.org/artifact/com.azure/azure-storage-blob/12.0.0-preview.4/jar

**Comment by joshfree** [comment]
@andreaturli thank you again for reporting this issue in the Preview 3 / September Preview.

I'm closing the issue out now that the October Preview link is available above.  Please feel free to reactivate (or file new issues) on the October Preview release.

Thanks again!

**Comment by srnagar** [comment]
We are also tracking Azurite request here - https://github.com/Azure/azure-sdk-for-java/issues/5884
