### ISSUE TITLE
azure-core exception types should present a more user-friendly console output

### ISSUE THREAD

**Issue by JonathanGiles** [Azure/azure-sdk-for-java#5662]
When an exception is encountered in azure-core and returned to the user, the result is a flat error message containing useful information such as response code, and the json payload. We should format this in a more user parsable way such that they can more easily act on the error being presented.

**Comment by sima-zhu** [comment]
Closed it as it finished first round of cosmetic.

**Comment by JonathanGiles** [comment]
What you did and what this issue requested are different things. This issue was to ensure that the formatting of an exception, when printed to the console, is as readable as possible. Try catching some exceptions in test code and observe that they do not format nicely on the console. I've reopened this issue so that it may be correctly reviewed and resolved.

**Comment by sima-zhu** [comment]
A good example to reference: github.com/Azure/azure-sdk-for-java/issues/6439

**Comment by sima-zhu** [comment]
One of the exception from RetryPolicy:

```
java.lang.RuntimeException: Max retries 5 times exceeded. Error Details: some error here

	at com.azure.core.http.policy.RetryPolicy.lambda$attemptAsync$1(RetryPolicy.java:89)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:88)
	at reactor.core.publisher.Operators.error(Operators.java:182)
	at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:134)
	at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:48)
	at reactor.core.publisher.MonoDelaySubscription.accept(MonoDelaySubscription.java:52)
	at reactor.core.publisher.MonoDelaySubscription.accept(MonoDelaySubscription.java:33)
	at reactor.core.publisher.FluxDelaySubscription$DelaySubscriptionOtherSubscriber.onNext(FluxDelaySubscription.java:123)
	at reactor.core.publisher.MonoDelay$MonoDelayRunnable.run(MonoDelay.java:117)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:93)
		at reactor.core.publisher.Mono.block(Mono.java:1663)
		at com.azure.core.http.policy.RetryPolicyTests.retryMax(RetryPolicyTests.java:66)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:515)
		at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:115)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:171)
		at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:167)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:114)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:59)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:105)
		at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:95)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:71)
		at java.util.ArrayList.forEach(ArrayList.java:1257)
		at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:110)
		at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:95)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:71)
		at java.util.ArrayList.forEach(ArrayList.java:1257)
		at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:110)
		at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:95)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:71)
		at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
		at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
		at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
		at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)
		at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)
		at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)
		at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)
		at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
		at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:69)
		at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
		at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
		at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: com.azure.core.exception.HttpRequestException: some error here
	at com.azure.core.http.policy.RetryPolicyTests$2.send(RetryPolicyTests.java:59)
	at com.azure.core.http.HttpPipelineNextPolicy.process(HttpPipelineNextPolicy.java:44)
	at com.azure.core.http.policy.RetryPolicy.attemptAsync(RetryPolicy.java:69)
	at com.azure.core.http.policy.RetryPolicy.lambda$attemptAsync$1(RetryPolicy.java:85)
	... 17 more
```

**Comment by sima-zhu** [comment]
- [ ] annotaion

- [ ] credential

- [ ] cryptography

- [ ] exception

- [ ] http

- [ ] http.policy

- [ ] rest

- [ ] implementation

- [ ] util

- [ ] util.logging

- [ ] util.polling

- [ ] util.serializer

- [ ] util.tracing

**Comment by sima-zhu** [comment]
Our SDK public Exceptions has API of returning message, response and object value. Usually, if clients try to get pretty message, they can access those APIs and pretty print the info they needed by client side.

**Comment by sima-zhu** [comment]
In RestProxy, when we construct exception. We plainly construct response body.

```xml
Response body:
{"error":{"code":"MethodNotAllowed","message":"HTTP POST not allowed"}}
<-- END HTTP
```

**Comment by sima-zhu** [comment]
It is better to pretty print the response body based on json or xml format.

**Comment by sima-zhu** [comment]
The one with pretty print.
```
{
  "error" : {
    "code" : "MethodNotAllowed",
    "message" : "HTTP POST not allowed"
  }
}
```

**Comment by sima-zhu** [comment]
Storage xml exception looks like:

```
com.azure.storage.blob.models.BlobStorageException: Status code 416, "﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidRange</Code><Message>The range specified is invalid for the current size of the resource.
RequestId:f1d87025-b01e-000d-0d9d-afdf7a000000
Time:2019-12-10T21:03:24.6948712Z</Message></Error>"
```

**Comment by sima-zhu** [comment]
Is enable storage pretty print xml. The exception looks like:
```
<Error>
  <Code>InvalidRange</Code>
  <Message>The range specified is invalid for the current size of the resource.
RequestId:22041e87-d01e-0034-1fa0-af9fde000000
Time:2019-12-10T21:25:16.6017463Z</Message>
</Error>
```

**Comment by sima-zhu** [comment]
Unassigned myself for the Java specific work. Please reassigned someone else. Thanks! :)

**Comment by alzimmermsft** [comment]
With enhancements to logging to allow for key-values to be used instead of just a message and Sync Stack which cleans up stack traces in thrown exceptions I'm going to close this is issue as resolved.
