### ISSUE TITLE
[BUG] NoRegisteredProviderFound for regions from subscription location's region in virtualMachines().sizes()

### ISSUE THREAD

**Issue by tobymurray** [Azure/azure-sdk-for-java#5673]
**Describe the bug**
Using values from `com.microsoft.azure.management.resources.fluentcore.arm.Region`, list the available virtual machine sizes (`azure.virtualMachines().sizes().listByRegion(regionName)`)

***Exception or Stack Trace***
```
com.microsoft.azure.CloudException: Status code 400, {"error":{"code":"NoRegisteredProviderFound","message":"No registered resource provider found for location 'francesouth' and API version '2019-03-01' for type 'locations/vmSizes'. The supported api-versions are '2015-05-01-preview, 2015-06-15, 2016-03-30, 2016-04-30-preview, 2016-08-30, 2017-03-30, 2017-12-01, 2018-04-01, 2018-06-01, 2018-10-01, 2019-03-01, 2019-07-01'. The supported locations are 'eastus, eastus2, westus, centralus, northcentralus, southcentralus, northeurope, westeurope, eastasia, southeastasia, japaneast, japanwest, australiaeast, australiasoutheast, australiacentral, brazilsouth, southindia, centralindia, westindia, canadacentral, canadaeast, westus2, westcentralus, uksouth, ukwest, koreacentral, koreasouth, francecentral, southafricanorth, uaenorth'."}}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_181]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_181]
	at com.microsoft.rest.ServiceResponseBuilder.build(ServiceResponseBuilder.java:122) ~[client-runtime-1.6.12.jar:?]
	at com.microsoft.azure.AzureResponseBuilder.build(AzureResponseBuilder.java:56) ~[azure-client-runtime-1.6.12.jar:?]
	at com.microsoft.azure.management.compute.implementation.VirtualMachineSizesInner.listDelegate(VirtualMachineSizesInner.java:140) ~[azure-mgmt-compute-1.26.0.jar:1.26.0]
	at com.microsoft.azure.management.compute.implementation.VirtualMachineSizesInner.access$000(VirtualMachineSizesInner.java:33) ~[azure-mgmt-compute-1.26.0.jar:1.26.0]
	at com.microsoft.azure.management.compute.implementation.VirtualMachineSizesInner$2.call(VirtualMachineSizesInner.java:122) ~[azure-mgmt-compute-1.26.0.jar:1.26.0]
	at com.microsoft.azure.management.compute.implementation.VirtualMachineSizesInner$2.call(VirtualMachineSizesInner.java:118) ~[azure-mgmt-compute-1.26.0.jar:1.26.0]
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69) ~[rxjava-1.3.8.jar:1.3.8]
	at retrofit2.adapter.rxjava.CallArbiter.deliverResponse(CallArbiter.java:120) ~[adapter-rxjava-2.4.0.jar:?]
	at retrofit2.adapter.rxjava.CallArbiter.emitResponse(CallArbiter.java:102) ~[adapter-rxjava-2.4.0.jar:?]
	at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:46) ~[adapter-rxjava-2.4.0.jar:?]
	at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:24) ~[adapter-rxjava-2.4.0.jar:?]
	at rx.Observable.unsafeSubscribe(Observable.java:10327) ~[rxjava-1.3.8.jar:1.3.8]
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48) ~[rxjava-1.3.8.jar:1.3.8]
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33) ~[rxjava-1.3.8.jar:1.3.8]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) ~[rxjava-1.3.8.jar:1.3.8]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) ~[rxjava-1.3.8.jar:1.3.8]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) ~[rxjava-1.3.8.jar:1.3.8]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) ~[rxjava-1.3.8.jar:1.3.8]
	at rx.Observable.subscribe(Observable.java:10423) ~[rxjava-1.3.8.jar:1.3.8]
	at rx.Observable.subscribe(Observable.java:10390) ~[rxjava-1.3.8.jar:1.3.8]
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:443) ~[rxjava-1.3.8.jar:1.3.8]
	at rx.observables.BlockingObservable.single(BlockingObservable.java:340) ~[rxjava-1.3.8.jar:1.3.8]
	at com.microsoft.azure.management.compute.implementation.VirtualMachineSizesInner.list(VirtualMachineSizesInner.java:71) ~[azure-mgmt-compute-1.26.0.jar:1.26.0]
	at com.microsoft.azure.management.compute.implementation.VirtualMachineSizesImpl.listByRegion(VirtualMachineSizesImpl.java:44) ~[azure-mgmt-compute-1.26.0.jar:1.26.0]
... <snip code that invokes the client> ...
```

**To Reproduce**
For each value in `Region`, list the VM sizes

***Code Snippet***
```
// Iterating the enum
for (Region region : Arrays.asList(Region.values())) {
    azure.virtualMachines().sizes().listByRegion(region.name());
}
// This fails for e.g. France South, Germany Central, Germany Northeast etc. (as well as all the "gov" ones that I don't care about presently)

// Iterating all the locations from the current subscription also fails
for (Location location : azure.getCurrentSubscription().listLocations()) {
    azure.getVirtualMachineSizes(location.region().name());
}
// This fails for a bunch similar values (France South, Australia Central 2, germanynorth...)
```

**Expected behavior**
The regions supported by the SDK would be consistent across the enum and the APIs that take a region as a parameter. E.g. there should be a registered provider for each region specified in the API, or at least for each region attached to a location from the subscription. 

**Setup (please complete the following information):**
 - OS: Windows 10, Ubuntu
 - IDE : Eclipse
 - Version of the Library used: 1.26.0 (from [here](https://mvnrepository.com/artifact/com.microsoft.azure/azure/1.26.0))

**Additional context**
I've seen the help article here: https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-manager-register-provider-errors - this doesn't seem to align with my expectation for the behavior of the SDK. Given that both of these strategies fail, I'm anticipating that I'm misunderstanding how the SDK is intended to be used (or just misunderstanding the model itself). I'm trying to compile a list of all VM sizes across all regions for a subscription but the SDK and Azure itself do not appear to be aligned on what regions exist.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by tobymurray** [comment]
Looking in the UI for the subscription I'm working with, the regions that are causing trouble don't appear (e.g. when selecting a region to deploy a public image). This is the complete list of regions that are returned from `azure.getCurrentSubscription().listLocations()` that I'm concerned about:
- francesouth (France South)
- australiacentral2 (Australia Central 2)
- uaecentral (UAE Central)
- southafricawest (South Africa West)
- switzerlandnorth (Switzerland North)
- switzerlandwest (Switzerland West)
- germanynorth (Germany North)
- germanywestcentral (Germany West Central)

These all appear on https://azure.microsoft.com/en-ca/global-infrastructure/locations/ for example. It's feeling like I'm just not quite getting something - there's some other source of regions or an additional check I need to be doing to determine the viable regions for a given subscription.

**Comment by tobymurray** [comment]
So what I was missing seems to be the somewhat fundamental relationship between resource providers, resource types, locations, and regions. The best I can tell, the code snippet below will give me the list I seek:

```
Set<String> allLocationDisplayNamesFromRegisteredProviders = azure.providers().list().stream()
                .filter(provider -> provider.registrationState().equals("Registered"))
                .flatMap(provider -> provider.resourceTypes().stream())
                .filter(resourceType -> resourceType.resourceType().equals("locations/vmSizes"))
                .flatMap(resourceType -> resourceType.locations().stream())
                .collect(Collectors.toSet());

Set<Region> regionsForSubscriptionThatHaveRegisteredProvider = azure.getCurrentSubscription().listLocations().stream()
                .filter(location -> allLocationDisplayNamesFromRegisteredProviders.contains(location.displayName()))
                .map(Location::region)
                .collect(Collectors.toSet());
```

Notably, the resource type locations are the display name, which is a bit of a pain. So as it stands, I don't think this was a bug I just was not really grasping what the providers do, and the resource types they provide.
