### ISSUE TITLE
2 unexpected NPEs

### ISSUE THREAD

**Issue by orkeret** [Azure/azure-sdk-for-java#5740]
Hi,
we have an app that uses the Azure java SDK and a customer that is using our app encountered 2 unexpected NPEs that were originated internally and unexpectedly from within the Azure java SDK.
Please see the relevant bits of the stack-traces here:

**1)** 
after invoking SqlDatabase::getTransparentDataEncryption() :
**java.lang.NullPointerException**
    at deployment.AzureCollector.ear//com.microsoft.azure.management.sql.implementation.TransparentDataEncryptionImpl.<init>(TransparentDataEncryptionImpl.java:39)
    at deployment.AzureCollector.ear//com.microsoft.azure.management.sql.implementation.SqlDatabaseImpl.getTransparentDataEncryption(SqlDatabaseImpl.java:505)
    at deployment.AzureCollector.ear//com.realstatus.azure.resources.database.SQLDatabaseCollector.createAttributes(SQLDatabaseCollector.java:84)

**2)**
after invoking SqlElasticPool::dtu() :
**java.lang.NullPointerException**
    at deployment.AzureCollector.ear//com.microsoft.azure.management.sql.implementation.SqlElasticPoolImpl.dtu(SqlElasticPoolImpl.java:157)
    at deployment.AzureCollector.ear//com.realstatus.azure.resources.database.SQLServerCollector.createElasticPoolTable(SQLServerCollector.java:204)
    at deployment.AzureCollector.ear//com.realstatus.azure.resources.database.SQLServerCollector.createTables(SQLServerCollector.java:142)

Could you please advise about those NPEs?

Thanks,
Or

**Comment by maggiepint** [comment]
@joshfree - can you help me route this one?

**Comment by xccc-msft** [comment]
Hi @orkeret After checking your description, it looks you opened this issue in wrong repo. Please raise it again at [azure-libraries-for-java](https://github.com/Azure/azure-libraries-for-java/issues) and provide more info about the version you are using/the steps to reproduce/the code snippet there. We are looking into this issue parallelly.
