### ISSUE TITLE
[Storage] Support all valid connection strings

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk-for-java#5845]
All valid connection strings should be supported.  There is some documentation at https://docs.microsoft.com/en-us/azure/storage/common/storage-configure-connection-string, though it doesn't specify exactly what is and isn't valid.

Here is a specific connection string which is valid in both .NET and Java `com.microsoft.azure.azure-storage@8.4.0`, but invalid in Java `com.azure.azure-storage-blob@12.0.0-preview.4`:

```
# Blob endpoint only
DefaultEndpointsProtocol=https;
BlobEndpoint=http://www.mydomain.com;
AccountName=storagesample;
AccountKey=<account-key>
```

In  `com.azure.azure-storage-blob@12.0.0-preview.4`, the following exception is thrown:

```
Exception in thread "main" java.lang.NullPointerException: 'endpoint' cannot be null.
at java.base/java.util.Objects.requireNonNull(Objects.java:246)
at com.azure.storage.common.BaseClientBuilder.buildPipeline(BaseClientBuilder.java:72)
at com.azure.storage.blob.BlobServiceClientBuilder.buildAsyncClient(BlobServiceClientBuilder.java:57)
at com.azure.storage.blob.BlobServiceClientBuilder.buildClient(BlobServiceClientBuilder.java:48)
```

**Comment by alzimmermsft** [comment]
We should target a fix for this before GA but it is mainly an implementation detail
