### ISSUE TITLE
[qpid-proton-j-extensions] OutOfMemoryError when frame larger than 4kB

### ISSUE THREAD

**Issue by mikestone77** [Azure/azure-sdk-for-java#5850]
**Describtion**
When trying to send an message larger than 4kB with TransportType AmqpWebSockets enabled the qpid-proton-j-extensions will throw an OutOfMemoryError Exception.

***Stack Trace***
```
Exception in thread "ReactorThreadc3cb21d1-35fd-4f86-935c-406298eb64e9" java.lang.OutOfMemoryError: insufficient output buffer size
	at com.microsoft.azure.proton.transport.ws.impl.WebSocketHandlerImpl.wrapBuffer(WebSocketHandlerImpl.java:151)
	at com.microsoft.azure.proton.transport.ws.impl.WebSocketImpl.wrapBuffer(WebSocketImpl.java:117)
	at com.microsoft.azure.proton.transport.ws.impl.WebSocketImpl$WebSocketTransportWrapper.head(WebSocketImpl.java:546)
	at org.apache.qpid.proton.engine.impl.HandshakeSniffingTransportWrapper.head(HandshakeSniffingTransportWrapper.java:151)
	at org.apache.qpid.proton.engine.impl.ssl.SimpleSslTransportWrapper.wrapOutput(SimpleSslTransportWrapper.java:222)
	at org.apache.qpid.proton.engine.impl.ssl.SimpleSslTransportWrapper.pending(SimpleSslTransportWrapper.java:400)
	at org.apache.qpid.proton.engine.impl.ssl.SslImpl$UnsecureClientAwareTransportWrapper.pending(SslImpl.java:173)
	at com.microsoft.azure.proton.transport.proxy.impl.ProxyImpl$ProxyTransportWrapper.pending(ProxyImpl.java:281)
	at org.apache.qpid.proton.engine.impl.TransportImpl.pending(TransportImpl.java:1577)
	at org.apache.qpid.proton.reactor.impl.IOHandler.pending(IOHandler.java:193)
	at org.apache.qpid.proton.reactor.impl.IOHandler.update(IOHandler.java:214)
	at org.apache.qpid.proton.reactor.impl.IOHandler.handleTransport(IOHandler.java:347)
	at org.apache.qpid.proton.reactor.impl.IOHandler.onUnhandled(IOHandler.java:384)
	at org.apache.qpid.proton.engine.BaseHandler.onTransport(BaseHandler.java:80)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:188)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:292)
	at com.microsoft.azure.servicebus.primitives.MessagingFactory$RunReactor.run(MessagingFactory.java:491)
	at java.lang.Thread.run(Thread.java:748)
```

***How to reproduce***
Send an message larger than 4kB using the qpid-proton-j-extensions by adding TransportType=AmqpWebSockets to the connection string.
Example connection string:
```
Endpoint=sb://weu-[alias]-sbus.servicebus.windows.net/;SharedAccessKeyName=[KeyName];SharedAccessKey=[AccessKey];TransportType=AmqpWebSockets
```

***Code Snippet according to the https://github.com/Azure/qpid-proton-j-extensions Repo***
Frame size limitation is hardcoded.
com.microsoft.azure.proton.transport.ws.impl.WebSocketImpl
```java
private final int maxFrameSize = (4 * 1024) + (16 * WebSocketHeader.MED_HEADER_LENGTH_MASKED);
```

com.microsoft.azure.proton.transport.ws.impl.WebSocketHandlerImpl
```java
// Copy frame to destination buffer
dstBuffer.clear();
if (dstBuffer.capacity() >= webSocketFrame.size()) {
    dstBuffer.put(webSocketFrame.toByteArray());
} else {
    throw new OutOfMemoryError("insufficient output buffer size");
}
```

**Expected behavior**
Possible to send messages with up to 1MB. According to the max Azure Service Bus limitation.

**Comment by jfggdl** [comment]
@mikestone77 , Thank you for creating this issue. We are looking at a potential fix that might be in the works already.
