### ISSUE TITLE
BlobClient.openInputStream() throws StorageException without ErrorCode if spaces are in blob name

### ISSUE THREAD

**Issue by daolis** [Azure/azure-sdk-for-java#5920]
If you try to open a input stream on BlobClient a exception is thrown without ErrorCode

Clone test program from: https://github.com/daolis/azureCopBlobInputStreamError

1. Create Azure BlobStore
2. Create Container `testcontainer`
3. Create Blobs `mytestblob.txt` and `my test blob.txt` with content
4. Set Environment Variables: `TEST_ACCOUNT_NAME` and `TEST_ACCOUNT_KEY`

**Expected behavior**
Input stream should be opened and can be used to stream to a OutputStream

**Screenshots**
From example code:
![image](https://user-images.githubusercontent.com/2550938/67082262-153b2a00-f199-11e9-9b95-3a87adcab2ad.png)

**Setup:**
 - OS: Linux
 - IDE : IntelliJ
 - com.azure:azure-storage-blob:12.0.0-preview.4

**Comment by rickle-msft** [comment]
@daolis Thank you for reporting this issue. It looks to be an issue with url encoding the blob name. We will look into the best way to solve this problem as we don't want to always encode a path given to us for fear of double encoding, but we also shouldn't leave customers with this vague error.

@vcolin7 Can you include this in your blobName encoding work? Of note here is that if your blob has a space in the name, and you go to get the url from the portal, the url will have an unencoded space in it, which is what seems to be breaking this api. (Technically what's breaking is the get properties call inside the BlobInputStream constructor. It fails with a 400 because of the unencoded space). It's unfortunate that this is what the portal gives because we have to be able to handle it since customers are inevitably going to grab urls from the portal and give it to us. Perhaps we need to scan the blobName for unencoded characters?

**Comment by vcolin7** [comment]
No problem @rickle-msft, this is included in the blobName changes I've been working on and should be fixed once I merge them.

**Comment by daolis** [comment]
@vcolin7 Thank you! :-)

Additional information from another test:
I tried to create the BlobClient with `testcontainer.getBlobClient("my%20test%20blob.txt");`. Then openInputStream was successful, but `blockBlobClient.upload(stream, length);` failed afterwards.

**Comment by rickle-msft** [comment]
@daolis Thank you for the update. Can you share what the error message was, please?

**Comment by daolis** [comment]
Hi @vcolin7 
Sorry, i also used the blob name with spaces for the target blob.
Then i get the following exception..

When using the name with %20 for the target BlockBlob, then the upload is successful.

FYI I updated the testprogram to reproduce the error. see https://github.com/daolis/azureCopBlobInputStreamError

```
com.azure.storage.blob.models.StorageException: Status code 400, "<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Bad Request</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Bad Request</h2>
<hr><p>HTTP Error 400. The request is badly formed.</p>
</BODY></HTML>
"
	at com.azure.storage.blob.implementation.PostProcessor.lambda$null$0(PostProcessor.java:30)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:118)
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:67)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1592)
	at reactor.core.publisher.MonoProcessor.subscribe(MonoProcessor.java:383)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4087)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:97)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:165)
	at reactor.core.publisher.FluxContextStart$ContextStartSubscriber.onError(FluxContextStart.java:117)
	at reactor.core.publisher.FluxDoOnEach$DoOnEachSubscriber.onError(FluxDoOnEach.java:181)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondError(MonoFlatMap.java:185)
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onError(MonoFlatMap.java:251)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onError(Operators.java:1825)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondError(MonoFlatMap.java:185)
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onError(MonoFlatMap.java:251)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onError(Operators.java:1825)
	at reactor.core.publisher.Operators.error(Operators.java:182)
	at reactor.core.publisher.MonoError.subscribe(MonoError.java:52)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4087)
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FluxSwitchIfEmpty.java:75)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onComplete(MonoFlatMap.java:174)
	at reactor.core.publisher.MonoProcessor$NextInner.onComplete(MonoProcessor.java:518)
	at reactor.core.publisher.MonoProcessor.onNext(MonoProcessor.java:308)
	at reactor.core.publisher.MonoProcessor.onComplete(MonoProcessor.java:265)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:141)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1592)
	at reactor.core.publisher.MonoProcessor.subscribe(MonoProcessor.java:383)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:55)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4087)
	at reactor.core.publisher.MonoProcessor.add(MonoProcessor.java:457)
	at reactor.core.publisher.MonoProcessor.subscribe(MonoProcessor.java:370)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:55)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:150)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1592)
	at reactor.core.publisher.MonoProcessor.onNext(MonoProcessor.java:317)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:123)
	at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:112)
	at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:213)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:123)
	at reactor.core.publisher.FluxFilterFuseable$FilterFuseableConditionalSubscriber.onNext(FluxFilterFuseable.java:330)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1592)
	at reactor.core.publisher.MonoReduceSeed$ReduceSeedSubscriber.onComplete(MonoReduceSeed.java:156)
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:136)
	at reactor.netty.channel.FluxReceive.terminateReceiver(FluxReceive.java:397)
	at reactor.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:197)
	at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:345)
	at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:363)
	at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:412)
	at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:556)
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:91)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:328)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:302)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1475)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1224)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1271)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:505)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:444)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:283)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1421)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:794)
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollRdHupReady(AbstractEpollChannel.java:437)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:431)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:326)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:93)
		at reactor.core.publisher.Mono.block(Mono.java:1663)
		at com.azure.storage.common.Utility.blockWithOptionalTimeout(Utility.java:242)
		at com.azure.storage.blob.specialized.BlockBlobClient.uploadWithResponse(BlockBlobClient.java:159)
		at com.azure.storage.blob.specialized.BlockBlobClient.upload(BlockBlobClient.java:120)
		at CopyBlobFailureTest.main(CopyBlobFailureTest.java:52)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)
Caused by: com.azure.storage.blob.models.StorageErrorException: Status code 400, "<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Bad Request</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Bad Request</h2>
<hr><p>HTTP Error 400. The request is badly formed.</p>
</BODY></HTML>
"
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.azure.core.implementation.RestProxy.instantiateUnexpectedException(RestProxy.java:373)
	at com.azure.core.implementation.RestProxy.lambda$null$4(RestProxy.java:427)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44)
	... 66 more
```

**Comment by vcolin7** [comment]
Hi @daolis, good news: I just tested your program using a version of the SDK with my fix and it worked just fine! I just had to make a slight modification though: by the time the `targetBlobClient` tries to consume the `InputStream` opened at [line 50](https://github.com/daolis/azureCopBlobInputStreamError/blob/ffd35c33f99b40885f6d02dae13899298d60c3fe/src/main/java/CopyBlobFailureTest.java#L50) it has already been consumed by `targetBlobClientOk`, and throws the following: `com.azure.core.exception.UnexpectedLengthException: Request body emitted 0 bytes, less than the expected 12 bytes.` So I had to open a new `InputStream` at [line 54](https://github.com/daolis/azureCopBlobInputStreamError/blob/ffd35c33f99b40885f6d02dae13899298d60c3fe/src/main/java/CopyBlobFailureTest.java#L54).

**Comment by daolis** [comment]
Hi @vcolin7 That's good news.Thank you.
Ahh, already used inputstream... of course - thanks
Do you know when it's planned to publish the next release?

**Comment by vcolin7** [comment]
Early november :)

**Comment by joshfree** [comment]
@daolis thanks again for reporting this issue with the October update (preview 4).  I'm closing this issue as the reported problem has now been fixed in the upcoming November update.

@daolis please feel free to reactivate or open a new issue if you're still seeing a problem with the November SDK update.
