### ISSUE TITLE
Error in deserialization of JsonNode throwing Null pointer - Name is null

### ISSUE THREAD

**Issue by s-rusev** [Azure/azure-sdk-for-java#595]
When using WebSiteManagementClient (com.microsoft.azure.management.websites.WebSiteManagementClient) like this:

`WebSiteManagementClient client = new WebSiteManagementClient();
client.getWebSitesOperations().get(resourceGroupName, webSiteName, slotName, parameters)`

It throws null pointer exception which is due to a bug in the Enum class for some properites in WebSiteOperationsImpl (com.microsoft.azure.management.websites) - state, usageState, remoteDebuggingVersion, managedPipelineMode, type, sku, runtimeAvailabilityState, hostType, sslState, availabilityState. The getTextValue() is not working here - for example Enum.valueOf(WebSpaceAvailabilityState.class, "0")

Here is the code for the deserialization:

    JsonNode usageStateValue = propertiesValue.get("usageState");
    if (usageStateValue != null && usageStateValue instanceof NullNode == false)  {
              WebSiteUsageState usageStateInstance;
              usageStateInstance = Enum.valueOf(WebSiteUsageState.class, usageStateValue.getTextValue());
               propertiesInstance.setUsageState(usageStateInstance);
    }

Probably we should invoke getIntValue?

Thanks!

**Comment by pednekarprajakta** [comment]
I am also getting same exception for websites get and list APIs of ARM JAR.
For example,
webSiteManagementClient.getWebSitesOperations().list(resourceGroupName, null, null)
webSiteManagementClient.getWebHostingPlansOperations().list(resourceGroupName).getWebHostingPlans()

Exception,
java.lang.NullPointerException: Name is null
at java.lang.Enum.valueOf(Enum.java:236)
at com.microsoft.azure.management.websites.WebHostingPlanOperationsImpl.list(WebHostingPlanOperationsImpl.java:1174)
at Test$1.onSuccess(Test.java:122)
at Test$1.onSuccess(Test.java:1)
at com.google.common.util.concurrent.Futures$6.run(Futures.java:1319)
at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:457)
at com.google.common.util.concurrent.ExecutionList.executeListener(ExecutionList.java:156)
at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:145)
at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:185)
at com.google.common.util.concurrent.SettableFuture.set(SettableFuture.java:53)
at com.microsoftopentechnologies.auth.AuthenticationContext$1.onSuccess(AuthenticationContext.java:175)
at com.microsoftopentechnologies.auth.AuthenticationContext$1.onSuccess(AuthenticationContext.java:104)
at com.google.common.util.concurrent.Futures$6.run(Futures.java:1319)
at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:457)
at com.google.common.util.concurrent.ExecutionList.executeListener(ExecutionList.java:156)
at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:145)
at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:185)
at com.google.common.util.concurrent.SettableFuture.set(SettableFuture.java:53)
at com.microsoftopentechnologies.auth.AuthenticationContext$2.onAuthCodeReceived(AuthenticationContext.java:336)
at com.microsoftopentechnologies.auth.webserver.AADWebServer$AuthRequestHandler.handle(AADWebServer.java:99)
at com.microsoftopentechnologies.auth.webserver.WebServer$1.handle(WebServer.java:82)
at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)

**Comment by jianghaolu** [comment]
This is fixed in 0.9.3.
