### ISSUE TITLE
[BUG] NoClassDefFoundError When initiating ClientSecretCredential

### ISSUE THREAD

**Issue by jclarkk** [Azure/azure-sdk-for-java#6313]
**Describe the bug**
NoClassDefFoundError when using attempting to use ClientSecretCredential from azure-identity

***Exception or Stack Trace***
Exception in thread "main" java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/TSFBuilder
	at com.fasterxml.jackson.dataformat.xml.XmlMapper.<init>(XmlMapper.java:122)
	at com.azure.core.implementation.serializer.jackson.JacksonAdapter.<init>(JacksonAdapter.java:75)
	at com.azure.core.implementation.serializer.jackson.JacksonAdapter.createDefaultSerializerAdapter(JacksonAdapter.java:108)
	at com.azure.identity.implementation.IdentityClient.<clinit>(IdentityClient.java:60)
	at com.azure.identity.implementation.IdentityClientBuilder.build(IdentityClientBuilder.java:50)
	at com.azure.identity.ClientSecretCredential.<init>(ClientSecretCredential.java:48)
	at com.azure.identity.ClientSecretCredentialBuilder.build(ClientSecretCredentialBuilder.java:39)

**To Reproduce**
Use:
        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-identity</artifactId>
            <version>1.0.0</version>
        </dependency>
in pom.xml and then init the credentials:
new ClientSecretCredentialBuilder()
                        .clientId(%CLIENT ID%)
                        .tenantId(azureConfig.getString(%TENANT ID%))
                        .clientSecret(azureConfig.getString(%CLIENT SECRET%))
                        .build();

***Code Snippet***
new ClientSecretCredentialBuilder()
                        .clientId(%CLIENT ID%)
                        .tenantId(azureConfig.getString(%TENANT ID%))
                        .clientSecret(azureConfig.getString(%CLIENT SECRET%))
                        .build();

**Expected behavior**
Authenticate with Azure using the client secret auth mode.

**Screenshots**
None

**Setup (please complete the following information):**
 - OS: Ubuntu
 - IDE : IntelliJ
 - Version of the Library used: 1.0.0

**Additional context**
None

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ v] Bug Description Added
- [ v] Repro Steps Added
- [ v] Setup information Added

**Comment by maggiepint** [comment]
@joshfree - can you route this?

**Comment by jianghaolu** [comment]
@jclarkk 
It seems like there's a mismatch of Jackson versions. We are using 2.10.0 version of Jackson and you may have another version in your classpath. 

Would you be able to run `mvn dependency:tree` from your project directory and paste the output here? That will help us identify the conflicting dependencies and take appropriate actions. Thanks!

**Comment by jclarkk** [comment]
Solved.

Forced jackson to be version 2.10.0.

Thanks!
