### ISSUE TITLE
[BUG] Address DocumentCrudTest::createLargeDocument test failure

### ISSUE THREAD

**Issue by David-Noble-at-work** [Azure/azure-sdk-for-java#6335]
This test fails due to timeouts in Direct HTTPS and Direct TCP mode at Eventual, Session, and Strong consistency levels. Here are sample stacks:
```
FAILED: DocumentCrudTest::createLargeDocument[Direct Https with Session consistency]("ede870bf-7e5b-4e6e-ac26-3e73cfcdf572")
org.testng.internal.thread.ThreadTimeoutException: Method com.azure.cosmos.rx.DocumentCrudTest.createLargeDocument() didn't finish within the time-out 40000
    at com.azure.cosmos.rx.TestSuiteBase.validateSuccess(TestSuiteBase.java:723)
    at com.azure.cosmos.rx.TestSuiteBase.validateSuccess(TestSuiteBase.java:712)
    at com.azure.cosmos.rx.DocumentCrudTest.createLargeDocument(DocumentCrudTest.java:81)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
    at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
    at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
```
```
FAILED: DocumentCrudTest::createLargeDocument[Direct Tcp with Eventual consistency]("+ -_,:.|~107768e4-400b-4999-8a21-12c0da8cc5f9 +-_,:.|~")
org.testng.internal.thread.ThreadTimeoutException: Method com.azure.cosmos.rx.DocumentCrudTest.createLargeDocument() didn't finish within the time-out 40000
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
    at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
    at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
```

**Comment by kushagraThapar** [comment]
This has been fixed.
