### ISSUE TITLE
[BUG] Address DocumentCrudTest::readDocumentWithVeryLargePartitionKey test failure

### ISSUE THREAD

**Issue by David-Noble-at-work** [Azure/azure-sdk-for-java#6336]
Here is a sample stack:
```
FAILED: DocumentCrudTest::readDocumentWithVeryLargePartitionKey[Direct Https with Strong consistency]("+ -_,:.|~c458f28f-4bff-4457-8466-e0cf0a6eef48 +-_,:.|~")
org.testng.internal.thread.ThreadTimeoutException: Method com.azure.cosmos.rx.DocumentCrudTest.readDocumentWithVeryLargePartitionKey() didn't finish within the time-out 40000
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
    at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
    at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
```

**Comment by kushagraThapar** [comment]
This has been fixed.
