### ISSUE TITLE
[BUG] Address DocumentCrudTest::deleteDocument test failure

### ISSUE THREAD

**Issue by David-Noble-at-work** [Azure/azure-sdk-for-java#6337]
Here is a sample stack:
```
FAILED: DocumentCrudTest::deleteDocument[Direct Tcp with Eventual consistency]("300b30fb-d812-48ac-bf9d-66268c3740fe")
org.testng.internal.thread.ThreadTimeoutException: Method com.azure.cosmos.rx.DocumentCrudTest.deleteDocument() didn't finish within the time-out 40000
    at sun.misc.Unsafe.compareAndSwapObject(Native Method)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.compareAndSetNext(AbstractQueuedSynchronizer.java:2318)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.cancelAcquire(AbstractQueuedSynchronizer.java:767)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1004)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1308)
    at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
    at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:81)
    at reactor.core.publisher.Mono.block(Mono.java:1663)
    at com.azure.cosmos.rx.DocumentCrudTest.deleteDocument(DocumentCrudTest.java:206)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
    at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
    at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
```

**Comment by kushagraThapar** [comment]
This has been fixed on v4.
