### ISSUE TITLE
[BUG] AggregateQueryTests initialization intermittently fails due to collection truncation error and consistently times out in CI  environments

### ISSUE THREAD

**Issue by David-Noble-at-work** [Azure/azure-sdk-for-java#6346]
This issue consistently reproduces on cloud (in my test environments) but frequently succeeds when run in my dev environment. 

Sample stack:
```
CONFIGURATION: @BeforeClass before_AggregateQueryTests
org.testng.internal.InvokeMethodRunnable$TestNGRuntimeException: reactor.core.Exceptions$ReactiveException: RequestTimeoutException{error=null, resourceAddress='rntbd://cdb-ms-prod-eastus1-fd37.documents.azure.com:14382/apps/f16794f1-66f3-4163-8d3e-7f76cdcef6a7/services/799cb769-6488-4b81-a494-034147af3cd1/partitions/0278881e-72c1-4192-ab7f-a23fcb30a21d/replicas/132181689051528160p/', statusCode=408, message=RntbdRequestRecord({"status":{"done":false,"cancelled":false,"completedExceptionally":false},"args":{"transportRequestId":14496,"origin":"rntbd://cdb-ms-prod-eastus1-fd37.documents.azure.com:14382","replicaPath":"/apps/f16794f1-66f3-4163-8d3e-7f76cdcef6a7/services/799cb769-6488-4b81-a494-034147af3cd1/partitions/0278881e-72c1-4192-ab7f-a23fcb30a21d/replicas/132181689051528160p","activityId":"493d791c-06c9-11ea-a23b-7390fcce50db","creationTime":1052579664476617,"lifetime":"PT1M0.026137134S"}}), 
RequestStartTime: "14 Nov 2019 10:26:57.518", RequestEndTime: "14 Nov 2019 10:27:57.544", Duration: 60026 ms, NUMBER of regions attempted: 1
StoreResponseStatistics{requestResponseTime="14 Nov 2019 10:27:57.544", storeResult=storePhysicalAddress: rntbd://cdb-ms-prod-eastus1-fd37.documents.azure.com:14382/apps/f16794f1-66f3-4163-8d3e-7f76cdcef6a7/services/799cb769-6488-4b81-a494-034147af3cd1/partitions/0278881e-72c1-4192-ab7f-a23fcb30a21d/replicas/132181689051528160p/, lsn: 0, globalCommittedLsn: -1, partitionKeyRangeId: null, isValid: true, statusCode: 408, subStatusCode: 0, isGone: false, isNotFound: false, isInvalidPartition: false, requestCharge: 0.0, itemLSN: -1, sessionToken: null, exception: RntbdRequestRecord({"status":{"done":false,"cancelled":false,"completedExceptionally":false},"args":{"transportRequestId":14496,"origin":"rntbd://cdb-ms-prod-eastus1-fd37.documents.azure.com:14382","replicaPath":"/apps/f16794f1-66f3-4163-8d3e-7f76cdcef6a7/services/799cb769-6488-4b81-a494-034147af3cd1/partitions/0278881e-72c1-4192-ab7f-a23fcb30a21d/replicas/132181689051528160p","activityId":"493d791c-06c9-11ea-a23b-7390fcce50db","creationTime":1052579664476617,"lifetime":"PT1M0.026137134S"}}), requestResourceType=Document, requestOperationType=Delete}
, causeInfo=null, responseHeaders={}, requestHeaders={authorization=type%3Dmaster%26ver%3D1.0%26sig%3D%2F6kPI9xq6vq%2Fb3KDFAt65X9SUi98fNaG294XkRHHC3o%3D, Accept=application/json, x-ms-date=Thu, 14 Nov 2019 10:26:57 GMT, x-ms-documentdb-collection-rid=kVhoAJ+kGM0=, x-ms-client-retry-attempt-count=0, x-ms-documentdb-partitionkey=["uniquePartitionKey"], x-ms-remaining-time-in-ms-on-client=60000, x-ms-consistency-level=Eventual}}
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:61)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: reactor.core.Exceptions$ReactiveException: RequestTimeoutException{error=null, resourceAddress='rntbd://cdb-ms-prod-eastus1-fd37.documents.azure.com:14382/apps/f16794f1-66f3-4163-8d3e-7f76cdcef6a7/services/799cb769-6488-4b81-a494-034147af3cd1/partitions/0278881e-72c1-4192-ab7f-a23fcb30a21d/replicas/132181689051528160p/', statusCode=408, message=RntbdRequestRecord({"status":{"done":false,"cancelled":false,"completedExceptionally":false},"args":{"transportRequestId":14496,"origin":"rntbd://cdb-ms-prod-eastus1-fd37.documents.azure.com:14382","replicaPath":"/apps/f16794f1-66f3-4163-8d3e-7f76cdcef6a7/services/799cb769-6488-4b81-a494-034147af3cd1/partitions/0278881e-72c1-4192-ab7f-a23fcb30a21d/replicas/132181689051528160p","activityId":"493d791c-06c9-11ea-a23b-7390fcce50db","creationTime":1052579664476617,"lifetime":"PT1M0.026137134S"}}), 
RequestStartTime: "14 Nov 2019 10:26:57.518FAILED", RequestEndTime: "14 Nov 2019 10:27:57.544", Duration: 60026 ms, NUMBER of regions attempted: 1
StoreResponseStatistics{requestResponseTime="14 Nov 2019 10:27:57.544", storeResult=storePhysicalAddress: rntbd://cdb-ms-prod-eastus1-fd37.documents.azure.com:14382/apps/f16794f1-66f3-4163-8d3e-7f76cdcef6a7/services/799cb769-6488-4b81-a494-034147af3cd1/partitions/0278881e-72c1-4192-ab7f-a23fcb30a21d/replicas/132181689051528160p/, lsn: 0, globalCommittedLsn: -1, partitionKeyRangeId: null, isValid: true, statusCode: 408, subStatusCode: 0, isGone: false, isNotFound: false, isInvalidPartition: false, requestCharge: 0.0, itemLSN: -1, sessionToken: null, exception: RntbdRequestRecord({"status":{"done":false,"cancelled":false,"completedExceptionally":false},"args":{"transportRequestId":14496,"origin":"rntbd://cdb-ms-prod-eastus1-fd37.documents.azure.com:14382","replicaPath":"/apps/f16794f1-66f3-4163-8d3e-7f76cdcef6a7/services/799cb769-6488-4b81-a494-034147af3cd1/partitions/0278881e-72c1-4192-ab7f-a23fcb30a21d/replicas/132181689051528160p","activityId":"493d791c-06c9-11ea-a23b-7390fcce50db","creationTime":1052579664476617,"lifetime":"PT1M0.026137134S"}}), requestResourceType=Document, requestOperationType=Delete}
, causeInfo=null, responseHeaders={}, requestHeaders={authorization=type%3Dmaster%26ver%3D1.0%26sig%3D%2F6kPI9xq6vq%2Fb3KDFAt65X9SUi98fNaG294XkRHHC3o%3D, Accept=application/json, x-ms-date=Thu, 14 Nov 2019 10:26:57 GMT, x-ms-documentdb-collection-rid=kVhoAJ+kGM0=, x-ms-client-retry-attempt-count=0, x-ms-documentdb-partitionkey=["uniquePartitionKey"], x-ms-remaining-time-in-ms-on-client=60000, x-ms-consistency-level=Eventual}}
	at reactor.core.Exceptions.propagate(Exceptions.java:336)
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:91)
	at reactor.core.publisher.Mono.block(Mono.java:1663)
	at com.azure.cosmos.rx.TestSuiteBase.truncateCollection(TestSuiteBase.java:240)
	at com.azure.cosmos.rx.AggregateQueryTests.before_AggregateQueryTests(AggregateQueryTests.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	... 6 more
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:93)
		... 15 more
Caused by: RequestTimeoutException{error=null, resourceAddress='rntbd://cdb-ms-prod-eastus1-fd37.documents.azure.com:14382/apps/f16794f1-66f3-4163-8d3e-7f76cdcef6a7/services/799cb769-6488-4b81-a494-034147af3cd1/partitions/0278881e-72c1-4192-ab7f-a23fcb30a21d/replicas/132181689051528160p/', statusCode=408, message=RntbdRequestRecord({"status":{"done":false,"cancelled":false,"completedExceptionally":false},"args":{"transportRequestId":14496,"origin":"rntbd://cdb-ms-prod-eastus1-fd37.documents.azure.com:14382","replicaPath":"/apps/f16794f1-66f3-4163-8d3e-7f76cdcef6a7/services/799cb769-6488-4b81-a494-034147af3cd1/partitions/0278881e-72c1-4192-ab7f-a23fcb30a21d/replicas/132181689051528160p","activityId":"493d791c-06c9-11ea-a23b-7390fcce50db","creationTime":1052579664476617,"lifetime":"PT1M0.026137134S"}}), 
RequestStartTime: "14 Nov 2019 10:26:57.518", RequestEndTime: "14 Nov 2019 10:27:57.544", Duration: 60026 ms, NUMBER of regions attempted: 1
StoreResponseStatistics{requestResponseTime="14 Nov 2019 10:27:57.544", storeResult=storePhysicalAddress: rntbd://cdb-ms-prod-eastus1-fd37.documents.azure.com:14382/apps/f16794f1-66f3-4163-8d3e-7f76cdcef6a7/services/799cb769-6488-4b81-a494-034147af3cd1/partitions/0278881e-72c1-4192-ab7f-a23fcb30a21d/replicas/132181689051528160p/, lsn: 0, globalCommittedLsn: -1, partitionKeyRangeId: null, isValid: true, statusCode: 408, subStatusCode: 0, isGone: false, isNotFound: false, isInvalidPartition: false, requestCharge: 0.0, itemLSN: -1, sessionToken: null, exception: RntbdRequestRecord({"status":{"done":false,"cancelled":false,"completedExceptionally":false},"args":{"transportRequestId":14496,"origin":"rntbd://cdb-ms-prod-eastus1-fd37.documents.azure.com:14382","replicaPath":"/apps/f16794f1-66f3-4163-8d3e-7f76cdcef6a7/services/799cb769-6488-4b81-a494-034147af3cd1/partitions/0278881e-72c1-4192-ab7f-a23fcb30a21d/replicas/132181689051528160p","activityId":"493d791c-06c9-11ea-a23b-7390fcce50db","creationTime":1052579664476617,"lifetime":"PT1M0.026137134S"}}), requestResourceType=Document, requestOperationType=Delete}
, causeInfo=null, responseHeaders={}, requestHeaders={authorization=type%3Dmaster%26ver%3D1.0%26sig%3D%2F6kPI9xq6vq%2Fb3KDFAt65X9SUi98fNaG294XkRHHC3o%3D, Accept=application/json, x-ms-date=Thu, 14 Nov 2019 10:26:57 GMT, x-ms-documentdb-collection-rid=kVhoAJ+kGM0=, x-ms-client-retry-attempt-count=0, x-ms-documentdb-partitionkey=["uniquePartitionKey"], x-ms-remaining-time-in-ms-on-client=60000, x-ms-consistency-level=Eventual}}
	at com.azure.cosmos.implementation.directconnectivity.rntbd.RntbdRequestRecord.expire(RntbdRequestRecord.java:64)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 more

SKIPPED CONFIGURATION: @BeforeClass before_AggregateQueryTests
SKIPPED CONFIGURATION: @BeforeClass before_AggregateQueryTests
SKIPPED CONFIGURATION: @BeforeClass before_AggregateQueryTests
SKIPPED CONFIGURATION: @BeforeClass before_AggregateQueryTests
SKIPPED CONFIGURATION: @BeforeClass before_AggregateQueryTests
```

**Comment by David-Noble-at-work** [comment]
# Workaround to this issue: 

Ignore failed collection truncations that regularly occur on azure cloud and less frequently occur on local dev test environments. Downside: ignoring truncation failures may cause downstream test failures.

I have a change pending on issue/#6289/cosmos/V4/assess-test-issue.
