### ISSUE TITLE
[BUG] EventHubProducerClient + ClientSecretCredential: cannot send message

### ISSUE THREAD

**Issue by stefando** [Azure/azure-sdk-for-java#6376]
**Describe the bug**
Trying to send data into Event Hub and authorize via ClientSecretCredentials.
Sending fails with the exception:
```
java.lang.IllegalArgumentException: 
status-code: 400, 
status-description: Property 'type' in the 'application-properties' section is either missing, has the wrong type, or has an unexpected value.
```
***Exception or Stack Trace***
```
Exception in thread "main" java.lang.IllegalArgumentException: status-code: 400, status-description: Property 'type' in the 'application-properties' section is either missing, has the wrong type, or has an unexpected value.
	at com.azure.core.amqp.exception.ExceptionUtil.amqpResponseCodeToException(ExceptionUtil.java:93)
	at com.azure.core.amqp.implementation.RequestResponseChannel.settleMessage(RequestResponseChannel.java:217)
	at com.azure.core.amqp.implementation.RequestResponseChannel.lambda$new$0(RequestResponseChannel.java:112)
	at reactor.core.publisher.LambdaSubscriber.onNext(LambdaSubscriber.java:160)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114)
	at reactor.core.publisher.FluxCreate$BufferAsyncSink.drain(FluxCreate.java:793)
	at reactor.core.publisher.FluxCreate$BufferAsyncSink.next(FluxCreate.java:718)
	at reactor.core.publisher.FluxCreate$SerializedSink.next(FluxCreate.java:153)
	at com.azure.core.amqp.implementation.handler.ReceiveLinkHandler.onDelivery(ReceiveLinkHandler.java:95)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:185)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291)
	at com.azure.core.amqp.implementation.ReactorExecutor.run(ReactorExecutor.java:92)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:93)
		at reactor.core.publisher.Mono.block(Mono.java:1663)
		at com.azure.messaging.eventhubs.EventHubProducerClient.send(EventHubProducerClient.java:213)
		at com.sygic.fcd.EhTest2.main(EhTest2.java:67)
```

**To Reproduce**
Run the code with valid event hub config and credentials.

***Code Snippet***
```java
var clientSecretCredential = new ClientSecretCredentialBuilder()
        .clientId("<clientid>")
        .clientSecret("<client secret>")
        .tenantId("<tenant id>")
        .build();

var producer = new EventHubClientBuilder()
        .credential(
                "sb://<my-eh-ns>.servicebus.windows.net",
                "<my-eh-name>",
                clientSecretCredential)
        .buildProducer();

var data = new Vector<EventData>(20);

for (int i = 0; i < 20; i++) {
    var item = new EventData(("Hello world from java! " + i).getBytes(UTF_8));
    item.addProperty("#", 1);
    item.addProperty("v", "TEST");
    data.add(item);
}
producer.send(data);
producer.close();
```

**Expected behavior**
Send will work.

**Setup (please complete the following information):**
 - OS: windows 10
 - Version of the Library used:
``` 
implementation 'com.azure:azure-messaging-eventhubs:5.0.0-preview.5'
implementation 'com.azure:azure-identity:1.0.0'
```

**Additional context**
I was able to send data using `implementation 'com.microsoft.azure:azure-eventhubs:3.0.2'` 
(the same event hub config and credentials (using `ApplicationTokenCredentials`)

**Comment by srnagar** [comment]
@stefando Thanks for reporting the issue. We will look into this and provide an update.

**Comment by conniey** [comment]
This should be fixed in https://github.com/Azure/azure-sdk-for-java/pull/6275
The fully-qualified domain name in the event hub client builder is incorrect. It shouldn't be prefixed with "sb://".

```java
var producer = new EventHubClientBuilder()
        .credential(
                "sb://<my-eh-ns>.servicebus.windows.net",
                "<my-eh-name>",
                clientSecretCredential)
        .buildProducer();
```
