### ISSUE TITLE
[BUG] Cosmos: Address `VeryLargeDocumentQueryTest::queryLargeDocuments` intermittently times out

### ISSUE THREAD

**Issue by David-Noble-at-work** [Azure/azure-sdk-for-java#6377]
#### Observations

When tested locally against a production endpoint this test intermittently fails due to timeouts in Gateway, Direct HTTPS, and Direct TCP when the default timeout is 60 seconds. After bumping the timeout interval to 120 seconds, I have seen that the test consistently succeeds in between 20 and 90 seconds.

#### Workaround

Increase timeout interval from the default of 60 seconds to 120 seconds.

#### Recommendation

Address query performance issues following release of v4.

**Comment by mbhaskar** [comment]
Also see failures with below stack trace!


java.lang.NullPointerException
at com.azure.cosmos.rx.VeryLargeDocumentQueryTest.createLargeDocument(VeryLargeDocumentQueryTest.java:79)
at com.azure.cosmos.rx.VeryLargeDocumentQueryTest.queryLargeDocuments(VeryLargeDocumentQueryTest.java:52)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by kushagraThapar** [comment]
This has been fixed on v4.
