### ISSUE TITLE
[BUG] UserDefinedFunctionUpsertReplaceTest initialization consistently times out in CI environments.

### ISSUE THREAD

**Issue by David-Noble-at-work** [Azure/azure-sdk-for-java#6383]
Sample stack
```
FAILED CONFIGURATION: @BeforeClass beforeClass
org.testng.internal.thread.ThreadTimeoutException: Method com.azure.cosmos.rx.UserDefinedFunctionUpsertReplaceTest.beforeClass() didn't finish within the time-out 60000
    at reactor.core.publisher.BlockingSingleSubscriber.dispose(BlockingSingleSubscriber.java:64)
    at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:84)
    at reactor.core.publisher.Mono.block(Mono.java:1663)
    at com.azure.cosmos.rx.TestSuiteBase.truncateCollection(TestSuiteBase.java:240)
    at com.azure.cosmos.rx.UserDefinedFunctionUpsertReplaceTest.beforeClass(UserDefinedFunctionUpsertReplaceTest.java:73)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
    at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
    at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
```

**Comment by kushagraThapar** [comment]
This has been fixed on v4.
