### ISSUE TITLE
[BUG] OrderbyDocumentQueryTest initialization intermittently times out in CI environments

### ISSUE THREAD

**Issue by David-Noble-at-work** [Azure/azure-sdk-for-java#6386]
See this [failure](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=190042&view=ms.vss-test-web.build-test-results-tab&runId=6818330&resultId=100264&paneView=debug), for example.

#### Error message
```
Method com.azure.cosmos.rx.OrderbyDocumentQueryTest.before_OrderbyDocumentQueryTest() didn't finish within the time-out 60000
```
#### Stack trace
```
org.testng.internal.thread.ThreadTimeoutException: Method com.azure.cosmos.rx.OrderbyDocumentQueryTest.before_OrderbyDocumentQueryTest() didn't finish within the time-out 60000
at java.base@11.0.5/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.indexOf(ScheduledThreadPoolExecutor.java:1024)
at java.base@11.0.5/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.remove(ScheduledThreadPoolExecutor.java:1048)
at java.base@11.0.5/java.util.concurrent.ThreadPoolExecutor.remove(ThreadPoolExecutor.java:1751)
at java.base@11.0.5/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.cancel(ScheduledThreadPoolExecutor.java:293)
at app//reactor.core.scheduler.SchedulerTask.dispose(SchedulerTask.java:126)
at app//reactor.core.publisher.MonoDelay$MonoDelayRunnable.cancel(MonoDelay.java:135)
at app//reactor.core.publisher.FluxDelaySubscription$DelaySubscriptionOtherSubscriber.cancel(FluxDelaySubscription.java:100)
at app//reactor.core.publisher.MonoSingle$SingleSubscriber.cancel(MonoSingle.java:101)
at app//reactor.core.publisher.Operators$MultiSubscriptionSubscriber.drainLoop(Operators.java:2013)
at app//reactor.core.publisher.Operators$MultiSubscriptionSubscriber.drain(Operators.java:1982)
at app//reactor.core.publisher.Operators$MultiSubscriptionSubscriber.cancel(Operators.java:1794)
at app//reactor.core.publisher.Operators$DeferredSubscription.cancel(Operators.java:1430)
at app//reactor.core.publisher.FluxDelaySubscription$DelaySubscriptionOtherSubscriber.cancel(FluxDelaySubscription.java:101)
at app//reactor.core.publisher.MonoSingle$SingleSubscriber.cancel(MonoSingle.java:101)
at app//reactor.core.publisher.Operators$MultiSubscriptionSubscriber.drainLoop(Operators.java:2013)
at app//reactor.core.publisher.Operators$MultiSubscriptionSubscriber.drain(Operators.java:1982)
at app//reactor.core.publisher.Operators$MultiSubscriptionSubscriber.cancel(Operators.java:1794)
at app//reactor.core.publisher.Operators$DeferredSubscription.cancel(Operators.java:1430)
at app//reactor.core.publisher.FluxDelaySubscription$DelaySubscriptionOtherSubscriber.cancel(FluxDelaySubscription.java:101)
at app//reactor.core.publisher.MonoSingle$SingleSubscriber.cancel(MonoSingle.java:101)
at app//reactor.core.publisher.Operators$MultiSubscriptionSubscriber.drainLoop(Operators.java:2013)
at app//reactor.core.publisher.Operators$MultiSubscriptionSubscriber.drain(Operators.java:1982)
at app//reactor.core.publisher.Operators$MultiSubscriptionSubscriber.cancel(Operators.java:1794)
at app//reactor.core.publisher.Operators$DeferredSubscription.cancel(Operators.java:1430)
at app//reactor.core.publisher.FluxDelaySubscription$DelaySubscriptionOtherSubscriber.cancel(FluxDelaySubscription.java:101)
at app//reactor.core.publisher.MonoSingle$SingleSubscriber.cancel(MonoSingle.java:101)
at app//reactor.core.publisher.Operators$MultiSubscriptionSubscriber.drainLoop(Operators.java:2013)
at app//reactor.core.publisher.Operators$MultiSubscriptionSubscriber.drain(Operators.java:1982)
at app//reactor.core.publisher.Operators$MultiSubscriptionSubscriber.cancel(Operators.java:1794)
at app//reactor.core.publisher.Operators$DeferredSubscription.cancel(Operators.java:1430)
at app//reactor.core.publisher.FluxDelaySubscription$DelaySubscriptionOtherSubscriber.cancel(FluxDelaySubscription.java:101)
at app//reactor.core.publisher.MonoSingle$SingleSubscriber.cancel(MonoSingle.java:101)
at app//reactor.core.publisher.Operators$MultiSubscriptionSubscriber.drainLoop(Operators.java:2013)
at app//reactor.core.publisher.Operators$MultiSubscriptionSubscriber.drain(Operators.java:1982)
at app//reactor.core.publisher.Operators$MultiSubscriptionSubscriber.cancel(Operators.java:1794)
at app//reactor.core.publisher.Operators$DeferredSubscription.cancel(Operators.java:1430)
at app//reactor.core.publisher.FluxDelaySubscription$DelaySubscriptionOtherSubscriber.cancel(FluxDelaySubscription.java:101)
at app//reactor.core.publisher.MonoSingle$SingleSubscriber.cancel
```

**Comment by kushagraThapar** [comment]
This has been fixed on v4.
