### ISSUE TITLE
[BUG] azure-storage.jar and rxjava.jar version 2 support 

### ISSUE THREAD

**Issue by vinayak-kuchekar** [Azure/azure-sdk-for-java#6552]
Hi,
We have integrated our product with Azure Blob Storage and communicate using the Azure Java SDK jars. As a jar dependency, we are using the rxjava.jar (version 1.2.4). This version of rxjava.jar uses unsafe API from Oracle Java 11 SDK and hence not compatible with java 11. The rxjava jar provider has fixed these issues in latest version 2.x.x. This 2.x.x version is complete rewrite of library and azure-storage.jar (version 8.3.0) and azure-keyvault.jar (version 1.2.0) are not compatible with it. Can you please let us know when Microsoft will support the rxjava.jar (version 2.x.x)?

Exception or Stack Trace
Caused by: java.lang.NoClassDefFoundError: rx/functions/Func1
	at com.ptc.windchill.objectstorage.azureblob.encryption.csekeyvault.CSEKeyVaultBlobEncryptConfig.getKeyVaultKey(CSEKeyVaultBlobEncryptConfig.java:86)
	at com.ptc.windchill.objectstorage.azureblob.encryption.csekeyvault.CSEKeyVaultBlobFileWriter.setEncryptionPolicy(CSEKeyVaultBlobFileWriter.java:54)
	at com.ptc.windchill.objectstorage.azureblob.BlobFileWriter.upload(BlobFileWriter.java:615)
	at com.ptc.windchill.objectstorage.azureblob.BlobFileWriter.storeStreamUpload(BlobFileWriter.java:533)
	at com.ptc.windchill.objectstorage.azureblob.BlobFileWriter.storeStreamMultipart(BlobFileWriter.java:410)
	at com.ptc.windchill.objectstorage.azureblob.BlobFileWriter.storeUnKnownLengthStream(BlobFileWriter.java:322)
	at com.ptc.windchill.objectstorage.azureblob.BlobFileWriter.storeStream(BlobFileWriter.java:281)
	at com.ptc.windchill.objectstorage.azureblob.BlobFileWriter.storeStream(BlobFileWriter.java:228)
	at wt.objectstorage.ContentFileWriter.storeStream(ContentFileWriter.java:97)
	at wt.objectstorage.ContentFileWriter.storeStream(ContentFileWriter.java:66)
	at wt.fv.StoreStreamListener.prepareToUpload(StoreStreamListener.java:207)
	at wt.fv.StoreStreamListener.prepareToUpload(StoreStreamListener.java:165)
	at wt.fv.StoreStreamListener.prepareToUpload(StoreStreamListener.java:128)
	at wt.fv.uploadtocache.DoUploadToCache_Server.storeContentInVaultOnMaster(DoUploadToCache_Server.java:612)
	at wt.fv.uploadtocache.DoUploadToCache_Server.storeSingleFile(DoUploadToCache_Server.java:1878)
	at wt.fv.uploadtocache.DoUploadToCache_Server.doMultiPartUploadToCache_Server(DoUploadToCache_Server.java:1689)
	... 55 more
Caused by: java.lang.ClassNotFoundException: rx.functions.Func1
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 71 more

Test the azure-storage.jar, azure-keyvault.jar and its dependencies with Java 11.
Using jdeps tool, scan the azure-storage.jar and its dependencies.

Any sample code (get Key from Key Vault Service) for azure-storage.jar, azure-keyvault.jar can be tested with java 11.

We expect that the azure-storage.jar, azure-keyvault.jar supports the rxjava.jar version 2.x.x

No screenshots

Setup:
 - OS: Centos 7
 - IDE : Eclipse
- JDK- Oracle SE JDK 11
 - azure-storage.jar(8.3.0) 
   azure-keyvault.jar (1.2.0)
   azure-keyvault-core.jar (1.2.0)
   azure-keyvault-cryptography.jar (1.2.0)
   azure-keyvault-extensions.jar (1.2.0)
   azure-keyvault-webkey.jar (1.2.0)
   rxjava.jar (1.2.4)

Additional context
We are upgrading the java support to version 11 for our product.

**Comment by vinayak-kuchekar** [comment]
Type in my above bug report. Under setup section, rxjava.jar should be 2.2.14.

**Comment by joshfree** [comment]
@rickle-msft can you please take a look?

**Comment by joshfree** [comment]
@vinayak-kuchekar please note that we have shipped new major releases of the Azure SDK for Java including KeyVault and Storage.  The new versions have names starting with 'com.azure' instead of 'com.microsoft.azure'.  The new SDK versions have new features, better performance, and are more usable and consistent following the Azure SDK Design Guidelines. 

- There is also a blog post about these new versions here: https://techcommunity.microsoft.com/t5/Azure-SDK/November-2019-unified-Azure-SDK-GA/ba-p/1020875

- You can find samples, migration guides, and documentation for the new major versions of the libraries here: https://github.com/azure/azure-sdk-for-java#client-ga-november-2019-releases

- A community "Gitter" channel for Azure SDK for Java is also available here: https://gitter.im/Azure/azure-sdk-for-java?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

**Comment by rickle-msft** [comment]
Hi, @vinayak-kuchekar. v8.x.x of the Storage sdk has no interaction with rxJava and will not be doing any work to explicitly support it. If you are seeing No Class Def errors, you are likely running into some sort of dependency conflict that has to be resolved by pinning the desired version of the dependency in question in your pom. Please let us know if you have trouble with this.

**Comment by amishra-dev** [comment]
@vinayak-kuchekar please reactivate if you still need help with this. Thanks
