### ISSUE TITLE
[BUG] KeyEncryptionKeyClientBuilder.buildKeyEncryptionKey().getKeyId(String keyId) leads to NullPointerException

### ISSUE THREAD

**Issue by chpoon92** [Azure/azure-sdk-for-java#6598]
**Describe the bug**
In com.azure:azure-security-keyvault-keys:4.0.0, use com.azure.security.keyvault.keys.cryptography.KeyEncryptionKeyClientBuilder.buildKeyEncryptionKey().getKeyId(String keyId) leads to NullPointerException

***Exception or Stack Trace***
```
java.lang.NullPointerException: null
	at com.azure.security.keyvault.keys.cryptography.KeyEncryptionKeyAsyncClient.getKeyId(KeyEncryptionKeyAsyncClient.java:38) ~[azure-security-keyvault-keys-4.0.0.jar:na]
	at com.azure.security.keyvault.keys.cryptography.KeyEncryptionKeyClient.getKeyId(KeyEncryptionKeyClient.java:28) ~[azure-security-keyvault-keys-4.0.0.jar:na]
	at com.example.demo.DemoApplication.test(DemoApplication.java:49) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389) ~[spring-beans-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333) ~[spring-beans-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157) ~[spring-beans-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:416) ~[spring-beans-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1795) ~[spring-beans-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595) ~[spring-beans-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:879) ~[spring-beans-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878) ~[spring-context-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550) ~[spring-context-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) ~[spring-boot-2.2.1.RELEASE.jar:2.2.1.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[spring-boot-2.2.1.RELEASE.jar:2.2.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-2.2.1.RELEASE.jar:2.2.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) ~[spring-boot-2.2.1.RELEASE.jar:2.2.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) ~[spring-boot-2.2.1.RELEASE.jar:2.2.1.RELEASE]
	at com.example.demo.DemoApplication.main(DemoApplication.java:28) ~[classes/:na]
```

**To Reproduce**
I have put the reproducible codes in https://github.com/chpoon92/azure-key-vault-bugs
Preparation:

1. Azure key vault url
2. Service principal that can access key vault
   * tenant-id
   * client id
   * client secret
3. Key name of an existing key in key vault
4. Put above values in the config file /src/main/resources/application.yml

Run:
In cmd, execute
```
mvn spring-boot:run
```

***Code Snippet***
I have put in /src/main/java/com/example/demo/DemoApplication.java
In function test()

**Expected behavior**
Key id returned by com.azure.security.keyvault.keys.models.KeyVaultKey should be same as key id returned by com.azure.core.cryptography.KeyEncryptionKey

**Setup (please complete the following information):**
 - OS: Windows
 - IDE : IntelliJ
 - JDK : OpenJDK 11
 - Build tools : Maven 3.6.2
 - Library:
    - com.azure:azure-security-keyvault-keys:4.0.0
   - com.azure:azure-identity:1.0.0
   - org.springframework.boot:spring-boot-starter:2.2.1.RELEASE

**Additional context**
The purpose of using com.azure.security.keyvault.keys.cryptography.KeyEncryptionKeyClientBuilder is because I need to apply Azure Key Vault to client side encryption of Azure Storage.
The setup in com.azure:azure-storage-blob-cryptography:12.0.0 requires an instance of com.azure.core.cryptography.AsyncKeyEncryptionKeyResolver, which is the interface implemented by KeyEncryptionKeyClientBuilder.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [*] Bug Description Added
- [*] Repro Steps Added
- [*] Setup information Added

**Comment by joshfree** [comment]
Thanks for reporting this issue @chpoon92.  The Key Vault SDK owners will follow up with you shortly.

/cc @g2vinay @samvaity

**Comment by FredGao-new** [comment]
Follow guide: https://docs.microsoft.com/en-us/azure/storage/blobs/storage-encrypt-decrypt-blobs-key-vault

To do client-side encryption of Azure storage
	1. Create a secret(symmetric key) that satisfies the requirements;
	2. Create a KeyEncryptionKeyResolver and use KeyEncryptionKeyResolver to build a KeyEncryptionkey with the secret;
	3. Create EncryptedBlobClient using the KeyEncryptionKey, KeyEncryptionKeyResolver;
	4. Then can use EncryptedBlobClient  to do the client-side encryption or decryption.

Please consider using the following code to do Azure Storage client-side encryption:
```
     ClientSecretCredential tokenCredential = new ClientSecretCredentialBuilder()
                    .tenantId(keyVaultProperties.getTenantId()).clientId(keyVaultProperties.getClientId())
                    .clientSecret(keyVaultProperties.getClientSecret()).build();
     //Create a secret(symmetric key) that satisfies the requirements;
     SecretClient secretClient = new SecretClientBuilder().vaultUrl(keyVaultProperties.getEndpoint()).credential(tokenCredential).buildClient();
     byte[] kek = { 0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x0E, 0x0F, 0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17 };
     KeyVaultSecret secret = secretClient.setSecret("yourSecretName",  Base64.getEncoder().encodeToString(kek));
     String secretId = secret.getId();
     log.info("secretId={}", secretId);
     //Create a KeyEncryptionKeyResolver and use KeyEncryptionKeyResolver to build a KeyEncryptionkey with the secret;
     KeyEncryptionKeyClientBuilder keyEncryptionKeyResolver = new KeyEncryptionKeyClientBuilder()
                    .credential(tokenCredential);
     byte[] cek =  { 0x00, 0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77, (byte) 0x88, (byte) 0x99, (byte) 0xAA, (byte) 0xBB, (byte) 0xCC, (byte) 0xDD, (byte) 0xEE, (byte) 0xFF };
     KeyEncryptionKey key = keyEncryptionKeyResolver.buildKeyEncryptionKey(secret.getId());
     //Create EncryptedBlobClient using the KeyEncryptionKey, KeyEncryptionKeyResolver;
     EncryptedBlobClient client = new EncryptedBlobClientBuilder()
	            .key(key, "A192KW").keyResolver(keyEncryptionKeyResolver)
	            .connectionString("yourConnectionString")
	            .containerName("yourContainerName").blobName("yourBlobName").buildEncryptedBlobClient();
```

**Comment by FredGao-new** [comment]
@jongio

**Comment by FredGao-new** [comment]
Hi, how is this issue going? Feel free to let us know if further help is needed.

**Comment by g2vinay** [comment]
The fix for this issue has been merged into the master. It will be released as part of the KV release going out tomorrow on 7th Jan 2020.

**Comment by chpoon92** [comment]
The fix has fixed the issue in my bug demo project.
However, in my use case, I found that following 2 functions throw IllegalStateException due to calling Mono.block() in non blocking thread:

com.azure:azure-storage-blob-cryptography:12.1.0:
com.azure.storage.blob.specialized.cryptography.EncryptedBlobAsyncClient.encryptBlob(Flux<ByteBuffer> plainTextFlux)

com.azure:azure-security-keyvault-keys:4.1.0
com.azure.security.keyvault.keys.cryptography.CryptographyClientBuilder.ensureValidKeyAvailable()

Currently I fix the issue by rewriting these two functions with non blocking function call.

**Comment by g2vinay** [comment]
@chpoon92 , 
good to know, the initial issue is resolved.

Mono.block() in a non-blocking thread is a generic error.
I haven't noticed this issue in CryptographyAsyncClient's crypto operation calls.
If you could share your code that would be helpful.

**Comment by g2vinay** [comment]
@chpoon92 
Thank you for posting this issue again.
Since the root issue is resolved, we'll be closing this issue.
Do reach out to us, If you spot any other issues.
