### ISSUE TITLE
Runtime exception: Service or property not registered for azure media service

### ISSUE THREAD

**Issue by kennethinsnow** [Azure/azure-sdk-for-java#668]
All i did is try to create a MediaContract object:
MediaContract mediaService = MediaService.create(MediaConfiguration.configureWithOAuthAuthentication(mediaServiceUri,
                oAuthUri, AMSAccountName, AMSAccountKey, scope));
It can be run in Intellij but if i try to package it into an independent jar and running it from the jar, it reports:
Exception in thread "main" java.lang.RuntimeException: Service or property not registered:  com.microsoft.windowsazure.services.media.MediaContract class com.sun.jersey.api.client.Client
    at com.microsoft.windowsazure.core.DefaultBuilder.build(DefaultBuilder.java:198)
    at com.microsoft.windowsazure.core.DefaultBuilder$1.create(DefaultBuilder.java:138)
    at com.microsoft.windowsazure.core.DefaultBuilder.build(DefaultBuilder.java:200)
    at com.microsoft.windowsazure.core.DefaultBuilder$1.create(DefaultBuilder.java:138)
    at com.microsoft.windowsazure.core.DefaultBuilder.build(DefaultBuilder.java:200)
    at com.microsoft.windowsazure.Configuration.create(Configuration.java:119)
    at com.microsoft.windowsazure.services.media.MediaService.create(MediaService.java:47)
    at com.yxxxx.fixxxx.InputAssetDeleter.main(InputAssetDeleter.java:37)

looks similar to issue 466 https://github.com/Azure/azure-sdk-for-java/issues/466, but the solution there can't fix my problem. Could anybody look into it?

Thanks,

**Comment by jianghaolu** [comment]
Can you try modifying the Exports file in the shaded jar directly? Adding all the entries from all the $Exports files in the modules you are depending on.

**Comment by jianghaolu** [comment]
This can only be worked around for now - in 1.0 we will ditch the service loader.

**Comment by kennethinsnow** [comment]
Jianghao, Thanks for the response.
Are you referring to this solution:
http://stackoverflow.com/questions/27127107/error-accessing-azure-service-bus-from-storm-cluster
if not, could you elaborate more on it?

**Comment by jianghaolu** [comment]
Hi @kennethinsnow 
Yes I'm referring to that and issue 466 both. The underlying problem is that multiple $Exports files across multiple modules will collapse into one and it's unpredictable which entries will survive in the single $Exports file in the shaded jar.

The service loader looks into $Exports file to find all the Exports classes defined. For example, this [core $Exports](https://github.com/Azure/azure-sdk-for-java/blob/master/core/azure-core/src/main/resources/META-INF/services/com.microsoft.windowsazure.core.Builder$Exports) defines a bunch, and the [media $Exports] defines a bunch too. You can take a look at your shaded jar and I believe not all of them are in the $Exports file.

**Comment by martinsawicki** [comment]
obsolete - pls refer to the latest Azure Maangement LIbraries for Java (no service loader anymore)
