### ISSUE TITLE
[BUG] Random Blob Upload Errors for Moderate Workloads

### ISSUE THREAD

**Issue by rbrako-nlsn** [Azure/azure-sdk-for-java#6688]
**Describe the bug**
Uploading files randomly fails when sequentially uploading 30 files.  Largest file is 100 MB, some are 1-100MB, and some are less than 1MB.  Error is always "Request body emitted ${n+1} bytes, more than the expected ${n} bytes."  Uploading all 30 files occasionally works, but typically not.

***Exception or Stack Trace***
```
2019-12-05 20:22:58 ERROR Managed to upload 17 files 
2019-12-05 20:22:58 ERROR com.azure.core.exception.UnexpectedLengthException: Request body emitted 7962674 bytes, more than the expected 7962673 bytes.
com.nielsen.redacted.InputUploadException: com.azure.core.exception.UnexpectedLengthException: Request body emitted 7962674 bytes, more than the expected 7962673 bytes.
	at com.nielsen.Redacted.method(Redacted.java:496)
```

**To Reproduce**
1. SDK Versions: both 12.0.0 and 12.0.0-preview-4
2. Java 11, including containerized openjdk:11-jre-slim
3. Setup multiple `InputStream` (particularly, from a remote connection instead of file system).
4. Synchronously and sequentially invoke `BlockBlobClient.upload(inputStream, size)`

***Code Snippet***
```
if (contentStream.getSize() < TWO_HUNDRED_FORTY_MB) { // api limit is 256MB
				BlockBlobItem blobItem = blockBlobClient.upload(stream, contentStream.getSize());
```

**Expected behavior**
Expected higher success rate; 95% would be fine.  Observed rate is under 50%.

**Screenshots**
N/A

**Setup (please complete the following information):**
 - OS: [Linux]
 - IDE : [IntelliJ]
 - Version of the Library used: 12.0.0

**Additional context**
Things are more reliable when using `blockBlobClient.getBlobOutputStream()`, but that is much slower, unless there's a trick to using it with arbitrary input streams.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by rickle-msft** [comment]
Hi, @rbrako-nlsn a couple thoughts. As may be self evident, this exception manifests when the length of the data passed does not match the length specified by the parameter. This is to provide safety against data loss/corruption, especially when hitting retries. 

It's interesting to me that you are seeing these failures more when you are using a remote connection. Because remote connections can be unreliable, we sometimes see problems there in successfully processing the whole stream. Are you able to confirm that there are no errors in your download network stream? And likewise are you able to see if your upload requests are getting retried at all?

Another interesting point is the n vs n+1 split. When you hit this UnexpectedLengthException, are you always seeing it off by one? That suggests to me that maybe there's an error in calculating the stream length.

Finally, if you have a more complete stack trace, that could also be helpful in validating that we aren't throwing an UnexpectedLengthException erroneously.

**Comment by rbrako-nlsn** [comment]
Hi @rickle-msft,
Thanks for the response.  I've been running the same workload each time.  My answers to your comments/questions are:
1. I do expect the occasional issue since remote connections are involved, and that's accounted for.  But so far, I've run a few test cases which copied remote->filesystem and filesystem->blob, and those were fine.  Copying from the remote->filesystem so far hasn't failed once for any file.
2. Currently not retrying individual requests, but we can revisit that.
3. Always manifests as one extra byte emitted.  The value passed for stream length is always the same.  The file which fails a given workload run varies.
4. More complete stack trace:
```
Caused by: com.azure.core.exception.UnexpectedLengthException: Request body emitted 575685 bytes, more than the expected 575684 bytes.
	at com.azure.storage.common.Utility.lambda$convertStreamToByteBuffer$3(Utility.java:232)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:243)
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:360)
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onComplete(FluxConcatMap.java:269)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onComplete(FluxMapFuseable.java:144)
	at reactor.core.publisher.FluxJust$WeakScalarSubscription.request(FluxJust.java:101)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:162)
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onSubscribe(FluxConcatMap.java:229)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:90)
	at reactor.core.publisher.FluxJust.subscribe(FluxJust.java:70)
	at reactor.core.publisher.FluxMapFuseable.subscribe(FluxMapFuseable.java:63)
	at reactor.core.publisher.FluxConcatMap.subscribe(FluxConcatMap.java:121)
	at reactor.core.publisher.FluxPeek.subscribe(FluxPeek.java:83)
	at reactor.core.publisher.Flux.subscribe(Flux.java:7793)
	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.run(FluxSubscribeOn.java:194)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	... 3 common frames omitted
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:93)
		at reactor.core.publisher.Mono.block(Mono.java:1494)
		at com.azure.storage.common.implementation.StorageImplUtils.blockWithOptionalTimeout(StorageImplUtils.java:94)
		at com.azure.storage.blob.specialized.BlockBlobClient.uploadWithResponse(BlockBlobClient.java:190)
		at com.azure.storage.blob.specialized.BlockBlobClient.upload(BlockBlobClient.java:144)
		at com.nielsen.Redacted.method(Domain.java:53)
		at com.nielsen.Redacted$$FastClassBySpringCGLIB$$8b08d1e8.invoke(<generated>)
		at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
		at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749)
		at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
		at com.ryantenney.metrics.spring.ExceptionMeteredMethodInterceptor.invoke(ExceptionMeteredMethodInterceptor.java:46)
		at com.ryantenney.metrics.spring.ExceptionMeteredMethodInterceptor.invoke(ExceptionMeteredMethodInterceptor.java:33)
		at com.ryantenney.metrics.spring.AbstractMetricMethodInterceptor.invoke(AbstractMetricMethodInterceptor.java:59)
		at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
		at com.ryantenney.metrics.spring.TimedMethodInterceptor.invoke(TimedMethodInterceptor.java:48)
		at com.ryantenney.metrics.spring.TimedMethodInterceptor.invoke(TimedMethodInterceptor.java:34)
		at com.ryantenney.metrics.spring.AbstractMetricMethodInterceptor.invoke(AbstractMetricMethodInterceptor.java:59)
		at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
		at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
		at com.nielsen.Redacted$$EnhancerBySpringCGLIB$$a330a5b6.method(<generated>)
		at com.nielsen.Redacted.method(Domain.java:31)
		at com.nielsen.Redacted.method(Domain.java:492)
```

**Comment by rickle-msft** [comment]
Would it be possible for you to give me some more exact stats on the number and size of the files and a larger sample of the code you're running so I can try to reproduce this more reliably? The fact that different runs of the same data sets will fail on different files, yet all the failures are off by one on the expected length is a little puzzling, and it'd be helpful to be able to run this locally.

**Comment by rbrako-nlsn** [comment]
Greetings,

I think this additional code should be helpful:

// note: ContentStream is a basic abstraction for
filename/size/InputStream used for remote connections

BlobContainerClient containerClient =
serviceClient.getBlobContainerClient(containerName); //
BlobServiceClient serviceClient is currently setup with just endpoint
and credential
String blobName = concatName(folder, contentStream.getName()); // just
a basic concat
BlockBlobClient blockBlobClient = getBlobClient(containerClient,
blobName).getBlockBlobClient(); // url character escape, then
containerClient.getBlobClient(escapedName)
try (InputStream stream = contentStream.getStream()) {
	if (contentStream.getSize() < TWO_HUNDRED_FORTY_MB) { // api limit is 256MB
		BlockBlobItem blobItem = blockBlobClient.upload(stream,
contentStream.getSize());
		return contentStream.getSize();

	} else { /* different path */ }
}



I have this log output which captured the expected results when copying to
filesystem.
(It is the same workload mentioned in the GitHub ticket):

2019-12-09 15:00:43 WARN  Copied to fs 301 / 301
2019-12-09 15:00:44 WARN  Copied to fs 4622962 / 4622962
2019-12-09 15:00:45 WARN  Copied to fs 8647589 / 8647589
2019-12-09 15:00:46 WARN  Copied to fs 582452 / 582452
2019-12-09 15:00:46 WARN  Copied to fs 1220453 / 1220453
2019-12-09 15:00:47 WARN  Copied to fs 682806 / 682806
2019-12-09 15:00:48 WARN  Copied to fs 707869 / 707869
2019-12-09 15:00:51 WARN  Copied to fs 1062240 / 1062240
2019-12-09 15:00:51 WARN  Copied to fs 20664 / 20664
2019-12-09 15:00:52 WARN  Copied to fs 22854 / 22854
2019-12-09 15:00:52 WARN  Copied to fs 2023609 / 2023609
2019-12-09 15:00:54 WARN  Copied to fs 42110347 / 42110347
2019-12-09 15:00:55 WARN  Copied to fs 45093634 / 45093634
2019-12-09 15:00:56 WARN  Copied to fs 1379303 / 1379303
2019-12-09 15:00:57 WARN  Copied to fs 575684 / 575684
2019-12-09 15:00:57 WARN  Copied to fs 1104468 / 1104468
2019-12-09 15:00:58 WARN  Copied to fs 8982452 / 8982452
2019-12-09 15:00:59 WARN  Copied to fs 7962673 / 7962673
2019-12-09 15:01:00 WARN  Copied to fs 670228 / 670228
2019-12-09 15:01:01 WARN  Copied to fs 127382939 / 127382939
2019-12-09 15:01:02 WARN  Copied to fs 3812172 / 3812172
2019-12-09 15:01:03 WARN  Copied to fs 13891009 / 13891009
2019-12-09 15:01:04 WARN  Copied to fs 11082432 / 11082432
2019-12-09 15:01:05 WARN  Copied to fs 3009580 / 3009580
2019-12-09 15:01:06 WARN  Copied to fs 1769 / 1769
2019-12-09 15:01:06 WARN  Copied to fs 580390 / 580390
2019-12-09 15:01:07 WARN  Copied to fs 3255638 / 3255638
2019-12-09 15:01:08 WARN  Copied to fs 114536 / 114536
2019-12-09 15:01:08 WARN  Copied to fs 2913446 / 2913446
2019-12-09 15:01:11 WARN  Copied to fs 50489069 / 50489069

Thanks again for your time,

Robert Brako

**Comment by rickle-msft** [comment]
Thank you for this data. I just set up a sample application that I think captures the same behavior, and I'm not able to see this exception. I will continue with a few more runs, but in the meantime, it may be worth exploring a couple other possibilities.

One hypothesis is that the reason for the +1 is that the source is actually an arbitrary size larger than the size parameter, but it always shows as a +1 because of an implementation detail. We call `available()` on the source stream to check if there's more data after we've read the expected amound, which, if it's a network stream, may only recognize the next byte on the wire? I'm not positive and it could depend on the implementation. I'm not sure how contentStream is implemented, but is there any chance the size property could be getting calculated incorrectly? 

Still, if that were the case, it seems like you would be getting some cases where the data size is too small...

**Comment by rickle-msft** [comment]
As a sanity check, can you see anything that is meaningfully different in how I'm trying to reproduce this error:

```
for (int i=0; i<30; i++) {
            long size = containerClient.getBlobClient("" + i).getProperties().getBlobSize();
            URLConnection conn = new URL("http://account.blob.core.windows.net/container/" + i).openConnection();
            containerClient.getBlobClient("upload_" + i).getBlockBlobClient().upload(conn.getInputStream(), size, true);
        }
```

**Comment by rickle-msft** [comment]
It may also be worth revisiting the possibility of retries on upload. Do you have any logs for your upload operations?

**Comment by rbrako-nlsn** [comment]
Hi, `ContentStream` is just a wrapper.  The actual `InputStream` actually comes from a vendor sdk; I don't know if `URLConnection` would be sufficiently similar.

The size also comes from the remote service, via an API call shortly beforehand.  Thus far, there has been no evidence that the value has been different from what it should be; in the tests copying from remote->filesystem, the values were always the same.

The sanity check looks fine and representative - I definitely appreciate it - with the caveat being the underlying `InputStream` as mentioned above.  We also have this inside a web app, executed in a thread pool outside of the http request thread, but I'm hoping that isn't relevant.  Also to confirm, the test is with 12.0.0 and Java 11?

I should be able test out the retries by tomorrow morning; I can see how to do it for `BlobServiceClient`, but any tips on if it's supported at the `ContainerClient` or `BlockBlobClient` level would be great.

**Comment by rickle-msft** [comment]
This is with 12.0.0 using Java 8. I can try again with 11 if you suspect there might be a difference in the stream management code. 

Retries should be the same for all clients--you can specify it on each builder, or you can specify it on a parent object like `BlobServiceClient` and then as you call `getContainerClient()`, etc. those child clients will inherit the retry and logging policies. Note that there should be up to three retries by default, so it should more be a matter of capturing the logs. Let me know if you need more support getting that setup, otherwise I'll hang tight until tomorrow for that info.

**Comment by rbrako-nlsn** [comment]
I think the java version is important.  We maybe should have reported this at the time, but we had a problem with blob sdk when switching from Java 8 to 11.  In some but not all endpoints, there was an extra `\0` that prevented parsing http responses, and there was some deep underlying java thing that changed.

**Comment by rickle-msft** [comment]
Ok. I will install jdk 11 and run the sample app on that

**Comment by rickle-msft** [comment]
I wasn't seeing any different results after running on JDK 11. Let me know what you find about retries in the morning.

**Comment by rbrako-nlsn** [comment]
Just to update, I'm having trouble configuring retry and logging - making updates to the builder doesn't seem to have an effect.

**Comment by rbrako-nlsn** [comment]
Ok, logging configured by adding setting `Configuration.PROPERTY_AZURE_LOG_LEVEL` to 2.
I observed that the `UnexpectedLengthException` seems to prevent retry, since there weren't additional http logs once the failure happened.

**Comment by rickle-msft** [comment]
@rbrako-nlsn Thanks for getting the logging up. It's expected that there would be no retries after the UnexpectedLengthException, but it's commonly triggered after the first retry. To clarify, you're seeing that the UnexpectedLengthException is happening on the first attempt before any retries, correct?

**Comment by rickle-msft** [comment]
Another thing we can try is setting an exception break point to break when the UnexpectedLengthException is thrown. If you can do that and capture some information about the state of the upload at that point like the value of any variables on the stack, that might also help us take a closer look at what's going on. I am continuing to run my test application in hopes of hitting a similar exception, but until that point I am limited to trying to facilitate your debugging locally. Thank you for your continued patience and cooperation in this matter.

**Comment by rbrako-nlsn** [comment]
Thanks, and likewise.  I'll see if I can catch it.

I did try another experiment where I wrapped the input stream with something that copies bytes to the filesystem as well as blob, and noticed strange behavior such as the files having a lot of empty data written at the end, even up to a few GB.  That was probably an implementation problem on my end though.

Similar to your suggestion, I'll also see if I can break at the call to `available()` when time permits.

**Comment by rbrako-nlsn** [comment]
Just to close out, we didn't solve the root cause, though we're able to go with `getBlobOutputStream` for a quick fix, and I have a custom client in progress which seems to be working ok for large workloads.
Thanks for your time and attention, I mentioned to our team that I appreciated your responsiveness.

**Comment by rickle-msft** [comment]
Thank you for the update. I am glad you guys have found a work around. I am still going to leave this open for now as I think my team should circle back and make another attempt to repro since high volume scenarios are important to us. If we still are unable to repro, we may close the issue from there.

**Comment by gapra-msft** [comment]
It looks like this issue has been resolved. If you hit another issue, please feel free to open another issue, and we'd be happy to help!

**Comment by arti-shinde** [comment]
Hi, 
I am facing this same error "com.azure.core.exception.UnexpectedLengthException: Request body emitted 67 bytes, more than the expected 66 bytes" using the 12.10.2 version azure-storage-blob. I am reading from S3 and writing to blob using the BlockBlobClient.stageBlock APIs. Could you please let me know how do I go about resolving this issue?
Thanks,
Arti

**Comment by rickle-msft** [comment]
@arti-shinde What is the size of your data as reported by s3?

I'll also recommend you upgrade to latest (12.14)
