### ISSUE TITLE
[BUG] conditional upsert fails via CosmosSyncContainer

### ISSUE THREAD

**Issue by akalfas** [Azure/azure-sdk-for-java#6838]
**Describe the bug**

I'm using the sync sdk from v 3.3.3 - and I would like to use some sort of a optimistic locking via the `AccessCondition` construct.

While doing so, I've got back a conflict error and digging in the code I've noticed  - https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/cosmos/microsoft-azure-cosmos/src/main/java/com/azure/data/cosmos/sync/CosmosSyncContainer.java#L189

I can work around the issue via the async sdk, but would like to know if it's a bug or just a intended behaviour. 

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by kushagraThapar** [comment]
@akalfas Can you please provide the stack trace for the conflict ?
I am not sure what you meant by code fragment link, can you please elaborate on that ?

**Comment by akalfas** [comment]
@kushagraThapar  Here is a code snippet that can be used to reproduce the issue that I've described:

```
    ConnectionPolicy connectionPolicy = new ConnectionPolicy()
        .connectionMode(ConnectionMode.GATEWAY);

    CosmosSyncClient client = CosmosClient.builder()
        .endpoint("REDACTED")
        .key("REDACTED")
        .connectionPolicy(connectionPolicy)
        .consistencyLevel(ConsistencyLevel.SESSION)
        .buildSyncClient();

    CosmosSyncDatabaseResponse dbResponse = client.createDatabaseIfNotExists("test-db");

    CosmosSyncDatabase database = dbResponse.database();

    CosmosSyncContainerResponse containerResponse = database
        .createContainerIfNotExists("test-coll", "/pk");

    CosmosSyncContainer container = containerResponse.container();

    String id = UUID.randomUUID().toString();

    ObjectMapper mapper = new ObjectMapper();

    ObjectNode item = mapper.createObjectNode();
    item.put("id", id);
    item.put("pk", id);
    item.put("attr", "before");

    CosmosSyncItemResponse itemResponse = container.upsertItem(item);

    String etag = itemResponse.properties().etag();

    CosmosItemRequestOptions option = new CosmosItemRequestOptions();

    AccessCondition condition = new AccessCondition()
        .type(AccessConditionType.IF_MATCH)
        .condition(etag);
    option.accessCondition(condition);

    item.put("attr", "after");

    // this will fail because
    // containerWrapper.createItem(item, options) is called inside instead of
    // containerWrapper.upsertItem(item, options)
    CosmosSyncItemResponse updatedResponse = container.upsertItem(item, option);

    System.out.println(updatedResponse.properties());

```

And the stack trace that I'm getting is:

```
Exception in thread "main" CosmosClientException{error={"code":"Conflict","message":"Entity with the specified id already exists in the system., \r\nRequestStartTime: 2020-01-22T07:55:00.0256765Z, RequestEndTime: 2020-01-22T07:55:00.0455957Z,  Number of regions attempted:1\r\nResponseTime: 2020-01-22T07:55:00.0455957Z, StoreResult: StorePhysicalAddress: REDACTED, LSN: 5, GlobalCommittedLsn: 5, PartitionKeyRangeId: 0, IsValid: True, StatusCode: 409, SubStatusCode: 0, RequestCharge: 1.24, ItemLSN: -1, SessionToken: -1#5, UsingLocalLSN: False, TransportException: null, ResourceType: Document, OperationType: Create\r\n, Microsoft.Azure.Documents.Common/2.7.0, StatusCode: Conflict","additionalErrorInfo":null}, resourceAddress='null', statusCode=409, message=Entity with the specified id already exists in the system., 
REDACTED
	at com.azure.data.cosmos.BridgeInternal.createCosmosClientException(BridgeInternal.java:350)
	at com.azure.data.cosmos.internal.RxGatewayStoreModel.validateOrThrow(RxGatewayStoreModel.java:331)
	at com.azure.data.cosmos.internal.RxGatewayStoreModel.lambda$null$0(RxGatewayStoreModel.java:268)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:378)
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:67)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:123)
	at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:112)
	at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:213)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:123)
	at reactor.core.publisher.FluxFilterFuseable$FilterFuseableConditionalSubscriber.onNext(FluxFilterFuseable.java:330)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1592)
	at reactor.core.publisher.MonoReduceSeed$ReduceSeedSubscriber.onComplete(MonoReduceSeed.java:156)
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:136)
	at reactor.netty.channel.FluxReceive.terminateReceiver(FluxReceive.java:397)
	at reactor.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:197)
	at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:345)
	at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:363)
	at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:412)
	at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:556)
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:91)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:328)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:302)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1475)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1224)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1271)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:505)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:444)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:283)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by kushagraThapar** [comment]
@akalfas thanks for the code snippet, I will look into this soon.

**Comment by kushagraThapar** [comment]
@akalfas We confirmed it was a bug, fixed in the above PR.

**Comment by kushagraThapar** [comment]
@akalfas The bug has been fixed in the master branch, will be released whenever the next release goes out, probably by end of next week.

**Comment by lilyjma** [comment]
Closing the issue as the bug has been fixed. Please reopen if necessary.
