### ISSUE TITLE
readmywrites workflow on Direct HTTPS has failures because of reactor netty NotYetConnectedException

### ISSUE THREAD

**Issue by mbhaskar** [Azure/azure-sdk-for-java#6955]
ERROR com.azure.cosmos.implementation.query.DocumentProducer - Unexpected failure
CosmosClientException{error=null, resourceAddress='null', statusCode=0, message=null, causeInfo=[class: class java.nio.channels.NotYetConnectedException, message: null], responseHeaders={}, requestHeaders={authorization=type%3Dmaster%26ver%3D1.0%26sig%3DZk%2BRtwqDdCvHdWB7tTLpGCyKwstITXzHpHQcq2uJ6mQ%3D, Accept=application/json, x-ms-session-token=0:-1#50102,1:-1#71225,2:-1#71251, x-ms-date=Wed, 18 Dec 2019 22:12:20 GMT, x-ms-documentdb-isquery=true, x-ms-documentdb-partitionkey=["756fdf90-21e3-11ea-8e94-fd4d274e06f7"], x-ms-max-item-count=100, x-ms-continuation=null, x-ms-consistency-level=Session, Content-Type=application/query+json}}
	at com.azure.cosmos.BridgeInternal.createCosmosClientException(BridgeInternal.java:345)
	at com.azure.cosmos.implementation.RxGatewayStoreModel.lambda$toDocumentServiceResponse$2(RxGatewayStoreModel.java:307)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:88)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onError(FluxMapFuseable.java:134)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:165)
	at reactor.core.publisher.MonoSingle$SingleSubscriber.onError(MonoSingle.java:141)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onError(MonoFlatMapMany.java:197)
	at reactor.core.publisher.FluxRetryPredicate$RetryPredicateSubscriber.onError(FluxRetryPredicate.java:101)
	at reactor.core.publisher.MonoCreate$DefaultMonoSink.error(MonoCreate.java:183)
	at reactor.netty.http.client.HttpClientConnect$MonoHttpConnect$TcpClientSubscriber.onError(HttpClientConnect.java:345)
	at reactor.core.publisher.MonoCreate$DefaultMonoSink.error(MonoCreate.java:183)
	at reactor.netty.resources.PooledConnectionProvider$DisposableAcquire.onUncaughtException(PooledConnectionProvider.java:516)
	at reactor.netty.resources.PooledConnectionProvider$DisposableAcquire.run(PooledConnectionProvider.java:543)
	at reactor.netty.resources.PooledConnectionProvider$DisposableAcquire.onNext(PooledConnectionProvider.java:477)
	at reactor.netty.resources.PooledConnectionProvider$DisposableAcquire.onNext(PooledConnectionProvider.java:443)
	at reactor.netty.internal.shaded.reactor.pool.AbstractPool$Borrower.deliver(AbstractPool.java:370)
	at reactor.netty.internal.shaded.reactor.pool.SimplePool.lambda$drainLoop$6(SimplePool.java:198)
	at reactor.core.publisher.LambdaMonoSubscriber.onNext(LambdaMonoSubscriber.java:168)
	at reactor.core.publisher.MonoCreate$DefaultMonoSink.success(MonoCreate.java:156)
	at reactor.netty.resources.PooledConnectionProvider$PooledConnectionAllocator$PooledConnectionInitializer.operationComplete(PooledConnectionProvider.java:301)
	at reactor.netty.resources.PooledConnectionProvider$PooledConnectionAllocator$PooledConnectionInitializer.operationComplete(PooledConnectionProvider.java:254)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:604)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.fulfillConnectPromise(AbstractEpollChannel.java:610)
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:648)
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:524)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:414)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:326)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.nio.channels.NotYetConnectedException
	at io.netty.channel.unix.Errors.ioResult(Errors.java:171)
	at io.netty.channel.unix.FileDescriptor.readAddress(FileDescriptor.java:143)
	at io.netty.channel.epoll.AbstractEpollChannel.doReadBytes(AbstractEpollChannel.java:343)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:780)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:424)
	... 5 more
[reactor-http-epoll-2] ERROR com.azure.cosmos.benchmark.ReadMyWriteWorkflow - Encountered failure null on thread reactor-http-epoll-2
CosmosClientException{error=null, resourceAddress='null', statusCode=0, message=null, causeInfo=[class: class java.nio.channels.NotYetConnectedException, message: null], responseHeaders={}, requestHeaders={authorization=type%3Dmaster%26ver%3D1.0%26sig%3DRy67407JV4hwa5qiJgdE132cfFvhsbohOZ3g0Xd%2FPE8%3D, Accept=application/json, x-ms-session-token=0:-1#50102,1:-1#88455,2:-1#88740,3:-1#106218,4:-1#106440,5:-1#106727,6:-1#106626,7:-1#110601,8:-1#110530,9:-1#110124,10:-1#109966,11:-1#110519,12:-1#110627,13:-1#110454,14:-1#110245, x-ms-date=Wed, 18 Dec 2019 22:42:06 GMT, x-ms-documentdb-isquery=true, x-ms-documentdb-partitionkey=["9e52cd20-21e7-11ea-8e94-fd4d274e06f7"], x-ms-max-item-count=100, x-ms-continuation=null, x-ms-consistency-level=Session, Content-Type=application/query+json}}
	at com.azure.cosmos.BridgeInternal.createCosmosClientException(BridgeInternal.java:345)
	at com.azure.cosmos.implementation.RxGatewayStoreModel.lambda$toDocumentServiceResponse$2(RxGatewayStoreModel.java:307)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:88)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onError(FluxMapFuseable.java:134)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:165)
	at reactor.core.publisher.MonoSingle$SingleSubscriber.onError(MonoSingle.java:141)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onError(MonoFlatMapMany.java:197)
	at reactor.core.publisher.FluxRetryPredicate$RetryPredicateSubscriber.onError(FluxRetryPredicate.java:101)
	at reactor.core.publisher.MonoCreate$DefaultMonoSink.error(MonoCreate.java:183)
	at reactor.netty.http.client.HttpClientConnect$MonoHttpConnect$TcpClientSubscriber.onError(HttpClientConnect.java:345)
	at reactor.core.publisher.MonoCreate$DefaultMonoSink.error(MonoCreate.java:183)
	at reactor.netty.resources.PooledConnectionProvider$DisposableAcquire.onUncaughtException(PooledConnectionProvider.java:516)
	at reactor.netty.resources.PooledConnectionProvider$DisposableAcquire.run(PooledConnectionProvider.java:543)
	at reactor.netty.resources.PooledConnectionProvider$DisposableAcquire.onNext(PooledConnectionProvider.java:477)
	at reactor.netty.resources.PooledConnectionProvider$DisposableAcquire.onNext(PooledConnectionProvider.java:443)
	at reactor.netty.internal.shaded.reactor.pool.AbstractPool$Borrower.deliver(AbstractPool.java:370)
	at reactor.netty.internal.shaded.reactor.pool.SimplePool.lambda$drainLoop$6(SimplePool.java:198)
	at reactor.core.publisher.LambdaMonoSubscriber.onNext(LambdaMonoSubscriber.java:168)
	at reactor.core.publisher.MonoCreate$DefaultMonoSink.success(MonoCreate.java:156)
	at reactor.netty.resources.PooledConnectionProvider$PooledConnectionAllocator$PooledConnectionInitializer.operationComplete(PooledConnectionProvider.java:301)
	at reactor.netty.resources.PooledConnectionProvider$PooledConnectionAllocator$PooledConnectionInitializer.operationComplete(PooledConnectionProvider.java:254)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:604)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.fulfillConnectPromise(AbstractEpollChannel.java:610)
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:648)
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:524)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:414)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:326)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.nio.channels.NotYetConnectedException
	at io.netty.channel.unix.Errors.ioResult(Errors.java:171)
	at io.netty.channel.unix.FileDescriptor.readAddress(FileDescriptor.java:143)
	at io.netty.channel.epoll.AbstractEpollChannel.doReadBytes(AbstractEpollChannel.java:343)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:780)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:424)
	... 5 more
2019-12-18 22:42:06,777       [reactor-http-epoll-2] WARN  reactor.netty.http.client.HttpClientConnect - [id: 0xd0adf6f8, L:/10.0.7.4:49716 - R:hamallap-readmywritestest-westus2.documents.azure.com/13.66.138.4:443] The connection observed an error
java.nio.channels.NotYetConnectedException
	at io.netty.channel.unix.Errors.ioResult(Errors.java:171)
	at io.netty.channel.unix.FileDescriptor.readAddress(FileDescriptor.java:143)
	at io.netty.channel.epoll.AbstractEpollChannel.doReadBytes(AbstractEpollChannel.java:343)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:780)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:424)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:326)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

**Comment by kushagraThapar** [comment]
Update: 
This test was failing for some different issue. 
NotYetConnectedException is still an issue which can be tracked in a separate item: https://github.com/Azure/azure-sdk-for-java/issues/7348
SSLEngine closed already is also another issue which needs to be fixed and can be tracked here: https://github.com/Azure/azure-sdk-for-java/issues/7349

**Comment by kushagraThapar** [comment]
Closing this issue as this has been fixed in all SDK versions.
