### ISSUE TITLE
com.azure.data.cosmos.internal.BaseAuthorizationTokenProvider : java.lang.CloneNotSupportedException: null 

### ISSUE THREAD

**Issue by Bertrand-m** [Azure/azure-sdk-for-java#7230]
**Description of the bug**
Hello all, A am trying to connect to Azure cosmos db by using the java sdk 3.5.0.
However, I have got an error on the internal java services that I can't solve.

Please find below the stacktrace:
java.lang.CloneNotSupportedException: null
at javax.crypto.MacSpi.clone(MacSpi.java:150)
at javax.crypto.Mac.clone(Mac.java:669)
at com.azure.data.cosmos.internal.BaseAuthorizationTokenProvider.getMacInstance(BaseAuthorizationTokenProvider.java:265)
at com.azure.data.cosmos.internal.BaseAuthorizationTokenProvider.generateKeyAuthorizationSignatureNew(BaseAuthorizationTokenProvider.java:238)
at com.azure.data.cosmos.internal.BaseAuthorizationTokenProvider.generateKeyAuthorizationSignature(BaseAuthorizationTokenProvider.java:212)
at com.azure.data.cosmos.internal.directconnectivity.GatewayServiceConfigurationReader.getDatabaseAccountAsync(GatewayServiceConfigurationReader.java:123)
at com.azure.data.cosmos.internal.directconnectivity.GatewayServiceConfigurationReader.lambda$initializeReaderAsync$0(GatewayServiceConfigurationReader.java:138)
at com.azure.data.cosmos.internal.GlobalEndpointManager.getDatabaseAccountFromAnyLocationsAsync(GlobalEndpointManager.java:93)
at com.azure.data.cosmos.internal.directconnectivity.GatewayServiceConfigurationReader.initializeReaderAsync(GatewayServiceConfigurationReader.java:134)
at com.azure.data.cosmos.internal.RxDocumentClientImpl.initializeGatewayConfigurationReader(RxDocumentClientImpl.java:246)
at com.azure.data.cosmos.internal.RxDocumentClientImpl.init(RxDocumentClientImpl.java:265)
at com.azure.data.cosmos.internal.AsyncDocumentClient$Builder.build(AsyncDocumentClient.java:185)
at com.azure.data.cosmos.CosmosClient.(CosmosClient.java:54)
at com.azure.data.cosmos.CosmosClientBuilder.build(CosmosClientBuilder.java:203)

The key used for the connections are correct and I don't know why there is this null issue.

**To Reproduce**
here is the content of the java class used for initate the connection:

		ConnectionPolicy policy = new ConnectionPolicy();
		policy.connectionMode(ConnectionMode.DIRECT);
		policy.maxPoolSize(400);
	    RetryOptions retryOptions = new RetryOptions();
	    retryOptions.maxRetryAttemptsOnThrottledRequests(6);
	    retryOptions.maxRetryWaitTimeInSeconds(30);
	    policy.retryOptions(retryOptions);
	    
	    CosmosClientBuilder cosmosClientBuilder = CosmosClient.builder();
	    CosmosClientBuilder cosmosClientBuilderReadOnly = CosmosClient.builder();
	
	    cosmosClientBuilder.endpoint(databaseUrl)
	    		.key(databasePassword)
	    		.connectionPolicy(policy)
	    		.consistencyLevel(ConsistencyLevel.SESSION)
	            .build();
	
	    cosmosClientBuilderReadOnly.endpoint(databaseUrl)
	            .key(databasePasswordReadOnly)
	            .connectionPolicy(policy)
	            .consistencyLevel(ConsistencyLevel.SESSION)
	            .build();
	    
	    
	    cosmosClient = cosmosClientBuilder.build();
	    cosmosClientReadOnly = cosmosClientBuilderReadOnly.build();
	    cosmosSyncClientReadOnly = cosmosClientBuilderReadOnly.buildSyncClient();
**Expected behavior**
It supposes to connect :)

**Actual behavior**
On calling my connect service described upper, I get an error with null

**Environment summary**
SDK Version: java SDK 3.5.0
Java JDK version: 1.8.0
OS Version (e.g. Windows, Linux, MacOSX) windows NT 6.2

If anyOne can help me
**regards**

**Comment by FredGao-new** [comment]
@Bertrand-m 
Tried to run the same code provided and set the environment as required on in the issue but cannot reproduce bug, can use the client to do other operations successfully(e.g. getDatabase). Below is the code :
```
        ConnectionPolicy policy = new ConnectionPolicy();
        policy.connectionMode(ConnectionMode.DIRECT);
        policy.maxPoolSize(400);
        RetryOptions retryOptions = new RetryOptions();
        retryOptions.maxRetryAttemptsOnThrottledRequests(6);
        retryOptions.maxRetryWaitTimeInSeconds(30);
        policy.retryOptions(retryOptions);
        
        CosmosClientBuilder cosmosClientBuilder = CosmosClient.builder();
        CosmosClientBuilder cosmosClientBuilderReadOnly = CosmosClient.builder();
        cosmosClientBuilder.endpoint(databaseurl)
                .key(databasePassword)
                .connectionPolicy(policy)
                .consistencyLevel(ConsistencyLevel.SESSION)
                .build();
        cosmosClientBuilderReadOnly.endpoint(databaseUrl)
                .key(databasePassword)
                .connectionPolicy(policy)
                .consistencyLevel(ConsistencyLevel.SESSION)
                .build();
 
        CosmosClient cosmosClient = cosmosClientBuilder.build();
        CosmosClient cosmosClientReadOnly = cosmosClientBuilderReadOnly.build();
        CosmosSyncClient cosmosSyncClientReadOnly = cosmosClientBuilderReadOnly.buildSyncClient();
        cosmosClient.createDatabase("test");
          if( "test"==cosmosClientReadOnly.getDatabase("test").id() && "test"==cosmosSyncClientReadOnly.getDatabase("test").id()){
            System.out.println("Successfully connected Azure cosmosdb by cosmosClient, cosmosSyncClient");
        }
```
Output:

Dependencies I used in pom.xml:
    <dependency>
      <groupId>com.microsoft.azure</groupId>
      <artifactId>azure-cosmos</artifactId>
      <version>3.5.0</version>
    </dependency>

Java JDK version: 1.8.0

Did I miss anything?

**Comment by FredGao-new** [comment]
@jongio

**Comment by Bertrand-m** [comment]
Hello @jongio,

I still don't know what was wrong. Indeed the code seems legit.
A colleague tried the same and it worked fine.
I have retried from the beginning and it works now.

maybe the issue concerned my jar files with a conflict of version.

I close the issue
