### ISSUE TITLE
NotYetConnectedException in reactor-netty http client

### ISSUE THREAD

**Issue by kushagraThapar** [Azure/azure-sdk-for-java#7348]
**Describe the bug**
NotYetConnectedException gets thrown when running ReadMyWritesConsistencyTests with Https Strong mode. 

***Exception or Stack Trace***
java.nio.channels.NotYetConnectedException
        at io.netty.channel.unix.Errors.ioResult(Errors.java:171)
        at io.netty.channel.unix.FileDescriptor.readAddress(FileDescriptor.java:143)
        at io.netty.channel.epoll.AbstractEpollChannel.doReadBytes(AbstractEpollChannel.java:343)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:780)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:424)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:326)
        at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

**Comment by kushagraThapar** [comment]
Looks like this issue might be related to the SSLException issue : https://github.com/Azure/azure-sdk-for-java/issues/7349

**Comment by kushagraThapar** [comment]
This is fixed, closing it.
