### ISSUE TITLE
[BUG] Integration azure-security-keyvault-secrets and azure-identity

### ISSUE THREAD

**Issue by igorky** [Azure/azure-sdk-for-java#7481]
**Describe the bug**
Looks like authentication has failed in my case. I am using service principal for that.

***Exception or Stack Trace***
WARN 93559 --- [nPool-worker-19] c.m.a.m.ConfidentialClientApplication    : [Correlation ID: 44e7f100-26c1-49da-af30-2929aaf1795c] Setting URL telemetry fields failed: java.net.URISyntaxException
	at java.base/java.net.URI$Parser.fail(URI.java:2936)
	at java.base/java.net.URI$Parser.checkChars(URI.java:3107)
	at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3189)
	at java.base/java.net.URI$Parser.parse(URI.java:3137)
	at java.base/java.net.URI.<init>(URI.java:623)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.initializeApiEvent(AuthenticationResultSupplier.java:139)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:48)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:17)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run$$$capture(CompletableFuture.java:1771)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1763)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
2020-01-15 13:34:22.515 ERROR 93559 --- [nPool-worker-19] c.m.a.m.ConfidentialClientApplication    : [Correlation ID: 44e7f100-26c1-49da-af30-2929aaf1795c] Execution of class com.microsoft.aad.msal4j.AcquireTokenByAuthorizationGrantSupplier failed.

java.net.URISyntaxException: Illegal character in query at index 169: https://login.microsoftonline.com/common/discovery/instance?api-version=1.1&authorization_endpoint=https://login.microsoftonline.com/8331e14a-9134-4288-bf5a-5e2c8412f074	/oauth2/v2.0/authorize
	at java.base/java.net.URI$Parser.fail(URI.java:2936) ~[na:na]
	at java.base/java.net.URI$Parser.checkChars(URI.java:3107) ~[na:na]
	at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3195) ~[na:na]
	at java.base/java.net.URI$Parser.parse(URI.java:3137) ~[na:na]
	at java.base/java.net.URI.<init>(URI.java:623) ~[na:na]
	at java.base/java.net.URL.toURI(URL.java:1048) ~[na:na]
	at com.microsoft.aad.msal4j.HttpHelper.executeHttpRequest(HttpHelper.java:37) ~[msal4j-0.5.0-preview.jar:0.5.0-preview]
	at com.microsoft.aad.msal4j.AadInstanceDiscovery.sendInstanceDiscoveryRequest(AadInstanceDiscovery.java:62) ~[msal4j-0.5.0-preview.jar:0.5.0-preview]
	at com.microsoft.aad.msal4j.AadInstanceDiscovery.doInstanceDiscoveryAndCache(AadInstanceDiscovery.java:78) ~[msal4j-0.5.0-preview.jar:0.5.0-preview]
	at com.microsoft.aad.msal4j.AadInstanceDiscovery.GetMetadataEntry(AadInstanceDiscovery.java:93) ~[msal4j-0.5.0-preview.jar:0.5.0-preview]
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.getAuthorityWithPrefNetworkHost(AuthenticationResultSupplier.java:33) ~[msal4j-0.5.0-preview.jar:0.5.0-preview]
	at com.microsoft.aad.msal4j.AcquireTokenByAuthorizationGrantSupplier.execute(AcquireTokenByAuthorizationGrantSupplier.java:49) ~[msal4j-0.5.0-preview.jar:0.5.0-preview]
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:57) ~[msal4j-0.5.0-preview.jar:0.5.0-preview]
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:17) ~[msal4j-0.5.0-preview.jar:0.5.0-preview]
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run$$$capture(CompletableFuture.java:1771) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1763) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177) ~[na:na]

**To Reproduce**

Create a KeyVault client:
new SecretClientBuilder()
                .vaultUrl("https://kvname_here.vault.azure.net/")
                .credential(new EnvironmentCredentialBuilder().build())
                .buildClient();

Call the com.azure.security.keyvault.secrets.SecretClient#getSecret(java.lang.String) method.

Use the following dependencies

        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-security-keyvault-secrets</artifactId>
            <version>4.1.0</version>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-identity</artifactId>
            <version>1.0.3</version>
        </dependency>

***Code Snippet***
new SecretClientBuilder()
                .vaultUrl("https://kvname_here.vault.azure.net/")
                .credential(new EnvironmentCredentialBuilder().build())
                .buildClient()
.getSecret("test");

**Expected behavior**
No exception should happen.

**Setup (please complete the following information):**
 - OS: Macos 10.14.6
 - IDE : IntelliJ
 - Version of the Library used: azure-security-keyvault-secrets:4.1.0 and azure-identity:1.0.3

**Comment by igorky** [comment]
The problem was with env AZURE_TENANT_ID. It had a tab character at the end (\t).
