### ISSUE TITLE
Make jackson-databinding-xml dependency optional

### ISSUE THREAD

**Issue by blacelle** [Azure/azure-sdk-for-java#7694]
We recently upgraded Azure-spring-boot-starter from 2.2.1 to 2.2.2

It led to various issues because this bugfix upgrade induced the drop of azure-keyvault dependency to azure-security-keyvault-secrets, which depends on azure-core, which depends on jackson-databinding-xml.

This led to various dubious side-effects like Spring RestTemplate switching from JaxB MessageSerializer to JacksonXml (see the static initializer in RestTemplate), which induces XML as default protocol (over json) when POSTing a Map with a RestTemplate, without specifing any Content-Type, which naturally led the many things not working anymore in our app.

However, exlcuding spring-databinding-xml from our dependencies prevent JacksonAdapter class to be initialized, while the XmlAdapter seems not to be strictly necessary.

Would it be reasonnable to make JacksonAdapter dependency over XmlAdapter an option, just like RestTemplate uses XmlAdapter only if it is available?

Thanks

**Comment by joshfree** [comment]
Thanks for reporting this issue @blacelle.  @hemanttanwar can you please follow up?

**Comment by blacelle** [comment]
@joshfree @hemanttanwar Have you been able to dig into this? Thanks

**Comment by chenrujun** [comment]
Now [azure-core](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/core/azure-core/pom.xml) does not have dependency of `jackson-databinding-xml`, does it mean this problem have been solved?

**Comment by amusaafir** [comment]
@chenrujun Can this be updated in dependencies like azure-identity (that make use of azure-core)? We'd like to _not_ make use of the xml dependency too as it changes our Controller's default JSON response type to XML. 
Can we simply exclude it from azure-identity without any problem?

**Comment by chenrujun** [comment]
@amusaafir ,

>  Can this be updated in dependencies like azure-identity 

Now [azure-identity](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/identity/azure-identity/pom.xml) does not have dependency of jackson-databinding-xml.

**Comment by amusaafir** [comment]
@chenjianfei2017 Thanks for the quick reply. My bad, I meant jackson-dataformat-xml which is included by azure-core, and which is subsequently used by azure-identity. (I think it's better if I open a new issue regarding this, as it is a different dependency than the one mentioned in this issue, )

**Comment by chenrujun** [comment]
@amusaafir ,

Thank you for your quick response.

Can you use [exclusions](https://maven.apache.org/guides/introduction/introduction-to-optional-and-excludes-dependencies.html) in you pom to exclude that dependency?

**Comment by amusaafir** [comment]
@chenrujun That does make it work indeed - would it have any unexpected side effects?

Thank you :)

**Comment by chenrujun** [comment]
> would it have any unexpected side effects?

I'm not sure. I'm the developer about spring-starter. I'm not very familiar with azure-core.

@alzimmermsft , I see you committed in azure-cure, could you please check this issue?

**Comment by amusaafir** [comment]
@alzimmermsft , it appears that excluding jackson-dataformat-xml from azure-identity breaks my current application. Ideally, this would be an optional dependency as it now overrides the default JSON response returned from all our Spring controllers to an XML response (and it can't be overridden in a somewhat clean manner).

**Comment by alzimmermsft** [comment]
Hi @chenrujun,

Currently, `azure-core` is required to have `jackson-databind-xml` as it handles serialization work for most other Azure SDKs which build on top of it. Given that some services use XML it is required to have this dependency.

In an upcoming change I'm looking into decentralizing serialization handling to allow down stream SDKs more flexibility. While doing this I can look at whether it would be possible to remove this dependency without it being backwards compatibility breaking.

**Comment by jongio** [comment]
@alzimmermsft - Do you have an update? This one is 207 days old, so we'd like to close out soon.  Thanks, Jon

**Comment by alzimmermsft** [comment]
From reviewing how `XmlMapper` is leveraged in Azure Core it won't be possible to remove it without leading to functional breaking changes for backwards compatibility.  However, it should be possible to shade and relocate the `jackson-dataformat-xml` dependency so that `RestTemplate` no longer picks it up on the classpath.

**Comment by thebenwaters** [comment]
I think I'm having related issues #15486

**Comment by blacelle** [comment]
@alzimmermsft Have you validated the shade+relocate option?

**Comment by alzimmermsft** [comment]
I attempted to validate @blacelle and I see the issue is that since the Jackson XML dependency is a dependency's dependency (application -> azure-core -> Jackson XML) it is not possible to resolve the issue through shading. Through additional research I see that `RestTemplate` uses well-known `HttpMessageConverter`s when checking the class path for automatic converters. Replacing the Jackson XML (`MappingJackson2XmlHttpMessageConverter`) `HttpMessageConverter` with the JAXB (`Jaxb2RootElementHttpMessageConverter`) `HttpMessageConverter` using `RestTemplate`'s get and set converter APIs should resolve the issue. If Spring also offers a way to pre-configure all `RestTemplate` instances that should simplify the fix further.

**Comment by carlosmgiraldo90** [comment]
Hi @alzimmermsft addressing your proposal I implemented a custom `MessageConverters ` inside a `WebMvcConfigurer` by using only `MappingJackson2HttpMessageConverter` and `Jaxb2RootElementHttpMessageConverter`. As a result, the default protocol (JSON) for web services through `RestController` is not affected and the integration with the Azure SDK (in my case blob storage) is working fine.

**Comment by duynk3** [comment]
Hi do we have any way to ignore com.fasterxml.jackson.dataformat.xml.XmlMapper or make it no impact to Spring RestTemplate?

**Comment by yangzii0920** [comment]
> Hi do we have any way to ignore com.fasterxml.jackson.dataformat.xml.XmlMapper or make it no impact to Spring RestTemplate?

Excluding the jackson xml module worked for me:
```
implementation('com.microsoft.azure:azure-active-directory-spring-boot-starter:2.3.2') {
    exclude group: 'com.fasterxml.jackson.dataformat', module: 'jackson-dataformat-xml'
}
```

**Comment by duynk3** [comment]
Hi @yangzii0920  i thought about it but 
com.azure.core.util.serializer.JacksonAdapter depend on jackson xml.
i'm using Azure core 1.3.0

**Comment by pennstatephil** [comment]
> > Hi do we have any way to ignore com.fasterxml.jackson.dataformat.xml.XmlMapper or make it no impact to Spring RestTemplate?
> 
> Excluding the jackson xml module worked for me:
> 
> ```
> implementation('com.microsoft.azure:azure-active-directory-spring-boot-starter:2.3.2') {
>     exclude group: 'com.fasterxml.jackson.dataformat', module: 'jackson-dataformat-xml'
> }
> ```

Thank you SO MUCH for this @yangzii0920 -- I have been fighting with getting this to work with Spring for a good while, and this was exactly the solution. Until this is implemented, would there be some sort of official FAQ or Spring guide that this can be added to?

**Comment by pennstatephil** [comment]
Well, I thought excluding the XML mapper would be the answer, but now I get this error when I try to use the client:
```
Caused by: java.lang.NoClassDefFoundError: com/fasterxml/jackson/dataformat/xml/XmlMapper$Builder
	at com.azure.storage.blob.implementation.util.ModelHelper.<clinit>(ModelHelper.java:53)
	at com.azure.storage.blob.BlobUrlParts.parse(BlobUrlParts.java:371)
	at com.azure.storage.blob.BlobServiceClientBuilder.endpoint(BlobServiceClientBuilder.java:147)
	at com.azure.storage.blob.BlobServiceClientBuilder.connectionString(BlobServiceClientBuilder.java:286)
	at util.AzureUtil.blobClient(AzureUtil.java:47)
	at util.AzureUtil.getSecureReadParams(AzureUtil.java:24)
	at util.AzureUtil.getFullSecuredURL(AzureUtil.java:35)
	at RestServer.fabric.FilesFabric.getPresignedGetUrl(FilesFabric.java:37)
	at RestServer.controllers.api.FilesController.getSecureFileUrl(FilesController.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:141)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:894)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1063)
	... 96 more
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.dataformat.xml.XmlMapper$Builder
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 116 more
```
Maven block:
```
        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-storage-blob</artifactId>
            <version>12.14.0</version>
            <exclusions>
                <exclusion>
                    <groupId>com.fasterxml.jackson.dataformat</groupId>
                    <artifactId>jackson-dataformat-xml</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```
So, this is really bad. If I don't exclude the dependency, everything in my app defaults to XML; but if I do exclude it, I can't use the client. Does anyone have a suggestion on how to resolve this?

**Comment by alzimmermsft** [comment]
Hey @pennstatephil, we can take a look at this again. Right now, this is a rock and a hard place problem as Storage heavily uses XML, requiring it to have the `XmlMapper` available.

I see that [RestTemplate](https://github.com/spring-projects/spring-framework/blob/main/spring-web/src/main/java/org/springframework/web/client/RestTemplate.java#L101) now appears to have a flag to disable XML support. I don't know if the is a possible solution for you if you need to leverage XML.

Looking forward we're investigating ways to further remove dependencies on Jackson libraries as they're commonly a source of dependency conflicts.

cc: @lmolkova

**Comment by sandeep859** [comment]
> Hey @pennstatephil, we can take a look at this again. Right now, this is a rock and a hard place problem as Storage heavily uses XML, requiring it to have the `XmlMapper` available.
> 
> I see that [RestTemplate](https://github.com/spring-projects/spring-framework/blob/main/spring-web/src/main/java/org/springframework/web/client/RestTemplate.java#L101) now appears to have a flag to disable XML support. I don't know if the is a possible solution for you if you need to leverage XML.
> 
> Looking forward we're investigating ways to further remove dependencies on Jackson libraries as they're commonly a source of dependency conflicts.
> 
> cc: @lmolkova

@alzimmermsft You suggested seems to have worked for us. We created  file with name spring.properties and added to the classpath and added this property: spring.xml.ignore=true

**Comment by blacelle** [comment]
> Now [azure-identity](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/identity/azure-identity/pom.xml) does not have dependency of jackson-databinding-xml.

@chenrujun Given azure-identity with no XML dependency in still in beta. Any plan for a proper release? Also, https://mvnrepository.com/artifact/com.azure/azure-core/1.32.0 is still relying on [jackson-dataformat-xml](https://mvnrepository.com/artifact/com.fasterxml.jackson.dataformat/jackson-dataformat-xml)

**Comment by alzimmermsft** [comment]
Hi @blacelle, there was [this recent change](https://github.com/Azure/azure-sdk-for-java/pull/30663) which made it so the usage of Jackson XML Databind is separated out into its own file and the usage of it is deferred until needed. So in the case you know you'll never need Jackson XML in JacksonAdapter it'll allow you to exclude the Jackson XML dependency. This will run into a crash if Jackson XML is eventually needed and doesn't remove Jackson XML everywhere, so I'm leaving this issue open.

There should be more changes around this in the next few months which should hopefully begin truly addressing this issue.

**Comment by blacelle** [comment]
Excellent. I got some feedback from SpringBoot indicating spring.xml.ignore=true is not a supported feature, and might/may/will be removed in the future (https://github.com/spring-projects/spring-boot/issues/32494).

**Comment by blacelle** [comment]
@alzimmermsft Can you confirm if there is a not-beta library with which we can exclude Jackson XML dependency?

**Comment by alzimmermsft** [comment]
@blacelle the PR I referenced hasn't been released yet, it should be released in `azure-core` some time around Oct 5th-8th with other Azure SDKs updating to that version of `azure-core` in the couple weeks after that.

That is a bit unfortunate to hear about `spring.xml.ignore` being unsupported. I wonder if Spring would be able to do something similar to [what we've done in this PR](https://github.com/Azure/azure-sdk-for-java/pull/30894) where we use a service provider which by default will use the first found implementation on the classpath but we also allow for configuration to select a specific instance. For example, in the issue you're facing you'd be able to configure Spring to explicitly use JaxB instead of their choice ordering which results in Jackson being used.

**Comment by alexander-svendsen** [comment]
I think this is out now: https://github.com/Azure/azure-sdk-for-java/pull/30663. Came in version 1.33.0 of azure-core

**Comment by alzimmermsft** [comment]
> I think this is out now: #30663. Came in version 1.33.0 of azure-core

While #30663 added a way to remove `jackson-dataformat-xml` from a build when XML parsing isn't needed I'll be leaving this issue opened until a more comprehensive removal of `jackson-dataformat-xml` from our POMs is done. For example, if you were using one of the Storage libraries, using XML serialization, you wouldn't be able to resolve this issue as `jackson-dataformat-xml` would be required.

**Comment by alzimmermsft** [comment]
Wanted to give an update on this issue, as of `azure-core` `1.37.0` `jackson-dataformat-xml` is no longer a dependency. Now, if an Azure SDKs requires XML serialization support it'll list `jackson-dataformat-xml` as a dependency and `azure-core` will reflectively bind everything it was previously using. This leaves the following SDKs with a dependency on `jackson-dataformat-xml`:

- `azure-data-tables`
- `azure-messaging-servicebus`
- All Azure Storage SDKs
