### ISSUE TITLE
[BUG] Unexpected header value: x-ms-client-request-id

### ISSUE THREAD

**Issue by rogelio-o** [Azure/azure-sdk-for-java#7940]
**Describe the bug**
With an async client, trying to download more than one file at the same time. The `DataLakeFileAsyncClient` clients are created (one for each downloaded file) from the same DataLakeFileSystemAsyncClient. The exception thrown said "Unexpected header value. Expected response to echo `x-ms-client-request-id: ...`. Got value `...`"

***Exception or Stack Trace***
```
Caused by: java.lang.RuntimeException: Unexpected header value. Expected response to echo `x-ms-client-request-id: a5cda32f-49cb-437a-a5c2-360d1fcf4545`. Got value `e8e1b114-4bd1-4381-96a7-3b9dfd0110e3`.
	at com.azure.storage.common.policy.ResponseValidationPolicyBuilder.lambda$addOptionalEcho$0(ResponseValidationPolicyBuilder.java:45)
	at com.azure.storage.common.policy.ResponseValidationPolicyBuilder$ResponseValidationPolicy.lambda$process$0(ResponseValidationPolicyBuilder.java:81)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:107)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:204)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1515)
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:241)
```

**To Reproduce**
Download more than one file at the same time without concurrency parameter set to one in the `flatMap`.

***Code Snippet***
```
final ListPathsOptions options = new ListPathsOptions();
options.setPath(directory);

return fileSystem.listPaths(options)
  .flatMap((item) -> downloadFile(directory, item, func))
  .then();
```

**Expected behavior**
Download both files without this exception.

**Screenshots**
...

**Setup (please complete the following information):**
 - OS: Windows 10
 - IDE : IntelliJ
 - Version of the Library used: 12.0.0-preview.6

**Additional context**
...

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by joshfree** [comment]
Thanks for reporting this issue in preview.6 @rogelio-o.  This may already be addressed in later releases such as beta.10 (https://mvnrepository.com/artifact/com.azure/azure-storage-file-datalake).

Assigning this to @rickle-msft and @gapra-msft who can help follow up.

**Comment by rickle-msft** [comment]
@rogelio-o I am pretty sure this was fixed in preview7 and later. Can you please try upgrading and let us know if this is still an issue?

**Comment by rogelio-o** [comment]
Yes, it works in the last beta!

Sorry, I didn’t check version dates on mavencentral, just pick the first row version.

Thanks!
