### ISSUE TITLE
Blob SDK class HttpPolicyProviders throws an exception with multiple concurrent uploads.

### ISSUE THREAD

**Issue by VIJAY-SUBRAMANIAM** [Azure/azure-sdk-for-java#8163]
Blob SDK class throws an exception with multiple concurrent uploads.  hashmap used by SDK concurrently modified by different threads

Exception stack trace

Caused by: java.util.ConcurrentModificationException
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1134)
	at com.azure.core.http.policy.HttpPolicyProviders.getPolicyProviders(HttpPolicyProviders.java:59)
	at com.azure.core.http.policy.HttpPolicyProviders.lambda$addAfterRetryPolicies$1(HttpPolicyProviders.java:39)
	at com.azure.core.http.policy.HttpPolicyProviders.addRetryPolicies(HttpPolicyProviders.java:44)
	at com.azure.core.http.policy.HttpPolicyProviders.addAfterRetryPolicies(HttpPolicyProviders.java:39)
	at com.azure.storage.blob.implementation.util.BuilderHelper.buildPipeline(BuilderHelper.java:95)
	at com.azure.storage.blob.BlobClientBuilder.buildAsyncClient(BlobClientBuilder.java:123)
	at com.azure.storage.blob.BlobClientBuilder.buildClient(BlobClientBuilder.java:93)
	at com.sonymusic.delivery.azure.client.AzureStorageClient.getBlobClient(AzureStorageClient.java:110)
	at com.sonymusic.delivery.azure.client.AzureStorageClient.uploadFile(AzureStorageClient.java:42

SDK V12.3.1

//My code to create a blob client
        return new BlobClientBuilder()
                .credential(credential)
                .endpoint(endPoint)
                .blobName(blobName)
                .buildClient();
                
                
//HttpPolicyProviders.java file. HashMap
private static final Map<Class<? extends HttpPolicyProvider>, ServiceLoader<? extends HttpPolicyProvider>>
        SERVICE_LOADERS = new HashMap<>();

ServiceLoader<? extends HttpPolicyProvider> serviceLoader = SERVICE_LOADERS
            .computeIfAbsent(cls, ServiceLoader::load);

**Comment by rickle-msft** [comment]
@VIJAY-SUBRAMANIAM thank you for reporting this. @alzimmermsft can you please take a look as the underlying problem seems to be in core?

**Comment by alzimmermsft** [comment]
Thank you for filing this issue @VIJAY-SUBRAMANIAM, we will look into the root cause and report our findings.
