### ISSUE TITLE
ClientSideRequestStatistics logger serialization issue

### ISSUE THREAD

**Issue by kushagraThapar** [Azure/azure-sdk-for-java#8281]
**Describe the bug**
Serialization error occurs when serializing ClientSideRequestStatistics

***Exception or Stack Trace***
Feb 18, 2020 5:10:36 PM com.fasterxml.jackson.module.afterburner.ser.OptimizedBeanPropertyWriter _reportProblem
WARNING: Disabling Afterburner serialization for class com.azure.cosmos.ClientSideRequestStatistics$StoreResponseStatistics (field #0; mutator com.fasterxml.jackson.module.afterburner.ser.ObjectFieldPropertyWriter), due to access error (type java.lang.IllegalAccessError, message=tried to access class com.azure.cosmos.ClientSideRequestStatistics$StoreResponseStatistics from class com.azure.cosmos.ClientSideRequestStatistics$StoreResponseStatistics$Access4JacksonSerializeraec329ec)

java.lang.IllegalAccessError: tried to access class com.azure.cosmos.ClientSideRequestStatistics$StoreResponseStatistics from class com.azure.cosmos.ClientSideRequestStatistics$StoreResponseStatistics$Access4JacksonSerializeraec329ec
	at com.azure.cosmos.ClientSideRequestStatistics$StoreResponseStatistics$Access4JacksonSerializeraec329ec.objectField(com/azure/cosmos/ClientSideRequestStatistics$StoreResponseStatistics$Access4JacksonSerializer.java)
	at com.fasterxml.jackson.module.afterburner.ser.ObjectFieldPropertyWriter.serializeAsField(ObjectFieldPropertyWriter.java:45)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:722)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:166)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:119)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:2795)
	at com.fasterxml.jackson.core.base.GeneratorBase.writeObject(GeneratorBase.java:388)
	at com.fasterxml.jackson.core.JsonGenerator.writeObjectField(JsonGenerator.java:1769)
	at com.azure.cosmos.ClientSideRequestStatistics$ClientSideRequestStatisticsSerializer.serialize(ClientSideRequestStatistics.java:280)
	at com.azure.cosmos.ClientSideRequestStatistics$ClientSideRequestStatisticsSerializer.serialize(ClientSideRequestStatistics.java:266)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:4094)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:3404)
	at com.azure.cosmos.CosmosResponseDiagnostics.toString(CosmosResponseDiagnostics.java:48)
	at com.azure.cosmos.CosmosClientException.getMessage(CosmosClientException.java:134)
	at com.azure.cosmos.CosmosClientException.toString(CosmosClientException.java:256)
	at java.lang.String.valueOf(String.java:2994)
	at java.io.PrintStream.println(PrintStream.java:821)
	at java.lang.Throwable$WrappedPrintStream.println(Throwable.java:748)
	at java.lang.Throwable.printStackTrace(Throwable.java:655)
	at java.lang.Throwable.printStackTrace(Throwable.java:643)
	at java.lang.Throwable.printStackTrace(Throwable.java:634)
	at com.azure.cosmos.sample.sync.SyncMain.main(SyncMain.java:57)

**To Reproduce**
Run Sample Code outside SDK - using 4.0.0-preview.2

***Code Snippet***
Code snippet which causes any exception will try to log statistics, and will cause this issue. 

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - IDE : [e.g. IntelliJ]
 - Version of the Library used

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by kushagraThapar** [comment]
Afterburner module has been removed from diagnostics.

**Comment by kushagraThapar** [comment]
This issue has been fixed here - https://github.com/Azure/azure-sdk-for-java/pull/19865
