### ISSUE TITLE
java.lang.ClassNotFoundException: retrofit2.BaseUrl when creating any client

### ISSUE THREAD

**Issue by digeratisensei** [Azure/azure-sdk-for-java#831]
I've been banging my head against this all day. 

Relevant maven dependencies and repo:

`<repositories>
    <repository>
      <id>adx-snapshots</id>
      <name>Azure ADX Snapshots</name>
      <url>http://adxsnapshots.azurewebsites.net/</url>
      <layout>default</layout>
      <snapshots>
        <enabled>true</enabled>
      </snapshots>
    </repository>

    <repository>
      <id>ossrh</id>
      <name>Sonatype Snapshots</name>
      <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
      <layout>default</layout>
      <snapshots>
        <enabled>true</enabled>
        <updatePolicy>always</updatePolicy>
      </snapshots>
    </repository>

  </repositories>

  <dependencies>

    <dependency>
      <groupId>com.microsoft.rest</groupId>
      <artifactId>client-runtime</artifactId>
      <version>1.0.0-SNAPSHOT</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.microsoft.azure</groupId>
      <artifactId>azure-mgmt-utility</artifactId>
      <version>0.9.1-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>com.microsoft.azure</groupId>
      <artifactId>azure-mgmt-resources</artifactId>
      <version>1.0.0-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>com.microsoft.azure</groupId>
      <artifactId>azure-mgmt-storage</artifactId>
      <version>0.9.1-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>com.microsoft.azure</groupId>
      <artifactId>azure-mgmt-network</artifactId>
      <version>1.0.0-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>com.microsoft.azure</groupId>
      <artifactId>azure-mgmt-compute</artifactId>
      <version>1.0.0-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>com.microsoft.azure</groupId>
      <artifactId>azure-client-authentication</artifactId>
      <version>1.0.0-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.12</version>
      <scope>test</scope>
    </dependency>

  </dependencies>`

Relevant Code:
`ApplicationTokenCredentials credentials = new ApplicationTokenCredentials(
                applicationId, tenantId, secretPassword, AzureEnvironment.AZURE
        );
SubscriptionClient client = new SubscriptionClientImpl(credentials);`
causes the error. So does:
`ResourceManagementClient resourceManagementClient = new ResourceManagementClientImpl(credentials);
StorageManagementClient storageManagementClient = new StorageManagementClientImpl(credentials);
NetworkManagementClient networkManagementClient = new NetworkManagementClientImpl(credentials);`

This was working earlier this week and now it is not. Here is the full stack trace:

Exception in thread "main" java.lang.NoClassDefFoundError: retrofit2/BaseUrl
	at com.example.test.Main.main(Main.java:54)
Caused by: java.lang.ClassNotFoundException: retrofit2.BaseUrl
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more

**Comment by digeratisensei** [comment]
Turns out our project was corrupt. Rebuilt the project from scratch and start working as expected.
