### ISSUE TITLE
[BUG] EventProcessorClient based application hangs after "send not allowed after the sender is closed"

### ISSUE THREAD

**Issue by cykl** [Azure/azure-sdk-for-java#8341]
**Describe the bug**

An EventProcessorClient based application runs fine until a `java.lang.IllegalStateException: send not allowed after the sender is closed` is thrown. Then, application hangs and does nothing else than complaining about TimeoutException while trying to get partition ids from Event Hubs API (scheduled load balacing).

***Exception or Stack Trace***

Note: name spaces and consumer groups have been redacted.

```java
2020-02-19 20:11:56,754 WARN  com.azure.core.amqp.implementation.ReactorExecutor [] - connectionId[MF_a05d13_1582044306398], message[Unhandled exception while processing events in reactor, report this error.]
java.lang.IllegalStateException: send not allowed after the sender is closed.
2020-02-19 20:11:56,766 WARN  com.azure.core.amqp.implementation.AmqpExceptionHandler [] - Connection exception encountered.
send not allowed after the sender is closed., TrackingId: 5e592a36-c122-43fa-9d3c-88b8e91ccbd6, at: 2020-02-19T20:11:56.766628Z[Etc/UTC], errorContext[NAMESPACE: ${namespace}.servicebus.windows.net]
2020-02-19 20:12:00,774 WARN  com.azure.messaging.eventhubs.PartitionBasedLoadBalancer [] - Load balancing for event processor failed - Did not observe any item or terminal signal within 60000ms in 'flatMapMany' (and no fallback has been configured)
Did not observe any item or terminal signal within 60000ms in 'flatMapMany' (and no fallback has been configured)
2020-02-19 20:12:00,776 ERROR com.greencom.xxx.events.ErrorEvent [] - Error while processing ${hub-name.1}, ${consumer-group.1}, NONE, java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 60000ms in 'flatMapMany' (
and no fallback has been configured), Thread : Thread[parallel-1,5,main]
java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 60000ms in 'flatMapMany' (and no fallback has been configured)
        at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.handleTimeout(FluxTimeout.java:288) [reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
        at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.doTimeout(FluxTimeout.java:273) [reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
        at reactor.core.publisher.FluxTimeout$TimeoutTimeoutSubscriber.onNext(FluxTimeout.java:390) [reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
        at reactor.core.publisher.StrictSubscriber.onNext(StrictSubscriber.java:89) [reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
        at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:73) [reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
        at reactor.core.publisher.MonoDelay$MonoDelayRunnable.run(MonoDelay.java:117) [reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
        at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68) [reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
        at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28) [reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
2020-02-19 20:12:02,108 WARN  com.azure.messaging.eventhubs.PartitionBasedLoadBalancer [] - Load balancing for event processor failed - Did not observe any item or terminal signal within 60000ms in 'flatMapMany' (and no fallback has been configured)
Did not observe any item or terminal signal within 60000ms in 'flatMapMany' (and no fallback has been configured)
2020-02-19 20:12:02,108 ERROR com.greencom.xxx.events.ErrorEvent [] - Error while processing ${hub-name.2}, ${consumer-group.2}, NONE, java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 60000ms in 'flatMapMany' (and no fallback has been configured), Thread : Thread[parallel-1,5,main]
java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 60000ms in 'flatMapMany' (and no fallback has been configured)
        at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.handleTimeout(FluxTimeout.java:288) [reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
        at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.doTimeout(FluxTimeout.java:273) [reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
        at reactor.core.publisher.FluxTimeout$TimeoutTimeoutSubscriber.onNext(FluxTimeout.java:390) [reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
        at reactor.core.publisher.StrictSubscriber.onNext(StrictSubscriber.java:89) [reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
        at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:73) [reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
        at reactor.core.publisher.MonoDelay$MonoDelayRunnable.run(MonoDelay.java:117) [reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
        at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68) [reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
        at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28) [reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
2020-02-19 20:12:02,291 WARN  com.azure.messaging.eventhubs.PartitionBasedLoadBalancer [] - Load balancing for event processor failed - Did not observe any item or terminal signal within 60000ms in 'flatMapMany' (and no fallback has been configured)
Did not observe any item or terminal signal within 60000ms in 'flatMapMany' (and no fallback has been configured)
2020-02-19 20:12:02,291 ERROR com.greencom.xxx.events.ErrorEvent [] - Error while processing ${hub-name.3}, ${consumer-group.3}, NONE, java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 60000ms in 'flatMapMany' (and no fallback has been configured), Thread : Thread[parallel-1,5,main]
java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 60000ms in 'flatMapMany' (and no fallback has been configured)
        at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.handleTimeout(FluxTimeout.java:288) [reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
        at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.doTimeout(FluxTimeout.java:273) [reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
        at reactor.core.publisher.FluxTimeout$TimeoutTimeoutSubscriber.onNext(FluxTimeout.java:390) [reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
        at reactor.core.publisher.StrictSubscriber.onNext(StrictSubscriber.java:89) [reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
        at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:73) [reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
        at reactor.core.publisher.MonoDelay$MonoDelayRunnable.run(MonoDelay.java:117) [reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
        at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68) [reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
        at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28) [reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
2020-02-19 20:12:10,772 WARN  com.azure.messaging.eventhubs.PartitionBasedLoadBalancer [] - Load balancing for event processor failed - Did not observe any item or terminal signal within 60000ms in 'flatMapMany' (and no fallback has been configured)
Did not observe any item or terminal signal within 60000ms in 'flatMapMany' (and no fallback has been configured)
2020-02-19 20:12:10,772 ERROR com.greencom.xxx.events.ErrorEvent [] - Error while processing ${hub-name.1}, ${consumer-group.1}, NONE, java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 60000ms in 'flatMapMany' (and no fallback has been configured), Thread : Thread[parallel-1,5,main]
java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 60000ms in 'flatMapMany' (and no fallback has been configured)
        at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.handleTimeout(FluxTimeout.java:288) [reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
        at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.doTimeout(FluxTimeout.java:273) [reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
        at reactor.core.publisher.FluxTimeout$TimeoutTimeoutSubscriber.onNext(FluxTimeout.java:390) [reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
        at reactor.core.publisher.StrictSubscriber.onNext(StrictSubscriber.java:89) [reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
        at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:73) [reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
        at reactor.core.publisher.MonoDelay$MonoDelayRunnable.run(MonoDelay.java:117) [reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
        at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68) [reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
        at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28) [reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
2020-02-19 20:12:12,108 WARN  com.azure.messaging.eventhubs.PartitionBasedLoadBalancer [] - Load balancing for event processor failed - Did not observe any item or terminal signal within 60000ms in 'flatMapMany' (and no fallback has been configured)
Did not observe any item or terminal signal within 60000ms in 'flatMapMany' (and no fallback has been configured)
2020-02-19 20:12:12,109 ERROR com.greencom.xxx.events.ErrorEvent [] - Error while processing ${hub-name.2}, ${consumer-group.2}, NONE, java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 60000ms in 'flatMapMany' (and no fallback has been configured), Thread : Thread[parallel-1,5,main]
java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 60000ms in 'flatMapMany' (and no fallback has been configured)
        at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.handleTimeout(FluxTimeout.java:288) [reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
        at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.doTimeout(FluxTimeout.java:273) [reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
        at reactor.core.publisher.FluxTimeout$TimeoutTimeoutSubscriber.onNext(FluxTimeout.java:390) [reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
        at reactor.core.publisher.StrictSubscriber.onNext(StrictSubscriber.java:89) [reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
        at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:73) [reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
        at reactor.core.publisher.MonoDelay$MonoDelayRunnable.run(MonoDelay.java:117) [reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
        at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68) [reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
        at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28) [reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
2020-02-19 20:12:12,434 WARN  com.azure.messaging.eventhubs.PartitionBasedLoadBalancer [] - Load balancing for event processor failed - Did not observe any item or terminal signal within 60000ms in 'flatMapMany' (and no fallback has been configured)
Did not observe any item or terminal signal within 60000ms in 'flatMapMany' (and no fallback has been configured)
2020-02-19 20:12:12,434 ERROR com.greencom.xxx.events.ErrorEvent [] - Error while processing ${hub-name.3}, ${consumer-group.3}, NONE, java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 60000ms in 'flatMapMany' (and no fallback has been configured), Thread : Thread[parallel-1,5,main]
java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 60000ms in 'flatMapMany' (and no fallback has been configured)
        at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.handleTimeout(FluxTimeout.java:288) [reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
        at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.doTimeout(FluxTimeout.java:273) [reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
        at reactor.core.publisher.FluxTimeout$TimeoutTimeoutSubscriber.onNext(FluxTimeout.java:390) [reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
        at reactor.core.publisher.StrictSubscriber.onNext(StrictSubscriber.java:89) [reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
        at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:73) [reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
        at reactor.core.publisher.MonoDelay$MonoDelayRunnable.run(MonoDelay.java:117) [reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
        at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68) [reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
        at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28) [reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
2020-02-19 20:12:20,771 WARN  com.azure.messaging.eventhubs.PartitionBasedLoadBalancer [] - Load balancing for event processor failed - Did not observe any item or terminal signal within 60000ms in 'flatMapMany' (and no fallback has been configured)
Did not observe any item or terminal signal within 60000ms in 'flatMapMany' (and no fallback has been configured)
2020-02-19 20:12:20,772 ERROR com.greencom.xxx.events.ErrorEvent [] - Error while processing ${hub-name.1}, ${consumer-group.1}, NONE, java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 60000ms in 'flatMapMany' (and no fallback has been configured), Thread : Thread[parallel-1,5,main]
java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 60000ms in 'flatMapMany' (and no fallback has been configured)
        at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.handleTimeout(FluxTimeout.java:288) [reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
        at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.doTimeout(FluxTimeout.java:273) [reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
        at reactor.core.publisher.FluxTimeout$TimeoutTimeoutSubscriber.onNext(FluxTimeout.java:390) [reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
        at reactor.core.publisher.StrictSubscriber.onNext(StrictSubscriber.java:89) [reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
        at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:73) [reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
        at reactor.core.publisher.MonoDelay$MonoDelayRunnable.run(MonoDelay.java:117) [reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
        at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68) [reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
        at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28) [reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
2020-02-19 20:12:22,108 WARN  com.azure.messaging.eventhubs.PartitionBasedLoadBalancer [] - Load balancing for event processor failed - Did not observe any item or terminal signal within 60000ms in 'flatMapMany' (and no fallback has been configured)
Did not observe any item or terminal signal within 60000ms in 'flatMapMany' (and no fallback has been configured)
2020-02-19 20:12:22,108 ERROR com.greencom.xxx.events.ErrorEvent [] - Error while processing ${hub-name.2}, ${consumer-group.2}, NONE, java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 60000ms in 'flatMapMany' (and no fallback has been configured), Thread : Thread[parallel-1,5,main]
java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 60000ms in 'flatMapMany' (and no fallback has been configured)
        at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.handleTimeout(FluxTimeout.java:288) [reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
        at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.doTimeout(FluxTimeout.java:273) [reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
        at reactor.core.publisher.FluxTimeout$TimeoutTimeoutSubscriber.onNext(FluxTimeout.java:390) [reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
        at reactor.core.publisher.StrictSubscriber.onNext(StrictSubscriber.java:89) [reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
        at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:73) [reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
        at reactor.core.publisher.MonoDelay$MonoDelayRunnable.run(MonoDelay.java:117) [reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
        at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68) [reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
        at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28) [reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

An IllegalStateException seems to be thrown every minute or so:

```
rg "report this error"  connector.log  | head -n 25
2020-02-19 20:11:56,754 WARN  com.azure.core.amqp.implementation.ReactorExecutor [] - connectionId[MF_a05d13_1582044306398], message[Unhandled exception while processing events in reactor, report this error.]
2020-02-19 20:12:56,783 WARN  com.azure.core.amqp.implementation.ReactorExecutor [] - connectionId[MF_a2ba22_1582044183886], message[Unhandled exception while processing events in reactor, report this error.]
2020-02-19 20:13:56,798 WARN  com.azure.core.amqp.implementation.ReactorExecutor [] - connectionId[MF_1a3bb4_1582044073391], message[Unhandled exception while processing events in reactor, report this error.]
2020-02-19 20:14:56,801 WARN  com.azure.core.amqp.implementation.ReactorExecutor [] - connectionId[MF_fc2e6b_1582043992974], message[Unhandled exception while processing events in reactor, report this error.]
2020-02-19 20:15:56,807 WARN  com.azure.core.amqp.implementation.ReactorExecutor [] - connectionId[MF_923860_1582044042888], message[Unhandled exception while processing events in reactor, report this error.]
2020-02-19 20:16:56,847 WARN  com.azure.core.amqp.implementation.ReactorExecutor [] - connectionId[MF_5c7f2e_1582044235315], message[Unhandled exception while processing events in reactor, report this error.]
2020-02-19 20:17:56,876 WARN  com.azure.core.amqp.implementation.ReactorExecutor [] - connectionId[MF_05cd29_1582044113923], message[Unhandled exception while processing events in reactor, report this error.]
2020-02-19 20:18:56,883 WARN  com.azure.core.amqp.implementation.ReactorExecutor [] - connectionId[MF_b5f54d_1582044214645], message[Unhandled exception while processing events in reactor, report this error.]
2020-02-19 20:22:56,972 WARN  com.azure.core.amqp.implementation.ReactorExecutor [] - connectionId[MF_5114d1_1582043990560], message[Unhandled exception while processing events in reactor, report this error.]
2020-02-19 20:23:56,979 WARN  com.azure.core.amqp.implementation.ReactorExecutor [] - connectionId[MF_57cd2a_1582044132650], message[Unhandled exception while processing events in reactor, report this error.]
2020-02-19 20:24:56,984 WARN  com.azure.core.amqp.implementation.ReactorExecutor [] - connectionId[MF_ede365_1582044273886], message[Unhandled exception while processing events in reactor, report this error.]
2020-02-19 20:27:57,002 WARN  com.azure.core.amqp.implementation.ReactorExecutor [] - connectionId[MF_e8b753_1582044294477], message[Unhandled exception while processing events in reactor, report this error.]
2020-02-19 20:31:57,014 WARN  com.azure.core.amqp.implementation.ReactorExecutor [] - connectionId[MF_9509d1_1582044071594], message[Unhandled exception while processing events in reactor, report this error.]
2020-02-19 20:32:57,016 WARN  com.azure.core.amqp.implementation.ReactorExecutor [] - connectionId[MF_dd81cb_1582044021178], message[Unhandled exception while processing events in reactor, report this error.]
2020-02-19 20:33:57,030 WARN  com.azure.core.amqp.implementation.ReactorExecutor [] - connectionId[MF_20519b_1582044243187], message[Unhandled exception while processing events in reactor, report this error.]
2020-02-19 20:34:57,036 WARN  com.azure.core.amqp.implementation.ReactorExecutor [] - connectionId[MF_fd6242_1582044042961], message[Unhandled exception while processing events in reactor, report this error.]
2020-02-19 20:35:57,039 WARN  com.azure.core.amqp.implementation.ReactorExecutor [] - connectionId[MF_40f5a9_1582044223149], message[Unhandled exception while processing events in reactor, report this error.]
2020-02-19 20:36:57,042 WARN  com.azure.core.amqp.implementation.ReactorExecutor [] - connectionId[MF_6809e3_1582044031535], message[Unhandled exception while processing events in reactor, report this error.]
2020-02-19 20:37:57,045 WARN  com.azure.core.amqp.implementation.ReactorExecutor [] - connectionId[MF_40fcae_1582044061799], message[Unhandled exception while processing events in reactor, report this error.]
2020-02-19 20:38:57,047 WARN  com.azure.core.amqp.implementation.ReactorExecutor [] - connectionId[MF_ee1cc8_1582044011238], message[Unhandled exception while processing events in reactor, report this error.]
2020-02-19 20:39:57,049 WARN  com.azure.core.amqp.implementation.ReactorExecutor [] - connectionId[MF_c35e87_1582043990604], message[Unhandled exception while processing events in reactor, report this error.]
2020-02-19 20:40:57,053 WARN  com.azure.core.amqp.implementation.ReactorExecutor [] - connectionId[MF_dc2653_1582044104070], message[Unhandled exception while processing events in reactor, report this error.]
2020-02-19 20:41:57,056 WARN  com.azure.core.amqp.implementation.ReactorExecutor [] - connectionId[MF_60dc03_1582044193984], message[Unhandled exception while processing events in reactor, report this error.]
2020-02-19 20:42:57,059 WARN  com.azure.core.amqp.implementation.ReactorExecutor [] - connectionId[MF_36d26e_1582044235897], message[Unhandled exception while processing events in reactor, report this error.]
2020-02-19 20:43:57,062 WARN  com.azure.core.amqp.implementation.ReactorExecutor [] - connectionId[MF_2a3a12_1582044285043], message[Unhandled exception while processing events in reactor, report this error.]
```

I can share an unredacted log file if it helps.

**To Reproduce**

This issue occurs from time to time. However, I'm not able to provide a deterministic minimal test case.

***Code Snippet***

```java
        BlobContainerAsyncClient blobContainerAsyncClient = new BlobContainerClientBuilder()
               [...]
                .buildAsyncClient();

        BlobCheckpointStore blobCheckpointStore = new BlobCheckpointStore(blobContainerAsyncClient);

        xEventProcessorClient = new EventProcessorClientBuilder()
                [...]
                .processError(new ErrorEvent(configuration))
                .checkpointStore(blobCheckpointStore)
                .buildEventProcessorClient();

        yEventProcessorClient = new EventProcessorClientBuilder()
                [...]                
                .processError(new ErrorEvent(configuration))
                .checkpointStore(blobCheckpointStore)
                .buildEventProcessorClient();

        zEventProcessorClient = new EventProcessorClientBuilder()
               [...]
                .processError(new ErrorEvent(configuration))
                .checkpointStore(blobCheckpointStore)
                .buildEventProcessorClient();

[...]

public class ErrorEvent implements Consumer<ErrorContext> {

    private static final Logger logger = LoggerFactory.getLogger(ErrorEvent.class);

    @Override
    public void accept(ErrorContext errorContext) {
        logger.error("Error while processing {}, {}, {}, {}",
                errorContext.getPartitionContext().getEventHubName(),
                errorContext.getPartitionContext().getConsumerGroup(),
                errorContext.getPartitionContext().getPartitionId(),
                errorContext.getThrowable(), errorContext.getThrowable());
    }
}
```

Application starts three EventProcessorClient sharing the same blob store.

I had expect the three client to be independant. However I observe that after the first `IllegalStateException` is catched by a ReactorExecutor, all three clients starts failing.

**Expected behavior**

Event consumption should resume as soon as possible or application should know that it should be restarted. 

**Setup (please complete the following information):**

 -  com.azure:azure-messaging-eventhubs:5.0.2

**Comment by conniey** [comment]
Thanks for reporting this issue! I'm taking a look into it.
