### ISSUE TITLE
[BUG]Come across java.lang.ArrayIndexOutOfBoundsException while download object from Azure storage container using azure-storage-blob API

### ISSUE THREAD

**Issue by mortzheng** [Azure/azure-sdk-for-java#8534]
**Describe the bug**
We're using Azure storage blob to store our source images. But when we try to download image using BlockBlobClient#Download method, java.lang.ArrayIndexOutOfBoundsException happens occasionally.  
Here's the SDK version we're using.
com.azure:azure-storage-blob:12.1.0

I also attached the code snippet and exception stack track. Can you please help to clarify what's going wrong here?

***Exception or Stack Trace***
00:00.070645780 a.a.s.AzureBlobService - download blob, container=static, key=product/f5548751-5623-4fde-8a68-45c4253a34e2.jpeg, elapsed=65680032
00:00.073364006 ERROR c.f.i.log.LogManager - [java.lang.ArrayIndexOutOfBoundsException] Index 2 out of bounds for length 2
java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2
	at java.base/java.lang.CompoundEnumeration.next(Unknown Source)
	at java.base/java.lang.CompoundEnumeration.hasMoreElements(Unknown Source)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(Unknown Source)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(Unknown Source)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(Unknown Source)
	at java.base/java.util.ServiceLoader$2.hasNext(Unknown Source)
	at java.base/java.util.ServiceLoader$3.hasNext(Unknown Source)
	at com.azure.core.util.tracing.TracerProxy.setSpanName(TracerProxy.java:77)
	at com.azure.core.http.rest.RestProxy.startTracingSpan(RestProxy.java:200)
	at com.azure.core.http.rest.RestProxy.invoke(RestProxy.java:134)
	at com.azure.storage.blob.implementation.$Proxy11.download(Unknown Source)
	at com.azure.storage.blob.implementation.BlobsImpl.downloadWithRestResponseAsync(BlobsImpl.java:259)
	at com.azure.storage.blob.specialized.BlobAsyncClientBase.downloadHelper(BlobAsyncClientBase.java:644)
	at com.azure.storage.blob.specialized.BlobAsyncClientBase.downloadWithResponse(BlobAsyncClientBase.java:629)
	at com.azure.storage.blob.specialized.BlobClientBase.downloadWithResponse(BlobClientBase.java:408)
	at com.azure.storage.blob.specialized.BlobClientBase.download(BlobClientBase.java:378)
	at app.azure.storage.AzureBlobService.download(AzureBlobService.java:61)
	at app.image.service.StorageService.download(StorageService.java:134)
	at app.image.service.StorageService.transform(StorageService.java:111)
	at app.image.service.StorageService.get(StorageService.java:84)
	at app.image.service.ImageService.get(ImageService.java:59)
	at app.image.web.ImageWebServiceImpl.get(ImageWebServiceImpl.java:28)
	at app.image.web.ImageWebServiceImpl$get$4.execute(ImageWebServiceImpl$get$4.java)
	at core.framework.internal.web.controller.InvocationImpl.proceed(InvocationImpl.java:51)
	at core.framework.internal.web.HTTPHandler.handle(HTTPHandler.java:99)
	at core.framework.internal.web.HTTPHandler.handleRequest(HTTPHandler.java:72)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:376)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1871)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1400)
	at java.base/java.lang.Thread.run(Unknown Source)
00:00.080104771 c.f.i.w.response.ResponseHandler - [response:header] Content-Type=application/json; charset=utf-8
00:00.082286192 c.f.i.w.response.BeanBody - [response] body={"id":"70843C7052FC7DB85EAA","severity":"ERROR","error_code":"INTERNAL_ERROR","message":"Index 2 out of bounds for length 2","stack_trace":"java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2\n\tat java.base/java.lang.CompoundEnumeration.next(Unknown Source)\n\tat java.base/java.lang.CompoundEnumeration.hasMoreElements(Unknown Source)\n\tat java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(Unknown Source)\n\tat java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(Unknown Source)\n\tat java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(Unknown Source)\n\tat java.base/java.util.ServiceLoader$2.hasNext(Unknown Source)\n\tat java.base/java.util.ServiceLoader$3.hasNext(Unknown Source)\n\tat com.azure.core.util.tracing.TracerProxy.setSpanName(TracerProxy.java:77)\n\tat com.azure.core.http.rest.RestProxy.startTracingSpan(RestProxy.java:200)\n\tat com.azure.core.http.rest.RestProxy.invoke(RestProxy.java:134)\n\tat com.azure.storage.blob.implementation.$Proxy11.download(Unknown Source)\n\tat com.azure.storage.blob.implementation.BlobsImpl.downloadWithRestResponseAsync(BlobsImpl.java:259)\n\tat com.azure.storage.blob.specialized.BlobAsyncClientBase.downloadHelper(BlobAsyncClientBase.java:644)\n\tat com.azure.storage.blob.specialized.BlobAsyncClientBase.downloadWithResponse(BlobAsyncClientBase.java:629)\n\tat com.azure.storage.blob.specialized.BlobClientBase.downloadWithResponse(BlobClientBase.java:408)\n\tat com.azure.storage.blob.specialized.BlobClientBase.download(BlobClientBase.java:378)\n\tat app.azure.storage.AzureBlobService.download(AzureBlobService.java:61)\n\tat app.image.service.StorageService.download(StorageService.java:134)\n\tat app.image.service.StorageService.transform(StorageService.java:111)\n\tat app.image.service.StorageService.get(StorageService.java:84)\n\tat app.image.service.ImageService.get(ImageService.java:59)\n\tat app.image.web.ImageWebServiceImpl.get(ImageWebServiceImpl.java:28)\n\tat app.image.web.ImageWebServiceImpl$get$4.execute(ImageWebServiceImpl$get$4.java)\n\tat core.framework.internal.web.controller.InvocationImpl.proceed(InvocationImpl.java:51)\n\tat core.framework.internal.web.HTTPHandler.handle(HTTPHandler.java:99)\n\tat core.framework.internal.web.HTTPHandler.handleRequest(HTTPHandler.java:72)\n\tat io.undertow.server.Connectors.executeRootHandler(Connectors.java:376)\n\tat io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)\n\tat org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1871)\n\tat org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1400)\n\tat java.base/java.lang.Thread.run(Unknown Source)\n"}

**To Reproduce**

***Code Snippet***
BlockBlobClient blobClient = client.getBlobContainerClient(container).getBlobClient(key).getBlockBlobClient();
        try (ByteArrayOutputStream stream = new ByteArrayOutputStream()) {
            blobClient.download(stream);
            return stream.toByteArray();
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        } catch (BlobStorageException e) {
            checkNotFoundException(e);
            throw e;
        }

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - IDE : [e.g. IntelliJ]
 - Version of the Library used

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by rickle-msft** [comment]
@mortzheng Thanks you for reporting this issue. This looks related to #8079 because it looks to be coming from tracing. @alzimmermsft can you take a look? @joshfree for visibility.

**Comment by alzimmermsft** [comment]
Thanks for the heads up @rickle-msft! It appears that the person who filed issue #8079 has opened PR #8442 with a potential solution, we'll get someone to review the PR and see when/if we can merge it in hopefully resolving both issues.

**Comment by alzimmermsft** [comment]
This should be fixed as PR #8442 has been merged, this fix was shipped with Azure Core 1.3.0.
