### ISSUE TITLE
[BUG] Blob batch client runs into UnexpectedLengthException when AD credentials are used

### ISSUE THREAD

**Issue by SukruthKS** [Azure/azure-sdk-for-java#8644]
**Describe the bug**
`BlobBatchClient` hits `UnexpectedLengthException` when a service principal with client secret key is used instead of other storage auth mechanisms like SAS tokens.

***Exception or Stack Trace***
```
Exception in thread "main" com.azure.core.exception.UnexpectedLengthException: Request body emitted 1639 bytes more than the expected 48 bytes.
	at com.azure.core.http.rest.RestProxy.lambda$validateLength$0(RestProxy.java:169)
	at reactor.core.publisher.FluxDoOnEach$DoOnEachSubscriber.onNext(FluxDoOnEach.java:140)
	at reactor.core.publisher.FluxIterable$IterableSubscription.slowPath(FluxIterable.java:243)
	at reactor.core.publisher.FluxIterable$IterableSubscription.request(FluxIterable.java:201)
	at reactor.core.publisher.FluxDoOnEach$DoOnEachSubscriber.request(FluxDoOnEach.java:97)
	at reactor.core.publisher.FluxMap$MapSubscriber.request(FluxMap.java:155)
	at reactor.core.publisher.FluxMap$MapSubscriber.request(FluxMap.java:155)
	at reactor.netty.channel.MonoSendMany$SendManyInner.onSubscribe(MonoSendMany.java:224)
	at reactor.core.publisher.FluxMap$MapSubscriber.onSubscribe(FluxMap.java:86)
	at reactor.core.publisher.FluxMap$MapSubscriber.onSubscribe(FluxMap.java:86)
	at reactor.core.publisher.FluxDoOnEach$DoOnEachSubscriber.onSubscribe(FluxDoOnEach.java:110)
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:139)
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:63)
	at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:53)
	at reactor.core.publisher.FluxDefer.subscribe(FluxDefer.java:54)
	at reactor.core.publisher.Flux.subscribe(Flux.java:8134)
	at reactor.netty.channel.MonoSendMany.subscribe(MonoSendMany.java:81)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.drain(MonoIgnoreThen.java:153)
	at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:56)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4087)
	at reactor.netty.NettyOutbound.subscribe(NettyOutbound.java:329)
	at reactor.core.publisher.MonoSource.subscribe(MonoSource.java:58)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at reactor.netty.http.client.HttpClientConnect$HttpIOHandlerObserver.onStateChange(HttpClientConnect.java:430)
	at reactor.netty.ReactorNetty$CompositeConnectionObserver.onStateChange(ReactorNetty.java:473)
	at reactor.netty.resources.PooledConnectionProvider$DisposableAcquire.onStateChange(PooledConnectionProvider.java:525)
	at reactor.netty.resources.PooledConnectionProvider$PooledConnection.onStateChange(PooledConnectionProvider.java:434)
	at reactor.netty.channel.ChannelOperationsHandler.channelActive(ChannelOperationsHandler.java:62)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:225)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:211)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:204)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelActive(CombinedChannelDuplexHandler.java:414)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:69)
	at io.netty.channel.CombinedChannelDuplexHandler.channelActive(CombinedChannelDuplexHandler.java:213)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:225)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:211)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:204)
	at reactor.netty.tcp.SslProvider$SslReadHandler.userEventTriggered(SslProvider.java:731)
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:341)
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:327)
	at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.ssl.SslHandler.setHandshakeSuccess(SslHandler.java:1750)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1409)
	at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1236)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1273)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:505)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:444)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:283)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:483)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:383)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:835)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:93)
		at reactor.core.publisher.Mono.block(Mono.java:1663)
		at com.azure.storage.common.implementation.StorageImplUtils.blockWithOptionalTimeout(StorageImplUtils.java:99)
		at com.azure.storage.blob.batch.BlobBatchClient.submitBatchWithResponse(BlobBatchClient.java:87)
		at com.azure.storage.blob.batch.BlobBatchClient.submitBatch(BlobBatchClient.java:60)
		at com.testfactory.apps.App.repro2(App.java:181)
		at com.testfactory.apps.App.main(App.java:76)

Process finished with exit code 1

```

**To Reproduce**
Please use the below code snippet to repro the issue.

***Code Snippet***
```
// Build blob service client
final String endpoint = "https://<storage_account_name>.blob.core.windows.net/";

ClientSecretCredential adCreds = new ClientSecretCredentialBuilder()
    .tenantId("<tenant_id>")
    .clientId("<client_id>")
    .clientSecret("<client_secret>")
    .build();

BlobServiceClient serviceClient = new BlobServiceClientBuilder()
    .endpoint(endpoint)
    //.sasToken("<SAS token>") // works fine with a SAS token
    .credential(adCreds)       // fails if a service principal is used
    .buildClient();

// Submit a batch delete request
final String container = "testcont";
final List<String> blobsToDelete = Arrays.asList("someblob.txt");

BlobBatchClient batchClient = new BlobBatchClientBuilder(serviceClient)
    .buildClient();

BlobBatch batchRequest = batchClient.getBlobBatch();

for (String blobToDelete : blobsToDelete)
{
    batchRequest.deleteBlob(container, blobToDelete);
}

batchClient.submitBatch(batchRequest);
```

**Expected behavior**
It is not expected to fail with the above error and submit batch requests to storage service.

**Screenshots**
NA

**Setup (please complete the following information):**
 - OS: Linux
 - IDE : IntelliJ
 - Version of the Library used: 
    - azure-storage-blob -> 12.4.0
    - azure-storage-blob-batch -> 12.4.0-beta.1
    - azure-identity -> 1.0.3

**Additional context**
NA

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by rickle-msft** [comment]
@SukruthKS thank you for reporting this. @alzimmermsft Can you please take a look? @joshfree for visibility.

**Comment by alzimmermsft** [comment]
@SukruthKS Thank you for filing this detailed issue, I'll start taking a look into.
