### ISSUE TITLE
[BUG]Encounter com.azure.storage.blob.models.BlobStorageException Authentication failed

### ISSUE THREAD

**Issue by mortzheng** [Azure/azure-sdk-for-java#8667]
**Describe the bug**
We're saving images to Azure storage and using azure-storage-blob SDK to download the image. But we encounter this exception from time to time, telling us the 403 authentication failed. When 
we retry with a new request, it backs to normal. Attached the stack track blew.

***Exception or Stack Trace***
00:00.016243347 ERROR c.f.i.log.LogManager - [com.azure.storage.blob.models.BlobStorageException] Status code 403, "﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:3b6c6db3-201e-0019-462f-f0cc84000000
Time:2020-03-02T01:14:25.3649912Z</Message><AuthenticationErrorDetail>Lifetime validation failed. The token is expired.</AuthenticationErrorDetail></Error>"
com.azure.storage.blob.models.BlobStorageException: Status code 403, "﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:3b6c6db3-201e-0019-462f-f0cc84000000
Time:2020-03-02T01:14:25.3649912Z</Message><AuthenticationErrorDetail>Lifetime validation failed. The token is expired.</AuthenticationErrorDetail></Error>"
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.azure.core.http.rest.RestProxy.instantiateUnexpectedException(RestProxy.java:357)
	at com.azure.core.http.rest.RestProxy.lambda$ensureExpectedStatus$3(RestProxy.java:400)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:118)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1592)
	at reactor.core.publisher.MonoProcessor.onNext(MonoProcessor.java:317)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1592)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:144)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1592)
	at reactor.core.publisher.MonoProcessor.subscribe(MonoProcessor.java:383)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:55)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4087)
	at reactor.core.publisher.MonoProcessor.add(MonoProcessor.java:457)
	at reactor.core.publisher.MonoProcessor.subscribe(MonoProcessor.java:370)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:55)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:150)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1592)
	at reactor.core.publisher.MonoProcessor.onNext(MonoProcessor.java:317)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:123)
	at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:112)
	at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:213)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:123)
	at reactor.core.publisher.FluxFilterFuseable$FilterFuseableConditionalSubscriber.onNext(FluxFilterFuseable.java:330)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1592)
	at reactor.core.publisher.MonoReduceSeed$ReduceSeedSubscriber.onComplete(MonoReduceSeed.java:156)
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:136)
	at reactor.netty.channel.FluxReceive.terminateReceiver(FluxReceive.java:397)
	at reactor.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:197)
	at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:345)
	at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:363)
	at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:412)
	at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:556)
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:91)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:328)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:302)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1475)
	at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1236)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1273)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:505)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:444)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:283)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:483)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:383)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:93)
		at reactor.core.publisher.Mono.block(Mono.java:1663)
		at com.azure.storage.common.implementation.StorageImplUtils.blockWithOptionalTimeout(StorageImplUtils.java:94)
		at com.azure.storage.blob.specialized.BlobClientBase.downloadWithResponse(BlobClientBase.java:418)
		at com.azure.storage.blob.specialized.BlobClientBase.download(BlobClientBase.java:378)
		at app.azure.storage.AzureBlobService.download(AzureBlobService.java:61)
		at app.image.service.StorageService.download(StorageService.java:134)
		at app.image.service.StorageService.transform(StorageService.java:111)
		at app.image.service.StorageService.get(StorageService.java:84)
		at app.image.service.ImageService.get(ImageService.java:59)
		at app.image.web.ImageWebServiceImpl.get(ImageWebServiceImpl.java:28)
		at app.image.web.ImageWebServiceImpl$get$4.execute(ImageWebServiceImpl$get$4.java)
		at core.framework.internal.web.controller.InvocationImpl.proceed(InvocationImpl.java:51)
		at core.framework.internal.web.HTTPHandler.handle(HTTPHandler.java:99)
		at core.framework.internal.web.HTTPHandler.handleRequest(HTTPHandler.java:72)
		at io.undertow.server.Connectors.executeRootHandler(Connectors.java:376)
		at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
		at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1871)
		at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1451)
		... 1 more
00:00.017291156 c.f.i.w.response.ResponseHandler - [response:header] Content-Type=application/json; charset=utf-8

**To Reproduce**

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - IDE : [e.g. IntelliJ]
 - Version of the Library used

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by rickle-msft** [comment]
@mortzheng Thank you for posting this issue. I notice this line in your stack trace: "Lifetime validation failed. The token is expired." Are you using OAuth token credentials to authenticate?

**Comment by mortzheng** [comment]
Here's the code snippet:
this.client = new BlobServiceClientBuilder()
            .endpoint(this.endpoint)
            .credential(new DefaultAzureCredentialBuilder().build())
            .buildClient();

We're using DefaultAzureCredential. And i think it should ManagedIdentityCredential, since we're deploy our service on AKS pod and binding aadpodidentity to it. If my understanding is correct, the default credential should be the managed identity. 
Just to strength this, it happens from time to time, not every request.

**Comment by rickle-msft** [comment]
Thanks, @mortzheng for the information. 

@g2vinay Can you please comment on the behavior of DefaultAzureCredential and managedIdentityCredential and why they may be causing these transient auth failures?

**Comment by rickle-msft** [comment]
@joshfree for visibility

**Comment by g2vinay** [comment]
@mortzheng Thanks for reporting this issue.
Looking at your use case, it is possible that the requests are getting queued in the netty connection pool while images are being downloaded.
The access token specified in the queued request expires by the time it reaches the server from time to time.

I would recommend that you change the tokenRefreshOffset on your token credential.
You can do this using`tokenRefreshOffset` setter on your credential. The default is 2 minutes duration, increase it to 5 minutes / 10 minutes / a value that works for your use case.
This functionality is available only in our latest beta release here: https://search.maven.org/artifact/com.azure/azure-identity/1.1.0-beta.2/jar

**Comment by mortzheng** [comment]
@g2vinay Sorry for the late response. I made the changes as you suggested several days ago. And it works for me. I don't see any Authentication failed errors so far. I will continue keep an eye on this for another week. If everything is ok, i will close this ticket. Really thanks for your help!

**Comment by rogelio-o** [comment]
We are getting same issue. It isn't related with the tokenRefreshOffset, but with concurrency executions. When token is expired and we try to get a new token in multiple threads at the same time, we get the "token expired" error. SimpleCache of credential policy is implemented with ReplayProcess, at some point this is failing (maybe because we are using blocking API) and returning expired token. Is ReplayProcess thread-safe and can be used in multi-thread context?

What we've done as workaround is implementing our own policy (setting a dummy TokenCredential and adding the policy to the builder). We aren't worried about asking for multiple token and using last one in future calls, so we are not controlling concurrency, just getting context each time we check the token is expired.

**Comment by jianghaolu** [comment]
@rogelio-o we rewrote the SimpleTokenCache to be more resilient to errors during proactive token refreshes. We also replaced ReplayProcess with an atomically referenced MonoProcessor. It's released last week at version 1.1.0-beta.6.
