### ISSUE TITLE
[BUG] Azure Core HTTP NETTY 1.4.0 forming invalid destination URIs

### ISSUE THREAD

**Issue by g2vinay** [Azure/azure-sdk-for-java#8898]
Throws Invalid URISyntaxException, not forming update target URI properly for CertificateClient updateCertificate call.

[main] INFO com.azure.security.keyvault.certificates.CertificateAsyncClient - Updating certificate - fc8686f2-0e9c-4ceb-b00c-6bac422a37bd-testCertificate2
[reactor-http-nio-1] WARN com.azure.core.test.policy.RecordNetworkCallPolicy - Illegal character in path at index 68: /certificates/fc8686f2-0e9c-4ceb-b00c-6bac422a37bd-testCertificate2/{certificate-version}?api-version=7.0
[reactor-http-nio-1] WARN com.azure.security.keyvault.certificates.CertificateService.updateCertificate - <-- HTTP FAILED: 
Illegal character in path at index 68: /certificates/fc8686f2-0e9c-4ceb-b00c-6bac422a37bd-testCertificate2/{certificate-version}?api-version=7.0
[reactor-http-nio-1] WARN reactor.netty.http.client.HttpClientConnect - [id: 0x72a16c09, L:/192.168.0.101:56134 - R:azure-java-live-test.vault.azure.net/13.66.226.249:443] The connection observed an error
java.lang.IllegalArgumentException: Illegal character in path at index 68: /certificates/fc8686f2-0e9c-4ceb-b00c-6bac422a37bd-testCertificate2/{certificate-version}?api-version=7.0
        at java.base/java.net.URI.create(URI.java:906)
        at reactor.netty.http.HttpOperations.resolvePath(HttpOperations.java:300)
        at reactor.netty.http.client.HttpClientConnect$HttpClientHandler.requestWithBody(HttpClientConnect.java:537)
        at reactor.netty.http.client.HttpClientConnect$HttpIOHandlerObserver.lambda$onStateChange$0(HttpClientConnect.java:429)
        at reactor.core@3.3.0.RELEASE/reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44)
        at reactor.netty.http.client.HttpClientConnect$HttpIOHandlerObserver.onStateChange(HttpClientConnect.java:430)
        at reactor.netty.ReactorNetty$CompositeConnectionObserver.onStateChange(ReactorNetty.java:503)
        at reactor.netty.resources.PooledConnectionProvider$DisposableAcquire.run(PooledConnectionProvider.java:571)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: java.net.URISyntaxException: Illegal character in path at index 68: /certificates/fc8686f2-0e9c-4ceb-b00c-6bac422a37bd-testCertificate2/{certificate-version}?api-version=7.0
        at java.base/java.net.URI$Parser.fail(URI.java:2936)
        at java.base/java.net.URI$Parser.checkChars(URI.java:3107)
        at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3189)
        at java.base/java.net.URI$Parser.parse(URI.java:3148)
        at java.base/java.net.URI.<init>(URI.java:623)
        at java.base/java.net.URI.create(URI.java:904)
        ... 14 more
[reactor-http-nio-1] WARN com.azure.core.test.policy.RecordNetworkCallPolicy - Illegal character in path at index 68: /certificates/fc8686f2-0e9c-4ceb-b00c-6bac422a37bd-testCertificate2/{certificate-version}?api-version=7.0
[reactor-http-nio-1] WARN com.azure.security.keyvault.certificates.CertificateService.updateCertificate - <-- HTTP FAILED: 
Illegal character in path at index 68: /certificates/fc8686f2-0e9c-4ceb-b00c-6bac422a37bd-testCertificate2/{certificate-version}?api-version=7.0
[reactor-http-nio-1] WARN reactor.netty.http.client.HttpClientConnect - [id: 0x72a16c09, L:/192.168.0.101:56134 - R:azure-java-live-test.vault.azure.net/13.66.226.249:443] The connection observed an error
java.lang.IllegalArgumentException: Illegal character in path at index 68: /certificates/fc8686f2-0e9c-4ceb-b00c-6bac422a37bd-testCertificate2/{certificate-version}?api-version=7.0
        at java.base/java.net.URI.create(URI.java:906)
        at reactor.netty.http.HttpOperations.resolvePath(HttpOperations.java:300)
        at reactor.netty.http.client.HttpClientConnect$HttpClientHandler.requestWithBody(HttpClientConnect.java:537)
        at reactor.netty.http.client.HttpClientConnect$HttpIOHandlerObserver.lambda$onStateChange$0(HttpClientConnect.java:429)
        at reactor.core@3.3.0.RELEASE/reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44)
        at reactor.netty.http.client.HttpClientConnect$HttpIOHandlerObserver.onStateChange(HttpClientConnect.java:430)
        at reactor.netty.ReactorNetty$CompositeConnectionObserver.onStateChange(ReactorNetty.java:503)
        at reactor.netty.resources.PooledConnectionProvider$DisposableAcquire.run(PooledConnectionProvider.java:571)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: java.net.URISyntaxException: Illegal character in path at index 68: /certificates/fc8686f2-0e9c-4ceb-b00c-6bac422a37bd-testCertificate2/{certificate-version}?api-version=7.0
        at java.base/java.net.URI$Parser.fail(URI.java:2936)
        at java.base/java.net.URI$Parser.checkChars(URI.java:3107)
        at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3189)
        at java.base/java.net.URI$Parser.parse(URI.java:3148)
        at java.base/java.net.URI.<init>(URI.java:623)
        at java.base/java.net.URI.create(URI.java:904)
        ... 14 more
[reactor-http-nio-1] WARN com.azure.core.test.policy.RecordNetworkCallPolicy - Illegal character in path at index 68: /certificates/fc8686f2-0e9c-4ceb-b00c-6bac422a37bd-testCertificate2/{certificate-version}?api-version=7.0
[reactor-http-nio-1] WARN com.azure.security.keyvault.certificates.CertificateService.updateCertificate - <-- HTTP FAILED: 
Illegal character in path at index 68: /certificates/fc8686f2-0e9c-4ceb-b00c-6bac422a37bd-testCertificate2/{certificate-version}?api-version=7.0
[reactor-http-nio-1] WARN reactor.netty.http.client.HttpClientConnect - [id: 0x72a16c09, L:/192.168.0.101:56134 - R:azure-java-live-test.vault.azure.net/13.66.226.249:443] The connection observed an error
java.lang.IllegalArgumentException: Illegal character in path at index 68: /certificates/fc8686f2-0e9c-4ceb-b00c-6bac422a37bd-testCertificate2/{certificate-version}?api-version=7.0
        at java.base/java.net.URI.create(URI.java:906)
        at reactor.netty.http.HttpOperations.resolvePath(HttpOperations.java:300)
        at reactor.netty.http.client.HttpClientConnect$HttpClientHandler.requestWithBody(HttpClientConnect.java:537)
        at reactor.netty.http.client.HttpClientConnect$HttpIOHandlerObserver.lambda$onStateChange$0(HttpClientConnect.java:429)
        at reactor.core@3.3.0.RELEASE/reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44)
        at reactor.netty.http.client.HttpClientConnect$HttpIOHandlerObserver.onStateChange(HttpClientConnect.java:430)
        at reactor.netty.ReactorNetty$CompositeConnectionObserver.onStateChange(ReactorNetty.java:503)
        at reactor.netty.resources.PooledConnectionProvider$DisposableAcquire.run(PooledConnectionProvider.java:571)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: java.net.URISyntaxException: Illegal character in path at index 68: /certificates/fc8686f2-0e9c-4ceb-b00c-6bac422a37bd-testCertificate2/{certificate-version}?api-version=7.0
        at java.base/java.net.URI$Parser.fail(URI.java:2936)
        at java.base/java.net.URI$Parser.checkChars(URI.java:3107)
        at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3189)
        at java.base/java.net.URI$Parser.parse(URI.java:3148)
        at java.base/java.net.URI.<init>(URI.java:623)
        at java.base/java.net.URI.create(URI.java:904)
        ... 14 more
[reactor-http-nio-1] WARN com.azure.core.test.policy.RecordNetworkCallPolicy - Illegal character in path at index 68: /certificates/fc8686f2-0e9c-4ceb-b00c-6bac422a37bd-testCertificate2/{certificate-version}?api-version=7.0
[reactor-http-nio-1] WARN com.azure.security.keyvault.certificates.CertificateService.updateCertificate - <-- HTTP FAILED: 
Illegal character in path at index 68: /certificates/fc8686f2-0e9c-4ceb-b00c-6bac422a37bd-testCertificate2/{certificate-version}?api-version=7.0
[reactor-http-nio-1] WARN com.azure.security.keyvault.certificates.CertificateAsyncClient - Failed to update the certificate - fc8686f2-0e9c-4ceb-b00c-6bac422a37bd-testCertificate2
Max retries 3 times exceeded. Error Details: Illegal character in path at index 68: /certificates/fc8686f2-0e9c-4ceb-b00c-6bac422a37bd-testCertificate2/{certificate-version}?api-version=7.0
[reactor-http-nio-1] WARN reactor.netty.http.client.HttpClientConnect - [id: 0x72a16c09, L:/192.168.0.101:56134 - R:azure-java-live-test.vault.azure.net/13.66.226.249:443] The connection observed an error
java.lang.IllegalArgumentException: Illegal character in path at index 68: /certificates/fc8686f2-0e9c-4ceb-b00c-6bac422a37bd-testCertificate2/{certificate-version}?api-version=7.0
        at java.base/java.net.URI.create(URI.java:906)
        at reactor.netty.http.HttpOperations.resolvePath(HttpOperations.java:300)
        at reactor.netty.http.client.HttpClientConnect$HttpClientHandler.requestWithBody(HttpClientConnect.java:537)
        at reactor.netty.http.client.HttpClientConnect$HttpIOHandlerObserver.lambda$onStateChange$0(HttpClientConnect.java:429)
        at reactor.core@3.3.0.RELEASE/reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44)
        at reactor.netty.http.client.HttpClientConnect$HttpIOHandlerObserver.onStateChange(HttpClientConnect.java:430)
        at reactor.netty.ReactorNetty$CompositeConnectionObserver.onStateChange(ReactorNetty.java:503)
        at reactor.netty.resources.PooledConnectionProvider$DisposableAcquire.run(PooledConnectionProvider.java:571)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: java.net.URISyntaxException: Illegal character in path at index 68: /certificates/fc8686f2-0e9c-4ceb-b00c-6bac422a37bd-testCertificate2/{certificate-version}?api-version=7.0
        at java.base/java.net.URI$Parser.fail(URI.java:2936)
        at java.base/java.net.URI$Parser.checkChars(URI.java:3107)
        at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3189)
        at java.base/java.net.URI$Parser.parse(URI.java:3148)
        at java.base/java.net.URI.<init>(URI.java:623)
        at java.base/java.net.URI.create(URI.java:904)
        ... 14 more
[main] INFO com.azure.core.test.InterceptorManag

**Comment by alzimmermsft** [comment]
@g2vinay is this an issue that should be investigated, I see it closed without a reason.
