### ISSUE TITLE
Not getting Application gateway's backend pools and frontend ip configurations in genericResources().getById(id)

### ISSUE THREAD

**Issue by galitharun** [Azure/azure-sdk-for-java#8958]
We are not able to get data for application gateway's inner resources through azure generic resources **get by id** API using azure java sdk 1.31.0: 

BackendPool :  
/subscriptions/{subscription_id}/resourceGroups/{resource_group}/providers/Microsoft.Network/applicationGateways/{application_gateway}/backendAddressPools/{backend_address_pool}

FrontEndIpConfiguration : 
/subscriptions/{subscription_id}/resourceGroups/{resource_group}/providers/Microsoft.Network/applicationGateways/{application_gateway}/frontendIPConfigurations/{frontend_ip_config}

are these resources not supported by the API?if not will they be supported in the future?

**Comment by joshfree** [comment]
Thanks for posting this inquiry @galitharun.  @yaohaizh can you please help follow up?

**Comment by yaohaizh** [comment]
@xccc-msft  could you help follow up wit the generic resource issue? //cc: @yungezz

**Comment by xccc-msft** [comment]
@galitharun Can you clarify what's the expected data for application gateway's inner resources? I just want to make sure if you get resource as NULL or only the properties missing.

**Comment by galitharun** [comment]
@xccc-msft  i am getting the resource as null, even though the resource is existing, am getting the following stack trace : 
`Exception in thread "main" java.lang.NullPointerException
	at com.microsoft.azure.management.resources.implementation.GenericResourcesImpl.getById(GenericResourcesImpl.java:93)
	at com.microsoft.azure.management.resources.implementation.GenericResourcesImpl.getById(GenericResourcesImpl.java:29)`

this stack trace is for application gateway's backend pool.

**Comment by xccc-msft** [comment]
@galitharun According to the REST APIs of [ApplicationGateways](https://docs.microsoft.com/en-us/rest/api/application-gateway/applicationgateways), no GET services available for its backend pools and frontend ip configurations even if they have their own ids. Once we request such resources, the server will return code 404. In SDK, we will return as NULL. Hence, you are facing same issue as #8935.
I'm not sure what's the detailed requirement in your project. But you can try either way below to get backend pools and front ip configurations from application gateways.
- Try with Azure client or network manager
```java
ApplicationGateway appGateway = azure.applicationGateways().getById(id);
//ApplicationGateway appGateway = networkManager.applicationGateways().getById(id);
ApplicationGatewayBackend backend = appGateway.backends().get(backendName);
ApplicationGatewayFrontend frontend = appGateway.frontends().get(frontendName);
```
- Try with getById by genericResources and find in properties
```java
GenericResource genericResource = resourceManager.genericResources().getById(id);
Object properties = genericResource.properties();
```

**Comment by galitharun** [comment]
@xccc-msft thank you for the information, will there be support for the above mentioned GET services in the future?

**Comment by xccc-msft** [comment]
@galitharun I just add label so the service team will share whether they would consider to support this. Thanks.
