### ISSUE TITLE
I tried the 1.1.0-beta.2. I consistently get that the process doesn't exit.

### ISSUE THREAD

**Issue by jongio** [Azure/azure-sdk-for-java#9058]
I tried the 1.1.0-beta.2. I consistently get that the process doesn't exit.

```
Caused by: java.lang.RuntimeException: Tried EnvironmentCredential, ManagedIdentityCredential, SharedTokenCacheCredential, AzureCliCredential but failed to acquire a token for any of them. Please verify the environment for either of them and see more details in the causes below.
        at com.azure.identity.ChainedTokenCredential.lambda$getToken$3(ChainedTokenCredential.java:51)
        at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44)
        ... 65 more
Caused by: java.lang.IllegalThreadStateException: process hasn't exited
        at java.base/java.lang.ProcessImpl.exitValue(ProcessImpl.java:522)
        at com.azure.identity.implementation.IdentityClient.authenticateWithAzureCli(IdentityClient.java:209)
        at com.azure.identity.AzureCliCredential.getToken(AzureCliCredential.java:35)
        at com.azure.identity.ChainedTokenCredential.lambda$getToken$1(ChainedTokenCredential.java:40)
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:378)
        at reactor.core.publisher.FluxIterable$IterableSubscription.slowPath(FluxIterable.java:243)
        ... 57 more
```

This on OSX 10.15 19A583 and openjdk 11.0.5.

_Originally posted by @sitase in https://github.com/Azure/azure-sdk-for-java/issues/8269#issuecomment-598704197_

**Comment by jongio** [comment]
@g2vinay

**Comment by g2vinay** [comment]
Thanks @jongio  for posting the issue.

Thanks @sitase  for trying out the DefaultAzureCredential in Identity 1.1.0-beta.2
It would be helpful if you could execute the following commands and share the output of the 2nd command:

1. az login
2. az account get-access-token --output json --resource https://vault.azure.net

Do REDACT the token/tenant/subscription value in the output before sharing.

**Comment by joshfree** [comment]
@g2vinay PTAL 
/cc @JimSuplizio as FYI

**Comment by g2vinay** [comment]
Thanks @sitase for posting the issue and trying out the DefaultAzureCredential.

It would be helpful if you could execute the following commands and share the output of the 2nd command:
1. az login
2. az account get-access-token --output json --resource https://vault.azure.net

Do REDACT the token/tenant/subscription value in the output before sharing.

**Comment by sitase** [comment]
```
{
  "accessToken": "eyJ0eXAiOXXXXXd35zwrdnPQPVpg",
  "expiresOn": "2020-03-16 13:42:13.761055",
  "subscription": "52bXXXXX2a",
  "tenant": "3b68cXXXa80b9529",
  "tokenType": "Bearer"
}
```

**Comment by sitase** [comment]
Ok. It seems to depend on your JDK. I was using:

```
$ sdk c java

Using java version 11.0.5-amzn
```

Switching to:

```
$ sdk u java  8.0.242-zulu 
```

made all the difference in the world.

Would of course appreciate if I could use a more recent Java than 8.

**Comment by g2vinay** [comment]
@sitase ,
Thank you for the update.
I am able to repro this issue on JDK 11 on mac.
Will be making a PR to fix this in our repo master and the fix will be available in our next release
