### ISSUE TITLE
[BUG] buffer reallocate exception 

### ISSUE THREAD

**Issue by VIJAY-SUBRAMANIAM** [Azure/azure-sdk-for-java#9080]
BufferOverflowException has thrown when netty trying to reallocate buffer.   The issue with azure v12.5.0 and netty 4.1.44.Final

It seems issue related to https://github.com/netty/netty/issues/9911
 
2020-03-13 20:37:55,967 [a8c597cc8a78] [reactor-http-epoll-21] WARN  reactor.netty.http.client.HttpClientConnect - [id: 0x09bbb32b, L:/172.17.0.5:52526 - R:lntsonymusicdsrv.blob.core.windows.net/52.239.220.100:443] The connection observed an error
java.nio.BufferOverflowException: null
	at java.nio.DirectByteBuffer.put(DirectByteBuffer.java:373) ~[?:?]
	at io.netty.buffer.PoolArena$DirectArena.memoryCopy(PoolArena.java:795) ~[netty-buffer-4.1.44.Final.jar:?]
	at io.netty.buffer.PoolArena$DirectArena.memoryCopy(PoolArena.java:704) ~[netty-buffer-4.1.44.Final.jar:?]
	at io.netty.buffer.PoolArena.reallocate(PoolArena.java:405) ~[netty-buffer-4.1.44.Final.jar:?]
	at io.netty.buffer.PooledByteBuf.capacity(PooledByteBuf.java:118) ~[netty-buffer-4.1.44.Final.jar:?]
	at io.netty.buffer.AbstractByteBuf.ensureWritable(AbstractByteBuf.java:334) ~[netty-buffer-4.1.44.Final.jar:?]
	at io.netty.handler.ssl.SslHandler.attemptCopyToCumulation(SslHandler.java:2210) ~[netty-handler-4.1.44.Final.jar:?]
	at io.netty.handler.ssl.SslHandler.access$2800(SslHandler.java:166) ~[netty-handler-4.1.44.Final.jar:?]
	at io.netty.handler.ssl.SslHandler$SslHandlerCoalescingBufferQueue.compose(SslHandler.java:2171) ~[netty-handler-4.1.44.Final.jar:?]
	at io.netty.channel.AbstractCoalescingBufferQueue.remove(AbstractCoalescingBufferQueue.java:175) [netty-transport-4.1.44.Final.jar:?]
	at io.netty.handler.ssl.SslHandler.wrap(SslHandler.java:814) [netty-handler-4.1.44.Final.jar:?]
	at io.netty.handler.ssl.SslHandler.wrapAndFlush(SslHandler.java:792) [netty-handler-4.1.44.Final.jar:?]
	at io.netty.handler.ssl.SslHandler.flush(SslHandler.java:773) [netty-handler-4.1.44.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:748) [netty-transport-4.1.44.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:740) [netty-transport-4.1.44.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:726) [netty-transport-4.1.44.Final.jar:?]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.flush(CombinedChannelDuplexHandler.java:531) [netty-transport-4.1.44.Final.jar:?]
	at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:125) [netty-transport-4.1.44.Final.jar:?]
	at io.netty.channel.CombinedChannelDuplexHandler.flush(CombinedChannelDuplexHandler.java:356) [netty-transport-4.1.44.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:748) [netty-transport-4.1.44.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:740) [netty-transport-4.1.44.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:726) [netty-transport-4.1.44.Final.jar:?]
	at reactor.netty.channel.MonoSendMany$SendManyInner.run(MonoSendMany.java:296) [reactor-netty-0.9.4.RELEASE.jar:?]
	at reactor.netty.channel.MonoSendMany$SendManyInner.trySchedule(MonoSendMany.java:383) [reactor-netty-0.9.4.RELEASE.jar:?]
	at reactor.netty.channel.MonoSendMany$SendManyInner.onNext(MonoSendMany.java:195) [reactor-netty-0.9.4.RELEASE.jar:?]
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114) [reactor-core-3.3.2.RELEASE.jar:?]
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114) [reactor-core-3.3.2.RELEASE.jar:?]
	at reactor.core.publisher.FluxDoOnEach$DoOnEachSubscriber.onNext(FluxDoOnEach.java:159) [reactor-core-3.3.2.RELEASE.jar:?]
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:203) [reactor-core-3.3.2.RELEASE.jar:?]
	at reactor.core.publisher.FluxIterable$IterableSubscription.slowPath(FluxIterable.java:243) [reactor-core-3.3.2.RELEASE.jar:?]
	at reactor.core.publisher.FluxIterable$IterableSubscription.request(FluxIterable.java:201) [reactor-core-3.3.2.RELEASE.jar:?]
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.request(FluxPeekFuseable.java:137) [reactor-core-3.3.2.RELEASE.jar:?]
	at reactor.core.publisher.FluxDoOnEach$DoOnEachSubscriber.request(FluxDoOnEach.java:97) [reactor-core-3.3.2.RELEASE.jar:?]
	at reactor.core.publisher.FluxMap$MapSubscriber.request(FluxMap.java:155) [reactor-core-3.3.2.RELEASE.jar:?]
	at reactor.core.publisher.FluxMap$MapSubscriber.request(FluxMap.java:155) [reactor-core-3.3.2.RELEASE.jar:?]
	at reactor.netty.channel.MonoSendMany$SendManyInner.onSubscribe(MonoSendMany.java:226) [reactor-netty-0.9.4.RELEASE.jar:?]
	at reactor.core.publisher.FluxMap$MapSubscriber.onSubscribe(FluxMap.java:86) [reactor-core-3.3.2.RELEASE.jar:?]
	at reactor.core.publisher.FluxMap$MapSubscriber.onSubscribe(FluxMap.java:86) [reactor-core-3.3.2.RELEASE.jar:?]
	at reactor.core.publisher.FluxDoOnEach$DoOnEachSubscriber.onSubscribe(FluxDoOnEach.java:110) [reactor-core-3.3.2.RELEASE.jar:?]
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onSubscribe(FluxPeekFuseable.java:171) [reactor-core-3.3.2.RELEASE.jar:?]
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:139) [reactor-core-3.3.2.RELEASE.jar:?]
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:63) [reactor-core-3.3.2.RELEASE.jar:?]
	at reactor.core.publisher.Flux.subscribe(Flux.java:8174) [reactor-core-3.3.2.RELEASE.jar:?]
	at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:199) [reactor-core-3.3.2.RELEASE.jar:?]
	at reactor.core.publisher.MonoFlatMapMany.subscribeOrReturn(MonoFlatMapMany.java:49) [reactor-core-3.3.2.RELEASE.jar:?]
	at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:46) [reactor-core-3.3.2.RELEASE.jar:?]
	at reactor.core.publisher.FluxDefer.subscribe(FluxDefer.java:54) [reactor-core-3.3.2.RELEASE.jar:?]
	at reactor.core.publisher.Flux.subscribe(Flux.java:8174) [reactor-core-3.3.2.RELEASE.jar:?]
	at reactor.netty.channel.MonoSendMany.subscribe(MonoSendMany.java:82) [reactor-netty-0.9.4.RELEASE.jar:?]
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.drain(MonoIgnoreThen.java:153) [reactor-core-3.3.2.RELEASE.jar:?]
	at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:56) [reactor-core-3.3.2.RELEASE.jar:?]
	at reactor.core.publisher.Mono.subscribe(Mono.java:4105) [reactor-core-3.3.2.RELEASE.jar:?]
	at reactor.netty.NettyOutbound.subscribe(NettyOutbound.java:329) [reactor-netty-0.9.4.RELEASE.jar:?]
	at reactor.core.publisher.MonoSource.subscribe(MonoSource.java:58) [reactor-core-3.3.2.RELEASE.jar:?]
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) [reactor-core-3.3.2.RELEASE.jar:?]
	at reactor.netty.http.client.HttpClientConnect$HttpIOHandlerObserver.onStateChange(HttpClientConnect.java:430) [reactor-netty-0.9.4.RELEASE.jar:?]
	at reactor.netty.ReactorNetty$CompositeConnectionObserver.onStateChange(ReactorNetty.java:503) [reactor-netty-0.9.4.RELEASE.jar:?]
	at reactor.netty.resources.PooledConnectionProvider$DisposableAcquire.run(PooledConnectionProvider.java:571) [reactor-netty-0.9.4.RELEASE.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [netty-common-4.1.44.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) [netty-common-4.1.44.Final.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384) [netty-transport-native-epoll-4.1.44.Final-linux-x86_64.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.44.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.44.Final.jar:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.44.Final.jar:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by joshfree** [comment]
Thanks for reporting this @VIJAY-SUBRAMANIAM.  It looks like this is fixed in 4.1.45.Final of netty.  @alzimmermsft can you please take a look?

**Comment by alzimmermsft** [comment]
This should be resolved by #9081

**Comment by VIJAY-SUBRAMANIAM** [comment]
When the new version will be available? 

https://mvnrepository.com/artifact/com.azure/azure-storage-blob/12.5.0

**Comment by alzimmermsft** [comment]
@VIJAY-SUBRAMANIAM the latest version of `azure-storage-blob` (12.6.0) should use Netty 4.1.45.Final.

**Comment by VIJAY-SUBRAMANIAM** [comment]
Thanks @alzimmermsft.  switched to a new version. so far everything fine with a new version.
