### ISSUE TITLE
Error while packaging [cspack.exe: Error   : Stream was too long.]

### ISSUE THREAD

**Issue by bhaskar-fealti** [Azure/azure-sdk-for-java#929]
I am building a SpringBoot application that also includes Activiti & Quartz libraries. The size of the final JAR is over 2.5GB.

I have created an Azure deployment project in Eclipse with a WorkerRole to deploy this application as Azure Cloud Service. I am able to run it fine under local Azure Emulator. But I get the following exception when I run package.xml with Ant for creating deployment package. 

```
[windowsazurepackage] cspack.exe: Error   : Stream was too long.
[windowsazurepackage] Waiting for process to exit...
[windowsazurepackage] Process exited with non-zero code
[windowsazurepackage] 	at com.microsoftopentechnologies.windowsazure.tools.build.WindowsAzurePackage.runCommandLine(WindowsAzurePackage.java:1045)
[windowsazurepackage] 	at com.microsoftopentechnologies.windowsazure.tools.build.WindowsAzurePackage.execute(WindowsAzurePackage.java:692)
[windowsazurepackage] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
[windowsazurepackage] 	at sun.reflect.GeneratedMethodAccessor51.invoke(Unknown Source)
[windowsazurepackage] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[windowsazurepackage] 	at java.lang.reflect.Method.invoke(Unknown Source)
[windowsazurepackage] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[windowsazurepackage] 	at org.apache.tools.ant.Task.perform(Task.java:348)
[windowsazurepackage] 	at org.apache.tools.ant.taskdefs.Parallel$TaskRunnable.run(Parallel.java:454)
[windowsazurepackage] 	at java.lang.Thread.run(Unknown Source)
[windowsazurepackage] Process exited with non-zero code
[windowsazurepackage] 	at com.microsoftopentechnologies.windowsazure.tools.build.WindowsAzurePackage.reportBuildError(WindowsAzurePackage.java:809)
[windowsazurepackage] 	at com.microsoftopentechnologies.windowsazure.tools.build.WindowsAzurePackage.execute(WindowsAzurePackage.java:699)
[windowsazurepackage] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
[windowsazurepackage] 	at sun.reflect.GeneratedMethodAccessor51.invoke(Unknown Source)
[windowsazurepackage] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[windowsazurepackage] 	at java.lang.reflect.Method.invoke(Unknown Source)
[windowsazurepackage] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[windowsazurepackage] 	at org.apache.tools.ant.Task.perform(Task.java:348)
[windowsazurepackage] 	at org.apache.tools.ant.taskdefs.Parallel$TaskRunnable.run(Parallel.java:454)
[windowsazurepackage] 	at java.lang.Thread.run(Unknown Source)
[windowsazurepackage] Caused by: Process exited with non-zero code
[windowsazurepackage] 	at com.microsoftopentechnologies.windowsazure.tools.build.WindowsAzurePackage.runCommandLine(WindowsAzurePackage.java:1045)
[windowsazurepackage] 	at com.microsoftopentechnologies.windowsazure.tools.build.WindowsAzurePackage.execute(WindowsAzurePackage.java:692)
[windowsazurepackage] 	... 8 more
```

**Comment by jianghaolu** [comment]
@martinsawicki @selvasingh Do you know who owns `com.microsoftopentechnologies.windowsazure.tools.build.WindowsAzurePackage` package?

**Comment by martinsawicki** [comment]
that's just ours, this should have been logged in the azure-tools-for-java repo, then Prajakta can take a look. (but I think it may just be too massive of a package)

**Comment by jianghaolu** [comment]
@pednekarprajakta

**Comment by bhaskar-fealti** [comment]
We managed to bring the jar down to manageable size and it is working fine now. It would still help to know what is the maximum size of the files the SDK can handle.
