### ISSUE TITLE
On  a machine where there is no internet access and azure calls are happening using proxy server azure "getlocations" call fails  unknown host exception

### ISSUE THREAD

**Issue by nihalnaik25** [Azure/azure-sdk-for-java#942]
On  a machine where there is no internet access and azure calls are happening using proxy server
azure "getlocations" call fails  due to below exception

API call : ServiceResponse<List<Provider>> result = armClient.getProvidersOperations().list(null)

Workaround : update the ip address for login.windows.net in hosts file. host should be resolvable to a IP address. It is ok even if ping request timed out

Caused by: java.io.IOException: java.net.UnknownHostException: login.windows.net
                at com.microsoft.azure.credentials.ApplicationTokenCredentials.acquireAccessToken(ApplicationTokenCredentials.java:113)
                at com.microsoft.azure.credentials.ApplicationTokenCredentials.getToken(ApplicationTokenCredentials.java:94)
                at com.microsoft.rest.credentials.TokenCredentialsInterceptor.sendRequestWithAuthorization(TokenCredentialsInterceptor.java:46)
                at com.microsoft.rest.credentials.TokenCredentialsInterceptor.intercept(TokenCredentialsInterceptor.java:37)
                at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:187)
                at com.microsoft.azure.CustomHeaderInterceptor.intercept(CustomHeaderInterceptor.java:133)
                at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:187)
                at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:160)
                at okhttp3.RealCall.execute(RealCall.java:57)
                at retrofit2.OkHttpCall.execute(OkHttpCall.java:177)
                at com.microsoft.azure.management.resources.ProvidersOperationsImpl.list(ProvidersOperationsImpl.java:240)
                ... 21 more
Caused by: java.util.concurrent.ExecutionException: java.net.UnknownHostException: login.windows.net
                at java.util.concurrent.FutureTask.report(FutureTask.java:122)
                at java.util.concurrent.FutureTask.get(FutureTask.java:192)
                at com.microsoft.azure.credentials.ApplicationTokenCredentials.acquireAccessToken(ApplicationTokenCredentials.java:108)
                ... 32 more
Caused by: java.net.UnknownHostException: login.windows.net
                at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
                at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
                at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
                at java.net.Socket.connect(Socket.java:589)
                at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
                at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
                at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
                at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
                at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
                at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:275)
                at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:371)
                at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
                at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1104)
                at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:998)
                at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
                at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1282)
                at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1257)
                at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:250)
                at com.microsoft.aad.adal4j.AdalOAuthRequest.configureHeaderAndExecuteOAuthCall(AdalOAuthRequest.java:140)
                at com.microsoft.aad.adal4j.AdalOAuthRequest.send(AdalOAuthRequest.java:83)
                at com.microsoft.aad.adal4j.AdalTokenRequest.executeOAuthRequestAndProcessResponse(AdalTokenRequest.java:80)
                at com.microsoft.aad.adal4j.AuthenticationContext.acquireTokenCommon(AuthenticationContext.java:818)
                at com.microsoft.aad.adal4j.AuthenticationContext.access$100(AuthenticationContext.java:66)
                at com.microsoft.aad.adal4j.AuthenticationContext$1.call(AuthenticationContext.java:174)
                at com.microsoft.aad.adal4j.AuthenticationContext$1.call(AuthenticationContext.java:163)

**Comment by jianghaolu** [comment]
Authentication through a proxy is currently not supported. You can work around by getting an access token on your own and use `TokenCredentials` instead. 
This feature will be added in the upcoming beta release.

**Comment by martinsawicki** [comment]
supported in the current SDK releases (automatic)

**Comment by gizdev** [comment]
This thread is a bit old, however I was just starting using the KeyVault SDK and encountered the same problem. I cloned the repo located [here](https://github.com/Azure-Samples/key-vault-java-authentication) and ran into the same problem, also using a proxy to connect to the internet. 

I solved this by changing the `getAuthenticatedClient` method as followings, assuming the proxy is running on _localhost_ on port _3128_: 

```
final String clientId = "YOUR-CLIENT-ID";
final KeyCert certificateKey = readPem(path, pemPassword);
final PrivateKey privateKey = certificateKey.getKey();

final Proxy proxy = new Proxy(Proxy.Type.HTTP, new InetSocketAddress("localhost", 3128));

KeyVaultClient keyVaultClient = new KeyVaultClient(new RestClient.Builder(new OkHttpClient.Builder(), new Retrofit.Builder())
	.withBaseUrl("YOUR-BASE-URL")
	.withCredentials(new KeyVaultCredentials() {

	@Override
	public String doAuthenticate(String authorization, String resource, String scope) {

		AuthenticationContext context;
		try {
			context = new AuthenticationContext(authorization, false, Executors.newFixedThreadPool(1));
			AsymmetricKeyCredential asymmetricKeyCredential = AsymmetricKeyCredential.create(clientId,
				privateKey, certificateKey.getCertificate());
			// pass null value for optional callback function and acquire access token
			context.setProxy(proxy);
			AuthenticationResult result = context.acquireToken(resource, asymmetricKeyCredential, null).get();

			return result.getAccessToken();
		} catch (Exception e) {
			e.printStackTrace();
		}
		return "";
		}
	})
	.withSerializerAdapter(new AzureJacksonAdapter())
	.withResponseBuilderFactory(new AzureResponseBuilder.Factory())
	.withProxy(proxy)
	.build());
return keyVaultClient;
```

For both, the `AuthenticationContext` (for communicating with Azure-AD) as well as the `RestClient` (for communicating with the service, i.e. Azure-KeyVault), the proxy must be set. Once set everything runs smooth. 

Hope this helps. 

Cheerzzz.
