### ISSUE TITLE
[BUG] Azure java client - Null pointer while update public ip address with leaf dns when not existing

### ISSUE THREAD

**Issue by fyrnaga** [Azure/azure-sdk-for-java#9852]
**Describe the bug**
In the Java client API, i get a public ip address without dns information. When I try to add the information, it results in a nullpointer exception. I have the version 1.32.1 of the client API.

***Exception or Stack Trace***
```
2020-04-03 14:43:36,797 [http-nio-8080-exec-1] ERROR c.c.m.r.m.UnexpectedExceptionMapper - Unmapped exception: java.lang.NullPointerException
java.lang.NullPointerException: null
	at com.microsoft.azure.management.network.implementation.PublicIPAddressImpl.withLeafDomainLabel(PublicIPAddressImpl.java:87) ~[azure-mgmt-network-1.32.1.jar:1.32.1]
	at com.microsoft.azure.management.network.implementation.PublicIPAddressImpl.withLeafDomainLabel(PublicIPAddressImpl.java:39) ~[azure-mgmt-network-1.32.1.jar:1.32.1]
	at com.cloudops.mc.plugin.azure.publicip.operations.UpdatePublicIPAddress.execute(UpdatePublicIPAddress.java:161) ~[classes/:na]

```

**To Reproduce**
Create a public ip address without DNS information
Get the public IP address from the azure client
update the dns leaf

***Code Snippet***
```
 PublicIPAddress azurePublicIpAdddress= az.publicIPAddresses().getById(fetchedEntity.getId());

      PublicIPAddress.Update update =  azurePublicIpAdddress.update();
      if (publicIpAddress.getAllocationMethod() != null){
         if (publicIpAddress.getAllocationMethod().equals(PublicIpAddress.AllocationMethod.DYNAMIC)){
            update = update.withDynamicIP();
         } else {
            update = update.withStaticIP();
         }
      }

      if (publicIpAddress.getIdleTimeout() != null){
         update = update.withIdleTimeoutInMinutes(publicIpAddress.getIdleTimeout());
      }

      // Bug causes null pointer in auzre api
      if (StringUtils.isEmpty(publicIpAddress.getDomainName())) {
         update.withoutLeafDomainLabel();
      } else {
         update.withLeafDomainLabel(publicIpAddress.getDomainName());
      }
```

**Expected behavior**
The api should detect that there is no dnsSettings and create a new one to post it.

**Screenshots**
N/A

**Setup (please complete the following information):**
 - OS: iOS
 - IDE : IntelliJ
 - Version 1.32.1 
    <dependency>
      <groupId>com.microsoft.azure</groupId>
      <artifactId>azure</artifactId>
      <version>1.32.1</version>
    </dependency>

**Additional context**
Nothing more to add

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by joshfree** [comment]
Thanks for reporting this issue with the management plane sdk @fyrnaga.  @yungezz could you please assist?

**Comment by xccc-msft** [comment]
@fyrnaga Thanks for reporting this. I just created PR to fix this.

**Comment by fyrnaga** [comment]
I found a way to bypass it, but found another issue down the line. If the IP has a domain leaf and I set withoutDomainLeaf, it causes an error while submitting it. 
In both case, my work around was to set the dnsProfile to new before doing the update method.

**Comment by xccc-msft** [comment]
@fyrnaga What's the error when you set `withoutLeafDomainLabel`?

**Comment by fyrnaga** [comment]
@xccc-msft 
When we call the withoutLeafDomainLabel on a publicIPAddress width a fqdn, it generates a 400 error. It clears the domainLabel but no the fqdn. Here is the log trace of it.
```

2020-04-07 15:27:37,936 [RxIoScheduler-2] INFO  c.m.a.m.n.PublicIPAddresses createOrUpdate - --> PUT https://management.azure.com/subscriptions/subscriptionId/resourceGroups/alavoie-azure3-system-alavoie-local-brh7q/providers/Microsoft.Network/publicIPAddresses/ip_root_yow?api-version=2019-11-01
2020-04-07 15:27:37,936 [RxIoScheduler-2] INFO  c.m.a.m.n.PublicIPAddresses createOrUpdate - Accept-Encoding: gzip
2020-04-07 15:27:37,936 [RxIoScheduler-2] INFO  c.m.a.m.n.PublicIPAddresses createOrUpdate - accept-language: en-US
2020-04-07 15:27:37,936 [RxIoScheduler-2] INFO  c.m.a.m.n.PublicIPAddresses createOrUpdate - Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IllNRUxIVDBndmIwbXhvU0RvWWZvbWpxZmpZVSIsImtpZCI6IllNRUxIVDBndmIwbXhvU0RvWWZvbWpxZmpZVSJ9.eyJhdWQiOiJodHRwczovL21hbmFnZW1lbnQuY29yZS53aW5kb3dzLm5ldC8iLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC8yOGRmNzQ3NS1kMGI3LTRkYzgtOTEwZC1hYzVhN2RmN2FmZDkvIiwiaWF0IjoxNTg2Mjg3MzU3LCJuYmYiOjE1ODYyODczNTcsImV4cCI6MTU4NjI5MTI1NywiYWlvIjoiNDJkZ1lQaXpQTzdoWTZtWDE1NjdTUzQ0OU9UMEFRQT0iLCJhcHBpZCI6Ijg2OWQ2ZWNkLWI4NTktNDVkYy05ZTQ1LWFlOTU2N2VlYmNmOCIsImFwcGlkYWNyIjoiMSIsImlkcCI6Imh0dHBzOi8vc3RzLndpbmRvd3MubmV0LzI4ZGY3NDc1LWQwYjctNGRjOC05MTBkLWFjNWE3ZGY3YWZkOS8iLCJvaWQiOiJjMzRiZThmNi03MzU5LTQxMTAtYmEyYS01YTg1YTQ2N2E2MjQiLCJzdWIiOiJjMzRiZThmNi03MzU5LTQxMTAtYmEyYS01YTg1YTQ2N2E2MjQiLCJ0aWQiOiIyOGRmNzQ3NS1kMGI3LTRkYzgtOTEwZC1hYzVhN2RmN2FmZDkiLCJ1dGkiOiI0UWVRSy10ZkUwMmdqeUZxTnJFa0FBIiwidmVyIjoiMS4wIn0.K6tbI3V9_bIhtJ5rc-AITRLm3a1I6UxV7msTC-Rjl-wsUGSDCXq_KXBhEv6kcTxUSmhEtAslXZv2xxsWCSaKI8YapAUU_ZiiOdPDaFTbv_dhJz8cCwzHcSPbJ8qpQCb3ymH1afgUzUykwp8IzbM0nV-PB0A81_9XszKXu99U_xUzqiArVR3N9h7fENqPUniExL04uxMAhyQCUmEaKpxtB2wpp8K0Sh8I-6DjsbvqC1i1B7PP32RDV-S0vn8luwDJTN_33107QZIhkZm9m9E8k7rOk7rcvoatfJhISMlBghNfPtUj2Azkr1ZEs-op7lD_KBLa0EcxuEwrM1QTxyLsQQ
2020-04-07 15:27:37,936 [RxIoScheduler-2] INFO  c.m.a.m.n.PublicIPAddresses createOrUpdate - Connection: Keep-Alive
2020-04-07 15:27:37,936 [RxIoScheduler-2] INFO  c.m.a.m.n.PublicIPAddresses createOrUpdate - Content-Length: 533
2020-04-07 15:27:37,937 [RxIoScheduler-2] INFO  c.m.a.m.n.PublicIPAddresses createOrUpdate - Content-Type: application/json; charset=utf-8
2020-04-07 15:27:37,937 [RxIoScheduler-2] INFO  c.m.a.m.n.PublicIPAddresses createOrUpdate - Host: management.azure.com
2020-04-07 15:27:37,937 [RxIoScheduler-2] INFO  c.m.a.m.n.PublicIPAddresses createOrUpdate - User-Agent: Azure-SDK-For-Java/1.32.1 OS:Mac OS X/10.15.4 MacAddressHash:7ad0633a9f7e5ac12ac2c42b7530f24616c0c0a63574ebef69f9ebe1b3a9e0a4 Java:11.0.6 (NetworkManagementClient)
2020-04-07 15:27:37,937 [RxIoScheduler-2] INFO  c.m.a.m.n.PublicIPAddresses createOrUpdate - x-ms-client-request-id: f890bf50-c262-4c1e-b32a-503c244ef25f
2020-04-07 15:27:37,937 [RxIoScheduler-2] INFO  c.m.a.m.n.PublicIPAddresses createOrUpdate - 533-byte body:
{"location":"canadacentral","tags":{"createdBy":"cloudmc","envid":"cdb2a8bb-99fc-4777-846b-809a09f7b69b","orgid":"409c1162-a930-4207-bdf9-710580c3542b"},"id":"/subscriptions/subscriptionId/resourceGroups/alavoie-azure3-system-alavoie-local-brh7q/providers/Microsoft.Network/publicIPAddresses/ip_root_yow","sku":{"name":"Basic"},"properties":{"publicIPAllocationMethod":"Dynamic","publicIPAddressVersion":"IPv4","dnsSettings":{"fqdn":"bob.canadacentral.cloudapp.azure.com"},"ipTags":[],"idleTimeoutInMinutes":4}}
2020-04-07 15:27:37,937 [RxIoScheduler-2] INFO  c.m.a.m.n.PublicIPAddresses createOrUpdate - --> END PUT
2020-04-07 15:27:38,169 [RxIoScheduler-2] INFO  c.m.a.m.n.PublicIPAddresses createOrUpdate - <-- 400  https://management.azure.com/subscriptions/subscriptionId/resourceGroups/alavoie-azure3-system-alavoie-local-brh7q/providers/Microsoft.Network/publicIPAddresses/ip_root_yow?api-version=2019-11-01 (231 ms, 286-byte body)
2020-04-07 15:27:38,169 [RxIoScheduler-2] INFO  c.m.a.m.n.PublicIPAddresses createOrUpdate - cache-control: no-cache
2020-04-07 15:27:38,169 [RxIoScheduler-2] INFO  c.m.a.m.n.PublicIPAddresses createOrUpdate - content-length: 286
2020-04-07 15:27:38,169 [RxIoScheduler-2] INFO  c.m.a.m.n.PublicIPAddresses createOrUpdate - content-type: application/json; charset=utf-8
2020-04-07 15:27:38,169 [RxIoScheduler-2] INFO  c.m.a.m.n.PublicIPAddresses createOrUpdate - date: Tue, 07 Apr 2020 19:27:37 GMT
2020-04-07 15:27:38,169 [RxIoScheduler-2] INFO  c.m.a.m.n.PublicIPAddresses createOrUpdate - expires: -1
2020-04-07 15:27:38,169 [RxIoScheduler-2] INFO  c.m.a.m.n.PublicIPAddresses createOrUpdate - pragma: no-cache
2020-04-07 15:27:38,169 [RxIoScheduler-2] INFO  c.m.a.m.n.PublicIPAddresses createOrUpdate - server: Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0
2020-04-07 15:27:38,169 [RxIoScheduler-2] INFO  c.m.a.m.n.PublicIPAddresses createOrUpdate - strict-transport-security: max-age=31536000; includeSubDomains
2020-04-07 15:27:38,169 [RxIoScheduler-2] INFO  c.m.a.m.n.PublicIPAddresses createOrUpdate - x-content-type-options: nosniff
2020-04-07 15:27:38,169 [RxIoScheduler-2] INFO  c.m.a.m.n.PublicIPAddresses createOrUpdate - x-ms-arm-service-request-id: 4d7d1854-062a-4e67-b94b-77c39ba4e682
2020-04-07 15:27:38,169 [RxIoScheduler-2] INFO  c.m.a.m.n.PublicIPAddresses createOrUpdate - x-ms-correlation-request-id: cdfeafb3-a455-4c1c-933e-47c6360c4661
2020-04-07 15:27:38,169 [RxIoScheduler-2] INFO  c.m.a.m.n.PublicIPAddresses createOrUpdate - x-ms-ratelimit-remaining-subscription-writes: 1199
2020-04-07 15:27:38,169 [RxIoScheduler-2] INFO  c.m.a.m.n.PublicIPAddresses createOrUpdate - x-ms-request-id: c7e37418-2c9e-451d-b39e-91e6103bbfab
2020-04-07 15:27:38,169 [RxIoScheduler-2] INFO  c.m.a.m.n.PublicIPAddresses createOrUpdate - x-ms-routing-request-id: CANADACENTRAL:20200407T192738Z:cdfeafb3-a455-4c1c-933e-47c6360c4661
2020-04-07 15:27:38,170 [RxIoScheduler-2] INFO  c.m.a.m.n.PublicIPAddresses createOrUpdate - 286-byte body:
{
  "error": {
    "code": "DomainNameLabelMissing",
    "message": "The domain name label in the dnsSettings section of the public IP address ip_root_yow is null or empty. If a dnsSettings section exists, its domain name label must not be null or empty.",
    "details": []
  }
}
```

**Comment by xccc-msft** [comment]
@fyrnaga Thanks for sharing the info. According the error message, I just added new fix commit to clear the dns settings when calling `withoutLeafDomainLabel()`.
