### ISSUE TITLE
[Auth] The access setup is frustrating

### ISSUE THREAD

**Issue by fabiofumarola** [Azure/azure-sdk-for-java#996]
[Auth](https://github.com/Azure/azure-sdk-for-java/blob/master/AUTH.md) document is not updated and after I spent 2 hours I cannot be able to make a simple example to list all the available images.

**Comment by martinsawicki** [comment]
which version of the API are you using?  The auth.md applies to v1.0-beta1 and later, not before.

**Comment by dadoonet** [comment]
I might have a similar issue so adding to this issue my comment instead of opening another one.

I'm following the guide available at https://github.com/Azure/azure-sdk-for-java/blob/master/AUTH.md but it appears that:

* some windows changed in the meantime, for example 

> `24.` Click Subscriptions and select the subscription in the list that you want to enable your application to access. 
> `25.` Click Users, Add 

You actually need to click on `All settings` after step 24.

But this is not my problem here. I'm blocked at the very last stage. 

> `27.` Click Add Users, then find and select your application using the name you provided earlier, and click the Select button near the bottom of the page.

But when I try to add my application as an user, Azure does not find my application.
Message is "There is no user in Default Directory with the full name matching 'MyApplicationNameHere'.".

So when I run the following code:

```java
ApplicationTokenCredentials credentials =
    new ApplicationTokenCredentials(CLIENT_ID, TENANT, SECRET, AzureEnvironment.AZURE);
Azure azure = Azure.authenticate(credentials).withSubscription(SUBSCRIPTION_ID);
PagedList<Deployment> list = azure.deployments().list();
```

I'm getting:

```
[2016-09-14T13:22:15,002][INFO ][com.microsoft.aad.adal4j.AuthenticationAuthority] [Correlation ID: XXX Instance discovery was successful
[2016-09-14T13:22:16,024][INFO ][com.microsoft.aad.adal4j.AuthenticationAuthority] [Correlation ID: YYY] Instance discovery was successful
com.microsoft.azure.CloudException: Invalid status code 401: The access token is from the wrong issuer 'https://sts.windows.net/MY-TENANT-ID-HERE/'. It must match the tenant 'https://sts.windows.net/ANOTHER-ID/' associated with this subscription. Please use the authority (URL) 'https://login.windows.net/ANOTHER-ID' to get the token. Note, if the subscription is transferred to another tenant there is no impact to the services, but information about new tenant could take time to propagate (up to an hour). If you just transferred your subscription and see this error message, please try back later.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at com.microsoft.rest.ServiceResponseBuilder.build(ServiceResponseBuilder.java:147)
	at com.microsoft.azure.management.resources.implementation.ResourceGroupsInner.listDelegate(ResourceGroupsInner.java:937)
	at com.microsoft.azure.management.resources.implementation.ResourceGroupsInner.list(ResourceGroupsInner.java:809)
	at com.microsoft.azure.management.resources.implementation.ResourceGroupsImpl.list(ResourceGroupsImpl.java:38)
	at com.microsoft.azure.management.resources.implementation.DeploymentsImpl.list(DeploymentsImpl.java:49)
	at org.elasticsearch.cloud.azure.arm.AzureARMClientTests.lambda$testConnectWithKeySecret$0(AzureARMClientTests.java:56)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.elasticsearch.cloud.azure.arm.AzureARMClientTests.testConnectWithKeySecret(AzureARMClientTests.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
```

Not sure it's related though. Whatever, can you tell me how I can do the last step of the guide?

**Comment by jianghaolu** [comment]
Hi @dadoonet 
With the new Azure Python CLI, creating a service principal has become much easier. Please refer to the updated doc: https://github.com/Azure/azure-sdk-for-java/blob/master/AUTH.md#creating-a-service-principal-in-azure to create an auth file with Azure CLI in just a few commands.

**Comment by jianghaolu** [comment]
Closing as the experience has been improved. Please reopen if you need further assistance.

Thanks!

**Comment by Madan165** [comment]
Hi @jianghaolu 
I do also have same issue while login in using java code, the link you provided on 28 Sep doesn't work.
can you please provide with any solution?
